### ISSUE TITLE
NotifPanel shouldn't be persisted in the RightPanel stack for a room.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23216] opened 2022-09-06 09:25 UTC
### Steps to reproduce

1. Go to a room
2. View NotifPanel (which is **not** a per-room view)
3. Switch room; observe the rightpanel switches for that room
4. Switch back; observe that we now have notifpanel back again, which is undesirable, given it has nothing to do with that room.

#### What did you expect?

Element shouldn't persist that the notifpanel is open for a given room.

#### What happened instead?

It does.

### Operating system

macOS

### Browser information

nightly

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-09-06 11:38
Duplicate of https://github.com/vector-im/element-web/issues/21529

**Closed by t3chguy** 2022-09-06 11:38 UTC
Labels: T-Defect
