### ISSUE TITLE
Disappearing Messages similar to the Signal messaging app.

### ISSUE THREAD

**Issue by gitr0n1n** [vector-im/element-web#16187] opened 2021-01-17 22:04 UTC
**Is your feature request related to a problem? Please describe.**
Disappearing Messages similar to the Signal messaging app. It is a pain to manually delete messages. An auto purge method after x days/weeks would be great for server resources and privacy.

**Describe the solution you'd like**
Implement Disappearing Messages similar to the Signal messaging app.

**Describe alternatives you've considered**
None, this is straight forward and should be a default feature.

**Additional context**
review a great implementation of this feature in this app: https://www.signal.org/

Related Issues:
https://github.com/matrix-org/synapse/issues/6287
https://github.com/vector-im/element-web/issues/16187
https://github.com/vector-im/element-ios/issues/3948
https://github.com/vector-im/element-android/issues/2691

Dated Issue:
https://github.com/vector-im/element-web/issues/2497

**Comment by t3chguy** [comment] 2021-01-17 22:09
Duplicate of #2497

**Comment by t3chguy** [comment] 2021-01-17 22:09
We don't create duplicate issues just because one is older and has a lot more feedback.

**Closed** 2021-01-17 22:09 UTC
Labels: suggestion
