### ISSUE TITLE
voice calls sometimes not working

### ISSUE THREAD

**Issue by AlBundy33** [vector-im/element-web#21720] opened 2022-04-08 11:16 UTC
### Steps to reproduce

the problem is a little bit strange.
We are useing different clients: element desktop app on windows, linux and macos and also the webclient.

Writing messages is working as expected.

But sometimes we have the problem that we don't hear each other if we start a voice call.
Sometimes it helps to restart the call.
Sometimes we have to restart the call multiple times and sometimes it doesn't work at all.
But this doesn't seem to be a problem of the participiants because event if it still works "now" it maybe works later as expected.

The only thing we "see" is, that we are in the call but we both hear nothing.

Do have others this problem too and is there maybe a workaround?

I know that the description is not that helpful but I have no idea how to describe it better. :-)
If you need more informations I'll try to add them.

### Operating system

windows, macos, ubuntu

### Will you send logs?

No

**Comment by dbkr** [comment] 2022-04-08 17:45
Filling in the rest of the template would really help here, specifically at least the homeserver field: if it's not matrix.org then the HS may be having turn setup issues. The other thing that would help is logs from both sides after a failed call. Without any of these, this probably isn't actionable.

**Comment by AlBundy33** [comment] 2022-04-08 21:50
server is histed in our compamy but I don't know what implementation is used.
-> I'll ask our admins

where can I find the client-logs for the windows and macos desktop apps?

**Comment by AlBundy33** [comment] 2022-04-12 07:00
We are using Synapse 1.55.0

Is there a way to have a look at the client-logs before uploading them?

**Comment by robintown** [comment] 2022-04-12 12:08
Yes, you can open the browser console to view the logs locally

**Comment by AlBundy33** [comment] 2022-04-14 13:12
ok - sounds easy.
I'll try this, next time the issue occurs

**Comment by Serenacula** [comment] 2022-05-19 08:34
I also pretty consistently have this issue. It may be related to communicating across servers, as it seems to work when we both are on matrix.org, but not when we have different home servers.

Video and audio calls fail maybe 80-90% of the time, more recently it has seemed to be 100% of the time. Calls seem to work when using two accounts on the same server.

These are the logs I see.

`b2cc6b39 - type: host, address: 192.168.1.119, port: 59254, protocol: udp, relay protocol: undefined, network type: undefined [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
230ca24b - type: srflx, address: 31.185.50.186, port: 59254, protocol: udp, relay protocol: undefined, network type: undefined [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
b53ee719 - type: relay, address: 94.237.57.30, port: 64812, protocol: udp, relay protocol: udp, network type: undefined [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
91081f92 - type: host, address: fd00::1:87:f7d2:55d0:a3c4, port: 49650, protocol: udp, relay protocol: undefined, network type: undefined [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
5b4eaf63 - type: host, address: 192.168.1.119, port: 64541, protocol: tcp, relay protocol: undefined, network type: undefined [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
271e1026 - type: relay, address: 94.237.57.30, port: 65488, protocol: udp, relay protocol: tcp, network type: undefined [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
7b6ebab6 - type: relay, address: 94.237.57.30, port: 57002, protocol: udp, relay protocol: tls, network type: undefined [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
ba9e4e2e - type: host, address: fd00::1:87:f7d2:55d0:a3c4, port: 57061, protocol: tcp, relay protocol: undefined, network type: undefined [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
Remote candidates: [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
3f1b2ddf - type: host, address: fd30:d3d:28b1:0:cdb:c7de:4bb2:b08e, port: 51395, protocol: udp [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
6be267c - type: host, address: 192.168.1.207, port: 64054, protocol: udp [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
83ead9b - type: host, address: fd30:d3d:28b1:0:cdb:c7de:4bb2:b08e, port: 9, protocol: tcp [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
6ab74dc7 - type: host, address: 192.168.1.207, port: 9, protocol: tcp [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
Candidate pairs: [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
91081f92 / 3f1b2ddf - state: failed, nominated: false, requests sent undefined, requests received  undefined,  responses received: undefined, responses sent: undefined, bytes received: 0, bytes sent: 0, [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
b2cc6b39 / 6be267c - state: failed, nominated: false, requests sent undefined, requests received  undefined,  responses received: undefined, responses sent: undefined, bytes received: 0, bytes sent: 0, [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
b53ee719 / 6be267c - state: failed, nominated: false, requests sent undefined, requests received  undefined,  responses received: undefined, responses sent: undefined, bytes received: 0, bytes sent: 0, [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
271e1026 / 6be267c - state: failed, nominated: false, requests sent undefined, requests received  undefined,  responses received: undefined, responses sent: undefined, bytes received: 0, bytes sent: 0, [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
7b6ebab6 / 6be267c - state: failed, nominated: false, requests sent undefined, requests received  undefined,  responses received: undefined, responses sent: undefined, bytes received: 0, bytes sent: 0, [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
Outbound RTP: [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
Inbound RTP: [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
Event sent to !rGujLUDagKKIsMMaDI:matrix.org with event id $vLmHxDsP55tYpXt9lCuz31tct376m5Uvxt8262ho9SQ [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
setting pendingEvent status to sent in !rGujLUDagKKIsMMaDI:matrix.org event ID ~!rGujLUDagKKIsMMaDI:matrix.org:m1652948955152.7 -> $vLmHxDsP55tYpXt9lCuz31tct376m5Uvxt8262ho9SQ [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
Got remote echo for event $vLmHxDsP55tYpXt9lCuz31tct376m5Uvxt8262ho9SQ -> $vLmHxDsP55tYpXt9lCuz31tct376m5Uvxt8262ho9SQ old status sent [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
EventTimelineSet.addLiveEvent: ignoring duplicate event $vLmHxDsP55tYpXt9lCuz31tct376m5Uvxt8262ho9SQ [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
Error: Promised response from onMessage listener went out of scope 9 [background.js:8:59730](moz-extension://abddedaf-cb26-4d82-b185-55b6f163ca9e/background/background.js)
Discarding an event, we don't have a call/peerConn m.room.encrypted [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)`

**Comment by EarthlingDavey** [comment] 2022-05-20 09:09
> I also pretty consistently have this issue. It may be related to communicating across servers, as it seems to work when we both are on matrix.org, but not when we have different home servers.

Serencaula and I were havig this issue. It turns out I was on a homeserver running synapse v1.49.2. Since moving to a homeserver running 1.59.1 the issue is fixed for us.

**Comment by turt2live** [comment] 2022-06-14 05:47
Considering fixed due to recent comment. If this is not the case, please open a new issue with new information.

**Closed by turt2live** 2022-06-14 05:47 UTC
Labels: T-Defect, X-Needs-Info, A-VoIP

**Comment by rekhabanga99** [comment] 2024-09-18 11:45
I am facing
CallEventHandler handleCallEvent() discarding possible call event as we don't have a call (type=m.call.select_answer)
