### ISSUE TITLE
Huge number of room key request cancellations

### ISSUE THREAD

**Issue by foldleft** [vector-im/element-web#13207] opened 2020-04-16 13:36 UTC
See https://github.com/matrix-org/riot-web-rageshakes/issues/2602

Lots of requests being sent out and cancelled again.   Might they be for the same session / why?

**Comment by bwindels** [comment] 2020-04-17 08:08
I'm seeing these at login, before you complete security. Currently at 250 and still sending for an account with not too many e2ee rooms. Was that the case for you as well?

**Comment by turt2live** [comment] 2022-06-14 05:08
Closing due to lack of information (and impractical debugging for 2 years ago). Presuming duplicate of https://github.com/vector-im/element-web/issues/3754

**Closed by turt2live** 2022-06-14 05:08 UTC
Labels: T-Defect
