### ISSUE TITLE
reactions on Desktop

### ISSUE THREAD

**Issue by joerglohrer** [vector-im/element-web#26174] opened 2023-09-15 10:06 UTC
#### What would you like to do?
I'd like see the Names of ALL people reacting in the desktop and browser versions of element. 

#### Why would you like to do it?
Because on mobile Apps you can open the reactions and names of ALL people reacting by holding a reaction button. On all Desktop Apps and in Browser you can online see the first 6 Names and than "x others".
Another reason why i would like to see all reactions is because we use this for voting and want to see the people besides the results.

#### How would you like to achieve it?
I myself can't do it. But the developers could make it available perhaps via a simple right-click of the mouse button or with hover function.

### Have you considered any alternatives?

Yes i log in with multiple mobile devices to see the all the Names of people reacting. 

### Additional context

Please ask back or tell me if this improvement is rather considered as a bug, you are already working on

**Comment by t3chguy** [comment] 2023-09-15 10:07
Duplicate of https://github.com/vector-im/element-web/issues/9723

**Closed by t3chguy** 2023-09-15 10:07 UTC
Labels: T-Enhancement
