### ISSUE TITLE
Something went wrong! Error: "End-to-end encryption disabled"

### ISSUE THREAD

**Issue by jomat** [vector-im/element-web#12060] opened 2020-01-26 12:25 UTC
### Description

This is not a duplicate of #11138 as I don't have low bandwith mode enabled.
Selecting a room/direct chat with encryption enabled or enabling encryption in a room crashes riot-web.
There are errors in the console:
Enabling encryption:
```
XHROPTIONShttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25474090_142780609_2988_6309155_964686_1634_212262_698111_177
[HTTP/1.1 200 OK 37ms]

XHRGEThttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25474090_142780609_2988_6309155_964686_1634_212262_698111_177
[HTTP/1.1 200 OK 6071ms]

Starting load of AsyncWrapper for modal bundle.js:2:560702
XHROPTIONShttps://asra.gr/_matrix/client/r0/rooms/!OEqptbLnGaQiufZAwr%3Aasra.gr/state/m.room.encryption
[HTTP/1.1 200 OK 48ms]

XHRPUThttps://asra.gr/_matrix/client/r0/rooms/!OEqptbLnGaQiufZAwr%3Aasra.gr/state/m.room.encryption
[HTTP/1.1 200 OK 116ms]

XHROPTIONShttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25474090_142780612_2988_6309155_964686_1634_212262_698111_177
[HTTP/1.1 200 OK 37ms]

XHRGEThttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25474090_142780612_2988_6309155_964686_1634_212262_698111_177
[HTTP/1.1 200 OK 94ms]

Error: "End-to-end encryption disabled"
    getKeyBackupEnabled https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    render https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    $a https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Ya https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    xs https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    gc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    hc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ic https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    unstable_runWithPriority https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    zo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    $o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Yo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ec https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    enqueueSetState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    setState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    e https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    c https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _invoke https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    t https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    s https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    exports https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    exports https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _updateE2EStatus https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    onRoomTimeline https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    emit https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    value https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    emit https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    value https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    emit https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    addEventToTimeline https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    addLiveEvent https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _addLiveEvent https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    addLiveEvents https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _processRoomEvents https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    e https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    c https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _invoke https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    t https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    s https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    exports https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    exports https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    e https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    e https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    c https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _invoke https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    t https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    s https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
bundle.js:2:560702
Error: "End-to-end encryption disabled"
    getKeyBackupEnabled https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    render https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    $a https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Ya https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    xs https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    gc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    hc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ic https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    unstable_runWithPriority https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    zo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    $o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Yo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ec https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    enqueueSetState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    setState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    e https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    c https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _invoke https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    t https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    s https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    exports https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    exports https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _updateE2EStatus https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    onRoomTimeline https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    emit https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    value https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    emit https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    value https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    emit https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    addEventToTimeline https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    addLiveEvent https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _addLiveEvent https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    addLiveEvents https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _processRoomEvents https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    e https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    c https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _invoke https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    t https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    s https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    exports https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    exports https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    e https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    e https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    c https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _invoke https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    t https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    s https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
bundle.js:2:560702
The above error occured while React was rendering the following components: 
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in t
    in MatrixChat bundle.js:2:560702
XHROPTIONShttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25474091_142780614_2988_6309155_964686_1634_212262_698111_177
[HTTP/1.1 200 OK 38ms]

XHRGEThttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25474091_142780614_2988_6309155_964686_1634_212262_698111_177
[HTTP/1.1 200 OK 300ms]

XHROPTIONShttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25474092_142780615_2988_6309155_964686_1634_212262_698111_177
[HTTP/1.1 200 OK 35ms]
```

Selecting encrypted room:
```
XHROPTIONShttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25474352_142781833_3063_6309293_964690_1634_212262_698125_177
[HTTP/1.1 200 OK 36ms]

Switching to room id !OEqptbLnGaQiufZAwr:asra.gr at event undefined bundle.js:2:560702
Looking at $uv8ABUZz2N2PhOGA9OMhPmCP3UawCjM7uwB4hmIgvLg bundle.js:2:879710
XHRGEThttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25474352_142781833_3063_6309293_964690_1634_212262_698125_177
[HTTP/1.1 200 OK 561ms]

RVS update: !OEqptbLnGaQiufZAwr:asra.gr undefined loading? false joining? false initial? true shouldPeek? true bundle.js:2:560702
Returning cached capabilities bundle.js:2:855284
Error: "End-to-end encryption disabled"
    getKeyBackupEnabled https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    render https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    $a https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Ya https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    xs https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    gc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    hc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ic https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    unstable_runWithPriority https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    zo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    $o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Yo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ec https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    enqueueSetState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    setState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _viewRoom https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
bundle.js:2:560702
Error: "End-to-end encryption disabled"
    getKeyBackupEnabled https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    render https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    $a https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Ya https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    xs https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    gc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    hc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ic https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    unstable_runWithPriority https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    zo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    $o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Yo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ec https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    enqueueSetState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    setState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _viewRoom https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
bundle.js:2:560702
The above error occured while React was rendering the following components: 
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in t
    in MatrixChat bundle.js:2:560702
newscreen room/!OEqptbLnGaQiufZAwr:asra.gr bundle.js:2:560702
[!OEqptbLnGaQiufZAwr:asra.gr] Current version: 5 bundle.js:2:905110
[!OEqptbLnGaQiufZAwr:asra.gr] Version capability:  
Object { default: "5", available: {…} }
bundle.js:2:905175
XHROPTIONShttps://asra.gr/_matrix/client/r0/user/%40jomat%3Aasra.gr/account_data/im.vector.setting.breadcrumbs
[HTTP/1.1 200 OK 294ms]

XHROPTIONShttps://asra.gr/_matrix/client/r0/rooms/!OEqptbLnGaQiufZAwr%3Aasra.gr/members?not_membership=leave&at=s25474352_142781833_3063_6309293_964690_1634_212262_698125_177
[HTTP/1.1 200 OK 302ms]

XHRPUThttps://asra.gr/_matrix/client/r0/user/%40jomat%3Aasra.gr/account_data/im.vector.setting.breadcrumbs
[HTTP/1.1 200 OK 63ms]

XHRGEThttps://asra.gr/_matrix/client/r0/rooms/!OEqptbLnGaQiufZAwr%3Aasra.gr/members?not_membership=leave&at=s25474352_142781833_3063_6309293_964690_1634_212262_698125_177
[HTTP/1.1 200 OK 87ms]

LL: got 1 members from server for room !OEqptbLnGaQiufZAwr:asra.gr bundle.js:2:908673
LL: RoomState about to set 1 OOB members ... bundle.js:2:735466
LL: RoomState put in OOB_STATUS_FINISHED state ... bundle.js:2:735575
LL: telling store to write 0 members for room !OEqptbLnGaQiufZAwr:asra.gr bundle.js:2:909567
XHROPTIONShttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25474352_142781833_3063_6309293_964691_1634_212262_698125_177
[HTTP/1.1 200 OK 40ms]

XHRGEThttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25474352_142781833_3063_6309293_964691_1634_212262_698125_177
[HTTP/1.1 200 OK 929ms]
```
### Steps to reproduce

- enable encryption in a room or select a room with encryption enabled
The whole riot-web becomes unusable with the "Something went wrong!" error.
Clear cache and reload doesn't help and instantly brings back the full screen error.

Log: not sent

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 70.0.1
- **OS**: Linux
- **URL**: riot.asra.gr v1.5.8-rc.2

**Comment by turt2live** [comment] 2020-01-26 12:37
is your disk full or nearly full?

**Comment by jomat** [comment] 2020-01-26 12:47
No:
/dev/dm-1       227G  187G   31G  86% /

Neither on the server:
/dev/vda2       408G  221G  171G  57% /

**Comment by jomat** [comment] 2020-01-26 20:31
Might be related to this:
![Screenshot_2020-01-26 asra gr #dendrite-dev matrix org](https://user-images.githubusercontent.com/381286/73141300-86cd2300-407a-11ea-989a-0771d694bd06.png)
Opening settings → Security & Privacy gives this error, and deleting the backup with riot-android didn't change anything here in riot-web.
```
XHRGEThttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25489371_142870292_13152_6322041_965473_1636_212435_698819_177
[HTTP/1.1 200 OK 107ms]

Unable to fetch check backup status TypeError: "this._crypto is null"
    checkKeyBackup https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    e https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    c https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _invoke https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    t https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    s https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    exports https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    exports https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    value https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    value https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Ri https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Ya https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    xs https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    gc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    hc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ic https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    unstable_runWithPriority https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    zo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    $o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Yo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    se https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Tn https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
bundle.js:2:560702
XHROPTIONShttps://asra.gr/_matrix/client/r0/devices
[HTTP/1.1 200 OK 76ms]

XHRGEThttps://asra.gr/_matrix/client/r0/devices
[HTTP/1.1 200 OK 92ms]

XHROPTIONShttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25489371_142870294_13152_6322041_965473_1636_212435_698819_177
[HTTP/1.1 200 OK 105ms]
```

**Comment by t3chguy** [comment] 2020-01-26 20:43
did you build the build for `riot.asra.gr` yourself? It seems that it was built without `olm` installed in the environment hence without e2ee support.

`_crypto` is only null if olm wasn't enabled or e2ee wasn't initialized (which riot only does if olm is available)

**Comment by jomat** [comment] 2020-01-26 21:10
No, I download the release from github: https://github.com/vector-im/riot-web/releases/download/${VERSION_GH}/riot-${VERSION_GH}.tar.gz, extract it and copy config.json, home.html and welcome.html from the old directory.
Looking at the timestamp (in UTC), I updated it on thursday:
```
lrwxrwxrwx   1 root     root       17 Jan 23 13:51  riot -> riot-v1.5.8-rc.2/
```
I'm able to decrypt messages in riot.asra.gr in another browser that were sent from riot-android (from the same account), so olm should be there, shouldn't it? I'll verify it with another account, too.
I'll try to figure out when I sent the last encrypted message with the broken device and keep you updated.

I just noticed that the device key is gone, too:
![image](https://user-images.githubusercontent.com/381286/73141557-4de27d80-407d-11ea-8abf-33faa6d888a7.png)

**Comment by jomat** [comment] 2020-01-26 21:16
Also other people are able to decrypt messages sent from riot.asra.gr opened in antoher browser and I can read their answers.

**Comment by jomat** [comment] 2020-01-26 21:26
I don't know if it was the last encrypted message sent with the broken device MAEHOJVIGQ, but this one was after the update, @1579816502656, which is Thu Jan 23 21:55:02 UTC 2020
![image](https://user-images.githubusercontent.com/381286/73142058-5be6cd00-4082-11ea-8c31-dff14d154a5c.png)

**Comment by jomat** [comment] 2020-01-26 21:53
Also other users on riot.asra.gr are able to use encryption, so most likely olm is there.

But following the hint that e2ee isn't initialized, i noticed this error upon refreshing:
```
IndexedDB worker is ready bundle.js:2:1868014
LocalIndexedDBStoreBackend.connect: connecting... indexeddb-worker.js:1:16906
LocalIndexedDBStoreBackend.connect: awaiting connection... indexeddb-worker.js:1:17672
LocalIndexedDBStoreBackend.connect: connected indexeddb-worker.js:1:17772
LocalIndexedDBStoreBackend: loading account data... indexeddb-worker.js:1:22462
LocalIndexedDBStoreBackend: loading sync data... indexeddb-worker.js:1:22796
Error running command: connect indexeddb-worker.js:1:87177
    value https://riot.asra.gr/bundles/987fb3d9511291da64bf/indexeddb-worker.js:1
Error: Query failed: undefined indexeddb-worker.js:1:87224
    value https://riot.asra.gr/bundles/987fb3d9511291da64bf/indexeddb-worker.js:1
Error starting matrixclient store - falling back to memory store Error: "Query failed: undefined"
    _onWorkerMessage https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
bundle.js:2:560702
    r https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    t https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    c https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    _invoke https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    t https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    n https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    c https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
MatrixClientPeg: waiting for MatrixClient store to initialise bundle.js:2:560702
Crypto: initialising roomlist... bundle.js:2:856342
connecting to indexeddb matrix-js-sdk:crypto bundle.js:2:123826
LocalIndexedDBStoreBackend: loaded account data indexeddb-worker.js:1:22685
connected to indexeddb matrix-js-sdk:crypto bundle.js:2:124226
Crypto: initialising crypto object... bundle.js:2:857180
Crypto: initialising Olm... bundle.js:2:245082
Crypto: initialising Olm device... bundle.js:2:245157
Crypto: loading device list... bundle.js:2:245249
Error performing indexeddb txn 
error { target: IDBRequest, isTrusted: true, srcElement: IDBRequest, currentTarget: IDBTransaction, eventPhase: 3, bubbles: true, cancelable: true, returnValue: true, defaultPrevented: false, composed: false, … }
bundle.js:2:1449863
Unable to initialise e2e DOMException: "The operation failed for reasons unrelated to the database itself and not covered by any other error code." bundle.js:2:560702
MatrixClientPeg: really starting MatrixClient bundle.js:2:560702
```

**Comment by jomat** [comment] 2020-01-27 00:11
Tried to sign out, but nothing happens but those errors:
```
XHRGEThttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25494769_142905745_17614_6327242_965657_1636_216084_699138_177
[HTTP/1.1 200 OK 3098ms]

Starting load of AsyncWrapper for modal bundle.js:2:560702
Error: "End-to-end encryption disabled"
    getKeyBackupEnabled https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    t https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Ci https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Ya https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    xs https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    gc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    hc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ic https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    unstable_runWithPriority https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    zo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    $o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Yo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ec https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    enqueueSetState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    setState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    componentWillMount https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
bundle.js:2:560702
AsyncWrapper promise failed Error: "End-to-end encryption disabled"
    getKeyBackupEnabled https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    t https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Ci https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Ya https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    xs https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    gc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    hc https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ic https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    unstable_runWithPriority https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    zo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    $o https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    Yo https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    ec https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    enqueueSetState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    setState https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
    componentWillMount https://riot.asra.gr/bundles/987fb3d9511291da64bf/bundle.js:2
bundle.js:2:560702
XHROPTIONShttps://asra.gr/_matrix/client/r0/sync?filter=47&timeout=30000&since=s25494769_142905746_17614_6327244_965657_1636_216084_699138_177
[HTTP/1.1 200 OK 35ms]
```

**Comment by turt2live** [comment] 2020-01-27 09:40
I have a feeling your browser is interfereing here. Are you using private mode or some similar sort of extension?

**Comment by jomat** [comment] 2020-01-27 11:53
The browser has two extensions active, uBlock Origin (last updated 2018) and Steam Database (last updated 2019), and some disabled ones like Ghostery and Privacy Badger - they haven't been enabled this year yet. I don't use private mode or changed any other browser settings this year.
The last system upgrade happened in December. Nothing I know of changed in the time period in question.
What I did on Jan 23 was compiling a linux kernel, which is quite CPU heavy, started at 14:48:11 UTC, finished at 17:23:58, but as a different user and I'm still running the old kernel 5.4.0. I don't know if I restarted the browser after that but before the last known encrypted message at 21:55.

**Comment by jomat** [comment] 2020-01-27 22:51
Updated to v1.5.8 and it still happens.

**Comment by turt2live** [comment] 2020-01-27 22:57
Can you go to Settings -> Help -> Submit debug logs please?

**Comment by jomat** [comment] 2020-01-27 23:20
Done. It would be nice to see what is sent in the debug log btw…

**Comment by turt2live** [comment] 2020-01-27 23:26
It's the same stuff that's visible in the JS console, just packaged up for us to more easily see if. You could run your own rageshake server or pull the contents from the indexeddb if you wanted.

**Comment by turt2live** [comment] 2020-01-27 23:27
anyways, this was the bit I was looking for:
```
2020-01-27T23:15:31.552Z E Error starting matrixclient store - falling back to memory store Query failed: undefined
_onWorkerMessage@https://riot.asra.gr/bundles/d441f426d823eb4f5dc4/bundle.js:2:1874573

2020-01-27T23:15:31.552Z I MatrixClientPeg: waiting for MatrixClient store to initialise
2020-01-27T23:15:31.675Z W Unable to initialise e2e The operation failed for reasons unrelated to the database itself and not covered by any other error code.
```

This sounds like a similar error to what we've seen with some people in the office.

**Comment by jomat** [comment] 2020-01-28 11:58
Ah yes, the one I posted two days ago in https://github.com/vector-im/riot-web/issues/12060#issuecomment-578547254
If I clear Site Data for riot, I should be able to use it again?

**Comment by turt2live** [comment] 2020-01-28 12:50
possibly, though it sounds like your browser has some weird problems going on

**Comment by martindale** [comment] 2020-02-15 06:30
I'm getting the same thing on build on MacOS:

```
Error: End-to-end encryption disabled
```

**Comment by turt2live** [comment] 2020-02-15 21:10
@martindale the actual error is going to be much higher up in the logs. Please submit debug logs from settings -> Help

**Comment by martindale** [comment] 2020-02-15 21:18
```
Unable to initialise e2e TypeError: Cannot read property 'NAME' of undefined
    at new Crypto (webpack-internal:///85:143)
    at MatrixClient.initCrypto (webpack-internal:///39:680)
    at async _MatrixClientPeg.assign (webpack-internal:///26:167)
    at async _MatrixClientPeg.start (webpack-internal:///26:195)
    at async startMatrixClient (webpack-internal:///1226:636)
    at async _doSetLoggedIn (webpack-internal:///1226:499)
    at async _restoreFromLocalStorage (webpack-internal:///1226:346)
    at async Module.loadSession (webpack-internal:///1226:140)
```

**Comment by turt2live** [comment] 2020-02-15 21:23
I can't reproduce this error, but it sounds like you're getting a different error from the OP here. I suspect it's down to how you're building the app: visit #riot-dev:matrix.org please

**Comment by ZerataX** [comment] 2020-05-06 21:46
![grafik](https://user-images.githubusercontent.com/5024958/81231378-5be85880-8ff3-11ea-92d9-84fe85b18c15.png)
left is chromium where olm is apparently enabled and firefox (all extensions disabled) on version 75.0 same account same riot instance but olm disabled.

riot-web version: 1.6.0-148-gcfd84688
olm version: 3.1.3

**Comment by SuperSandro2000** [comment] 2022-05-31 11:46
Do you have low bandwidth mode enabled under settings? This killed OLM support for me in firefox.

**Comment by richvdh** [comment] 2023-11-08 11:52
Likely the error was specific to the OP. Given that was nearly 4 years ago, time to close this

**Closed by richvdh** 2023-11-08 11:52 UTC
Labels: S-Critical, A-E2EE, X-Needs-Investigation, O-Uncommon
