### ISSUE TITLE
Recepient seeing "Unable to decrypt" message instead of actual message.

### ISSUE THREAD

**Issue by bsldld** [vector-im/element-web#14921] opened 2020-08-10 13:12 UTC
### Description

Recepient seeing "Unable to decrypt" message instead of actual message.

### Steps to reproduce

- Create a new room
- Add a user to the room
- Send message to the room or directly to the user.
- The user sees the message "Unable to decrypt"

My friend recently joined matrix network. He is using element.io app. So I created a new room and added my friend to that room. When I send a direct message to him or via the room, he sees a message "Unable to decrypt". Why could that be? I am also not able to verify him as he sees the same error message. I am using Riot Desktop app on Linux.

Log: sent/not sent?    Yes.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**:  Ubuntu 18.04.4
- **Version**: riot-web version: 1.6.0  - olm version: 3.1.3

**Comment by t3chguy** [comment] 2020-08-12 10:06
What is the full `Unable to decrypt` you are seeing?
Should say like `Unable to decrypt: User has not sent us the keys` or whatever

**Comment by bsldld** [comment] 2020-08-12 11:14
It was unable to decrypt messages sent to the other party. The other party that I was trying to persuade to use Element/Riot is now refusing to use the app. We have since moved to other platform for our chat communication. BTW, this has not happened the first time. Every time I try to get someone to use Riot/Element, the first hurdle they face is related to encryption/decryption. Users are not able to see messages because of some issue or the other.

**Comment by jryans** [comment] 2020-08-12 13:56
Unfortunately, it's quite hard to act on these reports without knowing what both sides are seeing, so it may be hard to take action here.

**Comment by TR-SLimey** [comment] 2020-08-17 21:16
Are they verified by you? If not, perhaps you have "never send encrypted messages to unverified sessions" enabled in settings? If that's the case, your device will deliberately not send them the keys because they are not verified. Also, if you have the option to, try upgrading to the latest (Element 1.7.4 as of today) version since a lot of bugs have been ironed out along the way.

**Comment by bsldld** [comment] 2020-08-18 03:18
> Are they verified by you?

The error was displayed from the start, from the verification stage to the message sending stages. A more user friendly option would be to let users know what the reason could be for this types of errors rather than giving a generic error message related to decryption. Lot of non-technical users don't understand these types of messages and have little patience to investigate the cause of it. They just move on to another platform. I have had hard time getting lot of my friends and family members to use riot/element for these reasons. It never works out of the box.

**Comment by turt2live** [comment] 2022-06-14 05:27
Duplicate of https://github.com/vector-im/element-web/issues/2996

**Closed by turt2live** 2022-06-14 05:27 UTC
Labels: T-Defect, X-Needs-Info, A-E2EE, Z-UISI
