### ISSUE TITLE
Space Member list keeps open while/after joining another space

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#19297] opened 2021-10-05 17:36 UTC
### Steps to reproduce

1. Create any space
2. Open the memberslist from the space home
3. Go to the home tab
4. Join a space via the room list
5. switch between (root?) spaces

#### What did you expect?

The memberslist should either disappear or change

#### What happened instead?

It keeps open with the initial Space.

### Operating system

Windows 11

### Browser information

Firefox 92.0.1 (64-bit) (Private window)

### URL for webapp

staging.element.io/#/

### Homeserver

matrix.org

### Will you send logs?

No

#### Additional Info

It happens to me but while the community testing it didnt happen to @kittykat

**Comment by MTRNord** [comment] 2021-10-05 17:42
Video of it:
https://user-images.githubusercontent.com/1374914/136075158-f5b7d714-ec96-4a0c-82fb-b8172b7e2534.mp4

**Comment by t3chguy** [comment] 2021-10-06 08:32
Duplicate of https://github.com/vector-im/element-web/issues/17376

**Closed by t3chguy** 2021-10-06 08:32 UTC
Labels: T-Defect
