### ISSUE TITLE
Ability to screenshare with audio on windows or linux

### ISSUE THREAD

**Issue by Dev-RS** [vector-im/element-web#22979] opened 2022-08-03 00:39 UTC
#### What would you like to do?
share audio of the window or screen that was chosen for screensharing.
#### Why would you like to do it?
It would help bring more users to element, and jitsi itself has quality issues from my personal experience. The screensharing feature in element video calls works better, would just like audio as well.
#### How would you like to achieve it?
hopefully using desktopCapturer in electron? 

### Have you considered any alternatives?

yes, I have tried using jitsi and I have tried using screensharing with OBS virtual cam, but the video quality is not great on either. Also, if I try to capture the audio using  OBS virtual cam and the VB audio virtual cable trick the audio does not pick up from the desktop so having the option in the app to capture audio would be great.

### Additional context

Thank you to the element team for all the work you continue to put in project!

**Comment by SimonBrandner** [comment] 2022-08-03 05:59
Duplicate of https://github.com/vector-im/element-web/issues/16657

**Closed by SimonBrandner** 2022-08-03 05:59 UTC
Labels: T-Enhancement
