### ISSUE TITLE
Ignore single '+' and '-' symbols from convertion to markdown list

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#13411] opened 2020-04-28 04:32 UTC
Very often users reply to questions via simple `+` symbol as "yes", or `-` as "no", but Riot converts both text to `◦` symbol as markdown list item with empty text, and users don't understand what happening!

> Boss: Who want beer?
> Alice: ◦
> Bob: ◦
> Eve: ◦ 

So, how much the beer?

Please make ignore rule for not convert those symbols to markdown lists, if list contain only one item!

**Comment by MurzNN** [comment] 2020-04-28 04:35
Same problem is with sentences, starting with `-` symbol, oftenly after quoting text, here is example of typed text:
```
> I think that the earth is flat!

- are you sure?
```
And here is result in Riot:
![image](https://user-images.githubusercontent.com/336662/80447688-d2fe5c80-8922-11ea-8890-726dbeaa505b.png)

**Comment by MurzNN** [comment] 2020-04-28 04:49
Related issues: https://github.com/vector-im/riot-web/issues/11230 https://github.com/vector-im/riot-web/issues/483

**Comment by t3chguy** [comment] 2020-04-28 09:16
Riot has previouisly expressed that it doesn't want to run and maintain its own flavour of Markdown, this would constitute that.

**Comment by robintown** [comment] 2021-09-17 20:02
Duplicate of https://github.com/vector-im/element-web/issues/7631

**Closed by robintown** 2021-09-17 20:02 UTC
Labels: T-Defect
