### ISSUE TITLE
Rendering in the thread panel is missing some replies

### ISSUE THREAD

**Issue by davidegirardi** [vector-im/element-web#25854] opened 2023-07-27 06:12 UTC
### Steps to reproduce

This happens from time to time and refreshing usually fixes the issue. It didn't in this case.

1. See a thread in the timeline
2. Notice the number of replies
3. Look at the same thread in the side bar, the number of replies does not match

I _suspect_ this happens more often if you have the thread panel already open when you switch to the room containing the thread after starting the application.

#### What did you expect?
To see all the messages in the thread.

#### What happened instead?
Some messages are missing. I suspect #24636 is a symptom of this.

### Operating system

Arch Linux

### Application version

Element version: 1.11.36 Olm version: 3.2.14

### How did you install the app?

pacman

### Will you send logs?

Yes

**Comment by davidegirardi** [comment] 2023-07-27 06:16
Screenshots are available in the rageshakes.

**Comment by weeman1337** [comment] 2023-07-27 06:39
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-07-27 06:39
Duplicate of https://github.com/vector-im/element-web/issues/24636

**Comment by davidegirardi** [comment] 2023-07-27 06:50
I also mentioned that #24636 could be a symptom of this but I _know_ there are n > m replies in a thread but Element is only rendering m replied in the thread panel. Other sessions are correctly rendering n replies in the thread panel.

The other issue mentions that the reply count is higher than what it should be.

**Comment by t3chguy** [comment] 2023-07-27 06:53
This is fixed on develop.

**Closed by t3chguy** 2023-07-27 06:54 UTC
Labels: T-Defect, A-Threads
