### ISSUE TITLE
Unable to Decrypt some New Messages

### ISSUE THREAD

**Issue by PlannedCanada** [vector-im/element-web#17700] opened 2021-06-18 20:18 UTC
### Description

In Element-desktop I'm unable to decrypt **new** messages from all but one contact. I get "The sender's device has not sent us the keys for this message" from everyone else. This would be expected for an old message, but is odd for a new one, and strangely doesn't apply to one other user.

### Steps to reproduce

- I experienced a crash recently that corrupted my old keys, that might have something to do with it.

I would like to be able to see my messages.

Logs being sent: yes

### Version information

- **Platform**: Desktop.
- **OS**: Whonix.
- **Version**: 15.

**Comment by t3chguy** [comment] 2023-07-11 09:22
Duplicate of https://github.com/vector-im/element-meta/issues/245

**Closed by t3chguy** 2023-07-11 09:22 UTC
Labels: T-Defect, A-E2EE, Z-Rageshake, Z-UISI
