### ISSUE TITLE
Message preview is stuck in roomlist

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18821] opened 2021-08-27 22:40 UTC
### Steps to reproduce

Just happened to notice that the message preview for #synapse-dev:matrix.org was wrong by several msgs.

### What happened?

Browsing around; noticed stale msg preview

### What did you expect?

msg preview should be the most recent msg in the room, not one from ~20 msgs ago.

### Application version

nightly

### Have you submitted a rageshake?

Yes

**Comment by SimonBrandner** [comment] 2021-08-28 07:32
I don't think I can repro, is this only happening for #synapse-dev, does it fix itself after a restart?

**Comment by robintown** [comment] 2021-08-28 13:56
Sounds like a duplicate of https://github.com/vector-im/element-web/issues/17893

**Comment by SimonBrandner** [comment] 2021-08-28 15:10
Okay, let's close this in favour of that as it sounds like that issue

**Closed by SimonBrandner** 2021-08-28 15:10 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, S-Minor, A-Room-List, A-Message-Previews, O-Low
