### ISSUE TITLE
When the space panel auto-collapses for the create dialog, it requires two clicks to expand it again

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17257] opened 2021-05-11 20:58 UTC
consequence of https://github.com/vector-im/element-web/issues/17027

**Comment by t3chguy** [comment] 2021-05-20 11:30
Cannot reproduce this

Tried closing create menu by clicking on blur, expanding worked first try
Tried closing create menu by clicking the X button, expanding worked first try
Tried expanding space panel whilst create menu was open, expanded immediately, closed create menu

**Comment by turt2live** [comment] 2021-05-20 13:52
What about the expand button next to a space? I rarely ever bother with the button at the bottom...

**Comment by turt2live** [comment] 2021-05-20 18:57
ok, well, I wasn't getting that brokenness before, but that looks exciting. My steps were to let it auto-collapse, dismiss/deal with the dialog, expand.

**Closed** 2021-05-27 10:41 UTC
Labels: A-Spaces, T-Defect
