### ISSUE TITLE
Don't require the https:// prefix to HS address

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#15569] opened 2020-10-26 21:47 UTC
When the server name is entered without protocol prefix, it should prepend `https://` automatically.
This is a small feature, but can hugely affect FTUE.
The information that Matrix is based on HTTPS, is a tech detail, non-techie users shouldn't have to worry about it. They should be able to extract the server address from a Matrix ID. E.g. when I say "Hey, my Matrix ID is @notramo:grin.hu, register on this server, and invite me", they should be able to enter the part after the `:` at registration, and not think about the actual domain (.well-known), or the `https://` protocol prefix.
Currently, if there is no prefix, it doesn't even allow to accept the given address.
![kép](https://user-images.githubusercontent.com/26059643/97231166-0424f000-17d3-11eb-990f-5256a6014b2b.png)

**Comment by turt2live** [comment] 2020-10-26 22:11
Duplicate of https://github.com/vector-im/element-web/issues/7706

**Closed by turt2live** 2020-10-26 22:11 UTC
