### ISSUE TITLE
Redactable threading

### ISSUE THREAD

**Issue by Natureshadow** [vector-im/element-web#25581] opened 2023-06-13 11:41 UTC
#### What would you like to do?

As an admin or moderator of a chat room, I want to redact the thread relation of a message in a scenario where a user fails to reply in the thread.

As in, I would like to be able to move an existing message into a thread.

#### Why would you like to do it?

Threading in chat apps is an important feature to keep room history tidy, but users need to be educated to use it because it is not common in everyday instant messaging apps.

This results in threads getting fragmented regularly, which stops us from introducing them in our community because fragmented threads are much worse than no threads at all.

#### How would you like to achieve it?

I am not sure about this. Concerning UI, one could look into how e.g. Zulip does it. But spec-wise, I am not sure because relations between messages are hard to change without issues as I take it.

### Have you considered any alternatives?

An alternative would be to delete the message and require the user to post it again within the thread.

However, that will annoy users, and becomes unfeasible once others start replying to a message sent outside a thread.

**Comment by t3chguy** [comment] 2023-06-14 08:15
Duplicate of https://github.com/vector-im/element-meta/issues/503

**Closed by t3chguy** 2023-06-14 08:15 UTC
Labels: T-Enhancement
