### ISSUE TITLE
URI scheme for matrix (like "mailto:" or "sms:")

### ISSUE THREAD

**Issue by thomiel** [vector-im/element-web#20359] opened 2021-12-27 00:00 UTC
#### What would you like to do?

provide a link on a webpage or email signature with my matrix address or a matrix channel.

#### Why would you like to do it?

clicking ist faster than copy&paste.

#### How would you like to achieve it?

register the uri schema (to be discussed, for example "matrix:@foo:matrix.example.org") on native platforms, so element is being started in a chatroom with the given matrix address or channel.

see https://en.wikipedia.org/wiki/List_of_URI_schemes for existing uri schemes.

one drawback needs to be mentioned: this will make it easier for spam crawler to collect matrix addresses on the web. but if the matrix protocol is by design much less prone to message spam, it shouldn't make a difference.

### Have you considered any alternatives?

no, there is no alternative to a decent uri schema, if it really aims to replace email one day.
the https://matrix.to service is not really an alternative to an uri schema. it's only useful for people who do not already have installed a matrix client.

**Comment by aaronraimist** [comment] 2021-12-27 15:11
The Matrix URL scheme already exists but Element doesn't support opening it yet.

Closing as duplicate of #16875

**Closed** 2021-12-27 15:12 UTC
Labels: T-Enhancement
