### ISSUE TITLE
Screensharing in video room crashes browser

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22573] opened 2022-06-14 16:10 UTC
### Steps to reproduce

1. Join a video room, screenshare
2. Stop screensharing

#### What did you expect?
Browser doesn't crash

#### What happened instead?
Browser crashes on stopping screen sharing

### Browser information

Chromium 102.0.5005.61 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Yesterday's develop

**Comment by robintown** [comment] 2022-07-11 19:23
@kittykat I can't reproduce this, if you still can, could you please send logs?

**Comment by robintown** [comment] 2022-07-28 04:30
Closing due to lack of info

**Closed by robintown** 2022-07-28 04:30 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, S-Critical, A-Jitsi, X-Needs-Investigation, O-Uncommon, Z-Labs, A-Video-Rooms
