### ISSUE TITLE
Change system font without breaking emojis

### ISSUE THREAD

**Issue by MountainX** [vector-im/element-web#17207] opened 2021-05-08 20:01 UTC
### Description

I'm using Element Desktop on Linux.

I would like to be able to set a font for text (and only text) here:
Setting > Appearance > Advanced> Use a system font
**without affecting the emojis**

### Steps to reproduce

1. Setting > Appearance > Advanced> Use a system font
2. Set your desired system font.

I'm using a custom installed font on my system.

#### Describe how what happens differs from what you expected.

The font is correctly changed. However, I immediately lose the standard set of colorful emojis. What I get instead is no-color simple emojis and many are unprintable symbols.

Therefore, I have to choose between a font I don't like or broken emojis. I am not sure if my report is a bug or a feature request. If this is by design, could we have an option to retain the standard emojis if the chosen font results in what I'm seeing? If it is not by design, what I would expect is that changing the font affects text without affecting the standard colorful emojis.

### Screenshots:

[Expected emojis](https://ibb.co/HTnhv09)
![Screenshot_20210508_154825](https://user-images.githubusercontent.com/48405/117551855-434fbb80-b016-11eb-87f7-f8740cef4218.png)

[Emojis I get after changing system font](https://ibb.co/FXYCCZY)
![Screenshot_20210508_154727](https://user-images.githubusercontent.com/48405/117551865-4cd92380-b016-11eb-90f6-062f040bbb09.png)

### Version information

- **Platform**: desktop
- **OS**: Arch Linux,
- affects latest version

**Comment by t3chguy** [comment] 2021-05-10 09:46
Duplicate of https://github.com/vector-im/element-web/issues/14398

**Closed by t3chguy** 2021-05-10 09:46 UTC
Labels: A-Emoji, T-Defect

**Comment by MountainX** [comment] 2021-09-22 02:17
> You can specify multiple fonts, so specify the Emoji font you want first.
> 
> The default font definition is
> 
> `Inter, Twemoji, 'Apple Color Emoji', 'Segoe UI Emoji', Arial, Helvetica, Sans-Serif, 'Noto Color Emoji'`

Thank you. Very helpful!
