### ISSUE TITLE
scroll jitter in room list is back

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20441] opened 2022-01-08 13:47 UTC
### Steps to reproduce

1. scroll

related #18440

### Outcome

https://user-images.githubusercontent.com/2803622/148646533-f7ff9d65-a11b-42c2-be03-65504c72a308.mp4

### Operating system

arch

### Application version

Element Nightly version: 2022010801 Olm version: 3.2.8

### How did you install the app?

aur/element-desktop-nightly-bin

### Will you send logs?

No

**Comment by robintown** [comment] 2022-01-08 17:14
Duplicate of https://github.com/vector-im/element-web/issues/19322

**Closed by robintown** 2022-01-08 17:14 UTC
Labels: T-Defect, X-Regression, S-Minor, X-Release-Blocker, A-Room-List, O-Uncommon
