### ISSUE TITLE
upgrading to v1.11.0 invalidates session

### ISSUE THREAD

**Issue by 3nprob** [vector-im/element-web#22776] opened 2022-07-08 00:02 UTC
### Steps to reproduce

1. Have existing installation and signed in profile of electron-desktop v1.10.15.
2. Install v1.11.0
3. Start element-desktop

#### What did you expect?

element-desktop starts and shows a signed-in view with rooms just as on v1.10.15.

#### What happened instead?

The following modal is  displayed with a "Sign out" button being the only actionable:

```
Missing session data

Some session data, including encrypted message keys, is missing. Sign out and sign in to fix this, restoring keys from backup.

Your browser likely removed this data when running low on disk space. To help us prevent this in future, please send us logs.
```

![element-unexplained-sign-out](https://user-images.githubusercontent.com/74199244/177890678-2e832830-1a00-4309-ae55-8c6ff11b99e9.png)

### Operating system

Linux (NixOS)

### Application version

1.11.0

### Will you send logs?

No

**Comment by 3nprob** [comment] 2022-07-08 00:07
Element may have been running during a period of high disk pressure but I assume the part about "your browser may have..." should only be applicable to element-web and not element-desktop?

If that assumption is not right then this issue may not be caused by the v1.11.0 upgrade.

**Comment by t3chguy** [comment] 2022-07-08 07:06
@3nprob Element Desktop is built on Electron which uses Chromium under the hood, so a browser is still involved even if the phrasing isn't the clearest

**Comment by 3nprob** [comment] 2022-07-08 07:34
So would having disk pressure while Element Desktop is running explain why crypto keys were wiped? If so, is this documented anywhere and can anything be done about it? (I did try to look for chromium/electron references on such behavior but have not came up short)

**Comment by 3nprob** [comment] 2022-07-08 07:41
Potentially related issue: #18625

No flatpak - running unsandboxed.

This happened simultaneously on two simultaneously running instances from the same installation of Element (separate profiles so should not be a cause of conflict there) but a third one on the same host, which was not running at the time that this got triggered, was unaffected.

**Comment by turt2live** [comment] 2022-07-08 21:01
this isn't a regression.

If your disk was nearly full then browsers, including desktop, tend to purge data we ask it to store, unhelpfully. 

Considering a duplicate of one of these issues:
* https://github.com/vector-im/element-web/issues/20931
* https://github.com/vector-im/element-web/issues/18423
* https://github.com/vector-im/element-web/issues/4014
* https://github.com/vector-im/element-web/issues/10891

**Closed by turt2live** 2022-07-08 21:01 UTC
Labels: T-Defect
