### ISSUE TITLE
Can't verify secondary device (phone) using either QR code or symbols on MacOS

### ISSUE THREAD

**Issue by deanedridge** [vector-im/element-web#23390] opened 2022-10-02 10:40 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
I first install macOS Element Desktop via homebrew and verify Desktop all OK. Then install Element APK on Android phone.

2. What do you click?
Try to verify phone by pointing phone at Desktop app using QR code that is displayed on the macOS Desktop app.

3. More steps…
I try again a few times with no success.

Then I tried verification via symbols or emojis. 

#### What did you expect?
For the verification process to be completed and for the Desktop app to show that this device, my phone, has been verified.
#### What happened instead?

Everything works at first both on Desktop and phone, but then Desktop app asks if shields are the same on phone and Desktop, so I click the YES box on the Desktop app, and then it says the verification process has been cancelled. The same happens if I attempt to verify via the symbols/emojis.

I later tried verifying the phone by using the element.io website/app and verifying the phone through this. It worked successfully, so I concluded the issue must be with the Desktop macOS app.

I don't think I can repeat the issue as my phone is already verified. So that is why I have not selected to share logs.

### Operating system

macOS

### Application version

Element Version 1.11.8 (1.11.8)

### How did you install the app?

Homebrew

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-10-03 08:23
Duplicate of https://github.com/vector-im/element-web/issues/18165

**Closed by t3chguy** 2022-10-03 08:23 UTC
Labels: T-Defect
