### ISSUE TITLE
Self-Destructing mesages in Element

### ISSUE THREAD

**Issue by snicky-panda** [vector-im/element-web#15489] opened 2020-10-18 18:08 UTC
**Is your suggestion related to a problem? Please describe.**

A lot of activists in Belarus protests started using Element for encrypted chat communication. We are using it both from mobile and desktop versions. Due to the high risk of detention and high interest of the police in communication channels (they are forcing people to unlock their phones up to torture cases) people ask for cleaning up the message archives to avoid any leak of sensitive data to the regime.

**Describe the solution you'd like**

Self-destructing messages are highly important for automation of cleaning the history and making sure that no extra data left behind. As i understood this is already implemented in Synapse here - https://github.com/vector-im/element-web/issues/2497 and just needs implementation for the UI.

**Comment by turt2live** [comment] 2020-10-18 18:10
Duplicate of https://github.com/vector-im/element-web/issues/2497

**Closed by turt2live** 2020-10-18 18:10 UTC
Labels: suggestion
