### ISSUE TITLE
Replace "All Rooms" with a "Home" space

### ISSUE THREAD

**Issue by leytilera** [vector-im/element-web#17613] opened 2021-06-10 11:35 UTC
#### Is your suggestion related to a problem? Please describe.
I you have huge spaces with many rooms, that specifically belong to a space, it is annoying to have them all in this "All Rooms" space. They should only appear in their specific space, or, if they are part of multiple spaces, in all of them.

#### Describe the solution you'd like.
Replace the "All Rooms" space with a "Home" space, which only includes the rooms, that are not part of any space and all the direct messages. This way element would be way more organized and not such a mess like now.

#### Describe alternatives you've considered.
Maybe a config option, which allows to enable the "All Rooms" space, for people, who really need to view all rooms at once, althrough I can't imagine a scenario, where this is needed.

**Comment by t3chguy** [comment] 2021-06-10 13:12
Duplicate of https://github.com/vector-im/element-web/issues/17203

**Closed by t3chguy** 2021-06-10 13:12 UTC
Labels: T-Enhancement
