### ISSUE TITLE
Database error when trying to /rageshake. "Failed to send logs: No connected database"

### ISSUE THREAD

**Issue by stevepdp** [vector-im/element-web#20225] opened 2021-12-16 17:47 UTC
### Steps to reproduce

I am trying to send a rageshake from two clients on develop.element.io to help provide more data for issue #13603. Both clients are Firefox and logged in with the same test user. One of these clients is running in a normal window, the other (client B) is within a private window.

1. Type "/rageshake From client B testing #13603". 
2. Fill the form, pasting the link to the Github issue.
3. Send and see the "No connected database" error message.

Please see this screenshot as evidence of the error seen:

![Screenshot from 2021-12-16 17-37-42](https://user-images.githubusercontent.com/1271004/146422236-4aae7dc6-8d7c-446a-9f86-1ba9fedd720a.png)

I will try to send a rageshake for this if I can.

#### What did you expect?

I expected the debug log to be sent.

#### What happened instead?

I was presented with a database connection error.

### Operating system

Ubuntu 21.10

### Browser information

95.0 (64-bit) (snap, private window)

### URL for webapp

https://develop.element.io

### Application version

Element version: 23b21c940c68-react-9a8265429c16-js-3eaed304466a Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by stevepdp** [comment] 2021-12-16 17:50
Unfortunately I am unable to send a rageshake due to the same error.

![Screenshot from 2021-12-16 17-50-25](https://user-images.githubusercontent.com/1271004/146423063-7261d285-d195-44c9-84e6-a966c7c0ebad.png)

**Comment by aaronraimist** [comment] 2021-12-16 17:50
That's likely because you are using a private tab. Firefox doesn't provide all of the features Element uses in private tabs.

**Comment by aaronraimist** [comment] 2021-12-16 17:51
Duplicate of https://github.com/vector-im/element-web/issues/19298

**Closed by aaronraimist** 2021-12-16 17:51 UTC
Labels: T-Defect
