### ISSUE TITLE
client didn't send E2E keys to all users in a room

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#14929] opened 2020-08-11 11:22 UTC
I sent some messages in an e2e room which included @benparsons, but he was unable to decrypt the messages. (Other room member had no problem.)

From my rageshake:

```
2020-08-10T22:31:21.306Z I Preparing to encrypt events for !zcVxlBiVrIjvDgOtAM:bpulse.org
2020-08-10T22:31:21.307Z I downloadKeys: already have all necessary keys
2020-08-10T22:31:21.315Z I Starting new megolm session for room !zcVxlBiVrIjvDgOtAM:bpulse.org
2020-08-10T22:31:21.347Z I Storing megolm session jGrA17TFl4y0bPOf+MUGPDAjVwqHLEFgjcFUWVDhiyE/tD66vaj8rnJ72A2yAaFJI7QRTZj4btyDJvs9Nsi2HTg with first index 0
2020-08-10T22:31:21.362Z I Started new megolm session tD66vaj8rnJ72A2yAaFJI7QRTZj4btyDJvs9Nsi2HTg for room !zcVxlBiVrIjvDgOtAM:bpulse.org
2020-08-10T22:31:21.407Z I Using sessionid caw40VWB/hjZmUereb2GxiiCJIR+d9XOFyVbq20naMA for device @richvdh:sw1v.org:NIMGMUDVRV
```
... and so on, but no mention of devices for benpa.

later:

```
2020-08-10T22:32:37.383Z I received to_device m.room_key_request from: @benpa:bpulse.org id: undefined
2020-08-10T22:32:37.416Z I m.room_key_request from @benpa:bpulse.org:UKMZAOHQOP for !zcVxlBiVrIjvDgOtAM:bpulse.org / tD66vaj8rnJ72A2yAaFJI7QRTZj4btyDJvs9Nsi2HTg (id $local.d0b77a9e-5aac-46e5-8c52-244883ec73ca)
2020-08-10T22:32:37.416Z I megolm session tD66vaj8rnJ72A2yAaFJI7QRTZj4btyDJvs9Nsi2HTg never shared with user @benpa:bpulse.org
```

benpa is (and was) shown in the membership list, so *some* parts of eleweb thought that he was in the room. 

He has previously been able to decrypt events sent from this device.

my rageshake: https://github.com/matrix-org/element-web-rageshakes/issues/3401
benpa's rageshake: https://github.com/matrix-org/riot-android-rageshakes/issues/14120

**Comment by turt2live** [comment] 2022-06-14 05:11
Considering a duplicate of https://github.com/vector-im/element-web/issues/3846

**Closed by turt2live** 2022-06-14 05:11 UTC
Labels: T-Defect
