### ISSUE TITLE
Threads panel constantly resets scroll while it's fetching thread summaries and re-rendering

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#23787] opened 2022-11-17 23:42 UTC
### Steps to reproduce

1. Have a room where you haven't opened the threads list panel in a while
1. Open the threads list panel
1. Try to scroll around while it's catching up and fetching thread summaries
1. Notice how you keep being forced back to the bottom of the list each time something updates (like a thread summary)

The video is a bit cut-off as I didn't have the recording wide enough before I started recording but demonstrates the problem perfectly. The scroll keeps getting reset to the bottom.

https://user-images.githubusercontent.com/558581/202582910-0b959141-25a0-40b5-b4a7-ed9ec4b6d52d.mp4

#### What did you expect?

I expect to be able to scroll around seamlessly while things load in.

#### What happened instead?

Scroll is reset to the bottom each time something updates.

### Operating system

Windows 10

### Browser information

Chrome Version 107.0.5304.107 

### URL for webapp

develop.element.io

### Application version

Element version: a788d3fc91ba-react-266716e88841-js-ffcdfe166e55 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-11-18 09:21
Duplicate of https://github.com/vector-im/element-web/issues/23727

**Closed by t3chguy** 2022-11-18 09:21 UTC
Labels: T-Defect, S-Minor, O-Occasional, A-Threads, A-Timeline-Jumpy-Scroll
