### ISSUE TITLE
Element doesn't support SVG as Room Icons

### ISSUE THREAD

**Issue by ovflowd** [vector-im/element-web#19116] opened 2021-09-21 17:30 UTC
### Steps to reproduce

1. Open a Room
2. Head to the Settings
3. Upload a new Icon that is an SVG
4. Profit

#### What did you expect?

To be able to use an SVG for the Room Icon

#### What happened?

The Room Icon was blank and not defined as the SVG that I uploaded.

### Operating system

Windows and macOS

### Application version

Element version: 1.8.5 Olm version: 3.2.3

### How did you install the app?

From Element's website

### Homeserver

https://gnome.element.io

### Have you submitted a rageshake?

No

**Comment by non-Jedi** [comment] 2021-12-17 20:53
Duplicate of #2581

**Closed** 2021-12-17 21:01 UTC
Labels: S-Minor, A-Room-Settings, A-Media, T-Enhancement, O-Uncommon
