### ISSUE TITLE
Messages stuck or very slow at "Encrypting your message..."

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#24153] opened 2023-01-04 10:24 UTC
### Steps to reproduce

1. Send a message

#### What did you expect?

The message to send instantanously

#### What happened instead?

It's very slow, above the 2mn mark!
![Screenshot 2023-01-04 at 10 23 10](https://user-images.githubusercontent.com/769871/210534781-1b155e20-a945-4d70-8e30-a696aef444b1.png)

### Will you send logs?

Yes

**Comment by gsouquet** [comment] 2023-01-04 19:07
Not a duplicate, this has just happened in a room with 20 people. I would not consider this a "massive" room.

**Comment by gsouquet** [comment] 2023-01-09 14:32
Adding `X-Regression` this was not happening a month ago!

**Comment by clokep** [comment] 2023-01-09 14:34
I've also seen this happen in fairly small rooms. Although mine wasn't quite as small (57 and 103 users). Maybe someone has a lot of devices though?

**Comment by daniellekirkwood** [comment] 2023-01-19 11:10
I encountered this today morning. 
- I was sending one message to Element Web Internal (27 people)
- I also was sending a few messages in a DM to @clokep 

I was able to send messages instantly on iOS, on web these 2 rooms took around 5 minutes to send - they stayed looking like the screenshot above.

**Comment by gsouquet** [comment] 2023-01-19 11:15
I've seen a few ad hoc mention of this issue in multiple internal rooms. Will bump to `O-Frequent` as it's been experienced many times by many different people

**Comment by ara4n** [comment] 2023-01-23 09:40
> Maybe someone has a lot of devices though?

This is "only" 1276 devices. I've benchmarked it in Oct v Jan based on rageshakes for the same number of devices (43 slices, so 1075 in total) and it looks like we have a ~50% slowdown from somewhere. It also really feels like it's churning megolm more frequently than I'd expect, and/or not setting them up proactively enough.

**Comment by davidegirardi** [comment] 2023-02-14 12:31
I got this in multiple rooms today, not in DMs for some reason.

I checked the console log in one room where I had 3 "stuck" messages and I found three of these:
```
rageshake.ts:73 Event ~!EVENTIDHERE in room !ROOMIDHERE is live, but it does not have a timeline
e.<computed> @ rageshake.ts:73
```

See the rageshake for the event information. At the time of writing they have been stuck for about 2 hours.

**Comment by richvdh** [comment] 2023-02-14 12:53
I did a deep dive on one instance of a slow  send at https://github.com/matrix-org/element-web-rageshakes/issues/20102; my conclusion is:

 * it takes 80 seconds to send keys out in a room with 1288 devices (~60ms per device).
 * There might be room to optimise it, but since we're replacing the offending code as part of https://github.com/vector-im/element-web/issues/21972 I'm not sure that is a good use of time.
 * I see no evidence of this being a regression, though if someone can point me to logs from October or earlier I can compare.

(If messages are actually getting *stuck* for periods of several minutes, that sounds like a *different* problem.)

**Comment by richvdh** [comment] 2023-02-14 14:04
Duplicate of #15476.

**Closed by richvdh** 2023-02-14 14:04 UTC
Labels: T-Defect, X-Regression, S-Major, A-E2EE, O-Frequent

**Comment by richvdh** [comment] 2023-02-22 12:05
> (If messages are actually getting stuck for periods of several minutes, that sounds like a different problem.)

Have opened https://github.com/vector-im/element-web/issues/24612 to track this
