### ISSUE TITLE
Unable to upload some media files (libx265 in this case)

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/element-web#14882] opened 2020-08-05 10:28 UTC
I can upload a video converted to using video codec `libx264`, but not `libx265`!

## Reproduce

```
$  ffmpeg -i input.mkv -vcodec libx265 -crf 28 output-doesntwork.mp4
$  ffmpeg -i input.mkv -vcodec libx264 -crf 28 output-works.mp4
```

Then try to upload both `output-doesntwork.mp4` and `output-works.mp4`. You can upload `output-works.mp4` ONLY, at least in my case. Of course you are free to replace the input file's extension (and name).

I understand if the issue is similar to that of lack of thumbnails for files, it could be an Electron (chromium browser) issue but I am not sure of this and I am not sure that one must not be able to send files because it is not recognizable by Electron. This issue might not be limited to media files.

**Comment by t3chguy** [comment] 2020-08-05 10:30
Duplicate of https://github.com/vector-im/element-web/issues/11417

**Closed by t3chguy** 2020-08-05 10:30 UTC
Labels: bug

**Comment by odiferousmint** [comment] 2020-08-05 10:35
I would like to add that I experience this on Arch Linux, `element-desktop 1.7.2-1`.
Given the original discussion, I am not sure what is the right course of action, but I do believe it should not just be silently stuck at `Uploading output-doesntwork.mp4`. It took me a few minutes to realize the issue was related to the video codec.

**Comment by t3chguy** [comment] 2020-08-05 10:42
Actually the issue is part of https://github.com/vector-im/element-web/issues/14328 and https://github.com/vector-im/element-web/issues/14453 which are how to handle thumbnailing failure such as for unsupported codecs
