### ISSUE TITLE
Parse http links in Explore Rooms

### ISSUE THREAD

**Issue by elibroftw** [vector-im/element-web#23846] opened 2022-11-28 02:25 UTC
#### What would you like to do?

Parse https://matrix.to/#/#ethxmrswap:matrix.org in the UI

#### Why would you like to do it?

matrix.to is giving me an SSL error so 

#### How would you like to achieve it?

Just past the URL instead of parsing the link myself

### Have you considered any alternatives?

Manually editing the URL 

### Additional context

![image](https://user-images.githubusercontent.com/21298211/204177413-edf65581-9153-428b-bfe4-583123b6a8ba.png)

**Comment by t3chguy** [comment] 2022-11-28 09:27
Duplicate of https://github.com/vector-im/element-web/issues/16393

**Closed by t3chguy** 2022-11-28 09:27 UTC
Labels: T-Enhancement
