### ISSUE TITLE
Username formatting issue with IRC style layout

### ISSUE THREAD

**Issue by benbz** [vector-im/element-web#17724] opened 2021-06-22 07:48 UTC
### Description

Odd formatting of some usernames, only in specific rooms (they look fine in others), with the IRC layout since upgrading EleDesktop to 1.7.31

### Steps to reproduce

- Have `Enable experimental, compact IRC style layout` enabled 
- Someone (whose displayname needs disambiguation in the room?) speaks

1.7.31 EleDesktop:
![image](https://user-images.githubusercontent.com/1325121/122883646-518f3800-d335-11eb-8c0a-c3a4e0be755e.png)

1.7.30 EleWeb (don't have an older EleDesktop to test with) but sized similarly:
![image](https://user-images.githubusercontent.com/1325121/122884784-63bda600-d336-11eb-8380-abe00334e5aa.png)

### Version information

- **Platform**: Desktop
- **OS**:  Ubuntu
- **Version**: 1.7.31

**Comment by SimonBrandner** [comment] 2021-06-22 07:50
Duplicate of https://github.com/vector-im/element-web/issues/17648

**Closed by SimonBrandner** 2021-06-22 07:50 UTC
Labels: T-Defect
