### ISSUE TITLE
Preservation of shape and position

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16904] opened 2021-04-10 08:02 UTC
This is related to an earlier bug report concerning restoration after update.  It should happen also on restart even if there is no update.  Replacement at the old size and place should be the default.  Other special arrangements, like full screen or centered with an 8/5 slenderness ratio, should be configurable in the settings.

**Comment by t3chguy** [comment] 2021-05-04 09:56
Related https://github.com/vector-im/element-web/issues/10291

**Comment by t3chguy** [comment] 2023-04-18 14:21
Duplicate of https://github.com/vector-im/element-desktop/issues/686

**Closed by t3chguy** 2023-04-18 14:21 UTC
Labels: T-Defect, S-Minor, A-Electron, Z-Upstream
