### ISSUE TITLE
Collapse collapsible timeline events across date borders

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21839] opened 2022-04-18 13:22 UTC
#### What would you like to do?
Collapse collapsible timeline events (room state changes?) such as ACL, join, leave, dis/invite, remove (kick), ban, name change, avatar change, power level change across date borders

#### Why would you like to do it?
collapsing these events in rooms like https://matrix.to/#/#matrix-voip:envs.net or announcement channels that see only irregular activity but frequent updates to room state allows to see the conversation instead of just screens full of room state changes

#### How would you like to achieve it?
A day (localtime) is eligible for day-collapsing if there are only regularly collapsible events in it. Potentially always exclude today from that list.

If there are 2+ subsequent of such days, collapse the date headers, e.g. `Tue, Apr 5 2022` and `Wed, Apr 6 2022` to the appropriate range `Tue, Apr 5 2022 - Wed, Apr 6 2022`. Potentially extend the behaviour to be smarter like `Tue, Apr 5 - Wed, Apr 6 2022` but I foresee a lot of issues with that regarding localisation, e.g. German could be `Di 5. - Mi 6. Apr 2022` in this case while stupider locales such as US can't.

**Comment by robintown** [comment] 2022-04-18 13:27
Duplicate of https://github.com/vector-im/element-web/issues/16902

**Closed by robintown** 2022-04-18 13:27 UTC
Labels: T-Enhancement
