### ISSUE TITLE
Emoji picker seems to occasionally make absurd suggestions

### ISSUE THREAD

**Issue by ell1e** [vector-im/element-web#23680] opened 2022-11-02 07:52 UTC
### Steps to reproduce

1. Type `:wea`
2. Check out what the emoji picker suggests

#### What did you expect?
If I typed something that matches exactly the beginning of any emoji names, those should be the top results above others. If it matches exactly a substring of any emoji names at least, those should also sorted above any others where it doesn't.

#### What happened instead?
`:scream_cat:`? For `:wear`? I don't know, to me that seems a little absurd, there isn't even a `w` anywhere in `:scream_cat:` so it's *neither* a prefix nor substring match and yet it's at the top(??):
![Screenshot from 2022-11-02 08-45-04](https://user-images.githubusercontent.com/64124388/199430081-73c36f40-4786-41fc-a350-36f227f9b850.png)
I just can't really imagine anyone finding that top suggestion fitting or expected.

### Operating system

Linux

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### How did you install the app?

flatpak/flathub

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment] 2022-11-02 08:25
The reason for this showing up is that the emoji is called „Weary Cat“ :scream_cat: 

![image](https://user-images.githubusercontent.com/6216686/199437291-26e23d7f-5f80-4b10-9031-c05c1095547f.png)

Not seeing this information in the inline picker can lead to the confusion. I think this needs to be decided by design/product.

**Comment by ell1e** [comment] 2022-11-02 08:42
Even then, `:weary:` is the shorter match so I'd argue it should be at the top. If the other one was e.g. named `:wearycat:` then it should be 2nd, not 1st.

**Comment by grimhilt** [comment] 2023-03-09 12:04
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/10212 ?

**Closed** 2023-03-09 12:05 UTC
Labels: T-Defect, S-Tolerable, A-Emoji, O-Frequent
