### ISSUE TITLE
"Something went wrong!" when trying to join Element Web

### ISSUE THREAD

**Issue by jplatte** [vector-im/element-web#23854] opened 2022-11-29 08:50 UTC
### Steps to reproduce

I doubt this is reproducible easily. I'm on element-desktop-git (AUR package) `1.11.15.r12.gcbf5c43ae7-1` (unfortunately I'm not seeing how that commit hash here or in the -desktop repo, not sure where it's coming from but I built it <1h ago so should be up-to-date with current `main` pretty much). I tried to join the Element Web room through a search in a space directory to report a different bug..

#### What did you expect?

Element joining the room as normal.

#### What happened instead?

"Something went wrong!" (German localization) with some generic text about reporting this on GitHub.

### Operating system

Arch Linux

### Application version

1.11.15

### How did you install the app?

AUR

### Homeserver

1.71.0

### Will you send logs?

Yes:  [issue.txt](https://github.com/vector-im/element-web/files/10111325/issue.txt), [log-0.log](https://github.com/vector-im/element-web/files/10111326/log-0.log), [log-1.log](https://github.com/vector-im/element-web/files/10111327/log-1.log), [log-2.log](https://github.com/vector-im/element-web/files/10111329/log-2.log)

**Comment by t3chguy** [comment] 2022-11-29 08:52
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-11-29 08:52 UTC
Labels: T-Defect
