### ISSUE TITLE
Messages are not appearing in timelines

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25831] opened 2023-07-21 06:17 UTC
### Steps to reproduce

1. Use the app normally
2. Wonder why entire conversations aren't visible on Element Desktop

#### What did you expect?

Message history to work :p 

#### What happened instead?

Entire conversations, seemingly at random, are unavailable in my Desktop client but are visible in other clients like Element Android. It does not appear to be room-specific, and the events are not in threads (so should be in the main timeline). One of them has caused a stuck notification/mention on a room of mine - the notifications panel (bell icon top right) shows the message, but clicking gives "Failed to find timeline position" as an error. The message is visible in Element Android.

Example: `https://matrix.to/#/!MBrxZRUoApYYjmyion:t2bot.io/$-Lw6CKHGA-48C-riXOurMSgCRHYo7s4CgoEDQ4oQ1lw?via=t2bot.io&via=t2l.io` (t2bot.io public room)

**This only started happening with this nightly build (as far as I can tell).** I'm aware of approximately 20 messages missing, but there may be more.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023072001 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by Johennes** [comment] 2023-07-21 06:31
We've recently also saw cases of missing messages in threads which might be related (https://github.com/vector-im/element-web/issues/24466).

**Comment by t3chguy** [comment] 2023-07-21 07:45
Duplicate of https://github.com/vector-im/element-web/issues/22603

**Closed by t3chguy** 2023-07-21 07:45 UTC
Labels: T-Defect, S-Critical, O-Occasional
