### ISSUE TITLE
Share device verification/blocking status between our own devices

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#2537] opened 2016-11-03 08:49 UTC
We could use the account data for this, but we'd need to do some signing to stop it being forged

**Comment by Torxed** [comment] 2017-02-09 06:11
Could you use the existing message e2e encryption method and just send a encrypted file containing a \n separated list of trusted keys?

That way you don't break the message protocol and you get the e2e protection assuming you've verified at least your own two keys?

**Comment by helmo** [comment] 2017-02-27 20:25
#2286 is about sharing keys for chat history, but has the concept of asking another user/device for keys.

"Matthew has added a new device 'iPad' and is requesting room history since Sept 18th. Do you want to share history?" [ref](https://github.com/vector-im/riot-web/issues/2286#issuecomment-248931509)

For this issue what about a message to your older devices when you add a new one: "You just logged in width a new device, do you want to share encryption keys for your history with this new device?"

And in return on the new device: "On other devices you have verified the keys of some contacts, would you like to trust the same ones on this device?"

**Comment by ara4n** [comment] 2017-05-05 17:07
Just discussed this IRL with @richvdh; we kicked around the idea of just storing the verification state in a megolm room rather than finding another way to share encrypted JSON between our devices.  We'd want to encrypt the verification data as well as sign it from a privacy perspective.  Conclusion was that this is really a refinement of improving the verification UX and we should come back to it once focusing on improving verification.

**Comment by marekjedrzejewski** [comment] 2019-10-13 18:20
Verification process has been improved, but but there's still no synchronization of verified devices.
Even for single private room it was quite painful (I'm using 5 devices + 3 devices for the other side, even using the old method for devices I already verified on other devices, there was a lot of clicking).
Is this anywhere on the horizon, or has been forgotten?

**Comment by uhoreg** [comment] 2020-02-01 03:09
We now partially have this on the verification side, with cross-signing.  But we don't share blocking status yet.

**Comment by kittykat** [comment] 2021-12-21 16:43
We now share blocked user status between devices so I will close this issue for now. If the issue is about another type of blocking, please update with more details and re-open.

**Closed by kittykat** 2021-12-21 16:43 UTC
Labels: P2, A-E2EE, T-Enhancement, X-Needs-Community-Testing

**Comment by aaronraimist** [comment] 2021-12-21 16:54
This issue isn't about the ignore user feature. It was about the blacklist feature which allowed you to stop sending encrypted messages to specific devices. That feature no longer exists but maybe will come back in the future https://github.com/vector-im/element-web/issues/11751.
