### ISSUE TITLE
Unhelpful 400 error when adding MSISDN and server doesn’t delegate

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#10950] opened 2019-09-24 15:55 UTC
If you try to add a MSISDN to your account in Settings, but the HS is not configured to delegate MSISDN handling, Riot does not handle the error very well and presents a 400 error.

**Comment by jryans** [comment] 2019-09-30 12:15
This is ideally resolved by a better error code in the spec and / or some way the client to know if HS supports adding MSISDNs.

**Comment by jryans** [comment] 2019-10-11 10:55
Right, I think we all agree. The challenge is that at the moment the HS doesn't signal to the client whether it supports adding MSISDNs, so we may need some spec work to add that signal.

**Comment by kittykat** [comment] 2021-10-05 10:46
Could this be caused by matrix-org/sydent/issues/410?

**Comment by babolivier** [comment] 2021-10-05 10:52
> Could this be caused by matrix-org/sydent/issues/410?

Ah no, this looks like a different issue: in this case the homeserver isn't configured to delegate MSISDN requests to an identity server (therefore doesn't support adding a phone number), whereas in https://github.com/matrix-org/sydent/issues/410 the homeserver is configured to do so but Sydent (or the OM API) silently fail to send the text message.

**Comment by babolivier** [comment] 2021-10-07 09:20
Looks like Synapse is the naughty one here, since it seems to be hiding errors from Sydent to clients: https://github.com/matrix-org/synapse/issues/11016

**Comment by t3chguy** [comment] 2022-10-14 18:02
Duplicate of https://github.com/vector-im/element-meta/issues/766

**Closed by t3chguy** 2022-10-14 18:02 UTC
Labels: T-Defect, A-3PIDs, Z-Privacy-Sprint
