### ISSUE TITLE
Upgrading to 2022021801 nightly has made most of my rooms vanish and/or corrupt

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#21130] opened 2022-02-18 18:26 UTC
### Steps to reproduce

1. Was running nightly prior to Feb 18 (probably a build from Feb 15 or so)
2. Upgraded
3. All my spaces disappeared, and most of my rooms, and remaining rooms seem to have lost state.

#### What did you expect?

The application not to selfdestruct on upgrade

#### What happened instead?
The app selfdestructed on upgrade.

### Operating system

macOS

### Application version

nightly 2022021801

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ara4n** [comment] 2022-02-18 18:36
(reloading the desktop app recovered as if nothing had happened)

**Comment by gsouquet** [comment] 2022-02-21 09:09
Will take a look at that this morning

**Comment by t3chguy** [comment] 2022-02-28 07:52
```
2022-02-26T17:50:47.542Z E Error processing cached sync TypeError: Cannot read properties of undefined (reading 'localTimestamp')
    at Room.createThread (vector://vector/webapp/bundles/5a49dfe6eced0bf94934/init.js:21312:84)
    at Room.addThreadedEvent (vector://vector/webapp/bundles/5a49dfe6eced0bf94934/init.js:21282:23)
    at async MatrixClient.processThreadEvents (vector://vector/webapp/bundles/5a49dfe6eced0bf94934/init.js:19432:7)
    at async vector://vector/webapp/bundles/5a49dfe6eced0bf94934/init.js:66237:7
    at async Object.promiseMapSeries (vector://vector/webapp/bundles/5a49dfe6eced0bf94934/bundle.js:1182:5)
    at async SyncApi.processSyncResponse (vector://vector/webapp/bundles/5a49dfe6eced0bf94934/init.js:66161:5)
    at async SyncApi.syncFromCache (vector://vector/webapp/bundles/5a49dfe6eced0bf94934/init.js:65726:7)
    at async getFilter (vector://vector/webapp/bundles/5a49dfe6eced0bf94934/init.js:65622:7)

**Comment by ara4n** [comment] 2022-03-05 15:19
Just happened again on 2022030402

**Comment by dbkr** [comment] 2022-03-08 10:30
It's starting up without net access and failing to set up encrypted rooms because it can't fetch the member list:

```
2022-03-05T15:17:09.808Z I Enabling encryption in !fQZDstnphEFtEhuPDt:matrix.org; starting to track device lists for all users therein
2022-03-05T15:17:09.808Z I Starting to track devices for room !fQZDstnphEFtEhuPDt:matrix.org ...
2022-03-05T15:17:09.815Z E request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/r0/rooms/!fQZDstnphEFtEhuPDt%3Amatrix.org/members?not_membership=leave&at=m2747703236%7E1.2747703242%7E3.2747703242_757284974_10961089_1256136758_1239828424_3048164_434512896_3074056939_211902
ConnectionError: request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/r0/rooms/!fQZDstnphEFtEhuPDt%3Amatrix.org/members?not_membership=leave&at=m2747703236%7E1.2747703242%7E3.2747703242_757284974_10961089_1256136758_1239828424_3048164_434512896_3074056939_211902
    at vector://vector/webapp/bundles/25c2586213e8b3c859f0/init.js:54344:15
    at Object.callback (vector://vector/webapp/bundles/25c2586213e8b3c859f0/init.js:54277:9)
    at on_response (vector://vector/webapp/bundles/25c2586213e8b3c859f0/vendors~init.js:209393:22)
    at XMLHttpRequest.on_state_change (vector://vector/webapp/bundles/25c2586213e8b3c859f0/vendors~init.js:209369:7)
    at XMLHttpRequest.<anonymous> (vector://vector/webapp/bundles/25c2586213e8b3c859f0/vendors~init.js:191560:41)
2022-03-05T15:17:09.815Z E Error configuring encryption in room !fQZDstnphEFtEhuPDt:matrix.org: request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/r0/rooms/!fQZDstnphEFtEhuPDt%3Amatrix.org/members?not_membership=leave&at=m2747703236%7E1.2747703242%7E3.2747703242_757284974_10961089_1256136758_1239828424_3048164_434512896_3074056939_211902
ConnectionError: request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/r0/rooms/!fQZDstnphEFtEhuPDt%3Amatrix.org/members?not_membership=leave&at=m2747703236%7E1.2747703242%7E3.2747703242_757284974_10961089_1256136758_1239828424_3048164_434512896_3074056939_211902
    at vector://vector/webapp/bundles/25c2586213e8b3c859f0/init.js:54344:15
    at Object.callback (vector://vector/webapp/bundles/25c2586213e8b3c859f0/init.js:54277:9)
    at on_response (vector://vector/webapp/bundles/25c2586213e8b3c859f0/vendors~init.js:209393:22)
    at XMLHttpRequest.on_state_change (vector://vector/webapp/bundles/25c2586213e8b3c859f0/vendors~init.js:209369:7)
    at XMLHttpRequest.<anonymous> (vector://vector/webapp/bundles/25c2586213e8b3c859f0/vendors~init.js:191560:41)
```

We should work out what the correct behaviour is for starting up offline, although given this doesn't seem to be new, I don't think it's a release blocker.

**Comment by novocaine** [comment] 2022-03-08 15:39
if its network, duplicate of https://github.com/vector-im/element-web/issues/21052

**Closed by novocaine** 2022-03-08 15:39 UTC
Labels: T-Defect, X-Regression, S-Critical, O-Uncommon
