### ISSUE TITLE
lost encrypted messages after providing passphrase

### ISSUE THREAD

**Issue by ousia** [vector-im/element-web#13388] opened 2020-04-26 13:20 UTC
### Description

I have just confirmed that encrypted messages go lost after providing the right passphrase.

If I follow the steps below, what I get from these sent messages in next sessions is: 

> **Unable to decrypt: The sender's device has not sent us the keys for this message.**

### Steps to reproduce

1. Log in to your account.
1. Send a message in an encrypted room (don’t provide the passphrase).
1. Proceed to logout and provide the passphrase.
1. Backup is restored (and click OK). Read previously encrypted messages.
1. Proceed to logout again and click on _Sign out_ confirmation button.
1. Log in again.
1. Connect session to key backup (or simply provide your passphrase to read encrypted messages).
1. Confirm (sorry, but with horror) that the message you sent from your previous session is lost forever.

What I think everyone would expect is that encryption backup was actually performed.

### Version information

- **Platform**: web (in-browser).
- **Browser**: Firefox 66.
- **OS**: Fedora.
- **URL**: https://riot.im/app.

**Comment by jryans** [comment] 2020-04-27 15:33
It would be interesting to know how this plays out in cross-signing world once 1.6 releases. It would also be good to have debug logs to be able to investigate. Once 1.6 has released, please retest and submit debug logs via Settings -> Help -> Submit debug logs.

**Comment by kittykat** [comment] 2021-11-30 18:13
We cannot reproduce this issue so I will close it for now. If you are still experiencing it, please reply with @kittykat and I will reopen it for you.

**Closed by kittykat** 2021-11-30 18:13 UTC
Labels: T-Defect, A-E2EE-Key-Backup, X-Needs-Community-Testing
