### ISSUE TITLE
Verified session claims that it's not verified

### ISSUE THREAD

**Issue by jdm** [vector-im/element-web#14351] opened 2020-07-06 14:30 UTC
### Description

I have a session that I have previously verified. My user profile shows that session as verified. Opening that session gives me the "Verify this session" dialog.

### Steps to reproduce

Not entirely clear; I have multiple other verified sessions that do not show the dialog.

Log: sent

### Version information

- **Platform**: web (in-browser)

For the web app:

(buggy session)
- **Browser**: Firefox 78.0.1
- **OS**: Windows
- **URL**: chat.mozilla.org

(working session)
- **Browser**: Firefox Nightly 80.0.a1 (7/5/2020)
- **OS**: macOS

**Comment by mistergibson** [comment] 2020-07-08 16:35
I have this issue as well, but on Linux Desktop Client. I must log in each and every time I launch the app, where it used to simply resume my session. Additionally, I have to VERIFY the session with my other devices EACH TIME I LAUNCH THE APP. Please fix this.

**Comment by jryans** [comment] 2020-07-08 16:41
@mistergibson That sounds unrelated, please file a separate issue so we can investigate.

**Comment by justfortherec** [comment] 2020-07-16 14:02
I see the same message on both `app.element.io` and `riot.im/app` (I switched from the latter to the former yesterday and kept both open because of this message) in Firefox 78.0.2 on Ubuntu 18.04.

The message has persistently shown up in `riot.im/app` for weeks already.

The message is not shown on my only other client RiotX on Android.

What makes this annoying is that I cannot actually go through the wizard to verify the session because I cannot find where I could do so in any of the other sessions since both sessions seem to see each other as verified:
![image](https://user-images.githubusercontent.com/935534/87641613-a3eccf80-c748-11ea-8d7f-6c7474ed9683.png)


(in RiotX I cannot even find where to list other sessions).

I am happy to provide logs or other debugging information if you consider it helpful.

**Comment by jryans** [comment] 2020-07-17 15:43
@jdm Hmm, looking at debug logs is seems like the cross-signing private key is not stored on your account, but it's puzzling that you only see this message in a single session...

In the problem session, what do you see in Settings -> Security & Privacy -> Cross-signing -> Advanced (maybe easiest to screenshot)?

Is this your only web session, or do you have other working web sessions? Maybe the other sessions are Element / RiotX for Android? (Again, perhaps a screenshot of your session list from your profile is easiest.)

I think this may be a case of web strictly testing for something that mobile does not, but would be good to confirm.

**Comment by jdm** [comment] 2020-07-17 16:00
I have two web sessions that I can access right now, and I have one RiotX for Android session as well.
![sessions](https://user-images.githubusercontent.com/27658/87806531-07e4c600-c825-11ea-8885-cafa8b8a6fcd.png)

![crosssign](https://user-images.githubusercontent.com/27658/87806538-0b784d00-c825-11ea-95c9-a44523ef3f12.png)

**Comment by gtbuchanan** [comment] 2020-07-17 19:25
I can confirm this was happening on Riot Desktop for my wife prior to the Element rename and it is still happening on the same machine after updating to Element, signing out, and re-verifying. The session shows verified in the session list but the verify dialog continues to pops up. The verification was done using Element Android.

**Comment by justfortherec** [comment] 2020-07-18 17:21
In my case, _Cross-signing_ is not set up either.

If that is the cause for the pop-up it might be helpful to reword the screens in the flow when pressing _Verify_ in the pop-up. At least to me it was not (and is still not) clear to me how I can continue once this screen shows up:
![image](https://user-images.githubusercontent.com/935534/87858105-cb4fc200-c92b-11ea-99ed-6944ef76401e.png)

**Comment by zeta0134** [comment] 2020-07-25 16:11
Chiming in here with exactly the same issue. I don't use encryption or cross-signing (at least, I haven't manually set those up on purpose) but I went through the verification process anyway, purging about a dozen old sessions and doing the cute little emoji thing. The flow appears to work, and all sessions show up as verified on all four devices:

![riot_verified](https://user-images.githubusercontent.com/1165075/88461016-1dca3a80-ce66-11ea-9730-a20f936a0a7c.png)

Despite this, opening the app on every device presents the verification dialog every time. There's no way to advance past the "Verify this session" dialog because none of my other devices actually display an unverified session to click on. So, the dialog must be repeatedly dismissed with "Later."

These sessions all used to be Riot and excepting the Android app, have been upgraded in place without a relog. The home server was also recently upgraded all the way from 1.0 -> 1.15, when I realized that it had been stuck on python 2.7 for quite some time and pip was holding updates back. So, I wouldn't rule out something funky happening on the homeserver, but I've got no idea what to look for. If there are any logs I can provide that would help narrow down the issue I'm all ears. :)

**Comment by jryans** [comment] 2020-09-02 14:11
Thanks for all the feedback on this! As part of https://github.com/vector-im/element-web/issues/14970, I've made some changes to the logic that affect this area and may help with this issue. For now, I'll close this as hopefully improved. If it's still an issue in future versions, please open a fresh issue so we have a clear story with fresh logs.

**Closed by jryans** 2020-09-02 14:11 UTC
Labels: feature:e2e-cross-signing
