### ISSUE TITLE
Resizable and/or larger composer/textbox

### ISSUE THREAD

**Issue by QEDeD** [vector-im/element-web#22400] opened 2022-05-30 16:43 UTC
#### What would you like to do?
I would like to be able to make the composer/textbox larger vertically.

#### Why would you like to do it?
Because as soon as you start writing a longer message, you quickly lose track of what you are writing and navigating up and down is in itself not very user-friendly now that I think about it, it seems like you have rather bad control of scrolling up and down through the message you're writing.

#### How would you like to achieve it?
I see two general approaches. 

1) Would be doing something similar to how Signal works, in which you can expand the compose field by clicking a button:
![image](https://user-images.githubusercontent.com/16562457/171033211-06a108f7-d3ce-418e-ab3f-2d3db9800805.png)

2) Would be doing something similar to how the room list can be expanded and contracted as the user sees fit

### Have you considered any alternatives?

1) A larger default composer
2) A compose that scales in size (to a certain extent) as you write a message

**Comment by t3chguy** [comment] 2022-05-30 16:46
Duplicate of https://github.com/vector-im/element-web/issues/5882

**Closed by t3chguy** 2022-05-30 16:46 UTC
Labels: T-Enhancement
