### ISSUE TITLE
Device additions and removals not reflected in Element Web R

### ISSUE THREAD

**Issue by hughns** [vector-im/element-web#26374] opened 2023-10-16 10:36 UTC
### Steps to reproduce

1. Open session manager in Element Web R
2. Sign in a new device
3. The new device is not listed on Web R, but it is shown automatically on Web (non-R).

#### What did you expect?

That the new device would automatically be added and removed to the device list like it does on regular Web.

#### What happened instead?

I had to force the device list to reload in order for the device to show/disappear.

### URL for webapp

https://pr10080--matrix-react-sdk.netlify.app

### Will you send logs?

Yes

**Comment by richvdh** [comment] 2023-10-16 11:00
Duplicate of #26263

**Closed by richvdh** 2023-10-16 11:00 UTC
Labels: T-Defect, A-Element-R
