### ISSUE TITLE
"some of your messages have not been sent" giving option for 'delete all or resend all' for all messages in a particular 'encrypted' room/dm

### ISSUE THREAD

**Issue by N1N74** [vector-im/element-web#17195] opened 2021-05-07 05:18 UTC
![image](https://user-images.githubusercontent.com/39383296/117397182-2e413280-af19-11eb-9676-6ce2eaec5015.png)

### Description
Was not able to send any messages at all in an 'encrypted' room (dm) from particular sessions. Not sure exactly how it happened but android element showed encryption disabled for room (dm) despite my other sessions showing the room encryption as already enabled. Enabling encryption on android element showed "encryption enabled" room message on my other sessions as well, despite already showing encryption enabled since before.
![image](https://user-images.githubusercontent.com/39383296/117398256-a01a7b80-af1b-11eb-8842-867f150b6586.png)
I was able to send messages properly immediately once encryption from android was enabled. Only new sessions were affected by this, and were unable to send encrypted messages to such rooms. I have noticed on staging.element.io for sure but also develop.element.io and app.element.io if I recall correctly. I have had cross signing turned on and used recovery keys while logging in to all my new sessions, unlike my older session that I setup by connecting to backup in the privacy settings menu. I also had cross signing turned on and the backup connected the way mentioned, long ago.

### Steps to reproduce
Not exactly sure since I don't want to disturb my setup again but I think connecting to backup via privacy settings between sessions with two different encryption options for the same room and then adding a new session but using recovery keys while logging in, is the culprit. I had cross signing enabled on all sessions so I'm guessing the conflicting information causes this error but I could be wrong. I'm not technically skilled in this to know, sorry for quality of report I had to make since I couldn't find similar issue mentioned. The original sessions with conflicting information both function as the room setting claims it works but new sessions don't. I had connected the backup and setup cross signing long ago and this might not be possible anymore.

Describe how what happens differs from what you expected:
To be able to send messages since the room is shown as encrypted with no indication of error other than "some of your messages have not been sent".

Logs being sent: yes

### Version information

- **Platform**: web (in-browser): staging.element.io as well as develop.element.io and app.element.io if I recall correctly

For the web app:

- **Browser**: Chrome and Firefox
- **OS**: Windows
- **URL**: develop.element.io / app.element.io / staging.element.io

**Comment by turt2live** [comment] 2021-05-07 05:48
Based on your logs, it looks like someone redacted the encryption event in that room, which will have confused the clients since now they won't know what to do. Or in other words, I think this is a duplicate of https://github.com/vector-im/element-web/issues/3498 and we should fix https://github.com/vector-im/element-web/issues/10618

**Closed by turt2live** 2021-05-07 05:48 UTC
Labels: T-Defect
