### ISSUE TITLE
selectin space not remove favorite empty rooms from room list

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#18041] opened 2021-07-17 13:16 UTC
![1](https://user-images.githubusercontent.com/1297163/126038065-af97bbf9-c4f3-477c-89de-c0f62a059b54.png)

Steps to reproduce:

1. create empty room (with only creator) - in my case is "my notes"
1. add this room to favorites
1. join to any space (where no my private room "my notes"
1. select space in UI
1. "my notes" room show in list, but it must be hided

Element desktop: 1.7.31
Ubuntu linux 20.04 x64

**Comment by t3chguy** [comment] 2021-07-17 13:23
Hmm, I cannot reproduce this

![image](https://user-images.githubusercontent.com/2403652/126038341-74eab65e-e96f-429d-b6f4-9cc1075056c0.png)

Shows a space selected and none of my favourites show up

![image](https://user-images.githubusercontent.com/2403652/126038350-54be09ef-7264-41ee-b61c-7547430283a7.png)

---

You are running 1.7.31 - latest is 1.7.32 with 1.7.33 in RC. I tested on latest Nightly, please try to reproduce on develop.element.io

**Comment by progserega** [comment] 2021-07-22 07:08
1. I update element-desktop to: 1.7.33
1. In Favorites always show only rooms with no users. Rooms, where only me joined. Other rooms filter by spaces very well.

**Comment by progserega** [comment] 2021-07-22 07:18
At this screenshot we can see:
1. selected space "Проекты"
1. open "Manage rooms of space" for this space
1. see, that room "Купить" and "Сохранение на rsprim.ru" - in favorites ("Избранные") (this rooms have only one member - me) no in rooms of this space, but it show in room list, when this space selected.
![1](https://user-images.githubusercontent.com/1297163/126602098-beaebba0-a28d-477d-b8f5-833afee59c47.png)

**Comment by t3chguy** [comment] 2021-07-22 08:14
Those rooms are likely DMs (with yourself) in your `m.direct` account data so thus will show in spaces you are in. Its an unrelated bug which will be solved by the Canonical DMs project

**Comment by progserega** [comment] 2021-07-23 22:59
Yes, this room in there as:
```
    "@progserega:rsprim.ru": [
      "!BbEbDoCAsldFrrwcdW:rsprim.ru",
      "!iEEJcPwBMJZJSllEBc:rsprim.ru"
    ],
```

**Comment by t3chguy** [comment] 2021-07-23 23:00
Duplicate of https://github.com/vector-im/element-web/issues/16547

**Closed by t3chguy** 2021-07-23 23:00 UTC
Labels: A-Spaces, T-Defect, X-Cannot-Reproduce
