### ISSUE TITLE
Support deleting of edited messages

### ISSUE THREAD

**Issue by jdohm** [vector-im/element-web#17032] opened 2021-04-21 20:35 UTC
#### Is your suggestion related to a problem? Please describe.
If I write a message to someone not using the Element app, change the message and then delete it, the edited message stays visible on his end. 

#### Describe the solution you'd like.
Delete both, the original as well as the edited message or at least give an option to do so.

#### Describe alternatives you've considered.
Also display the edited message on the element side. 

#### Additional context
here is a screenshot showing a edited and deleted message on element and cactus comments. 
![image](https://user-images.githubusercontent.com/9203094/115617261-7f361180-a2f1-11eb-9e25-6df1a0e2be06.png)

**Comment by t3chguy** [comment] 2021-04-22 07:35
Duplicate of https://github.com/vector-im/element-web/issues/11978

**Closed by t3chguy** 2021-04-22 07:35 UTC
Labels: T-Enhancement
