### ISSUE TITLE
newly joined rooms don't appear in breadcrumbs

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15941] opened 2020-12-09 20:05 UTC
which is very jarring for folks who depend on breadcrumbs to navigate recent rooms

**Comment by kegsay** [comment] 2021-08-17 09:27
Dupe of https://github.com/vector-im/element-web/issues/16400 - though probably not my place to close this issue.

**Closed** 2021-08-17 09:29 UTC
Labels: T-Defect, P2, S-Minor, A-Breadcrumbs
