### ISSUE TITLE
Message removal/redaction reason isn't shown

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element-web#23058] opened 2022-08-11 14:01 UTC
### Steps to reproduce

1. Remove a message
2. Element Web requests you to give an optional reason.
3. Supply it and press ok
4. See that you removed message, but not the reason.

#### What did you expect?

I expected to see "Aminda posti viestin syystä XYZ" (Aminda removed the message due to XYZ"

#### What happened instead?

I see "Aminda poisti viestin" ("Aminda removed the message") with no reason supplied.

I know that as a `/devtools` user I can view message source to get the message removal reason, but why ask it if it's not shown and the reason being visible there is not obvious to a non-experienced Matrix user.

### Operating system

"Fedora release 36 (Thirty Six)"

### Browser information

Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0 ID:20220810212956

### URL for webapp

develop.element.io

### Application version

Element-versio: 39eee10c576f-react-ed4286aa933b-js-478270b225ec Olm-versio: 3.2.12

### Homeserver

pikaviestin.fi is on Synapse 1.64.0

### Will you send logs?

No

**Comment by Mikaela** [comment] 2022-08-11 15:40
Hydrogen seems to support this too.

![Screenshot from Hydrogen saying "This message has been deleted (Testing message removal reason.)"](https://matrix.pikaviestin.fi/_matrix/media/r0/download/pikaviestin.fi/c533d6d567996e5631e3d3179983df9084240bd3)

**Comment by robintown** [comment] 2022-08-11 19:32
Duplicate of https://github.com/vector-im/element-web/issues/18581 (they're not shown because in their current form, they can be an abuse vector)

**Closed by robintown** 2022-08-11 19:32 UTC
Labels: T-Defect, S-Tolerable, A-Redaction, O-Occasional
