### ISSUE TITLE
[Feature request] Provide a list of public matrix server in the app

### ISSUE THREAD

**Issue by LoveIsGrief** [vector-im/element-web#16446] opened 2021-02-13 12:45 UTC
### Description

When opening the web or desktop app, there's an option to select an alternative server to create an account on, however as a newbie there's no instruction on how to find and select a public matrix server.

### Suggestion

Provide a list of instances to use / create an account on when using Element for the first time. An official, publicly maintained list would be really great. New users would be able to select on that is closest to them and take load off of the main matrix.org server.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: OpenSuse 15.2
- **Version**: 1.7.20

**Comment by t3chguy** [comment] 2021-02-13 12:58
Duplicate of https://github.com/vector-im/element-web/issues/6827

**Closed by t3chguy** 2021-02-13 12:58 UTC

**Comment by LoveIsGrief** [comment] 2021-02-13 14:50
My bad. Must'be searched for the wrong terms.
