### ISSUE TITLE
Space invite doesn't contain m.space event

### ISSUE THREAD

**Issue by ajbura** [vector-im/element-web#19862] opened 2021-11-23 10:02 UTC
### Steps to reproduce

1. Open app.element.io with test1.
2. Open private window of app.element.io with a test2 account.
3. Create a space on test1 account and invite test2.
4. Space invite on test2 will appear in room list.
5. Open test1 on Element android and follow step 3.
6. Invite on test2 will appear in space sidebar.

### Operating system

not needed

### Browser information

not needed

### URL for webapp

app.element.o

### Application version

Element version: 1.9.5 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by nadonomy** [comment] 2021-12-02 18:57
@t3chguy trivial fix?

**Comment by t3chguy** [comment] 2021-12-02 19:01
Needs investigation but what data is included in an invite stripped state is solely up to the server, the mobile app might be working around it by using the hierarchy or summary APIs but either would require quite a large effort to fit into this part of the dataflow of EW.

**Comment by t3chguy** [comment] 2021-12-03 10:05
Cannot reproduce


https://user-images.githubusercontent.com/2403652/144584262-68287315-cc83-4752-87c4-c050558c06f9.mov

**Comment by ajbura** [comment] 2021-12-03 13:38
Strangely, I am not also able to reproduce it now. Maybe it got fixed with synapse update. Feel free to close.

**Comment by t3chguy** [comment] 2021-12-03 13:46
Closing, do shout somewhere if you see it again!

**Closed by t3chguy** 2021-12-03 13:46 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Minor, A-Spaces, A-Invite, O-Occasional
