### ISSUE TITLE
Full time stamps for messages

### ISSUE THREAD

**Issue by DantrazTrev** [vector-im/element-web#16677] opened 2021-03-13 10:31 UTC
**Is your suggestion related to a problem? Please describe.**
If you scroll up in the element web app to some point , the only timestamp on messages visible are time of sending, 
Like this
![image](https://user-images.githubusercontent.com/43457420/111026792-57aa7a00-8412-11eb-991a-2c62ad6d852f.png)

This becomes particularly hard to navigate if there  are a lot of of messages in a day because there is no clear indicator of the day , other than the day heading at the start of the day thread and the hover over the time

![image](https://user-images.githubusercontent.com/43457420/111026866-c2f44c00-8412-11eb-99d6-4089c1a3ad80.png)

**Describe the solution you'd like**
A full day time stamp for the messages could be implemented

**Describe alternatives you've considered**
The Date separator can act like a fixed header for the conversations pertaining to the day

**Comment by SimonBrandner** [comment] 2021-03-13 11:57
Related to [#16221](https://github.com/vector-im/element-web/issues/16221)

**Comment by nicorikken** [comment] 2021-12-06 07:06
Rather than scrolling up by myself, I encounter this discomfort when using the 'Jump to first unread message' option. I have no idea if that message was from days ago or today. I don't check all channels daily. I either have to scroll up or down to encounter a date change to get a sense of the date we're at. The practical implications is low, but the feeling of being 'lost in time' brings discomfort. Thanks @DantrazTrev for reporting this.

**Comment by tsobolev** [comment] 2022-12-11 23:05
It would be perfect to have option for full datetime on every message. May be on mouse over.

**Comment by vertigo220** [comment] 2023-01-18 23:36
This is related to #7575, which is the alternative mentioned by OP, and if that were implemented having the date on each message wouldn't be as important and probably not needed at all, though it probably should still be an option for those that prefer it, plus it would probably be easier to implement and therefore be better than nothing while waiting for that issue to be completed.

**Comment by germain-gg** [comment] 2023-08-30 06:37
Marking as a duplicate of https://github.com/vector-im/element-web/issues/7575

This is an alternative solution to what is suggested there. I would suggest your idea there.

**Closed by germain-gg** 2023-08-30 06:37 UTC
Labels: A-Timeline, X-Needs-Design, T-Enhancement, O-Occasional
