### ISSUE TITLE
Not the entire list of users is displayed in the search

### ISSUE THREAD

**Issue by korneydanote2** [vector-im/element-web#19914] opened 2021-11-26 21:17 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
In the search for users, enter the desired
The result is not displayed
But the result is in the response from the server

![clear_result](https://user-images.githubusercontent.com/94513169/143645039-54707642-f512-48a8-b019-8a261c551705.png)
![tmp TmOqYdI4o3](https://user-images.githubusercontent.com/94513169/143645581-87101561-20b2-44ae-bf25-748745e81602.png)

At the same time, the result is displayed in the mobile version
![Screenshot_20211127_000551](https://user-images.githubusercontent.com/94513169/143649198-28e83018-19e0-4afb-9706-fe8b42299fe2.jpg)

It may be due to the fact that there is already a created dialog with the user

But it seems to me that it should still show the entire list of found

#### What did you expect?
Show the entire list of found users
### Operating system

Arch Linux

### Browser information

Google Chrome 96.0.4664.45

### URL for webapp

develop.element.io; app.element.io

### Application version

Matrix version: 1.9.3 Olm version: 3.2.3

### Homeserver

matrix.isg-sys.com

### Will you send logs?

No

**Comment by t3chguy** [comment] 2021-11-26 22:10
Looks like a duplicate of https://github.com/vector-im/element-web/issues/17075

**Closed by t3chguy** 2021-11-26 22:10 UTC
Labels: T-Defect
