### ISSUE TITLE
Combining Image AND text together in one message

### ISSUE THREAD

**Issue by shoqvalue** [vector-im/element-web#22272] opened 2022-05-18 18:51 UTC
#### What would you like to do?

As with Slack, I want to be able to paste an image into a message, and then type message text above or below it in the same message. 

#### Why would you like to do it?

Because a) it's extremely popular in Slack and Slack clones and many new users will expect the experience (as I did).  It's painfully inconvenient to always have to consider whether text or images should go first or last as a message, when intuitively, they should be combined in the same message in the first place.

#### How would you like to achieve it?
Whether I paste test first, or image first, simple position a thumbnail wherever it lands. The user can always adjust placement,

### Have you considered any alternatives?

Pasting images or text before or after one or the other is a workaround, but not really an alternative.

### Additional context

RocketChat had this same issue, and when I raised it there about 1.5 year ago, it set of a firestorm of rants about how developers always seem to ignore the obvious features that non-technical users want and need, in favor of those they think they should want and need. 

Almost every NTU (and a fair number of TUs) agreed it was an obvious feature, while almost every developer tried to tell them they were wrong.  I hope the same quarrel doesn't happen here. I come in peace. 

I am so excited about this app and it's potential, I'd just like to see features that are now fairly standard in most robust chat experiences. Element has so much going for it, I'd hate to see it get lower grades with reviewers simply because it misses some of the lowest-hanging fruit.

**Comment by robintown** [comment] 2022-05-18 20:06
Duplicate of https://github.com/vector-im/element-web/issues/6295

**Closed by robintown** 2022-05-18 20:06 UTC
Labels: T-Enhancement
