### ISSUE TITLE
Error decrypting image

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#20741] opened 2022-01-25 15:59 UTC
### Steps to reproduce

1. Open an encrypted room. Note that encryption seems to be working for text (and other images).
2. Receive an encrypted image.
3. Wait for it to decrypt (noting the pulsing thumbnail)
4. "Error decrypting image"

#### What did you expect?

An image to be decrypted and visible.

#### What happened instead?

Error decrypting image

### Operating system

Arch Linux / Wayland w/ Sway

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

Element version: 1.9.9 Olm version: 3.2.8

### Homeserver

Synapse 1.50.1

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-01-26 10:24
```
2022-01-25T15:57:27.956Z W Unable to decrypt attachment:  Failed to fetch
TypeError: Failed to fetch
```

Duplicate of https://github.com/vector-im/element-web/issues/3892

**Closed by t3chguy** 2022-01-26 10:24 UTC
Labels: T-Defect, S-Major, A-E2EE, Z-Rageshake, A-Media, O-Uncommon
