### ISSUE TITLE
Changing theme from Dark to Light does not take effect.

### ISSUE THREAD

**Issue by EECvision** [vector-im/element-web#21610] opened 2022-03-30 23:23 UTC
### Steps to reproduce

https://user-images.githubusercontent.com/63562663/160946884-0d80a580-650f-4f29-8fa7-96a87d77cbaf.mp4

#### What did you expect?
Change theme to Light mode

#### What happened instead?
Dark mode persisted after changing to Light mode 

### Operating system

Windows

### Application version

Version 21H2

### How did you install the app?

https://element.io/get-started

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-03-31 04:39
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19514

**Closed by SimonBrandner** 2022-03-31 04:39 UTC
Labels: T-Defect
