### ISSUE TITLE
The self-cross-sign modal should not be cancellable by hitting the background

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13067] opened 2020-04-07 21:05 UTC
After hitting the 'review' button on the 'new login' toast, @BillCarsonFr was managing to hit the bg and cancel the modal, with no easy way to resume the flow.  Perhaps we should disable modal-cancelling-by-clicking-in-the-bg for scenarios like this?

**Comment by t3chguy** [comment] 2023-10-16 09:17
Duplicate of https://github.com/vector-im/element-web/issues/6109

**Closed by t3chguy** 2023-10-16 09:17 UTC
Labels: T-Defect, S-Minor, A-E2EE-Cross-Signing, O-Uncommon
