### ISSUE TITLE
[Design] Stop using the user avatar as a room list gradient.

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20179] opened 2021-12-14 11:48 UTC
### Your use case

(...or at least make it opt-in)

Currently, Element's room list background will have a muted/blurred tint and gradient added to it from the user's avatar.

This may be a nice little touch, but it can have effect on how Design hits an outlook;

---

(Some [Conversation in the design room](https://matrix.to/#/!zzGPdcyFqxIOJEijoI:matrix.org/$2y_rV0uKq6qkowQtrG3tZOw0OB5dExOsmtKzrph_XLE?via=matrix.org&via=envs.net&via=kde.org))

A:

> > OH HEY the tab changed to a little arrow in a circle! i feel heard.
> 
> It looks much better

B:

> it does. but in dark mode i find the border between space bar and room list very hard to see, and thus it's not easy to see that the button is on that border.
> 
> it's better in light mode

![image](https://user-images.githubusercontent.com/22740616/145992156-2ffa87de-f671-4d9d-8984-b2c4e23704de.png)

> there's this gradient in the space bar, and you can see the border in the middle (lower arrow) thanks to it, but at the top barely

![image](https://user-images.githubusercontent.com/22740616/145992389-b1aa0389-2449-48e0-a560-04e4fe3c399d.png)

C (me):
> it depends much on the user's avatar
> 
> hold on

![image](https://user-images.githubusercontent.com/22740616/145992370-e89aa1f0-4e54-41a4-a0d8-c254cb05c7d5.png)

> i have a much lighter avatar, and its fairly visible where the seam is

---

So this is my recommendation to the design team: either generate and play with a wide array of avatars (from all colours to patterns and greytones) to see how their blurred backgrounds affect the new design, or stop using the blurring.

Personally, I much more notice it when it makes the room list look inconsistent (when the tint at the top is different at the bottom, it distracting me) than when it "adds flair".

### Additional context

https://github.com/vector-im/element-web/issues/20178

**Comment by t3chguy** [comment] 2021-12-14 11:49
Duplicate of https://github.com/vector-im/element-web/issues/14665

**Closed by t3chguy** 2021-12-14 11:49 UTC
Labels: T-Enhancement
