### ISSUE TITLE
I did a thread and it went wrong for Travis (maybe other folks too?)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#23249] opened 2022-09-09 15:03 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
I made a thread and typed lots of messages in it

### Outcome

The thread looked good for me, but for Travis it looked like a giant pile of replies.

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2022090801 Olm version: 3.2.12

### How did you install the app?

website

### Homeserver

lant.uk

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-09-10 03:19
I'm pretty sure Travis has the threads beta disabled, and is looking at the fallbacks?

**Comment by robintown** [comment] 2022-09-12 02:12
@turt2live Could you confirm?

**Comment by turt2live** [comment] 2022-09-12 03:05
yes, this is the fallbacks. The sending client appeared to use the thread root as the fallback for every message, which made the history unusable.

**Comment by t3chguy** [comment] 2022-09-12 08:43
Duplicate of https://github.com/vector-im/element-web/issues/23147

**Closed by t3chguy** 2022-09-12 08:43 UTC
Labels: T-Defect, S-Minor, O-Uncommon, A-Threads
