### ISSUE TITLE
Uploading files with special characters fails

### ISSUE THREAD

**Issue by QEDeD** [vector-im/element-web#20682] opened 2022-01-22 12:58 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Try to attach/share/upload a file in any type of room 

2. What do you click?
Upload file, pick a file with a file name containing an æ, ø or å

![image](https://user-images.githubusercontent.com/16562457/150639062-4709a2e0-2799-446b-9f33-d7cfe7a5e269.png)

#### What did you expect?
File with common character
![image](https://user-images.githubusercontent.com/16562457/150639028-cdc9377d-34c8-40a8-ba83-2adeaca7ebec.png)

#### What happened instead?
File with special character
![image](https://user-images.githubusercontent.com/16562457/150639073-31b17655-fe4c-4c36-a5ec-4d90167fe4cb.png)

![image](https://user-images.githubusercontent.com/16562457/150639077-c3c6d27c-6598-4691-a530-2ab1c913808d.png)

### Operating system

PopOS

### Application version

Element version: 1.9.9 Olm version: 3.2.8

### How did you install the app?

Flatpak

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2022-01-23 07:44
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19703

**Closed by SimonBrandner** 2022-01-23 07:44 UTC
Labels: T-Defect
