### ISSUE TITLE
Replying with /plain doesn't send a reply

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#15118] opened 2020-09-08 13:31 UTC
When replying with `/plain [message]` and sending, Element sends the text as a normal message rather than as a reply to the selected message.

![Peek 2020-09-08 14-29](https://user-images.githubusercontent.com/5547783/92482756-e201ef00-f1df-11ea-951d-ae188f350e1d.gif)

**Comment by turt2live** [comment] 2020-09-08 13:34
Duplicate of https://github.com/vector-im/element-web/issues/11170

**Closed by turt2live** 2020-09-08 13:34 UTC
Labels: bug
