### ISSUE TITLE
Kebab menu on space names causes jitter on hover

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#21140] opened 2022-02-21 14:13 UTC
### Steps to reproduce

1. Open the spaces panel
2. Hover over space names. This seems to be reproducible when the longest top level space name is short enough to not be truncated, but long enough that name + kebab > max width of the space panel

https://user-images.githubusercontent.com/3055605/154970650-60ddc43b-84f5-43fa-b7f0-4f5bd3f7bc3e.mov

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-02-21 14:41
Duplicate of https://github.com/vector-im/element-web/issues/19891

**Closed by t3chguy** 2022-02-21 14:41 UTC
Labels: T-Defect
