### ISSUE TITLE
Send button

### ISSUE THREAD

**Issue by Yajo** [vector-im/element-web#16010] opened 2020-12-21 08:56 UTC
### Description

There's no send button:
![image](https://user-images.githubusercontent.com/973709/102758159-3cc3ee80-436a-11eb-9179-0dd9d9286586.png)

When responding with an emoji, for example, this is very uncomfortable.

### Version information

- **Platform**:  desktop
- **OS**: Fedora 33 Silverblue
- **Version**: 1.7.15

**Comment by SimonBrandner** [comment] 2020-12-22 19:26
If this were to be implemented, there should definitely be a way to hide it

**Comment by t3chguy** [comment] 2020-12-29 13:08
Duplicate of https://github.com/vector-im/element-web/issues/4963

**Closed by t3chguy** 2020-12-29 13:08 UTC
Labels: suggestion, ui/ux
