### ISSUE TITLE
Autofocus switches from composer to widget in room with pinned widget

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20923] opened 2022-02-04 18:21 UTC
### Steps to reproduce

1. have a room with pinned widget that accepts kb input such as etherpad
2. switch to another room
3. switch back to widget room
4. while the widget is sill loading, start typing in the composer

#### What did you expect?
type in composer

#### What happened instead?
after the widget loads i continue typing in there

### Operating system

arch

### Application version

Element Nightly version: 2022020401 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.51

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-02-04 18:22
There's no way to prevent an iframe stealing focus

Duplicate of https://github.com/vector-im/element-web/issues/5130

**Closed by t3chguy** 2022-02-04 18:22 UTC
Labels: T-Defect
