### ISSUE TITLE
Notifications in a room randomly count up/increase rapidly into the hundreds

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#26233] opened 2023-09-25 08:29 UTC
### Steps to reproduce

![image](https://github.com/vector-im/element-web/assets/1342360/3f3854b2-707c-4b07-a4c2-5bb5816735aa)

1. I just reacted to a message (`$WJzFKTbNzdJinMruXbF9wZWsQIO_vG2846W6kdm7q8A`) in a room (`!SGNQGPGUwtcPBUotTL:matrix.org`)
2. I then clicked on another room (`!FUJJvSifWMeoTfRUzN:littlevortex.net`)
3. The notifications count in the original room started counting up rapidly from nothing (0) to 161.
4. After a few tens of seconds, the notification count disappeared again, back down to 0.

![image](https://github.com/vector-im/element-web/assets/1342360/9e084b16-fe17-40ea-ad61-43b845ec8288)

There were no new events sent in the room from the point of my reaction. Not even hidden events.

![image](https://github.com/vector-im/element-web/assets/1342360/4b77e129-296e-4034-9582-7f238a88d26b)

The contents of my reaction event:

```json
{
    "content": {
        "m.relates_to": {
            "event_id": "$WJzFKTbNzdJinMruXbF9wZWsQIO_vG2846W6kdm7q8A",
            "key": "🫂",
            "rel_type": "m.annotation"
        }
    },
    "origin_server_ts": 1695630298061,
    "sender": "@andrewm:element.io",
    "type": "m.reaction",
    "unsigned": {
        "age": 283,
        "transaction_id": "m1695630297783.107"
    },
    "event_id": "$6zfKLPORl3nenB13cQ5jF0hmgV8YPsDmd9a0UthO1Wo",
    "room_id": "!SGNQGPGUwtcPBUotTL:matrix.org"
}
```

#### What did you expect?

The notification count to only increase if a new message was sent in the room, and only increase by 1.

#### What happened instead?

The notification count rapidly increased to 161 (I watched it go up in rapid steps of 1), then eventually dropped again to 0 without any interaction on my part.

### Operating system

NixOS Linux

### Application version

Element version: 1.11.43, Olm version: 3.2.14

### How did you install the app?

From https://github.com/NixOS/nixpkgs/

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-10-09 07:41
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-10-09 07:41
Duplicate of https://github.com/vector-im/element-web/issues/25479

**Closed by weeman1337** 2023-10-09 07:41 UTC
Labels: T-Defect
