### ISSUE TITLE
Consenting to terms as a guest while joining a room leaves you stranded

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#14584] opened 2020-07-17 12:51 UTC
* From the login page, I clicked "Explore rooms", then tried to join HQ. That gave me a toast to review the Ts&Cs, which I did, but left me with: 
![image](https://user-images.githubusercontent.com/1389908/87786764-7419f680-c832-11ea-904c-61fdfb31b7c6.png). What do I do now? I'm certainly not in HQ, either way.
 * I went to the room explorer and clicked "Join" again. First nothing happened; then I got a room preview; eventually I got a proper view of the room. The whole process took ages and I wasn't sure if it had got stuck.

---
@jryans: These bits no longer reproduce / can't be actioned:

* I got a random "something went wrong!" popup; not exactly sure what caused it. sorry!
* attempting to sign out fails silently.

**Comment by vallode** [comment] 2020-07-17 14:30
I'm trying to switch a community I run over to riot/element and we are experience a lot of these issues too. Guest accounts in general feel like they aren't even meant to be a part of the experience right now.

From my side I've experienced:
* Inability to message anywhere (I believe this seems to be intended)
* Very inconsistent behaviour in previewing channels -> Clicking join leads to an empty screen asking for sign up (even on "guest can join" channels) where as preview actually loads the preview but doesn't offer a way to join the channel.

**Comment by anoadragon453** [comment] 2020-07-22 18:04
Additionally, when testing this, I found that navigating to http://localhost:8080/#/room/#some-room:localhost without being logged in created a guest account *on matrix.org*, even though the room only existed on my local HS, and Element's `config.json` mentioned `http://localhost:8008` as the default homeserver.

**Comment by t3chguy** [comment] 2020-07-22 18:05
Not related to #11655, that one is about Element validating its config against the well-known of the config HS (matrix.org)

**Comment by t3chguy** [comment] 2020-10-19 13:40
@anoadragon453 is it possible the guest already existed from an earlier session where your config.json was different? Can you reproduce it incognito?

I can reproduce it here. I set my config.json to riot.ovh and when loading incognito I see a failure to register a guest due to my server's guest access being disabled.

**Comment by ara4n** [comment] 2021-01-09 12:10
given fosdem wants to use guests, this could do with some urgent attention, cc @jryans

**Comment by jryans** [comment] 2021-01-15 10:48
> given fosdem wants to use guests, this could do with some urgent attention, cc @jryans

From chatting with @ara4n in more detail, it seems like FOSDEM's core use case of joining a room directly actually works okay and avoids the hoops recorded in this issue. In any case, since we're on the topic, I'll try reproducing and fixing what I find in this area.

**Comment by jryans** [comment] 2021-01-15 16:01
> Additionally, when testing this, I found that navigating to http://localhost:8080/#/room/#some-room:localhost without being logged in created a guest account _on matrix.org_, even though the room only existed on my local HS, and Element's `config.json` mentioned `http://localhost:8008` as the default homeserver.

Similar to @t3chguy, I can't replicate this issue: the guest account is created on Element's default server.

**Comment by jryans** [comment] 2021-01-15 16:30
> * Inability to message anywhere (I believe this seems to be intended)

I am not sure which path was tested here, but if you join a guests can join room, you can write in it. It's slightly unclear whether Element actually _intends_ for you to be able to join a room as a guest at the moment though, see https://github.com/vector-im/element-web/issues/16037.

> * Very inconsistent behaviour in previewing channels -> Clicking join leads to an empty screen asking for sign up (even on "guest can join" channels) where as preview actually loads the preview but doesn't offer a way to join the channel.

I can't reproduce this, please file a separate issue with more detailed steps. In my testing, "join" from the the directory joins for real, while the room preview bar wants you to register, which is another aspect of https://github.com/vector-im/element-web/issues/16037.

**Comment by jryans** [comment] 2021-01-15 16:36
> * From the login page, I clicked "Explore rooms", then tried to join HQ. That gave me a toast to review the Ts&Cs, which I did, but left me with:
>       ![image](https://user-images.githubusercontent.com/1389908/87786764-7419f680-c832-11ea-904c-61fdfb31b7c6.png). What do I do now? I'm certainly not in HQ, either way.

This is the main thing listed here that still exists (that I can replicate at least). At the moment, if you happen to need to consent to terms as a guest user to do some action (most likely joining), we do not remember what action you were trying to perform after you consent. This issue does not exist for normal (non-guest) users since require them to consent as a registration step.

> * I went to the room explorer and clicked "Join" again. First nothing happened; then I got a room preview; eventually I got a proper view of the room. The whole process took ages and I wasn't sure if it had got stuck.

This part sounds like mostly slow server performance...? I haven't been able to replicate, so a separate issue with video might be needed.

> * I got a random "something went wrong!" popup; not exactly sure what caused it. sorry!

Not sure what happened there, probably some unrelated thing.

> * attempting to sign out fails silently.

This has been "fixed" by changing the user menu to only allow "signing in as another account" if you are a guest. There is no sign out any more.

**Comment by jryans** [comment] 2021-01-15 16:40
Since the main remaining problem that still exists from this issue is part related to consent on join leaving you a bit lost, I have restructured the issue to focus on that.

**Comment by jryans** [comment] 2021-01-15 16:55
> I've noticed that it's not possible to follow an invite as guest. (Join a room as guest, get invited to DM by someone else, trying to follow this invite as guest fails.) I only found this issue that was similar so I subscribed here. Shall I create a new ticket for this?

Yes, please make a new issue, it's generally easier to track things that way, especially once fixes are in motion.

**Comment by freshprince** [comment] 2021-01-15 17:10
okay: #16164

**Comment by jryans** [comment] 2021-01-20 10:05
As of https://github.com/matrix-org/matrix-react-sdk/commit/3115c4f3f3ed0b2f1d82c5882dcce007b188c206, we have changed the room directory to only show preview buttons to guest users, so I believe this flow is no longer possible to reach. Given that, I'll close this issue.

**Closed by jryans** 2021-01-20 10:05 UTC
Labels: bug, defect, p2, severity:major, type:guestaccess
