### ISSUE TITLE
Something went wrong!

### ISSUE THREAD

**Issue by ligi** [vector-im/element-web#23902] opened 2022-12-05 04:03 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
 Seeing the HIP space
2. What do you click?
 joining multiple rooms - on the last one I got this:

![image](https://user-images.githubusercontent.com/111600/205546662-aadd5d52-bdc7-4041-843d-9a14e2bfc0b3.png)

#### What did you expect?

Joining the room

#### What happened instead?

![image](https://user-images.githubusercontent.com/111600/205546683-a288c2fa-3708-4750-9695-e2b33992dd0c.png)

### Operating system

Ubuntu

### Browser information

Brave Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)

### URL for webapp

https://app.element.io/#/room/#hip-berlin:milliways.info

### Application version

Element version: 1.11.15 Olm version: 3.2.12

### Homeserver

martix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-12-05 08:55
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-12-05 08:55 UTC
Labels: T-Defect
