### ISSUE TITLE
I would like the feature to delete/hide someones messages for ourself

### ISSUE THREAD

**Issue by ufkhf** [vector-im/element-web#20991] opened 2022-02-08 21:40 UTC
I would like the feature to delete someones messages for ourself like you can on Signal and on WhatsApp

![Delete message](https://user-images.githubusercontent.com/84050866/153080011-b24c2ced-b7e5-441d-8bdb-a00fcce57b43.png)

**Comment by SimonBrandner** [comment] 2022-02-09 07:07
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/5649

**Closed by SimonBrandner** 2022-02-09 07:07 UTC
