### ISSUE TITLE
Soft-crash on logout

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#12753] opened 2020-03-17 09:43 UTC
Rageshake: https://github.com/matrix-org/riot-web-rageshakes/issues/2405

MatrixClient is missing right after login ...
```
2020-03-16T09:58:47.793Z I Routing URL  https://riot.ensimag.fr/#/login
2020-03-16T09:58:47.809Z I newscreen login
2020-03-16T09:58:53.938Z I Overrode homeserver setting with https://matrix.ensimag.fr/ from login response
2020-03-16T09:58:53.941Z I Updating homeserver-configured integration managers...
2020-03-16T09:58:53.942Z E Cannot read property 'credentials' of null
TypeError: Cannot read property 'credentials' of null
    at e.value (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:1:89674)
    at e.<anonymous> (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:12:66428)
    at E (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:19:91871)
    at Generator._invoke (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:19:91659)
    at Generator.forEach.e.<computed> [as next] (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:19:92051)
    at Generator.c (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:1:81419)
    at f._promiseFulfilled (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:1:38290)
    at e.<anonymous> (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:1:40317)
    at e.<anonymous> (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:12:67597)
    at e.value (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:12:65854)
    at new e (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:12:65123)
    at Function.value (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:12:65252)
    at Z (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:19:143422)
    at Object.t.setLoggedIn [as onLoggedIn] (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:19:139514)
    at https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:94:193276
    at c (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:1:81419)
2020-03-16T09:58:53.943Z I setLoggedIn: mxid: <redacted user id> deviceId: QPXGVEBCGI guest: false hs: https://matrix.ensimag.fr/ softLogout: false
2020-03-16T09:58:53.950Z I Removing indexeddb instance: matrix-js-sdk:crypto
2020-03-16T09:58:53.955Z I Removed indexeddb instance: matrix-js-sdk:crypto
2020-03-16T09:58:54.177Z I IndexedDB worker is ready
2020-03-16T09:58:54.180Z I Deleted indexeddb data.
```

and right before logout ... (causing a soft-crash)

```
2020-03-16T13:55:41.460Z I stopping MatrixClient
2020-03-16T13:55:41.460Z I SyncApi.stop
2020-03-16T13:55:41.461Z I stopping OutgoingRoomKeyRequestManager
2020-03-16T13:55:41.466Z I Removing indexeddb instance: matrix-js-sdk:crypto
2020-03-16T13:55:41.467Z I Sync no longer running: exiting
2020-03-16T13:55:41.475Z E Cannot read property 'isGuest' of null
TypeError: Cannot read property 'isGuest' of null
    at t.render (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:41:426586)
    at ya (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:65582)
    at va (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:65377)
    at Zs (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:99683)
    at qs (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:83963)
    at Gs (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:80988)
    at Ms (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:79559)
    at https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:41813
    at t.unstable_runWithPriority (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:67:3884)
    at po (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:41541)
    at _o (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:41758)
    at go (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:41693)
    at Pe (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:109447)
    at Un (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:31680)
    at Bn (https://riot.ensimag.fr/bundles/2399aff5932e52cc7d90/bundle.js:59:31397)
2020-03-16T13:55:41.485Z E Cannot read property 'isGuest' of null
```

**Comment by bwindels** [comment] 2020-03-17 10:04
Just a hunch, but could this be `TopLeftMenu.render`?

**Comment by bwindels** [comment] 2020-03-17 10:27
Not sure which component's `render` method this is occurring in. `stopping MatrixClient` in the log seems to imply that `Lifecycle.stopMatrixClient` is already running. By then,  `on_logged_out` should have been (sync) dispatched, and MatrixChat should have switched to the login view already, so only a small set of components can be rendered, and all seem to be checking if there is a client at first sight.

**Comment by jryans** [comment] 2020-03-17 10:36
Hmm, yeah, most such issues like this have historically been fixed by testing for the client existence...

**Comment by MadLittleMods** [comment] 2022-10-14 22:51
Duplicate of https://github.com/vector-im/element-web/issues/11149 which looks resolved ✅

**Closed by MadLittleMods** 2022-10-14 22:51 UTC
Labels: T-Defect, S-Major, Z-Soft-Crash, A-Logout, O-Uncommon
