### ISSUE TITLE
Element unresponsive in quiet rooms when status changes are hidden

### ISSUE THREAD

**Issue by grisu48** [vector-im/element-web#17503] opened 2021-05-30 09:45 UTC
### Description

The Element Web UI and Desktop Application become unresponsive when displaying a very quiet room with disabled status changes, i.e.:

* Disabled: Show join/leave messages (invites/kicks/bans unaffected)
* Disabled: Show avatar changes
* Disabled: Show display name changes

In a quiet room, i.e. a room with almost no text messages but plenty of those status messages (join/leave, avatar changes, display name changes) Element becomes unresponsive/hangs itself, when the above mentioned preferences are applied.
In my case the affected room is [#dendrite-alerts:matrix.org](https://matrix.to/#/#dendrite-alerts:matrix.org) but I notice a noticeable slowdown also on other rooms with those settings in place.

Here is a screenshot of how the room typically looks.

![image](https://user-images.githubusercontent.com/1527829/120099466-e38f9080-c13b-11eb-93a6-d56044dbbff5.png)

### Steps to reproduce

* Join [#dendrite-alerts:matrix.org](https://matrix.to/#/#dendrite-alerts:matrix.org)
* Disable: Show join/leave messages (invites/kicks/bans unaffected)
* Disable: Show avatar changes
* Disable: Show display name changes
- Go another room, then go back to the affected room

Describe how what happens differs from what you expected.

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) and desktop

For the web app:

- **Browser**: Firefox 78 and 88
- **OS**: openSUSE Leap 15.2 and openSUSE Tumbleweed
- **URL**: app.element.io

For the desktop app:

- **OS**: openSUSE Leap and Tumbleweed
- **Version**: 1.7.26, olm 3.2.1 (current version from [flathub.org](https://flathub.org/apps/details/im.riot.Riot))

**Comment by t3chguy** [comment] 2021-06-01 08:13
Duplicate of https://github.com/vector-im/element-web/issues/7015

**Closed by t3chguy** 2021-06-01 08:13 UTC
Labels: T-Defect
