### ISSUE TITLE
Sending larger files peer-to-peer using WebRTC / BitTorrent / etc

### ISSUE THREAD

**Issue by AnisTaluqdar** [vector-im/element-web#19399] opened 2021-10-14 14:45 UTC
### Your use case

Is it possible to use peer to peer filesharing without having to use the servers?

**Comment by t3chguy** [comment] 2021-10-14 15:16
Duplicate of https://github.com/vector-im/element-web/issues/6834

**Closed by t3chguy** 2021-10-14 15:16 UTC
Labels: A-Media, T-Enhancement, A-File-Upload, A-File-Download, X-Spec-Changes, O-Uncommon
