### ISSUE TITLE
Room Settings - Rules and Permissions freezes and slowdown

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24133] opened 2023-01-01 09:54 UTC
**Describe the bug**

**To Reproduce**
1. Go to Room setting, Rules and permission
2. Waiting for result or try to change call event option
3. Watch you CPU and RAM loading

**Expected behavior**
No higher loading and works well.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 7 64-bit
 - Version 1.11.17

**Additional context**

**Comment by JeanPaulLucien** [comment] 2023-01-03 07:50
Oh, has moved from Desktop to Web. Well. I know reason now. Desktop app has not UI.

**Comment by SimonBrandner** [comment] 2023-01-03 07:53
> Oh, has moved from Desktop to Web. 

Yep, we keep all issues at element-web since element-desktop uses its code 

> Well. I know reason now. 

Reason for what?

> Desktop app has not UI.

I am not sure I understand what you mean?

**Comment by JeanPaulLucien** [comment] 2023-01-03 08:42
To reproduce possible you need:
1. Internet connection 6 mbits/s or less
2. Should be far away from server for ping 120 ms or more
3. Limit avaliable RAM (see my Memory leak issue), stay 3 GB RAM free and launch Element Desktop.

> Reason for what?

Reason for issue. Because UI is not a local file(s), but instructions (html, css, js) from the web server. UI loads (comletes) from the server each time when user opens Rules and Permissions (and many others menus). Javascript is the reason. Any QT will be faster.

**Comment by andybalaam** [comment] 2023-01-03 09:37
Closing on the basis that this is caused by a slow Internet connection. If you have evidence that there is another cause, please re-open this issue. Thank you!

**Closed by andybalaam** 2023-01-03 09:37 UTC
Labels: T-Defect, A-Performance, X-Cannot-Reproduce, S-Minor, A-Room-Settings, O-Uncommon, A-Power-Levels

**Comment by JeanPaulLucien** [comment] 2023-01-03 13:06
> Closing on the basis that this is caused by a slow Internet connection. If you have evidence that there is another cause, please re-open this issue. Thank you!

Oh, It's internet connection to watch Youtube 480p, but not for Element? Bad joke.

**Comment by JeanPaulLucien** [comment] 2023-01-04 16:19
@andybalaam

**Comment by andybalaam** [comment] 2023-01-05 16:10
@JeanPaulLucien are you suggesting we re-implement the application as a Qt app? If so, I would suggest using a different app, such as [Fractal](https://wiki.gnome.org/Apps/Fractal) or [NeoChat](https://apps.kde.org/en-gb/neochat/).

If you think this issue is caused by a bug, and not just waiting for information to download from the Internet, please could you use the profiler in your browser's developer tools to grab some information that would help us figure out what the cause is?
