### ISSUE TITLE
Missing message in the timeline

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#21112] opened 2022-02-17 10:55 UTC
### Steps to reproduce

I'm missing a message from @novocaine in Element Web. I can see it on iOS, where I also received a push notification.

Public issue for a private rageshake.

### Outcome

To see the thing.

### Operating system

macOS

### Browser information

Chrome, latest

### URL for webapp

Develop.

### Application version

Element version: `f14450fdd2d8-react-5fe8442f44e2-js-2910e62bb68d`
Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes -> https://github.com/matrix-org/element-web-rageshakes/issues/10866

**Comment by richvdh** [comment] 2022-02-25 10:32
see also https://github.com/vector-im/element-web/issues/19156

**Comment by gaelledel** [comment] 2022-02-25 10:45
Same issue from my account where messages are sent/received on iOS but not on the web et vice versa. The issue also accounts for messages edited where the edit is done on one platform but not on the other.  The issue is present in large rooms as well as in DM communications. Web client is Chrome Version 98.0.4758.102 (Official Build) (arm64)
 - iOS 14.8.1

**Comment by turt2live** [comment] 2022-05-16 22:25
@nadonomy, @gaelledel, and others: has this happened since?

**Comment by turt2live** [comment] 2022-06-14 05:56
Closing as presumed fixed.

**Closed by turt2live** 2022-06-14 05:56 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, S-Critical, A-Timeline, Z-Rageshake, O-Uncommon
