### ISSUE TITLE
Taskbar icon settings not preserved in Windows 10 after update

### ISSUE THREAD

**Issue by mtausig** [vector-im/element-web#15691] opened 2020-11-10 08:42 UTC
### Description

By default, the taskbar icon of Element is hidden in Windows 10 an only visible once you expand the menu.
You can change this behaviour to *Always Visible* in the taskbar settings, which produces the expected result.

Unfortunately, these settings are getting lost after every update of Element.

This seems to be related to issue #10131

### Steps to reproduce

- Install Element
- Set Element as Visible (Right click on taskbar -> Taskbar Settings -> Notification Area -> *Select which icons appear on the taskbar* -> Activate Element
- The tray icon of Element appears in the notification area permanentely
- Update Element
- Element Icon is gone in the notification area
- Goto step 2

I would expect these setting to preserve. 
The Mattermost desktop client, which is based on Electron, too, does not have this problem.

![image](https://user-images.githubusercontent.com/1511226/98650131-c2e72100-2338-11eb-8778-5ee83dc7623b.png)

![image](https://user-images.githubusercontent.com/1511226/98650159-cd091f80-2338-11eb-8179-7fcff8a26b8b.png)

### Version information

- **Platform**: Desktop
- **OS**: Windows 10 Enterprise (v1909)
- **Version**: 1.7.13

**Comment by t3chguy** [comment] 2020-11-10 09:32
Duplicate of https://github.com/vector-im/element-web/issues/4601

**Closed by t3chguy** 2020-11-10 09:32 UTC
Labels: bug
