### ISSUE TITLE
** Unable to decrypt: The sender's device has not sent us the keys for this message. **

### ISSUE THREAD

**Issue by ashfaqn** [vector-im/element-web#17129] opened 2021-05-02 03:15 UTC
### Description

I just hosted a web version of Elements application. I have created two users and have generated the respective security keys. I am able to retrieve older conversations using those keys but I can't decrypt the messages received when a user is offline. It seems that I have missed to change some configuration. Need assistance here please. 

### Steps to reproduce

- send messages to an offline friend

The conversation works fine when users are online. But users should receive the offline messages as well (sent to them) after logging in. For one user session I used Chrome and for the other Safari was used.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome(Version 90.0.4430.93 ), Safari (Version 14.0.3)
- **OS**: macOS Big Sur (Version 11.2)
- **URL**:  element-v1.7.26
<img width="1094" alt="Screen Shot 2021-05-02 at 6 58 34 AM" src="https://user-images.githubusercontent.com/13698649/116800925-4e868100-ab16-11eb-81ad-fc9961484080.png">

**Comment by ashfaqn** [comment] 2021-05-02 03:16
<img width="1094" alt="Screen Shot 2021-05-02 at 6 58 34 AM" src="https://user-images.githubusercontent.com/13698649/116800920-40d0fb80-ab16-11eb-8e55-4f0ba2c45b8a.png">

**Comment by pfdint** [comment] 2021-05-02 18:19
This is #16986

**Comment by jryans** [comment] 2021-05-04 13:48
@ashfaqn What does "offline" mean here? Temporarily disconnected from the network, or you logged out from all active sessions...?

**Comment by ashfaqn** [comment] 2021-05-05 01:05
> @ashfaqn What does "offline" mean here? Temporarily disconnected from the network, or you logged out from all active sessions...?

It means that user is logged out.

**Comment by aaronraimist** [comment] 2021-05-05 02:22
@ashfaqn It is normal that they cannot decrypt messages sent while they were logged out of all of their devices. That's just how encryption works. They are working on device dehydration which may allow for that in the future but right now that is an experimental feature. Closing as a duplicate of #10243 and #16986.

**Closed by aaronraimist** 2021-05-05 02:22 UTC
Labels: A-E2EE, T-Defect
