### ISSUE TITLE
Black window when starting in a Gnome on Wayland session

### ISSUE THREAD

**Issue by jakobkmar** [vector-im/element-web#19743] opened 2021-11-13 14:28 UTC
### Steps to reproduce

Hardware specs:
![image](https://user-images.githubusercontent.com/52456572/141647230-d2bfb940-31e3-4d23-84a0-6ab69bb64485.png)

The problem only appears on Wayland.

#### What did you expect?
The application should be visible.

#### What happened instead?
Only a black window is visible.

![image](https://user-images.githubusercontent.com/52456572/141647280-691ee607-d94e-4084-a14d-82ba69a2bb82.png)

**Logs**

<details>
<summary>Logs when starting element</summary>

```js
➜  flatpak run im.riot.Riot
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Element/element-desktop --type=zygote
/home/jakob/.var/app/im.riot.Riot/config/Element exists: yes
/home/jakob/.var/app/im.riot.Riot/config/Riot exists: no
Gtk-Message: 15:25:39.487: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:25:39.488: Failed to load module "pk-gtk-module"
Gtk-Message: 15:25:39.488: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:25:39.488: Failed to load module "pk-gtk-module"
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /app/Element/resources/app.asar/lib/language-helper.js
- /app/Element/resources/app.asar/lib/tray.js
- /app/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/app/Element/resources/app.asar/lib/language-helper.js:76:20)
    at /app/Element/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/app/Element/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/Element/resources/app.asar/lib/language-helper.js',
    '/app/Element/resources/app.asar/lib/tray.js',
    '/app/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Failed to establish dbus connectionResetting the UI components after locale change
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /app/Element/resources/app.asar/lib/language-helper.js
- /app/Element/resources/app.asar/lib/tray.js
- /app/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/app/Element/resources/app.asar/lib/language-helper.js:76:20)
    at /app/Element/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/app/Element/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/Element/resources/app.asar/lib/language-helper.js',
    '/app/Element/resources/app.asar/lib/tray.js',
    '/app/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
```

</details>

### Operating system

Fedora Linux 35 (Workstation Edition)

### Application version

Element version 1.9.4

### How did you install the app?

I tried both `dnf` and flatpak from Flathub.

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2021-11-13 14:32
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue. Could you also please copy over the logs there? Thank you

Duplicate of https://github.com/vector-im/element-web/issues/15486

**Comment by jakobkmar** [comment] 2021-11-13 14:34
Yes I can do that, but isn't this right here a different issue? The problem only appears on Wayland, while starting the same application on the same system in an XOrg session works perfectly fine.

**Comment by SimonBrandner** [comment] 2021-11-13 14:36
Ah, sorry, I misread the issue, seems different

**Comment by SimonBrandner** [comment] 2021-11-13 14:39
@jakobkmar, does this happen with other Electron apps (Discord, Slack...)?

**Comment by jakobkmar** [comment] 2021-11-13 14:52
No, Discord and Spotify work fine.

**Comment by jakobkmar** [comment] 2021-11-13 17:22
> does this happen with other Electron apps (Discord, Slack...)?

while some electron apps don't have this issue (previous message), there are other electron with this issue, e.g. GitHub Desktop

**Comment by novocaine** [comment] 2021-11-15 07:19
Are you passing the extra flags noted in https://github.com/vector-im/element-web/issues/18902 ?

**Comment by jakobkmar** [comment] 2021-11-15 10:34
No, but I did try it now and the result is that the window is invisible.

**Comment by novocaine** [comment] 2021-11-16 00:28
There's an existing ticket tracking Element not working in Fedora 35 here, with a suggested workaround: https://github.com/taw00/element-rpm/issues/50 - not sure if that would help you

**Closed** 2021-11-16 00:38 UTC
Labels: T-Defect, Z-Platform-Specific, S-Critical, A-Electron, O-Uncommon

**Comment by jakobkmar** [comment] 2021-11-16 15:47
> Let's track this as a duplicate of #19743

Seems like this link is incorrect, what is the correct one?

**Comment by novocaine** [comment] 2021-11-16 23:48
> > Let's track this as a duplicate of #19743
> 
> Seems like this link is incorrect, what is the correct one?

Sorry, should be https://github.com/vector-im/element-web/issues/18943
