### ISSUE TITLE
Create Local Password For Externally Authenticated User

### ISSUE THREAD

**Issue by jvincze84** [vector-im/element-web#25985] opened 2023-08-17 10:14 UTC
### Steps to reproduce

1. Singup a new user with external authentication provider (example google)
2. The "password_hash" will be "null" in the database.
3. You won't be able to do any action which needs the password.  (For example: "Set up Secure Backup")

### Outcome

Externally authenticated users should be able to change their password.

### Operating system

Linux (Kubernetes)

### Browser information

Opera One(version: 101.0.4843.43)

### Application version

Element version: 1.11.32 Olm version: 3.2.14

### Homeserver

matrixdotorg/synapse:v1.85.2

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-08-17 10:42
Duplicate of https://github.com/vector-im/element-meta/issues/417

**Closed by t3chguy** 2023-08-17 10:42 UTC
Labels: T-Defect
