### ISSUE TITLE
[Design] Hidden sticky day headers in element

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20142] opened 2021-12-10 19:34 UTC
### Your use case

This enhancement could sum up two of my concerns;
- Date indicators are always hidden until you've been scrolled up "enough"
- https://github.com/matrix-org/matrix-react-sdk/pull/7317 could be useful in all cases

What i'm asking for is something like the following;

Have date headers stick to the top of the page, but scroll with the timeline itself if a user scrolls up.

Have these headers hidden until the mouse comes within the 1/4th or 1/3th top part of the screen, after which they show up.

This could allow a date-jump from any view in the timeline, and would allow me to see which date something was by adjusting my mouse to the top of the screen.

**Comment by t3chguy** [comment] 2021-12-10 23:33
Duplicate of https://github.com/vector-im/element-web/issues/7575

**Closed by t3chguy** 2021-12-10 23:33 UTC
Labels: T-Enhancement
