### ISSUE TITLE
Mark a message as unread

### ISSUE THREAD

**Issue by rbignon** [vector-im/element-web#21588] opened 2022-03-29 06:34 UTC
#### What would you like to do?

As in slack, it would be interesting to mark a message as don't read,. It would be interesting too to implement the same feature than slack  “remind me later” with a custom delay.

#### Why would you like to do it?

Sometimes we receive a message but we would like to reply later.

#### How would you like to achieve it?

As the read mark is attached only on a single event, I guess the “unread” status may not be related to a single message, but the read mark may be moved back to the specific event.

For the “remind me later” feature, I think it is not supported by the matrix server, but perhaps it would be implemented only client-side.

### Have you considered any alternatives?

There is no alternative.

**Comment by gsouquet** [comment] 2022-03-29 07:12
Duplicate of https://github.com/vector-im/element-web/issues/4406

**Closed by gsouquet** 2022-03-29 07:12 UTC
Labels: T-Enhancement
