### ISSUE TITLE
provide better feedback when inviting somebody that is already in the room

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#15044] opened 2020-08-26 08:23 UTC
Currently looks like this 
![image](https://user-images.githubusercontent.com/274386/91280023-be698e00-e775-11ea-897f-ed7e4a16178a.png)

**Comment by t3chguy** [comment] 2020-08-26 08:40
Duplicate of https://github.com/vector-im/element-web/issues/12281

**Closed by t3chguy** 2020-08-26 08:40 UTC
