### ISSUE TITLE
Caps lock blocks `ctrl+k` for search

### ISSUE THREAD

**Issue by NukeManDan** [vector-im/element-web#23681] opened 2022-11-02 09:45 UTC
### Steps to reproduce

caps lock on, `ctrl+k`

### Outcome

Without caps lock things work fine, I see no reason not to have both `ctrl+k` and `ctrl+K` both work for search, or if possible to detect specifically if caps lock is on so `ctrl + shift+ k` could be mapped to another command/

### Operating system

Pop!_OS

### Will you send logs?

No

**Comment by MadLittleMods** [comment] 2022-11-29 05:00
Duplicate of https://github.com/vector-im/element-web/issues/23399

**Closed by MadLittleMods** 2022-11-29 05:00 UTC
Labels: T-Defect, S-Minor, A-Shortcuts, O-Occasional, A-New-Search-Experience
