### ISSUE TITLE
The sidebar is not able to collapse properly.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [vector-im/element-web#19098] opened 2021-09-19 21:55 UTC
### Steps to reproduce

1. Drag the sidebar left-ward to collapse it so that its width shall span one column.

### What did you expect?
The side-bar should be displayed correctly.

### What happened?
http://user-images.githubusercontent.com/42837531/133940420-fbf9f0a3-21b7-487b-b637-8a27ee8876ba.PNG

### Operating system

http://silverblue.fedoraproject.org

### Browser information

Commit 70d4e9d5db28869aaacdc30b5008766135167119af4c502a45b3ab6768455a6d of app/org.mozilla.firefox/x86_64/stable from http://dl.flathub.org/beta-repo/appstream/org.mozilla.firefox

### URL for webapp

//APP.ELEMENT.IO

### Homeserver

//MATRIX.ORG

### Have you submitted a rageshake?

No

**Comment by robintown** [comment] 2021-09-19 23:43
Duplicate of https://github.com/vector-im/element-web/issues/17068

**Closed by robintown** 2021-09-19 23:43 UTC
Labels: T-Defect
