### ISSUE TITLE
Widget fullscreen UX feels like a toggle, but isn't (resulting in **suprise**)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#21683] opened 2022-04-05 13:27 UTC
#### What would you like to do?
I would like to:
- click the two diagonal arrows to open the widget full screen
- click it _again_ to go back to pinned

Instead I click it again and it disappears! And I am surprised.

### Additional context

This feedback has been echoed by a customer, too.

**Comment by jryans** [comment] 2022-04-05 15:13
Yes, this is effectively the same as https://github.com/vector-im/element-web/issues/20506. We tried to improve this somewhat in https://github.com/matrix-org/matrix-react-sdk/pull/7734 by explicitly showing both maximise and pin actions, but perhaps it's not enough.

To summarise the current state, at the moment, "pinned" and "maximised" are really locations a widget moves to (as opposed to independent flags), so when you maximise, the widget has no knowledge that it used to be pinned.

@lampholder, did you notice the separate pin button which would have pinned it? It might be best to transform this report into an additional feedback comment on https://github.com/vector-im/element-web/issues/20506.

**Comment by andybalaam** [comment] 2022-04-20 13:55
I think this is a duplicate of #20506. @lampholder if you disagree, please re-open.

**Closed by andybalaam** 2022-04-20 13:55 UTC
Labels: T-Defect, X-Needs-Info, S-Tolerable, A-Widgets, O-Occasional, Z-Maximised-Widgets

**Comment by tmissoni** [comment] 2022-05-12 07:39
The same button should maximise and minimise (bring back to the original state) the Widget. The Pin button should pin it and unpin it from the room. 
The maximise button cannot become a close button all of a sudden.
