### ISSUE TITLE
Markdown ignored if it's after something that looks like a URL

### ISSUE THREAD

**Issue by reivilibre** [vector-im/element-web#20082] opened 2021-12-07 10:30 UTC
### Steps to reproduce

Send a message of the form `matrix.org **test**` and notice that bold doesn't get applied.

<img width="241" alt="image" src="https://user-images.githubusercontent.com/38398653/145012556-e255aa66-f2d5-4416-aed2-f4b04f64e8f4.png">

Possibly a regression caused by an attempt to fix #4674?

#### What did you expect?

Bold

#### What happened instead?

No bold

### Browser information

Firefox

### URL for webapp

https://develop.element.io

### Application version

Element version: b0abbfacd48b-react-26297f549827-js-b7247fcedc4d Olm version: 3.2.3

### Homeserver

librepush.net

### Will you send logs?

No

**Comment by gsouquet** [comment] 2021-12-08 08:52
Duplicate of https://github.com/vector-im/element-web/issues/20091

**Closed by gsouquet** 2021-12-08 08:52 UTC
Labels: T-Defect
