### ISSUE TITLE
The user receives a vague error when they've sent a message that is above the message character limit

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#23765] opened 2022-11-14 16:53 UTC
### Steps to reproduce

1. In a room, send a message with a lot of text. Here's a [pre-prepared example](https://gist.githubusercontent.com/anoadragon453/a7f1029b8f526391cb71f0a02ec216bf/raw/a7ab486f620f4332e57c1d4a98e422441654e1ce/lots-of-words.txt) you can copy and paste.
2. Notice a vague "Some of your messages have not been sent" error banner appear, with the subtext "You can select all or individual messages to retry or delete".
3. The user's first instinct is to click "Retry", but this will fail, as the message limit won't have suddenly gotten higher. They may do so again for a few times before becoming frustrated and assume that the service is broken. In reality, their message is just too long.

The behaviour differs slightly in an encrypted vs. unencrypted room. In an unencrypted room, clicking retry all will at least make the UI refresh for a moment while it attempts to send the message to the homeserver. The homeserver will return a HTTP 413 / `M_TOO_LARGE`. Element will then refresh the error banner.

In an encrypted room, clicking the Retry buttons will appear to do nothing, leading to the assumption that the button is broken. In reality, the crypto layer is now the one that is (silently) blocking the message from being sent. Opening up the JS console, one will see:

```
Error sending event Error: Message too long (104200 bytes). The maximum for an encrypted message is 49152 bytes.
    at checkPayloadLength (vector://vector/webapp/bundles/7eb9a34c4713eb085ec4/init.js:109058:17)
    at OlmDevice.encryptGroupMessage (vector://vector/webapp/bundles/7eb9a34c4713eb085ec4/init.js:109801:5)
    at MegolmEncryption.encryptMessage (vector://vector/webapp/bundles/7eb9a34c4713eb085ec4/init.js:111025:39)
    at async Crypto.encryptEvent (vector://vector/webapp/bundles/7eb9a34c4713eb085ec4/init.js:29509:30)
    at async Promise.all (index 0)
```

#### What did you expect?

In both of the above cases, the user should instead be presented with a clear error that the cause of their message not being sent is that it is too long. UI-wise, I think it'd be best if the user was not able to send their message at all.

Discord handles this by showing a red, negative character count in the corner once you go over the limit (with a suggestion to pay them money).

![image](https://user-images.githubusercontent.com/1342360/201717142-4be80a1d-af58-4e52-896f-59867f22e9eb.png)

#### What happened instead?

The user does not know why their message failed to send, and has no clear action for what to do about it.

#### Other notes

This behaviour also subtlety emerges when editing a long message. If you have a message that's slightly below the character limit ([example](https://gist.github.com/anoadragon453/7d0d741f0d0ee560ecdaf17600ea98dd)), and then edit it. The extra metadata that goes into the edit event will go over the message limit. Thus you are able send a message, but not edit it. In this case, even a "your message is too long" error is confusing, because _even if I delete a couple characters in my edit, the message is for some reason too long when it wasn't a second ago??_

It would be nice to handle this in an elegant manner, though I have to defer to design on how to communicate "edited messages require more characters that a non-edited message" to users.

### Operating system

Arch Linux

### Application version

Element version: 2022111401 Olm version: 3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-11-14 16:56
Duplicate of https://github.com/vector-im/element-web/issues/17663

**Closed by t3chguy** 2022-11-14 16:56 UTC
Labels: T-Defect
