### ISSUE TITLE
The fact filtering doesn't search all spaces is super confusing

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16998] opened 2021-04-19 12:59 UTC
The Home Space contains only orphaned rooms (which feels rather weird in its own right, as Home is generally where you find your most familiar things, not lost orphans).  This is made even more confusing by filtering only searching the currently selected space, as you now have to go through clicking on all possible spaces in order to locate a given room :/

**Comment by ara4n** [comment] 2021-04-19 13:00
one solution could be to have filtering search all spaces.

another solution could be to have a 'show everything' space still (which I thought we had in the designs, in fact - either by deselecting all spaces, or selecting a global one).

**Comment by jryans** [comment] 2021-04-19 13:19
I am also finding this very confusing... It's enough to make me want to disable the Spaces labs flag at the moment... 😭 I am so used to finding any room by filtering, but at moment I have to "guess" which spaces it might be in, then filter, which is infuriating.

I have no preference on whether it's Home space or some new Everything space, but please let's perserve some way to filter across all rooms.

**Comment by SimonBrandner** [comment] 2021-04-19 15:39
This is basically a dupe of these: [#16683](https://github.com/vector-im/element-web/issues/16683), [#16974](https://github.com/vector-im/element-web/issues/16974) and [#16847](https://github.com/vector-im/element-web/issues/16847)...

**Comment by niquewoodhouse** [comment] 2021-04-20 11:28
> at the moment I have to "guess" which space it might be in first, then filter, possibly get it wrong and retry, which is infuriating.

Hey @jryans that's really interesting, would you mind describing a bit more the scenario where you're guessing which space a room is in?  Eg - Is it a room for work and you have 6 spaces to do with work?  I just want to make sure I understand your scenario - not suggesting this is not a problem to fix.  Thanks

**Comment by jryans** [comment] 2021-04-20 11:56
> Hey @jryans that's really interesting, would you mind describing a bit more the scenario where you're guessing which space a room is in? Eg - Is it a room for work and you have 6 spaces to do with work? I just want to make sure I understand your scenario - not suggesting this is not a problem to fix. Thanks

For whatever reason, I'd like to switch to some room, let's say Matrix HQ for example. In the pre-Spaces world, there is a simple process I can always follow for any room I have joined: go to the filter bar type "hq" and select the room. At the moment, I have several spaces for related Matrix-themed topics, and those several spaces might include HQ or they might not.

In the current Spaces implementation, filtering seems to only act on a "bifurcated" view of the world. There is currently no single place to search all my rooms. So, now before searching for "hq", I have to first play a game: "Is Matrix HQ part of some space? If yes, which one?" For filtering to work, I first have to play a memory game of remembering which space a room is in, and select the correct space before I can filter for the room. If it is not in any of my spaces, I can search for it when Home is selected, but I also have to remember correctly that the room is _not_ in a space for that to work, so either way I have to remember the answer correctly. If there were some view that allowed searching across all rooms, these new challenges would not exist.

Jumping to room by room name is a critical workflow for me, and at the moment the Spaces implementation makes it much harder. I effectively now have to play a strange "memory mini-game" of trying to recall if each room might or might not be in a space first before trying to filter.

**Comment by niquewoodhouse** [comment] 2021-04-20 12:35
> one solution could be to have filtering search all spaces.

This is something that has come up as an option a few times in the [feedback room](https://matrix.to/#/!LPqOcoJQuGkweiTedq:riot.ovh/$lHGNtepwz4-S156tAQdbJDV-BC1xoFcsZ11KJhp0FRQ?via=matrix.org&via=dendrite.matrix.org&via=riot.ovh) and the other issues referenced above.  For me, it seems like the best choice for the user because alternatives like having to potentially change which space is selected is more work.  

It was mentioned in the spaces feedback room that this already exists in nehko + gomuks.  I see those are other matrix clients, which means it's possible?  I think @BillCarsonFr mentioned to me that searching on element android is global by default - the search will look through all spaces - is that right @BillCarsonFr?

**Comment by ara4n** [comment] 2021-04-20 13:21
I would be v. happy for filtering to search all spaces be the solution.  The only problem I see is that the feeling of being in a specific space would be undermined - but i think that the UX improvement of "breaking out of your space" when searching (or when multi-selecting spaces in future) outweighs any downside.

Ryan's explanation in https://github.com/vector-im/element-web/issues/16998#issuecomment-823213835 is excellent and precisely matches my problem (and @jaywink's, i think).  I don't want to remember what space HQ is in, or what space i'm currently in; i just want to be able to hit Cmd-K + H + Q + Return to jump to HQ.

**Comment by niquewoodhouse** [comment] 2021-04-27 09:23
> Jumping to room by room name is a critical workflow for me, and at the moment the Spaces implementation makes it much harder.

I think if we don't make this even _slightly better in some way_ ahead of shipping a beta, I would expect a number of people who join the beta will leave it early, and possibly not return as something they've become used to just being able to do has potentially become much harder.

**Comment by ara4n** [comment] 2021-04-27 09:38
I've already had to disable spaces because of the current behaviour, so we're missing valuable dogfooding opportunity for something which should be a fairly easy fix (i.e. filter should apply across all spaces, not just the currently selected one).  We shouldn't be waiting until the next sprint to iterate on something like this which is otherwise stopping people testing the feature.

Part of the problem here seems to be a lack of clear decision making on the product side.  Both myself & Nique have made proposals, but the issue is still stuck with X-Needs-Product.

To unblock this, please can we have filtering search across all spaces, and make the change asap rather than wait until the next sprint, so people affected can get dogfooding again.

@niquewoodhouse: Ideally we might need a design to explain to the user that the filter is searching all spaces (e.g. removing the highlights ont he selected spaces or something when filtering), but this can come later.

**Comment by ara4n** [comment] 2021-04-27 10:00
The first cut of this doesn't have to be blocked design changes; they can be added asynchronously.

**Comment by t3chguy** [comment] 2021-04-27 10:01
Given that I am tied up in Beta work it might as well go through Design before then.

**Comment by ara4n** [comment] 2021-04-27 10:18
`confusing("i try to filter on a room and it doesn't show up any more and i have to hunt for it manually") >> confusing("it says i'm in the Foo space but i'm showing rooms from the Bar space")`

**Comment by niquewoodhouse** [comment] 2021-04-27 10:23
> @niquewoodhouse: Ideally we might need a design to explain to the user that the filter is searching all spaces (e.g. removing the highlights ont he selected spaces or something when filtering), but this can come later.

I briefly looked at something like this when perusing space feedback before [here](https://github.com/vector-im/element-web/issues/16974#issuecomment-824865890) -  I'd be happy to look at it in more detail.  Maybe it's simplest to just pair with an engineer on this for 1 or 2 hours - just to see what's simple to do.  Sometimes we run away a bit with designing the solution and what we design isn't going to easily fit into the current build.  Something like this, esp for a beta, feels like it would be good to bias more towards what's simplest to build and isn't the worst UX > get feedback > iterate.

**Comment by BillCarsonFr** [comment] 2021-04-27 16:42
Notice the the breadcrump that is under the filter is already showing rooms from other spaces

**Closed** 2021-04-30 11:53 UTC
Labels: A-Room-List, A-Spaces, P1, S-Major, T-Defect, X-Needs-Design
