### ISSUE TITLE
Thread preview shows root message

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#20873] opened 2022-02-02 14:41 UTC
### Steps to reproduce

All I've done is look at a room with a thread in it.

#### What did you expect?

I don't remember if the thread preview should show the latest message in the thread or the 2nd one, but I do know it should definitely not show the initial one (since it's already shown in the room's timeline).

#### What happened instead?

Thread preview:

![image](https://user-images.githubusercontent.com/5547783/152175299-f3aebf99-3c3a-433c-92a8-e94c9924abef.png)

Full thread:

![image](https://user-images.githubusercontent.com/5547783/152175335-8892173c-3420-4ca6-aa65-569a072b44d1.png)

### Operating system

Arch Linux

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 6bc7036dc824-react-75b03ca101a3-js-9c242a9ce6d9, olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by HarHarLinks** [comment] 2022-02-03 23:08
please rename to something with "root" so you can actually find this issue when searching

**Comment by babolivier** [comment] 2022-02-04 10:02
> please rename to something with "root" so you can actually find this issue when searching

Done, though ironically, given how Github's search works, your comment should have already made the issue appear in the results.

**Comment by babolivier** [comment] 2022-02-08 13:51
Reopening as I've just seen it appear on develop, with the slight catch that the username shown in the preview is correct:

![image](https://user-images.githubusercontent.com/5547783/153000327-1ba7e964-a1eb-49e3-8ab3-57c91b693b3d.png)

**Comment by HarHarLinks** [comment] 2022-02-08 13:58
> the username shown in the preview is correct:

It is not, you are mistaking the pill for the display name

**Comment by babolivier** [comment] 2022-02-08 14:18
> It is not, you are mistaking the pill for the display name

Hah, indeed, good catch

**Comment by gsouquet** [comment] 2022-02-21 15:32
@babolivier I can't reproduce this. Could you let me know whether you're still experiencing this or not?

**Comment by babolivier** [comment] 2022-02-21 17:00
I'm not, but that's mostly because I can't find a room I'm in in which a tread was created recently enough to show in the latest messages, and https://github.com/vector-im/element-web/issues/21144 prevents me from paginating to check older ones.

**Comment by HarHarLinks** [comment] 2022-02-23 21:29
![image](https://user-images.githubusercontent.com/2803622/155411541-2ddf4c05-f2ea-4777-b796-3f38de8537cf.png)

This is in #element-community-testing:matrix.org

https://matrix.to/#/!CMjQWAjoxImKwLBMzX:matrix.org/$fNHrFd14fNXLJGaSIZykPgcxWyFYh3idc2spqIYeNXM?via=matrix.org&via=element.io&via=envs.net

Element Nightly version: 2022022301
Olm version: 3.2.8

**Comment by gsouquet** [comment] 2022-03-03 15:23
I have a strong feeling this is fixed, I have not encountered this at all in a long time.
But would like confirmation from @HarHarLinks or @babolivier that this is the case

**Comment by HarHarLinks** [comment] 2022-03-03 16:05
depends if the issue is different from https://github.com/vector-im/element-web/issues/21077#issuecomment-1057871758 which is still happening today

**Comment by gsouquet** [comment] 2022-03-08 10:47
Marking as duplicate of https://github.com/vector-im/element-web/issues/21044 to have one canonical source of information

**Closed by gsouquet** 2022-03-08 10:47 UTC
Labels: T-Defect, X-Cannot-Reproduce, X-Regression, S-Minor, O-Frequent, A-Threads, Z-Labs
