### ISSUE TITLE
Etherpad pad names are limited to 50 chars ... that’s not enough and often results in broken widgets.

### ISSUE THREAD

**Issue by fooness** [vector-im/element-web#15396] opened 2020-10-06 18:59 UTC
### Description

> Such a padname is forbidden

Works: https://scalar.vector.im/etherpad/p/01234567890123456789012345678901234567890123456789

Doesn’t: https://scalar.vector.im/etherpad/p/012345678901234567890123456789012345678901234567890

Problems occur with long homeserver names/url, as the default naming scheme is `!<some_uid_maybe_roomid>.<synapse_server_name>-<optionally-manually-defined-padname>` … the longer the homeserver name, the more likely Etherpad widgets added via the integration manager won’t work.

<img width="550" alt="Screenshot 2020-10-06 at 18 13 04" src="https://user-images.githubusercontent.com/11408027/95247808-a118ec80-0816-11eb-8f10-43cc6731f06b.png">

I don’t think Etherpad is going to change this, see [here](https://github.com/ether/etherpad-lite/issues/4396), so maybe we should come up with some other naming scheme?

**Comment by turt2live** [comment] 2020-10-06 19:09
Duplicate of https://github.com/vector-im/element-web/issues/10485

**Closed by turt2live** 2020-10-06 19:09 UTC
Labels: bug
