### ISSUE TITLE
In thread "Unable to load event that was replied to, it either does not exist or you do not have permission to view it."

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#21574] opened 2022-03-28 09:14 UTC
### Steps to reproduce

1. In a room with a thread
2. Someone has replied to their own message inside the the thread

#### What did you expect?
The replied-to messages should be displayed

#### What happened instead?
The replied-to messages are missing, replaced with "Unable to load event that was replied to, it either does not exist or you do not have permission to view it."

![image](https://user-images.githubusercontent.com/76812/160366042-90150053-6df6-4a54-b7b6-046aa9b1799e.png)

### Operating system

Ubuntu 21.10

### Browser information

Firefox 98.0.2

### URL for webapp

https://develop.element.io

### Application version

Element version: 14f46a8ca994-react-a3e523187374-js-e90f12ee321a Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-03-28 09:19
Duplicate of https://github.com/vector-im/element-web/issues/21543

**Closed by t3chguy** 2022-03-28 09:19 UTC
Labels: T-Defect
