### ISSUE TITLE
Threads composer shouldn't share message content between threads

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#19875] opened 2021-11-24 10:16 UTC
I'll often start writing a thread reply and need to refer to or look at other rooms, threads etc. When I view another thread, my half-composed message appears ready to send in a _completely different thread_.

This causes alarm (e.g. if composing something sensitive) and dashes confidence in Element all round. It would be a disaster if Element showed or offered to send half composed messages in other rooms, and threads are no different.

**Comment by daniellekirkwood** [comment] 2021-11-29 14:39
I can't recreate this issue, could you ad more details please @nadonomy ?

What I do see is:
* Start Thread
* Add message (don't send)
* Navigate to different room
* Start thread in different room (don't send message)
* Go back to OG room and message is in timeline message composer, not thread composer

**Comment by kittykat** [comment] 2021-12-10 10:06
I cannot reproduce this issue either. As we haven't had any more updates, I'm going to close this issue for now - please reopen or comment with more info if you are still seeing the problem.

**Closed by kittykat** 2021-12-10 10:06 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, A-Composer, O-Occasional, A-Threads, Z-Labs
