### ISSUE TITLE
Element's crash - white window

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24678] opened 2023-02-27 11:40 UTC
### Steps to reproduce

No idea. I was in room and typed. But it's not the first time. Pervious time was when I tried to collect Profile.

#### What did you expect?
Element Desktop works well.
#### What happened instead?
Element Desktop has crashed:
1. No GUI, window with white background;
2. The general process which consumes RAM (~700 MB on the start) more then others has gone.

### Operating system

Windows 7

### Application version

1.11.23

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-02-27 12:01
Duplicate of https://github.com/vector-im/element-web/issues/21336

**Closed by t3chguy** 2023-02-27 12:01 UTC
Labels: T-Defect
