### ISSUE TITLE
Add composer shortcut to add link or link highlighted text

### ISSUE THREAD

**Issue by SethFalco** [vector-im/element-web#18887] opened 2021-09-03 11:34 UTC
#### What would you like to do?
Add a shortcut for adding links or linking highlighted text.

#### Why would you like to do it?
Often when I'm writing messages, I'll write everything up first then add links afterwards. (Usually because I'll have to navigate to the pages manually to copy the URL over.)

This is faster to do with a shortcut rather than manually formatting/inserting the `[]()` characters myself. 

#### How would you like to achieve it?
In my opinion, GitHub offers the best UX for this.

![Peek 2021-09-03 13-21](https://user-images.githubusercontent.com/22801583/131997580-65cc5eba-0cc1-4594-8371-55faa81d8e44.gif)

Normally `CTRL` + `K` would be used for adding a URL, but IMs usually use this for finding chat rooms instead.

> | Key combination | Microsoft Windows/KDE/GNOME
> |---|---
> [`CTRL` + `K`](https://en.wikipedia.org/wiki/Control-K) | Insert hyperlink (word processing)
> 
> — https://en.wikipedia.org/wiki/Control_key#Table_of_examples

The following applications utilize `CTRL` + `K` for this purpose already:
* [Thunderbird](https://www.thunderbird.net/en-US/)
* [LibreOffice](https://www.libreoffice.org/)
* [Nextcloud](https://nextcloud.com/)
* [GitLab](https://about.gitlab.com/)
* [GitHub](https://github.com/)
* [Google Docs](https://docs.google.com/)

The next thought would probably be `CTRL` + `SHIFT` + `K`, it's worth noting browsers use this to open the dev tools console, so that might bother developers/debuggers, though.

Ideally, it should be something similar to `CTRL` + `K` so it feels more consistent with other software. ^-^'

**Comment by SimonBrandner** [comment] 2021-09-03 15:23
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/11577

**Closed by SimonBrandner** 2021-09-03 15:23 UTC
Labels: T-Enhancement
