### ISSUE TITLE
Consider a thing for "we updated your app while you were gone"

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9215] opened 2019-03-19 22:12 UTC
Riot updates when you launch it regardless of platform, so it is easy to miss updates. If combined with https://github.com/vector-im/riot-web/issues/8731, we could possibly have a notification for "Hey there! Riot updated to give you A, B, and C" to help highlight features. Might not need to do this on every update (bugfixes are cool, but not super important to the end user, probably).

Other apps seem to do this with a dedicated chat room/account for the platform. For instance, there'd be a Riot room which is just a bunch of announcements from the platform. Telegram does a similar thing, and appears to special case it.

**Comment by robintown** [comment] 2022-04-25 02:00
Duplicate of https://github.com/vector-im/element-web/issues/9899

**Closed by robintown** 2022-04-25 02:00 UTC
Labels: T-Enhancement
