### ISSUE TITLE
In DM one user left room and new DM was started with no history next message

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#19079] opened 2021-09-17 10:20 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
I had a DM with Kat (kittykat). I got a notification saying kittykat has left the room. DM is now called "Empty room (was kittykat)"
2. What do you click?
I clicked on kittykat avatar and selected Message. A new DM was created with no history of our previous messages.
Went back to "Empty room (was kittykat)" and reinvited Kat to room, she joined successfully but now we have 2 DMs, one called "KittyKat" (new) and one called "Empty Room (was kittykat)"

DM room vanished for both of us. 
Marked as critical due to data loss.

### What did you expect?
For our DMs to continue with no change.

### What happened?
DM with Kat disappeared and she had "left our room"

### Operating system

macOS

### Application version

Element Nightly version: 2021091701 Olm version: 3.2.3

### Have you submitted a rageshake?

Yes

**Comment by kittykat** [comment] 2021-09-17 10:41
With a bit of investigation, there seems to be a history view permission issue which made this look like a new room to me (I can't access history at all)
and there is an issue with me appearing to be in the room multiple times
and this appears as a room now rather than a DM

As a personal note, I think I left the DM when leaving a space that Danielle and I were both in and saying that I want to leave all rooms.

**Comment by t3chguy** [comment] 2021-09-17 10:47
> (I can't access history at all)

This will be due to lack of keys for a section of messages, Element then hides the history assuming you can't decrypt anything in the past

**Comment by t3chguy** [comment] 2021-09-17 14:45
![image](https://user-images.githubusercontent.com/2403652/133802165-f07c29a5-22b1-4932-9b92-ee8870e48c8e.png)

![image](https://user-images.githubusercontent.com/2403652/133802379-bb735645-7a9e-498f-aae0-7c3347f5e5d7.png)
![image](https://user-images.githubusercontent.com/2403652/133802433-96547e2d-69f0-450f-affc-806e20b9c359.png)

There were 3 leave calls, the two rooms and the space itself

![image](https://user-images.githubusercontent.com/2403652/133802524-6ace4533-3a6b-400e-b267-0d10bbb538b4.png)

I cannot reproduce this.

**Comment by kittykat** [comment] 2021-09-30 11:41
I can break this down into three issues:
- When I left a subspace, I left DMs (I believe this is fixed now?) as well as rooms when I chose "Leave all rooms and subspaces"
- When Danielle re-invited me to the DM room that I had left, it appeared in my rooms list rather than DMs list in the left panel which was confusing and I didn't realise that that was the "one true" DM room that I should be using with her (we ended up with multiple ones in the confusion)
- I accidentally left a DM room and lost all messages - maybe default setting should be changed so messages are viewable since member was invited for the first time, if this is possible?

**Comment by t3chguy** [comment] 2021-10-01 10:54
> (I believe this is fixed now?)

Nothing was changed here, it feels like the DM must've been added as a room to the Space otherwise I do not see any codepath which can cause this symptom.

> When Danielle re-invited me to the DM room that I had left, it appeared in my rooms list rather than DMs list in the left panel which was confusing and I didn't realise that that was the "one true" DM room that I should be using with her (we ended up with multiple ones in the confusion)

Yup, DM-ness is crap, Canonical DMs MSC+Project will solve this.

> I accidentally left a DM room and lost all messages - maybe default setting should be changed so messages are viewable since member was invited for the first time, if this is possible? Losing message history was very unpleasant and can be considered a data loss issue.

You didn't, Element Web is just hiding them from you because it sees undecryptables from prior to your join and has no way of knowing there are decryptables if you go back far enough. I'm sure this is a distinct issue open about this but I cannot find it at this time.

**Comment by kittykat** [comment] 2021-12-17 11:59
I'm going to close this as it was a culmination of a few different unexpected behaviours and this does not feel like a useful issue at this point.

**Closed by kittykat** 2021-12-17 11:59 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Critical, A-Spaces
