### ISSUE TITLE
Define Custom Key/Mouse/Joystick bindings for element

### ISSUE THREAD

**Issue by pharoah-islands** [vector-im/element-web#22323] opened 2022-05-24 10:50 UTC
### Your use case

Define Custom bindings for Keyboard/Mouse/Joystick to interact with Element. 

Especially useful for binding custom PTT (Push to Talk) buttons (as done on Mumble) as well as allow people with disabilities to interact with Element. 

![mumble keybindings](https://user-images.githubusercontent.com/106151850/170018077-194c3f03-f54d-4c88-89ca-be1dac93eefa.PNG)

**Comment by t3chguy** [comment] 2022-05-24 10:51
Duplicate of https://github.com/vector-im/element-web/issues/15076

**Closed by t3chguy** 2022-05-24 10:51 UTC
Labels: T-Enhancement
