### ISSUE TITLE
Admin validation to join a room  

### ISSUE THREAD

**Issue by AnassDriate** [vector-im/element-web#24240] opened 2023-01-16 09:43 UTC
### Your use case

As mntioned, this is and enhancement and not a bug.

It will be interesting (especially for public chats) that the room admin has the permissions to review and validate or decline the room joining requests.

Regards,

**Comment by t3chguy** [comment] 2023-01-16 09:44
Duplicate of https://github.com/vector-im/element-web/issues/18655

**Closed by t3chguy** 2023-01-16 09:44 UTC
Labels: T-Enhancement

**Comment by AnassDriate** [comment] 2023-01-16 09:47
thank you
