### ISSUE TITLE
Rendering of ordered list cuts off the first digit from line 100 and onwards

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#25707] opened 2023-07-03 22:08 UTC
### Steps to reproduce

Send an ordered list with 100 items or more

<details>
<summary>Click to expand for an example to copy-paste</summary>

```plaintext
1. This is line number 1
2. This is line number 2
3. This is line number 3
4. This is line number 4
5. This is line number 5
6. This is line number 6
7. This is line number 7
8. This is line number 8
9. This is line number 9
10. This is line number 10
11. This is line number 11
12. This is line number 12
13. This is line number 13
14. This is line number 14
15. This is line number 15
16. This is line number 16
17. This is line number 17
18. This is line number 18
19. This is line number 19
20. This is line number 20
21. This is line number 21
22. This is line number 22
23. This is line number 23
24. This is line number 24
25. This is line number 25
26. This is line number 26
27. This is line number 27
28. This is line number 28
29. This is line number 29
30. This is line number 30
31. This is line number 31
32. This is line number 32
33. This is line number 33
34. This is line number 34
35. This is line number 35
36. This is line number 36
37. This is line number 37
38. This is line number 38
39. This is line number 39
40. This is line number 40
41. This is line number 41
42. This is line number 42
43. This is line number 43
44. This is line number 44
45. This is line number 45
46. This is line number 46
47. This is line number 47
48. This is line number 48
49. This is line number 49
50. This is line number 50
51. This is line number 51
52. This is line number 52
53. This is line number 53
54. This is line number 54
55. This is line number 55
56. This is line number 56
57. This is line number 57
58. This is line number 58
59. This is line number 59
60. This is line number 60
61. This is line number 61
62. This is line number 62
63. This is line number 63
64. This is line number 64
65. This is line number 65
66. This is line number 66
67. This is line number 67
68. This is line number 68
69. This is line number 69
70. This is line number 70
71. This is line number 71
72. This is line number 72
73. This is line number 73
74. This is line number 74
75. This is line number 75
76. This is line number 76
77. This is line number 77
78. This is line number 78
79. This is line number 79
80. This is line number 80
81. This is line number 81
82. This is line number 82
83. This is line number 83
84. This is line number 84
85. This is line number 85
86. This is line number 86
87. This is line number 87
88. This is line number 88
89. This is line number 89
90. This is line number 90
91. This is line number 91
92. This is line number 92
93. This is line number 93
94. This is line number 94
95. This is line number 95
96. This is line number 96
97. This is line number 97
98. This is line number 98
99. This is line number 99
100. This is line number 100
101. This is line number 101
102. This is line number 102
103. This is line number 103
104. This is line number 104
105. This is line number 105
106. This is line number 106
107. This is line number 107
108. This is line number 108
109. This is line number 109
110. This is line number 110
111. This is line number 111
112. This is line number 112
113. This is line number 113
114. This is line number 114
115. This is line number 115
116. This is line number 116
117. This is line number 117
118. This is line number 118
119. This is line number 119
120. This is line number 120
121. This is line number 121
122. This is line number 122
123. This is line number 123
124. This is line number 124
125. This is line number 125
126. This is line number 126
127. This is line number 127
128. This is line number 128
129. This is line number 129
130. This is line number 130
131. This is line number 131
132. This is line number 132
133. This is line number 133
134. This is line number 134
135. This is line number 135
136. This is line number 136
137. This is line number 137
138. This is line number 138
139. This is line number 139
140. This is line number 140
141. This is line number 141
142. This is line number 142
143. This is line number 143
144. This is line number 144
145. This is line number 145
146. This is line number 146
147. This is line number 147
148. This is line number 148
149. This is line number 149
150. This is line number 150
151. This is line number 151
152. This is line number 152
153. This is line number 153
154. This is line number 154
155. This is line number 155
156. This is line number 156
157. This is line number 157
158. This is line number 158
159. This is line number 159
160. This is line number 160
161. This is line number 161
162. This is line number 162
163. This is line number 163
164. This is line number 164
165. This is line number 165
166. This is line number 166
167. This is line number 167
168. This is line number 168
169. This is line number 169
170. This is line number 170
171. This is line number 171
172. This is line number 172
173. This is line number 173
174. This is line number 174
175. This is line number 175
176. This is line number 176
177. This is line number 177
178. This is line number 178
179. This is line number 179
180. This is line number 180
181. This is line number 181
182. This is line number 182
183. This is line number 183
184. This is line number 184
185. This is line number 185
186. This is line number 186
187. This is line number 187
188. This is line number 188
189. This is line number 189
190. This is line number 190
191. This is line number 191
192. This is line number 192
193. This is line number 193
194. This is line number 194
195. This is line number 195
196. This is line number 196
197. This is line number 197
198. This is line number 198
199. This is line number 199
200. This is line number 200
201. This is line number 201
202. This is line number 202
203. This is line number 203
204. This is line number 204
205. This is line number 205
206. This is line number 206
207. This is line number 207
208. This is line number 208
209. This is line number 209
210. This is line number 210
211. This is line number 211
212. This is line number 212
213. This is line number 213
214. This is line number 214
215. This is line number 215
216. This is line number 216
217. This is line number 217
218. This is line number 218
219. This is line number 219
220. This is line number 220
```

</details>

#### What did you expect?
Proper rendering

#### What happened instead?

In Element Web and Desktop, the first digit in the line number from line 100 are rendered outside the visible area

![Screenshot 2023-07-03 225637](https://github.com/vector-im/element-web/assets/19155609/8bf2f71d-130a-4bef-892c-2a93c87f228d)

You can see parts of the 2 in line 200 and onwards

![Screenshot 2023-07-03 230525](https://github.com/vector-im/element-web/assets/19155609/6eeb21ae-7aeb-4a8c-8b20-6d49174611b1)

### Application version

Element version: 1.11.34 Olm version: 3.2.14

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-07-04 06:32
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-07-04 06:33
Duplicate of https://github.com/vector-im/element-web/issues/14621

**Closed by weeman1337** 2023-07-04 06:33 UTC
Labels: T-Defect
