### ISSUE TITLE
Can't join remote room because no servers that are in the room have been provided.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#23791] opened 2022-11-18 13:49 UTC
### Steps to reproduce

1. Click a link to a room that doesn't specify any servers, e.g. !CUrbAfAsdfAdfAsdf:reliable.homeserver.com
2. Get the "Can't join remote room because no servers that are in the room have been provided." message
3. Wonder why Element couldn't just have a stab at joining via reliable.homeserver.com
4. Copy the room id out of the error message, hand craft a https://matrix.to/#/!CUrbAfAsdfAdfAsdf:reliable.homeserver.com?via=reliable.homeserver.com, paste it into an unrelated room, and use it to join.

#### What did you expect?
Element to do the best job it could do to join the room.

#### What happened instead?
Annoying error.

### Operating system

Winnows 10

### Application version

Element Nightly version: 0.0.1-nightly.2022111801 Olm version: 3.2.12

### How did you install the app?

Via the Infomation Super Highway

### Homeserver

lant.uk

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-11-18 14:33
Duplicate of https://github.com/vector-im/element-web/issues/2925 which got closed as a spec bug. It should be up to the spec & server to do any smarts around joining from a room ID, not clients which would yield an inconsistent experience between clients.

**Closed by t3chguy** 2022-11-18 14:33 UTC
Labels: T-Defect
