### ISSUE TITLE
Custom sound packs? (My 🐕 hates the incoming message sound)

### ISSUE THREAD

**Issue by joshchang** [vector-im/element-web#15023] opened 2020-08-21 21:00 UTC
The incoming message (dink) sound is pleasing to me but my dog absolutely hates it. It drives her crazy and for some reason makes her urinate. Are there plans to release/allow custom sound packs?

**Comment by jnpf** [comment] 2020-10-12 15:52
Hey @t3chguy that would be awesome. Do you know when it will happen?

**Comment by t3chguy** [comment] 2020-10-12 15:59
In a phase of the FTUE Notifications project which is restarting in the next couple of weeks, though it is a later phase

**Comment by xavierzwirtz** [comment] 2021-05-20 20:39
I react similarly to OP's dog whenever the incoming call sound plays. The tone and the volume has made me rip my headphones off due to actual pain. Would love to be able to change the sounds, or at the very least change the volume of individual sounds.

**Comment by WardPearce** [comment] 2022-04-03 20:10
The incoming call sound makes me jump every time, element feels more like a cheap horror film to me currently. Custom notifcaiton sounds or even just a softer call sound would be awesome.

Isn't a new concept, but Microsoft did a interesting [article](https://www.microsoft.com/design/articles/designing-the-microsoft-soundscape/) about notifcaiton sound design.

Basically just a soft curve introducing the notification would help a lot.

**Comment by kenwuuu** [comment] 2023-03-31 19:21
[PR in draft currently](https://github.com/matrix-org/matrix-react-sdk/pull/10494)

**Comment by robintown** [comment] 2023-05-27 19:15
This is a duplicate of https://github.com/vector-im/element-web/issues/5891

**Closed by robintown** 2023-05-27 19:15 UTC
Labels: A-Notifications, T-Enhancement, Z-FTUE-Notifications
