### ISSUE TITLE
LaTeX parsing cannot discern $ when not intended to be used

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15846] opened 2020-11-28 05:23 UTC
Posting two permalinks in the same message, for instance, will result in a highly mangled message.

**Comment by turt2live** [comment] 2020-12-01 19:43
also applies when posting bash scripts, things in code blocks, etc. In my mind, this is a blocker to the feature ever leaving labs.

**Comment by jryans** [comment] 2020-12-02 10:56
@akissinger @uhoreg Any thoughts on how we might resolve this? I agree with @turt2live that we'd need to have some solution here before LaTeX composing could leave labs.

**Comment by akissinger** [comment] 2020-12-02 11:56
This was partly my intention when I originally made the delimiters double and triple $'s, rather than single and double. It doesn't totally avoid the problem, but it at least makes it more uncommon. Another option is to have latex-style delimiters `\(` `\)` and `\[` `\]`, but in practice people are not so familiar with these.

Another solution could be the following:
  1. make sure latex is never interpreted inside of a markdown link or code block.
  2. literal dollar signs in other contexts need to be escaped

This has the disadvantage that people who don't know/care about latex math might get weird output when talking about money. :)

Perhaps latex math should always be a setting that is off by default on the mainstream servers, but more specialised (e.g. academic) servers can make it on by default.

**Comment by uhoreg** [comment] 2020-12-02 15:21
One possibility is to only do the LaTeX substitution only when the first `$` not preceded by a word character or number (so either preceded by a non-word, non-numeric character or is at the beginning of the message) and the second `$` is not followed by a word character or number.  So if someone write "$1 or $2", this will not be interpreted as math since the second `$` is followed by a number.

**Comment by akissinger** [comment] 2020-12-02 18:28
I could still see this going wrong if someone is writing a bit of $-heavy code (bash, makefile, pearl, ...), but combined with avoiding latex-ing inside of code blocks would probably do the job for 99% of cases.

**Comment by turt2live** [comment] 2020-12-02 18:42
does it make sense to not parse it if there's a linebreak somewhere between the dollar signs? I think that would fix the majority of cases.

**Comment by akissinger** [comment] 2020-12-04 22:07
It's pretty common to have a linebreak in latex math, e.g. for matrices or long-ish expressions. It's more common for display math than inline, but I still think this would be undesirable for either

**Comment by turt2live** [comment] 2020-12-08 14:44
hmm, at the very least it shouldn't try to use dollar signs in code blocks (though parsing for that is not very fun)

**Comment by thosgood** [comment] 2020-12-08 15:24
not a solution, but just to mention that a lot of TeX syntax highlighters only treat dollar signs as delimiting math mode if there are spaces before the first dollar and after the second, but *not* after the first or before the second. I think combining this with some of the other suggestions (never render in code blocks or links) and disabling latex by default would be how other projects deal with this problem (does anybody have rocketchat or anything that they can test to see how it works there?)

note that, with the old composer, this could be solved quite easily by having an "enable/disable latex" toggle alongside the markdown toggle button, but that doesn't seem to be a solution any longer

**Comment by tobiasBora** [comment] 2020-12-13 13:18
I can confirm that we would not expect LaTeX to be rendered inside block, this gives quite strange results, like:
![image](https://user-images.githubusercontent.com/2164118/102012977-864e8100-3d4d-11eb-82e1-6ff1ebed8045.png)

Also, there is right now a bug when you output 3 dollars instead of two:
![image](https://user-images.githubusercontent.com/2164118/102012942-5bfcc380-3d4d-11eb-920c-c8f00566bc1f.png)

Finally, I would expect (like in latex) that an escaped dollar `\$` gives a normal dollar, like in LaTeX. The code
```
$x = \$3$
```
gives:
![image](https://user-images.githubusercontent.com/2164118/102013067-08d74080-3d4e-11eb-9a45-cba955d5ea9a.png)
while a true LaTeX gives:
![image](https://user-images.githubusercontent.com/2164118/102013082-15f42f80-3d4e-11eb-81ac-6acedcaed898.png)

**Comment by polwel** [comment] 2020-12-14 12:57
As much as I'd love to have LaTex messages, it is orders more common that users just plop a link into their messages. URLs with dollar symbols do exist. We already have issue #4674, so the introduction of math expression must not make this worse.

Since anyway it currently falls back to a code block, how about using `` `$\alpha$` `` as the syntax?

**Comment by jryans** [comment] 2020-12-14 13:41
@akissinger Would you be interested in working on some changes to ignore `$` for LaTeX when inside links and code blocks? That seems like it would address the main points here. 

Ideally, we'll find a way to craft something that can be enabled by default (rather than only used on certain deployments).

**Comment by tobiasBora** [comment] 2020-12-15 08:39
Just a note on the `$…$` syntax: then it means that we won't have a way to write a code that starts with a dollar and ends with a dollar. Which includes all latex codes :-P

**Comment by akissinger** [comment] 2020-12-15 15:31
Based on our experience running this on our own server, I don't think the `$...$` or $`...`$ syntax is a very good option. We already switched from $$ to $ because people found using double-$'s too confusing.

Possibly this strategy catches as many cases in the most unobtrusive way:
1. don't parse latex in links or code blocks
2. require the opening $ to be preceded by whitespace or BOL and the closing $ to be followed by whitespace or EOL
3. all other literal dollar signs should be escaped

Out of curiousity, how are underscores handled? These also commonly feature in URLs. I assume commonmark does the right think for proper markdown links, but for a bare URL in a message, does this put random stuff into italics?

@jryans I might get some time for working on this in the coming weeks/months, but it's hard to predict. If someone else wants to get involved, I could point them at the relevant bits.

**Comment by inducer** [comment] 2020-12-15 15:34
Gitlab uses
```
$`...`$
```
and that works OK IMO.

**Comment by akissinger** [comment] 2020-12-15 15:41
Presumably most people on Gitlab are programmers, who at least know what markdown is. It doesn't seem so suitable for our use case, which is general scientific communication (including e.g. physicists and mathematicians).

**Comment by t3chguy** [comment] 2020-12-15 15:43
> Out of curiousity, how are underscores handled? These also commonly feature in URLs. I assume commonmark does the right think for proper markdown links, but for a bare URL in a message, does this put random stuff into italics?

Nope, it breaks as documented here: https://github.com/vector-im/element-web/issues/4674 https://github.com/vector-im/element-web/issues/7368 https://github.com/vector-im/element-web/issues/6434

**Comment by polwel** [comment] 2020-12-16 10:12
> 
> 
> Presumably most people on Gitlab are programmers, who at least know what markdown is. It doesn't seem so suitable for our use case, which is general scientific communication (including e.g. physicists and mathematicians).

Scientists and engineers are also the exact kind of people that have no trouble learning a new syntax. I think that the Element UX is pretty good in that regard, as the markup buttons in the editor (the ones that appear when selecting a chunk of text) only apply the appropriate Markdown. They do a decent job at teaching how to use Markdown even when you've never heard of it. Why not simply add another button for math?

**Comment by rda0** [comment] 2020-12-21 14:24
I created a PR (https://github.com/matrix-org/matrix-react-sdk/pull/5515) that could potentially solve this. I tried to take all opinions in the comments here into account. 

Just to note, there are also some discussions in https://talk.commonmark.org/t/can-math-formula-added-to-the-markdown/3140/2 and https://talk.commonmark.org/t/mathematics-extension/457 about how maths could be a commonmark extension.

**Comment by grinapo** [comment] 2021-01-27 10:32
As mentioned in #16290 : why does it even try to interpret LaTeX in \`\`\` code blocks? It definitely should not.

**Comment by rda0** [comment] 2021-01-29 18:11
> As mentioned in #16290 : why does it even try to interpret LaTeX in ``` code blocks? It definitely should not.

@grinapo The current implementation first parses the raw input for LaTeX and then runs the output through the Markdown parser (commonmark). Solutions could be to use a combined parser or to replace commonmark (#5940) with an extensible markdown parser and add LaTeX syntax as an extension as it is done in FluffyChat.

**Comment by randolf-scholz** [comment] 2021-02-23 09:22
> Gitlab uses
> 
> ```
> $`...`$
> ```
> 
> and that works OK IMO.

This is not so nice because you cannot simply copy-paste math formulas from Markdown documents, Jupyter notebooks, Python comments or just plain LaTeX anymore. 

But I think markdown+MathJax / Katex how it is implemented in Jupyter/VSCode/math.stackexchange.com  has already kind of solved this problem: Any dollar sign inside code blocks [`` `..$..`  ``] or [``````  ```..$..```   ``````]  is escaped, and dollar signs for currency denomination can be escaped with a backslash [`\$`].

**Closed** 2021-04-09 10:07 UTC
Labels: A-Maths, P1, S-Major, T-Defect
