### ISSUE TITLE
Duplicate room name in side panel

### ISSUE THREAD

**Issue by expipiplus1** [vector-im/element-web#17637] opened 2021-06-13 02:48 UTC
![image](https://user-images.githubusercontent.com/857308/121793658-ead29600-cc33-11eb-91a0-7160563209ea.png)

### Description

The #haskell-language-server room has overtaken my room panel!

### Steps to reproduce

I'm not sure what happened, I

- C-k
- type `haskell-lan`
- `down, down, down` until I got to the (only) `haskell-language-server` room
- `enter`
- sent a message
- Noticed that more and more slots in the side panel were becoming `haskell-language-server`
  - A new one appears on interaction with the room panel, or sending a message in another room

Restarting element seems to fix it, however I was able to reproduce it by following the steps above:

![image](https://user-images.githubusercontent.com/857308/121793724-b90dff00-cc34-11eb-9c1d-549d707ae675.png)

Logs being sent: yes/no

### Version information

- **Platform**: desktop 
- **OS**: NixOS (GNU/Linux) 
- **Version**: 
  - Element version: 1.7.30
  - olm version: 3.2.3
  - synapse version: 1.35.1

**Comment by SimonBrandner** [comment] 2021-06-13 06:26
Duplicate of https://github.com/vector-im/element-web/issues/14508

**Closed by SimonBrandner** 2021-06-13 06:26 UTC
Labels: T-Defect
