### ISSUE TITLE
Messages in E2EE DM are suddenly "unencrypted"

### ISSUE THREAD

**Issue by newchoi** [vector-im/element-web#19924] opened 2021-11-29 03:43 UTC
### Steps to reproduce

Unfortunately, I cannot explain what caused this error to occur. Nothing unusual was initiated in this DM aside from messaging back and forth with a friend.

Here's what happened: a friend messaged me, and I noticed that beneath their profile picture a small red shield had appeared. When I hover my mouse over this red shield, a small text-box appears which says "Unencrypted". Here's a picture of what it looks like. 

![eissue 01 - Copy](https://user-images.githubusercontent.com/95199271/143804837-3bef0bc5-7ecd-4bfb-b2a5-0334801bc54a.png)

When I click on my friend's profile picture, under the "Security" tab, which is directly below the profile picture, it says "Messages in this room are end-to-end encrypted." I thought this "Unencrypted" issue was a false positive, in other words, the message was saying it is "unencrypted" when it really wasn't, so I enabled developer mode on Android. For my messages, I could hold the message and the "View Source" and "View Decrypted Source" menus would appear; but for my friend's messages, only the "View Source" menu would appear, which I believe implies my messages are encrypted, but my friend's aren't. 

![eissue 02 - Copy](https://user-images.githubusercontent.com/95199271/143805217-c655582f-d303-4f50-8dc2-c038f536e47e.png)

This issue was appearing on both Android and the web version of Element, so I don't think it's an OS specific issue... However, my friend uses IOS.

I would like to clarify this; only the messages from a specific point onward became unencrypted; not all messages my friend has sent me had become unencrypted. I asked my friend if they had done anything that might have caused this change, but they said they hadn't done anything at all. They had just been using the app as normal when the issue occurred. 

P.S. Can someone explain to me how to send the logs from the specific DM? I'm not too sure how to do that (on Web preferably...) How can I link this bug report when I send the logs? Thanks!

#### What did you expect?

The DMs in an E2EE DM would remain encrypted for all participants involved.

#### What happened instead?

The DMs my friend sent suddenly became unencrypted.

### Operating system

Windows 10

### Browser information

Firefox

### Application version

Element version: v1.9.5 Olm version: 3.2.3

### Will you send logs?

Yes

**Comment by dbkr** [comment] 2021-12-01 18:19
This sounds more likely to be an iOS bug (ie. it sounds like for some reason the iOS device is probably sending them unencrypted. If you can get your friend to submit a bug report from their device, that might help.

**Comment by newchoi** [comment] 2021-12-02 19:11
> This sounds more likely to be an iOS bug (ie. it sounds like for some reason the iOS device is probably sending them unencrypted. If you can get your friend to submit a bug report from their device, that might help.

I think you're right. When my friend sent me messages through Element web, the messages appeared encrypted. The issue was only occurring when they sent me messages on iOS.

Interestingly enough, my friend is saying that they are not seeing the red shield on their unencrypted messages. On their phone, it seems as though the messages are being sent encrypted as usual; the red shield only appears when they're on web, or when I'm on Android. 

I'll get them to send the logs from their side as soon as they're available. Thanks!

I hope this issue can be solved, given it's kind of concerning the messages suddenly became unencrypted... For reference, we are messaging on the same home server, and I've never experienced this issue with other friends also on the same home server; some of these friends use iOS too... 

Very interesting. I hope the logs can give some insight into what's going on!

**Comment by kittykat** [comment] 2021-12-23 16:06
I'm going to close this for now as the issue is in iOS. Please ask your friend to file a bug with a rageshake/logs against iOS if they are still experiencing the problem.

**Closed by kittykat** 2021-12-23 16:06 UTC
Labels: T-Defect, S-Critical, A-E2EE, A-DMs, Z-UISI
