### ISSUE TITLE
Pausing notifications / notification schedule

### ISSUE THREAD

**Issue by benjaminleonard** [vector-im/element-web#18591] opened 2021-08-17 11:22 UTC
#### What would you like to do?
Set a notification schedule, to prevent notifications outside of working hours 

#### Why would you like to it?
Working across timezones, I end up with a load of unwanted notifications from busy channels in an evening

#### How would you like to achieve it?
Something similar to the Slack notification settings – bonus points for the ability to snooze notifications for a period, and for others to be able to force-send an urgent notification
<img width="567" alt="image" src="https://user-images.githubusercontent.com/4020798/129717279-ee63f53c-8555-4e4c-b7f0-e6faa7cfa00f.png">

### Have you considered any alternatives?

Currently I'm reducing notifications overall in group channels

**Comment by t3chguy** [comment] 2021-08-31 12:06
Duplicate of https://github.com/vector-im/element-web/issues/3569

**Closed by t3chguy** 2021-08-31 12:06 UTC
Labels: S-Minor, A-Notifications, T-Enhancement, O-Intermediate
