### ISSUE TITLE
Can't verify any device at all

### ISSUE THREAD

**Issue by TobiasDev** [vector-im/element-web#13797] opened 2020-05-25 09:34 UTC
I'm trying to verify any device I have currently (riot on Android, RiotX on Android, Web, or the Linux Client), and neither of them can be verified. It asks me for my account password and I add the password and all it does it just fetch the keys forever, then again asks me for my account password. As it currently is I don't have any verified devices as all. Is there something I can do to fix this?

**Comment by TobiasDev** [comment] 2020-05-25 09:46
I have tried both the emoji verification, legacy verification and text verification. None of them mark any of my devices as "verified". :(

**Comment by bwindels** [comment] 2020-05-26 13:33
Can you please submit your debug logs @TobiasDev ? You can do this from "Help & About" in the settings.

**Comment by TobiasDev** [comment] 2020-05-26 14:02
Sure, do you want them from all my devices? EG. Riot Linux and Android, or is one of them enough?

**Comment by bwindels** [comment] 2020-05-26 14:20
Ideally the device where you've "upgraded your encryption" when cross-signing came out in 1.6, but probably logs from any device where you've attempted to verify could help shed some light.

**Comment by TobiasDev** [comment] 2020-05-27 10:25
Okay, do I need to clean anything out from the logs before uploading them? E.G. Are there any sensitive data in my logs?

**Comment by TobiasDev** [comment] 2020-05-27 10:29
I tried using the Riot Linux app to send the logs, and it said "thank you" so I guess the logs was sent?

**Comment by bwindels** [comment] 2020-05-27 15:38
Yes, thank you. Wrt to sensitive information in the logs, I refer you to what is mentioned in the settings above said button:
> Debug logs contain application usage data including your username, the IDs or aliases of the rooms or groups you have visited and the usernames of other users. They do not contain messages.

**Comment by TobiasDev** [comment] 2020-05-28 08:43
Yeah, I managed to see that as well. :smile: I should probably have looked in the app before asking that question. :disappointed: 

Anyway, I hope that you got the info you needed from that.

**Comment by ShadowJonathan** [comment] 2021-12-16 16:52
I have a feeling this is a SSSS/Backup "legacy weird situation" bug where the upgrade occured, though i could probably not reproduce it without using some older element versions first.

I wonder if this issue is still relevant at all today.

**Comment by kittykat** [comment] 2021-12-20 11:27
I'm going to close this issue for now because of its age and the fact that the code base has changed significantly since it was filed. If you are still experiencing it, please comment with @kittykat and submit a new rageshake so that I can re-open it for you.

**Closed by kittykat** 2021-12-20 11:27 UTC
Labels: T-Defect, A-E2EE-Cross-Signing, X-Needs-Community-Testing
