### ISSUE TITLE
Make the main address of a room selectable for copy

### ISSUE THREAD

**Issue by janvlug** [vector-im/element-web#17131] opened 2021-05-02 21:32 UTC
#### Is your suggestion related to a problem? Please describe.
I have difficulties selecting (copying) the name of a room so that I can share it with someone. If I go to the room settings, I cannot select the Main address, to copy it to send it to someone.

#### Describe the solution you'd like.
An easy way to copy the address of a room to send it to someone.

**Comment by SimonBrandner** [comment] 2021-05-03 17:01
@janvlug, what would the benefit of this? You can already mention the room in a message (if the other user is on Matrix already). Or you can share a link to that room using the share dialog

**Comment by t3chguy** [comment] 2021-05-03 17:05
Duplicate of https://github.com/vector-im/element-web/issues/14025

Empirically its possible by right-clicking, `Select all`, then Copy

![image](https://user-images.githubusercontent.com/2403652/116907858-137d6e00-ac3a-11eb-8234-4f18463cf4f5.png)

**Closed** 2021-05-03 17:05 UTC
Labels: A-Aliases, A-Room-Settings, A-Share, T-Enhancement, X-Needs-Info

**Comment by janvlug** [comment] 2021-05-08 12:59
I'm on Fedora 34 GNOME Wayland Firefox. It is not possible to select the main address there.
If I choose Select All, all text in the page is selected, except the Main address:

![image](https://user-images.githubusercontent.com/5903208/117539821-9de41a00-b00c-11eb-8937-160fd089d7b1.png)
 ##
So I think this is really an issue on my platform.
@t3chguy,  could you please re-open this issue?

> what would the benefit of this? You can already mention the room in a message (if the other user is on Matrix already) or you can share a link to that room using the share dialog

@SimonBrandner, the benefit would be that I could provide a room identifier to someone using another mechanism than Matrix. I could not find the share dialog in the element-web version.

**Comment by t3chguy** [comment] 2021-05-08 13:01
@janvlug. No this is a duplicate of https://github.com/vector-im/element-web/issues/14025
