### ISSUE TITLE
"Activity" sorting is no longer updated in real time

### ISSUE THREAD

**Issue by b0bh00d** [vector-im/element-web#26476] opened 2023-10-31 15:25 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

I have Sorting set to "Activity" in both `People` and `Rooms`.  In my `People` list, I expand it ("Show more") to reach an entry that has aged.  I send a message in that private chat.  The entry remains where it is, and disappears when I reduce the view ("Show less")

#### What did you expect?

The channel I just triggered activity in used to instantly got to the top.

#### What happened instead?

I now have to completely exit Matrix and restart it to get the Activity sorting to work as expected.

### Operating system

Windows 10 Pro

### Application version

Element version: 1.11.47 Olm version: 3.2.14

### How did you install the app?

https://element.io

### Homeserver

chat.mozilla.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-10-31 15:43
Duplicate of https://github.com/vector-im/element-web/issues/16127

**Closed by t3chguy** 2023-10-31 15:43 UTC
Labels: T-Defect
