### ISSUE TITLE
Implement key press to show all options with the message

### ISSUE THREAD

**Issue by hahahahacker2009** [vector-im/element-web#25607] opened 2023-06-15 09:52 UTC
#### What would you like to do?
The options appear when I put my mouse on a message, is basically the same on Discord and Element.
However, Discord have a feature, when I press the Shift key with the mouse on a message it would show me more options with the message, include delete (redact), copy message link/id, pin message. 
#### Why would you like to do it?
It is more convenient to just press a key and click the button, than click on the three dot to open the button list.
#### How would you like to achieve it?
Implement a key press (maybe Shift), show all the options that's currently available with the message (they are mostly necessary).

**Comment by t3chguy** [comment] 2023-06-15 10:05
Duplicate of https://github.com/vector-im/element-web/issues/18711

**Closed by t3chguy** 2023-06-15 10:05 UTC
Labels: T-Enhancement
