### ISSUE TITLE
Saved image auto-opens in browser from desktop

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20747] opened 2022-01-25 17:22 UTC
### Steps to reproduce

1. Find https://app.element.io/#/room/#element-community-testing:matrix.org/$Tj3PahHAqyqJhu9Wv2QvhZ0e3h2zDG2FKx4mkqzgPew in file panel (resent upload so near the end)
2. Click "Download"

#### What did you expect?
File downloads to Downloads in local storage and a toast pops up asking if I want to open it

#### What happened instead?
https://matrix-client.matrix.org/_matrix/media/r0/download/riot.ovh/uDcDukSWZhhdpYFEPkmlKGrR opens in a web browser

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022012401 Olm version: 3.2.8

### How did you install the app?

aur package

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-01-26 09:11
Duplicate of https://github.com/vector-im/element-web/issues/12405

**Closed by t3chguy** 2022-01-26 09:11 UTC
Labels: T-Defect, S-Major, A-File-Panel, A-File-Download, O-Uncommon, Z-Community-Testing
