### ISSUE TITLE
Rooms missing or showing as just usernames or Empty room

### ISSUE THREAD

**Issue by voice06** [vector-im/element-web#19260] opened 2021-10-03 02:32 UTC
### Steps to reproduce

Just running the Desktop app as normal

### What did you expect?
Normal operation with all rooms accounted for.

### What happened?
Multiple rooms missing, then reappearing as Empty room or a list of users. In addition the rooms appear as v1 with no room state info other than m.room.member, looking in the dev console I see messages like:

```
rageshake.js:65 [getType] Room !YTvKGNlinIzlkMTVRl:matrix.org does not have an m.room.create event
rageshake.js:65 [getType] Room !ukQuoWmDilxTuWNMjH:afternet.org does not have an m.room.create event
rageshake.js:65 [getType] Room !ehXvUhWNASUkSLvAGP:matrix.org does not have an m.room.create event
rageshake.js:65 [getType] Room !AZozoWghOYSIAfaZjJ:matrix.org does not have an m.room.create event
rageshake.js:65 [getType] Room !vHQXPGHpMwXbYrTNnq:libera.chat does not have an m.room.create event
```

![image](https://user-images.githubusercontent.com/4512200/135737322-8b28121b-1911-4a3c-bc31-802defc80be8.png)
![image](https://user-images.githubusercontent.com/4512200/135737324-47a95a4c-2df4-4243-a963-5f0804634aca.png)

I've tried clearing the cache and restarting Element but the issue persists. Its like for some reason Element has lost the room state for multiple rooms and is unable to resync properly.

### Operating system

Linux Mint

### Application version

Element version: 1.9.0 Olm version: 3.2.3

### How did you install the app?

Debian apt repo

### Homeserver

randomsonicnet.org

### Have you submitted a rageshake?

No

**Comment by voice06** [comment] 2021-10-03 02:33
I've also just noticed that under spaces even though I'm in the Matrix space it the space doesn't show with the others. None of these issues are seen in Element Android.

**Comment by voice06** [comment] 2021-10-03 16:22
Downgraded Element-Desktop to the previous version this morning and everything looks normal.

Element version: 1.8.5
Olm version: 3.2.3

Re-upped to 1.9.0 and its still looking normal.

**Comment by voice06** [comment] 2021-10-03 17:58
Found another room missing, went back to 1.8.5 to recover it, got the room back as a v6 room with full room state data. Re-upgraded to 1.9.0 and its now showing as Empty room, v1, no room state data.

**Comment by novocaine** [comment] 2021-10-04 09:20
Thanks for the report. What homeserver is randomsonicnet.org running? (and version?)

**Comment by voice06** [comment] 2021-10-04 13:51
Its running Synapse v1.43.0

I just sent in a rageshake

Not seeing anything suspicious at the moment

Currently though the room that was messed up is loading properly this morning.

**Comment by t3chguy** [comment] 2021-10-05 09:35
Looks like sync/sync accumulator issues which would cascade to all downstream room state consumers (e.g spaces) rather than an actual spaces issue.

**Comment by setpill** [comment] 2021-11-07 16:40
Happening to me too, the new Matrix HQ room is bugged for me. Showing as "[Username] and 27050 others".

> the version of element web being used

1.9.3

> the version of the homeserver

Not sure how to find that out. My account's homeserver is matrix.org. So is the room's.

> if you're willing to share screenshots (even heavily redacted ones), that would help

Channel list:

![image](https://user-images.githubusercontent.com/37372069/140653710-5fbc8341-337b-44af-a7c2-9c48f1981964.png)

What the (old) "Matrix HQ" room looks like (when you click the `The conversation continues here` link you go to the room with no name).

![image](https://user-images.githubusercontent.com/37372069/140653717-9dd2ebf8-58ab-4bf5-b90a-b8baa2abbff6.png)

**Comment by t3chguy** [comment] 2022-01-13 14:59
Duplicate of https://github.com/vector-im/element-web/issues/8246

**Closed by t3chguy** 2022-01-13 14:59 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, S-Critical, A-Room-List, O-Uncommon
