### ISSUE TITLE
Chrome uses native desktop notifs now on Linux, which don't support HTML

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5622] opened 2017-11-16 16:25 UTC
So we're leaking HTML into our desktop notifs now :(

**Comment by erikjohnston** [comment] 2017-11-16 16:32
Turns out that some do, e.g. `xfce4-notifyd`

**Comment by lampholder** [comment] 2017-11-22 16:32
Can whatever handles desktop notifs detect the OS and strip HTML accordingly?

If so a P3 stretch goal could be to implement forcing HTML notifs as an option (for the xfce4-notifyd fans)

**Comment by robintown** [comment] 2022-11-03 14:35
Does anyone know if this situation has changed in the last 5 years?

**Comment by turt2live** [comment] 2023-01-10 00:39
Closing as presumed fixed. If this is untrue, please open a new issue with fresh reproduction steps.

**Closed by turt2live** 2023-01-10 00:39 UTC
Labels: X-Needs-Info, Z-Platform-Specific, S-Minor, A-Notifications, O-Occasional
