### ISSUE TITLE
"Recently viewed" dropdown overlaps the new search experience

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21847] opened 2022-04-19 13:39 UTC
### Steps to reproduce

1. Enable new room breadcrumbs
2. Enable new search experience
3. Hover over "Recently viewed"
4. Hit "CtrlOrCommand+K"

#### What did you expect?

For the "recently viewed" dropdown to be either closed, or at the very least displayed under the new search dialog

#### What happened instead?

It's displayed over, and looks very out of place

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-19 22:21
Applies to any dialog that can be opened with the keyboard, e.g. the keyboard shortcuts dialog

**Comment by yaya-usman** [comment] 2022-04-30 23:12
@robintown can you help reproduce the issue by demonstrating with a video or something when you're free, i don't seem to understand the original issue statement very well

**Comment by robintown** [comment] 2022-05-01 00:47
@yaya-usman This is what it looks like:

https://user-images.githubusercontent.com/48614497/166127421-007bbea8-ba33-457e-b070-c7351639172b.mp4

**Comment by robintown** [comment] 2022-05-01 00:49
@yaya-usman This is what it looks like:

https://user-images.githubusercontent.com/48614497/166127462-027ada70-594f-483b-b953-157f687ac75e.mp4

**Comment by yaya-usman** [comment] 2022-05-01 09:07
@robintown Thanks, So how do i enable recently viewed breadcrumbs can't find it in the room settings. Also when i hit `ctrl+K`, it doesn't bring the keyboard shortcuts dialog like in the video but rather a search dialog.

**Comment by SimonBrandner** [comment] 2022-05-01 11:15
> @robintown Thanks, So how do i enable recently viewed breadcrumbs can't find it in the room settings. Also when i hit `ctrl+K`, it doesn't bring the keyboard shortcuts dialog like in the video but rather a search dialog.

The new breadcrumbs menu is a labs feature, so you'd need to enable labs settings and then enabled it. The new search experience is also labs feature though it should be accessible as a beta option in the labs section

**Comment by yaya-usman** [comment] 2022-05-01 18:28
@SimonBrandner Thanks, But so far i could only find `Thread `and `new search experience` in the labs settings as in the image below, no viewed breadcrumb or is there other way of enabling it?

![Capture](https://user-images.githubusercontent.com/38439166/166159369-134e6696-125f-476b-b1ae-d19f65e8c824.PNG)

**Comment by SimonBrandner** [comment] 2022-05-01 18:38
You need to enable labs, see https://github.com/vector-im/element-web/blob/develop/docs/labs.md, I would suggest moving to https://matrix.to/#/#element-dev:matrix.org for further discussion

**Comment by yaya-usman** [comment] 2022-05-01 19:47
Thanks, i followed the link above and included `"show_labs_settings": true` in the `config ` file as suggested, but it still didn't show the labs features in the settings, or maybe i am doing something wrong :(.  also i guess knowing the name of the feature probably i can just add it to the `features` section of the `config` file and see if it enables it that way.

**Comment by yaya-usman** [comment] 2022-05-01 19:57
@SimonBrandner Thanks, it's now enabled

**Closed** 2022-05-10 18:50 UTC
Labels: T-Defect, S-Minor, Help Wanted, A-Breadcrumbs, O-Uncommon, good first issue, Z-Labs, A-New-Search-Experience
