### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by brumasribera** [vector-im/element-web#23518] opened 2022-10-18 11:29 UTC
#### What would you like to do?
To be able to switch between multiple Matrix account on the app

#### Why would you like to do it?
So that I can use both the work account together with my personal one.
I would therefore be able to get an Element Home subscription and get my whole family in.

#### How would you like to achieve it?
Probably clicking the profile picture and selection another account. 

### Have you considered any alternatives?

I could provably achieve it by using other browsers and incognito mode, but, to be fair, that is not really an option, specially if I am going to pay for a subscription.

**Comment by t3chguy** [comment] 2022-10-18 11:31
Duplicate of https://github.com/vector-im/element-web/issues/2320

**Closed by t3chguy** 2022-10-18 11:31 UTC
Labels: T-Enhancement
