### ISSUE TITLE
RTL writing and font

### ISSUE THREAD

**Issue by mahmoodn** [vector-im/element-web#23725] opened 2022-11-08 09:28 UTC
### Your use case

Additional support for non-English languages, specially Farsi, which is a right-to-left language and also more standard fonts for better representation.

**Comment by t3chguy** [comment] 2022-11-08 09:31
> and also more standard fonts for better representation.

You can choose whichever font you like most in Settings > Appearance > Advanced

**Comment by t3chguy** [comment] 2022-11-08 09:31
Duplicate of https://github.com/vector-im/element-web/issues/14520

**Closed by t3chguy** 2022-11-08 09:31 UTC
Labels: T-Enhancement

**Comment by t3chguy** [comment] 2022-11-08 09:49
This repo is called element-web, you might want to try one called element-android for issues with the Android app.
