### ISSUE TITLE
Allocate more space to message bodies when the window is small

### ISSUE THREAD

**Issue by cbarrete** [vector-im/element-web#17883] opened 2021-07-05 13:44 UTC
![image](https://user-images.githubusercontent.com/62146989/124478297-575d3280-dda5-11eb-905c-961e44b5209e.png)

#### Is your suggestion related to a problem? Please describe.

In all modes (default/compact/IRC, IRC being shown in the screenshot),  messages are almost unreadable when the window is small/narrow. This is really painful as the message bodies are really what I (and likely most users?) care about most.

This stems from different things (which I'm happy to make separate issues for, although I'd consider this a general problem) :

- There is excessive padding on the left of timestamps, the right of message bodies, between the message bodies and read receipts, and the right of read receipts
- The column for nicknames has a fixed min width rather than the max width of all nicknames
- The read receipt column has a fixed min width rather than ~`number_of_members * read_receipt_width`
- There is excessive vertical padding between the last message and composer, especially after a typing notification has been received
- In IRC mode, the profile pictures are shown before all messages, but are really small, making them unreadable anyways (pictures are tiny, the first letter of the nickname is useless if it's next to the name anyways), but they still take up space.

#### Describe the solution you'd like.

Overall, it would be nice that allocating sufficient room to message bodies (including for small windows) is kept a priority when taking design decisions, more practically for now, I'd like to see many of the paddings mentioned previously be decreased to make more room for text.

#### Describe alternatives you've considered.

I've tried all appearance settings, but all of them make big compromise on waste of vertical or horizontal space.

**Comment by t3chguy** [comment] 2021-07-05 13:47
Duplicate of https://github.com/vector-im/element-web/issues/6488

**Closed by t3chguy** 2021-07-05 13:47 UTC
Labels: T-Enhancement
