### ISSUE TITLE
"Instant" voice rooms

### ISSUE THREAD

**Issue by jedahan** [vector-im/element-web#19115] opened 2021-09-21 14:48 UTC
#### What would you like to do?

I would like to 
* see who is in a voice room in the side bar
* see who is talking at any moment without joining
* and most importantly, join and leave a call with 1-click

In other words, make them as similar to text rooms as possible (or Discord)

#### Why would you like to do it?

There is this really informative thread, which I'll quote a bit below https://news.ycombinator.com/item?id=28435517 though please excuse the emphasis

> The difference is that the discord UI conveys information that is strictly missing in other UIs. By having a separate voice channel, it's implicitly broadcasting "these people want to talk".
> 
> 
> It's also broadcasting who -is- talking; I've very frequently made a binary choice of "do intrude" versus "don't intrude" based on who's actually talking. I know based on the social circles that if person A and B are talking, they're likely "talking shop", because person A commissions work from person B. But I also know that if it's person A and C, they're probably just gaming, and I'm welcome to join them.
> 
> This implicit social signaling is obscenely important. It's a make or break feature.
> 
> When I'm using slack, by comparison; I can see that a coworker is in "some mysterious voice call" but I have absolutely NO IDEA who they're calling, and whether I'm welcome to join. I have to openly intrude on their time, and ask that explicitly, and that's inherently rude. I'm able to do that with close friends because I have a huge buffer of goodwill, but interrupting people is always inherently rude.
> 
> Discord gives you a way to get this information without being rude.
> 
> If the only way to do it is to be rude, then - here's the kicker: It introduces an outright failure state! Quite a few people will actually decided "gosh, I don't feel comfortable interrupting this person I barely know, I'm just not going to." They literally DON'T make a call they otherwise would make, and it's 100% down to UX. It's a full on, binary, "failure to provide service", and it's because of how your software psychologically runs on the people using it.

#### How would you like to achieve it?

Good question! I am happy to accept guidance to come up with a concrete plan.

Speculating with no research, changing the 'join room' button link to whatever the join call button would be a good first step

### Have you considered any alternatives?

Discord is our alternative, moving away from Slack. We already run a matrix bridge, but would rather have everything on matrix.

We also are considering Revolt, though its a bit risky right now.

### Additional context

Please don't hesitate to reach out or we can chat wherever

There are two communities I am part of, for example, [nycresistor.org](nycresistor.org) that are leaning towards Discord, even though they would prefer matrix, and this is one of the sticking points.

It is more important for *future* membership, where many younger folks we'd like to be part of this community, use voice chat way more than our current members.

**Comment by robintown** [comment] 2021-09-21 15:16
Duplicate of https://github.com/vector-im/element-web/issues/3546

**Closed by robintown** 2021-09-21 15:16 UTC
Labels: X-Cannot-Reproduce, A-VoIP, X-Needs-Product, T-Enhancement, O-Frequent

**Comment by robintown** [comment] 2021-09-21 15:19
This is being worked on by the way, see https://matrix.org/open-tech-will-save-us/11 for a preview of the design work if you're interested

**Comment by jedahan** [comment] 2021-09-21 15:21
Very interested, thank you so much!

**Comment by jedahan** [comment] 2021-09-21 16:12
The recording is excellent - for those just interested in Voice & Video Rooms, I recommend fast forwarding to 21:00
