### ISSUE TITLE
If two calls are received in rapid succession, trying to answer the second may try instead to answer the first and crash.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2055] opened 2016-09-01 11:56 UTC
I was on a call with Amandine; it dropped due to a network outage.  She then tried calling me back twice.  When I answered the second call, react-sdk instead tried to answer the first call object - resulting in a fatal exception as the first PeerConnection has been closed by that point.

This seems to be because in https://github.com/matrix-org/matrix-react-sdk/blob/35fff744771aae322e6a2e85dc9d891a10700c5f/src/CallHandler.js#L315 and friends we operate on the 'current call for a room' rather than a specific call ID.  Surely our intents should be for a specific call ID, otherwise we end up with nasty races where we end up operating on the stale idea of a call.

Full logs, complete with the event timeline in question attached.
[addstream failure.txt](https://github.com/vector-im/vector-web/files/449548/addstream.failure.txt)

**Comment by kittykat** [comment] 2021-09-30 17:05
I'm going to close this issue for now as I couldn't reproduce it. Please reopen it and add it to the issue triage project if it is still happening for you.

**Closed by kittykat** 2021-09-30 17:05 UTC
Labels: T-Defect, P2, S-Major, A-VoIP
