### ISSUE TITLE
Do not play notification sounds when the window is focused and the room in question is opened

### ISSUE THREAD

**Issue by voidmann** [vector-im/element-web#15469] opened 2020-10-15 09:04 UTC
### Description

When audible notifications are enabled, the notification sound plays even when the room is opened and the window has focus.

### Steps to reproduce

- Enable audible/noisy notifications for a room;
- Keep the window focused and the room open;
- Wait for someone to message or notify you.

Like with any other chat application, notification sounds need not play for the chat the user is currently interacting with.

### Version information

- **Platform**: Both web and desktop
- **OS**: Any
- **Version**: 1.7.9 and below

**Comment by t3chguy** [comment] 2020-10-15 09:16
Duplicate of https://github.com/vector-im/element-web/issues/3434

**Closed by t3chguy** 2020-10-15 09:16 UTC
Labels: bug
