### ISSUE TITLE
Element Desktop App Screenshare Stuck Loading Forever 

### ISSUE THREAD

**Issue by LeeGlen610** [vector-im/element-web#21268] opened 2022-03-02 10:34 UTC
### Steps to reproduce

1. Startup Element app.
2. Join Video Call.
3. Click on toggle screenshare.
4. Both "Your entire screen" & "Application window" stuck in a infinite loading screen.

### Outcome

I expected to see either my entire screen or an application window to pop-up in the preview so that I would be able to share my screen with my team.

However, it will not load the preview and therefore I can't show my team my screen.

### Operating system

Windows 10

### Application version

Element version: 1.10.6 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-03-02 10:52
Duplicate of https://github.com/vector-im/element-web/issues/4880

**Closed by t3chguy** 2022-03-02 10:52 UTC
Labels: T-Defect
