### ISSUE TITLE
Bad UTD in Encrypted group room with Travis

### ISSUE THREAD

**Issue by Gnuxie** [vector-im/element-web#23592] opened 2022-10-25 17:44 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

Several of Travis's messages are UTD.

#### What did you expect?

to see his messages
### Operating system

Manjaro Linux

### Browser information

Firefox 105.0

### URL for webapp

https://app.element.io/?updated=1.11.2

### Application version

Element version: 1.11.11 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by turt2live** [comment] 2022-11-07 09:30
This is still happening, and it's doing so randomly.

Counting it as a regression as this failure mode seems new.

**Comment by turt2live** [comment] 2022-11-07 10:13
```
2022-11-06T23:01:20.046Z E Failed to share megolm keys for redacted in redacted (slice 1/46)
2022-11-06T23:01:20.046Z E Failed to ensure outbound session in redacted Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Worker.<anonymous> (vector://vector/webapp/bundles/a0d2dee82d8a1dde44f2/init.js:86316:25)
```

**Comment by weeman1337** [comment] 2022-11-09 09:38
Got UTD today in one of my rooms.

**Comment by richvdh** [comment] 2022-11-15 13:48
so yes, having stared at the rageshakes a bit more, this all seems to be due to the indexeddb failures.

Duplicate of https://github.com/vector-im/element-web/issues/14174

**Closed by richvdh** 2022-11-15 13:48 UTC
Labels: T-Defect, X-Regression, S-Major, A-E2EE, Z-UISI, O-Frequent, Team: Crypto
