### ISSUE TITLE
Force E2EE off in .well-known config

### ISSUE THREAD

**Issue by untildo** [vector-im/element-web#25600] opened 2023-06-14 12:04 UTC
### Your use case

Not everyone needs E2EE. Ideally there would be a Synapse config to completely disable E2EE and all associated functions such as device verification and key backup prompts. This way we do not place the trust on clients to encrypt or not, and the policy can be enforced by the homeserver admin instead, as discussed in https://github.com/vector-im/element-meta/issues/1442 and many other places.

However, in airgapped networks where there is a high degree of control and trust over the deployed software (such as Element Web / Desktop) it would be acceptable to configure this in the client instead. In these scenarios we do not need to be concerned about someone using a different client that somehow bypasses the E2EE policy.

We have the option to turn off E2EE by default in .well-known config for DM rooms but it doesnt cover group rooms and users can still manually enable E2EE. Some homeserver admins in a tightly controlled airgapped network need to enforce E2EE off and should not give users the choice to turn it back on.

1. A new config option that forces E2EE off in Element Web for all room types would meet this requirement.
2. There also seems to be a regression on https://github.com/vector-im/element-web/issues/13705. It states the following:

> Riot shouldn’t prompt users who haven't bootstrapped or enabled cross-signing to do so
> * On sign up & login, toasts, banners: all hidden
> * However, once the user has joined an E2EE room, toasts to setup cross-signing should still appear

However, with a newly created user that has never joined an E2EE room on a homeserver with .well-known configured for E2EE `“default”: false`, the following prompts are presented which make no sense in this context:

![image](https://github.com/vector-im/element-web/assets/56165341/3e40c19c-fbe4-49e4-85cf-576bfc3b7be9)

So there are 2 issues here (1 enhancement request and 1 bug report), but both are related to the fact that we want E2EE forced off in Element Web & Desktop. Please let me know if I should split this into 6 separate issues instead.

**Comment by t3chguy** [comment] 2023-06-14 12:26
Duplicate of https://github.com/vector-im/element-meta/issues/292

**Closed by t3chguy** 2023-06-14 12:26 UTC
Labels: T-Enhancement
