### ISSUE TITLE
I do get artefacts drawn wrong in the Room / User list 

### ISSUE THREAD

**Issue by LutzLange** [vector-im/element-web#23912] opened 2022-12-06 09:09 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

I'm running on Ubuntu.

```
lutz@lutzbox:~/Archive$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
```

I do have these element packages installed 
```
element-desktop/unknown,now 1.11.15 amd64 [installed]
element-nightly/unknown 2022120501 amd64
```

The room Danielle is selected, hovering over room Anthony21 right above will produce artifacts / icons in the wring place : 

![Screenshot from 2022-12-06 10-00-06](https://user-images.githubusercontent.com/2788194/205868803-ecfbc849-fc28-4dbd-96b0-e2c7180fb36f.png)

Please fix.

#### What did you expect?

clear drawns icons and names

#### What happened instead?

![Screenshot from 2022-12-06 10-00-06](https://user-images.githubusercontent.com/2788194/205868762-1bba91d6-8464-4041-809c-09ca23493eb9.png)

### Operating system

Ubuntu

### Application version

Element version: 1.11.15 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2022-12-06 09:20
Duplicate of https://github.com/vector-im/element-web/issues/22891

**Comment by weeman1337** [comment] 2022-12-06 09:20
Thanks for reporting @LutzLange . This may be a duplicate. If you think this is another issue please leave a comment.

**Closed** 2022-12-06 09:21 UTC
Labels: T-Defect
