### ISSUE TITLE
Same reaction emoji counted twice

### ISSUE THREAD

**Issue by elias-pap** [vector-im/element-web#23752] opened 2022-11-10 20:12 UTC
### Steps to reproduce

Screenshot:
![duplicate-reaction-bug](https://user-images.githubusercontent.com/18152197/201195675-1436004b-cdf7-4aa9-93b3-8825c818df6e.png)
Message source code:
```
{
  "content": {
    "body": "<redacted-for-the-bug-report>",
    "msgtype": "m.text"
  },
  "event_id": "$166706684330495EBckF:matrix.org",
  "origin_server_ts": 1667066843689,
  "room_id": "<redacted-for-the-bug-report>",
  "sender": "<redacted-for-the-bug-report>",
  "type": "m.room.message",
  "unsigned": {
    "age": 1042354920,
    "m.relations": {
      "m.annotation": {
        "chunk": [
          {
            "type": "m.reaction",
            "key": "👍️",
            "count": 5
          },
          {
            "type": "m.reaction",
            "key": "👍",
            "count": 1
          }
        ]
      }
    }
  },
  "user_id": "<redacted-for-the-bug-report>",
  "age": 1042354920
}
```
Hexdump of file containing the first emoji (with count 5):
```
0000000 9ff0 8d91 b8ef 008f                    
0000007
```
Hexdump of file containing the second emoji (with count 1):
```
0000000 9ff0 8d91                              
0000004
```

#### What did you expect?
I expected a single reaction with count 6.
#### What happened instead?
Two reactions with identical emojis, one with count 5 and another one with count 1.

### Operating system

MacOS Ventura 13.0 (22A380), Apple M2 chip

### Browser information

Version 107.0.5304.110 (Official Build) (arm64)

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.11.14 Olm version: 3.2.12

### Homeserver

Homeserver is https://matrix-client.matrix.org, Identity server is https://vector.im

### Will you send logs?

No

**Comment by weeman1337** [comment] 2022-11-11 08:33
Hi @elias-pap thanks for reporting the issue and sending the message source. The issue was already reported. To keep yourself updated about the progress follow the duplicated issue.

**Comment by weeman1337** [comment] 2022-11-11 08:33
Duplicate of #23558

**Closed by weeman1337** 2022-11-11 08:33 UTC
Labels: T-Defect

**Comment by t3chguy** [comment] 2022-11-11 09:16
@elias-pap are you able to find out which client software sent the one which isn't being grouped with the rest? This one lacks the [variant 16 selector](https://emojipedia.org/variation-selector-16/#:~:text=An%20invisible%20codepoint%20which%20specifies,character%20defaults%20to%20text%20presentation.) which the spec says it should include

**Comment by elias-pap** [comment] 2023-01-01 12:42
Just confirmed that the client is the Element android app, and the bug is still reproducible.

<img src="https://user-images.githubusercontent.com/18152197/210170820-505d0f02-0d88-4708-9f76-cf646bc367f6.png" width="40%" height="40%">

**Comment by t3chguy** [comment] 2023-01-03 11:01
@elias-pap the Element Android developers don't check the element-web repo issues
