### ISSUE TITLE
Room message preview is one message behind

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#20158] opened 2021-12-13 11:09 UTC
### Steps to reproduce

![previews](https://user-images.githubusercontent.com/1342360/145800736-ecbb0764-289c-40b8-a34c-66b0517a890a.jpg)

I often see the message preview of the room list showing the second-latest message in the room, rather than the latest. It's the exception rather than the norm however.

#### What did you expect?

To see the latest message in the room message preview.

#### What happened instead?

The second-latest is shown instead.

Possibly related: https://github.com/vector-im/element-web/issues/17477. I've noticed this latest version after resuming my computer from suspend. But this message should have been pulled in from an incremental sync, rather than being lost due to a gappy one.

### Operating system

Arch Linux

### Application version

Element version: 1.9.6, Olm version: 3.2.3

### How did you install the app?

Arch Linux Repos

### Will you send logs?

Yes

**Comment by robintown** [comment] 2021-12-13 19:57
Duplicate of https://github.com/vector-im/element-web/issues/17893

**Closed by robintown** 2021-12-13 19:57 UTC
Labels: T-Defect, S-Minor, A-Room-List, A-Message-Previews, O-Frequent
