### ISSUE TITLE
Original message obscures reply in Windows 10 notifications

### ISSUE THREAD

**Issue by ZenKyma** [vector-im/element-web#23939] opened 2022-12-08 01:02 UTC
### Steps to reproduce

1. Write a looong message to someone
2. Receive a reply to your long message
3. Confirm that the actual reply is not visible because the original message takes up all the space

#### What did you expect?

When I receive a reply to one of my messages, it is the content of the reply that is of interest and should be properly displayed.
Maybe it suffices to identify the reply by a symbol or small text after the sender's name, in a way that it does not take up space for the actual message.

#### What happened instead?

When I receive a reply to one of my messages, typically the content of my original message displaces the more interesting content of the reply.

![image](https://user-images.githubusercontent.com/116916092/206328828-1a8f0d37-8d11-4a4b-87b1-233a8c46eb0d.png)

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2022120701 Olm version: 3.2.12

### How did you install the app?

From https://element.io/get-started

### Homeserver

Synapse v1.73.0

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-12-08 09:37
Duplicate of https://github.com/vector-im/element-web/issues/9119

**Closed by SimonBrandner** 2022-12-08 09:37 UTC
Labels: T-Defect
