### ISSUE TITLE
Create a publicly accessible room

### ISSUE THREAD

**Issue by TROMsite** [vector-im/element-web#18191] opened 2021-07-22 19:07 UTC
I am using Netxcloud Talk for our project and one great feature is that you can easily create a public room that can be accessed via a unique URL. This is great since no one has to login or install any apps in order to join. How come this is not possible with Matrix? And do you plan to add such a feature?

**Comment by robintown** [comment] 2021-07-22 22:07
Element used to have that feature, which is called ILAG. So this is essentially a duplicate of https://github.com/vector-im/element-web/issues/9264

**Closed by robintown** 2021-07-22 22:07 UTC
Labels: T-Enhancement

**Comment by robintown** [comment] 2021-07-22 22:40
Actually, it *should* still be possible to make a room accessible to guests (via room settings join rules) and then just send people the matrix.to link, though I'm not super confident this is working

**Comment by t3chguy** [comment] 2021-08-04 20:09
Only if they're using Element, other clients may let them use guest accounts. Element does not.

**Comment by t3chguy** [comment] 2021-08-04 20:13
Element Web will not allow you to chat using guest users. You will need to find another Matrix client for that purpose.

**Comment by tio-trom** [comment] 2021-08-04 20:15
Ok. So why doesn't it allow to use the element-web for such public rooms? Seems a lot more convenient.

**Comment by t3chguy** [comment] 2021-08-04 20:16
See the issue you were linked to https://github.com/vector-im/element-web/issues/9264

Locking this issue as it is going around in circles.
