### ISSUE TITLE
Sentence starting with /confetti cannot be amended

### ISSUE THREAD

**Issue by AlexandraGhi** [vector-im/element-web#23182] opened 2022-09-01 12:33 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

I wrote /confetti Joyeux anniversaire @Giom + emojis then i pressed enter. 
It  didn't work to ping Giom properly (that may be also another bug) this way so i wanted to edit the sentence but i couldn't.

![image](https://user-images.githubusercontent.com/96295926/187913035-78bd34e9-25e5-42f9-8fc8-b19c42451472.png)

3. What do you click?
![image](https://user-images.githubusercontent.com/96295926/187913100-b9f243ce-ba1b-4dfe-80ca-c88dbd52cfbd.png)

5. More steps…

#### What did you expect?

To ping Giom correctly and to be able to edit the sentence.

#### What happened instead?

Could edit the sentence ah to wrote another message to ping Giom properly.

(same issue on Android)

Reach me if you need more info

### Operating system

Windows

### Application version

Element version: 1.11.4 Olm version: 3.2.12

### How did you install the app?

From the website element

### Homeserver

?

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-09-01 13:33
Duplicate of https://github.com/vector-im/element-web/issues/17976

**Closed by SimonBrandner** 2022-09-01 13:33 UTC
Labels: T-Defect
