### ISSUE TITLE
Multiple Audio tracks (old ones are not closing) in web and client

### ISSUE THREAD

**Issue by YourSandwich** [vector-im/element-web#19294] opened 2021-10-05 16:06 UTC
### Steps to reproduce

Running Arch Linux kernel 5.14.9
DE: KDE Plasma
Sound: pipewire.

1. Launch Element in web or in native client.
2. Take a call. -> in Sound Manager applications new Chromium pipes appear.
3. Close the call -> The Tracks are still here.
4. Take a call again and even more tracks open.

#### What did you expect?
A call opens 1 or 2 tracks maybe an option for selection channel count.
After call closes the tracks disconnect/close

#### What happened instead?
Element opens multiple tracks and dont close them afterwards

### Operating system

Linux

### Browser information

Chromium: 94.0.4606.61 

### URL for webapp

1.8.5-1

### Homeserver

matrix.archgang.xyz

### Will you send logs?

Yes

**Comment by gsouquet** [comment] 2021-10-07 08:24
Adding privacy as this could be interpreted the wrong way and some users might assume malicious intentions here

**Comment by SimonBrandner** [comment] 2021-10-31 09:43
So I think we aren't correctly stopping the audio elements, I don't seem to be able to repro with Jitsi

**Comment by SimonBrandner** [comment] 2021-10-31 10:38
So, I think I managed to get the `AudioFeeds` behaving (no idea how) but we still have some 6 `audio` elements which never get unmounted and they are never paused (those are for notifs, ringing and stuff like that)

**Comment by SimonBrandner** [comment] 2021-10-31 10:44
> So, I think I managed to get the `AudioFeeds` behaving (no idea how) but we still have some 6 `audio` elements which never get unmounted and they are never paused (those are for notifs, ringing and stuff like that)

Apparently, my changes had no effect and this was the behavior before them? Though, Electron seems to be doing something different

**Comment by SimonBrandner** [comment] 2021-10-31 10:47
> Though, Electron seems to be doing something different

I can find only 6 audio elements though my audio mixer is showing way more than that :thinking:

**Comment by YourSandwich** [comment] 2021-11-02 15:07
> > Though, Electron seems to be doing something different
> 
> I can find only 6 audio elements though my audio mixer is showing way more than that thinking

Tell me if i can support you somehow.

**Comment by SimonBrandner** [comment] 2021-11-02 17:11
> > > Though, Electron seems to be doing something different
> > 
> > 
> > I can find only 6 audio elements though my audio mixer is showing way more than that thinking
> 
> Tell me if i can support you somehow.

I don't think we need help atm, since we have a clear reproduction case

**Comment by SimonBrandner** [comment] 2021-11-17 08:05
@robertlong has suggested this could be caused by us not stopping the tracks correctly, though as far as I can tell, the bits of code that stop tracks look ok

**Comment by phoxmeh** [comment] 2022-03-02 22:49
I have been experiencing this myself for the past few months with all recent updates and it seems to get to a point where if I've had a few calls in the day pulse refuses to let any new applications create a new track until I completely kill Element to release all the tracks.

**Comment by YourSandwich** [comment] 2022-03-02 23:52
Same, thats supper anoying espaccialy if you are working with audio and channel wirering.

I found out this issue does not exist on Firefox. But i can only use Jitsi for calles in firefox and no encryption possible in VoIP

**Comment by turt2live** [comment] 2022-05-17 04:39
fwiw, this is normal for Firefox if you leave it open long enough on Windows with the Audio Mixer also open. Closing the mixer and reopening fixes it on Windows - does that happen to also fix it here?

**Comment by SimonBrandner** [comment] 2022-05-17 06:05
> fwiw, this is normal for Firefox if you leave it open long enough on Windows with the Audio Mixer also open. Closing the mixer and reopening fixes it on Windows - does something similar happen to also fix it here?

Nope, on Linux at least the only way to get rid of the tracks is to kill Element

**Comment by YourSandwich** [comment] 2022-05-17 10:25
On Firefox i don't have this bug somehow. So i imagine this has something to do with the Chromium engine.

**Comment by robintown** [comment] 2022-06-10 21:56
@turt2live theorizes that this could have the same underlying cause as https://github.com/vector-im/element-call/issues/267 (that we're cloning MediaStreams for Safari support)

**Comment by lukas-lang** [comment] 2022-08-06 15:17
I'm pretty sure I am experiencing the same issue on Windows. For me, this causes issues with my headphones: The headphones can connect to multiple devices at once, but will only play audio from one. Since the audio is not properly stopped after a voice call, I have to kill Element to "free up" the headphones & get them 
to play audio from other devices again.

**Comment by SimonBrandner** [comment] 2022-08-07 06:03
I do have a hypothesis that this was fixed in Element Call somehow though I have to give it a proper test somehow

**Comment by YourSandwich** [comment] 2022-08-08 09:21
But element call is using WebRTC and element is unsing the chromium engine. Atleast thats what i understand. Maybe thats an bug with the chromium engine itself?

**Comment by The-EDev** [comment] 2022-08-08 10:41
> But element call is using WebRTC and element is unsing the chromium engine. Atleast thats what i understand. Maybe thats an bug with the chromium engine itself?

wouldn't this mean many other web and electron apps would've suffered as a result? So far I've only seen this issue in Element..

**Comment by SimonBrandner** [comment] 2022-08-08 10:42
> But element call is using WebRTC and element is unsing the chromium engine. Atleast thats what i understand. Maybe thats an bug with the chromium engine itself?

They are both using WebRTC. Element uses Chromium engine if you're either using a Chromium browser or Element Desktop (Electron), so the issue probably isn't related to Chromium

**Comment by YourSandwich** [comment] 2022-08-08 21:11
Jup but the issue is not existent on firefox for example. So if you mean that WebRTC is used on firefox then it should have something to do with chomium? or am i wrong here?

**Comment by YourSandwich** [comment] 2022-08-08 21:12
> 

I dont know, maybe its not only chromium itself but its implementation. And discord for example uses WebRTC on Destop leint and in all browsers.

MS Teams uses chromium engine and does not have that issue.

**Comment by SimonBrandner** [comment] 2022-08-10 11:03
Could probably be influenced by Chromium but other Chromium apps don't have this issue, so it seems this is also influenced by our own code

**Comment by Krafting** [comment] 2023-03-07 21:43
Can confirm this on Fedora 37. Also, wouldn't it be possible to replace the "Chromium" text and logo to reflects Element branding instead too ?

**Comment by YourSandwich** [comment] 2023-03-16 12:05
Issue is fixed on ArchLinux and latest Nightly Element build!!!

**Comment by t3chguy** [comment] 2023-03-16 12:11
@YourSandwich do you want to close your own issue then?

**Comment by SimonBrandner** [comment] 2023-03-16 12:26
Ah, yeah, it seems fixed on my side as well - closing 

Let us know if you ever see this again

**Closed by SimonBrandner** 2023-03-16 12:26 UTC
Labels: T-Defect, S-Major, A-VoIP, Privacy, X-Needs-Investigation, O-Occasional
