### ISSUE TITLE
Can't join previous room after upgrade "No known servers"

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-web#11467] opened 2019-11-22 14:49 UTC
### Description

I joined the upgraded #riot-android room. and wanted to see older history. I went to the previous room in the advanced settings and tried joining the old room to see the last history. riot-web didn't know how to join and showed a "No known servers" error.

I have been in the previous room at some earlier point but left long before the room upgrade happened. Which also produced a "can't load specific point in timeline" error when viewing the older room.

### Steps to reproduce

- run your own homeserver
- be in a room
- leave that room
- someone else upgrade the room
- join the new room and try to get back to the previous version
- click "Join Discussion"

I expected to view the old rooms history.

Logs being sent: no

![image](https://user-images.githubusercontent.com/105185/69435281-27c7f680-0d37-11ea-9198-799674062a55.png)

### Version information

- **Platform**:  desktop

For the desktop app:

- **OS**: Ubuntu 18.04
- **Version**: riot-web version: 1.5.3

cc @turt2live

**Comment by Bubu** [comment] 2019-11-22 15:04
Okay, this also happens for rooms I've never been in before. I can't get to the older room from riot-web.

**Comment by kittykat** [comment] 2021-08-04 15:26
@Bubu Has this happened again since? Can you still not join those rooms or did you find a workaround?

**Comment by Bubu** [comment] 2021-08-04 19:22
I guess this is no longer relevant. No idea actually, it's been quite a while.

**Comment by SimonBrandner** [comment] 2021-08-05 05:54
Ok, let's close this. Shout if you ever see this again

**Closed by SimonBrandner** 2021-08-05 05:54 UTC
Labels: T-Defect, X-Needs-Info, Z-Room-Upgrade-2019

**Comment by Andrew15-5** [comment] 2023-07-26 20:07
I'm not super familiar with all implementation things in Matrix, but it seems to me I have a similar issue. If not, please, give me any advice on how to solve the problem or where to get help.

I've created a new room or DM, which is skinned as my Telegram self-DM. After some time it said that I should upgrade the room and that I still will be able to see all the previous messages. And it worked as intended. But today I again was going to look up something in the old room, and suddenly I can't access it. There was somewhat valuable information in there, so I really hope I can access it somehow. But I only have a link to it in the room. Fluffychat have no information that there was some old room (but I think it did show the old room as a separate room in the list, but now it disappeared).

![image](https://github.com/vector-im/element-web/assets/37143421/a884d6b4-8656-41ed-ae7b-60cf648e6cd7)

![image](https://github.com/vector-im/element-web/assets/37143421/c218d66d-f734-41ea-8547-573089914fc2)

![image](https://github.com/vector-im/element-web/assets/37143421/96c32164-c212-49ce-8e39-f56a92597808)

**Comment by Andrew15-5** [comment] 2023-07-26 21:55
Hmm, now in the Android Element app the bottom part with input field just disappears in the same upgraded room, but not in the other rooms, very strange. I also tried using the "go to older messages" in Android app and this is what I get:

![image](https://github.com/vector-im/element-web/assets/37143421/b376b533-43af-4faa-82d9-06482bb130d5)

When I instead have a "join server" popup, then I get:

![image](https://github.com/vector-im/element-web/assets/37143421/fd7254cb-b7f5-4a9f-95fc-0d48a07e9ebf)

(This is the same error as in the title.)

**Comment by Andrew15-5** [comment] 2023-07-29 12:01
I even tried removing all the data & re-installing the app. This room (upgraded) definitely has some bug, that make is "read-only" on Element Android app. Works fine on web, Linux, and all Fluffychat.
