### ISSUE TITLE
trying to download m4a opens it in a new tab/browser

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#15117] opened 2020-09-08 11:32 UTC
![image](https://user-images.githubusercontent.com/14617699/92470814-ac5d0600-f1df-11ea-8db2-594cb305ffdf.png)

Clicking on `Download` just opens it in a new tab / browser.

Element 1.7.5 desktop or web in FF 80.0.1 Debian sid.

**Comment by t3chguy** [comment] 2020-09-08 11:34
Duplicate of https://github.com/vector-im/element-web/issues/12405

**Closed by t3chguy** 2020-09-08 11:34 UTC
Labels: bug

**Comment by 532910** [comment] 2020-09-08 11:37
Thank you.
