### ISSUE TITLE
Poor mobile experience with guest access

### ISSUE THREAD

**Issue by mocalv** [vector-im/element-web#23225] opened 2022-09-06 21:37 UTC
### Steps to reproduce

1. Create room
2. Enable guest access
3. Open link as a guest on a mobile phone (join the room without having a registered account)

#### What did you expect?
A user friendly view 

#### What happened instead?
<img src="https://user-images.githubusercontent.com/30929452/188744931-6bf6ef7b-a8b4-4e9e-b822-dc216b3fc721.png"  height="600">

### URL for webapp

app.element.io/#/room

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-09-06 21:43
Duplicate of https://github.com/vector-im/element-web/issues/1633

Also worth noting mobile support is experimental in favour of the dedicated native apps. https://github.com/vector-im/element-web#supported-environments

**Closed by t3chguy** 2022-09-06 21:43 UTC
Labels: T-Defect
