### ISSUE TITLE
The "Send your first message to invite X to chat!" screen and your in-progress message is gone if you navigate away from it

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#24510] opened 2023-02-13 14:05 UTC
### Steps to reproduce

1. Click on a user's profile that you don't yet have a DM with and then click "Message"
2. You will be presented with an interim screen where you can type out a message before the recipient is invited to a DM room with you.
3. If you are typing out a long message, you may need to navigate to another room to get information to include in your message.
4. If you do so, and then hit back, you are not brought back to the interim screen - that screen disappears from your history and your breadcrumbs, along with your in-progress message.

#### What did you expect?

To be able to hit back in my browser and return to my in-progress message.

#### What happened instead?

[Screencast from 2023-02-13 14-04-30.webm](https://user-images.githubusercontent.com/1342360/218479419-bb7dba53-dc1d-415c-a502-f900af77723e.webm)

My message was lost - frustrating!

### Operating system

NixOS

### Application version

Element version: 1.11.20 Olm version: 3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-02-13 14:06
Duplicate of https://github.com/vector-im/element-web/issues/23196

**Closed by t3chguy** 2023-02-13 14:06 UTC
Labels: T-Defect
