### ISSUE TITLE
Invisible scroll bar on code blocks with dark theme

### ISSUE THREAD

**Issue by Yajo** [vector-im/element-web#16340] opened 2021-02-02 08:12 UTC
### Description

Code blocks on dark theme hide the scroll bar.

### Steps to reproduce

Code block on dark theme:

![screenshot-2021-02-02-08-10-20](https://user-images.githubusercontent.com/973709/106570683-22b32980-652e-11eb-99b3-0dbd98d88641.png)

On white theme (here you can see the scroll bars):

![image](https://user-images.githubusercontent.com/973709/106570743-31014580-652e-11eb-9843-64781d093600.png)

On dark mode, you can actually use the scroll bars, but you need to imagine where they are.

Logs being sent: n/a

### Version information

- **Platform**: desktop
- **OS**: Fedora 33 silverblue
- **Version**: 1.7.18

**Comment by SimonBrandner** [comment] 2021-02-02 08:41
Hmmm, that seems to be the case. Some time ago I've opened [this PR](https://github.com/matrix-org/matrix-react-sdk/pull/5559) which does a bunch of changes to displaying of code blocks. When that is merged, I'll look into this.

I generally think that the colours may need some tweeking.

**Comment by t3chguy** [comment] 2021-02-04 15:36
Duplicate of https://github.com/vector-im/element-web/issues/9052

**Closed by t3chguy** 2021-02-04 15:36 UTC
Labels: bug
