### ISSUE TITLE
No option to hide dm chats in a space from the main chat list.

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20199] opened 2021-12-15 06:06 UTC
#### What would you like to do?
Hide dm chats in a space from the main chat list.
#### Why would you like to do it?
This is an essential feature for anyone who has multiple bridges with tens -> hundreds of chats each, all of which should be lower priority than native rooms & to reduce room clutter :p.
### Have you considered any alternatives?

Low priority button, but this is a bandaid fix since it still appears on the main space, keeping visual clutter.

**Comment by dbkr** [comment] 2021-12-17 11:33
So the goal here would be to hide the 'people' section and have those rooms appear in some other place?

**Comment by SimonBrandner** [comment] 2022-01-09 07:00
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19649

**Closed by SimonBrandner** 2022-01-09 07:00 UTC
Labels: X-Needs-Info, T-Enhancement
