### ISSUE TITLE
Space aliases cannot be managed through the UI

### ISSUE THREAD

**Issue by kakolisgay** [vector-im/element-web#17341] opened 2021-05-17 18:57 UTC
### Description

The current Spaces UI doesn't provide any way to assign or manage room<sup>(space?)</sup> aliases. The room addresses manager could probably be reused, although the settings ui would need to be tweaked a bit to fit it

**Comment by t3chguy** [comment] 2021-05-17 18:58
Duplicate of https://github.com/vector-im/element-web/issues/17244

**Closed by t3chguy** 2021-05-17 18:58 UTC
Labels: T-Defect
