### ISSUE TITLE
How are notification under Windows are supposed to look like?

### ISSUE THREAD

**Issue by awesome-michael** [vector-im/element-web#10280] opened 2019-07-08 08:42 UTC
I'm using Riot quite a while now and I wondered why the Window clients doesn't show notifications like the Mac client does. The windows 'notifications' are so subtle that new messages are sometimes not noticed.
Is this normal/expected behaviour or are the notifications faulty on my Windows systems?

Screenshots:
MacOS notification
![riot1](https://user-images.githubusercontent.com/37796947/60795609-405eb800-a16c-11e9-94a4-d8b91ee3a81d.jpg)

Windows notification
This screenshot shows the notification when the client is minimized and the tray icon is forced to show on the taskbar. When the client window is closed and the tray icon hides behind the arrow there is no notification for new messages visible.
![riot2](https://user-images.githubusercontent.com/37796947/60795688-61bfa400-a16c-11e9-8a4a-df381ed08e3b.jpg)

Maybe this is linked to #4945?

### Version information

Platforms:
macOS HighSierra, Riot-Web Version 1.2.2
Windows 10, Riot-Web Version 1.2.2

**Comment by turt2live** [comment] 2019-07-08 15:27
They're supposed to look something like this:
![image](https://user-images.githubusercontent.com/1190097/60822318-77c86700-a162-11e9-9562-2c9385a58ecc.png)

If your notification settings look like the following, you won't receive the toast:
![image](https://user-images.githubusercontent.com/1190097/60822374-8f9feb00-a162-11e9-9f3a-52d25a214848.png)

If they are enabled, it's probably https://github.com/vector-im/riot-web/issues/4945

**Comment by awesome-michael** [comment] 2019-07-08 18:26
Yes.. all these settings are switched on. I updated to 1.2.3 but it's still the same.
I also reinstalled the client a few weeks ago because I read about Electron, notifications and that the path settings have to be correct and are set during installation.

Are there any things I could test to help identifying the problem? I run my own instance of Synapse so I could test pretty much everything.

**Comment by turt2live** [comment] 2019-07-08 18:32
We'd have to look into it more, and would need logs to do that. To send us logs: go to your settings then on the "Help & About" tab click "Send Debug Logs", using this issue as the Github issue.

**Comment by awesome-michael** [comment] 2019-07-11 08:27
Have uploaded Debug Logs two days ago. Did they provide any useful information? Could I check something else?

**Comment by turt2live** [comment] 2019-07-11 10:20
I haven't had a chance to take a look yet. I was hoping that someone who knew the notifications system better than I would take a look. 

Asking for some help in #riot:matrix.org might yield some results, although I'm not sure.

**Comment by nE0sIghT** [comment] 2020-05-20 08:39
Should Windows 10 notifications persist in Notification Center?
Using Riot 1.6.0 Desktop with Windows 10 1909 notifications appears for about 5 seconds and disappeared.

**Comment by t3chguy** [comment] 2020-05-20 08:44
Mine persist in the Notif center on Windows 10.

**Comment by t3chguy** [comment] 2023-02-01 11:16
Closing due to no reproductions in 2+ years

**Closed by t3chguy** 2023-02-01 11:16 UTC
Labels: A-Notifications, A-Electron, T-Other, X-Needs-Community-Testing, Z-GetYourUpdates
