### ISSUE TITLE
Riot/Web only backed up 1% of Manu's keys

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13115] opened 2020-04-10 03:33 UTC
https://github.com/matrix-org/riot-web-rageshakes/issues/2569

**Comment by bwindels** [comment] 2020-04-10 08:52
After having a quick look, only thing I can see in the shakes is some network failure related to the key backup endpoint (doesn't seem to mention with method was used):
```
2020-04-09T16:56:21.761Z I Key backup request failed CORS request rejected: https://matrix-client.matrix.org/_matrix/client/unstable/room_keys/keys?version=19
Error: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/unstable/room_keys/keys?version=19
    at on_response (webpack-internal:///143:254:22)

2020-04-09T16:56:52.884Z I Key backup request failed CORS request rejected: https://matrix-client.matrix.org/_matrix/client/unstable/room_keys/keys?version=19
Error: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/unstable/room_keys/keys?version=19
    at on_response (webpack-internal:///143:254:22)
```

**Comment by bwindels** [comment] 2020-04-10 08:53
Could be related to https://github.com/vector-im/riot-web/issues/12970

**Comment by jryans** [comment] 2020-04-14 16:39
@manuroe Can you please retest this case? We've fixed a number of backup related issues, so would be good to see if this is also fixed for you.

**Comment by jryans** [comment] 2020-04-17 14:03
Seems like an issue on the iOS side if I understand https://github.com/vector-im/riot-ios/issues/3090 correctly.

**Comment by manuroe** [comment] 2020-04-20 14:31
I have not experimented myself again but Giom had a similar issue on last Friday: https://github.com/matrix-org/riot-web-rageshakes/issues/2647.

> Seems like an issue on the iOS side if I understand vector-im/riot-ios#3090 correctly.

Issues are not related. Key share requests and key backup are two different mechanisms. If key backup restoration works, we do not need to send key share requests.

Riot-iOS is mentioned here only because it logs the number of keys available in the key backup. This number does not match the expected one.

**Comment by kittykat** [comment] 2021-12-09 16:17
@manuroe have you experienced the issue recently? There have been changed to the code since then so it may have been fixed. Cannot reproduce from this side.

**Comment by kittykat** [comment] 2021-12-16 17:05
I'm going to close this issue for now as it's old and we cannot action it based on available information. Please file a new one if you experience this problem.

**Closed by kittykat** 2021-12-16 17:05 UTC
Labels: T-Defect, A-E2EE-Cross-Signing, X-Needs-Community-Testing
