### ISSUE TITLE
"Something went wrong!" when joining a room

### ISSUE THREAD

**Issue by Spencer-0003** [vector-im/element-web#23348] opened 2022-09-23 17:33 UTC
### Steps to reproduce

1. Join a space
2. Join a room

#### What did you expect?
Join a room successfully.

#### What happened instead?
![image](https://user-images.githubusercontent.com/36741900/192023759-3e406b1b-6006-47ac-862a-e5d73776c73f.png)

### Operating system

Arch Linux

### Application version

element-desktop-git 1.11.1.r31.g070f4735cd-1

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-git

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-09-23 17:34
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-09-23 17:34 UTC
Labels: T-Defect
