### ISSUE TITLE
missing translation: en-us|Submit debug logs

### ISSUE THREAD

**Issue by grinapo** [vector-im/element-web#15527] opened 2020-10-22 10:15 UTC
### Description

https://riot.im/develop/ shows everything untranslated.

Probably would require reload or cache clear. Seems language independent, so probably some internal structures were changed in the meantime.

### Steps to reproduce

- revive long time running tab
- fun.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**:  Firefox nightly, long-running tab deactivated by some tab-unloading extension, then revived
- **OS**: Debian/sid
- **URL**: https://riot.im/develop/
 Element version: dae2f6c442db-react-ca4e7202aed6-js-f27db16e3098

Log follows shortly.

**Comment by grinapo** [comment] 2020-10-22 10:16
neither reload nor cache-reload fixed it. log sent.

**Comment by t3chguy** [comment] 2020-10-22 10:18
Duplicate of https://github.com/vector-im/element-web/issues/12591 - logs will still be helpful, thanks

**Closed by t3chguy** 2020-10-22 10:18 UTC
