### ISSUE TITLE
Expand sidepanel "lip" is not darkened when in dark mode

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20079] opened 2021-12-07 10:03 UTC
### Steps to reproduce

(Design issue)

#### What did you expect?

A similarly-themed button.

#### What happened instead?

![image](https://user-images.githubusercontent.com/22740616/145008536-fbd034c9-c56e-4e37-bcae-69f1bfb62640.png)

### Operating system

Linux

### Browser information

Brave (Version 1.26.67 Chromium: 91.0.4472.114)

### URL for webapp

develop.element.io

### Application version

Element version: b0abbfacd48b-react-b4b81a455e14-js-39a8399977af Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ShadowJonathan** [comment] 2021-12-07 10:03
cc @t3chguy & https://github.com/vector-im/element-web/issues/17993

**Comment by t3chguy** [comment] 2021-12-07 10:43
It is meant to be inverted by design. In light theme it is very dark.

**Comment by ShadowJonathan** [comment] 2021-12-07 11:01
It's extremely contrasting and does definitely sticks out, but in a "this looks like a theming fault", this feels like I'd see on a website with wonky CSS, thus this issue.

**Comment by t3chguy** [comment] 2021-12-07 11:05
Yup, I agree, hence me passing it onto Design rather than closing it

**Comment by HarHarLinks** [comment] 2021-12-08 11:13
It further "looks like a UI fault" because
- no animation
- not clearly attached or behind the spaces panel or similar, the color doesn't help with that
- overlays the Ctrl+K filter bar randomly
- hidden in place, will suddenly pop up when you hover over it while hidden
- pops up when hovering spaces bar anywhere
- doesn't follow the usual pattern for resizable panels (drag handle)

It feels like something where a bit more of a concept exists but it was implemented in parts and only this basic part has made it to the nightly/develop so far.

**Comment by robintown** [comment] 2021-12-08 15:42
To reiterate the feedback I had in #20094:

> The space panel expand button appears in the top left corner of the screen, which is distracting given how high-contrast and attention-drawing its appearance is. It's strange to see it appear no matter where or for how long I hover over the bar, since a lot of the time I'm looking at something far down in the space list, or even just moving my cursor through the bar to get to other parts of the screen. In both of these cases, it's surprising to see something flicker on/off so far away from the things I'm interacting with, and at such a high-importance location in the window.

**Comment by turt2live** [comment] 2021-12-08 17:56
having encountered this after updating to latest nightly, it's incredibly distracting and unclear. It feels more like a bookmark tab or broken UI at the moment.

Inverted styling isn't really helping with this.

**Closed** 2021-12-13 14:59 UTC
Labels: T-Defect, S-Minor, A-Room-List, A-Spaces, A-Appearance, O-Occasional
