### ISSUE TITLE
Thread content can jump around on hover

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#19906] opened 2021-11-26 12:11 UTC
https://user-images.githubusercontent.com/2403652/143579187-dcb11801-c515-49bf-9433-db41c1cc5916.mov

**Comment by gsouquet** [comment] 2021-11-26 16:11
Duplicate of https://github.com/vector-im/element-web/issues/19799

**Closed by gsouquet** 2021-11-26 16:11 UTC
Labels: A-Threads
