### ISSUE TITLE
Element on Windows puts deleted desktop shortcut back after update

### ISSUE THREAD

**Issue by benthetechguy** [vector-im/element-web#21227] opened 2022-02-27 03:36 UTC
### Steps to reproduce

1. Install Element Desktop on Windows
2. Delete shortcut from desktop
3. When there is a new update available for Element, click update inside the app
4. Shortcut is back on desktop

#### What did you expect?
Element shouldn't put a shortcut on the desktop on update, because if the user wanted one it would be there from the initial install.

#### What happened instead?
Element installs a shortcut on the desktop every update.

### Operating system

Windows 10

### Application version

Element version 1.10.4, olm version 3.2.8

### How did you install the app?

From https://element.io/get-started

### Homeserver

fairydust.space

### Will you send logs?

No

**Comment by Wendell250** [comment] 2022-02-27 16:20
Related - #9210

**Comment by t3chguy** [comment] 2022-02-28 07:49
Duplicate of #9210

**Closed by t3chguy** 2022-02-28 07:49 UTC
Labels: T-Defect
