### ISSUE TITLE
Left panel automatically switches to a metaspace when a space is clicked.

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#21064] opened 2022-02-14 10:13 UTC
### Steps to reproduce

1. In a space, look at a DM, then navigate to another space (at this point, I didn't open the webapp for a week)
2. After some time, click on the space in the left panel

#### What did you expect?
(Ideally land on the space explore page)
Last chat I viewed in that space

#### What happened instead?
The last DM that I viewed in that space opened and space in left panel switched to "People" metaspace.

Next time I clicked on the space, it did the right thing.

I've seen this issue happen occasionally over the last few weeks, but it's difficult to reproduce.

### Browser information

Version 98.0.4758.80 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: fa64d65e6e53-react-1c3507bc117a-js-cfad8d361454 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-02-14 10:38
Sounds like a duplicate of https://github.com/vector-im/element-web/issues/20425#issuecomment-1032760720

Correct me if I am wrong

**Closed by t3chguy** 2022-02-14 10:38 UTC
Labels: T-Defect
