### ISSUE TITLE
Cannot delete invitation from non-existent user/room

### ISSUE THREAD

**Issue by verglor** [vector-im/element-web#7384] opened 2018-09-25 11:29 UTC
### Description

If I receive invitation from a user that in the meanwhile does not exist anymore I cannot delete it and there is notification stuck on the browser tab: ![](https://i.imgur.com/mMDkIAj.png)

### Steps to reproduce

Trying to reject invitation:
![](https://i.imgur.com/Jf19iGD.png)

But I am getting the following error since the user no longer exists:
![](https://i.imgur.com/j6PThiY.png)

Neither deleting from settings page works:
![](https://i.imgur.com/9f2pdc6.png)

- **Logs**: sent

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 69
- **OS**: Windows 10 x64
- **URL**: riot.im/app

**Comment by richvdh** [comment] 2020-07-13 17:00
I think this is a duplicate of https://github.com/vector-im/riot-web/issues/3743 and is fixed as of Synapse 1.17.0.

**Comment by richvdh** [comment] 2020-07-13 17:54
actually, it's not quite a duplicate, because the error message is slightly different. The synapse error is https://github.com/matrix-org/synapse/issues/6902.

**Comment by ara4n** [comment] 2021-01-09 12:28
https://twitter.com/whitequark/status/1347766976408670208?s=20

**Comment by richvdh** [comment] 2021-01-11 10:15
> https://twitter.com/whitequark/status/1347766976408670208?s=20
 
almost certainly a different problem (at least on the server side), ftr.

**Comment by t3chguy** [comment] 2022-05-17 08:57
Closing in favour of https://github.com/matrix-org/synapse/issues/6902

**Closed by t3chguy** 2022-05-17 08:57 UTC
Labels: T-Defect, P1, S-Major, Z-Stuck-Invite, Z-Chronic
