### ISSUE TITLE
After an update the traybar pinned status is lost

### ISSUE THREAD

**Issue by litetex** [vector-im/element-web#23071] opened 2022-08-14 14:33 UTC
### Steps to reproduce

1. Pin the element desktop app to the traybar (so that it's always visible), like this:
![grafik](https://user-images.githubusercontent.com/40789489/184541666-79bf5169-7d16-428d-93f6-03e846de3600.png)
2. Wait for the next update

The problem might be caused by the underlying electron/squirrel framework. 
After an update the app is started in a new folder
![grafik](https://user-images.githubusercontent.com/40789489/184541757-e9d2f6c4-c431-47de-950c-ff8020ec7661.png)
which likely causes windows to think it's a new app and therefore it forgets its tray status.

#### What did you expect?
The app stays pinned (status=Always visible)

#### What happened instead?
The app is no longer pinned and I have to manually pin it again

### Operating system

Windows 10

### Application version

Element version: 1.11.2 Olm version: 3.2.12

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-08-15 06:50
Duplicate of https://github.com/vector-im/element-web/issues/4601

**Closed by SimonBrandner** 2022-08-15 06:50 UTC
Labels: T-Defect
