### ISSUE TITLE
Direct chat semantics are simply broken from some clients (Riot/iOS perhaps?)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4425] opened 2017-06-26 21:25 UTC
The whole `m.direct` logic seems to be broken currently for some clients.  To reproduce:

 * 'Start chat' with someone from Riot/iOS
 * Answer the invite on Riot/Web (or possibly Riot/iOS?)
 * Notice that the m.direct status in the invite is ignored, and the room ends up in Rooms rather than People.

**Comment by lampholder** [comment] 2017-06-30 13:19
I wasn't able to reproduce this. My exact steps were:

On iOS:
- Click the green +
- Click 'start chat'
- Click 'search/invite by User ID, Name or email'
- Type in @toml 
- Click the known contact
- Click 'start' on the 'new chat' screen
- Annoyingly get taken to an existing chat, not a new one
- Click the title of that existing room to expand it
- Click on '1/3 Active members' to open the room details
- Click on 'Tom Lant' in that room
- Click 'start new chat'
On Riot Web
- Accept the invite
- Navigate to the chat that seems to be in 'people', not rooms.

**Comment by ara4n** [comment] 2017-06-30 13:39
what about android->ios or ios->ios even? there is categorically some combo which is screwed

**Comment by aaronraimist** [comment] 2019-07-11 16:58
Does this still exist?

**Comment by yannicka** [comment] 2021-12-11 18:10
Is this still the case?

**Comment by kittykat** [comment] 2021-12-16 17:05
I'm going to close this issue for now as we cannot reproduce it and the code has changed significantly since it was filed. Please re-open with more details if it is still happening for you.

**Closed by kittykat** 2021-12-16 17:05 UTC
Labels: T-Defect, P1, S-Major, A-DMs, X-Needs-Community-Testing
