### ISSUE TITLE
Message preview in the room list doesn't unescape some characters

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#17267] opened 2021-05-12 13:21 UTC
![image](https://user-images.githubusercontent.com/5547783/117981637-84591000-b335-11eb-9c1d-a3a9c87ff448.png)

is the preview I get for this message:

![image](https://user-images.githubusercontent.com/5547783/117981727-9c309400-b335-11eb-8cea-58ed7d61ae4e.png)

Seen just now on develop.element.io

**Comment by t3chguy** [comment] 2021-05-12 13:22
Duplicate of https://github.com/vector-im/element-web/issues/17101 and friends

**Closed by t3chguy** 2021-05-12 13:22 UTC
