### ISSUE TITLE
After reloading, clicking a space bounces around to the wrong space

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20425] opened 2022-01-06 19:53 UTC
The steps to reproduce this are difficult, but extremely common in my daily usage:

1. Visit a room within a space which is included in another space. In my case, the Maunium space's Telegram bridge room
2. Visit a different space/room combination to assist in the bug
3. Reload/restart element
4. Click on the space from step 1 - this should bounce you into the space, then out of it again when the room change is detected
5. Repeat for all available spaces. Does not occur after the space has been visited once.

For added context, the t2bot.io space has the Telegram bridge room also listed, and the t2bot.io room is higher on the panel than the Maunium space. I suspect what's happening is a store somewhere is detecting a room change (something -> telegram bridge) and forgetting/ignoring that a space change is also happening and so is trying to find the most relevant space to switch the user to. 

This is additionally problematic when trying to visit community-specific spaces that get overruled by the Matrix Community, Core, and Corp spaces as they are *massive* and have all sorts of rooms.

**Comment by HarHarLinks** [comment] 2022-01-10 14:45
I believe I have the same issue. It happens often that switching to a space, it'll jump back to matrix community space on it's own, but may also to others. It'll always happen the first couple times after reloading/starting element, but then stop happening, very much as described above.

https://user-images.githubusercontent.com/2803622/148784272-e26e3b04-d178-4b03-beaf-aa12c3139989.mp4

**Comment by t3chguy** [comment] 2022-01-11 11:11
I cannot reproduce this on a test account


https://user-images.githubusercontent.com/2403652/148932235-9b383e3d-cd49-497e-9856-6d289815b8d6.mov

**Comment by t3chguy** [comment] 2022-01-11 11:15
Only think of is a weird interplay between `mx_last_room_id` and `mx_active_space` + `mx_space_context_` - will try to clean that up a little

**Comment by dbkr** [comment] 2022-01-11 11:39
This is marked as a release blocker, but it's not looking like it will be a trivial fix, so I'm going to do the RC anyway. We can decide if we need to delay the release to fix this.

Do we know when it regressed?

**Comment by turt2live** [comment] 2022-02-14 15:57
Bumping frequency of this because it's hitting a lot more people more often now.

**Comment by LynHyper** [comment] 2022-02-14 21:45
I'm getting this issue as well, but, the way it's happening is different for me:
1. Start the client for the first time (not minimised in the background).
2. Set it up so when Element starts it will be in the Home space or any other space on the sidebar except the space this issue is affected by (in my case, the IPFS room always bounces and no other space does)
3. Click on the afflicted space and see it quickly highlight and de-highlight the space (Bounce).
4. Restart the client and notice it now starts with Element showing a room within the afflicted space despite the fact that this space wasn't being shown before, possibly implying it *thought* it was showing the user that space even though the bounce occured.

**Closed** 2022-03-01 08:33 UTC
Labels: T-Defect, X-Regression, S-Major, A-Spaces, Z-t3chguy, O-Frequent
