### ISSUE TITLE
Cannot upload audio-only .webm file

### ISSUE THREAD

**Issue by foresto** [vector-im/element-web#14453] opened 2020-07-13 21:40 UTC
### Description

Attempting to upload a .webm file fails, regardless of whether through drag-and-drop or clicking the paperclip icon. The "Upload files" dialog correctly appears, but when I confirm by clicking the "Upload" button, the "Uploading filename.webm" message remains forever stuck at "0 B / <total> MB".

If I rename the same file to give it a .webmx suffix, uploading works.

### Steps to reproduce

- Drop a .webm file onto Riot, or select it from the paperclip icon.
- Confirm that you want to upload the file.
- Watch it claim to be uploading, with no progress, ever.

This appeared in the Electron console log:

    vendors~init.js:2 Starting load of AsyncWrapper for modal
    vendors~init.js:2 Uncaught TypeError: Cannot read property 'type' of null
        at vendors~init.js:2
    (anonymous) @ vendors~init.js:2

![stalled webm upload](https://user-images.githubusercontent.com/322134/87356145-6b65af80-c516-11ea-8090-0f2f90e35ed4.png)

- Attempting to exit the program also fails while the stalled upload is still present. Canceling the upload allows the program to exit.

### Version information

- **Platform**: desktop
- **OS**: Ubuntu 19.10
- **Version**: 1.6.8 (flathub)

**Comment by t3chguy** [comment] 2020-07-14 01:13
Duplicate of https://github.com/vector-im/riot-web/issues/14328

**Comment by foresto** [comment] 2020-07-14 01:32
@t3chguy Are you sure it's a dupe? That bug is about HEVC video encoding. This one is about an audio-only file, and the problem goes away when the same file has a different name.

**Comment by t3chguy** [comment] 2020-07-14 01:44
Ah well then it's your browser saying its a video file yet refusing to generate a thumbnail for it i bet, will leave open until I can confirm

**Comment by foresto** [comment] 2020-07-14 01:48
It's Electron, then. This is the desktop app.

**Comment by t3chguy** [comment] 2020-07-14 07:59
So this is a browser bug where it says the File type for an audio-only webm file is
![image](https://user-images.githubusercontent.com/2403652/87398346-a961e280-c5ad-11ea-9767-311336b3822d.png)

You can try it out yourself here: https://jsfiddle.net/dgw07tjh/1/

This boils down to a combination of 

https://github.com/vector-im/riot-web/issues/7370 (Browser reports file type incorrectly)
and
https://github.com/vector-im/riot-web/issues/14328 (Chromium chokes differently [harder] than Firefox on trying to thumbnail an incompatible video/not a video)

The fix for #14328 might be to send as a regular file without being playable if not able to thumbnail, causing something like https://github.com/vector-im/riot-web/issues/7370 and https://github.com/vector-im/riot-web/issues/14330

There is no sane way to detect the file type ourselves in client-side JS and we can't use any services for it due to the privacy issues with that, especially for encrypted rooms.

I have reported it to
Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1105377
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1652680

**Comment by foresto** [comment] 2020-07-18 07:46
> There is no sane way to detect the file type ourselves in client-side JS

How about catching the exception and handling it gracefully? That could mean just retrying the upload as an opaque file without type information. If that's not possible, at least letting the user know that Element can't handle file names with certain suffixes would be helpful; much better than just getting stuck with an "uploading" message that never progresses.

**Comment by t3chguy** [comment] 2020-07-18 09:23
Yup that is what I suggested as I said above.

> The fix for #14328 might be to send as a regular file without being playable if not able to thumbnail, causing something like #7370 and #14330

Its not whether element can handle the suffixes, it's whether your browser can.

**Comment by foresto** [comment] 2020-07-18 09:47
> Its not whether element can handle the suffixes, it's whether your browser can.

My browser has nothing to do with it. This is the Element desktop app.

**Comment by t3chguy** [comment] 2020-07-18 10:24
In which case it depends on the version of Chromium is used by Electron, which can vary depending on which repository you install the app from.

**Comment by DooMMasteR** [comment] 2020-11-07 00:05
In my case it is also still broken on current Chrome :-(

**Comment by t3chguy** [comment] 2022-05-23 19:55
The app now will fall back to uploading an `m.file` if the thumbnail generation fails

**Closed by t3chguy** 2022-05-23 19:55 UTC
Labels: T-Defect, Z-Platform-Specific, A-Media, Z-Upstream, A-File-Upload
