### ISSUE TITLE
Set HS for registration or login at Guest accounts

### ISSUE THREAD

**Issue by awesome-michael** [vector-im/element-web#11294] opened 2019-11-02 11:28 UTC
Scenario:

I have a self hosted Homeserver (matrix.example.org) and use the "Share room" functionality which generates me a link, e.g. `https://matrix.to/#/!xyz123:matrix.example.org?via=matrix.example.org`. I send that link to a person that follows the link and getting to matrix.to to choose a client. Assuming he took Riot.im he joins the server 'matrix.example.org' and gets a prompt to register an account or log in.
In both cases the dialog has set the default Homeserver (matrix-client.matrix.org). If the user doesn't recognize this he may register for an account on matrix.org and not be able to join the room he was invited to.
Is it possible to set the homeserver for registering or login to the one given by the link?

**Comment by binarymaster** [comment] 2021-11-07 17:10
Looks like a duplicate of #5469, unless it's only about `matrix.to` redirector.

**Comment by t3chguy** [comment] 2023-03-31 10:48
Duplicate of #5469

**Closed by t3chguy** 2023-03-31 10:48 UTC
Labels: T-Enhancement
