### ISSUE TITLE
Ability for sender to respond to keyshare requests from new verified recipient devices

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18666] opened 2021-08-20 14:50 UTC
Currently, if a recipient sees a UISI they send a keyshare request to all their other devices, and the specific device which sent the message in the first place.  (We don't send the request to the sender's other devices, as they don't necessarily know independently of the server whether the recipient was in the room at the point that the message was sent). 

However, the specific device which receives the request currently will not service the request unless the requesting device is the one they sent the key to in the first place.  So, if there's a netsplit, and a new device is added on the far side of the netsplit, that new device will request but never receive keys from the sending device.  If the newly added device has been verified, then the sender should be happy to share keys with it.

**Comment by novocaine** [comment] 2021-08-25 11:09
Downloading to O-Low as I believe netsplits are rare

**Comment by turt2live** [comment] 2022-06-14 05:00
Duplicate of https://github.com/vector-im/element-web/issues/15160

**Closed by turt2live** 2022-06-14 05:00 UTC
Labels: T-Defect, S-Critical, A-E2EE, Z-UISI, A-Session-Mgmt, O-Uncommon
