### ISSUE TITLE
Undismissable "New login" popup

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#22797] opened 2022-07-11 09:54 UTC
### Steps to reproduce

1. Log in on a new device
2. On the old device, a "New login" popup appears. Ignore for now
3. On the new device, click "verify from another app" (or whatever it's called)
4. On the old device, accept the verification request and complete as normal
5. The "New login" popup is still present on the old device, and clicking "Later" does nothing

![image](https://user-images.githubusercontent.com/1389908/178238569-a8e1e064-9757-45f1-8142-af5c1b091f29.png)

#### What did you expect?

Popup should disappear automatically after verification? Or should at least disappear when clicking "later"?

#### What happened instead?

Popup is obstinate

### Operating system

ubuntu 20.04

### Application version

Element Nightly version: 2022060301 Olm version: 3.2.8

### How did you install the app?

nightly debian

### Homeserver

Synapse 1.62ish

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-07-11 13:14
Duplicate of https://github.com/vector-im/element-web/issues/17667

**Closed by robintown** 2022-07-11 13:14 UTC
Labels: T-Defect
