### ISSUE TITLE
Logout button on the spinner page is full width

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7090] opened 2018-07-25 17:41 UTC

**Comment by lampholder** [comment] 2018-07-27 14:33
I guess this bug means that on the page you see when the app is loading but you're logged in:
![image](https://user-images.githubusercontent.com/1922197/43327026-3a7ee060-91b2-11e8-94cb-c75765e2c81b.png)

the 'logout' button, despite appearances, actually fills the whole width of the screen.

**Comment by kittykat** [comment] 2021-08-17 07:44
I can't reproduce the bug as I think the UI has changed now, so closing the issue. Please reopen if it's still happening for you.

**Closed by kittykat** 2021-08-17 07:44 UTC
Labels: T-Defect, P5

**Comment by kittykat** [comment] 2021-08-17 07:50
Just hit it for the first time:

![Screenshot from 2021-08-17 08-46-00](https://user-images.githubusercontent.com/51663/129685671-a6d9e9d2-2f67-44b9-b2ba-4152c706d161.png)

@turt2live Do you just want the button to not be full page width?

**Comment by turt2live** [comment] 2021-08-17 13:22
Yea. It should be relatively easy
