### ISSUE TITLE
lots of "missing translation" labels

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#21279] opened 2022-03-02 19:44 UTC
### Steps to reproduce

not really sure, they just appeared. Possibly related to `https://develop.element.io` being updated on the server side?

### Outcome

Generally everything that should have a text label is now missing its translation:

![image](https://user-images.githubusercontent.com/1389908/156437433-aea0d619-7ce4-4fe0-8ac6-fec7c4adcd95.png)
![image](https://user-images.githubusercontent.com/1389908/156437511-8f69a072-b189-4e8a-9766-6cc4c26103d7.png)

### Operating system

ubnuntu

### Browser information

Firefox

### URL for webapp

develop.element.io

### Application version

missing translation: en|Element version: 9a17a61809a9-react-b480bffab089-js-4e4afdb7954d missing translation: en|Olm version: 3.2.8

### Homeserver

synapse 1.53ish

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-03-02 23:54
Duplicate of https://github.com/vector-im/element-web/issues/9422

**Closed by robintown** 2022-03-02 23:54 UTC
Labels: T-Defect
