### ISSUE TITLE
Unable to initialise e2e OLM.BAD_ACCOUNT_KEY

### ISSUE THREAD

**Issue by k79e** [vector-im/element-web#17333] opened 2021-05-17 15:45 UTC
### Description

It's normal yesterday but suddenly can't login now
It said the connection to server is lost. And state is always offline.
I tried to logout and re-login then it works. But after some days it appear again.

### Steps to reproduce

Use program with http proxy for some days.

Describe how what happens differs from what you expected.
Should login normally but I can't login.

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) or desktop?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- win7 x64
- **Version**: 1.x.y 
- 1.7.27

**Comment by novocaine** [comment] 2022-02-22 08:57
Presumably due to this in the logs

```
2021-05-19T02:55:05.881Z W Unable to initialise e2e OLM.BAD_ACCOUNT_KEY
Error: OLM.BAD_ACCOUNT_KEY
    at vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:2046322
    at Me.<anonymous> (vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:2048828)
    at Me.unpickle (vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:2046028)
    at vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:1569334
    at IDBRequest.n.onsuccess (vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:3510069)
```

**Comment by novocaine** [comment] 2022-02-22 09:00
Duplicate of https://github.com/vector-im/element-web/issues/14515

**Closed by novocaine** 2022-02-22 09:00 UTC
Labels: T-Defect, S-Critical, A-Login, Z-Rageshake, O-Uncommon
