### ISSUE TITLE
File menu in DMs in new right bar fully broken

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#26411] opened 2023-10-20 14:44 UTC
### Steps to reproduce

1. Open the files submenu in the right bar

#### What did you expect?

A warning that it doesnt work due to e2ee

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1374914/e3ba3788-2fa9-449e-b18f-a22338c2c16e)

### Operating system

Fedora Silverblue 38

### Browser information

Firefox 118.0.1 (64-bit)

### URL for webapp

develop.element.io

### Application version

Version von Element: 80ba22a-react-f784a085fdfc-js-c0264954eda2 Version von Olm: 3.2.14

### Homeserver

matrix.midnightthoughts.space

### Will you send logs?

No

**Comment by germain-gg** [comment] 2023-10-20 14:52
Duplicate of https://github.com/vector-im/element-web/issues/26408

**Closed by germain-gg** 2023-10-20 14:52 UTC
Labels: T-Defect
