### ISSUE TITLE
Option to hide/remove user placed/answered call logs

### ISSUE THREAD

**Issue by Adam-Antios** [vector-im/element-web#7268] opened 2018-09-03 17:39 UTC
I use Riot for voice/video chat a lot so my room is filled with logs such as

"User placed a video call."
"User answered the call."
"User ended the call."

The problem is, especially if you have a lot of voice/video calls, that the messages in the room get buried under all the call logs.

Personally I have difficulty even seeing the relevant messages among all these logs. Given that the point of the text chat is to actually chat I believe this is a huge issue.

I understand the importance of having those logs but surely there has to be either an option to hide and show them when necessary or either find another way to see those without cluttering the actual chat.

**Comment by Ad-An** [comment] 2019-02-15 21:36
Is there any possibility of seeing this feature implemented? Is there any other way of achieving this, without obviously deleting the logs one by one?

**Comment by SimonBrandner** [comment] 2021-06-12 15:27
Duplicate of [#6841](https://github.com/vector-im/element-web/issues/6841)

**Closed by SimonBrandner** 2021-06-12 15:27 UTC
Labels: A-VoIP, P2, T-Enhancement
