### ISSUE TITLE
CIDER: Autocompleting an obvious emoji may first iterate through users

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10851] opened 2019-09-12 21:18 UTC
Ie: in HQ there's many `th` users, so `:th<tab>` starts cycling through users instead of the `:thumbsup:` emoji

**Comment by bwindels** [comment] 2019-09-23 12:37
Can't seem to repro ...
![bug](https://user-images.githubusercontent.com/274386/65426017-e8e0f780-ddfe-11e9-8d07-3d9e25d3dbb4.gif)

**Comment by resynth1943** [comment] 2020-10-29 18:44
No repro steps, but I have this:

![image](https://user-images.githubusercontent.com/49915996/97618319-c7e1d180-1a16-11eb-81a7-9f6e254f43e0.png)

**Comment by tulir** [comment] 2020-10-29 18:46
You need to do it fast enough. I use :thinking: often and it's really annoying in rooms that have users whose names start with `think`

![autocomplete-fail](https://user-images.githubusercontent.com/4224639/97618416-a9d09d00-1a27-11eb-95f3-7b8f50e545a5.gif)

**Comment by resynth1943** [comment] 2020-10-29 18:48
Yep, this is consistent.

![image](https://user-images.githubusercontent.com/49915996/97618678-3b83de80-1a17-11eb-8708-8cd44c792fb2.png)

**Comment by callahad** [comment] 2020-11-16 20:12
I can reliably repro. I also get some weird completions: `:R<tab>` somehow consistently gets me `Michael @delph:matrix.org` in the Backend Internal room.

...and if I let it complete to an emoji, I get ⭕  (`:o:`) as the first suggestion, which also makes minimal sense.

**Comment by resynth1943** [comment] 2020-11-17 17:23
Generally speaking, `Emoji` and `People` should never show up at the same time, so fixing this should be as easy as checking if both are present, then nuking one of them depending on the `:` / `@`.

**Comment by t3chguy** [comment] 2021-05-22 13:44
> that shouldn't be too hard to fix, sounds like the user force completer (ability to complete Ti<TAB> without @) is racing the autocomplete suggestions, it should probably await any pending completion promises first

**Comment by t3chguy** [comment] 2021-06-01 07:56
Duplicate of https://github.com/vector-im/element-web/issues/9757

**Closed by t3chguy** 2021-06-01 07:56 UTC
Labels: A-Composer, P2, S-Minor, T-Defect
