### ISSUE TITLE
"Create account" link on Sign in page when homeserver doesn't support registration

### ISSUE THREAD

**Issue by plinss** [vector-im/element-web#16261] opened 2021-01-24 03:02 UTC
### Description

The Sign in page includes the text "New? Create account" with a link to the register page. This page results in an error when the HS doesn't allow registration.

### Steps to reproduce

- Setup a homeserver that does not allow registration
- Click Sign In
- Click Create account
- See the error "Unable to query for supported registration methods."

Ideally the client should query the HS first, and only display the "Create account" link when registration is supported.

### Version information

- **Platform**: web 

For the web app:

- **Browser**: all
- **OS**: all
- **URL**: Private server, V1.7.17

**Comment by jryans** [comment] 2021-01-25 16:12
The create account link is not specific to any server. You can disable registration for the entire Element deployment using UI features: https://github.com/vector-im/element-web/blob/develop/docs/config.md#ui-features.

**Comment by plinss** [comment] 2021-01-25 17:08
I'm aware that the create account link can be entirely removed. However that is only reasonable to do when the client is restricted to a specific homeserver. When the user can select a homeserver, some may accept registrations, while others will not.

Having a button (or link) that will always result in an error (at least in some circumstances) is generally bad form. A better UX would be for the client to query the currently selected homeserver and check if registrations are allowed or not, and only show the link when it will actually work.

Please consider re-opening.

**Comment by t3chguy** [comment] 2021-01-25 17:15
I thought I had an issue about that, yes Login/Reg should get reworked to hide it if the server signals it does not support it. Looks like it got bundled into https://github.com/vector-im/element-web/issues/6847 even though poorly named

**Comment by t3chguy** [comment] 2021-01-25 23:11
Duplicate of #6847

**Closed by t3chguy** 2021-01-25 23:11 UTC
Labels: bug, ui/ux
