### ISSUE TITLE
Convert `store/session/webstorage` to TS

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19271] opened 2021-10-04 15:09 UTC
https://github.com/matrix-org/matrix-js-sdk/blob/5caf05cfa18069b5e0c27f2a57bb9d3e3ba670ee/src/store/session/webstorage.js

**Comment by t3chguy** [comment] 2021-10-05 08:34
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/1896

**Closed by t3chguy** 2021-10-05 08:34 UTC
Labels: T-Task, A-Developer-Experience
