### ISSUE TITLE
Notifications panel is inconsistent with red mark in room list

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#21530] opened 2022-03-23 10:34 UTC
### Your use case

When a message is sent with my displayname pilled, eleweb marks the room red, and the message is listed in the right alerts panel.

When a non-pilled message message which contains my displayname string is sent, the room is read but the message does not appear in the alerts panel.

### Have you considered any alternatives?

It just needs to be consistent either way.

**Comment by t3chguy** [comment] 2022-03-23 10:55
@benparsons is the message in an encrypted room?

**Comment by benparsons** [comment] 2022-03-23 10:56
> @benparsons is the message in an encrypted room?

Yes

**Comment by t3chguy** [comment] 2022-03-23 10:56
Duplicate of https://github.com/vector-im/element-web/issues/6874

**Closed by t3chguy** 2022-03-23 10:56 UTC
Labels: T-Enhancement
