### ISSUE TITLE
Element - Demo Mode

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#16000] opened 2020-12-18 16:54 UTC
I'd love to be able to enable a 'demo mode', that replaces all avatars, room names, display names, message text, filenames and images with random or obscured content, to preserve anonymity/privacy in screenshot for bugs and client demos.

**Comment by t3chguy** [comment] 2020-12-18 16:55
Duplicate of your own issue :P https://github.com/vector-im/element-web/issues/9615

**Closed by t3chguy** 2020-12-18 16:55 UTC
Labels: suggestion

**Comment by lampholder** [comment] 2020-12-18 17:22
Hah, I tried searching for it but couldn't find it - thanks :D
