### ISSUE TITLE
Messages "emotes" timestamp hidden

### ISSUE THREAD

**Issue by JordanConnor** [vector-im/element-web#18983] opened 2021-09-10 13:30 UTC
### Steps to reproduce

/me

### What happened?

Messages "emotes" (where the name is not displayed), have their timestamp hidden behind the avatar, I would expect it to be below or hidden(?)

### Operating system

MacOS

### Application version

Element version: 1.8.2 Olm version: 3.2.3

### How did you install the app?

/get-started

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment] 2021-09-10 13:32
Duplicate of https://github.com/vector-im/element-web/issues/2284

**Closed by t3chguy** 2021-09-10 13:32 UTC
Labels: T-Defect
