### ISSUE TITLE
Pop-up windows should not close when clicking outside of them.

### ISSUE THREAD

**Issue by antdude** [vector-im/element-web#17718] opened 2021-06-21 20:01 UTC
#### Is your suggestion related to a problem? Please describe.
As a newbie in web client in Firefox v89.0.1 web browser, I was looking at my settings and accidently clicked outside of its pop-up window:
![Settings](https://user-images.githubusercontent.com/998681/122820513-8c8b6000-d290-11eb-885b-4625f18ca3b9.gif)
I had to figure out how to get back to it. :(

#### Describe the solution you'd like.
Web site should ask user to confirm closing this pop-up window.

#### Describe alternatives you've considered.
Or don't close it at all until the user close this pop-up window.

#### Additional context
None.

**Comment by t3chguy** [comment] 2021-06-21 20:03
Duplicate of https://github.com/vector-im/element-web/issues/6109

**Closed by t3chguy** 2021-06-21 20:03 UTC
Labels: T-Enhancement
