### ISSUE TITLE
Tray icon position resets when app updates

### ISSUE THREAD

**Issue by aminomancer** [vector-im/element-web#23510] opened 2022-10-17 20:52 UTC
### Steps to reproduce

1. Install Element for Windows.
2. Move the tray icon from the hidden icons popup to somewhere on the taskbar other than the leftmost position.
3. Quit Element, reopen it a few times to see that the tray icon position persists between sessions.
4. Let Element install an update. (idk if you can force an update)
5. Click Update, Element restarts.
6. Tray icon has been moved to the hidden icons popup. (Depending on your Windows version there may be a bug where it initially shows in the leftmost position of the system tray area, rather than in the hidden icons popup, but if so, opening the hidden icons popup will cause it to jump into its real position in the popup)

#### What did you expect?
Tray icon position should persist between app updates

#### What happened instead?
Tray icon position resets on every app update, always starting at the default position at the end of the hidden icons, and requiring me to move the icon every time I update Element (which is pretty often since I 

### Operating system

Windows

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-10-18 09:06
Duplicate of https://github.com/vector-im/element-web/issues/4601

**Closed by t3chguy** 2022-10-18 09:06 UTC
Labels: T-Defect
