### ISSUE TITLE
Consider an option to keep grey badges on rooms but not raise desktop notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8610] opened 2019-02-14 00:13 UTC
For people that want the quiet nature of 'Mentions Only' without losing the number of unread messages

**Comment by carriejv** [comment] 2019-02-15 04:03
This honestly feels like it should be default behavior. Having no indicator of new messages at all is pretty counter-intuitive UX.

+1

**Comment by lampholder** [comment] 2019-02-19 14:57
Not sure whether we'd want to implement exactly this, but sorting our notifs behaviour would be super good.

**Comment by t3chguy** [comment] 2023-06-08 12:07
Duplicate of https://github.com/vector-im/element-meta/issues/528

**Closed by t3chguy** 2023-06-08 12:07 UTC
Labels: P1, A-Notifications, T-Enhancement, Z-GetYourUpdates
