### ISSUE TITLE
Copy tooltip doesn't disappear when showing Copied! tooltip

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#20162] opened 2021-12-13 15:51 UTC
### Steps to reproduce

1. Go to the Help & About section of Settings
2. Click on the copy button next to version info

#### What did you expect?
Copy tooltip goes away so you can see the Copied! tooltip

#### What happened instead?
Both tooltips show up on top of each other
<img width="286" src="https://user-images.githubusercontent.com/5855073/145844081-4633b414-7cd4-4991-a5b7-a0a9bf9adc2e.png">

### Application version

1.9.7

### Will you send logs?

No

**Comment by t3chguy** [comment] 2021-12-13 15:55
Duplicate of https://github.com/vector-im/element-web/issues/19663

**Closed by t3chguy** 2021-12-13 15:55 UTC
Labels: T-Defect, S-Tolerable, A-User-Settings, O-Uncommon
