### ISSUE TITLE
Video thumbnails

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1207] opened 2016-03-18 16:50 UTC
If I upload a .mov it'd be nice if it was thumbnailed.

**Comment by MadLittleMods** [comment] 2021-09-03 23:49
Current state: works for `mp4` but not `mov`

![](https://user-images.githubusercontent.com/558581/132074984-80e4be87-90a1-4ef5-a7dd-296e01ca7612.png)

**Comment by t3chguy** [comment] 2021-09-06 08:18
This is simply lack of browser support for `mov` - https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers

Mov support in the web:

> Only older versions of Safari, plus other browsers that supported Apple's QuickTime plugin

**Comment by t3chguy** [comment] 2022-01-31 12:12
Duplicate of https://github.com/vector-im/element-web/issues/2023

**Closed by t3chguy** 2022-01-31 12:12 UTC
Labels: A-Timeline, A-Media, T-Enhancement, O-Occasional
