### ISSUE TITLE
Improve invite workflow

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#18563] opened 2021-08-16 09:11 UTC
#### What would you like to do?

I'd like to be able to invite friends using SMS, WhatsApp, email, IRC, Signal, etc.

#### Why would you like to it?

Because so far, 100% of my attempts to invite non-Matrix-users to chat with me have failed and I had to help my friends and family get started. Compare to e.g. Discord in which invites are confusing but basically work. I want my friends and family to use Matrix :)

#### How would you like to achieve it?

At the moment, if I click "invite", I can either:

- invite by Matrix;
- invite by e-mail;
- share, which can be copied&pasted but doesn't work for private rooms.

I would prefer:

- invite by Matrix;
- invite by QR Code;
- invite by link, which copies into the clipboard a link valid for e.g. 72h and that I can next copy and paste anywhere I want. 

### Have you considered any alternatives?

So far, it's a missing feature. I can invite by email but there's no path that I could find for other invitation methods.

**Comment by robintown** [comment] 2021-08-16 13:39
Duplicate of https://github.com/vector-im/element-web/issues/12939

**Closed by robintown** 2021-08-16 13:39 UTC
Labels: T-Enhancement
