### ISSUE TITLE
Seeing emoji posters

### ISSUE THREAD

**Issue by InezMc** [vector-im/element-web#19100] opened 2021-09-20 10:06 UTC
#### What would you like to do?
Be able to see who responded to an emoji in a list on my Element desktop. It is possible to see it on my phone (IOS) 

#### Why would you like to do it?
inconsistent functionality between different versions of Element. Often use Emoji for polls and its difficult to see who has responded.

**Comment by SimonBrandner** [comment] 2021-09-20 11:15
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/9723

**Closed by SimonBrandner** 2021-09-20 11:15 UTC
Labels: T-Enhancement
