### ISSUE TITLE
Rooms disappearing after enabling threads.

### ISSUE THREAD

**Issue by karlabbott** [vector-im/element-web#21606] opened 2022-03-30 15:35 UTC
### Steps to reproduce

I've noticed something seemingly strange on [develop.element.io](http://develop.element.io/) -- if I turn on threads, not all of my rooms show up after the refresh. I can consistently reproduce this by turning threads on and then back off. If I leave a room in a non-threaded [develop.element.io](http://develop.element.io/), I can then join it in the threaded [develop.element.io](http://develop.element.io/) and then it will survive a transition, but I have at least 1 other room in this state and i don't want to have to take a careful inventory of rooms and ask people to re-invite me to rooms. Is this a known issue?

#### What did you expect?

All my rooms would still be there after enabling threads.

#### What happened instead?

Some rooms disappeared after enabling threads.

### Operating system

Fedora Linux 35 Kinoite

### Browser information

Version 1.36.122 Chromium: 99.0.4844.88 (Official Build) (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: f029b68ad4b1-react-d09205122d14-js-4360ae7ff817 Olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-03-30 15:36
Duplicate of https://github.com/vector-im/element-web/issues/21592

**Closed by t3chguy** 2022-03-30 15:36 UTC
Labels: T-Defect
