### ISSUE TITLE
Element can't hear microphone if I unplug and plug it back in

### ISSUE THREAD

**Issue by SethFalco** [vector-im/element-web#20880] opened 2022-02-02 20:14 UTC
### Steps to reproduce

In case it's important, I have an [Antlion Audio ModMic](https://antlionaudio.com/collections/microphones) which is wireless and connects via the wireless USB receiver. 

1. Be in a voice call in Element.
2. Unplug the wireless receiver and plug it back in.

The use case is that I want to move away from my desk while I'm on a call. Normally, I'd just move the USB from my [CalDigit Element Hub](https://www.caldigit.com/thunderbolt-4-element-hub/) to my laptop. However, this issue also occurs if you just unplug the USB and plug it back into the same port.

#### What did you expect?
I should be able to continue talking like nothing happened.

#### What happened instead?
Element no longer picks up the audio from my mic. I have to stop the call and make a new one.

### Operating system

Debian GNU/Linux 11 (bullseye) x86_64

### Application version

Element Nightly version: 2022020201 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started#nightly

### Homeserver

one.ems.host

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-02-02 21:09
Duplicate of https://github.com/vector-im/element-web/issues/7400

**Closed by robintown** 2022-02-02 21:09 UTC
Labels: T-Defect
