### ISSUE TITLE
End call button dissapears also when the mouse is on it

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17713] opened 2021-06-21 07:34 UTC
### Description
End call button disappears also when the mouse is on it. The problem is I want to click on the end call button, but it disappears because I waited "too much" when the mouse is on this button it should not disappear.

### Steps to reproduce

- Call someone
- Go to end call button with the mouse
- Wait a few seconds

Logs being sent: no

### Version information

- **Platform**: web 
- **Browser**: Chrome - the newest version: Version 91.0.4472.77 (Official Build) (64-bit)
- **OS**: Windows
- **URL**: https://app.element.io v1.7.30

**Comment by SimonBrandner** [comment] 2021-06-21 07:37
Duplicate of https://github.com/vector-im/element-web/issues/16751

**Closed by SimonBrandner** 2021-06-21 07:37 UTC
Labels: T-Defect
