### ISSUE TITLE
Clicking on "Update" doesn't seem to restart Element

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#18582] opened 2021-08-17 08:09 UTC
### Steps to reproduce

I don't know if this reproduce but I just witnessed it.

1. Run Element Desktop.
2. An update is available. Click on "Update".

### What happened?

1. Element Desktop quit.
2. Element Desktop didn't restart.

### What did you expect?

The Element Desktop application should have restarted automatically.

### Operating system

macOS 11.5

### Application version

Version 1.8.0 (1.8.0). I don't know which version I had before update.

**Comment by dbkr** [comment] 2021-08-17 10:41
Dupe of https://github.com/vector-im/element-web/issues/12433

**Closed by dbkr** 2021-08-17 10:41 UTC
Labels: T-Defect, S-Major, A-Electron
