### ISSUE TITLE
Switch theme icon is not displayed

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#21306] opened 2022-03-04 10:07 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
 -I've just updated my desktop nightly
2. What do you click?
 -I click on my avatar in the top left corner
3. More steps…
 -The "switch theme" icon is broken

![image](https://user-images.githubusercontent.com/18530109/156743074-61a31434-1213-4eba-bf1c-539226b3d2c5.png)

#### What did you expect?
The "switch theme" icon to be displayed on the right.
#### What happened instead?
The icon is not displayed

### Operating system

Windows 10 Home 21H1

### Application version

Element Nightly version: 0.0.1-nightly.2022030401 Olm version: 3.2.8

### How did you install the app?

From https://element.io/get-started#nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-03-04 10:13
Duplicate of https://github.com/vector-im/element-web/issues/21293

**Closed by t3chguy** 2022-03-04 10:13 UTC
Labels: T-Defect, S-Minor
