### ISSUE TITLE
All search results seem to be displayed as hyperlinks, and the search strings no longer seem to be highlighted

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6469] opened 2018-04-08 20:26 UTC
<img width="1017" alt="screen shot 2018-04-08 at 21 23 31" src="https://user-images.githubusercontent.com/1294269/38472158-7c0e07bc-3b73-11e8-9ca6-a80ed91e1603.png">

**Comment by turt2live** [comment] 2018-04-09 01:57
Duplicate of https://github.com/vector-im/riot-web/issues/5007 ?

**Comment by yannicka** [comment] 2020-05-21 15:18
The "All search results seem to be displayed as hyperlinks" part seems fixed.
The "the search strings no longer seem to be highlighted" part seems to be a duplicate of #5007.

So I think the issue can be closed.

**Closed** 2022-04-14 18:18 UTC
Labels: T-Defect, P2, X-Regression, A-Timeline-Search

**Comment by turt2live** [comment] 2022-04-14 18:23
@MadLittleMods why was this closed?

**Comment by MadLittleMods** [comment] 2022-04-14 18:25
@turt2live Based on what you and @yannicka found already. Search does not look like that anymore and https://github.com/vector-im/element-web/issues/5007 tracks the search keyword not being highlighted/pillified.

**Comment by turt2live** [comment] 2022-04-14 18:27
ah, would be good to have updated comments before closing for the context :)
