### ISSUE TITLE
Lost session after update

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21197] opened 2022-02-24 13:06 UTC
### Steps to reproduce

1. Don't use Element on this device for a while
2. Open it up, accept when it proposes to update, and let sync
3. Most recent e2ee doesn't get decrypted
4. Close Element
5. Restart Element

#### What did you expect?
works

#### What happened instead?
logged out of my session:
> Missing session data
> Some session data, including encrypted message keys, is missing. Sign out and sign in to fix this, restoring keys from backup.
> Your browser likely removed this data when running low on disk space. To help us prevent this in future, please send us logs.

my disk is not full (10+GB free), and i don't think anything else disrupting happened either.

### Operating system

w10

### Application version

1.10.4

### How did you install the app?

element.io/auto update

### Homeserver

1.52

### Will you send logs?

Yes

**Comment by HarHarLinks** [comment] 2022-02-24 13:07
![image](https://user-images.githubusercontent.com/2803622/155529751-66e9d5d2-d861-4f99-acd1-e5d959a15875.png)

**Comment by gsouquet** [comment] 2022-02-25 08:50
Seem to be a duplicate of https://github.com/vector-im/element-web/issues/18625 ?

**Closed** 2022-02-25 09:04 UTC
Labels: T-Defect
