### ISSUE TITLE
nicknames not displayed in search

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17343] opened 2021-05-17 19:27 UTC
### Description

![image](https://user-images.githubusercontent.com/2803622/118545068-684ed780-b756-11eb-9cb3-567bb51aa0bf.png)

### Steps to reproduce

- search?

render names (and avatars?) as usual

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021051701-1

**Comment by robintown** [comment] 2021-05-17 20:39
Duplicate of #560

**Closed** 2021-05-18 05:38 UTC
Labels: T-Defect
