### ISSUE TITLE
Receiving video / voice calls despite setting notification options of a room to "None"

### ISSUE THREAD

**Issue by absorber** [vector-im/element-web#16256] opened 2021-01-23 22:39 UTC
![MeOwmZq](https://user-images.githubusercontent.com/2358532/105616024-b9177a80-5dcb-11eb-8c59-3fe1241563f4.png)

### Description

If I set the notification options of a room to "None", I expect all notifications to be muted. Including voice / video calls.
Yet as of now I can still receive voice or video calls.

### Version information

- **Platform**: Element Web v1.7.17
- **Browser**: Chromium Version 87.0.4280.66 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
- **OS**: Ubuntu 18.04
- **URL**: https://app.element.io/#/room/#matrix:matrix.org

**Comment by SimonBrandner** [comment] 2021-01-24 06:58
I can reproduce this. It looks to me like the incoming calls aren't classified as a notification (just a guess). I think this should be fixed as a part of the ongoing effort to improve VoIP.

**Comment by jryans** [comment] 2021-02-01 17:23
I believe this is a duplicate of https://github.com/vector-im/element-web/issues/15591. Please reopen if I have misunderstood.

**Closed by jryans** 2021-02-01 17:23 UTC
Labels: bug, ui/ux
