### ISSUE TITLE
hitting 'resend unsent messages' allocates new txn ids and causes dup msgs

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#10273] opened 2019-07-05 21:36 UTC
if synapse is overloaded and msg sends time out, you get the resend button. but resending doesn't use the same txn ids, so if the original reqs complete (which is likely if the server is just slow) then you end up with dup msgs. this is ugly and unprofessional and makes us look like we don't know what idempotency is. on e2e rooms it looks awful

**Comment by turt2live** [comment] 2019-07-05 21:40
half of this is also likely to be https://github.com/matrix-org/synapse/issues/3365 (although it is true that we don't keep the same txnId)

**Comment by t3chguy** [comment] 2019-07-06 10:57
Resending does seem to use the same txnId:

![image](https://user-images.githubusercontent.com/2403652/60755264-365e7d00-9fe5-11e9-81e7-dcb6c5d19c83.png)

**Comment by turt2live** [comment] 2019-07-06 15:34
Might depend on how it fails? My test was knocking out synapse but leaving the reverse proxy up

**Comment by t3chguy** [comment] 2019-07-07 09:13
I tested by using Offline mode in Chrome Devtools, will try with knocking out Synapse but leaving Nginx up

**Comment by t3chguy** [comment] 2021-03-05 17:20
I believe 100% of this is the Synapse bug tbh

**Comment by t3chguy** [comment] 2022-04-28 21:36
Closing as cannot reproduce
We generate the txnId on our first send attempt and even persist it through refreshes

**Closed by t3chguy** 2022-04-28 21:36 UTC
Labels: T-Defect, X-Cannot-Reproduce, Z-Synapse
