### ISSUE TITLE
_checkForPreJoinUISI nukes timeline when peeking

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#12946] opened 2020-03-31 11:49 UTC
not that we should really have peekable e2ee rooms but if you left the room then peek it you have access to history then when a new message comes in, the `firstVisibleEventIndex` nukes them all

**Comment by turt2live** [comment] 2022-06-13 20:18
is this still a thing?

**Comment by turt2live** [comment] 2023-01-10 00:11
Duplicate of https://github.com/vector-im/element-web/issues/22671

**Closed by turt2live** 2023-01-10 00:11 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-E2EE, Z-UISI, O-Uncommon, Team: Crypto
