### ISSUE TITLE
Notication keywords trigger on homeserver domain in MXID

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#23469] opened 2022-10-12 19:02 UTC
### Steps to reproduce

1. Add a notification keyword that is a word in the domain section of anybody's MXID
2. Have someone reply to anyone other than you with that domain in their MXID

(Example: Add `matrix` as a notification keyword, then have anyone reply to a `matrix.org` user)

#### What did you expect?
User should NOT get a notification, because the body of the original message and the reply do not contain `matrix` (in the example given)

#### What happened instead?
I receive a notification because the user being replied to has `matrix` in the domain of their MXID, triggering the keyword. 

![Element "Mentions & Keywords" notification settings set to Noisy with "matrix" keyword set](https://user-images.githubusercontent.com/41203525/195426388-af8ef9d6-d6ba-40ac-9762-16583965a074.png)

Message being replied to (Example 1):
![](https://user-images.githubusercontent.com/41203525/195426114-39e0bbe8-dd69-40b4-ab97-b32ae996b966.png)

Example 2 (with reply that causes a notification):
![](https://user-images.githubusercontent.com/41203525/195426079-464208da-ff03-4fbc-90b7-64ece3bd27f1.png)

!["@emperorart:matrix.org" MXID shown off](https://user-images.githubusercontent.com/41203525/195426511-1b59e1de-9c85-4361-a7cb-ebfbd7754e87.png)

(Note: Neither of these are my account. The notification is only because the one being replied to is on matrix.org)

### Operating system

Arch Linux

### Browser information

Firefox 105

### URL for webapp

develop.element.io

### Application version

Element version: 2ef6abbfb8c1-react-8b54be6f4863-js-cc025ea45844 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by MadLittleMods** [comment] 2022-10-12 20:42
In the second example with the reply, it makes more sense why it would ping you since the reply syntax has the MXID in it with `matrix.org`.


![](https://user-images.githubusercontent.com/558581/195443628-2c4dcfbc-9333-4220-8822-1008f56de363.png)

```html
<mx-reply>
	<blockquote>
		<a href="https://matrix.to/#/!xxx:matrix.org/$123?via=matrix.org">In reply to</a> <a href="https://matrix.to/#/@madlittlemods:matrix.org">@madlittlemods:matrix.org</a>
		<br>foo
	</blockquote>
</mx-reply>

bar
```


<br>

---

For the first example, I'm not able to reproduce with from a normal message that has no `matrix` string in the body. Can you share the source for that message? Are you absolutely sure that you got a notification sound for it? Can you reproduce with another plain message?

**Comment by BurnyBoi** [comment] 2022-10-12 21:45
> For the first example, I'm not able to reproduce with from a normal message that has no `matrix` string in the body. Can you share the source for that message? Are you absolutely sure that you got a notification sound for it? Can you reproduce with another plain message?

@MadLittleMods  The first image is not a notification. It just has the green on the left because I clicked the reply to get to it. I just screenshot that one so I could prove the entire message does not contain "matrix" in it. This bug is only about the reply causing a notification.

While the formatted body may technically contain the MXID in the event body and does explain why the bug happens, it's not being presented that way to the user, and neither message actually contains "matrix" from that perspective. It would be useful if it didn't trigger notifications for this situation because then a server owner could put their domain as a notification keyword to track people actually discussing it in their messages. With the way it is now, they would get too many false notifications from this bug.

**Comment by MadLittleMods** [comment] 2022-10-12 22:38
Thanks for the clarification @BurnyBoi!

Looks like a duplicate of https://github.com/vector-im/element-web/issues/19595

**Closed by MadLittleMods** 2022-10-12 22:38 UTC
Labels: T-Defect, A-Notifications
