### ISSUE TITLE
The unrecoverable messages the Encryption problems

### ISSUE THREAD

**Issue by CyberMan571** [vector-im/element-web#15732] opened 2020-11-16 05:37 UTC
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    
yes, has send by me

### Version information

- **Platform**: web (in-browser) or desktop?

- **Browser**: Chrome, Safari, Firefox? which version?
For the web app:
opera vivaldi 
firefox 7.8.3r esr 
chrome Version 83.0.4103.116 (Developer Build)  
i.e to edge
Android riotx
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?
it is each both
For the desktop app:
Web apps on windows,linux and live o.s's

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y 

Hello, Dear Friends!
I have been experienced unrecoverable the encrypted messages. it is no decrypting absolutely 
I have used live o.s.'s(Operating system)
I have security passphrase and security key(s)

![image](https://user-images.githubusercontent.com/30759335/99216114-b5b0b300-27cc-11eb-91c5-15fab5304123.png)
![image](https://user-images.githubusercontent.com/30759335/99216179-edb7f600-27cc-11eb-93ba-f96ba836ca99.png)
I had sent twice the bug report, system logs
Definitely It is no recover, it is no back on life the messages the messages

**Comment by t3chguy** [comment] 2020-11-17 10:46
Duplicate of https://github.com/vector-im/element-web/issues/2996

**Closed by t3chguy** 2020-11-17 10:46 UTC
