### ISSUE TITLE
Reactions by the same person shown multiple times (after not syncing for a few hours)

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#16923] opened 2021-04-12 13:15 UTC
### Description

I chatted, put the laptop to sleep, came back after ~2 hours and noticed some messages showed the same reactions twice (and some even three times).

![Screenshot_2021-04-12_14-59-47](https://user-images.githubusercontent.com/10872136/114398702-623a6980-9ba0-11eb-8b57-d37800e6caae.png)

### Steps to reproduce

Not sure if this is reproducible or needs other conditions to be true:
- Chat a bit
- Put your computer to sleep (~2:30 hours in my case)
- Awake it
- Element syncs your rooms/ new messages

A few recent message that had been received before the computer went to sleep now have the same reaction show up twice. With some recent messages even three times.

Logs being sent: yes

![Screenshot_2021-04-12_15-05-11](https://user-images.githubusercontent.com/10872136/114399519-4aafb080-9ba1-11eb-9c1b-b05cce49d5df.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Mozilla Firefox 88.0b4
- **OS**: Manjaro Linux (Arch repo)
- **URL**: staging.element.io
- Element version: 1.7.25-rc.1
- olm version: 3.2.1

**Comment by t3chguy** [comment] 2021-04-12 13:50
Duplicate of https://github.com/vector-im/element-web/issues/11161

**Closed by t3chguy** 2021-04-12 13:50 UTC
Labels: T-Defect
