### ISSUE TITLE
Start 'channel' (Telegram-like admin-only post) without having to set permissions

### ISSUE THREAD

**Issue by patricksavalle** [vector-im/element-web#21821] opened 2022-04-16 11:09 UTC
#### What would you like to do?

Have a button / preset for a room that only allows admins and moderators to post. Call it a channel.

#### Why would you like to do it?

To help migration from Telegram. Normal users don't understand 'permissions'.

#### How would you like to achieve it?

A simple button / option.

**Comment by HarHarLinks** [comment] 2022-04-16 11:57
> Call it a channel.

I disagree with that, as IRC channel is established to mean what a matrix room is. I suggest "announcement room" instead?

I think the idea of a couple presets like this is good for community admin's UX, in fact I suggested something like it in https://github.com/vector-im/element-web/issues/20450. Community admins should be regarded end users and thus not have to deal with raw power levels directly if possible.

**Comment by SimonBrandner** [comment] 2022-04-16 16:29
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

This is a duplicate of https://github.com/vector-im/element-web/issues/17915 which has been closed in favour of https://github.com/vector-im/element-web/issues/16902, https://github.com/vector-im/element-web/issues/5186 and https://github.com/vector-im/element-web/issues/16832

**Closed by SimonBrandner** 2022-04-16 16:29 UTC
Labels: T-Enhancement
