### ISSUE TITLE
Not opening a room

### ISSUE THREAD

**Issue by fobuss** [vector-im/element-web#21767] opened 2022-04-13 07:00 UTC
### Steps to reproduce

1. Open application
2. Go to room where you've posted a message with Element Nightly

#### What did you expect?
As a user I should see all messages in the room.

#### What happened instead?

Getting _Something went wrong_ message.

### Operating system

MacOS 12.3.12

### Application version

Version 1.10.9 (1.10.9)

### How did you install the app?

from https://element.io/get-started#download

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-04-13 07:56
Your logs aren't showing up and you didn't fill the Homeserver field, what version is your homeserver? There is a known bug with threads with older homeservers - https://github.com/vector-im/element-web/issues/21762

**Comment by t3chguy** [comment] 2022-04-13 08:03
I found your logs, for next time please include the issue link as per the form.

Duplicate of https://github.com/vector-im/element-web/issues/21762

**Closed by t3chguy** 2022-04-13 08:03 UTC
Labels: T-Defect, X-Needs-Info
