### ISSUE TITLE
Automatic pill-ification picks up IRC logins as user IDs

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24804] opened 2023-03-12 05:56 UTC
### Steps to reproduce

1. Send a message similar to the one below.

#### What did you expect?

No pill

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/224527035-80cb5b2b-f662-4e21-8dd9-d28c3a600ff4.png)

on this message:
```
{
  "body": "Last login from: ~travisr@2001:470:69fc:105::f on Mar 12 04:06:44 2023 +0000.",
  "format": "org.matrix.custom.html",
  "formatted_body": "Last login from: <b>~travisr@2001:470:69fc:105::f</b> on Mar 12 04:06:44 2023 +0000.",
  "msgtype": "m.notice"
}
```

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2023031001 Olm version: 3.2.12

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-03-13 07:58
Tested with last stable version. This is not a regression caused by current work on pills. The issue is, that the part after `@` is linkified.

**Comment by t3chguy** [comment] 2023-03-13 11:21
This is a regression on Staging

App:
![image](https://user-images.githubusercontent.com/2403652/224687608-f7812c87-950b-4aa6-ae9d-17488d7ad47b.png)

Staging:
![image](https://user-images.githubusercontent.com/2403652/224687634-55cbceee-20da-4d03-9412-e4b29d5cf1fa.png)

**Comment by t3chguy** [comment] 2023-03-13 11:22
This breaks copy-pasting due to the pill adding spurious spaces

**Comment by weeman1337** [comment] 2023-03-13 11:54
Turning it into a pill is caused by it being detecting a MXID in the first place.
This is already the case on app.element.io.

In my opinion the real issue is: MXID-like strings inside text should not be detected as MXIDs.

**Comment by weeman1337** [comment] 2023-03-14 12:22
Closed by https://github.com/matrix-org/matrix-react-sdk/pull/10370

Linkification may be a separate topic.

**Closed by weeman1337** 2023-03-14 12:22 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Pills, O-Occasional
