### ISSUE TITLE
Threaded rooms

### ISSUE THREAD

**Issue by paboum** [vector-im/element-web#23910] opened 2022-12-06 02:24 UTC
### Your use case

I wish to host a "threaded room", a room that would be exclusively using threads for discussion, no linear message history as usual.

E.g. we post car pictures and the threads are used to comment each car. New messages can only be posted if they contain a picture of a car. Currently, such mode of operation requires to be enforced manually by admin/mod - ask nicely in the room topic and delete incorrect messages. I would like to be able to switch the room setting to become a "threaded room".

The simplest implementation includes limiting new message permission to the room admins/mods only and regular users can only respond with threads to the messages already written. To post a new car, the user sends it to the admin/mod and they manually post it. This requires a new room permission type - responding with threads.

A less manual approach would be to allow writing each user one message per day/etc. and reply freely in threads. This requires a rate-limiting setting for writing messages. In fact, it would perhaps be nice idea to also rate-limit avatar changing or nickname changing.

Another approach is allow changing the room into a "threaded room" which graphically hints on this idea, ie. while writing a message, the hint in the background wouldn't say "send a message" but rather "start a new thread" and to even display this input box for the message text, a button like "new thread" would first need to be clicked. Then, the rate-limiting setting would still make sense and wouldn't surprise the user.

Finally, clicking a "reply" button on an existing message would be blocked in a threaded room, making the user click "reply in thread", or writing new messages shorter than some preconfigured threshold (like 20 characters) would be blocked with a bubble saying "a new post needs to be longer than... if you wish to reply, use threads" etc.

**Comment by t3chguy** [comment] 2022-12-06 10:33
Duplicate of https://github.com/vector-im/element-meta/issues/209

**Closed by t3chguy** 2022-12-06 10:33 UTC
Labels: X-Needs-Product, T-Enhancement, O-Uncommon, A-Threads
