### ISSUE TITLE
Connectivity to the server has been lost. - `/sync error AbortError: The user aborted a request.`

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#23637] opened 2022-10-27 19:50 UTC
### Steps to reproduce

1. Have Element open
2. Notice `Connectivity to the server has been lost.` room status banner

> Connectivity to the server has been lost.
>
> Sent messages will be stored until your connection has returned.

![](https://user-images.githubusercontent.com/558581/198382029-1908b7d7-4037-455a-87be-43b422bd81f9.png)

#### What did you expect?

Element syncs without issue as expected

#### What happened instead?

I keep seeing these in the devtools console. Every `/sync` seems to timeout after 1.3mins. Maybe my session isn't valid anymore but I can send messages (they are actually sending). This session is having a lot of UTD's though (maybe related to https://github.com/vector-im/element-web/issues/20209#issuecomment-1293981617 which I'm also experiencing)

```
/sync error AbortError: The user aborted a request.
	overrideMethod	@react_devtools_backend.js:4026
	e.<computed>	@rageshake.ts:73
	(anonymous)	@logger.ts:50
	onSyncError	@sync.ts:978
	doSync	@sync.ts:821
```

The only successful requests there are the 204 CORS `OPTIONS` requests:

![](https://user-images.githubusercontent.com/558581/198382161-282a574c-21ec-4f93-bc25-068b3a65100f.png)

### Operating system

Windows 10

### Browser information

Chrome Version 107.0.5304.63

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.11.12 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by MadLittleMods** [comment] 2022-10-27 20:20
I think this is caused by having an old Element session from April (6 months ago) and the `/sync` requests won't respond in time with that much of a gap. Perhaps a Synapse problem but Element needs better feedback here. And there is probably a better way to recover by getting the latest instead of trying to `/sync` backfill the giant gap.

For example, I can see Synapse taking `2629.03s` for some of my `/sync` requests 😬, https://jaeger.proxy.matrix.org/trace/657fa919e14b7196

**Comment by turt2live** [comment] 2022-10-27 20:36
Effective duplicate of https://github.com/vector-im/element-web/issues/9198

(we also plan to solve this with sliding sync, so not sure there's much value in keeping this open tbh)

**Closed by turt2live** 2022-10-27 20:36 UTC
Labels: T-Defect, S-Major
