### ISSUE TITLE
The grab cursor on spaces is distracting/unreliable

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18974] opened 2021-09-09 15:22 UTC
### Steps to reproduce

1. Hover over a space in the left panel

### What did you expect?
Not for a grab handle to be there. The primary action for me is to click on spaces, not move them around. I presume this is to try and indicate that spaces can move, though in-context tutorial popups or similar would be best.

### What happened?
The grab cursor/handle was there.

### Have you submitted a rageshake?

No

**Comment by turt2live** [comment] 2021-09-09 15:23
As for why this is unreliable, here's the "grabbable" area:
![image](https://user-images.githubusercontent.com/1190097/132714735-83c3e7bf-3fb6-420b-9227-6cdacc7305b4.png)

This feels unexpectedly tall.

**Comment by ShadowJonathan** [comment] 2021-09-09 15:23
I dont get the grab handle on `app.`, i get a pointer. Is this on `develop.`?

**Comment by turt2live** [comment] 2021-09-09 15:24
Yes.

**Comment by robintown** [comment] 2021-09-09 16:31
Duplicate of https://github.com/vector-im/element-web/issues/18951

**Closed by robintown** 2021-09-09 16:31 UTC
Labels: T-Defect
