### ISSUE TITLE
Jitsi landing page

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16892] opened 2021-04-09 07:19 UTC
### Description

have to end call for all because I reached the jitsi landing page

![image](https://user-images.githubusercontent.com/31655082/114143348-563a7780-9914-11eb-9095-93b9755bee00.png)

### Steps to reproduce

unknown
usually I get redirected to the join conference screen when I leave the jitsi call

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) or desktop? web

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version? Chrome latest version and Element v1.7.13
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

**Comment by SimonBrandner** [comment] 2021-04-09 08:14
Looks like a duplicate of your own [issue](https://github.com/vector-im/element-web/issues/16537) :P Or is this something different?

**Comment by t3chguy** [comment] 2021-04-12 12:22
Looks like it

**Closed by t3chguy** 2021-04-12 12:22 UTC
Labels: T-Defect

**Comment by chagai95** [comment] 2021-04-12 18:24
yep, sorry about that I couldn't find it and wanted to send logs, now I see I already sent logs in the other ticket as well 🤦‍♀️
