### ISSUE TITLE
Leaving and re-joining a Libera.Chat room inside a space results in a "Something went wrong!" message.

### ISSUE THREAD

**Issue by ArrayBolt3** [vector-im/element-web#23250] opened 2022-09-09 20:00 UTC
### Steps to reproduce

1. Join the space #ubuntu-workshop:matrix.org.
2. Join one of the rooms (#ubuntu-devel works).
3. Leave the room (run the "/part" command in the text box)
4. Attempt to join the same room again.

#### What did you expect?
The room should be joined without error, and all messages will go through the Libera.Chat IRC bridge properly, both incoming and outgoing.

#### What happened instead?
The following screen appears:
![image](https://user-images.githubusercontent.com/104878738/189433557-815a2e4b-cfb6-47e7-8364-5aa477aaa96a.png)
Clicking off of it and onto the newly joined room seems to work, though I have not yet tested whether messages go through or not.

### Operating system

Ubuntu 22.04.1

### Application version

Element version: 1.11.4, Olm version: 3.2.12

### How did you install the app?

From the element.io apt repository

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ArrayBolt3** [comment] 2022-09-09 20:04
Additionally, I've noticed that messages I send through Matrix show up in IRC, but messages from IRC aren't showing up in Matrix.

Quick notice, I may have messed up the IRC bridge, or it might be Libera.Chat's fault, so this might not be a bug, but rather an issue on my end.

**Comment by ArrayBolt3** [comment] 2022-09-09 20:17
New updates - multiple bridged IRC rooms are still working for me. I have attempted entirely leaving the Ubuntu Workshop space and another space I was joined to, logging out, closing Element, opening it, logging back in, joining the space, and attempting to join a room, and I still get the error message.

**Comment by SimonBrandner** [comment] 2022-09-10 06:36
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by SimonBrandner** 2022-09-10 06:36 UTC
Labels: T-Defect
