### ISSUE TITLE
redacted messages show in mentonion list

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#15248] opened 2020-09-21 12:30 UTC
1. add to highlighted keywords list "Важность: Average" ("severity: Average")
1. get event, which contain "Важность: Average"
1. get event, which redact previous event text from "Важность: Average" to "Важность была: Average" (severity WAS average)
1. I see in mentonion list second event, but it is not contain highlighted keywords.

I think that it is not correct. I think message must do not show in mentonion-list if it was edited and was not contain keywords in latest version of message.

This situation occurs with our zabbix (system monitoring of servers): zabbix send to admins event with "server fail", but then, if server is ok - zabbix was edit fist message to "server is ok". And we do not need see "server is ok" in mentonion list. 

Element desktop: 1.7.7
Ubuntu 16.04 amd64
![1](https://user-images.githubusercontent.com/1297163/93766677-1bb00c80-fc5a-11ea-952d-8a71914c35a8.png)
My keywords:
![2](https://user-images.githubusercontent.com/1297163/93766785-4d28d800-fc5a-11ea-8b5a-87436956c8f8.png)

So, I need, that only "problem" ("Проблема") events from zabbix show in mentonion list, but not "success" ("Решено").

**Comment by progserega** [comment] 2020-09-21 12:32
My keywords:
![2](https://user-images.githubusercontent.com/1297163/93766785-4d28d800-fc5a-11ea-8b5a-87436956c8f8.png)

**Comment by turt2live** [comment] 2020-09-21 13:52
Duplicate of https://github.com/vector-im/element-web/issues/11978 (root cause)

**Closed by turt2live** 2020-09-21 13:52 UTC
Labels: bug
