### ISSUE TITLE
Numbered list alignment problems

### ISSUE THREAD

**Issue by drasbeck** [vector-im/element-web#15368] opened 2020-10-03 05:33 UTC
### Description

Numbered lists are right aligned relative to the period it seems. This can give problems when using numbered lists that reach more than 2-3 digits, or messages containing just a number and a period, e.g., `1984.`

### Steps to reproduce

1. send a message containing a number of more than one digit followed by a period.
1.a. alternatively, append list item body to the message.

**Expected behavior**: Not creating numbered lists when no text follows the number and period. Or better choice of alignment, than right aligned relative to the the period.

**Actual behavior**:

<img width="122" alt="image" src="https://user-images.githubusercontent.com/8578706/94983524-cb7f5700-0543-11eb-8b82-af401b9a3d4a.png"> 
<img width="114" alt="image" src="https://user-images.githubusercontent.com/8578706/94983917-0b940900-0547-11eb-970d-0cedf5b36d44.png">

Log: not sent, easily reproduced    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Safari Version 14.0 (15610.1.28.1.9, 15610), Firefox 81.0.1 in Windows and macOS
- **OS**: Windows 10 19041.546, macOS 10.15.7 (19H2)
- **URL**: app.element.io and private server, both at version 1.7.8 of Element Web

**Comment by t3chguy** [comment] 2020-10-03 11:30
Duplicate of https://github.com/vector-im/element-web/issues/14621

**Closed by t3chguy** 2020-10-03 11:30 UTC

**Comment by drasbeck** [comment] 2020-10-04 13:10
Hi @t3chguy, I agree that this issue is a duplicate of #14621. However I think that #14621 needs a better title, because I didn't find the issue when I searched for related keywords, such as numbered list and align/alignment, etc.
