### ISSUE TITLE
Pressing Enter when adding alias causes browser refresh

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#20810] opened 2022-01-31 05:46 UTC
### Steps to reproduce

1. Type a room alias under Local Addresses in room settings
2. Press Enter

#### What did you expect?

Either submit the alias or nothing

#### What happened instead?

Browser tab refreshes

### Operating system

Arch Linux

### Browser information

Firefox 96

### URL for webapp

develop.element.io

### Application version

Element version: 7078373fbbb3-react-b04d2de31344-js-164320136391 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-02-01 11:57
Duplicate of https://github.com/vector-im/element-web/issues/12013

**Closed by t3chguy** 2022-02-01 11:57 UTC
Labels: T-Defect, S-Major, A-Room-Settings, A-Aliases, O-Occasional
