### ISSUE TITLE
Joins, leaves, room updates formatted weirdly with maximized widgets

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21221] opened 2022-02-25 21:15 UTC
### Steps to reproduce

maximized widget + narrow timeline

#### What did you expect?
good layout

#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/155803995-31264936-5acd-495d-991a-e8d46e06994f.png)

### Operating system

arch

### Application version

Element Nightly version: 2022022501 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.52

### Will you send logs?

No

**Comment by robintown** [comment] 2022-02-26 03:40
Duplicate of https://github.com/vector-im/element-web/issues/21212

**Closed by robintown** 2022-02-26 03:40 UTC
Labels: T-Defect
