### ISSUE TITLE
Treat screenshare as voice call extension

### ISSUE THREAD

**Issue by mrkubax10** [vector-im/element-web#17734] opened 2021-06-23 07:13 UTC
I know that screenshare is still expermental feature but it is annoying that you have to terminate call and switch to video chat to share screen, also you can't accept video call when you don't have webcam attached. It would be nice if you were able to start sharing screen by for example pressing button next to voice chat icon during voice call.

**Comment by SimonBrandner** [comment] 2021-06-23 07:15
Duplicate of https://github.com/vector-im/element-web/issues/12652 and being worked on [here](https://github.com/matrix-org/matrix-react-sdk/pull/5992) :)

**Closed by SimonBrandner** 2021-06-23 07:15 UTC
Labels: T-Enhancement

**Comment by mrkubax10** [comment] 2021-06-23 07:36
Nice
