### ISSUE TITLE
Livestream widgets are disappearing on room switching action

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#20956] opened 2022-02-07 09:32 UTC
### Steps to reproduce

1. Live stream widgets (eg FOSDEM's live stream widget) ask the permission "Remain on your screen when viewing another room, when running" - approve it.
2. Open the room with active live stream, you will see and hear the livestream.
3. Switch to some other room.

#### What did you expect?
I expect to continue hearing the sound stream at least, and maybe video stream too in some PIP window.

#### What happened instead?
Sound from livestream immediately stops. Video stream disappears too!

### Operating system

Ubuntu

### Browser information

Chromium 94

### URL for webapp

chat.fosdem.org, app.element.io

### Application version

FOSDEM 2022 version: 1.10.1 Olm version: 3.2.8

### Homeserver

Synapse 1.50

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-02-07 10:58
It should remain only in if you're joined to the call

**Comment by t3chguy** [comment] 2022-02-07 11:11
Duplicate of https://github.com/vector-im/element-web/issues/20933

**Closed by t3chguy** 2022-02-07 11:11 UTC
Labels: A-Widgets, T-Enhancement, O-Occasional
