### ISSUE TITLE
Emojis don't display on browser without COLR and without SBIX support

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/element-web#10351] opened 2019-07-16 14:03 UTC
### Description

![riot-emoji-boxes](https://user-images.githubusercontent.com/17915621/61300989-09625500-a7b1-11e9-8dae-e1842e0b705e.png)

Fallback to Noto Color Emoji is no longer working on browsers that
have neither COLR nor SBIX support. If I add the following to my
user-style-sheet, I can see some emoji, but the emoji within the
reaction picker still don't display.

```css
.mx_scrollbar_overlay_noautohide {
    font-family: Nunito, 'Noto Emoji', Sans-Serif ! important;
}
```

### Steps to reproduce

![qutebrowser-chroma-check](https://user-images.githubusercontent.com/17915621/61316829-c368b980-a7cf-11e9-862e-c2da0d91089b.png)

Load Riot web in a browser without COLR and without SBIX support on
Linux with Noto Color Emoji installed. Navigate to page containing emoji.

### Version information

- **Platform**: web

For the web app:

- **Browser**: qutebrowser v1.6.3 ( QtWebEngine (Chromium 73.0.3683.105))
- **OS**: Void Linux
- **URL**: riot.im/develop

**Comment by non-Jedi** [comment] 2019-07-16 14:06
As an additional note, if I load a user-stylesheet while Riot is already active, the emoji in the reaction picker are displayed correctly as well as everything else. It's only if the user stylesheet is loaded before Riot that the reaction picker emoji are special snowflakes.

**Comment by turt2live** [comment] 2019-07-16 14:07
Related: https://github.com/vector-im/riot-web/issues/10296

@non-Jedi can we get a rageshake for this? There's some troubleshooting logs specifically for this problem which may be of use to the person who looks into this.

**Comment by non-Jedi** [comment] 2019-07-16 18:11
done

**Comment by jryans** [comment] 2019-07-19 12:55
Thanks for the additional details. What are the results from the ChromaCheck page if you try regular Firefox or Chrome (as opposed to qutebrowser)?

**Comment by non-Jedi** [comment] 2019-07-19 15:39
Firefox supports SVG-in-Opentype only and Chromium supports all but SVG-in-Opentype. Qt-Webengine uses an older version of chromium internally though.

**Comment by ara4n** [comment] 2019-07-19 15:51
this just sounds like the fallback to noto has got lost somewhere...

**Comment by globau** [comment] 2020-01-23 13:44
This is caused by the `Twemoji` font – removing it from the `font-family` declaration on the `body` element resolves this issue.

**Comment by turt2live** [comment] 2020-08-31 19:02
Presuming fixed by the new font family.

**Closed by turt2live** 2020-08-31 19:02 UTC
Labels: bug, defect, question, type:emoji
