### ISSUE TITLE
Suggestion:  Remove, move, or reduce large mostly-empty "seen by" field.

### ISSUE THREAD

**Issue by luckshot** [vector-im/element-web#17866] opened 2021-07-02 21:25 UTC
![image](https://user-images.githubusercontent.com/859590/124330181-bc185300-db41-11eb-92a0-d5e0bcbe6f7b.png)

#### Description
The UI/UX could be improved by removing (or moving) the very wide empty space where "seen by" icons are placed.  It would be awesome if the space were resizable, even better would be to optionally move the 'seen by' icons under the messages instead of sitting next to them taking up a significant amount of screen real-estate.  Even better still would be to let the whole field be moved to the left or right at the user's option, in addition to resizing it.

#### Steps to reproduce

Log: sent/not sent?    

#### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Windows 10 build 1904
- **Version**: 1.7.31

**Comment by t3chguy** [comment] 2021-07-02 21:42
![image](https://user-images.githubusercontent.com/2403652/124331134-b85aef80-db86-11eb-9539-d3445fee6d81.png)


It is only mostly empty in quiet rooms,
you can turn it off entirely if you like.

![image](https://user-images.githubusercontent.com/2403652/124331185-cd378300-db86-11eb-8744-a9518475e7d7.png)

**Comment by luckshot** [comment] 2021-07-02 22:54
Thanks for the suggestion, it's definitely an option.  Just my feedback though, the field is exceptionally large for its function in direct messages and smaller rooms (which are the majority I am in).  Being able to resize or move it while retaining its intended function would be super awesome.

**Comment by robintown** [comment] 2021-07-03 18:35
It could definitely be nice to have read receipts switch to being underneath messages a la message bubbles whenever you make the timeline small enough.

**Comment by turt2live** [comment] 2022-05-07 03:38
Considering this a duplicate of https://github.com/vector-im/element-web/issues/19734

**Closed by turt2live** 2022-05-07 03:38 UTC
Labels: A-Timeline, X-Needs-Design, T-Enhancement, A-Read-Receipts, A-Appearance
