### ISSUE TITLE
Element no longer starts

### ISSUE THREAD

**Issue by xobs** [vector-im/element-web#23110] opened 2022-08-19 03:32 UTC
### Steps to reproduce

1. Attempt to run Element.exe

#### What did you expect?

Element should start up. If it is unable to start up, it should print an error.

#### What happened instead?

```
$ pwd

Path
----
C:\Users\smcro\AppData\Local\element-desktop\app-1.11.0


Local/element-desktop/app-1.11.0
$ C:\Users\smcro\AppData\Local\element-desktop\Element.exe

Local/element-desktop/app-1.11.0
$

```

### Operating system

Windows 11 21H2 build 22000.856

### Application version

???

### How did you install the app?

???

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by dbkr** [comment] 2022-08-22 08:59
Could you tell us how you installed the app? ie. wherever you downloaded element from and the process you used to get it running. Does it make a difference if you reinstall?

**Comment by xobs** [comment] 2022-08-23 00:56
I installed it so long ago that I can't recall how it was originally installed. It might have been via chocolatey, it might have been via winget. I haven't updated the program because I wanted to leave it in this state in case you wanted me to do any troubleshooting.

Curiously, when I run it under a debugger I don't see any errors. Or at least I don't know what point to stop at. It seems like it's just exiting normally, albeit immediately.

**Comment by t3chguy** [comment] 2022-08-23 07:36
@xobs unfortunately how you installed is important, as chocolatey, winget, etc are all community packages, and thus any bugs caused by the packaging are not supported here

**Comment by kittykat** [comment] 2022-10-05 13:17
I'm going to close this issue for now as we cannot action it without additional information. Please reopen or tag me in the issue so I can reopen it for you if the details requested above become available.

**Closed by kittykat** 2022-10-05 13:17 UTC
Labels: T-Defect, X-Needs-Info, S-Critical, O-Uncommon
