### ISSUE TITLE
Element not loading when default homeserver is not reachable (or blocked)

### ISSUE THREAD

**Issue by rmalchow** [vector-im/element-web#24166] opened 2023-01-05 10:47 UTC
#### What would you like to do?
i would like to connect to a private homeserver from a location where matrix.org is blocked (specifically: china). however, i cannot easily do that - the current behaviour is a complete failure on first boot if matrix.org is not reachable ("element is misconfigured") 

#### Why would you like to do it?
to use my homeserver

#### How would you like to achieve it?
if the default homeserver isn't reachable, i would like to be prompted to enter my own homeserver.

**Comment by gsouquet** [comment] 2023-01-06 08:24
Could you specify how you're accessing Element? Via a web browser, if so, could you specify the URL. Or via the desktop applications?

**Comment by Subnet-Masked** [comment] 2023-01-06 15:45
Related to issue #11154 ?

**Comment by rmalchow** [comment] 2023-01-07 16:22
@gsouquet this is a desktop install from flatpak on fedora. and, @Subnet-Masked yeah, this seems related.

**Comment by turt2live** [comment] 2023-01-10 00:54
Duplicate of https://github.com/vector-im/element-web/issues/11154

**Closed by turt2live** 2023-01-10 00:54 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-Login, O-Occasional
