### ISSUE TITLE
Room avatar badge rendered incorrectly

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#20793] opened 2022-01-28 07:46 UTC
### Steps to reproduce

![obrazek](https://user-images.githubusercontent.com/15554561/151507147-a264763a-ce29-4b68-9f14-d74d596823a4.png)

### Outcome

Room avatar seems too small.

### Operating system

Windows 10

### Browser information

Firefox 97b9

### URL for webapp

develop.element.io

### Application version

Verze Element: cfa97212f73e-react-7fa27f583490-js-164320136391 Verze Olm: 3.2.8

### Homeserver

own

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-01-28 09:49
Duplicate of https://github.com/vector-im/element-web/issues/20090

**Closed by t3chguy** 2022-01-28 09:49 UTC
Labels: T-Defect, S-Tolerable, A-Appearance, O-Frequent
