### ISSUE TITLE
Please consider making "Show / Hide Riot" a single left click on tray icon

### ISSUE THREAD

**Issue by ndorf** [vector-im/element-web#14422] opened 2020-07-11 22:12 UTC
**Is your suggestion related to a problem? Please describe.**
Currently, the left and right mouse buttons on the tray icon do the same exact thing: open the popup menu. (Riot Desktop 1.6.8 on Debian Buster with MATE 1.20.3.)

Seems to me that the right button can handle this on its own, and the left one could be used for something more convenient.

**Describe the solution you'd like**
Make the left mouse button "Show / Hide Riot" with one click instead of just duplicating the functionality of the right button. Aside from making me happy, it would also be consistent with the majority of apps (at least that I have encountered) that use a tray icon this way, across all platforms.

**Describe alternatives you've considered**

I use "Show / Hide Riot" a lot, and having to go through the drop-down menu is quite inconvenient. What I do instead is have a normal launcher icon nearby, which I use instead of the "Show" half, and use Ctrl+W for the "Hide" half.

**Comment by t3chguy** [comment] 2020-07-11 22:14
> Please consider making "Show / Hide Riot" a single left click on tray icon

This is what it does on a supported platform.

> Currently, the left and right mouse buttons on the tray icon do the same exact thing: open the popup menu.

This happens when your platform only has partial chromium tray icon support

I would recommend trying different variations of SNI/libappindicator plugins/extensions for the MATE DE/WM

**Comment by ndorf** [comment] 2020-07-11 22:22
Thanks for the info; it didn't occur to me that a DE could support the icon but not support this.

**Comment by t3chguy** [comment] 2020-07-11 22:31
Its even worse in that Electron 8 upgraded to a Chromium version which dropped support for bunch of Tray Icon implementations which fixed this issue for a bunch of configurations (but broke the tray icon appearing for a LOT of others). Now that Electron has effectively undone that change it is back to how it was and the specific tray icon support path used between Electron (chromium) and the WM/DE determines what is supported

**Comment by ndorf** [comment] 2020-07-11 22:34
> This is what it does on a supported platform.

Where can I see which DEs are officially supported? The README only says this:

> Desktop OSes means macOS, Windows, and Linux versions for desktop devices that are actively supported by the OS vendor and receive security updates

**Comment by t3chguy** [comment] 2020-07-11 22:35
https://www.electronjs.org/docs/api/tray#class-tray

> Platform limitations:
> On Linux the app indicator will be used if it is supported, otherwise GtkStatusIcon will be used instead.
On Linux distributions that only have app indicator support, you have to install libappindicator1 to make the tray icon work.
App indicator will only be shown when it has a context menu.
When app indicator is used on Linux, the click event is ignored.

**Comment by ndorf** [comment] 2020-07-11 22:40
That is rather confusing. So, left click doesn't work with libappindicator, but at the same time, libindicator is preferred and in fact the riot-desktop package depends on it. Do I understand that right?

**Comment by ndorf** [comment] 2020-07-11 22:49
Is there any Linux DE on which this works? I just tried a fresh KDE setup and it's the same behavior there.

**Comment by t3chguy** [comment] 2021-01-10 15:30
Duplicate of https://github.com/vector-im/element-web/issues/11772

**Closed by t3chguy** 2021-01-10 15:30 UTC
Labels: suggestion
