### ISSUE TITLE
Stuck typing notifications (client edition)

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#2456] opened 2016-10-12 10:02 UTC
Sometimes it seems that typing notifications get stuck on in the _client_ side; they go away if you switch rooms

**Comment by richvdh** [comment] 2016-10-12 10:06
#2429 was a previous report of this which suggested it only happened in Firefox, but I've also seen it in Chrome 53.0.2785.116.

**Comment by ara4n** [comment] 2016-11-06 01:49
i haven't seen this since they were fixed serverside.

**Comment by richvdh** [comment] 2016-11-06 16:54
Nor have I tbh, though it was pretty rare in the first place. I remain to be convinced, but let's be optimistic.

**Comment by richvdh** [comment] 2016-11-15 13:48
@Kegsay saw this today

**Comment by Kegsay** [comment] 2016-11-15 13:51
They go away when you swap rooms, as per the original report (person was Erik over federation). Sometimes they do go away on their own (Amandine on matrix.org) when they send another message.

**Comment by richvdh** [comment] 2016-12-19 12:09
I observed this today, and dug into it.

It appears that `RoomMember.typing` events are not being propagated to the application. `_events` is empty for each `RoomMember` in the room.

I think the problem is that, when we get a gappy sync, we disable the event listeners for the room while we recreate the room state (including the bit in sync.js that listens for `RoomState.newMember` events and adds re-emitters for `RoomMember.*` events).

So basically: gappy syncs break typing notifications.

**Comment by richvdh** [comment] 2016-12-19 12:37
> Sometimes they do go away on their own (Amandine on matrix.org) when they send another message.

a `RoomMember.typing` event on any room will trigger a state update, which might explain this

**Comment by Kegsay** [comment] 2016-12-19 12:53
Gappy syncs are sufficiently rare at run-time that I'm surprised that this is the cause. /me shrugs

**Comment by devnoname120** [comment] 2017-05-18 23:49
I had this happen to me a few times in the past months using desktop client on Linux (vector-web version 0.9.7).

**Comment by dbkr** [comment] 2017-07-20 09:48
We suspect this may be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/504

**Comment by weeman1337** [comment] 2023-04-19 08:15
Closing as done because of 

> We suspect this may be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/504

**Closed by weeman1337** 2023-04-19 08:15 UTC
Labels: T-Defect, P2, S-Minor
