### ISSUE TITLE
Do Not Launch Into Chat View

### ISSUE THREAD

**Issue by tty7tyil** [vector-im/element-web#16703] opened 2021-03-16 23:20 UTC
**Current behaviour**:  
The last recent chat (on that device) is opened after launching Element<sup>[1](#fn1)</sup>

**Problems**:  
User will be forced into a chat rather than open by their choice from the chat list.  
If that chat is very active/has a lot of unread messages, it will be ‘read’ on Element launch.  
Plus, this is just not intuitive.

**Suggest Solution**:  
Use a blank page (like the ‘home view’ on first login) as the default view after launching Element.

---

<a name="fn1">Footnote 1</a>:

If you are not logged in, ‘home view’ is opened after Element launch (and after login), this is not the situation I am referring to.

If you have login state, _launch_ means:

- On Element Web: accessing Element address (e.g. `app.element.io`) with no sub-url
- On Element Desktop: _run_ (cold launch) Element app (not _open_ Element window, since that will just remember the state of last window closing (this is another problem in itself, see #16691))

**Comment by jwsp1** [comment] 2021-07-01 12:19
This would be nice to have

**Comment by jwsp1** [comment] 2021-07-01 12:24
I think this is kind of a duplicate of #5057

**Comment by SimonBrandner** [comment] 2021-07-01 12:24
> I think this is kind of a duplicate of #5057

Seems to be the case

**Closed by SimonBrandner** 2021-07-01 12:24 UTC
Labels: T-Enhancement
