### ISSUE TITLE
Add markdown message preview

### ISSUE THREAD

**Issue by superdump** [vector-im/element-web#3570] opened 2017-04-05 06:43 UTC
Make it possible to see a message preview when using markdown formatting in order to check it when doing something non-trivial, like one can on GitHub.

**Comment by lampholder** [comment] 2017-04-06 13:09
How necessary will this be once RTE is standard?

**Comment by hho** [comment] 2021-12-03 10:22
Mattermost also has this; it'd be a great feature, especially as Element is not using the familiar GFM.

**Comment by ShadowJonathan** [comment] 2021-12-03 10:49
Discord also has this, albeit "live" in the editor tab.

**Comment by kittykat** [comment] 2021-12-27 16:19
Duplicate of #20360

I'm going to close this issue in favour of the newer one because that has more detail in the description. Please subscribe to the other issue for updates.

**Closed by kittykat** 2021-12-27 16:19 UTC
Labels: X-Needs-Design, X-Needs-Product, T-Enhancement, A-Composer, O-Occasional
