### ISSUE TITLE
When the sidebar with rooms are collapsed, the three dots should be replaced by the category icons

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#21107] opened 2022-02-17 02:26 UTC
![Screenshot_20220217_092303](https://user-images.githubusercontent.com/47475676/154392518-c99287d5-bec9-43ed-997a-c69de27124d5.png)

**Comment by SimonBrandner** [comment] 2022-02-17 05:35
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19332

**Closed by SimonBrandner** 2022-02-17 05:35 UTC
