### ISSUE TITLE
Tabbing to auto-complete @user in composer is adding "false" after the second @

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#21312] opened 2022-03-04 12:06 UTC
### Steps to reproduce

1. In a room, start typing a username and tab to autocomplete it so you have `User1:` in pillified form
2. Start typing a second username and tab to autocomplete so you should now have `User1: User2` with both in pillified form

#### What did you expect?
![Screenshot from 2022-03-04 12-04-10](https://user-images.githubusercontent.com/51663/156760374-56a3ce04-dbe1-444c-9150-adb909b0c11f.png)

#### What happened instead?
Step 2 ended with "false" being auto-inserted after the user2 when I pressed tab:
![Screenshot from 2022-03-04 12-03-58](https://user-images.githubusercontent.com/51663/156760386-d061aae8-574f-47d7-b90c-96461add0a50.png)

Which when sent, shows:

![Screenshot from 2022-03-04 12-04-25](https://user-images.githubusercontent.com/51663/156760405-64a65c20-cc20-4933-8ea4-5745f0619fc7.png)

### Browser information

Version 98.0.4758.102 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 3f2ad33b2b22-react-84bd136657a5-js-9e4f109e80ae Olm version: 3.2.8

**Comment by t3chguy** [comment] 2022-03-04 12:15
Duplicate of https://github.com/vector-im/element-web/issues/21307

**Closed by t3chguy** 2022-03-04 12:15 UTC
Labels: T-Defect, X-Regression, S-Major, A-Composer, A-Pills, O-Frequent
