### ISSUE TITLE
Remember setting of Windows Tray Icon

### ISSUE THREAD

**Issue by mkarg** [vector-im/element-web#22550] opened 2022-06-13 11:18 UTC
#### What would you like to do?

The setting that Element's icon shall *always* be visible on the Windows notification tray shall be persistent and survive updates of Element.

#### Why would you like to do it?

1. Seeing the small info badge on the tray icon when there are new messages is my *primary* means of learning that I have new chats.
2. It is essential to know whether Element is running as a background service or whether I forgot to start Element.
3. It is tedious to always repeat that setting after every update of Element.

#### How would you like to achieve it?

Do not uninstall and install the background service but instead just replace the EXE file *in place*. That should prevent Windows from thinking that an uninstall happened, hence prevents Windows from throwing away that setting.

### Have you considered any alternatives?

Manually setting this option in Windows after *each* update of Element is very frustrating and error-prone.

**Comment by t3chguy** [comment] 2022-06-13 11:58
Duplicate of https://github.com/vector-im/element-web/issues/4601

**Closed by t3chguy** 2022-06-13 11:58 UTC
Labels: T-Enhancement
