### ISSUE TITLE
The window position and size cannot be remembered under certain conditions.

### ISSUE THREAD

**Issue by YamatoRyou** [vector-im/element-web#23625] opened 2022-10-27 06:33 UTC
### Steps to reproduce

1. Adjust the window size and position to the corner of the desktop (such as the lower right corner, which needs to be close to the last 1 pixel of the edge);
2. Exit Element and start it again.

#### What did you expect?
n/a

#### What happened instead?
When Element is started, the window position and size are changed.
The window coordinates recorded in `window-state.json` are also changed.

`window-state.json` content:
````
{"width":974,"height":1027,"x":946,"y":30,"displayBounds":{"x":0,"y":0,"width":1920,"height ":1080},"isMaximized":false,"isFullScreen":false}
````

**Exit the program, change one of the above values, for example, modify the X coordinate to 947, then the window position and size will also be changed after the next startup.**

### Operating system

x64 Windows 10 Enterprise LTSC 2021

### Application version

Element 1.11.12

### How did you install the app?

https://packages.element.io/desktop/update/win32/x64/

### Homeserver

Synapse 1.69.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-03-03 09:36
Duplicate of https://github.com/vector-im/element-web/issues/20940

**Closed by t3chguy** 2023-03-03 09:36 UTC
Labels: T-Defect, S-Tolerable, O-Uncommon
