### ISSUE TITLE
/topic doesn't show line breaks

### ISSUE THREAD

**Issue by resynth1943** [vector-im/element-web#15824] opened 2020-11-25 13:43 UTC
![IMG_20201125_133853](https://user-images.githubusercontent.com/49915996/100235126-e8248380-2f23-11eb-9b43-ec37e96c1a65.jpg)

### Description

The text needs newlines like when I'm editing the topic, so people can read it.

### Steps to reproduce

- Make a long-winded topic in a room with newlines
- Type /topic in composer
- 👀 really hard to read!

Logs being sent: no

**Comment by jryans** [comment] 2020-12-02 13:01
This is basically a duplicate of https://github.com/vector-im/element-web/issues/9623, https://github.com/vector-im/element-web/issues/5180.

**Closed by jryans** 2020-12-02 13:01 UTC
Labels: bug, ui/ux
