### ISSUE TITLE
Old phonecalls retriggered through history browsing - events not reprocessed correctly(?)

### ISSUE THREAD

**Issue by phpwutz** [vector-im/element-web#23676] opened 2022-11-01 18:07 UTC
### Steps to reproduce

1. open element
2. scroll through (load requiring?) history with someone you recently had a call with

#### What did you expect?
the call should show up as ended.

#### What happened instead?
the call is triggered again like it's being processed realtime

### Operating system

Arch

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### How did you install the app?

yay

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-11-02 02:53
https://github.com/vector-im/element-web/issues/22848 related

**Comment by phpwutz** [comment] 2022-11-02 15:03
yep this sounds pretty much like the same issue. i did use the issue search before opening this but apparently didn't use the right search, sorry.

**Comment by paulvt** [comment] 2022-11-02 17:59
This is in particular apparent if you use multiple PCs, each with a separate Element Web session. If you switch start using a different session, the call rings again.

Also note that when declining the repeated call, Element Android of the other user in the DM  handles that call decline event and then _they_ think you try to call them again too, leading to confusion all around.

**Comment by yajo** [comment] 2022-11-30 07:19
I think this is a duplicate of https://github.com/vector-im/element-web/issues/22848. BTW I experienced this yesterday and today. It's extremely annoying. 🤦🏼‍♂️

**Comment by t3chguy** [comment] 2022-11-30 14:19
Duplicate of https://github.com/vector-im/element-web/issues/22848

**Closed by t3chguy** 2022-11-30 14:19 UTC
Labels: T-Defect, S-Major, A-VoIP, O-Uncommon
