### ISSUE TITLE
Failed to load list of rooms in space home

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23831] opened 2022-11-24 14:54 UTC
### Steps to reproduce

1. Go to a space home
2. Search for a room, wait

#### What did you expect?
List of result matching the search term

#### What happened instead?
![Screenshot from 2022-11-24 14-52-52](https://user-images.githubusercontent.com/51663/203812988-26ab3ad3-857b-444c-ac48-31b35d223843.png)

![Screenshot from 2022-11-24 14-53-33](https://user-images.githubusercontent.com/51663/203813129-a4f20d99-a448-49f2-b529-e622dfc166f9.png)

### Browser information

Chromium 107.0.5304.110 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: cbf5c43ae79d-react-569a36493378-js-b318a77ecef1 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by babolivier** [comment] 2022-11-24 16:07
I've had a quick peek at the matrix.org logs upon request from @t3chguy, it looks like Synapse is responding with `M_INVALID_PARAM` and complains about `Unknown pagination token`:

```
2022-11-24 14:54:36,833 - synapse.http.server - 108 - INFO - GET-76f2fb182d1b88c1-LHR - <XForwardedForRequest at 0x7fa72ede5850 method='GET' uri='/_matrix/client/v1/rooms/!OJBlkJuUrsKnqtNnTi%3Amatrix.org/hierarchy?suggested_only=false&from=VpEadAYpvMgeFrDXGNehtGnt&limit=20' clientproto='HTTP/1.1' site='11104'> SynapseError: 400 - Unknown pagination token
2022-11-24 14:54:36,834 - synapse.access.http.11104 - 460 - INFO - GET-76f2fb182d1b88c1-LHR - [redacted IP address] - 11104 - {@kittykat:matrix.org} Processed request: 0.004sec/0.001sec (0.001sec, 0.000sec) (0.000sec/0.001sec/1) 64B 400 "GET /_matrix/client/v1/rooms/!OJBlkJuUrsKnqtNnTi%3Amatrix.org/hierarchy?suggested_only=false&from=VpEadAYpvMgeFrDXGNehtGnt&limit=20 HTTP/1.1" "[redacted user agent]" [0 dbevts]
```

**Comment by t3chguy** [comment] 2022-11-24 16:13
The token would have been issued by Synapse within the same set of interactions, but it is known to expire. Not that https://spec.matrix.org/v1.5/client-server-api/#get_matrixclientv1roomsroomidhierarchy allows such behaviour

**Comment by t3chguy** [comment] 2022-11-24 16:21
Duplicate of https://github.com/vector-im/element-web/issues/22138

**Closed by t3chguy** 2022-11-24 16:21 UTC
Labels: T-Defect, A-Spaces
