### ISSUE TITLE
voice/video information tones

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#15079] opened 2020-09-02 00:48 UTC
This is a copy of https://github.com/vector-im/element-android/issues/1687 as this is per client issue and no reaction from the core team has been received so far.

0. This is not only riotX issue, but all riot clients, including riot-ios and riot-web, but I'm not sure if 3 separate issues should be opened in each project.

1. First of all, when call is placed, the caller must hear beeps (ring.ogg) when and only when callee's phone has received incoming call notification and start ringing (vibrating / showing notification silently). There must be exactly the same principle as in GSM and SIP: if you hear beep it means the callee's phone is ringing.
\
https://en.wikipedia.org/wiki/Ringing_tone :
> destination terminal is alerting the receiving party

Yes, I know that all modern IMs completely ignore this rule, cause all they suck.

2. There should be another sound to show caller that we're trying to initiate the call. Sometimes I hear repeating tone before ringing tone, it's similar to this one, that I've tried to find manually:
`for i in {1..5}; do beep -f 330 -l 80 -n -f 440 -l 80 -n -f 550 -l 80 -n -f 400 -l 80; sleep 1.5s; done`
I don't know what it means, how it's called, neither can't found any information about it, but I always treated it as a call initiation notification.

3. Unlike SIP and GSM,  establishing p2p connection (call connection phase) may take significant time or fail. There must be special signal for this state, the silence is unacceptable here.

**Comment by turt2live** [comment] 2020-09-02 01:26
I've placed a call in a room and I hear a ringing tone - what am I missing here?

**Comment by 532910** [comment] 2020-09-02 01:40
> Ringing tone (audible ringing, also ringback tone) is a signaling tone in telecommunication that is heard by the originator of a telephone call while the destination terminal is **alerting** the **receiving party**.

This is not true for all Element clients.

**Comment by turt2live** [comment] 2020-09-02 01:45
It seems true for Element Web, so I'm closing this issue.

**Closed by turt2live** 2020-09-02 01:45 UTC
Labels: bug

**Comment by 532910** [comment] 2020-09-02 02:00
Travis, this is NOT true, please reopen.

Steps to reproduce:
-1. You have two matrix accounts and a room with both of them.
0. You have two Element Web opened, one for each account.
1. Close one of Element Web
2. Place a voice call from another Element Web

Current behaviour:
You'll hear ringing tone from the client you placed a call

Expected behaviour:
The ringing tone must be heared then and only then the callee's client starts ringing.

**Comment by turt2live** [comment] 2020-09-02 02:01
I can't reproduce that.

**Comment by 532910** [comment] 2020-09-02 02:05
I've tested this twice right now, and it's reproducable every time.
Element Web (1.7.5) starts ring as soon as you press the call button.

**Comment by turt2live** [comment] 2020-09-02 02:09
That's the intended behaviour. The call system does not translate to regular phone systems, and thus is not bound by the same rules. Matrix also does not have any way of knowing whether or not the other end has started ringing, so the client is forced to start ringing ahead of the dialing actually occurring. 

An MSC to fix this would be appreciated, if it's truly desired behaviour.
