### ISSUE TITLE
[Rich text editor] can't ping a user

### ISSUE THREAD

**Issue by Thatoo** [vector-im/element-web#24217] opened 2023-01-12 19:41 UTC
#### What would you like to do?
Start writting @someo and that it suggests @someone and we can select the user and ping the user.
#### Why would you like to do it?
To be able to ping a user in a room or averybody with @room as we can do it when the Rich text editor is not enabled

**Comment by t3chguy** [comment] 2023-01-13 09:07
Duplicate of https://github.com/vector-im/element-web/issues/23880

**Closed by t3chguy** 2023-01-13 09:07 UTC
Labels: S-Minor, A-Autocomplete, T-Enhancement, O-Frequent, Z-Labs, A-Rich-Text-Editor

**Comment by Thatoo** [comment] 2023-01-13 09:32
Good. Sorry, I thought commands starting with / and ping starting with @ was two different things, that's why I opened a new issue but if it is the same then good.
