### ISSUE TITLE
can't directly open link in replied-to message (new reply UI)

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18043] opened 2021-07-17 17:03 UTC
#### Is your suggestion related to a problem? Please describe.
matrix-org/matrix-react-sdk#3553 is on nightly.
It used to be that the reply content worked like a normal message and you could just click links.
This isn't possible anymore. I think that is bad UX.

Having just been in this situation, i felt
- it wasn't obvious why clicking the link "did nothing" - what element actually did was scroll to that msg and (too subtly) highlight it
- takes an unnecessary step to go to the link

I think this is reasonable, you might visit a link again/at all only when it is discussed again.

Links (in general) should probably also have a hover effect, like underline to indicate the action?

#### Describe the solution you'd like.
Make clickables in the replied-to msg clickable without going to the quoted message first.

#### Additional context
Should be designed to work with #18027

**Comment by robintown** [comment] 2021-07-17 17:41
Duplicate of https://github.com/vector-im/element-web/issues/18017

**Closed by robintown** 2021-07-17 17:41 UTC
Labels: T-Enhancement
