### ISSUE TITLE
Unable to decrypt: The sender's device has not sent us the keys for this message.

### ISSUE THREAD

**Issue by DaKingKovu** [vector-im/element-web#23151] opened 2022-08-24 16:22 UTC
### Steps to reproduce

I simply dmed one of the people on the server I'm in. 

#### What did you expect?
For the DM to go through normally
#### What happened instead?
The person on the other end can't see my messages and it turns out like "Unable to decrypt: The sender's device has not sent us the keys for this message." 

### Operating system

Windows

### Application version

Element version: 1.11.3 Olm version: 3.2.12

### How did you install the app?

Element.io/get-started

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-08-25 06:46
You will need to send logs for us to be able to figure out what is going on here - could you please do that?

**Comment by t3chguy** [comment] 2022-08-25 15:42
Duplicate of https://github.com/vector-im/element-web/issues/2996

**Closed by t3chguy** 2022-08-25 15:42 UTC
Labels: T-Defect, X-Needs-Info
