### ISSUE TITLE
Joining room from explore space gives an error

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23856] opened 2022-11-29 11:08 UTC
### Steps to reproduce

1. Go to a space home (click twice on space icon in left panel, space is an element.io one rather than matrix.org - not sure if this is relevant)
2. Search for room
3. Click "Join" on the right side of the room list

I get this on develop as well

#### What did you expect?
Joined room

#### What happened instead?
Error

![Screenshot from 2022-11-29 11-08-23](https://user-images.githubusercontent.com/51663/204513782-73263249-1bad-42b7-bb75-728da55e3d33.png)

### Browser information

Chromium 107.0.5304.121 (Official Build) Arch Linux (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.15
Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-11-29 11:20
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-11-29 11:20 UTC
Labels: T-Defect, A-Spaces
