### ISSUE TITLE
space panel kebab menu is rendered out of view on sub spaces 

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#21141] opened 2022-02-21 15:14 UTC
### Steps to reproduce

https://user-images.githubusercontent.com/3055605/154982220-22d6f26f-c24c-4e3a-b7d8-6f39a1246c32.mov

### Will you send logs?

No

**Comment by HarHarLinks** [comment] 2022-02-21 16:31
This does not happen for me on Element Nightly version: 2022022001 so probably regressed since then

**Comment by gsouquet** [comment] 2022-02-22 10:23
Downgrading to minor as I don't believe this is a major feature and you can right click on the space itself to display the context menu

**Comment by t3chguy** [comment] 2022-02-22 10:25
Also subspaces are still marked as Beta

**Comment by yaya-usman** [comment] 2022-03-30 21:52
@andybalaam @t3chguy can i get assigned this issue?

**Comment by SimonBrandner** [comment] 2022-03-31 04:35
> @andybalaam @t3chguy can i get assigned this issue?

I've assigned you to the issue. If you need any help/have any questions be sure to visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)!

**Comment by yaya-usman** [comment] 2022-03-31 05:01
> > @andybalaam @t3chguy can i get assigned this issue?
> 
> I've assigned you to the issue. If you need any help/have any questions be sure to visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)!

Thanks @SimonBrandner, can you pls direct me on how to make a nested chats or rooms like that, I can't seem to do that, when I tried that yesterday

**Comment by SimonBrandner** [comment] 2022-03-31 15:24
https://user-images.githubusercontent.com/25768714/161091599-eeac88f8-7264-4249-a906-0bf3d9db2ab9.mp4

Like so

**Comment by yaya-usman** [comment] 2022-03-31 19:34
> Peek.2022-03-31.17-24.mp4 
> Like so

Alright thanks.

**Comment by yaya-usman** [comment] 2022-04-16 05:43
@SimonBrandner can you please check again if it still happens for you... I tried again reproducing, i couldn't. I await your response thanks.

**Comment by HarHarLinks** [comment] 2022-04-16 10:40
It does still happen
![image](https://user-images.githubusercontent.com/2803622/163671827-f2c4260f-e3f0-4197-97dd-d8585231eb17.png)
Element Nightly version: 2022041601
Olm version: 3.2.8

**Comment by yaya-usman** [comment] 2022-04-16 11:17
> It does still happen ![image](https://user-images.githubusercontent.com/2803622/163671827-f2c4260f-e3f0-4197-97dd-d8585231eb17.png) Element Nightly version: 2022041601 Olm version: 3.2.8

Alright thanks.

**Comment by yaya-usman** [comment] 2022-04-16 17:49
@HarHarLinks One more question, what behavior would you guys want this to exhibit instead when subspaces name get longer. I am trying to think of a fix. I would appreciate any suggestion

**Comment by HarHarLinks** [comment] 2022-04-16 19:15
![image](https://user-images.githubusercontent.com/2803622/163688422-e16e8ee1-53a7-48d0-9f86-2ac1c9764432.png)
Subspace names are ellipses anyway, it just needs to be adjusted (to happen early enough) so the kebab menu is where it should be

**Comment by SimonBrandner** [comment] 2022-04-17 07:40
@yaya-usman, I am unassigning you until there is at least a draft PR linked to the issue

**Comment by yaya-usman** [comment] 2022-04-17 09:23
Dropping a PR now, i just wanted to be clear of what the supposed behavior should be

**Closed** 2022-04-30 15:36 UTC
Labels: T-Defect, S-Minor, A-Spaces, O-Uncommon, good first issue, A-Subspaces
