### ISSUE TITLE
Beeing able to change display name of a contact

### ISSUE THREAD

**Issue by yennor** [vector-im/element-web#16470] opened 2021-02-17 09:55 UTC
**Is your suggestion related to a problem? Please describe.**
I couldn't find an issue already describing this, so I open my own.
I've got some contacts which use user names I just won't be able to recognize or distinguish (think about john1, john2, test123). So in the 1:1 room I've tried to rename the room name, which ended in an edit war. There's already a ticket about that: #3130 .
But also there seems to be no possibility to change in other rooms, what name is displayed to me for certain users.

**Describe the solution you'd like**
I'd like a possibility to set a displayname for any user (contact) myself. eg. When john1 writes in the 1:1 room, and in any other room, I always see "John Smith".

**Comment by t3chguy** [comment] 2021-02-17 09:57
Duplicate of https://github.com/matrix-org/matrix-doc/issues/690

**Closed by t3chguy** 2021-02-17 09:57 UTC
Labels: suggestion
