### ISSUE TITLE
Riot crashing to white screen

### ISSUE THREAD

**Issue by vyrgozunqk** [vector-im/element-web#12783] opened 2020-03-19 09:10 UTC
### Description

Hi guys,

I had to migrate to OpenSuse Tumbleweed and need Riot for work. Unfortunately it is crashing very often, it can happen randomly while changing channels, selecting text or just doing nothing. The crashes lead to white screen. 

This looked like the typical Electron/ CEF issues with the GPU, so i've tried running with parameters like --disable-gpu and so on..

This is the output:

DESKTOP-3T4TM31:~> riot
No protocol specified
Seshat isn't installed, event indexing is disabled.
xdg-mime: application argument missing
Try 'xdg-mime --help' for more information.
No protocol specified
No update_base_url is defined: auto update is disabled
No protocol specified
No protocol specified
(node:6139) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:6139) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[6197:0319/105614.344603:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
(electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Fully updated OpenSuse TumbleWeed

- **Version**: 1.x.y 
riot-web version: 1.5.13
olm version: 3.1.3

**Comment by bwindels** [comment] 2020-03-19 13:23
[Apparently fixed](https://github.com/vector-im/riot-web/issues/12341) by upgrading electron to version 8, which should happen in the soon to be released Riot 1.6.

**Comment by novocaine** [comment] 2021-11-21 23:21
@vyrgozunqk is this still happening?

**Comment by turt2live** [comment] 2022-06-14 05:33
Duplicate of https://github.com/vector-im/element-web/issues/21541

**Closed by turt2live** 2022-06-14 05:33 UTC
Labels: T-Defect, X-Needs-Info, A-Electron
