### ISSUE TITLE
Mobile web support is now unusable

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#14962] opened 2020-08-14 19:14 UTC
It used to warn you to install mobile web, but then be vaguely usable (but dog slow). Nowadays following a event permalink looks like this:

<img src="https://user-images.githubusercontent.com/1294269/90284937-c585c780-de6a-11ea-86c4-f870f03f9cd7.png" width="350">

**Comment by t3chguy** [comment] 2020-11-12 17:20
So this is because of https://github.com/vector-im/element-web/issues/7378

**Comment by nadonomy** [comment] 2022-05-18 09:28
+1'ing this, this is heavily broken if e.g. someone shares a link to a room with you: https://github.com/vector-im/element-web/issues/22259

I believe this should be triaged as S‑Critical (given how broken the UI is) and O-Frequent (given it happens every single time).

@lampholder is the original rationale for https://github.com/vector-im/element-web/issues/7378 still valid?

**Comment by lampholder** [comment] 2022-05-18 09:42
I'm not sure I have any useful context on this, sorry.

I think we wanted deep links to render on phones (so people could read the contents in the web view), only prompting people to download the app once they tried to interact with the room, but I'm not certain.

But https://riot.im/app _isn't_ a deep link, so I don't know what 2018 me was talking about. Maybe the intercept page was just confusing folks by telling them to set a custom server to matrix.org when it is often the default (and is always the default on https://riot.im/app or https://app.element.io)? I'm just guessing now, though.

**Comment by nadonomy** [comment] 2022-05-18 09:47
> I think we wanted deep links to render on phones (so people could read the contents in the web view), only prompting people to download the app once they tried to interact with the room, but I'm not certain.

The problem is this means committing to a responsive web reading experience, which I'm not sure we can do right now. Will dig further.

> Maybe the intercept page was just confusing folks by telling them to set a custom server to matrix.org when it is often the default (and is always the default on https://riot.im/app or https://app.element.io/)? I'm just guessing now, though.

Yeah this sounds fair, we can revisit this and consider how we can be smarter pulling details from config.

**Comment by Greenheart** [comment] 2022-12-20 13:14
Is there a good workaround for this in the mean time?

I've tried using `matrix.to` links to work around this issue, but got user feedback that it was too confusing for people to have to select between the different Matrix clients (plus understanding the protocol matrix in the first place).

For my use case, I want people new to Element and Matrix to be able to click a link and get straight into a public chat room where they can read on the web, and potentially create account + install native apps if they decide to participate more actively. This works well for desktop users, and sharing direct links to Element web is great for that.

However, for mobile users it looks like this:
![image](https://user-images.githubusercontent.com/6125097/208672508-08ef4745-42c6-4aa0-b49d-76cf6be085fc.png)

**Comment by paboum** [comment] 2023-04-30 15:37
> Is there a good workaround for this in the mean time?

For my similar usecase https://github.com/cinnyapp/cinny seems to be the best workaround.

**Comment by t3chguy** [comment] 2023-07-13 11:38
Closing in favour of https://github.com/vector-im/element-web/issues/9814

**Closed by t3chguy** 2023-07-13 11:38 UTC
Labels: T-Defect, Z-Platform-Specific, S-Major, Z-Experimental, O-Uncommon, A-Mobile
