### ISSUE TITLE
Previews in Room List should distinguish between inbound & outbound messages.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23000] opened 2022-08-04 19:15 UTC
### Steps to reproduce

1. Enable room previews on the room list if you haven't already.
2. Send a message into the room from user bob. It will appear as `Bob: hello` in the preview.
3. Send a message from yourself into the room of `Bob: hello`
4. Realise that the previews are identical and indistinguishable

#### What did you expect?

To distinguish messages I send from messages I receive.

#### What happened instead?

Indistinguishable messages.

Instead, we could format the sender on inbound messages to make it clear that it's a sender.

### Operating system

macOS

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by turt2live** [comment] 2022-08-05 02:59
Duplicate of https://github.com/vector-im/element-web/issues/15589

**Closed by turt2live** 2022-08-05 02:59 UTC
Labels: T-Defect
