### ISSUE TITLE
Thumb in left panel is too narrow

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18695] opened 2021-08-23 13:57 UTC
### Steps to reproduce

1. Looking at the left panel, try to grab the thumb in the scrollbar next to room names

### What happened?

The area of the scroll thumb which is grabbable is ~1 pixel wide.

https://user-images.githubusercontent.com/51663/130459488-b99373b2-457d-4d49-9ff4-5f87c1cd90a1.mp4

### What did you expect?

How it works on app.element.io (Beta disabled): there is space to grab the scroll thumb.

### Operating system

Arch Linux

### Browser information

Chromium Version 92.0.4515.159 (Official Build)

### URL for webapp

develop.element.io with Beta enabled

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment] 2021-08-23 14:14
Duplicate of https://github.com/vector-im/element-web/issues/18689

**Closed by SimonBrandner** 2021-08-23 14:14 UTC
Labels: T-Defect, X-Regression, S-Major, A-Room-List, O-Intermediate
