### ISSUE TITLE
Room icon displays as user who just joined

### ISSUE THREAD

**Issue by expipiplus1** [vector-im/element-web#17600] opened 2021-06-09 07:43 UTC
![image](https://user-images.githubusercontent.com/857308/121313230-c4adad00-c938-11eb-9a19-e01a03635a44.png)

### Description

I just created the room and linked it somewhere, this voyager bot joined, and the room icon now shows as that users icon!

I joined using another user/client and the icon has returned to normal (a `V` in this case) (however the incorrect icon still remains in the sidebar:

![image](https://user-images.githubusercontent.com/857308/121313571-1bb38200-c939-11eb-81ac-9e23e918fb62.png)

Sorry if this is a duplicate, I had a search but the generality of the terms made it quite difficult!

### Steps to reproduce

- Create a room
- Have a user join
- Observe that the icon is incorrect, both in the room and the sidebar

### Version information

- **Platform**: desktop 
- **OS**: NixOS (GNU/Linux) 
- **Version**: 
  - Element version: 1.7.29
  - olm version: 3.2.3
  - synapse version: 1.35.1

**Comment by t3chguy** [comment] 2021-06-09 07:55
Duplicate of https://github.com/vector-im/element-web/issues/17559

**Closed by t3chguy** 2021-06-09 07:55 UTC
Labels: T-Defect

**Comment by expipiplus1** [comment] 2021-06-09 08:01
I don't quite understand #17559, but the gist of it seems to be that this room was mistakenly identified as a DM between me and the voyager bot?
