### ISSUE TITLE
Missing translations when I start my browser

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#21096] opened 2022-02-16 09:01 UTC
### Steps to reproduce

1. Log in to my computer, open Firefox, which has a saved session including Element Web as one tab
2. Switch to the Element Web tab

#### What did you expect?
I expected the strings to be visible as normal

#### What happened instead?
The translatable strings all say "missing translation":
![image](https://user-images.githubusercontent.com/76812/154230354-faa556db-fc15-4768-8541-97655512de56.png)

When I refresh the page, Element Web loads as normal

### Operating system

Ubuntu 21.10

### Browser information

Firefox 96.0 (64-bit)

### URL for webapp

develop.element.io

### Application version

missing translation: en|Element version: 135f37eeaf09-react-bb5f62edce79-js-2910e62bb68d missing translation: en|Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-02-16 10:38
Duplicate of https://github.com/vector-im/element-web/issues/9422

**Closed by t3chguy** 2022-02-16 10:38 UTC
Labels: T-Defect
