### ISSUE TITLE
Screen sharing in video room not available only in element desktop

### ISSUE THREAD

**Issue by fraimondo** [vector-im/element-web#23869] opened 2022-11-29 19:00 UTC
### Steps to reproduce

1. Join a Video Room after enabling the beta in the settings
2. a) In the web version, choose "toggle screensharing"
2. b) In the desktop version, no option

#### What did you expect?

Same behaviour

#### What happened instead?

Desktop version won't have the option.

### Operating system

macOS

### Application version

Element Nightly version: 2022112901 Olm version: 3.2.12 AND Element version: 1.11.15 Olm version: 3.2.12

### How did you install the app?

from element.io

### Will you send logs?

Yes

**Comment by fraimondo** [comment] 2022-11-29 19:02
Just sent two logs, one from element web and the other from desktop

**Comment by t3chguy** [comment] 2022-11-29 19:07
Duplicate of #4880

**Closed by t3chguy** 2022-11-29 19:07 UTC
Labels: T-Defect

**Comment by fraimondo** [comment] 2022-11-29 19:37
But this is not related to jitsii at all.

It's the new video room based on element call. I fail to see how this is a duplicate of #4880

**Comment by t3chguy** [comment] 2022-11-29 19:44
Video Rooms Beta are backed by Jitsi. Only if you enable the extra `Element Call video rooms` labs flag will they be backed by EC.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/2403652/204632512-42b3226c-b866-4ebb-a547-90edca5abe6c.png">

You do not have that option enabled.

`enabled_labs: feature_video_rooms, feature_thread`

**Comment by fraimondo** [comment] 2022-11-29 19:52
Thanks! I enabled the feature and then created a new video room as changing the flag does not affect previous rooms.

Now it works!
