### ISSUE TITLE
Historical state misrepresented in the timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15358] opened 2020-10-01 18:22 UTC
If you create a room with (say) name "Typoe", say something in it, then rename it "Typo", you end up seeing:

 * Matthew changed the room name from Typo to Typo

...and the timeline (when the collapsed creation details are expanded) apparently shows Typo rather than the original Typoe.  in other words, looks like something's going wrong with our state sentinels in js-sdk, such that it forgets the prevcontent.

**Comment by t3chguy** [comment] 2020-10-02 14:06
Cannot reproduce this

![image](https://user-images.githubusercontent.com/2403652/94932352-dcd34f80-04c0-11eb-8cfa-6cf7293b1249.png)

**Comment by ara4n** [comment] 2020-11-08 16:48
i just tried to repro and failed too.

**Comment by jryans** [comment] 2020-11-20 11:55
Closing for now then, until there's new evidence of something wrong here.

**Closed by jryans** 2020-11-20 11:55 UTC
Labels: bug, cannot-reproduce, p1, severity:minor, type:timeline
