### ISSUE TITLE
Read receipts are not animating properly anymore

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#16872] opened 2021-04-06 13:18 UTC
There seems to some read receipt animation regression, at least in Firefox, but perhaps other browsers as well.

**Comment by jryans** [comment] 2021-04-06 13:24
@ara4n says in Chrome receipts are working vertically but not horizontally.

**Comment by jryans** [comment] 2021-04-06 13:25
@turt2live Which browser(s) were you testing your recent receipt changes in?

**Comment by turt2live** [comment] 2021-04-06 13:27
Duplicate of https://github.com/vector-im/element-web/issues/16646 ?

I've tested Chrome and Firefox on Ubuntu, and Chrome, Firefox, Edge on Windows.

**Comment by jryans** [comment] 2021-04-06 14:53
Hmm, well, it's at least related, but I'm not entirely sure yet if they're precisely the same...

I'm noticing further strangeness which suggests at least a larger scope than what's described in https://github.com/vector-im/element-web/issues/16646 currently... For example, the "N+" labels for many receipt avatars seems to require **two** clicks to actually show them on Firefox, but not on Chrome.

Overall, it seems like recent changes have made things "more weird" than before.

**Comment by turt2live** [comment] 2021-04-06 14:55
Read receipts have plagued us for years, so this doesn't feel any more broken than what it was. It's differently broken, but roughly the same amount.

The next step is to write our own animation library: https://github.com/vector-im/element-web/issues/16554 - all other options have been exhausted to work with this bloody thing.

**Closed** 2021-04-15 07:27 UTC
Labels: A-Read-Receipts, P1, S-Minor, T-Defect, X-Regression
