### ISSUE TITLE
Blurhash shown for images in the browser cache

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18243] opened 2021-07-26 17:27 UTC

**Comment by t3chguy** [comment] 2021-07-28 12:56
Related https://github.com/vector-im/element-web/issues/17879

**Comment by Palid** [comment] 2021-07-28 13:12
Images were properly cached for unencrypted messages, but weren't really in a cache for encrypted messages. 
While fixing this problem I found out that there's some regression with sizing blurhash/placeholders and fell into a rabbit hole. Both will be fixed by my PR.

**Comment by Palid** [comment] 2021-08-04 13:45
Duplicate of https://github.com/vector-im/element-web/issues/17862
Turns out we can't cache the images that are encrypted, but we are already caching non-encrypted images via browser means.
The proper solution is to make better user experience for loading encrypted images.

**Closed by Palid** 2021-08-04 13:45 UTC
Labels: A-Media, T-Defect
