### ISSUE TITLE
Toggle is not showing, probably because of the new theming changes

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#20413] opened 2022-01-05 21:25 UTC
### Steps to reproduce

When the toggle is off, then the whole Element is not showing.

https://user-images.githubusercontent.com/31655082/148291099-4deb6346-fb7b-4a1f-909d-27f79c54bd21.mp4

I changed 
matrix-react-sdk\res\themes\light-custom\css\_custom.scss:49

to get it working for us again but I think that's not the right way

### Operating system

Windows

### Browser information

Version 93.0.4577.63 (Official Build) (64-bit)

### URL for webapp

private server

### Application version

Private fork merged with:
Element version: 1.9.8 Olm version: 3.2.8

### Homeserver

private server

### Will you send logs?

No

**Comment by gsouquet** [comment] 2022-01-06 09:04
I have been unable to reproduce that with the latest `develop` using both Firefox or Chromium browsers

Could you confirm that you're not experiencing this issue on `develop.element.io` too? It might be something to do with the changes made on your private fork

**Comment by SimonBrandner** [comment] 2022-01-09 07:11
![2022-01-09_08-08](https://user-images.githubusercontent.com/25768714/148672835-c6aee0fa-4826-4952-a506-33e328c631f1.png)

Do you have these colours set? I think it would be better to first visit https://matrix.to/#/#element-themes:raim.ist before filing issue like this as they might be just naming changes not bugs

**Comment by t3chguy** [comment] 2023-07-13 10:52
Closing due to no info and cannot reproduce

**Closed by t3chguy** 2023-07-13 10:52 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, S-Minor, A-User-Settings, O-Uncommon
