### ISSUE TITLE
Spaces "Give feedback" button doesn't seem to work

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#18944] opened 2021-09-08 13:17 UTC
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1922197/132516207-68f6c88f-1175-4091-a17a-a13ab8690ab4.png)

I go to explore rooms in our Element space, and I click "Give feedback" in the top right, but nothing happens.

### What did you expect?
I expected to be prompted for feedback

### What happened?
Nothing happened

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2021090801 Olm version: 3.2.3

### How did you install the app?

https://instantly.forgetable.riot.im/domain/that/we/use/for/nightly/builds.html

### Homeserver

lant.uk

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment] 2021-09-08 13:37
Duplicate of https://github.com/vector-im/element-web/issues/18524

**Closed by t3chguy** 2021-09-08 13:37 UTC
Labels: T-Defect
