### ISSUE TITLE
Timeline is full of the same date separator

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#22841] opened 2022-07-14 08:36 UTC
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1922197/178939635-3f9d5aeb-273a-4b80-9a4a-b0d84063123d.png)

#### What did you expect?
Not so much Today

#### What happened instead?
Too much Today

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2022071301 Olm version: 3.2.8

### How did you install the app?

website

### Homeserver

lant.uk Synapse 1.61.1

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-07-14 11:36
Duplicate of https://github.com/vector-im/element-web/issues/13232

**Closed by robintown** 2022-07-14 11:36 UTC
Labels: T-Defect, S-Major, A-Timeline, O-Uncommon
