### ISSUE TITLE
Provide 1-1 context on invite

### ISSUE THREAD

**Issue by SISheogorath** [vector-im/element-web#19935] opened 2021-11-29 14:27 UTC
#### What would you like to do?

When I get an invite to a new 1-1 conversation out of nowhere, I would like to be able to estimate whether I consider this spam, or not.

#### Why would you like to do it?

I would like to do this, in order to make a meaningful decision about joining a conversation or not.

#### How would you like to achieve it?

I could imagine "the simplest way" to do this, is to provide "rooms in common" on an invite, as this could show me, if this person is from a giant room, that might experiences a spam attack or maybe a smaller room where I'm an admin in and should really care about user requests. Having a list of common rooms makes it also easy to check if this user maybe just joined or not, asked a question there, or alike. 

### Have you considered any alternatives?

I haven't come up with any better idea, than "rooms in common" yet. But ideas would be more than welcome :)

**Comment by SimonBrandner** [comment] 2021-11-29 19:12
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/9593, https://github.com/vector-im/element-web/issues/16706 and https://github.com/vector-im/element-web/issues/14339

**Closed by SimonBrandner** 2021-11-29 19:12 UTC
Labels: T-Enhancement
