### ISSUE TITLE
Tree navigation

### ISSUE THREAD

**Issue by CyberShadow** [vector-im/element-web#24802] opened 2023-03-11 20:33 UTC
### What would you like to do?

This is a proposal to provide an alternative design to the double-sidebar room navigation in Element (Web/Desktop).

Most IRC clients, as well as many desktop IM applications, provide navigation (for their equivalent of rooms) using a tree or tree-like control:

<table>
<tr>
<td align="center"><img src="https://dump.cy.md/86ddd92f230a10c656d8b6d5c7c8cdcb/20%3A11%3A42-upload.png"><br>Convos</td>
<td align="center"><img src="https://dump.cy.md/4180d498d0bdaa29171f5b6ccf0306ba/19%3A53%3A24-upload.png"><br>HexChat</td>
<td align="center"><img src="https://dump.cy.md/a250d553cc87d6cc02d708dd34102f68/19%3A56%3A58-upload.png"><br>IceChat</td>
</tr><tr>
<td align="center"><img src="https://dump.cy.md/65f0f8f6a436284f9e57e955f41ce71a/20%3A32%3A06-upload.png"><br>KVIrc</td>
<td align="center"><img src="https://dump.cy.md/0a3a1b696baf8a2c47e4883ec7d7c788/19%3A59%3A34-upload.png"><br>Miranda IM</td>
<td align="center"><img src="https://dump.cy.md/057427f9e896e583b9db926fe077a688/19%3A49%3A06-upload.png"><br>mIRC</td>
</tr><tr>
<td align="center"><img src="https://dump.cy.md/2ee48dc4b9d779a51ed03a40392617b3/20%3A01%3A22-upload.png"><br>Pidgin</td>
<td align="center"><img src="https://dump.cy.md/b597a7ac629f5031371a4ad9643215df/19%3A52%3A27-upload.png"><br>Relay</td>
<td align="center"><img src="https://dump.cy.md/35dee442192398aada81ad74d1d6e9aa/19%3A59%3A01-upload.png"><br>Smuxi</td>
</tr>
</table>

I think it would be great to have an option in Element to replace the double sidebars with such a navigation control.
Perhaps (optimistically), it may even prove to be more popular and accessible than the current approach to navigation; especially for users of nested spaces, or users of bridges which create nested spaces, such as mautrix-discord.

### Why would you like to do it?

Some advantages of tree-based navigation:

- The room topology is presented clearly in its entirety.
- All rooms are visible just by scrolling, and accessible with one click (provided that no nodes are collapsed).

Some disadvantages of the double-sidebar navigation (compared to tree-based navigation):

- It copies too much from Discord's UI. Users who have not used Discord may not be familiar or productive with this UI.
- It relies too much on the space icon for navigation. Spaces must have sufficiently unique and recognizable icons (incl. to users with color-blindness) to be reasonably accessible.
- When both sidebars are expanded, they use too much horizontal space.
- UX of nested spaces is quite poor with the current UI. To get to a sub-space when starting with a collapsed left-most sidebar, one has to click the tiny arrow near the top-level space, which expands the sidebar, then click the sub-space, then re-collapse the left sidebar to bring it back to the original (collapsed) state.

### How would you like to achieve it?

Some goals for a tree-based navigation in Element could be:

- Rooms are arranged into a nested tree, according to their spaces / meta-spaces topology.
- Rooms and spaces are presented as one line in the tree, with both the icon and the name (as in most of the screenshots above).
- Categories of rooms within a space (e.g. "Low priority") would form another, bottom-level tree node.
- Non-leaf nodes can be collapsed to save vertical space.
- It should probably be possible to rearrange rooms using drag-and-drop.

**Comment by t3chguy** [comment] 2023-03-11 20:42
Duplicate of https://github.com/vector-im/element-web/issues/19140

**Closed by t3chguy** 2023-03-11 20:42 UTC
Labels: T-Enhancement

**Comment by CyberShadow** [comment] 2023-03-11 20:44
@t3chguy Thanks, could you please merge applicable parts of the issue description, I think it would be valuable for future discussion.

**Comment by t3chguy** [comment] 2023-03-11 21:03
@CyberShadow we don't tend to change the words of issue creators except to add code blocks around logs. I suggest just adding a comment.
