### ISSUE TITLE
Input Box locks-up after sending Voice-Mail

### ISSUE THREAD

**Issue by blindshare** [vector-im/element-web#21329] opened 2022-03-06 16:14 UTC
### Steps to reproduce

1. Where are you starting? What can you see ?

-> Open a private chat wit another person. Record a voice-mail and "try" to send it. The voice mail gets send out, but the Input-Box locks-up. No further input can be done and click the "send button" has no effect. Also the "three dot menu" is not available anymore.
This behaviour aslo dosn't change if you select another person/chat and switch back. The box remains locked untill a restart of the App.

 
3. More steps…
4. Running the Matrix/Synapse Server (ver. 1.54) inside a Docker container. Clients are latest Element App on Win-10

#### What did you expect?
Voice chat gets send. Input-Box is ready to accept chat-messages. "Three dot Menu" is visible/accessable.
#### What happened instead?
Input-Box doesn not respond to any input. Send-Button without function when clicked. No hints in Server-Logfiles

### Operating system

Windows 10

### Application version

Element version: 1.10.6 Version von Olm: 3.2.8

### How did you install the app?

Installer

### Homeserver

matrix/synapse version 1.54

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-03-06 20:20
Duplicate of https://github.com/vector-im/element-web/issues/21151, which is fixed in the upcoming version

**Closed by robintown** 2022-03-06 20:20 UTC
Labels: T-Defect
