### ISSUE TITLE
Reactions popover violently shakes when searching for emoji

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18272] opened 2021-07-27 16:08 UTC

**Comment by turt2live** [comment] 2021-07-27 16:33
Evidence for "violent":

https://user-images.githubusercontent.com/1190097/127192505-84260f0b-04ce-4d5c-b048-fee852870e58.mp4

**Comment by robintown** [comment] 2021-07-27 19:54
I can't reproduce on Firefox, assuming this is Chrome/Electron-specific

**Comment by SimonBrandner** [comment] 2021-07-28 12:03
I can't repro on nightly

**Comment by HarHarLinks** [comment] 2021-08-12 13:08
I can repro on nightly. More info from #18514:

1. open picker to react with emoji
2. search, e.g. `de` to find :de: 
3. scroll to the bottom
### Operating system

arch

### Application version

Element Nightly version: 2021081201 Olm version: 3.2.3

### How did you install the app?

aur nightly-bin

**Comment by robintown** [comment] 2021-11-29 19:01
Duplicate of https://github.com/vector-im/element-web/issues/15940

**Closed by robintown** 2021-11-29 19:01 UTC
Labels: T-Defect, Z-Platform-Specific, X-Cannot-Reproduce, S-Minor, A-Electron, A-Reactions
