### ISSUE TITLE
Messages marked as "from unverified session" although evidently wrong

### ISSUE THREAD

**Issue by ManDay** [vector-im/element-web#22716] opened 2022-07-02 16:28 UTC
### Steps to reproduce

Log into Element Web, verify login from other session (emoji compare)

### Outcome

Messages in DMs show with a red exclamation point before them "Encrypted by an unverified session":

Your own messages
The other party's messages

The sessions from which the messages were send exist and are verified (in fact, all sessions are verified and cross verification is properly set up). They show as verified in the user pane.

### Operating system

Linux

### Browser information

FIrefox

### Homeserver

matrix.org, both parties

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-07-04 09:29
Duplicate of https://github.com/vector-im/element-web/issues/17187

**Closed by t3chguy** 2022-07-04 09:29 UTC
Labels: T-Defect
