### ISSUE TITLE
Collapse mx-reply in desktop pop-up notification

### ISSUE THREAD

**Issue by korneyda** [vector-im/element-web#25110] opened 2023-04-14 13:11 UTC
### Your use case

Hello
#### What would you like to do?
It would be nice if for pop-up notifications, when replying to a message, the original message would be compressed in some way so that the reply message could be seen
#### Why would you like to do it?
When the original message is long, the response is not visible in the pop-up window

**Short original message - normal visible reply message**
![visible_msg](https://user-images.githubusercontent.com/13951456/232052706-d0b5e7c4-f5f5-4295-b01f-08650aaceff9.png)

**Long original message - not visible reply message**
![not_visible_msg](https://user-images.githubusercontent.com/13951456/232052698-25c1ff1b-04fe-49db-b2e5-0ab4f4de4629.png)

**Comment by t3chguy** [comment] 2023-04-14 14:15
Duplicate of https://github.com/vector-im/element-web/issues/17859

**Closed by t3chguy** 2023-04-14 14:15 UTC
Labels: T-Enhancement
