### ISSUE TITLE
Unable to Pin to Task Manager (Plasma) 

### ISSUE THREAD

**Issue by itguyeric** [vector-im/element-web#14658] opened 2020-07-20 16:42 UTC
### Description

When I right click the Element icon, I am unable to pin it to the task bar. The option is greyed out.

![image](https://user-images.githubusercontent.com/16472853/87963236-04984700-ca7e-11ea-8f88-c0ecac01d538.png)

### Version information
Fedora 32, Plasma
KDE Version: 5.18.5

Element 1.7.1
OLM 3.1.3
Flatpak

**Comment by t3chguy** [comment] 2020-07-20 16:43
Probably caused by https://github.com/vector-im/riot-web/issues/14619

**Comment by lerker100** [comment] 2020-07-20 16:48
Same on Manjaro. Installed through Flathub.
 
KDE Plasma version: 5.19.3
Electron: 9.1.0
Element version: 1.7.1
olm version: 3.1.3

**Comment by tiny6996** [comment] 2020-07-20 18:05
you can pin the app if you pull it up through the application menu , but it doesn't work when you try to pin it from the taskbar

OS: Fedora 32 Plasma
KDE Plasma version: 5.18.5
Element 1.7.1

**Comment by t3chguy** [comment] 2020-10-02 11:47
Closing as I believe this should be resolved in the latest versions, please shout if you are still experiencing this issue!

**Closed by t3chguy** 2020-10-02 11:47 UTC
Labels: bug
