### ISSUE TITLE
a11y: arrow-down doesn't get the cursor out of the filter

### ISSUE THREAD

**Issue by fcnjd** [vector-im/element-web#21824] opened 2022-04-16 12:51 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
In a logged in Element window, move into the list f rooms and chats, using only a keyboard as a user who is blind and uses a screenreader would do it
2. What do you click?
Inside the list, press the up-arrow until you are at the top, and then again to go into the text box to filter the rooms
3. More steps…
Turning on a screenreader is probably not needed, since things can also be verified without it here

#### What did you expect?
As pressing the up arrow inside the room list brings the focus into the filter, I'd expect the down-arrow to bring me back into the list, just as it is logically.
#### What happened instead?
Inside the filter, the down-arrow does nothing, or at least it doesn't bring the focus back into the rooms list. A few months ago in an older Element version, this worked properly, but now something is broken.

### Operating system

Windows

### Application version

Version of Element: 1.10.10 Version of Olm: 3.2.8

### How did you install the app?

from element.io

### Homeserver

juliandreykorn.de

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-16 23:21
Will no longer be relevant when the new search experience launches

**Comment by t3chguy** [comment] 2022-04-21 12:24
Duplicate of https://github.com/vector-im/element-web/issues/21436

**Closed by t3chguy** 2022-04-21 12:24 UTC
Labels: T-Defect, S-Minor, A11y, O-Uncommon, Z-Labs, A-New-Search-Experience
