### ISSUE TITLE
Difficult to separate message being typed from rest of timeline

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-web#15215] opened 2020-09-16 16:48 UTC
### Description

It is very difficult to visually separate text you are typing from text already in the timeline, especially when your message is multi-line.

### Steps to reproduce

- Send a few messages
- Type another multi-line message
- Try to quickly identify where the message you are typing starts

### Version information

- **Platform**: Desktop
- **OS**: openSUSE Tumbleweed/GNOME
- **Version**: 1.7.7

### Screenshots

<details><summary>Timeline scrolled all the way down with multi-line message</summary>

![image](https://user-images.githubusercontent.com/37966924/93365892-4a854780-f842-11ea-95b9-3589a97f6ade.png)

</details>

<details><summary>Timeline scrolled halfway with multi-line message</summary>

![image](https://user-images.githubusercontent.com/37966924/93365958-67217f80-f842-11ea-9373-2ff35188a68b.png)

</details>

<details><summary>Timeline scrolled all the way down with single-line message</summary>

![image](https://user-images.githubusercontent.com/37966924/93366053-88826b80-f842-11ea-8554-95e4462eb6b6.png)

</details>

<details><summary>Timeline scrolled halfway with a single-line message</summary>

![image](https://user-images.githubusercontent.com/37966924/93366128-a059ef80-f842-11ea-896b-cac5c22fb062.png)

</details>

<details><summary>Previous example but in light mode to show that it too is affected</summary>

![image](https://user-images.githubusercontent.com/37966924/93366281-d5664200-f842-11ea-8847-dd2b0c925480.png)

</details>

### Possible solutions
<details>
<summary>
• (1) Put message text in a differently-coloured bubble like FB Messenger
</summary>

![image](https://user-images.githubusercontent.com/37966924/93367084-f4b19f00-f843-11ea-9004-bda78fbacce5.png)

</details>

- (2) Add a different-coloured `margin-top` to the entire bottom panel

- (3) Make the whole bottom panel a different colour to the timeline

**Comment by t3chguy** [comment] 2020-09-16 16:53
Duplicate of https://github.com/vector-im/element-web/issues/14735

**Closed by t3chguy** 2020-09-16 16:53 UTC
Labels: bug, ui/ux

**Comment by TR-SLimey** [comment] 2020-09-16 16:59
Indeed it is. My bad!
