### ISSUE TITLE
Missing reactions in room (main timeline)

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#25630] opened 2023-06-19 23:23 UTC
### Steps to reproduce

1. Notice missing reactions on a message
1. Reproduced on Element Web and other Element Desktop clients
1. Consistent after update/refresh and switching rooms

#### What did you expect?

All reactions should be visible

#### What happened instead?

No reactions show up on the message and the reaction events don't even show up as hidden events in the timeline

All of the missing reactions correspond to these rageshake log entries which indicate the events are seen by the client but being mistakenly ignored in the main timeline ([details in the rageshake](https://github.com/matrix-org/element-web-rageshakes/issues/21918))
```
EventTimelineSet.addEventToTimeline: Ignoring event=$abc that does not belong in timeline=!foo:2023-06-19T22:17:22.759Z timelineSet(threadId=undefined)
```

---

Probably related to:

 - https://github.com/vector-im/element-web/issues/25596

### Operating system

Manjaro Linux (Arch-based)

### Browser information

Chrome Version 114.0.5735.133

### URL for webapp

https://develop.element.io/

### Application version

Element version: 041747391cf7-react-a491795aa7ed-js-80cdbe1058c1 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes -> https://github.com/matrix-org/element-web-rageshakes/issues/21918

**Comment by weeman1337** [comment] 2023-06-20 08:21
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-06-20 08:21
Duplicate of https://github.com/vector-im/element-web/issues/25596

**Closed** 2023-06-20 08:21 UTC
Labels: T-Defect, A-Timeline, A-Reactions

**Comment by MadLittleMods** [comment] 2023-06-20 17:53
Another set of debug logs with the extra info from https://github.com/matrix-org/matrix-js-sdk/pull/3494 -> https://github.com/matrix-org/element-web-rageshakes/issues/21931

Here are the logs around one missing reaction on the original message: `$p_giIbORbdY2Mk0f6mSFZOAfcG24eqIDsG-8PT7_E7E`
```
2023-06-20T17:42:26.548Z D Room::eventShouldLiveIn: eventId=$p_giIbORbdY2Mk0f6mSFZOAfcG24eqIDsG-8PT7_E7E parentEventId=$nH4JpeIhEuiY9ets2cgYn4IvsyQ_feCfZj-6MVP81YE found=true

2023-06-20T17:42:26.550Z D Room::eventShouldLiveIn: eventId=$p_giIbORbdY2Mk0f6mSFZOAfcG24eqIDsG-8PT7_E7E parentEventId=$nH4JpeIhEuiY9ets2cgYn4IvsyQ_feCfZj-6MVP81YE found=false
2023-06-20T17:42:26.550Z D Room::eventShouldLiveIn: eventId=$p_giIbORbdY2Mk0f6mSFZOAfcG24eqIDsG-8PT7_E7E belongs to an unknown timeline
2023-06-20T17:42:26.550Z W EventTimelineSet.addEventToTimeline: Ignoring event=$p_giIbORbdY2Mk0f6mSFZOAfcG24eqIDsG-8PT7_E7E that does not belong in timeline=!QKLszEbjJygAduTMZK:librepush.net:2023-06-20T17:40:23.927Z timelineSet(threadId=undefined)
```

Here is a missing reaction on the edited message: `$NccBSsH59-FnLgOiALNk6sY4pPhUyUnHyrIg3UlvNNo`

```
2023-06-20T17:40:40.014Z D Room::eventShouldLiveIn: eventId=$NccBSsH59-FnLgOiALNk6sY4pPhUyUnHyrIg3UlvNNo parentEventId=$nH4JpeIhEuiY9ets2cgYn4IvsyQ_feCfZj-6MVP81YE found=true
2023-06-20T17:40:40.014Z D Room::eventShouldLiveIn: eventId=$nH4JpeIhEuiY9ets2cgYn4IvsyQ_feCfZj-6MVP81YE not a relation
2023-06-20T17:40:40.014Z D Room::eventShouldLiveIn: eventId=$NccBSsH59-FnLgOiALNk6sY4pPhUyUnHyrIg3UlvNNo parentEventId=$nH4JpeIhEuiY9ets2cgYn4IvsyQ_feCfZj-6MVP81YE found=false
2023-06-20T17:40:40.014Z D Room::eventShouldLiveIn: eventId=$NccBSsH59-FnLgOiALNk6sY4pPhUyUnHyrIg3UlvNNo belongs to an unknown timeline
2023-06-20T17:40:40.014Z W EventTimelineSet.addEventToTimeline: Ignoring event=$NccBSsH59-FnLgOiALNk6sY4pPhUyUnHyrIg3UlvNNo that does not belong in timeline=!QKLszEbjJygAduTMZK:librepush.net:2023-06-20T17:40:23.927Z timelineSet(threadId=undefined)
```
