### ISSUE TITLE
Upgrade a space's version to support restricted joins

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#19564] opened 2021-11-01 08:45 UTC
#### What would you like to do?

After create a space, I should be able to set its join rule to "restricted". This isn't currently possible on Element Web because the space is created at room version 6, and Element Web simply hides the restricted option rather than offering to upgrade the space.

#### Why would you like to do it?

So I can make the space joinable by members of another space. 

#### How would you like to achieve it?

This is possible on EA, which upgrades the room's version in place if necessary (just like when you set a *room* to restricted).

### Have you considered any alternatives?

We could just create new spaces at room version 9.

**Comment by novocaine** [comment] 2021-11-01 08:45
I think main use case for this is probably subspaces?

**Comment by t3chguy** [comment] 2021-11-01 08:47
Duplicate of https://github.com/vector-im/element-web/issues/19208

**Closed by t3chguy** 2021-11-01 08:47 UTC
Labels: S-Minor, A-Spaces, T-Enhancement
