### ISSUE TITLE
Offer Element Desktop on the Microsoft Store

### ISSUE THREAD

**Issue by lectrician1** [vector-im/element-web#23878] opened 2022-11-30 14:26 UTC
#### What would you like to do?

Install Element Desktop on Windows from the Microsoft Store

#### Why would you like to do it?

Faster, easier to install, and I can see it in my history of installed apps on my Microsoft account and easily install it on other devices.

**Comment by t3chguy** [comment] 2022-11-30 14:29
Related https://github.com/vector-im/element-web/issues/21165 https://github.com/vector-im/element-web/issues/2817
The Squirrel config we're using in Element Builder doesn't support appx which is needed for the MS Store, which means we'd need to change our whole build process & update mechanism to NSIS which makes this somewhat tricky. As well as the added issue of re-exporting encryption from servers in the US

**Comment by rokejulianlockhart** [comment] 2022-12-30 00:51
@t3chguy, additionally, APPX is a deprecated target (like MSI). MSIX is the current installation format. However, the current liberalization of the Microsoft Store may mean that MSIs are allowed. Is that supported by your configuration of Squirrel?

**Comment by rokejulianlockhart** [comment] 2022-12-30 00:52
https://github.com/vector-im/element-web/issues/16738

**Comment by t3chguy** [comment] 2023-01-03 11:12
@rokejulianlockhart the MSI target within Squirrel for electron-builder just creates an MSI which unpacks the Squirrel installer, it is as close to useless as you could imagine.

**Comment by t3chguy** [comment] 2023-01-03 11:12
Duplicate of https://github.com/vector-im/element-web/issues/16738

**Closed by t3chguy** 2023-01-03 11:12 UTC
Labels: X-Needs-Product, T-Enhancement, A-Packaging, O-Uncommon

**Comment by rokejulianlockhart** [comment] 2023-01-09 11:59
@t3chguy, in which case, .exes might be allowed. You're really causing my to wonder why you chose Squirrel, though. VS Code manages to generate useful installers despite being Electron.
