### ISSUE TITLE
Prompted to verify against other devices even if there aren't any

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#17765] opened 2021-06-24 18:30 UTC
Signing into an account which doesn't have any other devices logged in will still tell you to verify against another device.

Same bug on iOS: https://github.com/vector-im/element-ios/issues/4474

**Comment by robintown** [comment] 2021-06-29 20:04
Regression since this was supposedly fixed before: #13289

**Comment by duxovni** [comment] 2021-10-05 13:07
Fixed in matrix-org/matrix-react-sdk#6811

**Closed by duxovni** 2021-10-05 13:07 UTC
Labels: T-Defect, X-Regression, S-Minor, A-E2EE-Cross-Signing, Z-Papercuts, O-Occasional
