### ISSUE TITLE
Read receipts overlap images in a thread

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24001] opened 2022-12-14 18:20 UTC
### Steps to reproduce

1. Begin a thread
2. Send an image to that thread
3. Have 1+ other people read it

#### What did you expect?

Read receipts to be under or next to the image

#### What happened instead?

The read receipts overlapped. I don't have a screenshot due to information sensitivity. 

If it helps, my right panel is the default width.

### Operating system

Windows 10

### Application version

Nightly (2022-12-14)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by gsouquet** [comment] 2022-12-15 07:32
Duplicate of https://github.com/vector-im/element-web/issues/23569

**Closed by gsouquet** 2022-12-15 07:32 UTC
Labels: T-Defect
