### ISSUE TITLE
Go to bottom of timeline button doesn't work reliably

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19907] opened 2021-11-26 12:22 UTC
### Steps to reproduce

1. Click on a permalink
2. Click the button to go to the bottom of the timeline

#### What did you expect?
Jump to the bottom of the timeline

#### What happened instead?
Nothing (see rageshake for screen recording)

Scrolling away from that point in the timeline got it working again

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 194aeac19e2d-react-138f6685d40e-js-b33b01df0f32 Olm version: 3.2.3

### Will you send logs?

Yes

**Comment by ShadowJonathan** [comment] 2021-12-08 14:58
This is also sometimes the case when clicking message links twice, see https://github.com/vector-im/element-web/issues/20097 for notes about timelines still being "loaded"

**Comment by aaronraimist** [comment] 2021-12-10 13:49
Duplicate of https://github.com/vector-im/element-web/issues/19813

**Closed by aaronraimist** 2021-12-10 13:49 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Timeline, O-Occasional
