### ISSUE TITLE
Reply indent in threads view

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19773] opened 2021-11-16 17:49 UTC
### Your use case

![image](https://user-images.githubusercontent.com/2803622/142038603-be82f61b-66b5-41eb-86a7-01a833b034cb.png)

clearly this isn't great, right?

**Comment by SimonBrandner** [comment] 2021-11-16 18:25
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19629

**Closed by SimonBrandner** 2021-11-16 18:25 UTC
Labels: T-Enhancement

**Comment by HarHarLinks** [comment] 2021-11-16 19:18
Thanks, I always try to look for existing issues but it's not always easy to find the right search queries.
