### ISSUE TITLE
Key backup nag dismissal needs to be done twice

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#11692] opened 2019-12-19 14:05 UTC
<img width="336" alt="image" src="https://user-images.githubusercontent.com/1922197/71179563-55d22500-2268-11ea-8ed4-3ba4d91e195a.png">

<img width="513" alt="image" src="https://user-images.githubusercontent.com/1922197/71179521-43f08200-2268-11ea-9a27-69bd1d18d60d.png">

to reproduce:
- don't have key backup set up
- go to an encrypted room
- get nagged
- click "don't ask me again"
- click "don't ask again" on the _are you sure_ modal
- still see the nag pane
- click "don't ask me again"
- click "don't ask again" on the _are you sure_ modal for the second time
- the nag pane is gone

**Comment by kittykat** [comment] 2021-11-30 18:02
We cannot reproduce this issue any more so I will close it for now.

**Closed by kittykat** 2021-11-30 18:02 UTC
Labels: T-Enhancement, A-E2EE-Key-Backup, X-Needs-Community-Testing
