### ISSUE TITLE
Unexpected concurrent DOM modification causing soft-crash

### ISSUE THREAD

**Issue by justjanne** [vector-im/element-web#24338] opened 2023-01-26 10:25 UTC
https://github.com/matrix-org/element-web-rageshakes/issues/19479

```
2023-01-23T10:17:06.116Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2023-01-23T10:17:06.119Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2023-01-23T10:17:06.119Z E The above error occurred while React was rendering the following components: 
    at h3
    at div
    at div
    at RoomPreviewBar (webpack:///react-sdk/src/components/views/rooms/RoomPreviewBar.tsx:114:8)
    at ErrorBoundary (webpack:///react-sdk/src/components/views/elements/ErrorBoundary.tsx:38:8)
    at div
    at RoomView (webpack:///react-sdk/src/components/structures/RoomView.tsx:385:8)
    at webpack:///react-sdk/src/contexts/MatrixClientContext.tsx:39:38
    at div
    at div
    at div
    at LoggedInView (webpack:///react-sdk/src/components/structures/LoggedInView.tsx:142:8)
    at ErrorBoundary (webpack:///react-sdk/src/components/views/elements/ErrorBoundary.tsx:38:8)
    at MatrixChat (webpack:///react-sdk/src/components/structures/MatrixChat.tsx:244:8)
```

**Comment by t3chguy** [comment] 2023-01-30 11:29
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2023-01-30 11:29 UTC
Labels: T-Defect
