### ISSUE TITLE
Microphone disappeared from settings after updating Element-Desktop

### ISSUE THREAD

**Issue by clickworkorange** [vector-im/element-web#18001] opened 2021-07-14 21:01 UTC
Please delete this - not an Element issue!

**Comment by clickworkorange** [comment] 2021-07-15 20:01
Actually, it is an issue with Element - microphone input verified in Ardour & Audactity, where it works perfectly. So I'm reopening this! 


Description

My laptop's microphone is no longer available in the 'Microphone' drop-down in the 'Voice & Video' settings. In fact all the items in the list appear to be audio output devices. My microphone was working well until I recently upgraded to Element 1.7.32.
Steps to reproduce

-     Open 'All Settings' and click on 'Voice & Video'
-     Expand the drop-down select for 'Microphone'
-     The microphone input is not listed

Logs being sent: yes
Version information

    Platform: desktop

For the desktop app:

    OS: Devuan Beowulf Linux
    Version: 1.7.32

**Comment by SimonBrandner** [comment] 2021-07-15 20:18
This is probably my fault

**Comment by SimonBrandner** [comment] 2021-07-16 06:25
Hmm, I am not able to reproduce this. 

@clickworkorange, could you please press `Ctrl + Shift + I` which will open the dev tools and click `Console`. In there type `await navigator.mediaDevices.enumerateDevices()`. That should give you the devices as the browser sees them. You can then expand each device and see if they match what Element shows. 

Does it match or not? If it does, then there really is a regression in Element otherwise there is something weird going on with your browser/Element desktop

**Comment by clickworkorange** [comment] 2021-07-16 11:07
@SimonBrandner Many thanks for looking at this! Here's what I get in the console: 

    [{
        "deviceId": "default",
        "kind": "audioinput",
        "label": "Default",
        "groupId": "1d128d1cb8073606b48dbc0692587aa7b247bdde880c757aaa82853e252c6777"
    },{
        "deviceId": "95eb11877ccebf8e581d811dd0758ce8b7a906da81f6ef86aab089f967461cba",
        "kind": "audioinput",
        "label": "HDA Intel PCH, ALC269VC Analog-Default Audio Device",
        "groupId": "201e5e144d9e3e9e5e1bfa50ed732b33856b63fd0f5fff4e95b8cca97205bb09"
    },{
        "deviceId": "1e0a1d39d88b240e966e5e0b89c35580e4449d7e3c13803e6cfa598f5a3cca62",
        "kind": "audioinput",
        "label": "HDA Intel PCH, ALC269VC Analog-Front speakers",
        "groupId": "f67289a5f8261a09434dc68398f5d3a53f1c39108672a5ede554078ef8f841a1"
    },{
        "deviceId": "c275341560c3767e1cad75b89a6fd2cd486149f2b4ca4a84b8c716751ddb50b1",
        "kind": "audioinput",
        "label": "HDA Intel PCH, ALC269VC Analog-Direct sample snooping device",
        "groupId": "8e4e6241e244fde4306d95a0607f157fda97b9c6c0f4babc483a134157f3c411"
    },{
        "deviceId": "7a1fc427ff33668a130c480fd46cf1758bac53fbdd56cccc368f861d602de22d",
        "kind": "audioinput",
        "label": "HDA Intel PCH, ALC269VC Analog-Direct hardware device without any conversions",
        "groupId": "5a6b1b9ce3aae1b253c2943efb3f379ec5a466c85b20f0bb370fc548480debc9"
    },{
        "deviceId": "89127f04184a5977575ab9bd9e66e1ad7177e21617db17bd2f52076019d9d36d",
        "kind": "audioinput",
        "label": "HDA Intel PCH, ALC269VC Analog-Hardware device with all software conversions",
        "groupId": "26e8b4aa494e20c55e39e0f22be1cfcd93f19c0e21fc9cf90444eedc5506092b"
    },{
        "deviceId": "1e1afc04ca69bcc644d8bd5f8fdb98cf786416d9ac71fda4a382c128ea748a64",
        "kind": "audioinput",
        "label": "HDA Intel PCH-USB Stream Output",
        "groupId": "ffd3f1966dc1e7c874a22560d8324ecb148b940468e9ae6d7f51ee2f42aa171b"
    },{
        "deviceId": "17d0a817ef03f0190138bf029942af3e7a50da42159e1bfef99969800d153bbf",
        "kind": "videoinput",
        "label": "Integrated Camera (04f2:b2ea)",
        "groupId": "dd278db395df52d559058de9dbdd90a1abcf4370d05992d09caefbef04b8521c"
    },{
        "deviceId": "default",
        "kind": "audiooutput",
        "label": "Default",
        "groupId": "default"
    },{
        "deviceId": "89127f04184a5977575ab9bd9e66e1ad7177e21617db17bd2f52076019d9d36d",
        "kind": "audiooutput",
        "label": "HDA Intel PCH, ALC269VC Analog-Hardware device with all software conversions",
        "groupId": "592c22c9d98d9c96a44b7d16bbbc03ace1a54fb887b1b881de0d105829565645"
    },{
        "deviceId": "f094697350794eefc072d804d88c9beb0e794ade2924300845271268c7dd518f",
        "kind": "audiooutput",
        "label": "HDA Intel PCH, HDMI 0-Hardware device with all software conversions",
        "groupId": "2db5e404840c70cccd340389a492af2cf04b4f63cac22a4ee3ad8ce8fd2cd05e"
    },{
        "deviceId": "c4c225bf97a85aaf4294a2ac21698ea521f36c8ddaa8064fe9971a27864cdd09",
        "kind": "audiooutput",
        "label": "HDA Intel PCH, HDMI 1-Hardware device with all software conversions",
        "groupId": "a0bd7ae7504b3f706edd54da926c19bb152fa65bbb288e695a109c51f7f09678"
    },{
        "deviceId": "0d56f8a39e3c480fcc03a1a3c5bf2a2b1c892054b442fd492ccc889082ab27a0",
        "kind": "audiooutput",
        "label": "HDA Intel PCH, HDMI 2-Hardware device with all software conversions",
        "groupId": "b2f286e401c35a6c1560d70fbfc170437c6e4526efa02e8b04b5f9533f78e8d6"
    }]

I have tried with "Default" and "HDA Intel PCH, ALC269VC Analog-Default Audio Device", restarting Element Desktop in between, but no one can hear me. But when I open Audacity and activate monitoring I get a signal: 

![Screenshot_2021-07-16_11-55-05](https://user-images.githubusercontent.com/196348/125938577-afad9625-8982-44e7-983a-cf7ae351387d.png)

**Comment by SimonBrandner** [comment] 2021-07-16 11:28
To clarify you have both the issue of your mic not appearing on the list and your mic not working or did the former resolve itself?

**Comment by clickworkorange** [comment] 2021-07-16 20:47
To be honest I'm not quite sure; I think there used to be a "Microphone" item in the list, but it may just have been "Default".

**Comment by clickworkorange** [comment] 2021-07-16 20:57
Be that as it may, no one can hear me through Element any more - and this is true for both the desktop client and the web client (recently tested in desperation).

**Comment by SimonBrandner** [comment] 2021-07-17 06:25
Could please try out if you see the same issue on an [older version of Element](https://riots.im/1.7.30/)? (just to make sure)

**Comment by gsouquet** [comment] 2021-07-27 09:44
Removing th `X-Release-Blocker` and `X-Regression` tag until we can reproduce what the problem is.

@clickworkorange I can see that you edited the original issue description, does that mean that we can safely close this ticket, or do you still have audio issues when using Element Desktop?

**Comment by clickworkorange** [comment] 2021-07-27 14:44
I still have issues with the microphone in Element Desktop - and using the version suggested by @SimonBrandner I also cannot hear the other party (I hear the ring signal, and Firefox asks which microphone I want to use, with the only option being "Default").

**Comment by SimonBrandner** [comment] 2021-07-27 14:47
> I still have issues with the microphone in Element Desktop - and using the version suggested by @SimonBrandner I also cannot hear the other party (I hear the ring signal, and Firefox asks which microphone I want to use, with the only option being "Default").

Well that sounds very much like an issue on your side, sorry. Just to be completely sure, could you please try [an even older version of Element](https://riots.im/1.7.26/)

**Comment by SimonBrandner** [comment] 2021-08-15 17:51
I will close this as I can not reproduce this and there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.

**Closed by SimonBrandner** 2021-08-15 17:51 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, A-VoIP, A-Media
