### ISSUE TITLE
Element desktop frequently crashes

### ISSUE THREAD

**Issue by rihardsk** [vector-im/element-web#23304] opened 2022-09-18 21:19 UTC
### Steps to reproduce

1. Open the app, wait around 10 seconds (sometimes a bit more, but not longer than a minute i guess).
2. Experience the crash

This happens very reliably. I cannot use the app for more than a few seconds. I've tried deleting `~/.config/Elemen` and reinstalling the app without success.

#### What did you expect?
Element donesn't crash

#### What happened instead?
A crash

### Operating system

Arch Linux

### Application version

Element version: 1.11.4 Olm version: 3.2.12

### How did you install the app?

From the official Arch repo (community)

### Homeserver

Private homeserver, Synapse 1.67.0 (from nixpkgs)

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-09-20 09:08
Duplicate of https://github.com/vector-im/element-web/issues/22690

**Closed by t3chguy** 2022-09-20 09:08 UTC
Labels: T-Defect

**Comment by rihardsk** [comment] 2022-11-13 13:00
@t3chguy this is still happening on v1.11.10-2. Please re-open.

**Comment by t3chguy** [comment] 2022-11-13 13:18
If there's no reports from the official builds then you'll need to file a bug with the community package you used

**Comment by rihardsk** [comment] 2022-11-14 22:29
Ok, thanks. I'll report back here if anything relevant comes up.

Btw, are the Ubuntu and Flatpak packages the ones considered official?

**Comment by t3chguy** [comment] 2022-11-14 23:15
> Ok, thanks. I'll report back here if anything relevant comes up.
> 
> Btw, are the Ubuntu and Flatpak packages the ones considered official?

https://github.com/flathub/im.riot.Riot

> This is a community-maintained Flatpak distribution of Element Desktop, formerly called Riot.

**Comment by rihardsk** [comment] 2023-01-05 19:46
The crashes stopped happening once I disabled search indexing as suggested in https://github.com/vector-im/element-web/issues/20926
