### ISSUE TITLE
unread count is hide after scroll room list down

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#20361] opened 2021-12-27 04:34 UTC
### Steps to reproduce

1. See unreadded messages in room and summary count of unreaded messages in "favorites" block
2. Scroll room list down - see, that unread room hide, but summary count of unread favorites - stil shown
3. Scroll room list down again - and I see, that "favorites" labal with unread count - is replaced by "People" summary without unread count.

#### What did you expect?
"favorites"  summary must be shown with "people" summary and other. User must see unread counts and must understand - where he must scroll for get unread rooms.
#### What happened instead?
It is hided.

![1](https://user-images.githubusercontent.com/1297163/147434706-4004df37-78b9-4ca8-9dc4-b3d8b967ec65.png)
![2](https://user-images.githubusercontent.com/1297163/147434704-f411eab6-8f64-485c-ab57-0fbbd65aa7a8.png)
![3](https://user-images.githubusercontent.com/1297163/147434703-c03a7f9e-0eef-4a40-8ad3-9200461e41c5.png)

### Operating system

Ubuntu 20.04

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

element debian repo

### Homeserver

https://rsprim.ru

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2021-12-27 11:28
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/14085

**Closed by SimonBrandner** 2021-12-27 11:28 UTC
Labels: A-Room-List, X-Needs-Design, X-Needs-Product, T-Enhancement, O-Occasional
