### ISSUE TITLE
Sorting People or Favourites by activity is not working right on develop

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#24537] opened 2023-02-15 10:44 UTC
### Steps to reproduce

1. Open the people metaspace and look at the list of the DMs
2. Check that you have it set to "sort by activity"
3. Start looking through the old messages that are at the top and they re-sort themselves correctly
4. Click to another meta space (e.g. favourites), then click back to "people" and see that the same old DMs are at the top again

It's the same withe the Favourites list

#### What did you expect?
DMs are sorted by activity

#### What happened instead?
DMs are in a random order and don't reflect who you've talked to recently

### Browser information

Chromium 110.0.5481.77 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: dfe2a21b5860-react-a4ff959aa184-js-cdd7dbbb2b12 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-02-15 11:06
Looks like a duplicate of https://github.com/vector-im/element-web/issues/24527

**Closed by t3chguy** 2023-02-15 11:06 UTC
Labels: T-Defect, S-Major, A-Room-List
