### ISSUE TITLE
Room search stops filtering half-way through search

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#15061] opened 2020-08-28 09:54 UTC
### Description

![image](https://user-images.githubusercontent.com/1342360/91547909-83558f00-e91c-11ea-93cc-b54a0ab4846e.png)

Searching seems to stop firing on each character half-way through a search. Now changing the characters doesn't change the room list.

Most notably, it seems to filter on pressing the first character, but every character after that is ignored.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Debian Linux
- **Version**: Nightly Aug 28th

**Comment by turt2live** [comment] 2020-08-28 13:52
appears to be a duplicate of https://github.com/vector-im/element-web/issues/14750

**Closed by turt2live** 2020-08-28 13:52 UTC
Labels: bug

**Comment by MRAAGH** [comment] 2021-01-26 13:53
I have encountered this issue as well. Only the first character is used for filtering, the rest are ignored.

I have encountered this issue after being unexpectedly required to relog (`Some session data, including encrypted message keys, is missing. Sign out and sign in to fix this, restoring keys from backup. Your browser likely removed this data when running low on disk space.`).

This issue was fixed for me after restarting Element. I am unable to reproduce this issue.

Logs being sent: no

## Version information

- Platform: desktop
- OS: Arch Linux
- Version: Element 1.7.16

**Comment by anoadragon453** [comment] 2021-01-26 15:38
I'm seeing the following in your logs:

```
2021-01-22T02:33:26.064Z W Recalculating filtered room list
2021-01-22T02:33:26.384Z W Recalculating filtered room list
2021-01-22T02:33:26.384Z W Recalculating filtered room list
2021-01-22T02:33:26.385Z W Recalculating filtered room list
2021-01-22T02:33:26.385Z W Recalculating filtered room list
2021-01-22T02:33:26.386Z W Recalculating filtered room list
2021-01-22T02:33:26.386Z W Recalculating filtered room list
2021-01-22T02:33:26.386Z W Recalculating filtered room list
2021-01-22T02:33:26.387Z W Recalculating filtered room list
2021-01-22T02:33:26.387Z W Recalculating filtered room list
2021-01-22T02:33:26.388Z W Recalculating filtered room list
2021-01-22T02:33:26.389Z W Recalculating filtered room list
2021-01-22T02:33:26.389Z W Recalculating filtered room list
2021-01-22T02:33:26.390Z W Recalculating filtered room list
2021-01-22T02:33:26.390Z W Recalculating filtered room list
2021-01-22T02:33:26.390Z W Recalculating filtered room list
2021-01-22T02:33:26.391Z W Recalculating filtered room list
2021-01-22T02:33:26.391Z W Recalculating filtered room list
2021-01-22T02:33:26.392Z W Recalculating filtered room list
2021-01-22T02:33:26.560Z W Recalculating filtered room list
2021-01-22T02:33:26.605Z W Recalculating filtered room list
2021-01-22T02:33:26.606Z W Recalculating filtered room list
2021-01-22T02:33:26.606Z W Recalculating filtered room list
2021-01-22T02:33:26.607Z W Recalculating filtered room list
2021-01-22T02:33:26.607Z W Recalculating filtered room list
2021-01-22T02:33:26.608Z W Recalculating filtered room list
2021-01-22T02:33:26.608Z W Recalculating filtered room list
2021-01-22T02:33:26.608Z W Recalculating filtered room list
2021-01-22T02:33:26.609Z W Recalculating filtered room list
2021-01-22T02:33:26.609Z W Recalculating filtered room list
2021-01-22T02:33:26.609Z W Recalculating filtered room list
2021-01-22T02:33:26.610Z W Recalculating filtered room list
2021-01-22T02:33:26.610Z W Recalculating filtered room list
2021-01-22T02:33:26.611Z W Recalculating filtered room list
2021-01-22T02:33:26.611Z W Recalculating filtered room list
2021-01-22T02:33:26.611Z W Recalculating filtered room list
2021-01-22T02:33:26.612Z W Recalculating filtered room list
2021-01-22T02:33:26.612Z W Recalculating filtered room list
2021-01-22T02:33:26.612Z W Recalculating filtered room list
2021-01-22T02:33:26.806Z W Recalculating filtered room list
2021-01-22T02:33:26.808Z W Recalculating filtered room list
2021-01-22T02:33:26.810Z W Recalculating filtered room list
2021-01-22T02:33:26.811Z W Recalculating filtered room list
2021-01-22T02:33:26.813Z W Recalculating filtered room list
2021-01-22T02:33:26.815Z W Recalculating filtered room list
2021-01-22T02:33:26.816Z W Recalculating filtered room list
2021-01-22T02:33:26.818Z W Recalculating filtered room list
2021-01-22T02:33:26.819Z W Recalculating filtered room list
2021-01-22T02:33:26.821Z W Recalculating filtered room list
2021-01-22T02:33:26.831Z W Recalculating filtered room list
2021-01-22T02:33:26.832Z W Recalculating filtered room list
2021-01-22T02:33:26.835Z W Recalculating filtered room list
2021-01-22T02:33:26.835Z W Recalculating filtered room list
2021-01-22T02:33:26.836Z W Recalculating filtered room list
2021-01-22T02:33:26.837Z W Recalculating filtered room list
2021-01-22T02:33:26.838Z W Recalculating filtered room list
2021-01-22T02:33:26.839Z W Recalculating filtered room list
2021-01-22T02:33:26.839Z W Recalculating filtered room list
2021-01-22T02:33:27.070Z W Recalculating filtered room list
2021-01-22T02:33:27.072Z W Recalculating filtered room list
2021-01-22T02:33:27.074Z W Recalculating filtered room list
2021-01-22T02:33:27.075Z W Recalculating filtered room list
2021-01-22T02:33:27.077Z W Recalculating filtered room list
2021-01-22T02:33:27.078Z W Recalculating filtered room list
2021-01-22T02:33:27.080Z W Recalculating filtered room list
2021-01-22T02:33:27.081Z W Recalculating filtered room list
2021-01-22T02:33:27.083Z W Recalculating filtered room list
2021-01-22T02:33:27.085Z W Recalculating filtered room list
2021-01-22T02:33:27.086Z W Recalculating filtered room list
2021-01-22T02:33:27.088Z W Recalculating filtered room list
2021-01-22T02:33:27.090Z W Recalculating filtered room list
2021-01-22T02:33:27.091Z W Recalculating filtered room list
2021-01-22T02:33:27.093Z W Recalculating filtered room list
2021-01-22T02:33:27.095Z W Recalculating filtered room list
2021-01-22T02:33:27.096Z W Recalculating filtered room list
2021-01-22T02:33:27.098Z W Recalculating filtered room list
2021-01-22T02:33:27.099Z W Recalculating filtered room list
2021-01-22T02:33:27.445Z W Recalculating filtered room list
2021-01-22T02:33:27.447Z W Recalculating filtered room list
2021-01-22T02:33:27.449Z W Recalculating filtered room list
2021-01-22T02:33:27.450Z W Recalculating filtered room list
2021-01-22T02:33:27.452Z W Recalculating filtered room list
2021-01-22T02:33:27.454Z W Recalculating filtered room list
2021-01-22T02:33:27.456Z W Recalculating filtered room list
2021-01-22T02:33:27.458Z W Recalculating filtered room list
2021-01-22T02:33:27.459Z W Recalculating filtered room list
2021-01-22T02:33:27.461Z W Recalculating filtered room list
2021-01-22T02:33:27.463Z W Recalculating filtered room list
2021-01-22T02:33:27.467Z W Recalculating filtered room list
2021-01-22T02:33:27.469Z W Recalculating filtered room list
2021-01-22T02:33:27.470Z W Recalculating filtered room list
2021-01-22T02:33:27.472Z W Recalculating filtered room list
2021-01-22T02:33:27.474Z W Recalculating filtered room list
2021-01-22T02:33:27.475Z W Recalculating filtered room list
2021-01-22T02:33:27.476Z W Recalculating filtered room list
2021-01-22T02:33:27.477Z W Recalculating filtered room list
2021-01-22T02:33:27.487Z W Possible EventEmitter memory leak detected. 11 room_preview_changed listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 room_preview_changed listeners added. Use emitter.setMaxListeners() to increase limit
    at d (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:15136)
    at S.s.addListener (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:17418)
    at new L (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1539865)
    at bi (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1946463)
    at La (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1963913)
    at fs (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:2002277)
    at lc (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1993524)
    at sc (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1993449)
    at Zs (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1990479)
    at vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1942121
2021-01-22T02:33:27.488Z W Possible EventEmitter memory leak detected. 11 update listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 update listeners added. Use emitter.setMaxListeners() to increase limit
    at d (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:15136)
    at m.s.addListener (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:17418)
    at new L (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1540128)
    at bi (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1946463)
    at La (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1963913)
    at fs (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:2002277)
    at lc (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1993524)
    at sc (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1993449)
    at Zs (vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1990479)
    at vector://vector/webapp/bundles/504aa24e021ebeda5b73/vendors~init.js:2:1942121
2021-01-22T02:33:27.605Z I Looking at $xxx
```

which indeed don't look great. @turt2live I assume this isn't normal?
