### ISSUE TITLE
"Add existing room" to Space opens "Create a room" form

### ISSUE THREAD

**Issue by sim6** [vector-im/element-web#21048] opened 2022-02-11 14:32 UTC
### Steps to reproduce

1. Click a Space in left menu
2. Click plus icon near Space name

![20220211_15h21m59s_grim](https://user-images.githubusercontent.com/449834/153611001-84f31476-3db3-48fa-8bf6-9d050ef9b0b5.png)

#### What did you expect?

Open "Add existing rooms" form

![20220211_15h38m54s_grim](https://user-images.githubusercontent.com/449834/153612877-bbc19bda-6058-4367-bca9-aadf56b9a150.png)

#### What happened instead?

Opens "Create room" form

![20220211_15h38m20s_grim](https://user-images.githubusercontent.com/449834/153611822-dc0d28bc-4b92-4f7f-bbfa-3ec54ab8eda8.png)

### Operating system

Debian 11.2

### Application version

Element version: 1.10.1 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started#linux

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by robintown** [comment] 2022-02-11 15:30
Duplicate of https://github.com/vector-im/element-web/issues/20924, which has been fixed

**Closed by robintown** 2022-02-11 15:30 UTC
Labels: T-Defect

**Comment by sim6** [comment] 2022-02-11 16:52
Ops, I'm sorry, I only searched in open issues.
