### ISSUE TITLE
Avatar overlaps display name in membership events

### ISSUE THREAD

**Issue by ilmari** [vector-im/element-web#18279] opened 2021-07-28 15:08 UTC
#### Description

The first part of a membership event (join/leave/display name/avatar change) is hidden behind the user's avatar.

#### Steps to reproduce

- Change your display name or observe someone joining or leaving the room

![Screenshot from 2021-07-28 16-02-30](https://user-images.githubusercontent.com/72175/127346545-8bc74cd1-b83c-4413-bc84-8007957acfd7.png)

Logs being sent: no

#### Version information

- **Platform**: web
- **Browser**: Firefox 78.12.0esr 
- **OS**: Debian 10 (Buster)
- **URL**: staging.element.

**Comment by robintown** [comment] 2021-07-28 15:50
Duplicate of https://github.com/vector-im/element-web/issues/18264, which is fixed on develop

**Closed by robintown** 2021-07-28 15:50 UTC
Labels: A-Message-Bubbles, A-Timeline, T-Defect, X-Regression, X-Release-Blocker
