### ISSUE TITLE
Cannot close "New Login" dialog

### ISSUE THREAD

**Issue by libexus** [vector-im/element-web#17303] opened 2021-05-14 17:53 UTC
### Description

I logged in on app.element.io. After verifying from another session, the "new login" dialog on my Element Desktop couldn't be closed. Neither could I close it by clicking on *Later*, nor by clicking on *Check your devices*.

*Note:* The dialog disappeared after I reloaded Element in dev tools, but it's still reproducible.

### Steps to reproduce

- Log in into Element Desktop and another Element instance (i.e. develop.element.io)
- Now log in into app.element.io, wait for the new login and Device verification dialog to appear on Desktop.
- Verify the session using the **develop.element.io** instance
- The "Check your devices" dialog on Desktop cannot be closed anymore.

### Version information

- Element Web: app.element.io on Linux/Firefox 88
- Element Desktop: 1.7.27/Flathub

**Comment by kittykat** [comment] 2021-12-21 13:49
Duplicate of #17667

**Closed by kittykat** 2021-12-21 13:49 UTC
Labels: T-Defect, P2, S-Minor, A-E2EE-Cross-Signing, A-Toast
