### ISSUE TITLE
IRC Theme usability bugs

### ISSUE THREAD

**Issue by caminsha** [vector-im/element-web#17872] opened 2021-07-04 02:59 UTC
#### Description

When using IRC-Layout there are several things broken and not usable. So I've seen the following two issues:
1. The UI is not very useful if the names aren't unique. (for example with a telegram bridge). So the following issue exists: names are displayed on top of other names and messages, making them unreadable.

2. when hovering a message, it moves to the right to show the time as intended. But when you try hover over the reactions of a message, it moves to the right and back eratically, making it hard to hit the reaction.

#### Steps to reproduce
- first bug: get a message from a non unique user. It'll be broken and the username is somewhere inside the application
- second: send a message and someone should send a reaction. Try to hover the reaction to check who sent it. It's not very easy to see who sent a reaction. If you really get the correct position you'll see the username who responded. If not: The message will jump arount.

Log: sent/not sent?    Not sent. 

#### Version information

- **Platform**: web (in-browser) or desktop?  Desktop installed via Flatpak (Fedora 33)
Same exists in the web application. (see below)

For the web app:

- **Browser**: Chromium, Chromium 90.0.4430.212 Fedora Project
- **OS**: Fedora
- **URL**: private server, newest version

For the desktop app:

- **OS**: Fedora 33
- **Version**: Element version: 1.7.31
olm version: 3.2.3

**Comment by SimonBrandner** [comment] 2021-07-04 07:24
Duplicate of https://github.com/vector-im/element-web/issues/17778 which should be fixed on develop.element.io

**Closed by SimonBrandner** 2021-07-04 07:24 UTC
