### ISSUE TITLE
Element keeps losing session data

### ISSUE THREAD

**Issue by fridtjof** [vector-im/element-web#19556] opened 2021-10-30 14:48 UTC
### Steps to reproduce

I have Element installed on an Arch Linux partition that I'm not using too often recently (~once a month currently). Element is set up to automatically start in my KDE (X11) session. Often, after booting and logging in, it will be stuck on the loading spinner. Opening Devtools and reloading, or restarting the whole application helps sometimes, but not always.

Sometimes, however, it will come back with an error message indicating the session data is gone and I'll have to log out (which is where I created this issue from). This has been happening quite often over the last times I started my Linux session.

The error message indicates this might happen due to low disk space, but I don't think this is the case, as I have a solid ~300GB left on the relevant file system.

#### What did you expect?
Element starts normally

#### What happened instead?
Element's session data is gone, forcing me to log in again.

### Operating system

Arch Linux

### Application version

Element Desktop 1.9.3

### How did you install the app?

Through the arch package repositories

### Will you send logs?

Yes

**Comment by fridtjof** [comment] 2021-10-30 14:50
I was going to send logs, but that fails with with the message "No connected database". I can't download them either due to the same error.

**Comment by gsouquet** [comment] 2021-11-01 09:31
The error message "No connected database" indicates an issue at the storage level which could explain why the session data is lost.

Inspecting the console errors, or have a summary of the main process logs could help unveil the root of this issue

**Comment by novocaine** [comment] 2021-11-05 09:27
Similar to https://github.com/vector-im/element-web/issues/18625

@fridtjof are you by any chance using flatpak, or some similar containerisation of Element?

**Comment by novocaine** [comment] 2021-11-05 09:40
Let's mark this as a duplicate of https://github.com/vector-im/element-web/issues/18625 and continue the conversation there.

**Closed by novocaine** 2021-11-05 09:40 UTC
Labels: T-Defect, X-Needs-Info, Z-Platform-Specific, S-Critical, A-Electron, A-Storage, O-Uncommon
