### ISSUE TITLE
Be able to choose username's colour

### ISSUE THREAD

**Issue by LongJohn-Silver** [vector-im/element-web#17373] opened 2021-05-19 03:16 UTC
### Description

Right now when you create an account a random colour is assignated to you, so that when you send a message, this is displayed to you and others. It would be nice if you could choose this.

I dont think system information is relevant for this since it is not a bug and this works the same in all platforms.

**Comment by turt2live** [comment] 2021-05-19 03:25
Duplicate of https://github.com/vector-im/element-web/issues/11816

**Closed by turt2live** 2021-05-19 03:25 UTC
