### ISSUE TITLE
Room previews as a guest are broken for some rooms

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15377] opened 2020-10-05 15:34 UTC
CC: @Cadair 

Reproduction steps:
- Use a fresh browser session / do not be logged in.
- Go to https://app.element.io/#/room/#matrix:matrix.org
  - Notice it previews successfully
- Go to https://app.element.io/#/room/#sunpy:openastronomy.org
  - Notice how the preview spinner spins forever

Both rooms appear to initialSync correctly, so I'm fairly certain that Element is getting the required data to show a preview and it's blowing up somewhere in the stack.

Some logs:

```
 error-codes.js:44:4
Stopped peeking in room !OGEhHVWSdvArJzumhm:matrix.org error-codes.js:44:4
Uncaught (in promise) TypeError: e is null
    loadRoomWidgets strings.ts:40
    p GroupAddressPicker.js:78
    emit events.js:157
    _handleEvent scheduler.js:204
    n scheduler.js:211
    emit events.js:152
    setStateEvents room-state.js:131
    d utils.ts:138
    setStateEvents room-state.js:763
    peek sync.js:132
    promise callback*m.prototype.peek sync.js:109
    peekInRoom client.js:3825
    setupRoom RoomView.tsx:1095
    X ReplaceTransition.js:38
    UNSAFE_componentWillMount RoomView.tsx:206
    React 7
    unstable_runWithPriority scheduler.production.min.js:13
    React 6
    viewRoom MatrixChat.tsx:437
    promise callback*viewRoom MatrixChat.tsx:413
    ge MatrixChat.tsx:234
    _invokeCallback setImmediate.js:126
    dispatch setImmediate.js:87
    setTimeout handler*dispatch MatrixClientPeg.ts:185
    viewRoom RoomViewStore.tsx:81
    __onDispatch Analytics.js:296
    __invokeOnDispatch FluxStoreGroup.js:15
    _dispatchToken StyledMenuItemRadio.tsx:31
    _invokeCallback setImmediate.js:126
    dispatch setImmediate.js:87
    setTimeout handler*dispatch MatrixClientPeg.ts:185
    showScreen MatrixChat.tsx:1542
    b app.tsx:61
    b app.tsx:69
    U app.tsx:146
    ne init.tsx:149
    27 index.ts:200
```

(I couldn't attach debug logs, as the debug logger depends on a working database)

**Comment by turt2live** [comment] 2020-10-05 15:36
Duplicate of https://github.com/vector-im/element-web/issues/8933

**Closed by turt2live** 2020-10-05 15:36 UTC

**Comment by Cadair** [comment] 2020-10-05 15:38
Disagree this is a dupe

**Comment by Half-Shot** [comment] 2020-10-05 15:39
I'm not sure this is the same. @ara4n describes widgets being unusable in rooms as a guest, whereas this is room previews being broken in a room before the user has even joined.

Also, the room doesn't have any widgets in it according to @Cadair, so let's not close issues in a rush :)

**Comment by turt2live** [comment] 2020-10-05 15:40
Please submit logs and get a stacktrace from a develop client then - we've fixed a few bugs in the area, and one of them is probably related.

**Comment by turt2live** [comment] 2020-10-05 15:41
(this was closed because the stacktrace provided uses widgets, and as far as the client and server are concerned you are a guest when you are previewing)

**Comment by Half-Shot** [comment] 2020-10-05 15:43
Hmm, logs weren't terribly enlightening.

**Comment by turt2live** [comment] 2020-10-05 15:44
The logs were also not from a develop client.

**Comment by Half-Shot** [comment] 2020-10-05 15:46
I don't think that helped you much.

**Comment by Cadair** [comment] 2020-10-05 15:48
Also it should be noted there are no active widgets in that room, just the remnants of them in room state.

**Comment by Cadair** [comment] 2020-10-05 15:50
> (this was closed because the stacktrace provided uses widgets, and as far as the client and server are concerned you are a guest when you are previewing)

I get this but previewing rooms used to work when there were widgets in there, even if you couldn't interact with the widgets themselves.

**Comment by turt2live** [comment] 2020-10-05 15:50
The logs not working is #15379. As for this issue, duplicate of https://github.com/vector-im/element-web/issues/15349

**Comment by Cadair** [comment] 2020-10-05 15:51
Thanks for the triage @turt2live :smile:
