### ISSUE TITLE
Enabled spaces, got an infinite spinner

### ISSUE THREAD

**Issue by afranke** [vector-im/element-web#18337] opened 2021-08-02 12:32 UTC
I went to the settings, experimental section, and enabled Spaces. The page reloaded and now it’s stuck on a spinner that never ends.

![image](https://user-images.githubusercontent.com/117241/127861811-0d7f9a2f-3494-4c22-9088-04ba6f8742de.png)

Closing the window and opening a new one doesn’t change anything. The only error I can see in the browser console is a 404 for https://app.element.io/config.app.element.io.json?cachebuster=somenumber

Logs being sent: no (I don’t see what logs I could possibly send)

#### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 90.0.2
- **OS**: Fedora 34
- **URL**: app.element.io

**Comment by afranke** [comment] 2021-08-02 12:35
I should mention that I also tried reloading with cache disabled (from the network tab of the developer tools) and it doesn’t change anything.

**Comment by t3chguy** [comment] 2021-08-02 12:40
Unrelated to Spaces, this is a Firefox IDB wedge

**Comment by t3chguy** [comment] 2021-08-02 12:46
Duplicate of https://github.com/vector-im/element-web/issues/17891

**Closed by t3chguy** 2021-08-02 12:46 UTC
Labels: T-Defect, Z-Platform-Specific
