### ISSUE TITLE
Add a noise gate to audio settings

### ISSUE THREAD

**Issue by SethFalco** [vector-im/element-web#17507] opened 2021-05-31 21:13 UTC
#### Is your suggestion related to a problem? Please describe.
When using Element currently it sends all sounds, including sighs, typing, or other quiet background sounds which aren't intended for the recipient. This can be a bit annoying for users.

#### Describe the solution you'd like.
Can a "[noise gate](https://en.wikipedia.org/wiki/Noise_gate)" be added in the Video/audio settings so users can configure the minimum decibels sound should be before Element will send this to other members of the call?

A noise gate may also be known as "input sensitivity" or "input threshold".

**Comment by SimonBrandner** [comment] 2021-06-01 05:30
Duplicate of [#15534](https://github.com/vector-im/element-web/issues/15534)

**Closed by SimonBrandner** 2021-06-01 05:30 UTC
Labels: T-Enhancement
