### ISSUE TITLE
Show icon for rooms with a draft

### ISSUE THREAD

**Issue by totpet** [vector-im/element-web#15096] opened 2020-09-04 12:27 UTC
**Is your suggestion related to a problem? Please describe.**
I often start writing a message in a room/to a person, then I go to a different thread and forget about it. 

**Describe the solution you'd like**
I think it would be useful if Element displayed an icon next to rooms with a started draft in the sidebar/room list, similarly to Slack.

**Describe alternatives you've considered**
¯\\\_(ツ)\_/¯

Maybe a separate view or section in the sidebar that lists the user's drafts.

**Additional context**
Slack UI as an example (see the two pencil icons on the right):
![image](https://user-images.githubusercontent.com/13013768/92238644-f2515b80-eeb9-11ea-8984-f4d9a9c21f8d.png)

**Comment by t3chguy** [comment] 2020-09-04 12:30
Related https://github.com/vector-im/element-web/issues/14182

**Comment by turt2live** [comment] 2020-09-04 15:59
Duplicate of https://github.com/vector-im/element-web/issues/14182 in fact

**Closed by turt2live** 2020-09-04 15:59 UTC
Labels: suggestion, type:new-room-list
