### ISSUE TITLE
avoid layout when thumbnails load

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#9016] opened 2019-03-01 13:42 UTC
set the thumbnail dimensions from the event on the <img> before the image loads in MImageBody, so they don't resize when the image is loaded.

**Comment by bwindels** [comment] 2019-03-01 13:48
#8565 should have already improved this for Chrome, but as this is probably the biggest cause for scroll jumping, seems like a no-brainer to do this for other browsers as well.

**Comment by MadLittleMods** [comment] 2023-05-01 17:55
Related to https://github.com/vector-im/element-web/issues/9670

**Comment by t3chguy** [comment] 2023-05-05 08:19
Duplicate of #9670

**Closed by t3chguy** 2023-05-05 08:19 UTC
Labels: T-Defect, P1, S-Minor, A-Timeline, A-Media, A-Timeline-Jumpy-Scroll
