### ISSUE TITLE
Play sound if a message is received in currently active conversation

### ISSUE THREAD

**Issue by vojtapolasek** [vector-im/element-web#24673] opened 2023-02-26 16:21 UTC
#### What would you like to do?
          
          I would like the Element app to play some mild sound when a new message is received into the currently opened conversation.
          
          #### Why would you like to do it?
          
          I am blind and therefore I can't detect if I have received a new message into currently active conversation. therefore, I have to constantly check the latest message if it did not change... what is not that convenient.
          
          #### How would you like to achieve it?
          By adding a feature which will allow to enable possibility o play sound if a new message is received into currently focused conversation. Possibility to choose custom sound would be nice.

### Have you considered any alternatives?

hm... not sure if there is any alternative solution.

**Comment by t3chguy** [comment] 2023-02-26 17:57
Duplicate of https://github.com/vector-im/element-meta/discussions/1065

**Closed** 2023-02-26 17:57 UTC
Labels: T-Enhancement
