### ISSUE TITLE
Audio messages are scanned after selecting chat window and slowing down the app

### ISSUE THREAD

**Issue by KPKoch** [vector-im/element-web#19756] opened 2021-11-15 10:10 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

If select a contact with many audio messages in the chat. Sadly this happens everytime you switch to the chat.

#### What did you expect?
I expect normal performance. So the wave forms may be analyzed ONE time. And as I really don't care how the audio wave looks like, a toogle to switch this scan of would be great!

#### What happened instead?
The audio messages are scanned, so the waveform can be displayed(?). This decreases performance on my u8550 so the app is unusable for a little while. Scrolling an with the the loading of new audio messages increases this problem and leads to stuttering scrolling or short stalling of the app, e.g. switching to another contact is delayed..

### Browser information

latest chromium , firefox, doesn't matter

### URL for webapp

Element 1.9.4

### Application version

Element 1.9.4

### Will you send logs?

No

**Comment by Friskygote** [comment] 2022-02-01 17:27
This issue has impacted my experience in using Element many times now. When multiple audio messages are sent (usually not even voice messages but music files), [generating waveforms](https://github.com/matrix-org/matrix-react-sdk/blob/82f3888cee298118d60a490a3e1e50e19939fd5b/src/audio/Playback.ts#L39) and [its parent function](https://github.com/matrix-org/matrix-react-sdk/blob/82f3888cee298118d60a490a3e1e50e19939fd5b/src/audio/Playback.ts#L135) often take 1-3 seconds per file according to profiler. This often completely halts usage of the application for quite some time (depending on amount of files to process (and their size?), sometimes even up to a minute when someone shares multiple such files). 

I feel like some kind of fallback audio object should be used while waveforms are generated (if possible in the background without killing the UI?) or at least some kind of method to completely stop the process of generating those if performance impact is possible. Perhaps even worth another issue of its own. 

Issue should be easily reproducible by sending multiple audio files with size 4MB+ in a channel.

**Comment by juanfra684** [comment] 2022-04-19 20:25
I've an encrypted room with a few tens of podcasts and I can't open that room with Element because it always crashes. The only matrix client which works as expected for that room is Nheko.

Please, add an option to disable the auto-download and processing of the audio files.

**Comment by masterflitzer** [comment] 2022-08-14 23:07
> without killing the UI

yes imo blocking the UI is a no go, this should be done in the background (also performance is much more important than these waveforms, whatsapp e.g. has a much smaller waveform which i don't mind but there is never a UI lag even when audio is loading)

also for me it just loads the currently visible audio messages, so when i scroll a bit up it hangs again and again when i try to scroll a bit (if you have a chat with audio messages regularly)

i'd appreciate if waveforms would be disabled until someone found a fix, then they could be brought back

**Comment by masterflitzer** [comment] 2022-08-14 23:10
i think mentioning high cpu in the title of this issue and closing the duplicate would make sense

**Comment by t3chguy** [comment] 2022-08-15 14:15
high cpu vs slowing down depends on very many factors

**Comment by masterflitzer** [comment] 2022-08-15 16:40
yes but it's important keyword which helps to locate this issue, the now closed duplicate was probably only created because searching for high cpu didn't return any results

**Comment by t3chguy** [comment] 2022-08-15 16:43
github keywords can exist in the comments too, not just the title

![image](https://user-images.githubusercontent.com/2403652/184678021-5c8c12f8-f4b5-4d1a-86bb-e1f3426e89b6.png)

**Comment by masterflitzer** [comment] 2022-08-15 16:46
yes you're right github is smart

**Comment by eTomte** [comment] 2023-01-13 20:10
I'd say that this issue has been going on since almost the beginning of the voice messages feature.  It doesn't even take very many messages in the chat before things start to slow down noticeably.

**Comment by Utesgui** [comment] 2023-02-13 21:02
This Issue is becoming one of the most frustrating things to me. I have multiple people who love to send voicemessages (don't ask me why) and i am now on the point where i can't switch between chats for 20 Seconds or so because the client is processing. I would highly appreciate if there would be some kind of fix for that some time in the future. Or maybe simply an option to disable the waveform generation in general? waveforms are surely nice to have, but if i need to decide between usabillity and waveforms, i would choose usability. This is really bothering me. Thanks to all contributors who make element a great messanger!

**Comment by a-mnich** [comment] 2023-02-19 19:17
I agree with the previous speaker.
Based on my experience, many people send voice messages because they don't have time to type a message at this exact moment. Having to wait until a chat is usable is not helpful in that case.
For me, this bug also makes some of my chats almost completely unusable.  
However, good usability is important to ensure the everyday practicality of Element and also to be able to convince other people of it.  
A solution would be very welcome. Thanks for your engagement.

**Closed** 2023-04-27 10:02 UTC
Labels: T-Defect, A-Performance, S-Major, A-Timeline, Z-t3chguy, A-Voice-Messages, O-Occasional
