### ISSUE TITLE
Clicking permalink to message in thread does not allow opening of other threads

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#26146] opened 2023-09-08 14:15 UTC
### Steps to reproduce

1. Click a permalink to a message that was posted in another room for a threaded message
2. From the main timeline, try to open any other thread
3. Observe thread panel briefly switch before snapping back to the permalinked message

#### What did you expect?

The thread panel to work.

#### What happened instead?

See observation.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023090701 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-09-11 06:10
Duplicate of #24850

**Closed** 2023-09-11 06:10 UTC
Labels: T-Defect, S-Major, O-Occasional, A-Threads
