### ISSUE TITLE
Clicking on the invite button has no effect despite being an admin in the room

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#14865] opened 2020-08-03 16:22 UTC
```
2020-08-03T15:02:32.619Z E The above error occurred in the <InviteDialog> component:
    in InviteDialog (created by AsyncWrapper)
    in AsyncWrapper
    in div
    in div

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
2020-08-03T15:02:32.619Z W AsyncWrapper promise failed dmTaggedRooms is not iterable
TypeError: dmTaggedRooms is not iterable
    at InviteDialog._buildRecents (webpack-internal:///585:824:26)
    at new InviteDialog (webpack-internal:///585:795:21)
    at constructClassInstance (webpack-internal:///42:12880:18)
    at updateClassComponent (webpack-internal:///42:17100:5)
    at beginWork (webpack-internal:///42:18620:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///42:188:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///42:237:16)
    at invokeGuardedCallback (webpack-internal:///42:292:31)
    at beginWork$1 (webpack-internal:///42:23203:7)
    at performUnitOfWork (webpack-internal:///42:22157:12)
```

**Comment by turt2live** [comment] 2020-08-03 16:38
Duplicate of https://github.com/vector-im/element-web/issues/14743 ?

**Closed** 2020-08-04 08:33 UTC
Labels: bug, release-blocker, type:invite
