### ISSUE TITLE
Graphical glitch with specific pattern

### ISSUE THREAD

**Issue by quentin9696** [vector-im/element-web#25592] opened 2023-06-13 14:46 UTC
### Steps to reproduce

1. Write a message that respect this regex: `^[0-9]{2,}0\.$`
2. The first part of the message is displayed like this: 
![image](https://github.com/vector-im/element-web/assets/14543538/e3c71fb6-a33c-425a-8243-30c8f205bb07)
When I check the raw message, I can see this: 
``` json
{
  "room_id": "REDACTED",
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "3500.",
    "format": "org.matrix.custom.html",
    "formatted_body": "<ol start=\"3500\">\n<li></li>\n</ol>\n"
  }
}
```

#### What did you expect?

The message should be correctly displayed

#### What happened instead?

The first part of the message is displayed like this: 
![image](https://github.com/vector-im/element-web/assets/14543538/e3c71fb6-a33c-425a-8243-30c8f205bb07)

### Operating system

I tryied on Element Web, Element desktop on Linux and Element on Android

### Browser information

Firefox 114.0

### URL for webapp

app.element.io

### Application version

Element version: 1.11.32 Olm version: 3.2.14

### Homeserver

element

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-06-14 08:18
Duplicate of https://github.com/vector-im/element-web/issues/14621

**Closed by t3chguy** 2023-06-14 08:18 UTC
Labels: T-Defect
