### ISSUE TITLE
Improve theming documentation

### ISSUE THREAD

**Issue by SuperDuperDeou** [vector-im/element-web#23523] opened 2022-10-18 15:06 UTC
#### What would you like to do?

Change the colors of scrollbar and text bubbles.

#### Why would you like to do it?

To have a consistent theme across all the programs I use.

#### How would you like to achieve it?

With the config.json file, the problem is that even if I change all the colors settings that are documented some colors, such as the scroll bar, the text bubbles, the background color of the messages you're hovering on, or the color of the text inside a post that mentions you, to their defaults. This means that either those colors are completely undocumented or are not yet configurable.

### Have you considered any alternatives?

Hunting for 3rd party documentation is an option that exist, reading the source code is an option that exists, but that's something that should absolutely be in the official user documentation.

**Comment by t3chguy** [comment] 2023-07-13 11:51
Duplicate of https://github.com/vector-im/element-web/issues/20342

**Closed by t3chguy** 2023-07-13 11:51 UTC
Labels: S-Minor, A-Documentation, T-Enhancement, A-Themes-Custom, Z-Labs
