### ISSUE TITLE
Option to not show acticity asterisk in title bare for low-priority channels

### ISSUE THREAD

**Issue by ThiefMaster** [vector-im/element-web#24585] opened 2023-02-20 11:27 UTC
### Your use case

I'm in a bunch of channels which I check very rarely and thus they are in my "low priority" list. However, having unread messages in those channels also triggers the asterisk in the Element title bar.

I'd like to have an option to configure whether a channel / category should contribute to showing this indicator, or as a simpler alternative simply exclude the "low priority" from it.

In fact I only noticed this recently, so maybe it changed recently? Not sure...

**Comment by t3chguy** [comment] 2023-02-20 11:28
Duplicate of https://github.com/vector-im/element-web/issues/24554

**Closed by t3chguy** 2023-02-20 11:28 UTC
Labels: T-Enhancement
