### ISSUE TITLE
what da padding doin

### ISSUE THREAD

**Issue by nabijaczleweli** [vector-im/element-web#26280] opened 2023-10-02 22:15 UTC
### Steps to reproduce

1. have typing notifications on
2. open a room
3. have someone be typing

#### What did you expect?
the typing notification should happen and then go away

#### What happened instead?
![image](https://github.com/vector-im/element-web/assets/6709544/17031061-0989-4d26-bd2a-a6e337aa6542)

### Operating system

Windows

### Application version

Element version: 1.11.45 Olm version: 3.2.14

### How did you install the app?

clicked enter on "Element Setup.exe"

### Homeserver

nabijaczleweli.xyz Synapse 1.93.0-1

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-10-02 22:17
Duplicate of https://github.com/vector-im/element-web/issues/8552

**Closed by t3chguy** 2023-10-02 22:17 UTC
Labels: T-Defect
