### ISSUE TITLE
Unread room status not going away

### ISSUE THREAD

**Issue by murlock1000** [vector-im/element-web#25005] opened 2023-03-31 11:09 UTC
### Steps to reproduce

1. Room has unread notification on desktop device
2. Opening room, restarting app does not make the notification go away
3. Sending a message to the room clears the notification due to https://github.com/matrix-org/matrix-js-sdk/pull/3139
4. The unread notification does not appear in other devices, just one.

![image](https://user-images.githubusercontent.com/25286623/229104293-a50293e5-7c42-46f4-8a9d-dd7459457394.png)

#### What did you expect?
The unread room notification to go away when the room is opened.
#### What happened instead?
The unread room notification persists, until I write a new message.

### Operating system

Windows

### Application version

1.11.25

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-03-31 11:11
Duplicate of https://github.com/vector-im/element-web/issues/24595

**Closed by t3chguy** 2023-03-31 11:11 UTC
Labels: T-Defect
