### ISSUE TITLE
Notifications about display name change or room joins/leaves despite room is set to "mentions & keywords"

### ISSUE THREAD

**Issue by aWeinzierl** [vector-im/element-web#26187] opened 2023-09-18 09:39 UTC
### Steps to reproduce

1. Have Element Desktop running, be in a room that has been set to "mentions & keywords"
2. Enable Beta for notifications (not sure if required, but I did that).  `All messages` is selected in the notification settings, and I checked everything except email notifications in the notifications screen.
3. Someone leaves the room, joins the room or changes their display name

#### What did you expect?

No notifications for rooms that have been set , because the notifications for the room are set keyword and mentions only. The display name change doesn't mention me and I haven't added a keyword to the keyword list.

#### What happened instead?
A notification was shown for every(!) room I shared with the user that changed their name.
A notification was shown for the room leave/join despite the room being mentions & keywords

### Operating system

Windows 11 Pro

### Application version

Element version: 1.11.43 Olm version: 3.2.14

### How did you install the app?

https://element.io/download respectively through the update mechanism

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-09-18 10:04
> Enable Beta for notifications (not sure if required, but I did that)

It is indeed the cause.

https://github.com/matrix-org/matrix-react-sdk/pull/11247 is the fix

**Comment by austinbutler** [comment] 2023-10-06 22:30
Looks like a duplicate of https://github.com/vector-im/element-web/issues/25911.

**Comment by t3chguy** [comment] 2023-10-11 16:20
Duplicate of https://github.com/vector-im/element-web/issues/25911

**Closed by t3chguy** 2023-10-11 16:20 UTC
Labels: T-Defect
