### ISSUE TITLE
Thread list doesn't update with new/changed threads

### ISSUE THREAD

**Issue by justjanne** [vector-im/element-web#24341] opened 2023-01-26 10:32 UTC
See https://github.com/matrix-org/element-web-rageshakes/issues/19476

**Comment by weeman1337** [comment] 2023-01-26 10:51
@justjanne could this be a duplicate of #24334 ?

**Comment by weeman1337** [comment] 2023-01-26 10:52
Rageshake says that the reporter is using version `1.11.1` . I am going to close this one…

**Closed by weeman1337** 2023-01-26 10:52 UTC
Labels: T-Defect, S-Major, O-Uncommon, A-Threads
