### ISSUE TITLE
Unable to seek/skip ahead consistently in media

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#15859] opened 2020-11-30 12:54 UTC
### Description

When an audio (or video) event is in the timeline, it's presented as the generic browser player. I've noticed that with Element Desktop (Electron/Chrome), I'm not able to consistently seek backwards and forwards, regardless of the audio or video encoding.

Recording of the behaviour: https://matrix.amorgan.xyz/_matrix/media/r0/download/amorgan.xyz/38751505a99e0a58269274034e0fa84b850327ea

I'll note that Discord's app (which this room is bridged to, and also uses Electron) has no problem seeking within these files.

### Steps to reproduce

- Upload an audio/video file
- Play the file
- Try to seek in the file

Log: yes

### Version information

- **Platform**: desktop
- **OS**: Debian Linux
- **Version**: 1.7.13

**Comment by t3chguy** [comment] 2020-11-30 12:58
Duplicate of https://github.com/vector-im/element-web/issues/4265
Looks like its https://github.com/matrix-org/synapse/issues/4780

**Closed by t3chguy** 2020-11-30 12:58 UTC

**Comment by anoadragon453** [comment] 2020-11-30 14:56
@t3chguy thanks for the background! In my specific case I'm using matrix-media-repo, which also lacks the same feature: https://github.com/turt2live/matrix-media-repo/issues/73
