### ISSUE TITLE
New room doesn't get added to the breadcrumbs when it's created

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#21145] opened 2022-02-21 16:57 UTC
### Steps to reproduce

1. In the left panel, click + next to the People section
2. In the "Direct Messages" dialog, add two users to start a three way DM
3. "Go" to start the DM

#### What did you expect?
See the new room as the most recently visited room in the breadcrumbs

#### What happened instead?
Room isn't added to the breadcrumbs

### Browser information

Chromium 98.0.4758.80 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

lement version: a01684e-react-e2827b40825c-js-a89c1990d6f2 Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-02-21 17:04
Duplicate of https://github.com/vector-im/element-web/issues/16400

**Closed by t3chguy** 2022-02-21 17:04 UTC
Labels: T-Defect, A-Breadcrumbs, Z-Papercuts
