### ISSUE TITLE
Random message from last year from old account

### ISSUE THREAD

**Issue by haecker-felix** [vector-im/element-web#21024] opened 2022-02-10 14:05 UTC
### Steps to reproduce

Absolutely no idea how to reproduce this. This came absolutely random.

#### What did you expect?

Nothing.

#### What happened instead?

![image](https://user-images.githubusercontent.com/6001248/153422606-d4549805-1d34-4e57-b0ba-e1a2120eae4e.png)

A random "yes" message from my old account from last year. (The green "F" is the old `haecker-felix@gnome.org` account, the new one is `felix@haecker.io`

Thib doesn't see the random message. It's just me. 

### Operating system

Fedora 35

### Browser information

Firefox 97.0 (64-Bit)

### URL for webapp

https://app.element.io/

### Application version

Element: 1.10.1, Olm: 3.2.8

### Homeserver

matrix.haecker.io (Synapse 1.52.0)

### Will you send logs?

Yes

**Comment by haecker-felix** [comment] 2022-02-10 14:11
![image](https://user-images.githubusercontent.com/6001248/153424826-76fa5c90-1dcf-43af-9bc1-0d1e3c32d1c4.jpeg)

**Comment by thibaultamartin** [comment] 2022-02-10 14:17
I rageshook too, as the other side of it (title: "The other side of #21024")

**Comment by t3chguy** [comment] 2022-02-10 14:18
Duplicate of https://github.com/vector-im/element-web/issues/1456

**Closed by t3chguy** 2022-02-10 14:18 UTC
Labels: T-Defect, Z-Synapse

**Comment by haecker-felix** [comment] 2022-02-10 14:23
> This will be Synapse sending it down /sync - this sometimes happens when an old server comes back to life.

Not sure what do you mean with that. There's no "old" server which could come back to life. The gnome.modular.im server is still active (wasn't dead / came back to life).

**Comment by t3chguy** [comment] 2022-02-10 14:26
That's one of the causes of this symptom, but definitely not the only. Fundamentally Element will show whatever it is told to via /sync or /messages APIs by your server.
