### ISSUE TITLE
Fenced code block renders incorrectly

### ISSUE THREAD

**Issue by rootkea** [vector-im/element-web#18391] opened 2021-08-04 18:06 UTC
Hello!

This is the markup text I entered in Element:
~~~
```
include <bits/stdc++.h>
using namespace std;

void bubbleSort(int arr[], int n)
{
	int i, j;
	for (i = 0; i < n-1; i++)
	for (j = 0; j < n-i-1; j++)
		if (arr[j] > arr[j+1])
			swap(&arr[j], &arr[j+1]);
}
```
~~~

And this is the o/p I get:
![Screenshot_2021-08-04_23-33-42](https://user-images.githubusercontent.com/2694559/128231734-dc000222-03bc-48f6-a9d0-4347d4650ddd.png)

I expected the o/p to have same indentation as that of above markup text with syntax highlighting.

#### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 90.0 (64-bit)
- **OS**: Ubuntu 20.04.2 LTS
- **URL**: app.element.io

**Comment by robintown** [comment] 2021-08-04 18:08
Duplicate of https://github.com/vector-im/element-web/issues/18365

**Closed by robintown** 2021-08-04 18:08 UTC
Labels: T-Defect
