### ISSUE TITLE
Several different error messages: OLM.BAD_MESSAGE_MAC ; Duplicate message index, possible replay attack ; Mismatched room_id for inbound group session

### ISSUE THREAD

**Issue by lvoss99** [vector-im/element-web#15637] opened 2020-11-02 20:00 UTC
Dear community,

this is my first post, so please forgive me if I don't use every convention correctly.
I am using the element messenger and it is only one specific group chat that I receive several different errors in about why I can't read the sent messages. Surprisingly this just occurs for a couple of participants, it works fine for the others. 
These error messages are the ones I mean:

* Unable to decrypt: Error: OLM.BAD_MESSAGE_MAC *

* Unable to decrypt: Error: Duplicate message index, possible replay attack: vT4f4OJSyZmjlObOmIE/CsZRY+saT4RGKhxEXA8oeSw|O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik|0 *

* Unable to decrypt: Error: Mismatched room_id for inbound group session (expected !XdAQbEbtBibsXlkixO:digipeg.de, was !hyzVdkvmOKXVoNHWLm:digipeg.de) *

I have already rebooted the server what seemed to have fixed at least the second error for a couple of days. But then it reoccured now on a daily basis. The errors occur on group participants that are using the firefox browser version of the element messenger.
I have also already updated synapse to version 1.22.0

Have you any recommendations what to do about these issues?
I would really appreciate your help, thanks.

L

**Comment by turt2live** [comment] 2020-11-02 20:06
Duplicate of https://github.com/vector-im/element-web/issues/15630

Internally we also briefly talked about this and think it's a duplicate of https://github.com/vector-im/element-web/issues/2996 generally as well.

From both sides please go to Settings -> Help -> Submit debug logs and send them our way.

If you need further help or support, please use http://matrix.to/#/#element-web:matrix.org

**Closed by turt2live** 2020-11-02 20:06 UTC
Labels: bug
