### ISSUE TITLE
Convert `src/errors` to TS

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19273] opened 2021-10-04 15:10 UTC
https://github.com/matrix-org/matrix-js-sdk/blob/c3308e1de95273a2e9baab4482176944a4138b2c/src/errors.js

**Comment by t3chguy** [comment] 2021-10-05 08:34
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/1893

**Closed by t3chguy** 2021-10-05 08:34 UTC
Labels: T-Task, A-Developer-Experience
