### ISSUE TITLE
Don't search domains for keyword

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#20518] opened 2022-01-12 18:53 UTC
### Your use case

I made the big mistake and my matrix server is contains my nickname jokergermany.XXX

#### What would you like to do?
Now i get a notification because "i got mentioned" when some of the ghost user on my matrix Server a mentioned.
It would be great if this could be stopped.

#### Why would you like to do it?
To get no notification when puppets are mentioned.

#### How would you like to achieve it?
When searching for keywords, ignore domain names.

### Have you considered any alternatives?

Yes, Anti-Keywords #20519

**Comment by t3chguy** [comment] 2022-01-13 00:33
Push rules are defined by the spec and evaluated by all clients and servers, I suggest opening this on the matrix-doc repo

**Comment by t3chguy** [comment] 2022-09-08 11:45
Duplicate of https://github.com/vector-im/element-web/issues/1007

**Closed by t3chguy** 2022-09-08 11:45 UTC
Labels: A-Notifications, Z-Synapse, T-Enhancement, X-Spec-Changes, O-Uncommon
