### ISSUE TITLE
Marking a channel as read doesn't work.

### ISSUE THREAD

**Issue by jrmuizel** [vector-im/element-web#26617] opened 2023-11-21 15:20 UTC
### Steps to reproduce

I channel I'm part of has a bunch of unread messages
- Clicking on the go back to unread messages button gives "Failed to load timeline position".
- Right clicking on the channel name and selecting "Mark as Read" will reset the count to 0, however it immediately starts counting up again.

#### What did you expect?
It should be possible to read any unread messages and once read they should stay read.

#### What happened instead?
The message read count stays above 0

### Operating system

macOS

### Application version

Version 1.11.50 (1.11.50)

### Homeserver

mozilla.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-11-21 15:22
Duplicate of https://github.com/vector-im/element-web/issues/24392

**Closed by t3chguy** 2023-11-21 15:22 UTC
Labels: T-Defect
