### ISSUE TITLE
Code block copy action does nothing on Element Desktop nightly if <code> missing

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#16445] opened 2021-02-13 12:36 UTC
### Description

Not sure when this has broken, but my recent element desktop nightly code blocks copy action doesn't seem to do anything. No errors in logs. On the web develop, there is the "Copied!" message and the text is copied to the clipboard. This does not happen any more on my nightly.

~~Edit: the issue is with `m.notice` messages.~~
Edit: the issue is that copy only works with `<pre><code>` not with `<pre>`

### Version information

- **Platform**: desktop
- **OS**: Ubuntu 20.04
- **Version**: 2021021101

**Comment by jaywink** [comment] 2021-02-13 12:46
Looks like it works for some code blocks but not for all :thinking:  

Have put a link to the message which does not work in the rageshake. Please ask for invite to room.

**Comment by SimonBrandner** [comment] 2021-02-13 12:54
Hmm, I am wondering if this is caused by one of my PRs ([#5559](https://github.com/matrix-org/matrix-react-sdk/pull/5559), [#5633](https://github.com/matrix-org/matrix-react-sdk/pull/5633))

I am unable to duplicate this. I'll take a closer look into this later

**Comment by SimonBrandner** [comment] 2021-02-13 13:40
@jaywink, I still can't reproduce this. Is there any chance you can see anything like this in the console?

![Screenshot_20210213_143659](https://user-images.githubusercontent.com/25768714/107851264-f094a800-6e08-11eb-8c61-fe8df973b71b.png)

If so, it looks like there is some problem with finding the element to copy.

Do the messages have something in common? Were they edited? There were some problems with that but I believe it should be fixed now. 

Sorry for the trouble

**Comment by SimonBrandner** [comment] 2021-02-13 14:40
> On the web develop, there is the "Copied!" message and the text is copied to the clipboard. This does not happen any more on my nightly.

I didn't notice this part before. Is this the same message? If this works on the web develop, I actually doubt this is a regressed by my PR.

**Comment by jryans** [comment] 2021-02-19 14:14
@jaywink If you can reply above to @SimonBrandner, that would be great. I'd like to know whether this is a regression before the RC next week.

**Comment by jaywink** [comment] 2021-02-22 11:09
Sorry, was distracted and forgot to update this.

I managed to now find the reason the copy doesn't work: the messages are of `m.notice` type. For the same content, using `m.text`, things work just fine.

**Comment by SimonBrandner** [comment] 2021-02-22 11:54
![Screenshot_20210222_124852](https://user-images.githubusercontent.com/25768714/108704460-56211c80-750c-11eb-8942-fa673f26bcaa.png)

```
{
    "msgtype": "m.notice",
    "format": "org.matrix.custom.html",
    "formatted_body": "<pre><code>Hello wrold\n</code></pre>\n"
}
```

@jaywink, this seems to work for me. Am I missing something? Could you share the event source? 

Is there any chance the `<code>` is missing? If so I can reproduce this

**Comment by jaywink** [comment] 2021-02-22 12:04
Ha, that's it, you're absolutely right. With `code` it works, both as `m.notice` and `m.text` :v: 

Either we shouldn't be showing the copy action if there is no `code` or the copy action should work with just `pre`, I suppose.

**Comment by SimonBrandner** [comment] 2021-02-22 12:06
@jaywink, I'll look into fixing/changing this so this doesn't happen.

@jryans, since this is caused by the event's source, I don't think this is a release-blocker but I think I can put something together anyway

**Comment by jryans** [comment] 2021-02-24 11:08
This does not appear to be a regression as far as I can tell... It seems like we have so far required the `code` element. We can work out how to fix that of course, but it's a lower priority improvement I'd say.

**Comment by SimonBrandner** [comment] 2021-02-24 11:12
@jryans, this _is_ a regression, we used to copy the content of the `<pre>`  element. [Here](https://github.com/SimonBrandner/matrix-react-sdk/blob/e90009772d0c2955e8caeecb1fc4f81d83b61afa/src/components/views/messages/TextualBody.js#L263)

**Comment by jryans** [comment] 2021-02-24 13:02
Ah hmm, I see... I tried making an event without `code` on app.element.io, but I guess the issue is just that I didn't back far enough in time, since the regression is already on app as well.

**Closed** 2021-02-24 13:33 UTC
Labels: bug, p2, regression, severity:minor, type:timeline
