### ISSUE TITLE
Threads all disappeared in main timeline

### ISSUE THREAD

**Issue by gileluard** [vector-im/element-web#24043] opened 2022-12-16 16:42 UTC
### Steps to reproduce

1. I opened my DM test room

#### What did you expect?

To see all my threads in the main timeline

<img width="486" alt="Screenshot 2022-12-16 at 17 28 20" src="https://user-images.githubusercontent.com/15386762/208146228-dcdb9117-cd80-4e14-8b2c-d1fd817e2510.png">

#### What happened instead?

Almost all the threads disappeared from the main timeline.

<img width="470" alt="Screenshot 2022-12-16 at 17 28 32" src="https://user-images.githubusercontent.com/15386762/208146461-fce04e9d-f5cc-4822-81a0-26107cda6b73.png">

**Note**
Threads reappeared when I opened the threads list panel
I can reproduce the bug by refreshing the page

### Operating system

macOS

### Browser information

Safari Version 16.2 (18614.3.7.1.5)

### URL for webapp

https://develop.element.io/
**AND**
https://app.element.io/

### Application version

Element version: a7124c935ece-react-bfaced2172f6-js-c973b26fa26e Olm version: 3.2.12
**AND**
Element version: 1.11.16
Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by MadLittleMods** [comment] 2022-12-16 17:29
Duplicate of https://github.com/vector-im/element-web/issues/24036

**Closed by MadLittleMods** 2022-12-16 17:29 UTC
Labels: T-Defect, A-Threads
