### ISSUE TITLE
Editing message breaks italic markdown made with asterisk when enclosed by text

### ISSUE THREAD

**Issue by samo296** [vector-im/element-web#23702] opened 2022-11-04 15:06 UTC
### Steps to reproduce

1. Have markdown enabled
2. Write message "foo\*bar\*baz"
3. Edit message and add a space, send again

### Outcome

Message should read "foo*bar*baz" before the edit and "foo*bar*baz " after, but instead it's "foo_bar_baz ", the italics disappeared.

### Will you send logs?

No

**Comment by robintown** [comment] 2022-11-04 15:29
Duplicate of https://github.com/vector-im/element-web/issues/23669

**Closed by robintown** 2022-11-04 15:29 UTC
Labels: T-Defect
