### ISSUE TITLE
Show which thread is unread (unread marker)

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19774] opened 2021-11-16 17:52 UTC
#### What would you like to do?
highlight somehow which thread is unread

#### Why would you like to do it?
the room has a notification count but there's no message. because it's in a thread. but which one?

#### How would you like to achieve it?
notification badge?

**Comment by daniellekirkwood** [comment] 2021-11-17 14:23
Thanks for creating this issue! We intend to add badges to the Thread Panel and are currently working on this. 

For now, I'll leave this issue open but once https://github.com/vector-im/element-web/issues/19126 is complete, this issue will also be closed.

**Comment by gsouquet** [comment] 2021-11-17 14:58
Closing as that's a duplicate of #19126.

**Closed by gsouquet** 2021-11-17 14:58 UTC
Labels: O-Frequent, A-Threads
