### ISSUE TITLE
Room topic unset itself when I deleted event from timeline

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20226] opened 2021-12-16 18:31 UTC
### Steps to reproduce

Cannot reproduce, but submitting rageshake in case it's got anything useful in it.

1. Updated room topic, closed dialog
2. Updated room topic again, closed dialog
3. Deleted timeline event for 1st update (maybe was 2nd by accident?)
4. Room topic vanished

#### What did you expect?
Room topic remains if I delete an old topic update

#### What happened instead?
Room topic deleted itself completely

### URL for webapp

develop.element.io

### Application version

Element version: 23b21c940c68-react-9a8265429c16-js-3eaed304466a
Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by gsouquet** [comment] 2021-12-20 09:46
I have tried the reproduction steps and did not experience the same issues as you did

**Comment by turt2live** [comment] 2022-06-14 05:45
Duplicate of https://github.com/vector-im/element-web/issues/7683

**Closed by turt2live** 2022-06-14 05:45 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, S-Minor, A-Room-Settings, A-Timeline, A-Room-View
