### ISSUE TITLE
"Username in use" during registration

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#3221] opened 2017-02-14 10:54 UTC
### Description

Occasionally, when registering using email identity, the message "Username in use" appears in the initial client - the one where registration began. The message appears when the recapture phase is complete in the second client - the one created by following the verification link in the email.

When the error message appears, the client appears to be syncing normally and clicking the "Register" button again will open the settings page of the new user as expected. The error message itself originates from a genuine "M_USER_IN_USE" from the server.

### Steps to reproduce

- Begin a registration process
- Receive email, click link in email
- Complete recapture phase in client opened using link
- Observe that occasionally, "Username in use" appears in the first client
![2017-02-14-100443_347x177_scrot](https://cloud.githubusercontent.com/assets/6750344/22926150/52fedf64-f2a3-11e6-9bed-c294593d11a4.png)

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Chromium 53
- **OS**: Ubuntu
- **URL**: locally-built Riot instance using `develop` branches. react-sdk 18cba1 - riot-web b6741d.

**Comment by ara4n** [comment] 2017-02-17 23:49
weird. never seen this before..

**Comment by ara4n** [comment] 2017-02-21 15:14
@BenfLewis0 caught this happening on video, i believe.  If it's happening to real hallway testing users we need to up the priority big-time.

**Comment by lukebarnard1** [comment] 2017-03-01 16:23
IRL @dbkr and I decided that it would best to wait for some changes of his that are up in the air before testing this or trying to fix it.

Given that the client with the error displayed is syncing normally, we should make sure that a correctly logged-in client (as login happens after a successful login) gets shunted to the directory.

**Comment by ara4n** [comment] 2017-03-20 11:23
@BenfLewis0 can you point us at the video where this happens?  Trying to work out if this leaves the whole app unusable or whether the 2nd window works...

**Comment by lampholder** [comment] 2017-03-20 11:26
This might be reprioritised based on the feedback from @BenfLewis0.

**Comment by BenfLewis0** [comment] 2017-03-20 11:31
Video in link below: 

https://www.dropbox.com/s/7pxreggk119g8hb/Recording%206.m4v?dl=0
Watch from 0:59 - 2:30

Hope this helps.

**Comment by BenfLewis0** [comment] 2017-03-20 11:32
@lampholder @ara4n ^

**Comment by dbkr** [comment] 2017-03-21 16:17
So the 2nd window works. It looks like it was being somewhat slow in this case: it sat there doing nothing for a bit after he completed the captcha, which was confusing. The second window did work in the end though.

I've tried to repro this and can't, so I'm fairly confident in saying that this will have been fixed in the latest refactor, or if it isn't, it is still possible for the user to complete registration.

**Comment by dbkr** [comment] 2017-03-22 11:41
I *did* just get this whilst testing signup from an iPhone (ie. when clicking the link, it went to /app which is running the old version which displayed 'username in use': registration continued fine on the iphone). This would tend to suggest it is indeed fixed on develop.

**Comment by lampholder** [comment] 2017-03-23 23:07
Okay, so we _think_ this one might be closed, but we're not 100% sure.

Because we have cause to think it's closed, and some supporting evidence, I'm going to bump this to P2 (meaning, if we had the time, we would invest it to establish for certain whether the refactor fixed what is otherwise quite a jarring introduction to the platform).

If we see more instances of this in the wild then consider bumping back to P2. If we don't see it again for a month or so, consider closing.

**Comment by lampholder** [comment] 2017-03-23 23:08
Dropping 'release-blocker' too on the strength of /develop's being at least not more broken than /app.

**Comment by lampholder** [comment] 2017-11-23 11:11
This just happened to me when registering for chat.status.im :sob: 

Steps:
- went to https://chat.status.im
- entered my email address, username (in this instance 'tom'), password, password conf
- clicked 'register' and received prompt to check email
- clicked the link in gmail
- opened a new chat.status.im tab
- that tab told me 'username in use'

Then I tried to log in anyway and succeeded.

I think this is higher than P2 - even if infrequent, it's super broken at a crucial moment.

**Comment by wuhlheide** [comment] 2020-01-02 16:25
Maybe it's similar to my problem:
Riot Web shows "**User ID already taken.**" when i do following on my private synapse/riot-web-environment:

* Register in Riot Web with e-mail (first browser tab)
* Click confirmation link in email
* A new browser tab opens which says "User ID already taken."
* Go to the first browser tab: Registration seems complete and i can login

The first browsertab receives some kind of ajax request which completes the registration, while the second browser tab opens.

**Comment by turt2live** [comment] 2020-01-02 16:32
@wuhlheide that's #10038

**Comment by kittykat** [comment] 2021-08-24 08:25
Closing as I can't reproduce this: both windows update me to show one of the "Registration Successful" messages.

If anyone can reproduce this issue, please reopen or reply with @kittykat so I get notified to reopen it for you.

**Closed by kittykat** 2021-08-24 08:25 UTC
Labels: T-Defect, P1, S-Major, A-Registration, X-Needs-Investigation
