### ISSUE TITLE
Cannot restore key

### ISSUE THREAD

**Issue by Dajamante** [vector-im/element-web#15792] opened 2020-11-22 13:56 UTC
### Description

Impossible to log in and restore previous sessions with recovery key.

### Steps to reproduce

1. Remove cookies
2. Logging to element
3. Trying to restore session

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) 
For the web app:

- **Browser**: Firefox and Opera
- **OS**: macOS, 
- **URL**:  app.element.io

**Comment by jryans** [comment] 2020-11-30 15:56
@Dajamante Sorry to hear about this, and thanks for including logs. My initial scan of the logs makes it seems as if key backup thinks it is enabled, so we may need a bit more detail. Could you include a screenshot / video of the step where restore is failing?

**Comment by Dajamante** [comment] 2020-12-07 12:17
Sorry for late reply. I can't manage to reproduce the exact error I reported.
But it is impossible to either confirm sessions by emoji or load recovery keys. I attach 2 screenshots.

https://drive.google.com/file/d/1_jQPTp1di-sRCNYEk2sedGXkgtpSeIEP/view?usp=sharing

https://drive.google.com/file/d/1yjcQf0b4czY4Uz0dyBHDzgViMfbtUkI6/view?usp=sharing

**Comment by jryans** [comment] 2020-12-08 16:53
@Dajamante I can't see those screenshots, can you mark them as viewable?

**Comment by Dajamante** [comment] 2020-12-08 22:16
Marked as viewable to anyone with the link.
Hope it works now.
https://drive.google.com/file/d/1yjcQf0b4czY4Uz0dyBHDzgViMfbtUkI6/view?usp=sharing
https://drive.google.com/file/d/1_jQPTp1di-sRCNYEk2sedGXkgtpSeIEP/view?usp=sharing

**Comment by jryans** [comment] 2020-12-11 17:32
@Dajamante Thanks for the screenshots! 

One thing to mention is the "Import E2E room keys" button in your second screenshot is not what you want here. (I agree it's confusing that there are so many different backup systems...) That only accepts an export of individual message keys created by the "Export E2E room keys", which is a manual step most people would not be going through. This is an old system that is not needed if you are using automated key backup.

The "recovery-key.txt" file you are trying to use is meant to unlock the newer automated key backup system e.g. on a new device if you aren't able to use emoji verification. It's just barely visible in your screenshots, but the "Secure Backup" section slightly up the screen is the one that applies here. From what I can see in the screenshot, I think it's trying to say "This session is backing up your keys", which means it's (supposed to be) working properly in the background. If some isn't decrypting the way you expect, you can force a restore from key backup with the green "Restore from Backup" button.

**Comment by Dajamante** [comment] 2020-12-11 19:16
Thank you for that. Even if I do restore from back up, it does not decrypt old messages that were "lost" when I changed sessions and deleted cookies.
For example I just restored backup and my messages are still encrypted.
<img width="571" alt="Screenshot 2020-12-11 at 20 14 39" src="https://user-images.githubusercontent.com/40670675/101944857-ae26d300-3bed-11eb-88a8-c1d7fc3089cc.png">

**Comment by jryans** [comment] 2020-12-14 10:53
Hmm, do you know if automated key backup was set up on your previous session? It would only have the message keys saved if it was active in the old session when those messages first arrived.

For example, when was your `recovery-key.txt` file created? Was it created in your old session?

**Comment by Dajamante** [comment] 2020-12-14 11:02
I think so, I had it for a while now. Just lingering in my downloads. But the undecrypted messages are older than the key.

**Comment by jryans** [comment] 2020-12-14 13:43
Hmm, I wonder if there was something preventing your previous session from uploading message keys to key backup...?

It's hard to know conclusively, since you don't have access to that session any more. 😖

**Comment by kittykat** [comment] 2021-11-30 18:18
We could not reproduce the issue during a community testing session, so I will close this one for now. Please commend with @kittykat if you are still experiencing it and I will reopen the issue for you

**Closed by kittykat** 2021-11-30 18:18 UTC
Labels: T-Other, A-E2EE-Key-Backup, X-Needs-Community-Testing
