### ISSUE TITLE
Names in channel list should not move around

### ISSUE THREAD

**Issue by nikhiljha** [vector-im/element-web#14913] opened 2020-08-09 03:31 UTC
### Description

Channels in the list should not move around when you click on them (at least, while sorting is set to A->Z mode). This is confusing and disorienting.

![2020-08-08_20-26-33](https://user-images.githubusercontent.com/2773700/89724273-aa700f00-d9b5-11ea-8a90-6ffd0377f921.gif)

### Steps to reproduce

- Join a bunch of channels, some inside of a community and some not.
- Click on a community to the left of the screen to select it.
- Click around on the channels, watch them move around.

### Version information

- **Platform**: web
- **Browser**: Firefox 79.0
- **OS**: Windows
- **URL**: Riot Web v1.7.1

**Comment by turt2live** [comment] 2020-08-09 03:50
Duplicate of https://github.com/vector-im/element-web/issues/14888

**Closed by turt2live** 2020-08-09 03:50 UTC
Labels: bug
