### ISSUE TITLE
Emoji reaction picker jittery when scrolling to the very bottom

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18514] opened 2021-08-12 12:42 UTC
### Steps to reproduce

1. open picker to react with emoji
2. search, e.g. `de` to find :de: 
3. scroll to the bottom

### What happened?

menu jitters, scrolling up and down by ~2px constantly. the bottom row is thus not clickable.

### What did you expect?

stay at bottom

### Operating system

arch

### Application version

Element Nightly version: 2021081201 Olm version: 3.2.3

### How did you install the app?

aur nightly-bin

**Comment by t3chguy** [comment] 2021-08-12 13:02
Duplicate of https://github.com/vector-im/element-web/issues/18272

**Closed by t3chguy** 2021-08-12 13:02 UTC
Labels: T-Defect
