### ISSUE TITLE
Call tiles type too big

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#25787] opened 2023-07-13 14:32 UTC
### Your use case

<img width="786" alt="Screenshot 2023-07-13 at 14 38 24" src="https://github.com/vector-im/element-web/assets/4626865/1e7dd112-6914-4ae9-bccb-cb409611c048">

With the best effort typography pass merged, the type in the call tiles is huge.

Suggest to normalise these to use the same as message senders & message body, i.e. `--cpd-font-body-md-semibold` & I think `--cpd-font-body-sm-regular`

**Comment by t3chguy** [comment] 2023-07-13 14:33
Duplicate of https://github.com/vector-im/element-web/issues/25684

**Closed by t3chguy** 2023-07-13 14:33 UTC
Labels: T-Enhancement
