### ISSUE TITLE
New notifications badge on Space for DMs

### ISSUE THREAD

**Issue by borisrunakov** [vector-im/element-web#19775] opened 2021-11-16 21:33 UTC
### Your use case

A new messages notification badge on a Space's Icon would be very helpful for new messages on DMs. Currently Element Web new messages in DMs generate a  badge only in `Home` Space. 
Focusing on a specific Space with top priority messages is not achievable, as the DMs don't show a notification badge for new messages. So if you are viewing a different Space you end up looking into `Home` for new messages and/or the Space you care most.
An option to enable this feature in user preferences would be very beneficial.

### Have you considered any alternatives?

Converting all DMs to Rooms.

**Comment by t3chguy** [comment] 2021-11-17 10:14
Duplicate of https://github.com/vector-im/element-web/issues/18728

**Closed by t3chguy** 2021-11-17 10:14 UTC
Labels: A-Notifications, A-Spaces, A-DMs, X-Needs-Design, T-Enhancement, O-Occasional
