### ISSUE TITLE
Is it possible to receive notifications when the page is closed？

### ISSUE THREAD

**Issue by miyouzi** [vector-im/element-web#14972] opened 2020-08-16 04:21 UTC
**Is your suggestion related to a problem? Please describe.**

Hello, I am using element-web(PWA) on Chrome (version 84), I found that I could only  receive notifications if the PWA was open. There are no notifications When I close the PWA (Chrome still running).

**Describe the solution you'd like**

I have tried to deploy element-web on my own server and to use app.element.io, but got the same situation.

**Describe alternatives you've considered**

So is it possible to receive notifications when the page is closed？

**Comment by t3chguy** [comment] 2020-08-17 09:06
Duplicate of https://github.com/vector-im/element-web/issues/604

**Closed by t3chguy** 2020-08-17 09:06 UTC
Labels: suggestion
