### ISSUE TITLE
Group/community long description remains (superficially) editable to admins even after they leave the group

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6310] opened 2018-03-13 15:54 UTC
- Create a group
- Leave the group
- Click on the long description box
- Typey typey typey

You're not the admin any more, so it should be styled disabled.

It's no biggy, since you can't actually save your changes, but it looks glitchy.

**Comment by turt2live** [comment] 2018-03-13 16:01
Sounds like a duplicate of https://github.com/vector-im/riot-web/issues/6180 by symptoms only

**Comment by turt2live** [comment] 2018-04-12 18:47
The root of this issue appears fixed, however there's a small delay between the time you leave and when you can no longer reach the settings. During this time, you're able to go back and poke around.

**Comment by SimonBrandner** [comment] 2021-06-22 10:28
Spaces are now in beta

**Closed by SimonBrandner** 2021-06-22 10:28 UTC
Labels: A-Spaces, P2, S-Tolerable, T-Defect
