### ISSUE TITLE
All rooms of subspaces are visible in parent Space

### ISSUE THREAD

**Issue by jeder49** [vector-im/element-web#22490] opened 2022-06-08 18:32 UTC
### Steps to reproduce

1. Create a Space (parent Space)
2. Create Spaces in this Space (subspaces)
3. Create rooms in this subspaces
4. look in the parent Spaces

#### What did you expect?
I hoped that the rooms of the subspaces would not be visible in the parent Space, so that I could use the subspaces as categories.
#### What happened instead?
All rooms of the subspaces are listed in the parent Space and it is a mess.

### Operating system

Window

### Application version

Element version: 1.10.14 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-06-08 18:37
Duplicate of https://github.com/vector-im/element-web/issues/16786

**Closed by t3chguy** 2022-06-08 18:37 UTC
Labels: T-Defect
