### ISSUE TITLE
Memory leak and RAM usage

### ISSUE THREAD

**Issue by kroeckx** [vector-im/element-web#10277] opened 2019-07-07 08:56 UTC
Hi,

The electron version uses 12 GB of RAM just after starting. This will grow over time, and I've seen it use 60 GB of RAM.

I'm using the .deb package from riot.im. currently using version 1.2.2, but it's not a new problem.

**Comment by ara4n** [comment] 2019-07-07 12:11
That’s crazy - for typical use it should use about 300MB resident (rsz); up to 1GB for worst case massive account.

What RSZ are you seeing? And how big is the javascript heap? (ctrl-shift-I to open the inspector; go to performance tab; hit heap snapshot to see where the RAM is going).

-- 
Matthew Hodgson
Matrix.org

**Comment by kroeckx** [comment] 2019-07-07 15:15
On Sun, Jul 07, 2019 at 05:11:34AM -0700, Matthew Hodgson wrote:
> That’s crazy - for typical use it should use about 300MB resident (rsz); up to 1GB for worst case massive account.

A few minutes after I started it, I get:
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
kurt      8021  4.7  3.5 1242136 284376 pts/5  Sl+  17:05   0:16  |   \_ /opt/Riot/riot-web
kurt      8023  0.0  0.4 210664 40136 pts/5    S+   17:05   0:00  |       \_ /opt/Riot/riot-web --type=zygote --no-sandbox
kurt      8051 28.5  7.9 12987672 638572 pts/5 Sl+  17:05   1:41  |       |   \_ /opt/Riot/riot-web --type=renderer 
kurt      8087 13.6 10.2 1638764 828360 pts/5  Sl+  17:05   0:45  |       |   \_ /opt/Riot/riot-web --type=renderer
kurt      8046  2.1  1.4 361956 117748 pts/5   Sl+  17:05   0:07  |       \_ /opt/Riot/riot-web --type=gpu-process

> And how big is the javascript heap?

It reports things around 300 MB.

**Comment by ara4n** [comment] 2019-07-07 16:11
right, so that’s 284MB + 40MB + 640MB + 828MB + 118MB of resident RAM. however, some of that might be shared libraries shared between the processes?

Will compare with other electron deployments.

300MB js heap is about right.

**Comment by kroeckx** [comment] 2019-07-07 16:28
So looking at the smaps file, I see things like:
32089a940000-320a9a900000 ---p 00000000 00:00 0
Size:            8388352 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
VmFlags: mr mw me sd

32081a900000-32089a900000 ---p 00000000 00:00 0
Size:            2097152 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
VmFlags: mr mw me sd

149b8d9b1000-149bcd942000 ---p 00000000 00:00 0
Size:            1048132 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
VmFlags: mr mw me sd

So that's 8 GB - 256 kB, 2 GB, and 1 GB - 444 kB that's allocated
but unused.

**Comment by kroeckx** [comment] 2019-08-13 22:01
So I got his now:
[4:0812/224748.911437:FATAL:memory_linux.cc(42)] Out of memory.

**Comment by kroeckx** [comment] 2019-09-18 16:49
I have to restart riot on daily basis because it just stops working.

**Comment by xsellier** [comment] 2020-02-27 21:53
Riot is just using 11G or ram....

**Comment by t3chguy** [comment] 2020-02-27 22:10
riot.im/develop (and next point release) fixes a lot of leaks.

**Comment by wsmwk** [comment] 2021-09-05 14:43
@kroeckx, @xsellier,  can you still reproduce this issue?

**Comment by xsellier** [comment] 2021-09-05 16:06
I no longer use riot sorry.

**Comment by kroeckx** [comment] 2021-10-03 10:07
I guess it's not as bad as it used to be. At start it seems to
require 1.5 GB and then seems to stay stable around 1 GB of used
RAM.

**Comment by kittykat** [comment] 2021-12-21 14:47
@kroeckx I'm going to close this issue for now as the problems from 2019 have been resolved and the codebase has changed significantly since then. If you feel that there are further improvements to be made, it would be helpful to have a new issue with fresh details. Thank you for helping make Element better!

**Closed by kittykat** 2021-12-21 14:47 UTC
Labels: X-Needs-Info, A-Performance, T-Other, A-Memory
