### ISSUE TITLE
if you click the facepile for a space, it noops if the memberlist is already shown

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#19818] opened 2021-11-19 20:01 UTC
this is very confusing, given the tooltip says 'click the facepile to see all the members!', and yet unless you realise that the membership list is already open, it does nothing. we should hide the tooltip if it's open or something.

**Comment by t3chguy** [comment] 2021-12-14 13:23
Duplicate of https://github.com/vector-im/element-web/issues/17406

**Closed by t3chguy** 2021-12-14 13:23 UTC
Labels: T-Defect, S-Minor, A-Spaces, X-Needs-Design, O-Occasional
