### ISSUE TITLE
Integrate video calls into regular calls.

### ISSUE THREAD

**Issue by BloodRaven0** [vector-im/element-web#12646] opened 2020-03-07 17:18 UTC
**Is your suggestion related to a problem? Please describe.**
The fact that you have to hang up a normal call and enter a video call is ridiculous. Even more so if the other person doesn't have a camera, it won't allow them to enter the call!

**Describe the solution you'd like**
Just make "enable camera" a button in a normal call, just like the mute button is.

**Comment by T-bond** [comment] 2020-11-06 20:08
It would be great, if this would include starting/stopping screen sharing in the middle of the call.

**Comment by SimonBrandner** [comment] 2021-02-28 16:57
Duplicate of [#188](https://github.com/vector-im/element-web/issues/188)

**Comment by SimonBrandner** [comment] 2021-02-28 16:58
Sorry, I got confused :laughing:

**Comment by L1pE** [comment] 2021-05-15 09:24
I had given Element another chance recently and was happy to see that screen share finally worked, only to have my hopes crushed when trying to get into an actual call and seeing it requires the other to have a webcam.

Is there any way to force both sides to screen share to maybe bypass this currently?

**Comment by SimonBrandner** [comment] 2021-05-15 09:29
There are ways to get around things like this. One option would be having a fake webcam (e.g. using OBS). Ask around in [Element Web/Destkop](https://matrix.to/#/#element-web:matrix.org?via=matrix.org&via=privacytools.io&via=mozilla.org) and someone might be able to help you with the specifics. 

Anyway, VoIP is currently being worked on, so we might get something in the next month/months

**Comment by L1pE** [comment] 2021-05-15 09:36
Thanks, but I was hoping for something that doesn't require another program. I figure since screen share counts as video call, and video call wants video feed from everyone, the one responding could provide his own screen share instead somehow. But if that's not possible currently I guess I will just wait for a proper solution in an update.

**Comment by SimonBrandner** [comment] 2021-05-15 09:40
Sadly, there is no way to do that currently. Let's hope for a better solution :)

(also, next time please ask in the Element Web/Desktop room as this is an issue tracker, not a forum)

**Comment by SimonBrandner** [comment] 2021-08-18 12:45
I am going to close this in favour of https://github.com/vector-im/element-web/issues/18619 where the design details will be figured out

**Closed by SimonBrandner** 2021-08-18 12:45 UTC
Labels: P1, A-VoIP, T-Enhancement
