### ISSUE TITLE
Room header avatar does not match timeline avatar

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21578] opened 2022-03-28 13:33 UTC
### Steps to reproduce

1. Not quite sure... but Element ends up in that state sometimes

#### What did you expect?

For the same avatar to be used everywhere for a given user

#### What happened instead?

Room header & room list use the wrong avatar, timeline uses the correct one

<img width="744" alt="Screen Shot 2022-03-28 at 14 30 08" src="https://user-images.githubusercontent.com/769871/160408866-b82ad693-e2a8-4544-b4bd-710c546fa06a.png">

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-03-28 13:42
Duplicate of https://github.com/vector-im/element-web/issues/20064

**Closed by t3chguy** 2022-03-28 13:42 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Avatar, Z-Cache-Confusion, O-Occasional
