### ISSUE TITLE
some ASCII smileys are turned into something different

### ISSUE THREAD

**Issue by Flexmaen** [vector-im/element-web#26724] opened 2023-12-11 18:33 UTC
### Steps to reproduce

1. I wrote _:-D_
3. I pressed enter.
4. I got ✌️

#### What did you expect?
I expeced to write _:-D_

#### What happened instead?
I got this emoji: ✌️

Oder Smileys like :-) ;-) ;-D work, but the same problem with :-O and :-P - so I guess everything containing a letter triggers the pop-up emoji window that will turn your input into something different then.

### Operating system

Windows

### Browser information

Vivaldi

### Application version

Version von Element: 1.11.49
Crypto version: Olm 3.2.15

### Will you send logs?

No

**Comment by jjj333-p** [comment] 2023-12-11 18:49
its a little strange that it changes to that but maybe try disabling this in settings -> preferences 

![image](https://github.com/vector-im/element-web/assets/94018608/8a79fc86-5f4a-4c6f-b1b4-74fd4d262873)

**Comment by Flexmaen** [comment] 2023-12-11 19:00
Thanks for the quick reply, but I even had this option off already.
It helped when I also disabled "Enable Emoji suggestions while typing".

But still this is a bug, because:
- replacing Emojis was already turned off
- :-D shouldn't be replaced with a emoji which is triggered by :v:

If you continue writing, the smiley won't be replaced. But usually you put the smileys on the end of the line and so when pressing enter afterwards it get's replaced then.

**Comment by t3chguy** [comment] 2023-12-12 09:08
Duplicate of https://github.com/vector-im/element-web/issues/9757

**Closed by t3chguy** 2023-12-12 09:08 UTC
Labels: T-Defect
