### ISSUE TITLE
Better error messages where actions fail due to restricted federation

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#19598] opened 2021-11-03 12:13 UTC
#### What would you like to do?
I'd like to know that my invite failed due to restricted federation.

#### Why would you like to do it?
Because the existing message "You do not have permission to invite people to this room" is not helpful or appropriate.

**Comment by t3chguy** [comment] 2021-11-03 12:42
The client has no way of knowing that the federation is restricted

**Comment by richvdh** [comment] 2021-11-19 11:34
> The client has no way of knowing that the federation is restricted

this is a thing that can be fixed, of course!

**Comment by t3chguy** [comment] 2022-02-04 10:34
Duplicate of https://github.com/vector-im/element-web/issues/10673

**Closed by t3chguy** 2022-02-04 10:34 UTC
Labels: A-Federation, A-Invite, T-Enhancement
