### ISSUE TITLE
RTL text should be right-justified

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#4771] opened 2017-08-09 12:48 UTC
If the message body contains (or at least, begins with) RTL script, it should be right-aligned in the message panel rather than left-aligned

**Comment by lukebarnard1** [comment] 2017-08-11 16:51
Message panel !== RTE

**Comment by lukebarnard1** [comment] 2018-05-17 09:02
Looking into this, the following changes need to be made:
```diff
 .mx_EventTile_body {
...
+    text-align: -webkit-auto;
+    display: block;
 }
```

I'm not sure how this will affect all other uses of event tiles, so should be worth testing thoroughly.

**Comment by ahangarha** [comment] 2020-03-02 19:04
Wouldn't it be solved by adding `text-aligh: start`? So it automatically and based on direction of the text will determine to align text on left or right.

**Comment by MohsenNz** [comment] 2020-11-30 19:50
Hi guys. How to fix rtl right-justified?

![Screenshot from 2020-11-29 18-08-35](https://user-images.githubusercontent.com/23291352/100656549-21b12080-3362-11eb-8624-25cb0f7480c6.png)

You can see It's left-justified.

**Comment by ahangarha** [comment] 2020-12-01 15:53
Unfortunately element uses <span> tag to put text in HTML. They should use
<p> or <div> with dir=auto and set text-align: start.

در تاریخ دوشنبه ۳۰ نوامبر ۲۰۲۰،‏ ۲۳:۲۰ mohsenNz <notifications@github.com>
نوشت:

**Comment by MohsenNz** [comment] 2020-12-01 19:09
:/ So dose this feature add in future? What do u think?

**Comment by ahangarha** [comment] 2020-12-03 14:47
This should be answered by the dev team. I myself have motivation to act on
it but don't have any timeframe. The best thing for now is to elaborate the
issue for them so that they can understand the exact issue and act
accordingly.

Maybe you can update the issue.

**Comment by jryans** [comment] 2020-12-14 14:00
https://github.com/matrix-org/matrix-react-sdk/pull/5453 fixes the messages themselves, but there are some surrounding UI issues to consider as part of that, since it also changes the appearance of things outside of the message (like edited indicators).

**Comment by ahangarha** [comment] 2021-11-29 14:21
Guys,

I have made these simple styles which nearly all issues with bidi support: https://userstyles.world/style/2159/element-bidi

As far as I see it is working perfectly. It was little issue if we have a mixed markdown content which can be managed in some way but doesn't have periority now.

I wonder why still we don't have this feature on element!

![image](https://user-images.githubusercontent.com/11241315/143884628-6bda775b-5b85-41be-b718-fc2f36701e37.png)

**Comment by SPiRiT369** [comment] 2022-01-23 11:37
IMHO - This is a very important change request. It would be great (and should be) if the entire app support RTL and not just message bodies.

Examples:
- The avatars should float to the right
- User names should float to the right
- If Element language is set to RTL language (Hebrew/Arabic) then all system messages should be in rtl direction as well. Currently, system messages and dialogs are always left-to-right and it look very bad when RTL language is used.
- Might also be good to make the side panel float to the right, as accepted in RTL apps. (but less important)

Perhaps it is a good idea to add a parameter for each language whether it is rtl or ltr?

**Comment by ahangarha** [comment] 2022-01-24 06:37
@SPiRiT369 The issue you raised is a different issue. That is to have support for RTL layout if a person choose to use some RTL languages for the app.

What we are discussing here is to add support for rendering text in correct direction regardless of the general direction of the layout. The title is misleading because if the layout be RTL, then we should render LTR text left-aligned. Though worth to mention that here the issue is not alignment only.

I can work on what you mentioned but I couldn't find any place to set language for entire app. If you help me to find this option, I might be able to fix this issue.

**Comment by alongls** [comment] 2022-04-03 13:34
Hello
is there any progress / update  with this issue ?
languages like Arabic and Hebrew are shown very badly in the element web client
thanks.

**Comment by t3chguy** [comment] 2022-06-10 23:54
Closing in favour of https://github.com/vector-im/element-web/issues/14520

**Closed by t3chguy** 2022-06-10 23:54 UTC
Labels: T-Defect, S-Major, A-Timeline, I18n

**Comment by sam-ka** [comment] 2022-11-21 08:30
For those who are just looking to improve the legibility of large blobs of text, you can temporarily fix the alignment yourself **right now** without using an alternative for or recompiling Element yourself. This fix must be re-applied each time you restart Element for Desktop. 

If you're using the web client, you can use Grease Monkey or similar add-ons to fix the issue more permanently.

In Element for Desktop:

1. Press Ctrl+Shift+I to bring up the element inspector
2. Click on the + in the CSS pane (near `.hov` and `.cls`). This will inject a new class for `<body>`. This doesn't matter.
3. Click on the small `inspector-stylesheet` link to the right of the newly injected class. This will open the largely empty inspector sheet in the sources pane.
4. Remove the empty body class and copy the following CSS rules and paste them into the new sheet:
    ````
        span.mx_EventTile_body {
            text-align: start;
            display: inline-block;
        }
    ````

While this rule won't fix everything, it will fix the alignment for multi-line comments (likely the most poignant issue for RTL users by far) without affecting anything else. It's a low-effort fix that should drastically improve your experience until a proper fix is implemented and pushed upstream.
