### ISSUE TITLE
Missing notification when a room you're in upgrades to a newer version

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#19112] opened 2021-09-21 13:30 UTC
### Steps to reproduce

1. Have an older version of the room
2. Make owner of the room upgrade it to the newest version

### What did you expect?
I expect a notification telling me that I need to take action, so that I won't lose new backlog.

### What happened?
I didn't get any notification or feedback from the Element client that the room has been upgraded, I've been told that by a friend instead.

### Have you submitted a rageshake?

No

**Comment by Palid** [comment] 2021-09-27 10:07
<img width="627" alt="CleanShot 2021-09-27 at 12 07 20@2x" src="https://user-images.githubusercontent.com/3636685/134888911-c0c1aec7-c365-4192-8e75-53876fbd3b1c.png">
Seems correct.

**Comment by Palid** [comment] 2021-09-27 10:08
To add some more context: neither Element on Android nor the Electron version pinged me.

**Comment by aaronraimist** [comment] 2022-02-22 16:35
Got it again today when `#matrix-debian:matrix.org` upgraded. The NotifPanel showed that the room was upgraded but the room list didn't show a red notification badge.

<img width="637" src="https://user-images.githubusercontent.com/5855073/155175982-679995c1-eb62-49f0-ac51-fecedbae9983.png">
<img width="309" src="https://user-images.githubusercontent.com/5855073/155176112-3c7fcce5-ac7b-4146-832d-f98359e792bc.png">
<img width="343" src="https://user-images.githubusercontent.com/5855073/155176141-8d1a5eaf-77fe-4c99-ae55-bb9c44f72390.png">

**Comment by t3chguy** [comment] 2022-06-13 20:10
Duplicate of https://github.com/vector-im/element-web/issues/11932

**Closed by t3chguy** 2022-06-13 20:10 UTC
Labels: T-Defect, S-Major, A-Notifications, A-Room-Upgrades, O-Uncommon
