### ISSUE TITLE
Updates revert Windows Sound settings for Elements Notifcations

### ISSUE THREAD

**Issue by SomeoneSomewhereHow** [vector-im/element-web#15470] opened 2020-10-15 10:42 UTC
### Description

When an update released within Element, if the volume of notification is controlled by Windows Sound Manager the volume level is reset to full maximum. The notification jingle is already annoying enough and with no easy way in the default client to change nor a volume control within the application; Windows Sound manager is the only way to control the level of alert.

### Steps to reproduce
Adjust volume of Element in Windows Sound Manager
Update Client

--

The volume level should stay the same after each update and not reset.

**Comment by t3chguy** [comment] 2020-10-15 10:47
Duplicate of https://github.com/vector-im/element-web/issues/15171

**Closed by t3chguy** 2020-10-15 10:47 UTC
