### ISSUE TITLE
Option for no dialog for posting of images

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16908] opened 2021-04-10 08:22 UTC
When I post a text message, it just works.  When I post an image, a dialog is raised. I don't ever want to see this dialog.  Please give the user an option to switch this off by having a checkbox on the dialog that says "Never show this again".  When the checkbox is checked, switch on a global setting that suppresses the dialog.  Don't make the user look around in the settings for a way to do this.  Don't do this in general, for any feature or reason, if at all possible.  Instead, provide the switch locally at the pain-point--the unwanted dialog--and then make any needed global-settings adjustments automatically for the user.

**Comment by SimonBrandner** [comment] 2021-04-10 11:27
Duplicate of [#9418](https://github.com/vector-im/element-web/issues/9418)

**Closed by SimonBrandner** 2021-04-10 11:27 UTC
Labels: T-Enhancement
