### ISSUE TITLE
Threads: Messages from Timeline going in Thread Panel

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#20340] opened 2021-12-23 15:16 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Typing messages in the timeline composer, they're appearing in the Thread panel as anew threads...
2. What do you click?
Thread panel list view
3. More steps…

#### What did you expect?
Messages to not show in thread panel
### Application version

Element Nightly version: 2021122301 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

<img width="1074" alt="threadpanelissue" src="https://user-images.githubusercontent.com/89144281/147259847-bd03cfd0-9502-45ef-b004-b47bcc2c3507.png">

**Comment by gsouquet** [comment] 2021-12-23 15:18
Duplicate of https://github.com/vector-im/element-web/issues/20325

**Closed by gsouquet** 2021-12-23 15:18 UTC
Labels: T-Defect, A-Message-Bubbles, Z-Labs
