### ISSUE TITLE
Can't invite a user using their user name

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [vector-im/element-web#19004] opened 2021-09-13 11:09 UTC
### Steps to reproduce

1. I pasted his UN into the invite field both in a private area & a group area & I got an error. Here's a recording. https://mega.nz/file/Y09SBLLa#TNYC3bNcLAlL5UZVA02tMaM8fll2sgfpgKw6JYxZtZQ
2. When I used his e-mail it worked.
3. When he came into the room, I checked, & it was his correct UN.

On another note, I updated a previous bug report about a month or two ago & never heard back. Do you guys get notified when a bug reported is added to?

I think you closed it & I thought it would re-open. 

I added a lot more evidence in that last update.

Thanks

### Operating system

Win 7

### Application version

There is no help about for me, just help --- Element Help - strange

### How did you install the app?

I really don't remember, it was over a year ago. I assume from your site.

### Homeserver

I think it's matrix.org. I still don't understand all of that

### Have you submitted a rageshake?

No

**Comment by robintown** [comment] 2021-09-13 12:01
Duplicate of https://github.com/vector-im/element-web/issues/17523 - Please watch that ticket for further progress on this issue.

**Closed by robintown** 2021-09-13 12:01 UTC
Labels: T-Defect
