### ISSUE TITLE
Impossible to interact with the tray icon and thus to quit the app (desktop version based on electron) (and weird icon issue)

### ISSUE THREAD

**Issue by ArchangeGabriel** [vector-im/element-web#3133] opened 2017-02-04 14:29 UTC
When I start riot, I’ve got a strange behaviour. I either start it from within a terminal or using the desktop entry added by [this .desktop file](https://aur.archlinux.org/cgit/aur.git/plain/riot.desktop?h=riot).

When starting a first time, it doesn’t work. A window is added to task manager if using the desktop entry, but then disappears without anything else happening; while using the terminal results in this:
```
Starting auto update with base URL: null
Auto update not supported on this platform
Unhandled exception TypeError: Error processing argument at index 0, conversion failure from /usr/lib/riot/electron/src/../img/riot.png
    at TypeError (native)
    at Object.exports.create (/usr/lib/riot/electron/src/tray.js:63:16)
    at App.electron.app.on (/usr/lib/riot/electron/src/electron-main.js:199:10)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

(electron:21415): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window

(electron:21415): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window

(electron:21415): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
```

And then nothing happens, I have to `Ctrl+C` to get out of it.

Then, on a second attempt, seems become very weird. If the previous attempt was from the terminal, then it doesn’t work as above. However, if the previous failed attempt was from the desktop entry, then it does work whether trying from the terminal or the desktop entry.

After this, it goes back to square one. So, I have a work-around for now (just launch it twice from the desktop entry), but this is far from ideal and could confuse people if I’m not the only one affected.

**Comment by ArchangeGabriel** [comment] 2017-02-04 14:46
OK, I’ve partly fixed it, the issue was the missing `riot.png` file. Adding it made it work (so sorry for the noise about this part), however it also enabled a tray icon that can’t be interacted with and makes `Ctrl+Q` the only way to exit the app (closing the window results in a tray icon staying indefinitely with means of interaction). Should I open a new issue or is #2799 somehow already tracking that?

**Comment by dbkr** [comment] 2017-02-04 18:32
Yep, this does sounds like problems caused by the new tray icon. What desktop environment are you using? I suspect it's not allowing interaction with the tray icon which means you don't get the menu / app focusing behaviour when you click the tray icon.

Can you interact with other tray icons in your desktop environment, and if so in what way?

**Comment by ArchangeGabriel** [comment] 2017-02-05 22:34
I’m running KDE’s Plasma 5… I can definitively interact with other tray icons, they all have different behaviours but most of them have left and right-click menus (plus hover display, which Riot does have too, displaying a pixelized icon with “electron” as text, see the attached picture).

![tray-hover](https://cloud.githubusercontent.com/assets/490531/22630495/885ee4a0-ebfb-11e6-89b7-7c1151ba8c3d.png)

**Comment by ArchangeGabriel** [comment] 2017-02-18 15:50
Another user reported the same issue, on Plasma 5 too.

**Comment by kbg** [comment] 2017-02-27 17:25
I had the same issues on Plasma 5. Installing the `libappindicator-gtk3` package on Arch Linux solved this problem for me.

I am now able to interact with the tray icon using the right mouse button. Unfortunately this also introduced an issue rendering the icon: When `libappindicator-gtk3` is installed, only the upper left corner of the riot icon is displayed in the system tray. If I remove the `libappindicator-gtk3` package (and restart the riot app), the full icon is shown again, but it cannot be interacted with.

In case this is a packaging issue: I built the Riot Desktop package using the build script from [AUR](https://aur.archlinux.org/packages/riot-desktop/), which currently uses version 0.9.7 of [riot-web](https://github.com/vector-im/riot-web).

**Comment by ArchangeGabriel** [comment] 2017-03-27 03:03
Hum indeed, using libappindicator-gtk3 allows to interact with the icon, but then it’s rendering is wrong.

**Comment by t3chguy** [comment] 2017-04-03 18:45
The tooltip text being `electron` is an issue upstream, I'll look through issues and report it if it doesn't already exist, tested it with the sample apps provided.

**Comment by t3chguy** [comment] 2017-06-12 17:03
I fixed this for myself on KDE Neon (Ubuntu + Plasma) by using equivs-control to make a dummy libappindicator1 and installing it

**Comment by MurzNN** [comment] 2017-07-12 11:17
@t3chguy can you describe more detaily how to fix this problem on Ubuntu with KDE5?

**Comment by t3chguy** [comment] 2017-07-12 11:20
@MurzNN install https://riot.ovh/_matrix/media/v1/download/riot.ovh/RrwsYrxMcIyHWjfhpxxWtvEN over libappindicator1, this is a dummy package I made using `equivs-control`, you are free to make your own if you don't trust mine. It `provides` `libappindicator1` at an inflated version to replace any installed with a no-op package.

**Comment by MurzNN** [comment] 2017-07-13 06:07
@t3chguy thanks, it helps! At now tray icon looks and works well!

**Comment by z3ntu** [comment] 2017-09-27 08:36
Can confirm that removing libappindicator3-gtk makes the icon look not-zoomed in but the resolution of the tray icon is very bad and looks pretty ugly it's current form.

**Comment by ArchangeGabriel** [comment] 2017-10-16 18:55
I confirm too that removing libappindicator3-gtk now results in a working tray icon but very blurred. At least we can interact with it and the notification badge works.

**Comment by ArchangeGabriel** [comment] 2018-05-20 18:57
Apparently blurry tray icon for electron apps under KDE is a common bug, not specific to Riot (and I can confirm I also have this issue with other apps). Same goes for wrong size when libappindicator is installed. For instance https://github.com/cozy-labs/cozy-desktop/issues/990.

**Comment by MurzNN** [comment] 2018-05-20 19:12
In cozy-labs/cozy-desktop#990 there are workaround that solve this KDE bug:
> I have patched the code to use a 22*22 icon size when KDE environment is detected.

Maybe Riot can do the same thing?

**Comment by MurzNN** [comment] 2018-06-06 14:07
Quck fix for Riot Electron app tray icon in Kubuntu (Ubuntu KDE) and Debian Linux systems:
```
mv /usr/lib/x86_64-linux-gnu/libappindicator.so.1.0.0 /usr/lib/x86_64-linux-gnu/libappindicator.so.1.0.0_off
```
This will work until `libappindicator1` package will be upgraded/reinstalled

**Comment by lazToum** [comment] 2018-06-18 23:35
on Arch, plasma 5.13 with `libappindicator-gtk3`:
``XDG_CURRENT_DESKTOP=Unity riot-desktop``

**Comment by mnn** [comment] 2018-07-31 09:59
Got same issue - icon is a purple box (and left click does nothing, not sure if that is correct behaviour). @lazToum's workaround seems to work (at least when launching from a console), I'll modify the autostart file and hopefully it will fix the issue for good.

**Comment by shirishag75** [comment] 2018-09-14 20:02
would having ayatana-appindicator help in anyway instead of libappindicator ? https://github.com/AyatanaIndicators/libayatana-appindicator.  See https://wiki.debian.org/Ayatana/IndicatorsTransition

**Comment by t3chguy** [comment] 2018-09-15 05:59
It's not something we get control of, it's something electron-builder specifies

**Comment by akontsevich** [comment] 2018-10-31 21:58
> XDG_CURRENT_DESKTOP=Unity riot-desktop
@lazToum  where to set this?

**Comment by ChrisP4** [comment] 2019-01-09 17:14
@akontsevich run that command: XDG_CURRENT_DESKTOP=Unity riot-desktop 
to run Riot client and get the correct displaying icon.

**Comment by akontsevich** [comment] 2019-01-09 19:01
@ChrisP4 it solves only icon look but does not fix tray behavior on mouse click. Also DE session manager does not store exact app command to rerun and icon still ugly on next DE start on session restore.

**Comment by c-e-p-x-u-o** [comment] 2019-01-09 20:21
without ```XDG_CURRENT_DESKTOP```:
![image](https://user-images.githubusercontent.com/14617699/50926078-30884480-1465-11e9-8625-cc6acbb6d201.png)

with ```XDG_CURRENT_DESKTOP=Unity```:
![image](https://user-images.githubusercontent.com/14617699/50926100-43027e00-1465-11e9-9a07-8c60ec16c0e5.png)

**Comment by c-e-p-x-u-o** [comment] 2019-01-09 20:21
Enlightenment 22.4

**Comment by eleius** [comment] 2019-02-16 11:52
Anyone got this working in Gnome? Even with libappindicator-gtk3 I have no tray icon and cannot close it, so I have to kill the process (or start it from the terminal and use ctrl-c to exit).

**Comment by Pointedstick** [comment] 2019-02-23 17:39
This is working properly for me now in KDE Plasma 5.15 with Riot 1.0.1. Can anyone confirm?

**Comment by akontsevich** [comment] 2019-02-23 17:43
@Pointedstick, what works for You? For me in KDE Plasma 5.15 with Riot 1.0.1 works only with right  mouse click - opens context menu, left mouse to show main window does not work.

**Comment by z3ntu** [comment] 2019-02-23 18:08
Both works for me with Plasma 5.15.1 and Riot 1.0.1 on Arch Linux

**Comment by ArchangeGabriel** [comment] 2019-02-23 18:59
With or without appindicator?

**Comment by akontsevich** [comment] 2019-02-23 19:22
Probably they does not use libappindicator. Does not work for me with libappindicator1 - forced to use for acestreamengine. Many distributions use patched libappindicator, hope openSUSE will patch or replace it as well.

**Comment by z3ntu** [comment] 2019-02-23 19:29
I do not have appindicator installed (only the gtk2 version)

**Comment by ArchangeGabriel** [comment] 2019-02-23 20:40
@akontsevich Then your issue is https://bugs.archlinux.org/task/59652.

**Comment by dos1** [comment] 2019-04-25 19:38
The correct way to have system tray icon properly working is to use Electron 5.0 or later and have libappindicator installed (but making sure that it doesn't use any patches that actually break it, like it's the case with Arch right now). Also, the app itself shouldn't have any special behavior when it detects KDE, like scaling down the icon to 22x22 - this was "helping" with old buggy Electron, but now (>= 5.0) it just makes the icon blurry.

There were multiple bugs in various places that were hindering the usability of systray icons in Electron apps, so you have to make sure all of these pieces are covered.

**Comment by 532910** [comment] 2019-04-25 19:42
```
% dpkg -l | grep libappindicator   
ii  gir1.2-appindicator3-0.1:amd64        0.4.92-7                             amd64        Typelib files for libappindicator3-1
ii  libappindicator1:amd64                0.4.92-7                             amd64        allow applications to export a menu into the panel
ii  libappindicator3-1:amd64              0.4.92-7                             amd64        allow applications to export a menu into the panel -- GTK3 version
```

**Comment by dos1** [comment] 2019-04-25 19:46
@532910 Your issue seems to be separate and I'd suspect a bug in Enlightenment there. Do other, non-electron apps that use libappindicator work with E?

**Comment by 532910** [comment] 2019-04-25 20:01
xfce4-panel: no icon
trayer: no icon
but volumeicon-alsa works everywhere

**Comment by dos1** [comment] 2019-04-25 20:08
Neither trayer nor xfce4-panel don't seem to support indicators, so as soon as there's any registrar running it's expected that there won't be any icon displayed there, as it won't fallback to XEmbed (and even if it fallbacks, it will be shown only in one panel at a time).

**Comment by t3chguy** [comment] 2022-05-06 18:56
Are people still experiencing this?

**Comment by ArchangeGabriel** [comment] 2022-06-05 08:29
It works for me both with and without libappindicator installed (though with libappindicator, both right and left click open the menu, while without it right click is the menu and left shows/hides element).

**Comment by weeman1337** [comment] 2022-06-10 08:05
Thank you for opening an issue. Unfortunately I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with @weeman1337  to let me know that it’s ready to be reopened.

**Closed by weeman1337** 2022-06-10 08:05 UTC
Labels: Z-Platform-Specific, P2, S-Major, A-Electron, A-Tray-Icon
