### ISSUE TITLE
Riot fails to verify one of my cross-signing signatures

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#14206] opened 2020-06-25 16:14 UTC
Last week (I think) I've added a new device to my account, which is an E2EE capable client (FluffyChat) that doesn't support interactive verification. I've therefore verified it using the legacy verification method (comparing keys).

I'm seeing this device as verified on my account, but other people who have verified me in the past now see this device as not trusted. I've managed to reproduce it with an account on another homeserver I own, and my user on that other homeserver indeed sees FluffyChat as not trusted after doing the cross-signing verification dance.

I'm pretty sure this isn't a server-side bug given I can see the cross-signature on FluffyChat's device in Riot for my user on that other homeserver.

FluffyChat's device ID on my account (`@brendan:abolivier.bzh`) is `STQFFXWFAK`.

I'm fine with providing keys and signatures through PMs if necessary. ~I'll also rageshake from the Riot session I've used to do the manual verification~ (done).

The manual verification was done on whatever the current version of `riot.im/develop` was at the time.

**Comment by babolivier** [comment] 2020-06-25 16:18
For what it's worth, it seems like a regression to me given I've done the manual verification for another client in the past and it was showing as verified to others (and other people told me they did the same thing in the past and it worked as well).

**Comment by jryans** [comment] 2020-06-30 12:56
Unsure what the precise problem is so far... As part of investigating this, @babolivier and I verified each other just now, and all of his sessions appear verified for me.

**Comment by babolivier** [comment] 2020-06-30 13:08
FWIW @anoadragon453 is still seeing that device as untrusted, despite running the latest Synapse and forcing his HS to resync my device list from mine.

**Comment by babolivier** [comment] 2020-06-30 13:24
Just to eliminate the possibility that this is a federation bug, the content for that device seems to be the same on both my test homeserver and matrix.org (checking there since that's where Ryan's account lives).

I did notice, though, that my labs homeserver seems to be lacking some historical cross-signing keys for my personal account that matrix.org has, __however__ @anoadragon453's homeserver also seems to have them.

So it doesn't seem to be e.g. the HS lacking data about my devices or something similar.

**Comment by jryans** [comment] 2021-04-13 12:12
I wonder if @babolivier ever found a resolution to this...?

**Comment by babolivier** [comment] 2021-04-13 12:14
No, and I can't repro it anymore because I've since logged out of that FluffyChat session (and successfully verified the new one using FluffyChat's interactive verification support that's been added in the meantime).

**Comment by jryans** [comment] 2021-04-19 17:11
Hmm, okay. I don't really know what to do if you can't reproduce it, so for now I'll close this.

**Closed by jryans** 2021-04-19 17:11 UTC
Labels: A-E2EE-Cross-Signing, T-Other
