### ISSUE TITLE
Include full timestamp and make more readable when selecting and copying messages from Element

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#15254] opened 2020-09-22 10:19 UTC
# Is your suggestion related to a problem? Please describe.
Copying a conversation from Element is annoying and requires a lot of manual formatting.

Currently, when you select and copy
<img width="801" alt="Screen Shot 2020-09-22 at 10 32 41 AM" src="https://user-images.githubusercontent.com/19155609/93866313-6617a480-fcbf-11ea-9dee-e0dc630a1c18.png">

You get this
<img width="542" alt="Screen Shot 2020-09-22 at 10 33 02 AM" src="https://user-images.githubusercontent.com/19155609/93866348-6dd74900-fcbf-11ea-8959-80c287498085.png">

# Describe the solution you'd like
Each message should have the full time stamp on it, and ideally a couple extra line breaks or something. So look something like this when pasted into a text editor:
```
Today - Tue Sep 22 2020

Tue, Sep 22 2020 10:31:47 BST
twily
Suspendisse interdum consectetur libero id


Tue, Sep 22 2020 10:31:55 BST
twilight
Eget gravida cum sociis natoque penatibus


Tue, Sep 22 2020 10:31:59 BST
twily
Amet consectetur adipiscing elit ut


Tue, Sep 22 2020 10:32:03 BST
twilight
Convallis a cras semper auctor neque


Tue, Sep 22 2020 10:32:06 BST
twily
Odio tempor orci dapibus ultrices in


Tue, Sep 22 2020 10:32:10 BST
twilight
Habitant morbi tristique senectus et netus et malesuada fames


Tue, Sep 22 2020 10:32:13 BST
twily
Vitae nunc sed velit dignissim sodales ut eu sem


Tue, Sep 22 2020 10:32:16 BST
twilight
Amet massa vitae tortor condimentum lacinia quis vel eros donec


Tue, Sep 22 2020 10:32:21 BST
twily
Velit euismod in pellentesque massa placerat duis ultricies
```

The date, and username should be included on every message, including when there are several messages in a row from the same user.

# Describe alternatives you've considered
I could go and pull this information from the database, but that is a dirty solution and does not work for non-technical users. So, no alternatives comes to mind, unless there are some Element and/or browser tricks I do not know about. 

# Additional context
I do this semi frequently for customer work, documentation etc. And I spend a lot of time manually formatting text copied from Element

## While I'm at suggesting copy features:
<img width="641" alt="Screen Shot 2020-09-22 at 11 11 19 AM" src="https://user-images.githubusercontent.com/19155609/93869911-649cab00-fcc4-11ea-92a8-e9643d6346f4.png">

When quotes are copied, you currently get:
```
twily
In metus vulputate eu scelerisque felis imperdiet proin fermentum leo
Praesent elementum facilisis leo vel fringilla est
twilight

twily

    In metus vulputate eu scelerisque felis imperdiet proin fermentum leo

Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin
```

Should look something like:
```
Tue, Sep 22 2020 11:10:29 BST
twily
In metus vulputate eu scelerisque felis imperdiet proin fermentum leo


Tue, Sep 22 2020 11:10:43 BST
twily
Praesent elementum facilisis leo vel fringilla est


Tue, Sep 22 2020 11:10:49 BST
twilight
> Tue, Sep 22 2020 11:10:29 BST
> twily
>    In metus vulputate eu scelerisque felis imperdiet proin fermentum leo
Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin
```

Code blocks are just copied as normal text:
```
twily
Fames ac turpis egestas sed tempus urna
Enim facilisis gravida neque convallis a cras semper auctor
```

Should include the backticks:
```
Tue, Sep 22 2020 10:54:27 BST
twily
\``` (without the backslash, thanks GH formatter)
Fames ac turpis egestas sed tempus urna
Enim facilisis gravida neque convallis a cras semper auctor
\```
```

**Comment by Twi1ightSparkle** [comment] 2020-09-22 10:23
Maybe also include the full Matrix ID on the name on every message

**Comment by t3chguy** [comment] 2020-09-22 10:24
Duplicate of https://github.com/vector-im/element-web/issues/154

**Closed by t3chguy** 2020-09-22 10:24 UTC
Labels: suggestion
