### ISSUE TITLE
ability to add alt text to images

### ISSUE THREAD

**Issue by teslasmoustache** [vector-im/element-web#19890] opened 2021-11-25 04:46 UTC
#### What would you like to do?
add image descriptions in the image upload dialog

#### Why would you like to do it?
Accessibility. The alt text of an image is the standard area where image descriptions are added for people who use screen readers.

#### How would you like to achieve it?
in the image upload dialog, there should be a text field for image descriptions. It should be labeled something like "Describe for the visually impaired" so it's clear to the user exactly what it's for.

### Have you considered any alternatives?

typing an image description in a separate message after the image is already uploaded.

We don't yet have the ability to send text and images at the same time, so this is really the only alternative at the moment.

### Additional context

This might also be a useful feature for people who use Matrix in a command line environment.

**Comment by SimonBrandner** [comment] 2021-11-25 08:43
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/17617, https://github.com/vector-im/roadmap/issues/13, https://github.com/vector-im/element-web/issues/11083

**Closed by SimonBrandner** 2021-11-25 08:43 UTC
Labels: T-Enhancement
