### ISSUE TITLE
Adding an HTML tag breaks links rendering

### ISSUE THREAD

**Issue by le-jun** [vector-im/element-web#23025] opened 2022-08-08 05:57 UTC
### Steps to reproduce

1. Send a message which includes a bracketed link in Markdown format.
2. Modify the message and add an HTML tag anywhere

![image](https://user-images.githubusercontent.com/88536727/183348458-a98d1307-411c-45e4-81fc-9b1b845c2551.png)

#### What did you expect?

Modification of HTML tagged strings only (Don’t know if that’s supported).

#### What happened instead?

Links’s appearance only where modified and showed some HTML tags

### Operating system

xUbuntu

### Application version

Version Element : 1.11.2 Version Olm : 3.2.12

### How did you install the app?

Official package from https://element.io/get-started

### Homeserver

tedomum.net

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-08-08 08:53
Duplicate of https://github.com/vector-im/element-web/issues/22953

**Closed by t3chguy** 2022-08-08 08:53 UTC
Labels: T-Defect
