### ISSUE TITLE
Visual notification dot not shown when windows taskbar is set to "Always, hide labels"

### ISSUE THREAD

**Issue by aleld** [vector-im/element-web#19986] opened 2021-12-01 12:05 UTC
### Steps to reproduce

1. Set windows taskbar to "Always hide labels" in the taskbar settings
2. Get a notification without reading it

When taskbar set to "Never"  combine taskbar buttons:
![grafik](https://user-images.githubusercontent.com/89131829/144231383-1d9c6b6b-a12c-4cbb-aa63-2d9fe96b864f.png)

When taskbar set to Always, hide labels"
![grafik](https://user-images.githubusercontent.com/89131829/144231424-69fa71b4-37fc-48f0-8245-fc81f3c8c772.png)

#### What did you expect?

Show red dot with number of unread meassages in it

#### What happened instead?

No red dot is shown

### Operating system

Windows 10

### Application version

Element version: 1.9.5 Olm version: 3.2.3

### How did you install the app?

From https://element.io/get-started

### Will you send logs?

No

**Comment by t3chguy** [comment] 2021-12-01 12:25
Duplicate of https://github.com/vector-im/element-web/issues/14033

**Closed by t3chguy** 2021-12-01 12:25 UTC
Labels: T-Defect
