### ISSUE TITLE
OS emoji used throughout app

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25692] opened 2023-06-30 15:01 UTC
### Steps to reproduce

1. Open nightly
2. Observe non-twemoji 

#### What did you expect?

twemoji

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/0d8e23bf-6b32-4490-8811-fc5c5df11050)

These would be from Windows

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023063001 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by germain-gg** [comment] 2023-07-03 08:24
Duplicate of https://github.com/vector-im/element-web/issues/25686

**Closed by germain-gg** 2023-07-03 08:24 UTC
Labels: T-Defect, X-Regression, X-Release-Blocker
