### ISSUE TITLE
Linux Desktop: Clicking the icon should open the application window

### ISSUE THREAD

**Issue by heini** [vector-im/element-web#15067] opened 2020-08-29 15:12 UTC
**Is your suggestion related to a problem? Please describe.**
I'm always frustrated when I click the system tray icon on my Linux desktop and the app doesn't open (as it does on Windows). Instead I first need to select a menu item to open the app. The menu should appear on right-clicking only.

**Describe the solution you'd like**
The app window should open on left-click on the tray icon while the menu should open on right-click, which is standard KDE behaviour.

**Describe alternatives you've considered**
I don't see any.

**Comment by t3chguy** [comment] 2020-08-29 15:20
That depends on which tray path is used by electron. The behaviour you described is the intentional one and happens with some tray icon implementations. Iirc libappindicator and SNI

**Comment by heini** [comment] 2020-08-29 15:26
It may well be that it's intentional, i don't know. But that's not the point. It behaves different than other KDE apps (but is in good company here with other IM apps like Jami or Keybase, which show the same weird behavior) and that shouldn't be. As written above, even the Windows version does it right...

**Comment by t3chguy** [comment] 2020-08-29 15:27
I'm saying the desired behaviour you described is intentional.

**Comment by t3chguy** [comment] 2020-08-29 15:28
Try installing libappindicator3 or SNI

**Comment by heini** [comment] 2020-08-29 15:29
Ah, OK. Misunderstood it. Thought you meant the current behaviour.

**Comment by heini** [comment] 2020-08-29 15:34
Did a quick check. They are both installed.

**Comment by t3chguy** [comment] 2020-08-29 17:21
Duplicate of https://github.com/vector-im/element-web/issues/11772

**Closed by t3chguy** 2020-08-29 17:21 UTC
Labels: suggestion
