### ISSUE TITLE
Feature request: export chat logs

### ISSUE THREAD

**Issue by sunnyolives** [vector-im/element-web#2630] opened 2016-11-22 15:17 UTC
A very useful feature. I find it strange it isn't already implemented, unless I am bad at searching.

Alternatives
* specify time range
* possibly, specify file format or formatting

What do you think?

**Comment by ara4n** [comment] 2016-11-25 22:58
yup, i find myself wanting this repeatedly too. #2129 is close to it, but would be nice to just be able to say "download room as log".

**Comment by Half-Shot** [comment] 2017-02-22 02:25
I was once toying with the idea of selecting some of the chat, and hitting some kind of key combo/ menu option to copy a IRC style log into the clipboard?

**Comment by ara4n** [comment] 2017-02-22 08:38
This would also be cool!

**Comment by Nadrieril** [comment] 2017-04-08 19:32
Any plans to do this ?

**Comment by ara4n** [comment] 2017-04-08 20:32
as a p2 feature req this is basically stuck behind everything tagged as p1, which is around 200 issues right now. but given this is FOSS anyone is welcome to contribute it!

**Comment by clopez** [comment] 2017-04-20 09:06
I find the search feature of matrix/riot pretty inefficient for an advanced user like me that is used to do greps (even using regexs) over simple text files.

So, being unable to extract simple plain text logs from my matrix conversations (both private or in rooms) is a serious regression for me, when compared with my previous experience with Jabber or IRC clients.

**Comment by ara4n** [comment] 2017-04-20 12:06
https://gitlab.com/argit/matrix-recorder is a good workaround for this for now (and even does e2e if you desire, albeit storing it unencrypted).  We could also build something like this into riot itself in future.

**Comment by MaskyS** [comment] 2018-03-08 17:10
+1 for this feature request

**Comment by kosherpork** [comment] 2018-05-10 01:49
+1

**Comment by intizarabe** [comment] 2018-05-10 03:59
I also need to inform that two my accounts at gmail and yahoo been locked and i have no access to them long time ago. I also worry that my citizen auth key was stored at that acc. Maybe anyone could help if you have my chats and so powerfullm

**Comment by sanecito** [comment] 2018-05-26 21:12
Being able to export IRC-like logs would be an extremely useful feature to have for quickly copying chat logs for reoccuring FOSS project meetings to archive somewhere. Glad to see it's now labelled p1 instead of p2.

**Comment by Valodim** [comment] 2018-06-21 10:37
I miss this feature a lot and I'm tempted to give this a go. However the riot-web code base looks *very* daunting, especially with the weird separation of sdk and actual app. Can someone who has an overview of the code base give a rough plan of the relevant cutpoints where this would be implemented in riot-web?

**Comment by t3chguy** [comment] 2018-06-21 10:38
@Valodim all the code would be in https://github.com/matrix-org/matrix-react-sdk/

**Comment by ilu33** [comment] 2018-06-27 20:09
This feature is also required by GDPR. I think GDPR favours structured formats, json and the like, but I don't mind whether it's txt or anything else. 
But besides the legal stuff it would be a really really useful feature. Copying the history manually is a p.i.t.a.. 
Also GDPR and other valid reasons convince server operators to delete older history (we are discussing something in between 3-6 month atm). So whatever is not copied gets lost.
So if anybody picks this up it would be great.

**Comment by t3chguy** [comment] 2018-06-27 21:17
@ilu33 https://matrix.org/docs/projects/other/matrix-recorder.html
riot-web doesn't store the data so it doesn't have to be able to export it

**Comment by t3chguy** [comment] 2018-06-27 22:30
Yet on the other hand you run into much bigger limitations in webapps in the sizes of files you can generate before the browser kills you

**Comment by ilu33** [comment] 2018-06-27 22:35
hm - limit the amount of lines?

It seems that matrix-recorder has a similar problem (ORG.MATRIX.JSSDK_TIMEOUT)?

**Comment by makedir** [comment] 2018-07-08 13:00
Why is there nothing done since ticket open of Nov 22, 2016? The Riot client fronted should have a simple user-friendly basic chat export for admins, just copy chat from 1.1.2018 to 1.2.2018 in channel x to clipboard.

**Comment by Nadrieril** [comment] 2018-07-09 20:38
@makedir It does indeed seem like a very useful feature, but please keep it civil. Developers have their own priorities. If you believe it is not very hard, why not give it a go ? Contributing to a super cool project like Riot is a fun experience !

**Comment by Eldovar** [comment] 2018-09-22 05:28
What Thibault @thiblahute has programmed is for sure useful, but only for programmers who know how to install and deal with that software.

An export of the chatlog to simple text is essential for example for group meetings, to be  able to write the minutes after the meeting. Therefore:
**Please, please, please** implement a possibility to export the chatlog to a simple text file.
Thank you very much.

**Comment by lapineige** [comment] 2019-01-15 18:55
> JFYI, @thiblahute was developed a simple but useful command line for this:
> https://gitlab.gnome.org/thiblahute/matrix-dl

@psaavedra is it working on encrypted channels too ?

Thanks for this tool BTW.


> Please, please, please implement a possibility to export the chatlog to a simple text file.

Allowing to do this in a convenient way for every users sounds like an important option to me - at least for backup before deleting the history, or exporting to other channel, or searching in an encrypted channel (as it not working right now), and so on.

**Comment by Grg-M** [comment] 2019-02-24 12:02
@thiblahute, @psaavedra when I try to run the command line tool to dump log for unencrypted named rooms I receive this error:
`raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

instead for encrypted rooms I receive this error: 
`event not found`
any suggestion on how to debug these?

Being able to export the logs would be extremely useful.

**Comment by Nigamanth96** [comment] 2019-04-19 12:02
@psaavedra , I do not understand what the matrix URL is. Can you please clarify what matrix.example.com is? I mean, is the 'example' in the URL the channel name?
I get a lot of exceptions while doing the same but replacing the 'example' with the channel I've created. BTW there is nothing called 'channel', but only rooms right?

**Comment by Nigamanth96** [comment] 2019-04-19 12:08
![image](https://user-images.githubusercontent.com/49784982/56423481-e0bde280-62c9-11e9-94bc-5ecbd9d6c047.png)
I get an exception like this.

**Comment by Nigamanth96** [comment] 2019-04-19 12:09
I've got no idea what URL is the right one

**Comment by JimmyCushnie** [comment] 2019-04-24 06:13
Really sorry if this is the wrong way to ask for help, but it is absolutely critical that I download this Matrix chat room and I don't know where else to go. I'm trying to use @thiblahute's tool, like so:

```
python matrix-dl --matrix-url https://riot.im/ [my username] "[room name]"
```

then I enter my password. Then I get this error:

```
[my username] connecting to https://riot.im/
Traceback (most recent call last):
  File "matrix-dl", line 164, in <module>
    getter.run()
  File "matrix-dl", line 80, in run
    password=self.password)
  File "C:\_Programs\Python\lib\site-packages\matrix_client-0.3.2-py3.7.egg\matrix_client\client.py", line 249, in login_with_password
    return self.login(username, password, limit, sync=True)
  File "C:\_Programs\Python\lib\site-packages\matrix_client-0.3.2-py3.7.egg\matrix_client\client.py", line 270, in login
    "m.login.password", user=username, password=password, device_id=device_id
  File "C:\_Programs\Python\lib\site-packages\matrix_client-0.3.2-py3.7.egg\matrix_client\api.py", line 160, in login
    return self._send("POST", "/login", content)
  File "C:\_Programs\Python\lib\site-packages\matrix_client-0.3.2-py3.7.egg\matrix_client\api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 404: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /_matrix/client/r0/login was not found on this server.</p>
</body></html>
```

What am I doing wrong?

**Comment by aaronraimist** [comment] 2019-04-24 06:19
In the future you should open an issue on that repo https://gitlab.gnome.org/thiblahute/matrix-dl, not here. I assume the problem is Riot is not a matrix server. The server is the bit at the end of your username. So if my account was @aaron:matrix.org, https://matrix.org would be the server or as they call it matrix-url.

No need to reply thanks if that fixed it. If it didn’t go open an issue on https://gitlab.gnome.org/thiblahute/matrix-dl.

**Comment by grahamperrin** [comment] 2019-04-28 19:17
> … backup before deleting the history, …

Or (edge case) before rejoining a room from which you have been kicked through no fault of your own. 

An example of history lost after rejoining: https://github.com/matrix-org/synapse/issues/2212#issuecomment-487407191

**Comment by End-to-End-is-the-way** [comment] 2019-08-12 19:17
I also would love to see this feature...

**Comment by makedir** [comment] 2019-08-27 01:37
> Is there any way to do that? I tried what's on https://gitlab.gnome.org/thiblahute/matrix-dl but doesn't work for me. I opened a issue there but seems like development there is inactive.

the method works fine if you do it correctly, it is really annoying though. and the matrid-dl client doesnt export all ASCII characters correctly.

**Comment by ara4n** [comment] 2019-09-01 19:00
i’ve been thinking about this while implementing a smarter clipboard for riot-web. I realised i don’t actually necessarily understand what the 63 people upvoting are after here. is it:

1. 👍 - ability to export logs from Riot/Web for a given room(s) as a big lump of static HTML, suitable for printing or grepping or sharing out of band? This is hard, given public rooms can easily have millions of messages, and you would probably run out of RAM (or bandwidth or time) trying to export them. But we could implement it with a date range or msgcount limit.
2. ❤️ - ability for Riot/Desktop to save all the messages it sees on disk as HTML or plain text, a bit like an IRC client would, spidering to fill in any gaps in the logs?
3. 🚀 - actually, pantalaimon / matrix-recorder / matrix-dl etc actually have solved this already for my use case.

Seshat may help with option 2 in the near future. Meanwhile, i may be able to tweak the clipboard code to easily support option 1.

Please vote by upvoting this msg with the matching emoji so I can get more of a handle.

**Comment by matheusfillipe** [comment] 2019-09-01 19:08
> i’ve been thinking about this while implementing a smarter clipboard for riot-web. I realised i don’t actually necessarily understand what the 63 people upvoting are after here. is it:
> 
>     1. +1 - ability to export logs from Riot/Web for a given room(s) as a big lump of static HTML, suitable for printing or grepping or sharing out of band? This is hard, given public rooms can easily have millions of messages, and you would probably run out of RAM (or bandwidth or time) trying to export them. But we could implement it with a date range or msgcount limit.
> 
>     2. heart - ability for Riot/Desktop to save all the messages it sees on disk as HTML or plain text, a bit like an IRC client would, spidering to fill in any gaps in the logs?
> 
>     3. rocket - actually, pantalaimon / matrix-recorder / matrix-dl etc actually have solved this already for my use case.
> 
> 
> Seshat may help with option 2 in the near future. Meanwhile, i may be able to tweak the clipboard code to easily support option 1.
> 
> Please vote by upvoting this msg with the matching emoji so I can get more of a handle.

What would be perfect to me is option 2 :heart: 

I wasn't able to check those you mentioned in option 3 but I will try it out now.... Still riot could maybe has such option.

**Comment by makedir** [comment] 2019-09-01 19:29
Isnt it obvious what people want? A simple per chat room export button with start date and end date, export al chat messages from start date to end date and give it as html or txt or zip file.

**Comment by JimmyCushnie** [comment] 2019-09-02 00:02
I want to export personal chats with only thousands to tens of thousands of messages, so running out of ram isn't a concern for me. But even if it was, "you have to use disk as ram to export chats" is better than "you can't export chats at all"

**Comment by ilu33** [comment] 2019-09-02 22:29
Per channel, with start and end date and probably a reasonable msgcount limit. If the room is big or old, people would have to maneuver around this limit by selecting periodic chunks. 

Maybe give format options, xml or json would work too. And thanks for coming back to this.

**Comment by rubo77** [comment] 2019-09-22 08:18
No 1 👍, but it Schild be possible to select multiple rooms at once

**Comment by melikyuksel** [comment] 2019-11-03 21:11
Why not both? Export on demand, and save all logs/events to disk as plaintext logs for posterity.

**Comment by 1ykos** [comment] 2019-11-04 23:24
I just noticed I spammed Matrix with lots of pictures (1.5MB each) and would like to help you clean up, but scrolling up takes around 10 minutes (I used a heavy item on the pgup). It would be so great if this process was easier, that is exporting and deleting chatrooms.

**Comment by arthurlutz** [comment] 2019-12-16 10:08
Does the integration of search through seshat which claims to support E2EE rooms https://github.com/vector-im/riot-web/pull/11125 change this feature request ? Could we use the indexed data collected there ?

**Comment by martindale** [comment] 2020-03-17 21:56
Allow for import as well! 👍

**Comment by arthurlutz** [comment] 2020-03-17 22:00
@martindale indeed. this would help unload the high traffic on matrix.org by enabling a migration to another (self-hosted?) server.

**Comment by aaronraimist** [comment] 2020-03-17 23:19
@arthurlutz I assume you are aware but you can already migrate to another server (that’s kind of the whole point of Matrix, that no one server owns a room). Just join the room from your new server. If you want the full history you can just scroll up in the room and then your new server will have a full copy of the room. (Yes there should probably be a button in Riot that performs both steps, joins a room and requests the full history. I just filed https://github.com/vector-im/riot-web/issues/12766 for that.)

**Comment by KopfKrieg** [comment] 2020-03-17 23:24
> If you want the full history you can just scroll up in the room and then your new server will have a full copy of the room.

That depends on your room settings and is not always possible. But thanks for filing the issue, hope it can be resolved. AFAIK the plan is to use a UUID derived from a private key and the server just being something you can change as you wish.

**Comment by protist** [comment] 2020-03-23 08:28
Has anyone actually managed to export E2E encrypted chats successfully? With COVID-19, there are many of us working from home now, and presumably many looking for new chat platforms. Without exported chat logs, Matrix/Riot are not viable options for me.

I've checked out the existing export options. matrix-dl [doesn't appear](https://gitlab.gnome.org/thiblahute/matrix-dl/issues/2) to export encrypted rooms. I can't even get matrix-recorder to build, and it looks like it may have been abandoned anyway. pantalaimon was mentioned above, but it's unclear to me how to export chat logs with this.

**Comment by JimmyCushnie** [comment] 2020-03-23 08:30
I tried a number of approaches several months ago but I ended up giving up. If it's presently possible to export E2E chats, it is really really difficult to do so and it needs to be more accessible.

**Comment by protist** [comment] 2020-03-23 08:31
Thanks @JimmyCushnie. I might have to go to a closed-source platform for now then.

**Comment by lapineige** [comment] 2020-03-23 10:26
Will the future "daemon" (I don't know if it's the correct name) that will allow to search an encrypted channel be able to export chat logs ?
I thought I've seen that information somewhere, yet I can't find it.

**Comment by t3chguy** [comment] 2020-03-23 10:39
Seshat will only be indexing encrypted rooms, it could possibly be extended to exporting but it isn't in place atm.

**Comment by poljar** [comment] 2020-03-23 10:50
There is functionality to export file based events (m.image, m.video, etc...) generalizing this to export all events for a room or all events for all rooms isn't that hard. How and if this should be exposed in Riot is another question.

**Comment by arthurlutz** [comment] 2020-03-23 14:20
@poljar good news ! Could you point to use the "export file based events" functionality or documentation ?

**Comment by t3chguy** [comment] 2020-03-23 14:23
Its the source for the File Panel on seshat-enabled riot-desktop builds.

**Comment by poljar** [comment] 2020-03-23 14:49
If you mean developer docs those can be found [here](https://docs.rs/seshat/1.2.0/seshat/struct.Connection.html#method.load_file_events) for the Rust side of things and [here](https://github.com/matrix-org/seshat/blob/master/seshat-node/lib/index.js#L458) for the Javascript side of things.

As for Riot like @t3chguy mentioned, it's used for the File Panel.

**Comment by eMPee584** [comment] 2020-04-08 07:55
It would already help **if one could PRINT the message pane** of a room.. at the moment that seems neither possible in web nor in desktop version.. The latter does not allow print, the former just spits out the room overview and room members pane..

**Comment by Enteneller2017** [comment] 2020-05-08 09:41
I would also like this feature - even above everything else that is not yet implemented.
I've also voted here: [https://github.com/vector-im/riot-web/issues/2630#issuecomment-526944604](url)

**Comment by matrixuser123** [comment] 2020-05-16 08:30
In Germany, Blackberry holds a patent for exporting chats. That's because Whatsapp has removed this feature from their version for Germany (German link: https://t3n.de/news/whatsapp-kein-chat-export-mehr-1238327/). 
Could that be a problem if this feature get implemented into Riot?

**Comment by afranke** [comment] 2020-05-16 10:55
That case is about sending the logs to a third party via email while this feature request is about saving to a local file. Unrelated.

**Comment by martindale** [comment] 2020-05-16 19:50
> That case is about sending the logs to a third party via email while this feature request is about saving to a local file. Unrelated.

Agree.  It would be ridiculous to deprive users of the ability to archive their own content for this reason, law or not.

**Comment by tredondo** [comment] 2020-07-21 20:53
> In Germany, Blackberry holds a patent for exporting chats.

IANAL but you can't patent an idea. The open-source Pidgin chat client has had export for 15+ years.

**Comment by 1over137** [comment] 2020-10-08 04:18
Anyone working on this now? It's been almost 4 years. matrix-recorder works for now but it lacks the ability to record older encrypted messages and seems to have been abandoned.

**Comment by arthurlutz** [comment] 2020-10-08 07:28
I think this feature is still needed in Element, but while it's not I successfully exported logs and media using https://github.com/russelldavies/matrix-archive

**Comment by xaur** [comment] 2020-11-08 18:34
Let me reformulate how bad the lack of offline history is, in hopes to increase its priority.

Imagine we have a community using a chat system not only to share cat picz but to build something great towards a big goal. Like an open source or an open hardware project. In the process we share valuable **knowledge** and ideas in this chat. In other words, we rely on chat for something serious.

Now consider the same scenario for two systems.

A: Any decade-old IRC or XMPP client:

1. enable saving of chat logs to local text files
2. chat with your community for years, accumulating knowledge
3. the single server we all used is gone (for whatever reason)

Result: a lot of members have replicas of community's entire chat history and can cooperate to quickly respawn it in a new location.

B: Matrix flagship client (Element) in 2020:

1. chat with your community for years, accumulating knowledge
2. the single server we all used is gone (for whatever reason)

Result: there is a high chance that everything is lost. If we are lucky, admins of participating homeservers will help to recover _some_ of the lost content. Now we have to scratch our heads: how does s2s replication work? Do homeservers replicate the entirety of _all_ rooms or only slices of rooms relevant to homeserver's users?

I didn't study other Matrix clients but I assume it is the same for many.

Now I open matrix.org:

> An open network for secure, **decentralized** communication

and

> Matrix is really a decentralised conversation store rather than a messaging protocol.

and so on.

Considering the practical difficulty of running homeservers let me ask a simple question: What is more decentralized?

a. 1 central IRC server + 10 always-online users that save chat logs and publish them somewhere + 50 users who periodically sync them

b. 1-3 Matrix homeservers you will find in small communities + **0** users saving chat logs

I should also mention that in the IRC scenario it is practically impossible to delete messages from users' local files. In Matrix it is possible to delete messages and while I hope the database is append-only, I'm not sure it is possible for users to recover deleted messages in all cases.

Closing my mini-rant, Matrix is the best open-source, actively-developed, semi-decentralized, self-hosted, E2EE-enabled chat system I am aware of. I highly respect what Matrix is doing and I am very thankful that we now have a decent alternative to Slack/Discord/Telegram where freedom and sovereignty mean something.

The point of this message is to make a case that from a _user perspective_, as it is today, Matrix is **less decentralized** than IRC. I don't want to sound too negative, but such system is _training_ end users to rely on servers and believe/hope everything will be fine. And all of it comes from one missing feature: easy-to-save offline history that keeps a copy of the knowledge the community generates every day.

I kindly ask to reconsider the priority of offline history.

Thank you for your attention.

**Comment by xaur** [comment] 2020-11-08 18:39
Speaking of how to implement it, I suggest these steps:

- command-line tool that simply saves events of all rooms as local json files, e.g. 1 file per one day of events
  - subsequent invocations incrementally sync only what is missing
  - this tool alone will enable archivists to make rooms much more resilient to loss

- another command-line tool that reads these files, reads e2ee key file and renders local html files, again one per day of events

- add UI feature to Element to select rooms, date range, and retrieve a compressed archive that uses same formats as above

**Comment by Porkepix** [comment] 2020-11-08 18:50
>     * command-line tool that simply saves events of all rooms as local json files, e.g. 1 file per one day of events

Considering this is only a matter of output formatting, which can easily offer several choices, plain text can also be a good choice for greping through them :)

Speaking of experience, this issue is one of the only two that are a blocking one for me to consider switching from full IRC to Matrix instead: I hold years of IRC logs, which act as a complete part of my memory. Sometimes it's easier to remember the context where a link was given, a conversations happened rather than the content itself.

So here we are more on a personal matter than a project one, but these logs act as complete part of my memory, where, aside from the fact than, as suggested by xaur, it makes this memory rely on server, I also consider that a fancy UI won't ever achieve the power and flexibility good ol' greps & pipes can get you when you're used to those.

**Comment by xaur** [comment] 2020-11-08 19:01
> plain text can also be a good choice for greping through them :)

Even plaintext logs would be infinitely better than nothing. But the reason I suggest to keep original even jsons is because they carry more information. If you have original events, you can then render them as plaintext, but not the other way round.

matrix-archive project linked earlier looks like the most up-to-date solution so I suggested this feature in their repo: https://github.com/russelldavies/matrix-archive/issues/14

**Comment by MurzNN** [comment] 2020-11-25 13:51
"How to export / save chat logs" seems most popular questions in Element related chats. And, when I write another answer to this question, thought came to my mind: 
Before this feature will be implemented in Element itself, maybe add "placeholder" menu item to all Element's interfaces, that will suggest to use https://github.com/russelldavies/matrix-archive script for this task, as workaround?

**Comment by NukeManDan** [comment] 2020-12-24 20:21
I just found this handy tool: https://github.com/shawntabrizi/matrix-dl-csv

Export some or all of your channel histories to a csv with a specific start/end date.

**Comment by tredondo** [comment] 2021-01-12 09:43
I'm sorry, I'm just a random user using the default public Matrix server (I don't even know which one) to talk to my wife. Do these scripts even apply to us?

@MurzNN: your 3rd link is identical to the first on1
@NukeManDan: that tool says it's a fork ofr @MurzNN' #2 tool

**Comment by MurzNN** [comment] 2021-01-12 10:15
> @MurzNN: your 3rd link is identical to the first one
Third one must be https://gitlab.com/argit/matrix-recorder - I updated that post.

**Comment by guerby** [comment] 2021-01-21 14:07
As I'm surprised that matrix/element is about the only chat system I know that doesn't have save or archive chat feature, is there a roadmap item to add this feature?

**Comment by kshitijzutshi** [comment] 2021-03-10 09:06
Hi All,

I recently saw the project idea on the GSoC site for this year. I wanted to reach out to the mentor for this chat export idea @Michael (t3chguy). Can u pl reply to this thread or reach out?

Thanks
Kshitij Zutshi

**Comment by SimonBrandner** [comment] 2021-03-10 20:04
@kshitijzutshi, you have pinged the wrong person. 

@t3chguy, someone seems to be looking for you :D

**Comment by kshitijzutshi** [comment] 2021-03-16 02:44
> @kshitijzutshi, you have pinged the wrong person. 
> 
> @t3chguy, someone seems to be looking for you :D

No one has reverted back yet! 😅

**Comment by tawfiek** [comment] 2021-03-25 11:31
Do the export function should be in each room individually, or we should add an export button some where to make us able to export all chat logs once ?!
Maybe we can do both 😃

**Comment by SimonBrandner** [comment] 2021-03-25 11:55
I guess both would be ideal. _Personally_, I'd like it to be per-room. You'll have to write the code for that anyway, right?

**Comment by tawfiek** [comment] 2021-03-25 12:08
Yea I guess, I just wonder if exporting everything is possible from the performance perspective since we need to decrypt thousands maybe tens of thousands of events once.

**Comment by lapineige** [comment] 2021-03-25 12:10
I would say, if we have to choose, a per-room basis would be better.
Exporting everything including some non interesting (for archiving) rooms could be rather useless, resource expensive for the server, and maybe harder to process later on. And you can export every room thanks to that feature (even if it's longer to do).

**Comment by xaur** [comment] 2021-03-26 01:09
Export of room or all history is the only way to save it locally in web-based Element because browser can't write to arbitrary files.

The problem with "export" flows is you have to do it over and over if you want to have chat history locally and updated.

In Desktop version though, it is possible to implement a "Save Logs" feature that will just save all messages in the logs directory. Per-room toggles wouldn't hurt because I can join _a lot_ of rooms but only need to save history for some.

IRC and XMPP clients had this feature for decades and it allows to archive and search history quickly and locally, independent of the server.

**Comment by t3chguy** [comment] 2021-03-26 08:52
Element Desktop already locally stores history of all encrypted rooms inside Seshat for search

**Comment by AppTester7** [comment] 2021-03-26 10:18
at some point i had posted this link to merely 'highlight' the fact than a pre-existing third-party app for windows exists
that exports all chat logs (selected or all) for room and/or all DM's for discord
I had used the app many time myself, its beautiful imo

https://github.com/Tyrrrz/DiscordChatExporter/releases

I do hope that some devs contact the creator of this app and see if a collaberation between him and devs here can come to a
potentially working equvelant HTML chat Exporter for any/all matrix.org and related matrix rooms for Linux will come about

**Comment by AppTester7** [comment] 2021-03-26 10:21
also:
https://github.com/Tyrrrz/DiscordChatExporter

**Comment by tawfiek** [comment] 2021-03-26 10:32
This has nothing to do with matrix because Discord is not end to end encrypted as far as I know

**Comment by AppTester7** [comment] 2021-03-26 10:48
@tawfiek - I think you need to "re-read" what i said above, as you appear to have either made a mistake or incorrectly interpreted what i said

**Comment by eTomte** [comment] 2021-03-29 21:30
I'd like to add my voice to everyone else who has been saying this is a must have feature.  I've been limping along with Matrix-recorder, which I think is the best end-to-end third party solution so far.  Not only will it download the room data and they keys but it will also write a nice html archive of the room history.  Sadly, it it is no longer actively maintained and the current state of the code points to out of date dependencies.

As far as actively maintained third party solutions go, I think the best is matrix-archive.  However it lacks the ability to automatically download the room keys, meaning that it can't be easily automated.  It also downloads the raw JSON, meaning that the data can't be easily converted into something more readable such as HTML or even text.

**Comment by tawfiek** [comment] 2021-03-30 13:12
As `matrix-js-sdk` provide us useful APIs to use, I think using making third party will adding unnecessary  layer of complexity.

**Comment by tawfiek** [comment] 2021-03-30 13:15
or just use [this](https://matrix.org/docs/spec/client_server/latest#id267) paginated endpoint to get the messages decrypt it and return all decrypted data to the react sdk which can format it and make a downloadable file

**Comment by t3chguy** [comment] 2021-06-01 09:02
@vector-im/design for this we could do with

1. knowing where the trigger for exporting a room would be, e.g Room Settings?
2. what the export modal would look like, it'd need to have options to choose
  + export format (pdf, HTML, plain text etc)
  + date range / number of messages / maximum size
  + whether or not to include attachments
 3. How progress should be expressed, should it be on this modal or should it be background-able somehow whilst still retaining ability for the user to monitor progress
 4. What should the PDF / HTML output format look like, identical to the way the timeline looks? Should it respect light/dark theme? Should it be simplified/optimised for exporting somehow?

**Comment by jonathon-moore** [comment] 2021-06-01 10:08
Hello, could anyone please work on this? It is a pretty essential feature for an advanced app like element. This is the first time I'm ever requesting a feature on Git. This feature is present in almost every messaging app, and it is kind of a deal-breaker to me. I have just seen the above tools, but I don't know how to use the terminal. So, please integrate the feature into element itself.

I understand this can be a little difficult given that this project has 5000 issues but please consider prioritising this feature.

Thanks,
JM

**Comment by t3chguy** [comment] 2021-06-01 10:09
@jonathon-moore I advise you read the latest few comments/statuses.

It is being worked on. I just tasked the Design team with designing the UX for it.

![image](https://user-images.githubusercontent.com/2403652/120306536-da342e80-c2c9-11eb-9ed0-3b7dbf7fce9e.png)

**Comment by jonathon-moore** [comment] 2021-06-01 10:17
Thanks for the very swift response, @t3chguy. Sorry I didn't check them out. Can you tell when it will be rolled out to users? Also, is it for IOS or only desktop?

**Comment by t3chguy** [comment] 2021-06-01 10:19
This repo is only for the webapp and desktop app.
It will be rolled out when it is ready.

**Comment by Porkepix** [comment] 2021-06-01 10:22
> @jonathon-moore I advise you read the latest few comments/statuses.
> 
> It is being worked on. I just tasked the Design team with designing the UX for it.
> 
> ![image](https://user-images.githubusercontent.com/2403652/120306536-da342e80-c2c9-11eb-9ed0-3b7dbf7fce9e.png)

I missed the fact it was already be worked on. Aside from one shot exports like it seems to be talked about here, does it also consider complete live logs, or would this need another issue, if this would ever be considered?

For a bit of context, on the irc side I rely heavily on grepping through logs, which I think no graphical interface would ever be as efficient as using correctly greps and similar tools.

**Comment by t3chguy** [comment] 2021-06-01 10:23
Nope, this focus is for the webapp, the desktop app would inherit it for free. Webapps can't do such a thing so it is not being considered here.

**Comment by Porkepix** [comment] 2021-06-01 10:25
> Nope, this focus is for the webapp, the desktop app would inherit it for free. Webapps can't do such a thing so it is not being considered here.

What do you mean by "can't do such a thing", it's completely possible for the application to write in a plain text file what's being said in chans/conversations.

**Comment by t3chguy** [comment] 2021-06-01 10:29
A webapp, as in a Javascript app running in a supported web browser cannot write to your filesystem. It can (on explicit user interaction, e.g a download button) download a file but cannot just keep appending to a file.

https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API / https://web.dev/file-system-access/ would allow for the latter but the user's consent would not persist between sessions plus the API is still a working draft.

https://web.dev/file-system-access/#stored-file-or-directory-handles-and-permissions

**Comment by neobrain** [comment] 2021-06-01 10:31
> https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API / https://web.dev/file-system-access/ would allow for the latter but the user's consent would not persist between sessions plus the API is still a working draft.

Interesting, I was just about to propose this as an alternative here. Any chance this could be used for the Desktop app though? To me it's a very desirable feature to have a quickly searchable local backup without needing to export manually all the time, possibly more so than a dedicated export feature (though we ultimately might need both). Though I guess the FS API doesn't really get you anything over electron APIs, and then the biggest problem is to find someone to do the work...

Either way, thanks for pushing forward the work on this problem area!

**Comment by Porkepix** [comment] 2021-06-01 10:32
That's right for the Web version, but can't Electron have better accesses to filesystem as it's a dedicated app?

**Comment by t3chguy** [comment] 2021-06-01 10:34
Yes. The Electron app could do this.

> ...this focus is for the webapp, the desktop app would inherit it for free. Webapps can't do such a thing so it is not being considered here.

Nothing to prevent someone else from contributing an Element-Desktop specific variant which is able to keep an append only log. It is not the target of the Google Summer of Code project which will be closing out this issue.

**Comment by jaiwanth-v** [comment] 2021-06-05 08:13
@neobrain I'll work on integrating that feature as well if I find time, but it'd be better to create a separate issue to track it.

**Comment by xelayz** [comment] 2021-08-15 16:13
Is it still not possible to safe chat logs? This is so extremely annoying. I have now loaded all clients and I can't even mark all chat messages because Matrix so stupidly always reloads and then removes the previous messages. This is just bullshit. How can I back up large chats now?!

**Comment by piegamesde** [comment] 2021-08-15 17:29
@xelayz Please remain polite and constructive, and make sure you are adding value to the discussion. If you read the backlog, you can see plenty of messages describing their frustration about this feature missing, as well as viable workarounds.

**Comment by Sieboldianus** [comment] 2021-08-30 08:38
btw. here is the [link ](https://github.com/matrix-org/matrix-react-sdk/pull/6081)to the Pull Request for the export feature

**Closed** 2021-09-30 11:49 UTC
Labels: P1, A-Timeline, X-Needs-Design, T-Enhancement

**Comment by jakecoppinger** [comment] 2021-10-05 11:18
I've been following this for a while and just exported using https://develop.element.io/ - absolutely amazing stuff, thanks so much for your hard work!

**Comment by xelayz** [comment] 2021-10-05 11:24
> 
> 
> I've been following this for a while and just exported using https://develop.element.io/ - absolutely amazing stuff, thanks so much for your hard work!

Wow, thats perfect. Is this a new developer feature? Because no one told us before this is possible over the developer site.

**Comment by t3chguy** [comment] 2021-10-05 12:38
develop.element.io has stuff which will be included in the next release, so this will be in that next release.

**Comment by Felix-Pedro** [comment] 2023-09-25 01:47
hey, is there a way for admins to block users from doing this?

**Comment by piegamesde** [comment] 2023-09-25 14:40
@Felix-Pedro why should there be one? This smells like poor threat modelling to me honestly, but I'd be curious about your motivation for this.

**Comment by Felix-Pedro** [comment] 2023-09-29 14:12
@piegamesde is not a formal feature request or anything like that, I was playing with the app trying to understand how it works, I'm new to matrix so I was wondering if there would be any privacy concerns about exporting unencrypted copies of conversations, an option to encrypt would probably be nice too or like if the chat is encrypted the app could advise or admins could enforce encrypted exports or admin notification of exports, my primary source of concern was hypothetical, I was trying to list good usages for people that need some security on their conversations and thought about persecuted journalists, organizations, etc . And the risk of such export in this situation. But I could also be completely wrong about this.

**Comment by t3chguy** [comment] 2023-09-29 14:17
@Felix-Pedro in an open protocol you can never enforce any such block, someone could always modify their client to remove the block. The export just uses the same API as a user scrolling back through a room. A user could also just video record themselves scrolling all the way up as a form of export.

**Comment by Felix-Pedro** [comment] 2023-09-29 14:34
@t3chguy I thought of video issue too, but not the client modify, I understand that if one is decided to do so, and it has access to the chat, they will get the information extracted, but like banking apps that make your screenshot black when at some parts of the app, it creates a way to make it harder for unwilling leaks, just an option to encrypt the export or an advise from the app itself that this is an encrypted chat and would be better to encrypt the export too, would probably be enough, i' hadn't thought of this possibility before, although it's not a huge urgent issue I still think the option to encrypt and advice to do so would be a good feature. But I see that enforcing it does not prevent it from happening, and now I see too it does not make sense on the platform.

**Comment by t3chguy** [comment] 2023-09-29 14:35
> but like banking apps that make your screenshot black when at some parts of the app

Have you seen any banking *websites* which do this? After all this is a webapp and websites cannot blank your screen. Plus given its open source someone could again just modify and remove whatever hurdles you choose to add, or simply use a different Matrix client given there are hundreds.

**Comment by t3chguy** [comment] 2023-09-29 15:01
> also for the non technical user changing app codebase to remove a warning is not a simple nor worth task.

No they'll just google "How to get around Element export chat blocked" and someone with the ability will have a fork/alternative available to them. Security via obscurity is not something we're interested in.

**Comment by Felix-Pedro** [comment] 2023-09-29 15:16
For god sake how many times I ha to say that't is not a block, it's just a warning message, and check box yes encrypt or no do not encrypt.

**Comment by remram44** [comment] 2023-09-29 15:30
If you have a feature request, maybe open a new ticket?
