### ISSUE TITLE
Phantom call notifications(?)

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18454] opened 2021-08-09 09:02 UTC
### Steps to reproduce

Nor reliably reproducebale

### What happened?

We're getting reports of users being in a 1:1 call, hanging up, and then 10 minutes later the other party claims they had another incoming call from them.

### What did you expect?

No phantom calls

**Comment by dbkr** [comment] 2021-08-09 13:19
Another report suggests this is happening whenever element ios is opened after a call, showing each user that the other is calling them, so it's possible this could actually be am element-ios bug.

**Comment by turt2live** [comment] 2022-06-15 19:09
Duplicate of https://github.com/vector-im/element-web/issues/4607

**Closed by turt2live** 2022-06-15 19:09 UTC
Labels: T-Defect, S-Minor, A-VoIP, O-Uncommon
