### ISSUE TITLE
Messages stuck in "Sending your message..." state

### ISSUE THREAD

**Issue by julioromano** [vector-im/element-web#26498] opened 2023-11-03 07:51 UTC
### Steps to reproduce

1. Send a message in a thread
2. Nothing happens
3. After some time you see the messages you wanted to send appearing like in the screenshot below:
4. 
![92c3abfa-60e3-4d41-b830-6357399d12f7](https://github.com/vector-im/element-web/assets/1273124/406e5e03-3464-4c7b-b757-2bfa97589113)

#### What did you expect?
To send a message

#### What happened instead?
Message never got send, got stuck in "Sending your message..." state.

### Operating system

MacOS

### Application version

Element web R nightly

### How did you install the app?

https://packages.element.io/

### Homeserver

element.io

### Will you send logs?

Yes

https://github.com/matrix-org/element-web-rageshakes/issues/23029

**Comment by julioromano** [comment] 2023-11-03 07:52
I can confirm this happens to me almost on a daily basis now.

**Comment by richvdh** [comment] 2023-11-06 21:01
@ara4n also reported this on a non-element-R build, so I don't think it is Element-R specific.

**Comment by richvdh** [comment] 2023-11-06 21:02
I was able to reproduce something similar as follows:

 * Send a reaction to an event in a thread
 * Redact that reaction

**Comment by richvdh** [comment] 2023-11-06 21:02
Throwing this one back over the wall to the WAT

**Comment by andybalaam** [comment] 2023-11-07 11:22
Looks likely to have been caused by https://github.com/matrix-org/matrix-js-sdk/pull/3800

**Comment by andybalaam** [comment] 2023-11-07 11:52
The PR to revert is here: https://github.com/matrix-org/matrix-js-sdk/pull/3858

I will continue working on how to fix the problem before I close this issue.

**Comment by Johennes** [comment] 2023-11-07 12:37
Upgrading this to `O-Frequent` with the new steps to reproduce. This also makes it P1 and a release blocker (which it would _not_ have been with `O-Occasional`).

**Closed** 2023-11-07 14:18 UTC
Labels: T-Defect, X-Regression, S-Major, X-Release-Blocker, O-Frequent
