### ISSUE TITLE
Element white-screen-of-deaths when I hang up a Matrix-native 1:1 call

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#23783] opened 2022-11-17 16:53 UTC
### Steps to reproduce

1. Start a call with Anthony (or Jordan)
2. Chat away for a bit
3. Go to a different room to enable PIP
4. Hang up
5. WSOD

Then you have to Task Manager kill the background processes to _really_ terminate Element such that you can start it again cleanly.

#### What did you expect?
No WSOD

#### What happened instead?
WSOD

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2022111701 Olm version: 3.2.12

### How did you install the app?

Website

### Homeserver

lant.uk

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-11-17 17:24
Sounds like an OOM https://github.com/vector-im/element-web/issues/21541 - @lampholder can you check your system logs

**Comment by dbkr** [comment] 2022-11-18 17:27
Seems to be reproducible if the other side hangs up. I didn't have to enter pip mode.

**Comment by robintown** [comment] 2022-11-18 17:30
I can't reproduce this in Firefox, so I'm assuming this is specific to the desktop app

**Comment by dbkr** [comment] 2022-11-18 18:25
Renderer process crash:

```
* thread #22, name = 'WebRTC_Network', stop reason = EXC_BAD_ACCESS (code=1, address=0x1f)
    frame #0: 0x0000000110aaaea8 Electron Framework`node::SetTracingController(v8::TracingController*) + 1118000
Electron Framework`node::SetTracingController:
->  0x110aaaea8 <+1118000>: ldrb   w8, [x1, #0x17]
    0x110aaaeac <+1118004>: tbnz   w9, #0x1f, 0x110aaaec8    ; <+1118032>
    0x110aaaeb0 <+1118008>: tbnz   w8, #0x7, 0x110aaaf10     ; <+1118104>
    0x110aaaeb4 <+1118012>: ldr    q0, [x1]
Target 0: (Electron Helper (Renderer)) stopped.
(lldb) bt
* thread #22, name = 'WebRTC_Network', stop reason = EXC_BAD_ACCESS (code=1, address=0x1f)
  * frame #0: 0x0000000110aaaea8 Electron Framework`node::SetTracingController(v8::TracingController*) + 1118000
    frame #1: 0x000000010b09af68 Electron Framework`v8::CpuProfileNode::GetParent() const + 54092
    frame #2: 0x000000010b09af68 Electron Framework`v8::CpuProfileNode::GetParent() const + 54092
    frame #3: 0x000000010b0997d4 Electron Framework`v8::CpuProfileNode::GetParent() const + 48056
    frame #4: 0x000000010b098638 Electron Framework`v8::CpuProfileNode::GetParent() const + 43548
    frame #5: 0x000000010b0982b4 Electron Framework`v8::CpuProfileNode::GetParent() const + 42648
    frame #6: 0x000000010b09dde8 Electron Framework`v8::CpuProfileNode::GetParent() const + 65996
    frame #7: 0x000000010c72cadc Electron Framework`v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 2443644
    frame #8: 0x000000010af6e6f4 Electron Framework`v8::internal::DefaultEmbedderRootsHandler::ResetRoot(v8::TracedReference<v8::Value> const&) + 21744
    frame #9: 0x000000010d42d6f0 Electron Framework`v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 16078224
    frame #10: 0x000000010d448394 Electron Framework`v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 16187956
    frame #11: 0x000000010d3f64e4 Electron Framework`v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 15852420
    frame #12: 0x000000010d448d9c Electron Framework`v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 16190524
    frame #13: 0x000000010d4149c8 Electron Framework`v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 15976552
    frame #14: 0x000000010d462290 Electron Framework`v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 16294192
    frame #15: 0x000000010d462404 Electron Framework`v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 16294564
    frame #16: 0x000000010d47d9d0 Electron Framework`v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 16406640
    frame #17: 0x000000019843c26c libsystem_pthread.dylib`_pthread_start + 148
```

**Comment by dbkr** [comment] 2022-11-21 19:05
I'm still not really sure what's causing this crash - in a testing build, it crashes somewhere else before I can repro this crash. However, it seems fine with the previous build, v20.3.4, so I suggest downgrading to that for this release. If we want a fix for this release, our options are going to be limited to either downgrading one patch release or upgrading a major version (if indeed that fixes it - I haven't tested that).

https://github.com/electron/electron/releases/tag/v20.3.5 are the fixes we'd be missing out on: I don't believe any of them are critical. One is a crash when SSRCs are are not unique, but this crashes most times anyway.

**Comment by t3chguy** [comment] 2022-11-21 23:24
Will accept backport into staging and upgrade to v21 to develop tomorrow

**Closed** 2022-11-22 10:17 UTC
Labels: T-Defect, X-Regression, S-Major, X-Release-Blocker, A-VoIP, A-Electron, O-Occasional
