### ISSUE TITLE
Create DM room only on first message

### ISSUE THREAD

**Issue by jakewbate** [vector-im/element-web#19024] opened 2021-09-14 10:16 UTC
- As a user sending a DM to someone I do not have an active DM conversation with
- I want the room to be created only when I first send a message (text, image or voice)
- So that the recipient receives the invite only when there is a message in the room

**Comment by t3chguy** [comment] 2021-09-14 10:50
Duplicate of https://github.com/vector-im/element-web/issues/14736

**Closed by t3chguy** 2021-09-14 10:50 UTC
Labels: A-DMs, X-Needs-Product, T-Enhancement, A-Create-Room, O-Intermediate
