### ISSUE TITLE
Suggest rooms in spaces first in the #-picker

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19096] opened 2021-09-19 21:39 UTC
#### What would you like to do?

When I want to reference another room with #, i'd like for the rooms belonging to the current space to pop up at the top of the autocomplete picker first.

#### Why would you like to do it?

When picking a room called "politics" from the picker, i accidentally picked a room in a very different space, as all rooms were the same name, with only differing profile pictures.

Putting the same-space room at the top would make the spaces feel a bit more integrated and contained.

#### How would you like to achieve it?

Either put a separate section "in this space" at the top (and rename the current one "not in this space"), or just sort the same-space rooms first invisibly.

**Comment by SimonBrandner** [comment] 2021-09-20 07:27
Duplicate of https://github.com/vector-im/element-web/issues/18757

**Closed** 2021-09-20 07:29 UTC
Labels: T-Enhancement
