### ISSUE TITLE
Communities don't list People/Rooms until Appearance setting is toggled; then only shows them until Community Filter is changed.

### ISSUE THREAD

**Issue by Hubcapp** [vector-im/element-web#15653] opened 2020-11-05 22:42 UTC
### Description

I would expect that when I click a community filter, all Rooms & People in the community would be shown immediately. Instead, If I would like a community filter to show any data at all, I must toggle the "Show rooms with unread messages first" setting. It doesn't matter if it's on or off, it's just to refresh the list, which apparently is not loading correctly when applying the community filter.

### Steps to reproduce

Here is a video of the frustrating & undesired behavior:

![communities are broken](https://user-images.githubusercontent.com/1337967/98304502-b30cbd00-1f85-11eb-8128-d48192ced0ff.gif)

### Version information

This issue is present on
* https://app.element.io/ with Firefox on Debian
* and with the README suggested "nativefier" of the hosted https://app.element.io/, which uses chrome sandbox.

**Comment by turt2live** [comment] 2020-11-05 23:23
I can't reproduce this - can you go to settings -> help -> submit debug logs and reference this issue after reproducing it please?

**Comment by Hubcapp** [comment] 2020-11-06 00:20
I am also unable to reproduce this issue now. :confused:  If I encounter it again, I will submit debug logs to this issue.

**Comment by turt2live** [comment] 2020-11-06 01:23
Alright. For now I'm going to close this - if it becomes reproducible, please open a new issue.

**Closed by turt2live** 2020-11-06 01:23 UTC
Labels: bug, cannot-reproduce, type:new-room-list

**Comment by Hubcapp** [comment] 2020-11-06 15:06
Fair. It is still a real problem that happened, but if there's no way to reproduce it for now, there are other problems that can be worked on...
