### ISSUE TITLE
messages show up blacked out with smaller white lettering when we write particular symbols like this:  `  

### ISSUE THREAD

**Issue by JessyMMO** [vector-im/element-web#16322] opened 2021-01-30 19:38 UTC
### Description

messages show up blacked out with smaller white lettering when we write particular symbols like this:  `  (in our room-chats)

### Steps to reproduce

It is expected to wirte ((Yâhuwshúa)) with this symbol described above, at the end of the Name so that the symbol shows up together at the end of the Name, nevertheles it is invisible and the message shows up blacked out with smaller white lettering when we write the particular symbol:  ` 

![Element issue](https://user-images.githubusercontent.com/68674451/106366150-96232400-62ff-11eb-9fd9-3116ce219cb7.JPG)

It must be like This: 

![Element issue 2](https://user-images.githubusercontent.com/68674451/106366221-0631aa00-6300-11eb-9b76-7eb25d312b4e.PNG)

### Version information

- **Platform**: 
- **OS**: Windows, 
- versión de Element: 1.7.18
- versión de olm: 3.2.1

**Comment by turt2live** [comment] 2021-01-30 19:42
This is markdown. To avoid this, type `/plain` before the message.

**Comment by t3chguy** [comment] 2021-02-01 13:35
Looks like a duplicate of https://github.com/vector-im/element-web/issues/16320 which got closed in favour of https://github.com/vector-im/element-web/issues/483

**Closed by t3chguy** 2021-02-01 13:35 UTC
