### ISSUE TITLE
Sessions info lost

### ISSUE THREAD

**Issue by hermann-san** [vector-im/element-web#23521] opened 2022-10-18 13:10 UTC
### Steps to reproduce

1. Starting ELement , probably after operating system crash
2. waiting for UI to be launched
3. Error message appears.

#### What did you expect?
loading UI without error message

#### What happened instead?
Error message came - logs below
```
Some session data, including encrypted message keys, is missing. Sign out and sign in to fix this, restoring keys from backup.
Your browser likely removed this data when running low on disk space. To help us prevent this in future, please send us logs.

```
### Operating system

Linux Mint 20

### Application version

Element version: 1.11.10
Olm version: 3.2.12

### How did you install the app?

apt.
I also have a Flatpak version installed, but it's not in use /auto-started

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-10-31 15:58
Duplicate of https://github.com/vector-im/element-web/issues/23123

**Closed by t3chguy** 2022-10-31 15:58 UTC
Labels: T-Defect, S-Critical, A-Electron, A-Storage, O-Uncommon
