### ISSUE TITLE
unable to use voice chat 

### ISSUE THREAD

**Issue by shirishag75** [vector-im/element-web#3582] opened 2017-04-07 17:42 UTC
I tried using the voice call functionality and was unable to complete even a single call. 

On the console I got this - 

```
[$] riot-web                                                                                                                     
Starting auto update with base URL: https://riot.im/download/desktop/update/
Auto update not supported on this platform
[12517:0407/223406:ERROR:stunport.cc(504)] sendto: [0x00000067] Software caused connection abort
[12517:0407/223406:ERROR:stunport.cc(504)] sendto: [0x00000067] Software caused connection abort
[12517:0407/223406:ERROR:stunport.cc(504)] sendto: [0x00000067] Software caused connection abort
[12517:0407/223407:ERROR:stunport.cc(504)] sendto: [0x00000067] Software caused connection abort
[12517:0407/223409:ERROR:stunport.cc(504)] sendto: [0x00000067] Software caused connection abort
[12517:0407/223410:ERROR:stunport.cc(504)] sendto: [0x00000067] Software caused connection abort
[12517:0407/223412:ERROR:stunport.cc(504)] sendto: [0x00000067] Software caused connection abort
[12517:0407/223414:ERROR:stunport.cc(504)] sendto: [0x00000067] Software caused connection abort
[12517:0407/223415:ERROR:stunport.cc(89)] Binding request timed out from 192.168.1.x:55297 (eth0)
[12517:0407/223417:ERROR:turnport.cc(703)] Jingle:Port[xxxxxxxx:audio:2:0:relay:Net[eth0:192.168.1.x/24:Ethernet]]: Failed to send TURN message, err=103
[12517:0407/225413:ERROR:turnport.cc(1506)] Received TURN CreatePermission error response, code=403; pruned connection.
[12517:0407/225414:ERROR:turnport.cc(1506)] Received TURN CreatePermission error response, code=403; pruned connection.
[12517:0407/225414:ERROR:turnport.cc(1506)] Received TURN CreatePermission error response, code=403; pruned connection.
[12517:0407/225429:ERROR:rtpreceiver.cc(61)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
```

### Version information

desktop 

For the desktop app:

- **OS**: Debian Stretch updated daily. 
- matrix-react-sdk version: 0.8.6
vector-web version: 0.9.7
olm version: 2.2.1

The 55297 port which by default was denied had opened it but still have the same issue. Have no idea what's wrong. 

the only thing I have blurred is jingle port values as they seemed to be something different than expect. I could pm it whoever feels like troubleshooting.

**Comment by lampholder** [comment] 2017-04-20 16:56
@shirishag75 Are you running your own homeserver/using a homeserver other than matrix.org? Is TURN configured and working correctly?

**Comment by shirishag75** [comment] 2017-04-20 21:02
@lampholder no, not running any homeserver. I just downloaded the binary from riot.im and and running it on my Debian desktop, that's about it.

**Comment by lampholder** [comment] 2017-04-20 22:39
I've put a lot of scary labels on this since I don't know how bad this is or widespread it is likely to be. I'll have a go at reproducing on my machine tomorrow.

**Comment by lampholder** [comment] 2017-05-17 13:27
Sorry, I forgot about this for a while - @shirishag75 I wasn't able to reproduce this with a fresh desktop app install calling a ______:matrix.org account (which picked up the call on an iPhone).

@shirishag75 - I forgot to ask who you were calling - was that person on their own homeserver?

Also, if you try again, could you upload the logs around the time of the call? You can upload logs by opening up the user settings panel (the cog in the bottom left) and scrolling to the bottom.

**Comment by shirishag75** [comment] 2017-05-17 13:40
I dunno if the person had their own homeserver running or not. I believe though that they were using one of the pre-existing services rather than running their own homeserver. Will ask and let you know.

**Comment by liberodark** [comment] 2017-08-05 19:31
For me calls don't work have send via Report it

**Comment by andreygursky** [comment] 2017-08-28 21:14
Have you looked into javascript/web console?

**Comment by shirishag75** [comment] 2017-08-29 02:14
@andreygursky  please share how to look into javascript/web console please.

**Comment by andreygursky** [comment] 2017-08-30 00:58
Firefox: Menu -> Tools -> Web Developer -> Browser Console
Chromium: Menu -> More tools -> Developer tools -> Console

**Comment by shirishag75** [comment] 2017-08-30 05:46
@andreygursky I think there is a bit of mis-communication here. I'm **NOT** using riot-web web client but riot-web desktop client i.e. https://riot.im/desktop.html .

**Comment by andreygursky** [comment] 2017-08-30 08:13
So you're running Electron based version, which is embedded in chromium. You could try Ctrl-Shift-I. If this will not help, hopefully riot-web devs could suggest, how to show the console.

**Comment by andreygursky** [comment] 2017-08-30 08:17
@shirishag75, BTW, you're running the recent 0.12.2 version?

**Comment by shirishag75** [comment] 2017-08-31 21:58
@andreygursky yup, using the latest version and was able to get the console, will get you back later on this after trying again in a day or two.

**Comment by SimonBrandner** [comment] 2021-02-22 19:28
@shirishag75, is this still a problem?

**Comment by SimonBrandner** [comment] 2021-03-22 11:17
I will close this as I can not reproduce this and there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.

**Closed by SimonBrandner** 2021-03-22 11:17 UTC
Labels: A-VoIP, P1, S-Major, T-Defect, X-Regression, Z-Platform-Specific
