### ISSUE TITLE
emoji autocomplete offers incorrect suggestion

### ISSUE THREAD

**Issue by skepticalwaves** [vector-im/element-web#19887] opened 2021-11-24 20:00 UTC
### Steps to reproduce

Typing in the messagebox, I type `:+1:`

The resulting autocomplete popup is this:
![image](https://user-images.githubusercontent.com/66973897/143305315-3cd4fd41-f8bc-448c-9ab2-a48f77534570.png)

#### What did you expect?

The thumbs up emoji

#### What happened instead?
See screenshot

Side info:

Typing `:thumbsup:` suggests the proper emoji with the proper text code!
![image](https://user-images.githubusercontent.com/66973897/143305493-c31a2950-cd47-46aa-adcc-25ec1ed8bca8.png)

### Operating system

Linux

### Browser information

Brave	1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)

### Application version

Element version: v1.9.5 Olm version: 3.2.3

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2021-11-25 07:34
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19302, https://github.com/vector-im/element-web/issues/19178

**Closed by SimonBrandner** 2021-11-25 07:34 UTC
Labels: T-Defect
