### ISSUE TITLE
Jitsi does not share a screen

### ISSUE THREAD

**Issue by AyelGoth** [vector-im/element-web#15483] opened 2020-10-17 15:49 UTC
Element 1.7.9
Kubuntu 20.04
Video: Gforce GT 970

I found several errors in Jitsi. The first one is that he doesn't share the screen. When you set screen sharing it opens a dialog to select whether to share a single window or share the entire screen, but it doesn't show anything and waits to load those screens to select them.

Another error is that when I press the button to enlarge Jitsi's screen, it opens a window in the browser that throws an error when loading it. When I return to the Element window, it doesn't show the conference anymore and a loading poster appears, but it doesn't reload anything and I have to close the widget.

**Comment by t3chguy** [comment] 2020-10-17 15:51
Duplicate of #4880

**Closed by t3chguy** 2020-10-17 15:51 UTC
Labels: bug
