### ISSUE TITLE
greyscale/b+w icon in the system tray

### ISSUE THREAD

**Issue by papamoose** [vector-im/element-web#20935] opened 2022-02-05 20:26 UTC
#### What would you like to do?

I'd like the ability to turn on a grey scaled or black and white icon in the system tray.

[My system tray in gnome-shell.](https://imgur.com/a/Hz3tOwf)

#### Why would you like to do it?

It looks better. All the other system tray icons have a grey scale/b+w option.

#### How would you like to achieve it?

I would imagine this would take the form of a toggle switch in settings.
"Enable grey scale system tray icon"

Additionally someone would need to make a grey scale version of the icon.

**Comment by SimonBrandner** [comment] 2022-02-06 13:11
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/9685

**Closed by SimonBrandner** 2022-02-06 13:11 UTC
Labels: T-Enhancement
