### ISSUE TITLE
Day 0: Trying to create a DM > created a room

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-web#15512] opened 2020-10-20 18:28 UTC
I tried to create my first DM and found a few issues that gave me reason to doubt the product.

1. Searching for "ni" and the first result was a slur - which made me question who this product is for/who uses it.
2. After finding someone > picking them > tapping "Go", I got a spinner that stayed on ~60seconds, while in the background a Room was made, not a DM.

![63](https://user-images.githubusercontent.com/1587166/96628787-9b3d0400-130a-11eb-9bc9-1330d23837fa.png)

![65](https://user-images.githubusercontent.com/1587166/96628736-89f3f780-130a-11eb-93e7-65afccfcdbf7.png)

**Comment by t3chguy** [comment] 2020-10-21 13:23
@niquewoodhouse any chance you still have that session alive and could rageshake? (Doesn't matter if you've refreshed, as long as you didn't log out)

**Comment by t3chguy** [comment] 2020-10-21 13:28
This looks like a server failure.
The error shows that it rejected our `/createRoom` and internally must have somehow broken and created the room as a Room and not DM - ignoring our `is_direct` flag

**Comment by t3chguy** [comment] 2020-10-21 13:30
I can reproduce on matrix.org

![image](https://user-images.githubusercontent.com/2403652/96726584-00940200-13aa-11eb-89d2-9e7d9262492e.png)

![image](https://user-images.githubusercontent.com/2403652/96726553-fd007b00-13a9-11eb-9898-32f873bf109f.png)

![image](https://user-images.githubusercontent.com/2403652/96726520-fb36b780-13a9-11eb-91db-e2a94caa0b1f.png)

**Comment by niquewoodhouse** [comment] 2020-10-21 15:33
> @niquewoodhouse any chance you still have that session alive and could rageshake? (Doesn't matter if you've refreshed, as long as you didn't log out)

Sorry @t3chguy I did log out, but I can log back in if helpful at all?

**Comment by t3chguy** [comment] 2020-10-21 15:33
Its alright, I managed to reproduce and confirmed it to be a Synapse issue

**Comment by richvdh** [comment] 2020-10-22 10:01
> Its alright, I managed to reproduce and confirmed it to be a Synapse issue, in future best to send one anyway right after creating an issue

Long story short, matrix.org was basically down between 13:00 UTC and 13:25 yesterday, and at the point you sent the createRoom, it was still catching up with the backlog :/. I've raised https://github.com/matrix-org/synapse/issues/7867 about the failure mode, but hopefully it's an unusual edge case...

**Comment by t3chguy** [comment] 2020-10-22 10:03
Weird that @niquewoodhouse saw the exact same failure mode a day before

**Comment by richvdh** [comment] 2020-10-22 11:05
yeah, similar failure mode. Perhaps it's not as unusual as I hoped :/

**Comment by ara4n** [comment] 2020-10-24 22:35
on the abusive username problem, i've raised it with the abuse team.

**Comment by turt2live** [comment] 2022-05-07 01:19
Closing as the root cause of this is primarily on the server (Synapse) side.

**Closed by turt2live** 2022-05-07 01:19 UTC
Labels: T-Defect, S-Major, A-DMs, Z-Synapse, Z-FTUE-User-Lists, O-Occasional
