### ISSUE TITLE
Emoji parsing bugged in combination with parentheses

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19174] opened 2021-09-26 09:44 UTC
### Steps to reproduce

1. Type `()`
2. Have your cursor inbetween the parentheses `(|)`
3. Press space `( |)`
4. Type any emoji `( :eyes:|)`
5. Observe "grin" being suggested, and suggestion not going away when going to other spots

### What did you expect?

"Eyes" to still get suggested

### What happened?

"Grin" got suggested, and the emoji parsing to be a bit bugged

### Operating system

Linux

### Application version

Element version: 1.8.5 Olm version: 3.2.3

### How did you install the app?

Flatpak

### Homeserver

jboi.nl

### Have you submitted a rageshake?

No

**Comment by ShadowJonathan** [comment] 2021-09-26 09:45
Additional context video;

https://user-images.githubusercontent.com/22740616/134802560-afd58c7b-125e-4441-b7c7-13c2f7279390.mp4

**Comment by SimonBrandner** [comment] 2021-09-26 09:59
This has nothing to do with parentheses, this just happens when you finish the shortcode - write the ending `:`

**Comment by SimonBrandner** [comment] 2021-09-26 10:14
I am inclined to close this in favour of https://github.com/vector-im/element-web/issues/19178 though @ShadowJonathan disagrees, so I am going to leave this up to the team

**Comment by ShadowJonathan** [comment] 2021-09-26 10:16
I disagree on the basis that this is an issue onto itself, which exhibits buggy behaviour. #19178 is an enhancement which'd coincidentally fix this problem as well, but i think it's up to the team/design to decide how to fix this issue.

**Comment by robintown** [comment] 2022-03-11 15:04
Duplicate of https://github.com/vector-im/element-web/issues/19302

**Closed by robintown** 2022-03-11 15:04 UTC
Labels: T-Defect, S-Minor, A-Composer, A-Emoji, O-Uncommon
