### ISSUE TITLE
Match system theme only works at launch

### ISSUE THREAD

**Issue by daenney** [vector-im/element-web#16944] opened 2021-04-13 23:26 UTC
### Description

When switching between light and dark themes and "Match System Theme" is enabled in Settings > Appearance, the theme only switches if you relaunch the app.

### Steps to reproduce

- Enable "Match system theme in settings"
- Switch your desktop theme from light to dark or vice versa

### Describe how what happens differs from what you expected.

It's fairly common across DEs to support automatically switching between light and dark mode, for example based on sunrise/sunset (in tandem with things like redshift/nightlight etc).

When I switch between light and dark themes for my OS, the whole application should adapt. Browsers like Firefox and most other apps do this correctly. If I flip my OS theme to dark mode, my Firefox turns dark as well as any site that uses CSS's [prefers-color-scheme](https://caniuse.com/?search=prefers-color-scheme)

When I flip my OS from dark to light or vice versa, the window decorations correctly update (b/c Gnome handles that). However, Element itself doesn't switch between its light and dark theme variants until I quit and relaunch the app.

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Btw I use Arch Linux
- **Version**: 1.7.24

**Comment by t3chguy** [comment] 2021-04-14 08:25
Duplicate of https://github.com/vector-im/element-web/issues/15459

**Closed by t3chguy** 2021-04-14 08:25 UTC
Labels: A-Themes-Official, S-Tolerable, T-Defect
