### ISSUE TITLE
E2E Unable to decrypt: The sender's device has not sent us the keys for this message. Issue with one user in just one room

### ISSUE THREAD

**Issue by miny1997** [vector-im/element-web#15112] opened 2020-09-07 21:36 UTC
### Description

I get the placeholder "Unable to decrypt: The sender's device has not sent us the keys for this message." on messages of just a specific user in a specific room. DM and other encrypted room do not do  this issue.

### Steps to reproduce

N/A

Logs being sent: yes

### Version information

Riot Web on Chrome 1.7.3
Element Windows 1.7.5

**Comment by miny1997** [comment] 2020-09-07 21:37
Logs were sent by Element Windows.

**Comment by turt2live** [comment] 2020-09-07 21:52
Duplicate of https://github.com/vector-im/element-web/issues/2996

Some things to check are:
* Did the sender enable "Never send encrypted messages to unverified sessions from this session"?
* Is the sender's server online and functioning?
* Is the sender using a client which is fully e2e-capable?

For further troubleshooting, visit #element-web:matrix.org

**Closed by turt2live** 2020-09-07 21:52 UTC
Labels: bug

**Comment by miny1997** [comment] 2020-09-28 18:17
I am not sure if it is a duplicate.

We all use Element.
I run the server, so I can say it is on because it affects only some users.
He has it turned on, but I am verified with him.

**Comment by 0lm** [comment] 2020-10-08 16:08
Not sure if this helps but, I got the same problem. My Acc is from matrix.org. I verified the dektop client and the newest 5 messages were decrypted, but the older ones all say the same error: Unable to decrypt: The sender's device has not sent us the keys for this message.

**Comment by miny1997** [comment] 2020-10-26 14:31
The ticket is still not solved...
