### ISSUE TITLE
SpacePanel should remember which branches you've collapsed

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17234] opened 2021-05-10 18:25 UTC
If you close and then open the top level of a space hierarchy in the spacepanel, it re-expands everything rather than remembering what you collapsed.

**Comment by SimonBrandner** [comment] 2021-05-10 18:27
Duplicate of [#17164](https://github.com/vector-im/element-web/issues/17164)

**Closed by SimonBrandner** 2021-05-10 18:27 UTC
