### ISSUE TITLE
Deleting all my messages in a Room

### ISSUE THREAD

**Issue by Keikai1880** [vector-im/element-web#21406] opened 2022-03-13 23:03 UTC
#### What would you like to do?
I would like to have an option to be able to delete all my previous messages in a room.

#### Why would you like to do it?
When i wanna delete my previous messages, i have to do it one by one in a public room. This is very tedious and annoying. I wanna be able to have full control over my data.

#### How would you like to achieve it?
I dont know.

**Comment by t3chguy** [comment] 2022-03-21 14:03
Duplicate of https://github.com/vector-im/element-web/issues/19063

**Closed by t3chguy** 2022-03-21 14:03 UTC
Labels: T-Enhancement, O-Uncommon
