### ISSUE TITLE
Share screen without having a webcam

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#23658] opened 2022-10-30 18:34 UTC
#### What would you like to do?
I don't have a webcam on my desktop computer.
I would still like to share my screen.
#### Why would you like to do it?
To discuss something on my screen with everyone on the call.
#### How would you like to achieve it?
It seems this feature is taken away artificially for no reason I can fathom.

### Additional context

It appears that this is (going to be) possible in element call.

**Comment by SimonBrandner** [comment] 2022-10-30 18:38
This is effectively a duplicate of https://github.com/vector-im/element-android/issues/3734 (and whatever the iOS counterpart is) as this already works between two up-to-date Element Web/Desktop clients 

(also, Element Call has this)

**Closed by SimonBrandner** 2022-10-30 18:38 UTC
Labels: T-Enhancement

**Comment by HarHarLinks** [comment] 2022-10-30 19:52
Indeed the call where I had this problem was desktop to iOS. Do I understand correctly: it's currently not possible because the initialization of the call determines whether there is video and it can't be switched on after establishing the call?

**Comment by SimonBrandner** [comment] 2022-10-31 05:44
> Indeed the call where I had this problem was desktop to iOS. Do I understand correctly: it's currently not possible because the initialization of the call determines whether there is video and it can't be switched on after establishing the call?

Yep, iOS and Android apps aren't able to start receiving a new video stream in the middle of a call: we can only screen share in video calls since there we can replace the already existing video with the screen sharing video
