### ISSUE TITLE
Redacted event does not update room preview

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23357] opened 2022-09-27 09:38 UTC
### Steps to reproduce

1. Enable message previews
2. Have someone send a message and redact it

#### What did you expect?

For the message preview in the room list to be redacted

#### What happened instead?

<img width="747" alt="Screen Shot 2022-09-27 at 10 33 57" src="https://user-images.githubusercontent.com/769871/192491578-a1d2b78e-13c8-4ea1-8a95-2a1ca997afcb.png">

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-09-27 09:50
Duplicate of https://github.com/vector-im/element-web/issues/17893

**Closed by t3chguy** 2022-09-27 09:50 UTC
Labels: T-Defect, S-Minor, A-Redaction, A-Message-Previews, O-Uncommon
