### ISSUE TITLE
"Can't load this message (m.room.message)" "Submit logs" is a confusing message

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#17289] opened 2021-05-13 17:02 UTC
#### Is your suggestion related to a problem? Please describe.
When I send some messages, I see:

![Screenshot 2021-05-13 at 18 01 06](https://user-images.githubusercontent.com/1197991/118159681-3b788880-b415-11eb-9b84-e92029ec4cc0.png)

#### Describe the solution you'd like.
There should be some explanation of why this is happening.

#### Additional context
https://github.com/matrix-org/element-web-rageshakes/issues/4945 describes the issue with concrete logs.

**Comment by t3chguy** [comment] 2021-05-13 17:11
Duplicate of https://github.com/vector-im/element-web/issues/17281

**Closed by t3chguy** 2021-05-13 17:11 UTC
Labels: T-Enhancement
