### ISSUE TITLE
Replies truncate too much

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18200] opened 2021-07-23 11:30 UTC
With the new replies implementation, I never see as much of a message being replied to as I want to. I'm spending my life clicking on messages being replied to and bouncing up and down the timeline, where before I'd just see more of the original message in context in the reply.

**Comment by t3chguy** [comment] 2021-07-23 11:31
Related https://github.com/vector-im/element-web/issues/18179

**Comment by ShadowJonathan** [comment] 2021-07-23 12:05
I'd argue that this is the reason why the new reply design was implemented; to only give a small preview, not the complete message, of that reply.

Tbh if that is something Design or Product doesn't agree with, it should've been caught *way* earlier in the process, as it's been in the works for quite a while, and now it's been out for a week or two.

**Comment by HarHarLinks** [comment] 2021-07-23 12:29
> to only give a small preview, not the complete message, of that reply.

in terms of user interaction that is "to remind of the original message which you likely already read and know", so it might be unnecessary to repeat it.
in my opinion, and why i like it, it also is: if replied to short messages, images and media, or if long ones weren't truncated, it translates to "use up way less space on the timeline"

a replied-to message that was navigated to should perhaps offer a button to jump back from whence you came.

as per #18179 I'm obviously a proponent of the replied-to-should-be-interactible-on-their own way to do things, because I don't see it possible nor reasonable to jump around so much. however I also like the new compactness of replies.

i tried to propose a couple ways in #18179 to reenable that _without_ significantly compromising or cluttering the new UI, e.g. just click the `...` to show the whole message in place.

**Comment by ShadowJonathan** [comment] 2021-07-23 12:33
Also note that some people *still* find this new approach too verbose, and would rather hide away the reply message and/or the replied-to preview entirely (something I personally disagree with); https://github.com/vector-im/element-web/issues/18078

**Comment by HarHarLinks** [comment] 2021-07-23 12:58
I would actually agree with that to some degree for my own use (see below), and potentially a setting in general for those who want it if the code is already there anyway.

---

Someone brought it up somewhere else in a related issue, but I can neither remember nor find it atm, but additional to my above points:

Contrary to popular believe it is __not__ so uncommon at all to reply to the direct predecessor message.
A common example would be a bot see below, but it also happens very regularly in the wild between humans.
![image](https://user-images.githubusercontent.com/2803622/126784374-c5dd429e-658c-4f22-87c5-c46407cf1999.png)


This is another reason for why I believe the previews might profit from more contextual truncating, e.g. to only one line if the message is still on screen.

**Comment by ShadowJonathan** [comment] 2021-07-23 13:06
> Someone brought it up somewhere else in a related issue [...]

(That was me, https://github.com/vector-im/element-web/issues/18171#issuecomment-884721651)

**Comment by robintown** [comment] 2021-08-02 01:04
Potentially part of the issue is that replies currently [look like any other normal text](https://github.com/vector-im/element-web/issues/18194), and so it's easy to start reading them before realizing it's only a truncated preview. Part of my reason for suggesting in https://github.com/matrix-org/matrix-react-sdk/pull/6396 that they be colored like blockquotes is to better set the user's expectations when they see them in the timeline.

**Comment by ara4n** [comment] 2021-08-09 13:46
This is really impacting my ability to use Element - i simply can't see the contents of the message that I'm replying to, and the last thing I want to do lose my place in the timeline to jump around.

Please can we implement an expand button on the truncated replies to let users expand them inline to avoid the truncation?

**Comment by ShadowJonathan** [comment] 2021-08-09 14:36
> and the last thing I want to do lose my place in the timeline to jump around.

That's why i opened https://github.com/vector-im/element-web/issues/18360, FWIW

**Comment by nadonomy** [comment] 2021-08-09 14:39
> Please can we implement an expand button on the truncated replies to let users expand them inline to avoid the truncation?

Agree, in lieu of printing the whole message (which harms legibility of the timeline overall) this is the most pragmatic & predictable fix to improve the goal at the core of the issue.

We'll take a look at what interaction makes the most sense (text buttons as show more/less or expand/collapse, or using dropdown iconography? etc).

**Comment by ShadowJonathan** [comment] 2021-08-09 14:41
@nadonomy https://github.com/vector-im/element-web/issues/18179 provides some mockups, and more information.

**Comment by nadonomy** [comment] 2021-08-09 14:52
@ShadowJonathan thanks. The ellipsis design looks interesting at a glance.

**Comment by Palid** [comment] 2021-08-18 14:18
Throwing this one back into design, we need to figure out some UX that will handle both the typical cases and corner cases in a proper manner.
The moment I started wrapping my head around this I immediately found a couple of cases where this may break the UX even more than jumping to a thread, for instance if you try to reply to a very nice amount of lorem ipsum e.g. (Generated 20 paragraphs, 1885 words, 12873 bytes of Lorem Ipsum) you'd need a way to both open and close the preview in a simple way that won't break your flow and current position in the timeline, which in this particular case where you have two screens of letters will screw things up immensly.
Maybe having some kind of a pop-over for that, or a hover effect would be good enough? Dunno about screen readers though.

@HarHarLinks's suggestion in #18179 for expand/collapse buttons seems pretty good for this case, but when there's more text in the message you'd have to click it multiple times to get to a satisfying point, which seems a lot more suited towards keyboard/power users, and not casual ones.
@nadonomy what do you think?

**Comment by HarHarLinks** [comment] 2021-08-18 14:29
Toggling the expand (once) could expand it up to a certain size (in pixels) and if the message still overflows have scrollbars.

btw did somebody mention that the same principle that applies for "quoted" replies in the TL as discussed here also applies to the composer during writing a reply?

**Comment by bkil** [comment] 2021-08-25 09:44
As a quick alternative, could we perhaps drop newlines when producing the two lines of preview? The thing is, sometimes people share a link and/or press enter a few times, and in such cases the preview contains very little information, while for the same vertical pixel space, more information could be shown.

On the same note, perhaps if the preview also contains an URI, it may also be shown as a shorter variant (like after chopping off parts of it, like protocol, `www.`, and perhaps the fragment or some of the query parameters as well - or possibly even anything but the hostname). Hovering over it would show the original link anyway.

**Comment by Palid** [comment] 2021-09-01 16:11
Added a video of why it is blocked in the pull request.

**Comment by Palid** [comment] 2021-09-03 11:22
Closing in favor of https://github.com/vector-im/element-web/issues/18884

**Closed by Palid** 2021-09-03 11:22 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Replies, X-Needs-Design, O-Frequent
