### ISSUE TITLE
unable to decrypt

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-web#26118] opened 2023-09-05 12:50 UTC
### Steps to reproduce

1. entering a room

#### What did you expect?
being able to read messages

#### What happened instead?
unable to decxrypt

### Operating system

Windows 11

### How did you install the app?

from Element

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-09-05 13:35
Duplicate of https://github.com/vector-im/element-meta/issues/245

**Closed by t3chguy** 2023-09-05 13:35 UTC
Labels: T-Defect
