### ISSUE TITLE
Can't load this message (m.room.message)

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#22801] opened 2022-07-11 11:56 UTC
### Steps to reproduce

1. Send a message in a public room
2. Observe error

![image](https://user-images.githubusercontent.com/1389908/178258861-d9108eca-8bba-4aeb-8b42-2d6a20d296ca.png)

#### What did you expect?

I should see my message

#### What happened instead?

Error message

### Operating system

Ubuntu 22.04

### Application version

Element Nightly version: 2022071101 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-07-11 12:10
Duplicate of https://github.com/vector-im/element-web/issues/22766

**Closed by t3chguy** 2022-07-11 12:10 UTC
Labels: T-Defect
