### ISSUE TITLE
 Unexpected concurrent DOM modification causing soft-crash #24338 

### ISSUE THREAD

**Issue by justjanne** [vector-im/element-web#24339] opened 2023-01-26 10:26 UTC
https://github.com/matrix-org/element-web-rageshakes/issues/19497

```
2023-01-23T22:18:52.676Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2023-01-23T22:18:52.676Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2023-01-23T22:18:52.678Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2023-01-23T22:18:52.678Z E The above error occurred while React was rendering the following components: 
    at span
    at div
    at Linkify (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/Linkify.tsx:27:26)
    at div
    at TooltipTarget (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/TooltipTarget.tsx:33:4)
    at div
    at RoomTopic (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/RoomTopic.tsx:40:36)
    at div
    at header
    at RoomHeader (webpack:///node_modules/matrix-react-sdk/src/components/views/rooms/RoomHeader.tsx:498:8)
    at ErrorBoundary (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/ErrorBoundary.tsx:38:8)
    at main
    at RoomView (webpack:///node_modules/matrix-react-sdk/src/components/structures/RoomView.tsx:378:8)
    at div
    at div
    at div
    at LoggedInView (webpack:///node_modules/matrix-react-sdk/src/components/structures/LoggedInView.tsx:140:8)
    at ErrorBoundary (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/ErrorBoundary.tsx:38:8)
    at MatrixChat (webpack:///node_modules/matrix-react-sdk/src/components/structures/MatrixChat.tsx:248:8)
2023-01-23T22:18:52.678Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2023-01-23T22:18:52.678Z E The above error occurred while React was rendering the following components: 
    at span
    at div
    at Linkify (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/Linkify.tsx:27:26)
    at div
    at TooltipTarget (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/TooltipTarget.tsx:33:4)
    at div
    at RoomTopic (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/RoomTopic.tsx:40:36)
    at div
    at header
    at RoomHeader (webpack:///node_modules/matrix-react-sdk/src/components/views/rooms/RoomHeader.tsx:498:8)
    at ErrorBoundary (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/ErrorBoundary.tsx:38:8)
    at main
    at RoomView (webpack:///node_modules/matrix-react-sdk/src/components/structures/RoomView.tsx:378:8)
    at div
    at div
    at div
    at LoggedInView (webpack:///node_modules/matrix-react-sdk/src/components/structures/LoggedInView.tsx:140:8)
    at ErrorBoundary (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/ErrorBoundary.tsx:38:8)
    at MatrixChat (webpack:///node_modules/matrix-react-sdk/src/components/structures/MatrixChat.tsx:248:8)
```

**Comment by t3chguy** [comment] 2023-01-30 09:44
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2023-01-30 09:44 UTC
Labels: T-Defect
