### ISSUE TITLE
New login "Later" button doesn't work

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#21390] opened 2022-03-11 10:19 UTC
### Steps to reproduce

1. Do a new device login.
2. "New login. Was this you?" toast is shown. Now the Later button works and dialog can be closed.
3. But if you do not close it and new device verification dialog appears, then after device verification Later button doesn't work and dialog doesn't dissapear.

#### What did you expect?
"New login. Was this you?" doalog buttons shall work anytime.

#### What happened instead?
"New login. Was this you?" cannot be closed, the only way is to reload the page.

### Operating system

Android 11

### Browser information

Forefox 99b2

### URL for webapp

own

### Application version

Verze Element: 1.10.7-rc.1 Verze Olm: 3.2.8

### Homeserver

own

### Will you send logs?

No

**Comment by robintown** [comment] 2022-03-11 12:34
Duplicate of https://github.com/vector-im/element-web/issues/17667

**Closed by robintown** 2022-03-11 12:34 UTC
Labels: T-Defect
