### ISSUE TITLE
Jumping to the first unread message fails

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-web#26354] opened 2023-10-10 19:22 UTC
### Steps to reproduce

1. Enter a room with many unread messages
2. Click on the UP arrow on the top right to get to the first unread message

#### What did you expect?
Jump to the first unread message

#### What happened instead?
Error message pops up and screen turns black

![image](https://github.com/vector-im/element-web/assets/640121/151bde96-84ed-484d-a1ab-aa2cfc46aa7e)

Side note: the German language translation is grammatically wrong

### Operating system

Windows 11

### Application version
Version von Element: 1.11.46
Version von Olm: 3.2.14

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-10-11 06:20
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-10-11 06:20
Duplicate of https://github.com/vector-im/element-web/issues/20927

**Closed by weeman1337** 2023-10-11 06:20 UTC
Labels: T-Defect
