### ISSUE TITLE
`classID` changes with each release causing taskbar settings to not be remembered

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#21131] opened 2022-02-19 01:34 UTC
*As reported in a feedback rageshake, https://github.com/matrix-org/element-web-rageshakes/issues/10883*

### Problem

Whenever Element auto-updates, the `classID` changes which causes the taskbar settings to not be remembered.

### Operating system

Windows

### Application version

Element version 1.10.4

**Comment by t3chguy** [comment] 2022-02-21 09:52
Duplicate of https://github.com/vector-im/element-web/issues/4601

**Closed by t3chguy** 2022-02-21 09:52 UTC
Labels: T-Defect, S-Minor, A-Electron, O-Occasional
