### ISSUE TITLE
Riot can get stuck endlessly pinging /register many times a second

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#10346] opened 2019-07-15 15:57 UTC
### Description

After trying to create an account and failing because the ID already existed, Riot got into a state where it slammed `/register` many times a second.

### Steps to reproduce

- Go to login screen
- Switch to Other as host
- Create account
- See that it's taken
- Switch to Matrix.org as host
- Switch back to Other as host
- Switch back to Sign-in

Logs being sent: yes

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox v69.0a1
- **OS**: Debian Stretch
- **Version**: Downloaded from buildkite: `bba167c4332e-react-111b28971a24-js-a8d200dd02d5`

**Comment by turt2live** [comment] 2019-07-15 16:20
Judging from the logs, my theory is that we're not cleaning up the UIA instance correctly when the server change happens. It seems to be re-submitting the dummy request over and over, and not getting an error to break the loop. If it was properly cleaned up, it should break the loop immediately.

**Comment by t3chguy** [comment] 2022-08-16 14:36
Closing in favour of https://github.com/vector-im/element-web/issues/23084 which has more repro 

Duplicate of https://github.com/vector-im/element-web/issues/23084

**Closed by t3chguy** 2022-08-16 14:36 UTC
Labels: T-Defect, A-Performance, P1, A-Registration
