### ISSUE TITLE
Full localStorage broke my element-web on Firefox

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#18258] opened 2021-07-27 12:07 UTC
Currently running develop.element.io on Firefox.

1. A few days ago, I suddenly became unable to send messages - pressing "return" would do nothing.
2. After this, attempting to log using develop.element.io informed me that I was using an incompatible browser.
3. I just attempted to log into develop.element.io. One of my rooms was full of "This message is corrupted".
4. Attempting again to log into develop.element.io informed me that I couldn't log (apologies, I didn't write down the error message).
5. Using app.element.io, everything works.

Looking at the console, I find out that my localStorage is full. This is most likely the cause of all these issues (including the "incompatible browser": if modernizer cannot write anything to localStorage, it decides that the browser doesn't have localStorage, even if it's because localStorage is full).

**Comment by jryans** [comment] 2021-07-27 13:34
Is there a clear way to distinguish "full" from "broken"...? E.g. does something like `await navigator.storage.estimate()` say anything that might be usable as an indicator of full?

**Comment by Palid** [comment] 2021-08-07 12:28
https://arty.name/localstorage.html The limit is around 5MB, but `await navigator.storage.estimate()` doesn't give any details about that, though we could use `new Blob(Object.values(localStorage))` instead to verify that.
The problem is that it takes around 20ms on my machine to verify. I think the best and easiest solution for that would be to create our own abstraction over localStorage that does the `new Blob` stuff for all incoming data, so that we can calculate the estimated size of incoming things. Full == broken in terms of `localStorage`, unfortunately.

**Comment by Yoric** [comment] 2021-08-16 09:26
Note that my Element is and remains broken. It would also be useful to have a way to unbreak it (a button such as "clear history").

**Comment by jryans** [comment] 2021-08-25 13:27
> Note that my Element is and remains broken. It would also be useful to have a way to unbreak it (a button such as "clear history").

Are you able to access the Sessions view for the bad session? You could use the "Clear Cache" button in Settings -> Help -> Clear cache. This removed IndexedDB cached content for the session, but perhaps it's enough by removing storage for that domain.

**Comment by Palid** [comment] 2021-09-02 18:20
Partial fix here: https://github.com/matrix-org/matrix-js-sdk/pull/1880

**Comment by novocaine** [comment] 2021-10-04 16:03
I'm collecting localStorage related failures into one issue - https://github.com/vector-im/element-web/issues/18423

Closing this as a duplicate - the details of this issue will be linked to it, and not lost.

**Closed by novocaine** 2021-10-04 16:03 UTC
Labels: T-Defect, S-Critical, A-Storage, O-Uncommon
