### ISSUE TITLE
Pasted image is uploaded as PNG

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#17688] opened 2021-06-18 11:48 UTC
### Description

When I paste an image from the clipboard, say, a screenshot (pixel data, not an existing file!) it is uploaded as PNG 🤨

Since I'm pasting pixel data, nothing dictates tht it has to be PNG, so why choose PNG? I would strongly encourage you to consider switching to WebP at the very least. There is no client (that isn't deprecated) in the world that can't display WebP.

A screenshot that I post, can easily blow itself up to 5MB, which is frankly a bit extreme just to quickly show someone what I mean. WebP, especially when being lossy (and this might be a user preference) can greatly reduce this size.

### Steps to reproduce

- Press printscreen
- Switch to Element
- Press Ctrl+V

Describe how what happens differs from what you expected.

Logs being sent: yes/no

I'd expect sane filesizes for screenshots, sent in a modern image format that every client & browser can display (can have been able to for a couple of years) - WebP 💪🏻

### Version information

- **Platform**: desktop
- **OS**: Windows 10 21H1
- **Version**: 1.7.30

**Comment by t3chguy** [comment] 2021-06-18 11:50
That's the only format your browser presents the data to us in. In the case of Element desktop that's the embedded Chromium inside Electron.

You can test it by trying to paste any image format into http://madebyevan.com/clipboard-test/

**Comment by thany** [comment] 2021-06-18 11:51
Like I said, all browsers - and Electron - support WebP.

**Comment by t3chguy** [comment] 2021-06-18 12:27
A lot of browsers block background canvas work when it isn't caused by a user click due to privacy/fingerprinting. Sure Electron doesn't. 

> Also mind you, there is no PNG data in the clipboard. Just plain vanilla uncompressed RGB pixels.

Sure, but there's no web API to access those and all the image upload code lives in the non-electron-specific part of the app.

Closing this in favour of https://github.com/vector-im/element-web/issues/14047

**Closed by t3chguy** 2021-06-18 12:27 UTC
Labels: T-Defect, Z-Upstream

**Comment by G2G2G2G** [comment] 2021-07-14 22:13
This has nothing to do with anything mentioned in this thread. The reason it is uploaded as a PNG is because your operating system copies the image buffer as lossless thus uses png. Every OS currently uses PNG. Hopefully they switch to lossless JXL (jpeg XL) but once again nothing to do with any of these browsers etc.
Copying an image's buffer from any software and pasting to anything will result in a PNG.
