### ISSUE TITLE
Edits can make the edited message disappear

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#17322] opened 2021-05-17 10:18 UTC
I've noticed Element Web sometimes blanks out messages when they are edited (instead of replacing them with the new content):

![image](https://user-images.githubusercontent.com/5547783/118472930-b5588c80-b709-11eb-9607-44536901b02c.png)

The new content appears after waiting for a bit or switching rooms.

Observed on develop.element.io with Firefox on Linux.

~Will rageshake.~ Done

**Comment by t3chguy** [comment] 2021-05-17 10:39
Duplicate of #17290

**Closed by t3chguy** 2021-05-17 10:39 UTC
