### ISSUE TITLE
User logged out, then logged in gets everytime ** Unable to decrypt: The sender's device has not sent us the keys for this message. **

### ISSUE THREAD

**Issue by svargh** [vector-im/element-web#20430] opened 2022-01-07 10:56 UTC
### Steps to reproduce

1. Testusers created:
cdssafss001 on firefox profile 1, Room1 created
cdssafss002 on firefox profile 2, Room2 created

2. Both users logged in and verified each other
3. cdssafss001  invited to Room2, cdssafss002 invited to Room1
4. cdssafss001 writes message to cdssafss001, Room1, Room2
5. cdssafss002 writes message to cdssafss002, Room2, Room3
6. Both users receive messages.

7. cdssafss002  logged off. Simulating our testcase device lost /laptop lost by removing firefox profile of cdssafss002  
8. cdssafss001  writes to logged off cdssafss002  
9. cdssafss002  logs in new firefox profile: Security Key given and room keys restored.
10. cdssafss002  sees old messages until step 6. But Message from step 8 is shown as 
   "** Unable to decrypt: The sender's device has not sent us the keys for this message. **"

#### What did you expect?
- Logged off users should be able to read messages from fresh new browser or laptop using whatever backup information is there, currently the full firefox profile needs to be backed up. 
- It would be nice if something like seeds can be used to restore all messages (like Bitcoin seed) on a fresh  browser.

- The one responsible stateful information in browser must be also backed up which is responsible for decrypting the messages
- Obviously not all keys are backuped which is very frustrating.

#### What happened instead?
After log in back (same as using new device without any other logged in session) ** Unable to decrypt: The sender's device has not sent us the keys for this message. **

### Operating system

Windows

### Browser information

Firefox 95

### URL for webapp

https://app.element.io/

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-01-07 10:59
Duplicate of https://github.com/vector-im/element-web/issues/18458

**Closed by t3chguy** 2022-01-07 10:59 UTC
Labels: T-Defect
