### ISSUE TITLE
Improve discoverability of Jitsi widgets

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#15768] opened 2020-11-18 17:00 UTC
A common @lampholder frustration:

- In some rooms, Jitsi conferences start while I'm focused on another room
- I switch to the room and can't see my Jitsi widget
- Then, I need to unpin & re-pin the Jitsi widget to join the call
- @lampholder can you confirm please if the show/hide widgets interaction in the room header works? if it doesn't, we have a bug, if it does, we have a discoverability issue
- In general, Jitsi conferences are difficult to discover

Proposed solution
- This point should be moot when we action upcoming VoIP usability issues, as we're improving the discoverability of conferences all round
- In the meanwhile, a quick fix could be to pin & show Jitsi conferences by default, until they're explicitly unpinned or hidden by the user

@t3chguy would be interested to see if you have any insight into this issue too as we worked on widgets together last
@dbkr heads up, we may want to action this as a quick win within the VoIP team to avoid it being backlogged into oblivion

**Comment by t3chguy** [comment] 2020-11-18 17:02
Duplicate of https://github.com/vector-im/element-web/issues/15737

**Comment by t3chguy** [comment] 2020-11-18 17:06
My insight:
Currently widgets by default are hidden but from then on will remember your settings, it probably makes sense to flip that to default-on, which for most users will only have one effect: showing Jitsi. Does not fix that if they ever click Hide widgets that'd mean any future jitsi confs would still be hidden.

**Comment by danielberndt** [comment] 2020-12-09 15:03
Just stumbled across this issue for a project of mine as well. Is there any way to change the defaults within a self-hosted instance already?

**Comment by toger5** [comment] 2021-11-02 16:49
Relates to: #15993 (also request pinning widgets by default)

**Closed** 2021-11-15 11:49 UTC
Labels: A-Widgets, X-Needs-Design, T-Enhancement, A-Jitsi
