### ISSUE TITLE
Option also show sub-space in the space bar (like it would be root)

### ISSUE THREAD

**Issue by 6543** [vector-im/element-web#22827] opened 2022-07-12 21:43 UTC
#### What would you like to do?
There are majour public Spaces like https://matrix.to/#/#gitea-space:matrix.org that should be on the "space selector" as root space.
But if you also have joined a space that did add it as subspace (witch itselve is usefull and fine) like https://matrix.to/#/#forgefederation:matrix.batsense.net , it will disapear.

#### Why would you like to do it?

I'm heavily connected via matrix to **a lot** of projects ...

#### How would you like to achieve it?

Just add an option into "Space Options" next to:
![2022-07-12_23-41](https://user-images.githubusercontent.com/24977596/178600573-a482b9d1-854b-4b1c-918f-142f17a5f138.png)

### Have you considered any alternatives?

creating an own private space that contain the same rooms as the public space ... but that wont scale :/

**Comment by 6543** [comment] 2022-07-12 21:49
something like:
![2022-07-12_23-41](https://user-images.githubusercontent.com/24977596/178601555-9f77205b-c1af-4d62-a95b-a9c25fe48586.png)

?

**Comment by aaronraimist** [comment] 2022-07-13 00:39
Duplicate of #17472

**Closed by aaronraimist** 2022-07-13 00:39 UTC
Labels: T-Enhancement
