### ISSUE TITLE
Encourage homeserver diversity by giving a choice at signup

### ISSUE THREAD

**Issue by bobobo1618** [vector-im/element-web#16282] opened 2021-01-25 18:19 UTC
**Is your suggestion related to a problem? Please describe.**
One of the great strengths of Matrix compared to other systems is federation but Element, the primary client, encourages all signups to go to matrix.org, creating one giant single point of failure.

**Describe the solution you'd like**
Inspired by Mastodon:
- Maintain a list of homeservers somewhere (see [Mastodon](https://joinmastodon.org/communities)
- Add a link to or embed this list in the signup flow
- Make using another homeserver dead easy (e.g. add a query parameter to the signup flow that pre-fills a different homeserver)

**Additional context**
Motivated by [this HN comment](https://news.ycombinator.com/item?id=25812950). Apologies if this is the wrong place.

**Comment by t3chguy** [comment] 2021-01-25 18:21
Duplicate of https://github.com/vector-im/element-web/issues/6827

**Closed by t3chguy** 2021-01-25 18:21 UTC
Labels: suggestion
