### ISSUE TITLE
"Always display timestamps" is not respected

### ISSUE THREAD

**Issue by tucznak** [vector-im/element-web#17748] opened 2021-06-23 18:30 UTC
### Description

After the last update, timestamps are no longer always displayed, irrespectible if the setting is toggled on or off. The only timestamps displayed are for the last message in the window, and the message that cursor is currently over. These messages are significantly offset to the right, which is visually jarring.

![element_bug](https://user-images.githubusercontent.com/24601129/123149566-b051d000-d461-11eb-932f-8faa108d9a82.png)

### Steps to reproduce

- install the update to 1.7.31
- toggle the "always display timestamps" setting in preferences -> timeline (sorry if my translation of the options is a bit off)

Log: sent? I clicked the button in the app but nothing happened    

### Version information

- **Platform**: desktop
- **OS**: Windows
- **Version**: 1.7.31

**Comment by SimonBrandner** [comment] 2021-06-23 18:32
Duplicate of https://github.com/vector-im/element-web/issues/17648

**Comment by tucznak** [comment] 2021-06-23 18:35
Sorry about making a dupe, searched but didn't find that one. Although the main point still stands, the timestamps are NOT displayed even with the IRC layout turned off.

**Comment by SimonBrandner** [comment] 2021-06-23 18:38
> the timestamps are NOT displayed even with the IRC layout turned off.

They work just fine for me :thinking: 

![Screenshot_20210623_203745](https://user-images.githubusercontent.com/25768714/123150623-dfb50c80-d462-11eb-9d0d-27b300438a72.png)

**Comment by robintown** [comment] 2021-06-23 19:39
@tucznak Can you try going to the home page with Ctrl+Alt+H, then going back to that conversation? Since it looks like you're only in one room, I believe the bug here is that RoomView doesn't automatically listen for changes to that setting, meaning you have to manually refresh the view in some way (e.g. switching rooms, which since you're only in one room, you're not able to do).

**Comment by tucznak** [comment] 2021-06-23 19:51
@robintown Thanks for the tip, that did it. After going home and back to the conversation the timestamps show for the regular view.

**Comment by robintown** [comment] 2021-06-23 19:51
(@SimonBrandner you can assign me; also, this happens to not be a regression)

**Closed** 2021-07-22 01:44 UTC
Labels: A-Timeline, S-Minor, T-Defect
