### ISSUE TITLE
Unable to verify session on mobile device

### ISSUE THREAD

**Issue by parkerdi12** [vector-im/element-web#25164] opened 2023-04-20 09:23 UTC
### Steps to reproduce

1. http://joxi.net/Q2KMDDKCg0yoBr
2. http://joxi.net/LmGNqq6CZpgjNr
3. http://joxi.net/xAeaNN9SVZbv9A

https://www.loom.com/share/b4d0bc971ba64279aaffadc1061b785a - desktop video
https://disk.yandex.ru/i/JpFcP4Grj2LVOw - mobile app video 

#### What did you expect? 
Verify my mobile app with desktop app

#### What happened instead?
If the verify case is positive, a window appears stating that the verify process is canceled

### Operating system

Windows 10

### Application version

Версия Element: 1.11.29 Версия Olm: 3.2.12

### Homeserver

riotim.olegb.ru

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-04-20 09:35
Duplicate of https://github.com/vector-im/element-web/issues/18165

**Closed by t3chguy** 2023-04-20 09:35 UTC
Labels: T-Defect
