### ISSUE TITLE
Server Connectivity is Lost for a week since Desktop App last update

### ISSUE THREAD

**Issue by madzzzb** [vector-im/element-web#19308] opened 2021-10-06 09:45 UTC
Just update to last version and my Desktop App lost connectivity to servers.

Thought it was a server down for 2 or 3 days but today I switched to Web Browser where I can connect.

Trying to send logs through the app but got this error message
Failed to send logs: request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/versions

**Comment by robintown** [comment] 2022-04-24 20:04
Closing due to lack of info, and this being a likely duplicate of the above issue

**Closed by robintown** 2022-04-24 20:04 UTC
Labels: T-Defect, X-Needs-Info
