### ISSUE TITLE
UISIs from Half-shot but without a UISI error?!

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16951] opened 2021-04-14 10:30 UTC
<img width="473" alt="Screenshot 2021-04-14 at 11 29 43" src="https://user-images.githubusercontent.com/1294269/114696639-c847fd80-9d14-11eb-9a1d-3792958b2340.png">

as opposed to a few msgs later:

<img width="683" alt="Screenshot 2021-04-14 at 11 30 24" src="https://user-images.githubusercontent.com/1294269/114696678-d6961980-9d14-11eb-8e8b-414f2883daf5.png">

wtf?

**Comment by anoadragon453** [comment] 2021-04-14 10:54
Duplicate of https://github.com/vector-im/element-web/issues/11194?

**Comment by ara4n** [comment] 2021-04-14 10:55
looks plausible

**Comment by turt2live** [comment] 2022-06-14 05:18
This is a feature for "show hidden events".

**Closed by turt2live** 2022-06-14 05:18 UTC
Labels: T-Defect, A-E2EE
