### ISSUE TITLE
E2E: Room Settings: Show E2E options when creating a room

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7817] opened 2018-12-10 18:02 UTC
Part of https://github.com/vector-im/riot-meta/issues/230

Include room E2E settings choices at room-creation time

This is missing a wireframe

**Comment by kittykat** [comment] 2021-12-01 14:42
I'm going to close this issue for now as room settings seem to be working as intended. Please open a new issue with more detailed ACs if needed.

**Closed by kittykat** 2021-12-01 14:42 UTC
Labels: A-E2EE, X-Needs-Design, T-Enhancement, X-Needs-Community-Testing
