### ISSUE TITLE
Element Desktop forgets all settings on logout

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element-web#19280] opened 2021-10-05 06:31 UTC
### Steps to reproduce

1. Login
2. Change settings (e.g. theme, font, disable notifications for this session)
3. Logout

### What did you expect?

I expect that my settings are remembered and I don't have to configure the three things I mentioned every morning I login on a work device which I don't want to stay logged in just in case someone else accidentally got access to my "professional" account.

*This is a separate issue, but I have enabled dehydrated devices in `config.json` which partially resolved the encrypted messages problem (even though I still only read myself after opening FluffyChat on mobile and letting it give the keys Element Desktop wants).*

### What happened?

All my settings that are not stored on account data are forgotten and I have to once again:

* change font
* change theme to message bubbles (which I have found makes speedreading easier)
* disable notifications for this session
* etc.?

### Operating system

Microsoft Windows [Version 10.0.19043.1266]

### Application version

Element-webin versio: 1.9.0 Olm version: 3.2.3

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment] 2021-10-05 07:55
Closing as a duplicate of #4385

**Closed by gsouquet** 2021-10-05 07:55 UTC
Labels: T-Defect

**Comment by Ersonusaini** [comment] 2021-11-09 08:37
How to change footer powered by matrix remove from element desktop app
