### ISSUE TITLE
Thread view shows me the wrong room

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#20976] opened 2022-02-08 11:47 UTC
### Steps to reproduce

I just stumbled upon that.

1. I have threads in rooms A and B.
2. I recently (2h ago) wrote something in a thread on room A.
3. Last time I wrote something in a thread in room B was yesterday and I have restarted my browser since then.
4. I just switched to room B and clicked on the *Threads* icon (top right of the tab).
5. This showed me my thread from room A instead.

### Outcome

I expected my threads from room B.

### Operating system

Ubuntu

### Browser information

Firefox 96.0 (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 64242a004eb7-react-4501308b4722-js-07171a95c4f0 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by gsouquet** [comment] 2022-02-09 09:17
Duplicate of https://github.com/vector-im/element-web/issues/20850

**Closed by gsouquet** 2022-02-09 09:17 UTC
Labels: T-Defect
