### ISSUE TITLE
Allow room address copying from the directory

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#16619] opened 2021-03-07 14:34 UTC
If one want to find a set of rooms in order to pass their addresses on, it seems one currently needs to enter all those rooms in order to get those addresses.  It would be good if it were possible simply to copy the addresses off the list, and paste them in a message as pills.
Possibly an external (matrix.to) link could be offered as well.

**Comment by SimonBrandner** [comment] 2021-03-07 14:36
@Biep, please fill in the issue template

**Comment by Biep** [comment] 2021-03-07 14:39
Sorry - forgot the closing quote, and the github bot is picky.  Should be better now.

**Comment by SimonBrandner** [comment] 2021-03-07 14:40
@Biep, it's fine, thought something weird must have happened :D

**Comment by t3chguy** [comment] 2021-03-07 14:44
Duplicate of https://github.com/vector-im/element-web/issues/13751

**Closed by t3chguy** 2021-03-07 14:44 UTC
Labels: A-Room-Directory, T-Enhancement
