### ISSUE TITLE
Handle gemini:// links

### ISSUE THREAD

**Issue by michel-slm** [vector-im/element-web#21051] opened 2022-02-11 20:04 UTC
#### What would you like to do?
Be able to open gemini:// links sent in Element the same way as https:// (it should trigger the appropriate handler)

#### Why would you like to do it?
Gemini is a protocol that sits in between Gopher and web, and is privacy focused - it seems a natural fit with the people interested in Matrix, so it will be nice to support it better

#### How would you like to achieve it?
Just recognize gemini:// tokens as URLs

**Comment by michel-slm** [comment] 2022-02-11 20:07
Probably dupe of https://github.com/vector-im/element-web/issues/15018 but I think gemini:// should be baked in, not requiring the user to customize the schemas handled.

**Comment by t3chguy** [comment] 2022-02-14 09:24
Duplicate of #15018 - what the defaults of said configuration can be should be handled as part of the work there.

**Closed by t3chguy** 2022-02-14 09:24 UTC
Labels: X-Needs-Product, T-Enhancement, O-Uncommon
