### ISSUE TITLE
Receiving encrypted messages over bad connection often fails

### ISSUE THREAD

**Issue by yennor** [vector-im/element-web#24296] opened 2023-01-23 16:10 UTC
### Steps to reproduce

1. Receive a message while having a bad (horrible) internet connection

#### What did you expect?
To receive the message and being able to read it.

#### What happened instead?
On the desktop "Unable to decrypt message" on android "Waiting for this message, this may take a while" appears.
On the desktop when reading the source, following is shown:
`{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: DecryptionError: decryption key withheld **"
  }
}`

To make it a bit longer: I live in a region with bad internet coverage. A lot of lost packets over the internet links are quite common. Also that the connection comes and goes.
So when I'm somewhere with a bad connection, it often happens, that I receive a message, but it can not be decrypted (see above). Even when having a good internet connection again, the message will just never be decrypted. The sender never notices that, so he won't send the message again. Even when we are next to each other, switch on both phones, open element on both phones, wait a few minutes, the message won't be decrypted.
I didn't look into the matrix protocol, but I guess the key is send separately from the message, never arrives (packet lost on the way, or the connection just drops completely), and for whatever reason, the client never tries to get the key later on.
I'm not sure, if the same thing happens, when the sender has a bad connection, since I only notice it, when I'm receiving messages.
This problem persists since at least a year. So it doesn-t seem to depend on the client or server version.
Message send later on, when the connection is alright again (could be just a few minutes afterwards) arrive and are decrypted properly.

### Operating system

Android & Debian Linux

### Application version

1.74.0

### Homeserver

Synapse 1.73.0-1

### Will you send logs?

No

**Comment by motey** [comment] 2023-01-23 18:25
Same observation here. Uploaded some logs via the Desktop client.

**Comment by weeman1337** [comment] 2023-01-24 07:31
Thanks for reporting the issue @yennor . This looks like a duplicate of #24114 . You can follow the other issue for updates.

**Comment by weeman1337** [comment] 2023-01-24 07:31
duplicate of #24114

**Closed** 2023-01-24 07:31 UTC
Labels: T-Defect

**Comment by HammyHavoc** [comment] 2023-02-24 17:55
Saw this today and rage-shaked crash logs. I was able to decrypt subsequent messages from the sender, but not previous ones, despite it having worked fine for 18 months until now. He also couldn't seem to send keys to be able to decrypt the messages that had the issue.
