### ISSUE TITLE
When jumping up to a message in a room, the "jump down" button does not work

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20097] opened 2021-12-08 09:23 UTC
### Steps to reproduce

A few notes, this happens in many other scenarios, and also happens with links themselves, but this is probably the most reliable method;

1. Click the replied-to-message on a reply near the bottom of the screen (the bottom of the window has to be touching the bottom of the timeline), the replied-to-message has to be either high up enough, or outside of the screen's view.
2. See the jump.
3. Click the "go back" bottom button
4. Nothing happens.

---

At the moment of writing this, this condition is satisfied in the #matrix-spec room, with nico's reply to uhoreg's message.

#### What did you expect?

Element to jump back to the beginning of the timeline

#### What happened instead?

Nothing happened.

---

I believe this has something to do with how element "loads" messages, and that it needs to have messages unloaded before they can be jumped to.

For instance, this also happens when jumping to a message, jumping down, and then attempting to jump back up, it will not happen, as the message was "already loaded".

### Operating system

PopOS Linux, 21.04

### Application version

Element version: 1.9.5 Olm version: 3.2.3

### How did you install the app?

Flatpak

### Homeserver

jboi.nl

### Will you send logs?

No

**Comment by robintown** [comment] 2021-12-08 13:46
Duplicate of https://github.com/vector-im/element-web/issues/19907

**Closed by robintown** 2021-12-08 13:46 UTC
Labels: T-Defect
