### ISSUE TITLE
Add rooms to spaces using drag and drop

### ISSUE THREAD

**Issue by noantiq** [vector-im/element-web#22105] opened 2022-05-07 09:06 UTC
### Your use case

I was wondering if an issue already exists for this feature but could not find a suitable one. That being said, maybe I overlooked something. I only found a similar issue for groups: https://github.com/vector-im/element-web/issues/6201 .

#### What would you like to do?

Easily add one or more existing rooms to one or more existing spaces.

#### Why would you like to do it?

For example: when I get invited to a new room and want to integrate it into my existing structure, I want to add it to an existing space without too many steps. Right now it is not much fun adding rooms to spaces, especially when you need to work with more than one room or space since you have to go through a lot of views.

#### How would you like to achieve it?

Add the support for drag and drop of rooms to add them to a specific space.

### Have you considered any alternatives?

https://github.com/vector-im/element-web/issues/17028 describes an alternative that might be helpful for many use cases, but in my opinion just being able to drag a room into a space is much easier and more intuitive.

**Comment by SimonBrandner** [comment] 2022-05-07 10:33
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/16992

**Closed by SimonBrandner** 2022-05-07 10:33 UTC
Labels: T-Enhancement
