### ISSUE TITLE
Nightly: during backfill, the timeline flickers and jumps around unusably

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#20341] opened 2021-12-23 17:06 UTC
### Steps to reproduce

Scroll up when you need to fetch backfill

#### What did you expect?

Backfill loads, drops me in a sensible place

#### What happened instead?

Much jumping and an unexpected landing position

It's worse with "Show hidden events" enabled

https://user-images.githubusercontent.com/1197991/147271753-2d56ceaa-2ab2-4d8c-b914-abb764ec7bb9.mov

But the problem still exists without

https://user-images.githubusercontent.com/1197991/147271765-c8d42506-5c3c-4e72-bddf-c12c7d7b1a11.mov

### Operating system

macOS

### Application version

Element Nightly version: 2021122301

### Homeserver

bpulse.org

### Will you send logs?

Yes

**Comment by kittykat** [comment] 2021-12-25 16:56
Duplicate of #20302

**Closed by kittykat** 2021-12-25 16:56 UTC
Labels: T-Defect, X-Regression, S-Major, X-Release-Blocker, A-Timeline, O-Frequent
