### ISSUE TITLE
provide way to retrigger a keyshare req

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5765] opened 2017-12-02 11:35 UTC
if the user hits 'ignore' they are screwed. presumably one bet would be to maintain the inbox of reqs forever

**Comment by kittykat** [comment] 2021-12-01 13:12
I'm going to close this issue for now as we cannot reproduce it because the UI has changed - there is a way to re-trigger verification from the settings dialog. Please comment with @kittykat if you are still experiencing it and I will reopen the issue for you.

**Closed by kittykat** 2021-12-01 13:12 UTC
Labels: P3, A-E2EE, T-Enhancement, X-Needs-Community-Testing
