### ISSUE TITLE
The Close button of the "Create a space" dialogue has an ugly square outline

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#19991] opened 2021-12-01 14:01 UTC
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1342360/144247322-dbfbaedb-a36a-4d1e-b506-216f5770419b.png)

https://user-images.githubusercontent.com/1342360/144247594-17a0ffe3-28c4-4c26-9edb-377f97531107.mp4

The "X" close button for the Create a space dialogue has a strange outline which rotates with the icon.

#### What did you expect?

For there to be no outline.

#### What happened instead?

A wild outline appeared.

### Operating system

Arch Linux

### Browser information

Firefox stable 94.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 2039f1fcae9a-react-204699184841-js-87b920698f4c Olm version: 3.2.3

### Will you send logs?

No

**Comment by t3chguy** [comment] 2021-12-01 14:14
Get a better browser :P it's a Firefox svg mask transformation bug

**Comment by t3chguy** [comment] 2021-12-01 14:16
Duplicate of #19296 which has more details about the upstream bug

**Closed** 2021-12-01 14:16 UTC
Labels: T-Defect
