### ISSUE TITLE
Memory leak and CPU usage while Failed to parse permalink Error: Unknown entity type in permalink

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24671] opened 2023-02-26 16:04 UTC
### Steps to reproduce

1. Open Explore;
2. Type "github" to search
3. Monitor usage and check logs

#### What did you expect?
Search does not ask hundreds MBs of RAM.
#### What happened instead?

High hardware usage, memory consuming... From 700-800 to  1500-1600
```
rageshake.ts:73 Failed to parse permalink Error: Unknown entity type in permalink
    at f.parsePermalink (MatrixToPermalinkConstructor.ts:83:19)
    at A (Permalinks.ts:424:55)
    at D (Permalinks.ts:367:32)
    at target (linkify-matrix.ts:215:37)
    at Te.get (index.js:2486:16)
    at i.render (index.js:2681:26)
    at Te.render (index.js:2517:20)
    at a (index.js:62:24)
    at J (HtmlUtils.tsx:703:12)
    at te (HtmlUtils.tsx:725:25)
```

### Operating system

Windows 7

### Application version

1.11.23

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-02-27 09:13
Duplicate of https://github.com/vector-im/element-web/issues/24672 - the error you noticed is a red herring.

**Closed by t3chguy** 2023-02-27 09:13 UTC
Labels: T-Defect
