### ISSUE TITLE
Thread content not showing in main view

### ISSUE THREAD

**Issue by Naxsun** [vector-im/element-web#23857] opened 2022-11-29 11:22 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

#### What did you expect?
The last message of the thread to be shown in the main page
#### What happened instead?
It didn't show the message. Seemed like empty threads. When hitting 'reply in thread' the thread opened in the panel on the right, and also the last preview messages appeared in the main view.

<img width="727" alt="Screen Shot 2022-11-29 at 12 20 13" src="https://user-images.githubusercontent.com/71384922/204516348-e6666604-e851-4f5d-a1b0-c8d46544c5da.png">
<img width="731" alt="Screen Shot 2022-11-29 at 12 20 20" src="https://user-images.githubusercontent.com/71384922/204516359-b1040811-987b-4ac3-8e20-97f85c9daa4b.png">

### Operating system

macOs

### Application version

1.11.15

### Will you send logs?

No

**Comment by justjanne** [comment] 2023-01-09 00:11
This might have been fixed by https://github.com/matrix-org/matrix-js-sdk/pull/2996 (as it looks like this is a duplicate of https://github.com/vector-im/element-web/issues/24036)

**Comment by justjanne** [comment] 2023-01-17 17:52
I'm unable to reproduce this ever since https://github.com/matrix-org/matrix-js-sdk/pull/2996 got merged, could you please try reproducing this?

**Comment by gsouquet** [comment] 2023-01-31 18:13
@Naxsun Are you still experiencing this issue?

**Comment by Naxsun** [comment] 2023-01-31 19:42
I think I have't experienced it in the last weeks.

**Comment by gsouquet** [comment] 2023-02-01 09:12
Will close this issue, feel free to open another one if you do experience it again
Thank you 🙏

**Closed by gsouquet** 2023-02-01 09:12 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, S-Major, O-Uncommon, A-Threads
