### ISSUE TITLE
Scroll to the bottom button shows when at the bottom of the timeline

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15060] opened 2020-08-28 08:51 UTC
### Description

This is always showing, even when at the bottom of the page. It's extra annoying because it obscures the read receipts in the room.

![image](https://user-images.githubusercontent.com/2072976/91540880-5badf900-e913-11ea-957c-63f19aa3b920.png)

I'm using Element 1.7.4 on Desktop with the IRC layout.

**Comment by turt2live** [comment] 2020-08-28 14:05
@Half-Shot does the latest message cause the timeline to move down regardless?

**Comment by Half-Shot** [comment] 2020-08-28 14:21
Noticed that it's not *always* reproducible. Clicking on some rooms causes it to happen reliably (for me, the EMS internal room) and some other ones. Watercooler is fine though.

>@Half-Shot does the latest message cause the timeline to move down regardless?

Actually, when messages are sent it seems to jump **up** :/

**Comment by turt2live** [comment] 2020-08-28 14:58
Duplicate of https://github.com/vector-im/element-web/issues/14386 then (I think)

**Closed by turt2live** 2020-08-28 14:58 UTC
Labels: bug
