### ISSUE TITLE
Markdown formatting in links

### ISSUE THREAD

**Issue by gnomelibre** [vector-im/element-web#15412] opened 2020-10-07 22:39 UTC
### Description

Pasting a link containing underscores triggered Markdown formatting, which transformed the link, rendering it invalid.

### Steps to reproduce

- By putting this link in a room, https://twitter.com/____Dopamine___/status/1313550213873885189
- You get a different link with «Dopamine» in italics and the link no longer works :

![image](https://i.imgur.com/BkpgCpV.png)

When a link is detected, formatting should be disabled.

Logs being sent: no

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 81.0.1
- **OS**: Fedora 32
- **URL**: app.element.io

**Comment by turt2live** [comment] 2020-10-08 00:29
Duplicate of https://github.com/vector-im/element-web/issues/4674

**Closed by turt2live** 2020-10-08 00:29 UTC
Labels: bug
