### ISSUE TITLE
If you Control+Right Arrow in the editor and pass over a pill your cursor is reset to the beginning of the text

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#15366] opened 2020-10-02 15:38 UTC
### Description

Video of the issue: https://streamable.com/j151lc

I use Ctrl+Right Arrow (and left arrow) to go quickly back and forth when writing a message. I've noticed that in Element if you do this while passing over a pill, your cursor will be reset to the beginning of the text field. Oddly, if there's a space at the beginning of the text field, then the cursor will be reset to the end of the first word.

### Steps to reproduce

- Enter some text with a pill in it. User and room pills both work.
- Try to Ctrl-Right Arrow past it
- Your cursor gets taken to the beginning of the line

Logs being sent: yes

### Version information

**I can reproduce this on:**

- **Platform**: desktop
- **OS**: Debian Linux
- **Version**: 1.7.8

**I cannot reproduce this on:**

- **Platform**: browser
- **Browser**: Firefox Nightly 83.0a1 (2020-09-24)
- **OS**: Debian Linux
- **URL**: develop.element.io

This has been a bug for a while, I don't think it's a recent regression.

**Comment by t3chguy** [comment] 2020-10-02 21:17
Duplicate of https://github.com/vector-im/element-web/issues/15037

**Closed by t3chguy** 2020-10-02 21:17 UTC
Labels: bug
