### ISSUE TITLE
Add ability to switch between input devices if multiple cameras/microphones are available

### ISSUE THREAD

**Issue by passw0rd123** [vector-im/element-web#18919] opened 2021-09-06 08:35 UTC
#### What would you like to do?
If a device has multiple input devices such as a second external webcam (or an obs virtual webcam) or multiple microphones (internal and bluetooth) there should be a setting to choose one specific before joining a call or maybe even to change it in call.

#### Why would you like to do it?
In Element Desktop there seems no such option to choose an input device other than the primary OS input device. While using element-web you can do the device selection e.g. in Firefox when the client is asking for permissions. But if you choose to save your granted permission you are not aked again. This is more like a workaround and not a convinient method to use element for calls.

#### How would you like to achieve it?
There sould be a setting in the call interface to choose the devices as also a default setting option in the preferences/settings menu.

**Comment by robintown** [comment] 2021-09-07 01:32
Duplicate of https://github.com/vector-im/element-web/issues/15595

**Closed by robintown** 2021-09-07 01:32 UTC
Labels: T-Enhancement
