### ISSUE TITLE
Plain text emoji parsing converts text to emoji when not intended

### ISSUE THREAD

**Issue by rda0** [vector-im/element-web#19569] opened 2021-11-01 12:22 UTC
### Steps to reproduce

1. Enable **Automatically replace plain text Emoji**
2. Try to write `MXID: @user:server`

#### What did you expect?

Beeing able to write `MXID: @user:server` without having to disable **Automatically replace plain text Emoji**

#### What happened instead?

The text gets converted to `MXI😩r:server` while typing.

### Operating system

Windows 10

### Application version

Element version: 1.9.3 Olm version: 3.2.3

### How did you install the app?

https://element.io/get-started

### Will you send logs?

No

**Comment by rda0** [comment] 2021-11-01 12:23
This is probably a duplicate of #19472

**Comment by t3chguy** [comment] 2021-11-01 12:51
Closing as duplicate of https://github.com/vector-im/element-web/issues/19472

**Closed** 2021-11-01 12:51 UTC
Labels: T-Defect
