### ISSUE TITLE
Space members aren't ordered in an obvious way

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17168] opened 2021-05-04 22:21 UTC
On my test account the order appears random, but on the account which created the space it seems appropriately ordered as Admins then displayname.

**Comment by t3chguy** [comment] 2021-05-05 15:04
Strange, it uses the standard MemberList panel for a room, so the ordering should be no different than for a room

**Comment by yannicka** [comment] 2021-12-29 14:34
I can't reproduce the problem. Do you have an example of an affected space?

**Comment by t3chguy** [comment] 2022-01-04 08:45
Closing due to not enough information and inability to reproduce

**Closed by t3chguy** 2022-01-04 08:45 UTC
Labels: T-Defect, X-Cannot-Reproduce, A-Spaces
