### ISSUE TITLE
media not showing in chat

### ISSUE THREAD

**Issue by tinsel-grumble** [vector-im/element-web#18495] opened 2021-08-11 16:34 UTC
### Steps to reproduce

1. start conversation with someone
2. person attach media to chat to share
3. see blank space/no show media
4. ask person to share other way, which is not always encrypt like element

### What happened?

when media share in element desktop nothing show in chat. popup for download is there if know to look at the spot, but looks like nothing. in experimental appearance there is almost not even blank line in spot. all media type affected, worked in old version fine with a block and "show" button

test with normal appearance, "modern" and experimental irc style. all same. otherwise no setting change after login to client

### What did you expect?

placehold or indicate of media to look at in the chat. option to download still available

### Operating system

windows

### Application version

element 1.7.3.4, olm 3.2.3

### How did you install the app?

install from element.io

**Comment by SimonBrandner** [comment] 2021-08-11 16:43
I don't think I am able to repro this

**Comment by tinsel-grumble** [comment] 2021-08-11 16:45
i can do a clean install if help or if you want me to change a setting. just need to start somehow to fix. my and contact share lots of media and is disruptive

**Comment by tinsel-grumble** [comment] 2021-08-11 17:20
i can also reproduce in web version using firefox 91

**Comment by victor-hg** [comment] 2021-08-13 14:30
Hello,
I can confirm media display has broke a few days/weeks ago. I do not remember when exactly. Same version as above, on windows, and in Chrome as well.
Fresh install of Element windows on a different machine, going where pictures should be in a private room. The picture doesn't show, but the hover menu with " download react reply options" shows up. If i click download, then open, the pictures opens properly but there's no preview in chat.
I can provide more information if needed.

**Comment by tinsel-grumble** [comment] 2021-08-15 15:37
@victor-hg were you able to fix? i did temp by making new account but that broke too.

**Comment by dbkr** [comment] 2021-08-17 12:41
So it's specific to certain accounts? Can you submit debug logs from settings please? I think this is the only way we stand any chance of finding out what's going on here. Also some more detailed repro steps would help, eg. how are you uploading the media? Clicking the paperclip icon? Drag & drop? What type of media? Are there any screenshots you could provide?

**Comment by victor-hg** [comment] 2021-08-17 20:10
Not sure if debug logs will attach correctly to this issue, I added the current url to the submit debug log menu.

I am drag and dropping items, and they upload correctly but don't show a preview once it's done. Using the paper clip icon also uploads files successfully. It show the preview modal window of the file before uploading, I click upload, it uploads. I see the media in the android app, but don't see it in the desktop app. I also don't see a preview of media posted by other people. 
Any regular image, jpg and png mostly, but gif don't display their preview picture either.

See [this image](https://i.imgur.com/pKEfi0f.png) for a view of the app with media not showing  ( other content redacted for privacy)

I am short on time for the moment so I can't post more, but I could probably screen record, a few days from today.

To answer @tinsel-grumble , I was not able to fix, but apart from fresh installing and logging in a new web browser, on a new computer, I haven't tried much.

**Comment by tinsel-grumble** [comment] 2021-08-22 18:06
> 
> 
> So it's specific to certain accounts? Can you submit debug logs from settings please? I think this is the only way we stand any chance of finding out what's going on here. Also some more detailed repro steps would help, eg. how are you uploading the media? Clicking the paperclip icon? Drag & drop? What type of media? Are there any screenshots you could provide?

issue happens on new account too so not account specific. any type of media and any way i upload them. also if others share with me is missing, which means i do nothing in those case. screenshot looks like @victor-hg posted in my client

**Comment by victor-hg** [comment] 2021-08-30 10:38
Hello,
I think the app updated, and the problem is now fixed for me. There was no action from my part.
Element version: 1.8.1
Olm version: 3.2.3

All media now show correctly in the windows app and the web version.
If anything was done to fix this in the background, thanks! 
(thanks anyway, the app's working nicely)

**Closed** 2021-09-07 14:19 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, A-Timeline, A-Media, O-Low
