### ISSUE TITLE
Option to change the default notification sound and its volume

### ISSUE THREAD

**Issue by monstro1** [vector-im/element-web#17100] opened 2021-04-28 22:37 UTC
I think the notification sound for element is way too loud. I have the option to change the sounds for individual rooms, but having to do each room individually is a real pain.

**Comment by SimonBrandner** [comment] 2021-04-29 05:45
Duplicate of [#5891](https://github.com/vector-im/element-web/issues/5891) and [#4192](https://github.com/vector-im/element-web/issues/4192)

**Closed by SimonBrandner** 2021-04-29 05:45 UTC
Labels: T-Enhancement
