### ISSUE TITLE
Performance regression in Element desktop 1.10.9 on Linux

### ISSUE THREAD

**Issue by catscratchedme** [vector-im/element-web#21802] opened 2022-04-14 15:37 UTC
### Steps to reproduce

I believe this happened on update 1.10.9 on Element desktop on Linux

1. Scrolling through the timeline has become more laggy and less responsive
2. Scrolling up and down on the timeline in Element desktop use to be smooth. Now, if I scroll up and down, it is laggy and jittery. (The messages have already been loaded into cache, so it is not a matter of loading messages from the server
3. I have already tried clearing cache and reloading, but this doesn't fix the problem

I don't see this issue in Element web in the browser (Element version: 1.10.8
Olm version: 3.2.8)

#### What did you expect?
To see the same level of performance and responsiveness as before

#### What happened instead?
The Element desktop client is now slow and laggy/jittery

### Operating system

Linux Mint 20.3

### Application version

Element version: 1.10.9 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started#linux-details

### Will you send logs?

No

**Comment by dbkr** [comment] 2022-04-14 16:17
Probably the same as https://github.com/vector-im/element-web/issues/21793

**Comment by robintown** [comment] 2022-04-16 23:16
Duplicate of https://github.com/vector-im/element-web/issues/21793

**Closed by robintown** 2022-04-16 23:16 UTC
Labels: T-Defect
