### ISSUE TITLE
Nightly won't shut down cleanly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#14971] opened 2020-08-15 11:13 UTC
Trying to quit Nightly leaves it hanging in a limbo state, needing to be force-quit to actually exit.  (This on Catalina).

**Comment by t3chguy** [comment] 2020-08-19 09:00
Duplicate of https://github.com/vector-im/element-web/issues/14123

**Closed by t3chguy** 2020-08-19 09:00 UTC
Labels: bug
