### ISSUE TITLE
Non-"selected" emojis don't get preformatted upon sending

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19176] opened 2021-09-26 09:48 UTC
### Steps to reproduce

1. Type any emoji, but don't select it (e.g. `:eyes:`, but raw)
2. Send it out
3. Observe raw `:eyes:` in the timeline

### What did you expect?

Any non-parsed emoji to get parsed upon sending, so `:eyes:` turning into :eyes:

### What happened?

All non-parsed emoji being sent as-is

### Operating system

Linux

### Application version

Element version: 1.8.5 Olm version: 3.2.3

### How did you install the app?

Flatpak

### Homeserver

jboi.nl

### Have you submitted a rageshake?

No

**Comment by ShadowJonathan** [comment] 2021-09-26 09:49
Here is a video showcasing the effect, amongst other bugs (already noted in other issues);

https://user-images.githubusercontent.com/22740616/134802768-26a44ddb-c0ce-4a39-bbf5-bdc50053f3d4.mp4

**Comment by SimonBrandner** [comment] 2021-09-26 09:55
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/7256

**Closed by SimonBrandner** 2021-09-26 09:55 UTC
Labels: T-Defect
