### ISSUE TITLE
Message previews show redacted messages

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#26149] opened 2023-09-09 19:59 UTC
### Steps to reproduce

1. Send a message with message previews enabled
2. Redact it

#### What did you expect?

The preview to be redacted.

#### What happened instead?

The message contents were visible for minutes. My theory is the room list components didn't get an update triggered, so they had no reason to get the newest message preview.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023090901 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-09-11 08:59
Duplicate of https://github.com/vector-im/element-web/issues/17893

**Closed by t3chguy** 2023-09-11 08:59 UTC
Labels: T-Defect
