### ISSUE TITLE
"Something went wrong!"

### ISSUE THREAD

**Issue by EEKIM10** [vector-im/element-web#16780] opened 2021-03-25 12:24 UTC
### Description

logged in and got "something went wrong"

### Steps to reproduce

- log in
-  reload (a lot, spam it)
after a while it'll break

Describe how what happens differs from what you expected.

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Chrome 89.0.4389.90
- **OS**: Windows
- **URL**: app.element.io

**Comment by EEKIM10** [comment] 2021-03-25 12:25
clearing cache fixes

**Comment by SimonBrandner** [comment] 2021-03-25 12:25
Duplicate of [#16765](https://github.com/vector-im/element-web/issues/16765)

**Closed by SimonBrandner** 2021-03-25 12:25 UTC

**Comment by turt2live** [comment] 2021-03-26 04:14
This does not appear to be a duplicate of https://github.com/vector-im/element-web/issues/16765, however constantly killing the app with reloads isn't exactly a supported operating mode.

If this happens without mashing reload, please report a bug.
