### ISSUE TITLE
[Feature request] support gemini url (gemini://)

### ISSUE THREAD

**Issue by fouine95** [vector-im/element-web#16417] opened 2021-02-09 15:13 UTC
Hello,

Thank you for the great work on this project !

Please add a way to support URL with gemini protocol scheme like:

gemini://www.underworld.fr/

or

gemini://gemini.bortzmeyer.org/fosdem/

Thank you

**Comment by t3chguy** [comment] 2021-02-09 15:20
Duplicate of https://github.com/vector-im/element-web/issues/15018

**Closed by t3chguy** 2021-02-09 15:20 UTC
Labels: suggestion
