### ISSUE TITLE
clicking permalinks for search results can result in permalinks being off the bottom of the page

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6126] opened 2018-02-12 12:11 UTC
by quite a long way. i think this is a regression. although my window was quite large

**Comment by turt2live** [comment] 2018-02-12 14:02
Duplicate of https://github.com/vector-im/riot-web/issues/4121

**Comment by t3chguy** [comment] 2022-05-23 19:14
This was fixed recently through [RAF](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)

**Closed by t3chguy** 2022-05-23 19:14 UTC
Labels: T-Defect, P2, S-Major, A-Timeline
