### ISSUE TITLE
Always clear unread status in room and send read receipt when using "Mark as read" feature

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#25611] opened 2023-06-15 16:16 UTC
#### What would you like to do?

Always clear unread status in room and send read receipt when using "Mark as read" feature

#### Why would you like to do it?

The "Mark as read" features are not reliable and can often have no effect leaving your room still as unread.

(whether pressing escape or using the "Mark as unread" option)
![](https://github.com/vector-im/element-web/assets/558581/a09d6e27-70d5-42ba-856d-714b013ac97b)

#### How would you like to achieve it?

Make the [`clearRoomNotification(...)`](https://github.com/matrix-org/matrix-react-sdk/blob/dd46db4817abe2e51c66adf9ae3f9b09b0d18464/src/utils/notifications.ts#L62-L94) logic robust:

 - Always choose the latest event
    - The logic around the latest event is obviously flawed because it uses event timestamps (untrusted and there so many race conditions where your perfectly accurate timestamp event can be behind or in front of another). It needs to use the latest event according to the DAG
    - `lastThread` has the same timestamp based flaws
    - Do we really not have access to a unthreaded timeline where we can just grab the latest event from `/sync` and `/messages`?
 - If it's a decision between two events, just send receipts for both anyway
 - Even if the app already believes it sent a receipt and is caught up, just send it again
 - Add feedback when an error occurs
 - Clearing notification counts as a last ditch effort without sending the receipts to back that up is just a recipe to have the unreads appear after refresh.

**Comment by t3chguy** [comment] 2023-06-19 09:53
> Even if the app already believes it sent a receipt and is caught up, just send it again

As far as I can see it sends a read receipt unconditionally already..?

![image](https://github.com/vector-im/element-web/assets/2403652/d1f1ab67-a4ba-48cf-8a49-3ddbb70fbb9c)

I just pressed the button a few times and it sent the same RR.

<img width="353" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/78043f26-e7f2-4ac1-99a2-708377b2efa9">

> Do we really not have access to a unthreaded timeline where we can just grab the latest event from /sync and /messages?

No as we ideally would not be paginating (`/messages`) threaded events in the same event stream as the main timeline: https://github.com/matrix-org/matrix-spec-proposals/pull/3874 - trying to maintain a single total order timeline would require forgoing any such thing which means scrolling up in a room is slow if the room is thread-heavy, as the client will just be loading walls of thread events it cannot render in the main timeline.

> The logic around the latest event is obviously flawed because it uses event timestamps (untrusted and there so many race conditions where your perfectly accurate timestamp event can be behind or in front of another). It needs to use the latest event according to the DAG

That's tracked in https://github.com/matrix-org/matrix-js-sdk/issues/3325

**Comment by MadLittleMods** [comment] 2023-06-19 22:07
@t3chguy The point of this issue is for "Mark as read" to actually do what it says. "Mark as read" from the context menu sends read receipts but it doesn't actually accomplish the job for a variety of reasons:

(room still unread after clicking "Mark as read")
![](https://github.com/vector-im/element-web/assets/558581/1d04637b-7590-4d95-8e9e-d73c8d561caa)

If we look at the keyboard shortcut `Esc`, it doesn't do anything if you're scrolled to the bottom already. And there is actually a caveat that it only clears notifications in the main timeline so the room still remains unread. Both random details  that don't help when you're just trying to clear unreads in the room.

**Comment by t3chguy** [comment] 2023-06-20 09:44
Duplicate of https://github.com/vector-im/element-web/issues/24229

**Closed by t3chguy** 2023-06-20 09:44 UTC
Labels: X-Cannot-Reproduce, A-Notifications, T-Enhancement, O-Occasional
