### ISSUE TITLE
non-compact list turned into compact list when editing a sent message

### ISSUE THREAD

**Issue by Flupp** [vector-im/element-web#22863] opened 2022-07-15 14:28 UTC
### Steps to reproduce

Send a message containing a non-compact list:
```
A list:

- item 1

- item 2
```
Then click on the edit button for that message.

#### What did you expect?
Markdown source with a non-compact list:
```
A list:

- item 1

- item 2
```

#### What happened instead?
Markdown source with a compact list:
```
A list:

- item 1
- item 2
```

Note that compact and non-compact lists are rendered differently.

Although already closed, issues #20073 and #13474 might be related.

### Operating system

Arch Linux

### Application version

element-desktop 1.11.0-1

### How did you install the app?

Pacman / official Arch Linux repositories

### Will you send logs?

No

**Comment by robintown** [comment] 2022-07-15 17:39
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/8004

**Comment by andybalaam** [comment] 2022-07-21 15:44
Hopefully a test in `matrix-react-sdk/test/editor/roundtrip-test.ts` could have caught this - when we fix it I suggest adding one if I'm right.

**Comment by robintown** [comment] 2022-07-21 23:29
We actually used to have a test for this in test/editor/deserialize-test.js, but I [removed it in that PR](https://github.com/matrix-org/matrix-react-sdk/pull/8004#discussion_r822224907) because the syntax it expected still didn't actually parse as a non-tight list under Commonmark

**Comment by t3chguy** [comment] 2022-11-02 11:47
Duplicate of https://github.com/vector-im/element-web/issues/10725

**Closed by t3chguy** 2022-11-02 11:47 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Message-Editing, A-Composer, O-Uncommon
