### ISSUE TITLE
let /myroomnick do not change back to /nick when /myavatar changed

### ISSUE THREAD

**Issue by jiangshanghan** [vector-im/element-web#22684] opened 2022-06-29 07:55 UTC
### Your use case

Element web version on Windows system.

first, i change my nick name (or avatar, since these two things are set in same place) in "setting". 

just like: change my nickname "A" to "B".

then, the "room nickname" in every chat room (no matter it maybe write as "C" or what) also changes to "A".

because i use different "chat room nick name" in different chat rooms, so i think this ↑ is not convinient.

#### What would you like to do?

let /myroomnick do not change back to /nick when /myavatar changed.

#### Why would you like to do it?

/myroomnick changes at the same time when /myavatar changed. this is not convenient enough.

#### How would you like to achieve it?

when /myavatar changed, /myroomnick shall keep not change.

thank you! hope my poor english can make this understandable.

**Comment by SimonBrandner** [comment] 2022-06-29 15:38
Sorry, I am having a  little bit of trouble following what exactly is happening... Could you please describe how the display name changes - to what name and when?

**Comment by jiangshanghan** [comment] 2022-07-01 03:30
> Sorry, I am having a little bit of trouble following what exactly is happening... Could you please describe how the display name changes - to what name and when?

i am not very good at english. so sorry about that. i just edit the above post. please check. thank you for your patient.

**Comment by SimonBrandner** [comment] 2022-07-01 07:33
Ah, I see, thanks for the update! This would then be a duplicate of https://github.com/vector-im/element-web/issues/2458 because in reality, we don't really have per-room display names/avatars

**Closed by SimonBrandner** 2022-07-01 07:33 UTC
Labels: X-Needs-Info, T-Enhancement
