### ISSUE TITLE
Infinispinnering memberlist after accepting an invite

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#7995] opened 2019-01-03 13:57 UTC
some people [on riot-web experimental] have reported an infinispinnering memberlist after accepting an invite. Not sure if this is a client-side or server-side issue.

**Comment by turt2live** [comment] 2019-01-04 23:33
I'm not able to reproduce this. Is it possible the server is just slow? Logs would maybe show the issue here.

**Comment by t3chguy** [comment] 2022-05-10 20:50
Closing due to lack of reproduction & response, please shout if you see this again

**Closed by t3chguy** 2022-05-10 20:50 UTC
Labels: T-Defect, P1, X-Cannot-Reproduce, S-Major
