### ISSUE TITLE
It's sometimes impossible to change server in the login prompt

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18031] opened 2021-07-16 18:14 UTC
If you click the textfield to enter your new server hostname it hurls you back out again in a nightmare haunted UI manner

https://user-images.githubusercontent.com/1294269/125991483-4de85b66-026f-49ab-a0d7-fc7b8a72aef1.mov

**Comment by ShadowJonathan** [comment] 2021-07-16 18:19
is this on `develop.` or `app.`?

**Comment by SimonBrandner** [comment] 2021-07-16 18:24
I swear this is a dupe of something

**Comment by dbkr** [comment] 2021-07-16 18:25
Both. I can reliably repo this by *clicking quickly*. Yep, really. If I hold the button down even for just a tiny amount of time, it's fine, but jabbing the button really quickly reproduces the bug every time. I had a quick look and it's nothing obvious like handling mouseDown / mouseUp events in a way that would race.

**Comment by dbkr** [comment] 2021-07-16 20:30
After some more experimentation, the only thing I change that prevents this happening is making the input field not a child of the styled radio button. I tried removing all the onchange / onclick functions from the field, removing the ref and preventing the field from re-rendering on focus change - none of those made any difference.

**Closed** 2021-07-19 09:09 UTC
Labels: A-Login, T-Defect, Z-Impact-2, Z-Papercuts, Z-Visibility-2
