### ISSUE TITLE
Joining multiple rooms in a space results in error

### ISSUE THREAD

**Issue by AJCxZ0** [vector-im/element-web#24235] opened 2023-01-14 01:10 UTC
### Steps to reproduce

1. Starting in the space's list of rooms, I see the list of rooms.
2. I clicked the _join_ button for rooms I wished to join.
3. After clinking three or four _join_ button, the rooms pane is replaced with the error message:  **Something went wrong!**
4. Selecting the option to _Clear cache and reload_, the client shows the selected rooms as joined.
5. Clicking more _join_ buttons reproduces the behaviour.

#### What did you expect?

I expected to join the rooms.

#### What happened instead?

An error.

### Operating system

Fedora

### Application version

Element 1.11.17

### How did you install the app?

Flathub

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by AJCxZ0** [comment] 2023-01-15 20:02
I just submitted a second log via the client's **Submit debug logs** referencing this issue with a note, but see no logs or that note. The client reported,
> Logs sent
> Thank you!

**Comment by t3chguy** [comment] 2023-01-16 09:01
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2023-01-16 09:01 UTC
Labels: T-Defect
