### ISSUE TITLE
Don't notify unless the user was explicitly mentioned (pill)

### ISSUE THREAD

**Issue by lapin-b** [vector-im/element-web#9302] opened 2019-03-27 20:58 UTC
### Description

In a few words, whenever someone answers a message from somebody else, I get notified becasue my username is in my domain name. For example, when `@userb:usera.website` answers to `@userc:usera.website`, `@usera:usera.website` gets notified.

Here's a more visual example of what's happening:

![image](https://user-images.githubusercontent.com/3647174/55111006-a94c8380-50d9-11e9-9f40-e351856bfe0c.png)

I'm mentioned and notified despite the answer not being directed at me.

### Steps to reproduce

Take the example case from abose. If needed, I can add a list of steps to follow to reproduce the case.

What's expected: I shouldn't get notified when an answer is directed at someone else despite my username appearing in my domain name.

Log: not relevant

### Version information

- **Platform**: Desktop and web app

#### Web app

- **Browser**: Firefox 66.0.1
- **OS**: Arch Linux, kernel version 5.0.3 (if that matters)
- **URL**: Self hosted chat, version 1.0.5

#### Desktop app
- **OS**: Arch Linux, kernel version 5.0.3 (if that matters)
- **Version**: 1.0.5

**Comment by turt2live** [comment] 2019-04-02 19:05
Have altered the title to adopt this as the canonical "notifications shouldn't do anything unless I'm mentioned" issue.

**Comment by turt2live** [comment] 2019-04-02 19:07
See also:
* https://github.com/vector-im/riot-web/issues/4973
* https://github.com/vector-im/riot-web/issues/8497
* https://github.com/vector-im/riot-web/issues/5420

**Comment by grinapo** [comment] 2020-12-05 13:23
I think the current categories are "flawed" or not complete.

A user is called "dolphin" using `@elephant:kangaroo.net`.

- match on display name matches anything containing the string "dolphin"
- match on username seems to match on anything containing "elephant"

However:
- match on display name will erroneously match on "bob" @`will`:**dolphin**.net, or "jane" @**dolphin**:racoon.org
- match on username will err match on "joe" @`sam`:**elephant**.com, "**elephant**" @`snake.fi`

So 
- there is no "match on mxid" option, which **only** would match "`@elephant:kangaroo.net`" string, pill or else

And in an ideal world
- display name match should not match on hostname substrings
- username likewise shall not match on hostname substrings

**Comment by t3chguy** [comment] 2022-05-10 20:36
Duplicate of https://github.com/vector-im/element-web/issues/8431

**Closed by t3chguy** 2022-05-10 20:36 UTC
Labels: A-Notifications, T-Enhancement
