### ISSUE TITLE
Spaces Store tests fail locally but not in CI

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#19043] opened 2021-09-15 10:30 UTC
These tests intermittently fail to varying degrees on my local.

```
FAIL  test/stores/SpaceStore-test.ts (9.199 s)
  ● SpaceStore › static hierarchy resolution tests › handles a basic hierarchy

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:128:13)

  ● SpaceStore › static hierarchy resolution tests › test fixture 1 › home space contains favourites

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:332:17)

  ● SpaceStore › static hierarchy resolution tests › test fixture 1 › home space contains invites

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:332:17)

  ● SpaceStore › static hierarchy resolution tests › test fixture 1 › all rooms space does contain rooms/low priority even if they are also shown in a space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:332:17)

  ● SpaceStore › static hierarchy resolution tests › test fixture 1 › home space doesn't contain rooms/low priority if they are also shown in a space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:332:17)

  ● SpaceStore › static hierarchy resolution tests › test fixture 1 › home space doesn't contain rooms/low priority if they are also shown in a space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      87 |         const emitProm = testUtils.emitPromise(store, UPDATE_HOME_BEHAVIOUR);
      88 |         await SettingsStore.setValue("Spaces.allRoomsInHome", null, SettingLevel.DEVICE, value);
    > 89 |         jest.runAllTimers(); // run async dispatch
         |              ^
      90 |         await emitProm;
      91 |     };
      92 |

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at setShowAllRooms (test/stores/SpaceStore-test.ts:89:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:366:17)

  ● SpaceStore › context switching tests › no last viewed room in home space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:619:13)

  ● SpaceStore › context switching tests › no last viewed room in home space

    expect(received).toBeNull()

    Received: "!space2:server"

      689 |             viewRoom(room1);
      690 |             await store.setActiveSpace(null);
    > 691 |             expect(getCurrentRoom()).toBeNull(); // Home
          |                                      ^
      692 |         });
      693 |     });
      694 |

      at Object.<anonymous> (test/stores/SpaceStore-test.ts:691:38)

  ● SpaceStore › context switching tests › no last viewed room in home space

    Invariant Violation: Dispatcher.unregister(...): `ID_37` does not map to a registered callback.

      627 |         afterEach(() => {
      628 |             localStorage.clear();
    > 629 |             defaultDispatcher.unregister(dispatcherRef);
          |                               ^
      630 |         });
      631 |
      632 |         const getCurrentRoom = () => {

      at invariant (node_modules/fbjs/lib/invariant.js:39:15)
      at MatrixDispatcher.unregister (node_modules/flux/lib/Dispatcher.js:139:68)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:629:31)

  ● SpaceStore › space auto switching tests › no switch required, room is in current space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:713:13)

  ● SpaceStore › space auto switching tests › switch to canonical parent space for room

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:713:13)

  ● SpaceStore › space auto switching tests › switch to first containing space for room

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:713:13)

  ● SpaceStore › space auto switching tests › switch to home for orphaned room

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:713:13)

  ● SpaceStore › space auto switching tests › when switching rooms in the all rooms home space don't switch to related space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:713:13)

  ● SpaceStore › space auto switching tests › when switching rooms in the all rooms home space don't switch to related space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      87 |         const emitProm = testUtils.emitPromise(store, UPDATE_HOME_BEHAVIOUR);
      88 |         await SettingsStore.setValue("Spaces.allRoomsInHome", null, SettingLevel.DEVICE, value);
    > 89 |         jest.runAllTimers(); // run async dispatch
         |              ^
      90 |         await emitProm;
      91 |     };
      92 |

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at setShowAllRooms (test/stores/SpaceStore-test.ts:89:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:745:13)

  ● SpaceStore › traverseSpace › avoids cycles

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      92 |
      93 |     beforeEach(() => {
    > 94 |         jest.runAllTimers(); // run async dispatch
         |              ^
      95 |         client.getVisibleRooms.mockReturnValue(rooms = []);
      96 |     });
      97 |     afterEach(async () => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:94:14)

Summary of all failing tests
 FAIL  test/stores/SpaceStore-test.ts (9.199 s)
  ● SpaceStore › static hierarchy resolution tests › handles a basic hierarchy

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:128:13)

  ● SpaceStore › static hierarchy resolution tests › test fixture 1 › home space contains favourites

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:332:17)

  ● SpaceStore › static hierarchy resolution tests › test fixture 1 › home space contains invites

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:332:17)

  ● SpaceStore › static hierarchy resolution tests › test fixture 1 › all rooms space does contain rooms/low priority even if they are also shown in a space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:332:17)

  ● SpaceStore › static hierarchy resolution tests › test fixture 1 › home space doesn't contain rooms/low priority if they are also shown in a space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:332:17)

  ● SpaceStore › static hierarchy resolution tests › test fixture 1 › home space doesn't contain rooms/low priority if they are also shown in a space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      87 |         const emitProm = testUtils.emitPromise(store, UPDATE_HOME_BEHAVIOUR);
      88 |         await SettingsStore.setValue("Spaces.allRoomsInHome", null, SettingLevel.DEVICE, value);
    > 89 |         jest.runAllTimers(); // run async dispatch
         |              ^
      90 |         await emitProm;
      91 |     };
      92 |

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at setShowAllRooms (test/stores/SpaceStore-test.ts:89:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:366:17)

  ● SpaceStore › context switching tests › no last viewed room in home space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:619:13)

  ● SpaceStore › context switching tests › no last viewed room in home space

    expect(received).toBeNull()

    Received: "!space2:server"

      689 |             viewRoom(room1);
      690 |             await store.setActiveSpace(null);
    > 691 |             expect(getCurrentRoom()).toBeNull(); // Home
          |                                      ^
      692 |         });
      693 |     });
      694 |

      at Object.<anonymous> (test/stores/SpaceStore-test.ts:691:38)

  ● SpaceStore › context switching tests › no last viewed room in home space

    Invariant Violation: Dispatcher.unregister(...): `ID_37` does not map to a registered callback.

      627 |         afterEach(() => {
      628 |             localStorage.clear();
    > 629 |             defaultDispatcher.unregister(dispatcherRef);
          |                               ^
      630 |         });
      631 |
      632 |         const getCurrentRoom = () => {

      at invariant (node_modules/fbjs/lib/invariant.js:39:15)
      at MatrixDispatcher.unregister (node_modules/flux/lib/Dispatcher.js:139:68)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:629:31)

  ● SpaceStore › space auto switching tests › no switch required, room is in current space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:713:13)

  ● SpaceStore › space auto switching tests › switch to canonical parent space for room

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:713:13)

  ● SpaceStore › space auto switching tests › switch to first containing space for room

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:713:13)

  ● SpaceStore › space auto switching tests › switch to home for orphaned room

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:713:13)

  ● SpaceStore › space auto switching tests › when switching rooms in the all rooms home space don't switch to related space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      80 |         client.getRoom.mockImplementation(roomId => rooms.find(room => room.roomId === roomId));
      81 |         await testUtils.setupAsyncStoreWithClient(store, client);
    > 82 |         jest.runAllTimers();
         |              ^
      83 |     };
      84 |
      85 |     const setShowAllRooms = async (value: boolean) => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at run (test/stores/SpaceStore-test.ts:82:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:713:13)

  ● SpaceStore › space auto switching tests › when switching rooms in the all rooms home space don't switch to related space

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      87 |         const emitProm = testUtils.emitPromise(store, UPDATE_HOME_BEHAVIOUR);
      88 |         await SettingsStore.setValue("Spaces.allRoomsInHome", null, SettingLevel.DEVICE, value);
    > 89 |         jest.runAllTimers(); // run async dispatch
         |              ^
Fix import, convert event type to constant
      90 |         await emitProm;
      91 |     };
      92 |

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at setShowAllRooms (test/stores/SpaceStore-test.ts:89:14)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:745:13)

  ● SpaceStore › traverseSpace › avoids cycles

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      92 |
      93 |     beforeEach(() => {
    > 94 |         jest.runAllTimers(); // run async dispatch
         |              ^
      95 |         client.getVisibleRooms.mockReturnValue(rooms = []);
      96 |     });
      97 |     afterEach(async () => {

      at FakeTimers.runAllTimers (node_modules/jest-environment-jsdom-sixteen/node_modules/@jest/fake-timers/build/jestFakeTimers.js:221:13)
      at Object.<anonymous> (test/stores/SpaceStore-test.ts:94:14)


Test Suites: 1 failed, 1 skipped, 53 passed, 54 of 55 total
Tests:       12 failed, 35 skipped, 545 passed, 592 total
Snapshots:   0 total
Time:        9.811 s, estimated 11 s
Ran all test suites.
error Command failed with exit code 1.
```

**Comment by t3chguy** [comment] 2021-09-16 07:57
Cannot reproduce this, works fine for me. Might be good to include all relevant tool versions in your bug report.

**Comment by novocaine** [comment] 2021-09-16 08:16
node v16.4.2 - not sure what else is relevant

**Comment by t3chguy** [comment] 2021-09-16 09:07
I suggest using Node 14 as per the README.

**Comment by t3chguy** [comment] 2021-09-29 13:20
@novocaine did changing node version to the project specified one fix this for you?

**Comment by novocaine** [comment] 2021-10-06 09:01
This didn't help, Node 14.18

Could https://github.com/facebook/jest/issues/3465 be related?

**Comment by novocaine** [comment] 2021-10-06 09:44
Yeah, I can only speculate its some sort of timing issue related to my CPU being newer; the OP in that thread mentions sensitivity to delay

**Comment by clokep** [comment] 2022-01-21 14:49
@turt2live @novocaine Is this still an issue for either of you? Looks like the linked PR wasn't actually merged.

**Comment by turt2live** [comment] 2022-01-21 17:47
I haven't seen this lately, and I'm pretty sure a different PR fixed it (can't find it now). Issue appeared to have been caused by concurrency and overwhelmed CPU - CI has more resources and doesn't end up overloading the timers into timeout.

**Comment by kerryarchibald** [comment] 2022-01-26 11:15
Fixed for me by https://github.com/matrix-org/matrix-react-sdk/pull/7634, @novocaine can you try to recreate?

**Closed** 2022-02-10 13:09 UTC
Labels: X-Needs-Info, T-Task, A-Spaces, A-Quality, A-Developer-Experience
