### ISSUE TITLE
Leaving Space is hard to find and some menu Items points to same place

### ISSUE THREAD

**Issue by yaya-usman** [vector-im/element-web#21827] opened 2022-04-16 15:45 UTC
#### What would you like to do?
- firstly I realized if i wanted to leave a space, i have to go to the settings of the space first before i can leave. Which i think for smoother user experience, there should be a one click menu item to leave the space without directing me to another unrelated modal.
- Secondly if i decided to visit my space dashboard or home i realized the `space home` and `manage & explore rooms`  both points to the same dashboard which i find again a less smoother user experience, each menu item should have a specific purpose.
- Below image is the current status
![1](https://user-images.githubusercontent.com/38439166/163681437-69ddec07-43ce-4efc-b483-f4eb19c89ab9.PNG)

#### Why would you like to do it?
Better user experience.

#### How would you like to achieve it?

- Removing the `manage & explore rooms` menu item, it doesn't fit properly in my opinion since there is a beta feature coming up involving space within space and we will want to manage space as well, so leaving only `space home` or renaming it `Manage space` i guess is fine.
- including the `leave  space` button within the space menu items.
![2](https://user-images.githubusercontent.com/38439166/163681649-bf800e9d-bb89-4c43-a84f-e12bdef32c13.PNG)

**Comment by robintown** [comment] 2022-04-16 23:39
Duplicate of https://github.com/vector-im/element-web/issues/16493 and https://github.com/vector-im/element-web/issues/21000

**Closed by robintown** 2022-04-16 23:39 UTC
Labels: T-Enhancement
