### ISSUE TITLE
Cannot mark room as read

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#26640] opened 2023-11-24 12:20 UTC
### Steps to reproduce

1. `!UVEsOAdphEMYhxzTah:grapheneos.org` had a red "admin upgraded this room" event, an `@room` message was sent, then two more upgraded events in the timeline
2. See red notification for the room
3. In the left panel, click ⋯ -> "Mark as read"

#### What did you expect?
Room marked as read when I looked at it
Room marked as read when I clicked "Mark as read"

#### What happened instead?
Room is persisting unread for 2 since yesterday. I think it was temporarily marked as read the first time I went to the room after those events but was marked as unread again after updating develop

### Operating system

Arch Linux

### Browser information

Chromium 118.0.5993.88

### URL for webapp

develop.element.io

### Application version

Element version: c378f676fde2-react-a6705304aa43-js-af9993a710ae Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-11-24 12:21
Duplicate of https://github.com/vector-im/element-web/issues/24392

**Closed by t3chguy** 2023-11-24 12:21 UTC
Labels: T-Defect
