### ISSUE TITLE
Room avatars are clipped

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18180] opened 2021-07-22 10:54 UTC
Screenshot/more info coming. On develop, the bottom of the room avatars are clipped in some cases.

**Comment by jryans** [comment] 2021-07-22 10:55
Duplicate of https://github.com/vector-im/element-web/issues/18100

**Comment by t3chguy** [comment] 2021-07-22 10:55
beat me to it!

**Closed by jryans** 2021-07-22 10:55 UTC
Labels: P1, X-Release-Blocker
