### ISSUE TITLE
“Hide profile/room images” settings option …

### ISSUE THREAD

**Issue by fooness** [vector-im/element-web#13100] opened 2020-04-09 11:06 UTC
It would be very good to offer an option to “Hide profile/room images”, or, `enable` and `disable` said images via some settings option. Definitely would be good for distractionless mode …

**Comment by aaronraimist** [comment] 2020-04-11 02:53
Are you talking about the 
- avatars in the room list and the user list
- images posted in rooms
- or the messages in the room saying that someone has changed their profile picture or the room avatar?

**Comment by fooness** [comment] 2020-04-11 10:23
Avatars in the room list and the user list.

**Comment by aaronraimist** [comment] 2020-04-11 17:14
This is basically duplicate of https://github.com/vector-im/riot-web/issues/6982 then

**Comment by MadLittleMods** [comment] 2021-09-02 04:57
Closing in favor of https://github.com/vector-im/element-web/issues/11900 since the focus seems to be on "Avatars, everywhere."

**Closed by MadLittleMods** 2021-09-02 04:57 UTC
Labels: T-Enhancement
