### ISSUE TITLE
Increase the max height of the composer

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18024] opened 2021-07-16 15:09 UTC
#### Is your suggestion related to a problem? Please describe.
Compared to other platforms, Element's composer height is quite restrictive.

<details>
<summary>Comparisons</summary>

Element, ~10%;

![image](https://user-images.githubusercontent.com/22740616/125968841-643a46fe-6e0d-408d-a43a-99d5ef5aa52f.png)

Telegram, ~15-20%;

![image](https://user-images.githubusercontent.com/22740616/125968917-20b678f1-81be-4233-9187-a8522463d03c.png)

Discord, ~50%;

![image](https://user-images.githubusercontent.com/22740616/125968984-f7d5923a-8aac-4cdd-a4c6-f340024fa547.png)

Slack, ~70%;

![image](https://user-images.githubusercontent.com/22740616/125969156-219e8917-c209-41ec-81cc-1784d3d93179.png)

</details>

#### Describe the solution you'd like.
Increase the composer height to 33% or 50% the window height.

**Comment by t3chguy** [comment] 2021-07-16 15:09
Duplicate of https://github.com/vector-im/element-web/issues/5882

**Closed by t3chguy** 2021-07-16 15:09 UTC
Labels: T-Enhancement
