### ISSUE TITLE
Scroll jump in room list with sticky headers

### ISSUE THREAD

**Issue by moritzdietz** [vector-im/element-web#19848] opened 2021-11-22 16:13 UTC
### Steps to reproduce

https://user-images.githubusercontent.com/7935536/142895943-4d683722-ed47-41ca-995f-66d4055a052b.mov

 

#### What did you expect?
Regardless of the windows size the scroll bar should not have a velocity / bounce effect.
All other scroll-y bits of the application don't suffer from this issues.
#### What happened instead?
Scrolling down bounces

### Operating system

macOS 12.0.1

### Application version

Version 1.9.5 (1.9.5)

### How did you install the app?

https://element.io/get-started#download

### Homeserver

moritzdietz.com

### Will you send logs?

Yes

**Comment by moritzdietz** [comment] 2021-11-22 16:14
Not sure if it's related to #10121

**Comment by moritzdietz** [comment] 2021-11-23 11:47
One thing to add is that the amount of bounce is related to the amount of speed when you scroll. Slower down scrolling causes slower bounces and faster scrolling causes faster bounces.

**Comment by MadLittleMods** [comment] 2022-02-24 16:13
Duplicate of https://github.com/vector-im/element-web/issues/19322

**Closed by MadLittleMods** 2022-02-24 16:13 UTC
Labels: T-Defect, S-Minor, A-Room-List, O-Uncommon
