### ISSUE TITLE
New login, was this you? popup won't go away

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18971] opened 2021-09-09 14:20 UTC
### Steps to reproduce

Logged in with Element iOS and verified the device

Then received the New Login. Was this you? popup

It didn't hide after I click "check my devices" or "later".

### What did you expect?

For the dialog to go away. I'm not sure why it was necessary for it to be visible at all, given I verified the device in the same Element Web instance

### What happened?

The dialog won't go away.

Note that this only happened once, and I wasn't able to replicate afterwards.

### Operating system

OS X

### Application version

Element Nightly version: 2021090901 Olm version: 3.2.3

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by robintown** [comment] 2021-09-09 15:24
Duplicate of https://github.com/vector-im/element-web/issues/17667

**Closed by robintown** 2021-09-09 15:24 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Minor, O-Intermediate
