### ISSUE TITLE
handle arbitrary URLs

### ISSUE THREAD

**Issue by scbarton** [vector-im/element-web#26113] opened 2023-09-04 15:09 UTC
#### What would you like to do?

I would like to include URL/URIs beyond just http, https and mailto as links within messages.

#### Why would you like to do it?

I share obsidian notes with my team, and I would like to be able to use `obsidian://` links to point to specific notes. This would also be useful for `evernote://` notes and probably a bunch of other protocols. 

#### How would you like to achieve it?

Wherever links can be included, make links such as the above clickable and resolvable. I don't know what is involved, but I do know that Element X handles such links, as do other similar apps.

### Have you considered any alternatives?

I have looked at Element X, which does support arbitrary URLs. However, many features are still missing there.

### Additional context

I have kept an eye on Element as an open-source replacement for Slack, and this is a key feature keeping us from making the switch, the other being custom emoji.

**Comment by t3chguy** [comment] 2023-09-04 15:10
Duplicate of https://github.com/vector-im/element-web/issues/15018

**Closed by t3chguy** 2023-09-04 15:10 UTC
Labels: T-Enhancement
