### ISSUE TITLE
Element Desktop: Duplicate message index

### ISSUE THREAD

**Issue by lanerussell** [vector-im/element-web#16428] opened 2021-02-10 16:37 UTC
### Description

Intermittently, messages are appearing with error: `** Unable to decrypt: Error: Duplicate message index, possible replay attack`. This doesn't always happen from a specific sender. Messages before and after the affected message generally appear correctly. Clicking `Re-request encryption keys from your other sessions.` has no effect. This happens on all 3 of my Element Desktop sessions.

In my case, these are not due to duplicate messages, they are due to actual messages from my contacts. I'm able to read these messages normally in Element Android. For reference, I set up all of my sessions by scanning the QR code with my Element Android session for verification. I have green shields with all contacts where this issue is occurring.

### Steps to reproduce

- Receive message on Element Desktop
- Intermittently, messages from various senders shows error:
`** Unable to decrypt: Error: Duplicate message index, possible replay attack`

Describe how what happens differs from what you expected.
- If most messages are able to be decrypted correctly, this error should not be appearing for random messages.

Logs being sent: yes

Element Desktop:
![element-desktop](https://user-images.githubusercontent.com/20979879/107540611-d8fcbb80-6b8b-11eb-87a9-8fb459dcfa8a.png)

Element Android:
![element-android](https://user-images.githubusercontent.com/20979879/107539843-fb420980-6b8a-11eb-913f-3cf556c41eb4.png)

### Version information

- **Platform**: Desktop
- **OS**: Ubuntu 20.04
- **Version**: 1.7.20

**Comment by harbinger0x7c0** [comment] 2021-02-10 18:53
I am seeing this behavior on the desktop client (windows 10) and the web client (running in Chrome), but messages which are failing to decrypt in the browser and the desktop app decrypt without issue on the Android client.

**Comment by AtomicRPM** [comment] 2021-02-11 16:03
I am experiencing this this with the desktop client as well. Another symptom i have observed is a posted image will suddenly disappear on other devices. Refreshing the cache on those devices does not force the image to reappear. 

The disappearing image always preceeds the “duplicate message possible replay attack” error message.

**Comment by AtomicRPM** [comment] 2021-02-12 03:14
I just built the latest element-web and signed into my HS and when the room was loading this appeared.

![image](https://user-images.githubusercontent.com/58311072/107726289-4e0be600-6c9d-11eb-91da-b7ab76081b6a.png)

**Comment by AtomicRPM** [comment] 2021-02-12 03:27
Here is the error

2021-02-11 19:26:31,928 - synapse.http.server - 74 - INFO - GET-4679 - <SynapseRequest at 0x7f10c0982e20 method='GET' uri='/_matrix/client/r0/room_keys/version' clientproto='HTTP/1.0' site='8448'> SynapseError: 404 - No backup found

**Comment by AtomicRPM** [comment] 2021-02-12 04:53
I am able to reproduce.

Sign in with web client.
Perform device key verification between first mobile device and web client.
Post image from first mobile device.
Image is seen in room.
Different user replies from second mobile device.
Next message posted from first mobile device produces unable to decrypt error message.

Synapse version
{
    "server_version": "1.26.0",
    "python_version": "3.8.5"
}

Element-web 1.7.20
IOS 1.1.7

![image](https://user-images.githubusercontent.com/58311072/107731354-a695b000-6caa-11eb-95bf-f0d24128b8e6.png)

**Comment by AtomicRPM** [comment] 2021-02-13 06:28
Here's a video.

https://www.youtube.com/watch?v=hnpILIIo9ek

**Comment by AtomicRPM** [comment] 2021-02-13 08:28
Where is Art|Code

**Comment by tleydxdy** [comment] 2021-02-27 14:28
Saw this in normal group chat as well, out of the blue, and no pictures posted before it. I was a reply tho.
Element version: 1.7.21
olm version: 3.2.1

on android it works fine

**Comment by localguru** [comment] 2021-03-01 12:06
Same problem here. Message on Andriod App is decrypted, on Desktop Client and iOS message is encrypted with `** Unable to decrypt: Error: Duplicate message index, possible replay attack` error. Re-request encryption keys from your other sessions. has no effect. This problem is reported be several users.

**Comment by localguru** [comment] 2021-03-01 12:13
@electricOzone if you clear the cache  in your desktop client, the message will be decrypted there too. Just tested it with the Linux desktop client. Hmmm ... so there must be a difference to the Andriod client, which doesn't have this problem.

**Comment by localguru** [comment] 2021-03-01 12:26
The following clients are affected by this problem: Linux V 1.7.20, MAC V 1.7.21, iPad V 1.2.1. Clearing the cache decrypts the message on all clients.

**Comment by AtomicRPM** [comment] 2021-03-01 13:50
Cleaning cache does not decrypt message for me. I am using the latest version of element web.

**Comment by harbinger0x7c0** [comment] 2021-03-05 05:04
Clearing the cache in the web version does not work for me either.

**Comment by thegcat** [comment] 2023-02-28 11:36
We also observe this issue, though I first thought this affected all other sessions other than the sending element iOS and I filed it there, see https://github.com/vector-im/element-ios/issues/7376.

See https://github.com/vector-im/element-ios/issues/7376#issuecomment-1448009641 for a video reproducing the error and following discussion that this might not be an element iOS issue.

**Comment by airforceixi** [comment] 2023-04-04 19:18
Observing the same issue. Occurs with Element on Windows, macOS, Linux, and Web. iOS appears fine. Clear cache resolved the most recent occurrence, however past messages that came through without issue are now presenting the issue when scrolling back. Occurs with **BOTH** users in both a direct message as well as a newly formed room.

**Comment by jacotec** [comment] 2023-04-14 08:59
Same here! Mostly after the other party has sent a picture. Clearing cache does not solve it and it's happening with the same messages on all Desktop and Web sessions.

See my comment in #25108 ... I think it is in fact not a key issue, but an Element-Web / Desktop issue where these messages are mistakenly interpreted as a "replay attack" (which they are in fact not).

IOS and Android apps are all fine in these chats!

**Comment by lychnikon** [comment] 2023-04-16 05:35
Same issue happening. reinstalled Element desktop and continues to produce errors even after reset/reload, and total reinstall & reverify. started suddenly today, using for years.

**Comment by jittygitty** [comment] 2023-04-25 07:12
I just got this error recently also....
""** Unable to decrypt: Error: Duplicate message index, possible replay attack: TD/M9fZ+....+ygd3iDP/U|0 **
Re-request encryption keys from your other sessions."

Apparently, it was because of a duplicate message, the person I was talking with sent me screenshot which showed that the message that gave me that error above was an exact duplicate of the previous message right above it. Now I don't know if the chat glitched and created the duplicate message itself or if he had done it accidently.

**Comment by neutralinsomniac** [comment] 2023-04-26 00:33
Myself and a friend both have this issue on the exact same message. iOS shows fine, Android shows fine, element-web shows the duplicate message index error.

**Comment by tnsasse** [comment] 2023-04-30 11:04
Same problem, iOS shows the message fine, element-desktop is unable to decrypt

```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: DecryptionError: Duplicate message index, possible replay attack: grzwPC3AyZHdXgosbqC/nEguJfKRX7WGuNP4PI4KABo|0dW6mPq/CMD/Wjl0ClAsiuHtThH73iIHZBCH6A7Zh1A|3 **"
  }
}
```

**Comment by patricksjackson** [comment] 2023-05-04 17:14
It looks like the likely root cause of the most common scenario has been found in https://github.com/vector-im/element-ios/issues/7499

In short, there are probably **3 separate problems** that would be great to fix:
* iOS Element is broken when using the **iOS Share Extension**
* iOS (and Android?) Element is too lenient in decrypting, and should also display an error/warning when it sees a duplicate `message_index`
* Element Web should handle this better. [Don't request keys](https://github.com/vector-im/element-web/issues/25108) because it won't help, and probably have a button for "It's not a replay attack, show me the message". Displaying the possibly replayed message with a warning is probably better than not allowing any way to view the message, but that should be discussed in a separate issue.

**Comment by einmueller** [comment] 2023-05-05 08:00
I think the broken usage of the share extension should be fixed first, not the relaxed handling of this error in mobile clients. I'm really happy, that all of my family uses android and ios apps and don't see this bug, that would lead to support requests and discussions  about "never had problems with other messengers..." *sigh*

[ beside: I'd like to have some -Wall feature like with gcc. All Warnings for tech persons and relaxed handling (and silent ignoring) of such errors for people who are not really interested in security at all. ]

**Comment by t3chguy** [comment] 2023-05-05 08:51
Closing in favour of https://github.com/vector-im/element-web/issues/25108

https://github.com/vector-im/element-ios/issues/7499 is the cause of the actual issue

**Closed by t3chguy** 2023-05-05 08:51 UTC
Labels: T-Defect, S-Major, A-E2EE, Z-UISI, O-Uncommon

**Comment by skrap** [comment] 2023-06-03 19:52
> Closing in favour of #25108
> 
> [vector-im/element-ios#7499](https://github.com/vector-im/element-ios/issues/7499) is the cause of the actual issue

Note that this issue is S:Major and #25108 is S:Minor, so closing this one in favor of that has effectively demoted the issue.
