### ISSUE TITLE
Tab completion of username now requires you to press tab twice

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#18911] opened 2021-09-05 18:17 UTC
### Steps to reproduce

1. Update to 1.8.2
2. Go to a room with many users
3. Start typing the name of one of the users
4. Press tab

### What did you expect?

The first name would be autocompleted while still allowing me to select another name from the list if that was wrong. This was the behavior in 1.8.1 and earlier releases.

### What happened?

I had to press tab a second time to autocomplete their username

### URL for webapp

1.8.2

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment] 2021-09-05 18:20
This is was intentional, afaik...

**Comment by aaronraimist** [comment] 2021-09-05 18:29
Yeah looks like it was intentional in https://github.com/matrix-org/matrix-react-sdk/pull/5659

> Autocomplete has been updated to match modern accessibility standards. Navigate via up/down arrows rather than Tab. Enter or Tab to confirm a suggestion. This should be familiar to Slack & Discord users.

> In the release notes, I think we should highlight this change as existing users will need to battle existing muscle memory and it's bound to cause friction.

This does not match Slack FTR. Slack works like Element 1.8.1 and earlier releases. You can start typing a name and press tab once and it gets autocompleted.

**Comment by joepie91** [comment] 2021-09-05 18:37
Is there some way to revert this to the old behaviour? Aside from conflicting with muscle memory and the awkward double tab that's needed for a simple highlight, it's also a lot less accessible to me - instead of "tab until I hit the right name" which doesn't require changing my focus, I now need to switch focus between multiple keys on my keyboard *and* a list on the screen to be able to navigate between the options positionally.

**Comment by novocaine** [comment] 2021-09-06 09:17
If there's only one match, it seems reasonable to simply complete to that on tab, depending on accessibility considerations.

Note that prefixing their name with @ while typing might give you the behaviour you are after? Appreciate that it's an extra keystroke.

**Comment by t3chguy** [comment] 2021-09-06 09:27
> If there's only one match, it seems reasonable to simply complete to that on tab, depending on accessibility considerations.

It'd be inconsistent with other platforms e.g Slack and lead to no way to tab out of the composer mid-word without causing a completion.

I.e writing `Tom<TAB>` currently opens the completions pane, which can be cancelled using Escape then the next Tab will move out of the composer.
With this proposal you won't see the completions pane thus won't be able to Escape to cancel and now have to remove the pill which you might not even realise was pillified when relying on a screen reader.

**Comment by novocaine** [comment] 2021-09-06 09:40
Slack does this

<img width="186" alt="Screenshot 2021-09-06 at 10 40 28" src="https://user-images.githubusercontent.com/57377/132196341-0d88c71c-ffb8-4719-98a2-e68aa1608ed4.png">

*TAB*

<img width="178" alt="Screenshot 2021-09-06 at 10 40 32" src="https://user-images.githubusercontent.com/57377/132196369-7016ca9d-406c-4dd9-a42f-f19c5d4de4ff.png">

**Comment by novocaine** [comment] 2021-09-06 09:42
Discord without a leading @ goes into control-switching mode

<img width="207" alt="Screenshot 2021-09-06 at 10 42 03" src="https://user-images.githubusercontent.com/57377/132196654-57db3f0b-f0e3-48f2-a657-68c000a04ef5.png">

*TAB*

<img width="226" alt="Screenshot 2021-09-06 at 10 42 06" src="https://user-images.githubusercontent.com/57377/132196672-379a4e4e-a955-4e06-bdba-3ab8e26c634a.png">

*TAB*

<img width="1304" alt="Screenshot 2021-09-06 at 10 42 12" src="https://user-images.githubusercontent.com/57377/132196696-17f74067-76fb-416e-88d8-f51828a5a9e1.png">

**Comment by t3chguy** [comment] 2021-09-06 10:18
I'm pretty sure Slack's behaviour there has changed since the last time I used it, Slack doesn't let you pick between multiple matches though which seems like a step backwards.

**Comment by novocaine** [comment] 2021-09-06 10:42
> I'm pretty sure Slack's behaviour there has changed since the last time I used it, Slack doesn't let you pick between multiple matches though which seems like a step backwards.

yeah it's quite weird - will almost certainly pick the wrong result in a large room when there's multiple matches

**Comment by aaronraimist** [comment] 2021-09-06 19:38
> Slack doesn't let you pick between multiple matches though which seems like a step backwards.

Yes Slack doesn't let you but that doesn't mean Element can't. Element 1.8.1 autocompleted the first user but kept the selection box open so you could still pick another user.

**Comment by t3chguy** [comment] 2021-09-07 09:39
Yes, but you shouldn't change the autocomplete type depending on how you start the completion, we use `aria-autocomplete=list` mode, you need `both` mode to do what you suggest @aaronraimist - we avoid both mode to match other accessible chat platforms (Slack & Discord & more) and for it performs more sanely with screen readers.

**Comment by gnomelibre** [comment] 2021-09-07 13:44
I hate the new behavior. If multiple users in a room have their names start with the same letters, I want to be able to easily and quickly switch between them by pressing the tab key several times, which is much faster than using the tab key and then moving with the up/down arrows in a list. At worst, add an option for those who prefer the old behavior.

**Comment by aaronraimist** [comment] 2021-09-07 15:11
If it fixes accessibility I guess that is worth it. It just seemed like a bug to me that if I start the mention with @ pressing tab behaves differently than if I don't start the mention with @.

**Comment by joepie91** [comment] 2021-09-07 15:52
I have difficulty seeing how this 'fixes accessibility', to be honest, for all the reasons described above.

**Comment by t3chguy** [comment] 2021-09-07 15:56
Keyboard accessibility relies on tab being the key to move around the app which can't happen if it also traps tab to be the key to cycle suggestions.

**Comment by novocaine** [comment] 2021-09-08 10:30
Removing `X-Regression` as this change is by design to free up tab as a focus cycler, similar to Discord.

That said, there's obviously demand for alternative behaviour behind a setting.

**Comment by joepie91** [comment] 2021-09-08 12:04
> Keyboard accessibility relies on tab being the key to move around the app which can't happen if it also traps tab to be the key to cycle suggestions.

The tab key is *still* trapped, just only to initiate and complete an autocomplete now, at which point it might as well allow for cycling too. I don't really see how this is relevant here.

**Comment by t3chguy** [comment] 2021-09-08 12:38
No, because cycling is an actual trap, given it is an infinite cycle. Current implementation matches standards in Slack and Discord (Slack's autocomplete is regarded as very accessible)

Something which only intercepts a tab or two is much more usable than something that keeps you trapped in the composer in an endless cyclical list

**Comment by rda0** [comment] 2021-09-08 14:24
If you want to autocomplete a user with two tabs, but made a typo (not matching any user), then the focus will be out of the composer and `[BACKSPACE]` has no effect.

**Comment by gnomelibre** [comment] 2021-09-09 10:43
> No, because cycling is an actual trap, given it is an infinite cycle. 

This is precisely the goal. Going back to the beginning of the list when you have reached the end.

> much more usable than something that keeps you trapped in the composer in an endless cyclical list.

How can you stay trapped in an endless cyclical list when you can use the escape key (that's what it is for)...

**Comment by novocaine** [comment] 2021-09-09 10:58
I'm closing this issue as the team is comfortable with this as the default behaviour.

As mentioned above, if you are interested in alternative behaviour, create a `T-Enhancement` requesting a config flag for it, and feel free to submit a PR implementing it.

**Closed by novocaine** 2021-09-09 10:58 UTC
Labels: T-Defect, S-Minor, A-Autocomplete, X-Needs-Design, O-Low

**Comment by joepie91** [comment] 2021-09-09 14:34
@novocaine Sorry, but that feels like a really dismissive response. This is a regression in functionality for users who are used to the existing behaviour (which I imagine is going to be all IRC users in particular, but not exclusively) - not a request for *new* functionality. The way I read that comment is basically "yeah, you can file a feature request and maybe some day someone will get around to it, you'll just have to deal".

That doesn't help me, or others running into this issue. We are experiencing accessibility issues using Element *right now*, as a result of abandoning a well-established UI pattern for seemingly no clear reason, and with zero warning. This change is significantly exacerbating my RSI issues, for example, because it becomes very difficult and frustrating to highlight relevant people in busy conversations - more so because I constantly have to correct for a literal decade of muscle memory. The result is that there are entire conversations I just cannot reasonably have, and rooms I cannot talk in.

I might understand changing the default, with a good-enough rationale (though I am very skeptical of the rationale presented here so far, especially with the common references to "well $otherBigPlatform does it this way", rather than self-supporting arguments). But there should at the very least be an *option* to revert to the old behaviour, and from where I'm standing, its nonexistence is a *bug*, not a feature request.
