### ISSUE TITLE
Registration fail for some mails

### ISSUE THREAD

**Issue by PxBCPG** [vector-im/element-web#20284] opened 2021-12-20 18:48 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

For gmail.com mails, it works, but for other mail (laposte.net for example), it doesn't. 
Using synapse and relaying on vector.im for mail confirmation

2. What do you click?

Registration process

#### What did you expect?

Receive confirmation's email in order to continue registration

#### What happened instead?

Don't receive the email confirmation link with some mail adresses

### Operating system

every OSs

### Browser information

every OSs

### Homeserver

custom server running on synapse

### Will you send logs?

No

**Comment by aaronraimist** [comment] 2021-12-20 19:33
>  Using synapse and relaying on vector.im for mail confirmation

Are you sure you aren't sending your own emails? AFAIK vector.im stopped doing that in 2019 https://matrix-org.github.io/synapse/latest/upgrade#3pid-verification-changes

**Comment by t3chguy** [comment] 2021-12-21 09:41
In any case this really isn't an element-web issue

**Comment by kittykat** [comment] 2021-12-21 15:02
I'm going to close this issue for now because it isn't in element-web. Please open a new issue in [matrix-org/synapse](https://github.com/matrix-org/synapse/issues) if the issue is valid after checking how the emails are sent.

**Closed by kittykat** 2021-12-21 15:02 UTC
Labels: X-Needs-Info, A-Registration, T-Other, Z-Backend

**Comment by PxBCPG** [comment] 2021-12-24 10:01
The mail verification still work for some mail adresses.
