### ISSUE TITLE
Incorrect member count in room

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#25646] opened 2023-06-21 21:27 UTC
### Steps to reproduce

1. Open room
2. Open room info
3. Look at member count

#### What did you expect?

The room has 5 members, so I expected to see 5 as the count.

#### What happened instead?

The count is only 1. I'm not sure if it's related, but it seems to coincide with the number of online members I can see in the members list. This room is the only one in which I have noticed the issue.
I'm not comfortable sharing the room ID here because it's a small public room that I don't want to be disturbed too much, but I'll include it in the rageshake.

### Operating system

Arch Linux

### Browser information

Firefox 114.0.1

### URL for webapp

app.element.io

### Application version

Element version: 1.11.34, Olm version: 3.2.14

### Homeserver

abolivier.bzh

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-06-23 08:24
There is noting really useful in the logs. Also Brendan reported that the issue „self healed“. I am closing it now because of the lack of information. Also this may be a duplicate of https://github.com/vector-im/element-web/issues/17096

**Comment by weeman1337** [comment] 2023-06-23 08:24
Duplicate of https://github.com/vector-im/element-web/issues/17096

**Closed by weeman1337** 2023-06-23 08:24 UTC
Labels: T-Defect
