### ISSUE TITLE
Community rooms stuck in loading loop

### ISSUE THREAD

**Issue by gabrielezarcone** [vector-im/element-web#12714] opened 2020-03-12 18:36 UTC
### Description

I've started using Riot.im today and at first I've created a new community. Then I've added some new rooms I've created to this community and this worked for the first room. When I've tried to add a second room I've got stuck. The system told me this:

![Schermata 2020-03-12 alle 19 09 22](https://user-images.githubusercontent.com/48182931/76554315-f6b23400-6495-11ea-8ed2-c98e081780d9.png)

And this happen with every room I try to add to this community. 

After this I've tried refreshing the page and what happened after was even stranger: the first room I've added to the community disappeared to the list of community's rooms and it was replaced by a loading loop

![Schermata 2020-03-12 alle 19 21 37](https://user-images.githubusercontent.com/48182931/76554771-b7381780-6496-11ea-915e-b99be3805073.png)

I've tried to change browser: I was initially with Chrome and then I've tried with Safari and Firefox but the problem persisted. 

I've also tried pressing the _Clear cache and reload_ button in settings but it was useless.

What make me choose to open this issue was the fact the opening the browser console I've found several error saying: 

`Failed to get resource GroupRooms for +regalino:matrix.org `

I've not found any other issue similar to this one and I've decided to write this down. 

This is my first ever issue report in GitHub so I'm sorry if I did something wrong, but I hope this could help you. 

### Steps to reproduce

Unfortunately I've tried to reproduce this, but creating new communities I've not found any problem.

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) and desktop same problem

For the web app:

- **Browser**: Chrome, Safari and Firefox (same problem)
- **OS**: macOS
- **URL**: riot.im/develop / riot.im/app / 

For the desktop app:

- **OS**: macOS
- **Version**: 1.5.12

**Comment by bwindels** [comment] 2020-03-13 10:47
The community endpoints seem to be misbehaving, returning 500 Internal Server Error. Of course, the UI should not get stuck when that happens.

**Comment by skade** [comment] 2020-03-19 22:59
I'm experiencing a similar issue with a self-hosted synapse server, the error message being:

```
Failed to get resource GroupRooms for +oxidize1k:chat.berline.rs 
Object { errcode: "M_UNKNOWN", name: "M_UNKNOWN", message: "Internal server error", data: {…}, httpStatus: 500, stack: "" }
bundle.js:2:720627
    n https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2
    _fetchResource https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2
```

**Comment by bwindels** [comment] 2020-03-20 08:54
Thanks @skade, while you are at it, could you have a look in the synapse logs for the cause of the Internal Server Error?

**Comment by badboy** [comment] 2020-03-20 10:38
Hi, server admin behind @skade's server here.
This is what I got in the logs:

```
Mar 19 22:57:57 matrix matrix-synapse[6661]: 2020-03-19 22:57:57,852 - synapse.http.server - 110 - ERROR - GET-19535 - Failed handle request via 'GroupRoomServlet': <XForwardedForRequest at 0x7f000e4b1240 method='GET' uri='/_matrix/client/r0/groups/%2Boxidize1k%3Achat.berline.rs/rooms' clientproto='HTTP/1.0' site=8008>
Mar 19 22:57:57 matrix matrix-synapse[6661]: Traceback (most recent call last):
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Mar 19 22:57:57 matrix matrix-synapse[6661]:     result = g.send(result)
Mar 19 22:57:57 matrix matrix-synapse[6661]: StopIteration: [{'room_id': '!KZwlWkhTSkUNDrquFg:chat.berline.rs', 'is_public': False}, {'room_id': '!LSJjLKsbWZqdvBuXJa:chat.berline.rs', 'is_public': False}, {'room_id': '!UJDBxLRJoRCeIlROCH:chat.berline.rs', 'is_public': False}, {'room_id': '!wJFqQvoWQaskEAMzoB:chat.berline.rs', 'is_public': False}, {'room_id': '!G
Mar 19 22:57:57 matrix matrix-synapse[6661]: During handling of the above exception, another exception occurred:
Mar 19 22:57:57 matrix matrix-synapse[6661]: Traceback (most recent call last):
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Mar 19 22:57:57 matrix matrix-synapse[6661]:     result = g.send(result)
Mar 19 22:57:57 matrix matrix-synapse[6661]: StopIteration: [{'room_id': '!KZwlWkhTSkUNDrquFg:chat.berline.rs', 'is_public': False}, {'room_id': '!LSJjLKsbWZqdvBuXJa:chat.berline.rs', 'is_public': False}, {'room_id': '!UJDBxLRJoRCeIlROCH:chat.berline.rs', 'is_public': False}, {'room_id': '!wJFqQvoWQaskEAMzoB:chat.berline.rs', 'is_public': False}, {'room_id': '!G
Mar 19 22:57:57 matrix matrix-synapse[6661]: During handling of the above exception, another exception occurred:
Mar 19 22:57:57 matrix matrix-synapse[6661]: Traceback (most recent call last):
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/util/caches/descriptors.py", line 438, in _wrapped
Mar 19 22:57:57 matrix matrix-synapse[6661]:     cached_result_d = cache.get(cache_key, callback=invalidate_callback)
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/util/caches/descriptors.py", line 160, in get
Mar 19 22:57:57 matrix matrix-synapse[6661]:     raise KeyError()
Mar 19 22:57:57 matrix matrix-synapse[6661]: KeyError
Mar 19 22:57:57 matrix matrix-synapse[6661]: During handling of the above exception, another exception occurred:
Mar 19 22:57:57 matrix matrix-synapse[6661]: Traceback (most recent call last):
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
Mar 19 22:57:57 matrix matrix-synapse[6661]:     await h(self, request)
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 331, in _async_render
Mar 19 22:57:57 matrix matrix-synapse[6661]:     callback_return = await callback_return
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/client/v2_alpha/groups.py", line 329, in on_GET
Mar 19 22:57:57 matrix matrix-synapse[6661]:     group_id, requester_user_id
Mar 19 22:57:57 matrix matrix-synapse[6661]: AttributeError: 'NoneType' object has no attribute 'content'
```

**Comment by bwindels** [comment] 2020-03-20 11:37
Great, thank you @badboy. I have filed https://github.com/matrix-org/synapse/issues/7114 for the server error. The action point for riot would be to stop showing the spinner if the server fails to return the rooms.

**Comment by tubui88** [comment] 2020-03-29 08:16
So is there any solution for this error? Sorry I am not a technical guy just managing a community and now the same thing happened for me. Our community has around 30 rooms, previously it was ok but now the list is not displayed either in the forum page:
https://riot.im/app/#/group/+uan:matrix.org

Or on the left side command menu.

Looking forward to any solution.

**Comment by bwindels** [comment] 2020-03-30 12:22
Apologies you're being inconvenienced by this problem.

We currently don't have capacity to work on this as we're focussing on higher priority things (cross-signing and making synapse scale better to make matrix.org not slow) so unsure when we'll be able to resolve this.

We do plan on redoing communities completely in the midterm future, keep an eye on the [Riot roadmap](https://github.com/vector-im/riot-web/projects/16#card-18662333) for this.

Sorry again for not being able to provide a more satisfactory answer for now.

**Comment by skade** [comment] 2020-04-01 15:26
In this case, I recommend removing the feature all together for now. It is broken and multiple people have spent quite some time at setting it up only to later figure out it is broken.

I understand the performance problems you have, but I frequently have to link to this issue when people are asking me why I don't use communities.

**Comment by t3chguy** [comment] 2021-05-13 08:19
This is fixed by Spaces landing in Beta in next Release

**Closed by t3chguy** 2021-05-13 08:19 UTC
Labels: A-Spaces, P2, T-Defect
