### ISSUE TITLE
Element still makes sound on GNOME when Do Not Disturb is enabled

### ISSUE THREAD

**Issue by SethFalco** [vector-im/element-web#22792] opened 2022-07-10 09:20 UTC
### Steps to reproduce

1. Enable `Enable audible notifications for this session` in client settings.
2. Then get a notification, and you'll see a desktop notification and get a sound.
3. On GNOME, open the notification area and enable `Do Not Disturb`.
4. Then get a notification again. While the desktop notification doesn't appear (GNOME will silently add it to the notification area), Element still plays the sound.

#### What did you expect?

If possible, I would expect Element to check if the operating system is in a Do Not Disturb mode. If so, don't play the sound.

For UX, it'd be good to display a warning or icon next to the `Enable audible notifications for this session`, stating that the OS is in Do Not Disturb, so users know why they might not be getting sound while the setting is enabled.

#### What happened instead?

Audible notifications are still played.

### Operating system

Debian GNU/Linux 11 (bullseye) x86_64

### Application version

Element Nightly version: 2022070201
Olm version: 3.2.8

### How did you install the app?

```sh
sudo apt install element-nightly
```

### Homeserver

one.ems.host

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-07-11 06:04
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/7758

**Closed by SimonBrandner** 2022-07-11 06:04 UTC
Labels: T-Defect
