### ISSUE TITLE
matrix.to links trigger useless URL previews

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#22042] opened 2022-05-03 21:39 UTC
### Steps to reproduce

1. Paste a matrix.to link into a room
2. Stare stupidly at the useless preview it unfurls. 

<img width="614" alt="Screenshot 2022-05-03 at 22 39 04" src="https://user-images.githubusercontent.com/1294269/166570837-ec534daf-956e-47cb-8428-d2bedb489170.png">

#### What did you expect?

Either no preview, or a useful one.

#### What happened instead?

A useless one

### Operating system

macOS

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-05-03 21:45
Duplicate of https://github.com/matrix-org/matrix.to/issues/182

**Closed by t3chguy** 2022-05-03 21:45 UTC
Labels: T-Defect
