### ISSUE TITLE
Remove "X kicked X" terminology when removing people from a room

### ISSUE THREAD

**Issue by gaelledel** [vector-im/element-web#20411] opened 2022-01-05 17:24 UTC
#### What would you like to do?
To remove the wording "X kicked X" when someone is removed from a room and replace with "X removed X"

#### Why would you like to do it?
Because it is more acceptable terminology

#### How would you like to achieve it?
Change the words cross platform

**Comment by t3chguy** [comment] 2022-01-05 17:27
Duplicate of https://github.com/vector-im/element-web/issues/9547

**Closed by t3chguy** 2022-01-05 17:27 UTC
Labels: T-Enhancement
