### ISSUE TITLE
Main menu "Help"entry doesn't actually contain any helpful information

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-web#13823] opened 2020-05-27 18:35 UTC
![image](https://user-images.githubusercontent.com/105185/83058822-3f22cc00-a059-11ea-97ea-ab414c85dea4.png)

### Description

I was looking for the keyboard shortcuts, I opened the help entry form the main menu, it just told me where I could report bugs.
![image](https://user-images.githubusercontent.com/105185/83058917-61b4e500-a059-11ea-842b-5935e0279002.png)

Turns out there's an unrelated "Help & About" Section in Settings where the keyboard shortcuts are linked. Maybe the main help section could be made more useful, or link to the settings page. 
![image](https://user-images.githubusercontent.com/105185/83059097-ab9dcb00-a059-11ea-8959-123a9ca3de26.png)

riot-web version: 1.6.0
Using riot-desktop Archlinux package

**Comment by t3chguy** [comment] 2020-05-27 23:24
Related https://github.com/vector-im/riot-web/issues/12415

**Comment by Bubu** [comment] 2020-05-28 00:31
Thanks. Searching github issues for "help" was returning too many results to go through them :)

**Comment by turt2live** [comment] 2022-05-07 03:04
Effective duplicate of https://github.com/vector-im/element-web/issues/12415 (closed)

**Closed by turt2live** 2022-05-07 03:04 UTC
Labels: T-Defect, A-Feedback-Reporting
