### ISSUE TITLE
multi-paragraph reacts weirdly after escaping all markdown

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#17933] opened 2021-07-10 16:52 UTC
#### Description

The composer emits weird formatting if - on multiparagraph - you escape all markdown.

#### Steps to reproduce

Send this exact markdown in a room;

```md
test

\*test*
```

The event will be `"formatted_body": "test\n\n*test*"`. (1)

I think that paragraph stripping here is especially aggressive, as the following works and produces correct results;

```md
test

test
```
-> `"body": "test\n\ntest"` (2)

```md
test

*test*
```
-> `"formatted_body": "<p>test</p>\n<p><em>test</em></p>\n"` (3)

![image](https://user-images.githubusercontent.com/22740616/125170649-32efc480-e1b0-11eb-8c2e-cfbad4055e90.png)

(Ordering in this screenshot is 2 -> 1 -> 3)

#### Version information

- **Platform**: desktop

- **OS**: Linux PopOS 21.04
- **Version**: 1.7.32

**Comment by ShadowJonathan** [comment] 2021-08-29 19:36
This sorta seems to be a duplicate of #15320, actually

**Comment by SimonBrandner** [comment] 2021-08-30 06:10
Yeah closing as a dupe of that

**Closed by SimonBrandner** 2021-08-30 06:10 UTC
Labels: T-Defect, S-Minor, Z-Upstream, A-Composer, O-Intermediate
