### ISSUE TITLE
/var/log/syslog filling up to 50GB

### ISSUE THREAD

**Issue by kristofmulier** [vector-im/element-web#22939] opened 2022-07-27 13:02 UTC
### Steps to reproduce

Suddenly the Element app couldn't connect to the server anymore. My internet connection is a bit unstable today. That in itself is not a big deal.

However, the Element app started writing errors to the `/var/log/syslog` file up to the point that it reached 50GB and my harddrive got full.

PS: I can't reproduce the problem.

#### What did you expect?

I would expect Element to write a few lines to the `/var/log/syslog` file.

#### What happened instead?

Element blew up the size of `/var/log/syslog` up to the point that my harddrive got full and my system almost crashed.

### Operating system

Ubuntu 22.04 LTS (jammy)

### Application version

Element version: 1.11.1 Olm version: 3.2.8

### How did you install the app?

I entered the commands given at the bottom of the page https://element.io/get-started#linux-details

### Will you send logs?

No (I can't reproduce the problem)

**Comment by weeman1337** [comment] 2022-07-27 14:39
Hi @kristofmulier thanks for bringing up this issue.

> I entered the commands given at the bottom of the page https://element.io/get-started#linux-details

The link doesn't show commands for me. Did you install the DEB package?

**Comment by kristofmulier** [comment] 2022-07-27 18:13
> The link doesn't show commands for me. Did you install the DEB package?

Please go to the link and click on the Linux button:

![Screenshot_20220727-201206](https://user-images.githubusercontent.com/19362684/181342990-3309307a-c179-4494-9842-01f2ca1490c8.png)

Then you'll see the installation commands:

![Screenshot_20220727-201216](https://user-images.githubusercontent.com/19362684/181343053-8cbbab84-8457-406a-9a2f-fdac2c2a953b.png)

Those are the commands I entered to install Element.

**Comment by weeman1337** [comment] 2022-07-28 07:18
Thanks for the info @kristofmulier . Can you additionally provide some sample logs that Element is writing to `/var/log/syslog`?

**Comment by turt2live** [comment] 2023-01-10 00:18
Closing due to lack of information. If you are still seeing this, please open a new issue with fresh reproduction steps for our QA team to review.

**Closed by turt2live** 2023-01-10 00:18 UTC
Labels: T-Defect, X-Needs-Info, Z-Platform-Specific, S-Minor, A-Electron, O-Occasional
