### ISSUE TITLE
Unable to decrypt messages of certain users (bug in desktop and web version, but not iOS)

### ISSUE THREAD

**Issue by caseypaquola** [vector-im/element-web#25698] opened 2023-07-03 09:01 UTC
### Steps to reproduce

Messages from certain users are not decrypted.

The issue started suddenly two weeks ago and only occurs for certain users. It occurs in both direct messages and channels. The problem arises in both the Desktop and Browser versions. I downloaded the iOS app today and found that the problem is not present there. Though messages decrpyted in the iOS app remain encrypted in the Desktop version, despite using the Desktop session to verify the iOS session. 

#### What did you expect?
To be able to see messages from other users

#### What happened instead?
"Unable to decrypt message"

### Operating system

macOS

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-07-05 13:44
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-07-05 13:45
Duplicate of https://github.com/vector-im/element-meta/issues/245

**Closed** 2023-07-06 07:05 UTC
Labels: T-Defect, S-Critical, Z-UISI, O-Occasional
