### ISSUE TITLE
Window state (location/size) not restored after update and/or restart

### ISSUE THREAD

**Issue by rikai** [vector-im/element-web#24726] opened 2023-03-02 20:23 UTC
### Steps to reproduce

1. Snap element to a section of your desktop
2. Update Element Desktop
3. Wait for it to re-open

#### What did you expect?
The app restored to the exact same window location (1720,0) and size (1720,1410)
#### What happened instead?
The app opens at top left corner of the screen (0,0) with different window dimensions (1010,761)

This may be somewhat related to, but separate from #15852 as I only use a single monitor.

This may also have something to do with window snapping. If I window snap Element, then close and re-open the application, it does not remember dimensions, however, if I move my element window to a specific location and then close and re-open, the window location is remembered, so perhaps Element is not updating window locations and dimensions when [Windows snap](https://support.microsoft.com/en-us/windows/snap-your-windows-885a9b1e-a983-a3b1-16cd-c531795e6241) is being used?

### Operating system

Windows

### Application version

Element version: 1.11.24; Olm version: 3.2.12

### How did you install the app?

https://element.io/download

### Homeserver

non-public on synapse

### Will you send logs?

No

**Comment by YamatoRyou** [comment] 2023-03-02 23:17
#23625

**Comment by t3chguy** [comment] 2023-03-03 09:36
Duplicate of https://github.com/vector-im/element-web/issues/20940

**Closed by t3chguy** 2023-03-03 09:36 UTC
Labels: T-Defect
