### ISSUE TITLE
IRC style layout jumps around way too much

### ISSUE THREAD

**Issue by meain** [vector-im/element-web#17801] opened 2021-06-27 16:10 UTC
https://user-images.githubusercontent.com/14259816/123551435-62a1d400-d78f-11eb-9eda-e1de18d0e736.mov

### Description

The layout seems to shift around a lot. This is with me just hovering on the message. The way the name is display is also messed up if they are not under the same server as the one I am on and have a full name displayed there.

### Steps to reproduce

- Enable IRC mode
- Open any room
- Scroll or hover on items

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS 11.4
- **Version**: 1.7.31

**Comment by SimonBrandner** [comment] 2021-06-27 16:15
Duplicate of https://github.com/vector-im/element-web/issues/17778

**Closed by SimonBrandner** 2021-06-27 16:15 UTC
Labels: T-Defect
