### ISSUE TITLE
Notification sound goes off upon Element desktop restart

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#24580] opened 2023-02-20 07:58 UTC
### Steps to reproduce

1. Restart Element

#### What did you expect?

Nothing?

#### What happened instead?

A lot of notification pings happen in the background as some messages are presumably being decrypted. They usually come in pair with a highlight (red) counter, but in those case I can not spot any red on my entire account.

I have not investigated what room those pings come from

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-02-20 10:34
@gsouquet the PR title says ED specifically, but the repro steps say Web?

> Notification sound goes off upon *Element desktop* restart

> Restart *Element Web*

**Comment by MadLittleMods** [comment] 2023-02-22 19:44
Seems like a duplicate of https://github.com/vector-im/element-web/issues/24569 (see the latest comments there)

> I'm getting this some time after startup, which feels like a message got decrypted somewhere and is triggering the noise part of the notifications system

> Confirmed this is happening to rooms when the threads list is finally decrypted (the decryption loop on my account during startup takes hours to complete)

**Closed by MadLittleMods** 2023-02-22 19:44 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-Notifications, O-Uncommon
