### ISSUE TITLE
Password lock for desktop app?

### ISSUE THREAD

**Issue by br4nnigan** [vector-im/element-web#20452] opened 2022-01-10 09:24 UTC
#### What would you like to do?
Telegram works with phone numbers, not accounts. But therefore they added the option of a "local passcode" to the Desktop App which you have to enter on start. Element does not have this security feature.

#### Why would you like to do it?
For example at my office pc I want an extra layer of security.

#### How would you like to achieve it?
Element could implement this simply with the the option "save account password?"

**Comment by SimonBrandner** [comment] 2022-01-10 09:41
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/3777

**Closed by SimonBrandner** 2022-01-10 09:41 UTC
Labels: T-Enhancement
