### ISSUE TITLE
Historical rooms don't dissapear upon clicking "Forget"

### ISSUE THREAD

**Issue by hwittenborn** [vector-im/element-web#16259] opened 2021-01-24 01:40 UTC
### Description

When clicking "Forget" on a historical room, the room doesn't dissapear from the view. Rather, the app must be restarted to take effect.

### Steps to reproduce

- Click "Forget" on a historical room
- Room doesn't dissapear
- Restart App
- Room dissapears

### Describe how what happens differs from what you expected.
I expect after clicking "Forget" that the room will immediately disappear from the view, instead of needing a restart of the app.

### Version information

- **Platform**: Desktop

- **OS**: Ubuntu 20.10
- **Version**: 1.7.17

**Comment by t3chguy** [comment] 2021-01-24 01:58
Duplicate of https://github.com/vector-im/element-web/issues/15559

**Closed by t3chguy** 2021-01-24 01:58 UTC
Labels: bug
