### ISSUE TITLE
Effect for messages mentioning you could be more visually attractive

### ISSUE THREAD

**Issue by Pointedstick** [vector-im/element-web#15660] opened 2020-11-05 23:11 UTC
### Description
When a message mentions you, the text is rendered in read and the background is changed to a pale tan square:

![Screenshot_20201105_161047](https://user-images.githubusercontent.com/1097249/98306649-78a12100-1f81-11eb-8fe5-b9c3c85c99b5.jpeg)

This is not very visually attractive and I feel like there may be a better way to communicate it to the user.

### Version information
- **Platform**: desktop
- **OS**: Linux: openSUSE Tumbleweed
- **Version**: 1.7.10

**Comment by turt2live** [comment] 2020-11-05 23:14
This is largely a duplicate of https://github.com/vector-im/element-web/issues/13963

**Closed by turt2live** 2020-11-05 23:14 UTC
Labels: bug, ui/ux
