### ISSUE TITLE
Short number followed by point seems to be understood as a list

### ISSUE THREAD

**Issue by Nainterceptor** [vector-im/element-web#15640] opened 2020-11-03 10:39 UTC
### Description

When I write a single message with the following content : `2020.`, element web show a truncated list element.
![Screenshot 2020-11-03 at 11 34 35](https://user-images.githubusercontent.com/1492215/97974934-9bd4a080-1dc8-11eb-92cd-331a8b381487.png)

On my iOS app, content is not shown at all, I'll create a similar bug report into the IOS app repository

### Steps to reproduce

- write a message with `2020.` content

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 83.0b7 (firefox dev edition)
- **OS**: macOS
- **URL**: private server hosted by EMS (Riot version: v1.7.12 / olm version: 3.2.1)

**Comment by t3chguy** [comment] 2020-11-03 10:41
Duplicate of https://github.com/vector-im/element-web/issues/14621

**Closed by t3chguy** 2020-11-03 10:41 UTC
Labels: bug
