### ISSUE TITLE
Turning off Threads caused me to see chat effects

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#19804] opened 2021-11-18 17:52 UTC
### Steps to reproduce

I posted :tada: in a thread. Later, I turned Threads off and saw the chat effect for tada... 

This should not be the case as when the unstable prefix is deprecated in the future we could leave users with an unknown number of chat effects received! Eek

### Will you send logs?

No

**Comment by gsouquet** [comment] 2021-11-22 17:42
I was not able to reproduce this and after looking at the logic, I am fairly confident I can say what happened.

We have a lot of "stuck" notifications with Threads, that's because some read receipts for events that exists in threads are not sent to Synapse. Upon a reload, EW will go through all unread events and play the chat effects of unread messages. 

This is most probably what happened and will be fixed once #19126 lands

Closing this issue for now, please feel free to reopen if you have another occurence of it

**Closed by gsouquet** 2021-11-22 17:42 UTC
Labels: T-Defect, X-Cannot-Reproduce, A-Threads, Z-ThreadsP0, Z-ThreadsInternalTesting
