### ISSUE TITLE
Confirm removal of event could be better

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#12667] opened 2020-03-09 18:29 UTC
![image](https://user-images.githubusercontent.com/2403652/76245456-d3884a00-6233-11ea-900c-c58a46eff33b.png)

The second part should be less ambiguous and warn you explicitly if it is a room name/topic change.

**Comment by robintown** [comment] 2022-04-25 00:42
Duplicate of https://github.com/vector-im/element-web/issues/8478

**Closed by robintown** 2022-04-25 00:42 UTC
