### ISSUE TITLE
Changing display name marks unread rooms as read

### ISSUE THREAD

**Issue by konomikitten** [vector-im/element-web#16820] opened 2021-03-30 07:06 UTC
### Description

Changing display name marks unread rooms as read.

### Steps to reproduce

- Change your display name while having unread messages in chat rooms
- As your display name propagates to each room the room is marked as read

I expect that when I change my Display Name that rooms do not get marked as read.

Logs being sent: No

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Debian Unstable
- **Version**: 1.7.24

**Comment by SimonBrandner** [comment] 2021-04-07 10:05
Duplicate of [#15860](https://github.com/vector-im/element-web/issues/15860)

**Closed by SimonBrandner** 2021-04-07 10:05 UTC
Labels: T-Defect
