### ISSUE TITLE
Deleted messages visible in room preview

### ISSUE THREAD

**Issue by Erik-Nickel** [vector-im/element-web#22334] opened 2022-05-25 07:51 UTC
### Steps to reproduce

1. I opened element and got notification for a new message.
2. Got into the space where a room was located which showed one unread message
3. I clicked on the room and upon opening saw that the message was deleted.
4. I saw that a new message was displayed in the room preview.
5. I hover my cursor over the message of in the room preview on the left side.
6. Upon hovering, the full (deleted) message was displayed.

#### What did you expect?
Deleted messages are not shown anywhere.

#### What happened instead?
The deleted message was visible in the upon hover in the room preview.

### Operating system

Win10

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.virtous.uni-osnabrueck.de

### Will you send logs?

No

**Comment by 532910** [comment] 2022-06-08 16:32
![image](https://user-images.githubusercontent.com/14617699/172669419-9247a41a-031c-4e42-9471-211b60e7346c.png)

**Comment by 532910** [comment] 2022-06-08 16:33
It remains even if I put a new message and remove it then.

**Comment by t3chguy** [comment] 2023-05-17 07:40
Duplicate of https://github.com/vector-im/element-web/issues/17893

**Closed by t3chguy** 2023-05-17 07:40 UTC
Labels: T-Defect, S-Minor, A-Message-Previews, O-Occasional
