### ISSUE TITLE
Authorization page doesn't scroll

### ISSUE THREAD

**Issue by DzenOwl** [vector-im/element-web#24045] opened 2022-12-17 20:42 UTC
### Steps to reproduce

1. Go to the welcome page
2. ~Choose German language~
3. Click on the "Log in" ("Anmelden")
4. Try to scroll

#### What did you expect?
To scroll the page

#### What happened instead?
Nothing

https://user-images.githubusercontent.com/58021505/208265311-5807e516-1be5-422f-8ed4-85921a10be37.mp4

### Operating system

Windows 10

### Browser information

Microsoft Edge 108.0.1462.54

### URL for webapp

app.element.io

### Application version

Element version: 1.11.16, Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2022-12-19 08:29
Thanks for reporting this issue @DzenOwl . This seems to be language independent. Selecting German only make it more likely to appear because of the longer intro sentence.

**Comment by t3chguy** [comment] 2022-12-23 14:26
Duplicate of https://github.com/vector-im/element-web/issues/19548

**Closed by t3chguy** 2022-12-23 14:26 UTC
Labels: T-Defect, S-Minor, Help Wanted, O-Occasional, good first issue
