### ISSUE TITLE
Implement context menu for messages; For deleting, replying, editing etc

### ISSUE THREAD

**Issue by TacoMarco** [vector-im/element-web#21059] opened 2022-02-13 08:49 UTC
### Your use case
Will use everytime one wants to reply, edit or delete a message

#### What would you like to do?
To be able to right click messages in the chat log, so I can choose the options. Instead of going all the way to the right of the screen and clicking one of the `delete`, `reply` or `edit` buttons.

#### Why would you like to do it?
It's alot quicker to just right click the message you want to reply to instead of going all the way to the right of the screen and 
selecting the option you want. This would be especially annoying on Ultra-Wide screens, you would have to keep looking back and forth to make sure you're deleting/editing the right message.
#### How would you like to achieve it?
Add a context menu for when you right click a message, with the same options as hovering over a message. Will save alot of time.

### Have you considered any alternatives?
You can press up arrow to edit a message, but that does not cover deleting or replying to a message.

**Comment by SimonBrandner** [comment] 2022-02-13 09:16
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/16480

**Closed by SimonBrandner** 2022-02-13 09:16 UTC
Labels: T-Enhancement
