### ISSUE TITLE
Searching not working

### ISSUE THREAD

**Issue by dm-msk** [vector-im/element-web#23164] opened 2022-08-29 08:28 UTC
### Steps to reproduce

Searching not working.
Error opening the database: IndexError(IOError(IOError { path: None, err: Custom { kind: Other, error: "Invalid MAC" } }))

### Operating system

Windows 10 x64

### Application version

Element version: 1.11.3 Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by turt2live** [comment] 2023-01-10 00:08
Duplicate of https://github.com/vector-im/element-web/issues/19001

**Closed by turt2live** 2023-01-10 00:08 UTC
Labels: T-Defect, S-Major, A-E2EE, A-Electron, A-Timeline-Search, A-Indexing, O-Uncommon
