### ISSUE TITLE
Tray icon regression in 0.15.x

### ISSUE THREAD

**Issue by akontsevich** [vector-im/element-web#6767] opened 2018-05-18 15:38 UTC
Tray icon regression in 0.15.x with latest Electron: https://github.com/electron/electron/issues/13000

**Comment by uhoreg** [comment] 2018-05-19 16:52
Possibly related to the presence/absence of various libappindicator libraries, as per discussion in https://github.com/vector-im/riot-web/issues/3133

**Comment by akontsevich** [comment] 2018-05-19 17:00
@uhoreg no, libappindicator1 libraries installed. 0.14.2 works fine without it.

**Comment by akontsevich** [comment] 2018-05-19 17:05
@uhoreg no, libappindicator1 libraries installed. 0.14.2 works fine without it, with libappindicator1 installed icon converted to purple square in 0.14.2 too.

**Comment by uhoreg** [comment] 2018-05-20 01:28
Yup, that was basically what [t3chguy's comment](https://github.com/vector-im/riot-web/issues/3133#issuecomment-307852295) was about.  With libappindicator1 installed (and no libappindicator-gtk3?), the icon is just a square.  With the dummy libappindicator1 that t3chguy created, it should be a proper icon.  So this isn't a regression, it's the same issue as before.

**Comment by akontsevich** [comment] 2018-05-20 01:44
I have no libappindicator-gtk3. What is dummy libappindicator1?

**Comment by ArchangeGabriel** [comment] 2018-05-20 18:58
@akontsevich What kind of DE do you use? Can you remove libappindicator from your system?

**Comment by akontsevich** [comment] 2018-05-20 20:47
@ArchangeGabriel, KDE. Can't remove as many applications depends on it. NetworkManager-applet, pasystray, MATE, etc.

**Comment by ArchangeGabriel** [comment] 2018-05-20 21:12
OK, it’s a known bug on KDE, I’m surprised you did not had it before. Why do you have pasystray, MATE and NetworkManager-applet if you are under KDE? And btw those should not depend on libappindicator, which is only really needed for unity…

**Comment by akontsevich** [comment] 2018-05-20 21:31
they not depend on libappindicator1 - it is removed, they depend on libappindicator3-1 which is GTK3 version.

**Comment by ArchangeGabriel** [comment] 2018-05-21 10:05
Yes, I’m talking about libappindicator3, the “1“ version just does not exist in my mind.

**Comment by dos1** [comment] 2018-08-13 21:39
It's actually Chromium that's breaking the icon, not libappindicator (although only the code that used libappindicator had this bug). I've submited a patchset that fixes this issue: https://chromium-review.googlesource.com/c/chromium/src/+/1173235

**Comment by akontsevich** [comment] 2018-09-25 23:31
> Possibly related to the presence/absence of various libappindicator libraries, as per discussion in #3133

Yes, so problem is in libappindicator3 (in openSUSE,  libappindicator-gtk3 in other distributions). Removing it causes icon to render properly and correct react on left mouse clicks. Works fine with libappindicator1 or without it. So it is a libappindicator3 bug/regression, you may close this issue. Icon is a little bit pixelated like mentioned here: https://github.com/vector-im/riot-web/issues/3133#issuecomment-277555620 - still some area to fix, but looks and works normal for now.

**Comment by dos1** [comment] 2018-09-25 23:34
It's not a libappindicator bug - it's a bug in Chromium's codepath that uses libappindicator. If you don't have libappindicator installed, it uses GTK+ codepath, which doesn't have this bug.

Also, GTK+ codepath is deprecated and is likely to be removed, as Chromium wants to make libappindicator3 a hard dependency.

That said, my patch to Chromium got in, and I believe Chromium 70 should have this bug fixed. Not sure when it will land in Electron.

**Comment by akontsevich** [comment] 2018-09-25 23:36
@dos1 Whatever more fixes is fine, work good for me for now. However libappindicator3 has another bug: https://github.com/electron/electron/issues/13087 - whether Your patch fixes it as well? Think - no.

**Comment by dos1** [comment] 2018-09-25 23:38
As I said, Chromium team wants to remove GTK+ codepath and depend strictly on libappindicator in the future. The GTK+ StatusIcon is already deprecated by GTK+ itself.

Also, left mouse button works fine for me using libappindicator and Plasma 5. Check whether your distribution patches libappindicator to add `Activate` dbus method. If it does, convince your maintainers to drop it. (I wrote this patch long ago for old Plasma versions, but nowadays it does more bad than good).

**Comment by akontsevich** [comment] 2018-09-25 23:41
@dos1 You said 
> Chromium wants to make libappindicator3 a hard dependency
So it is not clear for me whether libappindicator3 or Chromium have fixed mouse issue?!

**Comment by dos1** [comment] 2018-09-25 23:50
Chromium had a bug: when it used libappindicator and detected KDE, icons were being cropped. This was recently fixed (https://chromium-review.googlesource.com/c/chromium/src/+/1173235), but Electron doesn't have that fix yet.

libappindicator in some distributions has another issue: it doesn't play well with current Plasma versions, causing the left mouse button to not work properly. This is an issue which should be reported to your distribution, like I did here for Arch: https://bugs.archlinux.org/task/59652. It has nothing to do with Riot, Electron nor Chromium.

For optimal system tray experience, you should have a proper version of libappindicator installed, as GTK+ StatusIcon has its own set of issues that aren't likely to get ever fixed. Also, you may consider convincing your distro to ship libayatana-appindicator instead of the old unmaintained libappindicator, like Debian does (https://wiki.debian.org/Ayatana/IndicatorsTransition).

**Comment by akontsevich** [comment] 2018-09-29 13:34
@dos1 I see `libayatana-appindicator` exists in openSUSE and works fine for electron applications but does not work for some GTK+3 applications (`gnome-pomodoro`), and `python2-ayatana-appindicator` - does not work for python2 applications like `acestreamengine`, etc.

**Comment by dos1** [comment] 2018-09-29 14:13
As noted above, this is a matter for your distro maintainers, since some apps (especially Python ones) need small patches in order to work with Ayatana indicators.

**Comment by Pointedstick** [comment] 2019-02-23 17:30
Is this fixed along with https://github.com/vector-im/riot-web/issues/7555?

**Comment by akontsevich** [comment] 2019-02-23 17:39
@Pointedstick, no! Seems will be fixed only in next Electron version with Chromium 70+.

**Comment by dos1** [comment] 2019-02-23 17:39
I don't think so. Looking at Electron releases, the proper fix will be finally included in 5.0.0. Keepn in mind that there are two separate codepaths here that may be used depending on whether libappindicator is installed or not.

**Comment by rawlife56** [comment] 2019-04-07 09:49
@dos1 According to their release schedule, Electron 5.0 stable is set to out on April 23. Is it already fixed in Beta ?

**Comment by dos1** [comment] 2019-04-07 11:48
Yup!

After just seven months since merging in Chromium, the fix is coming :)

**Comment by ArchangeGabriel** [comment] 2019-04-25 12:11
Electron 5.x has been released as expected, but #9562.

**Comment by ArchangeGabriel** [comment] 2019-04-25 17:42
I can now confirm that this is indeed fixed with Electron 5.x. Remains the left-click feature disparity between GTK+ StatusIcon and libappindicator to be solved (#3133), but I did not have time yet to try Ayatana indicators.

**Comment by rawlife56** [comment] 2019-04-26 02:36
Looks like the icons are fixed. I really hoped left click would be fixed in 5.0 but I guess we'll have to wait. 
@ArchangeGabriel Btw, Which distro are you on ?

**Comment by ArchangeGabriel** [comment] 2019-04-26 09:47
ArchLinux. For the left click issue on Arch, you have to use ayatana indicators or rebuild libappindicator without the plasma patch.

**Comment by akontsevich** [comment] 2019-06-22 21:28
Think #7553 and #7624 could be closed for now: works fine if libappindicator3 (libappindicator-gtk3) not installed. Unlike #6767 and #8819 (icon look) should be reopened and fixed: stopped to work even if I run with `Exec=XDG_CURRENT_DESKTOP=Unity riot %U`. For now icon looks like blank black square in KDE which is weird. I think local electron version used to build riot should be manually patched like Skype done previous year, where icon looks good for now with whatever appindicator is used or not, Unity desktop set or not. Otherwise we can wait too long it will be fixed in Electron. Makes sense?

**Comment by t3chguy** [comment] 2020-07-25 09:29
Related https://github.com/vector-im/riot-web/issues/3133 https://github.com/vector-im/riot-web/issues/9027

**Comment by t3chguy** [comment] 2022-10-26 12:18
Closing in favour of https://github.com/vector-im/element-web/issues/11772

**Closed by t3chguy** 2022-10-26 12:18 UTC
Labels: T-Defect, P2, S-Minor, A-Electron, A-Tray-Icon
