### ISSUE TITLE
Can't have line breaks in quote block

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/element-web#15292] opened 2020-09-26 22:16 UTC
### Description

In some conditions it is impossible to have line breaks in quote blocks.

### Steps to reproduce

- Write this text:
    ```
    > Line1.
    >
    > Line2.
    >
    > Line3.
    ```
- See the result:
    > Line1.Line2.Line3.

The proper rendering would have been this:
> Line 1.
>
> Line2.
>
> Line3.

What is weird about that is that this issue only happens if you are only writing a quote block. See the screenshot from the [#linear-supporters:matrix.org](https://matrix.to/#/!eUGMvloIjhBoAwlyRh:matrix.org/$1601156818229561mPloC:matrix.org?via=matrix.org&via=kittenface.studio&via=gottsnack.net) room:
![image](https://user-images.githubusercontent.com/6382548/94351168-343a7100-0024-11eb-905d-8d5240db8ea5.png)

Logs being sent: yes

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Linux (Fedora 32)
- **Version**: 1.7.7

**Comment by t3chguy** [comment] 2020-09-27 12:37
Duplicate of https://github.com/vector-im/element-web/issues/8786

**Closed by t3chguy** 2020-09-27 12:37 UTC
Labels: bug

**Comment by MightyCreak** [comment] 2020-09-27 15:53
Ah sorry, I did a search before but couldn't find a related issue.. wrong search words apparently ;)
