### ISSUE TITLE
Custom font not being applied / fetched

### ISSUE THREAD

**Issue by pascbeck** [vector-im/element-web#23833] opened 2022-11-25 12:19 UTC
Hello, hope anyone can help me out here :)

### Steps to reproduce

Config:
![image](https://user-images.githubusercontent.com/55634271/203983192-bd6db609-f739-40f1-b47d-9f8de4059b51.png)
---
Folder:
![image](https://user-images.githubusercontent.com/55634271/203983241-770e5b27-5f54-482d-8c58-12712a7e4c30.png)
---
Styles:
![image](https://user-images.githubusercontent.com/55634271/203983388-09a5de45-7fc0-47ba-aff8-8939a4e2877f.png)
![image](https://user-images.githubusercontent.com/55634271/203983523-72a3d1e8-e09a-4303-a634-108b6ca60980.png)
---
Fallback font in use:
![image](https://user-images.githubusercontent.com/55634271/203983563-eb9ab793-28ef-4c90-a91c-fb7eb9bd31b1.png)

Not sure if I'm missing something - would be awesome if anyone can take a look please!

#### What did you expect?
Atkinson-Hyperlegible.ttf to load and display properly

---
#### What happened instead?
Fallback font is displayed

### Operating system

Windows

### Browser information

Google Chrome 107.0.5304.101

### URL for webapp

-

### Application version

-

### Homeserver

-

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-11-25 12:21
I suggest checking your browser console, likely the path is wrong. Also looks like you added the font to the source code rather the built bundle, did you build the app after?

**Comment by pascbeck** [comment] 2022-11-25 12:37
@t3chguy Thanks for your fast response.

I built the app and adapted the path accordingly, however it still does not seem to work, any advice?

---
![image](https://user-images.githubusercontent.com/55634271/203987283-662eb2d4-0d58-4667-b89e-1e29f30601cc.png)

---

![image](https://user-images.githubusercontent.com/55634271/203987334-79e99bc8-21df-44df-a80b-5833cfc4e789.png)

**Comment by t3chguy** [comment] 2022-11-25 12:41
> I suggest checking your browser console, likely the path is wrong.

**Comment by pascbeck** [comment] 2022-11-25 13:01
@t3chguy I checked the paths - also there are no console errors that indicate that the path is wrong.

---
![image](https://user-images.githubusercontent.com/55634271/203990682-62dc5af5-d27f-4f43-9553-4c4bbd1538ad.png)
---
![image](https://user-images.githubusercontent.com/55634271/203990791-8420d044-63bc-41e1-86ad-80c235fa8432.png)
---
![image](https://user-images.githubusercontent.com/55634271/203990864-2194c80a-e953-42dc-9906-9061dc0ba4bf.png)

---

I also tried:
webapp/fonts/
/fonts/
./fonts/
fonts/

also tried to put the font in root path and just call {"url": "Atkinson-Hyperlegible.ttf", "format": "ttf"}

**Comment by t3chguy** [comment] 2022-11-25 13:14
Can you see the font load attempt happening at all? Can you share your full JSON rather than just a snippet which doesn't help verify its validity?

**Comment by pascbeck** [comment] 2022-11-25 13:18
No, I cannot see the initial font load at all. 

```
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "private",
            "server_name": "Messenger Staging"
        },
        "m.identity_server": {
            "base_url": "https://vector.im"
        }
    },
    "disable_custom_urls": false,
    "disable_guests": true,
    "disable_login_language_selector": false,
    "disable_3pid_login": false,
    "brand": "ByCS",
    "integrations_ui_url": "https://scalar.vector.im/",
    "integrations_rest_url": "https://scalar.vector.im/api",
    "integrations_widgets_urls": [
        "https://scalar.vector.im/_matrix/integrations/v1",
        "https://scalar.vector.im/api",
        "https://scalar-staging.vector.im/_matrix/integrations/v1",
        "https://scalar-staging.vector.im/api",
        "https://scalar-staging.riot.im/scalar/api"
    ],
    "bug_report_endpoint_url": "https://element.io/bugreports/submit",
    "uisi_autorageshake_app": "element-auto-uisi",
    "default_country_code": "GB",
    "show_labs_settings": false,
    "features": { },
    "default_federate": true,
    "room_directory": {
        "servers": [
            "matrix.org"
        ]
    },
    "enable_presence_by_hs_url": {
        "https://matrix.org": false,
        "https://matrix-client.matrix.org": false
    },
    "default_theme": "custom-cs",
    "setting_defaults": {
        "baseFontSize": 11,
        "breadcrumbs": true,
        "custom_themes": [
            {
                "name": "cs",
                "is_dark": false,
                "fonts": {
                    "faces": [
                        {
                            "font-family": "Atkinson Hyperlegible",
                            "src": [{"url": "./fonts/Atkinson_Hyperlegible/Atkinson-Hyperlegible.ttf", "format": "ttf"}]
                        }
                    ],
                    "general": "Atkinson Hyperlegible"
                }
            }
        ]
    },
    "jitsi": {
        "preferred_domain": "meet.element.io"
    },
    "element_call": {
        "url": "https://call.element.io",
        "participant_limit": 8,
        "brand": "Element Call"
    },
    "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=fU3vlMsMn4Jb6dnEIFsx"
}

```

---

Yeah sorry, should ve shared the whole config earlier.

**Comment by t3chguy** [comment] 2022-11-25 13:19
You enabled the cs theme, right? Did you ever make use of the Add theme via JSON feature in Labs

**Comment by pascbeck** [comment] 2022-11-25 13:21
Yeah, cs theme is enabled.
> Did you ever make use of the Add theme via JSON feature in Labs

I did not

**Comment by t3chguy** [comment] 2022-11-28 23:45
I suggest sharing an example deployment so someone can dig into it

**Comment by AversaFTW** [comment] 2022-12-16 14:22
@t3chguy Can you confirm that this is generally possible and works for you? Because I also can't get this to work. An example deployment is not really possible, as it is branded.

**Comment by t3chguy** [comment] 2023-01-30 12:53
Duplicate of https://github.com/vector-im/element-web/issues/22724

**Closed by t3chguy** 2023-01-30 12:53 UTC
Labels: T-Defect, S-Minor, A-Themes-Custom, O-Uncommon, Z-Labs
