### ISSUE TITLE
ability to stop people ever leaving a room (or: autojoin and autoleave rooms in sync with joining/leaving a group)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5507] opened 2017-11-03 18:27 UTC
Discord has quite an interesting and nice UX where users never explicitly join or leave channels; they join/leave servers.  They are then implicitly within all the channels on that server.  This cuts down on join/leave spam a lot, and creates a different social dynamic where you use an #introductions channel to actually handle the social join/leave side of things.  Status want the same semantics on chat.status.im, which led me to wonder about the idea of having a flag on rooms which *recommends* that clients don't show a 'leave' button once they join that room - i.e. that the intent for that room is for it to blend into the wallpaper.  One could even go one step further and have the room associated with a group such that if the user is a member of said group, they autojoin it for the forseeable, without any UI provided to leave it, which I guess is what is really being asked for here.

**Comment by ara4n** [comment] 2017-11-03 18:46
actually, an alternative solution might be to let people leave the room, but (optionally) keep it listed in their LeftPanel so they can peek into it if desired and then rejoin.  Although they can also do this via the Historical section today if they really care.  The fact is more that when people leave it signals they are no longer really reading it, so it's only polite to tell the people in the room that the user has left.

Another alternative might be to differentiate between people explicitly leaving (or joining) the room - versus being autojoined/autoleft by being part of a group.  Then you get best of both worlds, i think.

**Comment by turt2live** [comment] 2017-11-13 20:04
Related: https://github.com/vector-im/riot-web/issues/5243

**Comment by SimonBrandner** [comment] 2021-06-22 10:07
Duplicate of https://github.com/vector-im/element-web/issues/16490

**Closed by SimonBrandner** 2021-06-22 10:07 UTC
Labels: A-Spaces, P2, T-Enhancement
