### ISSUE TITLE
No Search Results for Chinese

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [vector-im/element-web#6923] opened 2018-06-23 04:14 UTC
### Description

Can find nothing if I am searching for a Chinese character.

### Steps to reproduce

- Open Riot
- Create a new room and type in a sentence like ```我能吞下玻璃而不伤身体``` ("I can eat glass, it doesn't hurt me.")
- Search for any characters or words in this sentence, like ```玻璃``` ("glass")

Describe how what happens differs from what you expected.

There should be search results but indeed there is none.

Log: sent/not sent?   

Nope.
 

### Version information

- **Platform**: web (in-browser) or desktop?

Both desktop and in-browser.

For the web app:

- **Browser**: Firefox Quantom 60.0.2
- **OS**: Deepin 15.6 (Based on Debian)
- **URL**: Any, both official and unofficial site.

For the desktop app:

- **OS**: Windows 10 (Version 1803&1709) and Deepin 15.6

**Comment by March-happy** [comment] 2018-06-24 09:53
And what's more E2E rooms cannot be searched too... No matter in Chinese or English...

**Comment by t3chguy** [comment] 2018-06-24 10:07
Yes for the same reason. The server can't decrypt the rooms. If you want e2e search use matrix-search, not sure how well it works for Chinese either though

**Comment by turt2live** [comment] 2020-08-31 18:56
Duplicate of https://github.com/matrix-org/synapse/issues/901

**Closed by turt2live** 2020-08-31 18:56 UTC
Labels: bug, major, p1
