### ISSUE TITLE
Duplicate rooms in sidebar list

### ISSUE THREAD

**Issue by callahad** [vector-im/element-web#17492] opened 2021-05-28 09:21 UTC
### Description

When switching rooms, duplicates occasionally appear in the room list.

![Screen Shot 2021-05-28 at 10 07 30](https://user-images.githubusercontent.com/24193/119961161-a68d9780-bf9d-11eb-992b-50c9022bcb7f.png)

![Screen Shot 2021-05-28 at 10 07 24](https://user-images.githubusercontent.com/24193/119961146-a392a700-bf9d-11eb-97df-968bf2a115b0.png)

### Steps to reproduce

I haven't determined specific STRs yet, but I've hit this ~5 times over the past 12 hours, including for both normal rooms and DMs. I've even managed to create three duplicates of a room at once.

Duplicates are not always grouped together (per second screenshot).

Switching to a different room and changing Spaces fixes the rendering to show only a single entry.

All duplicate entries behave as expected.

I suspect it involved being in one space, hitting ctrl-k, and selecting a room that only exists in another space.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox Beta (89)
- **OS**: macOS
- **URL**: develop.element.io

**Comment by t3chguy** [comment] 2021-05-28 09:22
Duplicate of https://github.com/vector-im/element-web/issues/14508

**Comment by t3chguy** [comment] 2021-05-28 09:23
Also interesting Stylus/usermod you're running there

**Closed by t3chguy** 2021-05-28 09:22 UTC
Labels: T-Defect

**Comment by callahad** [comment] 2021-05-28 11:14
@niquewoodhouse I don't, but message previews seem to work well enough aside from a misalignment of the public room icon...
