### ISSUE TITLE
Element Desktop incorrectly thinks I'm not joined in a room

### ISSUE THREAD

**Issue by duxovni** [vector-im/element-web#22708] opened 2022-07-01 03:16 UTC
### Steps to reproduce

Unclear how to reproduce this. I opened Element Desktop, and the Forge Federation chatroom was in the "Historical" section, was missing its room name, and couldn't be viewed.

#### What did you expect?
I'm a member of the Forge Federation room, and I can see it and read it in Element Web, so I expected it to be viewable and in the list of current rooms I'm in.
#### What happened instead?
The room was in the Historical section, and attempting to open it just showed me a pre-join screen. Clicking "Join" just produces a loading spinner that stays there until I switch to a different room.

![20220630_23h08m33s_grim](https://user-images.githubusercontent.com/6477010/176816386-e43186b9-62b1-4008-91fe-ff2b43e173eb.png)
![20220630_23h14m38s_grim](https://user-images.githubusercontent.com/6477010/176816486-65600d14-d4a9-4744-a6b6-c1643ac08ecf.png)

### Operating system

NixOS

### Application version

Element version: 1.10.15, Olm version: 3.2.8

### How did you install the app?

From nixpkgs.

### Homeserver

Synapse 1.61.1

### Will you send logs?

Yes

**Comment by duxovni** [comment] 2022-07-01 13:16
I'm not really clear on what's wrong, but from my investigation, my desktop client also seemed to be experiencing https://github.com/vector-im/element-web/issues/21158, and the console had a warning about the forgefed room not having an `m.room.create` event.

**Comment by turt2live** [comment] 2022-07-04 14:49
Duplicate of https://github.com/vector-im/element-web/issues/22030

**Closed by turt2live** 2022-07-04 14:49 UTC
Labels: T-Defect, S-Major, Z-Cache-Confusion, O-Occasional
