### ISSUE TITLE
Up arrow does not toggle edit on last message

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23724] opened 2022-11-08 09:20 UTC
### Steps to reproduce

1. Have an empty rich text editor
2. Hit up arrow

#### What did you expect?

Your last message in the timeline should enter edit mode

#### What happened instead?

Nothing

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-11-08 09:49
Duplicate of https://github.com/vector-im/element-web/issues/23621

**Closed by t3chguy** 2022-11-08 09:49 UTC
Labels: T-Defect, S-Minor, O-Occasional, Z-Labs, A-Rich-Text-Editor
