### ISSUE TITLE
Show if I've left a message in the composer in the roomlist

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#16092] opened 2021-01-08 17:12 UTC
Is this a good idea? I don't know. But I just flipped to a room to find I'd left a message in the composer (i.e. forgotten to send it), and I've done this a few times.

**Comment by t3chguy** [comment] 2021-01-08 17:17
Duplicate of https://github.com/vector-im/element-web/issues/15096 which was closed as a duplicate of https://github.com/vector-im/element-web/issues/14182

**Closed by t3chguy** 2021-01-08 17:17 UTC
Labels: suggestion
