### ISSUE TITLE
New device verification popup appears whilst your signing-in device is still syncing

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15877] opened 2020-12-01 17:14 UTC
If you have a decent-sized account syncing takes a long time, waiting all that time to verify your new sign in is a pain and feels broken.

Can it wait until this is displayed on the logging in account? 
![image](https://user-images.githubusercontent.com/1922197/100773322-9d5dac80-33f8-11eb-8e81-ee1d08d2f8f6.png)

**Comment by jryans** [comment] 2020-12-02 11:06
It does sound tricky to do this securely: existing devices could wait until the new device is synced (somehow), but then an evil device could hide itself by evading that mechanism. It would depend how critical we feel it is that you are always toasted for new devices vs. possible only noticing an evil device later on when shields change or you review your device list.

**Comment by afranke** [comment] 2021-01-18 18:24
Related to (/duplicate of?) 15673.

**Closed** 2021-03-11 12:53 UTC
Labels: A-E2EE-Cross-Signing, T-Enhancement, X-Needs-Product
