### ISSUE TITLE
Remove the scroll from the Start Message screen

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21948] opened 2022-04-27 04:56 UTC
### Your use case

The screens here have a scroll and it would be better if they didn't... That also might fix the bottom corner being square instead of round?

<img width="409" alt="Screenshot 2022-04-26 at 21 55 24" src="https://user-images.githubusercontent.com/89144281/165443507-a7e9a16a-b964-4006-bab9-9f71890773a2.png">

<img width="408" alt="Screenshot 2022-04-26 at 21 55 31" src="https://user-images.githubusercontent.com/89144281/165443519-382e38a5-d854-49a2-a740-4f21919984ba.png">

**Comment by gsouquet** [comment] 2022-04-28 13:13
@daniellekirkwood / @kittykat I have not been able to reproduce. Could you give a bit more info regarding your setup?

**Comment by daniellekirkwood** [comment] 2022-04-28 19:05
Element version: 1.10.11
Olm version: 3.2.8

https://user-images.githubusercontent.com/89144281/165827552-7d63eee2-2e73-4c68-ab94-861c7654987d.mov

**Comment by daniellekirkwood** [comment] 2022-04-28 19:07
Also happens for me on Develop and Nightly on my _not_ test account.

**Comment by SimonBrandner** [comment] 2022-04-29 15:19
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/20911

**Closed by SimonBrandner** 2022-04-29 15:19 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Minor, A-Invite, A-Appearance, O-Occasional, Z-WTF, Team: Delight, Z-NewUserJourney

**Comment by kittykat** [comment] 2022-05-04 10:08
@SimonBrandner I'm not sure if it's related, I don't get a scroll bar. Either way, this dialog is about to go :+1:
