### ISSUE TITLE
Element Desktop precipitates an error when launched in a torified environment.

### ISSUE THREAD

**Issue by docteurdoom** [vector-im/element-web#23666] opened 2022-11-01 04:44 UTC
### Steps to reproduce

1. Install Whonix in a VirtualBox.
2. Add repository and install Element Desktop as [recommended](https://element.io/get-started#linux-details) on the official website.
3. Launch Element Desktop.

#### What did you expect?
It was expected to work as intended.
#### What happened instead?
See the screenshot
![element_bug](https://user-images.githubusercontent.com/117053906/199159830-0c6cce2b-6708-4ad4-91e2-9e0db0fe2e8e.png)

### Operating system

Whonix Workstation

### Application version

Element Desktop 1.11.12

### How did you install the app?

sudo apt install element-desktop

### Homeserver

It wouldn't even let me proceed to that step.

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-11-01 08:54
Duplicate of https://github.com/vector-im/element-web/issues/11154

**Closed by t3chguy** 2022-11-01 08:54 UTC
Labels: T-Defect
