### ISSUE TITLE
notif settings sometimes badly configured in a 1:1

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#4338] opened 2017-06-16 16:19 UTC
when creating a 1:1 sometines the notifs are set to 'mentions only'. Can't find the pattern

**Comment by t3chguy** [comment] 2022-05-06 18:55
Closing due to lack of reproduction, Element Web only touches push rules upon a user's explicit interaction

**Closed by t3chguy** 2022-05-06 18:55 UTC
Labels: P2, S-Major, A-Notifications
