### ISSUE TITLE
creating a room dumps you back in the previous room you were in, with no spinner, until suddenly the new room appears

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18476] opened 2021-08-10 14:37 UTC

**Comment by gsouquet** [comment] 2021-08-11 08:12
Could you provide a bit more information?
When trying to reproduce this on develop.element.io I can see the following steps (which seem to be the expected experience)

* Create a room
* See a spinner for a couple of seconds
* The new room appears

**Comment by robintown** [comment] 2022-04-24 20:25
Closing due to lack of info

**Closed by robintown** 2022-04-24 20:25 UTC
Labels: T-Defect, X-Needs-Info, S-Minor, A-Create-Room, O-Occasional
