### ISSUE TITLE
I got a CORS error a few minutes after cancelling a search across all rooms

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#8621] opened 2019-02-14 12:03 UTC
![image](https://user-images.githubusercontent.com/8582858/52785691-8a75be80-3050-11e9-872e-d08078dfb01c.png)
I did first a search in the local room (Riot Web internal, searching for 'release', then switched to "all rooms" and clicked on search again (I *think* I did launch it again). a few minutes later I got this popup ^ out of nowhere

**Comment by lampholder** [comment] 2019-02-19 16:14
That'll be the request timing out at the ha proxy.

We've got a problem that if the homeserver takes to long to respond and times out at the haproxy, then the 504(?) is returned by haproxy _without CORS headers_, so Riot just barfs this unhelpful error message.

@AmandineLP - was the search still searching when you got this popup? Or had you moved onto a different room?

**Comment by kittykat** [comment] 2021-09-30 17:22
I'm going to close this for now as I cannot reproduce it. Please reopen if you can.

**Closed by kittykat** 2021-09-30 17:22 UTC
Labels: T-Defect, X-Needs-Info, P2, S-Major, A-Search
