### ISSUE TITLE
Sometimes DMs and rooms are missing from spaces

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18700] opened 2021-08-23 21:14 UTC
### Steps to reproduce

Unclear. It just happens, and then it doesn't, and then it does.

### What happened?

Multiple times I've lost my DM with bots and coworkers for the internal company space despite them being members of the parent space and the DM map having the DMs appropriately flagged (the room list store also agrees on the DMness). Occasionally, non-DM rooms also go missing, possibly due to the room being mapped in multiple (sub)spaces. For example, the maubot room often ends up disappearing from all spaces, showing up in the Home view.

All the rooms are always accessible via Home, but that's not ideal if I've put them in spaces or joined spaces with them.

### What did you expect?

for spaces to show the right DMs and rooms.

### Operating system

Windows 10

### Application version

Nightly (2021-08-23)

### How did you install the app?

The Internet

### Have you submitted a rageshake?

Yes

**Comment by SimonBrandner** [comment] 2021-08-24 05:56
Mostly a duplicate of https://github.com/vector-im/element-web/issues/17291

**Closed by SimonBrandner** 2021-08-24 05:56 UTC
Labels: T-Defect
