### ISSUE TITLE
Convert room to people room

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/element-web#15547] opened 2020-10-25 00:21 UTC
**Is your suggestion related to a problem? Please describe.**
Because of the bug #15021, I now have people rooms as regular rooms (I often create rooms with my gf and I and a friend or couple, but if I add more than one people on room creation, it goes to the regular room list immediately instead of the people room).

**Describe the solution you'd like**
It would be nice to be able to **convert a regular room to a people room**, so that I could keep the discussion history with my friends. It doesn't have to be a hugely graphical feature, a mere command will be more than enough.

**Describe alternatives you've considered**
<del>The only alternative I've seen it to create another people room but adding just one person at creation, then once created, add the other people, thus loosing the history.</del> This alternative doesn't really work since if you already have rooms with the people individually, you can't create another room with them and then add more people in it.

**Comment by t3chguy** [comment] 2020-10-25 01:39
Duplicate of #14942

**Closed** 2020-10-25 01:39 UTC
Labels: suggestion

**Comment by MightyCreak** [comment] 2020-10-25 02:15
Ah sorry, I did make a search before but apparently didn't have the right words :wink:
