### ISSUE TITLE
"regexp is fair" turned into "rege😝air"

### ISSUE THREAD

**Issue by freaktechnik** [vector-im/element-web#19472] opened 2021-10-22 08:28 UTC
### Steps to reproduce

1. Enable "Automatically replace plain text Emoji" preference
2. Select the composition text box
3. Type "regexp is fair"

#### What did you expect?

"regexp is fair" or at least "rege😝 is fair" but arguably it shouldn't replace when there are letters before the matching "plaintext emoji".

#### What happened instead?

"rege😝air"

### Operating system

elementary OS

### Browser information

Firefox Nightly 95.0a1

### URL for webapp

https://one.humanoids.be/apps/riotchat/riot/

### Homeserver

humanoids.be

### Will you send logs?

No

**Comment by turt2live** [comment] 2022-05-11 21:24
From the cases linked to this issue, a simple check like the one suggested here would be good: if there are characters before the presumed emoji, don't convert it.

**Comment by turt2live** [comment] 2022-07-05 16:24
it also affects the element developers like myself, however on the larger scale of important bugs to fix it's just not at the same level as app reliability and performance, sorry :( 

the issue is flagged as Help Wanted to attract contributions, however.

**Comment by t3chguy** [comment] 2022-07-05 16:24
> No doubt it would already be fixed if it affected common suffixes in the most used languages among Matrix/Element owners and users.

Our triage is based on occurrence. If it only affects few users then yes it'll get triaged lower. But great news, the project is open source, you or anyone can fix this issue regardless of its triage.

**Comment by thany** [comment] 2022-08-01 14:23
> Our triage is based on occurrence. If it only affects few users then yes it'll get triaged lower. But great news, the project is open source, you or anyone can fix this issue regardless of its triage.

Occurrence must not be a factor when it comes two types of issues: security, and data loss.

This bug is a form of data loss.

**Comment by thany** [comment] 2022-08-16 11:06
Don't use regexes to replace emoji. There be dragons.

**Comment by adarsh-sgh** [comment] 2023-02-06 05:46
This is happening because of below corner case 
we look at last 8 characters to check if there is an emoticon 
so in case of string `regexp 12345` everything before xp gets trimmed and when matching remaining string `xp 12345` it looks like xp is an emoticon so it is replaced.

I would Love to submit my first PR on element on this issue, can someone assign this issue to me.

**Comment by t3chguy** [comment] 2023-02-06 10:55
@adarsh-sgh Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)

**Closed** 2023-02-08 16:29 UTC
Labels: T-Defect, S-Minor, Help Wanted, A-Composer, A-Emoji, O-Occasional, good first issue

**Comment by thany** [comment] 2023-02-10 10:25
Now please put a (bigger) task on your storyboard to remove regexes to identify emoticons. Problems like this is one of the many reasons why a tokeniser is a way more reliable way to parse a string, than a regex.

Or did you think Markdown does its thing by applying a million regexes? Of course not 😀
