### ISSUE TITLE
Disappearing thread summaries in the main timeline

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#21198] opened 2022-02-24 14:19 UTC
### Steps to reproduce

Don't really know how to reproduce it, but I've noticed a few thread summaries disappearing from the main timeline.

![Element  4  | Element Embedded Chat](https://user-images.githubusercontent.com/60790/155541363-f1399d94-79a9-4b32-b004-ef8635c73dd0.png)

### Outcome

The thread summaries for some threads are not being rendered.

### Operating system

macOS Monterey

### Browser information

Chrome 98

### URL for webapp

develop.element.io

### Application version

Element version: a2b0cf92485c-react-8c2dcca48fe1-js-4de1699c49ae Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by MadLittleMods** [comment] 2022-02-24 15:15
Duplicate of https://github.com/vector-im/element-web/issues/21144 ?

**Closed** 2022-02-24 15:37 UTC
Labels: T-Defect, A-Threads, Z-Labs
