### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#15708] opened 2020-11-12 09:47 UTC
![Screenshot from 2020-11-12 10-46-51](https://user-images.githubusercontent.com/10190/98923843-76384d00-24d4-11eb-8d48-38fac67b115a.png)

I got this today.

Running Firefox Nightly on Ubuntu in en-US.

**Comment by Yoric** [comment] 2020-11-12 09:48
Note: after reloading, the error disappears.

**Comment by turt2live** [comment] 2020-11-12 15:18
Duplicate of https://github.com/vector-im/element-web/issues/12591

**Closed by turt2live** 2020-11-12 15:18 UTC
Labels: bug, ui/ux
