### ISSUE TITLE
UTD in an existing room

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#23169] opened 2022-08-31 07:57 UTC
### Steps to reproduce

some room members observed UTD in an existing room

I will sent Logs

### Application version

Element version: 44e01823a35a-react-825a0af4a9dd-js-1fbd8983ed9d Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-08-31 08:05
Duplicate of https://github.com/vector-im/element-web/issues/2996

**Closed by t3chguy** 2022-08-31 08:05 UTC
Labels: T-Defect
