### ISSUE TITLE
Caps lock prevents keyboard shortcuts from working

### ISSUE THREAD

**Issue by thibaultamartin** [vector-im/element-web#23851] opened 2022-11-28 15:43 UTC
#### What would you like to do?

I would like to be a distracted user who accidentally pressed caps lock without realising it, and still be able to open the new search or use other keyboard shortcuts.

#### Why would you like to do it?

Because I have a very limited attention span and fat fingers.

#### How would you like to achieve it?

Pressing Cmd-K should open the new search, even when I had pressed caps lock. When starting to type, I will soon realise that it looks like I'm screaming, but I will love Element for being so understanding with my condition.

**Comment by MadLittleMods** [comment] 2022-11-29 04:58
Duplicate of https://github.com/vector-im/element-web/issues/23681

**Closed by MadLittleMods** 2022-11-29 04:58 UTC
Labels: T-Enhancement, A-Shortcuts
