### ISSUE TITLE
Explore (eventually) shows empty room list for non-existent server

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24481] opened 2023-02-10 10:34 UTC
### Steps to reproduce

1. You should inject `feneas.org` to your server list in Explore. I have this server there.
2. Start Element Desktop
3. Open Explore
4. Select `feneas.org`

More detailed and hard way:
1. Create own Matrix servers
2. Create rooms. Imitate that rooms with users exist.
3. Add in server list and ask for rooms.
4. Exit from Element
5. Disable server;
6. Ask for rooms again.

#### What did you expect?

Report that server does not exist. It's correct, because this Matrix server does not exist.

#### What happened instead?

About 60 seconds of loading, empty room list and nothing that server does not exist.

### Operating system

Windows

### Application version

1.11.22

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-02-14 12:04
The 60s timeout seems to be baked into Synapse. We cannot access the directories of other servers directly, we must ask your server to fetch them for us. So we have to await this timeout as we have no way of discerning if your server is being slow or the other server is slow/unavailable.

Eventually times out with 
![image](https://user-images.githubusercontent.com/2403652/218733196-c9b1bce7-91a4-4f0e-9d75-698c514b0125.png)
but you are right that there is no error just an empty list

![image](https://user-images.githubusercontent.com/2403652/218733241-5322a7ec-8eca-4ba7-b6ec-1d35b8c0704b.png)

This is a regression, there was an error in the old room directory modal

**Comment by t3chguy** [comment] 2023-08-14 11:59
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/11378

**Closed by t3chguy** 2023-08-14 11:59 UTC
Labels: T-Defect, X-Regression, S-Minor, O-Uncommon
