### ISSUE TITLE
Lab feature bug: "Multiple integration managers" causes action `close_scalar` to time out

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#17042] opened 2021-04-22 13:58 UTC
https://user-images.githubusercontent.com/10872136/115726399-fe275a80-a382-11eb-9df1-3ee3e6339749.mp4

### Description

When the lab feature "Multiple integration managers" is enabled, one can't close Scalar with the X.

### Steps to reproduce

- Go to develop.element.io
- Enable the lab feature "Multiple integration managers"
- Open Scalar in the sidebar of a room.
- Click the X within the modal to close Scalar.

It doesn't close. The JS console prints a timeout message.

Logs being sent: yes

![Screenshot_2021-04-22_15-57-11](https://user-images.githubusercontent.com/10872136/115726902-6c6c1d00-a383-11eb-859f-b8680df5d7f6.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Mozilla Firefox Developer 88.0b9
- **OS**: Manjaro (based on the Arch Linux repo)
- **URL**: develop.element.io

**Comment by turt2live** [comment] 2021-04-22 14:06
Duplicate of https://github.com/vector-im/element-web/issues/10678

**Closed by turt2live** 2021-04-22 14:06 UTC
Labels: A-Scalar, T-Defect
