### ISSUE TITLE
not trusted dialog uses black-on-dark icon on dark theme

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15533] opened 2020-10-22 21:37 UTC
<img width="375" alt="Screenshot 2020-10-22 at 22 36 57" src="https://user-images.githubusercontent.com/1294269/96932708-3672dc80-14b7-11eb-87c3-813c50cb83e9.png">

**Comment by t3chguy** [comment] 2020-10-22 21:38
Duplicate of https://github.com/vector-im/element-web/issues/15354

**Closed by t3chguy** 2020-10-22 21:38 UTC
