### ISSUE TITLE
list numbering overrides don't work in MD 

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9661] opened 2019-05-09 16:10 UTC

**Comment by yannicka** [comment] 2020-05-23 12:01
Isn't this an upstream issue (or the intended behaviour)?

By testing this on the [reference implementation of CommonMark](https://spec.commonmark.org/dingus/), I was able to reproduce the issue.

**Comment by r4dh4l** [comment] 2022-03-01 20:11
Uh, this bug causes misunderstandings and disputes. For example if

> The next meeting is on 14. April 2022.

is shown as

> The next meeting is on 1. April 2022.

**Comment by t3chguy** [comment] 2022-03-02 10:06
Element Web & Desktop handle this fine @r4dh4l 

<img width="345" alt="image" src="https://user-images.githubusercontent.com/2403652/156340564-ee1ddeec-ccb3-469e-9241-f4514ed1b241.png">

**Comment by t3chguy** [comment] 2022-03-02 10:06
Closing as wont-fix, one of the other md issues can act as a fallback

**Closed by t3chguy** 2022-03-02 10:06 UTC
Labels: X-Won't-Fix

**Comment by r4dh4l** [comment] 2022-03-02 10:08
> Element Web & Desktop handle this fine @r4dh4l
> 
> <img alt="image" width="345" src="https://user-images.githubusercontent.com/2403652/156340564-ee1ddeec-ccb3-469e-9241-f4514ed1b241.png">

Sure, but can I force team members to read messages only in a web/desktop client?

**Comment by t3chguy** [comment] 2022-03-02 10:09
You can either use `/plain` to not send markdown or file issues with the clients which render valid messages incorrectly.

**Comment by r4dh4l** [comment] 2022-03-02 10:24
> You can either use `/plain` to not send markdown or file issues with the clients which render valid messages incorrectly.

Thanks for the hint, but imagine telling this to a team of non-technical users: "Hey team, next time sending a message starting with an ordinal number don't forget use the `/plain` command so that people reading the message with a mobile client will receive the intended ordinal number."

Don't get me wrong: I'm deeply thankful for the great matrix/element messenger system but problems like this have a great impact on "average users" deciding to keep matrix/element as daily messenger or not.

**Comment by t3chguy** [comment] 2022-03-02 10:27
I agree it is a problem, but the problem is on the receiving side. Or you could complain to the Matrix spec for whitelisting the property in the first place.

**Comment by r4dh4l** [comment] 2022-03-02 11:01
> I agree it is a problem, but the problem is on the receiving side.

Sorry, just noticed this is the issue department of element-web, not mobile. So I will report it there.
