### ISSUE TITLE
Element should stop centralizing Matrix protocol in matrix.org homeserver.

### ISSUE THREAD

**Issue by cdaydreamer** [vector-im/element-web#18276] opened 2021-07-28 08:23 UTC
#### Is your suggestion related to a problem? Please describe.
Most of the Matrix users use Element to sign up. Matrix is a decentralized network and no homeserver should have the majority of the Matrix users since that homeserver will have a huge metadata database. However, Element doesn't list public homeservers when signing up and suggest matrix.org instead. Therefore matrix.org homeserver has the majority of Matrix users and a huge metadata database. 

#### Describe the solution you'd like.
Element should not have a default homeserver/suggest any homeserver and list public homeservers for the user to choose one.

**Comment by SimonBrandner** [comment] 2021-07-28 11:43
Duplicate of https://github.com/vector-im/element-web/issues/6827

**Closed by SimonBrandner** 2021-07-28 11:43 UTC
Labels: T-Enhancement
