### ISSUE TITLE
Forgot password reset UX is a total cluster

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2780] opened 2016-12-21 13:31 UTC
it doesn't tell you if you have no email address linked (or warn you sensibly), and it makes you enter your new password before you've confirmed you can do anything at all.

**Comment by ara4n** [comment] 2017-07-13 15:05
Just been talking to folks about disasters where they lost 30% of a 10,000 userbase due to inability to do a password reset......

**Comment by ara4n** [comment] 2018-01-19 14:55
@dbkr can we mitigate this nowadays by using the tokenRequest APIs to do sanity checks *before* you enter the new PW?

**Comment by dbkr** [comment] 2018-01-24 17:11
Yeah, I don't see why not. We probably ought to check what auth is acceptable for a password reset (eg. if we want to support pw rest via sms too) but that's fine as we can do a call with no auth first like we do for registering.

**Comment by turt2live** [comment] 2019-02-14 23:47
This is still a problem.

**Comment by lampholder** [comment] 2019-03-14 10:23
A motivated user failed to reset their password ~5 times, it seems due to closing the tab before clicking the button you're meant to click after clicking the link in the email.

We really need a password reset flow that works like everybody else's password reset flow - it's the kind of operation people expect to complete on autopilot.

**Comment by ara4n** [comment] 2019-04-04 23:42
see also https://github.com/vector-im/riot-web/issues/2761

**Comment by ara4n** [comment] 2019-05-02 19:44
Here's another one:

<img width="909" alt="Screenshot 2019-05-02 at 20 38 27" src="https://user-images.githubusercontent.com/1294269/57102310-21324d00-6d1b-11e9-90bd-23d68ccd5f2e.png">

**Comment by lampholder** [comment] 2019-05-03 08:08
In addressing this issue we should review https://github.com/vector-im/riot-web/labels/type%3Apassword-reset too

**Comment by richvdh** [comment] 2019-05-10 08:51
see alo https://github.com/matrix-org/synapse/issues/1710

**Comment by lampholder** [comment] 2019-05-13 15:10
I've taken the 'burning fire' label off this so that we can queue it up as a roadmap item rather than try and handle it as an urgent production issue.

I've added it to the _NEXT_ column of [our roadmap](https://github.com/vector-im/riot-web/projects/16?fullscreen=true)

**Comment by Flexmaen** [comment] 2020-05-15 12:32
This is also confusing. When trying to set a new password, Riot will promt you for a password.
The whole process is very confusing, why can't this be done like everywhere else?

![riot_passwort](https://user-images.githubusercontent.com/6330276/82050575-a5ead180-96b8-11ea-8880-e166c50c0043.png)

**Comment by novocaine** [comment] 2021-08-25 13:47
I am splitting this issue into multiple actionable ones as, while we need to fix stuff, it is not currently actionable and the labels seem off.

Assumption: This ticket relates to "forgot password" specifically, not password reset.

Issues named in this one:

1. *It doesn't tell you if you have no email address linked (or warn you sensibly)*

I'm not sure if this is still relevant but I might misunderstand the meaning. In the current UI you can't reset your password without entering an email - this might have been changed at some point

<img width="708" alt="Screenshot 2021-08-25 at 14 39 40" src="https://user-images.githubusercontent.com/57377/130801380-16b398ae-b665-42c1-a0b1-9785c5d7a45b.png">

2 *and it makes you enter your new password before you've confirmed you can do anything at all*

This is confusing. On other web sites you enter a new password after verifying your email, not before. Split into https://github.com/vector-im/element-web/issues/18743

**Comment by novocaine** [comment] 2021-08-25 14:20
3. Concern in https://github.com/vector-im/element-web/issues/2780#issuecomment-488806430 is moved to https://github.com/vector-im/element-web/issues/18752

**Comment by novocaine** [comment] 2021-08-25 14:23
Closing this mega-ticket in favour of the spun out tickets created above. Yell if I have not capture a part of this in those tickets.

**Closed by novocaine** 2021-08-25 14:23 UTC
Labels: T-Defect, X-Needs-Info, S-Critical, A-Password-Reset, X-Needs-Design, Z-Chronic, O-Intermediate

**Comment by ara4n** [comment] 2021-08-25 16:22
> In the current UI you can't reset your password without entering an email - this might have been changed at some point. Need @ara4n to confirm.

From memory, the problem is that it gives you no indication if the email you provided is remotely valid or known. This might be a privacy measure, but the fact you have no idea which email address it’s asking you for and if you got the right one is still a problem afaik.

**Comment by novocaine** [comment] 2021-09-01 10:17
Clarified out of band that we just want a copy change.

**Comment by novocaine** [comment] 2021-09-01 10:24
Just checked this, and the current behaviour is that we show an error message if the email isn't recognised (at least on matrix.org)

<img width="756" alt="Screenshot 2021-09-01 at 11 20 48" src="https://user-images.githubusercontent.com/57377/131655508-93d244d8-f6ab-4a9b-88ad-9351ec353dba.png">

This is triggered by a call to `https://matrix-client.matrix.org/_matrix/client/r0/account/password/email/requestToken` 400ing and returning `{"errcode":"M_THREEPID_NOT_FOUND","error":"Email not found"}`
