### ISSUE TITLE
Element Desktop can launch in disabled monitor

### ISSUE THREAD

**Issue by james2037** [vector-im/element-web#15639] opened 2020-11-03 08:08 UTC
### Description

When starting element, the initial position of the window can be off-screen if e.g. a monitor previously in-use in a multi-monitor setup was disabled.

### Steps to reproduce

Disable a monitor which contains the initial position of the Element Desktop Window. Element will still launch the window in this position.

### Version information

Windows 10, Element Desktop 1.7.12

**Comment by t3chguy** [comment] 2020-11-03 09:42
Duplicate of https://github.com/vector-im/element-web/issues/6783

**Closed by t3chguy** 2020-11-03 09:42 UTC
Labels: bug
