### ISSUE TITLE
Smileys are too small

### ISSUE THREAD

**Issue by Hoeze** [vector-im/element-web#9146] opened 2019-03-13 00:07 UTC
Smileys are too small to read if they are in text blocks:
![grafik](https://user-images.githubusercontent.com/1200058/54244316-6365bc00-452c-11e9-980e-08cd39146d7b.png)

**Comment by jryans** [comment] 2019-03-13 09:37
Thanks for reporting this issue!

Do you feel that the font size of text generally is also too small, or only the emojis in text?

**Comment by Hoeze** [comment] 2019-03-13 10:24
The font size is OK IMHO, but I think it would be cool to have an option to configure the font somewhere in the advanced settings :)

**Comment by aaronraimist** [comment] 2019-03-13 19:14
#3160 is for configurable font sizes

**Comment by rkfg** [comment] 2020-11-07 17:03
Duplicate of #2890

**Closed** 2020-11-08 00:39 UTC
Labels: bug, p2, severity:cosmetic, severity:minor, type:emoji, ui/ux
