### ISSUE TITLE
Strangeness at login

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#16291] opened 2021-01-27 10:55 UTC
Logging in with a test account I experienced the following flow:

1. Log in to matrix.org account with username and password from https://develop.element.io
2. Get the prompt to cross sign - choose to use passphrase
3. Passphrase accepted
4. Receive the "don't you want to set up key backup" prompt you receive when you try to log out without having set up key backup, on top of the login UX
5. Choosing 'cancel' causes the prompt to flash away and then return
6. Choosing 'log out' is the only option - this logs you out

**Comment by jryans** [comment] 2021-02-12 13:07
@lampholder Hmm, it something that happens every time for that account?

**Comment by kittykat** [comment] 2021-12-21 17:00
I'm going to close this for now as the UI has changed and we cannot reproduce the issue any more

**Closed by kittykat** 2021-12-21 17:00 UTC
Labels: T-Defect, X-Needs-Info, P2, S-Tolerable, A-E2EE-Cross-Signing, X-Needs-Community-Testing
