### ISSUE TITLE
Email field on reset password is sensitive to spaces

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#20239] opened 2021-12-17 11:00 UTC
### Your use case

When resetting a password, the email field is sensitive to space characters at the end of the email, we should ignore any spaces after the email address.

This issue was found during community testing on December 16, 2021

**Comment by daniellekirkwood** [comment] 2021-12-17 11:00
This issue might be solved when we move to OIDC

**Comment by gsouquet** [comment] 2021-12-20 12:58
Could you elaborate on this?
You mention that the password reset fields trims spaces at the beginning and the end of the string? That sounds like the appropriate behaviour to me.

What are the reasons why we'd want to keep a space at the end of an email adress? This goes against the spec for a well formed email address

**Comment by daniellekirkwood** [comment] 2021-12-22 16:34
The issue was found by a community member during the testing session. If we can confirm the field trims spaces then I'm happy that we close this with no work needed/cannot reproduce

**Comment by andybalaam** [comment] 2022-03-30 13:25
Marking as good first issue, but bear in mind your first job is to check whether this is a problem or not, because there is confusion in the comments above ^

**Comment by TheReshma** [comment] 2022-03-31 16:24
![image](https://user-images.githubusercontent.com/70228821/161103329-6f53f819-04df-47eb-9ba8-ac6885c53369.png)

Well, It doesn't accept emails with space at the end.

**Comment by gsouquet** [comment] 2022-04-01 07:50
You just reproduced the issue. This is the behaviour we want to avoid.
Whitespaces should be trimmed at the beginning and the end of the input

**Comment by TheReshma** [comment] 2022-04-01 10:45
Thank you. I understood this issue now. The email field shouldn't be space sensitive but whitespaces should be trimmed after fetching the email from the user .

I'd like to work on this. Can you assign me this issue ?

**Closed** 2022-04-16 01:17 UTC
Labels: A-Password-Reset, T-Enhancement, Z-Community-Feedback, O-Occasional, good first issue, Z-Community-Testing
