### ISSUE TITLE
White Screen of Death - Sometimes white Window on  Startup

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#24110] opened 2022-12-25 18:52 UTC
Like mentioned here, it occurred today:
https://github.com/vector-im/element-web/issues/21886#issuecomment-1331450842

### Steps to reproduce
autostart command: /opt/Element/element-desktop --hidden
(I have 2 Element Profile, the other didn't even start, although it is in the autostart, too. But this also happens when you only have on Element Profile. Experienced this at others)
![grafik](https://user-images.githubusercontent.com/30293477/209478883-3a3f1d93-73c6-4868-a5db-00a154ff6e7e.png)
That green is my Desktop of one of my secondary screens.
The White is Element. It's in the foreground no matter what happens. When you have only one screen and you start another application, it's behind this white screen. If you don't know that this is element, you are lost.
(Had some acquaintance who asked for help because of this)
The only possibility to close this is to click on the element logo in the notification bar and  choose show/hide or close.
This time i clicked on show/hide twice and i see this, now:
![grafik](https://user-images.githubusercontent.com/30293477/209479068-4df63c22-18f7-4973-8f42-825f96621cb9.png)

The mouse has a offset but now keyboard inputs aren't getting accepted, therefore i can't get in the developer console :(

When i close it and start it again, everything is normal. (perhaps the startup is a little bit slow)

#### What did you expect?
Normal starting element

### Operating system

Ubuntu Mate 22.04

### Application version

Version von Element: 1.11.16 Version von Olm: 3.2.12

### How did you install the app?

https://packages.element.io/debian/

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment] 2022-12-27 07:43
Hi @JokerGermany thanks for reporting the issue. This looks like a duplicate of #22477 . If you think it is a different issue please leave a comment.

**Comment by weeman1337** [comment] 2022-12-27 07:43
duplicate of #22477

**Closed by weeman1337** 2022-12-27 07:43 UTC
Labels: T-Defect

**Comment by jessicaalaura** [comment] 2024-12-04 12:18
It seems like you are encountering the White Screen of death with Element on startup. Try updating the app, clearing the cache, or adjusting the autostart command. Additionally, you can use a blank [black screen](https://whitescreen.vip/black-screen/) tool to check for any white spots or dead pixels on your monitor, as hardware issues can sometimes contribute to such display problems.
