### ISSUE TITLE
No way to deny trust request

### ISSUE THREAD

**Issue by janosbrodbeck** [vector-im/element-web#16680] opened 2021-03-13 15:46 UTC
### Description
When logging into a new device you need to trust the new device. But when you cancel the process (e.g. because no immediate access to another device) and log into your other devices later you always get a prompt that you have an ongoing trust review. I don't want to trust this device, I don't even have access to it anymore...but I can't cancel the process now. All I can do is to do the three options in the screenshot. But none of them cancels the process. I get this prompt now every time I start element / log into one of the devices. It's really annoying.

### Steps to reproduce

- Log into account from unknown device
- Do not do the trust process
- Log into trusted device and try to block/cancel the unknown device request

Describe how what happens differs from what you expected.

I expect a cancel/deny button.

![element](https://user-images.githubusercontent.com/5045674/111035300-1b7b1780-841a-11eb-84c5-1c45d303df76.png)

### Version information

- **Platform**: web and desktop

For the web app:

- **Browser**: Firefox
- **OS**: Ubuntu + Arch Linux
- **URL**: Element version: 1.7.22 olm version: 3.2.1

For the desktop app:

- **OS**: Ubuntu + Arch Linux
- **Version**: Element version: 1.7.22 olm version: 3.2.1

**Comment by t3chguy** [comment] 2021-03-15 09:26
> I don't even have access to it anymore...

You should de-authorise the device from your account then in Settings > Security & Privacy
that'll stop the prompts.

Related https://github.com/vector-im/element-web/issues/14343

I think this is a duplicate of https://github.com/vector-im/element-web/issues/13187

**Closed by t3chguy** 2021-03-15 09:26 UTC
Labels: A-E2EE-Cross-Signing, T-Defect
