### ISSUE TITLE
Embed links to images/videos, like how discord does it

### ISSUE THREAD

**Issue by obj-obj** [vector-im/element-web#25130] opened 2023-04-18 03:59 UTC
### Your use case

This would allow, for example, discord bridges to just send a link to the image (still on discord's servers), rather than downloading every single image sent in every bridged channel, without requiring the link to be clicked to view the image.

Example of how it works in Discord:

[2023-04-17 20-54-17.webm](https://user-images.githubusercontent.com/57120300/232667386-372bebbc-968e-444f-867e-ceeda0123c86.webm)

### Have you considered any alternatives?

There is an existing sort-of embed, but the image is extremely small (meaning you have to click it to view it)
![image](https://user-images.githubusercontent.com/57120300/232667530-155c0a8d-178b-42f6-8e50-a85d19e2a65e.png)

### Additional context

I had the idea to make this issue after reading https://github.com/mautrix/discord/issues/16

**Comment by t3chguy** [comment] 2023-04-18 07:33
Duplicate of https://github.com/vector-im/element-meta/issues/1099

**Closed by t3chguy** 2023-04-18 07:33 UTC
Labels: T-Enhancement

**Comment by obj-obj** [comment] 2023-04-19 04:17
Oh, didn't check other repositories for issues, sorry
