### ISSUE TITLE
Video dimensions not verified

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#4478] opened 2017-07-03 02:50 UTC
### Description

![image](https://user-images.githubusercontent.com/1190097/27776444-e0a4c988-5f67-11e7-8cb4-c864fb4a0b37.png)

(ruler on right side is another monitor)

Video file was https://t2l.io/_matrix/media/v1/download/matrix.org/TiGRzLzVjIvgbnjPdZDaWsdv

### Steps to reproduce

- Send portrait video to room
- Browse file panel

The video was recently shot, so the pagination should not(?) affect it.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment] 2017-07-05 15:38
It seems to work fine for me:
- Chrome 59
- macOS Sierra

![image](https://user-images.githubusercontent.com/1922197/27872228-fd30132a-619f-11e7-8345-c76339fdbdf5.png)

I'll see if I can reproduce on Windows

**Comment by lampholder** [comment] 2017-07-05 15:43
Seems to work fine on Chrome 59 on Windows 7, too. I can try on my Windows 10 machine when I get home.

It seems unlikely to be a Chrome 58 thing or a Windows 10 thing, though, I'd have thought :\

**Comment by turt2live** [comment] 2017-07-05 22:16
Turns out that the video was shot on a mobile device (android) using the built-in video function. They said their phone filmed portrait when they had it landscape (this is a different bug).

The app claimed the video was 470x280 instead of 280x470 because of the weird landscape-flipping thing and therefore the preview in the file pane overflows.

The latest version of the android app just crashes when i try to replicate this, so it's probably from an older version. A workaround to relying on other buggy behaviour would be to send an event using curl and flip the dimensions.

**Comment by kittykat** [comment] 2021-08-11 12:29
It seems to be working right with latest Android-produced videos both on web and desktop, and it sounds like the issue is more with the recording than element-web. So closing for now, please reopen if you feel that it's still valid.

![Screenshot from 2021-08-11 13-26-54](https://user-images.githubusercontent.com/51663/129028678-69baeeef-c799-4d18-884b-9ec005d1f916.png)

**Closed by kittykat** 2021-08-11 12:29 UTC
Labels: T-Defect, P2, S-Minor, A-File-Panel
