### ISSUE TITLE
DM invite accepted on another device did not move out of "invites" section of room list

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25428] opened 2023-05-23 14:49 UTC
### Steps to reproduce

1. While viewing a space, receive a DM invite from someone in that space
2. Accept it on another device
3. Note that the DM doesn't move down
4. Click another space and back
5. DM moved down

#### What did you expect?

The room list state to match what happened on other devices

#### What happened instead?

See above. Clicking the room in the invite caused a timeline to be opened, as it knew it was a real room.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023052201 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-05-31 11:23
Unfortunately I cannot reproduce it. @turt2live can you add the DM room Id and user Id to the rageshake? Maybe I can find something interesting in the logs.

**Comment by turt2live** [comment] 2023-05-31 14:06
It's always whatever DM has unread messages when I refresh. 

I'll test again later today.

**Comment by t3chguy** [comment] 2023-11-16 11:51
Closing due to no reproductions

**Closed by t3chguy** 2023-11-16 11:51 UTC
Labels: T-Defect, X-Cannot-Reproduce
