### ISSUE TITLE
Element Desktop turns in to an unresponsive white screen after a day or so open on both my Windows desktop and my Macbook

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#26588] opened 2023-11-15 09:48 UTC
### Steps to reproduce

Element Desktop works fine for "a while", then becomes unresponsive and is just a white rectangle. Restarting it brings it back to life.

I've just restarted on my mac - I'll update this issue when it next becomes unresponsive.

I'm currently on Element version: 1.11.48, Crypto version: Olm 3.2.15 but this issue has affected my desktop experience for a while. I'll upgrade now to latest.

### Operating system

macOS 14.0 (23A344)

### Application version

Element version: 1.11.48 Crypto version: Olm 3.2.15

### How did you install the app?

website

### Homeserver

lant.uk

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-11-15 22:38
Duplicate of https://github.com/vector-im/element-desktop/issues/672

**Closed by t3chguy** 2023-11-15 22:38 UTC
Labels: T-Defect, S-Critical, X-Release-Blocker, A-Electron, O-Frequent
