### ISSUE TITLE
"Give feedback" link for spaces in "Explore rooms" doesn't work

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19029] opened 2021-09-14 10:53 UTC
### Steps to reproduce

1. Go to "Explore rooms"
2. See this top-right: 
![Screenshot from 2021-09-14 11-51-27](https://user-images.githubusercontent.com/51663/133244943-76552e17-f3b0-4b5f-9671-36a0de7f10e0.png)

3. Try clicking "Give feedback"

### What did you expect?
Something to happen

### What happened?
Nothing

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment] 2021-09-14 10:56
Duplicate of https://github.com/vector-im/element-web/issues/18524

**Closed by t3chguy** 2021-09-14 10:56 UTC
Labels: T-Defect, S-Critical, A-Spaces, O-Intermediate, Z-Spaces-Testing
