### ISSUE TITLE
Desktop app tells me I need to use the desktop app to search encrypted rooms

### ISSUE THREAD

**Issue by Prog1563** [vector-im/element-web#16721] opened 2021-03-18 22:27 UTC
### Description

When trying to search an encrypted room on the desktop app, the search returns no results and tells me I need to use the desktop app...

### Steps to reproduce

- Open up Riot/Element
- Open an E2EE room
- Attempt a search

Describe how what happens differs from what you expected.

When searching using the desktop app, I would expect the search to work, maybe take a little while to decrypt... But it just immediately returns no results.

Logs being sent: yes

![Screenshot_2021-03-18_18-24-47](https://user-images.githubusercontent.com/55600371/111705557-4b119180-8817-11eb-9cef-d4e771b5108d.png)

![Screenshot_2021-03-18_18-23-57](https://user-images.githubusercontent.com/55600371/111705476-23bac480-8817-11eb-8f6f-a281a8ded402.png)

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Manjaro / Arch Linux
- **Version**: Rolling release, full up to date as of the creation of this issue.

**Comment by SimonBrandner** [comment] 2021-03-19 06:56
Related to/possible duplicate of [#16636](https://github.com/vector-im/element-web/issues/16636), [#14229](https://github.com/vector-im/element-web/issues/14229), [#15715](https://github.com/vector-im/element-web/issues/15715)

**Comment by t3chguy** [comment] 2021-03-19 09:42
> Logs being sent: yes


No logs seem to have been sent

Closing as duplicate of https://github.com/vector-im/element-web/issues/16636

**Closed by t3chguy** 2021-03-19 09:42 UTC
Labels: A-Indexing, A-Search, T-Defect
