### ISSUE TITLE
Make a configuration option so text input can default to either markdown or plain

### ISSUE THREAD

**Issue by voice06** [vector-im/element-web#19802] opened 2021-11-18 16:45 UTC
#### What would you like to do?
I would like the ability to configure Element so by default it doesn't go through markdown unless I specify it.

#### Why would you like to do it?
Some messages get mangled due to markdown being always-on unless I use /plan, for example if I'm sending irc-style hostmasks, ie *!*@*.hostname.tld in a irc channel results in the *'s being interpreted as `<em></em>`. Its nice to have markdown but coming from a IRC background I'm much more used to sending plain messages.

#### How would you like to achieve it?
A preference option for this would be nice, when I mentioned it in a room someone also mention it'd be nice to have as a per-room option as well.

**Comment by SimonBrandner** [comment] 2021-11-18 18:27
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of [#???](https://github.com/vector-im/element-web/issues/483)

**Closed by SimonBrandner** 2021-11-18 18:27 UTC
Labels: T-Enhancement
