### ISSUE TITLE
Discrepancy in displaying usernames

### ISSUE THREAD

**Issue by TheReshma** [vector-im/element-web#21831] opened 2022-04-17 12:54 UTC
### Steps to reproduce

1. Go to app.element.io in your browser
2. Join this room :  #hookshot:half-shot.uk
3.  Scroll to messages before 15th of April 2022.
4.  You'd see the same user sometimes represented by his username & sometimes by his matrix user id .. 
5. This is what I mean : 
![image](https://user-images.githubusercontent.com/70228821/163714797-7d6da931-3969-4213-8bc0-d5c978c44c3f.png)
![image](https://user-images.githubusercontent.com/70228821/163714820-e280e9ed-8108-4146-b20e-0ddd364ac1c5.png)

Another one 
![image](https://user-images.githubusercontent.com/70228821/163714850-d1b38d76-a56c-47e2-8c20-edbd814793a8.png)
![image](https://user-images.githubusercontent.com/70228821/163714862-34ebd1d9-fc8b-4844-b618-8c9d9e9b331a.png)

#### What did you expect?
Consistency in usernames
#### What happened instead?
Usernames & user ids are swapped sometimes. Avatar is not shown.
#### How long have you been noticing this ?
For about 2 days
#### Does it display names properly when the window is refreshed ?
No
#### Does it happen only in #hookshot:half-shot.uk ?
Maybe. I did look through the other rooms but didn't find this error.
#### Are you sure that they're the same user ?
Yes.

### Operating system

Windows 10

### Browser information

Edge

### URL for webapp

app.element.io

### Application version

Element version: 1.10.10 Olm version: 3.2.8

### Homeserver

Matrix

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-17 14:02
Duplicate of https://github.com/vector-im/element-web/issues/7417

**Closed by robintown** 2022-04-17 14:02 UTC
Labels: T-Defect
