### ISSUE TITLE
Message deleted icon clips strangely when zooming in

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#13634] opened 2020-05-11 17:05 UTC
Latest chrome, /develop, bottom clipped @ 110%:

<img width="277" alt="Screenshot 2020-05-11 at 18 06 00" src="https://user-images.githubusercontent.com/4626865/81591068-bbf44b80-93b3-11ea-88f0-1b43e9fc23a9.png">

**Comment by aaronraimist** [comment] 2020-05-22 19:53
Hmm can't reproduce in Firefox or Chrome on macOS

**Comment by t3chguy** [comment] 2023-07-10 13:06
Closing due to no reproductions since

**Closed by t3chguy** 2023-07-10 13:06 UTC
Labels: T-Defect, X-Cannot-Reproduce, A-Redaction
