### ISSUE TITLE
Icon in systray is labelled «electron»

### ISSUE THREAD

**Issue by ariasuni** [vector-im/element-web#23288] opened 2022-09-15 16:59 UTC
### Steps to reproduce

1. Launch Element
2. Check Element icon in systray

#### What did you expect?

The icon in the systray to be labeled Element.

#### What happened instead?

The icon in the systray is labeled Element.

Label when hovering the systray icon:
![image](https://user-images.githubusercontent.com/2446451/190462488-a7f669df-d447-4521-9c4a-530a3fcee0b4.png)

Label when the icon is hidden part of the systray:
![image](https://user-images.githubusercontent.com/2446451/190461728-218aa514-dd50-44b7-8b87-9bb654980b7d.png)

### Operating system

Arch Linux

### Application version

Element version 1.11.4, olm version 3.2.12

### How did you install the app?

https://archlinux.org/packages/community/x86_64/element-desktop/

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-09-15 17:00
Duplicate of https://github.com/vector-im/element-web/issues/22914

**Closed by t3chguy** 2022-09-15 17:00 UTC
Labels: T-Defect
