### ISSUE TITLE
User info default avatars are tiny

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#26135] opened 2023-09-07 06:13 UTC
### Steps to reproduce

1. Click on someone's avatar to open User Info (assuming they don't have an avatar set)

#### What did you expect?

A regular sized avatar.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/c6c6b43d-7e61-45ec-9ffa-9aedffae155c)

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023090601 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-09-07 07:50
Partially regressed by https://github.com/matrix-org/matrix-react-sdk/commit/09c5e06d12ac15511e8310a572a3295064394dee It was good before that commit and broken after that (the letter was already in a wrong position but with a higher font weight).

**Comment by kittykat** [comment] 2023-09-07 13:40
Duplicate of #26081

**Closed by kittykat** 2023-09-07 13:40 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Avatar, O-Occasional
