### ISSUE TITLE
Switching tabs on chrome OS ends when reaching riot web 

### ISSUE THREAD

**Issue by kingflurkel** [vector-im/element-web#6076] opened 2018-01-31 22:30 UTC
### Description

When switching between tabs using ctrl+tab on a chromebook, I got stuck on riot web. The ctrl+tab resulted in selecting the input field. 

### Steps to reproduce

- Open chrome 
- Open a few tabs 
- In one of the tabs go to your favorite room on riot web
- Focus on the input field (click in it)
- Now start cycling the tabs with ctrl+tab 
- Get stuck at the riot one

I expect it to not do that so I can continue happily switching tabs.

### Version information

- **Platform**: web (in-browser) or desktop?
ChromeOS / Google Pixelbook / web in browser

**Comment by lampholder** [comment] 2018-02-01 10:08
I don't have a ChromeOS machine to verify this, though I can confirm it's not a problem on Chrome browser on mac, ubuntu or windows.

**Comment by siddhanathan** [comment] 2018-02-10 22:54
Unable to reproduce. Chrome OS v63 running on Kevin (Samsung Chromebook Plus).

**Comment by HarHarLinks** [comment] 2018-02-22 17:44
This is an issue for me (Windows 7 x64) using Vivaldi 1.15.1104.3 x64, which is based on Chromium 64.0.3282.170.

**Comment by ldexterldesign** [comment] 2018-05-02 18:00
Hey all,

My partner and I are experiencing the same issue, respectively:

Device: Apple MacBook Pro
Platform: OS X 10.13.4 (17E199)
Browser: Vivaldi 1.15.1147.36 (Stable channel) (64-bit)

Device: n/a
Platform: Windows
Browser: Vivaldi 1.15.1147.36 (Stable channel) (32-bit)

We don't suffer this issue in Chrome so I can only assume it's a (Blink) engine issue that's been resolved in Chrome but not Vivaldi yet?

Regards

**Comment by ldexterldesign** [comment] 2018-09-19 10:41
https://forum.vivaldi.net/topic/7386/vivaldi-steals-focus-prevent-alt-tabbing-to-other-applications/7

**Comment by ldexterldesign** [comment] 2018-10-25 14:53
BUMP

**Comment by t3chguy** [comment] 2022-05-17 10:59
Has anyone reproduced this since 2018?

**Comment by ldexterldesign** [comment] 2022-05-17 18:35
Hi @t3chguy,

Thanks for follow up

This is a Vivaldi issue so feel free to close this issue

Regards

**Closed** 2022-05-17 18:36 UTC
Labels: T-Defect, Z-Platform-Specific, P3, S-Major
