### ISSUE TITLE
Remove button on the 'Encryption Enabled' banner isn't clear

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15236] opened 2020-09-18 14:46 UTC
A user could reasonably expect the button to hide the banner instead of destroying the room:
![](https://i.imgur.com/l37y2T5.png)

**Comment by kittykat** [comment] 2021-12-01 13:05
> Remove button no longer there

I'm going to close this issue for now as we cannot reproduce it. Please comment with @kittykat if you are still experiencing it and I will reopen the issue for you.

**Closed by kittykat** 2021-12-01 13:05 UTC
Labels: T-Defect, P2, S-Major, A-E2EE, A-Timeline, X-Needs-Community-Testing
