### ISSUE TITLE
Black screen, no GUI on Element Desktop 1.11.35

### ISSUE THREAD

**Issue by RevAngel7** [vector-im/element-web#25776] opened 2023-07-12 11:08 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…
When autostarting or manually starting Element Deskotp on Ubuntu Linux (22.04.02, Kernel 6.4.3 mainline, mesa (AMD) 23.2, enough RAM and disk space, fast system) Element opens but shows only a black/dark grey screen with the Element title on top. It seems that I can click invisible things where they supposed to be, but nothing visibly shows, just the cursor shows a hand symbol on some positions. A restart after close (and checking active processes) brings no solution.
![Bildschirmfoto vom 2023-07-12 12-57-02](https://github.com/vector-im/element-web/assets/38556983/17eea0a2-a9f2-4bcb-8164-8af5d8a7540e)

#### What happened instead?
Expected behaviour would be to show Element Desktops GUI. Instead it doesn't.

### Operating system

Ubuntu 22.04.02, mainline kernel 6.4.3, mesa (AMD) 23.2

### Application version

1.11.35 amd64 from packet manager because GUI not usable

### How did you install the app?

https://element.io/download#linux

### Homeserver

matrix.org

### Will you send logs?

No
```[tasklist]
### Tasks
```

**Comment by RevAngel7** [comment] 2023-07-12 11:12
I did a 
element-desktop /rageshake
command manually to get the logs, but since the above picture is the only GUI I get it will be impossible to show it to you the "normally" intended way.

**Comment by insidesmart** [comment] 2023-07-13 13:06
Just want to highlight that I am facing the same problem in Element Desktop App for Linux. Would love to have a fix.

**Comment by efflamlemaillet** [comment] 2023-07-13 21:56
I got similar issue  with version 1.11.35  with  Linux.
I figured  out a way to fix : 
1. Stop completely element processes.
2. Delete  GPUCache folder (~/.config/Element/GPUCache/)

**Comment by insidesmart** [comment] 2023-07-14 01:34
@efflamlemaillet Thanks for providing the steps. It fixed the issue.

**Comment by RevAngel7** [comment] 2023-07-14 04:53
@efflamlemaillet fix did not work for me. It just changed the issue from a blank screen to two narrow (around 60px and 40px) collumns, and a huge section showing the chat.
![Bildschirmfoto vom 2023-07-14 06-52-39](https://github.com/vector-im/element-web/assets/38556983/76cb0712-43ee-42ac-858b-d7399f849420)

**Comment by t3chguy** [comment] 2023-07-14 07:37
@RevAngel7 you can expand the room list by dragging its resize handle.

**Comment by t3chguy** [comment] 2023-07-14 07:37
Duplicate of https://github.com/vector-im/element-desktop/issues/1074

**Closed by t3chguy** 2023-07-14 07:37 UTC
Labels: T-Defect, Z-Platform-Specific, S-Critical, A-Electron, O-Uncommon

**Comment by RevAngel7** [comment] 2023-07-14 07:40
Thank you. I tried that before, but on the first try the mouse pointer icon to resize was there, but it did not work. Now I tried again after restarting Element, and it worked.

**Comment by G0rd0n** [comment] 2025-06-21 09:18
So I am experiencing the same issue, only with the screen completely black and no title on top. I can resize the window, but no buttons interaction of any kind. Element only starts in the background when I want to launch it.
Also the folder (~/.config/Element/GPUCache/) does not exist for me. So I am have a bit of trouble finding the right direction
Pop!_OS with Element 1.11.104
 ~minor update: I found the folder as /.var/app/im.riot.Riot/config/Element/GPUCache and deleted it. But restarting element after that did not solve the issue.
