### ISSUE TITLE
Instead of including the reply in the notification when someone replies to a message, it should say that the message replies to a message

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#21117] opened 2022-02-18 01:21 UTC
Could be
```
In reply to <user>: <reply message content>
```

instead of
```
> <@user:domain.tld> <message content>
<reply message content>
```
...if the replied message is too long, it wouldn't fit in the notification

**Comment by SimonBrandner** [comment] 2022-02-18 06:33
Related/duplicate of https://github.com/vector-im/element-web/issues/9119

**Comment by t3chguy** [comment] 2022-02-18 07:47
Closing in favour of #9119

**Closed by t3chguy** 2022-02-18 07:47 UTC
Labels: A-Notifications, A-Replies, T-Enhancement, O-Frequent
