### ISSUE TITLE
When enabling encryption, link directly to verification rather than telling the user to tap on their avatar(!)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18140] opened 2021-07-21 10:22 UTC
<img width="971" alt="Screenshot 2021-07-21 at 11 21 19" src="https://user-images.githubusercontent.com/1294269/126473778-d339148e-d262-4f63-bb01-5756b78079d3.png">

Surely we should provide a verification button directly inline which does the right thing rather than telling the user to click on avatars and stuff...

**Comment by robintown** [comment] 2021-07-21 12:20
Duplicate of https://github.com/vector-im/element-web/issues/15831

**Closed by robintown** 2021-07-21 12:20 UTC
Labels: T-Defect
