### ISSUE TITLE
Windows 10 notification breaks Riot window

### ISSUE THREAD

**Issue by tgm-git** [vector-im/element-web#9193] opened 2019-03-17 12:08 UTC
### Description

While the Riot window is open and without focus, receiving a message, that causes windows show a notification, will make the Riot window uninteractable.
No errors messages are shown however the window cannot regain focus

### Steps to reproduce

- Open Riot window
- Move focus (click somewhere else)
- Receive a message
- The Riot window can't be interacted with any longer

Describe how what happens differs from what you expected.

The Riot window should remain interactable

Log: not sent  

### Version information

matrix-react-sdk version: <local>
riot-web version: 1.0.3
olm version: 3.0.0

- **Platform**: desktop
For the desktop app:

- **OS**: Windows
- **Version**: 1.0.3

**Comment by turt2live** [comment] 2019-03-18 15:11
Without logs I'm afraid this is impossible to troubleshoot. As a Windows 10 user myself, I can't reproduce  this. 

After experiencing the problem, please go to the Help tab of your settings and click "Submit debug logs", referencing this issue. If the application needs to be killed first then please do so before sending logs (the logs will include your last session, so no need to worry about losing them).

**Comment by tgm-git** [comment] 2019-03-26 16:27
I have submitted debug logs after reproducing the issue again today.

**Comment by t3chguy** [comment] 2019-03-26 16:31
I doubt debug logs will help much as this issue will very much be in Electron land rather than Riot, and Electron logs to its own place where Riot doesn't see it

**Comment by turt2live** [comment] 2019-03-26 16:33
in fact, they didn't help and I was just coming here to say that it looks like there is indeed a crash, but not one we can see. I've opened https://github.com/vector-im/riot-web/issues/9283 for future people who might be bitten by a similar scenario.

I'm not sure where Electron keeps its logs, but if found it'd be good to get a copy of them for investigation. Feel free to send them over private chat to me (`@travis:t2l.io` on matrix) if you're not comfortable posting them here.

**Comment by t3chguy** [comment] 2022-05-10 20:50
Closing due to lack of main process logs, please shout if you are still seeing this

**Closed by t3chguy** 2022-05-10 20:50 UTC
Labels: T-Defect, Z-Platform-Specific, X-Cannot-Reproduce
