### ISSUE TITLE
Need a persistent room list window after joining a room

### ISSUE THREAD

**Issue by siddhartharao17** [vector-im/element-web#12441] opened 2020-02-20 18:52 UTC
**Current feature**
When I click on the "Explore" button, I get a window showing me a list of rooms like this ![Window-showing-rooms-list](https://user-images.githubusercontent.com/8169998/74967879-b0097680-53ce-11ea-9c3c-7ab12d90fc1a.png)
When I scroll through the list to find my channel of interest, I click on "Join" on the right. The window then disappears and drops me in the room. In this case I'm only limited to join 1 room at a time which is time consuming and also frustrating to some extent.

**Solution I'd like**
I'd like to keep the rooms list window persistent after joining a room instead. This way I won't be repeating the efforts of scrolling/searching for a room and I would also be able to join multiple rooms at the same time. 

**Additional context**
When I click on "Join", the button changes to "View" but I'm still on the rooms list window and once I'm done all the rooms of my interest, I can just click the X on the top right to exit.

**Comment by bkil** [comment] 2022-03-03 11:55
Related to #21288

**Comment by t3chguy** [comment] 2023-04-25 15:09
Duplicate of https://github.com/vector-im/element-web/issues/12269

**Closed by t3chguy** 2023-04-25 15:09 UTC
Labels: A-Room-Directory, T-Enhancement
