### ISSUE TITLE
badge notification not shown

### ISSUE THREAD

**Issue by pyrates999** [vector-im/element-web#23575] opened 2022-10-24 05:32 UTC
### Steps to reproduce

1. Notifications are enabled
2. I see the number of unread notifications in the system tray
3. The number of unread notifications is not shown as a badge notification on the app icon in the windows task bar like it does on skype and discord

#### What did you expect?
I should see the number of unread notifications, shown as a badge notification on the app icon, in the windows task bar.  Discord and Skype are able to show them.
#### What happened instead?
No badge notifications are shown on the app icon in the windows task bar.

### Operating system

windows

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### How did you install the app?

From https://element.io/get-started#download

### Homeserver

https://matrix.to/#/#rossmannrepair:matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-10-24 07:57
Duplicate of https://github.com/vector-im/element-web/issues/14033

**Closed by t3chguy** 2022-10-24 07:57 UTC
Labels: T-Defect
