### ISSUE TITLE
Old calls sometimes ring the user when reloading a room

### ISSUE THREAD

**Issue by karlabbott** [vector-im/element-web#21722] opened 2022-04-08 12:12 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Make a 1:1 video call using Element web at some point. Close out the tab Element is in.

Re-open element and go to the room that you made the 1:1 call in.

#### What did you expect?

To enter the room and not get a call.

#### What happened instead?

Entered the room and was notified I had a call from the other user. Upon joining the call, it was an empty room. After talking to that user, they informed me they had not called me.

### Operating system

Fedora Linux 35 Kinoite

### Browser information

Brave Version 1.37.109 Chromium: 100.0.4896.60 (Official Build) unknown (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: cec31d0e714e-react-f63923d60fad-js-6d0f4e537ea5 Olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-04-08 14:26
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of  https://github.com/vector-im/element-web/issues/21294

**Closed by SimonBrandner** 2022-04-08 14:26 UTC
Labels: T-Defect
