### ISSUE TITLE
Room alias and mentions

### ISSUE THREAD

**Issue by v411e** [vector-im/element-web#23206] opened 2022-09-05 08:17 UTC
#### What would you like to do?
Mentioning a room without an alias is not possible. But the standard user does not know that an alias should be set for a newly created room in order to make it mentionable in messages. This leads to confusion at the users side, because it is unclear why some rooms can be mentioned and some can't. 

#### Why would you like to do it?
Mentioning rooms is very handy in daily business. The current state is too complex for normal users. They do easily find the reason why a room is not mentionable and how they can fix it.

#### How would you like to achieve it?
Option 1:
Create a default alias for each newly created room that can be used to mention the room in messages.

Option 2:
Make it possible to mention rooms without alias in messages

Option 3:
Tell the user on room creation that an alias is useful and should be set. Currently there is not even an option to set an alias in the room creation dialogue.
![image](https://user-images.githubusercontent.com/8049779/188400836-a2b3b4e9-941e-499f-a081-ec76992bb939.png)

### Have you considered any alternatives?

Render internal room id's like !ioheCZEUhpuHlhoCPS:example.com as pills in messages.

### Additional context

If this is implemented in Web, it might be useful for mobile clients as well.

**Comment by t3chguy** [comment] 2022-09-05 08:28
Duplicate of https://github.com/vector-im/element-web/issues/17996

**Closed by t3chguy** 2022-09-05 08:28 UTC
Labels: T-Enhancement

**Comment by v411e** [comment] 2022-09-05 08:36
Hmmm I don't really see this as a duplicate. Maybe I should have named it "Auto-create room alias".

**Comment by t3chguy** [comment] 2022-09-05 08:39
Room aliases are single use and squattable, so they shouldn't be used where not needed, they're only strictly needed for public rooms. If every time someone created a private room about something that burned the nice aliases for it all public room aliases would get much longer and harder to remember

**Comment by v411e** [comment] 2022-09-05 13:17
I agree, but this makes it really hard for normal users to use room mentions for their created rooms. I think there should be at least an option to create an alias when creating a room. This option would allow us to explain the advantages and disadvantages to the user and they can decide on their own, whether they need an alias

**Comment by t3chguy** [comment] 2022-09-05 13:19
That's what #17996 is about - the ability to use room mentions without an alias. I suggest creating a discussion in https://github.com/vector-im/element-meta if you want to promote use of aliases even for non-public rooms, this is something that should be consistent across all Element clients, not just Web
