### ISSUE TITLE
Chat sidebar expanded state not remembered if window is narrow when the app launches

### ISSUE THREAD

**Issue by Pointedstick** [vector-im/element-web#15661] opened 2020-11-05 23:17 UTC
### Description
When you manually expand a collapsed sidebar, your choice is not remembered across app launches.

### Steps to reproduce
- Resize the app's window to be narrow until the chat sidebar collapses automatically
- Manually expand it
- Quit the app
- Re-open the app

At this point the chat sidebar is collapsed, implicitly ignoring your prior choice to expand the sidebar at a narrow window width.

This is annoying because I tile the window horizontally, and at that width, the app always opens with the sidebar collapsed even though I want it expanded and there is plenty of space in the chat view to use an expanded sidebar:

![Screenshot_20201105_161546](https://user-images.githubusercontent.com/1097249/98307039-2c0a1580-1f82-11eb-9284-61f5b9ac1839.jpeg)

### Version information
- **Platform**: desktop
- **OS**: Linux: openSUSE Tumbleweed
- **Version**: 1.7.10

**Comment by turt2live** [comment] 2020-11-05 23:18
Duplicate of https://github.com/vector-im/element-web/issues/14496 - still unclear on cause.

**Closed by turt2live** 2020-11-05 23:18 UTC
Labels: bug
