### ISSUE TITLE
Colors in darkmode very aggressive and grating

### ISSUE THREAD

**Issue by IF-Adin** [vector-im/element-web#26157] opened 2023-09-13 05:57 UTC
### Steps to reproduce

1. Start Element web

#### What did you expect?

I expected the dark color scheme to be calm and easy to read, like they have been before 1.11.41

#### What happened instead?

The dark color mode is not calm and easy to read. This is very literally causing me actual eye strain to look at.

![Screenshot_20230913_064312](https://github.com/vector-im/element-web/assets/11959695/60bc1320-8737-4df4-bb5c-70dad2f32df3)

### Operating system

Linux

### Application version

Element version: 1.11.41 Olm version: 3.2.14

### How did you install the app?

From the repository

### Homeserver

Synapse 1.91.2

### Will you send logs?

No

**Comment by Johennes** [comment] 2023-09-13 06:26
Thanks for your report. We're already tracking this in https://github.com/vector-im/compound/issues/217.

**Comment by Johennes** [comment] 2023-09-13 06:27
Duplicate of https://github.com/vector-im/compound/issues/217

**Closed by Johennes** 2023-09-13 06:27 UTC
Labels: T-Defect

**Comment by dkasak** [comment] 2023-09-19 21:56
@Johennes Is this really a duplicate of that issue? The screenshot in this issue is clearly talking about room avatars while the other issue is talking specifically about username colours.

**Comment by Johennes** [comment] 2023-09-20 06:05
Assuming this issue speaks to the color of text in the default avatars, that color is identical to the username color. So we cannot fix one without the other and the problem of "usernames are too bright" really is the same as "avatars are too bright".

I've changed the title of https://github.com/vector-im/element-meta/issues/2046 to better reflect that.
