### ISSUE TITLE
RoomUpgradeWarningBar: Unstable room version v5, upgrade to v4

### ISSUE THREAD

**Issue by jomat** [vector-im/element-web#11820] opened 2020-01-11 14:20 UTC
### Description
Users sometimes see the RoomUpgradeWarningBar in v5 rooms, clicking on upgrade tries to downgrade to v4. This message also disappears again when switching rooms.
![unstableroom](https://user-images.githubusercontent.com/381286/72205488-706c7800-347b-11ea-8ebc-db62dc8de957.png)

### Steps to reproduce

- Be admin in a v5 room

### Version information

riot-web 1.5.7-rc.2, but also happened in older versions.

**Comment by turt2live** [comment] 2020-01-12 02:50
@jomat please rageshake for this issue.

**Comment by jomat** [comment] 2020-01-12 10:54
How? I only know the rageshake on riot-android.

**Comment by turt2live** [comment] 2020-01-12 16:19
Settings -> help -> submit debug logs

**Comment by yangm97** [comment] 2020-01-15 15:57
Just sent some logs for this.

**Comment by aaronraimist** [comment] 2020-01-15 21:00
Related: #11636

**Comment by turt2live** [comment] 2020-01-16 00:50
One instance of this is the homeserver being offline/slow during startup, so Riot thinks that there's no capabilities and therefore nothing is safe. We could probably fix this by altering the defaults a bit, or by being less aggressive when the request fails.

**Comment by turt2live** [comment] 2020-01-19 02:30
keeping this open to track the cache problem (and when this happens again for v6)

**Comment by t3chguy** [comment] 2022-05-07 03:24
Duplicate of https://github.com/vector-im/element-web/issues/16068

**Closed by t3chguy** 2022-05-07 03:24 UTC
Labels: T-Defect, A-Room-Upgrades
