### ISSUE TITLE
Require confirmation when clicking away room settings with unsaved changes

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#21568] opened 2022-03-26 15:48 UTC
#### What would you like to do?

Have a confirmation popup or the likes when clicking away from unsaved changes in room settings.

#### Why would you like to do it?

When I've edited room settings in some way in the "general" tab, and not saved those changes, and then click away (another tab, going back to the room by clicking the cross mark or outside the settings modal), element immediately discards the changes without prompting.

### Additional context

Here's how discord does it, it requires you to save all changes (or it'll "shake its head"), and has a toast banner at the bottom of the screen while doing so.

(Video cropped for relative privacy)

https://user-images.githubusercontent.com/22740616/160247085-a4d3c891-0e2a-416d-93dc-5b47e1d634b7.mp4

**Comment by t3chguy** [comment] 2022-03-28 08:20
Duplicate of https://github.com/vector-im/element-web/issues/6109

**Closed by t3chguy** 2022-03-28 08:20 UTC
Labels: A-Room-Settings, X-Needs-Design, T-Enhancement, O-Occasional
