### ISSUE TITLE
develop shows squares instead of some characters and meta space icons are missing

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#24204] opened 2023-01-10 16:46 UTC
### Steps to reproduce

1. Update to latest version of develop

![Screenshot from 2023-01-10 16-46-46](https://user-images.githubusercontent.com/51663/211611974-321a10ad-4cbb-4bde-9e2c-cc41033870cb.png) ![Screenshot from 2023-01-10 16-49-35](https://user-images.githubusercontent.com/51663/211612602-5e0f376e-1402-4d19-927a-996e3353f873.png) ![Screenshot from 2023-01-10 16-43-40](https://user-images.githubusercontent.com/51663/211611341-ccd43fd5-4b2e-4aa9-9e78-513670a12a61.png)

#### What did you expect?
Numbers, room names in the left panel, user list in the right panel all show correct characters. Metaspace icons are there.

#### What happened instead?
Some characters are shown as rectangles in those areas. Metaspace icons are missing

### Browser information

Chromium 108.0.5359.124 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 5b730f4b07b1-react-67396020e823-js-185ded4ebc25 Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by andybalaam** [comment] 2023-01-10 17:13
I can now reproduce this in Firefox and Chromium on Ubuntu Linux 22.04

**Comment by andybalaam** [comment] 2023-01-10 17:17
Other things are missing to, e.g. the Jump to unread button:
![image](https://user-images.githubusercontent.com/76812/211618548-6f30a576-e32d-4eda-a870-664419ec6ec6.png)

and all the buttons in the composer

**Comment by andybalaam** [comment] 2023-01-10 17:19
Getting lots of 404s
![image](https://user-images.githubusercontent.com/76812/211618864-12b64539-168f-42c1-bb8c-680d23ff4dcb.png)

**Comment by turt2live** [comment] 2023-01-10 20:08
I can't reproduce this locally, which implies deployment issue.

* https://github.com/vector-im/element-web/actions/runs/3884595985 -> Build is fine (down arrow on language dropdown for signin)
* https://github.com/vector-im/element-web/actions/runs/3885207742 (the next successful build) -> Build is not fine (missing down arrow on language dropdown for signin)

**Comment by turt2live** [comment] 2023-01-10 20:28
The 404 errors look legit, which has me concerned about what was actually deployed to R2 here.

**Comment by turt2live** [comment] 2023-01-10 20:35
I've reverted the 3 commits in the react-sdk that are between the two builds (working and failed): https://github.com/vector-im/element-web/actions/runs/3887044602

https://github.com/matrix-org/matrix-react-sdk/commit/0453283bede917a220e9b04cffd415ec61e7bdea
https://github.com/matrix-org/matrix-react-sdk/commit/99e38ca88e084f06c45e16fce5b1994e01a5ae11
https://github.com/matrix-org/matrix-react-sdk/commit/b4f2db22dfaaf69989d47ad198aab959189908b5

let's see what happens. Will re-revert those commits if it ends up not helping

**Comment by turt2live** [comment] 2023-01-10 20:43
okay, that fixed it - now to figure out which of the 3 causes the problem...

**Comment by madduck** [comment] 2023-01-10 20:45
Fixed for me too.

**Comment by turt2live** [comment] 2023-01-10 20:46
Reverted the reverts, bundling these two in one push:
https://github.com/matrix-org/matrix-react-sdk/commit/19ba620de228dcc5307ec9ef1f868db0a64833c6
https://github.com/matrix-org/matrix-react-sdk/commit/edc44922c2809162aac6cec07751c49fab4273de

Theory is these two commits should *not* cause the problem to happen because they're purely in the tests, but let's see :D 

https://github.com/vector-im/element-web/actions/runs/3887109704

**Comment by turt2live** [comment] 2023-01-10 20:54
no change (as expected): build still fine

Reverted the last commit: https://github.com/matrix-org/matrix-react-sdk/commit/b642df98e9047fd901ea66edb4f76d9bcce339d0 (this one should cause the issue, though isn't obvious why)

build: https://github.com/vector-im/element-web/actions/runs/3887167215

**Comment by turt2live** [comment] 2023-01-10 21:06
Naturally, the build is completely fine.

I suppose it's possible it just got confused about which deployment to use and ended up using half of both, or something. Likely caused by landing 3+ changes in rapid succession. 

Considering fixed and closing - if this happens again, we can reopen or open a new issue.

**Closed by turt2live** 2023-01-10 21:06 UTC
Labels: T-Defect, X-Regression, S-Critical, X-Release-Blocker, O-Occasional

**Comment by turt2live** [comment] 2023-01-10 21:12
ftr I think it was https://github.com/vector-im/element-web/actions/runs/3885198906 which got half-deployed, because the job passed but the overall workflow was cancelled. Artifact appears to confirm that it would have been half-deployed from this state.

**Comment by madduck** [comment] 2023-03-30 06:29
The problem seems to be back, @turt2live, as of yesterday
