### ISSUE TITLE
logged out after running out of diskpace

### ISSUE THREAD

**Issue by Wieter** [vector-im/element-web#25052] opened 2023-04-05 21:15 UTC
### Steps to reproduce

ran out of disk space, the app logged out and a popup requesting to submit log data.
for submitting log data, this report had to be opened.

### Outcome

N/A

### Operating system

MacOS

### Will you send logs?

Yes

**Comment by Wieter** [comment] 2023-04-05 21:16
Failed to send logs: No connected database

**Comment by t3chguy** [comment] 2023-04-06 08:28
Duplicate of https://github.com/vector-im/element-web/issues/18423

**Closed by t3chguy** 2023-04-06 08:28 UTC
Labels: T-Defect
