### ISSUE TITLE
"You can't see earlier messages" in old room

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#21028] opened 2022-02-10 15:55 UTC
### Steps to reproduce

Unknown

#### What did you expect?
Room history as normal (eg. on iOS I can see there's a message from 9:54 this morning)

#### What happened instead?
In a room I've been in for many months, I can see the most recent couple of messages but then the "You can't see earlier messages" banner is above and I can't see anything beforehand.

History now seems to have appeared

### Operating system

macOS

### Application version

Nightly 20220210

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by MadLittleMods** [comment] 2022-04-27 16:08
Duplicate of https://github.com/vector-im/element-web/issues/16983

A lot of highly related issues have been closed in favor of this one ^

**Closed by MadLittleMods** 2022-04-27 16:08 UTC
Labels: T-Defect, S-Critical, A-Timeline, Z-Rageshake
