### ISSUE TITLE
Option to configure and disable spellcheck missing

### ISSUE THREAD

**Issue by rupi-lol** [vector-im/element-web#13543] opened 2020-05-06 10:24 UTC
There are several issues with spellchecking open allready. #13317 would solve a lot of problems regarding multi-language users (and I do think that most non-english speakers in IT related fields are also in several english language channels) but it still leaves a lot of jargon, mixed language usage.. issues open.
So a kill-switch for the spellchecker would be appreciated.

**Comment by t3chguy** [comment] 2020-05-06 10:26
This should probably take a form of a language picker with an `<OFF>` mode

**Comment by t3chguy** [comment] 2020-05-06 10:27
Related https://github.com/vector-im/riot-web/issues/7773

**Comment by c33s** [comment] 2020-05-15 12:48
in general preferences for spellcheck would be appreciated see #13684

**Comment by c33s** [comment] 2020-07-22 19:31
is it possible to give this more priority? after upgrading to 1.6.0 it really does not make fun to use riot any more. everything i write is marked as wrong, the program tells me to upload keys which i don't want to upload (#13685). it's very difficult to convince new people to use riot because of this.

**Comment by gsurkov** [comment] 2020-08-15 10:35
Not judging the decisions behind this, but I personally don't need the spell check and it's really distracting. It agroes not only at jargon or intentionally misspelled words, but also on web links. Having a simple checkbox (on-off) would be very great.

**Comment by alajovic** [comment] 2020-08-29 10:39
Let me just add a +1 on this. Virtually all discussions I have in element are in my native language (Slovenian) and it's really distracting to have everything underlined with red squiggles. Many of my colleagues have also been complaining about it. Adding an option do disable the spell checker would be much appreciated.

**Comment by Findus23** [comment] 2020-08-30 08:39
For me it is the other way round. My system is in German, but I mostly write in English causing nearly all words to be underlined which I think makes it harder to notice typos than without any spellchecking at all.

**Comment by zingus** [comment] 2020-09-06 21:33
At the very least let's just turn it off by default until it's configurable?
Is it too much to ask NOT to have a feature nobody wants to develop?

**Comment by t3chguy** [comment] 2020-09-07 08:11
https://github.com/vector-im/element-web/issues/2661 had a lot of upvotes too.

> maybe turn spellchecking off by default until it's configurable?

By default implies it'd be configurable.

**Comment by alajovic** [comment] 2020-09-07 09:43
I think the main point is not that disabling the spellchecker would be as equally good as having it enabled all the time. The point is that it would be just as equally _bad_. There is a large pool of English-only speaking people that apparently like the spellchecker. Which is fair enough. But there is also a good amount of non-English speaking people to which the spellchecker is (currently) a constant nuisance. A decision in favor of any of the two groups is inherently, and equally unfair.

Personally, I'd much prefer making an occasional uncaught spelling slip over being continuously told that _everything I write is wrong_. It's quite a bad user experience to be yelled at all the time.

Also, in my everyday chats, I often use colloquial speech. I sometimes skip or mutate letters, I glue words together or [invent new ones](http://catb.org/jargon/html/overgeneralization.html). In my world, this is a valid mode of speech, and I dislike to be told that it isn't. Just like the sledgehammer, I like the spellchecker as a tool that I can use when I want to. But I wouldn't want it to be permanently attached to my arm.

**Comment by c33s** [comment] 2020-09-07 10:16
@t3chguy but in the current state it is a real bad UX. 

the riot team has choosen electron or the current version of electron, so is it really enough to say it's an upstream problem? it is a problem of the riot team and their users. i don't know electron but isn't there anything you can do to use a different "textbox" or a textarea without a spellcheck? 

as @alajovic wrote above, in the current state riot tells me that **everything** i type is wrong and that my chats are not safe (see #13685). the spellchecker and the annoying "setup encryption" popup made me stop using riot.

**Comment by t3chguy** [comment] 2020-09-07 13:35
It is *not* an upstream problem.
We enabled the spellcheck on purpose to close #2661
We need the design team to draw up how they want the multi-selection (and disablement) of Spellchecking to look.

**Comment by c33s** [comment] 2020-09-07 15:48
sorry for my dump question but if you can enable the spellchecking, isn't it possible to disable it again and if it's possible to enable and disable where is the problem in a setting to let the user enable and disable the whole spellchecking?

**Comment by t3chguy** [comment] 2020-09-07 16:29
The problem is we want to have a selector for languages (which includes the ability to turn it off entirely) rather than a naive on/off which will need replacing in the future. Doing work twice is not worth it.

**Comment by c33s** [comment] 2020-09-07 17:29
you say you don't want to do the work twice but instead of leaving it as is until you implement your preferred solution which will work for all your users, you implemented a half baked solution for only a part of the people using it and wonder why they now want a simple off switch.

> Doing work twice is not worth it.

this statement makes me a little sad, i think it is easy to say that something isn't worth it if you are not hit by it. tell a wheelchair user that the ramp is not worth it, because everyone can use the stairs.

isn't diversity important? according to https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers your implementation of only english is only for 4,9% of the world if you want to allow them to write in their native language. so i kindly ask you to remove the spellchecking for all until the full solution is done, or at least provide an option to disable it in the meantime.

the reason for my repeated and maybe hard comments is, that with this change my personal riot expericene is not fun/nice any more. it's like a person stands next to me and shout "wrong, wrong, everything wrong" for each character i am typing. since this change i hardly used riot any more. please give me my good riot expierence back. it's holding me back to create the german speaking symfony community on riot :(

**Comment by twouters** [comment] 2020-09-07 17:32
In case anyone wants to build their own element-desktop, the following patch adds an undocumented option which can be used to toggle spellchecking as a very dirty workaround.

```
diff --git a/src/electron-main.js b/src/electron-main.js
index b736299..42899b0 100644
--- a/src/electron-main.js
+++ b/src/electron-main.js
@@ -882,7 +882,7 @@ app.on('ready', async () => {
             // main page from the background script.
             contextIsolation: false,
             webgl: false,
-            spellcheck: true,
+            spellcheck: (vectorConfig.hasOwnProperty('spellcheck_enabled')) ? vectorConfig['spellcheck_enabled'] : true,
         },
     });
     mainWindow.loadURL('vector://vector/webapp/');
```

**Comment by t3chguy** [comment] 2020-09-07 17:35
> this statement makes me a little sad, i think it is easy to say that something isn't worth it if you are not hit by it. tell a wheelchair user that the ramp is not worth it, because everyone can use the stairs.

There are too many ongoing projects for wasted cycles from the core team. It is an open source project, you can always implement it yourself or stick it on BountySource. It is planned to be worked on, when other higher priority projects are not in its way.

> isn't diversity important? according to https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers your implementation of only english is only for 4,9% of the world if you want to allow them to write in their native language. so i kindly ask you to remove the spellchecking for all until the full solution is done, or at least provide an option to disable it in the meantime.

Its not fixed to English whatsoever, it tries to match your UI language which *IS* configurable. Falling back to English if there's no close match.

https://github.com/vector-im/element-desktop/blob/94086f247a8c89630ddf3c134e4af50c18d1af3b/src/electron-main.js#L377-L420

**Comment by thany** [comment] 2020-11-28 18:44
> It is an open source project, you can always implement it yourself

Why was a spellcheck built in te first place then? Does seem like a must-have feature when other things aren't really very polished still.

Besides, open source or not, the service behind it is commercial(-ish), and probably does make money.

**Closed** 2021-03-02 14:38 UTC
Labels: design, electron, i18n, suggestion

**Comment by nidico** [comment] 2022-04-24 09:07
I ended up here looking for how I can disable the spell checker. "Removing all dictionaries" is not an intuitive way of disabling a spell checker.

I would *definitely* prefer a "spell checker on/off" switch on top of the multi-language dictionary selector, which would disable the dictionary selector, but keep the spell checker settings in case you want to turn it back on later.

Shall I file a new issue or can we reopen this one (as the original request is precisely about this: a kill switch for the dictionary)?

As long as there is no kill switch there should *at least* be an explanation that removing all languages disables the spell checker. I'll file a separate issue for that.

(Furthermore, the current overly complex implementation, i.e. *not having an explicit on/off switch* is more error prone, see #16590).

**Comment by thany** [comment] 2022-04-25 07:58
I'm not convinced an instant messaging app needs spell checking in the first place. It's not like people are typing a formal letter in a message... Plus you can always edit a mistake after having sent a message.

Having said that, can anyone shed some light on how the spell check language is currently being picked?
Does it look at the system locale, or display language, or geographical location? (not always the same!) Or is it just some default variety of English?

**Comment by SimonBrandner** [comment] 2022-04-25 15:23
> Having said that, can anyone shed some light on how the spell check language is currently being picked?

IIRC, it should pick automatically based on whatever Electron does (meaning it should behave the same way Chromium does)

**Comment by thany** [comment] 2022-04-27 15:12
> IIRC, it should pick automatically based on whatever Electron does (meaning it should behave the same way Chromium does)

Which is how? I don't use Chrome.

**Comment by SimonBrandner** [comment] 2022-04-28 07:13
> > IIRC, it should pick automatically based on whatever Electron does (meaning it should behave the same way Chromium does)
> 
> Which is how? I don't use Chrome.

I am not sure how exactly but I suppose it will be based on the OS locales and similar to what Firefox does

**Comment by ronilaukkarinen** [comment] 2024-03-17 17:18
+1 This is the only annoyance for me with the Element-desktop right now.

**Comment by ronilaukkarinen** [comment] 2024-03-17 18:13
Workaround on Linux:

First, quit Element completely. Then:

```bash
sudo nano ~/.config/Element-Nightly/Preferences
```

Change enable_spellchecking to false, add your local dictionary and add to the end of it use_spelling_service as false, like this:

```json
{"browser":{"enable_spellchecking":false},"electron":{"media":{"device_id_salt":"XXX"}},"spellcheck":{"dictionaries":["fi-FI"],"dictionary":"","use_spelling_service":false}}
```
