### ISSUE TITLE
Urls are made clickable too eagerly

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#18605] opened 2021-08-17 21:43 UTC
### Steps to reproduce

1. Send a message anywhere with the passage `.hack//sign` (it's an anime series, so it's a real-world example)
2. Observe what appears in the chat history.

### What happened?

The part `//sign` is made clickable, as if it's a valid URL. Even though *technically* it might be, it actually isn't because obviously it doesn't lead anywhere.

### What did you expect?

Don't make a URL (if you have to call it that) clickable if it can't possibly lead anywhere.

Also on a sidenote, if you edit the message to make it `.hack\//sign` (in hopes to escape it from being made clickable) the `\` is not rendered, and upon a second edit it turns out it is thrown away. This is a form a data loss, which deserves elevated priority.

### Operating system

Windows

### Application version

Element version: 1.8.1 Olm version: 3.2.3

### How did you install the app?

https://element.io/get-started

**Comment by aaronraimist** [comment] 2021-08-17 22:12
Duplicate of https://github.com/vector-im/element-web/issues/5323

Related: https://github.com/vector-im/element-web/issues/8720 https://github.com/vector-im/element-web/issues/5621

**Closed by aaronraimist** 2021-08-17 22:12 UTC
Labels: T-Defect

**Comment by thany** [comment] 2021-08-23 08:51
I wouldn't call that a duplicate.
