### ISSUE TITLE
Unread messages in DMs aren't shown in the space panel

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/element-web#20672] opened 2022-01-21 17:40 UTC
### Steps to reproduce

1. Have a space
2. Have someone talking to you in private in this space
3. Have some talking in another room in the same space
4. See on the space panel that only the unread messages from the other room are counted

#### What did you expect?

I expect to have the sum of the DMs and rooms unread messages in the space panel.

#### What happened instead?

Only the unread messages from the other room are counted. It's displayed in Home though I disabled to show all the rooms in the Home:

![image](https://user-images.githubusercontent.com/6382548/150575187-9e4193c6-08d0-4828-a23e-70d36894244f.png)

I expect the Home space to only show orphan rooms and DMs here.

### Operating system

Fedora Linux 35

### Application version

Element 1.9.9, Olm 3.2.8

### How did you install the app?

Flatpak

### Homeserver

matrix.org

### Will you send logs?

No

Linked with: https://github.com/vector-im/element-android/issues/5027

**Comment by SimonBrandner** [comment] 2022-01-21 17:47
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/18728

**Closed by SimonBrandner** 2022-01-21 17:47 UTC
Labels: T-Defect
