### ISSUE TITLE
Private space room lists show DMs as 'unnamed room'

### ISSUE THREAD

**Issue by penn5** [vector-im/element-web#17351] opened 2021-05-18 14:12 UTC
### Description

When creating a personal space and adding some DMs, they show up as "Unnamed Room". They show with the correct name in the chat chooser.

### Steps to reproduce

- Create a personal space
- Add DMs

The DMs should show with the correct name.

Logs being sent: no

![image](https://user-images.githubusercontent.com/5600962/118666678-46536480-b7eb-11eb-8798-736317dd5f78.png)

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Fedora
- **Version**: 1.7.28

**Comment by t3chguy** [comment] 2021-05-18 14:15
Duplicate of https://github.com/vector-im/element-web/issues/17336

**Closed by t3chguy** 2021-05-18 14:15 UTC
Labels: T-Defect
