### ISSUE TITLE
PIP not discarded after a Jitsi call

### ISSUE THREAD

**Issue by gaelledel** [vector-im/element-web#21664] opened 2022-04-04 13:36 UTC
### Steps to reproduce

Where are you starting? What can you see?
 - When leaving a Jitsi call in Element, the PIP remains. It is impossible to get rid of it

<img width="1344" alt="Screenshot 2022-04-04 at 12 59 05" src="https://user-images.githubusercontent.com/76945183/161556044-5d82a3d3-7d0a-4de4-972c-bbc5a20a7f46.png">

#### What did you expect?
The PIP to be discarded when I leave the call - The PIP to be discarded when the call admin ends the call
#### What happened instead?
The PIP stays with no ability to remove it

### Operating system

macOS

### Browser information

Chrome Version 99.0.4844.83 (Official Build) (arm64)

### URL for webapp

https://develop.element.io/

### Application version

Element version: b1a60b25b4c8-react-13a51654e782-js-106f7beb48fe Olm version: 3.2.8

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-04 13:38
Duplicate of https://github.com/vector-im/element-web/issues/21648

**Closed by robintown** 2022-04-04 13:38 UTC
Labels: T-Defect
