### ISSUE TITLE
Allow showing invite only rooms in spaces room list

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#19746] opened 2021-11-13 22:54 UTC
#### What would you like to do?

I would like to set some (or all, as default) invite only rooms that are a part of a space to be shown in the space room list.

#### Why would you like to do it?

This would allow space members to see what rooms are available in the space, so they can request invites to them. If they don't know what rooms are available, they cannot request invites to them.

#### How would you like to achieve it?

Ideally this would be a thing that space maintainers could configure for each invite only room, whether it should be shown in addition to being a part of the space. However, personally I would be happy if all invite only rooms would also show in the space rooms list without any configuration.

**Comment by t3chguy** [comment] 2021-11-15 09:42
This will be possible with Knocking, the issue is that if a room is invite only (and not world readable via History=Anyone) then you have no way of knowing the name/avatar/topic of the room prior to your invite. With knocking you do.

> I would be happy if all invite only rooms would also show in the space rooms list without any configuration.

This would require a metadata leak which would not be possible.

Closing in favour of https://github.com/vector-im/element-web/issues/18655 & https://github.com/vector-im/element-web/issues/5788

**Closed by t3chguy** 2021-11-15 09:42 UTC
Labels: A-Spaces, T-Enhancement, O-Occasional
