### ISSUE TITLE
Rendering of thousands of invites makes Element slow down to a crawl

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#24886] opened 2023-03-21 22:12 UTC
### Steps to reproduce

1. Make a room
2. Invite 2.2K accounts to it

(use case not in the purpose of spam but rather setting up a new room for a community and inviting the community members to it as agreed in the community governing group)

#### What did you expect?

The new room feels snappy.

#### What happened instead?

Even after all the invites have been sent, switching to the room takes up to a minute or two for all the thousands of avatar icons to render. Even after all the invite events are rendered on screen, Element feels extremely sluggish. Scrolling the room (for example messages before the invites) is extremely slow and painful.

Navigating away from the room makes Element not sluggish again. Navigating back repeats the multi-minute cycle of loading invite events with their avatars and makes Element sluggish again.

Suggestion: don't render all the thousands of avatars in the case of invites being clearly grouped ("user and 2223 others were invited" grouping), assuming the issue is the rendering of all the avatar icons.

![Selection_288](https://user-images.githubusercontent.com/1174866/226754929-923cd07e-a3c6-4252-a96b-80f5055aeef2.png)

### Operating system

Ubuntu

### Application version

Element Nightly version: 2023031801 Olm version: 3.2.12

### How did you install the app?

Official repositories

### Homeserver

Synapse v1.79.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-03-22 08:25
Duplicate of https://github.com/vector-im/element-web/issues/11604

**Closed by t3chguy** 2023-03-22 08:25 UTC
Labels: T-Defect
