### ISSUE TITLE
Video call active but not shown in Desktop App

### ISSUE THREAD

**Issue by Chuhtra** [vector-im/element-web#15090] opened 2020-09-03 13:31 UTC
### Description

Me and a friend decided to make a call through Element.io (we were both using Desktop apps). Since we hadn't clarified who will call first, we both called. The result was only one call succeeded. The issue is that while on my end the call was activated (could see the microphone light being active) inside the Element.io app UI nothing indicated that a call was in progress.

### Steps to reproduce

It was a bit fuzzy how exactly it happened and what was the exact turn of events so I will just write the 2 experiences.

For my friend:
- Placed a call
- Got in a call
- Wrote that she can hear and see me
- After some messages and the realization of what happened she ended the call.

For me:
- Placed a call
- Received an incoming call
- Rejected incoming call
- Saw application in no-call state
- Received Incoming message that she can hear and see me, while I thought I wasn't in a call.
- I saw that microphone light and OS microphone indication where both turned on.
- I waited for the "ghost" call to be terminated.

### Describe how what happens differs from what you expected.

Well, it's obvious that the app should indicate whether or not it's in a call else it should deactivate every call just to be safe.

Logs being sent: no

### Screenshot of chat at the time
![image](https://user-images.githubusercontent.com/40795688/92120293-87444e00-ee01-11ea-9694-1bd22a3faab3.png)

### Version information

- **Platform**: Both of us in Desktop app
- **OS**: 
  - Friend: Windows 10
  - Me: Manjaro Linux
- **Version**: 
  - Friend: Element version: 1.7.5, olm version: 3.1.3
  - Me: Element version: 1.7.4, olm version: 3.1.3

**Comment by t3chguy** [comment] 2020-09-03 14:38
Duplicate of https://github.com/vector-im/element-web/issues/12569

**Closed by t3chguy** 2020-09-03 14:38 UTC
Labels: bug
