### ISSUE TITLE
Placeholder: e2ee is slow in massive rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16043] opened 2020-12-28 21:09 UTC

**Comment by turt2live** [comment] 2020-12-28 21:26
Sending test messages in the megolm test room.

Initial observations:

Claiming the keys takes forever:
![image](https://user-images.githubusercontent.com/1190097/103243226-6d7dc800-4916-11eb-873b-67ea6cbc5010.png)

There's a bunch of half-second to_device message calls. Might be able to stack these?
![image](https://user-images.githubusercontent.com/1190097/103243248-838b8880-4916-11eb-807c-ab7313cbf48a.png)

There are also slightly above half-second calls to broadcast keys being withheld, which feels excessive given there shouldn't be any withheld keys?
![image](https://user-images.githubusercontent.com/1190097/103243299-a61da180-4916-11eb-87b4-e5bddef69ba8.png)

The actual message send took 600ms:
![image](https://user-images.githubusercontent.com/1190097/103243319-b766ae00-4916-11eb-86d4-4f556767d185.png)

`ensureOlmSessionsForDevices` is a bit slow (red bar on `Task` is overtime):
![image](https://user-images.githubusercontent.com/1190097/103243371-e8df7980-4916-11eb-9285-0638f16e4024.png)

There are seemingly thousands of calls into WASM (presumably Olm), all which take 1-2ms each:
![image](https://user-images.githubusercontent.com/1190097/103243427-1298a080-4917-11eb-9315-56bcf9fd22cf.png)
(this is about 1.76ms)

The WASM calls (and the long `ensureOlmSessionsForDevices`):
![image](https://user-images.githubusercontent.com/1190097/103243597-a2d6e580-4917-11eb-9a5a-5270eb792590.png)

It takes 2ms for some devices to be encrypted:
![image](https://user-images.githubusercontent.com/1190097/103243686-dc0f5580-4917-11eb-93ad-75cbc8dc90cb.png)

... while others (most) take about 0.2ms:
![image](https://user-images.githubusercontent.com/1190097/103243709-e6315400-4917-11eb-96ea-d266c21c17f0.png)

There is a lot of unpickling going on:
![image](https://user-images.githubusercontent.com/1190097/103243729-f6493380-4917-11eb-9708-dc2de3fd3d3e.png)

Rough timeline for the web requests:
![image](https://user-images.githubusercontent.com/1190097/103243854-6a83d700-4918-11eb-9dfe-97080d10c12f.png)

The CPU spikes a bit with each encryption, but nothing terribly dangerous (same timeframe as above):
![image](https://user-images.githubusercontent.com/1190097/103243895-8be4c300-4918-11eb-8dc8-68f58622ab4e.png)

The hill of ~50% CPU is what appears to be ensuring the devices exist and initial encryption. We might not be stacking the encryption up high enough?

**Comment by turt2live** [comment] 2020-12-28 23:20
We can probably make a bunch of this more concurrent and save session keys somewhere safe, leading to faster messages after reloading the app. We can also probably increase the number of devices per to_device message when sending out keys, and defer the withheld notifications to after the message is actually sent.

**Comment by uhoreg** [comment] 2020-12-29 15:21
> Claiming the keys takes forever:

Yup, that's the long timeout from fetching keys over federation, and basically means that some other homeserver is timing out with its reply.  It's supposed to also do a keys claim with a shorter (2s) timeout first, and the long-timeout one isn't supposed to hold up the message sending.  But maybe it only does the longer timeout one when it's automatically creating sessions when you start typing a message?  It's been a while since I've looked at the code. (https://github.com/vector-im/element-web/issues/11836)

> There are also slightly above half-second calls to broadcast keys being withheld, which feels excessive given there shouldn't be any withheld keys?

"Withheld" could also be due to failures in creating olm sessions, which could be due to some devices having run out of one-time keys (which is likely if you sent a message large public room), or due to some servers failing to send keys (which seems likely given that the keys claim call took >10s, which means that some servers have timed out).

Another thing that I had been thinking about was batching up some of the IndexedDB operations so that, for example, it fetches the olm sessions for multiple devices at a time, rather than fetching them individually.  My suspicion is that it won't produce enough speedup to be worth the effort (since it will probably involve lots of refactoring and increasing code complexity), but maybe your magic graphs can give some more insight.

**Comment by novocaine** [comment] 2021-08-25 16:20
Downgrading, as this does not *prevent work*, it merely makes it slower..

**Comment by novocaine** [comment] 2021-08-25 16:22
Not clear to me from this issue:

* How much of the speed problems could be resolved by changes to EW?
* What is a 'massive room'? 
* What is the ultimate impact on message delivery latency?

**Comment by richvdh** [comment] 2023-02-14 14:36
Duplicate of #15476.

**Closed by richvdh** 2023-02-14 14:36 UTC
Labels: T-Defect, A-Performance, S-Major, A-E2EE, Z-Chronic, O-Uncommon
