### ISSUE TITLE
Latex lab option mangles message when using $$$ $$$

### ISSUE THREAD

**Issue by dali99** [vector-im/element-web#15910] opened 2020-12-07 14:56 UTC
### Description

When using the latex rendering option writing `$$$ a + b $$$
will send
```
"formatted_body": "<p>&lt;span data-mx-maths=&quot;&lt;div data-mx-maths=&quot;a+b&quot;&gt;</p>\n<p>&lt;/div&gt;</p>\n<p>&quot;&gt;</p>\n"
```

which looks bad:
![bilde](https://user-images.githubusercontent.com/990767/101365682-624df400-38a4-11eb-895d-470d0a8ca7a8.png)

### Steps to reproduce

- Enable Latex rendering
- Send anything inside $$$

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 83
- **OS**: Windows 10
- **URL**: 1.7.15

**Comment by dali99** [comment] 2020-12-07 14:57
@uhoreg, @akissinger

**Comment by jryans** [comment] 2020-12-08 17:07
I believe this effectively a duplicate of https://github.com/vector-im/element-web/issues/15910.

**Closed by jryans** 2020-12-08 17:07 UTC
Labels: bug
