### ISSUE TITLE
DMing a remote user from MemberInfo can take seconds to respond, and doesn't deduplicate clicks

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15448] opened 2020-10-12 20:56 UTC
So if you click the DM button in MemberInfo once, absolutely nothing happens. You click it again. Three seconds later, the user gets two DMs opened :(

**Comment by turt2live** [comment] 2020-10-12 21:07
Duplicate of https://github.com/vector-im/element-web/issues/12848

**Closed by turt2live** 2020-10-12 21:07 UTC
