### ISSUE TITLE
high cpu after recording and play audio message

### ISSUE THREAD

**Issue by bgbruno** [vector-im/element-web#23050] opened 2022-08-10 17:57 UTC
### Steps to reproduce

1. Where are you starting? What can you see? >> chat
2. What do you click? >> record

#### What did you expect?
normal slow process

#### What happened instead?
crash after 2 minutes - sound craped after while more and more -- I have to reboot whole #macos

### Operating system

macos

### Browser information

chrome 104

### URL for webapp

app

### Application version

Element version: 1.11.2 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by masterflitzer** [comment] 2022-08-14 23:09
i think this is a duplicate of #19756

**Comment by bgbruno** [comment] 2022-08-14 23:23
@masterflitzer possibly - I cannot figure out from that issue description that issue like I have , so I cannot it search either

**Comment by masterflitzer** [comment] 2022-08-14 23:40
at least for me the high cpu and unresponsive UI happens when an audio message is in the currently visible chat window, doesn't matter if i recorded it or it was just sent to me or if it was a week ago, as soon as i scroll into an area with 2-3 or more audio messages it happens (like 25-45% cpu usage on my ryzen 5 2600)

**Comment by t3chguy** [comment] 2022-08-15 14:14
Duplicate of #19756

**Closed by t3chguy** 2022-08-15 14:14 UTC
Labels: T-Defect, A-Performance, S-Major, A-Voice Messages, O-Occasional
