### ISSUE TITLE
Need: Possibility to CHANGE the notification SOUND

### ISSUE THREAD

**Issue by jnpf** [vector-im/element-web#15442] opened 2020-10-12 13:41 UTC
Hi Guys, 

thanks for the new UI in https://app.element.io - it's great! But please, we need the possibility to change the DING sound for notifications. I can't hear it anymore.

Back in the days ICQ shows how important a good notification sound is and Apple showed exactly the same with the sounds in their mail app or on the iPhone

Your UI is great, but the sounds should be changable to get in peace with it.

Thanks a lot!

**Comment by t3chguy** [comment] 2020-10-12 13:44
Duplicate of https://github.com/vector-im/element-web/issues/15023

**Closed by t3chguy** 2020-10-12 13:44 UTC
