### ISSUE TITLE
Spaces IA: Allow toggle to hide Subspaces from Parent space

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#19796] opened 2021-11-18 09:59 UTC
### Your use case

A request from a customer that we add a setting (either on the Space overflow menu, or in the new Sidebar tab in Settings) that removes Rooms in a subspace from showing in their parent space. 

Today I see Rooms in a Space, and all the subspaces. It makes the Parent Space cluttered and reduces the impact of careful organisation of subspaces... To be able to remove Subspaces from the Parent Space (similar to how Home and All Rooms works today) would simplify the view and the process.

**Comment by SimonBrandner** [comment] 2021-11-18 10:01
Duplicate of https://github.com/vector-im/element-web/issues/18905

**Closed** 2021-11-18 10:17 UTC
Labels: A-Spaces, X-Needs-Design, T-Enhancement, Z-IA
