### ISSUE TITLE
Custom global hotkeys

### ISSUE THREAD

**Issue by BloodRaven0** [vector-im/element-web#12645] opened 2020-03-07 17:15 UTC
**Is your suggestion related to a problem? Please describe.**
The fact that you can't change hotkeys (and the existing ones are not documented anywhere I could find) is a pretty big issue in my opinion.

**Describe the solution you'd like**
Just add a menu where you can choose actions for which you can bind certain hotkeys and a tick to make said hotkeys (or hotkey combinations) global (work when window is not in focus.

**Comment by kintso** [comment] 2021-04-27 09:51
On top of what @BloodRaven0 suggested, I would add that on Windows on a AZERTY keyboard the hotkey "CTRL+A" asks to close the application whereas we could expect it to select all the content of the current container. Therefore being able to customize the hotkeys will make the experience better imo

**Comment by t3chguy** [comment] 2021-04-27 09:52
@kintso that is unrelated to this issue. Your issue should be resolved in v1.7.26 which should be deployed today.

**Comment by kintso** [comment] 2021-04-27 11:59
Thanks a lot for the new version. It does fix my issue

**Comment by SimonBrandner** [comment] 2021-12-27 08:37
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/15076

**Closed by SimonBrandner** 2021-12-27 08:37 UTC
Labels: T-Enhancement, A-Shortcuts
