### ISSUE TITLE
History is broken

### ISSUE THREAD

**Issue by 1000i100** [vector-im/element-web#24437] opened 2023-02-04 13:19 UTC
### Steps to reproduce

1. Create a private space with subspace and room accessible to every invited to main space.
2. Keep defaut history setting (since option selection).
3. Say something in the room.
4. Invite somebody to your space
5. Let it join the room
6. Ask him if he see what you said before. In my experiment : no.

#### What did you expect?
Seeing previous message

#### What happened instead?
Only see what've been added since i join.

### Operating system

Linux Mint 21

### Browser information

Firefox 108.0.1

### URL for webapp

https://app.element.io/

### Application version

Version de Element : 1.11.21 Version de Olm : 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-02-06 09:10
This is because they self-joined, if you had invited them explicitly into the room then you'd have sent them keys.

Duplicate of https://github.com/vector-im/element-meta/issues/646

**Closed by t3chguy** 2023-02-06 09:10 UTC
Labels: T-Defect
