### ISSUE TITLE
Tried to join a room in space, got error report dialog

### ISSUE THREAD

**Issue by vranki** [vector-im/element-web#23171] opened 2022-08-31 12:09 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

Space home. I just joined another room

3. What do you click?

Join button on a room

#### What did you expect?

Joining a room

#### What happened instead?

Got error report dialog

### Operating system

Windows

### Browser information

Firefox 104.0

### URL for webapp

https://app.element.io/

### Homeserver

hacklab.fi

### Will you send logs?

Yes

**Comment by vranki** [comment] 2022-08-31 12:13
Actually, I don't want to send logs. I just realized they contain potentially private data "Debug logs contain application usage data including your username, the IDs or aliases of the rooms you have visited, which UI elements you last interacted with, and the usernames of other users."

I can send the logs via e-mail or preferably DM in Matrix if needed.

**Comment by vranki** [comment] 2022-09-01 06:57
This should be clarified in the in app message. Just add something like "Logs are not attached to the public github issue and are only visible for Element employees". I'll find a way to send the logs.

**Comment by t3chguy** [comment] 2022-09-01 07:17
@vranki the issue is it depends per-deployment, someone could have their rageshake server configured to post the logs publicly, on our deployments (e.g. app.element.io) we do not.

**Comment by t3chguy** [comment] 2022-09-01 07:24
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-09-01 07:24 UTC
Labels: T-Defect, X-Needs-Info
