### ISSUE TITLE
Joining a room from a space causes an error and requires cache to be cleared

### ISSUE THREAD

**Issue by runbgp** [vector-im/element-web#23360] opened 2022-09-27 14:55 UTC
### Steps to reproduce

1. Navigate to the home page of a space.
2. Attempt to join a room.
3. Wait, and get presented with an error. "Something went wrong!"

#### What did you expect?
I expected to be able to join the room from the space without issue.
#### What happened instead?
An error occured and I was presented with "Something went wrong!". This happens whenever trying to join a room from a space. If I clear the cache, everything reflects normally and the room was actually joined successfully. I find myself having to clear cache quite frequently just to do things like joining rooms.

![image](https://user-images.githubusercontent.com/99215336/192561265-486f4615-93f1-45e4-8d83-82691bb58a00.png)

### Operating system

Windows 11

### Application version

Element version: 1.11.5 Olm version: 3.2.12

### How did you install the app?

From https://element.io/get-started

### Homeserver

Dendrite 0.9.9

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-09-27 15:48
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-09-27 15:48 UTC
Labels: T-Defect
