### ISSUE TITLE
Toast backgrounds use the wrong colour

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18511] opened 2021-08-12 11:25 UTC
### Steps to reproduce

<img width="506" alt="Screenshot 2021-08-12 at 12 20 21" src="https://user-images.githubusercontent.com/4626865/129188685-ba913174-d0ab-47f2-844b-3f31d1c10416.png">

Toast backgrounds ugly/low contrast.

### What happened?

See above.

### What did you expect?

<img width="435" alt="Screenshot 2021-08-12 at 12 24 12" src="https://user-images.githubusercontent.com/4626865/129189040-c0aa8260-56bb-4fba-a9f9-af6c7e4bece3.png">

Toasts to match production.

**Comment by SimonBrandner** [comment] 2021-08-12 11:26
Duplicate of https://github.com/vector-im/element-web/issues/18396

**Closed by SimonBrandner** 2021-08-12 11:26 UTC
Labels: T-Defect, X-Release-Blocker
