### ISSUE TITLE
Include optional source-path when forwarding messages

### ISSUE THREAD

**Issue by shoqvalue** [vector-im/element-web#22312] opened 2022-05-22 16:05 UTC
#### What would you like to do?
When I forward a message to another room, I would like the option to include the source room path when it appears in the destination room (as shown below), 

![2022-05-22_11h45_55](https://user-images.githubusercontent.com/10272750/169704587-fc84ec85-534a-435d-84f7-eb780b2cbe21.png)

#### Why would you like to do it?
 As it stands, users of those other destination rooms have no idea that the message was even forwarded at all  (which can ethical implications in many contexts), nor can the forwarded item serve as an invitation to come into the source room to see the original context. 
#### How would you like to achieve it?

A simple checkbox option added to the existing Forwarding UI.  This lets the user opt out of the feature. (I rarely would)
![2022-05-22_11h56_49](https://user-images.githubusercontent.com/10272750/169704605-67d9d06e-c06e-4e91-8856-d77b6df9a27a.png)

Once SEND, and if checked, the URL of the source is echoed in the message (as shown in first image above).

**Comment by t3chguy** [comment] 2022-05-22 20:40
Duplicate of https://github.com/vector-im/element-web/issues/4747

**Closed by t3chguy** 2022-05-22 20:40 UTC
Labels: T-Enhancement

**Comment by t3chguy** [comment] 2022-05-23 13:06
![image](https://user-images.githubusercontent.com/2403652/169825910-9a036f7c-dc6b-42ac-8083-b68a8c85f6c8.png)

New github feature getting in the way. Its a duplicate of a still open issue.

**Comment by shoqvalue** [comment] 2022-05-23 13:15
AH, thanks for explaining.  Reading this related thread on the issue, I can now see why it's a complex problem. 
https://github.com/matrix-org/matrix-spec-proposals/pull/2730

For me, I think maybe forwarding should be removed altogether, and the sharing function be embellished as I already suggested here.  
https://github.com/vector-im/element-web/issues/22268

At least that way, the user can be nudged to indicate where a reference was coming from.  Forwarding makes it too easy to pass things along with no attribution possible at all.

**Comment by t3chguy** [comment] 2022-05-23 13:19
@shoqvalue comments on this issue will be missed by people, I suggest commenting on the open issue instead.
