### ISSUE TITLE
is it possible to combine rooms & dms? ( consolidate all msg into one "group" eg. get rid of room / people separation )

### ISSUE THREAD

**Issue by ArneNostitz** [vector-im/element-web#16727] opened 2021-03-19 13:47 UTC
Hi everyone,

i really love the element/matrix & bridging of all my messengers into one hub - but i really dont need the separation of rooms and people ... is there a way of elimination this separation and combine them into one group? i love favorite and low prio - but i´d really like some way of getting rid of scrolling around just to read a new msg in rooms/dm

after googling the hell out of this - probably i just did not find the right formula i finally see this as my last resort. thanks a lot

cheers, and all the best, arne

**Comment by t3chguy** [comment] 2021-03-19 13:49
Duplicate of https://github.com/vector-im/element-web/issues/16306

**Closed by t3chguy** 2021-03-19 13:49 UTC
