### ISSUE TITLE
'was this you?' popup should disappear after having verified new login

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#23312] opened 2022-09-20 08:19 UTC
The dialog doesn't closy by itself when it arguably should, but also the later button does not work on my element desktop

Element version: 1.11.5
Olm version: 3.2.12

**Comment by turt2live** [comment] 2022-09-21 20:51
Duplicate of https://github.com/vector-im/element-web/issues/17667

**Closed by turt2live** 2022-09-21 20:51 UTC
