### ISSUE TITLE
Filter messages by regex

### ISSUE THREAD

**Issue by irigone** [vector-im/element-web#18044] opened 2021-07-17 19:04 UTC
#### Is your suggestion related to a problem? Please describe.

Some words or phrases either annoy me or I'm simply not interested in them. Sometimes, in a room there's a frequently asked question that I'm tired of, or just dumb, or some words that offend me, or some topic I can discuss for hours which can distract me, etc.

I'd like to hide these messages and not get notifications when I get such messages.

#### Describe the solution you'd like.
A setting where I can input a regex, and every message that matches this regex gets hidden and isn't notified about. Make it possible to have a list of such regexes, and each regex should be named by the user. Ideally, make it possible to customize which rooms/communities a regex works with, with a tickbox or something. Make it possible to choose whether regex is enabled or disabled by default.

#### Describe alternatives you've considered.
> Use something that isn't regex, like a word list or a Parsing Expression grammar

A word list isn't as powerful, and parsing expression grammar, while more powerful than regex, is too obscure for even tech savvy people.

**Comment by BieHDC** [comment] 2021-10-31 07:50
I would like to bring attention to this issue again, with 2 more use cases:
1. Blocking over Bridges
Mostly irc bridges dont create fake users and just repeat the text. It would allow you to just block by matching "^<username> " (sorry dont know proper regex syntax) and call it a day.
2. Reducing clutter
Also on irc, they sometimes have a gitbot that posts a message when a new commit was made. This would also allow you to blend out those messages, reducing clutter for people who dont like to see them.

**Comment by bkil** [comment] 2021-11-04 11:14
* You should ideally ask moderators to disconnect bots from a room that are not useful
* Otherwise you would probably need proper threading to be able to ignore frequently asked questions you do not care about

**Comment by BieHDC** [comment] 2021-11-04 12:11
>     * You should ideally ask moderators to disconnect bots from a room that are not useful
This is about the case where some people want it and others do not.
>     * Otherwise you would probably need proper threading to be able to ignore frequently asked questions you do not care about
I just imagined it to work like messages from blocked users.

**Comment by bkil** [comment] 2021-11-04 12:20
When some people want it and others do not, it would be best to create a room for the given bot, and those people who are interested should join that room. Otherwise you might consider ignoring the bot if it isn't posting too many different kind of things.

Exactly: messages from ignored users are usually messing up conversations in a room when they post a lot and people interact with them. This would again not be a problem with threaded views.

**Comment by BieHDC** [comment] 2021-11-04 17:16
> Otherwise you might consider ignoring the bot if it isn't posting too many different kind of things.
Thats the whole point of the idea, to have a better option than that.
> Exactly: messages from ignored users are usually messing up conversations in a room when they post a lot and people interact with them. This would again not be a problem with threaded views.
I disagree. When i block someone i do not even want to know that person wrote something, i specifically like Element for doing that. If one is concerned about broken up conversations, then different block options should exist.

**Comment by t3chguy** [comment] 2022-05-17 21:50
Duplicate of https://github.com/vector-im/element-web/issues/7120

**Closed by t3chguy** 2022-05-17 21:50 UTC
Labels: A-Timeline, Z-Power-Users, T-Enhancement, A-Timeline-Search, O-Uncommon
