### ISSUE TITLE
Room visibility in a Space (and setting a Space logo) doesn't work

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#23565] opened 2022-10-20 16:32 UTC
### Steps to reproduce

One user set up a space. 
They then made me Admin of that space. 

There are 2 users in the space, both with Admin level permissions. 

(I am not able to set the logo for the space, it allows me to see the panel, upload the image and select "save" but when I close the modal it hasn't changed). 

From Spaces home I can only see one room even though the other user can see 4 rooms - all of which are set as visibility at Space level (see the screenshot - this is not the space in question but is exactly the same setting for the rooms in question)
<img width="583" alt="Screenshot 2022-10-19 at 16 57 13" src="https://user-images.githubusercontent.com/89144281/197006077-c9efa0b0-da46-4c10-b262-ba77996045f0.png">

#### What did you expect?
To be able to see the rooms in the space that have this ☝️ setting even if i'm not a member of those rooms. 

#### What happened instead?
They don't show up.

(I was able to set the logo on iOS but am not able to see the rooms on my iOS device either)

### Operating system

MacOS

### Application version

Element Nightly version: 2022102001 Olm version: 3.2.12

### How did you install the app?

element.io

### Homeserver

ems.one.host & matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-10-21 13:38
> (I am not able to set the logo for the space, it allows me to see the panel, upload the image and select "save" but when I close the modal it hasn't changed).

Could you try again and please send logs?
What file type are you trying?

> They then made me Admin of that space.

Relative to the screenshot you shared, which space is this?

---

This is likely an issue of indirect relations or upgraded rooms in a space listing

**Comment by turt2live** [comment] 2023-01-10 00:38
Closing as cannot reproduce/missing information. If this is untrue, or this is still happening, please open a new issue with fresh reproduction steps for the QA team to review.

**Closed by turt2live** 2023-01-10 00:38 UTC
Labels: T-Defect, X-Needs-Info
