### ISSUE TITLE
`polls/polls.spec.ts` → „displays polls correctly in thread panel“ failing

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23451] opened 2022-10-10 08:05 UTC
### Steps to reproduce

Sample run https://dashboard.cypress.io/projects/ppvnzg/runs/4745/test-results/a427ea69-0e52-4d77-9c8c-0393929e99d7

Logs:

```
M_INVALID_PARAM

The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > event_id $TylyWHJ9CdnaeQGibCRZKwG9ClkEoL63ZG4XTjS5iQU is not related to thread $0dX0Jz71z_UbtRRgrzObk0tRl6djOFMNgpNUfU1yH40

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the uncaught:exception event.

https://on.cypress.io/uncaught-exception-from-application

at parseErrorResponse (http://localhost:8080/bundles/cc8b528ed0970d448730/init.js:59888:13) at http://localhost:8080/bundles/cc8b528ed0970d448730/init.js:59838:17 at Object.callback (http://localhost:8080/bundles/cc8b528ed0970d448730/init.js:59762:9) at on_end (http://localhost:8080/bundles/cc8b528ed0970d448730/vendors~element-web-app.js:294:13) at XMLHttpRequest.on_state_change (http://localhost:8080/bundles/cc8b528ed0970d448730/vendors~element-web-app.js:244:7) at XMLHttpRequest.<anonymous> (http://localhost:8080/bundles/cc8b528ed0970d448730/vendors~init.js:203360:41) at XMLHttpRequest.eval (eval at makeContentWindowListener (http://localhost:8080/__cypress/runner/cypress_runner.js:171203:10), <anonymous>:4:29)
```

Screenshot

![image](https://user-images.githubusercontent.com/6216686/194822120-4754f1a8-ff25-4201-9c26-fabbd2f00d56.png)

**Comment by gsouquet** [comment] 2022-10-10 11:52
Delight will take on this 🖐️

**Comment by t3chguy** [comment] 2022-10-10 12:04
Related https://github.com/matrix-org/synapse/blame/1bf2832714abdfc5e10395e8e76aecc591ad265f/synapse/rest/client/versions.py#L108

**Comment by gsouquet** [comment] 2022-10-10 15:15
Synapse returns a `400` with an errcode `M_INVALID_PARAM` because the timeline code is trying to send a read receipt with a thread id param for a poll answer to the thread root. 

If you traverse the relations of that poll answer it will lead you to the thread root that does not hold a `m.thread` relation, therefore the read receipt endpoint will fail.

We have two ways of solving this issue, either adding another codepath client side to prevent sending RR with thread id for relations to the thread root in a thread timeline (poll answers, annotation to the thread root, ...) or we make the API endpoint more flexible and accept that as an incoming request.

**Comment by gsouquet** [comment] 2022-10-12 14:43
This is pending changes on synapse that @clokep will do to accept that scenario.
If that is too cumbersome to implement on the server, clients will do some of the heavy lifting

**Comment by clokep** [comment] 2022-10-13 17:06
matrix-org/synapse#14168 should fix the synapse behavior here.

**Comment by clokep** [comment] 2022-10-14 19:06
This should be fixed on the latest synapse.

**Comment by t3chguy** [comment] 2022-10-17 14:01
Confirmed fixed by https://github.com/matrix-org/matrix-react-sdk/commit/13e9e14eaaa87bbc5b277327728cbefbd0c4d5e8 passing

**Closed by t3chguy** 2022-10-17 14:01 UTC
Labels: T-Defect, S-Major, A-Developer-Experience, O-Uncommon, A-Polls, Z-Flaky-Test
