### ISSUE TITLE
Explore rooms window too narrow for translated buttons

### ISSUE THREAD

**Issue by slsimic** [vector-im/element-web#16244] opened 2021-01-22 17:57 UTC
### Description

The Explore rooms window is too narrow when translated text is on the buttons.
On English, everything looks fine when Preview and Join are side by side but when translated, button labels tend to go off limits. I believe it's troubling many localized instances of Element because on many languages it's hard to put both strings in just 7 + 4 characters.
If window can be wider or fonts smaller or "columns" reserved for Preview and Join wider, that could solve the issue.

Tried to upload screenshots but Github won't let me. Hence the links
https://ibb.co/kQJbf2Z
https://ibb.co/vwbmDdF

### Steps to reproduce

- Click on + to Add room
- Click on Explore public rooms

- **Platform**: web (in-browser) or desktop?
* **Both**

For the web app:

- **Browser**:  Firefox
- **OS**: Debian Linux

For the desktop app:

- **OS**: Debian Linux
- **Version**: 1.7.17

**Comment by t3chguy** [comment] 2021-01-22 18:24
Sounds like a duplicate of https://github.com/vector-im/element-web/issues/15347 but the links you sent immediately crash my browser tab.

**Closed by t3chguy** 2021-01-22 18:24 UTC
Labels: bug, ui/ux
