### ISSUE TITLE
Changing of theme from Dark mode to Light mode does not respond

### ISSUE THREAD

**Issue by EECvision** [vector-im/element-web#21611] opened 2022-03-30 23:48 UTC
### Steps to reproduce

https://user-images.githubusercontent.com/63562663/160947985-fabcfc38-b74b-4c4d-a879-24cc92a03210.mp4

#### What did you expect?
Change from Dark mode to Light mode
#### What happened instead?
Dark mode persisted.

### Operating system

Windows

### Browser information

Version 99.0.4844.84 (Official Build) (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.10.8 Olm version: 3.2.8

### Will you send logs?

No

**Comment by robintown** [comment] 2022-03-31 02:40
Duplicate of https://github.com/vector-im/element-web/issues/21610 - generally, only one issue is necessary for problems that occur on both Web and Desktop.

**Closed by robintown** 2022-03-31 02:40 UTC
Labels: T-Defect

**Comment by EECvision** [comment] 2022-03-31 06:13
Okay, thank you for letting me know.
