### ISSUE TITLE
attempting to paste a largeish image into an e2e room locks up the UI for many seconds

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#6857] opened 2018-06-11 19:07 UTC

**Comment by turt2live** [comment] 2018-06-11 19:09
Related: https://github.com/vector-im/riot-web/issues/4264

**Comment by kittykat** [comment] 2021-12-01 12:55
I'm going to close this issue for now as we cannot reproduce it. Please comment with @kittykat if you are still experiencing it and I will reopen the issue for you.

**Closed by kittykat** 2021-12-01 12:55 UTC
Labels: T-Defect, A-Performance, P2, S-Minor, A-E2EE, A-Media, X-Needs-Community-Testing
