### ISSUE TITLE
Balloons 🎈 

### ISSUE THREAD

**Issue by Yajo** [vector-im/element-web#21721] opened 2022-04-08 11:43 UTC
#### What would you like to do?

I want to send balloons 🎈 and it would be nice to see them flying around, just like confetti 🎉 

#### Why would you like to do it?

Because sending confetti 🎉  is nice, but not enough!

#### How would you like to achieve it?

Just entering one 🎈 emoji in one message.

### Have you considered any alternatives?

When #415 gets fixed, I guess could search for a 🎈 gif.

### Additional context

If you don't want, don't worry! But I had to ask. 😄

**Comment by t3chguy** [comment] 2022-04-08 12:04
Duplicate of https://github.com/vector-im/element-web/issues/16368

**Closed by t3chguy** 2022-04-08 12:04 UTC
Labels: T-Enhancement
