### ISSUE TITLE
"Send message" box not intuitive

### ISSUE THREAD

**Issue by code3z** [vector-im/element-web#20759] opened 2022-01-26 00:55 UTC
### Your use case

Inputs should probably be highlighted. I think there have been studies on this.
![image](https://user-images.githubusercontent.com/77302900/151081650-725cc170-c6b0-4a6e-bab0-1801771418b9.png)

**Comment by robintown** [comment] 2022-01-26 02:42
Duplicate of https://github.com/vector-im/element-web/issues/17362

**Closed by robintown** 2022-01-26 02:42 UTC
Labels: T-Enhancement
