### ISSUE TITLE
Room member filter reset after closing member info

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6197] opened 2018-02-17 01:25 UTC
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15188299361581158eAkPS:matrix.org

**Comment by lampholder** [comment] 2018-02-21 10:07
jzk> Hi,
When I search for a user in the members list, and then click on a result, and then feel unsatisfied with my result and click X, I am not dropped back into the results from where I came to try another result. Instead I have to tax the client/server with another search through the list. Would this be considered a legit usability bug? Is there a bug filed?

**Comment by lampholder** [comment] 2018-02-21 10:09
Keeping the filter in place after clicking the 'X' would be more in line with how the roomlist filter works on the other side of the screen.

On the roomlist filter today, though, it can be easy to forget you've got the list filtered (and waste a beat or two looking for a room that's been filtered away) - ideally we would somehow avoid introducing this problem in addressing #6197

**Comment by t3chguy** [comment] 2020-09-09 15:14
Duplicate of https://github.com/vector-im/element-web/issues/693

**Closed by t3chguy** 2020-09-09 15:14 UTC
Labels: bug, minor, p2, type:userinfo, ui/ux
