### ISSUE TITLE
Long display name don't render well in thread previews

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#21591] opened 2022-03-29 16:26 UTC
### Steps to reproduce

1. Have a long enough display name
2. Post in a thread

#### What did you expect?

Not sure how it should be rendered, but the name seems weirdly spaced in the screenshot below.

#### What happened instead?

![image](https://user-images.githubusercontent.com/5547783/160659392-a46fdcdd-3711-443c-804c-fd276186c98a.png)

(not sending logs because I don't believe it's necessary, feel free to ask for some if it is)

### Operating system

Arch Linux

### Browser information

98.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 5eecc768a389-react-e161f0b17bf4-js-26cbe02a7f2e, olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

No

**Comment by robintown** [comment] 2022-03-29 16:36
Duplicate of https://github.com/vector-im/element-web/issues/21472

**Closed by robintown** 2022-03-29 16:36 UTC
Labels: T-Defect
