### ISSUE TITLE
Screen sharing does not work in the desktop app

### ISSUE THREAD

**Issue by FF03de** [vector-im/element-web#16641] opened 2021-03-08 19:44 UTC
### Description

When I do a meeting with the Jitsi widget, I can't share a screen with the desktop app, it just loads the whole time. In the browser version you can share the screen without any problem.

### Steps to reproduce

I click on the i at the top and then on Edit Widgets, Bridges & Bots. After I have done that I click on Add integrations and select Jitsi. In the meeting I want to share the screen, it opens the window but it just loads and I can't select what I want to share.  

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: Desktop

For the web app:

- **Browser**: Microsoft Edge  89.0.774.45
- **OS**: Windows 10
- **URL**: app.element.io 

For the desktop app:

- **OS**: Windows 10
- **Version**: 1.7.22

**Comment by FF03de** [comment] 2021-03-08 19:46
Logs being sent: no

**Comment by t3chguy** [comment] 2021-03-08 20:02
Duplicate of https://github.com/vector-im/element-web/issues/4880

**Closed by t3chguy** 2021-03-08 20:02 UTC
