### ISSUE TITLE
Encryption Issue in Desktop App

### ISSUE THREAD

**Issue by kattiara** [vector-im/element-web#16613] opened 2021-03-05 16:43 UTC
### Description

The desktop app of Element errors out for me after longish periods of inactivity. Something seems to be breaking the encryption, but not sure what. This happens every single night, overnight -- when I go to my computer in the morning, all previous messages show up like this:
![element_error1_decryptfail](https://user-images.githubusercontent.com/3699278/110134982-00663300-7d9c-11eb-921e-bbde05862910.png)

It happens every night, but I've also had it happen a couple times during the day when away from my computer for longish times (~5+ hours). 

When this happens, it also seems to "break" the ability to log out from the desktop app -- clicking to try and sign out does nothing. The only fix I've found is to go into the mobile app, use that to terminate the desktop session, and then log back in to the desktop app. At that point everything looks normal again.

This is on a Windows 10 computer which is not set to sleep or hibernate.

These are my current security settings from the desktop app:
![element_securitysettings1](https://user-images.githubusercontent.com/3699278/110144891-dbc38880-7da6-11eb-93c7-0cf5f94426dc.PNG)
![element_securitysettings2](https://user-images.githubusercontent.com/3699278/110147285-7fae3380-7da9-11eb-8a43-e5e3fd312567.png)

### Steps to reproduce

- Leave computer alone for 5+ hours, with Element desktop app running

Messages seem to "break" and don't display correctly until after force killing the desktop session (from mobile app) and relogging.

Logs being sent: yes

### Version information

- **Platform**: 
Desktop app - Windows 10, Element version: 1.7.22, olm version: 3.2.1

**Comment by kattiara** [comment] 2021-03-05 16:47
After creating the ticket, I tried to submit debug logs through the app, however, I now get another error message:

![element_debuglogsendfail](https://user-images.githubusercontent.com/3699278/110146447-986a1980-7da8-11eb-8b71-341bf6503ec0.PNG)

**Comment by jryans** [comment] 2021-03-05 16:54
@kattiara Are you perhaps low on disk space? The transaction error suggests the app is having trouble writing to storage on disk.

**Comment by kattiara** [comment] 2021-03-05 17:27
@jryans Thanks for taking a look! I'm actually fine on disk space (~750+ GB free) atm, so don't think that's the issue.

**Comment by kattiara** [comment] 2021-03-05 23:31
I'm not sure if something else triggered it this time, but I actually just had it happen again without the longer period of inactivity:

![element_shortfail](https://user-images.githubusercontent.com/3699278/110185585-bc495180-7de0-11eb-93b9-094fbeab980f.png)

Note that at 5:40, I was able to send messages just fine. However, about half an hour later, the client had broken again, and responses to me were throwing the same error. Once again needed to forcekill the session and relog. 

The user who was messaging me said that from their client, they were able to see the shield icon for me go red, indicating (I think) my encryption was broken.

**Comment by richvdh** [comment] 2023-01-12 17:37
duplicate of https://github.com/vector-im/element-web/issues/14174 I think

**Closed by richvdh** 2023-01-12 17:37 UTC
Labels: T-Defect, X-Needs-Info, A-E2EE, A-Storage
