### ISSUE TITLE
Element-R: lazy loading of members not working

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26419] opened 2023-10-23 09:27 UTC
Element-R loads all the members of encrypted rooms at startup, making lazy-loading a bit useless

https://github.com/matrix-org/matrix-js-sdk/blob/6e2ac03f7e130ec721fc67176883571547608ee6/src/rust-crypto/rust-crypto.ts#L1237

legacy crypto has code to handle this:  https://github.com/matrix-org/matrix-js-sdk/blob/6e2ac03f7e130ec721fc67176883571547608ee6/src/crypto/index.ts#L2928

**Comment by t3chguy** [comment] 2023-10-23 09:29
Duplicate of https://github.com/vector-im/element-web/issues/26418

**Closed by t3chguy** 2023-10-23 09:29 UTC
Labels: T-Enhancement, Z-Labs, A-Element-R
