### ISSUE TITLE
Element Desktop error dialog triggered when joining a Room via a Space (Godot)

### ISSUE THREAD

**Issue by nlutterman** [vector-im/element-web#24113] opened 2022-12-27 11:27 UTC
### Steps to reproduce

**1. Where are you starting? What can you see?**

I was examining the Godot Space and clicked the "Join" button to join the "Godot Engine" Room. The error dialog appeared and suggested filing a bug report. The "Join" function failed repeatedly before the popup appeared. Other than that, nothing else was strange or seemingly broken.

After clicking the link to submit an issue, this is my screen: 

![image](https://user-images.githubusercontent.com/2424815/209659410-e5f86a07-756c-41f7-b4e4-e69e940d42b3.png)

**2. What do you click?**

I clicked the "Join" button for the "Godot Engine" Room from the perspective of the Godot Space.

**3. More steps…**
Nothing else.

#### What did you expect?

I expected to join the Godot Room from the Godot Space.

#### What happened instead?

Joining failed repeatedly without specific reason. After 3-4 attempts, the error dialog appeared.

### Operating system

Fedora Rawhide, KDE 5.26.4, Qt 5.15.7, Wayland

### Application version

Element/1.11.17 Chrome/108.0.5359.62 Electron

### How did you install the app?

https://flathub.org/apps/details/im.riot.Riot

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by nlutterman** [comment] 2022-12-27 11:37
Apologies for not having more worthwhile notes for reporting. The issue occurred rather abruptly.

It does seem as though I did successfully join the Godot Engine Room, however. 
![image](https://user-images.githubusercontent.com/2424815/209660714-d601d618-b6b1-4bb1-94f0-040743838348.png)

I'm suspecting that the error occurred from my already having successfully joined the Room, but clicking the "Join" link repeatedly like a dingus anyway. 

I suppose in that case I would have expected that the application would have reacted by showing a "success" message of some kind and disabled the "Join" button to denote already being a member. 

Let me know if there's anything else I can do to assist!

**Comment by weeman1337** [comment] 2022-12-29 08:08
Thanks for reporting the issue @nlutterman . I would file this as a duplicate of #15627. Follow the other issue for updates.

**Comment by weeman1337** [comment] 2022-12-29 08:08
duplicate of #15627

**Closed by weeman1337** 2022-12-29 08:08 UTC
Labels: T-Defect

**Comment by t3chguy** [comment] 2023-01-03 11:24
@weeman1337 this sounds like a duplicate of https://github.com/vector-im/element-web/issues/22752

**Comment by weeman1337** [comment] 2023-01-03 12:41
Duplicate of #22752
