### ISSUE TITLE
Allow vertical resizing/expansion of message box. Accommodate editing large messages.

### ISSUE THREAD

**Issue by jwmay2012** [vector-im/element-web#22366] opened 2022-05-26 18:50 UTC
#### What would you like to do?
Have the message edit/create box allow for significantly more than 9 lines. Especially on Desktop/Web.
The message box should be able to grow to 2/3 vertical height or more lines tall, somehow.

#### Why would you like to do it?
To conveniently write/edit large messages. 
My purposes are for note taking and markdown editing, but any message larger than ~18 or so lines becomes difficult to edit.

#### How would you like to achieve it?
I'm imagining something similar to Slack which automatically expands up to a certain height (~2/3 of screen), or maybe even like these text boxes on Github where you manually expand the textbox. 

Maybe a configuration option can set how large the message box can get automatically in lines, percent of screen, etc.
Maybe a config option enables manual resizing. 

I'm not sure how mobile formats should be affected, if at all. Probably fine the way it is. 

### Additional context

Thanks

**Comment by t3chguy** [comment] 2022-05-26 18:56
Duplicate of https://github.com/vector-im/element-web/issues/5882

**Closed by t3chguy** 2022-05-26 18:56 UTC
Labels: T-Enhancement

**Comment by jwmay2012** [comment] 2022-05-26 18:58
Thanks, I searched for a while but was unable to locate the existing issue.  :)
