### ISSUE TITLE
Left-click on tray icon opens menu instead of show/hiding the window

### ISSUE THREAD

**Issue by kindlyfire** [vector-im/element-web#11772] opened 2020-01-04 12:35 UTC
### Description

Left-clicking on the tray icon does not show/hide the Riot desktop app. Instead, it shows the menu that also shows up on right click.

As I understand it, other people in the Riot Web/Desktop room do not seem to have this issue.

### Steps to reproduce

- Start Riot
- Left click the tray icon
- Menu opens instead of Riot hiding itself

### Version information

- **Platform**: desktop
- **OS**: [Solus](https://getsol.us/home/) with Budgie
- **Version**: 1.5.6 from the Solus repos

**Comment by foresto** [comment] 2020-01-22 22:39
Confirming. It is a hassle to fiddle with menus when I just want to open the chat window from the system tray / indicator icon. I should be able to just click it.

Tested on Xubuntu linux, using the Riot electron app downloaded today from the ubuntu repo. I don't know how to get it to tell me its version number.

**Comment by foresto** [comment] 2020-01-22 22:45
Probably a dupe of #7553.

**Comment by MazeChaZer** [comment] 2020-02-19 14:51
A few weeks ago, left clicking opened Riot directly, but now I am also experiencing the same problem, now matter if left or right click, only the menu comes up. I'm using i3 with i3bar.

**Comment by t3chguy** [comment] 2020-02-19 16:23
I believe the electron version was updated so its probably an upstream issue

**Comment by foresto** [comment] 2020-02-19 17:13
If it's an upstream issue, has somebody on the riot dev team reported the issue upstream?

**Comment by t3chguy** [comment] 2020-02-19 17:15
I don't think anyone on the dev team can reproduce it on their machines and don't have time to set up i3 etc to reproduce it, do you get similar issues on any other modern electron apps?

**Comment by foresto** [comment] 2020-07-08 19:39
> do you get similar issues on any other modern electron apps?

I don't use any other electron apps. Can you suggest one with which to test?

For the record, the tray icon was behaving correctly for several versions (left click opens window), until a recent upgrade broke it again (left click opens menu).

**Comment by ozanakman** [comment] 2020-08-31 11:37
I use CentOS 7 and have the same issue. It shows only the menu "Show/hide and Quit" on the left click

**Comment by herzenschein** [comment] 2020-09-13 20:28
I can reproduce this on openSUSE Tumbleweed/Krypton with Element from the official repo. libappindicator3 is installed.

Slack and Discord (both flatpaks) show the same behavior.

**Comment by t3chguy** [comment] 2020-09-13 20:53
The official repo is Debian and Ubuntu only, so which repo did you use?

**Comment by herzenschein** [comment] 2020-09-13 21:12
> The official repo is Debian and Ubuntu only, so which repo did you use?

Sorry, it was a while since I installed it, I misremembered. I installed it from [this repo](https://github.com/taw00/element-rpm) which builds from the [Fedora COPR](https://copr.fedorainfracloud.org/coprs/taw/element/). By official I actually meant a proper rpm package rather than a containerized one like flatpak.

**Comment by wincak** [comment] 2020-12-21 10:03
This is also an issue for as long as I remember on KDE Neon (based on Ubuntu) with the official package from:
https://packages.riot.im/debian/
I don't have any other Electron based applications to compare; libappindicator3 is installed, if that matters.

**Comment by shapirus** [comment] 2021-01-15 21:49
FWIW, I have this issue on a current Debian Sid with KDE 5.20.5. I installed electron-desktop from https://packages.riot.im/debian/pool/main/e/element-desktop/ and it pulled libappindicator3 as a dependency.

**Comment by shapirus** [comment] 2021-01-15 21:51
FWIW, I have this issue on a current Debian Sid with KDE 5.20.5. I installed electron-desktop from https://packages.riot.im/debian/pool/main/e/element-desktop/ and it pulled libappindicator3 as a dependency.

**Comment by manuke42** [comment] 2021-05-22 11:27
I have the same issue in latest Kubuntu version. I found a workaround that's working for me from the [Signal Issue (comment)](https://github.com/signalapp/Signal-Desktop/issues/3045#issuecomment-844877110). For me it was:
`$ sudo touch /opt/Element/libappindicator3.so
$ sudo touch /opt/Element/libappindicator3.so.1`

Now left clicking the tray icon of Element opens and hides the window directly instead of just opening the context menu.

**Comment by heini** [comment] 2021-05-22 11:33
Thanks, @manuke42, works for me too.
Maybe worth mentioning: One has to restart Element after creating the files.

**Comment by foresto** [comment] 2021-05-22 21:12
I hereby confirm the libappindicator3 workaround on Xubuntu 20.04 when applied to the flatpak build of Element.

Adding these lines to the build-commands in im.riot.Riot.json did the trick:

    "touch /app/Element/libappindicator3.so.1",
    "ln -s libappindicator3.so.1 /app/Element/libappindicator3.so",

**Comment by Jieiku** [comment] 2022-07-03 13:38
This is not longer fixed by touching those files.

**Comment by Solarunit** [comment] 2022-08-22 21:40
I wanted to create an issue about this problem, but it turned out there is an old one.
I hope it will be fixed some day.
I am using Solus Budgie.

**Comment by shapirus** [comment] 2022-08-23 06:00
It can [only, I'm afraid] be fixed to moving to a different toolkit (for example, QT) that is not made of a pile of garbage code like Electron is.

**Comment by foresto** [comment] 2022-09-06 22:00
> This is no longer fixed by touching those files, back to being an issue.
> I am on latest Manjaro KDE Plasma.

Still works for me with the latest freedesktop (flatpak) runtime, by adding these steps to the flatpak build-commands section:

      - touch /app/Element/libappindicator3.so.1
      - ln -s libappindicator3.so.1 /app/Element/libappindicator3.so

**Comment by autoteelar** [comment] 2022-10-26 12:18
does anyone know if those workarounds still work?

**Comment by autoteelar** [comment] 2022-10-26 12:19
well, seems to need to be recompiled anyways with that workaround from the short read i did, imo not too worth it since element releases are pretty frequent, would have to do it every time

**Comment by autoteelar** [comment] 2022-10-26 12:21
> It can [only, I'm afraid] be fixed by moving to a different toolkit (for example, QT) that is not made of a pile of garbage code like Electron is.

honestly from the last time i used nheko, im happy with electron

qt would be nice though i like GTK better, themes look better

**Comment by autoteelar** [comment] 2022-10-27 15:12
hi thanks for the reply! 

Adding these lines to the build-commands in im.riot.Riot.json did the trick:

"touch /app/Element/libappindicator3.so.1",
"ln -s libappindicator3.so.1 /app/Element/libappindicator3.so",


i saw you posted this earlier,

how exactly can i do that?  i cant find a im.riot.Riot.json did anywhere

**Comment by foresto** [comment] 2022-10-27 18:52
> how exactly can i do that? i cant find a im.riot.Riot.json did anywhere

That variant of the workaround is for people who build the flatpak themselves. I did it using flathub's [manifest](https://docs.flatpak.org/en/latest/manifests.html), which is a yaml file, not json. (It also uses the Element binary from the official element.io .deb file.)

**Comment by t3chguy** [comment] 2022-12-06 23:26
Fixed in Electron 22

**Closed by t3chguy** 2022-12-06 23:26 UTC
Labels: T-Defect, A-Electron, Z-Upstream, A-Tray-Icon
