### ISSUE TITLE
Cannot Access Encrypted Historical Room History

### ISSUE THREAD

**Issue by notifier1** [vector-im/element-web#16284] opened 2021-01-26 01:17 UTC
### Description

When you leave an encrypted room on Element desktop, you cannot access your copy of the conversation history, because it apparently disappears from the GUI altogether after signing out once.

This is a problem because when it is important to cite past conversations in order to prevent interpersonal and work accountability issues, it becomes difficult to avoid narrative-twisting by one party if you leave a room to avoid interacting with someone behaving unpleasantly. Then, the person who abused the software has all the records, and can use them to selectively tell a narrative, without being able to be checked by the shared record of the person who tried to distance themselves from a problematic interaction by leaving the room.

Accountability in group comms is important, and having these records deleted seems like a mistake in either design or implementation. I'm leaning towards the latter, because it appears that historical rooms were at least originally intended to be retained by parties who left a room. I filed this as a "suggestion" just to be on the safe side and not get this issue deleted prematurely, because I think it's a conversation worth having.

Additionally, there is no functionality within the GUI to export room history either. So people who are trying to avoid abusive comms are in a difficult position: either remain in chat and retain records, or leave chat and not retain records. I guess you can mute it, but that's not sufficient for everyone's needs either. I think that both retaining historical chats, and allowing for some usable functionality in the GUI to export chats you are currently in, are good ideas that should be considered/discussed for development.

Thank you for everyone who read this report. Out

Related: 

https://github.com/vector-im/element-web/issues/7850

https://github.com/vector-im/element-web/issues/9129

https://github.com/vector-im/element-web/issues/2286

https://github.com/vector-im/element-web/issues/15247

### Steps to reproduce

- Join encrypted room on element-web
- Leave that room, room joins historical list
- Sign out and in, the room is no longer in the historical list

Logs being sent: yes/no

### Version information

- desktop (linux, Pure OS, debian), android
- latest versions as of jan 25 2021 (fully up to date) 
v1.7.17 desktop 
v1.0.14 android

**Comment by t3chguy** [comment] 2021-01-26 01:19
Duplicate of #7850 & https://github.com/vector-im/element-web/issues/14038

**Closed by t3chguy** 2021-01-26 01:19 UTC
Labels: suggestion
