### ISSUE TITLE
Previewing a room you've previously joined gives preview for when you last joined it

### ISSUE THREAD

**Issue by Standard8** [vector-im/element-web#15043] opened 2020-08-26 06:29 UTC
### Description

A while ago, I was in a room, then left it. I wanted to preview it to see a recent discussion that was held (rather than joining as I don't need to join in this case). However when I preview it, I get the history of the room from when I last left.

### Steps to reproduce

- Join a room, let there be a page or two of discussion, leave a room.
- Wait a month or so.
- Attempt to preview the room.

Expected Results: Preview of the latest discussions in the room.
Actual Results: The preview shows the discussions from the last time I was in the room.

Logs being sent: yes/no

### Version information

- **Platform**: desktop
- **OS**: macOS
- **Version**: 1.7.4

**Comment by t3chguy** [comment] 2020-09-09 15:14
Duplicate of https://github.com/vector-im/element-web/issues/1220

**Closed by t3chguy** 2020-09-09 15:14 UTC
Labels: bug, synapse
