### ISSUE TITLE
Shortcut to temporarily hide read rooms in the sidebar

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#7635] opened 2018-10-31 11:21 UTC
A shortcut/button or both to hide all read rooms (and possibly rooms that don't pass the threshold to send a notification) temporarily in the sidebar so you can focus only on the rooms that you currently care about.

I feel that having the shortcut be one that you press and hold would also be kind of nice UX.

**Comment by MurzNN** [comment] 2018-10-31 11:24
When users are joined to many active rooms, very often they mark as read rooms in top of list, but after this they don't see in Riot interface rooms, that have unread messages, without scrolling.
Here is example of problem: 
![](https://i.imgur.com/8cxPOlR.png)
So I vote too for have quick toggle "all / only unread rooms" in Room list panel, eg via checkbox in top right panel, that will temporary hide all read rooms from interface and show only unread.

**Comment by uhoreg** [comment] 2018-10-31 14:19
Related to (possibly dup of) https://github.com/vector-im/riot-web/issues/3446

**Comment by anoadragon453** [comment] 2018-10-31 15:58
It is indeed related, but this would be a keyboard shortcut to activate the functionality.

**Comment by lampholder** [comment] 2018-11-13 15:16
There's a clear need at the heart of this and #3446 (the need to focus on 'active rooms requiring your attention now' over all the rooms you're joined to), but we'll want to think about the UX of how that need is met very carefully. Done poorly this could easily be either hard to discover or confusing to use :\

**Comment by MurzNN** [comment] 2018-11-13 16:56
In VK messenger this feature is implemented in toggle at bottom of rooms list, here is screenshot:
![](https://i.imgur.com/A5Jt5Sa.png)
In Riot we can place same toggle to right side of top search (room filter) line, and hide it when user start typing.

**Comment by turt2live** [comment] 2020-08-31 19:34
Duplicate of https://github.com/vector-im/element-web/issues/7185

**Closed by turt2live** 2020-08-31 19:34 UTC
Labels: feature, p2, type:roomlist, type:shortcuts, ui/ux
