### ISSUE TITLE
Ability to move in call window

### ISSUE THREAD

**Issue by Latrolage** [vector-im/element-web#17566] opened 2021-06-05 04:02 UTC
The in call window is currently always in the bottom right of the screen when you switch to other channels.

It blocks view of read receipts, being able to drag this window around, and maybe smoothly snap near a corner/side of the screen after letting go of it would be nice.

Also, in call box is too large (when it covers the top of the chat). The resizing function there is limited there and I couldn't find a way to just minimize it.

**Comment by SimonBrandner** [comment] 2021-06-05 05:22
Duplicate of [#17130](https://github.com/vector-im/element-web/issues/17130)

**Closed by SimonBrandner** 2021-06-05 05:22 UTC
Labels: T-Enhancement
