### ISSUE TITLE
There should be a clear indicator of the text input area

### ISSUE THREAD

**Issue by K4LCIFER** [vector-im/element-web#25855] opened 2023-07-27 02:15 UTC
#### What would you like to do?

I would like to see a clear deliniation of the text input/typing area. Currently, the text input area has no visual difference with the rest of the chat history. All it shows is "Send a message...":
![image](https://github.com/vector-im/element-desktop/assets/7829231/5df4eff7-4971-4d56-a601-361816916fc7)

#### Why would you like to do it?

I feel that it is better for UX to show a clear indicator of the typing area. It feels weird that the text just goes right to the bottom of the window, and right into the chat history with no clear designated area for it.

#### How would you like to achieve it?

What discord does is a good example:
![image](https://github.com/vector-im/element-desktop/assets/7829231/7be1172a-19e3-4a46-adde-8b33b011adc5)

**Comment by weeman1337** [comment] 2023-07-27 08:33
Duplicate of https://github.com/vector-im/element-meta/issues/947

**Closed by weeman1337** 2023-07-27 08:33 UTC
Labels: T-Enhancement
