### ISSUE TITLE
Allow composer size to be configurable

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#17854] opened 2021-07-01 10:59 UTC
#### Is your suggestion related to a problem? Please describe.

> Several customers complain it should be bigger. Is there some way to change constants in code to make it preexpanded to N lines and dynamically grow to M lines?

#### Describe the solution you'd like.

https://github.com/matrix-org/matrix-react-sdk/blob/78b1f6c0b13efd57031a329a1ac62baba948dad3/res/css/views/rooms/_SendMessageComposer.scss

Currently, the size is controlled by `mx_BasicMessageComposer` `min-height` and `mx_BasicMessageComposer_input` `max-height`, expressed in pixels. Ideally we could express this in lines of text, and have there be two variables:

* `composer.initialLineHeight`
* `composer.maxLineHeight`

Where `maxLineHeight` is the number of lines before scrolling begins.

#### Describe alternatives you've considered.

The same but still using pixels. I'd prefer lines.

#### Additional context

Customer ask. This is in a context where they are replacing email, rather than another chat, so needs to be larger area.

**Comment by t3chguy** [comment] 2021-07-01 11:01
Duplicate of https://github.com/vector-im/element-web/issues/5882

**Closed by t3chguy** 2021-07-01 11:01 UTC
Labels: A-Composer, Sponsored, T-Enhancement
