### ISSUE TITLE
Riot should not overrestrict alias character set

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12455] opened 2020-02-21 13:25 UTC
Riot randomly refuses to let me use capital letters in alias names. This is very frustrating when trying to add alt aliases with different capitalisation...

**Comment by bwindels** [comment] 2020-02-21 13:30
Alt aliases or local aliases? There's no UI yet for the former though? Latter seems to work for me:

![capalias](https://user-images.githubusercontent.com/274386/75038432-4496d600-54ae-11ea-9c1e-2d3df278aaca.gif)

**Comment by aaronraimist** [comment] 2020-02-21 14:26
Yeah as far as I can tell Riot doesn't do this (but it should, until the spec finally decides to make aliases all lowercase Riot should at least enforce this)

**Comment by t3chguy** [comment] 2023-05-12 09:14
Closing as cannot reproduce.

**Closed by t3chguy** 2023-05-12 09:14 UTC
Labels: A-Aliases
