### ISSUE TITLE
Notification badge/count caused by a thread won't clear

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#19770] opened 2021-11-16 15:42 UTC
### Steps to reproduce

I can't clear the red badge count in a room. I suspect it's because I was mentioned in a thread.:

<img width="1904" alt="Screenshot 2021-11-16 at 15 37 15" src="https://user-images.githubusercontent.com/4626865/142016515-5a8d0e7f-1816-4cbe-ad67-9c68fd22f168.png">

### Operating system

macOS

### Browser information

Chrome, latest

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Will you send logs?

If requested (please DM).

**Comment by HarHarLinks** [comment] 2021-11-16 17:42
Happens to me, too

**Comment by gsouquet** [comment] 2021-11-22 16:13
Sorry I know this is a very frustrating one, but it is a duplicate of https://github.com/vector-im/element-web/issues/19126

I'm in the process of testing and making sure this PR can land safely as I found many regressions in my previous testing. For threads we need to rework significantly how notifications work hence why this is taking a bit longer

**Closed by gsouquet** 2021-11-22 16:13 UTC
Labels: S-Critical, O-Frequent, A-Threads, Z-ThreadsP0
