### ISSUE TITLE
Windows, desktop: Blank screen with automatic startup

### ISSUE THREAD

**Issue by AaronStiff** [vector-im/element-web#16247] opened 2021-01-22 23:06 UTC
### Description

I'm running Element Desktop on Windows, and when "Start automatically after system login" is on, Element starts up like it should, but all it displays is a black screen. Once I close this and open it again, it runs properly.

### Steps to reproduce

- Turn on "Start automatically after system login" under Settings>Preferences>General
- Shut down and then boot up machine
- Log on, and Element will start up with a blank screen
- Close Element, and then reopen to run normally

Element should start up normally on the first try.

Logs being sent: no (unable to upload .tar, please instruct)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.7.17

![Capture](https://user-images.githubusercontent.com/69512633/105558259-90688580-5ce4-11eb-8abf-a09a6c3a62db.PNG)

**Comment by a-mnich** [comment] 2021-01-29 07:47
duplicate of #15486

**Closed** 2021-01-29 10:35 UTC
Labels: bug
