### ISSUE TITLE
Exception when trying to join a room from a Space using the filter

### ISSUE THREAD

**Issue by Florian14** [vector-im/element-web#23034] opened 2022-08-09 09:07 UTC
### Steps to reproduce

1. In the menu, I selected "explore rooms" right to a Space title
2. I filtered the rooms list to find a specific room
3. I found the room which was displayed several times (belong to different sub-spaces)
4. I click on the join button on the first result (in the top level of my current space)
5. The exception appeared in a pop-up and suggested sending a report

#### What did you expect?
To join the requested room

#### What happened instead?
An exception

### Operating system

MacOS

### Application version

Element Nightly : 2022080801
Olm : 3.2.12

### How did you install the app?

From the website

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Florian14** [comment] 2022-08-09 09:14
Update: I succeed to join the room, I think the error has been triggered when trying to navigate to the room or to update the room list

**Comment by t3chguy** [comment] 2022-08-09 09:52
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-08-09 09:52 UTC
Labels: T-Defect
