### ISSUE TITLE
Canonical DM handling

### ISSUE THREAD

**Issue by cvoges12** [vector-im/element-web#14634] opened 2020-07-19 14:15 UTC
In the original riot, there was a feature to mark a room as a direct message, or as Element calls it "people". So in element, I would suppose the best would be to mark rooms as People instead of just Favorites.

The alternative would be to auto-detect same accounts, but this could turn "hacky" as many accounts do not have exactly the same name. In fact, many users have a few changes in their names on purpose to differentiate between the accounts.

Another alternative would be to mark accounts as identical accounts or as back ups. This way element could see there's only really 2 users in the group. No special treat meant such as mirroring would be desired. Just the ability to have direct message chats be treated different than Rooms, and as People.

It would be nice to have the same feature as riot because many of the users on matrix invite their alternative or back up accounts to these direct message rooms. But it is still a one on one conversation. So a lot of rooms that are actually DMs would get miss-organized very quickly.

**Comment by turt2live** [comment] 2020-07-19 15:55
This is effectively a duplicate of several DM-related issues in our issue tracker, all leading back to https://github.com/matrix-org/matrix-doc/pull/2199

The naming, behaviour, and representation of these rooms will be changing.

**Comment by turt2live** [comment] 2020-09-01 13:34
Duplicate of https://github.com/vector-im/element-web/issues/3457

**Closed by turt2live** 2020-09-01 13:34 UTC
Labels: suggestion
