### ISSUE TITLE
Adding GIF Search database button

### ISSUE THREAD

**Issue by n4rkip0d** [vector-im/element-web#20299] opened 2021-12-21 11:26 UTC
#### What would you like to do?

Would it be possible to add a custom button next to emoji / file sharing button ?

![image](https://user-images.githubusercontent.com/68989865/146922456-aa0b1e4b-ae6f-458f-bca5-46f08360b1e8.png)

Or maybe add it as a features labs first ?

#### Why would you like to do it?

The users in our company are pretty annoyed with the request `!giphy text_to_find_giphy` they need to type everytime, and they get a random GIF, which sometimes does not refer to what they say.

#### How would you like to achieve it?

It would be nice to have something like Google Chat button, a simple one with search database for GIPHY. 

![gif_searchbase](https://user-images.githubusercontent.com/68989865/146921441-0f89c51a-f3a1-4ce5-b6ee-b295e2d72647.gif)

### Have you considered any alternatives?

I already try the go-neb bot with GIPHY service, it work but it add useless text in the chat conversation.

**Comment by t3chguy** [comment] 2021-12-21 12:30
Duplicate of https://github.com/vector-im/element-web/issues/415

**Closed by t3chguy** 2021-12-21 12:30 UTC
Labels: T-Enhancement
