### ISSUE TITLE
Eventually Element shows nothing but a white page

### ISSUE THREAD

**Issue by konomikitten** [vector-im/element-web#18385] opened 2021-08-04 16:38 UTC
#### Description

After leaving Element alone for awhile I'll come back to an empty white window.
I can get the developer console to come up with ctrl+shift+i but DevTools reports
that it has been disconnected from the page. I have no option but to restart the client.
I use Discord another Electron based client and it never has any issues like this.

#### Steps to reproduce

- I can't think of any specific steps to reproduce this.

Describe how what happens differs from what you expected.

Logs being sent: no

#### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Debian Bullseye
- **Version**: 1.7.34

#### Screenshots
![Screenshot_2021-08-05_02-31-43](https://user-images.githubusercontent.com/12713710/128219365-1e1f06cf-c87c-4fe1-99cc-3c92c7170d56.png)

**Comment by robintown** [comment] 2021-08-04 18:03
So if I understand correctly, Firefox is causing your system to run out of memory and kill Element? From what I'm reading, oom badness is just calculated from how much memory the process is using, and how long it's been running (targeting shorter-lived processes first), so I don't really see much reason why Element would be targeted while Discord is safe, other than perhaps just general memory usage.

Any way you can fix that buggy Firefox page? ;)

**Comment by konomikitten** [comment] 2021-08-04 18:55
>  From what I'm reading, oom badness is just calculated from how much memory the process is using

It's not that simple Element is setting it's oom_score_adjust to 300 which is much higher than it's actual score which would only be 20. Discord also sets oom_score_adjust but only to 200. Even if it was set lower it probably still would've been the first killed based on the scores. I wish electron apps wouldn't touch oom_score_adjust.

Is there any way Element could handle one of it's processes being killed off instead of just showing a white ui? Maybe the main process should quit if a vital sub process dies?

**Comment by robintown** [comment] 2021-08-04 19:05
Ah I see, that info is very helpful

**Comment by AppTester7** [comment] 2021-11-15 02:21
I too have this exactly same problem with element occasionally going to a white screen, even if i dont interact with element
Sometimes this happens upon startup, and sometimes when Im going to a different room it happens

OS: OpenSUSE Tumbleweed
DE: KDE Plasma Wayland
Element version: 1.9.2
Olm version: 3.2.3

**Comment by novocaine** [comment] 2021-11-21 23:23
Duplicate of https://github.com/vector-im/element-web/issues/18168

**Closed by novocaine** 2021-11-21 23:23 UTC
Labels: T-Defect, S-Minor, A-Electron, O-Uncommon
