### ISSUE TITLE
Add ability to disable read/leave/join notifications per-channel

### ISSUE THREAD

**Issue by mbr0wn** [vector-im/element-web#16310] opened 2021-01-29 13:49 UTC
## The Problem

This is one of the chat rooms I'm in (screenshot only of chat room window, i.e., the middle bit):
![image](https://user-images.githubusercontent.com/508035/106281675-d4590e80-623f-11eb-8f7a-e250ec6bddb5.png)

This room has around 1-1.5k users, depending how you count (the IRC bridge doesn't make this obvious). The amount of screen real estate used by notifications is ridiculous. At this number of users, I don't want see joins, leaves or reads. Also, no "$USER is typing". 

[It's a public room, so no secrets. I smudged the names just so there's no distraction].

For reference, here's the actual content:
![image](https://user-images.githubusercontent.com/508035/106282133-7547c980-6240-11eb-83fa-2f06e2500e96.png)

All the white bits are clogging the interactions. The problem is that not only is screen real estate wasted, I also have a hunch we might be transmitting unnecessary info to folks.

## Suggestion

Can we please have a button that turns all of this off. Not sure if this should be per-user-and-room, or per-room. The latter might help us reduce our server loads. Maybe this is also a server-side thing, I'm not sure.

**Comment by t3chguy** [comment] 2021-02-01 13:27
Duplicate of https://github.com/vector-im/element-web/issues/5186

**Closed by t3chguy** 2021-02-01 13:27 UTC
Labels: suggestion
