### ISSUE TITLE
Toggling Video off in a call still shows using camera

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17454] opened 2021-05-24 15:04 UTC
### Description

Toggling Video off in a call still shows using camera - the camera is showing this.

### Steps to reproduce

- Make a video call
- Toggle video off

I expected the camera to not be used...

Logs being sent: no

![image](https://user-images.githubusercontent.com/31655082/119367241-0b04da00-bcb2-11eb-95cd-d5e6ca06787e.png)

**Comment by SimonBrandner** [comment] 2021-05-24 16:02
Ah, sorry I got confused... What do you mean? This looks like a duplicate of [#17455](https://github.com/vector-im/element-web/issues/17455). But perhaps you mean that the light on the camera is saying it's recording?

**Comment by chagai95** [comment] 2021-05-24 17:08
Yep that's exactly what I mean I guess it doesn't have to be the camera it can also be the browser with that red blinking light

**Comment by SimonBrandner** [comment] 2021-05-24 17:09
Ah, okay, is this is a regression or is this a new thing?

**Comment by chagai95** [comment] 2021-05-24 17:11
I'm not sure, I didn't test before...

**Comment by SimonBrandner** [comment] 2021-05-24 17:24
@chagai95, can you please try [this](https://jyasskin.github.io/sandbox/camera-pause/) out - click `Replace stream` and then click `Disable stream` and see what happens. From my testing, this looks like a Chrome bug which already seemed to have been filed [here](https://bugs.chromium.org/p/chromium/issues/detail?id=642785)

**Comment by chagai95** [comment] 2021-05-24 17:30
I'll try reproducing but it was a college who ran into the issue I just filed the issue here

**Comment by SimonBrandner** [comment] 2021-06-22 10:43
I will close this as there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.

**Closed by SimonBrandner** 2021-06-22 10:43 UTC
Labels: A-VoIP, T-Defect, X-Needs-Info

**Comment by chagai95** [comment] 2022-07-08 14:00
@SimonBrandner I just realized, I can reproduce, for some reason I thought this was another issue, so my comments before are just weird, so ignore them. Regarding the chrome bug, is there no way to work around that? Maybe this ticket should stay open while waiting for them to fix it or eventually someone could come up with a workaround?

**Comment by SimonBrandner** [comment] 2022-07-09 07:35
> Regarding the chrome bug, is there no way to work around that? 

There is no proper way to work around it. The only option would be to drastically change the way we handle muting in calls which is more of a spec issue (see https://github.com/matrix-org/matrix-spec-proposals/pull/3291 and mainly https://github.com/matrix-org/matrix-spec-proposals/pull/3291#discussion_r850442946)

> Maybe this ticket should stay open while waiting for them to fix it or eventually someone could come up with a workaround?

Since once this is fixed in Chrome there won't be anything for us to do to fix it, we wouldn't keep the issue open to just lie around here
