### ISSUE TITLE
Collapsed LeftPanel is now ugly due to the explore button at the bottom.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15256] opened 2020-09-22 10:48 UTC
<img width="134" alt="Screenshot 2020-09-22 at 11 46 46" src="https://user-images.githubusercontent.com/1294269/93873326-72086400-fcc9-11ea-9d98-1422183e42be.png">

**Comment by t3chguy** [comment] 2020-09-22 10:50
Duplicate of https://github.com/vector-im/element-web/issues/15166

**Closed by t3chguy** 2020-09-22 10:50 UTC
Labels: bug, needs-design
