### ISSUE TITLE
pills pop into shape when rendered in the timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7290] opened 2018-09-05 16:32 UTC
it looks like the react component is getting weirdly re-rendered somehow

**Comment by ara4n** [comment] 2018-09-05 20:54
looks on closer inspection as if the avatar is getting added in a separate render phase. @bwindels i wonder if this is somehow connected to profile changes due to LL?

**Comment by weeman1337** [comment] 2023-03-01 08:49
Cannot reproduce for the avatars but for the display name resolution:

![avatar](https://user-images.githubusercontent.com/6216686/222089292-661ca199-918e-42b7-89b3-3222763b4565.gif)

**Comment by t3chguy** [comment] 2023-03-01 15:55
Likely fixed in the past 4.5 years

**Comment by t3chguy** [comment] 2023-03-01 15:55
I can't read

**Comment by weeman1337** [comment] 2023-03-27 08:14
[Current work on permalinks](https://github.com/vector-im/element-meta/issues/1030) should reduce this behaviour.

If the information is locally available it will now be loaded synchronously when rendering a pill. Profile requests are now cached. This means a profile pill will still pop into shape during the first rendering. Further renderings of the same profile should have a stable UI.

→ closing this issue

**Closed by weeman1337** 2023-03-27 08:14 UTC
Labels: T-Defect, P2, S-Major, S-Tolerable, A-Pills
