### ISSUE TITLE
Zero-change edit is not zero-change

### ISSUE THREAD

**Issue by tomsmeding** [vector-im/element-web#23669] opened 2022-11-01 11:09 UTC
### Steps to reproduce

1. Send a message with two `*` embedded in one word, for example `hi*hi*hi`
2. Edit that message by pressing arrow-up
3. Observe that the `*` have changed to `_` -- that's not what you entered before
4. Submit the edit (you need to type something (not necessarily change something) to make Element accept the edit -- but this can be space + backspace)
5. Observe that the message now says "hi_hi_hi" instead of "hi*hi*hi" which it was before

#### What did you expect?

I expect that making no edits to a message (or to a part of a message) does not change that (part of the) message.

#### What happened instead?

It looks like Element reverse-engineers the markdown necessary to produce the original HTML rendering of the user-entered message, and makes mistakes in that process -- relevant to the example, it doesn't know that `*` and `_` have different semantics despite both indicating italics.

This reinterpretation happens in other cases too: sending `\(` and editing that results in `(` (which means the same thing, fortunately). Sending `test` `> test` (with a newline in between) and editing that results in `test` ` `&nbsp;`> test` (which fortunately also means the same thing).

I think the proper solution here would be to somehow give the user the exact same text as they entered when they sent the original message. This also follows the principle of least surprise.

### Operating system

Arch Linux

### Browser information

Firefox 104.0.2, reproduces on Chrome 107.0.5304.87

### URL for webapp

Private server, reproduces on develop.element.io

### Application version

Element version: 1.11.10, Olm version: 3.2.12; reproduces on 8eafb70327a3-react-253129e6f283-js-52830a2a5073 with olm 3.2.12

### Homeserver

Conduit; reproduces on Synapse 1.70.0rc1

### Will you send logs?

No

**Comment by tomsmeding** [comment] 2022-11-01 18:26
This is even worse with usage of `/html`, though that might be harder to fix.
Send the following:

    /html <details><summary>Summary</summary>
    ```
    test
    ```
    </details>

editing that gives a textarea with the following content:

    Summary
    \`\`\`
    test
    \`\`\`

which means something very different.

**Comment by tomsmeding** [comment] 2022-11-01 21:08
Another example without `/html`. Send the following:

```
\- test
```

edit and it becomes this:

```
- test
```

which becomes a bulleted list upon accept.

**Comment by robintown** [comment] 2022-11-02 02:49
These issues will likely be fixed when we switch over to the new rich text editor.

**Comment by t3chguy** [comment] 2022-11-02 11:47
Duplicate of https://github.com/vector-im/element-web/issues/10725

**Closed by t3chguy** 2022-11-02 11:47 UTC
Labels: T-Defect, S-Minor, A-Message-Editing, A-Composer, O-Occasional
