### ISSUE TITLE
Jitsi conference is still running after logout in element

### ISSUE THREAD

**Issue by JohannesKleine** [vector-im/element-web#16725] opened 2021-03-19 09:50 UTC
### Description

Jitsi conference is still running after logout in element.

### Steps to reproduce

- open element
- sign in
- start Jisti session over the jitsi widget
- press the logout button in element
- wait for the element web login screen
- you can still communicate over jitsi
- login again
-  jitsi is open, untill the user interface is fully loaded (it shows the room list)

All jitsi widgets must be terminated within the logout procedure

### Version information

- Firefox 78.7.0esr Debian 10, Element 1.7.20
- Firefox 85.0 Ubuntu 20.10, Element 1.7.20
- Element Desktop 1.7.17 Ubuntu 20.04
- Element Desktop 1.7.20 Debian
- Element Desktop 1.7.20 Ubuntu 20.04

**Comment by t3chguy** [comment] 2021-03-19 09:52
I'm pretty sure this was fixed in 1.7.23.

**Comment by SimonBrandner** [comment] 2021-03-19 09:57
It isn't that PR is for native Matrix calls...

**Comment by t3chguy** [comment] 2021-03-19 09:58
oh indeed

**Comment by SimonBrandner** [comment] 2021-03-19 09:59
I kind of feel like this is a duplicate of something...

**Comment by SimonBrandner** [comment] 2021-03-19 10:01
Probably just related to [#15703](https://github.com/vector-im/element-web/issues/15703)

**Comment by JohannesKleine** [comment] 2021-03-19 14:44
- Firefox 78.8.0esr Debian 10, Element 1.7.23
- Element Desktop on Linux 1.7.22

changed conduct: after logout and login it does not abort the jitsi connection, and then there is after the login the jitsi widged visible

all audio/video connections are created with the Element phone/camera buttons

**Comment by chagai95** [comment] 2021-04-09 10:20
tested with 1:1 matrix calls and the same problem exists (on 1.7.23)

**Comment by JohannesKleine** [comment] 2021-04-09 10:21
here 1.7.24 still the same

**Comment by JohannesKleine** [comment] 2021-04-09 10:26
on Debian 10 and 1.7.24 it ends the call on logout

**Closed** 2021-04-20 08:16 UTC
Labels: A-Jitsi, A-VoIP, P1, T-Defect
