### ISSUE TITLE
Strip EXIF metadata from avatar image (camera make, date and time picture taken, software version)

### ISSUE THREAD

**Issue by solus-hq** [vector-im/element-web#16222] opened 2021-01-20 15:18 UTC
It really is an issue to have EXIF data persist in user avatar images. I can clearly see this (see screenshot below) and it's not something I'd like to see from a privacy respecting app.

<img width="425" alt="Screenshot 2021-01-20 at 18 18 00" src="https://user-images.githubusercontent.com/26515805/105195603-d76f4300-5b4b-11eb-9390-d7ec91bdbe68.png">

<img width="420" alt="Screenshot 2021-01-20 at 18 18 17" src="https://user-images.githubusercontent.com/26515805/105195641-e0601480-5b4b-11eb-8015-a7676432130d.png">

**Comment by t3chguy** [comment] 2021-01-20 15:20
Duplicate of https://github.com/vector-im/element-web/issues/4426

**Closed by t3chguy** 2021-01-20 15:20 UTC
Labels: suggestion
