### ISSUE TITLE
modernizr claims browser has no localstorage when localstorage is full

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3897] opened 2017-05-11 21:49 UTC

**Comment by lampholder** [comment] 2017-05-12 14:42
Do we know if this is a bug with modernizr or our usage of it?

If it's with modernizr nobody else seems to have experienced/reported it on their GitHub.

**Comment by lampholder** [comment] 2017-05-12 14:43
I've P1 majored this because I _imagine_ this causes big problems when it's encountered and I _imagine_ it's most likely to be encountered by power users?

**Comment by uhoreg** [comment] 2017-12-01 19:06
Yes, this causes big problems because Riot will essentially refuse to load at all.  And it will affect people who have logged in long enough to accumulate enough e2e data.  But hopefully this will mostly be addressed when e2e gets moved to indexeddb.

**Comment by Mikaela** [comment] 2019-10-18 14:02
I just encountered this, because my /tmp was full due to being tmpfs (half of RAM) and my RAM was close to full. I wouldn't have known this was the cause without `#riot-web`

**Comment by novocaine** [comment] 2021-10-04 16:03
I'm collecting localStorage related failures into one issue - https://github.com/vector-im/element-web/issues/18423

Closing this as a duplicate - the details of this issue will be linked to it, and not lost.

**Closed by novocaine** 2021-10-04 16:03 UTC
Labels: T-Defect, P1, S-Major
