### ISSUE TITLE
Is it possible to use a opensource CAPTCHA service?

### ISSUE THREAD

**Issue by inet56** [vector-im/element-web#16099] opened 2021-01-09 19:36 UTC
It would be nice if Google captcha is removed and replaced with something opensource.

**Comment by t3chguy** [comment] 2021-01-09 20:30
The captcha used is the one requested by the Matrix server you choose to connect to. Element can't "pick" a different captcha. Duplicate of https://github.com/matrix-org/matrix-doc/issues/1281

**Closed by t3chguy** 2021-01-09 20:30 UTC
Labels: suggestion
