### ISSUE TITLE
Broken "suggested" section in room list

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21848] opened 2022-04-19 13:54 UTC
### Steps to reproduce

switch to a space with suggested rooms you haven't joined

related: #19414?

### Outcome

e.g. #community:element.io

https://user-images.githubusercontent.com/2803622/164019201-69b6ce97-1217-460d-baa8-25080e592b32.mp4

### Operating system

arch

### Application version

Element Nightly version: 2022041901 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.56

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-19 14:51
This would be the 'suggested' header getting wrongly stickied to the bottom

**Comment by t3chguy** [comment] 2023-08-07 14:02
Duplicate of https://github.com/vector-im/element-web/issues/19414

**Closed by t3chguy** 2023-08-07 14:02 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Room-List, A-Spaces, O-Occasional
