### ISSUE TITLE
When a message is not immediately decryptable, you can't react to it once it _has_ decrypted.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#16462] opened 2021-02-16 09:46 UTC
To reproduce:

1. I switched to an encrypted room containing messages which (for some reason) my Eleweb didn't have some decryption keys
2. I checked my mobile to see if it could decrypt the messages - it could
3. I guess Eleweb synced the keys from my mobile and then _could_ decrypt
4. The messages appeared decrypted in the timeline, but mousing over didn't pop up the normal interaction elements (I had the ellipsis for inspecting the event, but no reply/react buttons)

**Comment by t3chguy** [comment] 2021-02-16 09:48
Duplicate of https://github.com/vector-im/element-web/issues/16238

**Closed by t3chguy** 2021-02-16 09:48 UTC
Labels: bug
