### ISSUE TITLE
Convert `src/http-api` to TS

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19274] opened 2021-10-04 15:11 UTC
https://github.com/matrix-org/matrix-js-sdk/blob/ab59e9134b027580d5c067dab279150427836817/src/http-api.js

**Comment by t3chguy** [comment] 2021-10-05 08:34
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/1894

**Closed by t3chguy** 2021-10-05 08:34 UTC
Labels: T-Task, A-Developer-Experience
