### ISSUE TITLE
Scrolling the timeline can get caught in a loop.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#26556] opened 2023-11-11 23:46 UTC
### Steps to reproduce

1. Click on a permalink (e.g. a search result)
2. Start scrolling downwards to read lots of conversation.
3. After ~10 pages, discover that you've suddenly scroll-jumped back several pages - potentially to the permalink
4. Scroll downwards to try to get past the point you got to before
5. Get teleported back again; congratulations: you're stuck in a scroll loop.

The behaviour seems to coincide with hitting a thread in the main timeline.

#### What did you expect?

Scrolling without jumps or loops.

#### What happened instead?

Scrolling with a persistent and reproduceable jump which leaves you stuck in a loop.

I don't have logs atm, but will rageshake when it next happens. I suspect it's reproduceable if you jump to a permalink and then try to scroll past a thread root.

### Application version

nightly

### Will you send logs?

No

**Comment by HarHarLinks** [comment] 2023-11-12 13:11
I think you reported this previously: https://github.com/vector-im/element-web/issues/26080

**Comment by t3chguy** [comment] 2023-11-13 09:13
Duplicate of https://github.com/vector-im/element-web/issues/26080

**Closed by t3chguy** 2023-11-13 09:13 UTC
Labels: T-Defect
