### ISSUE TITLE
The inbound VoIP ringtone is deafening and horrific

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16927] opened 2021-04-12 17:16 UTC
I only added it as a temporary measure, uh, 6 years ago.

Please can we swap it for *anything* which sounds better.

**Comment by turt2live** [comment] 2021-04-12 17:28
Duplicate of https://github.com/vector-im/element-web/issues/5031

**Closed by turt2live** 2021-04-12 17:28 UTC
Labels: A-VoIP, P2, S-Minor, T-Defect
