### ISSUE TITLE
Indicate Notification Received when Chat Room is Out of View

### ISSUE THREAD

**Issue by SethFalco** [vector-im/element-web#16334] opened 2021-02-01 01:44 UTC
**Is your suggestion related to a problem? Please describe.**
When a user is in a lot of chat rooms, a message / notification can occur in a room that's not scrolled into view.
As someone that does not depend on any kind of audio cue, when I received a message sometimes I don't notice at all that I got a new message.

![image](https://user-images.githubusercontent.com/22801583/106405571-f8327500-6436-11eb-9352-557df67ce22a.png)  
> Despite having an unread message, there is no visual guide of this because the "People" section isn't scrolled into view.
 
![image](https://user-images.githubusercontent.com/22801583/106405587-0aacae80-6437-11eb-9b74-80d133359dcf.png)  
> In this example, I sent a message and then deleted it. Deleting the message removes the (1) on the "People" section, however the chat room above still had activity and displays a white dot which I'd like to be aware of. 

**Describe the solution you'd like**
There should be some kind of visual indicator that a message was received in the UI as well. For example Discord handles this situation quite well.

![image](https://user-images.githubusercontent.com/22801583/106405623-2adc6d80-6437-11eb-9b73-fd99ba31c646.png)  
> When a user is scrolled down so a new message is out of view, a little "NEW" badge appears to indicate there's a new message to see if one scrolls up.

**Describe alternatives you've considered**
Alternatively, the "People" field could be made sticky so that it always remains in view at the top.

![image](https://user-images.githubusercontent.com/22801583/106405644-3def3d80-6437-11eb-827f-23aa2c2a1b8e.png)  
> Clicking it would scroll the user up to the top of the "People" section, and provides a visual cue that there is a new message.

**Comment by t3chguy** [comment] 2021-02-01 12:35
There is stickiness already but it is limited to one header at each end.

Duplicate of https://github.com/vector-im/element-web/issues/14057

**Closed by t3chguy** 2021-02-01 12:35 UTC
Labels: suggestion
