### ISSUE TITLE
element desktop installation path

### ISSUE THREAD

**Issue by eetsceeck1** [vector-im/element-web#18946] opened 2021-09-08 13:51 UTC
### Steps to reproduce

Hi

guys your app is i think the most appreciated app what exists on earth in a such a data capitalism,

but i have a serious problem here,
cause this is urgent and very important!

the thing is this, i dont understand guys why you did create an installer with path to a version number,

which is goes like this:

C:\Users\user\AppData\Local\riot-desktop\app-1.8.2

app-1.8.0 OR app-1.8.1 OR app-1.8.2 and so on,

this is really annoying to re-set all my firewalls rules for every new version again and again,

every time a new element version is being installed my 4 firewalls + 3 HIPS and program control modules all need to be reconfigured again for element, cause they are all goes to the absolute path of element, which is include the version number so all the configurations what have been set before are all irrelevant for the new version,

also the program don't inform at all for updates, it just updating and its updating at the very wrong time,

my father did called me on element in an emergency matter and element decided to update itself in a middle of a call,

element is the only communication i have with family and friends at the moment cause its the only app i trust and i have no mobile phone more than 5 years, i am using only my laptop, that's the second time is happening to me, in a middle of a call element decide to update itself and then all my security modules, hips, firewalls, jump up so many permission requests wile i hear a call ring when someone is calling me, and then i reject the call, and i start to click on intrusion prevention requests, firewall requests, and so on, and its take me more than 2 minutes to permit it to again, at the first time it was fine,

but now at the last time when it was my father who is calling me in an emergency, i did told my father element is the best app and i did installed it on his android phone so he can reach me, he did ask me if its reliable of i didn't hesitate to tell him of course you can reach me anytime with it,

then he came home said "you and your stupid apps, when i need you all your stupid apps don't works"

we little bit got into fight and i did find myself explain to a 72 years old man who don't know nothing about firewalls, that i had some issues and i needed to click and bla bla, he said i don't care your stupid apps anymore,

any program in the world are always installed on some very regular and firm path, no version number should be included on the path, its not come to sense,

when you install lets say comodo antivirus it will go to programfiles/comodo, not programfiles/comodo_ver1.0.2

the same with element, it need to update it self first after a user confirmation, it will pop up a message something like:

"an updates are ready to be installed for element desktop, do you like them to be installed now? or click postpone for later"

and the path need to be just : "C:\Users\user\AppData\Local\element\", without version,

i hope guys you will take it very seriously and will fix it as soon as you can,

thank you!

### What happened?

.

### Operating system

Windows 10 x64

### Application version

element 1.8.2

### How did you install the app?

desktop installer

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment] 2021-09-08 14:13
This is simply how the default Squirrel.Windows installer for Electron functions.

Duplicate of https://github.com/vector-im/element-web/issues/15973

**Closed by t3chguy** 2021-09-08 14:13 UTC
Labels: T-Defect

**Comment by eetsceeck1** [comment] 2021-09-08 14:48
thank you for the reply, though its not a solution for a professionals to claim that, but if that is the case i will need to probably to block update IP's to prevent auto update, i will try also to to convert element into portable state, if it will be unsuccessful, i will have no choice move to another app, i have many security softwares installed on my machine, spyshelter, comodo, simplefirewall, OSarmor, my own security modules which i developed myself, which i need to configure them all everytime, 
moreover, i just checked all the other versions folders what being left on my appdata, they are all taking capacity about 250mb each i never been noticed this, i have already 3 gb in use by left over element folders which during time will blot unnecessary capacitance, this issue have to be taken very seriously instead to be closed with such claim, there is always solution

**Comment by eetsceeck1** [comment] 2021-09-10 14:15
i have found solution for this, element act as portable without any dependencies on the system which is great, i was hoping from the first place it will be the case, 
now i just did create a folder somewhere desired on the system with it, and i did blocked the updates ip's, no need them so often, 
after a while i will check if there is any new version by myself, 

in that case i think you don't need to use "Squirrel", you can provide it as portable compressed file or something, it will have the same effect as it is with the installer just better, 

i am sorry i didn't knew that someone already did complaint about it before on another thread, i am not a pro in searching on github archives, 

anyway i hope it will provide an idea or concept to fix this.
thanks
