### ISSUE TITLE
Badge for unread count on element-desktop doesn't appear

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#15967] opened 2020-12-14 22:01 UTC
Placeholder for reports from customer about notification badge not appearing in element-desktop. More info to come.

**Comment by xobs** [comment] 2021-01-29 12:20
Related: https://github.com/vector-im/element-web/issues/14033

**Comment by t3chguy** [comment] 2021-02-01 12:42
Duplicate of #14033

**Closed by t3chguy** 2021-02-01 12:42 UTC
Labels: bug, type:electron, type:notifications
