### ISSUE TITLE
Unable to decrypt message /_matrix/client/v3/room_keys/keys 404 Not Found

### ISSUE THREAD

**Issue by matutter** [vector-im/element-web#24972] opened 2023-03-28 16:49 UTC
### Homeserver & Element setup

- I have a private Synapse server that is not federated.
- Synapse `v1.80.0`, Element `v1.11.26`.
- I have 2 users, `tester1` and `tester2`.
- Synapse is configured to use OpenIDConnect for login.
- Everything described below also occurs on the desktop version (`1.11.25`)
- Both browser were used incognito mode for this test - however I've also received the exact same outcome without incognito mode.

### Steps

1. `tester1` logs in & sets a passphrase for backup.
2. `tester2` logs in & sets a passphrase for backup.
3. Both users are in an room with E2E enabled.
4. Both users send a message.
5. Both users receive a message that is decrypted.
6. `tester1` logs out.
7. `tester2` sends a message.
8. `tester1` logs in & clicks "Verify with Security Key or Phrase", uses a phrase, is prompted with "device verified".
9. `tester1` sees `Unable to decrypt message` in place of `tester2`'s message. A banner at the top of the windows displays the message 
  > **Some messages could not be decrypted**
  > Unfortunately, there are no other verified devices to request decryption keys from. Signing in and verifying other devices may help avoid this situation in the future.
  
  
### Logs & Configs

- Log from browser console: [rageshake.log](https://github.com/vector-im/element-web/files/11092183/rageshake.log)
- Element config.json: [element-config.json](https://github.com/vector-im/element-web/files/11092206/element-config.json.txt)
- Homeserver.yaml: [homeserver.yml.txt](https://github.com/vector-im/element-web/files/11092230/homeserver.yml.txt)
- I think I have rageshake disabled `/rageshake` does nothing in our element-web instance.
- The traefik labels for the Synapse container:
```
      traefik.enable: 'true'
      traefik.http.routers.matrix.entrypoints: websecure
      traefik.http.routers.matrix.rule: Host(`chat.test.lab`) && PathPrefix(`/_matrix/`,
        `/_synapse/`, `/.well-known/`)
      traefik.http.routers.matrix.service: matrix-svc
      traefik.http.routers.matrix.tls: 'true'
      traefik.http.routers.matrix.tls.certresolver: acme
      traefik.http.routers.matrix.tls.domains[0].main: chat.test.lab
      traefik.http.services.matrix-svc.loadbalancer.server.port: '8008'
```
- The traefik labels for the Element-web container:
```
      traefik.enable: 'true'
      traefik.http.middlewares.element-headers.headers.accessControlAllowCredentials: 'true'
      traefik.http.middlewares.element-headers.headers.accessControlAllowHeaders: '*'
      traefik.http.middlewares.element-headers.headers.accessControlAllowMethods: '*'
      traefik.http.middlewares.element-headers.headers.accessControlAllowOriginList: https://chat.test.lab
      traefik.http.middlewares.element-headers.headers.accessControlMaxAge: '12'
      traefik.http.middlewares.element-headers.headers.addVaryHeader: 'true'
      traefik.http.routers.element.entrypoints: websecure
      traefik.http.routers.element.middlewares: element-headers
      traefik.http.routers.element.rule: Host(`chat.test.lab`)
      traefik.http.routers.element.service: element-svc
      traefik.http.routers.element.tls: 'true'
      traefik.http.routers.element.tls.certresolver: acme
      traefik.http.routers.element.tls.domains[0].main: chat.test.lab
      traefik.http.services.element-svc.loadbalancer.server.port: '80'
```

#### What did you expect?

Logged out users to be able to decrypt messages after they are logged in.

#### What happened instead?

Messages sent while a user are logged out cannot be decrypted by the user after sign-in.

In the scenario above, if `tester2` exports their E2E room keys, sends it to `tester1`, then `tester1` imports the E2E room keys - `tester1` can now read the encrypted messages.

### Operating system

Ubuntu 22.04

### Browser information

Firefox 110.0.1 (64-bit), Google Chrome Version 110.0.5481.96 (Official Build) (64-bit)

### URL for webapp

Element web v1.11.26

### Application version

version: 1.11.26 Olm version: 3.2.12

### Homeserver

Synapse v1.80.0

### Will you send logs?

Yes

**Comment by andybalaam** [comment] 2023-04-03 10:24
I think this is a duplicate of https://github.com/vector-im/element-web/issues/23381 - please re-open if not.

**Comment by andybalaam** [comment] 2023-04-03 10:24
Duplicate of https://github.com/vector-im/element-web/issues/23381

**Closed by andybalaam** 2023-04-03 10:24 UTC
Labels: T-Defect
