### ISSUE TITLE
Layout shift on expanded space sidebar hover

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#20906] opened 2022-02-04 09:22 UTC
### Steps to reproduce

https://user-images.githubusercontent.com/769871/152504020-39b4adc5-dc36-4501-92ba-28ff0c5ca645.mov

#### What did you expect?

No layout shift

### Operating system

macOs

### URL for webapp

Element Nightly

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-02-04 10:13
Duplicate of https://github.com/vector-im/element-web/issues/19891

**Closed by t3chguy** 2022-02-04 10:13 UTC
Labels: T-Defect, S-Tolerable, A-Spaces, O-Occasional
