### ISSUE TITLE
Drafts of new messages are discarded when switching rooms

### ISSUE THREAD

**Issue by thibaultamartin** [vector-im/element-web#23737] opened 2022-11-09 08:56 UTC
### Steps to reproduce

1. Create a new DM with someone
2. Start drafting your first message
3. Switch to another room (accidentally or not. For me I hit `option` + `down arrow` accidentally, when trying to move cursor one word backward with `option` + `left arrow`)
4. Your draft disappeared and you need to start over

This can be particularly frustrating when you have been working on a quite long draft before sending your first message because [you're following the nohello policy](https://nohello.net/en/) and creates a feeling of distrust towards the app.

#### What did you expect?

I expected to be able to get back to my draft after switching rooms accidentally.

#### What happened instead?

My draft disappeared and I was very sad.

### Operating system

macOS

### Application version

Element Nightly version: 2022110801, Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started#nightly

### Homeserver

Synapse 1.70.1

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-11-09 08:57
Is this with the new rich text editor?

**Comment by t3chguy** [comment] 2022-11-09 09:00
Duplicate of https://github.com/vector-im/element-web/issues/23196

**Closed by t3chguy** 2022-11-09 09:00 UTC
Labels: T-Defect, X-Needs-Info
