### ISSUE TITLE
Highlight keywords in a pill

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#13964] opened 2020-06-09 08:49 UTC
https://www.figma.com/file/M15i7l4PSPY1B5M7Zhu80H/Notifications?node-id=547%3A3122

![](https://user-images.githubusercontent.com/558581/122311328-8e8fa080-ced7-11eb-8493-cc4097f3d606.png)

**Comment by MadLittleMods** [comment] 2021-06-17 00:25
Closing as duplicate of https://github.com/vector-im/element-web/issues/8821

**Closed** 2021-06-17 00:25 UTC
Labels: A-Pills, T-Enhancement, Z-FTUE-Notifications
