### ISSUE TITLE
On bad connectivity, trying to upload a file will block. On cancelling the upload, the modal still appears (minutes later)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#22998] opened 2022-08-04 17:03 UTC
### Steps to reproduce

1. Simulate a bad network
2. In an e2ee room send some normal messages, which will probably stack up as we try to do e2ee with the server
3. Send an image
4. Watch an infinite fullscreen modal spinner; the thumbnail doesn't even appear (which is weird, as it shouldn't need to talk to the server to calculate a thumbnail)
5. Click in the background of the modal to cancel it
6. Move on with your life
7. Be very confused when ~30s later the thumbnail upload still suddenly pops up... even if you're now in an entirely different room.

#### What did you expect?

You should be able to queue up images to be sent even when on bad connectivity.  They certainly shouldn't pop up unexpectedly later.

#### What happened instead?

Much flakiness.

### Operating system

macOS 12.3.1 on M1

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by turt2live** [comment] 2022-10-31 20:05
> (which is weird, as it shouldn't need to talk to the server to calculate a thumbnail)

This sounds like it might be the `/media/config` request or possibly it trying to encrypt before determining size/thumbnail/whatever

**Comment by t3chguy** [comment] 2022-11-01 08:59
That is exactly what it is, it only happens once per session

**Comment by ara4n** [comment] 2023-05-07 16:26
(related: https://github.com/vector-im/element-web/issues/7069)

**Comment by t3chguy** [comment] 2023-05-09 08:18
Duplicate of https://github.com/vector-im/element-web/issues/24667

**Closed by t3chguy** 2023-05-09 08:18 UTC
Labels: T-Defect, S-Minor, A-Media, O-Uncommon

**Comment by gaelledel** [comment] 2023-12-18 15:37
We should use the Retry banner that appears above the composer when sending fails. 
This currently works for messages that failed to send. We should therefore display the same banner for anything else including photos, videos, attachments etc...
As a second phase, we will probably modify this and adopt the same behaviour/style as EX. This will come with the timeline rework using Compound.
