### ISSUE TITLE
After clearing the cache a upgraded room isn't in the space anymore

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#21685] opened 2022-04-05 14:08 UTC
### Steps to reproduce

Yesterday i had to clear the cache because of a sticky message.
After this i can only see the old room of #datenschutzraum:matrix.org in the #privacy-space-de:matrix.org space
The new one is only listed in "other rooms"
when i leave the old room, the #datenschutzraum:matrix.org isn't visible in the #privacy-space-de:matrix.org space anymore.
If i join the room #datenschutzraum:matrix.org via the #privacy-space-de:matrix.org space i only get to the old room

I leave the new and old #datenschutzraum:matrix.org.

When i join #datenschutzraum:matrix.org it didn't appear in privacy-space-de:matrix.org

When i join #datenschutzraum:matrix.org via the space, i only get into the old room.

To be clear: Before i cleared the cache, i got access to the upgraded room via the space!

If you need any logs or videos about this you can ask me.

#### What did you expect?
That the upgraded room is in the space

i testet it with another room.
I created a room in a space and upgraded it => the upgraded room is in the space.

#### What happened instead?
Only the old room is in the space.

### Operating system

Ubuntu Mate 20.04

### Application version

Version von Element: 1.10.8 Version von Olm: 3.2.8

### How did you install the app?

package source from element.io (not flatpak!)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by MadLittleMods** [comment] 2022-05-10 19:27
Duplicate of https://github.com/vector-im/element-web/issues/21225

**Closed by MadLittleMods** 2022-05-10 19:27 UTC
Labels: T-Defect, S-Major, A-Spaces, A-Room-Upgrades, X-Needs-Investigation
