### ISSUE TITLE
Something went wrong error when attempting to join a room in a space

### ISSUE THREAD

**Issue by MURBASLMS** [vector-im/element-web#22956] opened 2022-07-28 23:07 UTC
### Steps to reproduce

Was invited to a space, joined ok
list of rooms in there, clicked join
something went wrong message appeared
clear cache and reload worked

### Outcome

when clicking join a room in a space would expect to just join.

### Operating system

OSX 10.15.7

### Application version

1.11.1

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-07-29 08:30
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-07-29 08:30 UTC
Labels: T-Defect, S-Major, O-Uncommon
