### ISSUE TITLE
Add push notifications when voice/video conferences start/stop

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1989] opened 2016-08-20 17:38 UTC
We should get something to push notifications when voice/video conferences start/stop.

**Comment by ara4n** [comment] 2016-08-26 23:00
Context: i missed a VC in HQ that I wanted to participate in because nothing sent me a push notif to tell me it was happening!

**Comment by SimonBrandner** [comment] 2021-12-05 07:33
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/18709

**Closed by SimonBrandner** 2021-12-05 07:33 UTC
Labels: S-Minor, T-Enhancement, A-Jitsi, O-Occasional
