### ISSUE TITLE
Add timestamp to /me status messages

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#16436] opened 2021-02-11 20:43 UTC
**Is your suggestion related to a problem? Please describe.**

Add timestamp to `/me` status messages like other messages already have (time below the avatar).

**Additional context**

Currently, `/me` status messages look like the following and it's not possible to tell when they are sent.

![](https://user-images.githubusercontent.com/558581/107696359-7680e980-6c77-11eb-9aab-14d5d00752c9.png)

**Workaround**

On the message -> View source -> `origin_server_ts` but it's still in a unix epoch timestamp format which isn't human readable.

**Comment by t3chguy** [comment] 2021-02-11 20:51
They have one, its just behind the avatar. If the emote isn't the first in a continuation then it'll be visible

**Comment by t3chguy** [comment] 2021-02-11 20:52
Duplicate of https://github.com/vector-im/element-web/issues/2284

**Closed by t3chguy** 2021-02-11 20:52 UTC
Labels: suggestion, type:timeline, ui/ux

**Comment by MadLittleMods** [comment] 2021-02-11 20:53
Thanks @t3chguy 👍
