### ISSUE TITLE
No way to join a known community from the UI

### ISSUE THREAD

**Issue by Cadair** [vector-im/element-web#6501] opened 2018-04-12 08:25 UTC
Say I have a secret society, and we have a matrix community, I have told my very secret friends that it's +ssshhhhhh:matrix.org, the only way for them to join it without typing it into a chat is to manually put it in the URL (which dosen't work for the desktop client)

**Comment by turt2live** [comment] 2018-04-12 16:31
Related: #5364

**Comment by lampholder** [comment] 2018-04-16 09:16
An obviously desirable feature - p3 only because we're not committed to working on it right now.

**Comment by ara4n** [comment] 2018-04-16 12:25
as discussed, can we use priority to reflect the 'platonic ideal priority' - i.e. how important this is to us, rather than somehow trying to reflect the actual scheduling?  It's more important to know what things we consider important and would try to schedule first (if we had infinite manpower) than losing any importance metadata in the tagging on the bug and trying to reflect "when we would work on it"

**Comment by SimonBrandner** [comment] 2021-06-22 10:27
Duplicate of https://github.com/vector-im/element-web/issues/17264

**Closed by SimonBrandner** 2021-06-22 10:27 UTC
Labels: A-Spaces, P3, T-Enhancement
