### ISSUE TITLE
No audio device detect

### ISSUE THREAD

**Issue by pomaskin** [vector-im/element-web#16717] opened 2021-03-18 15:44 UTC
![image-2021-03-04-11-42-11-679](https://user-images.githubusercontent.com/5239755/111654176-92008680-8819-11eb-9f97-02558ed753cc.png)

### Description

No Audio Outputs detected.
No Microphones detected.

### Steps to reproduce

- Run Element via Citrix XA

### Version information

- **Platform**: desktop
- **OS**: Windows
- **Version**: 1.7.22 and 1.7.23

Version 1.7.21 not affected.

**Comment by pomaskin** [comment] 2021-03-18 15:46
Version **1.7.21** on same Citrix XA:

![image-2021-0](https://user-images.githubusercontent.com/5239755/111654775-1d7a1780-881a-11eb-8e16-3126a5455630.png)

**Comment by dbkr** [comment] 2021-03-18 16:21
I'm not sure any of us have a Citrix environment to test this against: I can't reproduce it on plain Windows. Anyone?

**Comment by pomaskin** [comment] 2021-03-18 16:30
I noticed something. After clicking on the "Voice & Video" menu item, the message "No media permissions" appears for a moment and then disappears.
![PERM image-2021-03-04-11-44-12-879](https://user-images.githubusercontent.com/5239755/111661800-6765fc00-8820-11eb-8c68-740c0dc8ccec.png)

**Comment by dbkr** [comment] 2021-03-18 16:46
OK - looks like it's getting an error listing the media devices then. Unfortunately we don't log this error: I've submitted https://github.com/matrix-org/matrix-react-sdk/pull/5771 to log it so we can see what the error is.

Could be permission error of some kind - each new version of element is a new binary (because of how the auto update works) so check if there's a rule to allow element access to audio devices somewhere, and if so, if it's pointing to a specific version's binary.

Otherwise, try submitting debug logs in the next release, or in the next day's nightly build once the PR above is merged.

**Comment by jryans** [comment] 2021-05-10 13:04
@pomaskin Has this improved in more recent releases? If not, please submit fresh debug logs since we've added new logging here.

**Comment by pomaskin** [comment] 2021-05-11 14:28
@jryans There is a problem in version 1.7.27.

**Comment by SimonBrandner** [comment] 2021-11-17 14:13
@pomaskin, are you still seing this?

**Comment by SimonBrandner** [comment] 2021-11-28 10:08
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.

**Closed by SimonBrandner** 2021-11-28 10:08 UTC
Labels: T-Defect, X-Needs-Info, Z-Platform-Specific, X-Cannot-Reproduce, A-VoIP
