### ISSUE TITLE
Can't scroll to bottom of room list

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17460] opened 2021-05-25 09:33 UTC
### Description

![image](https://user-images.githubusercontent.com/2803622/119474510-84e9a180-bd4c-11eb-99a1-3f8c866eacec.png)
This is the very bottom of my room list in home metaspace, i.e. the image's bottom border is my screen border. Rooms are in low prio section.
Upon scrolling to the bottom, it jumps back up to this position. Expand button is still clickable.

### Steps to reproduce

- unsure
- probably only happens when switching rooms and the room list things are not properly resized

Logs being sent: yes/no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021052501-1

**Comment by MadLittleMods** [comment] 2021-08-06 20:42
Looks related to https://github.com/vector-im/element-web/issues/18440

**Comment by MadLittleMods** [comment] 2021-08-09 23:17
Here is some more info and actual reproduction instructions since my issue was closed out:

> ### Steps to reproduce
> This bug depends on your viewport height compared to one of your room list sub-sections.
> 
> 1. Start with a big viewport, and have a room subsection expanded where all of it fits on screen
> 2. Resize to shrink your viewport so that it's just big enough to show the whole room subsection. Then shrink a bit more so that the headings overlap when you scroll down
> 3. Scroll to the bottom of the room list
> 4. Notice the jitter
> 
> I have reproduced this with Chrome on Windows and the Element desktop app on macOS but seems like it would happen in any environment.
> 
> I have also reproduced this with several different room sub-sections and also when switched to a space.
> 
> Related issues:
> 
> - https://github.com/vector-im/element-web/issues/17864
> - https://github.com/vector-im/element-web/issues/17460
> - https://github.com/vector-im/element-web/issues/18366
> - https://github.com/vector-im/element-web/issues/14085
> 
> ### What happened?
> The whole scrollable room list area jitters up and down as the different sticky headings jockey for position (jumpy).
> 
> https://user-images.githubusercontent.com/558581/128567603-cc95887d-05e2-45e5-b8c6-8e9c17b205cd.mp4
> ### What did you expect?
> The headings would have a steady state no matter how big the viewport is.
> 
> ### Operating system
> Windows, macOS
> 
> ### Browser information
> Chrome, Element desktop app
> 
> ### URL for webapp
> develop.element.io
>
> *-- https://github.com/vector-im/element-web/issues/18440*

**Comment by MadLittleMods** [comment] 2021-08-09 23:20
@robintown I think I am actually going to close this around the other way which has more detail even though this is an older bug report.

**Closed** 2021-09-14 19:40 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Room-List, O-Frequent
