### ISSUE TITLE
explore rooms no longer works for public spaces

### ISSUE THREAD

**Issue by tschreier** [vector-im/element-web#24065] opened 2022-12-20 14:53 UTC
### Steps to reproduce

It looks like the search is no longer finding public spaces. In version 1.11.14 this problem did not occur and it also affects the desktop version.
The problem seems to be the request payload. room_types contains only the value [null]. If the request is executed without room_types or with room_types: [null,'m.space'], the response contains the expected result.

![image](https://user-images.githubusercontent.com/1712585/208685805-f99a9847-8633-46f7-9d58-38737323bfa4.png)
![image](https://user-images.githubusercontent.com/1712585/208685850-ea61e31c-6360-441a-b0f5-f8938785da53.png)
![image](https://user-images.githubusercontent.com/1712585/208685881-5f11647b-2fbf-4806-b660-058eef406025.png)
![image](https://user-images.githubusercontent.com/1712585/208686001-1fa88306-d728-4257-a519-979049de20ea.png)
![image](https://user-images.githubusercontent.com/1712585/208695259-523d3550-00c5-4371-9927-eb1198b3ba2a.png)
![image](https://user-images.githubusercontent.com/1712585/208695304-d9001175-ed09-4c76-8646-1c32daf7c054.png)

#### What did you expect?
I expect to find public spaces through search

#### What happened instead?
nothing ;-)

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-12-20 14:56
Duplicate of https://github.com/vector-im/element-web/issues/24064

**Closed by t3chguy** 2022-12-20 14:56 UTC
Labels: T-Defect

**Comment by tschreier** [comment] 2023-01-13 08:57
Unfortunately, switching on the labs flag does not work in our self-hosted environment.
It works only when setting "feature_exploring_public_spaces" default: true in the matrix-react-sdk (settings.tsx).
![image](https://user-images.githubusercontent.com/1712585/212278837-54129e69-a174-473f-aa7b-e0860ea9ef5d.png)
Then the space search is available in the search dialogue.
Because of this change in the sdk, all desktop clients must be rebuilt.
Unfortunately, this means a lot of work and leads to an error. https://github.com/vector-im/element-web/issues/24207
From my point of view, the problem could easily be solved by setting the default value in the sdk to true.
Do I see this correctly?
Would that be possible?
Is there another way to activate the space search, **which is very, very important for us**?

**Comment by t3chguy** [comment] 2023-01-13 09:11
> Unfortunately, switching on the labs flag does not work in our self-hosted environment.

You can enable it in config.json.

https://github.com/vector-im/element-web/blob/develop/docs/config.md

**Comment by tschreier** [comment] 2023-01-13 10:28
Shame on me!
I thought lab flags are only activated via the key "features" and have not perceived that with the key "settings_defaults" the default values from Settings.tsx can be overwritten.  That was a hard long way to the realization, but I learned a lot ;-)
Michael, many, many thanks. You have saved me!

**Comment by tschreier** [comment] 2023-01-13 10:49
;-(
it works well in element-web **_but the settings have no impact on element-desktop_** ...
![image](https://user-images.githubusercontent.com/1712585/212302162-782e22eb-8d27-41a4-8d79-9a2118490031.png)

**Comment by t3chguy** [comment] 2023-01-13 10:49
@tschreier Element Desktop embeds its own Element Web, so you'd need to modify its own config.json - https://github.com/vector-im/element-desktop/#user-specified-configjson

**Comment by tschreier** [comment] 2023-01-13 11:01
@t3chguy 
I know the document.
If I understand it correctly, each user has to do it individually?
(We have potentially thousands of users and no opportunity of a central roll out...)

**Comment by t3chguy** [comment] 2023-01-13 11:02
Then I suggest packaging your own instance of Element Desktop containing the build config options you desire

**Comment by tschreier** [comment] 2023-01-13 11:09
ok, that sounds good (the second best solution ;-) )
Is it foreseeable when the feature will be in the standard?
Again, thank you very much for your help!

**Comment by t3chguy** [comment] 2023-01-13 11:10
Yeah hopefully it won't take long now, there's some internal team reshuffling happening right now which might unlock resources to put this back on the agenda

**Comment by tschreier** [comment] 2023-01-20 16:10
I would enable the checkbox by default but I can't find that option in the element settings.
Am I missing something?
Your screen shot looks like there is this possibility.
https://github.com/vector-im/element-web/issues/24064
![image](https://user-images.githubusercontent.com/1712585/213747218-d9ea0da6-8bbd-4696-acd1-8395bf93ec40.png)
