### ISSUE TITLE
Space Sidebar acts weirdly on hover (when all subspaces are collapsed)

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#21826] opened 2022-04-16 15:23 UTC
### Steps to reproduce

1. Find/make a space with a long name
2. Open the sidebar by expanding subspaces
3. Collapse subspaces
4. Mouse over space with long name
5. Observe

#### What did you expect?

No CSS jitter

#### What happened instead?

https://user-images.githubusercontent.com/22740616/163680710-01ae7df9-b6a7-43cc-946a-b60efac76665.mp4

### Operating system

PopOS 21.10

### Application version

Element version: 1.10.9 Olm version: 3.2.8

### How did you install the app?

Flatpak

### Homeserver

jboi.nl

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-16 23:22
Duplicate of https://github.com/vector-im/element-web/issues/19891, which is now fixed on develop

**Closed by robintown** 2022-04-16 23:22 UTC
Labels: T-Defect, S-Minor, A-Spaces, O-Uncommon
