### ISSUE TITLE
Unable to decrypt messages sometimes after restoring from backup on a new login

### ISSUE THREAD

**Issue by tx1683** [vector-im/element-web#10577] opened 2019-08-16 11:25 UTC
### Description

After logging to matrix account, and then logging to backup sometimes messages cannot be decrypted. Reported by few colleagues. 

### Steps to reproduce

- Log in
- Connect to backup
- Send message in encrypted channel
- Log out/close tab in private mode
- Log in
- Connect to backup
- Sometimes messages can be decrypted, and sometimes can't, even recent ones

After connecting to backup, all keys necessary to decrypt received messages should be on server, and all messages should be decryptable.

### Version information

- **Platform**: web
- **Browser**: Firefox 60.8.0esr and Firefox 68.0.1
- **OS**: Debian 9 and Mint 19.2
- **URL**: riot.junta.pl 1.3.2 (but reported also in earlier versions)

**Comment by turt2live** [comment] 2019-08-16 14:45
Closing as a duplicate of https://github.com/vector-im/riot-web/issues/10578 due to private mode use.

**Comment by tx1683** [comment] 2019-08-16 21:08
@turt2live I wasn't clear in the description. This problem appears in normal mode as well as in private mode, even on new, empty Firefox profile. That was my reason to create separate issues. I am asking you to reconsider your decision to close that issue.

**Comment by turt2live** [comment] 2019-08-16 21:33
@tx1683 logs would really help us in identifying what might be going wrong here. Before closing the session, please submit logs referencing this issue and then when starting the next session please submit logs again.

To submit logs, go to your user settings in the top left of the app and click the "Send Debug Logs" button on the Help tab.

**Comment by jryans** [comment] 2019-09-04 12:12
As Travis says, please submit debug logs for this. There's not much we can do to help without them for this kind of problem.

**Comment by richvdh** [comment] 2023-08-30 10:03
We haven't received debug logs, so closing

**Closed by richvdh** 2023-08-30 10:03 UTC
Labels: T-Defect, X-Needs-Info, A-E2EE, A-E2EE-Key-Backup, A-Storage, Z-UISI
