### ISSUE TITLE
Chrome can misrecognise the username field at registration as an email address and autofill, causing confusion

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#741] opened 2016-01-22 20:09 UTC
I've heard one report of Chrome autofilling the username field at registration with an email address, causing confusion.

**Comment by richvdh** [comment] 2017-01-06 11:21
Should probably apply matrix-org/matrix-react-sdk#520 to the registration form

**Comment by kittykat** [comment] 2021-09-24 07:33
Closing as it should have been fixes by the PR above and I cannot reproduce the issue.

**Closed by kittykat** 2021-09-24 07:33 UTC
Labels: T-Defect, P3, A-Registration, Z-FTUE, A11y
