### ISSUE TITLE
Trying to upload a large profile picture can cause stalls/crashes

### ISSUE THREAD

**Issue by SethFalco** [vector-im/element-web#11479] opened 2019-11-22 21:52 UTC
### Description

If you upload a large file, Riot stalls, and sometimes crashes.
I have tried using a 3.8GB `mkv` file which causes a crash. And a 1.2GB image file which freezes the application for a while, and eventually responds again with the profile picture not appearing.

### Steps to reproduce

- Open Account Settings
- Select a large image (or non-image file)

For non image files it simply shouldn't accept it, however for large image files I would expect either a clear file size limit such as 1024KB or 8MB, and for the application to not stop responding during the uploading of the image.

Logs being sent: yes

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Ubuntu 18.04
- **Version**: 1.5.3

**Comment by jph168** [comment] 2019-11-22 22:09
In general their is a 100mb limit, common sense is expected..repeat of Issue #11478, I would recommend closing this and that one.

**Comment by SethX3** [comment] 2019-11-22 23:47
I don't think common sense justifies this behaviour when it can be programatically handled, for example from the Discord UI, `Image` is the only File Explorer filter available, if I have a large (1.8GB png) it does force Discord to restart which is not ideal but it's better than just not-responding  or becoming a white window.

I could concede this is a low priority, however it's certainly unexpected behaviour that should be addressed.

**Comment by jph168** [comment] 2019-11-23 00:44
That behavior I do understand should be addressed. Being able to select other file formats upon selecting all files is not really a problem in my op since most applications restrict formats to the point of having to convert files in order to be readable.

**Comment by 532910** [comment] 2020-07-04 17:05
Riot-electron hangs with white screen trying to send the same 200Mb H264 video file, while riot-web in ff works fine.

**Comment by turt2live** [comment] 2022-06-14 04:34
Duplicate of https://github.com/vector-im/element-web/issues/4264

**Closed by turt2live** 2022-06-14 04:34 UTC
Labels: T-Defect, S-Tolerable, A-File-Upload, A-Avatar, O-Uncommon
