### ISSUE TITLE
Sometimes markdown doesn't work for sending

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20540] opened 2022-01-13 17:10 UTC
I haven't figured out what causes it yet, but sometimes italics and bolding go through as literals, despite other formatting being applied safely. More confusingly, the symbols sometimes change from asterisks to underscores, indicating that the markdown is recognized but just doesn't get rendered properly

**Comment by t3chguy** [comment] 2022-01-14 09:54
Related https://github.com/vector-im/element-web/issues/20091

**Comment by rda0** [comment] 2022-02-08 08:41
It also tends to eat whitespaces before links

**Comment by robintown** [comment] 2022-03-04 22:13
Duplicate of https://github.com/vector-im/element-web/issues/20091

**Closed by robintown** 2022-03-04 22:13 UTC
Labels: T-Defect, S-Minor, A-Composer, O-Uncommon
