### ISSUE TITLE
Clicking the 'Direct message' link in the memberinfo panel to create a DM (with a user with whom you don't already have a DM) gives no feedback and is not debounced...

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#12848] opened 2020-03-24 17:43 UTC
...leading to a legion of invites:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1922197/77458960-e172c900-6df6-11ea-8aaf-d511ed213662.png">
![image](https://user-images.githubusercontent.com/1922197/77458899-cf912600-6df6-11ea-8e37-8afddd8a7587.png)

Pls add some feedback and some debouncing 👍

**Comment by jryans** [comment] 2020-03-26 10:45
Thanks for filing! 😁 I'll track this for post-release cross-signing work.

**Comment by lampholder** [comment] 2020-06-17 14:13
It bit me again! I am not a patient man and all my new friends end up with a million DMs by way of introductiong!

**Comment by t3chguy** [comment] 2020-06-17 14:14
So you're the invite spammer in the wild!

**Comment by kittykat** [comment] 2021-12-09 18:24
I'm going to close this issue for now as we cannot reproduce it. Please open a new issue if you are still experiencing the problem.

**Closed by kittykat** 2021-12-09 18:24 UTC
Labels: T-Defect, P1, A-User-Info, A-E2EE-Cross-Signing, X-Needs-Community-Testing

**Comment by t3chguy** [comment] 2021-12-10 09:24
It is still reproducible, but a duplicate of https://github.com/vector-im/element-web/issues/7763 anyhow
