### ISSUE TITLE
Sign out button not working on app.element.io

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17217] opened 2021-05-09 17:10 UTC

**Comment by ara4n** [comment] 2021-05-09 17:11
https://user-images.githubusercontent.com/1294269/117580877-ed504600-b0f1-11eb-875b-96816c172109.mov

**Comment by ara4n** [comment] 2021-05-09 17:11
(nothing in the console)

**Comment by jryans** [comment] 2021-05-10 12:28
Hmm, working fine here... 😕

**Comment by HarHarLinks** [comment] 2021-06-08 10:29
I just had a similar experience on develop.element.io:
- signed in fresh to check out some develop features
- takes a few minutes for element to sync my session
- xsign
- fiddle around for a couple minutes
- sign out
- nothing
- after a minute the sign out confirmation dialogue finally appeared and let me sign out
- since i had mashed the sign out button a dozen more times, also more of the dialogues

**Comment by t3chguy** [comment] 2023-07-13 13:31
Duplicate of https://github.com/vector-im/element-web/issues/9319

**Closed by t3chguy** 2023-07-13 13:31 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, A-Logout
