### ISSUE TITLE
Two notifications show up when you get pinged, rather than one like you would expect. (Element Nightly)

### ISSUE THREAD

**Issue by ArrayBolt3** [vector-im/element-web#24088] opened 2022-12-22 06:06 UTC
### Steps to reproduce

1. Ask for someone to ping you.
2. Minimize the Element Desktop window.
3. Wait for them to ping you.

#### What did you expect?
A single notification should pop up.

#### What happened instead?
Two notifications pop up, one from the message coming into the room as usual, and one from being pinged. The two notifications are identical.

### Operating system

Lubuntu 23.04 Alpha

### Application version

Element Nightly version: 2022122101 Olm version: 3.2.12

### How did you install the app?

From the element.io apt repository

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ArrayBolt3** [comment] 2022-12-22 06:15
Note that I don't think this used to happen - I believe it happened just after the last update. (I might be wrong there, but I'm pretty sure this is a recent issue, at least.)

**Comment by weeman1337** [comment] 2023-01-02 07:46
Thanks for reporting the issue @ArrayBolt3  Don't have a Lubuntu 23.04 but cannot reproduce on latest Ubuntu 22.04.1 LTS. Can you send a screenshot of your notification settings?

**Comment by t3chguy** [comment] 2023-01-03 12:21
This might a Synapse issue - https://github.com/matrix-org/synapse/issues/14539

**Comment by ArrayBolt3** [comment] 2023-01-03 14:35
@weeman1337 Screenshot of notification settings:

![image](https://user-images.githubusercontent.com/104878738/210377615-e1fa7eb5-cbf0-41c3-b2f1-ddfa06c1a2d1.png)

I notice it only happens in certain Matrix rooms - if I'm pinged in a Libera.Chat room, this doesn't seem to happen, but if I'm pinged in a room such as @lubuntu-devel:lubuntu.me, or a private room I'm a part of, I get the doubled notifications. One time it was even four notifications all at once.

@t3chguy That Synapse issue matches my symptoms quite well. Additionally, I noticed when using Thunderbird's Matrix client connected to my lubuntu.me homeserver, messages sent in the #lubuntu-devel:lubuntu.me room appeared doubled. So I think it's very likely that this bug is an unintentional duplicate of the one you linked to.

**Comment by t3chguy** [comment] 2023-01-03 15:02
Closing in favour of https://github.com/matrix-org/synapse/issues/14539

The Matrix spec says push rules should be evaluated against all live events, nothing about client doing any de-duplication

**Closed by t3chguy** 2023-01-03 15:02 UTC
Labels: T-Defect, X-Needs-Info
