### ISSUE TITLE
Composer should be visually separated from timeline

### ISSUE THREAD

**Issue by spantaleev** [vector-im/element-web#24188] opened 2023-01-09 10:38 UTC
#### What would you like to do?

![image](https://user-images.githubusercontent.com/388669/211289347-494de578-7dcf-4fc8-a8a9-bf203bab0e55.png)

The composer is hard to see right now, because it's not separated from the timeline in any way (no border, etc).

I've had it trip me up before, confusing me which part from a wall-of-text is part of my message and which part is part of the timeline text.

Worse yet, I've seen more elderly people around me **not see the composer at all**. The light-gray placeholder value is the only thing that makes it stand out, and it doesn't making it stand out enough, especially on bad screens (not everyone is on a high-contrast 4K screen).

#### Why would you like to do it?

So that Element would be more usable by normal people with poor screens.

#### How would you like to achieve it?

Add a border-top to the composer. Possibly make the placeholder text a little darker.

### Have you considered any alternatives?

Cinny seems to do it right:

![image](https://user-images.githubusercontent.com/388669/211289136-11db81fb-82a9-40d6-b896-7ae88400f6c3.png)

**Comment by turt2live** [comment] 2023-01-09 17:59
Duplicate of https://github.com/vector-im/element-web/issues/22072

**Closed by turt2live** 2023-01-09 17:59 UTC
Labels: T-Enhancement
