### ISSUE TITLE
Video call takes a long time to start

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20750] opened 2022-01-25 17:30 UTC
### Steps to reproduce

1. Start video call on Nightly (user1)
2. Accept call (from staging, user2)

#### What did you expect?
Ringing stops as soon as I accept call from staging (user2) and at least audio starts promptly

#### What happened instead?
Call takes 5+ seconds to start after the view changes and the ringtone keeps going even when video shows call as started

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022012401 Olm version: 3.2.8

### How did you install the app?

aur package

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-01-25 19:17
So it takes time for the call to connect? Is there any chance this is caused by the fact the room is encrypted and it takes time to encrypt the signalling messages before they're sent and received by the other side?

**Comment by SimonBrandner** [comment] 2022-02-12 10:44
@kittykat ping

**Comment by kittykat** [comment] 2022-02-18 12:08
I was experiencing this on develop yesterday. I don't think it was related to encryption as at lunch time the call was ringing for a long time (minutes) and same room in the evening when I went back to try and get useful reproduction steps, the call stopped ringing at the right time on one test run and 1 or 2 rings late on the next test run.

**Comment by turt2live** [comment] 2022-06-14 04:44
Rageshake logs appear to show this is related to encryption being slow.

Duplicate of https://github.com/vector-im/element-web/issues/18561

**Closed by turt2live** 2022-06-14 04:44 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-VoIP, O-Occasional, Z-Community-Testing
