### ISSUE TITLE
Many rooms appear as unread with lots of notifications after starting the desktop app on a spare computer again after long time

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-web#26649] opened 2023-11-26 20:15 UTC
### Steps to reproduce

1. Start desktop app

#### What did you expect?
Notifications and unread state in sync with other desktop app that is in daily use

#### What happened instead?
Fairly out of sync state with large number of notification counts shown. The system seems to be leading still, as there are also many UTDs that are only resolved over time. Notifications keep going up while I watch this.

### Operating system

Windows 11

### Application version

Element version: 1.11.50 Crypto version: Olm 3.2.15

### How did you install the app?

element.io

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-11-27 08:04
Thank you for reporting the issue @kongo09 . I would say this is a duplicate of #25479 or part of the [stuck notification epic](https://github.com/vector-im/element-web/issues/24392).

If you think it isn't covered by these issues leave a comment.

**Comment by weeman1337** [comment] 2023-11-27 08:04
Duplicate of #25479

**Closed by weeman1337** 2023-11-27 08:04 UTC
Labels: T-Defect, X-Regression, S-Major, A-Notifications, O-Occasional
