### ISSUE TITLE
Recent joined room is empty on Desktop but partially available on iOS 

### ISSUE THREAD

**Issue by danibonilha** [vector-im/element-web#24724] opened 2023-03-02 15:13 UTC
### Steps to reproduce

I was added to an encrypted room with this option selected:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/20520102/222465587-65854214-6c5e-4fda-9ef1-2c86c4b5ee8b.png">

and the desktop app informs: 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/20520102/222466040-3fac538b-d931-4033-8609-6584a87c2aeb.png">

But on the iOS app I'm able to see older messages and a couple of other messages with:
`** Unable to decrypt" The sender's session has not sent us the keys for this message **`

#### What did you expect?
I expected to be able to see the older messages on both platforms
#### What happened instead?
Desktop does not show any older messages

PS: I'm not entirely sure what's the correct behavior, if the iOS shouldn't show any messages too, but I expected at least both platforms to have the same behavior 

### Operating system

macOS

### Application version

Element version: 1.11.24 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started

### Homeserver

thesis

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-03-02 15:28
Related https://github.com/vector-im/element-web/issues/22671

**Comment by richvdh** [comment] 2023-03-15 11:59
looks like a duplicate of #22671 to me

**Closed by richvdh** 2023-03-15 11:59 UTC
Labels: T-Defect, S-Major, A-E2EE, O-Frequent
