### ISSUE TITLE
Inherit permissions from space

### ISSUE THREAD

**Issue by yajo** [vector-im/element-web#25841] opened 2023-07-24 07:34 UTC
#### What would you like to do?

I'm managing a big space with around 50 rooms.

I'd like to be able to welcome a new admin or moderator.

#### Why would you like to do it?

Because it is a FLOSS space with public access and we are frequent victims of spam. Having more moderators on board will help banning those attackers.

#### How would you like to achieve it?

I'd like to be able to add the new admin or moderator to the space and have him inherit that permission level in all rooms within automatically.

### Have you considered any alternatives?

Room by room:

1. Join it, even if it's not of my own interest.
2. Invite the new user.
3. Change permissions.
4. Leave room.

### Additional context

The same problem applies if I need to change some settings for all rooms at once. 

It is also not intuitive that banning a user in the space doesn't ban him in all rooms within, even if they are configured for space membership.

But I guess these are different issues.

**Comment by t3chguy** [comment] 2023-07-24 07:36
Duplicate of https://github.com/vector-im/element-meta/discussions/582

**Closed by t3chguy** 2023-07-24 07:36 UTC
Labels: T-Enhancement
