### ISSUE TITLE
Voicecalls not working at all

### ISSUE THREAD

**Issue by vordenken** [vector-im/element-web#16128] opened 2021-01-12 15:57 UTC
### Description

I just downloaded element and wanted to try to use it as a replacement for another voicecalling software.
I installed the windows app, registered an account and invited a friend. This friend made an account & we now can chat with eachother. The problem is that we cannot get voicecalls to work. If I press the call button, I get the UI for the calling but my friend doesnt get any UI for accepting the call. Its the same if he is calling me. I dont get any indication that theres someone calling me. If any of us click on the "End call" button, the other one gets the message "XXXX has made a voicecall." (Translated)

If this is the wrong place for my bug report please let me know.

### Steps to reproduce

1. Call someone

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: Desktop (and iOS: Didn't get any information on my phone that I'm beeing called)

For the desktop app:

- Windows 
- Version 1.7.16

**Comment by SimonBrandner** [comment] 2021-01-12 16:15
@vordenken This is weird. This is probably a long shot, but can you make sure the app has access to your microphone/webcam. Do you hear the "beep" sound? Also, can you try it out in your browser to see what happens, [here](app.element.io/)

**Comment by vordenken** [comment] 2021-01-12 17:25
I tried it with a second account via safari on a Mac and called my first account on windows browser, this time it worked. Then I tested it with the windows desktop app instead of the browser and it also worked...
This is really weird! 
I have to tried it with my mate later but so far this doesn't make any sense to me. 

If there is anything else I can provide to get this fixed let me know. (I already uploaded the logs when I created the issue.)

**Comment by SimonBrandner** [comment] 2021-01-12 17:42
@vordenken I am not a part of the core team, so I can't take a look at the logs. That's up to someone else. Definitely try it out again later with your friend and see what happens. If this only happens with your friend, the problem is probably on his side.

Element can be a bit buggy when it comes to VoIP, but it's getting a lot of improvements currently. If you manage to get it working but it's not performing well maybe switching to a different homeserver can do some good.

**Comment by Extarys** [comment] 2021-01-14 00:55
I have been having this exact issue for over a month.

I call my friend and he get no UI notification or anything that let him answer the call. Matrix HQ room didn't have anything for me when I asked there. Discord works fine so microphone permission shouldn't be an issue.

I'll try to convince him to make more tests with me when we get the chance.

**Comment by SimonBrandner** [comment] 2021-01-14 07:48
@Extarys I've been working on something having to do with calls yesterday. I can confirm that it often takes a bunch of time before the other user gets the notification. I think switching to a different homeserver may improve the time. But I am not really sure.

**Comment by SimonBrandner** [comment] 2021-01-14 08:45
> I think switching to a different homeserver may improve the time

[It seems to be the case](https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$uZ7EdWhAu6knwLB6nZuth1VwnegDBWc02h4HbZ-MS5c?via=matrix.org&via=privacytools.io&via=mozilla.org)

**Comment by Extarys** [comment] 2021-01-14 15:49
@SimonBrandner Oh thank you for that! I've been asking from time to time to no avail. So not an element issue, it's a matrix issue - still I thought the calls where P2P and wasn't affected by the server but I don't understand everything that the server is doing so. :thinking:  (I confirmed my call settings)

I would suggest you close this issue - the good thing is now people can find the solution here :smile:

**Comment by SimonBrandner** [comment] 2021-01-14 15:52
We still don't know if it's solved for @vordenken

**Comment by jryans** [comment] 2021-01-25 17:58
Hmm, it seems the original reporter has disappeared, so I'll close this. Let's open fresh issues with logs for any new problems.

**Closed by jryans** 2021-01-25 17:58 UTC
Labels: bug
