### ISSUE TITLE
Images sent received as blurry. Must be clicked on to un-blur.

### ISSUE THREAD

**Issue by quantazelle** [vector-im/element-web#20774] opened 2022-01-26 22:16 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

Recipents of messages say that images sent inline as a direct message are blurry.

2. What do you click?

Asking user to click on each image will un-blur them.

3. More steps…

#### What did you expect?

User able to see sent images.

#### What happened instead?

User sees blurry images.

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-01-26 22:22
Duplicate of https://github.com/vector-im/element-web/issues/2769

**Closed by t3chguy** 2022-01-26 22:22 UTC
Labels: T-Defect
