### ISSUE TITLE
Riot doesn't respect the order of messages on connection loss

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#11534] opened 2019-11-27 11:39 UTC
I tried to send two messages in a room (one being a reaction to the other), but lost the connection to my homeserver while doing that. Riot ended up timing out my first message but apparently the connection came back before the second one could be timed out, so Riot sent it but waited on a manual operation from me to resend the first one, therefore breaking the ordering the messages were meant to have. A probably good way to fix this would be, on connection loss, and if sending a message times out, to time out every message after it (and generally ensure that the ordering of messages is respected).

**Comment by trs-eric** [comment] 2020-06-03 14:03
I'm experiencing low packet loss due to ISP issues and it's making riot unusable, as messages are not only slow (no fault of riot), but also out of order.

**Comment by t3chguy** [comment] 2021-07-28 12:56
Duplicate of https://github.com/vector-im/element-web/issues/6398

**Closed by t3chguy** 2021-07-28 12:56 UTC
