### ISSUE TITLE
Phone number field shown in settings even when not supported by Synapse

### ISSUE THREAD

**Issue by rettichschnidi** [vector-im/element-web#11738] opened 2019-12-29 20:05 UTC
### Description

The "Phone numbers" field in the "Settings"  screen is visible even when Synapse is not able to deal with SMS.

### Steps to reproduce

- Set up Synapse which does not do/use SMS 3pid
- Sign up to it using Riot
- Go to the user setings and try to add a phone number:
![image](https://user-images.githubusercontent.com/920644/71561995-4def5d80-2a7e-11ea-8a13-8489c6095a5e.png)
- The following error screen appears:
![image](https://user-images.githubusercontent.com/920644/71562007-6c555900-2a7e-11ea-8d48-4176aa23cc56.png)

### Version information
- **Platform**: web (in-browser)

For the web app:

- **Browser**: all
- **OS**: all
- **URL**: private, version 1.5.6

**Comment by t3chguy** [comment] 2022-10-14 18:02
Duplicate of https://github.com/vector-im/element-meta/issues/766

**Closed by t3chguy** 2022-10-14 18:02 UTC
Labels: T-Defect, A-3PIDs
