### ISSUE TITLE
Verification cancelled on Element Desktop

### ISSUE THREAD

**Issue by monochromec** [vector-im/element-web#25103] opened 2023-04-09 16:04 UTC
A verification is cancelled on the desktop side when the mobile app side already displays the green shield above the "Done" button.

**To Reproduce**
1. Initiate verification of mobile device session on Desktop (Settings->Security&Privacy->Unverified Devices)
2. Verify by either scanning the QR code or matching the emojis
3. App on mobile device already displays the green shield but desktop apps indicates "Verification Cancelled"

**Expected behavior**
Verification on mobile device concludes successfully.

**Desktop:**
 - OS: OSX 13.3.1
 - Version 1.11.28 (Desktop)

**Smartphone:**
 - Device: Sony Xperia XZ1 compact
 - OS:  Android  13
 - Version 1.5.28 

**Additional context**
Please indicate if more information is needed (such as debug logs, etc.) - more than happy to provide as required.

**Comment by t3chguy** [comment] 2023-04-13 08:35
Duplicate of https://github.com/vector-im/element-web/issues/18165

**Closed by t3chguy** 2023-04-13 08:35 UTC
