### ISSUE TITLE
Keys Backup can be setup twice

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#9510] opened 2019-04-17 12:37 UTC
I reproduced on Riot-web the issue described here: https://github.com/vector-im/riot-android/issues/2973

Indeed while setup banner is displayed on the top of an encrypted room, if I create the backup on another client, and then click on the "Start using Key Backup" button of this banner, I will create a new backup.

When clicking on "Start using Key Backup" button, a force refresh should be done

**Comment by kittykat** [comment] 2021-12-01 12:58
I'm going to close this issue for now as we cannot reproduce it. Please reopen with more info if you are still experiencing it

**Closed by kittykat** 2021-12-01 12:58 UTC
Labels: T-Defect, P1, Z-Parity-With-Android, A-E2EE-Key-Backup, X-Needs-Community-Testing
