### ISSUE TITLE
Unread marker moves back if I leave a room quickly

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#20026] opened 2021-12-03 09:55 UTC
### Steps to reproduce

1. Find a room with unread messages
2. Switch to the room, press Esc on the keyboard to mark all messages read.
3. Notice that the unread marker line disappears.
4. Quickly, switch to another room, then switch back.

#### What did you expect?

I expected the room would show no unread messages.

#### What happened instead?

The unread marker re-appeared where it originally was.

Below, I am pressing:
* Alt-DownArrow to enter the Complement room
* Esc to clear the unread marker
* Alt-UpArrow to switch to the synapse-dev room
* Alt-DownArrow to switch back to Complement
* Note the unread marker keeps re-appearing in the Complement room
![unread-not-preserved](https://user-images.githubusercontent.com/76812/144582721-f58c0680-389a-4b5c-9e12-813a158b09ec.gif)

### Operating system

Ubuntu 21.10

### Browser information

Firefox 94.0 (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 459f2f2334ff-react-390dde055a11-js-ba1b1cc6fa86 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by MadLittleMods** [comment] 2022-02-28 22:44
Seems like a duplicate of https://github.com/vector-im/element-web/issues/10873 or https://github.com/vector-im/element-web/issues/1681

**Comment by andybalaam** [comment] 2022-05-25 11:22
I am working on a fix here: https://github.com/andybalaam/matrix-react-sdk/tree/andybalaam/read-marker-doesnt-revert

**Closed** 2022-06-09 13:41 UTC
Labels: T-Defect, S-Minor, A-Timeline, A-Room-View, A-Read-Marker, O-Occasional
