### ISSUE TITLE
UX enhancement: Show additional actions for a message while holding shift

### ISSUE THREAD

**Issue by username-redacted** [vector-im/element-web#22478] opened 2022-06-08 01:51 UTC
### What would you like to do?

Allow additional actions to show up while hovering on a message in Element and holding a key (Shift), such as delete.
Similiarly how to Discord does it:

Actions while hovering over a message in Discord:
![image](https://user-images.githubusercontent.com/105281854/172487044-ccbe9915-d4b1-4477-8a39-1bf162c96b30.png)
(**Actions shown**: Add reaction, reply, create thread, more options)

Actions while hovering over a message AND holding shift in Discord:
![image](https://user-images.githubusercontent.com/105281854/172487107-419835bf-8f09-448f-a5cb-3e5cc049ef44.png)
(Actions shown: Reply, create thread, mark unread, pin message, copy link, copy message id, delete)

### Why would you like to do it?
Currently, as far as I'm aware, for example in order to delete a message, an user needs to click on options and then click on delete, if they want to delete multiple messages in succession. Implementing this would enhance the user experience.

**Comment by t3chguy** [comment] 2022-06-08 07:13
Duplicate of https://github.com/vector-im/element-web/issues/18711

**Closed by t3chguy** 2022-06-08 07:13 UTC
Labels: S-Minor, X-Needs-Product, T-Enhancement, O-Occasional
