### ISSUE TITLE
Invite to spaces behaviour is inconsistent

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18569] opened 2021-08-16 12:36 UTC
### Steps to reproduce

1. Right click on space icon in the left menu, see:
![Screenshot from 2021-08-16 13-15-51](https://user-images.githubusercontent.com/51663/129564075-02bdc1ac-652a-4c09-a0f6-75f24dc8b9d6.png)
2. Open "Invite people" and see:
![Screenshot from 2021-08-16 13-16-12](https://user-images.githubusercontent.com/51663/129564103-43bb0e3c-a061-479a-9a38-612644293ba3.png)

Try another invite method:

1. Go to Explore rooms view and open the members panel. See the greyed out button for "Invite to this space":
![Screenshot from 2021-08-16 13-16-38](https://user-images.githubusercontent.com/51663/129563992-1c57191e-1032-4f5e-a485-dc901ff6c3bf.png)

### What happened?

The two invite paths had different outcomes: the button in the "Explore rooms" view implies that I can't invite users while the menu in the left panel lets me invite using a URL.

### What did you expect?

If I don't have permission to invite users directly, I expect the invite URL window to pop up for the members list in the "Explore rooms" view.

That I couldn't invite from that view left me feeling like I didn't have permissions to invite a user at all.

Ideally, I would like to be able to drag and drop a user into the space to invite them.

### Operating system

Arch Linux

### Browser information

Chromium Version 92.0.4515.131 (Official Build)

### URL for webapp

develop.element.io

**Comment by t3chguy** [comment] 2021-08-31 12:04
Duplicate of https://github.com/vector-im/element-web/issues/17345

**Closed by t3chguy** 2021-08-31 12:04 UTC
Labels: T-Defect, S-Major, A-Spaces, O-Intermediate
