### ISSUE TITLE
Broken search in encrypted room

### ISSUE THREAD

**Issue by domestomas** [vector-im/element-web#20564] opened 2022-01-14 19:45 UTC
### Steps to reproduce

In a 1-1 encrypted room, search omits some results. I can not find any pattern in which messages can not be searched. Both users on matrix.org.

### Operating system

Linux Mint

### Application version

 Element 1.9.8 Olm 3.2.8

### How did you install the app?

official repository

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by G2G2G2G** [comment] 2022-01-14 20:30
https://github.com/vector-im/element-web/issues/19001

**Comment by SimonBrandner** [comment] 2022-01-15 07:14
@domestomas, could you please check Settings -> Security & Privacy -> Message Search? Are there any errors there?

**Comment by domestomas** [comment] 2022-01-17 16:54
Hi, there are no errors there.

**Comment by turt2live** [comment] 2022-06-14 04:49
without an error this sounds effectively like https://github.com/vector-im/element-web/issues/21535 where we are using a different search algorithm and that's causing a tripup for the user.

Closing as a duplicate of https://github.com/vector-im/element-web/issues/21535

**Closed by turt2live** 2022-06-14 04:49 UTC
Labels: T-Defect, X-Needs-Info, S-Minor, A-Timeline, A-Timeline-Search
