### ISSUE TITLE
expose public cross-signing keys to support non-interactive verification

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16826] opened 2021-03-30 13:00 UTC
If I want to publish my Matrix E2EE identity somewhere (e.g. on a keybase style system, for social proof) I don't think I have an easy way to do so currently.

**Comment by t3chguy** [comment] 2023-04-04 11:08
Duplicate of https://github.com/vector-im/element-meta/issues/1364

**Closed by t3chguy** 2023-04-04 11:08 UTC
Labels: T-Enhancement, A-E2EE-Cross-Signing
