### ISSUE TITLE
Messages in thread are out of order

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22641] opened 2022-06-24 13:24 UTC
### Steps to reproduce

1. Start a thread
2. Put your computer to sleep
3. Receive some replies to that thread overnight
4. Take your computer out of sleep and watch Element sync

#### What did you expect?

The messages in the thread should be in chronological order, as they are on Element Android.

#### What happened instead?

The 3 messages from Matthew at the top of this thread are actually supposed to follow the message at the bottom:

![Screenshot 2022-06-24 at 09-23-00 Element](https://user-images.githubusercontent.com/48614497/175544855-a3d73c44-f779-4db6-a824-81c982d2a82f.png)

### Operating system

NixOS unstable

### Browser information

Firefox 101.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 7a131fc50f09-react-18c21d77cd6c-js-58227307974a Olm version: 3.2.8

### Homeserver

Synapse 1.61.0

### Will you send logs?

Yes

**Comment by gsouquet** [comment] 2022-07-29 12:38
The proper solution to this issue is https://github.com/vector-im/element-web/issues/21877 . This will however require a level of support for homeserver that are not able to provide a thread list

**Comment by gsouquet** [comment] 2022-07-29 12:42
Duplicate of https://github.com/vector-im/element-web/issues/21799

**Comment by robintown** [comment] 2022-07-29 13:37
This issue is about the thread itself being out of order, not the thread list. Or are they actually related problems?

**Comment by daniellekirkwood** [comment] 2022-09-06 16:12
I created a rageshake and here's the screenshot

<img width="100" alt="Screenshot 2022-09-06 at 09 33 55" src="https://user-images.githubusercontent.com/89144281/188684526-4783fe8f-1be5-4418-9417-848837cfc2a7.png">

**Comment by gsouquet** [comment] 2022-09-15 06:29
Stopping the investigation of this issue at the moment as @justjanne might have found ways to improve the load experience of threads.

**Closed** 2022-10-28 11:48 UTC
Labels: T-Defect, S-Major, A-Timeline, O-Uncommon, A-Threads
