### ISSUE TITLE
Returning to a low traffic room after the last message was sent by me and it failed to send prints the word "Today" a lot

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#18672] opened 2021-08-20 16:11 UTC
### Steps to reproduce

1. Go to a low traffic room
2. Try to send a message but it fails somehow and enters "failed message" state
3. Get COVID and don't return to your PC for 5 days
4. Return to your PC, open Element and switch to said low traffic room
5. Observe Today Today Today Today Today Today Today Today Today Today... (it keeps printing more Todays the longer you wait)
6. Delete the unsent message and flip out-and-back-in to the room to fix

![image](https://user-images.githubusercontent.com/1922197/130262416-84eaea12-9ff2-40c6-a55b-4d38774aa2d0.png)

### What happened?

The word Today appeared more times than was necessary

### What did you expect?

Only a single instance of the word Today

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2021082001 Olm version: 3.2.3

### How did you install the app?

Nightly

### Have you submitted a rageshake?

No

**Comment by ara4n** [comment] 2021-08-21 18:34
i saw this too yesterday

**Comment by Palid** [comment] 2021-08-25 15:03
Bumping the priority to O-Intermediate, I have noticed this myself too. It's not that frequent due to slightly complex reproduction steps (I'd definitely replace covid with something else though), but it becomes a lot more visible for servers with frequent reboots.

**Comment by novocaine** [comment] 2021-09-23 09:52
Is anyone able to still reproduce this recently?

**Comment by nadonomy** [comment] 2021-09-23 15:48
I haven't seen this in several weeks, was encountering it every day when I made [this comment](https://github.com/vector-im/element-web/issues/18672#issuecomment-906252014).

**Comment by novocaine** [comment] 2021-09-23 16:45
Closing, will re-open if it recurs for anyone

**Closed by novocaine** 2021-09-23 16:45 UTC
Labels: T-Defect, S-Major, A-Timeline, Z-Rageshake, O-Occasional
