### ISSUE TITLE
Can't invite federated user in a private space

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21973] opened 2022-04-28 10:15 UTC
### Steps to reproduce

1. Create a private space on matrix.org
2. Invite an EMS One account to that private space

#### What did you expect?

To have that user join my private space

#### What happened instead?

A modal says I do not have invite permissions (which is incorrect, I'm an admin). Looking in the console I can see an unrelated failure to the displayed error message that says:

```
{"errcode":"M_FORBIDDEN","error":"Profile lookup over federation is disabled on this homeserver"}
```

Fails for the following `GET` call

```
https://matrix-client.matrix.org/_matrix/client/r0/profile/[mxid]
```

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-04-28 10:24
Duplicate of https://github.com/vector-im/element-web/issues/17269

**Closed by t3chguy** 2022-04-28 10:24 UTC
Labels: T-Defect, S-Major, A-Spaces, A-Federation, A-Invite, O-Uncommon
