### ISSUE TITLE
Replying to big pictures or long messages takes up too much screen space

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16488] opened 2021-02-19 06:43 UTC
### Description

Replying to big pictures or long messages takes up too much screen space

### Steps to reproduce

- send a long message/big picture
- reply to it

Describe how what happens differs from what you expected:
have a thumbnail of the picture like suggested in https://github.com/vector-im/element-web/issues/1520 but perhaps even smaller. For text have only the beginning of the text and then 3 dots...

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop? both

For the web app:

all versions with reply

For the desktop app:

all versions with reply

**Comment by SimonBrandner** [comment] 2021-02-19 06:55
Duplicate of [#7169](https://github.com/vector-im/element-web/issues/7169)

Will be fixed by [#3553](https://github.com/matrix-org/matrix-react-sdk/pull/3553)

**Closed by SimonBrandner** 2021-02-19 06:55 UTC
Labels: bug, type:timeline, ui/ux
