### ISSUE TITLE
Messages not arriving from server

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#24201] opened 2023-01-10 10:58 UTC
### Steps to reproduce

I have develop.element.io in two different tabs, and am getting this error in one of them. Did not do anything to trigger it:

![Screenshot from 2023-01-10 10-54-22](https://user-images.githubusercontent.com/51663/211533385-0b04c81a-b41d-4d8f-a219-a25831460537.png)

#### What did you expect?
Both tabs can connect to server and work the same

#### What happened instead?
One tab can't connect to server and I am not receiving messages (messages are going out fine, but are showing as not sent locally).

### Browser information

Chromium 108.0.5359.124 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 5b730f4b07b1-react-b1c32995c679-js-e2ce379b56b9 Olm version: 3.2.12

### Homeserver

I am on matrix.org, the other person is on element.io

### Will you send logs?

Yes

**Comment by andybalaam** [comment] 2023-01-10 11:07
Possibly a dupe of https://github.com/vector-im/element-web/issues/24200 ?

**Comment by andybalaam** [comment] 2023-01-10 13:19
Duplicate of #24200

**Closed by andybalaam** 2023-01-10 13:19 UTC
Labels: T-Defect
