### ISSUE TITLE
Poor performance when leaving Element open for a while

### ISSUE THREAD

**Issue by gspbirel56** [vector-im/element-web#25834] opened 2023-07-21 22:42 UTC
### Steps to reproduce

1. Load Element desktop (Windows)
2. Keep chat window open for a few hours/days
3. UI slows down, and by that I mean the UI itself responds less quickly. Keystrokes, mouse hovers, mouse clicks all take a lot longer to react. I can fix this by clearing cache

#### What did you expect?
No slowdown
#### What happened instead?
Slowdown

### Operating system

Windows 11

### Homeserver

chrrreeeeesss.com 1.88.0

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-07-26 06:45
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-07-26 06:45
Duplicate of https://github.com/vector-im/element-web/issues/25713

**Comment by weeman1337** [comment] 2023-07-26 06:46
@gspbirel56 it would be helpful if you can upload profiling information. If possible to the duplicated issue in a comment: https://github.com/vector-im/element-web/issues/25713

**Closed by weeman1337** 2023-07-26 06:45 UTC
Labels: T-Defect
