### ISSUE TITLE
Constant log spam: too many `Thread.update` listeners

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25407] opened 2023-05-18 16:49 UTC
### Steps to reproduce

1. Open your JS console

#### What did you expect?

Less spam.

#### What happened instead?

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Thread.update listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (vector://vector/webapp/bundles/4087e245b690faed1450/bundle.js:55693:15)
    at Thread.addListener (vector://vector/webapp/bundles/4087e245b690faed1450/bundle.js:55709:10)
    at Thread.on (vector://vector/webapp/bundles/4087e245b690faed1450/bundle.js:42930:18)
    at TypedReEmitter.reEmit (vector://vector/webapp/bundles/4087e245b690faed1450/bundle.js:87881:14)
    at TypedReEmitter.reEmit (vector://vector/webapp/bundles/4087e245b690faed1450/bundle.js:87901:11)
    at MatrixEvent.setThread (vector://vector/webapp/bundles/4087e245b690faed1450/bundle.js:21772:22)
    at mapper (vector://vector/webapp/bundles/4087e245b690faed1450/bundle.js:228318:13)
    at Array.map (<anonymous>)
    at vector://vector/webapp/bundles/4087e245b690faed1450/bundle.js:17090:114
    at async Thread.updateThreadMetadata (vector://vector/webapp/bundles/4087e245b690faed1450/bundle.js:23525:11)
```

at approximately 2Hz.

This makes it difficult to dig through the logs to find other issues.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023051801 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-05-19 12:22
Duplicate of https://github.com/vector-im/element-web/issues/24987

**Closed by t3chguy** 2023-05-19 12:22 UTC
Labels: T-Defect
