### ISSUE TITLE
Inviting people to rooms who have already joined isn't helpful

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#17540] opened 2021-06-02 16:54 UTC
Element shows a generic `Something went wrong` type message which is quite startling.

1. Can we show a better contextual message if this happens?
2. Can we do a better job of excluding people from the invite modal if they're already in the room?

**Comment by t3chguy** [comment] 2021-06-02 17:24
Duplicate of https://github.com/vector-im/element-web/issues/12281

**Closed by t3chguy** 2021-06-02 17:24 UTC
