### ISSUE TITLE
Text event covering the avatar on a thread

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22379] opened 2022-05-28 04:29 UTC
### Steps to reproduce

1. Open https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$MAhSEJGAQqUWyfXDPnHJwZbcGtWuo54wf7HfUzU7NNc?via=matrix.org&via=privacytools.io&via=mozilla.org

#### What did you expect?

The common inline start margin should be applied to align the textual event with other elements.

![after](https://user-images.githubusercontent.com/3362943/170809603-4139a5d5-fb75-4f3a-a172-8f7577f8bfc1.png)

#### What happened instead?

The margin is not set and the textual event covers the avatar.

![before](https://user-images.githubusercontent.com/3362943/170809612-02b79b82-1b2a-4279-a92d-db309d82e0a2.png)

### Operating system

Debian

### Browser information

Firefox ESR 99

### Application version

develop branch

### Will you send logs?

No

**Comment by robintown** [comment] 2022-05-28 14:01
Those kinds of events should never show up in the thread in the first place, so we should instead continue tracking this as https://github.com/vector-im/element-web/issues/21613.

Duplicate of https://github.com/vector-im/element-web/issues/21613

**Closed by robintown** 2022-05-28 14:01 UTC
Labels: T-Defect
