### ISSUE TITLE
Wrong link to Element desktop on the home page

### ISSUE THREAD

**Issue by tredondo** [vector-im/element-web#25053] opened 2023-04-06 06:57 UTC
The link under "Element desktop" points to https://github.com/vector-im/element-android/

![image](https://user-images.githubusercontent.com/10043369/230295590-33e79606-b7aa-4e5e-b43d-b0d79e69c1c5.png)

**Comment by t3chguy** [comment] 2023-04-06 07:43
Duplicate of https://github.com/vector-im/element.io/issues/58

**Closed by t3chguy** 2023-04-06 07:43 UTC
