### ISSUE TITLE
In an encrypted one to one chat, allow opposite party to read old messages

### ISSUE THREAD

**Issue by yennor** [vector-im/element-web#22598] opened 2022-06-16 17:43 UTC
#### What would you like to do?

In a one to one chat allow the other party to read old messages.

#### Why would you like to do it?

A friend just told me, that he can't read old messages anymore in our one to one chat (he didn-t reinstall the programm or anything). The programm is telling him that it is "requesting the key" (or similar, the message is in german). (I've also had that problem once, but I didn't care enough to investigate how that happens).
Obviously he got no backup of his keys.
I would like to allow him, to read the old messages again.

#### How would you like to achieve it?

Somehow in the user interface to allow the other party to see the old messages again. Even if all of them would need to be retransmitted again. Either the other party requesting it, and I have to accept it, or i can just initiate it from my side...

### Have you considered any alternatives?

maybe there is already a function for that? In that case, try to make it more obvious.

**Comment by turt2live** [comment] 2022-06-16 23:08
Duplicate of https://github.com/vector-im/element-web/issues/6454

**Closed by turt2live** 2022-06-16 23:08 UTC
Labels: T-Enhancement
