### ISSUE TITLE
Send a link for people to create an account on a specific homeserver

### ISSUE THREAD

**Issue by PxBCPG** [vector-im/element-web#20591] opened 2022-01-17 17:25 UTC
#### What would you like to do?

Send an invite link that will contain the home server to sign in on. 
This something really annoying to have to type the name of the custom home server, especially when you're new to element. 

#### How would you like to achieve it?

Send a link that looks like app.element.io/register#homeserver=myserver.org

**Comment by t3chguy** [comment] 2022-01-17 17:26
Duplicate of https://github.com/vector-im/element-web/issues/5469

**Closed by t3chguy** 2022-01-17 17:26 UTC
Labels: T-Enhancement
