### ISSUE TITLE
Nightly does not work with ozone (wayland native)

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18902] opened 2021-09-04 08:59 UTC
### Steps to reproduce

Stable supports running in wayland native like this: `element-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland`. Doing the same with element-desktop-nightly apparently does not. Maybe because bundles its own electron (assumption based on no dependency in the pkg)?

This is on sway 1.6.1.

### What did you expect?
element works as usual

### What happened?
no window, only the indicator icon appears.

### Operating system

arch

### Application version

Element Nightly version: 2021090301 Olm version: 3.2.3

### How did you install the app?

aur/element-desktop-nightly-bin

### Homeserver

own

### Have you submitted a rageshake?

No

**Comment by dbkr** [comment] 2021-09-06 13:00
This isn't one of our packages I'm afraid - I'm not sure we can really help much unless it's just a case of it using a different electron version or something perhaps? Although we are fairly up to date.

**Comment by HarHarLinks** [comment] 2021-09-07 18:36
I realize that this package isn't strictly provided to aur by element, but looking at the pkgbuild https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=element-desktop-nightly-bin it really is just the packages.riot.im .deb nightly. Isn't that yours?

**Comment by SimonBrandner** [comment] 2021-09-10 15:41
Perhaps this was caused by https://github.com/vector-im/element-desktop/pull/256 as @yu-re-ka suggests in https://github.com/vector-im/element-desktop/pull/256#issuecomment-913676319. @yu-re-ka, what leads you to think that was the change that broke Element with Wayland?

**Comment by SimonBrandner** [comment] 2021-09-10 15:42
@yu-re-ka and @HarHarLinks, does Jitsi work for you?

**Comment by yu-re-ka** [comment] 2021-09-10 18:23
The described failure mode matches what I have observed.

https://github.com/vector-im/element-desktop/pull/256 adds a `--enable-features WebRTCPipeWireCapturer` flag to the electron cmdline. However @HarHarLinks and I set this flag as well, so effectively electron gets started with `--enable-features WebRTCPipeWireCapturer --enable-features UseOzonePlatform` and Chromium/Electron don't support passing the flag multiple times.

This should be fixed by https://github.com/vector-im/element-desktop/pull/261, but the build date of the nightly package suggests it doesn't include the fix.
The Jitsi desktop app had the same problem.

**Comment by SimonBrandner** [comment] 2021-09-10 18:32
Ah, great thanks for the explanation! Let's assume this is fixed now. Let me know if you ever see this again

**Closed by SimonBrandner** 2021-09-10 18:32 UTC
Labels: T-Defect, S-Critical, O-Low

**Comment by HarHarLinks** [comment] 2021-09-13 17:31
It does seem to work in principle now. I'm noticing a last small problem: when running with ozone, the window_properties field is missing. This contains a bunch of meta info to identify the program and is commonly used to e.g. assign apps to fixed workspaces. Consequently my condition that moves windows with class beginning in Element to a certain workspace.
get_tree with ozone:
```
            {
              "id": 23,
              "type": "con",
              "orientation": "none",
              "percent": 1.0,
              "urgent": false,
              "marks": [
              ],
              "focused": false,
              "layout": "none",
              "border": "normal",
              "current_border_width": 2,
              "rect": {
                "x": 0,
                "y": 415,
                "width": 1920,
                "height": 1025
              },
              "deco_rect": {
                "x": 0,
                "y": 0,
                "width": 1920,
                "height": 25
              },
              "window_rect": {
                "x": 0,
                "y": 0,
                "width": 1920,
                "height": 1025
              },
              "geometry": {
                "x": 0,
                "y": 0,
                "width": 1024,
                "height": 768
              },
              "name": "Element Nightly [1] | Room Name",
              "window": null,
              "nodes": [
              ],
              "floating_nodes": [
              ],
              "focus": [
              ],
              "fullscreen_mode": 0,
              "sticky": false,
              "pid": 4509,
              "app_id": "Element-Nightly",
              "visible": true,
              "max_render_time": 0,
              "shell": "xdg_shell",
              "inhibit_idle": false,
              "idle_inhibitors": {
                "user": "none",
                "application": "none"
              }
            }
```
with Xwayland:
```
            {
                  "id": 27,
                  "type": "con",
                  "orientation": "none",
                  "percent": 1.0,
                  "urgent": false,
                  "marks": [
                  ],
                  "focused": false,
                  "layout": "none",
                  "border": "normal",
                  "current_border_width": 2,
                  "rect": {
                    "x": 0,
                    "y": 415,
                    "width": 1920,
                    "height": 1025
                  },
                  "deco_rect": {
                    "x": 0,
                    "y": 0,
                    "width": 1920,
                    "height": 25
                  },
                  "window_rect": {
                    "x": 0,
                    "y": 0,
                    "width": 1920,
                    "height": 1025
                  },
                  "geometry": {
                    "x": 0,
                    "y": 0,
                    "width": 1024,
                    "height": 768
                  },
                  "name": "Element Nightly [1] | Room Name",
                  "window": 23068673,
                  "nodes": [
                  ],
                  "floating_nodes": [
                  ],
                  "focus": [
                  ],
                  "fullscreen_mode": 0,
                  "sticky": false,
                  "pid": 7935,
                  "app_id": null,
                  "visible": true,
                  "max_render_time": 0,
                  "shell": "xwayland",
                  "inhibit_idle": false,
                  "idle_inhibitors": {
                    "user": "none",
                    "application": "none"
                  },
                  "window_properties": {
                    "class": "Element-Nightly",
                    "instance": "element-nightly",
                    "title": "Element Nightly [1] | Room Name",
                    "transient_for": null,
                    "window_role": "browser-window",
                    "window_type": "normal"
                  }
                }
```
