### ISSUE TITLE
Image captions look unrelated

### ISSUE THREAD

**Issue by swapnilraj** [vector-im/element-web#14912] opened 2020-08-08 15:57 UTC
**Is your suggestion related to a problem? Please describe.**
When you send an image message, there is no ability to add caption to the image. So you need to send a separate message explaining/referring to the message, visually they look like unrelated messages.

**Describe the solution you'd like**
Two possible solutions to this could be:

* Add a new message type imageWithText
* Use the already existing HTML messages to encode this, will need some tweaking; currently the images tags are not shown

**Describe alternatives you've considered**
I tried sending HTML but the image tag is not displayed

**Additional context**
Screenshots of how Whatsapp implements this.
![image](https://user-images.githubusercontent.com/1834746/89714584-95848300-d997-11ea-9af4-50d90acba7cc.png)

**Comment by t3chguy** [comment] 2020-08-08 16:06
> currently the images tags are not shown

Yes they are, but for privacy purposes they must point to `mxc://` resources

Duplicate of https://github.com/vector-im/element-web/issues/1818

**Closed by t3chguy** 2020-08-08 16:06 UTC
Labels: suggestion, ui/ux
