### ISSUE TITLE
SVG space logo broken

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#20905] opened 2022-02-04 09:11 UTC
### Steps to reproduce

1. Go to one of your space's settings
2. Upload an SVG as the thumbnail for that space
3. Hit save

#### What did you expect?

For the image to be uploaded and used as the space logo

#### What happened instead?

The upload went through, and I ended up with a broken thumbnail

<img width="192" alt="Screen Shot 2022-02-04 at 09 10 49" src="https://user-images.githubusercontent.com/769871/152502470-a684d921-08c7-42e8-9541-221fffac1c58.png">
<img width="343" alt="Screen Shot 2022-02-04 at 09 10 55" src="https://user-images.githubusercontent.com/769871/152502474-6f0bf159-572c-4b6b-ae22-c96d15ceddaf.png">

### Operating system

macOS

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-02-04 10:13
Unrelated to Spaces 
Duplicate of https://github.com/vector-im/element-web/issues/2581

**Closed by t3chguy** 2022-02-04 10:13 UTC
Labels: T-Defect, S-Minor, A-Spaces-Settings, O-Uncommon
