### ISSUE TITLE
/Spoiler show the original text in windows notification

### ISSUE THREAD

**Issue by Donpipolitto** [vector-im/element-web#22128] opened 2022-05-10 09:41 UTC
### Steps to reproduce

One user use the /poiler code to send a message in a room
An other user with notification activated shows a popup with the clear/original text

#### What did you expect?
Dont really know. At least a popup with no text or something like *****

#### What happened instead?
The popup show the full text

### Operating system

Windows 10

### Application version

Element 1.10.11 OLM 3.2.8

### How did you install the app?

don't remember, but downloaded on internet

### Homeserver

don't know

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-05-10 10:42
Duplicate of https://github.com/vector-im/element-web/issues/12034

**Closed by t3chguy** 2022-05-10 10:42 UTC
Labels: T-Defect
