### ISSUE TITLE
Messages starting with a number and a followed by a full stop is rendered without the first digit

### ISSUE THREAD

**Issue by mehmetalianil** [vector-im/element-web#24282] opened 2023-01-21 10:48 UTC
### Steps to reproduce

1. I am just sending a message that starts with a number that is followed by a full stop. For example:
`117. olcum`
![image](https://user-images.githubusercontent.com/551129/213863473-6d779046-346e-4c83-9a29-7245b3011e3c.png)

#### What did you expect?
I expect the message to be rendered as is
#### What happened instead?
The message is rendered without the first digit as:
`17.olcum`
![image](https://user-images.githubusercontent.com/551129/213863492-cb48aefc-4d50-46ba-885e-84e3770eaf19.png)

It seems that there is an issue about the HTML formatting. The number is wrapped in an ol tag
Redacted message source: 
```
{
  "type": "m.room.message",
  "content": {
    "org.matrix.msc1767.message": [
      {
        "body": "117. olcum icin sadece digerlerinde peak resolve edilemiyor",
        "mimetype": "text/plain"
      },
      {
        "body": "<ol start=\"117\">\n<li>olcum icin sadece digerlerinde peak resolve edilemiyor</li>\n</ol>\n",
        "mimetype": "text/html"
      }
    ],
    "body": "117. olcum icin sadece digerlerinde peak resolve edilemiyor",
    "msgtype": "m.text",
    "format": "org.matrix.custom.html",
    "formatted_body": "<ol start=\"117\">\n<li>olcum icin sadece digerlerinde peak resolve edilemiyor</li>\n</ol>\n"
  },
}
```

### Operating system

Windows

### Application version

Element version: 1.11.17 Olm version: 3.2.12

### How did you install the app?

Don't remember

### Homeserver

matrix.org and homeserver

### Will you send logs?

No

**Comment by tulir** [comment] 2023-01-21 11:10
Duplicate of #14621

**Comment by mehmetalianil** [comment] 2023-01-21 11:19
Thanks, I had made a quick search but couldn't find this issue.

**Closed** 2023-01-23 13:46 UTC
Labels: T-Defect
