### ISSUE TITLE
"Show hidden events" doesn't show reaction events anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25796] opened 2023-07-13 17:49 UTC
### Steps to reproduce

1. Send a bunch of reactions
2. Enable "Show Hidden Events"

#### What did you expect?

To see reaction events.

#### What happened instead?

They're hidden :( 

(it used to work)

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023071301 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-07-14 07:34
<img width="528" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/03e3276e-5b01-4d6d-af91-ea427b53a022">

@turt2live works fine for me. 

One change in this area is when paginating and we encounter a reaction we do not have the parent event for we do indeed not add it to a timeline as adding it to the correct timeline would require asking the server for the parent event which significantly hurts scrolling performance.

**Comment by turt2live** [comment] 2023-07-16 09:54
It's possibly this only happens when someone has spammed reactions outside of the UI - to be investigated further, possibly out of band (related issues have not been opened publicly yet)

**Comment by t3chguy** [comment] 2023-10-16 10:12
Closing due to no reproduction

**Closed by t3chguy** 2023-10-16 10:12 UTC
Labels: T-Defect, X-Cannot-Reproduce
