### ISSUE TITLE
Missed call ringing on every load

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#22984] opened 2022-08-03 17:21 UTC
### Steps to reproduce

1. Have a missed call in a DM
2. Reload Element Web

#### What did you expect?

No ringing

#### What happened instead?

Missed calls are ringing for a very short time (with audio notification). Watch this video carefully:

![ring](https://user-images.githubusercontent.com/6216686/182670192-0d2e625f-ffbd-4f35-9c1d-9e0fb7e87390.gif)

Also happening with Desktop Client

### Operating system

Ubuntu 22.04 LTS

### Browser information

Firefox 103.0 (64-Bit)

### URL for webapp

https://develop.element.io/

### Application version

Version von Element: fc6c859976b3-react-0e0be0878102-js-c36bfc821c18 Version von Olm: 3.2.12

### Will you send logs?

Yes

**Comment by turt2live** [comment] 2022-08-05 03:06
Duplicate of https://github.com/vector-im/element-web/issues/4607

**Closed by turt2live** 2022-08-05 03:06 UTC
Labels: T-Defect
