### ISSUE TITLE
/register call seems to loop when server replies with M_USER_IN_USE

### ISSUE THREAD

**Issue by njouanin** [vector-im/element-web#15290] opened 2020-09-26 07:55 UTC
# Description

With riot-1.7.7 : 
I'm using riot to test user registration on [mascarene](https://gitlab.com/mascarene/mascarene) homeserver. When trying to register with a username which already exists, mascarene replies with with 400 error code: 
```
{"errcode":"M_USER_IN_USE","error":"'@nico:localhost' is already used"}
```
Then it seems that riot loops indefinitevely on calling /register endpoint with the same data again and again. See screenshot for a trace of API calls. 

![riot_loop](https://user-images.githubusercontent.com/728898/94335878-ae043780-ffef-11ea-8fda-aa5ac9facd25.jpg)

I'havn't try this with synapse, but mascarene answer seems to be correct ...

### Steps to reproduce

- register with some user
- register again with the same user

Describe how what happens differs from what you expected.

Riot should report the error (user already exists) and stop calling /register until the user change the username

### Version information

- **Platform**: web - riot 1.7.7

For the web app:

- **Browser**: Firefox 80.0.1
- **OS**: Manjaro Linux
- **URL**: riot deployed on local web server for mascarene development

**Comment by t3chguy** [comment] 2020-09-28 13:50
Hmm, cannot reproduce against Synapse which also sends a `400 M_USER_IN_USE`

![image](https://user-images.githubusercontent.com/2403652/94440853-0119ee00-019a-11eb-8774-7669ea8e008b.png)

**Comment by njouanin** [comment] 2020-09-29 16:17
I'll need to re-test, sorry.

**Comment by t3chguy** [comment] 2020-10-02 12:19
Duplicate of https://github.com/vector-im/element-web/issues/10346

**Closed by t3chguy** 2020-10-02 12:19 UTC
Labels: bug, cannot-reproduce, p2, severity:minor, type:registration
