### ISSUE TITLE
Visiting a link to a room doesn't show the mobile install guide

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#22259] opened 2022-05-18 09:16 UTC
### Steps to reproduce

1. Visit a link to a room on mobile (e.g. if someone shared a link with you).
2. Have a bad time:

![image](https://user-images.githubusercontent.com/4626865/169003227-433577a4-8baa-4a2d-8265-87bfe2bf695e.png)

### Outcome

We should show the mobile install guide on Element Web. We should also sanity check the iOS & Android smart banners are using the right links, and that the mobile clients are handling them.

Later, we should revisit the content of the mobile install guide, and polish onboarding in the mobile clients.

### Operating system

iOS15, latest

### Browser information

Safari, latest

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-05-18 09:26
Duplicate of https://github.com/vector-im/element-web/issues/14962

**Closed by t3chguy** 2022-05-18 09:26 UTC
Labels: T-Defect
