### ISSUE TITLE
VSCode style Title bar

### ISSUE THREAD

**Issue by baek-sang** [vector-im/element-web#17788] opened 2021-06-25 18:29 UTC
#### Is your suggestion related to a problem? Please describe.
![title](https://user-images.githubusercontent.com/69100154/123469870-95808680-d62e-11eb-9afd-ba986c042764.png)

Using Windows 10 Dark Theme, but title bar is white.

**Comment by SimonBrandner** [comment] 2021-06-25 19:34
Duplicate of https://github.com/vector-im/element-web/issues/15997

**Closed by SimonBrandner** 2021-06-25 19:34 UTC
Labels: T-Enhancement
