### ISSUE TITLE
Spaces not discoverable

### ISSUE THREAD

**Issue by ninoppp** [vector-im/element-web#21384] opened 2022-03-10 21:10 UTC
### Steps to reproduce

Hello there.
I'm using a self hosted synapse with element web&desktop apps for my organization. My synapse is de-federalized (no federation client, federation whitelist empty, 8448 blocked), however, the same issue exists for a user with a federalized server I spoke to.
`Disclaimer: I'm not sure if this is an issue with element, synapse or the matrix protocol itself. Please refer me to the right place if this is wrong here`

### Outcome

When I click on the explore room icon (besides the search bar) in element, only my public rooms show up: not my public spaces. Keyword searching doesn't work either, the spaces only appear after typing out the exact address (doesn't matter if it's local only or published).
Is there any option to fix that? Would be quite useful for us since it would allow anyone to join certain groups which have more than one room.

### Operating system

Arch Linux

### URL for webapp

different one's

### Application version

Element version: 1.10.6 Olm version: 3.2.8

### Homeserver

matrix-synapse-py3 1.54.0+bullseye1 amd64 

### Will you send logs?

yes

**Comment by t3chguy** [comment] 2022-03-10 22:55
Duplicate of https://github.com/vector-im/element-web/issues/17264

**Closed by t3chguy** 2022-03-10 22:55 UTC
Labels: T-Defect
