### ISSUE TITLE
Custom Logout URL

### ISSUE THREAD

**Issue by jonathanmmm** [vector-im/element-web#19822] opened 2021-11-20 11:22 UTC
#### What would you like to do?

I would like to set a custom logout url, so that after sucessfull logout it goes somewhere else as https://element.my-domain.com/#/login
Actually just redirecting it to my custom welcome url (that I set) would be enought, but a complete custom logout url would be great.

#### Why would you like to do it?

This way I can sucessfully logout from keycloak (as I use a logout redirect url), but also for other use cases people would like this feature. They can send them to a custom url that gives them access to other services or so.

#### How would you like to achieve it?

A config.json parameter that lets the default parameter be changed.

**Comment by t3chguy** [comment] 2021-11-20 11:33
Given that this relates to SLO/logout redirect URL it should be controlled by the server to which you're connected rather than a client config.json, otherwise Element Desktop etc won't ever perform SLO which would be inconsistent. Maybe it should be a field that the server returns in the logout API response.

**Comment by jonathanmmm** [comment] 2021-11-20 12:29
I know, that is inconsistent.

My use case is "going to not your private pc and logging and logging out" you normally don't do that in a desktop app.

Problem right now, synapse doesn't support logout from SSO which makes the web application not usable (as I can't explain every user that they won't be logged out if they press "logout", as somebody else can just press "login with OpenID Connect" and have access to the account of the other user.

Right now, if a user accesses the welcome page he is redirected to keycloak and logged out and keycloak redirect to the login page.

Hope you understand what I try to achieve. 

Also I think if a user loggs out of element it should be possible to redirect to the welcome page, as a new user maybe needs it.

**Comment by t3chguy** [comment] 2022-04-29 14:08
Duplicate of https://github.com/vector-im/element-web/issues/15829

**Closed by t3chguy** 2022-04-29 14:08 UTC
Labels: Z-Synapse, X-Needs-Product, T-Enhancement, A-Logout
