### ISSUE TITLE
Hard coded font-weight in .mx_Dialog interacts poorly with fonts that support "Light" weights

### ISSUE THREAD

**Issue by globau** [vector-im/element-web#21171] opened 2022-02-23 07:04 UTC
### Steps to reproduce

1. Install `Fira Sans` font, or any other font that supports Light or variable weights
2. Change the Element font to `Fira Sans`

#### What did you expect?

Readable text, and an accurate preview.

More specifically the `.mx_Dialog` class should not specify `font-weight: 300`, which maps to OpenType's "Light" weight name.
The default font, Inter, does not support this font-weight, so dialogs are rendered identically to the default font-weight of 400.

#### What happened instead?

<img src="https://user-images.githubusercontent.com/872825/155272934-2730ac16-0fdd-4ffb-8c18-d27ec8728f6e.png" width="750px">

Note that the preview at the top of the screenshot is incorrect - the message list doesn't specify a font weight:

<img src="https://user-images.githubusercontent.com/872825/155273566-ffa0aeea-0aca-49c0-bcf3-dc471ca8b105.png" width="486px">

### Will you send logs?

No

**Comment by goelesha** [comment] 2022-04-09 16:12
@globau Can you pls elaborate on the issue?
I tried reproducing the issue but could not identify the problem exactly. Below are some screenshots for your reference. 
<img width="1136" alt="Screenshot 2022-04-09 at 9 38 59 PM" src="https://user-images.githubusercontent.com/54431564/162582159-58bb3da8-83f7-4a84-a6fb-7eefd7246d6b.png">
<img width="990" alt="Screenshot 2022-04-09 at 9 40 14 PM" src="https://user-images.githubusercontent.com/54431564/162582168-68dc6a7e-6c0b-484e-bb5f-735f324e14fc.png">
<img width="439" alt="Screenshot 2022-04-09 at 9 40 35 PM" src="https://user-images.githubusercontent.com/54431564/162582169-59d5ab46-34ce-48e8-9087-395f41285549.png">

**Comment by globau** [comment] 2022-04-09 16:17
Make sure the typeface you're using has a specific weight for 300.  There's a discussion on the referenced pr.

**Comment by goelesha** [comment] 2022-04-09 18:54
@globau I was able to reproduce it using Fira Sans Extralight. Like this:
<img width="1082" alt="Screenshot 2022-04-09 at 11 16 55 PM" src="https://user-images.githubusercontent.com/54431564/162585577-913069ee-cfa8-4875-88ea-df0fd9c57a35.png">

**Comment by goelesha** [comment] 2022-04-16 07:40
@globau On changing the font-weight to 400, the issue is fixed in Safari but I am not able to understand why it still doesn't fix the issue in chrome.

Safari-
<img width="1425" alt="Screenshot 2022-04-16 at 1 08 04 PM" src="https://user-images.githubusercontent.com/54431564/163666435-5d8be982-4a43-4e49-a968-e21777161c4e.png">
Chrome-
<img width="1438" alt="Screenshot 2022-04-16 at 1 08 34 PM" src="https://user-images.githubusercontent.com/54431564/163666471-1e111518-add7-46c8-814f-aacd86b26c9c.png">

Following are the changes I have made
<img width="998" alt="Screenshot 2022-04-16 at 1 09 20 PM" src="https://user-images.githubusercontent.com/54431564/163666514-c72eefe9-22c8-4c5c-999c-62dd5ed11866.png">
<img width="958" alt="Screenshot 2022-04-16 at 1 09 29 PM" src="https://user-images.githubusercontent.com/54431564/163666523-07dbbd4a-c407-458a-a214-ccb427d47e25.png">

Can you pls guide me on how to proceed further?

**Comment by globau** [comment] 2022-04-16 09:46
I can't help you with Chrome.

**Closed** 2022-04-22 14:44 UTC
Labels: T-Defect, S-Tolerable, A-Appearance, O-Uncommon
