### ISSUE TITLE
Room keeps getting unread with no new activity

### ISSUE THREAD

**Issue by moritzdietz** [vector-im/element-web#26104] opened 2023-09-03 11:55 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
I just noticed that for some days I have this room which keeps being marked as unread even though there is no new activity.

2. What do you click?
Element is closed, I start the application it loads all rooms and the room is being marked as unread, I go into it and then it's marked as read. After a while it keeps being marked as unread again.

#### What did you expect?
Room not being unread as there is no new activity – this room only has < 30 messages and no threads, no other things like locations or live streams, no polls etc.
#### What happened instead?
Room is being marked as unread.

### Operating system

macOS

### Application version

Nightly Version 2023090301 (2023090301)

### Homeserver

Synapse 1.91.0

### Will you send logs?

Yes

**Comment by moritzdietz** [comment] 2023-09-03 11:56
I just also send a rageshake with a link to this issue

**Comment by andybalaam** [comment] 2023-09-08 08:16
Duplicate of https://github.com/vector-im/element-web/issues/24392

Thanks for the report - we're handling this problem under #24392

**Closed by andybalaam** 2023-09-08 08:16 UTC
Labels: T-Defect
