### ISSUE TITLE
Latex lab option cant be escaped

### ISSUE THREAD

**Issue by dali99** [vector-im/element-web#15931] opened 2020-12-08 14:26 UTC
### Description

If the render latex option is enables you cannot escape the latex. Neither `\` nor wrapping it in a codeblock will escape the interpreters wrath.

Was noticed when someone tried to send a log from the commandline with $ on each line

```
$ mkdir o6klone
$ cd o6klone
$ git init
$ touch a
$ git add a
$ git commit -m "la til filen a"
$ mkdir ../tmp
$ cd ../tmp
$ git clone ../o6klone
$ cd o6klone/
$ touch b
$ git add b
$ touch c
$ cd ..
$ tar czvf o6klone.tar.gz o6klone/
```

@akissinger @uhoreg

**Comment by t3chguy** [comment] 2020-12-08 14:30
Duplicate of https://github.com/vector-im/element-web/issues/15846

**Closed by t3chguy** 2020-12-08 14:30 UTC
Labels: bug
