### ISSUE TITLE
Convert `src/browser-index.js` to TS

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19272] opened 2021-10-04 15:10 UTC
https://github.com/matrix-org/matrix-js-sdk/blob/0f559050d859ecd74be5c75f38f00fe0269210ee/src/browser-index.js

**Comment by t3chguy** [comment] 2021-10-05 08:34
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/1893

**Closed by t3chguy** 2021-10-05 08:34 UTC
Labels: T-Task, A-Developer-Experience
