### ISSUE TITLE
"Some of your messages have not been sent" for specific device/room combination

### ISSUE THREAD

**Issue by Mortein** [vector-im/element-web#24785] opened 2023-03-10 01:44 UTC
### Steps to reproduce

1. Have a specific room which is bridged to Signal (may or may not be related)
2. On a specific desktop device:
    1. Send a message to the room
    2. React to another user's message using emoji

Has been happening for several months.

#### What did you expect?
1. Message would be sent
2. Message will show emoji

#### What happened instead?
1. Message is not sent
    1. `Some of your messages have not been sent` error, with _Delete all_ and _Retry all_ buttons.
    2. _Delete all_ works as expected. _Retry all_ does nothing.
3. Message does show emoji (as expected)

On other devices (Android/Windows), messages can be sent to this room.
On this device, other rooms work as expected.

### Operating system

Windows 10

### Application version

Element version: 1.11.24 Olm version: 3.2.12

### How did you install the app?

https://element.io/download

### Homeserver

Synapse 1.78.0

### Will you send logs?

Yes

**Comment by Mortein** [comment] 2023-03-10 01:47
Have sent logs.

**Comment by t3chguy** [comment] 2023-03-10 12:26
Duplicate of https://github.com/vector-im/element-web/issues/22771

**Closed by t3chguy** 2023-03-10 12:26 UTC
Labels: T-Defect
