### ISSUE TITLE
No way to disable "unread message" asterisk in tab name for rooms

### ISSUE THREAD

**Issue by nukeop** [vector-im/element-web#26219] opened 2023-09-22 09:08 UTC
### Steps to reproduce

1. Join any room
2. Switch to a different room
3. When somebody sends a message to the first room, Element will display a dot next to that room's name, and the name will be rendered in bold letters to signify that it has unread messages.
4. Element will also display an asterisk in the tab name if any room has unread messages.

I want to be able to ignore new messages in some rooms that I only visit on an occasional basis. I used the asterisk to see that there are new messages in the few rooms that really interest me, I'm no longer able to use it this way. I have to manually click all the rooms that I don't care about to clear the notification, which doesn't always work (see #24392 ).

A few versions ago, I was able to simply put the room the "low priority" category, but now low priority rooms also change the tab's title. I don't want to mute the room, I still want to see the dot next to its name when I look at Element, but I don't want it to change the tab's title.

This is the dot next to the room name
<img width="150" alt="image" src="https://github.com/vector-im/element-web/assets/12746779/9e7045e4-3aa2-4561-805c-e069a1b850e9">

This is an asterisk in the tab name when there are any unread messages
<img width="101" alt="image" src="https://github.com/vector-im/element-web/assets/12746779/a33d7344-2be3-4568-8160-d24ef224719a">

#### What did you expect?
Explained above

#### What happened instead?
Explained above

### Operating system

All

### Browser information

N/A

### URL for webapp

Private server

### Application version

1.11.35

### Homeserver

Synapse

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-09-22 09:13
Duplicate of https://github.com/vector-im/element-web/issues/24554

**Closed by t3chguy** 2023-09-22 09:13 UTC
Labels: T-Defect
