### ISSUE TITLE
Following a permalink to a thread root opens the thread

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21280] opened 2022-03-02 19:57 UTC
### Steps to reproduce

1. Reply to a thread root
2. Click on the reply preview

#### What did you expect?

Only to jump to the thread root.

#### What happened instead?

The timeline jumped to the thread root, and additionally the thread panel opened to display the thread.

### Operating system

NixOS unstable

### Browser information

Firefox 97.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 6721a7162f81-react-3572b36648db-js-ac4e504b8d40 Olm version: 3.2.8

### Homeserver

Synapse 1.52.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-03-04 08:35
https://github.com/matrix-org/matrix-react-sdk/blob/c72794209508ef16ecf4f39d9b1d1af63f96fa5d/src/components/structures/RoomView.tsx#L452-L458 this looks intentional, a quick ask internally points out that we're likely to want the permalink to dictate the behaviour depending on where the link is copied from (via extending matrix.to) so needs Product insight

**Comment by daniellekirkwood** [comment] 2022-11-15 10:57
👋  This is by design - when a user clicks on a reply (from the main timeline and from inside the thread) the timeline should go to the OG message, and show the thread in the thread panel. 

Closing without action :) Thanks!

**Closed by daniellekirkwood** 2022-11-15 10:57 UTC
Labels: T-Defect, S-Minor, X-Needs-Design, O-Occasional, A-Threads, Z-Labs
