### ISSUE TITLE
Can't dismiss the "New login. Was this you?" toast

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#18133] opened 2021-07-21 08:25 UTC
While testing whether https://github.com/matrix-org/matrix-react-sdk/pull/6423 fixed my image display issue (https://github.com/vector-im/element-web/issues/18115), I logged in on the netlify deploy. The "New login. Was this you?" toast appeared, and I just ignored it till I verified my new session. Now I'm trying to click "Later" and it doesn't do anything.

[removed GIF because it showed my home IP address, I'm attaching it to the rageshake]

Observed now on develop.element.io

**Comment by babolivier** [comment] 2021-07-21 08:30
Note that clicking "Check your devices" shows my security and privacy settings but doesn't dismiss the toast.

**Comment by robintown** [comment] 2021-07-28 00:20
Duplicate of https://github.com/vector-im/element-web/issues/17667

**Closed by robintown** 2021-07-28 00:20 UTC
Labels: A-E2EE-Cross-Signing, S-Major, T-Defect, X-Regression
