### ISSUE TITLE
Notifications that can be turned off at certain times

### ISSUE THREAD

**Issue by CodeFreezr** [vector-im/element-web#23350] opened 2022-09-25 03:03 UTC
#### What would you like to do?
I wanna disable notifications from channels/user/space for an amount of time. For e.g. Next 12 hrs, Next 3 hrs, ...

#### Why would you like to do it?
Because sometimes there are well known peaks. Or I wanna need concentration on stuff. With a time intervall I would never forget to enable back the alerting later on.

#### How would you like to achieve it?
Add a additiona property on "Notification options" for e.g. with the Attribut "Duration" with two different Attributes Permanent or Next [n] hrs.

**Comment by SimonBrandner** [comment] 2022-09-25 06:40
Duplicate of https://github.com/vector-im/element-web/issues/3569

**Closed by SimonBrandner** 2022-09-25 06:40 UTC
Labels: T-Enhancement
