### ISSUE TITLE
Show the target of a link, when you hover over it.

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#21907] opened 2022-04-24 17:06 UTC
### Your use case

Links in matrix are very unsecure in my opinion.
You can hide links behind other links
e.g. [https://bankXY.tld](https://gauner.tld/)
Pls make it more secure and fade in the target of a link in the bottem left on the chat window.
Perhaps there where typing appears when someone is typing.

**Comment by gsouquet** [comment] 2022-04-25 08:11
Browsers seem to have fixed this issue already by adding a little tooltip of the bottom right of the viewport.
Unencrypted rooms will also display a link preview, leveraging the meta tags of the link target.

This issue mainly affects people in encrypted rooms using Electron as they have no way to know the target of a link generated by markdown

**Comment by t3chguy** [comment] 2022-04-25 08:12
> Unencrypted rooms will also display a link preview, leveraging the meta tags of the link target.

Only if enabled & your HS supports url previews

You can also enable such preview in e2ee rooms

**Comment by t3chguy** [comment] 2022-04-25 08:13
> This issue mainly affects people in encrypted rooms using Electron as they have no way to know the target of a link generated by markdown

Right clicking shows it

<img width="819" alt="image" src="https://user-images.githubusercontent.com/2403652/165047854-4b3b6fa4-c24b-4d2a-ba47-d9f9721b8b10.png">

**Comment by gsouquet** [comment] 2022-04-25 08:14
Closing as this is a duplicate of https://github.com/vector-im/element-web/issues/6532
I believe that solving #6532 will bring a satisfying resolution to this ticket too

**Comment by t3chguy** [comment] 2022-04-25 08:14
Thanks, thats the dup I knew existed but couldn't find :D

**Closed by gsouquet** 2022-04-25 08:14 UTC
Labels: A-Electron, X-Needs-Design, T-Enhancement, O-Frequent
