### ISSUE TITLE
Expired server SSL certificate prompts room upgrade popup

### ISSUE THREAD

**Issue by MazeChaZer** [vector-im/element-web#16112] opened 2021-01-10 18:17 UTC
### Description

If the SSL certificate of the server has expired, the room version checker thinks that every room has to be upgraded and propmts the user with a propmt to initiate a room upgrade.

### Steps to reproduce

- Setup a server with a valid SSL certificate
- Login with Element, keep the session
- Let the server SSL certificate expire
- Go back into the client, the prompt should appear

I expected that this error would be handled gracefully and not wrongly prompt the user for a room upgrade.

### Version information

- **Platform**: Web
- **Browser**: Firefox, 84.0.1
- **OS**: Arch Linux
- **Version**: `588566cae788-react-588566cae788-js-588566cae788`

**Comment by t3chguy** [comment] 2021-01-10 18:45
Duplicate of https://github.com/vector-im/element-web/issues/16068

**Closed by t3chguy** 2021-01-10 18:45 UTC
Labels: bug
