### ISSUE TITLE
Messages from removed devices show warnings

### ISSUE THREAD

**Issue by michaelharmonart** [vector-im/element-web#16459] opened 2021-02-15 16:21 UTC
I recently switched phones, and so I verified my new device through my old phone, then removed my old phone from the device list on element. I now have a message next to every single message from that phone that says "encrypted by a deleted session" whenever I hover over the red shield next to each of those messages. 

![image](https://user-images.githubusercontent.com/15620900/107970399-4afb4900-6f6e-11eb-9b09-1f87698f0b4b.png)

This doesn't happen on android, and overall is really annoying.

Ideally this would be turned off, with maybe the possibility of turning it on in settings for the occasional person who needs the feature.

People switch devices quite often, and have no real reason to keep their old devices signed in and verified when it's just clutter.

### Steps to reproduce

- Create an an encrypted conversation
- send a few messages
- remove the device the messages were sent with
- view the conversation from the desktop element client

**Platform**: Desktop
**OS**: Kubuntu
**Version**: 1.7.20

**Comment by michaelharmonart** [comment] 2021-02-15 16:22
This could be considered a feature request. If someone would like to reassign the labels so that they match the issue more closely, go ahead.

**Comment by aaronraimist** [comment] 2021-02-15 19:35
Duplicate of https://github.com/vector-im/element-web/issues/13701

**Closed by aaronraimist** 2021-02-15 19:35 UTC
Labels: bug, ui/ux
