### ISSUE TITLE
Setting a custom font affects emojis

### ISSUE THREAD

**Issue by SethFalco** [vector-im/element-web#20357] opened 2021-12-26 12:48 UTC
### Steps to reproduce

1. Go to `Settings` → `Appearance` → `Font size` → `Use a system font`.
2. Enable `Use a system font` and set it to a custom font. (In my case, `Lucida Sans Unicode`.)
3. Send or receives an emoji in any chat room.

#### What did you expect?
Either:
1. The custom font shouldn't apply to emojis.
2. There should be a separate custom font field for emojis. This would be nice for users that want to use an alternative emoji set like [OpenMoji](https://openmoji.org/).

#### What happened instead?
Emojis no longer use `Twemoji`, but rather the custom font, so `Lucida Sans Unicode` in my case, and just looks really shoddy. ^-^'

![image](https://user-images.githubusercontent.com/22801583/147408293-2e8249f3-4869-4536-98cd-ef667ee331c1.png)

### Operating system

Windows 10

### Application version

Element Nightly version 0.0.1-nightly.2021122301 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started#nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2021-12-27 08:23
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/14398

**Closed by SimonBrandner** 2021-12-27 08:23 UTC
Labels: S-Minor, A-User-Settings, X-Needs-Design, X-Needs-Product, T-Enhancement, A-Emoji, Z-Papercuts, O-Occasional
