### ISSUE TITLE
"New login. Was this you?" popover is persistent and can't be dismissed

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18603] opened 2021-08-17 19:55 UTC
### Steps to reproduce

1. Log into Element from another platform

### What happened?

This popover is persistent:
![Screenshot from 2021-08-17 20-47-19](https://user-images.githubusercontent.com/51663/129791250-dedba44f-01a9-42a3-899d-ba06d6274338.png)

The "Check your devices" button opens the "Where you’re logged in" settings window.
The "Later" button doesn't do anything.

### What did you expect?

Being able to dismiss the dialog in some way

### Operating system

Arch Linux

### Browser information

Chromium Version 92.0.4515.131 (Official Build)

### URL for webapp

develop.element.io

**Comment by SimonBrandner** [comment] 2021-08-18 06:15
Does this freeze the whole app? It might be a duplicate of https://github.com/vector-im/element-web/issues/17667

**Comment by dbkr** [comment] 2021-08-18 14:35
I still can't repro it though

**Comment by kittykat** [comment] 2021-08-20 09:07
> Does this freeze the whole app? It might be a duplicate of #17667

No, the rest of the app worked fine and I can't reproduce it now either. Will /rageshake and reopen if it comes up again.

**Comment by kittykat** [comment] 2021-09-03 10:20
Rageshake submitted. I'm using same browser, normal and private sessions, for both element sessions. The toast pops us first, then gets the authentication toasts stacked in front of it and when those are dismissed/actioned/go away, the new login one is persistent.

https://user-images.githubusercontent.com/51663/131990209-1958045e-0cc7-4749-95dc-b0fac33b47d0.mp4

**Comment by dbkr** [comment] 2021-09-08 16:46
As per above PR, there's now some logging on develop to debug this: if anyone sees this again, please submit debug logs & mention this issue.

**Comment by robintown** [comment] 2021-09-09 15:26
This is in fact a duplicate of https://github.com/vector-im/element-web/issues/17667. Confusingly, the title of that issue is not referring to the entire UI being frozen, just the toast.

**Closed by robintown** 2021-09-09 15:26 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, S-Major, A-E2EE-Cross-Signing, A-Toast, O-Low
