### ISSUE TITLE
Element window often white

### ISSUE THREAD

**Issue by aha999** [vector-im/element-web#22477] opened 2022-06-08 00:34 UTC
### Steps to reproduce

1. Where are you starting? What can you see? Sometimes when I try to open Element, it's just a white color window inside (see screenshot) 
![image](https://user-images.githubusercontent.com/50620416/172505377-52d629f5-0dc0-476f-b289-37f5f82bc460.png)
3. What do you click? Element from a taskbar or when starting it
4. More steps…

#### What did you expect?
A normal window to be opened with information inside
#### What happened instead?
A blank window. When i force close it and reopen it, the problem is gone.

### Operating system

EndeavourOS

### Application version

1.10.13-1

### How did you install the app?

8 community/element-desktop 1.10.13-1 (4.0 MiB 18.1 MiB) (Installed)     Glossy Matrix collaboration client — desktop version.

### Will you send logs?

No

**Comment by weeman1337** [comment] 2022-06-08 06:55
Hi @aha999 thank you for opening an issue. If that white screen occurs next time, can you go to the developer console by pressing `Ctrl + Alt + i`, go to `Console` and post the contents from there here?

![image](https://user-images.githubusercontent.com/6216686/172551645-068bec7c-1ace-48aa-877c-10365eb6848b.png)

**Comment by t3chguy** [comment] 2022-06-08 07:09
Related https://github.com/vector-im/element-web/issues/21541

**Comment by t3chguy** [comment] 2022-11-15 10:07
Related https://github.com/vector-im/element-web/issues/21336

**Comment by aha999** [comment] 2022-11-26 09:37
@kittykat sorry but i replaced my GPU to RX 580 and i'm not having these issues anymore.

**Comment by turt2live** [comment] 2023-01-10 00:44
Closing as unable to reproduce. If this is still happening, please open a new issue with fresh reproduction steps for our QA team to review.

**Closed by turt2live** 2023-01-10 00:44 UTC
Labels: T-Defect, X-Needs-Info, X-Blocked, S-Major, A-Electron, O-Uncommon

**Comment by yagarea** [comment] 2024-02-13 12:26
I am reporting exact same issue on Arch linux. It was solved by installing vulkan driver for my GPU.

**Comment by melroy89** [comment] 2024-08-20 19:53
Same issue, while screen of dead. I got Failed to load resource and an errro of CORS on https://www.recaptcha.net/recaptcha. See log:

[vector-1724183550035.log](https://github.com/user-attachments/files/16681103/vector-1724183550035.log)

Re-open issue?
