### ISSUE TITLE
Room filtering very slow on nightly.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#16952] opened 2021-04-14 11:06 UTC
To reproduce:
- be in ~750 rooms
- type in something to the room list filter
- wait 20 seconds whilst it churns (it does eventually seem to filter successfully)

**Comment by SimonBrandner** [comment] 2021-04-14 13:43
Is this a duplicate of [#14750](https://github.com/vector-im/element-web/issues/14750) or is this pointing to regression perhaps?

**Comment by turt2live** [comment] 2021-04-14 14:39
Almost certainly a duplicate of https://github.com/vector-im/element-web/issues/14750

**Closed by turt2live** 2021-04-14 14:39 UTC
Labels: A-Room-List, A-Search, T-Defect
