### ISSUE TITLE
Unable to decrypt messages

### ISSUE THREAD

**Issue by asdil12** [vector-im/element-web#20156] opened 2021-12-13 10:43 UTC
### Steps to reproduce

I have two devices - one android device and one desktop client.
When one of these devices was offline while I received some messages on the other device, it very often shows this error in the client instead of the messages. This also happens for messages I sent from my other device while the first device was offline:
`Unable to decrypt: The sender's device has not sent us the keys for this message.`

Clicking this button in the message to try to get the key usually doesn't really work (eg on the desktop app, unless I open the android app on my phone, but sometimes that doesn't help either).

What does help nearly always is going to `Settings` -> `Security` -> `Restore Keys from Backup`.

#### What did you expect?
All messages shown.

#### What happened instead?
Unable to decrypt messages.

### Operating system

openSUSE

### Application version

1.9.6

### How did you install the app?

via RPM from default repo

### Homeserver

im.f3l.de

### Will you send logs?

No

**Comment by dbkr** [comment] 2021-12-13 12:50
We would need logs from both the sending and receiving device to usefully debug this

**Comment by fabric-and-ink** [comment] 2021-12-22 12:08
Same for me, this is typically when trying to get the keys on the element-web from an android client. Element-web vs element-web works fine. Not sure how to provide logs but I can consistently reproduce this since more than a year.

**Comment by robintown** [comment] 2022-04-24 19:38
Closing, as we are unable to take action on this without logs (they can be submitted via the Feedback button)

**Closed by robintown** 2022-04-24 19:38 UTC
Labels: T-Defect, X-Needs-Info

**Comment by fabric-and-ink** [comment] 2022-11-06 10:11
Checked again today and works now!
