### ISSUE TITLE
You have to go through space home to change power levels

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17558] opened 2021-06-04 18:39 UTC
If you open the members using right-click menu and you also aren't viewing the space's home, the members panel doesn't allow you to change a user's power level

**Comment by t3chguy** [comment] 2021-06-04 18:44
Duplicate of https://github.com/vector-im/element-web/issues/17018

**Closed by t3chguy** 2021-06-04 18:44 UTC
Labels: A-Spaces, T-Defect, X-Needs-Design

**Comment by SimonBrandner** [comment] 2021-06-04 18:46
I commented on that issue and I don't remember it's existence? Good job Šimon! 😅
