### ISSUE TITLE
UI Enhancement: Fix Bullet Point Spacing on Web/Desktop/Android

### ISSUE THREAD

**Issue by 8227846265** [vector-im/element-web#24677] opened 2023-02-27 10:14 UTC
#### What would you like to do?

Fix the spacing of bullet points, currently it looks stupid and doesn't make sense! I'm fed up with seeing this UI spacing on the bullet points for the past few weeks. Hence, I'm posting this as an issue.

The screenshot is created based on the latest stable version of their respective platforms.

On Element Desktop > Thread View
![image](https://user-images.githubusercontent.com/66582769/221534470-9e8b8459-02a2-4708-8a0c-6b988b4b8cb8.png)

The same message but on Element Android
![image](https://user-images.githubusercontent.com/66582769/221534794-fd3b3412-314b-4349-8194-41ebcb4bb37f.png)

This should be a high priority issue since bullet points are an essential function of Element.

#### Why would you like to do it?

I use bullet points a lot for various purposes (e.g. Note-Taking). The spacing of the bullet points looks stupid. I don't know how and why this UI even passed. No offense, but it really looks ugly honestly.

### Have you considered any alternatives?

Please look at the glorious bullet point UI spacing in GitHub

Item A:

- Lorem Ipsum
- Lorem Ipsum
- Lorem Ipsum

Item B:

- Lorem Ipsum
- Lorem Ipsum
- Lorem Ipsum

Item C:

- Lorem Ipsum
- Lorem Ipsum
- Lorem Ipsum

### Additional context

I don't know if it's just me. I notice things posted on https://github.com/vector-im/element-meta/discussions doesn't get any meaningful traction, wherein there's no weekly or monthly review of ideas that are considered/rejected/work-in-progress.

While, if it's posted under `Issues` of element-web. It gets at least someone who adds proper labels on the post.

**Comment by t3chguy** [comment] 2023-02-27 10:18
Duplicate of https://github.com/vector-im/element-web/issues/24602

**Closed by t3chguy** 2023-02-27 10:18 UTC
Labels: T-Enhancement
