### ISSUE TITLE
pills should use the same display name as message sender

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#16418] opened 2021-02-09 15:48 UTC
**Is your suggestion related to a problem? Please describe.**
There is a discrepancy between the displayed names and pills across all elements currently:
![image](https://user-images.githubusercontent.com/2803622/107364295-8b287a80-6adb-11eb-9ffb-7bb4b5764368.png)
Display names in pills are (re-)resolved based on the current (newest) room state, i.e. will be refreshed upon switching to another room and back. Message sender names are resolved based on the room state at the point in time the message was sent, i.e. are "historically accurate".

**Describe the solution you'd like**
Neither solution is perfect, but it seems obvious that both display names should match.

As to which one is the better choice see #16419.

**Describe alternatives you've considered**
- Use MXID: constant, but hard to make the connection to possibly drastically different display name.

**Additional context**
- #16419
- MXID as fallbacks in fluffychat #16262

**Comment by t3chguy** [comment] 2021-02-09 15:50
Duplicate of https://github.com/vector-im/element-web/issues/4677

**Closed by t3chguy** 2021-02-09 15:50 UTC
Labels: suggestion
