### ISSUE TITLE
Trying to publish a room which is blocked by the server doesn't do anything

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9467] opened 2019-04-14 21:04 UTC
Synapse can return 403 forbidden for the request, however the toggle swallows errors. We should at least give a dialog like we do for room aliases.

**Comment by t3chguy** [comment] 2023-06-09 10:38
Duplicate of https://github.com/vector-im/element-web/issues/8632

**Closed by t3chguy** 2023-06-09 10:38 UTC
Labels: T-Defect, P1, A-Room-Settings
