### ISSUE TITLE
Attempting to join a Jitsi video call fails when you have no display name set

### ISSUE THREAD

**Issue by hanthor** [vector-im/element-web#25510] opened 2023-06-01 19:02 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
in a regular room from a user account with a blank display name

3. What do you click?
The video call button

5.Join the video call, it never joins

#### What did you expect?
Be able to join a Jitsi call, even from a nameless user

#### What happened instead?
It gets stuck loading

### Operating system

Windows, MacOS

### Browser information

chrome 113

### URL for webapp

app.element.io

### Application version

1.11.26

### Homeserver

1.80

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-06-02 09:28
@hanthor  Unfortunately I cannot reproduce your issue. Please update your issue with more information. If we don’t hear back from you in a week, we will close the issue as we need to be able to reproduce it before we can fix it.

I have tested with a user with a blank display name. Jitsi falls back to the MXID in this case for me. I would also recommend to update to a more recent client version of Element Web. app.element.io currently ships 1.11.31 . Did you use another environment?

**Comment by t3chguy** [comment] 2023-07-13 13:37
Closing due to no response & cannot repro

**Comment by hanthor** [comment] 2023-07-18 17:46
I'm able to re-pro on bluk created users with no display name set.

[console-export-2023-7-18_13-44-55.txt](https://github.com/vector-im/element-web/files/12084452/console-export-2023-7-18_13-44-55.txt)

Not much in the way of output to console. I have a screen recording, but I have no idea how to increase the logging to get something helpful

**Comment by t3chguy** [comment] 2023-07-19 10:02
Cannot reproduce either. Can you share the screen recording?

**Comment by hanthor** [comment] 2023-07-19 14:47
https://drive.google.com/file/d/1AKbBMHUGJKqyObCad8zB2nZf1ATHDfar/view?usp=sharing

**Comment by hanthor** [comment] 2023-07-19 14:48
I can give access to the instance too if you want

**Comment by t3chguy** [comment] 2023-07-19 15:46
@hanthor if it can't be reproduced on a public server + public instance its unlikely to be dealt with by the team, I'd suggest trying to reproduce it there

**Comment by hanthor** [comment] 2023-07-19 17:02
Well, it's affecting pain customers on ESS. The only way I know how to create it is using the both user creation with synapse admin.

I could maybe set up an ENS cloud host, but I don't think there's a way to reproduce it on a public public server

**Comment by hanthor** [comment] 2023-07-19 17:02
Actually scratch that I probably can't reproduce it on EMS Cloud host since it uses mute.element.io for jitsi

**Comment by hanthor** [comment] 2023-07-21 17:01
I can give anyone access to the server with a login so that you can repro the issue

**Comment by daniellekirkwood** [comment] 2023-07-24 10:32
Stepping in -- I've been given more context to this issue and we'll need to find the right place for it to slot into our backlog somewhere. I will discuss this with @Johennes this afternoon and we'll discuss online and in Element in the following days :) 

Please do not close this issue until it's resolved for @hanthor !

**Comment by weeman1337** [comment] 2023-07-25 14:58
Synapse issue: https://github.com/matrix-org/synapse/issues/16000

**Closed** 2023-07-26 10:18 UTC
Labels: T-Defect, X-Cannot-Reproduce, A-Jitsi, Z-Retainer
