### ISSUE TITLE
Unencrypted messages after encryption was turned on.

### ISSUE THREAD

**Issue by madduck** [vector-im/element-web#12313] opened 2020-02-11 01:00 UTC
![image](https://user-images.githubusercontent.com/195073/74204008-5fab5e00-4cd6-11ea-9da2-5360e45a953c.png)

My colleague turned on encryption. The next couple of messages I sent from Riot-Web still went unencrypted. Then, a message sent from Android to the room was encrypted properly. And when I went to create this bug report, also Riot-Web sent encrypted messages.

Maybe the keys took a bit longer to exchange, but Riot should definitely not claim that it turned on encrypted, and then proceed to send unencrypted messages.

riot-web version: 1.5.7.9
olm version: 3.1.3
FF: 72.0.2

**Comment by kittykat** [comment] 2021-11-30 17:53
I'm going to close this issue as we cannot reproduce it any more. If you are still experiencing it, please comment with @kittykat and I will reopen it.

**Closed by kittykat** 2021-11-30 17:53 UTC
Labels: T-Defect, A-E2EE, X-Needs-Community-Testing
