### ISSUE TITLE
Track the verified status of keys that have been backed up or shared

### ISSUE THREAD

**Issue by DemiMarie** [vector-im/element-web#26041] opened 2023-08-24 00:42 UTC
#### What would you like to do?

Be able to validate the authenticity of messages in new sessions.

#### Why would you like to do it?

Obvious security reasons.

#### How would you like to achieve it?

Key backups should include enough information to validate the authenticity of the keys being backed up, and key sharing should include enough information to verify that the keys being shared are authentic.

### Have you considered any alternatives?

None.

**Comment by t3chguy** [comment] 2023-08-24 09:24
Duplicate of https://github.com/vector-im/element-web/issues/14323

**Closed by t3chguy** 2023-08-24 09:24 UTC
Labels: T-Enhancement
