### ISSUE TITLE
Element-Desktop and Element-Android do not respect choice of Jitsi server

### ISSUE THREAD

**Issue by eganonoa** [vector-im/element-web#15951] opened 2020-12-11 20:42 UTC
In a self-hosted instance we have set it so that starting a conference call in a room will launch our own jitsi server rather than the standard jitsi.riot.im by setting the preferred domain in the config.json to our jitsi server.  This works perfectly in the web-app.  But the desktop and android apps do not respect the choice and default to jitsi.riot.im with no way to launch a call in our own server.  

Because of the ability to pin conference calls this isn't the end of the world, as we can create and pin the web-app and then always launch on our server no matter which app being used (web, desktop or mobile). But it does prevent a functional default to own servers being used and presumably means that there is additional load on jitsi.riot.im that there shouldn't be.

OS = Debian Buster (both server and workstation)
Desktop App Version = 1.7.14 (flatpak) & 1.7.15 (apt) (tried both)
Android Version = 1.0.11
Web Version = 1.7.6

**Comment by t3chguy** [comment] 2020-12-11 20:44
Can you explain exactly how you have set the preferredDomain? Can you send debug logs?

Thanks

**Comment by eganonoa** [comment] 2020-12-11 20:57
> Can you explain exactly how you have set the preferredDomain? Can you send debug logs?
> 
> Thanks

Sure thing.  The install overall followed precisely the guide from April 2020: https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi. This means the preferred domain was set in accordance with https://github.com/vector-im/element-web/blob/develop/docs/jitsi.md. We tried the optional extra of setting the /.well-known/matrix/client config to as suggested in the latter link, reloading the server and refreshing the clients, but that had no impact.

Logs sent from the Flatpak version.

**Comment by t3chguy** [comment] 2020-12-11 21:12
well-known has since been removed, debugging will continue probably after the weekend

**Comment by TheTimeWalker** [comment] 2021-02-01 08:58
Any news about this? I can confirm that overriding with "im.vector.riot.jitsi" does not work with Element Desktop in 1.7.18 but works with Element Web (Firefox browser) and, different to OP, works on Element Android.

**Comment by eganonoa** [comment] 2021-02-01 09:15
> Any news about this? I can confirm that overriding with "im.vector.riot.jitsi" does not work with Element Desktop in 1.7.18 but works with Element Web (Firefox browser) and, different to OP, works on Element Android.

Sorry, this is my fault. I ended up getting incredibly busy and not restarting the conversation despite the very proactive response from @t3chguy .  In the end I realized that the problem is very isolated to only a few apps (e.g. Element Desktop) and has a super-simple workaround.  Basically, you don't try to launch the jitsi call for the first time via the widget. Instead, once you have 3 or more people in the room, you simply press the call button and it will launch the jitsi linked to your own server. This appears to work for me regardless of the app used, which means the bug appears to be limited to only certain apps and only when trying to call the call via the widget instead of the call button.

**Comment by TheTimeWalker** [comment] 2021-02-01 10:01
Hmm, for me the call and video call button still redirect to the wrong Jitsi in my case. Widget works fine since I'm on a home server with Dimension installed that has set the private Jitsi instance as default.

**Comment by eganonoa** [comment] 2021-02-01 10:04
> Hmm, for me the call and video call button still redirect to the wrong Jitsi in my case. Widget works fine since I'm on a home server with Dimension installed that has set the private Jitsi instance as default.

Before trying had you completely removed the widget that you had previously started? I found that once the widget was set to go via jitsi meet there was nothing you could do to stop that happening.  I had to completely remove the widget and then make the call.

**Comment by TheTimeWalker** [comment] 2021-02-01 10:18
Yes, always completely removing the widget before starting a new call. Actually worse, I have to remove it via the Widget options as trying to click the hang-up button actually doesn't work - probably because of the "im.vector.riot.jitsi" bug.

**Comment by eganonoa** [comment] 2021-02-01 11:33
Just tried again and I'm now experiencing the same using the latest linux flatpak version of the Element app. I did remove the preferredDomain from the .well-known client config. So would need to re-enable to see if that makes a difference.

**Comment by TheTimeWalker** [comment] 2021-02-18 13:10
Tried it out again at Element Desktop 1.7.21 and it seems like the bug has been fixed. The video call button correctly goes over to my by well-known configured Jitsi instance

**Comment by jryans** [comment] 2021-03-05 17:51
Hmm, it sounds like this is possibly fixed, so I'll close this for now. Feel free to reopen if I misunderstood.

**Closed by jryans** 2021-03-05 17:51 UTC
Labels: A-Jitsi, P2, S-Minor, T-Defect

**Comment by WizWareTech** [comment] 2021-06-13 00:57
I am having this problem as well, even with Element version: 1.7.30 (Windows). I have also tried Android and Web client and none of them pay attention to the directives in client:

(domain.com replaced my actual)

{
"m.homeserver": {
"base_url": "https://matrix.domain.com"
},
"m.identity_server": {
"base_url": "https://vector.im"
},
"jitsi": {
"preferredDomain": "jitsi.domain.com"
},
"im.vector.riot.jitsi": {
"preferredDomain": "jitsi.domain.com"
},
"io.element.e2ee": {
"default": true
}
}

**Comment by WizWareTech** [comment] 2021-06-13 01:27
Ok, I think I figured out where the bug is. If you add the widget use 'Edit widgets, bridges & bots', it does NOT use the well-known data. It only uses that if you have 3+ people in a room and click on the call buttons. This is definitely a bug, and seems to occur no matter what I use (web, windows, android, iphone). Is there a file that can be edited on the server for the widget itself to change the default URL that is displayed when someone tries to add the Jitsi widget?

**Comment by t3chguy** [comment] 2021-06-14 21:10
Modular/Scalar (the default integrations manager) indeed does not look at your config.json or well-known, you should set up a Dimension instance connected to your Jitsi for the `Edit widgets, bridges & bots` to work. https://dimension.t2bot.io/

**Comment by janonym1** [comment] 2022-01-25 12:55
When setting up your own Jitsi with Dimension, "[an admin user needs to configure the domain via the admin ui once dimension is running. In Element, go to Manage Integrations → Settings → Widgets → Jitsi Conference Settings and set Jitsi Domain and Jitsi Script URL appropriately](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-dimension.md)" 

However, when you add a Jitsi Widget by hand, it still showed riot.im within the dimension manager but in reality, my own domain was used correctly (when looking at the network traffic itself). I dont know if the same thing happens with the all of the desktop clients but it could be a source of confusion
