### ISSUE TITLE
Red fonts flicker

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18733] opened 2021-08-24 19:39 UTC
### Steps to reproduce

1. Have red (usually bold) text on screen
2. Change rooms
3. Note the lag with the CSS catching up

### What happened?

I don't know why, but it seems to only affect red text (mentions, Dismiss button of toasts, etc). Other text seems unaffected.

Example: Here's two stills for what is going on:
![1](https://user-images.githubusercontent.com/1190097/130679170-c84fe373-0357-49c5-ac06-64b290e334e5.png)
![2](https://user-images.githubusercontent.com/1190097/130679172-aa1b75b5-8bed-4824-942a-cd0647cfbce0.png)

That's not super clear on its own, so here's a gif of the same thing (the Dismiss button text is what to watch for):
![out](https://user-images.githubusercontent.com/1190097/130679224-aab1fa34-13e7-4705-9d8f-3169d4d1bd47.gif)

It's not a rendering artifact: it actually does that. The outline also appears to get *more red* in the transition.

### What did you expect?

For the font size/weight to be stable.

### Operating system

Windows 10

### Application version

Nightly (2021-08-24)

### How did you install the app?

The Internet

### Have you submitted a rageshake?

No

**Comment by Palid** [comment] 2021-09-02 16:43
@turt2live that looks like another problem with fonts antialiasing. I can clearly see it going from subpixel to grayscale in this, which makes it behave weirdly.

**Comment by Palid** [comment] 2021-09-02 16:55
It seems to have been fixed by the general css fixes with background blur & contain statements. I can't really reproduce it at all.

**Closed by Palid** 2021-09-02 16:55 UTC
Labels: T-Defect, X-Regression, S-Major, A-Electron-Nightly, A-Toast, O-Intermediate
