### ISSUE TITLE
Unable to load room in latest nightly

### ISSUE THREAD

**Issue by 33Fraise33** [vector-im/element-web#20433] opened 2022-01-07 12:24 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
When opening a certain room I get: "something went wrong" 
This room does work on mobile, clearing cache and reloading does not help
2. What do you click?
I clicked a certain room, this room is bridged with a telegram room through [mautrix/telegram](https://github.com/mautrix/telegram)

#### What did you expect?
To be able to view the room

#### What happened instead?
"Something went wrong"

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022010701 Olm version: 3.2.8

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin/

### Homeserver

matrix.frai.se

### Will you send logs?

Yes

**Comment by 33Fraise33** [comment] 2022-01-07 12:26
I have uploaded my logs through element but I am unsure if I should be able to see them here?

**Comment by t3chguy** [comment] 2022-01-07 12:26
No, logs are privately uploaded.

**Comment by t3chguy** [comment] 2022-01-07 12:28
@toger5 this may be related to right panel store changes, this is a UserInfo panel being rendered without a `user` prop even though it is most certainly required

**Comment by toger5** [comment] 2022-01-07 16:04
@33Fraise33 I could not reproduce the exact issue you had. The fix got merged so reloading develop should fix it. I will reopen this issue for now. You can close it if it solves it on your end as well.

**Comment by t3chguy** [comment] 2022-01-10 10:53
Closing, if the issue does recur please shout!

**Closed by t3chguy** 2022-01-10 10:53 UTC
Labels: T-Defect, X-Regression, S-Critical, X-Release-Blocker, A-User-Info, Z-Rageshake, Z-Soft-Crash, O-Occasional

**Comment by 33Fraise33** [comment] 2022-01-10 12:18
This seems to be resolved for me
