### ISSUE TITLE
PageUp/PageDn broken in Web 1.7.30

### ISSUE THREAD

**Issue by erAck** [vector-im/element-web#17633] opened 2021-06-11 23:34 UTC
### Description

In Web 1.7.30 PageUp/PageDn page the timeline only if the room's chat area / timeline frame has the focus. e.g. after having clicked on it somewhere. The timeline can not be paged if any other element has the focus, which is specifically awkward when traveling rooms with the keyboard (e.g. Alt+Down) or when in the composer edit field.

This worked in previous versions.

### Steps to reproduce

- enter any room, clicking on it or via Alt+Down
- press PageUp
- nothing happens

Timeline should page back.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox; versions 78.11.0 and 88.0.1
- **OS**: Linux, Debian and Fedora
- **URL**: any Matrix room

**Comment by robintown** [comment] 2021-06-12 00:37
Duplicate of #17588, which is fixed on develop

**Closed** 2021-06-12 00:39 UTC
Labels: T-Defect
