### ISSUE TITLE
Room ID

### ISSUE THREAD

**Issue by Wolfgang-lobo** [vector-im/element-web#15728] opened 2020-11-14 21:18 UTC
### Description

I need my room ID to enter the first room I just created- Für Montagsdemo - progessive online meeting kann keine Vorschau erzeugt werden. Möchtest du den Raum betreten? - If I click the button it says: No known servers.  I am erbewo
@erbewo:matrix.org. Could you please give me a hint. Please mail to: erbewo@gmx.net Thanks a lot. Wolfgang Erbe
Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by t3chguy** [comment] 2020-11-14 22:40
Duplicate of https://github.com/vector-im/element-web/issues/2925 - You should create a Room Address, as Room IDs are not routable over federation.

**Closed by t3chguy** 2020-11-14 22:40 UTC

**Comment by Wolfgang-lobo** [comment] 2020-11-14 23:16
Thank you for help. It's the first time I work here. I understand now. I must do/create those rooms step by step. My fault was to start in the middel of no where. Instead of going step by step in creating my personal room.
Thanks a lot Wolfgang
