### ISSUE TITLE
Systray icon on KDE Plasma not monochrome

### ISSUE THREAD

**Issue by riidom** [vector-im/element-web#25155] opened 2023-04-19 13:42 UTC
### Steps to reproduce

Having the "minimize to systray icon" option active, so a systray icon appears in first place.

#### What did you expect?

In the systray all icons should have a transparent background and white or black foreground color, depending on theme.

#### What happened instead?

The icon is colored (green background, white icon).

### Operating system

Kubuntu 22.04

### Application version

Version von Element: 1.11.28 // Version von Olm: 3.2.12

### How did you install the app?

Flatpak (there is some `--file-forwarding im.riot.Riot` if that's important)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-04-19 14:11
Duplicate of https://github.com/vector-im/element-desktop/issues/757

**Closed by t3chguy** 2023-04-19 14:11 UTC
Labels: T-Defect
