### ISSUE TITLE
List better search results in room list when search has two or more words

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18808] opened 2021-08-27 10:24 UTC
### Steps to reproduce

1. In the left panel, search for the first and last word in a room name of a room which has at least three words in the name

### What happened?

![Screenshot from 2021-08-27 11-03-53](https://user-images.githubusercontent.com/51663/131112623-680c948e-db27-4046-88a9-98354ec9b8f3.png)

### What did you expect?

![Screenshot from 2021-08-27 11-04-14](https://user-images.githubusercontent.com/51663/131112643-ba51734e-be94-4339-9b25-859ef99a3ada.png)

### Acceptance criteria for fix
- [ ] Search results suggest partial matches
- [ ] Full matches are higher in the results list than partial matches

### Operating system

All

### Browser information

All

### URL for webapp

develop.element.io

### Homeserver

n/a

### Have you submitted a rageshake?

No

### Seealso
#18409

**Comment by t3chguy** [comment] 2021-08-31 16:22
Duplicate of https://github.com/vector-im/element-web/issues/14410

**Closed by t3chguy** 2021-08-31 16:22 UTC
Labels: T-Defect, S-Major, A-Room-List, A-Search, Z-Papercuts, O-Intermediate
