### ISSUE TITLE
Offer to recompress pasted images from clipboard to save server bandwidth

### ISSUE THREAD

**Issue by EvocativeOlash** [vector-im/element-web#17900] opened 2021-07-07 06:00 UTC
#### Is your suggestion related to a problem? Please describe.

Users often paste images from clipboard as the fastest way, but they seem to be uncompressed and take up 10x the size of the jpg adding excessive burden to servers for no good reason.

#### Describe the solution you'd like.
A dialog for recompression on paste

#### Describe alternatives you've considered.
n/a

#### Additional context
n/a

**Comment by SimonBrandner** [comment] 2021-07-07 06:01
Duplicate of https://github.com/vector-im/element-web/issues/14047

**Closed by SimonBrandner** 2021-07-07 06:01 UTC
Labels: T-Enhancement
