### ISSUE TITLE
Session verification hangs on "COMPARE EMOJI" (when verifying itself)

### ISSUE THREAD

**Issue by codewiz** [vector-im/element-web#16888] opened 2021-04-08 11:53 UTC
### Description

The web UI shows that the *current* session is untrusted. So I click to verify it, select "Interactively verify by Emoji", and a spinner appears... but the emojis never show up.

### Steps to reproduce

- Go to any room
- Select your own avatar
- In the list under "SECURITY" select an untrusted session (probably, the bug is only reproducible by choosing the current session)
- Select "Interactively verify by Emoji"

Describe how what happens differs from what you expected.

A spinner appears, and never goes away.
I expect to see a bunch of emojis :sob:

### Version information

- **Platform**: web
- **Browser**: Chromium 89.0.4389.114
- **OS**: Arch Linux
- **URL**: app.element.io

Console log:
```
index.js:218 GET https://matrix-client.matrix.org/_synapse/admin/v1/users/%40bernie%3Amatrix.org/admin 403
(anonymous) @ index.js:218
t @ index.js:179
(anonymous) @ browser-index.js:29
_request @ http-api.js:716
requestOtherUrl @ http-api.js:594
request @ http-api.js:549
authedRequest @ http-api.js:492
F.isSynapseAdministrator @ client.js:5049
(anonymous) @ UserInfo.tsx:947
rs @ react-dom.production.min.js:211
fc @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vr @ react-dom.production.min.js:122
gc @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
U @ scheduler.production.min.js:17
w.port1.onmessage @ scheduler.production.min.js:14
rageshake.js:65 Error decrypting event (id=$i_o5_QmYPBfvqO737sfmF2l4OPnRqf8pgdgX6jfBoqY): DecryptionError[msg: The secure channel with the sender was corrupted. Trying to create a new secure channel and re-requesting the keys., session: 94QR5ZWJ8GFCDXtTY+IDEMVQG3l0uur7EPn91IW612A|l4PbrpaoXP9uztc3Z/kGNK0QEV9ISAbxdKu0aGHcF80]
e.<computed> @ rageshake.js:65
(anonymous) @ logger.ts:50
_decryptionLoop @ event.js:552
async function (async)
_decryptionLoop @ event.js:495
attemptDecryption @ event.js:445
(anonymous) @ client.js:5522
(anonymous) @ sync.js:1530
m._mapSyncEventsFormat @ sync.js:1526
(anonymous) @ sync.js:1161
I @ utils.ts:740
async function (async)
I @ utils.ts:739
m._processSyncResponse @ sync.js:1158
m._sync @ sync.js:777
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:744
m._sync @ sync.js:820
async function (async)
m._sync @ sync.js:762
rageshake.js:65 Starting load of AsyncWrapper for modal
rageshake.js:65 Refreshing/starting the verification transaction timeout timer
rageshake.js:65 downloadKeys: already have all necessary keys
rageshake.js:65 PUT /sendToDevice/m.key.verification.start/m1617881853119.4 {@bernie:matrix.org: Array(1)}
rageshake.js:65 Verification request s9MPO9Gi6KVaiQWtn1tQeTe4YseTBpjv: m.key.verification.start event with id:undefined, content:{"method":"m.sas.v1","from_device":"NJWQCJKZWH","key_agreement_protocols":["curve25519-hkdf-sha256","curve25519"],"hashes":["sha256"],"message_authentication_codes":["hkdf-hmac-sha256","hmac-sha256"],"short_authentication_string":["decimal","emoji"],"transaction_id":"s9MPO9Gi6KVaiQWtn1tQeTe4YseTBpjv"} deviceId:NJWQCJKZWH, sender:@bernie:matrix.org, isSentByUs:true, isLiveEvent:true, isRemoteEcho:true, phase:1=>4, observeOnly:false=>false
rageshake.js:65 received to_device m.key.verification.start from: @bernie:matrix.org id: undefined
rageshake.js:65 Verification request s9MPO9Gi6KVaiQWtn1tQeTe4YseTBpjv: m.key.verification.start event with id:undefined, content:{"method":"m.sas.v1","from_device":"NJWQCJKZWH","key_agreement_protocols":["curve25519-hkdf-sha256","curve25519"],"hashes":["sha256"],"message_authentication_codes":["hkdf-hmac-sha256","hmac-sha256"],"short_authentication_string":["decimal","emoji"],"transaction_id":"s9MPO9Gi6KVaiQWtn1tQeTe4YseTBpjv"} deviceId:NJWQCJKZWH, sender:@bernie:matrix.org, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:4=>4, observeOnly:false=>false
```

**Comment by codewiz** [comment] 2021-04-08 11:54
Also reproducible with develop.element.io

**Comment by codewiz** [comment] 2021-04-08 12:06
Also reproducible on Firefox 87.0 and using a different session

**Comment by jryans** [comment] 2021-04-08 12:20
What happens if you try to verify the problem session from a different device (instead from itself)?

**Comment by codewiz** [comment] 2021-04-09 09:13
Same result from the phone app:
![Uploading Screenshot_20210409-133830.jpg…]()

**Comment by codewiz** [comment] 2021-04-09 09:16
Could this be a server-side issue with my account state on matrix.org?

**Comment by codewiz** [comment] 2021-04-09 09:31
> Same result from the phone app:
I'm sorry, a verification request actually appeared in the web app. I hadn't noticed it because there were no notifications and the tab wasn't marked as needing attention.

This could be filed as two separate usability bugs:
 - verification requests should send a notification and call attention to the browser tab
 - the session sending a verification request should display a message besides the spinner, such as: "Please confirm the notification request on another session"

**Comment by codewiz** [comment] 2021-04-09 10:03
Are those `undefined` ids expected in the logs of a successful transaction?
```
rageshake.js:65 Verification request s9MPO9Gi6KVaiQWtn1tQeTe4YseTBpjv: m.key.verification.start event with id:undefined, content:{"method":"m.sas.v1","from_device":"NJWQCJKZWH","key_agreement_protocols":["curve25519-hkdf-sha256","curve25519"],"hashes":["sha256"],"message_authentication_codes":["hkdf-hmac-sha256","hmac-sha256"],"short_authentication_string":["decimal","emoji"],"transaction_id":"s9MPO9Gi6KVaiQWtn1tQeTe4YseTBpjv"} deviceId:NJWQCJKZWH, sender:@bernie:matrix.org, isSentByUs:true, isLiveEvent:true, isRemoteEcho:true, phase:1=>4, observeOnly:false=>false
rageshake.js:65 received to_device m.key.verification.start from: @bernie:matrix.org id: undefined
rageshake.js:65 Verification request s9MPO9Gi6KVaiQWtn1tQeTe4YseTBpjv: m.key.verification.start event with id:undefined, content:{"method":"m.sas.v1","from_device":"NJWQCJKZWH","key_agreement_protocols":["curve25519-hkdf-sha256","curve25519"],"hashes":["sha256"],"message_authentication_codes":["hkdf-hmac-sha256","hmac-sha256"],"short_authentication_string":["decimal","emoji"],"transaction_id":"s9MPO9Gi6KVaiQWtn1tQeTe4YseTBpjv"} deviceId:NJWQCJKZWH, sender:@bernie:matrix.org, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:4=>4, observeOnly:false=>false
```

**Comment by ShadowJonathan** [comment] 2021-12-16 17:14
Cannot reproduce, the current behaviour is to show "verify this session", with then "verify with another login".

If i press it when navigating to members -> my user, then i get a popup regarding secure backup.

**Comment by kittykat** [comment] 2021-12-16 17:20
I'm going to close this issue for now because we believe it has been resolved. Please open a new issue with a rageshake if you experience the problem again. Thank you!

**Closed by kittykat** 2021-12-16 17:20 UTC
Labels: T-Defect, P1, S-Minor, A-E2EE-Cross-Signing, X-Needs-Community-Testing
