### ISSUE TITLE
Add a hotkey to jump to next unread notification

### ISSUE THREAD

**Issue by maralorn** [vector-im/element-web#22305] opened 2022-05-21 17:33 UTC
#### What would you like to do?

I would like to have a hotkey to jump to the next unread *notification* (as opposed to next unread room).

#### Why would you like to do it?

I am in a lot of rooms and I don’t read all of them. But I want to read all my notifications (because I have configured them accordingly.)
The `Alt+Shift+Up` hotkey is not helpful for that, because it just jumps to any unread room, not just to rooms with unread notifications.

#### How would you like to achieve it?

I don‘t care a lot about which hotkey to use.

### Have you considered any alternatives?

In my particular case other ways to jump to unread notifications would also be helpful. A button at the top for example or a clickable number on the notification sidebar bell. It’s for example quite annoying to jump to an unread room, when the people list is expanded because you need to scroll down first.

A related issue is, that since a while ago you can‘t go to notifications by clicking the notification count on a list like "rooms" or "favorites" because the number disappears on mouse over and get’s replaced by a "list options".

Another helpful way to find notifications would be if the "notifications" side bar would actually contain all notifications and not just mentions.

**Comment by robintown** [comment] 2022-05-21 19:09
Duplicate of https://github.com/vector-im/element-web/issues/21876

**Closed by robintown** 2022-05-21 19:09 UTC
Labels: T-Enhancement
