### ISSUE TITLE
Show mutual rooms in user profile

### ISSUE THREAD

**Issue by resynth1943** [vector-im/element-web#15492] opened 2020-10-19 08:29 UTC

**Comment by Half-Shot** [comment] 2020-10-19 08:33
This is implemented in https://github.com/matrix-org/matrix-react-sdk/pull/4897, however it's continuing to rot due to not design :(

**Comment by t3chguy** [comment] 2020-10-19 08:34
Duplicate of #14339

**Closed by t3chguy** 2020-10-19 08:34 UTC
