### ISSUE TITLE
Linkify ircs protocol handler and forward it to the system

### ISSUE THREAD

**Issue by SuperSandro2000** [vector-im/element-web#17447] opened 2021-05-24 02:25 UTC
#### Is your suggestion related to a problem? Please describe.
I want to click on [ircs://irc.hackint.org/nixos](ircs://irc.hackint.org/nixos)

#### Describe the solution you'd like.
Elements should convert that into a link I can click on.

#### Describe alternatives you've considered.
Copy paste it into my browser which opens my IRC client.

**Comment by t3chguy** [comment] 2021-05-24 07:53
Duplicate of https://github.com/vector-im/element-web/issues/15018

**Closed by t3chguy** 2021-05-24 07:53 UTC
Labels: A-Timeline, P4, T-Enhancement
