### ISSUE TITLE
Support for incoming webhooks

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#4978] opened 2017-09-05 12:11 UTC
- for integration with other projects.

Rocketchat have this, for example:  https://rocket.chat/docs/administrator-guides/integrations

**Comment by turt2live** [comment] 2017-09-05 12:53
I'm not sure what the intended scope of the issue is, but I have a bridge for this: https://github.com/turt2live/matrix-appservice-webhooks

**Comment by kvark** [comment] 2019-12-21 17:14
Newbie here. Tried to see how to set up github event notifications in a Matrix room similar to the way Gitter has it, and the only option is to allow the official Github bot to access everything at the admin level... this is by far not acceptable. We need a webhooks-based way of receiving notifications without asking for any access to Github at all.

**Comment by t3chguy** [comment] 2019-12-21 17:18
@kvark riot is just a matrix client, you might want to look at go-neb or Travis' bridge above. Riot doesn't run whilst your browser isn't open so can't do things like webhooks

**Comment by t3chguy** [comment] 2022-05-17 10:57
Closing as Element runs entirely in the browser, there's also a bridge linked above which is capable of this

**Closed by t3chguy** 2022-05-17 10:57 UTC
Labels: P3, T-Enhancement
