### ISSUE TITLE
Inconsistent DM backgrounds

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#13489] opened 2020-05-04 12:10 UTC
<img width="497" alt="Screenshot 2020-05-04 at 13 03 52" src="https://user-images.githubusercontent.com/4626865/80964436-c5f0da00-8e08-11ea-9ccd-c302c7eb07c2.png">

Background fills are inconsistent between the room list & avatars in the timeline/room title/user profiles. There's 2 different issues happening in this screenshot, where this issue is concerned with the former bug:

- We only specify 3 colours for avatar fills (green, blue or purple) which should be consistent wherever (room list avatar, room title avatar, timeline avatar, anywhere else?), unlike this screenshot.
- Relatedly, we should consider [unifying user colours & avatar fills](https://github.com/vector-im/riot-web/issues/13490)

**Comment by robintown** [comment] 2021-07-16 04:24
Duplicate of #2449

**Closed by robintown** 2021-07-16 04:24 UTC
