### ISSUE TITLE
tags not remember his state (enable or disable)

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#9395] opened 2019-04-05 23:41 UTC
If "group by tags" enabled in labs settings and tags set to rooms - they show at start as circle at left down ("M" and "Z"):

![2](https://user-images.githubusercontent.com/1297163/55661495-6e6feb80-584f-11e9-94b1-7424eaadd7d2.png)

But I must enable it every time after startup - and then this tags show in room list. Enabled state of tags not saved. And at next start riot I must again enable each tags for they show in room list:

![3](https://user-images.githubusercontent.com/1297163/55661577-dc1c1780-584f-11e9-8325-b99905561967.png)

### Version information

For the web app:

- Firefox 66.0.2 64bit
- Ubuntu 16.0.4
- https://riot.im/develop

version riot-web: ab136c42a7fe-react-2ca281f6b7b7-js-0a82c8400696
version olm: 3.0.0

**Comment by lampholder** [comment] 2019-04-29 14:34
I think this is true of all the labs features - they're _per device_ settings, and (as far as Riot's concerned) if you're logging out and then logging in again, that's a brand new 'device'.

**Comment by aaronraimist** [comment] 2019-04-29 14:42
This issue isn’t asking for them to apply to all devices. It is just asking for the tags you clicked to still be included in the room list when you refresh the page.

**Comment by progserega** [comment] 2019-04-30 10:01
Yes - after refresh riot-page - selected tags are all unselecting. I was test this bug on one device.

**Comment by steef435** [comment] 2020-04-16 15:48
It appears that the fold/unfold state of the tag folders are remembered though, so would it be an acceptable quick (hopefully, haven't tried yet) fix to just select all tags on startup?

**Comment by progserega** [comment] 2020-04-17 06:10
May be selct all tags on startup is fine. But more nice solution is save select state of each tugs between startups.

**Comment by turt2live** [comment] 2020-08-31 19:24
I'm considering this a duplicate of https://github.com/vector-im/element-web/issues/8609 as it's a labs feature.

**Closed by turt2live** 2020-08-31 19:24 UTC
Labels: bug, help-wanted, p2, type:llp, type:tags, ui/ux
