### ISSUE TITLE
Email invites land on welcome page with guest disabled

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#10026] opened 2019-06-12 14:34 UTC
If Riot's default HS doesn't have guest access enabled, clicking through on an email invite just lands you on the welcome page with no mention of the room or invite or anything.

**Comment by the-moog** [comment] 2019-06-20 11:11
Ref previous, closed bug #9816. Is that supposed to be fixed in 1.2.2?

Just installed and tried it and the behaviour is similar, still broken.  I'm guessing that is related to this new bug #10026?

In Riot, Invite user that does not already exist by email
User clicks link in email
User gets the empty "Create Your Account" page.  All fields are empty, but the HS and IS are set.
After manually entering the userid, password, email (should not have to do the email)
I now get the Create Your Account page again, this time with "An email has been sent to email@domain", "Please check your email to continue registration", "This validation session has not yet neen completed".
Clicking the 2nd validation email gets a new tab:
There are now two tabs.
The first tab has gone to "Successful Regisration", you can now login
The other new tab has gone back to the first "Create You Account" page.
Clicking the link on the first tab logs in immediately
The user now has the pending invites tab.

So the only issue seems to be the lack of a pre-filled email address on the "Create You Accout" page, this dissapeard a couple revisions ago so should not be difficult to re-introduce.

**Comment by the-moog** [comment] 2019-07-20 12:10
Ok, found the cause, but not sure how to fix it in the correct way.

Clicking the following (altered to prevent spam) invite link:
https://chat.cambsac.org.uk/#/register?email=test1907.1%40gmail.com

Goes to: https://chat.cambsac.org.uk/#/register
This creates the registration form as expected.  But the email field is not pre-filled, which is the issue.

Looking at that page in the debugger, the email IS sent to Registration.js, and is presented to react but it's simply missing from the rendered page.
In the react RegisatrationForm_email component there are two fields for email: 
{
  "id": "mx_RegistrationForm_email",
  "type": "text",
  "label": "Email",
  "defaultValue": "test1907.1@gmail.com",
  "value": "",
  "onChange": "[function ]",
  "placeholder": "Email",
  "onFocus": "[function ]",
  "onBlur": "[function ]"
}

Editing the email value in the React debugger puts the correct text in the form.

So, the defaultEmail value, though present, is not being rendered into the email field on page load.
In RegistrationForm.js, in the function renderEmail:
            defaultValue={this.props.defaultEmail}
            value={this.state.email}
this.state.email is == ""
this.state.defaultEmail == "test1907.1@gmail.com"

I don't know enough about Riot, React and JS to fix this properly, as I can't work out how the clicked URL passes to the Registration.js instance.
I think it might be as simple as at the top of RegistrationForm.js in the function getInitialState(), changing email: "" to email: this.props.defaultEmail

**Comment by the-moog** [comment] 2020-01-29 10:14
Anybody looking at this?  Or can somebody at least let me know if my analysis is in the right direction so that I can have some confidence that should I try to fix it I'm doing so in the correct way?

**Comment by turt2live** [comment] 2020-09-12 02:44
Closing in favour of https://github.com/vector-im/element-web/issues/15130 because I've already referenced that issue in a commit and rebasing doesn't feel worth the effort (sorry).

**Closed by turt2live** 2020-09-12 02:44 UTC
Labels: bug, defect, p1, type:invite, type:threepids
