### ISSUE TITLE
Export/Import app preferences

### ISSUE THREAD

**Issue by haasn** [vector-im/element-web#17408] opened 2021-05-20 05:32 UTC
#### Is your suggestion related to a problem? Please describe.
If I migrate from one account to the other, I need to re-do all of my settings. This is an annoying waste of time.

#### Describe the solution you'd like.
* The ability to export/import app settings, the way I can export/import encryption keys.

#### Describe alternatives you've considered.
* Alternatively, app settings could just be made per-machine rather than per-account. So me logging into a different account on the same machine would retain the same app preferences. I assume there's some reason you didn't already make it this way, though?

**Comment by SimonBrandner** [comment] 2021-05-20 05:37
Duplicate of [#8717](https://github.com/vector-im/element-web/issues/8717)

**Closed by SimonBrandner** 2021-05-20 05:37 UTC
Labels: A-User-Settings, P3, T-Enhancement

**Comment by haasn** [comment] 2021-05-20 05:44
Ah, my bad. I had searched for "preferences", not "settings"

**Comment by SimonBrandner** [comment] 2021-05-20 05:45
No worries :)
