### ISSUE TITLE
Allow marking a room as DM

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#15010] opened 2020-08-20 11:28 UTC
Not sure if this falls under the new room list or the room settings.

The old room list had an option to mark a room as a DM, which the new room list removed. This is problematic since, after my account migration, all of the DMs I had with others were suddenly not marked as DMs anymore (both on my side and on the other party's); and I had to log into an old version of Riot to fix that. It would be nice to bring that option back (maybe in the room settings?).

**Comment by t3chguy** [comment] 2020-08-20 11:34
Duplicate of https://github.com/vector-im/element-web/issues/14942.

**Closed by t3chguy** 2020-08-20 11:34 UTC
