### ISSUE TITLE
Scrolling beyond room list is jerky again

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19555] opened 2021-10-30 13:31 UTC
### Steps to reproduce

It seems #17460 #17565 #18440 has resurfaced.

Not sure if related to #19414.

#### What did you expect?
Scroll to the bottom

#### What happened instead?

https://user-images.githubusercontent.com/2803622/139534634-c12e9e03-5612-41f9-8cde-e7c95ffe18b9.mp4

### Operating system

arch / sway / ozone

### Application version

Element Nightly version: 2021102801 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by robintown** [comment] 2021-10-30 17:37
Duplicate of https://github.com/vector-im/element-web/issues/19322

**Closed by robintown** 2021-10-30 17:37 UTC
Labels: T-Defect
