### ISSUE TITLE
joining a series of invites in rapid succession can leave them infinispinnering until you switch back & forth

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4397] opened 2017-06-22 14:29 UTC

**Comment by lukebarnard1** [comment] 2017-06-23 08:40
This would be because the RVS only expects one join to be ongoing ever, and we've already discussed the solution which is to have per-room state in the RVS for things like joining and alias resolution.

**Comment by frakic** [comment] 2022-07-07 18:12
I tried joining a bunch of invites but I wasn't able to reproduce this issue. As it's pretty old, I'm going to close it but please let me know if you still encounter it.

**Closed by frakic** 2022-07-07 18:12 UTC
Labels: T-Defect, P1, S-Minor
