### ISSUE TITLE
Can't jump to already highlighted message even if out of range of vision

### ISSUE THREAD

**Issue by SeerLite** [vector-im/element-web#16710] opened 2021-03-17 18:29 UTC
### Description

After jumping to a message by clicking on the timestamp of it inside a response/quote, the message will get highlighted and it won't be possible to jump to it anymore.

### Steps to reproduce

- Send an initial message ("A")
- Send filler messages, enough to move the initial one ("A") out of range at the top
- Scroll up to the initial message and respond to it ("B")
- Use message "B" to jump to "A" by clicking on the timestamp of the "A" quoted inside "B"
- Scroll back down
- Try to jump from "B" to "A" again

Since "A" is already highlighted, clicking the quoted timestamp inside "B" will do nothing. What's expected is that even though "A" was highlighted, clicking the timestamp will jump or scroll to the message.
Sidenote: I also want to say that clicking on the timestamp feels really unintuitive, as opposed to being able to click anywhere inside the quote to jump to the message, like on other apps.

Logs being sent: no

![image](https://user-images.githubusercontent.com/21978144/111518529-eaaa2380-8734-11eb-8fb8-9a2966cd8c14.png)
Message that was highlighted after being "jumped to" by clicking on a response. It can no longer be jumped to unless another message is highlighted manually (e.g. clicking timestamp of another message) or the chat is switched/reopened.

### Version information

- **Platform**: Desktop

- **OS**: Arch Linux
- **Version**: 1.7.22

**Comment by aaronraimist** [comment] 2021-03-27 05:23
Duplicate of https://github.com/vector-im/element-web/issues/2903

**Closed by aaronraimist** 2021-03-27 05:23 UTC
Labels: A-Timeline, T-Defect
