### ISSUE TITLE
Client needs to detect when user adds a room published address with wrong format

### ISSUE THREAD

**Issue by rht** [vector-im/element-web#16569] opened 2021-03-01 04:31 UTC
### Description

Currently, when I accidentally add a room with a format of 'alias' instead of '#alias:server' I got this generic error
![2021-02-28-232704_761x275_scrot](https://user-images.githubusercontent.com/395821/109452052-e2f03c80-7a1c-11eb-94f0-1e9ceac3e5ef.png)

The client should be able to tell the user that their format is wrong even before sending the request to the server.
I only discovered the real problem after checking the server log:
```
SynapseError: 400 - Expected RoomAlias string to start with '#'
```

**Comment by aaronraimist** [comment] 2022-01-10 12:22
Duplicate of https://github.com/vector-im/element-web/issues/12685 and https://github.com/vector-im/element-web/issues/13077

**Closed by aaronraimist** 2022-01-10 12:22 UTC
Labels: T-Defect, P3, S-Tolerable, A-Aliases
