### ISSUE TITLE
Allow to pin and expand widgets on room creation

### ISSUE THREAD

**Issue by skolmer** [vector-im/element-web#15746] opened 2020-11-16 14:41 UTC
**Is your suggestion related to a problem? Please describe.**

When we create rooms that contain the Jitsi widget it is currently not possible to make this widget pinned to the room and expanded for all users who join the room.

**Describe the solution you'd like**

Allow to pin and expand widgets for all users when the widget gets added.

**Comment by t3chguy** [comment] 2020-11-16 15:01
Jitsi widgets are planned to get alternative treatment and live in a different place than other widgets which will render this moot.

**Comment by skolmer** [comment] 2020-11-16 23:38
That sounds great but I would like to keep this issue open because it might be useful for other integrations. For our current usecase though, it won't be a priority if it is re-implemented as you described.

**Comment by turt2live** [comment] 2020-11-23 02:04
I think this is a duplicate of https://github.com/vector-im/element-web/issues/15267 and https://github.com/vector-im/element-web/issues/15718 (as a bug).

**Closed by turt2live** 2020-11-23 02:04 UTC
Labels: suggestion, type:widgets
