### ISSUE TITLE
Limiting number of reply lines broke at some point

### ISSUE THREAD

**Issue by tulir** [vector-im/element-web#18106] opened 2021-07-20 14:34 UTC
The `display: -webkit-box` from [_ReplyTile.scss](https://github.com/matrix-org/matrix-react-sdk/blob/4a877300dab76670ee3a0037a998340059e2b65a/res/css/views/rooms/_ReplyTile.scss#L66) gets overridden in [_EventTile.scss](https://github.com/matrix-org/matrix-react-sdk/blob/4a877300dab76670ee3a0037a998340059e2b65a/res/css/views/rooms/_EventTile.scss#L217-L222):

![image](https://user-images.githubusercontent.com/4224639/126342410-b8a0ea89-aff6-4480-afc0-1b5ad1637517.png)

**Comment by t3chguy** [comment] 2021-07-20 14:35
duplicate of https://github.com/vector-im/element-web/issues/18099

**Closed by t3chguy** 2021-07-20 14:35 UTC
Labels: T-Defect
