### ISSUE TITLE
UI: Wrong Timeline height after sending a message (is typing Indicator) 

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-web#25325] opened 2023-05-10 10:27 UTC
### Steps to reproduce

1. Open a Chat and wait when a dm is text to you

#### What did you expect?
The Timeline height revert to normal state like before

#### What happened instead?
Wrong Timeline height after sending a message (is typing Indicator) 

https://github.com/vector-im/element-web/assets/1436958/cc628c96-f7b6-43d0-a582-a9309b8291c9

### Operating system

All

### Browser information

All

### URL for webapp

https://messenger.3dns.eu/

### Application version

Develop

### Homeserver

v1.83.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-05-10 10:28
Duplicate of https://github.com/vector-im/element-web/issues/8552

**Closed by t3chguy** 2023-05-10 10:28 UTC
Labels: T-Defect
