### ISSUE TITLE
Freeze when finishing verification

### ISSUE THREAD

**Issue by tuxayo** [vector-im/element-web#15685] opened 2020-11-09 18:27 UTC
### Description

After confirming that the emojis match with a instance of Element Android, Element Web would freeze for more than 30 min. Meanwhile Element Android waits for the other device.
After 30 min, I just noticed that I had a popup of a another totally unrelated website that also froze and I told Firefox to stop the script and then Element also stopped freezing. That makes no sense. Anyway now Element Web doesn't freeze and I can now send logs against this ticket.
Now it's just wating forever the confirmation of the other device.

Since months I can't validate between these two devices but it's the first time that when trying, it freezes.
Usually, Element Android reports success and Element web waits forever the confirmation of the other device.

### Version information

- **Platform**: Web

For the web app:

- **Browser**: Firefox 83 beta
- **OS**: EndeavourOS (Arch based)
- **URL**: https://app.element.io

**Comment by tuxayo** [comment] 2020-11-09 18:42
Actually, the page isn't hard freezed but I can't click on anything so I can't send logs.

So I refreshed and retried, hard freeze, no suspicious pop up, but other websites also are freezed, they must be in the same process. Anyway, unrelated.

**Comment by kittykat** [comment] 2021-11-30 18:14
I am going to close this issue for now as we were unable to reproduce it during the community testing session that focused on encryption. If you still experience it, please comment with @kittykat and I will reopen it for you

**Closed by kittykat** 2021-11-30 18:14 UTC
Labels: T-Defect, A-Performance, P1, X-Regression, S-Major, A-E2EE-SAS-Verification, A-E2EE-Cross-Signing, X-Needs-Community-Testing
