### ISSUE TITLE
Setting a profile picture no longer shows the new profile picture

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18348] opened 2021-08-02 22:00 UTC
<img width="307" alt="Screenshot 2021-08-02 at 22 59 59" src="https://user-images.githubusercontent.com/1294269/127929349-6b4aa037-2961-4597-9f94-60efd7819a25.png">

**Comment by ShadowJonathan** [comment] 2021-08-02 22:43
Duplicate of https://github.com/vector-im/element-web/issues/18321

**Closed** 2021-08-02 22:45 UTC
Labels: X-Regression
