### ISSUE TITLE
Temporary guest account with new messages -- Allow nonusers to see the platform in action without creating an account

### ISSUE THREAD

**Issue by quantazelle** [vector-im/element-web#20762] opened 2022-01-26 07:52 UTC
#### What would you like to do?

A user sends a message to a nonuser and a temporary account is created with a nonuser's incoming messages from that user.  The nonuser cllicks on a link sent by the user and a guest account is created for the nonuser--who is now a guest. The guest acccount Web version shows the messages from the inviting user. The guest account only exists for a limited time, unless the guest chooses to become a user and then register to acccess the full site. When the guest converts to a user, the "guest messages" from the inviting user are merged into the full account.

#### Why would you like to do it?

I am having trouble converting friends over from Telegram. A lot of them had enough trouble with TG itself and won't register for a new platform that they would have to learn. The best feature to convert nonusers is the Voice Message aspect, likely because typing is even too much for these nontechnical folks. You see the barrier here?

I borrowed this concept from retail. As a promotion, people are sent a link through email to a temporary cart with a free gift already in it. They have to meet a minimum purchase requirement before they are allowed to check out. When they go to checkout they can either sign in and merge the guest cart with their user cart, or create a new user and merge the guest cart. If they don't register in n amount of time, their guest account expires and they won't be able to see their messages or interact with the sending user.

This also creates buy-in because the messages belong to the guest. It's where _their_ personal messages are from their friends are stored. It'd be a shame if something happened to it. Heh.

#### How would you like to achieve it?

There's already a web version. Maybe do an encrypted link that spawns a barebones site when clicked? Then add in expirations to encourage account conversion so that guests can still view their messages and interact with the senders for a limited time.

**Comment by t3chguy** [comment] 2022-01-26 09:26
Duplicate of https://github.com/vector-im/element-web/issues/3076

**Closed by t3chguy** 2022-01-26 09:26 UTC
Labels: A-ILAG, X-Needs-Product, T-Enhancement, O-Uncommon
