### ISSUE TITLE
Open Element with Double Click on Tray Icon [Ubuntu]

### ISSUE THREAD

**Issue by kojid0** [vector-im/element-web#17315] opened 2021-05-16 14:58 UTC
I'd like to open Element by double clicking on the system tray icon. Currently you have to click once, move mouse cursor to show/hide button and click it.
OS: Zorin16, based on Ubuntu 20.04 LTS

**Comment by xekon** [comment] 2021-06-30 20:45
bah, I missed this one.

I just opened this one: https://github.com/vector-im/element-web/issues/17850

I am suggesting single left displays or hides element. This is the exact behavior of other applications such as Pidgin, or Kdocker which I use to minimize Thunderbird to system tray.

I am running Kubuntu 20.04.2 LTS

**Comment by xekon** [comment] 2021-06-30 21:13
I just found this: https://github.com/vector-im/element-web/issues/11772

**Comment by xekon** [comment] 2021-06-30 21:17
This worked for me:

```
sudo touch /opt/Element/libappindicator3.so
sudo touch /opt/Element/libappindicator3.so.1
```

After doing that left click now shows and hides Element.

**Comment by t3chguy** [comment] 2021-07-01 07:20
Duplicate of https://github.com/vector-im/element-web/issues/11772

**Closed by t3chguy** 2021-07-01 07:20 UTC
Labels: A-Electron, A-Tray-Icon, P4, T-Enhancement, Z-Platform-Specific

**Comment by Jieiku** [comment] 2022-07-03 13:37
This no longer works. its back to not showing/hiding on mouse click of tray icon.
