### ISSUE TITLE
New composer has encryption shield against "no permission to post" text

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22502] opened 2022-06-09 16:23 UTC
### Steps to reproduce

1.Look at a room you don't have permission to post in

#### What did you expect?

Shield to be consistently placed.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/172896550-60b9c2d8-9f14-4bbf-8e55-7a2a99ba974b.png)

### Operating system

Windows 10

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-06-09 16:24
Duplicate of https://github.com/vector-im/element-web/issues/22484

**Closed by t3chguy** 2022-06-09 16:24 UTC
Labels: T-Defect, A-Composer, Team: Delight
