### ISSUE TITLE
chat jumps to selected message when opening or closing the user panel

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/element-web#11576] opened 2019-12-02 14:41 UTC
If you select a message (by clicking on the time of sending) and the go on chatting in the room, opening or closing the user panel on the right causes the view to jump back to that message.

**Comment by MadLittleMods** [comment] 2021-08-23 23:46
Closing as I can't reproduce this nowadays.

We also seem to have some magic where if you scroll away from that area, the event ID is removed from the URL. It's still possible to click an event timestamp, send a message to jump back down to the latest in the timeline, and keep the old event ID in the URL. But I can't reproduce this bug with that trick still.

**Closed by MadLittleMods** 2021-08-23 23:46 UTC
Labels: T-Defect, A-Timeline

**Comment by mvgorcum** [comment] 2021-08-24 20:18
Yeah, this old bug seems gone on my end too. Possibly it was fixed upstream in react or something? Thanks for taking the time to look in to it!
