### ISSUE TITLE
URLs containing emojis are not linked correctly

### ISSUE THREAD

**Issue by koalatux** [vector-im/element-web#16359] opened 2021-02-03 19:12 UTC
### Description

When I send an URL in a chat and the URL contains an emoji which must be IDN encoded, the URL is not linked correctly.

### Steps to reproduce

- Open a chat
- Enter the URL `https://☃.example.org` or `https://☃.example`
- Send the message

Expected behaviour:

- The whole text making out the URL is linked.

Actual behaviour:

- In the emoji in the subdomain example: Only the example.org part is a link and points to http://example.org (http instead of https)
- In the second example: Nothing is linked.

Other thoughts:

I did not consider if emojis in URLs are actually allowed according to IDNA2008 (RFC 5890 - 5894), I believe as long as web browsers support such URLs, users will expect them to work in a chat application. Also the Element Android app seems to support these example URLs.

Logs being sent: no

Screenshot:
![grafik](https://user-images.githubusercontent.com/973758/106783624-c6462c00-664b-11eb-8a00-8c44ebb07fd2.png)

### Version information

- **Platform**: web

- **Browser**: Firefox 85.0
- **OS**: Debian stable
- **URL**: develop.element.io and app.element.io

**Comment by t3chguy** [comment] 2021-02-04 15:40
Duplicate of https://github.com/vector-im/element-web/issues/5808

**Closed by t3chguy** 2021-02-04 15:40 UTC
Labels: bug
