### ISSUE TITLE
Unable to decrypt an image i sent myself

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2948] opened 2017-01-14 12:59 UTC
all the other messages in this convo were okay, and the image was received okay, and viewable on the original sending device (iOS).  but on opening riot-web 0.9.6 i get this:

<img width="499" alt="screen shot 2017-01-14 at 12 55 09" src="https://cloud.githubusercontent.com/assets/1294269/21954998/45de0948-da59-11e6-8601-85a893860cbe.png">

[logs.txt](https://github.com/vector-im/riot-web/files/705934/logs.txt)

**Comment by kittykat** [comment] 2021-11-30 17:20
I'm going to close this issue as we can't reproduce it at the moment. If it's still happening for you, please re-open.

**Closed by kittykat** 2021-11-30 17:20 UTC
Labels: T-Defect, P2, A-E2EE, X-Needs-Community-Testing
