### ISSUE TITLE
"New Messages"-Counter on the toolbar icon is not shown when the app is pinned

### ISSUE THREAD

**Issue by morbonator** [vector-im/element-web#20242] opened 2021-12-17 11:39 UTC
### Steps to reproduce

While the app is not pinned to the taskbar, right-clicking it will cause the unread messages counter to disappear. If the app is pinned, the counter won't appear in the first place. The app needs to be pinned and un-pinned again for it to reappear.
![image](https://user-images.githubusercontent.com/96293430/146539100-91165b1f-6bbb-49e4-a9b1-e356ea038aa0.png) ![image](https://user-images.githubusercontent.com/96293430/146539176-ed2995af-c353-41b4-af13-a8d8ba49736a.png)

#### What did you expect?
I expected the counter to not disappear

#### What happened instead?
It disappeared

### Operating system

Windows 10

### Application version

Element 1.9.7, Olm 3.2.8

### How did you install the app?

From the element.io website

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2021-12-17 13:27
Duplicate of https://github.com/vector-im/element-web/issues/14033

**Closed by t3chguy** 2021-12-17 13:27 UTC
Labels: T-Defect
