### ISSUE TITLE
Element shutdown itself by itself after couple of minutes?!

### ISSUE THREAD

**Issue by TNTBOMBOM** [vector-im/element-web#24108] opened 2022-12-24 19:56 UTC
### Steps to reproduce

Install -> run it for few minutes -> there you go

#### What did you expect?

Stay opened until i close it manually 

#### What happened instead?

```
user@host:~$ element-desktop 
Error in cpuinfo: failed to parse processor information from /proc/cpuinfo
Error in cpuinfo: failed to parse processor information from /proc/cpuinfo
[1:1224/194546.346369:ERROR:content_main_runner_impl.cc(444)] Failed to initialize cpuinfo
[12033:1224/194546.346341:ERROR:content_main_runner_impl.cc(444)] Failed to initialize cpuinfo
/home/user/.config/Element exists: yes
/home/user/.config/Riot exists: no
Disabling hardware acceleration.
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[12065:1224/194546.861764:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store [Error: The name org.freedesktop.secrets was not provided by any .service files]
Trace/breakpoint trap (core dumped)
user@host:~$ 
```

### Operating system

Debian 11

### Application version

Element version: 1.11.17 Olm version: 3.2.12

### How did you install the app?

element repository

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Orhideous** [comment] 2022-12-26 17:28
Confirmed.
It's just impossible to use Element now — instant crash after typing single letter in chat with broken messages.

**Comment by unknownterritory** [comment] 2022-12-26 23:02
I am on Pop!_OS 22.04 LTS, using Element version: 1.11.17 Olm version: 3.2.12 and Matrix.org as homeserver. I had installed Element using [Pop!_Shop](https://github.com/pop-os/shop) (System76's app center). The same thing as described in the issue report was happening to me.

I've uninstalled Element and reinstalled it using the instructions provided on [Element's website](https://element.io/download#linux-details). It seems to be holding up normally now.

**Comment by weeman1337** [comment] 2022-12-27 08:09
@Orhideous @unknownterritory can you try to provide more information like @TNTBOMBOM  (thanks) did? You can start element from a shell and see if there are useful logs.

**Comment by Orhideous** [comment] 2022-12-27 11:11
@weeman1337 
[Log with error](https://github.com/vector-im/element-web/files/10307740/err.log)
[Log after clean installation](https://github.com/vector-im/element-web/files/10307742/err_2.log)

Reinstall did not help.

**Comment by YourSandwich** [comment] 2022-12-28 15:59
I have the same issue on ArchLinux

**Comment by YourSandwich** [comment] 2022-12-28 16:04
This issue exists for me from the upgrade of version 1.11.10 to 1.11.15

**Comment by weeman1337** [comment] 2022-12-28 16:39
@Orhideous , @YourSandwich  unfortunately your platforms (Flatpak and Arch) are officially not supported. Can you open issues in the community bug trackers? Keeping this open for the issue from the description.

**Comment by YourSandwich** [comment] 2022-12-28 16:49
@weeman1337 thanks il do that!

**Comment by t3chguy** [comment] 2023-01-03 16:08
Duplicate of https://github.com/vector-im/element-web/issues/23311

**Closed by t3chguy** 2023-01-03 16:08 UTC
Labels: T-Defect, S-Major, O-Occasional
