### ISSUE TITLE
Spurious Video Call when starting Element Desktop

### ISSUE THREAD

**Issue by zhao-nan** [vector-im/element-web#26523] opened 2023-11-08 07:31 UTC
### Steps to reproduce

When starting Element Desktop, it plays a ringing sound and says one of my contacts is making a video call (it is always the same contact) although my contact is actually not making a call. When I accept the call, a video conference starts, but I only see a black screen. Unlike actual video calls in the same chat, the spurious call does not appear in the chat history.
![image](https://github.com/vector-im/element-web/assets/5895380/cd65b305-8685-47ba-85fa-faf5ec5dfc84)

#### What did you expect?
Receiving only calls that people actually make

#### What happened instead?
I receive spurious calls every time I start Element

### Operating system

Ubuntu

### Application version

Element version: 1.11.47 Olm version: 3.2.14

### Homeserver

https://matrix-client.matrix.org

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-11-08 08:20
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-11-08 08:21
Duplicate of https://github.com/vector-im/element-web/issues/4607

**Closed by weeman1337** 2023-11-08 08:21 UTC
Labels: T-Defect
