### ISSUE TITLE
Search results aren't usefully clickable any more

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#19482] opened 2021-10-22 16:25 UTC
### Steps to reproduce

1. Search for something
2. Click a result
3. Expect to navigate to the message in the timeline
4. _Sometimes_ it works. Almost always though it doesn't

#### What did you expect?
To navigate to the search result's position in the timeline.

#### What happened instead?
Mostly, nothing. Occasionally (one click in 30) works. I tried clicking the timestamp, mxid, and message.

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2021102201 Olm version: 3.2.3

### How did you install the app?

Website

### Homeserver

lant.uk

### Will you send logs?

No

**Comment by lampholder** [comment] 2021-11-05 11:34
I should have recorded which _room_ I encountered this in first - looking again, I can repro it sometimes - perhaps something to do with whether rendering the search result would require a move in the timeline (i.e. if the search result is already in the visible timeline, clicking on the message text in the result doesn't do anything).

I'm not certain that's it though - I'll see if I can make a room that demonstrates it in a reproducible way.

**Comment by Palid** [comment] 2021-11-15 14:20
@lampholder how's the reproduction going? 😄 
If you could please add some very simple reproduction steps working 100% of the time it'd be so much better!

**Comment by t3chguy** [comment] 2022-01-26 17:24
@lampholder any updates here?

**Comment by novocaine** [comment] 2022-02-21 10:44
Closing due to no repro steps posted

**Closed by novocaine** 2022-02-21 10:44 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, S-Major, A-Search, O-Occasional
