### ISSUE TITLE
Sending two messages at the same and having the first fail still sends the second

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22885] opened 2022-07-18 19:27 UTC
### Steps to reproduce

1. Send two messages
2. Ensure your server fails to send the first
3. Watch the second get sent (it should be blocked due to the error on the first)
4. Send another message
5. That message gets appropriately gated by the failed message

#### What did you expect?

3 of my messages to fail to send, not 2.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/179601204-95c64de1-2666-4d16-9cc9-f318b5ad32cd.png)

The first message sent okay. After it was sent, a new batch of messages was started: the second and third were sent at roughly the same time and due to a server crashing slowly ended up blocked for long enough to work. Once the second failed to send and the third sent, I started a new message (fourth) which appropriately got marked as failed to send.

Resolved by manually re-queuing the messages in the order I wanted them, and screenshotting the messages so the receipients knew what was going on :) 

(this is what makes this bug nasty: we have a lot of code which tries to make sure order is preserved, and it broke that guarantee here, making the app lose a bit of user trust that it can safely send messages)

### Operating system

Windows 10

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by ara4n** [comment] 2023-01-22 14:45
(i don't think we expose UX to let the user manually re-queue them as a workaround, either? and certainly not reliably)

**Comment by ara4n** [comment] 2023-02-14 10:11
I just reproduced this again on `Element Nightly version: 2023021301` - have rageshaked.

**Comment by turt2live** [comment] 2023-02-14 20:20
confirmed: in a room where encryption is slow, I sent a message which happened to be far too large to send as an event. While that message was encrypting, I sent a second message. The first message (the large one) failed for hopefully obvious reasons, but the second was sent anyways.

After the failure (and second message sent), I tried sending a third which was appropriately prevented.

Feels like the bug is in the loop not breaking out when an error happens given the symptoms.

Currently on `Element Nightly version: 0.0.1-nightly.2023021401`.

**Comment by MadLittleMods** [comment] 2023-02-15 20:31
Related to https://github.com/matrix-org/matrix-spec/issues/1316

**Comment by turt2live** [comment] 2023-04-25 00:05
The original steps to reproduce have always triggered it for me. Not sure my logs will be any more revealing than local debugging, tbh.

**Comment by Johennes** [comment] 2023-04-25 06:35
@turt2live we're not able to reproduce this, sadly, so we can't debug it locally. If you can easily reproduce it, we'd very much appreciate another rageshake so that we can try and investigate it based on the additional logging.

**Comment by Johennes** [comment] 2023-06-08 13:36
I'm closing this for now since we're unable to action it without further input. Logging has been extended though, as mentioned above. So happy to reopen if anyone manages to reproduce this.

**Closed by Johennes** 2023-06-08 13:36 UTC
Labels: T-Defect, S-Major, A-Timeline, Z-Chronic, O-Uncommon, Team: App
