### ISSUE TITLE
Add a config to choose what the default themes should be

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#20508] opened 2022-01-12 13:23 UTC
#### What would you like to do?
Have a different default light/dark mode

#### Why would you like to do it?
Because a) we defined them to be different for our customers and b) we would like them to work with the match system theme option 

#### How would you like to achieve it?
I was trying to change this line:
https://github.com/matrix-org/matrix-react-sdk/blob/5ae166777c96df4cac7e406938e327c04f5f0cdb/src/components/structures/UserMenu.tsx#L303
to 
        `let newTheme = this.state.isDarkTheme ? "custom-Light" : "custom-Dark";`

And call the themes "Light" and "Dark"
I also added this line [here](https://github.com/matrix-org/matrix-react-sdk/blob/5ae166777c96df4cac7e406938e327c04f5f0cdb/src/components/views/elements/StyledRadioGroup.tsx#L58) to remove the two default themes:
        `d.value !== "light" && d.value !== "dark" &&`
but I did not get that to work.

**Comment by t3chguy** [comment] 2022-11-10 13:47
Duplicate of https://github.com/vector-im/element-web/issues/14873

**Closed by t3chguy** 2022-11-10 13:47 UTC
Labels: T-Enhancement, A-Config, A-Themes-Official, O-Uncommon
