### ISSUE TITLE
Clear cache and reboot for "Restoring current session"

### ISSUE THREAD

**Issue by cavabanga26** [vector-im/element-web#7176] opened 2018-08-16 09:12 UTC
Hello!
when opening sessions on the stage Restoring session for " + o"  I need to clear the cache by analogy with the button in the client's  "Clear cache and reload" settings. In this case, the authorization data must be saved.
I try to insert the code in thebundle.js  session verification phase
```
function () {
S.get () && (w.get (). StopClient (), w.get (). Store.deleteAllData (). Done (function () {
S.get (). Reload ()
}))
}
```

But it does not work. Any ideas?

**Comment by lampholder** [comment] 2018-08-20 16:29
Hi - can you explain a bit more what the problem is you're trying to overcome?

**Comment by cavabanga26** [comment] 2018-08-23 11:13
After login, must be simulated click button "Clear Cache and reboot" from User Settings

**Comment by lampholder** [comment] 2018-09-10 15:53
Hey, sorry I havent responded to this in a while, but I'm still not sure _why_ you're trying to simulate the 'clear cache and reload' action. 

Inserting code into thebundle.js seems like the wrong approach (for whatever it is you're trying to do) - if you can describe how you're trying to use riot and why you need to clear the cache, there might be a better approach we can advise :)

**Comment by kittykat** [comment] 2021-12-21 14:38
I'm going to close this for now as we haven't had a follow up with more information. Please file a new issue with more details for any ongoing problems.

**Closed by kittykat** 2021-12-21 14:38 UTC
Labels: T-Other
