### ISSUE TITLE
Web doesn't seem to respect changes in OS level change of sound input

### ISSUE THREAD

**Issue by neilmiddleton** [vector-im/element-web#17775] opened 2021-06-25 11:40 UTC
### Description

Whilst on a video call inside web, changing the sound input from one mic to another doesn't appear to be respected by web, even when the device in app is set to default.  This does not appear to be the same with output.

### Steps to reproduce

- Set the mic in macOS to a mic
- Ensure the input device in Element is set to 'Default'
- Start a call
- Change the input device in macOS
- Input device does not change in call without restarting the call

Describe how what happens differs from what you expected.

It should be using the default input as provided by macOS even if that device changes.

### Version information

- macOS 11.4  Element Web Desktop 1.7.31 - may apply to other platforms but untested

**Comment by robintown** [comment] 2021-06-25 14:48
Duplicate of #15595

**Closed by robintown** 2021-06-25 14:48 UTC
Labels: A-VoIP, T-Defect
