### ISSUE TITLE
Unremovable message persists at end of message list

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#17474] opened 2021-05-26 23:40 UTC
At the bottom of the message list in a private room where I keep notes to self, I have a message that persists always in the last position, no matter how many new messages are entered.  All new message go into the list just above the last message, after a short delay.  The popup menu for the last message does not include 'Remove'.   It therefore cannot be removed.  How do I remove it?

**Comment by SimonBrandner** [comment] 2021-05-27 04:33
This looks like a relatively common bug - could you try clearing your cache and reloading to see if that fixes this?

![Screenshot_20210527_063324](https://user-images.githubusercontent.com/25768714/119766517-72d74280-beb5-11eb-820d-e59bcde85959.png)

**Comment by t3chguy** [comment] 2021-05-27 07:08
Duplicate of https://github.com/vector-im/element-web/issues/17471 - this is a server/sync issue

**Closed by t3chguy** 2021-05-27 07:08 UTC
Labels: T-Defect, X-Needs-Info
