### ISSUE TITLE
Mentioning matrix username will notify all users with substring display names

### ISSUE THREAD

**Issue by fladd** [vector-im/element-web#8497] opened 2019-02-09 17:42 UTC
### Description

If a mentioned matrix username includes a display name, then the user with that display name is also notified. For instance, if I mention "@some.guy.named.matthew:matrix.org", then besides that person, also every other person with a username being "Some", "Guy", "Named", "Matthew", "Matrix" or "Org" gets notified.

### Steps to reproduce

- mention "@some.guy.named.matthew:matrix.org"

Describe how what happens differs from what you expected.
Besides that person, also every other person with a username being "Some", "Guy", "Named", "Matthew", "Matrix" or "Org" gets notified.

Of course only the person with the exact mentioned username "@some.guy.named.matthew:matrix.org" should be notified.

Log: sent/not sent?  no  

### Version information

- **Platform**: web (in-browser) or desktop?
web

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
all
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
all
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?
develop

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
not tested
- **Version**: 0.x.y 
not tested

**Comment by fladd** [comment] 2019-02-09 17:55
Apparently this is bug is not unique to matrix IDs. Mentioning "some.guy.named.matthew" will notify the same multiple people, none of which where mentioned explicitly.

**Comment by aaronraimist** [comment] 2019-02-09 17:58
This is by design as far as I know, to support clients that don't create mention "pills"

**Comment by fladd** [comment] 2019-02-10 19:59
Not sure I understand what mention pills have to do with it. The issue I am reporting is that when mentioning a very specific user, with their full matrix user name, other unrelated users get notified as well. I don't think this is intended.

**Comment by lampholder** [comment] 2019-02-19 10:53
Yeah, this doesn't sound like a good end result :\

**Comment by SantjagoCorkez** [comment] 2020-06-02 18:28
A user gets mentioned when just a word in another user's message matches partially one's Matrix ID.

My username is `@as:server.name`. So when anyone writes a wall of text that will almost always contain the word `as` (without @-sign) I will be mentioned and notification arises. Make a setting or fix it please.

**Comment by t3chguy** [comment] 2020-06-02 19:07
![image](https://user-images.githubusercontent.com/2403652/83559567-ac78a600-a50c-11ea-8714-0b2b9eb361be.png)

it is configurable, you can opt to just have mentions be of your display name and even any custom keywords.

**Comment by SantjagoCorkez** [comment] 2020-06-02 20:10
Which one disables mentioning me by the word `as` and still allows mentioning with `@as`?

**Comment by t3chguy** [comment] 2020-06-02 20:15
your username is `as`
You could add a keyword for `@as` but `@as` is not a recognized format of anything in Matrix

**Comment by SantjagoCorkez** [comment] 2020-06-02 20:17
Could it be resolved, not workarounded? What if someone mentions by full usernme? That goes deeper and deeper losing mentions here and there. Still to often people use `as` in their talks to ignore.

**Comment by t3chguy** [comment] 2020-06-02 20:27
It'd need to be a conversation for a different project, riot-web is just using the push rules system that Matrix offers it

**Comment by christophedcpm** [comment] 2020-12-23 09:12
I have the same issue. My username is also contained in my homeserver name. So anytime anyone on my server is mention, I'm also mention cause the server name automatically mention me too. 
I didn't find any way to workaround this or disable this behavior.

I think mention should not take in subset of a username in account but only a full match. @t3chguy where should we bring this discussion to make it move forward ?

**Comment by zaibon** [comment] 2020-12-23 09:26
I have the same issue. My username is also contained in my homeserver name. So anytime anyone on my server is mention, I'm also mention cause the server name automatically mention me too.
I didn't find any way to workaround this or disable this behavior.

I think mention should not take in subset of a username in account but only a full match. @t3chguy where should we bring this discussion to make it move forward ?

**Comment by t3chguy** [comment] 2022-05-10 20:37
Duplicate of https://github.com/vector-im/element-web/issues/8431

**Closed by t3chguy** 2022-05-10 20:37 UTC
Labels: T-Defect, P2, S-Major, A-Notifications, A-Pills
