### ISSUE TITLE
Uncollapsing collapsed replies doesnt work

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#19299] opened 2021-10-05 17:44 UTC
### Steps to reproduce

1. Write a long message
2. Reply to it
3. Press the uncollapse button

#### What did you expect?

To have the message line expanded vertically to fit the reply

#### What happened instead?

It added a scrollbar but didnt give any further vertical space.

Note: This was in an encrypted room

### Operating system

Windows 11

### Browser information

Firefox 92.0.1 (64-bit)

### URL for webapp

develop.element.io

### Homeserver

nordgedanken.dev

### Will you send logs?

No

**Comment by weeman1337** [comment] 2022-07-01 09:43
@gsouquet do you know what the expected product-side behaviour is? Should it become scrollable or expand?

Expanding it is what I've expected because I just wondered why I have to click expand only to enable scrolling :laughing:

**Comment by gsouquet** [comment] 2022-07-12 07:06
@weeman1337 just saw your comment now. I can't say for sure, but I can direct you to @janogarcia who originally worked on this issue

**Comment by janogarcia** [comment] 2022-11-27 12:14
I can't reproduce it, unless I'm getting the context wrong. The "Expand quotes"/"Collapse quotes" contextual action is working as expected for me (it expands vertically to fit the contents, there's no scrollbar introduced).

**Comment by t3chguy** [comment] 2022-12-05 15:44
![image](https://user-images.githubusercontent.com/2403652/205679776-2b65e714-f1ec-47af-b9c3-3d3b543bb4d1.png)

Works fine here too, closing until proven otherwise

**Closed by t3chguy** 2022-12-05 15:44 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Minor, A-Timeline, A-Replies, O-Uncommon, Z-Community-Testing
