### ISSUE TITLE
New retry toolbar icons are inconsistently sized, with a disproportionately massive trash can

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17741] opened 2021-06-23 11:06 UTC
Looks like the asset sizing is wrong?  Or we're using the wrong assets?

<img width="381" alt="Screenshot 2021-06-23 at 09 41 10" src="https://user-images.githubusercontent.com/1294269/123086484-634b0b00-d41b-11eb-8cf6-eea77a783669.png">

**Comment by t3chguy** [comment] 2021-06-23 11:07
Yup.

Duplicate of https://github.com/vector-im/element-web/issues/17731#issuecomment-866596111

**Closed by t3chguy** 2021-06-23 11:07 UTC
Labels: T-Defect
