### ISSUE TITLE
Number of unread messages not shown in the taskbar anymore

### ISSUE THREAD

**Issue by jcklie** [vector-im/element-web#19534] opened 2021-10-28 08:27 UTC
### Steps to reproduce

1. Get a message with Element Desktop minimized
2. See that the tray shows unread messages, but the taskbar icon does not

It worked before upgrading to the latest element with my current config.

![image](https://user-images.githubusercontent.com/934600/139217022-50162587-f62b-41c0-a835-894d1b21f1a3.png)
![image](https://user-images.githubusercontent.com/934600/139217061-0a4fc56e-1792-4d15-b1e1-fadcf2fe1bfa.png)
![image](https://user-images.githubusercontent.com/934600/139217709-89adc642-09e3-4277-bf68-f564147e55a8.png)

#### What did you expect?

I want to see the number of unread messages

#### What happened instead?

No unread message count

### Operating system

Windows 10

### Application version

Element version: 1.9.3 Olm version: 3.2.3

### How did you install the app?

https://element.io/get-started#download

### Homeserver

https://messenger.ukp.informatik.tu-darmstadt.de/

### Will you send logs?

Yes

**Comment by ddnomad** [comment] 2021-11-01 17:20
This is really unfortunate. Any idea when upstream is gonna fix it?

**Comment by foxx** [comment] 2021-11-01 17:22
@dbkr I would argue that this is not a "S-Minor" as it prevents users from being notified that they have messages pending.

**Comment by novocaine** [comment] 2021-11-02 17:29
if this started only recently, it's likely related to the recent electron version upgrade (which fixed other problems)

some upstream issues that may be related to this (although not particularly associated with recent electron versions)

* https://github.com/electron/electron/issues/28581
* https://github.com/electron/electron/issues/27321

**Comment by t3chguy** [comment] 2021-11-08 09:27
Duplicate of https://github.com/vector-im/element-web/issues/14033

**Closed by t3chguy** 2021-11-08 09:27 UTC
Labels: T-Defect, Z-Platform-Specific, X-Regression, S-Minor, A-Electron, Z-Upstream, O-Frequent
