### ISSUE TITLE
Can't download file in message list

### ISSUE THREAD

**Issue by cesar-cardinale** [vector-im/element-web#24473] opened 2023-02-08 16:42 UTC
### Steps to reproduce

I'm just sending a file to another user, like a PDF or MP4.
When I'm clicking on the download button nothing happened.

<img width="205" alt="Capture d’écran 2023-02-08 à 17 28 32" src="https://user-images.githubusercontent.com/37698963/217591055-a56f24da-e55d-41b5-8af5-7968735c1799.png">

### Outcome

I expect to download the file.

Thank you.

### Operating system

MacOS

### Browser information

Safari, Chrome, Firefox

### Application version

Element Web 1.11.22

### Homeserver

Synapse 1.16.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-02-08 16:49
Nothing to investigate without logs

**Comment by cesar-cardinale** [comment] 2023-02-08 17:00
Which log I need to provide ?

**Comment by t3chguy** [comment] 2023-02-08 17:05
<img width="892" alt="image" src="https://user-images.githubusercontent.com/2403652/217601031-07928bb4-ca03-4584-9809-47f9f077d8fb.png">

**Comment by cesar-cardinale** [comment] 2023-02-08 17:11
`/rageshake` is not a found command

**Comment by t3chguy** [comment] 2023-02-08 17:20
Are you using a custom instance without rageshake configured? You left the instance url field blank in the template

**Comment by cesar-cardinale** [comment] 2023-02-08 17:22
I'm using this Helm to deploy my element-web https://gitlab.com/ananace/charts/-/tree/master/charts/element-web

**Comment by t3chguy** [comment] 2023-02-08 17:23
I suggest just getting logs out of your browser Javascript console or seeking support from the maintainer of that chart on how to get rageshake working

**Comment by cesar-cardinale** [comment] 2023-02-08 17:25
Nothing is in the console, just a network call to this page who return a 200 response : `https://HOMESERVER/_matrix/media/r0/download/SERVER/hMQHyIFMvwFSHFyUVMVUpEIr`

But nothing more ...

**Comment by t3chguy** [comment] 2023-02-08 17:30
Please provide browser information in the issue form, also try with a clean browser profile. If the request is being made as you confirmed then either something on the server is mutating the content disposition headers or your browser settings/extensions are preventing it from working

**Comment by MadLittleMods** [comment] 2023-02-22 20:06
@cesar-cardinale Any update with a fresh/clean browser environment?

**Comment by t3chguy** [comment] 2023-03-13 09:23
Closing due to lack of requested info

**Closed by t3chguy** 2023-03-13 09:23 UTC
Labels: T-Defect, X-Needs-Info, A-Timeline, A-File-Download
