### ISSUE TITLE
Icons are not properly centered with minimized left-panel

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#18696] opened 2021-08-23 14:55 UTC
Expected behavior: `+` should be in the middle of the gray area, not outside of it.

Current behavior:
![CleanShot 2021-08-23 at 16 53 06](https://user-images.githubusercontent.com/3636685/130469047-02d68b3b-fcc0-4873-81db-07eb25251258.png)

Browser: Version 92.0.4515.159 (Official Build) (x86_64)
OS: MacOS Big Sur 11.5.2 (20G95)
Environment: https://app.element.io/ (reproducible on dev/develop/nightly).

**Comment by SimonBrandner** [comment] 2021-08-23 14:57
Duplicate of https://github.com/vector-im/element-web/issues/17068

**Closed by SimonBrandner** 2021-08-23 14:57 UTC
