### ISSUE TITLE
Unable to decrypt on one device only

### ISSUE THREAD

**Issue by tuxayo** [vector-im/element-web#12782] opened 2020-03-19 03:11 UTC
### Description

Both UTD on my Riot web device

https://matrix.to/#/!CWLUCoEWXSFyTCOtfL:matrix.org/$bE_RiRVnVcW68eoDX4Qhopfojn0BBJFPwR5kOXyO6BI?via=sw1v.org&via=matrix.org&via=chat.weho.st

https://matrix.to/#/!CWLUCoEWXSFyTCOtfL:matrix.org/$tH62-sX-RHWZH74hFuA-zwApUB17DWIL6kRw0oltca4?via=sw1v.org&via=matrix.org&via=chat.weho.st

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Firefox dev edition 75.0b5 (64-bit)
- **OS**: EndeavourOS (Arch Linux based)
- **URL**: riot.im/develop / and riot.im/app /

**Comment by tuxayo** [comment] 2020-03-19 03:17
Asking the keys from another device worked.

I sent debug logs before and after requesting keys from other device.

UTDs are getting rare (kudos for that!) so no remaining UTD must remain "unpunished" as reproducing might be hard. Correct my if that not very useful.

**Comment by tuxayo** [comment] 2020-03-19 03:20
Same is happening with two older messages:
https://matrix.to/#/!CWLUCoEWXSFyTCOtfL:matrix.org/$Rnv4uPKp85pIokE-V7l62mD_Aeft57o-LFijh-ffVPI?via=matrix.org&via=raim.ist&via=cooperteam.net
https://matrix.to/#/!CWLUCoEWXSFyTCOtfL:matrix.org/$YbmHIm9-xTg28gZnYBPAJL-NMIZwgYFAV5NA_yGzWWE?via=matrix.org&via=raim.ist&via=cooperteam.net

I didn't ask keys from another device. Waiting for instruction to not risk "loosing proofs"

**Comment by kittykat** [comment] 2021-12-08 11:57
@tuxayo Are you still seeing the issue? If you are, the Crypto team will need logs (which you can submit using the /rageshake command) to be able to debug the issue

**Comment by turt2live** [comment] 2022-06-14 05:30
Duplicate of https://github.com/vector-im/element-web/issues/2996

**Closed by turt2live** 2022-06-14 05:30 UTC
Labels: T-Defect, X-Needs-Info, P1, A-E2EE, Z-UISI
