### ISSUE TITLE
Allow to rename other users privately

### ISSUE THREAD

**Issue by c7hm4r** [vector-im/element-web#20805] opened 2022-01-29 07:26 UTC
#### What would you like to do?
I would like to rename another user, such that this new name ("custom display name") is only visible to me. Thereby, each user has assigned a username (part of their Matrix ID), possibly a public display name they choose themselves, and every other user might assign them a custom display name only visible to the other user.

When the user is referred to somewhere in the GUI, it should be primarily presented with the custom display name.

When I mention the user with @…, I would like to be able to search for any of the above three names visible to me.

#### Why would you like to do it?
Some contacts of me have Matrix IDs and public display names which are pseudonyms, not their real names. I don't want them to make their real name public, either. But sometimes I get a bit confused, who is behind some name.

Also this would be more similar to SMS: People are referred to by their phone number, and every contact may add them under any name they want in their address book, and the name they give them stays private.

BTW the public display name may be queried/crawled from Synapse without any authentication (https://my_domain:8448/_matrix/client/v3/profile/@username:my_domain).

#### How would you like to achieve it?
Add a dictionary of custom display names into the private, encrypted account storage of me.

(For the mobile versions of Element, it could be nice to manage this information in the phone address book.)

### Have you considered any alternatives?

I'm not aware of alternatives.

### Additional context

Element version: 1.9.9

**Comment by SimonBrandner** [comment] 2022-01-29 10:17
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/4488

**Closed by SimonBrandner** 2022-01-29 10:17 UTC
Labels: T-Enhancement

**Comment by c7hm4r** [comment] 2022-01-29 17:22
Actually, it's a …

Duplicate of #3130

**Comment by SimonBrandner** [comment] 2022-01-29 17:22
> Actually, it's a …
> 
> Duplicate of #3130

Both I guess :P
