### ISSUE TITLE
Joining an E2EE room redownloads keys for all members in that room, even if you're already tracking them.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#24288] opened 2023-01-23 01:23 UTC
### Steps to reproduce

1. Join an E2EE room
2. Look at the JS console
3. See loads of `Marking device list outdated` and then re-downloading everyone's devices & keys, even if you're already tracking those users.

#### What did you expect?

We shouldn't be redownloading devices/keys data for members we already know about.

#### What happened instead?

Loads of redundant traffic.

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-03-15 13:38
`Marking device list outdated` is a signal that those came down `/sync` `device_lists` or `/keys/changes` in the `changed` field. This behaviour matches the spec on the client's end:

https://spec.matrix.org/v1.6/client-server-api/#tracking-the-device-list-for-a-user

> During its normal processing of responses to [/sync](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3sync), Alice’s client inspects the changed property of the [device_lists](https://spec.matrix.org/v1.6/client-server-api/#e2e-extensions-to-sync) field. If it is tracking the device lists of any of the listed users, then it marks the device lists for those users outdated, and initiates another request to [/keys/query](https://spec.matrix.org/v1.6/client-server-api/#post_matrixclientv3keysquery) for them.

This seems like a Synapse issue related to https://github.com/matrix-org/synapse/issues/9392

I cannot reproduce this specific issue - I joined a test E2E room with my real account in it and the `/sync` response contained a `changed` entry for my own user only.

![image](https://user-images.githubusercontent.com/2403652/225325146-3c052d0c-50e9-4a84-9230-8c51836b2ea9.png)

> even if you're already tracking those users.

Surely this only happens once you type into a room to create new megolm sessions

@ara4n Logs would be helpful here next you see it

**Comment by t3chguy** [comment] 2023-07-13 10:51
Closing as invalid

**Closed by t3chguy** 2023-07-13 10:51 UTC
Labels: T-Defect, X-Needs-Info, S-Minor, O-Frequent
