### ISSUE TITLE
Cannot click background to escape community filter

### ISSUE THREAD

**Issue by r4dh4l** [vector-im/element-web#15056] opened 2020-08-27 13:52 UTC
Clicking on one of my community buttons on the left side shows me the related community rooms as expected but there is no way to get back to the view listing all my rooms. Clicking on an empty spot of the community panel doesn't help (I remember it worked this way under riot). So currently I have to restart element to see all rooms again.

*element version: 1.7.4
*Debian 10.5

**Comment by turt2live** [comment] 2020-08-27 13:54
Clicking on the community again will turn it off again - this looks like a regression.

**Comment by r4dh4l** [comment] 2020-08-27 14:00
> Clicking on the community again will turn it off again - this looks like a regression.

Oh, thank you, works! Well, for me this is a typical "hidden feature": It works if you know how to use it. Isn't there a "show all rooms" button in the element mobile client? This would be more intuitive (as additional button/option for people like me).

**Comment by turt2live** [comment] 2020-08-27 14:04
That sort of button is a different issue: https://github.com/vector-im/element-web/issues/13141

**Comment by t3chguy** [comment] 2020-08-27 14:31
Duplicate of https://github.com/vector-im/element-web/issues/12988

**Closed by t3chguy** 2020-08-27 14:31 UTC
Labels: bug, regression
