### ISSUE TITLE
Consider showing room metadata if a room alias/ID is placed in the explore search bar

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#17088] opened 2021-04-28 12:37 UTC
#### Is your suggestion related to a problem?

In https://github.com/matrix-org/synapse/issues/9883 it was found that it could be unclear why one room would appear in the list of searchable rooms when typing in an alias, when that alias led to a completely different room. Turns out it was due to the separate room containing the alias in its topic, and the room the alias led to not actually being published to the public rooms list (Synapse will also search for rooms via their canonical alias).

#### Describe the solution you'd like.
Published or not, considering this window is currently the intended way to join via a room alias or ID in the UI, it might make sense to show a (slightly visually separated) entry at the top of the public rooms list with details of the room you've typed in the alias/ID for.

#### Describe alternatives you've considered.
The current situation is that unless the room has been published to the public rooms directory, nothing will show in the list of rooms until you hit the small "Join" button.

It may be also just be simpler to split out the room search and room join actions from the same input field.

#### Additional context
Showing metadata about rooms that aren't yet known to your homeserver will probably require [peeking over federation](https://github.com/matrix-org/matrix-doc/pull/2444) to be implemented first.

**Comment by t3chguy** [comment] 2021-04-28 12:40
This is largely a duplicate of https://github.com/vector-im/element-web/issues/14980 - and I'm considering closing it as such as this is a proposal for a solution vs that one which is the issue without specifying a solution

**Comment by anoadragon453** [comment] 2021-04-28 12:56
@t3chguy That sounds like a good idea (I say, being completely unbiased in the matter :innocent:).

**Closed** 2021-04-28 13:07 UTC
Labels: T-Enhancement
