### ISSUE TITLE
Alt+shift hotkey in element opens menu

### ISSUE THREAD

**Issue by maxmenGMK** [vector-im/element-web#20095] opened 2021-12-08 07:54 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…
I am using ubuntu 20 and i bind my hotkeys to switch between the layots "alt+Shift" as usual it was in the windows. The  "always show the menu" in element settings must be disabled. 

#### What happened instead?
When element app is open i cant to use these hotkeys to change the keyboard layot without problems because the pointer (cursor) is moving to the elements menu when i am using it (alt+shift) and i have to move the pointer (cursor) back to the text input field with the mouse or over another method. It is very unusable and it is irritates. I was try to find the element hotkeys tuning to switch these hotkey off but there was no result.

### Operating system

Ubuntu 20

### Application version

Element: 1.9.6 Версия Olm: 3.2.3

### How did you install the app?

i dont remember

### Homeserver

my own server

### Will you send logs?

No

**Comment by t3chguy** [comment] 2021-12-08 08:51
Duplicate of https://github.com/vector-im/element-web/issues/3871

**Closed by t3chguy** 2021-12-08 08:51 UTC
Labels: T-Defect
