### ISSUE TITLE
Matrix user nicks not rendering in IRC bridged rooms

### ISSUE THREAD

**Issue by emonty** [vector-im/element-web#17917] opened 2021-07-08 16:21 UTC
<img width="1098" alt="Screen Shot 2021-07-08 at 10 41 27" src="https://user-images.githubusercontent.com/95156/124956040-33843180-dfdd-11eb-9def-0bd13153ab76.png">

#### Description

You can see the lines from 10:34 and 10:35 have icons but no name rendered. The channel, #_oftc_#opendev:matrix.org, is a matrix irc bridge channel. The two of us speaking at those times are coming in via matrix.

In native matrix channels this problem does not happen. 

#### Steps to reproduce

This happens using element desktop for Mac. I have tried restarting element several times - issue persists. HOWEVER - I tried the same version of element on a different laptop and it does not exhibit the issue.

Logs being sent: yes

#### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS
- **Version**: 1.7.32

**Comment by emonty** [comment] 2021-07-08 16:24
<img width="1130" alt="Screen Shot 2021-07-08 at 11 22 42" src="https://user-images.githubusercontent.com/95156/124957616-e30dd380-dfde-11eb-9c84-e03313ecf56b.png">

Oh look - if I increase the nick column width the nicks show up but super shifted - it seems it's spacing it for the matrix id detail which is otherwise hidden. (I moused over one to show that)

**Comment by SimonBrandner** [comment] 2021-07-08 16:49
This is one of the IRC layout regressions caused by https://github.com/matrix-org/matrix-react-sdk/pull/5880 and by one more PR whose name I don't remember

**Comment by SimonBrandner** [comment] 2021-07-10 18:03
Closing in favour of https://github.com/vector-im/element-web/issues/17930

**Closed by SimonBrandner** 2021-07-10 18:03 UTC
Labels: A-IRC-Layout, T-Defect, X-Regression
