### ISSUE TITLE
List of servers (public room search) not scrollable

### ISSUE THREAD

**Issue by hex-m** [vector-im/element-web#26085] opened 2023-08-31 08:09 UTC
### Steps to reproduce

1. add multiple servers to check their public room directory
2. once the list is longer than your screen/window is high, you can't reach the first entry anymore

![Screenshot from 2023-08-31 10-07-46](https://github.com/vector-im/element-web/assets/16013327/195fae6a-d447-44d3-bba0-d0c80a49b3d0)

#### What did you expect?

the scroll wheel should work

#### What happened instead?

the scroll wheel doesn't work

### Operating system

Debian GNU/Linux 12

### Application version

tested with Element Desktop 1.11.39 and Element 1.11.26 in Firefox 102.14.0esr (64-bit)

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-08-31 08:41
Duplicate of https://github.com/vector-im/element-web/issues/25983

**Closed by t3chguy** 2023-08-31 08:41 UTC
Labels: T-Defect
