### ISSUE TITLE
Voice messages break conversations, can't send messages anymore

### ISSUE THREAD

**Issue by Mozoloa** [vector-im/element-web#21331] opened 2022-03-06 19:26 UTC
### Steps to reproduce

1. Open Element Web or Desktop
2. Open any conversation and record a vocal message
3. Whether you send it (sending it works, the glitch isn't there) or cancel/trash it, the field is now blocked and glitched this way and you can't click "send a message", nor write:
 ![image](https://user-images.githubusercontent.com/20817233/156938732-b17d5df0-ac44-4301-8b08-aa6f827cfa0c.png)
4. Only this conversation is affected, the other ones work and you can check them
5. When you come back to the conversation, it shows you this : 
![image](https://user-images.githubusercontent.com/20817233/156938773-f11142da-c9b1-4b7d-b3aa-a2ca852e5b50.png)
 as if you hadn't sent it, (whether you had sent it, or deleted it), sending "send" won't send anything, the conversation is still blocked until app restart/browser refresh

#### What did you expect?
I expect my vocal messages to work like they've always done
#### What happened instead?
It breaks the conversation and I can't write messages until I refresh the browser or restart the app

### Operating system

Windows 10 21H1

### Application version

Element 1.10.6 Olm 3.2.8

### How did you install the app?

https://element.io

### Homeserver

matrix.ems.gg, private synapse server by etke.cc

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-03-06 20:20
Duplicate of https://github.com/vector-im/element-web/issues/21151, which is fixed in the upcoming version

**Closed by robintown** 2022-03-06 20:20 UTC
Labels: T-Defect
