### ISSUE TITLE
Threads sidebar getting stuck in individual threads

### ISSUE THREAD

**Issue by alsoknownaslj** [vector-im/element-web#23852] opened 2022-11-28 17:30 UTC
### Steps to reproduce

1. Open thread sidebar
2. Click into a specific thread
3. Click the 'back' arrow to get back to the list of threads 

#### What did you expect?
Being able to go back to the list of threads

#### What happened instead?
It gets 'stuck,' i.e. when I click the back button it refreshes but doesn't navigate back to the lit. It stays in the current thread.

### Operating system

macOS Ventura 13.0

### Will you send logs?

No

**Comment by gsouquet** [comment] 2022-11-29 09:02
Possible duplicate of https://github.com/vector-im/element-web/issues/23852

**Comment by Shadowfiend** [comment] 2022-12-06 02:23
@gsouquet that issue number is this issue 😬

**Comment by gsouquet** [comment] 2022-12-12 09:19
Possible duplicate of https://github.com/vector-im/element-web/issues/23764
Thanks for the heads up @Shadowfiend

**Closed** 2023-01-23 13:35 UTC
Labels: T-Defect, S-Minor, O-Uncommon, A-Threads
