### ISSUE TITLE
cannot dismiss "new login. was this you?" notification

### ISSUE THREAD

**Issue by GreenBattery** [vector-im/element-web#20446] opened 2022-01-08 23:09 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

- after login in on an android phone, a dialog pops up saying: "New Login. Was this you?" with options to check your devices or "later" to dismiss. 
- This dialog cannot be dismissed, even after restarting the application. cannot be moved, and obscures some parts of the UI.

<img width="337" alt="element-undismissible" src="https://user-images.githubusercontent.com/16048186/148662908-09cd7181-172e-460e-8e45-45c35ad3a70e.png">

#### What did you expect?
To be able to dismiss this dialog

#### What happened instead?
there is no obvious way to dismiss this dialog. The "Later" button is not responsive

### Operating system

Windows 10

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

downloaded the app from element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-01-09 06:56
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/17667

**Closed by SimonBrandner** 2022-01-09 06:56 UTC
Labels: T-Defect
