### ISSUE TITLE
Support variable playback speed for Voice Messages

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-web#19655] opened 2021-11-08 10:05 UTC
As a user playing a voice message
I can choose a playback speed
So that I can listen to very long messages more quickly

Consideration to be given to the correct playback speeds. WhatsApp has 1x 1.5x and 2x, but should we also offer slower speeds? (e.g. 0.5x speed)

**Comment by robintown** [comment] 2021-11-08 16:20
Duplicate of https://github.com/vector-im/element-web/issues/19228

**Closed by robintown** 2021-11-08 16:20 UTC
Labels: X-Needs-Design, A-Voice Messages
