### ISSUE TITLE
Sometimes main timeline messages appear on a thread as well

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22380] opened 2022-05-28 05:04 UTC
### Steps to reproduce

1. Open https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$o_u7bf4h1gbFReQlE17NzfSL180iC_uoA-fCS42HFHA?via=matrix.org&via=privacytools.io&via=mozilla.org

#### What did you expect?

Main timeline messages should not appear on the thread.

#### What happened instead?

Sometimes they appear on the thread as well. I think it is not expected. The issue is reproduced intermittently.

![Untitled](https://user-images.githubusercontent.com/3362943/170810447-77d1c52a-15bc-41a0-a74a-5a7e84e8f088.png)

![Untitled](https://user-images.githubusercontent.com/3362943/170810517-8f100758-c9e8-4188-8b74-22a2965b7a04.png)

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-05-28 07:45
Duplicate of https://github.com/vector-im/element-web/issues/21613

Next time you see it please send logs.

**Closed by t3chguy** 2022-05-28 07:45 UTC
Labels: T-Defect

**Comment by luixxiul** [comment] 2022-05-28 08:39
I did not notice that log could be sent from the UI directly. I got the same issue and sent the log :-)
