### ISSUE TITLE
Forward message should probably quote to show the message was from.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17804] opened 2021-06-28 01:40 UTC
Currently it blindly forwards it direct, switching the sender to appear to be you.  This seems unlikely to be the desired behaviour - it'd be better to show it as a forward (like you would on email), quoting the original message - rather than spoofing it to appear to come from you.

<img width="555" alt="Screenshot 2021-06-28 at 02 39 15" src="https://user-images.githubusercontent.com/1294269/123567499-35b6e680-d7ba-11eb-8159-7d79f3474299.png">

^ I didn't say this, Travis did!

**Comment by t3chguy** [comment] 2021-06-28 07:27
Duplicate of https://github.com/vector-im/element-web/issues/4747

**Closed by t3chguy** 2021-06-28 07:27 UTC
Labels: T-Defect
