### ISSUE TITLE
Reactions sometimes counted multiple times in the buttons below messages

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#11161] opened 2019-10-18 21:03 UTC
Not sure of the cause yet, but I have seen (and others have reported) that reactions can be counted twice in the row of buttons below a message.

There are not duplicate reaction events in the timeline when this happens. Refreshing Riot makes the problem go away. Somehow, the `Relations` structure for the event ends up with several copies of seemingly the same event.

It be best to have a clear reproduction case... Without that, the best I can imagine is just strengthening `Relations` to ignore events with the same ID as one it already has... It would still be best to understand what's actually going wrong.

**Comment by anoadragon453** [comment] 2020-02-12 14:04
Issue with screenshot and rageshake: https://github.com/vector-im/riot-web/issues/11710

**Comment by ara4n** [comment] 2020-02-13 09:55
I'm pretty sure this is because of https://github.com/matrix-org/matrix-doc/pull/1849/files#diff-07b4d0d635f906073d643f758ae283bdR194.

**Comment by tredondo** [comment] 2020-05-07 19:56
@jryans: I could reliably reproduce reacting twice with the same emoji to a given message in #13586. Not sure if that is a dupe of this issue, but @turt2live seems to believe so.

**Comment by jryans** [comment] 2020-05-11 11:28
> @jryans: I could reliably reproduce reacting twice with the same emoji to a given message in #13586. Not sure if that is a dupe of this issue, but @turt2live seems to believe so.

Looks like that's in fact a separate issue with different emoji character sequences. In any case, thanks for reporting.

**Comment by bwindels** [comment] 2021-05-19 09:55
Given that at the time of writing, element web aggregates reactions completely client-side, this must be a client bug. Events in https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/models/relations.js are deduplicated by using a `Set`, which compares object references to determine identity. So if somehow a reaction snuck in and wasn't deduplicated with an event object we already know about, this could easily happen.

**Closed** 2021-05-19 12:23 UTC
Labels: A-Reactions, P2, T-Defect
