### ISSUE TITLE
formatted_body not encoding < character in nickname pill properly

### ISSUE THREAD

**Issue by neilalexander** [vector-im/element-web#15583] opened 2020-10-28 11:09 UTC
Apparently having `<` in a nickname pill can cause message rendering issues - it appears they don't get encoded properly in `formatted_body` therefore it is treated like a malformed HTML tag.

The below screenshot illustrates the error - `Mathijs` sent a message with a nickname pill containing a `<` and the rest of his message was not rendered as a result.

<img width="732" alt="Screenshot 2020-10-28 at 11 02 45" src="https://user-images.githubusercontent.com/310854/97428023-50744b00-190d-11eb-9a9b-7ef7c9508c72.png">

### Version information

- **Platform**: Desktop
- **OS**: macOS
- **Version**: 1.7.11

**Comment by jryans** [comment] 2020-11-20 11:42
Related to https://github.com/vector-im/element-web/issues/15651 which is more about receiving messages that aren't escaped properly. For this one though, we should be escaping the name on send.

**Comment by t3chguy** [comment] 2020-11-20 12:16
Looks related to https://github.com/vector-im/element-web/issues/15525 in that case

**Comment by jryans** [comment] 2021-03-25 11:22
From @gsouquet's investigation, it looks like Element does actually escape these on send properly, so this is more about receiving such messages from other clients who might have failed to escape the HTML body correctly.

**Comment by gsouquet** [comment] 2021-03-30 09:47
At this stage I could not reproduce this issue using Element at all.

The issue is triggered by the call to `htmlSanitiser` in `HtmlUtils.ts#bodyToHtml`. That library does not really behave predictably with HTML that is not well-formed. `cheerio` (an other library used in Element) does not perform any better in that scenario

Both `cheerio` and `htmlSanitiser` lack a `isValidHtml` function that would help us determine whether to display the `formatted_body` or a fallback of any sort.
The overhead and performance cost the above would bring is also not negligeable

I probably won't make any updates to Element at this stage and will focus on finding the origin of those messages when @neilalexander is back from holidays

**Comment by t3chguy** [comment] 2023-07-18 16:11
Closing in favour of https://github.com/vector-im/element-web/issues/15651

**Closed by t3chguy** 2023-07-18 16:11 UTC
Labels: T-Defect, P3, S-Major, A-Timeline
