### ISSUE TITLE
Ability to select audio & video devices from within a voip 1:1 call.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18559] opened 2021-08-15 22:05 UTC
#### What would you like to do?

I want to be able to switch microphone, speaker and camera devices while on a 1:1 call (or at least see which ones it thinks it's using).

#### Why would you like to it?

I have multiple mics which come and go depending on where I plug my computer in, and want to know which it's using, and switch to the right one if needed.

#### How would you like to achieve it?

Copying the Jitsi UI where the audio & video mute buttons have a context menu to let you select the device.

**Comment by SimonBrandner** [comment] 2021-08-16 05:51
Duplicate of https://github.com/vector-im/element-web/issues/15595 and others

**Closed by SimonBrandner** 2021-08-16 05:51 UTC
Labels: T-Enhancement
