### ISSUE TITLE
Move user's avatar to right side

### ISSUE THREAD

**Issue by the0demiurge** [vector-im/element-web#10357] opened 2019-07-17 07:40 UTC
User's avatar and other's avatars are all left side, which makes it a little hard to distinguish which user sent that message. Especially when someone uses similar avatars.

For example:

## Easy to distinguish:
![图片](https://user-images.githubusercontent.com/11363529/61356640-5aee0b00-a8a9-11e9-9d9a-c68fcef8a324.png)

## Hard to distinguish:
![图片](https://user-images.githubusercontent.com/11363529/61356334-ae138e00-a8a8-11e9-85e7-926129bd7b45.png)

**Comment by robintown** [comment] 2021-07-16 04:48
Essentially a duplicate of #4635, which is coming Soon™

**Closed by robintown** 2021-07-16 04:48 UTC
Labels: T-Enhancement
