### ISSUE TITLE
Button to find the most recent notif in a room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23405] opened 2022-10-03 20:58 UTC
#### What would you like to do?

I have a red badge on a room.  I want to know what it's about.  I have no way of finding it short of manually paginating back through the room (or going to NotifPanel and finding it buried in other ones)

#### Why would you like to do it?

To find my missed notifs

#### How would you like to achieve it?

perhaps have a (^) "jump to last notif" overlay in the top right, similar to "jump to last unread msg"?

**Comment by SimonBrandner** [comment] 2022-10-04 06:46
Duplicate of https://github.com/vector-im/element-meta/issues/217

**Closed by SimonBrandner** 2022-10-04 06:46 UTC
Labels: T-Enhancement
