### ISSUE TITLE
Forward now causes room to be marked as unread

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#22160] opened 2022-05-12 10:09 UTC
### Steps to reproduce

1. Forward an event to a room you're not currently viewing
2. Observe room on the left nav

#### What did you expect?
Room should not be marked as unread, but should move to the top if sorted by Activity

#### What happened instead?
Room is marked as unread with the white dot on the left nav, even though it is my own event. This didn't happen before and was changed recently.

### Operating system

Arch Linux

### Browser information

Firefox 100

### URL for webapp

N/A

### Application version

Element version: 1.10.12-16-g479d4bf64-dirty Olm version: 3.2.8

### Homeserver

N/A

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-05-12 10:11
This unread is done by the server, not the client. Related to https://github.com/matrix-org/synapse/issues/9716 - I suggest opening an issue in https://github.com/matrix-org/synapse

**Comment by t3chguy** [comment] 2022-05-12 10:11
Oh wait, I misread I thought you meant it *cleared* the unread

**Comment by BurnyBoi** [comment] 2022-05-12 10:16
Right, it marks it as unread, not clears. Like when I forward to the room, this happens:
![image](https://user-images.githubusercontent.com/41203525/168048399-0b18d965-5906-4e23-ba64-eba7c9d66786.png)

Moving the room to the top of the list when sorted by Activity makes sense, but marking it as unread with the white dot and bolded name makes no sense since it's my own event.

**Comment by SimonBrandner** [comment] 2022-05-14 08:38
@BurnyBoi, are you able to reliably reproduce this on develop.element.io. I am unable to do so

**Comment by BurnyBoi** [comment] 2022-05-15 17:36
> @BurnyBoi, are you able to reliably reproduce this on develop.element.io? I am unable to do so

I cannot, both with my matrix.org account and my account on my own homeserver

**Comment by SimonBrandner** [comment] 2022-05-15 17:53
> > @BurnyBoi, are you able to reliably reproduce this on develop.element.io? I am unable to do so
> 
> I cannot, both with my matrix.org account and my account on my own homeserver

If you are unable to reproduce this I am afraid, there isn't much for us to go on here. Without a proper reproduction case, we can't do anything here...

**Comment by SimonBrandner** [comment] 2022-05-16 06:50
Is there anyone who can reliably reproduce this?

**Comment by turt2live** [comment] 2022-09-21 21:03
Closing until reliable reproduction steps are identified: please open a new issue if you are still seeing this.

**Closed by turt2live** 2022-09-21 21:03 UTC
Labels: T-Defect, X-Cannot-Reproduce, A-Room-List, A-Notifications, A-Message-Forwarding
