### ISSUE TITLE
macOS notifies about unread message notification when element is started - just in treads 

### ISSUE THREAD

**Issue by greinick** [vector-im/element-web#25107] opened 2023-04-14 06:40 UTC
### Steps to reproduce

It happend with previous macOS and element versions to, but right now I have a macOS 13.3 system and element 1.11.29.

- Start element

#### What did you expect?

in that case - nothing

#### What happened instead?

- The macOS notify popup appears
- The mentioned "new" message is an answer in a tread and is already read - so not new.

### Operating system

macOS

### Application version

Element version 1.11.29

### How did you install the app?

from element.io

### Homeserver

Synapse 1.81.0

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-04-21 10:51
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-04-21 10:54
This should be fixed by „Issues to be fixed via the recursive relations MSC“ mentioned [here](https://github.com/vector-im/element-web/issues/24392).

Without any further information about the context or logs I would say this is most likely a duplicate of one of the issues mentioned in the epic.

If this issue still appears after release of the fix, pleas leave a comment!

**Closed by weeman1337** 2023-04-21 10:54 UTC
Labels: T-Defect
