### ISSUE TITLE
Search messages or (or more broadly, channels or spaces or networks) using attribute queries

### ISSUE THREAD

**Issue by caitp** [vector-im/element-web#25628] opened 2023-06-19 18:05 UTC
#### What would you like to do?

We should be able to write something discord-style like "user:@caitp@igalia.com since:w25 has:link -stackoverflow.com", or something like that.

#### Why would you like to do it?

Often, I want to find recent messages I posted. Searching for my username will find mentions by other people, but not my own messages.

The current implementation of search is pretty bad, and makes it very difficult to actually find anything, even when I know roughly what and when a message was posted. Any options to narrow down the search will help immensely and dramatically improve the experience of using any of the Element clients.

#### How would you like to achieve it?

I'd like to achieve it by having someone who is familiar with the limitations of the matrix specification to propose a solution and have someone familiar with the Element codebases implement it

### Have you considered any alternatives?

copying message links into a notes file, but that's pretty awful. Having a bot automatically catalog messages and support querying, but that's not any more efficient than having the server do this for us

**Comment by t3chguy** [comment] 2023-06-19 21:04
Duplicate of https://github.com/vector-im/element-meta/issues/1156

**Closed by t3chguy** 2023-06-19 21:04 UTC
Labels: T-Enhancement
