### ISSUE TITLE
Make emoji picker more accessible via arrow keys

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18857] opened 2021-09-01 09:14 UTC
#### What would you like to do?

I would like to be able to pick an emoji from the emoji picker via arrow keys.

#### Why would you like to do it?

Convenience, and also because of muscle memory from Discord.

### Additional context

https://github.com/vector-im/element-web/issues/11284 is related, but I feel that's an old internal issue. (with both task items crossed out, and a related PR)

The issue still persists, and so i'd like to replace that issue with this one as to give more context and information to the suggestion.

How it looks on discord;

https://user-images.githubusercontent.com/22740616/131645453-52416ddc-c9d2-4225-9c06-dea5ac707465.mp4

**Comment by t3chguy** [comment] 2021-09-01 09:17
Duplicate of https://github.com/vector-im/element-web/issues/17189

**Closed by t3chguy** 2021-09-01 09:17 UTC
Labels: T-Enhancement
