### ISSUE TITLE
Failed to login/sign in

### ISSUE THREAD

**Issue by licopper** [vector-im/element-web#15287] opened 2020-09-25 22:39 UTC
I'm trying to sign in into the Mozilla Addons chat using Firefox 80.0
 https://chat.mozilla.org/#/room/#addons:mozilla.org

And the login process drives me in circle. First I get to this page:
https://auth.mozilla.auth0.com/login?state=g6Fo2SB5UXItWHdwRDJLaWc4VG5NamFRVEtQZ2tZeHozWVA5YqN0aWTZIHUyRTFETEN4b2VudVFaeDk0eG8xRnpUSWl5N3VCTDdno2NpZNkgTEdLMzRWN3dUalo4dGtNU0NRaHhJMHluZmlNY0Fzdmc&client=LGK34V7wTjZ8tkMSCQhxI0ynfiMcAsvg&protocol=samlp&SAMLRequest=jVJdT8IwFP0rS9%2FZyvhQG7ZkQkQCKLJJIi%2BkbAWqazt7OwR%2Fvd0UiS%2FEt557zz339LQ9CZhEpdnJOXsvGRjnIHIJxJYDVGpJFAVuIRUMiElJHE0nxHcxKbQyKlU5%2Bh1oXh6gAEwbriRyotOxrySUgumY6T1P2fN8EqCdMQUQzxPqk%2Bc5dYXKypxqlwtvJajR%2FOABFbnv0cr1SjMorApDzsC655JWumeViuSepCqA3VSJWqHwJsNxq724%2Bkhel9fmbRr3n3aHET7KDZ%2BmEey3yBkNAsSzxsNLvzvE43SNu%2Fmytcg2tgNQspEEQ6UJkI993MA3Db%2BT%2BD5pdUizvUTO7CejWy4zLreX81l%2Fk4DcJ8msMXuME%2BQsmIb6OpaAwp7NmNR7tXOntA3jsmJVseY3NZUwabg5ovDf%2BQpmaEYNde0D97zz7rACfz9N%2BAU%3D&RelayState=https%3A%2F%2Fchat.mozilla.org%2F%23%2Froom%2F%23addons%3Amozilla.org

Next is this one:
https://accounts.firefox.com/oauth/?response_type=code&redirect_uri=https%3A%2F%2Fauth.mozilla.auth0.com%2Flogin%2Fcallback&scope=openid%20profile&state=zfQZ3lU8e7pXzz6PfO9KELrbg3HTdxpu&client_id=1a118eae25503e99

Then I get to the chat but as a Guest
https://chat.mozilla.org/?loginToken=MDAxOWxvY2F0aW9uIG1vemlsbGEub3JnCjAwMTNpZGVudGlmaWVyIGtleQowMDEwY2lkIGdlbiA9IDEKMDAyN2NpZCB1c2VyX2lkID0gQGJyb3dza2k6bW96aWxsYS5vcmcKMDAxNWNpZCB0eXBlID0gbG9naW4KMDAxZGNpZCB0aW1lIDwgMTYwMTA3MzU1ODU5MgowMDJmc2lnbmF0dXJlIC4xLjEXf_W1grDJR9j0K4gziMa74GtpMvLs28pNYxc9Cg#/room/#addons:mozilla.org

The process begins and the same.
What am I doing wrong?

**Comment by t3chguy** [comment] 2020-09-28 09:20
I cannot reproduce this, do you have any browser extensions/settings which prevent cookies/localStorage?

The last link there would only not work if the localStorage didn't persist from the first link.

**Comment by novocaine** [comment] 2021-10-04 16:06
I'm closing this as the OP hasn't responded with more info, and its been a while ..

**Closed by novocaine** 2021-10-04 16:06 UTC
Labels: T-Other, Z-Mozilla
