### ISSUE TITLE
button "go to latest messages" do not work correctly

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#15731] opened 2020-11-15 22:19 UTC
![1](https://user-images.githubusercontent.com/1297163/99198299-7e013580-27e3-11eb-8863-c7a00eff26aa.png)
![2](https://user-images.githubusercontent.com/1297163/99198303-82c5e980-27e3-11eb-80da-04d3ec213b5d.png)
![3](https://user-images.githubusercontent.com/1297163/99198306-85284380-27e3-11eb-99ee-21dcc6e29829.png)
![4](https://user-images.githubusercontent.com/1297163/99198307-878a9d80-27e3-11eb-9787-56983afbcb33.png)
![5](https://user-images.githubusercontent.com/1297163/99198308-89546100-27e3-11eb-808c-8ce466052691.png)

### Description

new messages hide in bottom. 

### Steps to reproduce

- select some room with showed "go to end" button
- press to this button - messages scrolled to end, but button not hide
- type and send some count of messages
- see, that latest messages hided in end and not show
- if press "go to end" button again - it show

If user press "go to end" button - it must be hided. If user after that send messages - window must autoscrolled to end and show latest messages.

### Version information

- **Platform**: desktop
- **OS**: GNU/Linux Ubuntu 16.0.4 LTS amd64
- **Version**:  1.7.13

**Comment by progserega** [comment] 2020-11-15 22:20
It is occur in latest desktop version. Before it is not occur.

**Comment by progserega** [comment] 2020-11-15 22:25
But some time in some rooms - it work correctly...

**Comment by turt2live** [comment] 2020-11-16 05:23
I think this is a duplicate of https://github.com/vector-im/element-web/issues/11805

**Closed by turt2live** 2020-11-16 05:23 UTC
Labels: bug, ui/ux
