### ISSUE TITLE
Add an option to disable URL previews for specific users in specific rooms

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#11211] opened 2019-10-24 10:30 UTC
For example, in `#synapse-dev:matrix.org`, the NEB bot is quite talkative, and in every message about an issue or a PR usually mentions the metadata I need about the issue or PR along with its link, which means that URL preview uses a lot of space on the screen to display information the user either already has or doesn't need.
On the other hand, other users might post a link to a tool, an issue, a PR, etc., without mentioning all of that data, so URL previews are helpful in this case.
A per-room setting allowing users to disable URL previews for messages posted by specific users could solve this kind of issues.

**Comment by turt2live** [comment] 2022-05-07 03:57
Effective duplicate of https://github.com/vector-im/element-web/issues/5717

**Closed by turt2live** 2022-05-07 03:57 UTC
Labels: A-URL-Previews, T-Enhancement
