### ISSUE TITLE
Add option for resize image before sending

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#17305] opened 2021-05-15 00:03 UTC
#### Is your suggestion related to a problem? Please describe.
When I send image over web-element - image send in original size. If I send image to user, which use mobile client - he sayd me, that "element is to slow", because image download was more time.

#### Describe the solution you'd like.
1. send image in reduce size by default
1. Please redesign dialog send file as in android-element: add option "send in original size" disabled by default.

#### Additional context
When resize image - please, store in image exif information (date of shot, geo-tags and other).

**Comment by t3chguy** [comment] 2021-05-15 00:04
Duplicate of https://github.com/vector-im/element-web/issues/14047

**Closed by t3chguy** 2021-05-15 00:04 UTC
Labels: T-Enhancement
