### ISSUE TITLE
3 useless notifications when a call is accepted 

### ISSUE THREAD

**Issue by PxBCPG** [vector-im/element-web#20362] opened 2021-12-27 10:46 UTC
### Steps to reproduce

When I call someone, the moment when he will answer the call will come with 3 notifications (for android and MacOS at least), just to say that we're online. 

### Outcome

Those notifications are useless, so it could be great if there weren't there. 

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2021-12-27 11:20
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/7941

**Closed by SimonBrandner** 2021-12-27 11:20 UTC
Labels: T-Defect
