### ISSUE TITLE
Something weird happened when I clicked to join a room

### ISSUE THREAD

**Issue by wildwestrom** [vector-im/element-web#23744] opened 2022-11-10 09:59 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
I was looking through a matrix space.
2. What do you click?
"Join room"
It may also be notable that it was a space within a space. Maybe element desktop can't handle nested spaces?

#### What did you expect?
Just join the room.
#### What happened instead?
Got a "Something went wrong!" message, and the new room didn't show up on the sidebar.

### Operating system

Arch GNU/Linux

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### How did you install the app?

Arch community repository

### Homeserver

https://matrix-client.matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-11-10 10:01
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-11-10 10:01 UTC
Labels: T-Defect
