### ISSUE TITLE
Change "clear cache and reload" button to yellow

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#17987] opened 2021-07-13 22:29 UTC
#### Is your suggestion related to a problem? Please describe.
I often use the "clear cache" button to refresh my client's sync state from a particular homeserver, to diagnose ongoing issues.

I often get scared i accidentally press the "deactivate account" button, as that one also exists at the "bottom" of a settings page.

I cant simply remember "red = dont press" because of this, and i have to double-check (often white against red, as in dark mode it's not very legible) the naming of the button before i press it.

#### Describe the solution you'd like.
Changing the button to yellow to reflect a "tentative danger"-esc design language of the button would help a bunch with differentiating the button's action inbetween other "definitely destructive"-red buttons.

#### Describe alternatives you've considered.
Changing the button to green, I'm on the fence for this one, as the button's effects could technically be "disruptive" for a user depending on how fast their homeserver is (and how big their account is).

**Comment by robintown** [comment] 2021-07-14 01:14
Yellow isn't used anywhere else in the app, I think the more "correct" thing design-wise would probably be to make it a red outline button

![Screenshot 2021-07-13 at 21-13-30 Element](https://user-images.githubusercontent.com/48614497/125545188-25d6997f-f307-40aa-be41-0ef307395d17.png)

**Comment by aaronraimist** [comment] 2021-07-14 09:02
Duplicate of https://github.com/vector-im/element-web/issues/7536

**Closed by aaronraimist** 2021-07-14 09:02 UTC
Labels: A-Appearance, A-User-Settings, T-Enhancement, X-Needs-Design
