### ISSUE TITLE
Emoji verification pop up can be accidentally dismissed.

### ISSUE THREAD

**Issue by vchernin** [vector-im/element-web#18782] opened 2021-08-25 18:33 UTC
### Steps to reproduce

1. Log in to another device/browser and initiate emoji verification.
2. When the emojis pop up, click outside the pop up box.
Doing so will dismiss the current emoji verification and cause you to have to restart it to verify the new device/browser

### What happened?

An misclick meant I had to re go through the dialogs to initiate the emoji verification. It's not a lot of work, and only takes few seconds, but it's a papercut that affects ease of verification.

### What did you expect?

The dialog should only be closable using the x (close button top right in dialog). Or maybe it could at least warn you.

### Application version

Element version: 1.8.1 Olm version: 3.2.3

### How did you install the app?

Web and Linux (Flatpak)

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment] 2022-03-28 08:20
Closing as duplicate of #6109

**Closed by t3chguy** 2022-03-28 08:20 UTC
Labels: T-Defect, S-Minor, X-Needs-Design, A-E2EE-SAS-Verification, O-Occasional
