### ISSUE TITLE
The sidebar is not able to collapse properly.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [vector-im/element-web#19097] opened 2021-09-19 21:55 UTC
### Steps to reproduce

1. Drag the sidebar left-ward to collapse it so that its width shall span one column.

### What did you expect?
The side-bar should be displayed correctly.

### What happened?
http://user-images.githubusercontent.com/42837531/133940420-fbf9f0a3-21b7-487b-b637-8a27ee8876ba.PNG

### Operating system

http://silverblue.fedoraproject.org

### Application version

Element version: 1.8.4 Olm version: 3.2.3

### How did you install the app?

http://github.com/flathub/im.riot.Riot

### Homeserver

//MATRIX.ORG

### Have you submitted a rageshake?

No

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-09-19 21:55
http://github.com/vector-im/element-web/issues/19097

**Comment by robintown** [comment] 2021-09-19 23:43
Duplicate of https://github.com/vector-im/element-web/issues/17068

**Closed by robintown** 2021-09-19 23:43 UTC
Labels: T-Defect
