### ISSUE TITLE
Tray icon doesn't show on tray

### ISSUE THREAD

**Issue by hrqmonteiro** [vector-im/element-web#24187] opened 2023-01-08 20:27 UTC
### Steps to reproduce

I just open the app and it doesn't show the icon, even though i allow it in the options...

![Screenshot from 2023-01-08 17-26-57](https://user-images.githubusercontent.com/17055027/211217455-2fff2f46-70a6-41be-a3f3-494e0c80f511.png)

### Outcome

Tray icon doesn't show...

### Operating system

Fedora 37

### Application version

Element version: 1.11.17 Olm version: 3.2.12

### How did you install the app?

Flatpak

### Homeserver

Idk

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-01-09 07:15
Thanks for reporting the issue @hrqmonteiro . This looks like a duplicate of #23993. You can follow the other issue for updates.

**Comment by weeman1337** [comment] 2023-01-09 07:15
Duplicate of #23993

**Closed by weeman1337** 2023-01-09 07:15 UTC
Labels: T-Defect
