### ISSUE TITLE
Input focus bug locks up Brave/Chromium

### ISSUE THREAD

**Issue by jason-oliveira** [vector-im/element-web#21565] opened 2022-03-26 01:16 UTC
### Steps to reproduce

1. use brave browser or Chromium
2. start up element
3. eventually mouseOver reply/emoji button one too many times
4. watch cursor rapidly switch from arrow to hand icon multiple times per second, freezing Brave and locking the browser (any other open window) from being able to accept input until the issue is resolved
5. have someone type in the active chat, and wait for the issue to resolve itself once enough CPU cycles are eaten.

#### What did you expect?
To be able to move my cursor from one part of the browser to another without freezing input

#### What happened instead?
input done froze.

### Operating system

Gentoo Linux

### Browser information

Brave 1.37.105

### URL for webapp

https://app.element.io

### Application version

Element version: 1.10.7, Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-03-26 04:41
Duplicate of https://github.com/vector-im/element-web/issues/21147

**Closed by robintown** 2022-03-26 04:41 UTC
Labels: T-Defect
