### ISSUE TITLE
message is stuck at the bottom

### ISSUE THREAD

**Issue by colemickens** [vector-im/element-web#16054] opened 2020-12-31 01:07 UTC
### Description

This message is stuck to the bottom of my client in a certain room:
https://matrix.to/#/!DcljdpAmkmotyoLCHU:matrix.org/$6iDMbkrWcF05TkprPRuQ1QDrGOljrkqNFT5k1s7FVCE?via=matrix.org

Screenshot:

![screenshot-1609376703](https://user-images.githubusercontent.com/327028/103389012-30a20480-4ac1-11eb-811d-ebef0386835b.png)

The message at the bottom was actually sent (and showed as sent) after the message where I sent the Gist link.

### Steps to reproduce

Unfortunately I don't know. This repros _very_ rarely on `element-web`, but, as you can see from the screenshot, I felt like there was message mis-ordering going on. It *may* have simply been that I saw my message "send" and then "re-order" multiple times until I realized it was just stuck. Or it may have been that matrix.org/the irc bridge/my client/my network was chugging and element-web got confused? Total handwaving speculation from me.

Log: _not sent_ I may be ignorant but it looked like there were lots of `keys` in the `issue.txt` and log files.

However, I did extract the internal room ID and then find the relevant events from the log and have shared them here, and some of `issue.txt`:

```
app = element-web
version = 1.7.16
user_agent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.7.16 Chrome/83.0.410    3.122 Electron/9.4.0 Safari/537.36
installed_pwa = false
user_id = @colemickens:matrix.org
device_id = AQENUTXKQ
```

```
❯ cat log-0.log| rg DcljdpAmkmotyoLCHU
2020-12-31T00:21:35.502Z I Switching to room id !DcljdpAmkmotyoLCHU:matrix.org at event undefined
2020-12-31T00:21:35.503Z I RVS update: !DcljdpAmkmotyoLCHU:matrix.org  loading? false joining? false initial? true shouldPeek? true
2020-12-31T00:21:35.523Z I [!DcljdpAmkmotyoLCHU:matrix.org] Current version: 5
2020-12-31T00:21:35.523Z I [!DcljdpAmkmotyoLCHU:matrix.org] Version capability:  {"default":"6","available":{"1":"stable","2":"stable","3":"stable","4":"stable","5":"stable","6":"stable"}}
2020-12-31T00:22:26.816Z I sendEvent of type m.room.message in !DcljdpAmkmotyoLCHU:matrix.org with txnId m1609374146816.3
2020-12-31T00:22:27.714Z I Event sent to !DcljdpAmkmotyoLCHU:matrix.org with event id $yhBrY7HjNKamFYIYgO5uubOwz5V9g2tRHQkBqyYO0-s
2020-12-31T00:22:27.714Z I setting pendingEvent status to sent in !DcljdpAmkmotyoLCHU:matrix.org event ID ~!DcljdpAmkmotyoLCHU:matrix.org:m1609374146816.3 -> $yhBrY7HjNKamFYIYgO5uubOwz5V9g2tRHQkBqyYO0-s
2020-12-31T00:22:45.292Z I sendEvent of type m.room.message in !DcljdpAmkmotyoLCHU:matrix.org with txnId m1609374165292.4
2020-12-31T00:22:45.661Z I Event sent to !DcljdpAmkmotyoLCHU:matrix.org with event id $F9azybKwzMNtII_bOsCyK0jsFR0rqfyOqhq0p7gkgwo
2020-12-31T00:22:45.661Z I setting pendingEvent status to sent in !DcljdpAmkmotyoLCHU:matrix.org event ID ~!DcljdpAmkmotyoLCHU:matrix.org:m1609374165292.4 -> $F9azybKwzMNtII_bOsCyK0jsFR0rqfyOqhq0p7gkgwo
2020-12-31T00:25:29.619Z I sendEvent of type m.room.message in !DcljdpAmkmotyoLCHU:matrix.org with txnId m1609374329619.5
2020-12-31T00:25:30.340Z I Event sent to !DcljdpAmkmotyoLCHU:matrix.org with event id $EeSLXQe_SLGVj_QGH7TtPiL5C8iXcxWBf9G3dj8hGQc
2020-12-31T00:25:30.340Z I setting pendingEvent status to sent in !DcljdpAmkmotyoLCHU:matrix.org event ID ~!DcljdpAmkmotyoLCHU:matrix.org:m1609374329619.5 -> $EeSLXQe_SLGVj_QGH7TtPiL5C8iXcxWBf9G3dj8hGQc
2020-12-31T00:27:20.514Z I sendEvent of type m.room.message in !DcljdpAmkmotyoLCHU:matrix.org with txnId m1609374440514.6
2020-12-31T00:27:21.101Z I Event sent to !DcljdpAmkmotyoLCHU:matrix.org with event id $bvz12uOyvUD9SMVeaOELUnZzT_YNE_hVzab07dZGihM
2020-12-31T00:27:21.101Z I setting pendingEvent status to sent in !DcljdpAmkmotyoLCHU:matrix.org event ID ~!DcljdpAmkmotyoLCHU:matrix.org:m1609374440514.6 -> $bvz12uOyvUD9SMVeaOELUnZzT_YNE_hVzab07dZGihM
2020-12-31T00:28:28.946Z I sendEvent of type m.room.message in !DcljdpAmkmotyoLCHU:matrix.org with txnId m1609374508946.7
2020-12-31T00:28:29.381Z I Event sent to !DcljdpAmkmotyoLCHU:matrix.org with event id $jizW3im_JbSwr0agERakWBQBdZUIEVBb1Kye_8Y8ULs
2020-12-31T00:28:29.381Z I setting pendingEvent status to sent in !DcljdpAmkmotyoLCHU:matrix.org event ID ~!DcljdpAmkmotyoLCHU:matrix.org:m1609374508946.7 -> $jizW3im_JbSwr0agERakWBQBdZUIEVBb1Kye_8Y8ULs
2020-12-31T00:28:36.034Z I sendEvent of type m.room.message in !DcljdpAmkmotyoLCHU:matrix.org with txnId m1609374516034.8
2020-12-31T00:28:36.926Z I Event sent to !DcljdpAmkmotyoLCHU:matrix.org with event id $uiLSodKvJdXD6k85tT6b3FDpnnLOjeXZBcGlbHOPIQM
2020-12-31T00:28:36.926Z I setting pendingEvent status to sent in !DcljdpAmkmotyoLCHU:matrix.org event ID ~!DcljdpAmkmotyoLCHU:matrix.org:m1609374516034.8 -> $uiLSodKvJdXD6k85tT6b3FDpnnLOjeXZBcGlbHOPIQM
2020-12-31T00:28:44.278Z I sendEvent of type m.room.message in !DcljdpAmkmotyoLCHU:matrix.org with txnId m1609374524278.9
2020-12-31T00:28:44.774Z I Event sent to !DcljdpAmkmotyoLCHU:matrix.org with event id $6iDMbkrWcF05TkprPRuQ1QDrGOljrkqNFT5k1s7FVCE
2020-12-31T00:28:44.774Z I setting pendingEvent status to sent in !DcljdpAmkmotyoLCHU:matrix.org event ID ~!DcljdpAmkmotyoLCHU:matrix.org:m1609374524278.9 -> $6iDMbkrWcF05TkprPRuQ1QDrGOljrkqNFT5k1s7FVCE
2020-12-31T00:31:57.717Z I sendEvent of type m.room.message in !DcljdpAmkmotyoLCHU:matrix.org with txnId m1609374717717.10
2020-12-31T00:31:58.568Z I Event sent to !DcljdpAmkmotyoLCHU:matrix.org with event id $wu3nB8LL8_QZiBXorJ_pIj0Cu-y2bIewKB3_j2eDGjY
2020-12-31T00:31:58.568Z I setting pendingEvent status to sent in !DcljdpAmkmotyoLCHU:matrix.org event ID ~!DcljdpAmkmotyoLCHU:matrix.org:m1609374717717.10 -> $wu3nB8LL8_QZiBXorJ_pIj0Cu-y2bIewKB3_j2eDGjY
2020-12-31T00:33:38.316Z I sendEvent of type m.room.message in !DcljdpAmkmotyoLCHU:matrix.org with txnId m1609374818316.11
2020-12-31T00:33:38.682Z I Event sent to !DcljdpAmkmotyoLCHU:matrix.org with event id $e7N51od_UUwColl5Grc-6cTfEEoh-ci5HDtxpPBlKLs
2020-12-31T00:33:38.682Z I setting pendingEvent status to sent in !DcljdpAmkmotyoLCHU:matrix.org event ID ~!DcljdpAmkmotyoLCHU:matrix.org:m1609374818316.11 -> $e7N51od_UUwColl5Grc-6cTfEEoh-ci5HDtxpPBlKLs
2020-12-31T00:33:49.468Z I sendEvent of type m.room.message in !DcljdpAmkmotyoLCHU:matrix.org with txnId m1609374829468.12
2020-12-31T00:33:49.826Z I Event sent to !DcljdpAmkmotyoLCHU:matrix.org with event id $lpseFgHZzuMbz_rmG5Xax0plFMcYGpnsm-lgSi6qrNY
2020-12-31T00:33:49.826Z I setting pendingEvent status to sent in !DcljdpAmkmotyoLCHU:matrix.org event ID ~!DcljdpAmkmotyoLCHU:matrix.org:m1609374829468.12 -> $lpseFgHZzuMbz_rmG5Xax0plFMcYGpnsm-lgSi6qrNY
2020-12-31T00:34:22.780Z I Switching to room id !DcljdpAmkmotyoLCHU:matrix.org at event undefined
2020-12-31T00:34:22.781Z I RVS update: !DcljdpAmkmotyoLCHU:matrix.org  loading? false joining? false initial? true shouldPeek? true
2020-12-31T00:34:22.799Z I [!DcljdpAmkmotyoLCHU:matrix.org] Current version: 5
2020-12-31T00:34:22.799Z I [!DcljdpAmkmotyoLCHU:matrix.org] Version capability:  {"default":"6","available":{"1":"stable","2":"stable","3":"stable","4":"stable","5":"stable","6":"stable"}}
2020-12-31T00:44:03.916Z I Switching to room id !DcljdpAmkmotyoLCHU:matrix.org at event undefined
2020-12-31T00:44:03.917Z I RVS update: !DcljdpAmkmotyoLCHU:matrix.org  loading? false joining? false initial? true shouldPeek? true
2020-12-31T00:44:03.937Z I [!DcljdpAmkmotyoLCHU:matrix.org] Current version: 5
2020-12-31T00:44:03.937Z I [!DcljdpAmkmotyoLCHU:matrix.org] Version capability:  {"default":"6","available":{"1":"stable","2":"stable","3":"stable","4":"stable","5":"stable","6":"stable"}}

```

If you need more of this log, I kept it, I can extract the entire chunk that contains any instance of the room id and then redact the JSON blobs from within. Let me know if that's necessary/

### Version information

- **Platform**: web (in-browser) or desktop? Desktop.
- Version: 
```
- Element version: 1.7.16
olm version: 3.2.1
```

For the desktop app:

- **OS**: Linux (NixOS)
- **Version**: from the current package def:
```
  version = "1.7.16";                                                                                                         
  src = fetchFromGitHub {                                                                                                     
    owner = "vector-im";                                                                                                      
    repo = "element-desktop";                                                                                                 
    rev = "v${version}";                                                                                                      
    sha256 = "sha256-mdHsw1Vi+2hrAF7biX3pJqfRaZU2lpw9zUZdcCm717g=";                                                           
  };                                                                                                                          
  electron = electron_9;
```

**Comment by t3chguy** [comment] 2020-12-31 09:55
Duplicate of https://github.com/vector-im/element-web/issues/16050

**Closed by t3chguy** 2020-12-31 09:55 UTC
