### ISSUE TITLE
Add Spaces to Room Directory

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#19277] opened 2021-10-04 16:58 UTC
#### What would you like to do?

Add a space to the room directory.

#### Why would you like to do it?

Adding a space to the room directory makes it more discoverable.

#### How would you like to achieve it?

Either allow users to add spaces to the existing room directory (since from a data perspective they are rooms), or have a separate section for a Space Directory.

**Comment by SimonBrandner** [comment] 2021-10-04 16:59
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/17264

**Closed by SimonBrandner** 2021-10-04 16:59 UTC
Labels: T-Enhancement
