### ISSUE TITLE
Restore option to turn off threads

### ISSUE THREAD

**Issue by strypey** [vector-im/element-web#26271] opened 2023-10-02 11:20 UTC
#### What would you like to do?

Turn off threads.

#### Why would you like to do it?

Two reasons. The main one is that I dislike threading. Even in web forums, I prefer apps like Discourse that don't do threading, and instead provide an anchor that links to the message being replied to. Discord is an example of this in a chat interface.

The second reason is that the implementation of threads in Element is confusing and frustrating to use, and full of bugs. It's really damaging the HX (Human eXperience) of the app for me.

#### How would you like to achieve it?

Add a control to the settings panel to turn off threads, like the one that used to be in All Settings > Labs.

### Have you considered any alternatives?

Using a different matrix app that doesn't have threads, or has an option to turn them off.

### Additional context

I've worked very hard not to let me frustration with threads in Element boil over onto you folks, who are all doing amazing work that I value and appreciate. Hope I succeeded!

**Comment by t3chguy** [comment] 2023-10-02 11:28
Duplicate of https://github.com/vector-im/element-meta/issues/1090

**Closed by t3chguy** 2023-10-02 11:28 UTC
Labels: T-Enhancement
