### ISSUE TITLE
Read receipts overlaps messages in timeline

### ISSUE THREAD

**Issue by bbhtt** [vector-im/element-web#20574] opened 2022-01-15 13:24 UTC
### Steps to reproduce

1. Send a reasonably long message
2. Have enough people read it so read receipts show up
3. Expand the read receipts by clicking +
 
See: 

![Screenshot](https://user-images.githubusercontent.com/62639087/149623285-87e91549-d18b-4a3a-8058-d3be66b848b0.png)

#### What did you expect?

I'm not sure if this is an expected outcome or an issue but the current behaviour looks a bit odd to me. I think they should at least be wrapped or shown in a separate menu after a fixed count passes so that they do not obstruct the messages sent in the timeline when expanded.

#### What happened instead?

Read receipt row obstructs timeline messages.

### Operating system

Arch Linux

### Browser information

Firefox 96

### URL for webapp

app.element.io

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### Homeserver

N/A

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-01-15 15:40
This is the expected behaviour

**Comment by daniellekirkwood** [comment] 2022-03-08 11:33
Marking this as a WTF issue and removing the Needs-Product label. 

This is currently the intended behaviour but it's less than ideal. The Design team should propose a solution to this bug. 

Thanks for raising!

**Comment by gsouquet** [comment] 2022-04-19 13:31
@niquewoodhouse this looks great. It might be helpful to open the right panel and show the full user profile. In the screenshot above we're missing infos like the Matrix ID or whether you've done the encryption dance with that user.

Might give that extra info in case someone tries to impersonate someone else.

Once this is ready to be worked on, could you assign this to @justjanne ?

**Comment by niquewoodhouse** [comment] 2022-04-20 10:49
> @niquewoodhouse this looks great. It might be helpful to open the right panel and show the full user profile. In the screenshot above we're missing infos like the Matrix ID or whether you've done the encryption dance with that user.
> 
> Might give that extra info in case someone tries to impersonate someone else.

Opening the right panel to the full user profile sounds like it might work, I don't personally use the right panel much so I'd like someone who does to try it out when we have a build to test.

I've amended the designs to include a tooltip that shows the Matrix ID when you hover over someone in the list.


https://user-images.githubusercontent.com/1587166/164214830-a1de3db4-656a-4b44-8242-3c78b1b75e27.mov

[Figma link](https://www.figma.com/file/T66ljRxRw3wh0Q9CcgWraM/%5BWeb%5D-Read-receipts-overlaps-messages-in-timeline?node-id=101%3A8455).

**Closed** 2022-04-22 15:09 UTC
Labels: A-Timeline, T-Enhancement, A-Read-Receipts, O-Occasional, Z-WTF
