### ISSUE TITLE
Ability to hide Spaces left-left panel from interface

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#19195] opened 2021-09-28 08:24 UTC
#### What would you like to do?
Will be good to have ability to hide (or disable) the Spaces "left left" panel from Element interfac, like we can hide the former Communities panel.

#### Why would you like to do it?
Because not all communities uses the Spaces feature, and in those cases the "Spaces" panel simply eats a very useful space on screen. So will be good to have an option "Hide Spaces panel" in settings.

**Comment by t3chguy** [comment] 2021-09-28 08:38
Duplicate of https://github.com/vector-im/element-web/issues/18898

**Closed by t3chguy** 2021-09-28 08:38 UTC
Labels: A-Spaces, T-Enhancement
