### ISSUE TITLE
deb package of 1.7.35 not available

### ISSUE THREAD

**Issue by wyrdthud** [vector-im/element-web#18352] opened 2021-08-03 05:40 UTC
when doing `sudo apt update` followed by `sudo apt -y full-upgrade`
I get an error stating 
> https://packages.riot.im/debian/pool/main/e/element-desktop/element-desktop_v1.7.35_amd64.deb 404  Not Found [IP: 2606:4700:20::ac43:46e2 443]

**Comment by SimonBrandner** [comment] 2021-08-03 05:42
Duplicate of https://github.com/vector-im/element-web/issues/18345

**Closed by SimonBrandner** 2021-08-03 05:42 UTC
