### ISSUE TITLE
Unable to accept an invitation

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24161] opened 2023-01-04 16:15 UTC
Reported by aka "help vampire".

### Steps to reproduce

I can't accept old invitations. Element loads something and says that user has left chat.

#### What did you expect?
Join to chat
#### What happened instead?
Popup with
```
Failed to join
The person who invited you has already left
```

### Operating system

Windows 7

### Application version

1.11.17, 1.11.22

### How did you install the app?

official website

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-01-11 11:05
@JeanPaulLucien please send logs.

**Comment by MadLittleMods** [comment] 2023-02-15 01:32
Duplicate of https://github.com/vector-im/element-web/issues/21676 and no debug logs here

**Closed by MadLittleMods** 2023-02-15 01:32 UTC
Labels: T-Defect, X-Needs-Info, S-Minor, A-Invite, O-Occasional

**Comment by JeanPaulLucien** [comment] 2023-02-23 00:22
@MadLittleMods 
My report is not duplicate of https://github.com/vector-im/element-meta/issues/1000 , because when I joined other user was in room. Today I have reproduced, I joined to chat that was "... left" before.

**Comment by JeanPaulLucien** [comment] 2023-02-23 00:31
It's invite from user on matrix.org
```
POST https://matrix-client.matrix.org/_matrix/client/r0/join/!kCzNXjTHZofRbHftpG%3Amatrix.org 404
fetch @ fetch.ts:62
requestOtherUrl @ fetch.ts:264
request @ fetch.ts:205
authedRequest @ fetch.ts:156
joinRoom @ client.ts:3999
await in joinRoom (async)
dis.dispatch.action @ RoomViewStore.tsx:541
i @ promise.ts:39
joinRoom @ RoomViewStore.tsx:539
onDispatch @ RoomViewStore.tsx:297
t._invokeCallback @ Dispatcher.js:214
t.dispatch @ Dispatcher.js:189
setTimeout (async)
dispatch @ dispatcher.ts:52
(anonymous) @ RoomView.tsx:1467
Promise.then (async)
(anonymous) @ RoomView.tsx:1465
ze @ react-dom.production.min.js:52
Ye @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Dr @ react-dom.production.min.js:100
kr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Pe @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mr @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Qt @ react-dom.production.min.js:73
```

**Comment by MadLittleMods** [comment] 2023-02-23 00:36
> My report is not duplicate of https://github.com/vector-im/element-meta/issues/1000 , because when I joined other user was in room.

How are you able to join the room and confirm that the other person is actually there? From your original report, you were running into an error dialog that says: "Failed to join: The person who invited you has already left"

Does it eventually allow you to join the room?
