### ISSUE TITLE
Session Keys lost

### ISSUE THREAD

**Issue by niccokunzmann** [vector-im/element-web#23547] opened 2022-10-19 07:39 UTC
### Steps to reproduce

1. I started the Element Desktop app

#### What did you expect?

It should open and I should see the chats that I saw before.

#### What happened instead?

It said that the session keys are lost  in a pop-up and offered me some logs.
I was not logged in any more after this.

### Operating system

Ubuntu 22

### Application version

there are no settings on the login screen

### How did you install the app?

forgot, could be apt

### Homeserver

chat.ccc-p.org

### Will you send logs?

Yes

issue.txt
```
text = User did not supply any additional text.
app = element-web
version = 1.11.10
user_agent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.10 Chrome/104.0.5112.114 Electron/20.1.4 Safari/537.36
installed_pwa = false
touch_input = false
user_id = @56496572859:matrix.org
device_id = guest_device
device_keys = [edited]
cross_signing_key = null
cross_signing_ready = false
cross_signing_supported_by_hs = true
cross_signing_key = null
cross_signing_privkey_in_secret_storage = false
cross_signing_master_privkey_cached = false
cross_signing_self_signing_privkey_cached = false
cross_signing_user_signing_privkey_cached = false
secret_storage_ready = false
secret_storage_key_in_account = false
session_backup_key_in_secret_storage = false
session_backup_key_cached = false
session_backup_key_well_formed = false
storageManager_persisted = true
storageManager_quota = 369967222407
storageManager_usage = 167559
storageManager_usage_indexedDB = 167559
mx_local_settings = {"RightPanel.phasesGlobal":null}
```
log:

```
Wed Oct 19 2022 08:36:26 GMT+0100 (British Summer Time) ::: Log database was created.2022-10-19T07:36:24.852Z I Initialised rageshake.
2022-10-19T07:36:24.852Z I To fix line numbers in Chrome: Meatball menu � Settings � Ignore list � Add /rageshake\.js$
2022-10-19T07:36:24.938Z I Using Electron platform
2022-10-19T07:36:25.146Z I Configuring rageshake persistence...
2022-10-19T07:36:25.211Z I Using WebAssembly Olm
2022-10-19T07:36:25.900Z I set language to en-us
2022-10-19T07:36:27.080Z I Application is running in production mode
2022-10-19T07:36:27.093Z I Vector starting at vector://vector/webapp/
2022-10-19T07:36:27.094Z I Verifying homeserver configuration
2022-10-19T07:36:27.094Z I Config uses a default_server_name - doing .well-known lookup
2022-10-19T07:36:27.094Z W DEPRECATED CONFIG OPTION: In the future, default_server_name will not be accepted. Please use default_server_config instead.
2022-10-19T07:36:29.745Z I Using homeserver config: {"hsUrl":"https://matrix-client.matrix.org","hsName":"matrix.org","hsNameIsDifferent":true,"isUrl":"https://vector.im","isDefault":true,"isNameResolvable":true,"warning":null}
2022-10-19T07:36:29.746Z I Updating SdkConfig with validated discovery information
2022-10-19T07:36:29.942Z I No previous session found.
2022-10-19T07:36:29.942Z I Doing guest login on https://matrix-client.matrix.org
2022-10-19T07:36:29.980Z I Starting load of AsyncWrapper for modal
2022-10-19T07:36:30.246Z I Registered as guest: @5...9:matrix.org
2022-10-19T07:36:30.247Z I setLoggedIn: mxid: @5...9:matrix.org deviceId: guest_device guest: true hs: https://matrix-client.matrix.org softLogout: false  freshLogin: undefined
2022-10-19T07:36:30.253Z I EventIndex: Deleting event index.
2022-10-19T07:36:30.829Z I Removing indexeddb instance: matrix-js-sdk:crypto
2022-10-19T07:36:30.830Z I Removed indexeddb instance: matrix-js-sdk:crypto
2022-10-19T07:36:30.895Z I IndexedDB worker is ready
2022-10-19T07:36:30.897Z I Deleted indexeddb data.
2022-10-19T07:36:30.897Z I StorageManager: Checking storage consistency
2022-10-19T07:36:30.897Z I StorageManager: Local storage supported? true
2022-10-19T07:36:30.897Z I StorageManager: IndexedDB supported? true
2022-10-19T07:36:30.897Z I StorageManager: Local storage contains data? false
2022-10-19T07:36:30.897Z I StorageManager: Crypto initialised? false
2022-10-19T07:36:31.078Z I StorageManager: Sync store using IndexedDB contains data? false
2022-10-19T07:36:31.379Z I StorageManager: Crypto store using IndexedDB contains data? false
2022-10-19T07:36:31.380Z I StorageManager: Storage consistency checks passed
2022-10-19T07:36:31.479Z I Session persisted for @5...9:matrix.org
2022-10-19T07:36:31.480Z I Lifecycle: Starting MatrixClient
2022-10-19T07:36:31.848Z I StorageManager: Persistent? true
2022-10-19T07:36:31.854Z I newscreen welcome
2022-10-19T07:36:35.744Z I EventIndex: Successfully initialized the event index
2022-10-19T07:36:35.850Z I EventIndex: Loaded checkpoints []
2022-10-19T07:36:35.851Z I IndexedDBStore.startup: connecting to backend
2022-10-19T07:36:35.852Z I MatrixClientPeg: waiting for MatrixClient store to initialise
2022-10-19T07:36:35.916Z I IndexedDB worker is ready
2022-10-19T07:36:36.133Z I IndexedDBStore.startup: loading presence events
2022-10-19T07:36:36.136Z I IndexedDBStore.startup: processing presence events
2022-10-19T07:36:36.137Z I Crypto: Starting up crypto store...
2022-10-19T07:36:36.138Z I connecting to indexeddb matrix-js-sdk:crypto
2022-10-19T07:36:36.227Z I Upgrading IndexedDBCryptoStore from version 0 to 11
2022-10-19T07:36:36.315Z I connected to indexeddb matrix-js-sdk:crypto
2022-10-19T07:36:36.320Z I Crypto: initialising roomlist...
2022-10-19T07:36:36.329Z I Crypto: initialising crypto object...
2022-10-19T07:36:36.329Z I Crypto: initialising Olm...
2022-10-19T07:36:36.329Z I Crypto: initialising Olm device...
2022-10-19T07:36:36.449Z I Crypto: loading device list...
2022-10-19T07:36:36.453Z I Crypto: fetching own devices...
2022-10-19T07:36:36.454Z I Crypto: adding this device to the store...
2022-10-19T07:36:36.458Z I Now tracking device list for @5...9:matrix.org
2022-10-19T07:36:36.458Z I Crypto: checking for key backup...
2022-10-19T07:36:36.459Z I Checking key backup status...
2022-10-19T07:36:36.459Z I Skipping key backup check since user is guest
2022-10-19T07:36:36.464Z I MatrixClientPeg: really starting MatrixClient
2022-10-19T07:36:36.467Z I Fetching new TURN credentials
2022-10-19T07:36:36.800Z I Attempting to send queued to-device messages
2022-10-19T07:36:36.801Z I MatrixClientPeg: MatrixClient started
2022-10-19T07:36:36.805Z I Attempting to get Jitsi conference information from homeserver
2022-10-19T07:36:36.806Z I Jitsi conference domain: meet.element.io
2022-10-19T07:36:36.807Z I All queued to-device messages sent
2022-10-19T07:36:36.814Z I Updating homeserver-configured integration managers...
2022-10-19T07:36:36.814Z I Homeserver has no integration managers
2022-10-19T07:36:36.815Z I Attempting to get Jitsi conference information from homeserver
2022-10-19T07:36:36.815Z I Jitsi conference domain: meet.element.io
2022-10-19T07:36:36.955Z I Saving device tracking data null
2022-10-19T07:36:37.029Z I Got TURN URIs: turn:turn.matrix.org:3478?transport=udp,turn:turn.matrix.org:3478?transport=tcp,turns:turn.matrix.org:443?transport=tcp refresh in 86400 secs
2022-10-19T07:36:37.059Z I Initial sync performed - resetting device tracking state
2022-10-19T07:36:37.059Z I Now tracking device list for @5...9:matrix.org
2022-10-19T07:36:37.065Z W Adding default global override for .org.matrix.msc3786.rule.room.server_acl
2022-10-19T07:36:37.068Z I MatrixClient sync state => %s PREPARED
2022-10-19T07:36:37.071Z I Starting key download for ["@5...9:matrix.org"]
2022-10-19T07:36:37.076Z I MatrixClient sync state => %s SYNCING
2022-10-19T07:36:37.078Z I generating oneTimeKeys
2022-10-19T07:36:37.089Z I Regenerating room lists: Startup
2022-10-19T07:36:37.089Z W Regenerating all room lists
2022-10-19T07:36:37.091Z W Resetting known rooms, initiating regeneration
2022-10-19T07:36:37.091Z W Resetting known rooms, initiating regeneration
2022-10-19T07:36:37.095Z I Saving device tracking data s....
2022-10-19T07:36:37.095Z I EventIndex: Adding initial crawler checkpoints
2022-10-19T07:36:37.097Z I Setting up Mjolnir: after sync
2022-10-19T07:36:37.097Z I Updating Mjolnir ban lists to: 
2022-10-19T07:36:37.099Z I Old unverified sessions: 
2022-10-19T07:36:37.099Z I New unverified sessions: 
2022-10-19T07:36:37.099Z I Currently showing toasts for: 
2022-10-19T07:36:37.270Z I generating fallback key
2022-10-19T07:36:37.390Z I got device keys for @5...9:matrix.org: {"guest_device":{"algorithms":["m.olm.v1.curve25519-aes-sha2","m.megolm.v1.aes-sha2"],"device_id":"guest_device","keys":{"curve25519:guest_device":"eS...w","ed25519:guest_device":"4o...7BY"},"signatures":{"@.....9:matrix.org":{"ed25519:guest_device":"SW...Q"}},"user_id":"@5....9:matrix.org","unsigned":{"device_display_name":"Element Desktop (Linux)"}}}
2022-10-19T07:36:37.391Z I got cross-signing keys for @5...9:matrix.org: {}
2022-10-19T07:36:37.395Z I Completed key download for @5...9:matrix.org
2022-10-19T07:36:37.396Z I Device list for @5...9:matrix.org now up to date
2022-10-19T07:36:37.402Z I calling uploadOneTimeKeys
2022-10-19T07:36:37.404Z I Old unverified sessions: 
2022-10-19T07:36:37.404Z I New unverified sessions: 
2022-10-19T07:36:37.404Z I Currently showing toasts for: 
2022-10-19T07:36:37.702Z I generating oneTimeKeys
2022-10-19T07:36:37.779Z I calling uploadOneTimeKeys
2022-10-19T07:36:37.897Z I Saving device tracking data s,,,,
2022-10-19T07:36:38.112Z I generating oneTimeKeys
2022-10-19T07:36:38.212Z I calling uploadOneTimeKeys
2022-10-19T07:36:38.446Z I generating oneTimeKeys
2022-10-19T07:36:38.512Z I calling uploadOneTimeKeys
2022-10-19T07:36:38.756Z I generating oneTimeKeys
2022-10-19T07:36:38.813Z I calling uploadOneTimeKeys
2022-10-19T07:36:39.068Z I generating oneTimeKeys
2022-10-19T07:36:39.134Z I calling uploadOneTimeKeys
2022-10-19T07:36:40.540Z I generating oneTimeKeys
2022-10-19T07:36:40.596Z I calling uploadOneTimeKeys
2022-10-19T07:36:41.016Z I generating oneTimeKeys
2022-10-19T07:36:41.072Z I calling uploadOneTimeKeys
2022-10-19T07:36:41.283Z I generating oneTimeKeys
2022-10-19T07:36:41.338Z I calling uploadOneTimeKeys
2022-10-19T07:36:41.626Z I generating oneTimeKeys
2022-10-19T07:36:41.682Z I calling uploadOneTimeKeys
2022-10-19T07:36:50.678Z I Starting load of AsyncWrapper for modal
2022-10-19T07:37:10.769Z I Sending bug report.
```

**Comment by uhoreg** [comment] 2022-10-19 21:25
Was this the first time you started the app?  Or did you run it before?

Can you post a screenshot?

**Comment by niccokunzmann** [comment] 2022-10-19 22:38
I ran the app before and was successfully logged in and this is why I posted this. I am logged in again and I forgot to take a screenshot. If it happens again, I would like to send one.

**Comment by uhoreg** [comment] 2022-10-20 18:42
Thanks for the response.   By chance, was the error message that you got the same as the one in https://github.com/vector-im/element-web/issues/23521 ?

> Some session data, including encrypted message keys, is missing. Sign out and sign in to fix this, restoring keys from backup.
> Your browser likely removed this data when running low on disk space. To help us prevent this in future, please send us logs.

**Comment by niccokunzmann** [comment] 2022-10-20 19:38
Yes, that is the message I saw.

**Comment by t3chguy** [comment] 2022-10-31 15:58
Duplicate of https://github.com/vector-im/element-web/issues/23123

**Closed by t3chguy** 2022-10-31 15:58 UTC
Labels: T-Defect, S-Critical, A-Electron, O-Uncommon
