### ISSUE TITLE
Label Threads as Beta

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#21351] opened 2022-03-08 10:40 UTC
When we release threads to the public, we initially need them to be labelled as beta. We'd like to start gathering feedback and finding bugs from the public, but threads will be missing some features around notifications, so it's helpful to flag that the feature isn't quite done yet. 

We will remove this label once we have launched Threads P1.

For web, this should include taking threads out of labs and making it available as a regular setting for all users.

**Comment by gsouquet** [comment] 2022-03-15 16:53
Duplicate of https://github.com/vector-im/element-web/issues/21351

**Comment by gsouquet** [comment] 2022-03-16 09:39
@janogarcia beta features also require some copy on the "settings" tab, alongside some little imagery that explain what the feature is.
If we decide that we can't opt-out, then I will add an option to hide the button.

<img width="710" alt="Screen Shot 2022-03-16 at 09 32 20" src="https://user-images.githubusercontent.com/769871/158561056-b00f630b-0387-40e3-9ffe-236328523580.png">

Would you be able to share copy + imagery for threads here?

**Comment by t3chguy** [comment] 2022-03-29 10:03
@janogarcia in my opinion users should not be forced into a Beta, psychologically that has bad connotations of degrading a product. If a user wants to opt out of this beta they would have to roll back to an older version and miss out of security updates (given we do not backport them).

Additionally, the Threads MVP as it currently stands will degrade existing experiences such as but not limited to
+ Search results contexts will be missing or shorter than usual because the server is returning events from different timelines which must be filtered out.
+ Notifications are currently incomplete and it is hard to know where to look for unreads for some people, whereas in a reply-chain model (current) that is not an issue as everything is linear.

I don't disagree with default-on, but think users should have the ability to opt out should they want to, I cannot think of any other product which doesn't give you the option to switch from Beta back to Stable.

**Comment by t3chguy** [comment] 2022-03-29 16:20
@novocaine closest that exists is https://github.com/vector-im/element-meta/issues/150 - the search and context APIs are both impacted

**Comment by novocaine** [comment] 2022-03-29 16:36
So I'm leaning towards agreeing that we should allow people to opt-out, mainly as we know our threads experience is a bit imperfect, particularly with regards to notifications. Given the current [limitations](https://docs.google.com/document/d/1V5G1WbvBwvqt3t0XCMfIt39Eu-veoN-4Ca7Z5VGE_A8/edit#), we are going to have some cranky users that don't know where notifications are coming from and find the behaviour unintuitive.

Opted-out users will perceive threads as reply-chains and have a "flattened" experience of them. 

It looks like this is already supported by the beta component that we have, so its just a matter of supporting the button?

**Comment by janogarcia** [comment] 2022-03-29 16:43
Yeah, Michael made a really good point regarding the notifications not being mature enough, and potentially introducing some undesired instability/unreliability to the app. 👍️

I probably focused too much on the _"threads are not completely replacing an existing feature"_ mindset without being really aware of that undesired side effect, which has now become more clear as we discussed our plans on improving notifications.

**Closed** 2022-04-05 16:15 UTC
Labels: T-Enhancement, A-Threads, Z-ThreadsP0, Z-Labs
