### ISSUE TITLE
Implement pin/password lockscreen in the desktop app too.

### ISSUE THREAD

**Issue by Athwale** [vector-im/element-web#17429] opened 2021-05-21 12:36 UTC
I believe people who have the client always on the screen/taskbar might have some private messages in the app and thus might benefit from a similar feature that the android version of element has - the lock that requires a pin/password after a while of inactivity.
Thanks.

**Comment by t3chguy** [comment] 2021-05-21 12:39
Duplicate of https://github.com/vector-im/element-web/issues/3777

**Closed by t3chguy** 2021-05-21 12:39 UTC
Labels: T-Enhancement
