### ISSUE TITLE
Chat line sent ages ago stuck above composer

### ISSUE THREAD

**Issue by gaelledel** [vector-im/element-web#19111] opened 2021-09-21 08:29 UTC
### Steps to reproduce

There aren't really any steps to reproduce this bug, but this isn't the first time I see it.

I sent a message at around 3 pm the day before and it never appeared in the timeline space it should have fitted into. However, the message got stuck above the composer with my Matrix ID (message saying: "Cool, ideally if we could have 2 people per user group/client type that would be great.")

Now every time I send a new message, the message is still displayed above the composer. The other party does not see the stuck message.

<img width="1306" alt="Screenshot 2021-09-21 at 09 07 55" src="https://user-images.githubusercontent.com/76945183/134137432-3087fcb1-2a78-4feb-964b-3de65b6f139c.png">
"

Now, on refresh of the page it keeps displaying the error message saying that the message wasn't sent. Retrying to send does not send anything and every so often a new notification appears to let me know that the message wasn't sent ( no refresh needed) Attempting to resend all messages does not work.
I was only able to solve the problem by clicking on the Delete all button on the error message prompt.

<img width="1304" alt="Screenshot 2021-09-21 at 10 30 44" src="https://user-images.githubusercontent.com/76945183/134147680-b81ef230-520d-4bed-aa7c-beb68b935273.png">
### Operating system

macOS

### Browser information

Chrome Version 93.0.4577.82 (Official Build) (arm64)

### URL for webapp

https://develop.element.io/

### Homeserver

Matrix.org

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment] 2021-09-21 10:08
@gaelledel, could you please try clearing the cache and seeing if the issue still perists?

**Comment by whtshername** [comment] 2021-09-21 13:15
I am currently having a very similar issue, where a message is stuck above the composer and I can't delete it (Linux Desktop Client)
I don't have any error messages.
I Previously had this issue on Android with the :roll_eyes: emoji

**Comment by SimonBrandner** [comment] 2021-09-21 13:16
Perhaps a duplicate of https://github.com/vector-im/element-web/issues/17966

**Comment by robintown** [comment] 2021-09-21 13:34
Yeah, they seem to be the same issue.

Duplicate of https://github.com/vector-im/element-web/issues/17966

**Closed by robintown** 2021-09-21 13:34 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-Timeline, O-Uncommon
