### ISSUE TITLE
reloading riot/web when you have recently received an inbound VoIP call still causes the incoming call dialog to retrigger

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5189] opened 2017-10-09 13:46 UTC
even though the call is long dead. looks like we've lost the check on whether the call is in the live timeline or not

**Comment by SimonBrandner** [comment] 2021-08-30 07:28
Duplicate of https://github.com/vector-im/element-web/issues/4607

**Closed by SimonBrandner** 2021-08-30 07:28 UTC
Labels: T-Defect, P2, S-Major, A-VoIP
