### ISSUE TITLE
Ability to set a custom displayname/avatar for a given group

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5488] opened 2017-11-01 14:58 UTC
### Description

Although not actively supported by Riot, it is possible to have a per-room avatar and display name for yourself. It would be nice if this was also extended to groups. The motivation would be to allow people with alternate identities to maintain those identities in the group's rooms and in the group.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by SimonBrandner** [comment] 2021-06-22 10:06
Duplicate of https://github.com/vector-im/element-web/issues/17177

**Closed by SimonBrandner** 2021-06-22 10:06 UTC
Labels: A-Avatar, A-Spaces, P3, T-Enhancement
