### ISSUE TITLE
Deleted message "reason": requires restart to appear

### ISSUE THREAD

**Issue by LynHyper** [vector-im/element-web#20382] opened 2021-12-31 22:52 UTC
### Steps to reproduce

1. Send a message to someone
2. Delete the message, with a reason
3. View the deleted message's source and see no reason section
4. Fully exit and restart Element Desktop
5. View the deleted message's source again and see the `"reason":` field appear alongside other fields not present before the restart

#### What did you expect?

"View Source" should show the actual source of the deleted message without requiring a restart of Element, or, should at least update by itself if the message's source takes time to finalize.

#### What happened instead?

The source of deleted messages' remain minimal until the user restarts Element, waiting for the message to update doesn't work.

### Operating system

Arch Linux

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

FlatHub

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by kittykat** [comment] 2022-01-01 09:22
I can also confirm that it takes a long time to appear on web as well (on develop).

**Comment by SimonBrandner** [comment] 2022-01-02 09:05
This seems to be present only in encrypted rooms

**Comment by SimonBrandner** [comment] 2022-01-02 10:53
This is caused by `MatrixEvent::makeRedacted()` not settings `MatrixEvent::clearEvent`

**Comment by SimonBrandner** [comment] 2022-01-10 13:18
There is some confusion regarding how should this work, see https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$hZdXXwCdxBrqxS5BTwbhMGSvjz62JA4sIG9f6OUVDtM?via=matrix.org&via=tchncs.de&via=chat.weho.st

**Comment by SimonBrandner** [comment] 2022-01-10 13:23
Closing in favour of https://github.com/vector-im/element-web/issues/new

**Closed by SimonBrandner** 2022-01-10 13:23 UTC
Labels: T-Defect, S-Minor, A-E2EE, A-Timeline, A-Message-Editing, X-Needs-Investigation, O-Frequent
