### ISSUE TITLE
Sometimes I can't dismiss the toast

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#20126] opened 2021-12-09 20:07 UTC
### Steps to reproduce

Sometimes I see a toast in Element interface appeared, but button "Later" becomes unclickable, so I can't disappear it, here is the screenshot of this situation:
![image](https://user-images.githubusercontent.com/336662/145468463-370d7805-0395-40ce-b61c-e27c452b964c.png)

Pressing "Check your devices" shows the Settings dialog, but after closing it - toast is stays visible, so there is no ways to dismiss the toast, only full reload of app helps.

Hope that rageshake will help to debug this problem.

#### What did you expect?
Toast must be closed.

#### What happened instead?
Nothing.

### Operating system

Ubuntu

### Browser information

Chromium 94

### URL for webapp

develop.element.io

### Application version

Element version: 0a5adedbc12f-react-68ac5785770d-js-4e9fe8f53fd2 Olm version: 3.2.3

### Homeserver

ru-matrix.org

### Will you send logs?

Yes

**Comment by kittykat** [comment] 2021-12-09 21:29
Duplicate of #17667

**Closed by kittykat** 2021-12-09 21:29 UTC
Labels: T-Defect
