### ISSUE TITLE
“Something went wrong” page after updating Element develop

### ISSUE THREAD

**Issue by RAOF** [vector-im/element-web#15093] opened 2020-09-04 00:14 UTC
### Description

“Something went wrong” page after hitting the “Update to latest Element” button on nightly.

### Steps to reproduce

- Attempt to access some subset of channels (known bad include #freenode_#ubuntu-devel:matrix.org, working include #freenode_#mir-server:matrix.org) 
- The content of the channel briefly appears, replaced almost immediately by the “Something went wrong” page.

Hitting the “clear cache and reload” button does not fix this.

Log: Will be sent.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox Nightly
- **OS**: Ubuntu
- **URL**: develop.element.io, connected to my homeserver at cooperteam.net running Synapse 1.19.1

**Comment by madduck** [comment] 2020-09-04 00:53
Duplicate of #15092

**Comment by t3chguy** [comment] 2020-09-04 08:21
Duplicate of https://github.com/vector-im/element-web/issues/15091

**Closed by t3chguy** 2020-09-04 08:21 UTC
