### ISSUE TITLE
Sometimes profile pictures aren't shown in places they should be

### ISSUE THREAD

**Issue by Oh-My-Lands** [vector-im/element-web#25879] opened 2023-07-30 23:34 UTC
### Steps to reproduce

1. Open Element
2. Click on a room
![Element PFP Issue](https://github.com/vector-im/element-web/assets/114635931/62aa30a5-f910-4388-84b9-b19e454aafc9)

#### What did you expect?
The profile pictures to be shown
#### What happened instead?
They were not shown

### Operating system

Fedora 38 Workstation

### Browser information

Firefox 115.0.2

### URL for webapp

https://chat.tchncs.de/#/room/!DjyDIsUHDKPqOMGJPg:tchncs.de

### Application version

Element version: 1.11.36 Olm version: 3.2.14

### Homeserver

chat.tchncs.de

### Will you send logs?

Yes

**Comment by germain-gg** [comment] 2023-08-07 07:17
Duplicate of https://github.com/vector-im/element-web/issues/20064

**Closed by germain-gg** 2023-08-07 07:17 UTC
Labels: T-Defect, A-Room-List, O-Occasional
