### ISSUE TITLE
"Unexpected error resolving homeserver configuration" on freshly installed build (including nightly build)

### ISSUE THREAD

**Issue by CrackThrough** [vector-im/element-web#24112] opened 2022-12-25 23:40 UTC
### Steps to reproduce

1. I just finished installing Element, then ran it.
2. Then I see the following:
![image](https://user-images.githubusercontent.com/59867573/209484587-6220e24c-12c4-478b-bc13-95be0ab78c5c.png)
Note that I couldn't locate any logs except for `SquirrelSetup.log`, and there were no helpful contents in the only log I could find.
```
2022-12-26 08:23:35> Program: Starting Squirrel Updater: --checkForUpdate https://packages.element.io/desktop/update/win32/x64/
2022-12-26 08:23:35> Program: Fetching update information, downloading from https://packages.element.io/desktop/update/win32/x64/
2022-12-26 08:23:35> CheckForUpdateImpl: Using existing staging user ID: 9fbb7fad-a0c4-5432-802a-7b2373bd9f6d
2022-12-26 08:23:35> CheckForUpdateImpl: Downloading RELEASES file from https://packages.element.io/desktop/update/win32/x64
2022-12-26 08:23:35> FileDownloader: Downloading url: https://packages.element.io/desktop/update/win32/x64/RELEASES?id=element-desktop&localVersion=1.11.17&arch=amd64
```

#### What did you expect?
Maybe some input fields to log in? To register? Anything that is functional.
#### What happened instead?
I can't access any of the features. I just see this error screen and I cannot do anything.
#### What I tried so far
- Re-installing Element
- Restarting my PC
- Searching for the same issue (I could find none)
- Find any logs and look into other accessible directories under `%APPDATA%\Local\element-desktop\` to find anything useful

### Operating system

Windows 10 (x64)

### Application version

Cannot find version, I have the "app-1.11.17" directory instead.

### How did you install the app?

https://packages.riot.im/desktop/install/win32/x64/Element%20Setup.exe

### Homeserver

None. I couldn't log in.

### Will you send logs?

No

**Comment by andybalaam** [comment] 2023-01-03 09:48
It would help us to debug if you can find some browser console logs - please could you press Ctrl-Shift-i and paste any logs you see into here? Thanks!

**Comment by t3chguy** [comment] 2023-01-03 10:16
This will be a networking problem with the inability to connect to the default configured servers (matrix.org) either due to proxy or firewall or similar. The solution is to specify an alternative server in config.json

**Comment by turt2live** [comment] 2023-01-10 00:54
Considering a duplicate of https://github.com/vector-im/element-web/issues/11154

**Closed by turt2live** 2023-01-10 00:54 UTC
Labels: T-Defect, X-Needs-Info, S-Critical, A-Electron, O-Uncommon
