### ISSUE TITLE
Jitsi still in background - pwa

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16617] opened 2021-03-06 12:21 UTC
### Description

Jitsi still going on even though ended the conference :
closed the conference on web
![image](https://user-images.githubusercontent.com/31655082/110206521-7cd14280-7e7e-11eb-9037-a79918078d31.png)
this is how it looks like on Android 
![image](https://user-images.githubusercontent.com/31655082/110206538-983c4d80-7e7e-11eb-9823-a01cafbdcdc8.png)

### Steps to reproduce

not sure

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome
- **OS**: Windows
- **URL**:  app.element.io

**Comment by jryans** [comment] 2021-04-20 10:18
I assume this is a duplicate of https://github.com/vector-im/element-web/issues/16725 or other related issues.

**Closed by jryans** 2021-04-20 10:18 UTC
Labels: A-Jitsi, T-Defect
