### ISSUE TITLE
the two different search bars can be confusing

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#15138] opened 2020-09-10 11:22 UTC
Element has two different search bars, which reduces usability and creates confusion:
 
1. Search bar for rooms:
![image](https://user-images.githubusercontent.com/19155609/92722858-1e5c5900-f360-11ea-8807-fc8fa026d976.png)

 
It is not readily clear that this search bar can only be used to search for rooms and people, therefore the placeholder text maybe could be updated from just "Search" to "Search for rooms and people", or something to that effect.
 
2. Search bar for content within rooms
![image1](https://user-images.githubusercontent.com/19155609/92722873-22887680-f360-11ea-99c9-f1dab138ed84.png)

Since the search icon is contained within a specific room top navigation menu, it is not intuitive enough that one could use it also to search for content in all rooms, unless someone clicks on it.
Also in this case the placeholder text should clarify what can be searched.
 
3. Ideally, there should be only one search tool within the app, with specific filters to search for content, rooms or both, etc. It may be harder to design, but it may also reduce confusion and improve usability, if done well.

**Comment by t3chguy** [comment] 2020-09-10 11:26
Duplicate of https://github.com/vector-im/element-web/issues/14785

**Closed by t3chguy** 2020-09-10 11:26 UTC
Labels: suggestion
