### ISSUE TITLE
Quotes are missing their distinctive left-side line to make them a quote

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25795] opened 2023-07-13 15:33 UTC
### Steps to reproduce

1. Quote some text

#### What did you expect?

A line on the left side of the quote, as is present in every other app which supports quotes.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/61f7c657-59f8-4387-b4bd-714a87cf0cd4)

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023071301 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-07-13 15:39
Duplicate of https://github.com/vector-im/element-web/issues/25782

**Closed by t3chguy** 2023-07-13 15:39 UTC
Labels: T-Defect
