### ISSUE TITLE
/invite slash command doesn't seem to keyshare

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20778] opened 2022-01-27 11:08 UTC
### Steps to reproduce

 * I invited Amandine to a room with shared history viz via `/invite @Amandine:matrix.org`
 * She got no shared history

#### What did you expect?

We should keyshare for the missing history.

#### What happened instead?

No keys were shared, seemingly.

### Operating system

macOS 12.1 on M1

### Application version

Nightly

### Will you send logs?

No

**Comment by robintown** [comment] 2022-01-27 14:42
Duplicate of https://github.com/vector-im/element-web/issues/16982

**Closed by robintown** 2022-01-27 14:42 UTC
Labels: T-Defect
