### ISSUE TITLE
Start Element Minimised to system tray

### ISSUE THREAD

**Issue by Lamdarer** [vector-im/element-web#19278] opened 2021-10-04 18:41 UTC
#### What would you like to do?
Add an option to start Element Minimized to system tray.
#### Why would you like to do it?
For the same reason there is an option to minimize Element on close to system tray.
It is good to have element running in the background if it isn't frequently enough used.
Also convenience, currently I run a script on startup to minimize element.

#### How would you like to achieve it?
By setting an option in the preferences tab of the Desktop client and maybe by adding a `--background` as a starting parameter on Linux

### Have you considered any alternatives?

Option to start Element-Desktop Minimized but not to system tray

### Additional context

This is related to the [desktop client](https://github.com/vector-im/element-desktop) which does not have an option for issues.

**Comment by aaronraimist** [comment] 2021-10-05 05:50
I think this is a duplicate of https://github.com/vector-im/element-web/issues/19092

**Closed by aaronraimist** 2021-10-05 05:50 UTC
Labels: T-Enhancement
