### ISSUE TITLE
element-desktop crashes when downloading large encrypted file

### ISSUE THREAD

**Issue by ldot72** [vector-im/element-web#21094] opened 2022-02-16 01:35 UTC
### Steps to reproduce

1. Start element desktop app. Open an encrypted room that has a large file uploaded to it. I tested with a 1.95GB .tar.
2. Click on download. Wait.

#### What did you expect?
The file downloads and decrypts normally.

#### What happened instead?
The element desktop app crashes after downloading for some time. White window, RAM usage of the process drops to below 100MB and stays there. Closing and reopening the app needed to restore functionality.

### Operating system

Windows 10

### Application version

1.10.3

### How did you install the app?

https://element.io/get-started#download Windows 64-bit

### Homeserver

Synapse 1.52.0

### Will you send logs?

No

**Comment by dbkr** [comment] 2022-02-16 11:51
I'm assuming this is also specific to encrypted rooms?

**Comment by turt2live** [comment] 2022-06-14 04:34
Duplicate of https://github.com/vector-im/element-web/issues/4264

**Closed by turt2live** 2022-06-14 04:34 UTC
Labels: T-Defect, X-Needs-Info, S-Minor, A-File-Download, O-Uncommon
