### ISSUE TITLE
Screensharing not possible in a room

### ISSUE THREAD

**Issue by FelixFurtmayr** [vector-im/element-web#23370] opened 2022-09-28 16:43 UTC
### Steps to reproduce

1. Using the desktop client you create a meeting in a room
2. There are several participants
3. You click on share screen
4. The screen share dialog appears, but there is nothing in it - no preview pic of your screen

It works in the web client and it also works when you connect directly with another person.

#### What did you expect?
Screensharing works 

#### What happened instead?
Not able to select the screen to share

I would be very happy if this can be fiixed as it goes on my nerves in our daily meeting.

### Operating system

Ubuntu

### Application version

 1.10.11

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-09-28 16:46
Duplicate of #4880

**Closed by t3chguy** 2022-09-28 16:46 UTC
Labels: T-Defect

**Comment by FelixFurtmayr** [comment] 2022-09-28 16:51
@t3chguy thanks for mentioning, that there is already an issue. I'll close this one.
