### ISSUE TITLE
Constant 50% CPU usage recalculating style when not being used  

### ISSUE THREAD

**Issue by jrmuizel** [vector-im/element-web#21889] opened 2022-04-22 18:19 UTC
### Steps to reproduce

1. Load Element on macOS and wait for a minute or two

### Outcome

2. Activity monitor shows Element (Renderer) at around 50% CPU
3. Profiling with the dev tools shows recalculating style at 60fps

I don't see the problem when running directly in Firefox. (I did not try running directly in Chrome)

Here's a profile from dev tools
[profile.zip](https://github.com/vector-im/element-web/files/8543144/profile.zip)
And the same profile loaded into profiler.mozilla.org: https://share.firefox.dev/36DygxF

### Operating system

macOS

### Application version

Version 1.10.10 (1.10.10)

### Homeserver

mozilla.modular.im

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-22 18:22
Duplicate of https://github.com/vector-im/element-web/issues/21793

This will be fixed in the upcoming release, but in the meantime, the workaround is to enable the threads beta at least once.

**Closed by robintown** 2022-04-22 18:22 UTC
Labels: T-Defect
