### ISSUE TITLE
after xsigning, settings don't auto update

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20232] opened 2021-12-16 19:49 UTC
### Steps to reproduce

0. device isn't xsigned yet, but my other devices are xsigned
1. go to settings -> privacy
2. on this device, verify
3. go through verificaton process
4. list isn't update to show that this device is now xsigned

### Outcome

see above

### Operating system

arch

### Application version

Element Nightly version: 2021121401 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by kittykat** [comment] 2021-12-16 22:51
Duplicate of #20203

**Closed by kittykat** 2021-12-16 22:51 UTC
Labels: T-Defect
