### ISSUE TITLE
Allow changing the red color of the text of messages which are answers or pings 

### ISSUE THREAD

**Issue by raphj** [vector-im/element-web#26286] opened 2023-10-03 12:43 UTC
### Your use case

When someone answers or mentions you, the message is rendered in red.

The red color is useful to spot this answer... However, especially when I'm a bit down, I feel like being yelled at by people answering/mentioning me because of this red color.

#### What would you like to do?

- Get rid of this red color.
- Still have some kind of obvious emphasis because that's very useful

#### Why would you like to do it?

- To stop feeling being yelled at or that people are angry at me, while still keeping the convenience of spotting answers / mentions concerning me.

#### How would you like to achieve it?

- if the color mechanism is kept as is:
  - a color picker to change it would be great. I guess I would pick some kind of purple, blue, or dark green (and possibly change when I get tired of this color)
  - I believe red not a great default, so changing the default would be a big plus (though I know changing something existing can upset users, so I don't know). Saying this because while the color picker would 100% fix it for me, I discovered recently that the feeling of being yelled at by the red color is well known to affect some people, and red text is avoided in some public messages IRL for this reason or because red culturally conveys danger or interdiction in many places.
- another indicator that does not involve the red color at all, or at least red text could be a great option (in a second time), since [only conveying something by color is not very accessible](https://github.com/vector-im/element-web/issues/24931). 

### Additional context

I was looking at how Signal does it, but it actually does not seem to provide the feature, so not sure what could be a good way to do it differently.

**Comment by t3chguy** [comment] 2023-10-03 12:55
Duplicate of https://github.com/vector-im/element-web/issues/18802

**Closed by t3chguy** 2023-10-03 12:55 UTC
Labels: T-Enhancement

**Comment by t3chguy** [comment] 2023-10-03 13:03
https://github.com/vector-im/element-web/issues/6520 was closed in favour of #18802 indeed.
