### ISSUE TITLE
Replies in an open chat in Riot-Web create push notifications @mobile

### ISSUE THREAD

**Issue by jacotec** [vector-im/element-web#9561] opened 2019-04-25 11:01 UTC
Platform: Riot-Web 1.08 self hosted from repo (Ubuntu 16.04)

When I'm in a chat with a guy on Riot-IOS on my iPad, I'm not getting any push notifications on my iPhone (repective my Apple Watch) when the chat partner did send a reply. This is the behavior as it should be - I don't need ongoing notifications from a chat where I'm currently active.

Having the same chat open in Riot-Web every response from the other party in the open chat window creates a push notification to my mobiles which is very annoying.

Somehow my Matrix-Synapse "knows" when the chat is open on another Riot-IOS device and suppresses the push notifications for this chat. Using Riot-Web this knowledge seems to be lost.

I'm pretty sure it was working the proper way before, but I can't really tell at which point this got broken. Or is there something which could be wrong on "my side"?

**Comment by t3chguy** [comment] 2019-04-25 11:13
> Somehow my Matrix-Synapse "knows" when the chat is open on another Riot-IOS device and suppresses the push notifications for this chat. Using Riot-Web this knowledge seems to be lost.

I do not believe this to be true, to my knowledge, this is APNS being smart about which device handles your push notification

**Comment by t3chguy** [comment] 2022-05-25 21:10
Duplicate of https://github.com/vector-im/element-web/issues/469

**Closed by t3chguy** 2022-05-25 21:10 UTC
Labels: T-Defect, S-Minor, A-Notifications, X-Needs-Investigation, O-Occasional
