### ISSUE TITLE
Scroll jumps then empty timeline

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#20585] opened 2022-01-17 09:38 UTC
### Steps to reproduce

1. Receive a notification somewhere deep in scrollback
2. Go to the room
3. Click the green "jump to last unread message" circle arrow in the top right corner
4. Briefly see your notification
5. Scroll jumps ahoy, up and down
6. Eventually settle on an completely white rectangle of timeline

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2022011601 Olm version: 3.2.8

### How did you install the app?

Web link

### Homeserver

lant.uk

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-01-17 09:41
@lampholder are you using Message Bubbles?

**Comment by t3chguy** [comment] 2022-01-17 09:42
`"layout":"bubble"` - yes you are

Duplicate of https://github.com/vector-im/element-web/issues/20302

**Closed by t3chguy** 2022-01-17 09:42 UTC
Labels: T-Defect
