### ISSUE TITLE
[Design Suggestion] Spaces drag-n-drop pop-ups (with IA)

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19884] opened 2021-11-24 16:00 UTC
### Your use case

If I understand correctly, together with [IA](https://github.com/vector-im/element-meta/issues/56), subspaces will be revamped to become a header in the room panel, while viewing a space.

If this is the case, and inspired from this, I’d like to suggest the following design;

Dragging and dropping subspaces “into” other spaces, and with this a two-variant confirmation popup:

- If the user doesn’t have permission to remove subspaces, a popup explaining that the user can still “copy” the subspace to the destination space should appear.
  -  This popup should have a filled “green” button (saying “copy”), and an optional checkmark saying “don’t notify me for copying spaces anymore”
- if the user does have permission to remove subspaces, a popup should always appear;
  - two buttons, one with only red borders (and no fill) saying “move”, and a filled green one saying “copy”
  - No checkmark option, as move-or-copy actions should always explicitly be confirmed

---
 Here I’m using the terminology “copy”, while this is technically not correct, as the space is only newly referenced in another space, and the entire structure isn’t copied with it.

I chose this word because I thought that move/copy mechanisms would be more familiar with users, coming from file systems.

**Comment by SimonBrandner** [comment] 2021-11-24 16:02
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/16992

**Comment by t3chguy** [comment] 2021-11-24 16:03
> subspaces will be revamped to become a header in the room panel, while viewing a space.

This is still up in the air, closer to not than to

**Closed by SimonBrandner** 2021-11-24 16:02 UTC
Labels: T-Enhancement

**Comment by ShadowJonathan** [comment] 2021-11-25 00:16
@SimonBrandner this is actually more an addition to that issue than a duplicate, I’m trying to build on top of it as a separate design decision to the design team, I think it should be re-opened as such.

**Comment by t3chguy** [comment] 2021-11-25 08:51
@ShadowJonathan its based on a Figma comp which is likely not going to see the light of day though, better first await design picking the path to go for that bit of the app before layering things atop it and creating defacto decisions
