### ISSUE TITLE
Element locks up after login long enough to show browser unresponsive banner

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#23313] opened 2022-09-20 08:24 UTC
After logging in on element web with my medium sized account (~300 rooms), element locks up on both chrome and firefox, long enough that both of those browsers bring up the the page has become unresponsive, wait or force stop? banner. This is after navigating to the main screen and before verifying the device, so before having access to key backup to start decrypting previous message.

**Comment by bwindels** [comment] 2022-09-20 08:26
```
Element version: fed77108e6ca-react-0cc4f4e1bc4d-js-9ff11d1f325f
Olm version: 3.2.12
Chromium: Version 103.0.5060.114 (Official Build) Fedora Project (64-bit)

**Comment by turt2live** [comment] 2022-09-21 20:49
Without a performance profile this is difficult to diagnose - it could be Element trying to send a billion keyshare requests or something.

**Comment by florianduros** [comment] 2022-10-19 15:09
@bwindels Hi, do you still reproduce this issue ? If yes, can you provide a performance profile ? Thank you

**Comment by turt2live** [comment] 2023-01-10 00:23
Closing due to lack of information. If this is still happening, please open a new issue with fresh reproduction steps for the QA team to review.

**Closed by turt2live** 2023-01-10 00:23 UTC
Labels: T-Defect, X-Needs-Info, A-Performance, S-Major, A-E2EE, O-Uncommon
