### ISSUE TITLE
Make Remove Recent Messages dialogue more clear

### ISSUE THREAD

**Issue by catscratchedme** [vector-im/element-web#16064] opened 2021-01-03 22:38 UTC
### Description

Using the Remove recent messages feature does not always remove messages that are visible on the screen.

### Steps to reproduce

- Go to room with many messages
- Scroll up multiple pages, and use "Remove recent messages" on a user
- Observe the # of messages it tells you will be removed. It's not clear to the user where this number comes from (where does it look for the first and last messages that are eligible to be removed?)
- Copy the permalink of the oldest removed message (further up on the timeline). Let's say you become busy with something else, and can't finish redacting all the messages right now.
- Clear cache
- Use /goto to jump to the permalink that you copied earlier
- Scroll up a bit to load messages for the targeted user
- If you are too far away from the oldest message you've already redacted, the remove recent messages dialogue will tell you "No recent messages by [user] found. Try scrolling up in the timeline to see if there are any earlier ones."
- It's not clear to me why no recent messages are found, when you can see messages by the targeted user on the screen. If you scroll up on the timeline, you will get the same dialogue, and will not be able to redact any messages

**Describe how what happens differs from what you expected.**

I would expect that Remove recent messages would work from newest to oldest messages. If the user's 100 most recent messages has been redacted, I would expect that it would start redacting from the 101th most recent message, even if you had the 500th most recent message on your screen.

I would expect that it would at least remove at least as many messages as are on the screen from the targeted user. 

If the dialogue tells me: "Try scrolling up in the timeline to see if there are any earlier ones," I would expect that scrolling up would let the client find messages that I can redact, but in reality scrolling up doesn't achieve that. 

### Version information

- **Platform**: desktop?
- Version: 1.7.16

For the desktop app:

- **OS**:  Linux Mint
- **Version**: 20

**Comment by t3chguy** [comment] 2023-07-13 11:53
Duplicate of https://github.com/vector-im/element-web/issues/10819

**Closed by t3chguy** 2023-07-13 11:53 UTC
Labels: T-Defect, P2, S-Minor, A-Moderation
