### ISSUE TITLE
Email confirmation phase of registration doesn't wrap properly

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#15946] opened 2020-12-10 14:56 UTC
![image](https://user-images.githubusercontent.com/279572/101788231-c61c2b00-3af7-11eb-98b9-a84244c7fc5b.png)

**Comment by t3chguy** [comment] 2020-12-10 15:02
Duplicate of https://github.com/vector-im/element-web/issues/15936

**Closed by t3chguy** 2020-12-10 15:02 UTC
Labels: bug, defect, delight, p1, severity:cosmetic
