### ISSUE TITLE
"Unable to decrypt: The sender's device has not sent us the keys for this message." when switching from Fractal to app.element.io

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#15680] opened 2020-11-09 10:28 UTC
### Description

1. Logged to matrix.org using the Fractal client (which does not handle E2EE as of yet).
2. Fractal client didn't show any message (although it did show a message count), so logged out.
3. Logged back using app.element.io on Gnome Web Browser (WebKitGTK  2.28.4)
4. All the messages in history show up as

```
** Unable to decrypt: The sender's device has not sent us the keys for this message. **
Re-request encryption keys from your other sessions.?
```

Clicking on the link doesn't do anything.

5. New messages show up correctly.

**Comment by t3chguy** [comment] 2020-11-09 10:34
Matrix encryption features Perfect Forward Secrecy https://en.wikipedia.org/wiki/Forward_secrecy so messages from sessions before the existence of your current one will be unreadable. If you didn't make use of Key Backup then you will not be able to read them.

**Comment by Yoric** [comment] 2020-11-09 10:49
I should have mentioned that I was not prompted for my key backup on either application.

**Comment by t3chguy** [comment] 2020-11-09 10:50
Given that Fractal doesn't support E2EE it won't support Key Backup either.

**Comment by Yoric** [comment] 2020-11-09 10:51
Shouldn't the web client have asked me for my Key Backup?

**Comment by t3chguy** [comment] 2020-11-09 10:55
It should ask you to create one, but that won't help you read existing history unless you already had a key backup which had the keys to decrypt those. You should have seen a "Set up Secure Backup" toast at some point.

**Comment by Yoric** [comment] 2020-11-09 10:58
I got one when I created my id with the web client. I have a Key Backup.

**Comment by t3chguy** [comment] 2020-11-09 10:59
So when you logged back into the web client were you not prompted to `Verify this session`?

**Comment by Yoric** [comment] 2020-11-09 11:00
Indeed.

**Comment by t3chguy** [comment] 2020-11-09 11:02
So the issue is Fractal being not E2EE capable it was not adding the new encrypted sessions to your Key Backup.
Due to PFS you must always have an encryption-capable session not logged out (offline for whatever period of time is fine)

**Comment by Yoric** [comment] 2020-11-09 11:05
Also, I tried to manually `Restore from Backup`, to no avail.

**Comment by Yoric** [comment] 2020-11-09 11:09
> So the issue is Fractal being not E2EE capable it was not adding the new encrypted sessions to your Key Backup.
> Due to PFS you must always have an encryption-capable session not logged out (offline for whatever period of time is fine)

Fair enough. In this case, the error message should probably be improved.

**Comment by t3chguy** [comment] 2020-11-09 11:14
Closing in favour of other issues which cover this;
https://github.com/vector-im/element-web/issues/2286
https://github.com/vector-im/element-web/issues/2996

**Closed by t3chguy** 2020-11-09 11:14 UTC
