### ISSUE TITLE
provide a way to select multiple messages

### ISSUE THREAD

**Issue by damnms** [vector-im/element-web#16218] opened 2021-01-20 08:52 UTC
**Is your suggestion related to a problem? Please describe.**
i often have to delete or forward multiple messages. its very cumbersome to delete/foward one and then go over to the next one.

**Describe the solution you'd like**
i would love to somehow select multiple (like 20+) messages and then execute one action like "delete" to all of those

**Describe alternatives you've considered**
none

**Additional context**
whatsapp provides such a functionality. selecting multiple messages and then forward/delete them

**Comment by t3chguy** [comment] 2021-01-20 10:00
Duplicate of https://github.com/vector-im/element-web/issues/3689 + https://github.com/vector-im/element-web/issues/5536

**Closed by t3chguy** 2021-01-20 10:00 UTC
Labels: suggestion
