### ISSUE TITLE
Don't block the UI when leaving rooms as part of leaving a space

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#22987] opened 2022-08-04 09:48 UTC
#### What would you like to do?

When I leave the space and leave all or some rooms under this space, the UI currently greys out and shows a spinner in the middle (implicitly blocking any further operation) until all rooms are left. On a homeserver with realistic rate limiting and with a space that's got a decent amount of rooms (the one I'm currently leaving has 20-30 rooms I'd say) this means the UI is blocked for ages. On top of it, it also just shows a spinner with no indication of what the app is currently doing.

![image](https://user-images.githubusercontent.com/5547783/182817638-8fc5991d-e5bf-4350-89d2-0e765166a899.png)

I feel like Element shouldn't block the UI in this way in this case, because it means as a user I feel like I just can't use the app while it does that and it makes using spaces frustrating.

#### Why would you like to do it?

See above.

#### How would you like to achieve it?

It could either be done in the background without telling the user, or with a small toast in eg the bottom left corner that's either spinning until the rooms are all left or shows a progress bar indicating how many rooms remain to be left.

**Comment by t3chguy** [comment] 2022-08-04 09:57
Duplicate of https://github.com/vector-im/element-web/issues/13911

**Closed by t3chguy** 2022-08-04 09:57 UTC
Labels: T-Enhancement
