### ISSUE TITLE
All old messages are "Encrypted by a deleted session"

### ISSUE THREAD

**Issue by mrjohnson22** [vector-im/element-web#13531] opened 2020-05-06 06:29 UTC
### Description

When logging in to an existing account that has been validated via cross-signing, all existing messages in encrypted chats have a status of "Encrypted by a deleted session", even if the session used to send those messages is still active.

### Steps to reproduce

- With any client & account, send some messages in an encrypted room
- Use a new web browser session to log in to that same account, and verify it with cross-signing
- Wait for encrypted message keys to be shared

Encrypted messages will be readable in the new account, but they will appear with a red shield & status of "Encrypted by a deleted session". This includes messages sent by your account from other clients, and messages received from other users that have been verified via cross-signing. Messages sent by accounts that haven't set up cross-signing don't have this status, though.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome, Firefox (latest versions)
- **OS**: Windows 10, Fedora 32
- **URL**: any URL using riot-web-1.6.0-rc6 or newer (riot.im/develop / riot.im/app / riot.im/staging / self-hosted Riot Web)

**Comment by Morishiri** [comment] 2020-05-06 13:26
I'm experiencing the same things. Additionally this messages are shown as "Encrypted by a deleted session" on my PC and are displayed with green lock in Mobile App. This is strange.

**Comment by mrjohnson22** [comment] 2020-05-06 15:30
Note that this does not happen when upgrading a previously logged-in Riot Web to 1.6.0 (the RCs I tested were 3 (I think) and 6) and validating it with another session.

A similar issue happened before cross-signing, so maybe this is the same issue but just with a slightly different UI outcome.

**Comment by mrjohnson22** [comment] 2020-05-07 00:02
Building on @Morishiri's comment, this isn't a problem in RiotX. I just logged into my account from RiotX on a fresh Android emulator and cross-verified it with a Riot Web session; once encrypted messages became readable, they appeared without any warnings.

**Comment by mrjohnson22** [comment] 2020-05-07 06:24
Riot Web has the same problem when viewing messages sent from RiotX. I tested sending some messages from a verified RiotX session, then logging into a new Riot Web session, where the RiotX messages appear as "Encrypted by a deleted session".

This rules out the problem only affecting messages sent from Riot Web.

**Comment by mrjohnson22** [comment] 2020-05-07 16:56
It's also worth mentioning that if you really do delete a session, their messages correctly appear with the shield & warning.

**Comment by T-bond** [comment] 2020-10-26 14:53
Tested on a [Nextcloud hosted Element app](https://github.com/gary-kim/riotchat/tree/v0.6.13) and still happens.
Element version: Element Web v1.7.10
I was logged in on my phone with Element Android (1.0.9 F-Droid version), and on app.element.io (Element version: 1.7.10). Cross singing and key backup are turned on and working.

The newly logged in client (Nextcloud Element) synced the keys, after verification with app.element.io, all messages says: "The authenticity of this encrypted message can't be guaranteed on this device."
Except redacted messages. All the redacted messages in the history says: "Encrypted by a deleted session"

Me and the recipient are using self hosted homeservers (it it helps anything at all).

**Comment by kittykat** [comment] 2021-12-09 18:20
From the testing session:
> "No red shield any more. It'a grey one and the info „encrypted by a deleted session“.

I'm going to close this issue for now as the design has changed since it's been filed and we cannot reproduce it. Please open a new issue if you feel that there are improvements to be made.

**Closed by kittykat** 2021-12-09 18:20 UTC
Labels: T-Defect, A-E2EE-Cross-Signing, X-Needs-Investigation, X-Needs-Community-Testing
