### ISSUE TITLE
Add messages to favorites

### ISSUE THREAD

**Issue by lukaszpolowczyk** [vector-im/element-web#16331] opened 2021-01-31 17:18 UTC
I need a feature:
Add the selected message to "Favorites".
Later I want to view my "favorite" messages in one place.

These are the things I want to refer to later or I need something else.

Currently, I can only add a link to the message to the bookmark in the web browser.
I can't do this in the app.

This feature exists at slack.com.

**Comment by t3chguy** [comment] 2021-01-31 17:19
Duplicate of https://github.com/vector-im/element-web/issues/2938

**Closed by t3chguy** 2021-01-31 17:19 UTC
Labels: suggestion
