### ISSUE TITLE
Messages composed entirely of whitespace should disable send

### ISSUE THREAD

**Issue by JorikSchellekens** [vector-im/element-web#15556] opened 2020-10-26 12:25 UTC
![image](https://user-images.githubusercontent.com/23084468/97171774-e4b3a600-1785-11eb-8b8f-9bf0c2abbe96.png)

The input box should probably prevent the sending of entirely whitespace messages since they look like the contents failed to load

**Comment by t3chguy** [comment] 2020-10-26 12:26
Duplicate of https://github.com/vector-im/element-web/issues/15524

**Closed by t3chguy** 2020-10-26 12:26 UTC
Labels: bug, ui/ux
