### ISSUE TITLE
Client locks up calculating blurhash

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17945] opened 2021-07-11 08:49 UTC
Makes it really hard to type a caption while the blurhash is being calculated

**Comment by gsouquet** [comment] 2021-07-12 08:18
This appears to be a duplicate of vector-im/element-web#17890 and has potentially been fixed by matrix-org/matrix-react-sdk#6329

Let me know whether this has fixed the problem you're facing

**Comment by t3chguy** [comment] 2021-07-12 08:20
that PR only fixed *rendering* performance, not the performance issue when calculating the blurhash during sending in the first place

**Closed** 2021-07-14 19:14 UTC
Labels: A-Media, T-Defect, X-Regression
