### ISSUE TITLE
Central settings panel to manage avatar/nick overrides

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#17755] opened 2021-06-24 13:27 UTC
#### Is your suggestion related to a problem? Please describe.
Currently when I want to manage my nickname and avatar per room, i'll have to go to that specific room to observe and possibly make changes there via a command.

#### Describe the solution you'd like.
I'd like there to be a single panel where I can observe all avatar/nick "overrides", and also change per room, or a selection of rooms (possibly also per space).

#### Additional context
Some inspiration;

(Discord, Notification settings per server)

![image](https://user-images.githubusercontent.com/22740616/123270540-489e9200-d500-11eb-8d50-abc0d4f51559.png)

**Comment by t3chguy** [comment] 2021-06-24 13:29
Duplicate of https://github.com/vector-im/element-web/issues/2458

The current implementation doesn't cut the mustard hence that issue remains open.

**Closed by t3chguy** 2021-06-24 13:29 UTC
Labels: T-Enhancement
