### ISSUE TITLE
Confusing error when trying to join via an invite link

### ISSUE THREAD

**Issue by Demi-Marie** [vector-im/element-web#13247] opened 2020-04-17 20:09 UTC
### Description

https://riot.im/app/#/room/!RPcrrAZGkFhSYabkrM:matrix.org gives a rather confusing error.

### Steps to reproduce

- Try to join the room given by this link: https://riot.im/app/#/room/!RPcrrAZGkFhSYabkrM:matrix.org
- Expected behavior: success, or a useful error message.
- Actual behavior: confusing error.

### Version information

- **Platform**: desktop

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Debian Linux
- **Version**: 1.5.15

**Comment by MichaelKohler** [comment] 2020-04-17 20:30
This is the error I'm getting:

![error](https://user-images.githubusercontent.com/330324/79611464-377f1780-80ea-11ea-8a69-d14d4a7a77f8.png)

**Comment by DemiMarie-parity** [comment] 2020-04-17 21:43
@MichaelKohler I get the same error message.

**Comment by aaronraimist** [comment] 2020-04-18 00:48
This issue is essentially a duplicate of https://github.com/vector-im/riot-web/issues/2925

In general you should not use room ID's to join rooms. Room IDs aren't meant for humans. They cannot be used to join rooms without extra information. Now the link that is in the README on https://github.com/iqlusioninc/armistice#contributing, which is I assume where you got that link, does have this extra info (the ?via= bit at the end). So the link in the README should work although usually you should join rooms using aliases not room IDs. Did you get the link from another location or has the ?via= bit of the URL been stripped off somewhere?

**Comment by DemiMarie-parity** [comment] 2020-04-18 00:52
The link in the README does not work either.  It should be noted that my homeserver is `matrix.parity.io`, *not* `matrix.org`, and that I have firewall rules blocking access to other homeservers.

**Comment by aaronraimist** [comment] 2020-04-18 00:53
... well how do you expect it to work then? Matrix is all about federation. If you refuse to federate then you can't participate in rooms on other servers.

**Comment by DemiMarie-parity** [comment] 2020-04-18 00:56
> ... well how do you expect it to work then? Matrix is all about federation. If you refuse to federate then you can't participate in rooms on other servers.

The firewall rules are on the client, not the server.  The client’s network logs show no indication of attempts to connect to other servers.

**Comment by aaronraimist** [comment] 2020-04-18 00:59
Oh. That's fine. Your client only communicates with your server.

**Comment by aaronraimist** [comment] 2020-04-18 01:12
Which error are you seeing? I get an error "You are not invited to this room" which seems pretty clear. They seem to have the room set to invite only. Are you seeing this error or the "No know servers" error from above?

**Comment by DemiMarie-parity** [comment] 2020-04-18 16:44
I got the “No known servers” error last I checked.  Searching for the room manually works.

**Comment by turt2live** [comment] 2022-05-07 01:27
Duplicate of https://github.com/vector-im/element-web/issues/11756

**Comment by aaronraimist** [comment] 2022-07-03 00:44
I don't think this is a duplicate @turt2live. In https://github.com/vector-im/element-web/issues/11756, they used a link that had via servers.

**Comment by JeanPaulLucien** [comment] 2023-02-11 08:38
It's 0 users room.

**Closed** 2023-02-24 15:59 UTC
Labels: A-Error-Message
