### ISSUE TITLE
minimize/open on click at tasktray icon

### ISSUE THREAD

**Issue by damnms** [vector-im/element-web#16111] opened 2021-01-10 14:00 UTC
**Is your suggestion related to a problem? Please describe.**
its very annoying to always right-click at the icon in the tasktray - select open to have the client open. it happened so many times that i accidentally closed element. for disabled people thats even worse.

**Describe the solution you'd like**
element should behave like any other desktop app with a tray icon i know (e.g. thunderbird). when i click on the icon at the tray, open the application. i dont want to click 3 times to have it open.

**Describe alternatives you've considered**
i see no alternative

**Additional context**
none

**Comment by t3chguy** [comment] 2021-01-10 14:15
Left clicking does toggle visibility. Please fill the issue template to share version and environment details.

**Comment by SimonBrandner** [comment] 2021-01-10 15:10
@t3chguy I think there's a bug on Linux. It at least doesn't work for me. I think there was an issue but I couldn't find it.

**Comment by t3chguy** [comment] 2021-01-10 15:13
On Linux it depends on what tray icon support your desktop environment has. Typically libappindicator works as expected. This is just common behaviour of electron.

**Comment by t3chguy** [comment] 2021-01-10 15:30
Duplicate of https://github.com/vector-im/element-web/issues/11772

**Closed by t3chguy** 2021-01-10 15:30 UTC
Labels: suggestion
