### ISSUE TITLE
Pressing enter after a URL

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#17301] opened 2021-05-14 14:10 UTC
### Description

Pressing enter (might be shift+enter) after a URL duplicates the last character of the URL onto the next line.

### Steps to reproduce

- In a conversation in the message box underneath, paste a URL. Any URL will do, as far as I can tell.
- Press Shift+Enter to make a newline, rather than send the message. If you've set Ctrl+Enter to send, regular Enter will do as well, although I'm not 100% certain.
- Observe the last character of the pasted url being copied and carried over the the next line.

This doesn't happen always. So please try a few times before saying "cannot reproduce" and calling it a day 🙏

Logs being sent: no (I don't really think this is the type of bug that requires them, but lemme know if you need them).

### Version information

- **Platform**: desktop
- **OS**: Windows 10 20H2
- **Version**: 1.7.27

**Comment by t3chguy** [comment] 2021-05-14 14:11
This looks like https://github.com/vector-im/element-web/issues/17215 ?

**Comment by thany** [comment] 2021-05-14 14:12
Possibly, but I've only ever had this problem with pasted urls...

**Comment by yannicka** [comment] 2021-05-31 21:07
For me it's the same problem as #17215 (only with the "Use Ctrl + Enter to send a message" parameter enabled).

Whether I am typing a URL or text, when I press Shift+Enter, it duplicates the last letter of the previous line:

https://user-images.githubusercontent.com/22885898/120241957-1c2a8980-c264-11eb-932b-3a1ab2fdb61d.mp4

If I press Enter only, I don't have this problem (the line feed is done as expected).

- Element Desktop 1.7.29.

**Comment by SimonBrandner** [comment] 2021-06-01 05:21
@thany, could you please confirm this is a dupe of [#17215](https://github.com/vector-im/element-web/issues/17215)

**Comment by thany** [comment] 2021-06-04 09:07
Yes, I checked, it's a dupe.

Well, I guess that confirms some extra priority if two issues exist for the same bug 😘

**Comment by SimonBrandner** [comment] 2021-06-04 09:08
Closing then, there is already a PR to fix this, btw

**Closed by SimonBrandner** 2021-06-04 09:08 UTC
Labels: A-Composer, T-Defect, X-Needs-Info
