### ISSUE TITLE
Browse through pictures in a room with arrow keys when viewing enlarged version

### ISSUE THREAD

**Issue by Snamhdaen** [vector-im/element-web#21348] opened 2022-03-07 22:57 UTC
#### What would you like to do?

I would like to browse through pictures in a room by tapping the arrow keys/clicking on an arrow symbol when I view them in enlarged form. Currently, I have to close the enlarged view, scroll up/down to the next picture and click on it. This is cumbersome when examining/comparing related pictures.

#### How would you like to achieve it?

I think the ability to skip through the pictures uploaded to a room should be added via both keyboard and mouse input.

### Additional context

The feature I have in mind is nicely implemented in the android app. I'd like something similar for the web/desktop version. I was unable to find issues discussing this on github but please feel free to correct me.

**Comment by aaronraimist** [comment] 2022-03-08 00:54
Duplicate of https://github.com/vector-im/element-web/issues/337

**Closed by aaronraimist** 2022-03-08 00:54 UTC
Labels: T-Enhancement
