### ISSUE TITLE
Desktop app: Ability to scan & send documents right away - scan built in feature

### ISSUE THREAD

**Issue by miguelhub** [vector-im/element-web#7733] opened 2018-11-22 08:00 UTC
### Description

This is a request to develop a new feature for the desktop app.
I use to communicate with some people by sending us scanned documents. We also send us normal messages, but basically we use to send us scanned documents. In order to make the communication lighter, it will be good to be able to scan a document AND send it right away, when being at the channel/chat window. There will be no need to save the document in the computer beforehand, just scan and send.

It will be like WhatsApp when sending a picture/document, where you have the chance to make a picture within the chat window and send it right away. 

It will be nice to have a built in functionality to do that task. 

Summary: built in functionality to scan & send a document right away (without having to save it first in the computer).

  

### Version information

For the desktop app:
- Desktop app.
- Ubuntu/Xubuntu

**Comment by t3chguy** [comment] 2018-11-22 08:17
Does this exist in any other messaging client? Seems a thing which will require a lot of native work (different per OS)

**Comment by t3chguy** [comment] 2022-05-17 10:52
Duplicate of https://github.com/vector-im/element-web/issues/3423

**Closed by t3chguy** 2022-05-17 10:52 UTC
Labels: P3, T-Enhancement
