### ISSUE TITLE
Room is not accessible anymore (bug screen)

### ISSUE THREAD

**Issue by Igeljaeger** [vector-im/element-web#19143] opened 2021-09-22 21:23 UTC
### Steps to reproduce

A room primarily used for calls is not accessible anymore.
Clicking on it doesnt grant me visible access.

### What happened?

It displays a screen asking me to open a github issue and send logs.
If i remember correctly, it might have had a running jitsi thing open and some other custom one (mumble web probably). But I sadly cannot check anymore as I am completely locked out due to this screen.

### Operating system

every OS

### Application version

Element Nightly version: 0.0.1-nightly.2021092201 Olm version: 3.2.3

### How did you install the app?

https://packages.riot.im

### Homeserver

jaeger.website

### Have you submitted a rageshake?

Yes

**Comment by SimonBrandner** [comment] 2021-09-23 04:26
Duplicate of https://github.com/vector-im/element-web/issues/19125

Should be fixed on the next Nightly, let me know if it isn't

**Closed by SimonBrandner** 2021-09-23 04:26 UTC
Labels: T-Defect
