### ISSUE TITLE
Automatically close jitsi meeting when nobody is on it

### ISSUE THREAD

**Issue by PxBCPG** [vector-im/element-web#19898] opened 2021-11-25 21:15 UTC
#### What would you like to do?

Avoid removing widget each time when nobody is on the call. 

#### Why would you like to do it?

It's a bit boring to manually have to close the meeting each time

#### How would you like to achieve it?

At least a "end meeting" button for the desktop app (great integration on android by the way), or, even better, an automatic process when there is nobody for X minutes (or both!)

**Comment by gsouquet** [comment] 2021-11-26 09:10
I'm not entirely sure it would be desirable to auto remove a widget after a specific period of time. I can think of a few scenarios where one would want to keep that up.

Trying to understand why the "remove for everyone" button does not fit the bill for you?

<img width="419" alt="Screen Shot 2021-11-26 at 09 09 51" src="https://user-images.githubusercontent.com/769871/143555901-21358780-2c00-4bdc-bb97-3efe0d95e09a.png">

**Comment by PxBCPG** [comment] 2021-11-26 19:27
I base this feature request on my previous experience with other platform. 
On most of the other plateforme with group meetings, when every participant have left the meeting, then the meeting automatically closes. 
I don't see the "few scenarios were one would want to keep that up" you're thinking at. Can you tell me a bit more about that?

**Comment by gsouquet** [comment] 2021-11-29 07:45
For example if a team wanted to use a Matrix room to do their daily standup, keeping the widget on at the same time could help individuals to join that meeting quite easily.

**Comment by PxBCPG** [comment] 2021-11-29 19:58
Okay, but for that kind of thing, it's better to manually create the widget once (because you will never remove it), and for all the other case (where you want to remove it), automatically remove it when nobody is left on the call

**Comment by toger5** [comment] 2021-12-21 16:02
Duplicate of: https://github.com/vector-im/element-web/issues/9055?

**Comment by SimonBrandner** [comment] 2021-12-22 14:52
> Duplicate of: #9055?

Yes

**Closed by SimonBrandner** 2021-12-22 14:52 UTC
Labels: X-Needs-Product, T-Enhancement, A-Jitsi, O-Occasional
