### ISSUE TITLE
Notification badge out of sync with mobile app

### ISSUE THREAD

**Issue by jrmuizel** [vector-im/element-web#25637] opened 2023-06-20 18:10 UTC
### Steps to reproduce

Not clear

#### What did you expect?

The notification badges should match between desktop and mobile. I.e. both clients should think there are the same number of unread messages.

#### What happened instead?

On desktop I see a badge with 1 unread message, and mobile there are no unread messages.

### Operating system

macOs

### Application version

Version 1.11.34 (1.11.34)

### Homeserver

mozilla.org

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-06-21 08:16
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-06-21 08:16
Duplicate of https://github.com/vector-im/element-web/issues/14863

**Closed by weeman1337** 2023-06-21 08:16 UTC
Labels: T-Defect
