### ISSUE TITLE
Spaces icon has weird outline in left left panel

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20186] opened 2021-12-14 14:12 UTC
### Steps to reproduce

1. Click on a space so that space avatar is outlined with a black outline.

### Outcome

Odd pale outline between space avatar and emphasis outline:
![Screenshot from 2021-12-14 13-22-25](https://user-images.githubusercontent.com/51663/146014463-935fa567-35ac-4f85-ad9f-f9d36f83a678.png)

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 705366ab8c7a-react-60286f617087-js-aeec4aa4a809 Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment] 2021-12-15 13:44
there's meant to be a 1px gap between the icon and the selected border, is that what you're referring to @kittykat?

**Comment by kittykat** [comment] 2021-12-16 05:22
> there's meant to be a 1px gap between the icon and the selected border, is that what you're referring to @kittykat?

Yes, that's it

**Comment by niquewoodhouse** [comment] 2022-04-11 14:48
Closing this issue because it's intentional and not a bug, thanks

**Closed** 2022-04-11 15:50 UTC
Labels: T-Defect, S-Minor, A-Spaces, X-Needs-Design, O-Uncommon
