### ISSUE TITLE
UI gets unresponsive and locked due to flickering error

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21313] opened 2022-03-04 12:43 UTC
### Steps to reproduce

1. Open Element
3. Open an ongoing room
4. Keep hovering the mouse pointer over the menu of a message until the issue happens

### Outcome

The mouse pointer keeps changing constantly very fast and it makes impossible to select an element of the UI at all, making the UI unusable. The mouse pointer can be moved.

See the GIF image below:

![Peek 2022-03-04 12-27](https://user-images.githubusercontent.com/3362943/156763525-8a1e7aca-b8d3-4452-baeb-1409028962a4.gif)

This can be reproduced on the reply icon as well.

Also this can be reproduced both modern layout and bubble layout.

![Peek 2022-03-04 12-41](https://user-images.githubusercontent.com/3362943/156765422-2869c4c9-06ba-4678-8dc1-a715e01585c1.gif)

### Operating system

Debian

### Application version

Element version 1.10.5

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-03-04 12:53
Duplicate of https://github.com/vector-im/element-web/issues/21147

**Closed by t3chguy** 2022-03-04 12:53 UTC
Labels: T-Defect

**Comment by luixxiul** [comment] 2022-03-04 13:23
@t3chguy whoops, thanks for checking!
