### ISSUE TITLE
--hidden launch flag broken in Element

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/element-web#14620] opened 2020-07-18 21:06 UTC
Upgraded from Riot-Desktop to Element, and now the launch flag "--hidden" is broken.

As in, the application launches but just draws a dark blank window. Never actually loads. Launching app without flag it loads fine.

Additionally, it does not even actually do what it's supposed to do, which is hide to system tray.

**Comment by t3chguy** [comment] 2020-07-18 21:09
Please fill in the issue template.

**Comment by BloodyIron** [comment] 2020-07-18 21:14
>Version:
Element version: 1.7.1
olm version: 3.1.3

Reproduction:
Run "element-desktop --hidden" in the console. Happens 100% of the time

OS:
Ubuntu 19.10

We're talking about Element-Desktop.

The rest of info really relevant in the template is already provided above.

**Comment by t3chguy** [comment] 2020-07-20 10:03
I cannot reproduce this on a fresh Ubuntu 20.04


![14620](https://user-images.githubusercontent.com/2403652/87925772-aae14e00-ca78-11ea-9ce0-c3b4448b193a.gif)

**Comment by BloodyIron** [comment] 2020-07-20 13:12
Well I did say I'm on 19.10, so there is that.

**Comment by BloodyIron** [comment] 2020-07-20 13:13
Also, may be relevant, but I'm using an RX580 with AMDGPU with the ACO code in it.

**Comment by t3chguy** [comment] 2020-07-20 13:14
19.10 is EOL so if that is to blame I wouldn't expect support

**Comment by BloodyIron** [comment] 2020-07-20 13:41
Support from Element? It's the last release before 20.04. The ONLY reason I haven't upgraded to 20.04 is because AMD has not released the ROCM driver for it, so by upgrading I would break OpenCL ability on my system, which I use for DaVinci Resolve offload.

**Comment by t3chguy** [comment] 2020-07-20 13:44
Support from whatever is the cause of that issue, Element is not the thing drawing the windows, that's Electron

**Comment by BloodyIron** [comment] 2020-07-20 13:46
No, I meant support from Element, as in the overarching name of the org that I am reporting the bug to.

Help me, or not, it's up to you.

**Comment by t3chguy** [comment] 2020-07-20 13:48
Its really not up to me, Element isn't huge enough to have sway over Electron, we also don't have the bandwidth to solve an issue one user hits and do not have the hardware to even reproduce.

**Comment by BloodyIron** [comment] 2020-07-20 13:49
Well, whenever it's possible to get solved, so be it. Just wanted to file the bug and do my part is all. :)

**Comment by daniel-lerch** [comment] 2020-10-25 17:37
This bug also affects Windows 10. If Element is launched with an argument `--hidden` a maximized black screen appears (#15486) instead of just a tray icon showing up.

Windows auto run invokes `Update.exe --processStart "Element.exe" --process-start-args "--hidden"` but it makes no difference if I start Element directly with `Element.exe --hidden`.

OS: Windows 10 Pro 2004 (Build 19041.72)
Element version: 1.7.10
Olm version: 3.2.1

**Comment by bronger** [comment] 2021-12-25 19:36
I confirm this issue on Ubuntu 20.04.  Note that it only occurs – at least for me, FWIW – if Element launches in full-screen mode (because I closed it that way last time).

**Comment by t3chguy** [comment] 2022-06-10 23:50
Duplicate of https://github.com/vector-im/element-web/issues/5214

**Closed by t3chguy** 2022-06-10 23:50 UTC
Labels: T-Defect, Z-Platform-Specific, X-Cannot-Reproduce, A-Electron, Z-Upstream
