### ISSUE TITLE
User Profile Picture Not Showing Properly

### ISSUE THREAD

**Issue by 8227846265** [vector-im/element-web#24348] opened 2023-01-27 08:03 UTC
### Steps to reproduce

Some members of our Space who already uploaded a profile picture are not appearing on the People section on the left sidebar however on the chat messages, their profile pictures appear properly.

#### What did you expect?
If the user already uploaded a Profile Picture, it will also update their profile icon on the People section of the sidebar instead of the default letters.

Reference for `People` section on the description above:
- Wherein `Rufus` already have a profile picture.
- However, in the People section, instead of `Rufus`'s profile picture. It still uses the `R` icon.
![image](https://user-images.githubusercontent.com/66582769/215037197-9a0e427a-dabe-48f2-93fd-3e140fc01a88.png)

#### What happened instead?
The user already uploaded a profile picture, but People section of the sidebar shows a letter as profile icon instead.

### Operating system

Windows

### Application version

Element version: 1.11.21-rc.1 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-01-30 16:07
Duplicate of https://github.com/vector-im/element-web/issues/20064

**Closed by t3chguy** 2023-01-30 16:07 UTC
Labels: T-Defect, S-Minor, A-Avatar, O-Frequent
