### ISSUE TITLE
element custom theme turns white on relaunch

### ISSUE THREAD

**Issue by autoteelar** [vector-im/element-web#18444] opened 2021-08-07 19:45 UTC
### Steps to reproduce

1 set a custom theme
2. close and re open element

happens in both the downloaded client and in the browser @ develop.element.io

### What happened?

theme colors dont apply and its as if you are using white theme

### What did you expect?

custom theme to reload 

### Operating system

linux

**Comment by robintown** [comment] 2021-08-07 19:48
Duplicate of https://github.com/vector-im/element-web/issues/17721

**Closed by robintown** 2021-08-07 19:48 UTC
Labels: T-Defect

**Comment by autoteelar** [comment] 2021-08-07 20:07
my bad seems the duplicate passed my eyes on my search, i also found a similar one https://github.com/vector-im/element-web/issues/18038, although the title is slightly misleading as it doesnt default to white unless you choose a custom theme
