### ISSUE TITLE
Poll votes different on pin message sidebar and on main room timeline

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21408] opened 2022-03-14 09:40 UTC
### Steps to reproduce

1. Pin a poll
2. Have people vote and then come back to the room later

### Outcome

<img width="1138" alt="Screen Shot 2022-03-14 at 09 37 54" src="https://user-images.githubusercontent.com/769871/158145984-aad0e9d6-1f2f-4361-b450-a7fd5ea181a2.png">

### Application version

Element Nightly version: 2022031001
Olm version: 3.2.8

### Will you send logs?

No

**Comment by robintown** [comment] 2022-03-14 12:46
What version is this on? This is supposed to be fixed.

**Comment by gsouquet** [comment] 2022-03-14 12:55
@robintown I've updated the original bug report with the version information

**Comment by robintown** [comment] 2022-03-14 12:57
Looks like this is a duplicate of https://github.com/vector-im/element-web/issues/21382, then

**Closed by robintown** 2022-03-14 12:57 UTC
Labels: T-Defect, S-Major, A-Message-Pinning, O-Occasional, A-Polls, Z-Labs
