### ISSUE TITLE
Element Icon no Longer Appears in Tray

### ISSUE THREAD

**Issue by InklingGirl** [vector-im/element-web#24361] opened 2023-01-29 01:32 UTC
### Steps to reproduce

1. Can't see icon in tray, only taskbar. Not even Gnome extensions like _Tray Icons: Reloaded_ or _TopIcons Fix_ restore it.
2. Can't click icon in tray, as it is not in tray.

#### What did you expect?
Icon to be in tray like it used to be.
#### What happened instead?
Icon is not in tray.

### Operating system

Ubuntu 22.04

### Application version

Element version: 1.11.21-rc.1 Olm version: 3.2.12

### How did you install the app?

Official Element PPA

### Homeserver

Irrelevant.

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-01-30 07:43
Hi @InklingGirl . This looks like duplicate of #23993 to me. You can follow the other issue for updates. If you think this is a different issue please send a comment.

**Comment by weeman1337** [comment] 2023-01-30 07:43
Duplicate of #23993

**Closed by weeman1337** 2023-01-30 07:43 UTC
Labels: T-Defect, Z-Platform-Specific, S-Minor, A-Tray-Icon

**Comment by InklingGirl** [comment] 2023-02-06 07:56
I should note this is particularly dangerous, as it gets rid of the only safe way to exit the app, w/o which you may accidentally end up launching other sessions or corrupting your current session.
