### ISSUE TITLE
seshat: not syncing all messages in all rooms (riot-desktop)

### ISSUE THREAD

**Issue by ericmigi** [vector-im/element-web#14407] opened 2020-07-10 20:23 UTC
### Description

I compiled riot-desktop with seshat to test out encrypted desktop search. I have discovered that some rooms are not fully cached, but others work fine.

![image](https://user-images.githubusercontent.com/1048265/87206982-a8843480-c2bf-11ea-8518-46f7a2b14a6d.png)

For example, this room with Rodrigo
- I can search for messages that were recently received. but then if I search for one sent a few minutes before, it does not show up.

In the video, I search for 'excellent' and no results. but one for 'windows' returns results.

https://streamable.com/ect8tx

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

linux, ubuntu 20.04. 

Logs: 
[seshat debug.zip](https://github.com/vector-im/riot-web/files/4905190/seshat.debug.zip)

**Comment by ericmigi** [comment] 2020-07-10 22:13
ok I think the issue is the 'not currently indexing messages for any rooms' window. It looks like that message is wrong. I left it running for a while longer, and it cached more messages.  
![image](https://user-images.githubusercontent.com/1048265/87207066-dbc6c380-c2bf-11ea-81c7-2a4c065cae2b.png)

**Comment by tredondo** [comment] 2020-07-23 09:15
Sounds like mt #13708

**Comment by turt2live** [comment] 2022-06-14 05:54
Duplicate of https://github.com/vector-im/element-web/issues/13708

**Closed by turt2live** 2022-06-14 05:54 UTC
Labels: T-Defect, A-Timeline-Search, A-Indexing
