### ISSUE TITLE
element-desktop: Auto-scrolling not working if window is maximized

### ISSUE THREAD

**Issue by dkl** [vector-im/element-web#15200] opened 2020-09-15 14:24 UTC
### Description
Hi,

since the upgrade of elements-desktop from 1.7.5 to 1.7.7 I've had some issues with scrolling.

If the elements-desktop window is maximized, the "Scroll to most recent messages" button is always visible in the right bottom corner, even if the chat window is scrolled down as far as possible. Clicking the button does not make it disappear as you would expect it to.
![element_maximized_reduced](https://user-images.githubusercontent.com/212549/93221945-a2527e80-f76e-11ea-873c-cb904b74982d.png)

If the window is not maximized, it appears to work as before (scroll all the way down, and the "Scroll to most recent messages" button disappears):
![element_unmaximized_reduced](https://user-images.githubusercontent.com/212549/93222043-c615c480-f76e-11ea-8a37-caba858e80de.png)

In addition to that, I've noticed that it scrolls/jumps up when receiving a new message in the chat, while it should scroll down. (maybe related to the issue above, but I'm not sure).

### Version information
elements-desktop 1.7.7, Ubuntu 20.04 x86_64

**Comment by t3chguy** [comment] 2020-09-16 15:15
Duplicate of https://github.com/vector-im/element-web/issues/14984

**Closed by t3chguy** 2020-09-16 15:15 UTC
Labels: bug, ui/ux
