### ISSUE TITLE
Can't promote users in a space to "admin" when using the context menu beside the space

### ISSUE THREAD

**Issue by wlach** [vector-im/element-web#17415] opened 2021-05-20 14:37 UTC
### Description

I can't promote users in a space to "admin" when using the context menu beside the space:

![image](https://user-images.githubusercontent.com/20569/118998267-4d978100-b957-11eb-807f-d410f2f76783.png)

### Steps to reproduce

- As an admin user, open the context menu for a space from the side-panel
- Select a non-admin user
- Note that there is no option to promote them to admin

I suspect it might be opening the options for a room, but am not sure. Selecting the user from the space overview *does* allow me to set the permissions appropriately. This is happening in the "Glean" space on chat.mozilla.org, if it helps.

### Version information

- **Platform**: web (in-browser) - Firefox

**Comment by t3chguy** [comment] 2021-05-20 14:45
> I suspect it might be opening the options for a room, but am not sure.

Yup, you need to `Manage & explore` first, then select the member to see their space profile/role

**Comment by t3chguy** [comment] 2021-05-20 14:46
Duplicate of https://github.com/vector-im/element-web/issues/17018

**Closed by t3chguy** 2021-05-20 14:46 UTC
Labels: A-Spaces, T-Defect
