### ISSUE TITLE
Rooms incorrectly marked as unread

### ISSUE THREAD

**Issue by Sorunome** [vector-im/element-web#10954] opened 2019-09-25 06:41 UTC
### Description

Rooms which only had a whole ton of m.room.member changes are incorrectly marked as unread. It mostly happens with discord linked rooms as the discord appservice tends to generate quite a few m.room.member events.

### Steps to reproduce

- Join a room with little activity
- wait for tons of m.room.member changes
- room will be marked as unread upon starting riot

Room should not be unread

Logs being sent: yes/no

### Version information

Pretty much all versions since a very long time, currently on 1.3.2 desktop.

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Waterfox 56.2.12
- **OS**: Arch Linux
- **URL**: https://ponies.im/_matrix/client/develop/ and others

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.3.2

**Comment by aaronraimist** [comment] 2019-09-27 15:07
Related: https://github.com/vector-im/riot-web/issues/8513

**Comment by matejdro** [comment] 2020-04-01 16:35
Also happens on Android client 0.9.10

**Comment by matejdro** [comment] 2020-04-09 06:55
I did some digging and I think I found root cause of the issue:

Riot gets its unread status by [Getting short list of last events and attempts to find last read message](https://github.com/matrix-org/matrix-react-sdk/blob/a26a3f58624d5e135104029a8bc9799df3962414/src/Unread.js#L72). However, this list of events is very short and if it gets filled by status messages, riot will never find any read messages there and always mark the list as read.

I am not sure what would be the best way to fix this though.

**Comment by andybalaam** [comment] 2023-05-16 09:40
I saw this problem again this morning. Up until recently, this problem has been masked by much worse unread problems that have hopefully now been fixed by the work on [stuck notifications #24392](https://github.com/vector-im/element-web/issues/24392).

**Closed** 2023-05-26 14:40 UTC
Labels: T-Defect, A-Room-List, A-Read-Marker

**Comment by leonardehrenfried** [comment] 2023-09-14 07:38
After this issue had mostly disappeared, I'm seeing this again starting yesterday. I've submitted debug logs.

It's both the case on develop.element.io and app.element.io.

**Comment by andybalaam** [comment] 2023-09-14 12:50
> After this issue had mostly disappeared, I'm seeing this again starting yesterday. I've submitted debug logs.
> 
> It's both the case on develop.element.io and app.element.io.

Hmm - the only change we made in this area was https://github.com/matrix-org/matrix-js-sdk/pull/3706/files which we really tried to think through and make sure it didn't cause the problem. Discussion here: https://github.com/matrix-org/matrix-js-sdk/issues/3684

@leonardehrenfried if you were able to provide a consistent way to reproduce the problem that would be incredibly helpful. Then we could create a test case in https://github.com/vector-im/element-web/issues/25449 that would make sure we squashed the bug for good.

**Comment by andybalaam** [comment] 2023-09-14 16:04
Thank you @leonardehrenfried for your understanding. Thank you for sending reports, but we've got plenty and they mostly don't tell us what we need to know (probably because of a lack of the right logging...), so there's not much value in sending more. We are actively working on this and expect to improve it over the next few weeks.
