### ISSUE TITLE
Labels not displaying correctly

### ISSUE THREAD

**Issue by lupa18** [vector-im/element-web#20423] opened 2022-01-06 15:29 UTC
### Steps to reproduce

1. I began an individual call
2. Click share screen button

#### What did you expect?
See correct texts

#### What happened instead?
"missing translation" appears next to actual text

![imagen](https://user-images.githubusercontent.com/463429/148407306-887b2dcd-d62b-49c6-ba04-50faaaebc752.png)

### Operating system

Linux

### Application version

Versión de Element: 1.9.8
Versión de Olm: 3.2.8

### How did you install the app?

https://element.io/get-started (apt)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by kittykat** [comment] 2022-01-06 15:32
Duplicate of #9422 

Thank you for taking the time to report this issue. I'm going to close this report in favour of the old one. Please follow that one if you would like updates on the progress.

**Comment by SimonBrandner** [comment] 2022-01-06 15:37
Hmm, this I don't think this is the same issue, just a feeling now, will investigate

**Comment by MTRNord** [comment] 2022-01-06 19:48
> Hmm, I don't think this is the same issue, just a feeling now, will investigate

Knowing the old issue, I agree that this is different. There was a recent fallback related PR in the react-sdk "recently" which is my guess on what is causing it since this is happening also for things that had no code changes for 6 months or more. 

(My guess is https://github.com/matrix-org/matrix-react-sdk/pull/7323 though I am not sure what exactly in it may cause this)

**Comment by MTRNord** [comment] 2022-01-06 20:02
Actually looking more at this the exact regression seems to be that https://github.com/matrix-org/matrix-react-sdk/pull/7323/files#diff-0733568a0dbb658491a8eb24c5646711c77c32f86701b3212ac5a54b014c683eL101-L105 is missing now. At least, I don't see how it now is handled? 

The old code handled that by explicitly requesting it by overwriting the language of the specific string. However, the new code sets the fallback language. If the comment on the old code can be trusted, the new code works as long as there are no plurals. So in short the old if is still needed as counterpart is not doing fallback for plural things and there for we can't rely on the fallback language option.

**Comment by kittykat** [comment] 2022-01-07 11:16
Also nightly on Linux:
![Screenshot from 2022-01-07 11-15-42](https://user-images.githubusercontent.com/51663/148536223-83898fd6-a7a2-4a04-9c7b-6eb7a1f8cedf.png)

**Closed** 2022-01-07 11:22 UTC
Labels: T-Defect, X-Regression, S-Major, A-VoIP, X-Needs-Investigation

**Comment by kerryarchibald** [comment] 2022-01-07 16:52
Duplicate of https://github.com/vector-im/element-web/issues/20426
