### ISSUE TITLE
Someone's avatar is loaded in our DM room, but not in the list of people

### ISSUE THREAD

**Issue by thibaultamartin** [vector-im/element-web#20220] opened 2021-12-16 09:57 UTC
### Steps to reproduce

Open a DM with someone
Their avatar loads in the room, next to their messages
The avatar is not updated in the left bar nor the header (it's still a letter in a circle)

#### What did you expect?

I expected the avatar to be consistently loaded everywhere

#### What happened instead?

The avatar wasn't loaded in the left bar nor header, and the placeholder was still displayed

### Operating system

macOS

### Application version

Element Nightly version: 2021121601

### How did you install the app?

https://element.io/get-started#nightly

### Homeserver

ergaster.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2021-12-16 10:08
Clear your client cache, likely your `m.direct` account data event is stale or something similar.

Settings > Help & About > Clear cache and reload

**Comment by SimonBrandner** [comment] 2021-12-18 08:56
> Clear your client cache, likely your `m.direct` account data event is stale or something similar.
> 
> Settings > Help & About > Clear cache and reload

@thibaultamartin, did that help?

**Comment by thibaultamartin** [comment] 2021-12-20 08:59
@SimonBrandner yes it did fix the issue for me :)

**Comment by SimonBrandner** [comment] 2021-12-22 16:11
Closing as a duplicate of https://github.com/vector-im/element-web/issues/20064

**Closed by SimonBrandner** 2021-12-22 16:11 UTC
Labels: T-Defect, X-Needs-Info
