### ISSUE TITLE
Formatting bar broken into two lines unless I zoom out

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#17453] opened 2021-05-24 11:20 UTC
### Description
The formatting bar is split up into two lines and looks broken unless I zoom out in Element Desktop. The second line often overlaps with the input line. It looks like this:

![image](https://user-images.githubusercontent.com/463342/119340405-c1f15d80-bc92-11eb-9c7a-b1c56e38be5b.png)

### Version information

- **OS**:  Arch Linux
- **URL**: Element Desktop 1.7.28

**Comment by t3chguy** [comment] 2021-05-24 11:21
Could you rageshake to share your settings/env with the dev team, thanks

**Comment by dkasak** [comment] 2021-05-24 11:29
Done!

**Comment by t3chguy** [comment] 2021-05-24 11:31
I'd wager its related to you having increased your font-size in settings

`"baseFontSize":11`

Should be reasonably simple to fix

**Comment by hpdeifel** [comment] 2021-06-11 06:24
Fwiw: I have the same problem (Element desktop, flatpak, wayland). The font size is on the default value and `"baseFontSize":11` doesn't help either.

It's `S-Tolerable` only in the sense that I inadvertently convert single words to quoted paragraphs almost every day because I can't get out of the habit of using triple-click-selections. Those should select the whole line, but since the formatting bar appears under the cursor after a double click, the third click hits the quote button.

**Comment by t3chguy** [comment] 2021-07-12 12:50
Duplicate of https://github.com/vector-im/element-web/issues/12390

**Closed by t3chguy** 2021-07-12 12:50 UTC
Labels: S-Minor, T-Defect, Z-Bite-Sized, Z-Rageshake
