### ISSUE TITLE
Unread message notification stuck in thread

### ISSUE THREAD

**Issue by jlfrance** [vector-im/element-web#23770] opened 2022-11-15 08:18 UTC
### Steps to reproduce

1. I have reviewed and clear all unread message notifications except for 2
2. I click into the room with the 2 unread message notifications (room ID !FopvdhNdkJGyyImWXb:thesis.co)
3. I open threads and locate the red unread message dot
4. I click on the thread with the dot and scroll through all the messages (last posted message Sept 10th)
5. The dot remains and the unread message count remains at 2

#### What did you expect?
I expected the red dot / unread message notification to be cleared once I clicked on the unread message

#### What happened instead?
The unread message notification remained despite reviewing all the messages in the thread

### Operating system

macOS

### Application version

Element version: 1.11.14 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started#download

### Homeserver

chat.thesis.co

### Will you send logs?

Yes

**Comment by gsouquet** [comment] 2022-11-15 09:53
Hi @jlfrance I believe the symptoms you are describing are the same as in this other issue https://github.com/vector-im/element-web/issues/23754

Can you reproduce the same problem in develop.element.io?

**Comment by gsouquet** [comment] 2022-11-21 08:12
Duplicate of https://github.com/vector-im/element-web/issues/23754

**Closed by gsouquet** 2022-11-21 08:12 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-Notifications, A-Threads
