### ISSUE TITLE
Switching audio device in the settings while calling someone doesn't change the mic until you re-initiate the call

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20547] opened 2022-01-14 07:07 UTC
### Steps to reproduce

1. Call someone
2. Change your audio devices in the settings
3. Observe nothing happening until you recall

#### What did you expect?
I expected it to change my audio devices
#### What happened instead?
Nothing (until recall)

### Operating system

Windows 10

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-01-14 07:08
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/15595

**Closed by SimonBrandner** 2022-01-14 07:08 UTC
Labels: T-Defect
