### ISSUE TITLE
Make it easier to read long topics

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#17367] opened 2021-05-18 20:18 UTC
With a simple tweak, e.g. clicking to reveal in a low touch dedicated modal with:

- Room avatar & room name as modal title
- Topic as modal body
- X button to close

**Comment by SimonBrandner** [comment] 2021-05-19 06:04
Duplicate of [#9623](https://github.com/vector-im/element-web/issues/9623)

**Closed by SimonBrandner** 2021-05-19 06:04 UTC
Labels: Z-Impact-2, Z-Papercuts, Z-Visibility-1
