### ISSUE TITLE
Requests for room avatars when I change room list width

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24619] opened 2023-02-23 00:13 UTC
### Steps to reproduce

When I change a width of room list Element asks for avatars. Element asks for avatars from servers when I make room list as avatars only and asks again if increase width with room titles. Again if make "avatars only"... 

#### What did you expect?
Element does not ask for avatars. Because there is no difference.
#### What happened instead?
Element send request for avatars
` GET https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/...?width=32&height=32&method=crop`

### Operating system

Windows 7

### Application version

1.11.23

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-02-23 07:29
@JeanPaulLucien Unfortunately I cannot reproduce your issue. Can you send logs anyway after you resized the room list to see if any error is causing re-requesting the room avatars?

**Comment by JeanPaulLucien** [comment] 2023-02-23 08:56
@weeman1337 I try to describe "how to" more.
Room list can be only avatars or avatars + title. At the moment when Element switches between these mode the request for avatars are going. In fact I do not understand why Element does requests avatars when I switch a view of a room list because an avatars was loaded before. I have not seen difference, avatars are same.

**Comment by t3chguy** [comment] 2023-02-23 09:26
@JeanPaulLucien Element is a Web app (under Electron on Desktop) so things like image loading are actually handled by the browser. Element uses the `<img />` tag to specify where images should go. When switching from minimized to normal room list the DOM changes and thus the browser may choose to re-request the resources.

I cannot reproduce this unless I select `Disable cache`


https://user-images.githubusercontent.com/2403652/220867916-e4f56b30-3aab-4348-a192-27ad85caf021.mov

**Comment by JeanPaulLucien** [comment] 2023-02-23 09:42
@t3chguy you reproduced. 0:05-0:06. Just I have discovered the requests because have seen an error. 
I see 200 code. Element even downloads that.

**Comment by t3chguy** [comment] 2023-02-23 09:43
@JeanPaulLucien as I wrote in my comment, it is only reproducible if caching is disabled. The server sets a `Cache-Control` header which browsers should be respecting.

> I cannot reproduce this unless I select Disable cache

**Comment by JeanPaulLucien** [comment] 2023-02-23 09:46
@t3chguy my case about Desktop. Where to find about "Cache-Control"?

**Comment by t3chguy** [comment] 2023-02-23 09:47
> Element is a Web app (under Electron on Desktop) so things like image loading are actually handled by the browser. Element uses the <img /> tag to specify where images should go. When switching from minimized to normal room list the DOM changes and thus the browser may choose to re-request the resources.

If you're not going to bother reading my responses I won't be bothering to further reply to you.

**Comment by JeanPaulLucien** [comment] 2023-02-23 09:58
I would to prefer not spend a computing power to tries to renew (get from the server) room avatars so often, but seems you have no choice.

**Comment by t3chguy** [comment] 2023-02-27 13:06
Closing as Windows 7 is not a supported environment, could not reproduce as per my video above. Please leave a comment with a screen recording from a supported environment if this still affects you

**Closed by t3chguy** 2023-02-27 13:06 UTC
Labels: T-Defect, X-Cannot-Reproduce
