### ISSUE TITLE
Animate microphone icon as someone speaks to help identify microphone configuration issues

### ISSUE THREAD

**Issue by DavyLandman** [vector-im/element-web#18645] opened 2021-08-19 21:37 UTC
#### What would you like to do?
Most video calling software have a small indicator that you are speaking. I would like the much improved one-on-one calls to also have this.

#### Why would you like to it?

It's a very useful debugging util to show people their selected microphone is picking up sound. Or other the opposite, you've just plugged in a headset (or connected a Bluetooth one) and the switch wasn't made. I've seen this in many other video calling solutions, and it's a very subtle thing, that I think a lot of people would appreciate.

### Have you considered any alternatives?

Alternativly a bar below the settings menu where you switch a microphone, but that is less Visual. Ideally you want to help the scenario where both sides are trying to debug why they aren't hearing one side.

### Additional context

There is already a microphone icon (to show muted status) animating/coloring that in some relation to sound input would I hope be a small step to make, while improving UX.

**Comment by robintown** [comment] 2021-08-19 23:15
Duplicate of https://github.com/vector-im/element-web/issues/17627

**Closed by robintown** 2021-08-19 23:15 UTC
Labels: T-Enhancement

**Comment by DavyLandman** [comment] 2021-08-20 07:03
Sorry, I tried searching, but used the wrong terms it seemed, glad it's already bring tracked as an improvement.

**Comment by SimonBrandner** [comment] 2021-08-20 07:05
> Sorry, I tried searching, but used the wrong terms it seemed

No need to worry about it :)
