### ISSUE TITLE
Ongoing rooms /events stream for a joined room

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/element-web#1607] opened 2016-06-07 10:32 UTC
After creating a 1:1 room there is an ongoing events stream, e.g.:

```
/_matrix/client/r0/events?room_id=!nSDXcqITYQOwemzUEf%3Amatrix.org&timeout=30000&from=s23723119_10771800_2748_1816477_7197_2731&access_token=...
```

**Comment by ara4n** [comment] 2016-06-18 22:36
this is confused peeking code, I guess.  It sounds like you're about to remove the v1 peeking crap whilst doing paginated sync, which will help this a lot...

**Comment by turt2live** [comment] 2020-09-02 01:30
Duplicate of https://github.com/vector-im/element-web/issues/1229 I think

**Closed by turt2live** 2020-09-02 01:30 UTC
Labels: maintenance, p2
