### ISSUE TITLE
Space panel expand button is distracting

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20094] opened 2021-12-08 03:22 UTC
### Steps to reproduce

Hover over the space panel

### Outcome

The space panel expand button appears in the top left corner of the screen, which is distracting given how high-contrast and attention-drawing its appearance is. It's strange to see it appear no matter where or for how long I hover over the bar, since a lot of the time I'm looking at something far down in the space list, or even just moving my cursor through the bar to get to other parts of the screen. In both of these cases, it's surprising to see something flicker on/off so far away from the things I'm interacting with, and at such a high-importance location in the window.

### Operating system

NixOS unstable

### Browser information

Firefox 94.0.2

### URL for webapp

develop.element.io

### Application version

Element version: b0abbfacd48b-react-97ee25126fb7-js-2206b80e65aa Olm version: 3.2.3

### Homeserver

townsendandsmith.ml

### Will you send logs?

No

**Comment by t3chguy** [comment] 2021-12-08 08:50
Duplicate of https://github.com/vector-im/element-web/issues/20079

**Closed by t3chguy** 2021-12-08 08:50 UTC
Labels: T-Defect, S-Minor, A-Spaces, X-Needs-Design, Z-Community-Feedback, O-Frequent
