### ISSUE TITLE
Backup restoration is blocking me from using the product

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23930] opened 2022-12-07 14:29 UTC
### Steps to reproduce

1. Start backup restoration
2. It now has a modal that fetches ALL your keys... and this took approximately 1h30m on my account

#### What did you expect?

For this to be performed in the background, and for messages to be decrypted as keys are downloaded, not for everything to be downloaded when i have downloaded all my keys

#### What happened instead?

There is a modal that blocks me from using Element. If i click away, all progress is lost and nothing is decrypted

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-12-07 14:44
Duplicate of https://github.com/vector-im/element-web/issues/20694

**Closed by t3chguy** 2022-12-07 14:44 UTC
Labels: T-Defect, A-E2EE-Key-Backup
