### ISSUE TITLE
Clicking a reply timestamp the second time doesn't jump

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#17717] opened 2021-06-21 19:21 UTC
### Description

When clicking on a reply timestamp for a second time, i don't jump to the message.

### Steps to reproduce

1. See a reply to a message that was posted outside of the current view window.
2. Click on time stamp, observe jump
3. Go back down, via scrolling or right-side down-arrow button
4. Click on time stamp a second time, observe no jump

#### Describe how what happens differs from what you expected.

I expected the action to be idempotent, to center my attention on the message again, only it (i suspect) did the message highlighting thing without jumping me to it, because the message was already "in the timeline"

### Version information

- **Platform**: desktop

- **OS**: Linux, via flatpak
- **Version**: 1.7.30

**Comment by robintown** [comment] 2021-06-21 19:40
Duplicate of #2903, which is fixed in 1.7.31 by matrix-org/matrix-react-sdk#5823.

**Closed** 2021-06-21 19:43 UTC
Labels: T-Defect
