### ISSUE TITLE
Option to only display direct member rooms in (sub-)space view

### ISSUE THREAD

**Issue by alyaeanyx** [vector-im/element-web#17382] opened 2021-05-19 10:35 UTC
#### Is your suggestion related to a problem? Please describe.
When organizing lots of rooms in recursive structures with spaces and subspaces, the Rooms section of higher-level spaces generally is unordered and confusing. Consider the following example setup:

```
Example Space
| Room 1
| Room 2
+ Subspace 1
 | Room 3
 | Room 4
 | Room 5
+ Subspace 2
 | Room 6
 | Room 7
 | Room 8
```
When clicking on "Example Space" in the spaces bar, I'd mostly be looking for Rooms 1 and 2 in this scenario, but due to the recursive search for room members in all subspaces, the "Example Space" room view will also include all the other rooms, which can make searching for Rooms 1 and 2 quite annyoing.

#### Describe the solution you'd like.
Add an option to disable recursive searching for member rooms - either in the space settings or globally in the client settings.

#### Describe alternatives you've considered.
Disabling recursive search entirely, ordering rooms based on whether they are direct members or recursive members

**Comment by t3chguy** [comment] 2021-11-10 11:40
Duplicate of https://github.com/vector-im/element-web/issues/16786

**Closed by t3chguy** 2021-11-10 11:40 UTC
Labels: A-Spaces, X-Needs-Product, T-Enhancement
