### ISSUE TITLE
Element-Desktop: Tray icon missing from Xfce notification panel

### ISSUE THREAD

**Issue by krassle** [vector-im/element-web#24092] opened 2022-12-22 17:24 UTC
### Steps to reproduce

1. Install Element-Desktop 1.11.17 on Debian 10 with Xfce4 Desktop Environment
2. Start newly installed Element-Desktop 1.11.17
3. Observe: Element tray icon is not added to the Xfce notification panel
4. Downgrading to Element-Desktop 1.11.16 fixes this issue!

#### What did you expect?
Application icon is shown in the the Notification Area (xfce4-panel / systray)

#### What happened instead?
Element icon missing from Notification area (xfce4-panel / systray)

### Operating system

Debian 10 (buster)

### Application version

1.11.17

### How did you install the app?

https://packages.element.io/debian

### Will you send logs?

No

**Comment by weeman1337** [comment] 2022-12-23 07:36
I had a similar issue yesterday and thought some other update broke it #24089 .

**Comment by t3chguy** [comment] 2022-12-23 09:35
Duplicate of https://github.com/vector-im/element-web/issues/23993

**Closed by t3chguy** 2022-12-23 09:35 UTC
Labels: T-Defect, Z-Platform-Specific, S-Minor, O-Occasional
