### ISSUE TITLE
Seen by/Read receipt icons showing at top of long message

### ISSUE THREAD

**Issue by amalon** [vector-im/element-web#15514] opened 2020-10-20 22:31 UTC
### Description

The "Seen by ..." / read receipt icons show alongside the last seen message, but if the message is long (e.g. a reply) they show at the top of that message:
![image](https://user-images.githubusercontent.com/210303/96650017-05b16c80-132a-11eb-89a4-d492fb8f470b.png)

This can sometimes be confusing, especially with a wide screen, as it looks as if they haven't seen the big message when they have.
The confusion is made worse by the visual joining of multiple consecutive messages from the same person, as the separation of the messages isn't visible unless you move the mouse over it, so there is sometimes no visual cue exactly how far through that user's text people have really seen.

it would be better to show these icons aligned with the bottom of the message, as that is the actual separation of seen/unseen.

### Steps to reproduce

- send (multiple consecutive) long message (e.g. a long reply) in room with others
- icons should move to bottom of last message seen as people see the messages

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: element-desktop-1.7.10-1

**Comment by amalon** [comment] 2020-10-20 22:34
Note that element-android shows these icons **below** the last seen message (presumably to save horizontal space)

**Comment by t3chguy** [comment] 2020-10-20 22:36
Duplicate of https://github.com/vector-im/element-web/issues/4377

**Closed by t3chguy** 2020-10-20 22:36 UTC
Labels: bug, ui/ux
