### ISSUE TITLE
QR code for xsigning loading endlessly

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20230] opened 2021-12-16 19:43 UTC
### Steps to reproduce

1. log out
2. log back in
3. click verify with another device
4. on other (android) device choose scan qr code

cancel and try again doesn't fix it

#### What did you expect?
qr code appears
#### What happened instead?
no qr code, only spinner

### Operating system

arch

### Application version

Element Nightly version: 2021121401 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

Yes

**Comment by HarHarLinks** [comment] 2021-12-16 19:46
emoji however do work

**Comment by kittykat** [comment] 2021-12-16 20:04
Duplicate of #20188

**Closed by kittykat** 2021-12-16 20:04 UTC
Labels: T-Defect
