### ISSUE TITLE
BigblueButton Widget Issue with audio peripherals

### ISSUE THREAD

**Issue by efazenda** [vector-im/element-web#14901] opened 2020-08-07 08:00 UTC
### Description

Dear Team, 

Great product !
We have an issue with the integration of Widget BigBlueButton (With BigBlueButton instance self-hosted) and Element WebApp or Element Desktop App Windows 10, when we join the conference while choosing Micro, it say's that there is an issue accessing my peripherals.

We use an self-hsoted Matrix Server
We use an selft-hosted BigBlueButton Server.

![image](https://user-images.githubusercontent.com/2209728/89622826-ee6af300-d893-11ea-982b-bc510d5f98e8.png)

### Version information

- **Platform**: Web Browser and Application ?

For the Web app and Desktop App:

- **Browser**: Chrome 84.0.4147.105 
- **OS**: Windows 10 Latest Version with Patches.
- Element Desktop App : 1.7.3

Do you have an idea why this is blocking ? If you need more information don't hesitate to ask :) 

Thank You.

Best Regards, Edouard Fazenda.

**Comment by bwindels** [comment] 2020-08-07 09:50
@efazenda what is the url of your widget? Can we use it to try and reproduce your issue?

**Comment by bwindels** [comment] 2020-08-07 09:52
@anoadragon453 any ideas?

**Comment by efazenda** [comment] 2020-08-10 07:42
Hi, @bwindels  

_@efazenda what is the url of your widget? Can we use it to try and reproduce your issue?_

It's a private room but here a new one where the problem is similar.

URL of the conference room on out BigBlueButton instance.
https://conference.csti.ch/b/faz-ttj-xkw 

It you need more information don't hesitate to ask.

Best Regards, Edouard Fazenda.

**Comment by anoadragon453** [comment] 2020-08-14 10:43
Sorry for the late reply, was on holiday :slightly_smiling_face: 

I can reproduce this. Thanks for the test URL, it was quite useful. I get an error in the JS console in Chromium:

```
ERROR: clientLogger: Error getting microphone - {NotAllowedError: Permission denied}
```

which comes from [here](https://github.com/bigbluebutton/bigbluebutton/blob/2a28bb1df29d0470c40f7b70ad540080b0c8f515/bigbluebutton-html5/imports/ui/services/audio-manager/index.js#L451) in BBB's source code.

Element does allow widget iframes microphone and camera permissions, however it looks like the widget's inner iframe does not have the `microphone` or `camera` properties, which would block access to the iframe. I'll have a play around and see if I can modify scalar's iframe to allow this.

**Comment by anoadragon453** [comment] 2020-08-14 15:07
Adding the `camera; microphone` feature policies to the inner `iframe` has allowed the widget to request camera/microphone permissions :)

A fix is now in development - will keep you posted.

**Comment by efazenda** [comment] 2020-08-17 09:40
Hi @anoadragon453 , 

No worries , Hope you enjoy your holidays :) !
Thanks a lot for the fix !

Waiting to have this released.

Have a nice day.

**Comment by anoadragon453** [comment] 2020-08-18 09:22
@efazenda The fix has been released to production as of today. Let us know if it doesn't work for you - and thanks again for reporting!

**Closed by anoadragon453** 2020-08-18 09:22 UTC
Labels: bug, type:scalar

**Comment by efazenda** [comment] 2020-08-18 10:05
Hi @anoadragon453 ,

Yes it's working now ! 

Thanks for the fix and keep up the good work :) 

Cheers, Edouard.

**Comment by danielfomin96** [comment] 2021-05-29 14:04
I am having the same problem.
I get the following error:
```
sip.SessionDescriptionHandler | SessionDescriptionHandler.getDescription failed - NotAllowedError: The request is not allowed by the user agent or the platform in the current context. sip.js:9594:25
sip.Inviter | Session.getOffer: SDH getDescription rejected... sip.js:9594:25
sip.Inviter | The request is not allowed by the user agent or the platform in the current context.
```

### Version information

    Platform: Web Browser and Application ?

For the Web app and Desktop App:

    Browser: Firefox 88.0.1
    OS: Linux
    Element Desktop App : 1.7.29

**Comment by anoadragon453** [comment] 2021-06-03 10:21
@danielfomin96 Judging by the logs I think you're attempting a SIP call instead of a BigBlueButton one?

This issue was something specifically broken in the BigBlueButton widget. If you're having issues with SIP calling in Element, please open a new issue :slightly_smiling_face:
