### ISSUE TITLE
Replies on avatars look bad

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7530] opened 2018-10-22 21:42 UTC
![image](https://t2l.io/_matrix/media/v1/download/t2l.io/a8916731d40afc1eff6366c3a7213dbd)

**Comment by turt2live** [comment] 2018-10-22 21:50
Note that in Riot you can't actually reply to state events, which might also be a feature we could support.

**Comment by anoadragon453** [comment] 2019-06-27 16:03
I can confirm that this is still a problem.

![image](https://user-images.githubusercontent.com/1342360/60281749-6f1f9780-98fd-11e9-9e45-dec87cff4a85.png)

Although this is only possible by sending a custom event.

**Comment by t3chguy** [comment] 2019-06-27 16:07
This is technically against the spec so I'm not sure why it should be supported:
https://matrix.org/docs/spec/client_server/r0.5.0#rich-replies

The fix here might be just to not render it at all:

> Rich replies may reference any other m.room.message event

**Comment by anoadragon453** [comment] 2019-06-27 16:09
@t3chguy Indeed, good find.

**Comment by tulir** [comment] 2019-10-13 13:06
> The fix here might be just to not render it at all

No, the spec should be fixed. I don't get why there are so many dumb arbitrary limitations in the spec

**Comment by t3chguy** [comment] 2019-10-13 18:44
The limitations on the spec are due to fallback support only.

**Comment by tulir** [comment] 2019-10-13 18:51
That's a valid (but still dumb) excuse for preventing replying with images and such, but not for preventing replies to state events. The fallback can simply say "In reply to [...] zabot set a profile picture"

**Comment by t3chguy** [comment] 2019-10-13 18:55
I completely agree, I was working to a very tight specification and it hurt me to kneecap it as such

**Closed** 2021-07-15 14:52 UTC
Labels: A-Avatar, A-Replies, P2, S-Minor, T-Defect
