### ISSUE TITLE
People Header Misaligned on Safari (macOS)

### ISSUE THREAD

**Issue by justledbetter** [vector-im/element-web#23890] opened 2022-12-02 15:18 UTC
### Steps to reproduce

1. Open Safari
2. Login to app.element.io
3. Observe the position of the People (DMs) section in the left sidebar.

#### What did you expect?
This control renders correctly in Chrome.

#### What happened instead?
This control renders incorrectly in Safari.

This screenshot illustrates the difference (Safari on left, Chrome on right)

![Screenshot 2022-12-02 10 12 42](https://user-images.githubusercontent.com/13354341/205324832-aad34aa3-ace2-43ed-931e-48b7e35541ef.png)

### Operating system

macOS

### Browser information

Safari 16.0 (17614.1.25.9.10, 17614)

### URL for webapp

app.element.io

### Application version

1.11.15

### Homeserver

Synapse

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-12-02 15:29
Duplicate of https://github.com/vector-im/element-web/issues/17283

**Closed by t3chguy** 2022-12-02 15:29 UTC
Labels: T-Defect
