### ISSUE TITLE
regression: on 1.10.10, windows 10/x64, one of sub-processes (element.exe) is creating tenfold or more load when simply visible main gui window.

### ISSUE THREAD

**Issue by subscribernamegoeshere** [vector-im/element-web#21825] opened 2022-04-16 13:50 UTC
### Steps to reproduce

1. just updated (two machines) to 1.10.10 element desktop for windows, on two win10 pro x64 machines. only change of the situation is it being 1.10.10 compared to release right before (1.10.9). main gui appears and on a weak older laptop (one of the two involved windows machines) i noticed that the cpu fan getting noisy. researched the situation and figured out exactly, that the third sub-process (element.exe) on this machine is creating real high cpu load on this laptop when the main gui of element desktop is visible. no fancy animations, no gifs, or no video or nothing exciting going on in the chat of the two involed matrix.org user accounts. just like few chat lines, some picture attached visible
2. as soon as i just only as much as lower the window (element desktop) to the task bar, or as i hide it with just any other windows programs windows (such as notedpad.exe) fully (! every pixel of it, every border of element gui), the third subprocess element.exe cpu load calms down completely doing as little as .00% load or very little. compared to 10-15% (!) cpu load on this aged laptop when even visible as much as a pixel width of its border of the gui or fully visible, doesnt matter the cpu load.

3. use such tools to observe the process and subprocesses (and threads) activity such as process explorer by microsoft/sysinternals or also process-hacker (open source project).

4. this cpu load situation was NOT the case in the previous version of element desktop at 1.10.9

5. the third subprocess of element.exe is being shown (in the process explorer etc tools) to be running with the following command line parameters (spawned, called): 

"C:\Users\userhere\AppData\Local\riot\app-1.10.10\Element.exe" --type=renderer --user-data-dir="C:\Users\userhere\AppData\Roaming\Riot" --standard-schemes=vector --enable-sandbox --secure-schemes=vector --bypasscsp-schemes --cors-schemes --fetch-schemes=vector --service-worker-schemes --streaming-schemes --app-user-model-id=com.squirrel.element-desktop.Element --app-path="C:\Users\userhere\AppData\Local\riot\app-1.10.10\resources\app.asar" --lang=de --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=4 --launch-time-ticks=112657028243 --mojo-platform-channel-handle=2440 --field-trial-handle=1720,14098625769721958728,269692039262696788,131072 --enable-features=WebRTCPipeWireCapturer --disable-features=HardwareMediaKeyHandling,MediaSessionService,PlzServiceWorker,SpareRendererForSitePerProcess,WinRetrieveSuggestionsOnlyOnDemand /prefetch:1

### Operating system

windows 10, pro, x64

### Application version

1.10.10

### How did you install the app?

long termin riot desktop use case here, installed originally from riot elements official webpage with .exe download installer etc.

### Homeserver

matrix.org accounts, two simple accounts there, chatting to each other.

### Will you send logs?

No

**Comment by subscribernamegoeshere** [comment] 2022-04-16 13:56
could be the very same or tied to this issue also reported about cpu load issues: https://github.com/vector-im/element-web/issues/21793

thanks for considering.

**Comment by SimonBrandner** [comment] 2022-04-16 16:37
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/21793

**Closed by SimonBrandner** 2022-04-16 16:37 UTC
Labels: T-Defect
