### ISSUE TITLE
We should be able to paste a room URL into the `mxRoom_search_input`.

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#20938] opened 2022-02-06 12:30 UTC
### Your use case

Consider the following case:

1. I already have an account and I have my Element Web open.
2. I receive the URL of a public room in some manner, perhaps by email.
3. Clicking on it opens a new browser window.
4. I can now accept to use Element.
5. But not Element Desktop.
6. Ok, link is followed to Element
7. If I'm unlucky, I now have a tab requesting my password and I have no idea why, because Element is already open on another tab.
8. If I manage to reach the end of the flow, I now have two Element tabs.

Recently, I've tried to guide a newbie through joining a Fosdem room and that was... complicated.

I'd like to be able to do the following:

1. I already have an account and I have my Element Web open.
2. I receive the URL of a public room in some manner, perhaps by email ­— hopefully with instructions.
3. I copy this URL to the room search bar.
4. This gets my Element Web to join the room.

I believe that this would make for a simpler user experience.

**Comment by gsouquet** [comment] 2022-02-07 09:13
I believe the functionality already exists if you do `/join <address>` in the message composer.
But I do agree with you, Element would most likely benefit from spreading that behaviour in other parts of the product so that it is easier for folks to follow those links

**Comment by Yoric** [comment] 2022-02-07 09:16
Good to know! Not very discoverable, though.

**Comment by t3chguy** [comment] 2022-02-07 09:55
The happy paths here are

1. Receive matrix.to link
2. Click open in Element
3. It opens in your Element Desktop automagically using the `element://` protocol handler

OR

1. Receive a room address (#foobar:server)
2. Enter into the room directory
3. Hit Join

![image](https://user-images.githubusercontent.com/2403652/152765557-bff152b5-7895-41a8-9933-7c2a28749afe.png)

**Comment by Yoric** [comment] 2022-02-07 09:57
I agree that these are the happy paths. I believe that we should strive to make more paths happy :)

**Comment by t3chguy** [comment] 2022-02-07 09:58
Closing as duplicate of https://github.com/vector-im/element-web/issues/15723

**Closed by t3chguy** 2022-02-07 09:58 UTC
Labels: X-Needs-Product, A-Matrix.to, T-Enhancement, O-Uncommon, A-Spotlight-Search
