### ISSUE TITLE
ability to test the input (microphone) in the settings

### ISSUE THREAD

**Issue by youdontneedtoknow22** [vector-im/element-web#22287] opened 2022-05-19 22:24 UTC
#### What would you like to do?

On Discord, you have a feature to test your microphone. It shows if the input is being registered and you have the ability to hear yourself talking

#### Why would you like to do it?

I often need to change my input/microphone, because when using bluetooth headphones the sound is pretty bad when using the built-in microphone (it's a limitation to all bluetooth headphones/earphones), so I tend to use an external microphone or the microphone from my laptop. As you can imagine, this doesn't work flawlessly all the time due to some complications on the earphones side (Handfree-Mode vs Stereo Mode)

#### How would you like to achieve it?

Right there where the user can change input, there should be a way to test it. I'll paste 2 screenshots from element and from discord:
![grafik](https://user-images.githubusercontent.com/85135068/169414232-4fb37ec0-4825-455f-b1c9-fe3e09d6a66d.png)

![grafik](https://user-images.githubusercontent.com/85135068/169414339-28072816-0ede-4050-8847-e22a21497351.png)

**Comment by SimonBrandner** [comment] 2022-05-20 04:16
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/12647

**Closed by SimonBrandner** 2022-05-20 04:16 UTC
Labels: S-Minor, A-User-Settings, A-VoIP, X-Needs-Design, T-Enhancement, O-Occasional
