### ISSUE TITLE
Unread marker shows up on every start

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24070] opened 2022-12-21 09:11 UTC
### Steps to reproduce

1. As user A
2. Create a new encrypted room
3. Invite user B
4. Write a welcome message
5. As user B
6. Join the room
7. Everything is read
8. Switch to another room (so that it is not reopened when starting the app)
9. Restart (App) or reload (Web) Element

#### What did you expect?

No unread marker

#### What happened instead?

Unread marker for the room

Room ID `!UqYQnsoskuppidyBCN:matrix.org`

### Operating system

Ubuntu 22.04.1 LTS

### Application version

Element Nightly version: 2022122001 Olm version: 3.2.12

### How did you install the app?

official deb

### Homeserver

element.ems.host

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2022-12-21 09:17
Also happens on Web on app.element.io and develop.element.io

**Comment by gsouquet** [comment] 2022-12-21 09:24
Duplicate of https://github.com/vector-im/element-web/issues/23685 

We should probably re-triage the other issue

**Closed by gsouquet** 2022-12-21 09:24 UTC
Labels: T-Defect, S-Major, O-Uncommon
