### ISSUE TITLE
WYSIWYG Composer Underline Shortcut Bug

### ISSUE THREAD

**Issue by callumu** [vector-im/element-web#23619] opened 2022-10-26 15:58 UTC
### Steps to reproduce

1. Where are you starting? What can you see? Type text in the composer with no formatting enabled. Mac on Chrome browser.
2. What do you click? Highlight the last part of the text and underline using the shortcut 'command + U'
3. The blinking carat then moves to the start of all the text and none of the text stays highlighted
4. The text that was highlighted does get formatted

#### What did you expect?

I expected the blinking carat to stay in the same location, the highlighted text to remain and the text to become underlined

#### What happened instead?

 The text that was highlighted does get formatted, but the blinking carat moves to the start of all the text and none of the text stays highlighted

### Operating system

macOS

### Browser information

Chrome Version 106.0.5249.119 (Official Build) (arm64)

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by florianduros** [comment] 2023-01-27 09:58
Cannot reproduce, fixed in in a previous release.

**Closed by florianduros** 2023-01-27 09:58 UTC
Labels: T-Defect, S-Minor, O-Occasional, Z-Labs, A-Rich-Text-Editor
