### ISSUE TITLE
The ability to create custom sections in your profile

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#20147] opened 2021-12-11 15:53 UTC
I used Mastodon a while before, and one thing that I noticed while editing my Mastodon profile is that you can do this:
![mastodon](https://user-images.githubusercontent.com/47475676/145682776-226eea81-7dfd-40a9-8341-febb66206993.png)
(doesn't have to be URLs, can be plain text as well)

It would be interesting to add that in Element (but not like Mastodon's, and with support for Markdown), but right now when you're viewing a user's profile, the avatar is big, so it'll need to be smaller

Here's what I have in mind
![user profile mockup](https://user-images.githubusercontent.com/47475676/145682544-af441da3-422f-4ff9-a8f2-b4a4eb4d1cbc.png)

**Comment by SimonBrandner** [comment] 2021-12-11 18:27
This would have to been done through https://github.com/matrix-org/matrix-doc/pull/1769

**Comment by t3chguy** [comment] 2021-12-13 09:44
Duplicate of https://github.com/vector-im/element-web/issues/1401

**Closed by t3chguy** 2021-12-13 09:44 UTC
Labels: A-User-Info, X-Needs-Design, X-Needs-Product, A-Custom-Status, T-Enhancement, X-Spec-Changes, O-Occasional
