### ISSUE TITLE
Leave room in background

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21993] opened 2022-04-29 13:21 UTC
#### What would you like to do?
Leave a room "instantly", no foreground spinner.

#### Why?
I just `/part`ed a room. This brought up a spinner in the foreground for no apparent reason. It should spin in the background instead and thus feel like snappier UX. For now I clicked the spinner away and have no idea whether that made a difference. Other users may not know they can or be scared to.

#### How would you like to achieve it?
Joining rooms can be done in the background for a while now: a spinner appears in the room list, indicating there is background activity.

**Comment by t3chguy** [comment] 2022-04-29 13:28
Duplicate of https://github.com/vector-im/element-web/issues/13911

**Closed by t3chguy** 2022-04-29 13:28 UTC
Labels: T-Enhancement
