### ISSUE TITLE
View Zoom in with STRG + + is not possible on Notebook with QWERTZ-Keyboard without numberpad ( connect to #21067?)

### ISSUE THREAD

**Issue by WHR-07071963** [vector-im/element-web#21199] opened 2022-02-24 14:54 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Normal Element-Desktop in any room.
2. What do you click?
Several times STRG + - to zoom out. As expected, everything is getting smaller.
3. More steps…
Trying to go back with STRG + +. Doesn't work.

#### What did you expect?
Everything is getting bigger again.
#### What happened instead?
Nothing.

#### Work arround
I found 2 ways:
1st: ALT, View, Zoom In. Repeat until size is ok.
2nd: STRG + 0 followed by several STRG + - until size is ok.
(You can also use an external QWERTZ-keyboard with numberpad, using the + on the numberpad.)

### Operating system

Windows 11

### Application version

Element version 1.10.4; Olm version 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.ecker-ecker.de; implementation & version unknown

### Will you send logs?

No

**Comment by HarHarLinks** [comment] 2022-02-24 20:32
#21067

**Comment by t3chguy** [comment] 2022-02-25 08:46
Closing as duplicate of #21067

**Closed by t3chguy** 2022-02-25 08:46 UTC
Labels: T-Defect
