### ISSUE TITLE
After discarding a voice message a restart is required

### ISSUE THREAD

**Issue by kubo6472** [vector-im/element-web#21398] opened 2022-03-11 21:14 UTC
### Steps to reproduce

1. Open a chat
2. Start recording a voice message
3. Discard it while recording

#### What did you expect?
Message gone and I can keep on using the app.
#### What happened instead?
The message box is blacked out, green send button is the only one displayed, says send the voice message, I can't type, the button does nothing, when I switch chats it tries to load the voice message part recorded, to be send again.

### Operating system

Windows 11

### Application version

Element version: 1.10.6 Olm version: 3.2.8

### How did you install the app?

Element.io Website

### Homeserver

Homeserver version: Synapse 1.52.0

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-03-11 23:24
Duplicate of https://github.com/vector-im/element-web/issues/21151, which is fixed in the upcoming version

**Closed by robintown** 2022-03-11 23:24 UTC
Labels: T-Defect
