### ISSUE TITLE
Message previews on room list include HTML entities instead of characters

### ISSUE THREAD

**Issue by KamilBaczkowski** [vector-im/element-web#18724] opened 2021-08-24 13:39 UTC
### Steps to reproduce

1. Enable `Show previews of messages` on a room list
2. Send a message with some special characters (for example `<>`)
3. Instead of the message being shown correctly, some characters will be shown as HTML entities

### What happened?

Characters were rendered as HTML entites

### What did you expect?

Characters should be shown as they were send

### Operating system

Fedora 34

### Browser information

Firefox 91

### URL for webapp

1.7.33

### Have you submitted a rageshake?

No

**Comment by KamilBaczkowski** [comment] 2021-08-24 13:39
Oh, the screenshot didn't upload ![image](https://user-images.githubusercontent.com/41474169/130626832-a4e24e95-196c-476c-aae5-ebfa18556eb6.png)

**Comment by robintown** [comment] 2021-08-24 13:44
Duplicate of https://github.com/vector-im/element-web/issues/17101

**Closed by robintown** 2021-08-24 13:44 UTC
Labels: T-Defect
