### ISSUE TITLE
Thread panel causes old confetti effects to play.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#26592] opened 2023-11-15 19:58 UTC
### Steps to reproduce

1. View a room with the thread panel open
2. As the thread panel populates, any confetti emoji present in old scrollback triggers the effect

#### What did you expect?

Effects only on live new messages

#### What happened instead?

Flakey spurious confetti coming out of bugs in the threads implementation.

### Application version

nightly

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-11-15 22:13
Duplicate of https://github.com/vector-im/element-web/issues/24811

**Closed by t3chguy** 2023-11-15 22:13 UTC
Labels: T-Defect
