### ISSUE TITLE
Timeline wobbles vertically when viewing a new room for the first time as the history loads.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18522] opened 2021-08-13 09:29 UTC
### Steps to reproduce

View a room for the first time since launching the client (particularly an E2EE room, where the effect is either more noticeable because the history loads more slowly, or perhaps it only effects E2EE rooms).

### What happened?

Watch the timeline carefully as the history is displayed on the room; notice that some messages sometimes 'dance' or 'wobble' up and down by 1px (or perhaps 0.5px?) as the history is added higher up the page, e.g. Anoa's one here.  This is a regression in the last week or so, and makes things literally look wobbly and flakey.

https://user-images.githubusercontent.com/1294269/129336575-33527256-e916-4f47-9aab-684d884ae9cc.mov

### What did you expect?

The timeline should be rock solid as the history backfills.  It's acceptable (but not desirable) for replies and URL previews and media thumbnails to push events *upwards* if they load below them in the timeline (but ideally we should be reserving the right vertical space in the timeline for these things).  But it's not acceptable for things loading *above* the content to make the content wobble around.

### Operating system

macOS 10.15.7

### Application version

nightly 2021-08-12

### How did you install the app?

nightly

**Comment by Palid** [comment] 2021-09-02 19:34
Spent 15min or so scrolling and couldn't reproduce it anymore. Tried with new room and CPU slowdown, neither helped. Hopefully it got accidentally fixed with something.
@ara4n can you let me know if it still reproduces for you? Tested on develop.

**Comment by novocaine** [comment] 2021-10-01 10:11
Closing as no recent report.

**Closed by novocaine** 2021-10-01 10:11 UTC
Labels: T-Defect, X-Needs-Info, X-Regression, S-Minor, A-Timeline, O-Frequent
