### ISSUE TITLE
Ability to (un)mute all rooms of a space at once

### ISSUE THREAD

**Issue by JocelynDelalande** [vector-im/element-web#26358] opened 2023-10-12 07:39 UTC
#### What would you like to do?

Being able to « mute » a space notifications.

#### Why would you like to do it?

Better focus : if I work today for that organization, I may want not to be distracted by the channels of that other organization I work for on the week-end.

#### How would you like to achieve it?

Have a notification settings on spaces list as it exists for rooms to disable notification for everything contained in the space. I suppose it is not that simple, but that would be a very valuable feature, kind with the attention of users with multi-spaces.

### Have you considered any alternatives?

Using several accounts, and several clients.

**Comment by t3chguy** [comment] 2023-10-12 07:40
Duplicate of https://github.com/vector-im/element-meta/issues/88

**Closed by t3chguy** 2023-10-12 07:40 UTC
Labels: T-Enhancement

**Comment by JocelynDelalande** [comment] 2023-10-12 07:41
@t3chguy oh sorry, haven't found it during my initial search.

PS: How fast you are !
