### ISSUE TITLE
Elements seemingly randomly increase sharpness

### ISSUE THREAD

**Issue by zeirio** [vector-im/element-web#22518] opened 2022-06-10 12:21 UTC
### Steps to reproduce

The issue occurs in every room I've been in, does not have to have a media item it in but that's when I notice it often. The effect looks like someone is turning up the sharpness on the entire app and looks like the effect in this video: https://www.youtube.com/watch?v=sWNnkuY4tKE

Another example: 
![messed up](https://user-images.githubusercontent.com/30398485/173062753-fa22d4f6-9e51-4a25-9166-cdad31d35c9e.png)

It usually occurs after I start or stop hovering over some UI element with shading like a text message or a room. I've tried reinstalling Nvidia drivers and changing other settings in windows/element which could possibly be related but to no avail.

### Outcome

I expected the elements I hover over to be displayed with a little shadow or outline, but it's causing this effect in addition to it.

### Operating system

Windows 10 x64

### Application version

Element version: 1.10.14 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.kjbbird.com

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-06-10 12:26
How is this different to your other issue? https://github.com/vector-im/element-web/issues/22439

**Comment by zeirio** [comment] 2022-06-10 12:35
It's not, I got an email asking me to submit a ticket and logs. I can
delete the thread if that's not needed.

Brad

**Comment by t3chguy** [comment] 2022-06-10 12:36
Duplicate of https://github.com/vector-im/element-web/issues/22439

**Closed by t3chguy** 2022-06-10 12:36 UTC
Labels: T-Defect
