### ISSUE TITLE
Initiating user verification in a Direct Chat starts a new Direct Chat

### ISSUE THREAD

**Issue by strypey** [vector-im/element-web#13707] opened 2020-05-19 06:11 UTC
### Description

I have a Direct Chat with another user. We are both using Riot-web on Firefox variants, on GNU/Linux. We are trying to verify each other using an out-of-band channel. But when the other user initiates verification, it comes up in my UI as an invite to a new chat. When I accepted that invite, it did initiate the verification, but now I have two DMs with the same person.

### Steps to reproduce

- Create new Direct Chat with one other user.
- Have one user initiate user verification.
- Observe that an invite to a new chat has appeared in the other user's UI
- Accept the invite
- Observe that the verification process then proceeds in the new chat

Describe how what happens differs from what you expected.

I expected to see a message appear on the same Direct Chat, asking me I want to continue verifying the other user.

### Version information

- **Platform**: web (in-browser)

For the web app:

On my system:
- **Browser**: Firefox 76.0.1 (Abrowser variant, 32-bit)
- **OS**: Trisquel 8 Flidas GNU/Linux (32-bit)
- **URL**: https://chat.feneas.org/ , riot-web version: 1.6.0, olm version: 3.1.3

On the other user's system:
- **Browser**: Firefox ?
- **OS**: NixOS GNU/Linux ?
- **URL**: ?

### Further context

EDIT: I just remembered (because it's happening again) that in the cases I experienced the bug in, I couldn't turn encryption on in Riot-web from my end, I have to ask the other user to turn it on. The slider for turning encryption on doesn't seem to do anything. 

Obviously, these are all legacy DCs from before encryption was turned on by default for private chats. Could it be anything to do with the fact that I've invited my new account into all the affected chats, then had the original account leave the room, then tagged it as a Direct Chat?

FWIW a slider probably isn't the right UI element for a feature that can only be turned on, not off.

**Comment by t3chguy** [comment] 2020-05-19 08:50
This would be a case of the room not being correctly associated as a DM with that other user which would be solved by Canonical DMs.

**Comment by strypey** [comment] 2020-05-22 11:48
I just remembered (because it's happening again) that in the cases I experienced the bug in, I couldn't turn encryption on in Riot-web from my end, I have to ask the other user to turn it on. The slider for turning encryption on doesn't seem to do anything. Could it be anything to do with the fact that I've invited a new account into all the affected chats, then had the original account leave the room, then tagged it as a Direct Chat?

FWIW a slider probably isn't the right UI element for a feature that can only be turned on, not off.

**Comment by t3chguy** [comment] 2020-05-24 18:46
> Could it be anything to do with the fact that I've invited a new account into all the affected chats

Yup that would confuse the DM-with-user marking for sure.
It wouldn't cause the inability to enable encryption though.

**Comment by strypey** [comment] 2020-06-01 02:54
Obviously this aspect of the bug is only going to affect Riot early adopters who already had DCs going, before you turned on encryption-by-default in private chats. But depending on the cause it could also cause problems down the line for:
* chat that start as public rooms but decide to become invite-only and turn on encryption
* legacy DCs between a user on Riot and a user on another client, after that client ships E2EE and cross-signing support, and the users want to turn encryption on.

**Comment by turt2live** [comment] 2020-09-01 13:32
Duplicate of https://github.com/vector-im/element-web/issues/13647

**Closed by turt2live** 2020-09-01 13:32 UTC
Labels: bug

**Comment by strypey** [comment] 2020-09-17 03:30
@turt2live it is indeed a duplicate, thanks for noticing and marking it as such. However, it would be great if you could pass on this feedback to your UX team:

A slider probably isn't the right UI element for a feature that can only be turned on, not off. I suggest replacing the slider for turning on encryption with a simple button that, once clicked, changes into static text that says encryption is on. Obviously this will only be relevant to rooms where encryption is still optional.
