### ISSUE TITLE
Messages appear as encrypted even though they were already decrypted

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17703] opened 2021-06-19 12:30 UTC
![Screenshot_20210619_142729](https://user-images.githubusercontent.com/25768714/122642491-ed892b80-d10a-11eb-827d-414c5c91d58a.png)

Once, I switch off that room and switch back into it the messages are displayed correctly. The events are being decrypted in the background but the timeline doesn't get updated

**Comment by SimonBrandner** [comment] 2021-06-19 14:28
![Screenshot_20210619_162815](https://user-images.githubusercontent.com/25768714/122645591-5b3d5380-d11b-11eb-97d5-85efe499cfdb.png)

The `clearEvent` somehow doesn't get set :thinking:

**Comment by t3chguy** [comment] 2021-06-19 14:59
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/6196 / https://github.com/matrix-org/matrix-js-sdk/pull/1738

**Comment by jryans** [comment] 2021-06-19 17:08
A related symptom is the decrypted event source seems to simply be empty for all encrypted events:

![image](https://user-images.githubusercontent.com/279572/122650170-45cf2600-d129-11eb-82ec-6c23c326fc6a.png)

(If I should file that separately, let me know.)

**Comment by SimonBrandner** [comment] 2021-06-19 17:08
I am pretty sure this is the same bug

**Comment by t3chguy** [comment] 2021-06-19 18:21
That is a separate issue, caused by my typescriptifications and ViewSource relying on an underscored field

**Comment by t3chguy** [comment] 2021-06-19 19:17
[`a2a5158` (#6215)](https://github.com/matrix-org/matrix-react-sdk/pull/6215/commits/a2a515841138a3c545b6a44477df3e9ef3992b93) covers the view source issue

**Comment by turt2live** [comment] 2021-06-19 19:45
immediate issue fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6196 - leaving open for further investigation.

**Comment by turt2live** [comment] 2021-07-22 21:58
Closing this issue as it's not actually an issue in current releases, but if we ever do re-launch the problematic feature then it'll become an issue again. I've tracked this awkward state here: https://github.com/vector-im/element-web/issues/18193

**Closed by turt2live** 2021-07-22 21:58 UTC
Labels: A-E2EE, P1, S-Major, T-Defect, X-Regression
