### ISSUE TITLE
Assorted E2E errors in #megolm

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#4592] opened 2017-07-17 13:07 UTC
UTD and some messages from users on matrix.org were decryptable and others not.

**Comment by aaronraimist** [comment] 2020-01-05 01:31
This issue is probably not actionable anymore

**Comment by turt2live** [comment] 2020-01-05 01:35
UISIs are being investigated still, so there's hope.

**Comment by aaronraimist** [comment] 2020-01-05 01:40
Sure but this issue doesn't have any details or rageshakes right?

**Comment by turt2live** [comment] 2020-01-05 02:20
it has rageshakes with more details.

**Comment by turt2live** [comment] 2022-06-14 05:25
Duplicate of https://github.com/vector-im/element-web/issues/2996

**Closed by turt2live** 2022-06-14 05:25 UTC
Labels: T-Defect, P2, S-Major, A-E2EE, Z-Rageshake
