### ISSUE TITLE
Fails to join rooms in apothecary.club

### ISSUE THREAD

**Issue by controlpl4n3** [vector-im/element-web#24057] opened 2022-12-19 17:13 UTC
### Steps to reproduce

Viewing the Apothecary Community Space, list of rooms.
2. Join a room, eg "Calls"
3.Receive the error modal (attached)
![element_bug](https://user-images.githubusercontent.com/58838288/208481408-f0bbc850-b38e-4754-9e58-f7b8c0a3535f.png)

#### What did you expect?
I expected to Join the room

#### What happened instead?
I got an error message (screenie attached)

### Operating system

MacOS 12.6.1

### Application version

Version 1.11.16 (1.11.16)

### How did you install the app?

https://element.io/get-started /usr/local/Caskroom/element/1.10.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-12-19 17:33
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-12-19 17:33 UTC
Labels: T-Defect
