### ISSUE TITLE
System tray icon not functioning

### ISSUE THREAD

**Issue by jahway603** [vector-im/element-web#22741] opened 2022-07-05 19:59 UTC
### Steps to reproduce

1. Open Element Desktop client.
2. Go into Settings -> Preferences.
3. Toggle on and off and on "Show tray icon and minimise window to it on close"
4. System tray icon for the Element client does not appear as it has on other different Linux distros.

#### What did you expect?
I expected that the System tray icon would appear.

#### What happened instead?
No System tray icon appeared.

### Operating system

Artix Linux

### Application version

Element version: 1.10.15, Olm version: 3.2.8

### How did you install the app?

from OS package manager

### Homeserver

N/A as this is a client issue

### Will you send logs?

No

**Comment by AffSeda** [comment] 2022-12-23 17:39
This has also happened to me on Debian with the latest Element update. The tray icon doesn't appear, although closing the client window does hide it entirely it is still running.

My version was installed via the official apt repository.

**Comment by jahway603** [comment] 2022-12-28 17:24
@AffSeda Interesting that this issue I'm having is happening for you on Debian, which is a much more common Linux distro.

**Comment by t3chguy** [comment] 2023-01-03 11:27
Duplicate of https://github.com/vector-im/element-web/issues/23993

**Closed by t3chguy** 2023-01-03 11:27 UTC
Labels: T-Defect, Z-Platform-Specific, S-Major, A-Electron, A-Tray-Icon, O-Uncommon, X-Community-Supported-Platform
