### ISSUE TITLE
Missing session data - "low on disk space"

### ISSUE THREAD

**Issue by dzil123** [vector-im/element-web#23742] opened 2022-11-09 22:10 UTC
### Steps to reproduce

1. Open Element Web

#### What did you expect?

I was previously signed in. I closed the browser and reopened it, and navigated to Element. I expected to open the app like I had before.

#### What happened instead?

I was shown this fullscreen message and I was signed out. I am not low on disk space.

> 
> Missing session data
> Some session data, including encrypted message keys, is missing. Sign out and sign in to fix this, restoring keys from backup.
> 
> Your browser likely removed this data when running low on disk space. To help us prevent this in future, please send us logs.
> 

### Operating system

Arch Linux

### Browser information

Chromium Version 107.0.5304.87

### URL for webapp

chat.fairydust.space

### Application version

Element version: 1.11.14, Olm version: 3.2.12

### Homeserver

matrix.fairydust.space, Synapse 1.71.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-11-10 09:25
Duplicate of https://github.com/vector-im/element-web/issues/23123

**Closed by t3chguy** 2022-11-10 09:25 UTC
Labels: T-Defect, S-Major, A-Storage, O-Uncommon
