### ISSUE TITLE
Error joining Room within a Space

### ISSUE THREAD

**Issue by ProactiveServices** [vector-im/element-web#23044] opened 2022-08-09 22:44 UTC
### Steps to reproduce

1. Clicked on to the Libre Gaming Space
2. Clicked to join the "Games" Room

#### What did you expect?
To join the Room

#### What happened instead?
Element threw the "Something went wrong!" page, asking to submit an issue.

### Operating system

Ubuntu 20.04.4

### Application version

Element 1.11.2

### How did you install the app?

https://packages.riot.im/debian apt repo

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ProactiveServices** [comment] 2022-08-09 22:47
After clicking the "Clear cache and reload" button in the error window, it appears that the join succeeded.

**Comment by ProactiveServices** [comment] 2022-08-09 22:52
This seems to be reproducible; from the Opensource_gaming Space I clicked to join the General Room and encountered the error. Before clicking the "Clear cache and reload" I checked on my Android mobile and saw that I had been joined.

**Comment by t3chguy** [comment] 2022-08-10 06:26
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-08-10 06:26 UTC
Labels: T-Defect
