### ISSUE TITLE
Translate Smileys

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#24837] opened 2023-03-15 22:07 UTC
#### What would you like to do?
I want to be able to choose a smiley in my language.
![grafik](https://user-images.githubusercontent.com/30293477/225454250-c078b1f7-1f43-4340-bff4-3cb4ecc4bec9.png)

#### Why would you like to do it?
It makes Element beginner friendly

#### How would you like to achieve it?
Solution One:
The Smileys get translated

Solution Two:
Perhaps it's possible to tag a smiley with more tags?

**Comment by weeman1337** [comment] 2023-03-16 06:25
Duplicate of https://github.com/vector-im/element-web/issues/11013

**Comment by weeman1337** [comment] 2023-03-16 06:25
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Closed by weeman1337** 2023-03-16 06:25 UTC
Labels: T-Enhancement
