### ISSUE TITLE
Export/import keys result desynched room sessions

### ISSUE THREAD

**Issue by grinapo** [vector-im/element-web#8944] opened 2019-02-25 21:12 UTC
### Description

The room is encrypted. There is client1 which sits there continuously. 
Client2 was there in the past but not recently, and reading the room (refreshing) there shows all messages unable to decrypt. 
So I try what happens if I export keys from client1 and import into clien2?
The result: client2 can read all messages now. 
However client2's messages can't be decrypted by client1, and vice versa.
Client2 leave/rejoin room doesn't change the state.

Log: will be sent (two), requested by @uhoreg .

### Version information
- **Platform**: web (in-browser) or desktop?
Riot web, 1.0.1, [client1 is self hosted, client2 is on riot.im]

For the web app:
- **Browser**: Chrome, Safari, Firefox? which version? 
Chromium latest, Firefox nightly

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Debian/sid

**Comment by lampholder** [comment] 2019-02-27 14:47
This sounds complicated to unpick :S 

A few questions:
- are both clients logged in as the same user?
- is either client configured not to encrypt messages for unverified devices?
- has client 1 verified client 2?
- has client 2 verified client 1?

**Comment by grinapo** [comment] 2019-02-27 15:41
Especially since riot.im was rejecting to send the debug logs.... anyway:
1. no, one is grin:matrix.org and the other is grin:grin.hu
2. no
3. yes
4. yes

**Comment by duxovni** [comment] 2021-11-30 07:34
If I understand correctly, this is about exporting keys from an Element session, and importing them to another Element session logged in as an entirely different user, which doesn't seem like it should be a supported operation to begin with? I may be confused though. If this is in fact something we shouldn't support, then it may still be worth testing to see whether the UI could do a better job warning users when they attempt to do it.

**Comment by uhoreg** [comment] 2021-11-30 13:48
Yes, importing keys from another user isn't something that should necessarily be supported, but on the other hand, it shouldn't make a difference whether you import from another user or the same user, since the export only contains megolm keys.  So this issue, if it still exists, should also affect imports from the same user.

**Comment by kittykat** [comment] 2021-12-20 12:43
I'm going to close this issue for now as we couldn't reproduce it during the community resting session. If you can still reproduce it, please commend with @kittykat and I will re-open it :+1:

**Closed by kittykat** 2021-12-20 12:43 UTC
Labels: T-Defect, X-Needs-Info, A-E2EE, X-Needs-Community-Testing
