### ISSUE TITLE
Thread not in thread panel list

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24334] opened 2023-01-26 08:01 UTC
### Steps to reproduce

1. Have some threads
2. Open threads panel

#### What did you expect?

All threads in the list

#### What happened instead?

Thread is missing

![image](https://user-images.githubusercontent.com/6216686/214785068-7e384bf2-31a4-4694-93fd-6265e1b0faff.png)

### Operating system

Ubuntu 22.04 LTS

### Application version

Element Nightly version: 2023012501 Olm version: 3.2.12

### How did you install the app?

https://packages.element.io/debian/

### Homeserver

element.ems.host

### Will you send logs?

Yes

**Comment by gsouquet** [comment] 2023-01-31 18:03
Two potential issues unearthed from the rageshakes

```
2023-01-25T11:57:54.516Z E /sync error %s Server returned 502 error
Error: Server returned 502 error
    at parseErrorResponse (vector://vector/webapp/bundles/7e76e6596b4a093d681d/init.js:83836:10)
    at MatrixHttpApi.requestOtherUrl (vector://vector/webapp/bundles/7e76e6596b4a093d681d/init.js:136347:86)
```

```
2023-01-26T07:27:46.391Z E Failed to parse permalink Unknown entity type in permalink
Error: Unknown entity type in permalink
    at MatrixSchemePermalinkConstructor_MatrixSchemePermalinkConstructor.parsePermalink (vector://vector/webapp/bundles/6c88b737e720524ad4b9/init.js:25852:13)
    at parsePermalink (vector://vector/webapp/bundles/6c88b737e720524ad4b9/init.js:26236:86)
    at tryTransformEntityToPermalink (vector://vector/webapp/bundles/6c88b737e720524ad4b9/init.js:26143:30)
    at formatHref (vector://vector/webapp/bundles/6c88b737e720524ad4b9/init.js:77109:124)
    at Options.get (vector://vector/webapp/bundles/6c88b737e720524ad4b9/vendors~init.js:31169:16)
    at Token.toFormattedHref (vector://vector/webapp/bundles/6c88b737e720524ad4b9/vendors~init.js:31285:20)
    at Token.render (vector://vector/webapp/bundles/6c88b737e720524ad4b9/vendors~init.js:31359:21)
    at Options.render (vector://vector/webapp/bundles/6c88b737e720524ad4b9/vendors~init.js:31200:20)
    at tokensToNodes (vector://vector/webapp/bundles/6c88b737e720524ad4b9/vendors~init.js:88529:27)
    at linkifyElementHelper (vector://vector/webapp/bundles/6c88b737e720524ad4b9/vendors~init.js:88578:19)
```

@justjanne any idea on why this might be happening?

**Comment by justjanne** [comment] 2023-01-31 18:16
Sorry, those stacktraces really don't mean anything to me :(

I'll have to take a look at that tomorrow :/

**Comment by t3chguy** [comment] 2023-07-19 09:33
Had anyone seen this since Jan?

**Comment by t3chguy** [comment] 2023-08-14 12:02
Closing due to no reproductions in a long time

**Closed by t3chguy** 2023-08-14 12:02 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, O-Uncommon, A-Threads
