### ISSUE TITLE
Attaching media with text

### ISSUE THREAD

**Issue by nonl4331** [vector-im/element-web#20173] opened 2021-12-14 08:36 UTC
#### What would you like to do?
When sending media it is common to want to be able to send text alongside the media typically this text is before the media. Currently to do this in element (element-desktop at least) you need to first then text then separately send the media.

Being able to send text alongside media would be an enhancement.  

#### Why would you like to do it?
This would increase the general quality of life for the program as users coming from other messaging applications such as Discord might expect this feature, here is a picture of this feature in discord: 
![image](https://user-images.githubusercontent.com/25993108/145960745-21cf7841-4514-4783-adb5-9ea57a71ddfa.png)

#### How would you like to achieve it?
Here are some possible options:
 - Attach a textbox above the upload button in this picture: 
![image](https://user-images.githubusercontent.com/25993108/145961074-51e6fcf6-0346-4fcb-910e-e90c7d0c3083.png)
 - Have the media attached to the already existing textbook similar to how is demonstrated in the first picture)

### Have you considered any alternatives?

I have not.

**Comment by t3chguy** [comment] 2021-12-14 09:05
Duplicate of https://github.com/vector-im/element-web/issues/1818

**Closed by t3chguy** 2021-12-14 09:05 UTC
Labels: T-Enhancement
