### ISSUE TITLE
Element Desktop Major slowdown post 30-40 minutes of runtime after latest update.

### ISSUE THREAD

**Issue by h3ll0-w00rld** [vector-im/element-web#21829] opened 2022-04-16 17:40 UTC
### Steps to reproduce

Launching the app, waiting / using it for 30-40 minutes

### Outcome

Major slowdown, hogging the CPU (from what HTOP tells me) [Freaking Electron]
![image](https://user-images.githubusercontent.com/96695457/163685596-4b32bea3-debc-4e60-a6c4-3e1454933b42.png)

### Operating system

Arch Linux (Endreavour OS)

### Application version

Element version: 1.10.10 Olm version: 3.2.8

### How did you install the app?

VIA AUR

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-04-17 04:06
Duplicate of https://github.com/vector-im/element-web/issues/21793

**Closed by robintown** 2022-04-17 04:06 UTC
Labels: T-Defect
