### ISSUE TITLE
Cache in service worker for offline experience 

### ISSUE THREAD

**Issue by HKalbasi** [vector-im/element-web#18147] opened 2021-07-21 14:11 UTC
Currently there is just an empty service worker. It seems there was a functional service worker, but it is removed in https://github.com/vector-im/element-web/commit/cfee4c925a43a5792ac5854235e0410fa9cea060#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166f and reverted. Why? It is useful for faster initial times and better experience for network problems.

**Comment by t3chguy** [comment] 2021-07-21 14:19
https://github.com/vector-im/element-web/pull/15352

> Due to how we handle updates and versioning it became quite problematic, the solution will need more experimentation.

It was causing updates to not happen due to it disagreeing that an update was needed, given how we have our version just in a loose text file, I think it'd need to be embedded into the code for this to work better.

**Comment by HKalbasi** [comment] 2021-07-21 16:42
So just change the handler to `StaleWhileRevalidate`?

Or better, `CacheFirst` for assets that have content hash in their names, and `StaleWhileRevalidate` for others?

**Comment by t3chguy** [comment] 2021-07-21 16:47
StaleWhileRevalidate didn't work for the automatic update prompt that came up in the app and workbox offered no sane way to override it. We either have to work the update prompt around the service worker or vice versa, out of the box neither likes the other

**Comment by HKalbasi** [comment] 2021-07-21 22:51
Aha, so a hand written service worker is the way to go? Or workbox without webpack plugin? Or making changes in versioning system?

**Comment by t3chguy** [comment] 2021-07-22 08:22
One of the above, I'd kinda prefer using a solid approach like workbox and improving our versioning/update mechanism given it is very naive and basic atm (just watches a `/version` file for changes, in theory if an update happens as you are loading the page atm your app will fetch the wrong (newer) version file and thus be confused and miss an update)

**Comment by t3chguy** [comment] 2023-05-16 08:19
Duplicate of https://github.com/vector-im/element-web/issues/7984

**Closed by t3chguy** 2023-05-16 08:19 UTC
Labels: T-Enhancement
