### ISSUE TITLE
Composer doesn't allow to send message ("DOMException: The quota has been exceeded.")

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#20422] opened 2022-01-06 14:59 UTC
## What's wrong?
I'm replying to a message
The message doesn't send by pressing the Enter key or the send button of the composer.
The UI doesn't give any feedback about the error so I opened the JavaScript console.

![Screenshot 2022-01-06 at 15-58-07 Element Bridge Crew](https://user-images.githubusercontent.com/10872136/148402667-96d6468e-6a54-4896-b10d-ff332bf823e0.png)

```
sendEvent of type m.room.message in **room id redacted by me** with txnId m1641480767412.93 rageshake.ts:60:15
Uncaught (in promise) DOMException: The quota has been exceeded. vendors~init.js:2
    sendMessage SendMessageComposer.tsx:522
    i MessageComposer.tsx:522
    React 11
    bind_applyFunctionN self-hosted:1376
    Xt self-hosted:1339
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    bind_applyFunctionN self-hosted:1376
    $t self-hosted:1339
```

## Client & server
* Homeserver: vector.modular.im
* staging.element.io
```
Element version: 1.9.8
Olm version: 3.2.8
```

**Comment by novocaine** [comment] 2022-01-11 09:41
This is an error writing to storage - either storage is full, or there's some other issue. 

Is this for Element desktop, or web?

**Comment by t3chguy** [comment] 2022-01-11 14:39
Duplicate of https://github.com/vector-im/element-web/issues/18423

**Closed by t3chguy** 2022-01-11 14:39 UTC
Labels: T-Defect, S-Critical, A-Storage, A-Composer, O-Uncommon
