### ISSUE TITLE
WebRTC error displays as "Unable to access microphone'

### ISSUE THREAD

**Issue by DogeyStamp** [vector-im/element-web#22314] opened 2022-05-23 00:33 UTC
### Steps to reproduce

1. I have a Coturn setup on my homeserver using this configuration:
```
use-auth-secret
static-auth-secret={{ coturn_secret_key }}

realm={{ domain }}
server-name=turnserver

log-file=/var/log/coturn.log
verbose
fingerprint
simple-log

# Security
no-tcp-relay

# Deny private IPs
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255

no-multicast-peers
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.0.2.0-192.0.2.255
denied-peer-ip=192.88.99.0-192.88.99.255
denied-peer-ip=198.18.0.0-198.19.255.255
denied-peer-ip=198.51.100.0-198.51.100.255
denied-peer-ip=203.0.113.0-203.0.113.255
denied-peer-ip=240.0.0.0-255.255.255.255

# Allow localhost
allowed-peer-ip={{ local_ip }}

user-quota=12
total-quota=1200

# TLS
cert=/etc/ssl-acme/certs/fullchain_{{ domain }}.crt
pkey=/etc/ssl-acme/keys/{{ domain }}.key

# External IP address
external-ip={{ public_ip }}

listening-ip={{ local_ip }}
listening-port=3478
min-port=49152
max-port=65535
```
2. Relevant homeserver configuration lines:
```
turn_uris: [ "turn:{{ domain }}/?transport=udp", "turn:{{ domain }}/?transport=tcp" ]
turn_shared_secret: {{ coturn_secret_key }}
turn_user_lifetime: 1h
turn_allow_guests: true
```
3. Try to call a user on matrix.org on Element Desktop (from an account on my homeserver)

#### What did you expect?

A proper error message saying my WebRTC isn't configured correctly.

#### What happened instead?

This error shows suggesting an audio issue:
![image](https://user-images.githubusercontent.com/61116261/169723243-e6c9584a-476d-4e8e-9f89-11060a65685e.png)

In devtools:
![image](https://user-images.githubusercontent.com/61116261/169723258-2decb9a0-d206-4fbd-b522-6d00c40a3310.png)
Failed to construct 'RTCPeerConnection': ICE server parse failed

EDIT: The error is caused by an extra slash in turn_uris

### Operating system

Gentoo Linux

### Application version

Element version: 1.10.11 Olm version: 3.2.8

### How did you install the app?

net-im/element-desktop-bin package from Gentoo

### Homeserver

Synapse 1.57.0-1

### Will you send logs?

No

**Comment by robintown** [comment] 2022-05-23 01:39
Duplicate of https://github.com/vector-im/element-web/issues/21804

**Closed by robintown** 2022-05-23 01:39 UTC
Labels: T-Defect
