### ISSUE TITLE
Custom font gets reset when the system color scheme (dark/light) is changed, until the tab is reloaded

### ISSUE THREAD

**Issue by intelfx** [vector-im/element-web#26246] opened 2023-09-27 10:59 UTC
### Steps to reproduce

1. Set up a custom "system font" in Preferences → Appearance → Show advanced → Use a system font
2. Switch to a different tab
3. Change the system color scheme (dark ↔ light)
4. Return to the Element tab

#### What did you expect?

Expected result: selected custom font continues to be used.

#### What happened instead?

Actual result: Element uses its default font.

### Operating system

Arch Linux

### Browser information

Firefox 116.0.3

### URL for webapp

develop.element.io

### Application version

Element version: 1707ecd8b620-react-2cfdf2ced99e-js-74193ad05734 Olm version: 3.2.14

### Homeserver

Synapse 1.92.1

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-09-27 11:00
Related https://github.com/vector-im/element-desktop/issues/1091

**Comment by intelfx** [comment] 2023-09-27 11:13
@t3chguy Right! Thanks for the link, I see the precise trigger now. I have my system set up to change the global color scheme according to the time of day. Once this happens, the custom font is reset until the tab is reloaded.

**Comment by t3chguy** [comment] 2023-09-27 11:16
Duplicate of https://github.com/vector-im/element-web/issues/26248

**Closed by t3chguy** 2023-09-27 11:16 UTC
Labels: T-Defect
