### ISSUE TITLE
if you hit the up key in the composer while scrolled up, it no longer scrolls to show you the edit box

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#19946] opened 2021-11-29 22:31 UTC

**Comment by ShadowJonathan** [comment] 2021-11-29 23:18
Dup of https://github.com/vector-im/element-web/issues/19908?

**Comment by t3chguy** [comment] 2021-11-29 23:43
Duplicate of https://github.com/vector-im/element-web/issues/16402

**Closed by t3chguy** 2021-11-29 23:43 UTC
