### ISSUE TITLE
Forget Room doesn't work

### ISSUE THREAD

**Issue by dadaphl** [vector-im/element-web#16136] opened 2021-01-13 15:39 UTC
### Description

Click on Historical -> Room Option -> "Forget Room" link doesn't do anything. Room is still in the list.

### Steps to reproduce

see description

# Describe how what happens differs from what you expected.

Room should be immediately forgotten and all traces deleted from the system.

### Version information
For the desktop app:
Linux Manjaro
Element version: 1.7.16
olm version: 3.2.1

**Comment by SimonBrandner** [comment] 2021-01-13 15:40
@dadaphl I think there is a bug. You need to restart Element

**Comment by SimonBrandner** [comment] 2021-01-13 15:41
Duplicate of [#15559](https://github.com/vector-im/element-web/issues/15559)

**Closed** 2021-01-13 15:42 UTC
Labels: bug
