### ISSUE TITLE
Option to switch between audio, video and screen sharing

### ISSUE THREAD

**Issue by LendoK** [vector-im/element-web#18021] opened 2021-07-16 13:49 UTC
#### Is your suggestion related to a problem? Please describe.
There seems to be no way to switch to video call, or screen sharing when you already in a audio call.
Also it is not possible to stop/pause screen sharing without stopping the complete call, the camera toggle has no effect while screen sharing. 

#### Describe the solution you'd like.
Only one button for starting a call. After starting a call - a confirmation prompt with options for microphone mute, video or screen sharing or audio only. This confirmation prompt should also appear when accepting a call -> #17152.
The options for the video source should also be available during any call, to seamlessly switch between audio only, video or screen sharing.

#### Describe alternatives you've considered.
At least the camera toggle button should be able to deactivate the screen sharing.

**Comment by SimonBrandner** [comment] 2021-07-16 16:28
Duplicate of https://github.com/vector-im/element-web/issues/12646 and https://github.com/vector-im/element-web/issues/12652. Where the latter is being worked on at https://github.com/matrix-org/matrix-react-sdk/pull/5992

**Closed by SimonBrandner** 2021-07-16 16:28 UTC
Labels: T-Enhancement
