### ISSUE TITLE
Element keeps reverting to system font on Windows

### ISSUE THREAD

**Issue by ajkessel** [vector-im/element-web#26720] opened 2023-12-10 16:36 UTC
### Steps to reproduce

Element version: 1.11.51
Crypto version: Olm 3.2.15

Go to All Settings-->Appearance-->Show Advanced-->Use Bundled Emoji Font

Even when checkbox is checked, I'm seeing the system emoji font.

If I uncheck and re-check the box, it goes back to the bundled font.

Next time I restart Element, same issue -- even with "bundled emoji font" checked, I'm seeing the system emoji font until I re-check the setting.

### Outcome

Should show the selected font

Instead it always shows the system font until the setting is re-checked

### Operating system

Windows 10 22H2 (19045.3758)

### Browser information

N/A - standalone app

### Application version

Element version: 1.11.51 Crypto version: Olm 3.2.15

### Homeserver

Synapse 1.97.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-12-11 08:39
Duplicate of https://github.com/vector-im/element-web/issues/26248

**Closed by t3chguy** 2023-12-11 08:39 UTC
Labels: T-Defect
