### ISSUE TITLE
Filter out flood of hidden events when we detect the scrollback is full of it

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#22080] opened 2022-05-05 08:47 UTC
#### What would you like to do?
Element Web doesn't handle Location streams well if there are no non-hidden events filling the vertical timeline.

I have a room in which I often leave my location stream bot running for hours at a 2 second interval. When I come back it has 3000+ hidden location events that bring Element Web to its knees. Element keeps requesting more events from the homeserver until the vertical browser view is filled with visible events. Usually this means that roughtly 30 events have to be loaded, but when there are 1000s of hidden events in the room's history it takes a very long time until the room is usable and it might fill up the RAM or cause you to get ratelimited.

Join at your own risk: [Geo Tracker: Test room](https://staging.element.io/!CkaXdsNbtUPNOwmwuB:iot-staging.ems.host)

This is similar to vector-im/element-meta#491 but with regular events that Element decides to hide.

#### Why would you like to do it?
If Element detects that the room history is full of hidden events, e.g. [`m.beacon`](https://github.com/matrix-org/matrix-spec-proposals/pull/3489), it may decide to not request these from the home`server.

#### How would you like to achieve it?
Can Element ask to exclude certain events types when asking for more messages?

### Have you considered any alternatives?

`m.beacon` events could become an "edit" their previous event.

**Comment by andybalaam** [comment] 2022-05-05 09:02
I would argue this is a defect: "when someone has been sharing live location, Element Web freezes". Do you agree @jaller94 ?

**Comment by t3chguy** [comment] 2022-05-06 15:36
Duplicate of https://github.com/vector-im/element-web/issues/21789

**Closed by t3chguy** 2022-05-06 15:36 UTC
Labels: T-Defect, S-Major, O-Uncommon, Z-Labs, A-Location-Sharing
