### ISSUE TITLE
Room leave progress indicator shouldn't be modal

### ISSUE THREAD

**Issue by lheckemann** [vector-im/element-web#21768] opened 2022-04-13 07:45 UTC
### Steps to reproduce

1. Leave a room.

#### What did you expect?

The room to disappear from my list, and to be able to continue using the app as normal.

#### What happened instead?

A modal spinner appeared, blocking any further interaction until the leave request was complete(?).

### Operating system

Linux

### Browser information

Firefox 98.0.2

### URL for webapp

app.element.io

### Application version

Element version: 1.10.9 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-04-13 08:44
Duplicate of https://github.com/vector-im/element-web/issues/6405

**Closed by t3chguy** 2022-04-13 08:44 UTC
Labels: T-Defect
