### ISSUE TITLE
Matrix links open browser instead of navigating in Element desktop.

### ISSUE THREAD

**Issue by jedahan** [vector-im/element-web#24994] opened 2023-03-30 16:50 UTC
### Steps to reproduce

Click on any link like [#element-ios:matrix.org](https://matrix.to/#/#element-ios:matrix.org) and it opens a browser tab, then must click 'continue' to open in the desktop app.

#### What did you expect?

I expected to navigate within the application

#### What happened instead?

A browser tab opened and I had to click continue

### Operating system

macOS

### Application version

Element Nightly version: 2023032901 Olm version: 3.2.12

### How did you install the app?

brew install element-nightly

### Homeserver

matrix.woodbine.nyc

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-03-30 16:58
Duplicate of https://github.com/vector-im/element-web/issues/23395

**Closed by t3chguy** 2023-03-30 16:58 UTC
Labels: T-Defect
