### ISSUE TITLE
URL with hostname starting by unicode char not recognized

### ISSUE THREAD

**Issue by ZettaScript** [vector-im/element-web#18914] opened 2021-09-05 19:55 UTC
### Steps to reproduce

Send a message containing a URL with a hostname starting by a unicode character (like `http://ée.tld`).

### What did you expect?
I expected to see `http://ée.tld` formatted as a URL, the same way `http://eé.tld` (starting by an ASCII character) is correctly formatted. These domain names are valid, thus they should be formatted correctly (even if it means replacing unicode characters by their ASCII representation).

### What happened?
It was plain text, not formatted.

### Operating system

Arch Linux

### Browser information

Firefox 91.0.2

### URL for webapp

https://txmn.tk/element

### Homeserver

matrix.txmn.tk

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment] 2021-09-06 08:04
This is an upstream issue with LinkifyJS
![image](https://user-images.githubusercontent.com/2403652/132182137-feb6d6d0-a4c9-467e-b526-8b5719cd08b6.png)

Duplicate of https://github.com/vector-im/element-web/issues/17133

**Closed by t3chguy** 2021-09-06 08:04 UTC
Labels: T-Defect
