### ISSUE TITLE
Make it clear you can start a DM conversation before the invite was accepted

### ISSUE THREAD

**Issue by raboof** [vector-im/element-web#21353] opened 2022-03-08 12:02 UTC
#### What would you like to do?

I would like to add a note to the DM caption explaining that you can start talking even before the other user has accepted the invite.

#### Why would you like to do it?

Currently, when you start a DM, you can see that the other user has been invited to the DM, but [it is unclear](https://merveilles.town/@raboof/107915569473669945) whether after accepting the invite, they will see the messages you sent before they accepted the invite.

(this problem is amplified by the fact that sometimes, in case of problems with encryption keys, the other user actually cannot read the messages from before the invite. That is not the typical scenario, so I don't think we should mention that, but it does make it extra useful to make it clear that in the regular scenario you can start sending messages immediately)

#### How would you like to achieve it?

With https://github.com/matrix-org/matrix-react-sdk/pull/7998 :smile: 

### Have you considered any alternatives?

We might give the whole DM flow a more holistic overhaul (e.g. some of the ideas in #15733).

I think adding a note is a useful simple improvement we can do now. It can always be removed again when/if the flow is improved such that it is no longer needed.

**Comment by daniellekirkwood** [comment] 2022-03-08 14:57
Thanks so much for creating this issue! 

@guillaumevillemont & @gaelledel This might be of particular interest to you, as a stop gap and opportunity to test as we discuss further DM improvements. WDYT

**Comment by giomfo** [comment] 2022-03-09 09:56
> Thanks so much for creating this issue!
> 
> @guillaumevillemont & @gaelledel This might be of particular interest to you, as a stop gap and opportunity to test as we discuss further DM improvements. WDYT

I confirm (@daniellekirkwood, FYI my github username is @giomfo)

**Comment by daniellekirkwood** [comment] 2022-03-09 10:17
> I confirm (@daniellekirkwood, FYI my github username is @giomfo)

Oops! Thank you :)

**Comment by giomfo** [comment] 2022-03-18 15:05
@raboof FYI I just described our plan [here](https://github.com/vector-im/element-web/issues/14736#issuecomment-1072492069) about creating the DM only on first message

Do you agree to close your request according to this plan?

**Comment by raboof** [comment] 2022-03-18 15:21
> @raboof FYI I just described our plan [here](https://github.com/vector-im/element-web/issues/14736#issuecomment-1072492069) about creating the DM only on first message

Looks like a great alternative!
 
> Do you agree to close your request according to this plan?

That depends on the timeline on which you plan to implement #14736 ;) - if that's still a while in the future we can leave this and https://github.com/matrix-org/matrix-react-sdk/pull/7998 open on the chance that it might be ready to go in sooner. If you're actively working on #14736 and expect to ship it soon then I agree we can close this and https://github.com/matrix-org/matrix-react-sdk/pull/7998

**Comment by turt2live** [comment] 2022-05-07 02:57
I believe this is an effective duplicate of https://github.com/vector-im/element-web/issues/14736

**Closed by turt2live** 2022-05-07 02:57 UTC
Labels: A-DMs, X-Needs-Design, T-Enhancement, O-Occasional
