### ISSUE TITLE
"New" login on Element Desktop, requires I validate with other device (same) twice

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/element-web#25169] opened 2023-04-20 23:11 UTC
### Steps to reproduce

This has happened to me several times now, and others around me.

In the most recent example, my computer didn't shut down correctly and the session data corrupted. It required I log out, and log back in.

When I logged in, my Android device prompted me saying that someone logged in as me, do I want to verify it. I tap on it (on my android device) and then scan (with my android device) the barcode that was generated on my Element desktop session I just logged into.

Then within a second or two my same android device is prompted again with the same validation alert, that I logged in, do I want to verify. So I click it, and my Element desktop again shows up a barcode, and I scan the barcode again with my android device. And now both devices are not saying anything about verifying.

### Outcome

I expected that I only needed to verify once, not twice, with the same devices.

### Operating system

Ubuntu 22.04

### Application version

Element version: 1.11.29 Olm version: 3.2.12

### How did you install the app?

Aptitude repository

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-04-21 09:47
I was able to reproduce this with my first try. Logs sent from Web and Android.

- Have the Android App open
- Sign in with Element Web to the same account
- Tap the verification banner on Android
- Verification starts, scan QR Code, finish verification
- Banner show up on Android again

I will file another issue in the Android repo, because I am unsure which side is causing this.

**Comment by BloodyIron** [comment] 2023-04-21 13:54
Thanks for your help @weeman1337 !

**Comment by BillCarsonFr** [comment] 2023-07-03 07:38
Closed as per https://github.com/vector-im/element-android/pull/8536

**Closed by BillCarsonFr** 2023-07-03 07:38 UTC
Labels: T-Defect, X-Regression, S-Minor, A-E2EE-SAS-Verification, O-Occasional, A-Onboarding
