### ISSUE TITLE
Edit room directory directly?

### ISSUE THREAD

**Issue by ukcb** [vector-im/element-web#7267] opened 2018-09-03 17:23 UTC
Please see this issue: https://github.com/matrix-org/synapse/issues/3787

riot-web v0.16.3

**Comment by ukcb** [comment] 2018-09-04 18:14
I do not want to manage the whole server, just add a remote room to the room_list. The option is there, but it is disabled.

**Comment by aaronraimist** [comment] 2018-12-09 05:04
Duplicate of #112 but maybe close that in favor of this since it has the 👍s

**Comment by t3chguy** [comment] 2022-05-24 21:25
Duplicate of https://github.com/vector-im/element-meta/issues/287

**Closed by t3chguy** 2022-05-24 21:25 UTC
Labels: P2, A-Room-Directory, T-Enhancement
