### ISSUE TITLE
Links in replies should open as links

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18059] opened 2021-07-19 14:45 UTC
I really don't want to jump back in time, losing context.

**Comment by SimonBrandner** [comment] 2021-07-19 14:46
Duplicate of https://github.com/vector-im/element-web/issues/18017

**Closed by SimonBrandner** 2021-07-19 14:46 UTC

**Comment by t3chguy** [comment] 2021-07-19 14:48
> I really don't want to jump back in time, losing context.

Is a sane argument, except reply previews are only 2 lines anyway, so you're missing context by just clicking on the visible links to begin with.
