### ISSUE TITLE
Please make custom protocol links clickable

### ISSUE THREAD

**Issue by jaime-rivas** [vector-im/element-web#15753] opened 2020-11-16 15:45 UTC
### Description

Hello! Great job with Element! Please could you make custom protocol links clickable so they open in the respective app? We have an application that creates links to files and not being able to open the links in Element is a major pain point to fully transition from Slack (which makes these links clickable by default). Thank you very much!

### Steps to reproduce

- Copy this link: sdrive://file?Doc-862cce33-fd0a-4c81-8c9d-bf25b1d61e48
- Paste in Element and send
- Check that it is not clickable

Element: 
<img width="373" alt="Screenshot 2020-11-16 164248" src="https://user-images.githubusercontent.com/19812916/99274711-ede6de80-282a-11eb-8980-46bff36c9bb5.png">

Slack: 
<img width="323" alt="Screenshot 2020-11-16 164449" src="https://user-images.githubusercontent.com/19812916/99274844-18389c00-282b-11eb-9a13-c45842a5aff7.png">

In Slack it is automatically clickable (screenshot attached).

### Version information

- **Platform**: web and desktop

**Comment by t3chguy** [comment] 2020-11-16 15:47
Duplicate of https://github.com/vector-im/element-web/issues/15018

**Closed by t3chguy** 2020-11-16 15:47 UTC
Labels: bug
