### ISSUE TITLE
Allow log in with QR code

### ISSUE THREAD

**Issue by LinAGKar** [vector-im/element-web#15071] opened 2020-08-31 16:53 UTC
So currently when you log in you need to verify with another session you need to verify with another session. But you still need to log in first by selecting homeserver and entering your username and password. But how about skipping that and just letting people scan a QR code on their PC with their phone, to log in their phone with a logged in PC or vice versa, and have it select home server, authenticate, and verify all in one step. Basically, verify with a not yet logged in device and have the already logged in device send the new device account credentials.

This is something you can already to on Discord. If you're logged into Discord on you're phone, you can scan a QR code on your PC with your phone to log your PC in. It would improve UX to make it similarly easy to log into Element, rather than the multi-step login currently required.

**Comment by turt2live** [comment] 2020-08-31 17:04
Duplicate of https://github.com/vector-im/element-web/issues/11416

**Closed by turt2live** 2020-08-31 17:04 UTC
Labels: suggestion
