### ISSUE TITLE
Rename Room does not refresh in room list 

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#18855] opened 2021-09-01 08:59 UTC
### Steps to reproduce

https://user-images.githubusercontent.com/31655082/131643030-9bb230d2-b65f-4a07-961c-b4dc108ba22f.mp4

### What happened?

Rename Room does not refresh in room list 

### What did you expect?

Rename Room does should refresh in room list 

### Operating system

Windows

### Browser information

Chrome Version 92.0.4515.131 (Official Build) (64-bit)

### URL for webapp

https://app.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

Yes

**Comment by robintown** [comment] 2021-09-01 11:39
Duplicate of https://github.com/vector-im/element-web/issues/17480

**Closed by robintown** 2021-09-01 11:39 UTC
Labels: T-Defect
