### ISSUE TITLE
Convert pasted text to an uploaded textfile if too many characters pasted / display an uploaded text file as the message in a code block

### ISSUE THREAD

**Issue by christiansacks** [vector-im/element-web#26145] opened 2023-09-08 13:46 UTC
#### What would you like to do?
Something that Discord does that'll be neat on Element would be when pasting a bunch of text into chat between triple back ticks, and it has too many characters, suggest to paste it as a text file instead and then create a text file for it and automagically upload it instead of the pasted text... and something that would go hand in hand with this, is the ability to automatically display text files as a message when uploaded.

#### Why would you like to do it?
Because it would be a very nice bit of polish, very helpful and useful.

#### How would you like to achieve it?
Ask a dev to make the magic happen.

**Comment by t3chguy** [comment] 2023-09-11 09:01
Duplicate of https://github.com/vector-im/element-meta/issues/1130

**Closed by t3chguy** 2023-09-11 09:01 UTC
Labels: T-Enhancement, A-Composer
