### ISSUE TITLE
Save unsent messages so they survive restarts

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#14857] opened 2020-08-01 17:52 UTC
Currently I believe that stacked up unsent messages get lost if you restart the app.  It'd be nice to persist them so you they don't get lost by a restart.

**Comment by t3chguy** [comment] 2020-08-03 11:38
Duplicate of https://github.com/vector-im/element-web/issues/7177

**Closed by t3chguy** 2020-08-03 11:38 UTC
Labels: suggestion
