### ISSUE TITLE
matrix.to link for already joined room sends you to matrix.to only on Desktop

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23007] opened 2022-08-05 10:46 UTC
### Steps to reproduce

Only applies to Element Desktop. The same link works as expected on Element Web.

1. Share a matrix.to link to a room by ID. Be sure that you are already member of this room.
2. Click the link

#### What did you expect?

Go to the room on click

#### What happened instead?

- Send to matrix.to
- Click „Continue“ there
- Send back to the room in Element Desktop

### Operating system

Ubuntu 22.04 LTS

### Application version

Element version: 1.11.2
Olm version: 3.2.12

### How did you install the app?

deb

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-08-05 10:49
Fixed in 1.11.2

**Comment by weeman1337** [comment] 2022-08-05 10:55
Updated to 1.11.2: The problem still exists

**Comment by t3chguy** [comment] 2022-08-05 10:56
My bad, fixed on nightly*

Duplicate of https://github.com/vector-im/element-web/issues/22970

**Closed by t3chguy** 2022-08-05 10:56 UTC
Labels: T-Defect

**Comment by weeman1337** [comment] 2022-08-05 10:59
:+1: Works on nightly
