### ISSUE TITLE
Window body is missing when started at boot

### ISSUE THREAD

**Issue by hwittenborn** [vector-im/element-web#17033] opened 2021-04-21 21:49 UTC
OS: Ubuntu 20.04.2 LTS
Element version: 1.7.25
olm version: 3.2.1

When Element is set to start from boot, the following screen is shown, and doesn't seem to go away for quite a bit:
![2021-04-21_16-40](https://user-images.githubusercontent.com/74838472/115624924-f1dac900-a2c0-11eb-89e3-a375feee7598.png)
The area where you can see my background is where the Element window is supposed to be - as per the title, it's just missing for some reason.

I've noticed it a bit on other Electron apps, but it seems to be drawn out most on Element - every other Electron app I use has the window body appear within a second or less. I tried waiting about 3 minutes with Element, but nothing showed up still.

On a side note, the window also can't be closed without first clicking on `Show/Hide Element` in the system tray(after doing it once on boot, the close button works normally). Not doing so makes the window unclosable, with only minimizing and maximizing working.

**Comment by SimonBrandner** [comment] 2021-12-19 09:27
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/15486

**Closed by SimonBrandner** 2021-12-19 09:27 UTC
Labels: T-Defect, Z-Platform-Specific, S-Critical, A-Electron, O-Occasional
