### ISSUE TITLE
Element Web shows that unread messages in rooms each tim

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#25150] opened 2023-04-18 20:56 UTC
### Steps to reproduce

1. Launch Element Web
2. Visit rooms with "unread messages" icon
3. Close tab.
4. Launch Element Web
5. See, where "unread message" icon again, but no new messages

#### What did you expect?
No "unread messages" for rooms where I have scrolled all messages and no new messages.
#### What happened instead?
"Unread messages" in visited rooms without new messages.

### Operating system

Windows

### Application version

1.11.29

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-04-19 07:34
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-04-19 07:35
Duplicate of https://github.com/vector-im/element-web/issues/24629

**Closed by weeman1337** 2023-04-19 07:35 UTC
Labels: T-Defect
