### ISSUE TITLE
Inconsistent order of reactions

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#22698] opened 2022-06-30 12:54 UTC
### Steps to reproduce

1. Send reactions
2. Wait for enough messages to be sent to the room
3. Refresh the tab
4. Back-paginate in the room till you reach the message you reacted on

#### What did you expect?

The reactions appeared in the order I sent them. In this case, I reacted with the emojis for N, O and M to a message from a coworker announcing they afk'd for lunch.

#### What happened instead?

The reactions appeared in the reverse order:

![Screenshot from 2022-06-30 10-23-52](https://user-images.githubusercontent.com/5547783/176681377-b6c10566-b36c-4d0a-a1ae-f3f7a09572aa.png)

It's a bit annoying, as a large chunk of the use of reactions in communities I'm in is using letter emojis to spell out silly and funny things. The fact that Element Web orders by the amount of reactions for a given emoji is already a bit painful for that, and it feels even more painful if I also can't rely on the ordering of emojis with the same amount of reactions.

### Operating system

Arch Linux

### Browser information

Firefox 102.0

### URL for webapp

develop.element.io

### Application version

Element version: 0baca38c31f7-react-f137bf3fd395-js-9f01c8d1fb83, olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-06-30 13:40
Duplicate of https://github.com/vector-im/element-web/issues/9698

**Closed by t3chguy** 2022-06-30 13:40 UTC
Labels: T-Defect
