### ISSUE TITLE
matrix.to deeplinks don't open the Element Desktop app

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#19819] opened 2021-11-19 22:13 UTC
### Steps to reproduce

Copy a link to a room through the right click context menu

Open the link in your browser

#### What did you expect?

For the link to open in Element Desktop

#### What happened instead?

It opens in the browser

### Operating system

OS X

### Application version

NIghtly

### How did you install the app?

Element Nightly version: 2021111701 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by novocaine** [comment] 2021-11-19 22:14
There's an upstream issue for this in matrix.to - https://github.com/matrix-org/matrix.to/issues/230#issuecomment-974485710

But given this affects Element Web specifically, I think the EW team should take care of it, so logging it here

**Comment by t3chguy** [comment] 2021-11-20 00:09
Duplicate of https://github.com/vector-im/element-web/issues/17446

**Closed by t3chguy** 2021-11-20 00:09 UTC
Labels: T-Defect, S-Minor, O-Occasional
