### ISSUE TITLE
large/long prefix ordered lists start out of the pane (not visible)

### ISSUE THREAD

**Issue by grinapo** [vector-im/element-web#16299] opened 2021-01-28 08:02 UTC
![2021-01-28_08-55-06_screenshot](https://user-images.githubusercontent.com/1056054/106107130-d2f7eb00-6146-11eb-8b81-2f21c20b0d12.png)

### Description

1. large prefix ordered lists are prefix-number-center aligned, so long numbers start outside of the left edge of the pane
2. roman numerals can be conjured (this seems not to be documented anywhere) but they have the same alignment problem plus they have an unordered list indicator within the number.

### Steps to reproduce

(See image. The top part is okay, just showing it how **not to** test it. :))

```
1234. this is the beginning of a beautiful list

- 1972. this looks doubly weird
```

### Version information

- **Platform**: web, 1.7.18, chromium latest release

**Comment by t3chguy** [comment] 2021-01-28 18:20
Duplicate of https://github.com/vector-im/element-web/issues/14621

**Closed by t3chguy** 2021-01-28 18:20 UTC
Labels: bug, ui/ux
