### ISSUE TITLE
[Labs UI Search] Search defaults to an unrelated DM if the User has the search term anywhere in the name

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#20148] opened 2021-12-11 16:07 UTC
#### What would you like to do?

Currently, the new search view seems to default to the DM being focused.

Example:
![image](https://user-images.githubusercontent.com/1374914/145683298-9fcab1f4-cf3a-4b46-9c17-6ed38c7b672a.png)

For the case like in the example, this seems to make little sense. I think it would make sense to also have a condition to check if the DM name starts with the specific search term and if it does not default to a room. Especially if the majority of the search term is part of the room name, like in this example.

#### Why would you like to do it?

The current behaviour adds an extra required action to the search to get to the room instead of being able to do ctrl+k, search, enter. This would slow down the overall flow of the search.

#### How would you like to achieve it?

One way would be, as mentioned above, to take into account where the search term is matched and prefer the one that matches earlier.

### Have you considered any alternatives?

No

**Comment by dbkr** [comment] 2021-12-13 12:35
Probably needs design input on what would happen here: the room here is an exact match but the DM is presumably taking precedence because the DMs section always comes first.

**Comment by t3chguy** [comment] 2021-12-13 12:44
Yup, exactly that. Ordering the groups by max rank within would be one solution

**Comment by t3chguy** [comment] 2022-01-27 13:17
Duplicate of https://github.com/vector-im/element-web/issues/20635

**Closed by t3chguy** 2022-01-27 13:17 UTC
Labels: X-Needs-Design, T-Enhancement, O-Occasional, Z-Labs, A-Spotlight-Search
