### ISSUE TITLE
Using the Desktop Windows app

### ISSUE THREAD

**Issue by GentleRV** [vector-im/element-web#23556] opened 2022-10-20 06:58 UTC
### Steps to reproduce

1. Using Windows 10 Pro version 21H2
2. Downloaded the Windows (64) app from https://element.io/get-started#download 
3. Did a install from this app
4. After double click the created Icon on the desktop I see screen in where is mentioned that my homeserver setup is wrong
5. I tried to find in the application directory any configuration file but failed

#### What did you expect?
I expected, after the install, a menu to fill-in the homeserver and a login or the ability to create one

#### What happened instead?
Only a screen with your homeserver is misconfigured

### Operating system

Windows 10 21H2

### Application version

Element V1.11.10

### How did you install the app?

https://element.io/get-started#download

### Homeserver

Latest Synapse on my own server

### Will you send logs?

No

**Comment by dbkr** [comment] 2022-10-21 13:41
You may be better off asking for support in #element-web:matrix.org

**Comment by t3chguy** [comment] 2022-10-21 13:46
Duplicate of https://github.com/vector-im/element-web/issues/11154

**Closed by t3chguy** 2022-10-21 13:46 UTC
Labels: T-Defect, X-Needs-Info

**Comment by GentleRV** [comment] 2022-10-21 18:40
Eventhough you see it as a duplicate the issue is still not solved

**Comment by t3chguy** [comment] 2022-10-21 18:44
Yup, hence #11154 still being open.
