### ISSUE TITLE
Spoilers are shown in message previews

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#21646] opened 2022-04-01 18:40 UTC
### Steps to reproduce

1. Start a thread
2. In the thread, respond with `/spoiler oops, this just got spoiled in the thread preview`
3. Notice the message is displayed in plain-text in the thread replies preview

For context: While doing some moderation, I recently used the spoiler syntax to hide some nasty abusive text (spam). This way, I could reference the problem text but hide it by default for onlookers.

As a note, I'm not usually one to care about spoilers and whether someone uses the syntax. 

#### What did you expect?

Thread preview hides the actual message in some way. This could be just displaying `spoiler` in place of the content.

#### What happened instead?

The spoiled message text is displayed

![](https://user-images.githubusercontent.com/558581/161322562-0aa0e291-26a2-404f-b5de-55031638efac.png)

### Operating system

Windows 10

### Browser information

Chrome Version 100.0.4896.60

### URL for webapp

https://develop.element.io/

### Application version

Element version: aeb6cddc2f15-react-1f64835fabe9-js-d6f1c6cfdc5a Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment] 2022-04-04 08:38
True as well in the room list message preview

<img width="263" alt="Screen Shot 2022-04-04 at 09 38 06" src="https://user-images.githubusercontent.com/769871/161506454-f63f0ab5-bca4-46b4-862f-ffa0a03b0a15.png">
n

**Comment by t3chguy** [comment] 2022-04-08 09:14
Duplicate of https://github.com/vector-im/element-web/issues/19945#issuecomment-992699506

**Closed by t3chguy** 2022-04-08 09:14 UTC
Labels: T-Defect, S-Tolerable, A-Moderation, A-Message-Previews, O-Uncommon, A-Threads, Z-Labs
