### ISSUE TITLE
Slight UI flicker occurs when user send a message

### ISSUE THREAD

**Issue by Sr-Preet** [vector-im/element-web#17712] opened 2021-06-21 07:07 UTC
I'm facing some issues with element web.
Every time I sends a new message there's a slight UI flickering occurs.
Can anyone please help me regarding this.

Thanks
![CPT2106211226-822x180](https://user-images.githubusercontent.com/55445693/122720464-20f3c380-d28d-11eb-8596-7907c56a4d0c.gif)

**Comment by t3chguy** [comment] 2021-06-21 07:11
That looks like a modified Element. Can you reproduce it on a release build, unmodified?

**Comment by SimonBrandner** [comment] 2021-06-21 07:26
I am pretty sure this is a duplicate of https://github.com/vector-im/element-web/issues/16914 which got solved quite some time ago. Your modified Element is probably based on the version that had this issue.

**Comment by Sr-Preet** [comment] 2021-06-21 07:47
@t3chguy 
Yes I did checked the latest version of element unmodified of course. And it's not occurring there.

**Comment by Sr-Preet** [comment] 2021-06-21 07:48
@SimonBrandner 
Thanks Simon
I'll check into it and see if this issue is resolved.

**Comment by t3chguy** [comment] 2021-06-21 07:49
Given that it does not happen on an unmodified Element I will be closing this issue, you may want to file a similar issue with whomever is supporting the modified version which you are using.

**Closed by t3chguy** 2021-06-21 07:49 UTC
Labels: X-Needs-Info
