### ISSUE TITLE
Unable to copy text from room description if no permission to change it

### ISSUE THREAD

**Issue by afranke** [vector-im/element-web#18359] opened 2021-08-03 10:44 UTC
#### Steps to reproduce

- Go to the room settings for any room which you are not a moderator of
- Text in the room description is greyed out because you don’t have permission to change it. You can still select parts of it. Select text.
- Right click on it.

Expected: “Copy” is possible.
Actual result: “Copy” is disabled.

![element-topic-rightclick](https://user-images.githubusercontent.com/117241/128002275-5b4984f7-75c4-4c21-bf71-45b7bbac0e28.png)

This was discovered because a room description was too long to be displayed completely in the header and I went to the room settings to copy a link from there.

#### Version information

- **Platform**: web
- **Browser**: Firefox 90.0.2
- **OS**: Fedora 34
- **URL**: app.element.io

**Comment by t3chguy** [comment] 2021-08-03 10:48
Closing in favour of https://github.com/vector-im/element-web/issues/9623

**Closed by t3chguy** 2021-08-03 10:48 UTC
Labels: T-Defect

**Comment by afranke** [comment] 2021-08-03 10:59
#9623 is what made discover this, but they are two distinct issues.

**Comment by t3chguy** [comment] 2021-08-03 11:04
We can't control whether your browser makes a disabled textarea copyable or not, so the plan is to expose the full topic in a more dedicated mechanism #9623 

Your issue is a direct duplicate of https://github.com/vector-im/element-web/issues/15693 which was closed in favour of #9623
