### ISSUE TITLE
Forwarding Messages - Let the user choose to insert quotes and orgin of a messages 

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#23773] opened 2022-11-15 13:31 UTC
#### What would you like to do?
I want to be able to choose that i want to mark the message as quote and put the origin address (like when sharing a message) on top of it.

#### Why would you like to do it?
I want to show messages from other rooms, but if i forward them it looks like i have written it.

#### How would you like to achieve it?
After clicking on Forward message there should be an checkbox where i can enable putting the origin address into the message.
eg.
![grafik](https://user-images.githubusercontent.com/30293477/201930095-53110db0-6ce0-40a0-928b-7107eb5cec6e.png)
should be forwarded:
![forwarding](https://user-images.githubusercontent.com/30293477/201931411-66993aef-a2eb-42f8-b4c7-8269a6681673.png)

### Have you considered any alternatives?

#5952 is similiar

### Additional context

perhaps there a data protection concerns, but it should be an option and perhaps it should change when forwarding from an private room.

**Comment by SimonBrandner** [comment] 2022-11-15 13:40
Duplicate of https://github.com/vector-im/element-web/issues/4747

**Closed by SimonBrandner** 2022-11-15 13:40 UTC
Labels: T-Enhancement
