### ISSUE TITLE
reCAPTCHA stops accepting clicks

### ISSUE THREAD

**Issue by marcustyphoon** [vector-im/element-web#26215] opened 2023-09-21 09:55 UTC
### Steps to reproduce

Attempted to create a new matrix.com account in the MacOS desktop app.

#### What did you expect?

To be able to submit the reCAPTCHA form and proceed with account creation.

#### What happened instead?

The reCAPTCHA form shown did not accept clicks anywhere in the bottom bar of the popup (i.e. "verify") and after two clicks on the prompt squares it stopped accepting clicks there as well. Exiting the modal via an outside click, going back and forward did not fix this.

<img width="1024" src="https://github.com/vector-im/element-web/assets/8336245/a7b29b51-f64b-45a7-ac69-437cd0e2ae1f">

### Operating system

MacOS 13.5

### Application version

Element version: 1.11.43 / Olm version: 3.2.14

### How did you install the app?

From https://element.io/download

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-09-21 09:57
Duplicate of https://github.com/vector-im/element-desktop/issues/1199

**Comment by marcustyphoon** [comment] 2023-09-21 09:57
Oops, sorry! Searched the wrong repo.

**Closed by t3chguy** 2023-09-21 09:57 UTC
Labels: T-Defect
