### ISSUE TITLE
Missing thread event causes stuck notification

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#24069] opened 2022-12-20 23:06 UTC
### Steps to reproduce

This won't go away no matter how much I open the room, scroll around, open the threads panel, ditto:

![image](https://user-images.githubusercontent.com/1389908/208783245-49c80232-d0e8-42b7-96f9-d27122d155fd.png)

### Outcome

-

### Operating system

Ubuntu 22.04

### Application version

Element Nightly version: 2022121801 Olm version: 3.2.12

### Will you send logs?

Yes, https://github.com/matrix-org/element-web-rageshakes/issues/18581

Discussed at https://matrix.to/#/!tCaHWuHHvOHjWyqapP:matrix.org/$NJt7bWWvJJkfg-q40xnPU4D17MOnIlR6qZcQd1fBkIM?via=matrix.org&via=element.io&via=riot.ovh

**Comment by richvdh** [comment] 2022-12-20 23:56
It turns out I had missed an active thread; opening it reduced the unread count from 3 to 2.

Comparing with @MadLittleMods' view of the same thread, it appears I am missing the two most recent messages in the thread.

**Comment by Me4Linux** [comment] 2022-12-21 00:26
Can confirm the problem - my Client (Element: 1.11.16, Olm: 3.2.12, Debian 11) shows the notification marker stuck at "1" for my favourite room. Deleted the cache and restartet the client, but that didn't help.
My other client (1.5.11, Android) works without problems with the same room.

**Comment by weeman1337** [comment] 2022-12-21 08:54
> Comparing with @MadLittleMods' view of the same thread, it appears I am missing the two most recent messages in the thread.

That sounds like another problem @richvdh . Can you open another issue for it?

**Comment by richvdh** [comment] 2022-12-21 10:31
> > Comparing with @MadLittleMods' view of the same thread, it appears I am missing the two most recent messages in the thread.
>
> That sounds like another problem @richvdh . Can you open another issue for it?

I mean I can, but isn't it likely to be the *cause* of my stuck notification marker? I can retitle this one instead?

**Comment by Me4Linux** [comment] 2022-12-21 22:57
Just received an update (to version 1.11.17), the bug is gone. Thank you :-) .

**Comment by gsouquet** [comment] 2022-12-22 11:51
I have a feeling that https://github.com/matrix-org/matrix-js-sdk/pull/3002 will have a positive impact on this.

The stuck notifications are likely caused by the missing events in the thread, so it can't send a read receipt.
I managed to reproduce this issue once and saw that the pagination token was missing. 

Have not yet figured out what caused it and how to reproduce reliably

**Comment by weeman1337** [comment] 2022-12-23 08:58
https://github.com/matrix-org/matrix-js-sdk/pull/3002 got merged. Can you test again on develop @richvdh ?

**Comment by richvdh** [comment] 2022-12-23 11:01
I can't reproduce it any more with the previous version, so :man_shrugging:

**Comment by turt2live** [comment] 2023-01-10 00:47
Closing as presumed fixed. If this is untrue, please open a new issue with fresh reproduction steps for the QA team to review.

**Closed by turt2live** 2023-01-10 00:47 UTC
Labels: T-Defect, X-Needs-Info, S-Major, O-Occasional, A-Threads
