### ISSUE TITLE
Room message preview incorrectly display HTML entities

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#17693] opened 2021-06-18 16:07 UTC
<img width="317" alt="Screen Shot 2021-06-18 at 17 06 21" src="https://user-images.githubusercontent.com/769871/122589015-aaba4b80-d057-11eb-88e4-692241ea59d0.png">

Original message is
```
<span data-mx-spoiler="matrix client that support spoiler are">element
```

**Comment by t3chguy** [comment] 2021-06-18 16:08
Duplicate of https://github.com/vector-im/element-web/issues/17101

**Closed by t3chguy** 2021-06-18 16:08 UTC
Labels: A-Room-List, P2, X-Regression
