### ISSUE TITLE
UI for enabling encryption needs to be more obvious

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8678] opened 2019-02-15 02:28 UTC
c.f. https://banana.dog/@migratory/101593735981017517

@nadonomy how about turning the lost e2e icon by the composer into a way to enable encryption for non-encrypted rooms?

**Comment by turt2live** [comment] 2019-02-15 02:31
Borderline duplicate of https://github.com/vector-im/riot-web/issues/4213

**Comment by kittykat** [comment] 2021-12-16 16:44
Closing as UI has been updated

**Closed by kittykat** 2021-12-16 16:44 UTC
Labels: T-Defect, P1, A-E2EE, X-Needs-Community-Testing
