### ISSUE TITLE
Soft crash when joining rooms from the space landing page

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22807] opened 2022-07-11 16:51 UTC
### Steps to reproduce

Unsure, but this is what I was doing at the time:

1. Go to the landing page of a space
2. Click the 'join' button on one of that space's subspaces
3. Click the 'join' button on one of that subspace's rooms

#### What did you expect?

No crash

#### What happened instead?

'Something went wrong!' in the main panel

### Operating system

NixOS unstable

### Browser information

Firefox 102.0

### URL for webapp

develop.element.io

### Application version

Element version: 7708d0584bb7-react-0bc2f1c101d0-js-1fbfdaf22131 Olm version: 3.2.8

### Homeserver

Synapse 1.62.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-07-12 06:25
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-07-12 06:25 UTC
Labels: T-Defect, S-Major, Z-Rageshake, A-Spaces, Z-Soft-Crash, O-Uncommon
