### ISSUE TITLE
New web update fetches data continously from server

### ISSUE THREAD

**Issue by mds512** [vector-im/element-web#26060] opened 2023-08-26 20:46 UTC
It made the synapse server to build logs around 2 GB in one day.

### Steps to reproduce

open https://app.element.io/#/room/<room>.
open devtools -> network, to see requests.

https://github.com/vector-im/element-web/assets/143015285/471357b2-3e97-40b0-8638-044f894cd459

#### What did you expect?

very less number of requests to server

### Operating system

MacOs

### Browser information

firefox 116.0.3 (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.39 Olm version: 3.2.14

### Homeserver

matrixdotorg/synapse   latest  image Id : 5ae86c251d51 

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-08-31 07:10
The Matrix spec /sync API is designed to be called continually in a long-polled fashion. Can you expand the `File` column and take another video to check that the since token is changing, often it only changes by 1 digit.

**Comment by mds512** [comment] 2023-08-31 07:52
@t3chguy Looks like request and response is same for all requests. Not a single bit of change.

https://github.com/vector-im/element-web/assets/143015285/ab2fb067-0821-4a0c-9c2c-4af7bc21191b

**Comment by t3chguy** [comment] 2023-08-31 08:02
Duplicate of https://github.com/vector-im/element-web/issues/25324

**Comment by t3chguy** [comment] 2023-08-31 08:02
> Will you send logs?
Yes

I didn't see any logs arrive, please do send them tagging either this issue or https://github.com/vector-im/element-web/issues/25324

**Closed by t3chguy** 2023-08-31 08:02 UTC
Labels: T-Defect, X-Needs-Info

**Comment by mds512** [comment] 2023-08-31 15:34
@t3chguy is there a solution for this issue or the issue is still open?

**Comment by t3chguy** [comment] 2023-09-01 07:28
@mds512 #25324 is still open but at risk of being closed due to insufficient info. No one experiencing this issue has yet sent logs.
