### ISSUE TITLE
"Something went wrong" while joining a room from a Space page

### ISSUE THREAD

**Issue by anton-molyboha** [vector-im/element-web#23081] opened 2022-08-16 01:57 UTC
### Steps to reproduce

1. Go to "Matrix Community" space page.
2. Search for "maubot" rooms.
3. Click "Join" buttons next to "Bots" subspace and "Maubot" room.
4. Wait for the joins to finish.

#### What did you expect?

I am joined to the "Bots" subspace and also to the "Maubot" room.

#### What happened instead?

At some point, I saw that the word "joined" appeared next to the "Bots" subspace, while the "Maubot" join was still in progress (rotating circle indicator).

When I checked on the Element tab later, there was the "Something went wrong" screen.

### Operating system

Gentoo Linux

### Browser information

Firefox 91.11.0esr (64-bit)

### URL for webapp

https://app.element.io

### Application version

Element version: 1.11.2
Olm version: 3.2.12

### Homeserver

Dendrite 0.9.1

### Will you send logs?

Yes

**Comment by anton-molyboha** [comment] 2022-08-16 02:04
After leaving the "Something went wrong" page, I see that I did join both the "Bots" space and "Maubot" room.

**Comment by SimonBrandner** [comment] 2022-08-16 06:06
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by SimonBrandner** 2022-08-16 06:06 UTC
Labels: T-Defect
