### ISSUE TITLE
Confetti effects have started firing way too often.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#25491] opened 2023-05-31 16:10 UTC
### Steps to reproduce

1. Go to a room where someone has put 🎉 in a message (or possibly as a reaction?) in a thread root, or possibly just in scrollback
2. Scroll back through history
3. Watch as the screen keeps exploding with confetti.

#### What did you expect?

I /think/ the previous behaviour is that confetti only fires if it arrives while you're actively looking at the room, so the user can make the correlation between the newly received message containing the emoji and the confetti going off?  Or possibly just once if the most recent history includes one?

#### What happened instead?

It fires as you read scrollback, or as the threadpanel updates itself. Which is very unintuitive.

### Application version

latest nightly

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-05-31 16:13
Duplicate of https://github.com/vector-im/element-web/issues/25489

**Closed by t3chguy** 2023-05-31 16:13 UTC
Labels: T-Defect
