### ISSUE TITLE
Published tar files are still riot-v1.7.8.tar.gz

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15423] opened 2020-10-08 20:44 UTC
We should be publishing `element-` instead of `riot-`. For a transition period, we could publish both and define a date/release where we stop supporting `riot-`.

**Comment by jryans** [comment] 2020-10-09 08:54
Duplicate of https://github.com/vector-im/element-web/issues/14896

**Closed by jryans** 2020-10-09 08:54 UTC
Labels: bug, defect, maintenance, p2, type:packaging
