### ISSUE TITLE
Full indexedDB breaks element web

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#20931] opened 2022-02-05 14:18 UTC
### Steps to reproduce

I first noticed this in a fosdem room, but this sems to be generalized across rooms. I cannot send messages at all, afaict.

chat.element.io works, though

### Outcome

Cannot send messages. Messages show as "Failed to send".

### Operating system

Ubuntu

### Browser information

Firefox 96.0 (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 64242a004eb7-react-7f3f18604417-js-2d23330b74da Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Yoric** [comment] 2022-02-05 14:19
Ah, I find in the logs

```
Uncaught (in promise) DOMException: The quota has been exceeded.
```

So I guess it's a matter of localStorage/indexedDB being full. We should find a way to fix this.

**Comment by Yoric** [comment] 2022-02-05 14:23
I've removed my indexedDB manually. Unfortunately, Element Web won't launch at all now.

**Comment by aaronraimist** [comment] 2022-02-06 13:32
Duplicate of https://github.com/vector-im/element-web/issues/18423

To get back in maybe going to the Lock icon in the URL bar and clicking Clear cookies and site data will help.

**Comment by Yoric** [comment] 2022-02-06 13:32
Ok, restarting Firefox after removing indexedDB seems to have done the trick.
However, my Element Web self-destructed again 10 minutes before my Fosdem talk. Not ideal.

**Comment by Yoric** [comment] 2022-02-06 13:33
> Duplicate of #18423
> 
> To get back in maybe going to the Lock icon in the URL bar and clicking Clear cookies and site data will help.

I can do that. Random user can't.

**Comment by aaronraimist** [comment] 2022-02-06 13:33
Which is why https://github.com/vector-im/element-web/issues/18423 is open

**Comment by aaronraimist** [comment] 2022-02-06 13:34
>  However, my Element Web self-destructed again 10 minutes before my Fosdem talk. Not ideal.

Delete some stuff from your disk so you have some free space

**Comment by Yoric** [comment] 2022-02-06 14:37
Note that I have 300Gb available on my hd, so that's *not* the issue.

**Comment by novocaine** [comment] 2022-02-10 18:16
Yikes, apologies I might have been unclear - if its a result of the browser allocated disk space filling up, then I think that is part of https://github.com/vector-im/element-web/issues/18423 . 

I'm not sure I quite trust the quota message - are you able to check the size of your IndexDB ?

**Comment by Yoric** [comment] 2022-02-11 13:22
> I'm not sure I quite trust the quota message though - are you able to check the size of your IndexDB ?

Not a few days after cleaning it up, I'm afraid.

**Comment by jlemangarin** [comment] 2022-02-24 16:46
I confirm this issue happens with a lot of disk space available and with no information in the client, just the message not sending.

![ead68e72-9afe-4397-a005-b58b1383dfb9](https://user-images.githubusercontent.com/22454938/155568497-0059a2bd-45e9-4b9f-9e7a-e367b6360450.png)

It happens with actually not a lot of tabs opened (like 5) and with a decent amount of rooms (~100). I'm concerned about this hard limitation in IndexDB also, do you know about any issue opened outside of Element ?

Also maybe Element should clear some space when it's reaching the limit, even if it has to download again some resources later.

**Comment by turt2live** [comment] 2022-05-26 14:10
Mine managed to break in such a way where I got notifications but not messages in the timeline. No obvious errors presented to me as a user that would suggest anything was wrong (not even a "disconnected from homeserver" warning)

**Comment by t3chguy** [comment] 2023-03-16 09:37
Closing in favour of #18423

**Closed by t3chguy** 2023-03-16 09:37 UTC
Labels: T-Defect, Z-Rageshake, A-Storage
