### ISSUE TITLE
Feature Req: Restore Markdown toggle

### ISSUE THREAD

**Issue by CyberneticCody** [vector-im/element-web#15073] opened 2020-08-31 22:38 UTC
**Is your suggestion related to a problem? Please describe.**
When using Element, it is very frustrating when I am trying to compose a message and my input gets mistaken as markdown.
There used to be a feature to disable markdown when needed, however it has been removed.

**Describe the solution you'd like**
I would like for the markdown feature to be added back to Element, perhaps in a way that keeps the composer simple, but also allows advanced users to retain their advanced options.

**Describe alternatives you've considered**
As mentioned by jryans, "Removing modes is believed to simplify the composer experience for most people", removing this option does make the composer easier for most people. However, for those of us that actively used this feature, it makes the experience more complicated and cumbersome needing to use /plain in front of every message I want to send that may get caught by Markdown when we do not want it to be. I believe that a better solution for this would be to place an option to show or hide the markdown button in an advanced section of the settings instead of removing it completely like has already been done.

**Additional context**
This option is still left intact on the Android Element app and I have markdown turned off there. This could also be an accessibility issue for some people.

**Comment by turt2live** [comment] 2020-09-01 01:13
Duplicate of https://github.com/vector-im/element-web/issues/483

**Closed by turt2live** 2020-09-01 01:13 UTC
Labels: suggestion
