### ISSUE TITLE
seshat doesn't understand room versions

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#11155] opened 2019-10-18 08:11 UTC

**Comment by jryans** [comment] 2020-01-02 13:15
@poljar Is this a Seshat issue or something in the Riot integration layer?

**Comment by poljar** [comment] 2020-01-02 15:05
Both, some initial table changes for Seshat were made to support this, but no public API yet. The crawler logic will need to be slightly modified as well.

**Comment by t3chguy** [comment] 2023-04-25 14:54
Duplicate of https://github.com/vector-im/element-desktop/issues/909

**Closed by t3chguy** 2023-04-25 14:54 UTC
Labels: A-Indexing
