### ISSUE TITLE
Broken connectivity from Element Desktop Nightly on Windows

### ISSUE THREAD

**Issue by rxl881** [vector-im/element-web#21152] opened 2022-02-22 09:33 UTC
### Steps to reproduce

I've been using Element Desktop Nightly on my Windows Desktop machine for a long time, without any issues. However, recently it sometimes appears to be unable to access any network functions, typically once already logged in to a session, after a machine restart.

I've tried to run through the main "idiot test" items... there are no general internet connectivity issues on the machine, web browser login etc. works. I've checked the (Windows Defender) firewall and there are no obvious issues or exceptions there (the app still appears to be unable to connect with the firewall completely disabled (temporarily).

Lack of connectivity is indicated in various places in the app, e.g. "Connectivity to the server has been lost" in the main timeline, "Unable to load device list", "Unable to load key backup status", I believe that there was also a message about room upgrade not being possible as I was currently "offline", but I can't find an example of this right now.

Once connectivity in the app is lost, the only way that I have been able to get it working again is by logging out and logging in again on the same machine / client and starting a whole new session. This worked until I rebooted the machine over night, and now on starting the app, connectivity has been lost again. I just tried the same trick of logging out, logging back in and reverifying etc., and it is working again ... but this is rather tedious (to say the least).

This is a desktop machine, and I'm wondering if the application is detecting going to sleep or something, but not recovering when it awakes?

Before logging out this time, I downloaded the debug logs, attached. Will the help to track down the issue? Please let me know if you need anything else from my side. Thanks

### Operating system

Windows 10 Pro - 10.0.19043 

### Application version

Element Desktop Nightly Element version: 1.10.4 Olm version: 3.2.8

### How did you install the app?

Element website

### Homeserver

vector.modular.im

### Will you send logs?

Yes

**Comment by rxl881** [comment] 2022-02-22 09:36
Debug logs:

[rageshake.tar.gz](https://github.com/vector-im/element-web/files/8115426/rageshake.tar.gz)

**Comment by novocaine** [comment] 2022-02-22 09:40
```
2022-02-22T08:48:25.014Z W Unable to initialise e2e OLM.BAD_ACCOUNT_KEY
Error: OLM.BAD_ACCOUNT_KEY
    at vector://vector/webapp/bundles/f2df67371ec7a840fddf/vendors~init.js:2:4051177
    at Ce.<anonymous> (vector://vector/webapp/bundles/f2df67371ec7a840fddf/vendors~init.js:2:4054056)
    at Ce.unpickle (vector://vector/webapp/bundles/f2df67371ec7a840fddf/vendors~init.js:2:4050883)
    at vector://vector/webapp/bundles/f2df67371ec7a840fddf/vendors~init.js:2:2044969
    at IDBRequest.n.onsuccess (vector://vector/webapp/bundles/f2df67371ec7a840fddf/vendors~init.js:2:4221547)
```

duplicate of https://github.com/vector-im/element-web/issues/14515

**Closed by novocaine** 2022-02-22 09:40 UTC
Labels: T-Defect
