### ISSUE TITLE
If you don't have any keywords set for notifications, you can't change the notif level on 'Message containing keywords' to 'off' or 'noisy'.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7011] opened 2018-07-12 10:50 UTC
And your clicks are just ignored, which is confusing.

To reproduce:
- go to user settings
- click on the _keywords_ link in notifs
- delete all your keywords
- try and change the notif level to 'off' or 'noisy'
- observe you clicks being ignored

**Comment by MadLittleMods** [comment] 2021-06-16 22:37
Duplicate of https://github.com/vector-im/element-web/issues/2188

**Closed by MadLittleMods** 2021-06-16 22:37 UTC
Labels: A-Notifications, A-User-Settings, P3, S-Minor, T-Defect
