### ISSUE TITLE
[Firefox] [Privacy Possum] Viewport size calculated incorrectly

### ISSUE THREAD

**Issue by jwflory** [vector-im/element-web#25726] opened 2023-07-06 13:19 UTC
### Steps to reproduce

1. Open Firefox. Install/enable the [_Privacy Possum_ browser add-on](https://addons.mozilla.org/en-US/firefox/addon/privacy-possum/).
2. Open Element (in my case, chat.fedoraproject.org).
3. The viewport is too large for the screen size. Several elements of the UI are off-screen.

#### What did you expect?

The viewport is correctly sized for the visible screen.

#### What happened instead?

The viewport is incorrectly sized for the visible screen, with several UI components off-screen. A combination of vertical and horizontal scrolling is required in order to see all parts of the UI. This is a regression, as I have used Privacy Possum with Element for some time and did not have this issue. I noticed it in within the last 1-2 weeks.

![Screenshot of the Element Web window, with several UI components clipped in the visible viewport. The settings module and read receipts are out of view.](https://github.com/vector-im/element-web/assets/4721034/fa2d24f6-2e4d-456c-b07e-7f59e7ebae8d "Screenshot of the Element Web window, with several UI components clipped in the visible viewport. The settings module and read receipts are out of view.")

### Operating system

Fedora Linux 38

### Browser information

Firefox 114.0.2

### URL for webapp

https://chat.fedoraproject.org/

### Application version

Fedora Chat version: 1.11.34, Olm version: 3.2.14

### Homeserver

EMS-hosted

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-07-06 13:20
![image](https://github.com/vector-im/element-web/assets/2403652/c3b4763c-ab84-455e-af28-307b70df4801)

Cannot reproduce

**Comment by t3chguy** [comment] 2023-07-19 09:38
Closing due to unable to reproduce following repro steps, if anyone else can repro please shout.

**Closed by t3chguy** 2023-07-19 09:38 UTC
Labels: T-Defect, X-Cannot-Reproduce
