### ISSUE TITLE
Tooltips used to encourage you to set avatars on new rooms have astonishingly high z-index

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15957] opened 2020-12-14 00:27 UTC
The tooltip used in the timeline to nag users to set an avatar for newly created rooms seems to have an infinite z-index, in that if you do things like open up Room Settings the tooltip hovers over the modal - and if you scroll the timeline, it hovers over the RoomTitle etc.

**Comment by jryans** [comment] 2020-12-14 10:00
Basically a duplicate of https://github.com/vector-im/element-web/issues/15854, I'll copy your comment there.

**Closed by jryans** 2020-12-14 10:00 UTC
