### ISSUE TITLE
Extremely high lag and GPU demand on Linux

### ISSUE THREAD

**Issue by ekaitz-zarraga** [vector-im/element-web#19217] opened 2021-09-29 08:33 UTC
### What happened?

Since the addition of the *spaces* feature Element web client makes my integrated GPU suffer and sets my processor temperature to 70 degrees C while most of the websites, like github right now, set it to 44C.

It's obvious its element because the temperature goes up when I change to the element tab.

Element version: 1.9.0
Olm version: 3.2.3

### Steps to reproduce

Use a recent element version that includes the spaces feature.

### What did you expect?

I expected it to work like before, it wasn't superfast, but it didn't have that lag.

### What happened?

It has a very annoying lag. Reaching to 1s to see what I type and it's very GPU demanding.

### Operating system

Linux

### Browser information

Firefox 78.10.0esr-64bit

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by novocaine** [comment] 2021-09-29 14:30
Can you please name the specific Element version you starting having an issue with? You may believe that it is Spaces, but there are other concurrent changes that may also have caused the issue - in particular, there have been some changes to the left panel's background filter that might be impacting your GPU.

**Comment by ekaitz-zarraga** [comment] 2021-09-29 14:33
Element version: 1.9.0
Olm version: 3.2.3
I'll update the issue

**Comment by novocaine** [comment] 2021-09-29 14:40
Thankyou 🙏 

I don't believe this issue is experienced by our team so with your help, we would love some more details to debug - 

* Are you able to post your model of GPU and linux distribution?
* Does the problem also manifest itself in Element Desktop and/or other browsers?
* Are you able to provide a performance recording from Firefox developer tools?

**Comment by ekaitz-zarraga** [comment] 2021-09-29 14:54
- The linux distribution is Guix System
- I don't experience the same issue in ungoogled-chromium
- [profile.zip](https://github.com/vector-im/element-web/files/7252885/profile.zip)

Extra: the browser is a Icecat, not a plain Firefox, there might be some differences... :disappointed:

**Comment by gsouquet** [comment] 2021-09-29 15:23
Would you be able to record a performance profile of Element whilst doing the actions that are very slow for you.
You can use https://profiler.firefox.com/ to do so

**Comment by novocaine** [comment] 2021-10-01 09:21
If you don't experience the issue in Chromium, it is most likely some negative interaction between your GPU and Firefox which will be difficult for us to address directly. 

If we can isolate the exact area that's causing issues, it might be possible to flag it off, but if it only affects a small subset of our users, it's difficult to justify spending time on it versus the backlog of more widespread bugs ..

**Comment by ekaitz-zarraga** [comment] 2021-10-01 09:57
But it worked correctly with previous versions of element, so there must be some change in the app that produced the lag.

**Comment by novocaine** [comment] 2021-10-01 10:57
I agree.

**Comment by Mershl** [comment] 2021-10-04 16:00
Coming from #19268. I can reproduce the same issue on Element desktop (using the rpm or flathub release).

> Are you able to post your model of GPU and linux distribution?
    Does the problem also manifest itself in Element Desktop and/or other browsers?
    Are you able to provide a performance recording from Firefox developer tools?

Tested with clean installations of the rpm and flathub releases. Not tested in Browser. Performance profile (uploaded in #19268) shows extreme GPU usage while the client is visible. Instantly fixed while minimized.

Reproduciable on Element 1.8.5 and 1.9.0 (not tested on other versions).

System:
```
System:    Host: mershl-t495 Kernel: 5.14.9-200.fc34.x86_64 x86_64 bits: 64 
           compiler: gcc v: 2.35.2-5.fc34 Desktop: GNOME 40.4 tk: GTK 3.24.30 
           wm: gnome-shell dm: GDM Distro: Fedora release 34 (Thirty Four) 
CPU:       Info: Quad Core model: AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx 
           bits: 64 type: MT MCP arch: Zen rev: 1 cache: L2: 2 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
           bogomips: 33537 
           Speed: 1233 MHz min/max: 1400/2100 MHz boost: enabled Core speeds (MHz): 
           1: 1233 2: 1408 3: 1225 4: 1223 5: 1225 6: 1223 7: 1223 8: 1225 
Graphics:  Device-1: AMD Picasso vendor: Lenovo driver: amdgpu v: kernel bus-ID: 05:00.0 
           chip-ID: 1002:15d8 
           Display: wayland server: X.Org 1.21.1.2 compositor: gnome-shell driver: 
           loaded: amdgpu,ati unloaded: fbdev,modesetting,vesa 
           resolution: 1920x1080~60Hz s-dpi: 96 
           OpenGL: renderer: AMD Radeon Vega 8 Graphics (RAVEN DRM 3.42.0 
           5.14.9-200.fc34.x86_64 LLVM 12.0.1) 
           v: 4.6 Mesa 21.1.8 direct render: Yes 
```

**Comment by novocaine** [comment] 2021-10-05 08:23
> Coming from #19268. I can reproduce the same issue on Element desktop (using the rpm or flathub release).

This is slightly different - the OP in this ticket reports an issue with Firefox on Element Web, but no issue with Chromium, whereas your issue is with Element Desktop (which bundles Chromium)

**Comment by Palid** [comment] 2021-10-05 08:27
@ekaitz-zarraga can you let me know if you have `gfx.webrender.all` set to `true` in `about: config` ? Seems some distros don't have this flag, and without it Firefox still uses the old rendering engine before rewrite to Rust, which is pretty freaking slow in comparison and eats up a lot more resources.

**Comment by ekaitz-zarraga** [comment] 2021-10-05 08:57
@Palid I can't believe it! it was that! Now my gpu consumption it's not only normal in element but MUCH better in all the other apps. This is crazy.
Thank you very much.

**Comment by Palid** [comment] 2021-10-05 09:04
@ekaitz-zarraga can I ask you to raise the issue within your distro packager? It could probably profit other users too. 😄 
https://mastransky.wordpress.com/2021/01/10/firefox-were-finally-getting-hw-acceleration-on-linux/ there's this quite recent thing for Fedora and seems that this flag is not turned on by default due to wayland problems, but hopefully that'll be resolved soon for most distros.

**Comment by ekaitz-zarraga** [comment] 2021-10-05 09:09
@ekaitz-zarraga I will!

**Comment by Palid** [comment] 2021-10-05 11:06
Alright, closing the issue then!

**Closed by Palid** 2021-10-05 11:06 UTC
Labels: T-Defect, A-Performance, Z-Platform-Specific, X-Cannot-Reproduce, X-Regression, S-Major, O-Uncommon
