### ISSUE TITLE
element-desktop takes the whole screen and doesn't close, no icon in systray. 

### ISSUE THREAD

**Issue by shirishag75** [vector-im/element-web#24203] opened 2023-01-10 13:52 UTC
### Steps to reproduce

This is from - 

```
$ apt-cache policy element-desktop
element-desktop:
  Installed: 1.11.17
  Candidate: 1.11.17
  Version table:
 *** 1.11.17 500
        500 https://packages.element.io/debian default/main amd64 Packages
        100 /var/lib/dpkg/status

```
I had shared about this issue in https://github.com/vector-im/element-web/issues/10832 . Still the issue is persisting. 

The added bit is now it doesn't even register in the systray and have to do CTRL+C couple of times to close the app. 

I start the app. using `$ element-desktop` on the CLI 

Please let me know if you need any more details. 

#### What did you expect?

Flawless experience. 

#### What happened instead?

Unable to see controls, unable to close the app. from systray, have to manually kill the app using CTRL+C. 

### Operating system

Debian testing

### Application version

Element version: 1.11.17 Olm version: 3.2.12

### How did you install the app?

https://packages.element.io/debian default/main amd64 Packages

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-01-11 11:38
Duplicate of https://github.com/vector-im/element-web/issues/23993

**Closed by t3chguy** 2023-01-11 11:38 UTC
Labels: T-Defect
