### ISSUE TITLE
When using on Windows, Chinese is set, but after the program is closed and restarted, it changes back to English

### ISSUE THREAD

**Issue by zxc178499074** [vector-im/element-web#22399] opened 2022-05-30 16:27 UTC
### Steps to reproduce

1. open program
2. set Chinese
3. close the program
4. open program
5. show english

### Outcome

I hope that when I restart the program, it will still display Chinese

### Operating system

windows

### Will you send logs?

Yes

**Comment by ritikBhandari** [comment] 2022-05-30 17:37
Can I work on this issue if possible?

**Comment by zxc178499074** [comment] 2022-05-30 19:53
sure

**Comment by ritikBhandari** [comment] 2022-05-31 00:09
@t3chguy @a4 As I'm new here, can anybody pls guide me which file/folder to start with?
Would be grateful.

**Comment by YamatoRyou** [comment] 2022-05-31 18:19
For the Windows version, try the following:

Option A:
1. First set the language to English;
2. Press Ctrl + Shift + I to open the developer tools;
3. Go to the "Application" tab;
4. Expand "Local Storage" on the left, click "vector://vector";
5. Find "mx_local_settings" on the right, and start editing the JSON on the right;
6. Edit the value on the right side of "language" to "zh-hans", press Enter when finished;
7. Restart Element.

Option B:
1. Navigate to the Element user data folder;
2. Create a new file here, file name: ```config.json```;
3. Open this file with Notepad and paste the following (if this file already exists, just insert ```"language": "zh-hans"```):
````
{
     "settingDefaults": {
         "language": "zh-hans"
     }
}
````
4. Save the changes and restart Element.

**Comment by turt2live** [comment] 2022-06-11 02:05
This needs more information to know what is going on. Are you logged into the app? How did you set the app to Chinese?

The issue also says you sent logs, but I don't see them. After reproducing the issue, please go to Settings -> Help -> Submit Debug Logs and use this issue as the URL.

**Comment by kittykat** [comment] 2022-10-05 13:10
@zxc178499074 Can you please help us with the above questions? We cannot debug the issue any further at this time without additional information.

**Comment by robintown** [comment] 2022-11-19 03:54
Closing since we don't have enough information to help here.

**Closed by robintown** 2022-11-19 03:54 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-User-Settings, I18n, Z-TravisR, O-Occasional

**Comment by SiriusXT** [comment] 2025-03-07 13:51
Currently, it is set as `"setting_defaults": { "language": "zh-hans" }`, rather than setting `settingDefaults`.
