### ISSUE TITLE
FeatureRequest Screen sharing during video call

### ISSUE THREAD

**Issue by j-c-cook** [vector-im/element-web#16955] opened 2021-04-14 18:21 UTC
#### Is your suggestion related to a problem? Please describe.
For this to become a true _alternative_ to Microsoft Teams, it will be necessary to have a "share screen" option when on a video call. 

#### Describe the solution you'd like.
On video calls, allow for one person to share their screen at a time. 

#### Describe alternatives you've considered.
From my experience in testing out this program, it does not have this feature.

**Comment by t3chguy** [comment] 2021-04-14 18:23
Duplicate of https://github.com/vector-im/element-web/issues/239

**Closed by t3chguy** 2021-04-14 18:23 UTC
Labels: T-Enhancement
