### ISSUE TITLE
Element  1.11.4 won't open

### ISSUE THREAD

**Issue by Rayserzor** [vector-im/element-web#23177] opened 2022-08-31 23:30 UTC
### Steps to reproduce

Everything started after I did an update using the `flatpak update`.

### Outcome

If I try to `run im.riot.Riot`
The error is:

```
flatpak run im.riot.Riot
/home/user/.var/app/im.riot.Riot/config/Element exists: yes
/home/user/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 20:19:42.372: Failed to load module "xapp-gtk3-module"
[3:0831/201942.414892:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0831/201942.415046:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Couldn't find webapp files in any of: 
	/app/Element/resources/app.asar/webapp.asar
	/app/Element/resources/webapp.asar
	/app/Element/resources/app.asar/webapp
	/app/Element/resources/webapp
App setup failed: exiting Error: Failed to find webapp files
    at /app/Element/resources/app.asar/lib/electron-main.js:145:15
    at Generator.throw (<anonymous>)
    at rejected (/app/Element/resources/app.asar/lib/electron-main.js:43:65)
```

### Operating system

Linux Mint 21

### Application version

Element 1.11.4

### How did you install the app?

Flatpak (flatpak install flathub im.riot.Riot) 

### Will you send logs?

No

**Comment by turt2live** [comment] 2022-08-31 23:34
Related: https://github.com/vector-im/element-web/issues/23174

**Comment by lowercaseUpperCase** [comment] 2022-09-01 00:23
having same problem btw

**Comment by t3chguy** [comment] 2022-09-01 09:48
Duplicate of https://github.com/flathub/im.riot.Riot/issues/290

**Closed by t3chguy** 2022-09-01 09:48 UTC
Labels: T-Defect, X-Community-Supported-Platform
