### ISSUE TITLE
`Issue` Thread Name doesn't accept `Code Markdown`

### ISSUE THREAD

**Issue by 8227846265** [vector-im/element-web#25199] opened 2023-04-25 00:09 UTC
### Where are you starting? What can you see?
- Send a message like this `Test` Thread Name
- Then convert this into a thread.

#### What did you expect?

The Thread Name should follow the format of the original message.

#### What happened instead?

If you go back to the `Thread List`, `Test` is not formatted on code Markdown but rather just a regular text
![image](https://user-images.githubusercontent.com/66582769/234141057-bcf6def1-e444-4ebd-b0e5-a2a28db628c0.png)

### Operating system

Windows

### Application version

Element version: 1.11.29 Olm version: 3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-04-25 08:35
Duplicate of https://github.com/vector-im/element-web/issues/19945

**Closed by t3chguy** 2023-04-25 08:35 UTC
Labels: T-Defect
