### ISSUE TITLE
"Missing session data" error after disk was full

### ISSUE THREAD

**Issue by davidak** [vector-im/element-web#25463] opened 2023-05-28 12:20 UTC
### Steps to reproduce

1. Open https://app.element.io/
2. See Error

![Screenshot from 2023-05-28 14-18-40](https://github.com/vector-im/element-web/assets/91113/2a7d817c-98aa-4573-92f0-028a98c799b1)

> **Missing session data**
> Some session data, including encrypted message keys, is missing. Sign out and sign in to fix this, restoring keys from backup.
> 
> Your browser likely removed this data when running low on disk space. To help us prevent this in future, please send us logs.

Related issues:

- https://github.com/vector-im/element-web/issues/18423
- https://github.com/vector-im/element-desktop/issues/692

#### What did you expect?

working app

#### What happened instead?

error

### Operating system

NixOS 22.11.4021.54495a4eafe

### Browser information

Chromium 112.0.5615.165

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.11.31
Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

I tried, but it failed (https://github.com/vector-im/element-web/issues/25464).

**Comment by weeman1337** [comment] 2023-05-30 07:34
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-05-30 07:35
Duplicate of https://github.com/vector-im/element-desktop/issues/692

**Closed by weeman1337** 2023-05-30 07:35 UTC
Labels: T-Defect
