### ISSUE TITLE
Element Desktop crashes flatpack

### ISSUE THREAD

**Issue by NukeManDan** [vector-im/element-web#23401] opened 2022-10-03 19:07 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Normal use of app

2. What do you click?
Nothing

2. More steps…
Wait for a random interval

```
flatpak run im.riot.Riot

[3 zypak-helper] Wait found events, but sd-event found none
/home/dan/.var/app/im.riot.Riot/config/Element exists: yes
/home/dan/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 13:08:03.004: Failed to load module "appmenu-gtk-module"
Gtk-Message: 13:08:03.066: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:08:03.066: Failed to load module "canberra-gtk-module"
[3:1003/130803.084238:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1003/130803.084307:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
[54:1003/130417.807291:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
[54:1003/130417.807696:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
/app/bin/element: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

### Outcome

No random hard crashes

### Operating system

Ubuntu

### Application version

1.11.8 

### How did you install the app?

flatpak

### Homeserver

matrix.parity.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-10-03 19:09
Duplicate of https://github.com/vector-im/element-web/issues/20926

**Closed by t3chguy** 2022-10-03 19:09 UTC
Labels: T-Defect
