### ISSUE TITLE
Ignored Users should be made more obvious

### ISSUE THREAD

**Issue by Joybuke** [vector-im/element-web#26462] opened 2023-10-27 23:25 UTC
#### What would you like to do?
When in a room with another user, and that user is set to be ignored, the user who is ignoring ought to easily know that the other user in the conversation is being ignored at a glance. This is so that users who ignore others will have more information present to provide reasoning for messages not being sent. 

#### Why would you like to do it?
While attempting to fix some homeserver communication issues with Matrix.org, I accidentally ignored my own matrix.org account on my homeserver testing account. I was not aware of this until I checked the "Security & Privacy" settings for my homeserver account, only to discover I accidentally ignored myself while doing my work. I was not aware of this fact for quite some time, and it led to me believing there was an issue with my home server. If more information was provided to me that I ignored myself, I could have more quickly resolved the issue for why communication was failing.

In a more conventional situation: a user ignores another user intentionally. If the user who is ignoring wants to talk to the ignored user in a private, the user who is ignoring will have to unignore the user to receive communication. Currently, if you send a message to an ignored user, you won't be aware of the replies the ignored user sends, or that you've even ignored them, unless you go looking for it. This can cause communication break downs in a conventional scenario, where it looks like the ignored user is just not responding to someone, when in reality the user attempting to make contact is just unaware that the other user is being ignored.

This fact can lead to rather inconvenient cases where messages are missed without any reasoning provided. If I am ignoring a user, but wish to make contact, I should be made aware that I am ignoring the other user rather easily, and will need to unignore the user to see messages sent to me.

#### How would you like to achieve it?
I would suggest that a username of an ignored user, in the member's list, have the word "[IGNORED]" appended to it either in a non-default color, in bold, or in italics, so that a user who is ignoring someone can know, at a glance, that said user is being ignored.
An example of what I would suggest being added in the "people" section of room info:
![image](https://github.com/vector-im/element-web/assets/32282125/0c22fcb6-8aad-4579-b041-80710552f4bd)

### Have you considered any alternatives?

If this feature cannot be added, I would instead suggest that, when you attempt to start a room with a singular individual who is being ignored, it alerts you to that fact, and provides you with a button to unignore the individual, and then start the conversation.

**Comment by t3chguy** [comment] 2023-10-28 10:22
Duplicate of https://github.com/vector-im/element-meta/issues/874

**Closed by t3chguy** 2023-10-28 10:22 UTC
Labels: T-Enhancement
