### ISSUE TITLE
A message is incorrectly marked as sent

### ISSUE THREAD

**Issue by fulmicoton** [vector-im/element-web#18953] opened 2021-09-09 01:54 UTC
### Steps to reproduce

I don't know how to reproduce

### What happened?

I was chatting normally.

One of my message started being consistently reordered as the last message.
The person I was talking with never received the message, yet it was marked as sent by the UI.
In the screenshot below, the faulty message is "or something else"

![image](https://user-images.githubusercontent.com/1021506/132608884-d4f6a08b-9dcb-4d98-90f5-14fe2bd12955.png)
![image](https://user-images.githubusercontent.com/1021506/132608891-d5b9c04f-502c-4ef4-b571-d5b0071ad792.png)

### Operating system

Linux

### Application version

The software does not tell. (!?)

### How did you install the app?

apt get 

### Have you submitted a rageshake?

Yes

**Comment by robintown** [comment] 2021-09-09 02:52
Duplicate of https://github.com/vector-im/element-web/issues/17966

**Closed by robintown** 2021-09-09 02:52 UTC
Labels: T-Defect
