### ISSUE TITLE
Adding a sub space does not work

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#25146] opened 2023-04-18 13:08 UTC
### Steps to reproduce

1. Create a private space
2. Right click on the space in the space bar
3. Select „+ -Space“
4. Type any name
5. Click „Add“

#### What did you expect?

Sub space created

#### What happened instead?

Nothing. Unfortunately there is nothing in the logs.

![space](https://user-images.githubusercontent.com/6216686/232786701-e148c053-4dd8-45ac-a5c0-7c0f3b6ce262.gif)

### Operating system

Ubuntu 22.04.2 LTS

### Browser information

Firefox 112.0.1

### URL for webapp

https://develop.element.io/

### Application version

Element version: b31aa1725349-react-7632f3662481-js-a03438f2af0c Olm version: 3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-04-18 13:08
Duplicate of https://github.com/vector-im/element-web/issues/24882

**Closed by t3chguy** 2023-04-18 13:08 UTC
Labels: T-Defect, A-Spaces, A-Subspaces

**Comment by weeman1337** [comment] 2023-04-18 13:10
Great that GitHub does not find the issue when searching for „sub space“ :neutral_face:
