### ISSUE TITLE
Message not staying in correct place in chat

### ISSUE THREAD

**Issue by InezMc** [vector-im/element-web#17756] opened 2021-06-24 13:29 UTC
![image](https://user-images.githubusercontent.com/71381074/123270547-e93c8400-d4f7-11eb-86c5-727f03086b0f.png)

![image](https://user-images.githubusercontent.com/71381074/123271205-81d30400-d4f8-11eb-867a-55155cc49a26.png)

### Description

I sent a message and then following messages would replace it and it would keep dropping down in the chat even though it was at a different time. See on screenshot the times
 

Sending logs. 

Log: sent/    

### Version information

- **Platform**: desktop?

For the desktop app:

- **OS**: Windows,  
- **Version**: 1.x.y

**Comment by t3chguy** [comment] 2021-06-24 13:30
This is a missing /sync echo from your Server, a Synapse bug

**Comment by t3chguy** [comment] 2021-06-24 13:30
Duplicate of https://github.com/vector-im/element-web/issues/17471

**Closed by t3chguy** 2021-06-24 13:30 UTC
