### ISSUE TITLE
Border of video 1:1 PiP blends into background

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15919] opened 2020-12-08 11:09 UTC
<img width="394" alt="Screenshot 2020-12-08 at 10 59 04" src="https://user-images.githubusercontent.com/1294269/101476503-c5dc2e00-3945-11eb-9348-2a71edbd0241.png">

**Comment by SimonBrandner** [comment] 2021-03-14 07:56
Duplicate of [#16570](https://github.com/vector-im/element-web/issues/16570)

**Closed by SimonBrandner** 2021-03-14 07:56 UTC
Labels: A-VoIP, P3, S-Tolerable, T-Defect, X-Needs-Design
