### ISSUE TITLE
Updated element, was told to sign out

### ISSUE THREAD

**Issue by tdfischer** [vector-im/element-web#25068] opened 2023-04-08 07:09 UTC
### Steps to reproduce

I got the popup saying "A new update for element is available" in the app. Clicked "reload", it bounced me back to the page telling me I lost all my keys and needed to sign in again.

This is the third time today this has happened.

#### What did you expect?
To not lose my keys.

#### What happened instead?
Lost my keys, had to be signed out.

### Operating system

Windows

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-04-11 09:38
Duplicate of https://github.com/vector-im/element-web/issues/24560

**Closed by t3chguy** 2023-04-11 09:38 UTC
Labels: T-Defect
