### ISSUE TITLE
Thread missing from thread list

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#26406] opened 2023-10-20 09:26 UTC
### Steps to reproduce

1. (using an alt account that isn't the one that started the thread), I see a thread preview in the timeline that I can click to use the thread
2. looking at the thread list

#### What did you expect?
all threads are in the thread list
#### What happened instead?
that newest thread isn't in the thread list

### Operating system

arch

### Browser information

firefox 118.0.2

### URL for webapp

https://develop.element.io

### Application version

Element version: 80ba22aba28f-react-a63b99f68714-js-7501e28decb4 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-10-23 06:54
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-10-23 06:55
Duplicate of https://github.com/vector-im/element-web/issues/25543

**Closed by weeman1337** 2023-10-23 06:55 UTC
Labels: T-Defect
