### ISSUE TITLE
Element desktop crashes out of nowhere

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#22815] opened 2022-07-12 09:40 UTC
### Steps to reproduce

Nothing really I can discern. The app just crashes while it's running, a good few tens of minutes after having opened it and is syncing happily, without interacting with it at all, or even having the window in focus.

### Outcome

The app crashed

### Operating system

Linux

### Application version

Element version: 1.11.0 Olm version: 3.2.8

### How did you install the app?

Flatpak

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Alkl58** [comment] 2022-07-14 10:19
Not sure, if I have the exact same issue, however Element-Desktop also crashes randomly for me.

**System:** 
Arch Linux (EdeavourOS)

**Application version:**
Element version: 1.11.0 Olm version: 3.2.8

**How did you install the app?**
[AUR](https://archlinux.org/packages/community/x86_64/element-desktop/)

**Journal Log:**
<details>
  <summary>Click to expand!</summary>

```bash
  systemd-coredump[11301]: [🡕] Process 10739 (electron) of user 1000 dumped core.


```
</details>

**Comment by TheJonny** [comment] 2022-07-14 17:12
Also for me, installed via flatpak
```
/app/bin/element: line 10:     3 Trace/breakpoint trap   env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

**Comment by hunicus** [comment] 2022-07-15 05:42
Having the same issue.

1.10.15 works fine...downgrading using [this method](https://github.com/flatpak/flatpak/issues/3097) is how I'm working around this for now.

**Comment by Alkl58** [comment] 2022-07-16 10:38
> Not sure, if I have the exact same issue, however Element-Desktop also crashes randomly for me.
> 
> **System:** Arch Linux (EdeavourOS)
> 
> **Application version:** Element version: 1.11.0 Olm version: 3.2.8
> 
> **How did you install the app?** [AUR](https://archlinux.org/packages/community/x86_64/element-desktop/)
> 
> **Journal Log:**
> Click to expand!

For some unknown reason, crashing disappeared for me in the last 24h. Maybe some external package got updated.

**Comment by BritneyLozza** [comment] 2022-07-16 19:51
Also happening to me. Element will randomly crash and when I load it back up it requires a login. It happened three times in a row so I switched to logging in via browser. 1.10 worked fine.

Please let me know how I can help debug this. I'm not sure how to add my journal.

System: Arch Linux

Application version: Element version: 1.11.0 Olm version: 3.2.8

How did you install the app? [AUR](https://archlinux.org/packages/community/x86_64/element-desktop/)

**Comment by t3chguy** [comment] 2022-07-18 07:22
Has anyone had this crashing with the first-party Debian/Ubuntu Element Desktop builds from https://element.io/get-started#linux-details

**Comment by hunicus** [comment] 2022-07-23 05:56
> 1.10.15 works fine...downgrading using [this method](https://github.com/flatpak/flatpak/issues/3097) is how I'm working around this for now.

Updated to 1.11.0 by mistake, then downgraded to 1.10.15, and now 1.10.15 is crashing randomly for me too.

**Comment by BritneyLozza** [comment] 2022-07-28 17:49
> Also happening to me. Element will randomly crash and when I load it back up it requires a login. It happened three times in a row so I switched to logging in via browser. 1.10 worked fine.
> 
> Please let me know how I can help debug this. I'm not sure how to add my journal.
> 
> System: Arch Linux
> 
> Application version: Element version: 1.11.0 Olm version: 3.2.8
> 
> How did you install the app? Official Arch package.

Also happened with 1.10.15-1

**Comment by NukeManDan** [comment] 2022-07-28 21:16
```
Name            Application ID               Version                 Branch     Installation
Element         im.riot.Riot                 1.11.1                  stable     user
```

Pop!_OS 22.04 LTS

```bash 
flatpak run im.riot.Riot
/home/dan/.var/app/im.riot.Riot/config/Element exists: yes
/home/dan/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 22:08:40.151: Failed to load module "appmenu-gtk-module"
Gtk-Message: 22:08:40.185: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:08:40.185: Failed to load module "canberra-gtk-module"
[3:0728/220840.195452:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0728/220840.195477:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change


# No logs, normal running... then... 

/app/bin/element: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

**Comment by 999eagle** [comment] 2022-08-11 19:41
Same issue for me as well and might also be the same as #22966.

**Comment by Hoeze** [comment] 2022-08-17 19:27
+1... same issue here on Arch linux with latest flatpak

**Comment by NukeManDan** [comment] 2022-09-02 18:47
flatpack again is quite unstable, the last line in the logs might be of use: 

```

$ flatpak run -v im.riot.Riot

F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/.../.local/share/flatpak
F: Opening user flatpak installation at path /home/.../.local/share/flatpak
F: Skipping parental controls check for app/im.riot.Riot/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/.../.local/share/flatpak
F: /home/.../.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/c7252386179c4c1ecf5d93bdaec6ca82852dddfdae7112b5c3177f7424c4a928/files/lib32 does not exist
F: Cleaning up unused container id 3724913426
F: Cleaning up per-app-ID state for im.riot.Riot
F: Cleaning up unused container id 3585824827
F: Cleaning up per-app-ID state for im.riot.Riot
F: Allocated instance id 1397664497
F: Add defaults in dir /im/riot/Riot/
F: Add locks in dir /im/riot/Riot/
F: Xdg dir xdg-music is $HOME (i.e. disabled), ignoring
F: Xdg dir xdg-videos is $HOME (i.e. disabled), ignoring
F: Xdg dir xdg-download is $HOME (i.e. disabled), ignoring
F: Xdg dir xdg-documents is $HOME (i.e. disabled), ignoring
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/.../.config/pulse/client.conf': Error opening file /home/.../.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 42 xdg-dbus-proxy --args=44'
F: Running 'bwrap --args 42 element'
/home/.../.var/app/im.riot.Riot/config/Element exists: yes
/home/.../.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 12:27:39.931: Failed to load module "appmenu-gtk-module"
Gtk-Message: 12:27:39.961: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:27:39.961: Failed to load module "canberra-gtk-module"
[3:0902/122739.969604:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0902/122739.969630:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
/app/bin/element: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

**Comment by theotheroracle** [comment] 2022-09-14 02:27
fedora 36  same issue

**Comment by hunicus** [comment] 2022-09-14 02:43
Was [holding at 1.10.15 until recently](https://github.com/vector-im/element-web/issues/22815#issuecomment-1185195093) but upgraded to 1.11.4 a couple days ago and it's been stable.

Ran a whole bunch of system updates before updating Element this time though...GNOME was one of those updates, so maybe that helped (?).

**Comment by spacescientist** [comment] 2022-09-18 10:18
Today I've started encountering such crashes as well. It's very sudden, no idea why. I'm using element everyday on my desktop running **Manjaro**; the version is element-desktop **1.11-4-1 (Official Repositories (community))**.

Earlier today, it suddenly started complaining about not being able to decrypt messages that were typed only a few minutes earlier, so I restarted it. It then prompted
```
Unable to restore session
We encountered an error trying to restore your previous session.

If you have previously used a more recent version of Element, your session may be incompatible with this version. Close this window and return to the more recent version.

Clearing your browser's storage may fix the problem, but will sign you out and cause any encrypted chat history to become unreadable.
```
I then did "Clear Storage and Sign out", then signed back in and recovered the messages (I tried both with the security key and using another device). However, it crashes just a few seconds later, one or two minutes maximum.

Started with the command line, it doesn't give much information. After loading, it doesn't say anything, and then suddenly:
```
Trace/breakpoint trap (core dumped)
```
or sometimes even no error message in the terminal it seems.

**Comment by spacescientist** [comment] 2022-09-18 10:22
Oh, I've just done another test, starting element-desktop from in the terminal. It didn't ask to restore the session this time, and seemed fine; I sent a test message and it crashed immediately. All within less than 5 seconds. Here's the output:
```
/home/<user>/.config/Element exists: yes
/home/<user>/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en-us,en
Fetching translation json for locale: en-us
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
[6290:0918/122113.561120:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
Trace/breakpoint trap (core dumped)
```
Luckily, there's an extra error message this time. Hopefully that can help.

**Comment by spacescientist** [comment] 2022-09-18 10:44
It was already installed, but **I've reinstalled electron 20.0.3-1** in case something weird had happened there.
No more crashes, nor weird behaviour now.

**Comment by theotheroracle** [comment] 2022-09-19 10:27
i'm not able to reproduce it anymore on ``` Element version: 1.11.5
Olm version: 3.2.12 ```

**Comment by t3chguy** [comment] 2022-09-20 09:08
Duplicate of https://github.com/vector-im/element-web/issues/22690

**Closed by t3chguy** 2022-09-20 09:08 UTC
Labels: T-Defect, Z-Platform-Specific, S-Critical, A-Electron, Z-Upstream, O-Uncommon, Z-Crash, X-Community-Supported-Platform
