### ISSUE TITLE
"Can't load this message (m.room.message)" on reply in thread

### ISSUE THREAD

**Issue by dinosmm** [vector-im/element-web#22141] opened 2022-05-11 08:31 UTC
### Steps to reproduce

I replied to a message in the main chat room, and chose to reply in thread, from Element Android.

In Element Web and Element Desktop, in place of my reply I see this:

Can't load this message (m.room.message)

'View source' shows the message text correctly.

#### What did you expect?
I expected to see my threaded reply correctly in the web and desktop clients.

#### What happened instead?
I see the error message:
`Can't load this message (m.room.message)`

Underlying JavaScript error:

```
2022-05-13T10:31:28.021Z E Cannot read properties of null (reading 'getThreads')
TypeError: Cannot read properties of null (reading 'getThreads')
    at new F (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:636300)
    at k.getThreadsRoomState (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:637831)
    at Xe.setupNotificationListener (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~element-web-app.js:2:1047649)
    at Xe.componentDidMount (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~element-web-app.js:2:1052579)
    at hs (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3063847)
    at Cl (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3080905)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3106190)
    at zi (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3022782)
    at Fl (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3077450)
    at hl (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3073561)
```

### Operating system

Windows 10

### Application version

1.10.12

### How did you install the app?

From the official website

### Homeserver

Synapse 1.58.0

### Will you send logs?

Yes

**Comment by markiceman** [comment] 2022-05-11 17:53
I have the same problem. It is last message in thread. 

It is really big problem. Threads in 1.10.12 are unusable.

**Comment by MadLittleMods** [comment] 2022-05-14 00:20
I was able to reproduce with the following:

 1. Start a thread
 1. Add some thread replies
 1. React to one of the replies
 1. Edit the reply you reacted to
 1. Clear cache and refresh
 1. Notice the thread now has a `Can't load this message (m.room.message)`, `Submit logs` (tile error boundary) for the message in question
 
 ```
react_devtools_backend.js:3973 TypeError: Cannot read properties of null (reading 'getMyMembership')
    at ReactionsRow_ReactionsRow.render (ReactionsRow.tsx:170:32)
    at qi (react-dom.production.min.js:187:125)
    at pi (react-dom.production.min.js:186:166)
    at ck (react-dom.production.min.js:269:357)
    at bk (react-dom.production.min.js:250:341)
    at ak (react-dom.production.min.js:250:277)
    at Tj (react-dom.production.min.js:250:138)
    at Lj (react-dom.production.min.js:243:146)
    at react-dom.production.min.js:123:110
    at push.exports.unstable_runWithPriority (scheduler.production.min.js:18:336)
    at gg (react-dom.production.min.js:122:318)
    at jg (react-dom.production.min.js:123:61)
    at ig (react-dom.production.min.js:122:428)
    at Jg (react-dom.production.min.js:237:147)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at TimelinePanel_TimelinePanel.push.C.setState (react.production.min.js:12:356)
    at onLoaded (TimelinePanel.tsx:1279:18)
```

*(spawned from https://github.com/vector-im/element-web/issues/22157#issuecomment-1124338375*)

**Comment by turt2live** [comment] 2022-05-16 21:20
stacktrace converted (loosely):

```
new ThreadsRoomNotificationState()
RoomNotificationStateStore#getThreadsRoomState // from the set call
EventTile#setupNotificationListener
```

this implies that `thread.room` is null, which is scary.

**Comment by turt2live** [comment] 2022-05-16 22:17
I'm unable to find a way to reproduce this, and can't seem to trick it into happening on my local machine. If people see this, please submit logs with a link to the message so we can attempt investigation that way.

It's quite clear from the log traffic that it's happening often, so upgrading occurrence rating.

**Comment by turt2live** [comment] 2022-05-17 03:59
Noting the "should never happen" cases, https://github.com/matrix-org/matrix-js-sdk/pull/2375 attempts to add a more obvious error to locate what is going wrong and https://github.com/matrix-org/matrix-react-sdk/pull/8618 is an extremely long shot at fixing this.

**Comment by markiceman** [comment] 2022-05-17 05:47
What changed from 1.10.11 to 1.10.12? Version 1.10.11 don't have this problem.

**Comment by turt2live** [comment] 2022-05-17 06:02
Far too many changes to consider, unfortunately. There's a dozen things which were fixed or changed about Threads alone.

**Comment by markiceman** [comment] 2022-05-17 06:32
Try "Clear cache and reload".

![obrazek](https://user-images.githubusercontent.com/54726936/168744294-07e19731-d94c-4ddf-af7b-93a223a700d8.png)

**Comment by t3chguy** [comment] 2022-05-17 07:55
> What changed from 1.10.11 to 1.10.12? Version 1.10.11 don't have this problem.

A huge refactoring of how threads got created from being async to sync

**Comment by markiceman** [comment] 2022-05-19 12:02
@t3chguy , @turt2live : Still cannot reproduce?

**Comment by turt2live** [comment] 2022-05-19 17:41
for now, yes. We're collecting more information until we have a cause determined.

Please continue to submit logs when the bug happens.

**Comment by JokerGermany** [comment] 2022-06-14 19:52
![grafik](https://user-images.githubusercontent.com/30293477/173676563-fd3809c4-afa0-4b28-9ff8-62101ec406d2.png)
On all rooms (element-Android, element-web and so on, will send logs)

**Comment by JokerGermany** [comment] 2022-06-14 19:53
![grafik](https://user-images.githubusercontent.com/30293477/173676777-f5d5f2c5-cfc8-4547-8f19-53e05a335b82.png)

**Comment by JokerGermany** [comment] 2022-06-14 19:58
Clearing Cache fixed it

**Comment by turt2live** [comment] 2022-06-14 21:55
@JokerGermany looks like your issue was something else, awkwardly. Fix/mitigation is up at https://github.com/matrix-org/matrix-react-sdk/pull/8845

**Comment by gsouquet** [comment] 2022-08-18 16:53
This will be fixed once we land https://github.com/vector-im/element-meta/issues/196 and https://github.com/vector-im/element-web/issues/22981

**Closed** 2022-10-28 11:48 UTC
Labels: T-Defect, X-Blocked, X-Cannot-Reproduce, S-Major, A-Timeline, Z-Rageshake, Z-Soft-Crash, O-Uncommon, A-Threads

**Comment by christro** [comment] 2023-11-26 17:53
I have the same problems with https://app.element.io in Mac OS: Can't load this message (m.room.message)
