### ISSUE TITLE
Clicking on a user in a group should show me other groups I share with them

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5216] opened 2017-10-11 16:12 UTC
### Description

Currently it brings up a start chat dialog, which is a bit weird. Maybe show a profile page of sorts?

The profile page could be:
* Groups they are in
* Groups I share with them
* Start chat button

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment] 2017-10-12 10:25
One of the key usecases for groups is for finding people to talk to (mirroring a common pattern whereby users navigate to room member lists to find the "right" person to speak with), so I think the 'start chat' dialog will remain a key part of this component.

Seeing what groups you share with a user sounds like a great feature :)

**Comment by turt2live** [comment] 2017-10-12 14:52
Some way to discover more groups would be awesome. Much like liking every page on facebook to associate yourself, it might be desirable to join every group you possibly can.

**Comment by thekyriarchy** [comment] 2017-10-18 21:37
Related to #4228?

**Comment by SimonBrandner** [comment] 2021-06-22 10:01
Duplicate of https://github.com/vector-im/element-web/issues/14339

**Closed by SimonBrandner** 2021-06-22 10:01 UTC
Labels: A-Spaces, P2, T-Enhancement
