### ISSUE TITLE
Allow for desktop audio during screen sharing

### ISSUE THREAD

**Issue by fighuass** [vector-im/element-web#18601] opened 2021-08-17 19:50 UTC
#### What would you like to do?

I would like for Element to feature the ability to allow streaming desktop audio during screen sharing sessions. This way, people who would like to collaborate on things like making music can hear the other person's audio.

#### Why would you like to it?

Currently this seems to be unavailable, and you can only hear the other person's mic. This isn't sufficient for doing things like working together on making music remotely.

#### How would you like to achieve it?

I would suggest adding a setting under Voice & Video that would enable or disable the sharing of desktop audio. Probably this would be achieved by enabling the desktop audio as an additional input alongside the mic input.

**Comment by kittykat** [comment] 2021-08-17 20:10
Thank you for filing this enhancement request. I am going to close it because it is a duplicate of #16657 - please feel free to subscribe to it for updates.

**Closed by kittykat** 2021-08-17 20:10 UTC
Labels: T-Enhancement

**Comment by kittykat** [comment] 2021-08-17 20:17
Duplicate of #16657
