### ISSUE TITLE
Editing a message to contain nothing should delete the message

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-web#14990] opened 2020-08-17 21:00 UTC
**Is your suggestion related to a problem? Please describe.**
I often find it much quicker to press `ArrowUp` + `CTRL+A` + `Backspace` + `Enter` than to move my mouse all the way to the delete button on a message, so I was disappointed to find out that Element actually changes its behaviour from `send` to `insert new line` when the edit field is empty. This is kind of confusing (the behaviour shouldn't change at least), but also could be used better.

**Describe the solution you'd like**
Since editing a message to be empty is basically an attempt at redacting it, Element should automatically redact any message which is edited to be empty. There could still be a confirmation box as is shown when redacting a message in the usual way, with `confirm` focused by default, in order to ensure that this is not done accidentally by pressing enter while re-writing a message. I think this would not only be quicker but also make Element more usable with just a keyboard. 

**Describe alternatives you've considered**
None really. There could be (already is?) a dedicated shortcut, but that's another shortcut to memorise, over something quite intuitive imo.

**Comment by t3chguy** [comment] 2020-08-18 09:51
Duplicate of https://github.com/vector-im/element-web/issues/11024

**Closed by t3chguy** 2020-08-18 09:51 UTC
Labels: suggestion
