### ISSUE TITLE
when 3rd party cookies are disabled the "add widgets" dialog is blank

### ISSUE THREAD

**Issue by select** [vector-im/element-web#16540] opened 2021-02-25 17:43 UTC
### Description

I have 3rd party cookies disabled in my browser. When clicking on `Add widgets, bridges & bots` I only see a blank modal popping up.

![Screenshot from 2021-02-25 18-39-06](https://user-images.githubusercontent.com/1164760/109194032-4f5b0980-7799-11eb-92e8-f7fb9bfa9206.png)

### Steps to reproduce

- Disable 3rd party cookies
- click on `Add widgets, bridges & bots`
### Version information

- **Platform**: web 

For the web app:

- **Browser**: Chrome, & Firefox (both latest)
- **OS**: Ubuntu
- **URL**: https://app.element.io/#/room/#docu-tech-scienence-audius:matrix.org

**Comment by t3chguy** [comment] 2021-02-25 17:51
Duplicate of https://github.com/vector-im/element-web/issues/10288

**Closed by t3chguy** 2021-02-25 17:51 UTC
Labels: bug
