### ISSUE TITLE
Element lost session for unknown reason

### ISSUE THREAD

**Issue by vranki** [vector-im/element-web#24805] opened 2023-03-12 17:57 UTC
### Steps to reproduce

I launched element and got this dialog:

![image](https://user-images.githubusercontent.com/81116/224563154-e6c30749-f5df-4d9c-a509-d162a36abe34.png)

#### What did you expect?

Element starting

#### What happened instead?

Session logout, as in the screenshot.

### Operating system

Ubuntu 22.10

### Application version

1.11.24

### How did you install the app?

Debian packages

### Homeserver

hacklab.fi

### Will you send logs?

Yes

**Comment by vranki** [comment] 2023-03-12 17:59
Btw there is 25 gigs of disk space free currently, so probably that's not the cause.

**Comment by t3chguy** [comment] 2023-03-13 09:16
Duplicate of https://github.com/vector-im/element-web/issues/23123

**Closed by t3chguy** 2023-03-13 09:16 UTC
Labels: T-Defect
