### ISSUE TITLE
Suggestion: Improve direct message UI

### ISSUE THREAD

**Issue by domoritz** [vector-im/element-web#16220] opened 2021-01-20 11:23 UTC
The direct message UI is a lot busier in element compared to other messengers. I don't think the profile images need to be repeated for every message block in a direct conversation with one other person.

**Comment by SimonBrandner** [comment] 2021-01-20 11:51
Related to or duplicate of [#19](https://github.com/vector-im/roadmap/issues/19). Possibly could be improved by [#4635](https://github.com/vector-im/element-web/issues/4635)

**Comment by domoritz** [comment] 2021-01-20 11:58
Thank you for finding the related issues @SimonBrandner. I will leave this issue open since https://github.com/vector-im/roadmap/issues/19 does not cover UI changes and https://github.com/vector-im/element-web/issues/4635 does not address direct messages as being different.

**Closed** 2021-07-20 09:22 UTC
Labels: A-Create-Room, A-DMs, T-Enhancement
