### ISSUE TITLE
Element does not show encrypted messages prior to my join when it should

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#25550] opened 2023-06-09 15:50 UTC
### Steps to reproduce

1. Be invited in an encrypted room with history visibility set to `shared` (the device that sent the invite is also an instance of Element, and to the best of my knowledge has the key-share-on-invite logic enabled)
2. Join
3. Try to read scrollback

#### What did you expect?

Messages prior to my join are visible.

#### What happened instead?

Messages prior to my join are not visible, with this message visible above my invite/join:

![image](https://github.com/vector-im/element-web/assets/5547783/e3284f4c-fde3-4ae5-aa6b-3cf86545b5b3)

However, in the threads tab, I can see messages that are successfully decrypted dating back from several hours before I joined the room. I can also scroll back before my join in Element Android.

### Operating system

Arch Linux

### Browser information

Firefox 114.0

### URL for webapp

app.element.io

### Application version

Element version: 1.11.33, Olm version: 3.2.14

### Homeserver

abolivier.bzh

### Will you send logs?

Yes

**Comment by kittykat** [comment] 2023-06-15 13:41
Duplicate of #25473

**Closed by kittykat** 2023-06-15 13:41 UTC
Labels: T-Defect
