### ISSUE TITLE
Desktop app crashed (`broker_posix` `Recvmsg error: Connection reset by peer (104)`)

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24168] opened 2023-01-05 11:37 UTC
### Steps to reproduce

1. Use the desktop app

#### What did you expect?

It works

#### What happened instead?

It crashed

```
Trace/breakpoint trap (core dumped)
[58814:0105/123420.802706:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
```

### Operating system

Ubuntu 22.04.1 LTS

### Application version

Element Nightly version: 2023010401 Olm version: 3.2.12

### How did you install the app?

https://packages.element.io/debian/

### Homeserver

element.ems.host

### Will you send logs?

Yes

**Comment by e00E** [comment] 2023-01-08 11:28
Copy of my comment on https://github.com/vector-im/element-web/issues/24185 .

I have probably the same issue. It started happening maybe a week ago. Using the element-desktop package on Arch.

I run element-desktop from the shell. The last two lines, that appear immediately before the crash are
```
ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
element-desktop terminated by signal SIGSEGV (Address boundary error)
```
The last line is printed by my shell, not element-desktop.

**Comment by turt2live** [comment] 2023-01-09 23:47
Duplicate of https://github.com/vector-im/element-web/issues/23311

**Closed by turt2live** 2023-01-09 23:47 UTC
Labels: T-Defect, Z-Platform-Specific, S-Major, X-Needs-Investigation, O-Uncommon
