### ISSUE TITLE
Screen Sharing

### ISSUE THREAD

**Issue by linuxtyp** [vector-im/element-web#23850] opened 2022-11-28 10:58 UTC
### Steps to reproduce

If i am in a Group Conference and i click on the screen sharing button, it loads forever. If i am in a call and i click the sharing button the share content menu comes up but if i click on one of the tiles and click share, it just disapeares and there is no screensharing.

### Outcome

The outcome is that the call continues as normal as if i never pressed the screensharing button. In a group call the share content popup just loads forever.

### Operating system

Linux Mint

### Application version

Element version: 1.11.15 Olm version: 3.2.12

### Homeserver

mtmayr.com

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-11-28 11:02
Duplicate of #4880

**Closed by t3chguy** 2022-11-28 11:02 UTC
Labels: T-Defect
