### ISSUE TITLE
database full error

### ISSUE THREAD

**Issue by erkinalp** [vector-im/element-web#26605] opened 2023-11-18 06:47 UTC
### Steps to reproduce

1. Join lots of rooms, including Matrix HQ
2. Use element for a long time
3. If you manage to use it on Wayland without crash to white screen, you face a database too large error later down the road.

#### What did you expect?
Element clears cache instead of settings.

#### What happened instead?
Element desktop cleared settings and threw

"Some session data, including encrypted message keys, is missing. Sign out and sign in to fix this, restoring keys from backup.

Your browser likely removed this data when running low on disk space. To help us prevent this in future, please send us logs."

### Operating system

Ubuntu 22.04 + GNOME 42 + Wayland

### Application version

1.11.49

### How did you install the app?

DPKG/APT

### Homeserver

*irrelevant, as this is a purely client-side issue*

### Will you send logs?

Yes

**Comment by erkinalp** [comment] 2023-11-18 06:50
[rageshake package, repackaged in ZIP as GitHub does not let us upload TARs](https://github.com/vector-im/element-web/files/13399248/rageshake.zip)

**Comment by t3chguy** [comment] 2023-11-20 08:14
Duplicate of https://github.com/vector-im/element-web/issues/18423

**Closed by t3chguy** 2023-11-20 08:14 UTC
Labels: T-Defect
