### ISSUE TITLE
Double count for new messages

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#25851] opened 2023-07-26 14:42 UTC
### Steps to reproduce

1. Receive one message (in a DM)

#### What did you expect?
See one unread message in the left panel for the room

#### What happened instead?
See that unread count is 2 in the left panel for the room

### Browser information

Chromium 113.0.5672.92 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: cc8afed1968f-react-9319911a27ad-js-0e95df5dba26 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-07-26 14:46
Duplicate of https://github.com/vector-im/element-web/issues/25803

**Closed by t3chguy** 2023-07-26 14:46 UTC
Labels: T-Defect
