### ISSUE TITLE
Media ⬅️ navigation ➡️ (buttons, hotkeys)

### ISSUE THREAD

**Issue by yajo** [vector-im/element-web#22618] opened 2022-06-19 13:04 UTC
#### What would you like to do?

Open one picture in a family group and be able to navigate to previous or next pictures without having to go back and forth in the messages.

#### Why would you like to do it?

Maybe I'm just used to it in whatsapp and telegram. It's more comfortable.

#### How would you like to achieve it?

In phone/tablet: swiping.

In desktop: arrow keys on the keyboard, and some nice ⬅️ ➡️ buttons in the UI.

### Have you considered any alternatives?

Close the picture, open the next one. The only alternative AFAIK.

### Additional context

I love element!

**Comment by SimonBrandner** [comment] 2022-06-19 13:47
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/337

**Closed by SimonBrandner** 2022-06-19 13:47 UTC
Labels: T-Enhancement

**Comment by yajo** [comment] 2022-06-21 22:31
Sorry, I promise I searched!
