### ISSUE TITLE
Can't call from desktop element to mobile element

### ISSUE THREAD

**Issue by pretentious7** [vector-im/element-web#16269] opened 2021-01-25 02:30 UTC
### Description

calls from element application on desktop to element on mobile and vice versa fail.

### Steps to reproduce

- call from room on desktop
-  pick up on mobile.

Describe how what happens differs from what you expected.

Logs being sent: yes

### Version information

- **Platform**: desktop, mobile

Desktop
- **OS**:  Ubuntu
- **Version**: 1.7.17

Mobile:
- **OS**: Android 9
-  **Version**: 1.0.12

**Comment by SimonBrandner** [comment] 2021-01-25 06:45
Looks like a duplicate of [#16239](https://github.com/vector-im/element-web/issues/16239)

**Closed** 2021-01-25 10:17 UTC
Labels: bug
