### ISSUE TITLE
drop & drag target needs to be redesigned for Element

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#14589] opened 2020-07-17 14:12 UTC

**Comment by turt2live** [comment] 2020-07-17 14:17
Duplicate of https://github.com/vector-im/riot-web/issues/8614

**Comment by t3chguy** [comment] 2020-07-17 14:27
Is it? That one is about room lists 

This looks to be about 
![image](https://user-images.githubusercontent.com/2403652/87796984-070e5d00-c842-11ea-9e31-5af7e705029e.png)

**Comment by turt2live** [comment] 2020-07-17 14:34
Descriptive titles help :|

**Comment by SimonBrandner** [comment] 2021-04-06 06:07
Closing as this has already happened, see [#5505](https://github.com/matrix-org/matrix-react-sdk/pull/5505)

**Closed by SimonBrandner** 2021-04-06 06:07 UTC
Labels: A-File-Upload, X-Needs-Design
