### ISSUE TITLE
Recursive citations handled incorrectly

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#12460] opened 2020-02-21 14:27 UTC
See https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$hO5FfBiBXvtYWAFrADnEDaADy3J6wsX57qKFeDiyizU?via=matrix.org&via=privacytools.io&via=feneas.org and following.

**Comment by aaronraimist** [comment] 2020-02-21 14:33
More keywords: Quoting a quoted message removes one level of quotedness.

<img width="793" alt="Screen Shot 2020-02-21 at 8 31 38 AM" src="https://user-images.githubusercontent.com/5855073/75042913-ca059080-5484-11ea-9da6-b7fadbd07fcc.png">

**Comment by heylix** [comment] 2020-06-08 13:26
This got worse in 1.6.0. The quotes sometimes get inserted as regular text at the beginning of the line and you don't even get a newline between that and the next thing you write:

![grafik](https://user-images.githubusercontent.com/36211486/84034469-abc39200-a99a-11ea-874c-f93bf77be857.png)

As I see it on the mobile client (RiotX 0.21.0):

![grafik](https://user-images.githubusercontent.com/36211486/84034628-e1687b00-a99a-11ea-8b14-c6afa12463b4.png)

Sometimes it uses the text "in reply to" and sometimes "Als Antwort auf" – so maybe the translations break quotes?

This is the decrypted message:

```
{
  "content": {
    "body": "> <@user1:example.com> > <@user2:example.com> why does it work properly when we try to reproduce it but it shits itself usually\n> \n> I dont really know, maybe we need more quotes referencing each other\n\nI think it's when you use the mobile client",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!Ro0mIdEnntific4tin:example.com/$dLL4x3Y2HDEoTYktLh27NRCer-5HCVZSf61Zi-pLMpo\">Als Antwort auf</a><a href=\"https://matrix.to/#/@user1:example.com\">@user1:example.com</a><br /><mx-reply><blockquote><a href=\"https://matrix.to/#/!Ro0mIdEnntific4tin:example.com/$MD_2l3777HxejAU71tj11Y4_HnWv_bydy36gGeWccJg?via=example.com\">In reply to</a> <a href=\"https://matrix.to/#/@user2:example.com\">@user2:example.com</a><br>why does it work properly when we try to reproduce it but it shits itself usually</blockquote></mx-reply>I dont really know, maybe we need more quotes referencing each other</blockquote></mx-reply>I think it's when you use the mobile client",
    "msgtype": "m.text"
  },
  "room_id": "!Ro0mIdEnntific4tin:example.com",
  "type": "m.room.message"
}
```

Looks like a random `\nl` instead of `\n` gets inserted? You can't really replicate it consistently, sometimes quoting works, sometimes it doesn't…

**Comment by t3chguy** [comment] 2020-06-08 19:52
> Looks like \n isn't always rendered properly? You can't really replicate it consistently, sometimes quoting works, sometimes it doesn't…

Are those broken events even sent by riot-web? There have been riot mobile bugs that look like that but I've never seen such an issue sent by riot-web.

**Comment by heylix** [comment] 2020-06-08 21:33
>Are those broken events even sent by riot-web?

Yes.

>They are a flawed send over the wire, not rendering.

No.

>The decrypted message you shared is different to the faulty one

No.

**Comment by t3chguy** [comment] 2020-06-08 21:42
The event is flawed over the wire as it is a reply without an `m.relates_to` `m.in_reply_to`

![image](https://user-images.githubusercontent.com/2403652/84083163-05e34800-a9d9-11ea-9ff6-a8c87eb5d7a3.png)

The event you shared is fine:
![image](https://user-images.githubusercontent.com/2403652/84083357-5f4b7700-a9d9-11ea-8888-e393065b3612.png)

**Comment by t3chguy** [comment] 2020-06-08 21:43
Your riot android screenshot doesn't even include that message, it is scrolled off the bottom.

**Comment by heylix** [comment] 2020-06-08 22:10
You see how it renders for me in the first screenshot? The Android screenshot is just to show that while quoting a message originating from Android Riot-Web/Desktop doesn't properly render the message. The fact that it seems to render properly when you copy paste it is weird as it's clearly botched at my end.

Copying the message I posted is rendered properly again. So while the message is apparently fine, it still looks weird when I receive it.

I don't know what more information I can give you. If you don't believe me that I can reproduce this when quoting a message on Android, then quoting it on Desktop, so be it.

**Comment by t3chguy** [comment] 2020-06-09 08:57
@heylix upon review, this isn't the right issue for you, this issue is about Quotes, your example shows Replies.

**Comment by Michae94** [comment] 2020-06-10 08:30
same problem than @heylix

**Comment by t3chguy** [comment] 2020-06-12 10:24
It looks to be a RiotX bug with Replies to Replies which creates invalid events. Replying to those invalid events then from any clients creates more invalid events.

**Comment by t3chguy** [comment] 2020-06-18 12:37
The symptom is being tracked as part of https://github.com/vector-im/riot-web/issues/14081

**Comment by Biep** [comment] 2020-07-28 21:11
A maybe related issue:
A line with just `===` on it breaks citing.  The lines after it become an independent citation.

**Comment by t3chguy** [comment] 2022-03-10 13:18
This is fixed on develop

**Closed by t3chguy** 2022-03-10 13:18 UTC
Labels: T-Defect, A-Composer
