### ISSUE TITLE
Element needs a correct styles for h1-h7

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24645] opened 2023-02-24 13:48 UTC
### Your use case

![image](https://user-images.githubusercontent.com/24779886/221194537-32db8861-c492-4870-8a77-f2dac6b56020.png)

As you see. H1-H3 are same, H5-H6 too. I ask for new styles for h1-h7.

**Comment by t3chguy** [comment] 2023-02-24 13:49
Duplicate of https://github.com/vector-im/element-web/issues/19551

**Closed by t3chguy** 2023-02-24 13:49 UTC
Labels: T-Enhancement
