### ISSUE TITLE
emoji 13 polar bear ligature gets confused in CIDER on Chrome

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13939] opened 2020-06-05 20:28 UTC
🐻‍❄️

**Comment by ara4n** [comment] 2020-06-05 20:29
but black cat is okay, despite being cat with a black modifier... 🐈‍⬛

**Comment by rgpublic** [comment] 2020-12-08 17:38
Happens also in the standalone Electron app. Only the polar bear is affected.

**Comment by t3chguy** [comment] 2020-12-08 22:35
![image](https://user-images.githubusercontent.com/2403652/101549488-ad036500-39a5-11eb-9c43-12e0118c3b83.png)

Looks fine here?

**Comment by aaronraimist** [comment] 2020-12-09 01:04
In the desktop app I see 
<img width="271" src="https://user-images.githubusercontent.com/5855073/101560039-06f53200-3988-11eb-92bb-4de9ffbd33e6.png">

In Firefox I see the polar bear in the composer but if I hit the delete key once then it shows a normal bear and then delete a second time will actually delete it.

**Comment by t3chguy** [comment] 2020-12-09 01:06
Weird, am on Nightly on Macos

**Comment by aaronraimist** [comment] 2020-12-09 01:21
That was on 1.7.15 but I see the same on nightly. Maybe a macOS version thing. I am on macOS 10.14.6 since my computer is too old to upgrade to 10.15.

**Comment by rgpublic** [comment] 2020-12-09 10:40
I'm on Linux and I'm using the electron app. I can select the polar bear by typing :polar... and clicking on the polar bear but in the editor it immediately turns into a bear and a snowflake. LOL. I gotta say this certainly one of the funniest bugs I encountered lately.
![grafik](https://user-images.githubusercontent.com/17726950/101619287-5c2a5580-3a13-11eb-9898-cfc31b02f0c8.png)

**Comment by jryans** [comment] 2020-12-14 10:34
> In Firefox I see the polar bear in the composer but if I hit the delete key once then it shows a normal bear and then delete a second time will actually delete it.

This part I believe has always been the case for all multi-part emoji. (If we want it to change, let's file a separate issue from this one.)

**Comment by robintown** [comment] 2022-01-22 21:20
> > In Firefox I see the polar bear in the composer but if I hit the delete key once then it shows a normal bear and then delete a second time will actually delete it.
> 
> This part I believe has always been the case for all multi-part emoji. (If we want it to change that part, let's file a separate issue from this one.)

Opened https://github.com/vector-im/element-web/issues/20688 for that issue

**Comment by robintown** [comment] 2022-01-23 16:23
Can't reproduce with Element Desktop on Linux. There have been multiple updates to the emoji font in the past year, so I'm sort of inclined to close this, though it would be good to get another confirmation.

![polar bear](https://user-images.githubusercontent.com/48614497/150687754-9c5cddfb-396a-47f1-a257-250ced55b5ae.png)

**Comment by SimonBrandner** [comment] 2022-01-23 16:29
I can't repro either

**Closed** 2022-01-23 16:30 UTC
Labels: T-Defect, Z-Platform-Specific, P2, X-Cannot-Reproduce, S-Minor, A-Composer, A-Emoji
