### ISSUE TITLE
Empty Room for non-empty 1:1 chat

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/element-web#7982] opened 2019-01-02 14:25 UTC
This might be a duplicate, but I was unable to find an existing report.

### Description

A couple times I've seen a 1:1 chat show as "Empty Room" in the sidebar room list until I open that room and speak in it. This is similar behavior to https://github.com/vector-im/riot-android/issues/2671

### Steps to reproduce

- Open Riot
- Clear client cache
- Sometimes some 1:1 rooms show as empty room in the left sidebar list (all rooms in question are e2ee, but most 1:1 rooms I'm in are, so that might be irrelevant).
- Open "empty" room and say something, and the room name is calculated correctly afterward.

Log: Will send after issue number created.

### Version information

- **Platform**: web

For the web app:

- **Browser**: qutebrowser v1.5.2
- **OS**: Void Linux
- **URL**: riot.im/develop

**Comment by lampholder** [comment] 2019-01-03 11:42
/me wonders if this is lazy loading releated

**Comment by non-Jedi** [comment] 2019-01-28 22:07
I'd say most likely. For what it's worth, I haven't seen this again in riot web develop in the past few weeks. It may have been a transient bug. Hopefully the rageshake shows something obvious.

**Comment by Ezwen** [comment] 2019-02-04 12:00
I encountered this problem several times as well, along with two friends of mine. Each time, I could not find any way to make the problem disappear, and had to recreate a new 1-1 room.

**Comment by szimszon** [comment] 2019-02-26 14:37
Have this issue as well. The weird thing is I have it in Android too...

**Comment by Eisfunke** [comment] 2019-04-28 19:10
Still happening – a few weeks ago, an E2E 1:1 chat began showing up as »Empty Chat« for my chat partner.
Now, after reinstalling the Android app because of the re-release, it's the same for me. For both of us it's only happening on Android, on our desktop clients the chats show up correctly with the name of the other person.

**Comment by groug** [comment] 2019-04-29 15:34
This happens to me and a friend 1:1 chat: we experimented a while ago to change the room's name, then removed it. It "restored" the room's name (i.e. his name from my side and my name from his side). On riot web, the room's name is correct (even after trying it on a pristine browser), on newly installed riot on Android, it says "Empty Room".

**Comment by non-Jedi** [comment] 2019-04-29 17:12
Please note that this bug-report is specifically for the in-browser version of Riot. For the bug y'all are experiencing, please see https://github.com/vector-im/riot-android/issues/2671.

**Comment by turt2live** [comment] 2020-08-31 19:37
I'm presuming this is fixed by the new room list as it takes a different approach to detecting this sort of thing - if it's not, please open a reproducible case in a new issue.

**Closed by turt2live** 2020-08-31 19:37 UTC
Labels: bug, major, p1, type:roomlist
