### ISSUE TITLE
Soft crash in notification panel

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#20947] opened 2022-02-06 15:35 UTC
### Steps to reproduce

1. Click notifications bell
2. Soft crash

### Outcome

Rageshake on the way

### Operating system

macOS

### Application version

Nightly

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2022-02-06 15:43
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/20807

**Closed by SimonBrandner** 2022-02-06 15:43 UTC
Labels: T-Defect
