### ISSUE TITLE
Local file storage corrupt on every startup

### ISSUE THREAD

**Issue by dolfandringa** [vector-im/element-web#25631] opened 2023-06-20 01:51 UTC
### Steps to reproduce

1. Startup the application on Fedora 37
2. Nothing, just wait for element.io to start

#### What did you expect?
I wait for element.io to sign in

#### What happened instead?
If I auto start the application from gnome's autostart, I just get a black window (using dark mode) with a spinning icon and nothing else. If I close element.io and start it again, it seems to have removed all local storage, and asks me to login again, and re-verify my device. 
If I don't auto-login, but wait a bit after gnome startup to manually start element.io, I get an error that elemen.io was unable to restore the session, and I can upload the logs. 

![image](https://github.com/vector-im/element-web/assets/1193497/84a54cb7-9e82-44dc-8eb4-5e78250c3e25)

### Operating system

Fedora 37

### Application version

1.11.33

### How did you install the app?

Flatpak

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-06-20 08:17
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-06-20 08:17
Duplicate of https://github.com/vector-im/element-web/issues/24560

**Closed by weeman1337** 2023-06-20 08:17 UTC
Labels: T-Defect
