### ISSUE TITLE
Loading spinner has a ~1px wide white line visible around it on dark theme

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#18136] opened 2021-07-21 08:36 UTC
#### Description

As the title says, the spinner (e.g. when joining a room) has a thin, dotted white line around it, visible only in some frames, which rotates with it when using the dark theme. This is on latest Element Web.

![image](https://user-images.githubusercontent.com/463342/126458004-eeddaed0-1984-4a86-afb3-678d623f2733.png)

#### Steps to reproduce

1. Set dark theme.
2. Try joining a room (or equivalent action which shows the spinner).
3. If the problem doesn't appear, try doing it a few times and/or zooming the page in a bit (not sure if it's necessary).

#### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 89.0.2
- **OS**: Arch Linux
- **URL**: app.element.io (1.7.33)

**Comment by t3chguy** [comment] 2021-07-21 08:39
Duplicate of https://github.com/vector-im/element-web/issues/17642 - this is a Firefox bug with masks and transformations

**Closed by t3chguy** 2021-07-21 08:39 UTC
Labels: T-Defect
