### ISSUE TITLE
New login verification dialog has some dark theme issues

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16839] opened 2021-04-01 05:27 UTC
Shield in the top left is nearly invisible, and the green shield at the end is missing the white fill on the checkmark:

![image](https://user-images.githubusercontent.com/1190097/113247642-abbdb700-9278-11eb-8e2a-1b919fa1ac4c.png)

![image](https://user-images.githubusercontent.com/1190097/113247667-b9733c80-9278-11eb-9113-3a5db0305ada.png)

**Comment by SimonBrandner** [comment] 2021-04-01 05:37
Duplicate of [#15354](https://github.com/vector-im/element-web/issues/15354)

**Closed by SimonBrandner** 2021-04-01 05:37 UTC
