### ISSUE TITLE
Images are missing from E2EE conversation exports

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#22655] opened 2022-06-27 09:48 UTC
### Steps to reproduce

1. Take an encrypted room with a bunch of photos
2. Hit export conversation
3. Note that the zip contains the attachments, but they aren't actually referenced from the HTML (or CSS)

#### What did you expect?

Images should be exported correctly.

#### What happened instead?

Images are missing.

### Operating system

macOS 12

### Application version

Nightly

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-06-27 09:51
Duplicate of https://github.com/vector-im/element-web/issues/22059

**Closed by t3chguy** 2022-06-27 09:51 UTC
Labels: T-Defect
