### ISSUE TITLE
Everything freezes when trying to attach a file 

### ISSUE THREAD

**Issue by mureni** [vector-im/element-web#26334] opened 2023-10-07 23:28 UTC
### Steps to reproduce

1. Ubuntu 20.04 desktop Element app and 22.04 both on different systems, each with most recent release of Element desktop app as of Oct 7, 2023
2. Click "Attachment" to include an attachment (image, video, text file, any size or format, doesn't seem to make a difference)
3. Watch Element "freeze" (main window can be resized and moved, but internal dialog "Upload files" only shows preview of file and no further interaction is possible)

#### The cursor does not change and is entirely unresponsive; keyboard controls to control which element is to be interacted with are unresponsive; cannot close parent window; all input becomes unresponsive. 

I do not know what changed but this happens every time regardless of filetype, file size, contents, etc. it all just becomes unresponsive but does not cause any CPU/RAM/disk access issues. No indication why all user input is halted once a file is ready to upload; preview of file works fine. 

### Operating system

Ubuntu 20.04 and 22.04

### Application version

Element version: 1.11.45 Olm version: 3.2.14

### How did you install the app?

apt repository

### Homeserver

private

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-10-09 07:22
@mureni  Unfortunately I cannot reproduce your issue. Please update your issue with more information: Can you send logs from the settings „help and about“ after a freeze? If we don’t hear back from you in a week, we will close the issue as we need to be able to reproduce it before we can fix it.

**Comment by t3chguy** [comment] 2023-11-29 11:24
Hi, I'm going to close this issue for now as there is not enough info here for us to be able to action it. Please feel welcome to reopen or ask me to reopen the issue if you update the description with steps/screenshots/video/more details so our developers can have a look at it.

**Closed by t3chguy** 2023-11-29 11:24 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, A-File-Upload
