### ISSUE TITLE
Various stumbling blocks for guest users

### ISSUE THREAD

**Issue by LookitheFirst** [vector-im/element-web#15677] opened 2020-11-08 21:01 UTC
# Description

We had an event some time ago, where we used matrix for communicating and many people used guest users to communicate with us. During this event we had many problems with the way guest access works right now which I want to collect in this issue:

- [ ] When a user accesses a room from "Explore Rooms" -> "Preview" and decides they want to join the conversation afterwards, there is only the possibility in the UI to create an account to start writing. When using "Explore Rooms" -> "Join" no account creation is required ![image](https://user-images.githubusercontent.com/6774795/98484476-0134f100-2210-11eb-9712-4a8de68ce8a9.png)

- [ ] All messages sent are printed twice (see #13706) ![image](https://user-images.githubusercontent.com/6774795/98484503-37727080-2210-11eb-8c8b-7ec328b2df44.png)

- [ ] It is impossible to DM a guest account, they are not able to accept the invite, because a "Join the conversation with an account" prompt is in the way ![image](https://user-images.githubusercontent.com/6774795/98484515-54a73f00-2210-11eb-859f-4688bd86b85c.png)

- [ ] When they create an account in order to view a DM, the room is gone since it is associated with the guest account

- [ ] Many UI elements lead to a prompt to create an account (e.g. "Create new Room", "Settings", "Create a new Community", ...). If they cannot use them, can we just hide them? ![image](https://user-images.githubusercontent.com/6774795/98484522-5d981080-2210-11eb-9251-0710f127595b.png)

- [ ] Guests can be invited to communities but cannot accept invites to communities, so can we maybe hide the community UI altogether? ![image](https://user-images.githubusercontent.com/6774795/98484529-756f9480-2210-11eb-95ce-8c4c8b3c1437.png)

- [x] Guests cannot open Jitsi Call windows, because they cannot accept the disclaimer about 3rd party widgets -> **this was fixed recently apparently**

### Version information

Used for the event:
- Element Web v1.7.4
- Synapse v1.19.0

Used for the testing:
- Element Web v1.7.12
- Synapse v1.22.1

**Comment by turt2live** [comment] 2020-11-09 23:07
This is effectively a duplicate of https://github.com/vector-im/element-web/issues/9264

**Closed by turt2live** 2020-11-09 23:07 UTC
Labels: bug, ui/ux

**Comment by LookitheFirst** [comment] 2020-11-10 07:10
Can you please elaborate how these two issues are the same @turt2live ?

As far as I can see the other issue is talking about improving the Guest experience by reverting behaviour to a time where guest users were required to select a username.

My issue is about the various bugs I encountered while using Element with Guest users. I quickly read through the other thread and the only topic that is overlapping with this one seems to be 

> When they create an account in order to view a DM, the room is gone since it is associated with the guest account

That's not enough to just close this issue as a duplicate, especially since the other issue is about a feature request and this issue is about bug fixes, which IMO have a much higher priority.

**Comment by turt2live** [comment] 2020-11-10 14:08
9264 is our issue for reintroducing guest support to the app. We don't currently have a supported mode of operation for guests, therefore any bugs are generally expected.
