### ISSUE TITLE
Move composer/room tooltips to the top/bottom instead of the left

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#20266] opened 2021-12-19 20:47 UTC
![Tooltip composer](https://user-images.githubusercontent.com/47475676/146690231-718b7671-8f74-42c2-801a-a127e86abcee.png)
![Tooltip room](https://user-images.githubusercontent.com/47475676/146690234-80bad5ac-ecd4-4dff-87fd-5084bab82a4c.png)
Currently, the composer/room tooltips are on the left, it would be better if it doesn't block the other buttons (moving the composer tooltips to the top, and moving the room tooltips to the bottom)

**Comment by t3chguy** [comment] 2021-12-20 09:13
Duplicate of https://github.com/vector-im/element-web/issues/11486

**Closed by t3chguy** 2021-12-20 09:13 UTC
