### ISSUE TITLE
Hide spaces bar

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#19191] opened 2021-09-27 17:19 UTC
#### What would you like to do?
Hide the spaces bar

#### Why would you like to do it?
Because when only in one space, it'll take up horizontal real estate for nothing.

#### How would you like to achieve it?
A setting.

### Have you considered any alternatives?

"Display communities instead of spaces" is a workaround. For one session, apparently, and the option is supposedly getting removed in the future.

### Additional context

Next time, please don't forget to also optimize for smaller windows, where real estate is too valuable to just willy-nilly add a whole non-hidable bar that (for many people) isn't even doing anything useful.

**Comment by gdvine** [comment] 2021-09-27 17:30
+1

Never add a big piece of UI like this without option to hide or disable.

**Comment by SimonBrandner** [comment] 2021-09-27 17:43
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/18898

**Closed by SimonBrandner** 2021-09-27 17:43 UTC
Labels: T-Enhancement
