### ISSUE TITLE
one e2e room always shows as unread after refreshing riot/web

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6240] opened 2018-02-23 14:34 UTC
despite there not having been messages there for weeks.

**Comment by lampholder** [comment] 2018-02-28 08:30
Is there a rageshake for this? (Is one likely to be useful?)

**Comment by kittykat** [comment] 2021-11-26 17:08
I'm going to close this issue for now as we cannot reproduce it. Please reopen with more details if this is still happening.

**Closed by kittykat** 2021-11-26 17:08 UTC
Labels: T-Defect, P2, S-Major, A-E2EE, A-Notifications
