### ISSUE TITLE
Stale display names appearing

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#20981] opened 2022-02-08 15:57 UTC
### Steps to reproduce

Current display names are being replaced with old display names, seemingly at random, not in response to users changing their display names.

### Application version

Element Nightly version: 0.0.1-nightly.2022020701 Olm version: 3.2.8

### How did you install the app?

Website

### Homeserver

lant.uk

### Will you send logs?

Yes

**Comment by novocaine** [comment] 2022-02-09 12:02
Saw this in a DM with Susan just now

**Comment by ara4n** [comment] 2022-02-09 13:26
Emma is also seeing this.

**Comment by emmaburton1** [comment] 2022-02-09 13:30
Other people in the same room did not see the stale display name.

**Comment by callahad** [comment] 2022-02-09 13:44
Also saw this in a DM with Shay on Tuesday. Only Web was affected, and only the DM room; Android seemed fine. Displaying hidden events in the timeline did not reveal anything untoward. Refreshing resolved it.

**Comment by rxl881** [comment] 2022-02-09 16:22
I'm still seeing this (I've tried multiple times to reset it). It seems to change for a bit and then revert after a while?

![image](https://user-images.githubusercontent.com/6763606/153243653-5f15c0ca-952f-47b7-8e60-da1bf70a419c.png)

**Comment by emmaburton1** [comment] 2022-02-09 16:41
Happened again to me just now.

**Comment by turt2live** [comment] 2022-02-10 09:59
fwiw, I outright lost the entire profile of someone in a fresh DM. First message received fine, all others did not.

Seemingly once I've lost the user's profile the remote end also sees UISIs from me, even if my previous messages were just fine. 

Feels like it's losing the profile on the first message they send after I've sent/established an Olm session, though unconfirmed.

**Comment by andybalaam** [comment] 2022-02-10 11:31
Just happened to me in a DM with Jake.  I rageshook.

**Comment by dbkr** [comment] 2022-02-10 15:38
Somehow the js-sdk's RoomMember object has got out of sync. I had a room member object where the events array had a member event with the correct display name for the user, but the `name` property on the RoomMember object was an old display name. Reloading the client does indeed fix it.

**Comment by ara4n** [comment] 2022-02-11 12:18
I just got this in a non-DM (my client doesn't think @Erethon is in the Full Mesh VoIP room, so he's getting UISIs from me)

**Comment by dbkr** [comment] 2022-02-11 16:55
Now fairly certain this is the same bug as https://github.com/vector-im/element-web/issues/20962 so we can close this once we confirm that was the cause.

**Comment by dbkr** [comment] 2022-02-14 13:58
No more reports of this since the revert so I'm going to say that this is fixed

**Closed by dbkr** 2022-02-14 13:58 UTC
Labels: T-Defect, X-Regression, S-Major, X-Release-Blocker, A-Timeline, O-Occasional
