### ISSUE TITLE
Add locale/dictionary English (Canada) to Element Desktop

### ISSUE THREAD

**Issue by dnisbetjones** [vector-im/element-web#15688] opened 2020-11-09 22:57 UTC
### Description

Please allow English (Canada) to be added as a locale in Element Desktop.  This is already available in Chromium so it may not require much to do it (?). 

### Version information

- **Platform** Desktop

For the desktop app:
OS: Ubuntu 20.04
Versions
Element version: 1.7.13
olm version: 3.2.1

**Comment by turt2live** [comment] 2020-11-09 23:00
Duplicate of https://github.com/vector-im/element-web/issues/13317

**Closed by turt2live** 2020-11-09 23:00 UTC
