### ISSUE TITLE
Webapp lost state, prompting me to log out and log back in with a backup phrase

### ISSUE THREAD

**Issue by blast-hardcheese** [vector-im/element-web#25366] opened 2023-05-14 16:43 UTC
### Steps to reproduce

I don't have much context here. I've had the same tab open through multiple restarts, no issues for months. The only thing that changed recently is that the new Brave browser version mentioned a "Memory Saver" feature that should only unload tabs when in the background, not purge any data.

#### What did you expect?

Switching back to the Element tab in my browser should have resumed where I was.

#### What happened instead?

I got a message saying state was lost and I had to restore my session from my recovery phrase.

### Operating system

macOS Ventura, 13.1 (22C65)

### Browser information

Brave, Version 1.51.110 Chromium: 113.0.5672.77 (Official Build) (arm64)

### URL for webapp

https://app.element.io/

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by andybalaam** [comment] 2023-05-23 08:46
Brave is not a supported browser. I think this is a duplicate, so closing on that basis.

Duplicate of https://github.com/vector-im/element-web/issues/25147

**Closed by andybalaam** 2023-05-23 08:46 UTC
Labels: T-Defect
