### ISSUE TITLE
Cannot copy-paste in search bar: "Failed to find the following users"

### ISSUE THREAD

**Issue by piegamesde** [vector-im/element-web#19456] opened 2021-10-19 20:37 UTC
### Steps to reproduce

1. Select a user name, e.g. `piegames` and copy it to clipboard.
2. Create a new direct chat, and click on the search bar to enter a name
3. Paste

#### What did you expect?

The previously copied name is pasted into the search bar and searched for.

#### What happened instead?

![Failed to find the following users. The following users might not exist or are invalid, and cannot be invited: piegames](https://user-images.githubusercontent.com/14054505/137986530-e86c427e-c19f-469e-9afb-5279683126c9.png)

### Operating system

Arch Linux

### Browser information

94.0.4606.61 (Official Build) (64-bit)

### URL for webapp

https://app.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by robintown** [comment] 2022-03-21 18:08
Duplicate of https://github.com/vector-im/element-web/issues/17523

**Closed by robintown** 2022-03-21 18:08 UTC
Labels: T-Defect, S-Minor, A-Create-Room, O-Uncommon
