### ISSUE TITLE
Element-R: Message sending is taking several seconds

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-web#26355] opened 2023-10-11 10:17 UTC
### Steps to reproduce

Send a message on webR, it's often taking several seconds to send, even if no key distribution is happening (~5s)

### Outcome

Should be a lot faster

### Operating system

macOS

### Application version

d74186d7adf0-react-c1c6dc00083d-js-f19f0a87933f

### How did you install the app?

https://pr10080--matrix-react-sdk.netlify.app

### Will you send logs?

Yes

**Comment by BillCarsonFr** [comment] 2023-10-11 10:28
See https://github.com/matrix-org/matrix-rust-sdk/issues/281#issuecomment-1564213984

**Comment by richvdh** [comment] 2023-10-16 13:45
Duplicate of #26375

**Closed by richvdh** 2023-10-16 13:45 UTC
Labels: T-Defect, S-Major, O-Frequent, Z-Labs, A-Element-R
