### ISSUE TITLE
Local message search event index failed to initialise

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21158] opened 2022-02-22 11:44 UTC
### Steps to reproduce

1. My local event index got corrupted on Element Desktop
2. Try to follow the options to recover
3. That didn't work, disable search altogether
4. Try to re-enable it

#### What did you expect?

For the event crawler to do it's job

#### What happened instead?

<img width="583" alt="Screen Shot 2022-02-22 at 11 43 24" src="https://user-images.githubusercontent.com/769871/155125597-5240c5bb-01b6-44e3-9f3d-797eaf132670.png">

The above will spin forever...
Looking at the console I can see

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addInitialCheckpoints')
    at EventIndexPanel.tsx:129:15
```

<img width="623" alt="Screen Shot 2022-02-22 at 11 44 04" src="https://user-images.githubusercontent.com/769871/155125701-0b47abf1-89a0-4e2d-98c0-e6d1c6fa0d8e.png">

### Operating system

macOS

### Application version

*No response*

### How did you install the app?

*No response*

### Homeserver

*No response*

### Will you send logs?

No

**Comment by turt2live** [comment] 2022-05-17 04:04
How did it end up getting corrupted?

**Comment by gsouquet** [comment] 2022-05-17 14:05
I don't know. I just know it ended up being corrupted one day.

**Comment by turt2live** [comment] 2022-05-17 18:34
hmm, alright. Without knowing what caused it to become corrupted I don't think we can reasonably look into this. Practically speaking, we could simulate various types of corruption however I don't believe that would actually fix any realistic problems.

Closing for now. If it happens again, please open a new issue with modern information.

**Comment by gsouquet** [comment] 2022-05-18 08:17
@turt2live the issue still happens on my install of Element Nightly
Would be happy to add any info you need. Just not entirely sure how to get my hands on the the ipc logs of the packaged application.

**Comment by gsouquet** [comment] 2022-05-18 09:38
I did look into my logs a bit further and you find that the event index failed to initialise because of an invalid passphrase.
What's weird is that the event index is completely disable as I've tried to reset it in the past.

Somehow ended up in this limbo state. There's probably a way to remove some files on disk to fix that, but I don't think that's a satisfactory workaround to resolve this issue

**Comment by turt2live** [comment] 2022-05-18 13:13
Can we get those logs uploaded to a rageshake?

**Comment by gsouquet** [comment] 2022-05-18 13:52
@turt2live done

**Comment by lampholder** [comment] 2022-05-23 15:09
Seems related - I just got this:

![image](https://user-images.githubusercontent.com/1922197/169850044-7814ffa1-5909-44f3-9d29-08f94433ea18.png)

It feels frustrating to rely on me to click the "unbreak my software" button when Element could have elected to rebuild the index upon discovering that it is (presumably irretrievably) corrupted?

**Comment by lampholder** [comment] 2022-05-23 15:09
I've rage shook

**Comment by lampholder** [comment] 2022-05-23 15:10
Also, the only way to fix this is hidden in an "advanced" dropdown.

**Comment by turt2live** [comment] 2022-07-04 23:44
sending this to the crypto team for now as I think it's their domain. Alternatively, the rust team.

**Comment by t3chguy** [comment] 2023-03-13 08:52
Duplicate of https://github.com/vector-im/element-web/issues/19001

**Closed by t3chguy** 2023-03-13 08:52 UTC
Labels: T-Defect, S-Major, A-E2EE, A-Electron, A-Timeline-Search, A-Indexing, O-Occasional, Team: Crypto
