### ISSUE TITLE
Resizing room list while home is selected doesn't release the mouse

### ISSUE THREAD

**Issue by Sleuth56** [vector-im/element-web#19139] opened 2021-09-22 16:20 UTC
### Steps to reproduce

1. Open element
2. Click on home (Make sure your in the spaces beta)
3. Try to resize the room list
4. Find out that when you release your mouse it's still trying to resize the room list

This isn't a problem if you have a space selected in the side bar. It only effects the home "space"

### Operating system

Manjaro Linux

### Application version

Nightly 2021092201

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin

### Homeserver

NA

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment] 2021-09-22 16:21
This is fixed on develop.element.io

**Comment by turt2live** [comment] 2021-09-22 16:21
Duplicate of https://github.com/vector-im/element-web/issues/19119 - should be fixed in the next nightly.

**Closed** 2021-09-22 16:21 UTC
Labels: T-Defect
