### ISSUE TITLE
Incorrect / Unusual emoji codes

### ISSUE THREAD

**Issue by ad-si** [vector-im/element-web#17007] opened 2021-04-19 19:00 UTC
#### Is your suggestion related to a problem? Please describe.

The shortcode for the 😉 emoji is `:coy:` in Element. However, in every other app I've been using so far it has been `:wink:`. Why is it different? Is this a bug?

There are probably other weird shortcodes, which should be checked as well.

#### Describe the solution you'd like.

Use the usual shortcode

**Comment by SimonBrandner** [comment] 2021-04-19 19:02
Duplicate of [#13857](https://github.com/vector-im/element-web/issues/13857)

**Comment by t3chguy** [comment] 2021-04-19 19:02
Duplicate of https://github.com/vector-im/element-web/issues/13857

**Comment by t3chguy** [comment] 2021-04-19 19:02
arg

**Closed** 2021-04-19 19:02 UTC
Labels: T-Enhancement
