### ISSUE TITLE
Thread summary does not show latest message as shown in the thread panel

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21077] opened 2022-02-14 17:41 UTC
### Steps to reproduce

1. don't include `"rel_type": "io.element.thread"` in a reply to a threaded message

#### What did you expect?
Message in the thread summary is the same as the last one in the thread.

#### What happened instead?
It is not:
![image](https://user-images.githubusercontent.com/2803622/153916925-5a620e0d-23a9-40c2-9c33-34f71bdc270d.png)

Link to the last message in the thread (room is public #element-android:matrix.org): https://matrix.to/#/!AZozoWghOYSIAfaZjJ:matrix.org/$xjYvq8qTWe5td6qGuecUBEZ7_p1zELVhFNmZ9nQrYL4?via=matrix.org&via=privacytools.io&via=tchncs.de

### Operating system

arch

### Application version

Element Nightly version: 2022021401 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.52

### Will you send logs?

No

**Comment by HarHarLinks** [comment] 2022-03-03 09:55
Link to another broken thread: https://matrix.to/#/!UrnolKvyGxLvrqKFmv:amorgan.xyz/$24bkKl7W-myCFI08uKr9fW5qypRp_xz0kRGJcE7yDJk?via=amorgan.xyz&via=matrix.org&via=envs.net

Contrary to repro steps above, all of the events in this thread do have `"rel_type": "io.element.thread"`.

![image](https://user-images.githubusercontent.com/2803622/156540624-e1ef6000-fbf1-4707-8f0c-0f975e22da13.png)

Element Nightly version: 2022030201
Olm version: 3.2.8

**Comment by babolivier** [comment] 2022-03-03 16:21
I've been seeing this too today:

![image](https://user-images.githubusercontent.com/5547783/156606516-184f59ea-70b0-4296-a877-6d3565014f82.png)

Thread sidebar:

![image](https://user-images.githubusercontent.com/5547783/156606551-4186f3c3-6e8c-4459-ac57-c2a7d5debc56.png)

**Comment by HarHarLinks** [comment] 2022-03-03 16:24
Note that in my OP and babolivier's case the count in the thread summary is wrong. In my other case with the correct thread relation, the count is correct.

**Comment by babolivier** [comment] 2022-03-03 16:27
> babolivier's case the count in the thread summary is wrong

Not in mine, it says "2 replies" in the preview which is correct.

**Comment by HarHarLinks** [comment] 2022-03-03 17:00
Ah of course, sorry, I counted the root in yours which of course is wrong.
In that case the common denominator for the count might again be the thread relation.

**Comment by HarHarLinks** [comment] 2022-03-04 16:50
I have just experienced this again, except for perhaps the first time it fixed itself after I wrote more messages to the main TL

**Comment by gsouquet** [comment] 2022-03-08 10:47
Marking as duplicate of https://github.com/vector-im/element-web/issues/21044 to have one canonical source of information

**Closed by gsouquet** 2022-03-08 10:47 UTC
Labels: T-Defect, S-Minor, O-Frequent, A-Threads, Z-Labs
