### ISSUE TITLE
Show community flairs on user menus

### ISSUE THREAD

**Issue by CubeGame** [vector-im/element-web#15841] opened 2020-11-26 20:42 UTC
**Is your suggestion related to a problem? Please describe.**
I'd expect in the room's users menu and individual user info pane to see what community flairs they have displayed, like they do in chat.

**Describe the solution you'd like**
The flairs could be shown in a row of clickable icons like after their name like in chat, or below their user id.
In the user info pane they have a row, or be a list with community names.
An overflow (or just lots) of communities should also be handled, either with a scrollbar or be re-sizeable like the rooms list.

**Additional context**
Element currently looks like this:
Name with flair in chat:
![image](https://user-images.githubusercontent.com/44947101/100389741-18ece180-3026-11eb-8e6a-9a786e4537cb.png)
User info pane:
![image](https://user-images.githubusercontent.com/44947101/100389766-286c2a80-3026-11eb-9d96-ea293334c251.png)

**Comment by t3chguy** [comment] 2020-11-26 20:59
Duplicate of https://github.com/vector-im/element-web/issues/4438

**Closed by t3chguy** 2020-11-26 20:59 UTC
Labels: suggestion
