### ISSUE TITLE
Something went wrong when joining a room directly from a space's list of rooms

### ISSUE THREAD

**Issue by Onihikage** [vector-im/element-web#24400] opened 2023-02-01 17:02 UTC
### Steps to reproduce

I tried to join the Jellyfin General Chat room from the Jellyfin public space using the Join button on that entry in the list of available rooms in the Jellyfin space, and an error page came up instead. Unlike when I joined the Jellyfin Troubleshooting and Jellyfin Announcements rooms, I did not view the channel first and then hit the Join button at the bottom; instead, I used the button directly on that room while viewing the list of rooms.

#### What did you expect?
To join the Jellyfin General Chat channel

#### What happened instead?
An error page came up saying Something Went Wrong and that I ought to submit a bug report.

### Operating system

Windows 11

### Application version

Element 1.11.22

### How did you install the app?

winget

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-02-01 17:05
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2023-02-01 17:05 UTC
Labels: T-Defect
