### ISSUE TITLE
® emoji is illegible

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18673] opened 2021-08-20 16:16 UTC
© and ™ are both fine enough

**Comment by MadLittleMods** [comment] 2021-08-23 22:02
Interestingly, I think the registered trademark ® and copyright © are supposed to be different sizes 🤔 as they appear that way on GitHub, GitLab, StackOverflow, across platforms. But the registered trademark ® in Element is definitely too small (especially non-retina) to make out the "R" like other sites.

Here are some reference screenshots of Element.

Windows 10 Chrome:

![](https://user-images.githubusercontent.com/558581/130524664-78e5dd79-da66-436f-af94-6224e1b064f9.png)

macOS desktop app:

<img width="318" alt="" src="https://user-images.githubusercontent.com/558581/130524702-06621a45-fcb3-4f9b-9ef6-2e15314a2678.png">

**Comment by robintown** [comment] 2022-01-23 17:08
![Screenshot 2022-01-23 at 12-06-29 Element  1  Test room](https://user-images.githubusercontent.com/48614497/150689642-12422e75-dd57-4bc6-9b9f-1e65a6dd893e.png)

When the :registered: emoji is rendered with Twemoji, it looks fine. The fact that it doesn't render with Twemoji on Chrome is a duplicate of https://github.com/vector-im/element-web/issues/20043.

**Closed by robintown** 2022-01-23 17:08 UTC
Labels: T-Defect, S-Tolerable, A-Emoji, O-Uncommon
