### ISSUE TITLE
Element R: "DomException UnknownError (0)" in console

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#26473] opened 2023-10-31 11:00 UTC
### Steps to reproduce

1. Using Element R via a new login on develop.element.io
2. Using the app normally, and it appears to work well
3. Look at the console

#### What did you expect?

No errors

#### What happened instead?

Lots of messages like this:

```
Uncaught (in promise) Error: DomException UnknownError (0): The operation failed for reasons unrelated to the database itself and not covered by any other error code.
    __wbindgen_error_new matrix_sdk_crypto_wasm.js:6834
    __wbg_adapter_59 matrix_sdk_crypto_wasm.js:274
    real matrix_sdk_crypto_wasm.js:216
    promise callback*1408/</module.exports.__wbg_then_ec5db6d509eb475f matrix_sdk_crypto_wasm.js:7636
    __wbg_adapter_56 matrix_sdk_crypto_wasm.js:270
    real matrix_sdk_crypto_wasm.js:252
    __wbg_setonerror_019196fbce756cc0 matrix_sdk_crypto_wasm.js:7332
    __wbg_adapter_59 matrix_sdk_crypto_wasm.js:274
    real matrix_sdk_crypto_wasm.js:216
    promise callback*1408/</module.exports.__wbg_then_ec5db6d509eb475f matrix_sdk_crypto_wasm.js:7636
    __wbg_adapter_658 matrix_sdk_crypto_wasm.js:334
    cb0 matrix_sdk_crypto_wasm.js:7618
    __wbg_new_9d3a9ce4282a18a8 matrix_sdk_crypto_wasm.js:7623
    backupRoomKeys matrix_sdk_crypto_wasm.js:4010
    backupKeysLoop backup.ts:276
matrix_sdk_crypto_wasm.js:6834
```

### Operating system

Ubuntu 22.04

### Browser information

Firefox 119.0

### URL for webapp

https://develop.element.io

### Application version

Element version: 56bdaaf2f2b7-react-860764c05764-js-e0dacf75299a Crypto version: Rust SDK 0.6.0, Vodozemac 0.5.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by richvdh** [comment] 2023-11-07 14:34
This is odd. The error seems to reflect some indexeddb failure, in the depths of the key backup loop. (Specifically, I think it is happening in `CryptoStore::inbound_group_sessions_for_backup`).

Could be related to https://github.com/vector-im/element-web/issues/26488, maybe?

We could do with improving the logging in this area of the codebase, anyway. This is a particular highlight:

```
2023-10-31T09:59:55.434Z D Starting loop for 1.
```

**Comment by richvdh** [comment] 2023-12-06 17:37
I think this has now turned into

```
Backup: Error processing backup request for rust crypto-sdk Error: failed to read or write to the crypto store DomException UnknownError (0): The operation failed for reasons unrelated to the database itself and not covered by any other error code."
```

... and I think it's due to https://github.com/vector-im/element-web/issues/26488. Closing as a duplicate of that for now.

**Closed by richvdh** 2023-12-06 17:37 UTC
Labels: T-Defect, S-Tolerable, O-Occasional, Z-Labs, A-Element-R, Z-Element-R-Blocker

**Comment by andybalaam** [comment] 2023-12-06 17:53
Confirming I see that message too.
