### ISSUE TITLE
Why history messages are not visible to invited users in encrypted rooms even after settings says it should

### ISSUE THREAD

**Issue by MrJai** [vector-im/element-web#21072] opened 2022-02-14 16:53 UTC
### Steps to reproduce

**Background:**

We are trying to implement a mobile app with end-to-end encryption but providing past messages history to new members joining the group is a key thing we need. 

**Plan:**

We were planning to use olm/megolm and matrix-SDK, and then we tried to test our use cases with [Element.io](http://element.io/) (web, desktop, ios, android) versions.

**Issue:**

History wasn’t available for new users in a room. Since then we have been studying it, the documentation says it should work by sharing keys, but it is not working with Element clients. We have tried all possibilities of inviting a user from different clients and then accepting the invitation from different clients but the new user is either not able to see the history at all or it is broken (like some messages say keys are not shared, or not possible to show).

We are following these issues from different related repositories, they are also talking about similar or same issues and are not able to fix the issue, but **we are not sure what are the reasons for not being able to fix/implement this feature of sharing history with new group member by sharing the keys.**

[element-web#2286](https://github.com/vector-im/element-web/issues/2286)

[element-web#2713](https://github.com/vector-im/element-web/issues/2713)

[matrix-react-sdk#5763](https://github.com/matrix-org/matrix-react-sdk/pull/5763)

**Request:**

It will be a huge favour if anyone of you can document the reasons why we have not been able to implement this feature till now, what are the issues that even when the client and the documentation says that it should work, but it is still broken.

#### What did you expect?
Every new member in the end-to-end encrypted private room should be able to see the history when in the settings we have selected "Anyone" for who can watch the history.

#### What happened instead?
Either it doesn't show anything as if it is a new room and there is no previous message, or it shows waiting for messages/keys, or it shows other warnings/informations but never shows the actual messages.

### Operating system

macOS

### Application version

Element version: 1.10.1 Olm version: 3.2.8

### How did you install the app?

From element.io website I downloaded the dmg file.

### Homeserver

matrix.org.

### Will you send logs?

No

**Comment by MrJai** [comment] 2022-02-15 04:01
- create a new private (invite only) room with end-to-end encryption enabled.
- in the settings select Anyone for who can read history.
- send a few messages.
- invite another user b.
- user b should be able read the messages you sent initially, but either those messages are not visible or there information messages on the message timestamps.

From different issues reported on GitHub we noticed that may be the client that is used to send or receive the invitation, can be one of the reasons of different behavior. But we are not sure. We have tried by keeping both user a and b online when sending and accepting invitation but still of no use.

**Comment by t3chguy** [comment] 2022-02-15 12:08
@MrJai did you send the few messages *AND* invite user B from Element Web/Desktop - are they not hitting https://github.com/vector-im/element-web/issues/16983 ?

**Comment by MrJai** [comment] 2022-02-15 12:14
We are using Element Desktop and Mobile apps mainly for both sending and accepting invite. We hardly used Element web.

**Comment by t3chguy** [comment] 2022-02-15 12:16
Element Web/Desktop support this sharing of keys, Element mobile does not yet

**Comment by MrJai** [comment] 2022-02-15 12:47
Thank you for your response @t3chguy 

I have two questions here

- We were definitely using Element Desktop for sending invites, (later on we did try Element Mobile as well), but it didn't work maybe because we were using Element mobile for accepting invites.
- Why this feature is available in Element Web/Desktop and not in Element Mobile. Is there a limitation or is it not possible to share keys from iOS/Android? I am asking this because the product I am planning to develop is a 100% mobile application (at least for now).

**Comment by t3chguy** [comment] 2022-02-15 13:16
> and not in Element Mobile. Is there a limitation or is it not possible to share keys from iOS/Android? I am asking this because the product I am planning to develop is a 100% mobile application (at least for now).

Just hasn't been implemented yet, you'd need to ask the relevant team (not the element-web tracker) if you have more specific mobile questions however

**Comment by p1gp1g** [comment] 2022-03-21 18:16
These steps highlight 2 different problems related to history visibility :
1. Create a private space
2. Invite user2 to the space
3. Create a private room visible to all member
4. Set history visible to all members
5. Join with user2 : the user can't see the history *
6. Redo 1-4 or leave the previous room with user2
7. Invite user2 to the room
8. User2 has to open another room to load the history *

**Comment by t3chguy** [comment] 2022-03-22 07:28
@p1gp1g 8. is tracked as a different issue https://github.com/vector-im/element-web/issues/16983

**Comment by turt2live** [comment] 2022-04-27 15:05
I think this is largely a duplicate of https://github.com/vector-im/element-web/issues/16983 - if people are running into a different case, please open a new issue with new information and we can triage it from there.

From the comments, it looks like this might be a mobile issue instead as well.

**Closed by turt2live** 2022-04-27 15:05 UTC
Labels: T-Defect, X-Needs-Info, A-E2EE
