### ISSUE TITLE
Application visually glitches on some environments

### ISSUE THREAD

**Issue by HotoRas** [vector-im/element-web#26009] opened 2023-08-19 23:59 UTC
### Steps to reproduce

1. Download, install, and run Element desktop.
2. The issue comes out right away.

##### Environment details (as I expect it's required)
- CPU: Intel(R) Core(TM) i5-13400F
- GPU: NVIDIA GeForce RTX 3070 8GB
- RAM: 32GB (31.8GB avaliable)
- Element installed on 1TB NVME SSD

#### What did you expect?
- The app runs normally, as everyone could expect.
- Every tab functions.

#### What happened instead?
- The screen glitches as like below.
![Glitched Screen (Other rooms)](https://github.com/vector-im/element-web/assets/34373595/e674cd67-c9b8-4832-9dab-aa75da98d746)
![Glitched Screen (Group - Search rooms)](https://github.com/vector-im/element-web/assets/34373595/bd1bc558-08a3-418b-97c4-688cf089e156)
> The second one glitches every time you hover to search box.

![Glitched Screen (Other rooms - Search)](https://github.com/vector-im/element-web/assets/34373595/d711dd3e-53ac-4ecc-b517-df2dc4a8a3b2)
> The extremely glitched in this sc happened when I pressed `Win` + `Shift` + `S` to cap it.

- Every tab still functions.

### Operating system

Windows 11 Home (x64) (10.0.22621.2134)

### Application version

Element version 1.11.39; Olm version 3.2.14

### How did you install the app?

element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-08-21 07:48
Duplicate of https://github.com/vector-im/element-desktop/issues/823

**Closed by t3chguy** 2023-08-21 07:48 UTC
Labels: T-Defect
