### ISSUE TITLE
Changed password on Desktop can not login on Android phone

### ISSUE THREAD

**Issue by AdKiller** [vector-im/element-web#10057] opened 2019-06-14 13:53 UTC
### Description

using latest version of Riot portable: https://portapps.io/app/riot-portable/
Changed password on Desktop, could not login on Android phone

### Steps to reproduce

1. Created account on Desktop (.matrix.org)
2. Logged in on Android phone
3. Changed password on desktop
4. Got logged out on Android, could not log in using new password.
5. Exited and reopened on desktop (stayed logged in)
6. Cleared cache and reload on desktop (stayed logged in)
7. Logged out on desktop
8. Could not login anymore neither on desktop nor Android phone. (username/password incorrect)

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

For the desktop app:

- **OS**: Windows 10 1803 & Android 8.0.0
- **Version**: 1.2.1 (portable v11)

**Comment by dbkr** [comment] 2019-06-14 14:41
have you tried the old password?

**Comment by jryans** [comment] 2019-06-17 11:35
You may also want to try the password reset path as well, assuming that account has an email.

**Comment by kittykat** [comment] 2021-12-21 14:43
I'm going to close this issue for now as we don't have enough information to be able to reproduce it and the app has changed significantly since it was filed.

**Closed by kittykat** 2021-12-21 14:43 UTC
Labels: T-Other
