### ISSUE TITLE
i18n can still go wrong

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#12591] opened 2020-03-02 19:22 UTC
Resurgence of https://github.com/vector-im/riot-web/issues/10859

Possible cause being https://github.com/vector-im/riot-web/issues/10965

**Comment by bwindels** [comment] 2020-03-06 09:38
If it's caused by missing cache, one way to prevent this would be to make all of the assets available offline through our service worker. This would also preload icons, etc. The hardest part probably being creating a list of all of our assets (during build) without causing a maintenance headache, although we might be able to get rid of the content hashes with this approach.

**Comment by t3chguy** [comment] 2020-03-06 09:54
There's https://www.npmjs.com/package/serviceworker-webpack-plugin to auto-populate it with a blacklist

**Comment by bwindels** [comment] 2020-03-06 10:48
Probably best to keep the content hashes though, in case the browser removes your cache but not your (outdated) service worker, you'd end up rerequesting but getting the asset for a newer version.

**Comment by ara4n** [comment] 2020-09-07 11:39
I'm getting reports on this on app.element.io (i.e. not to do with cachebusting going wrong, unless it happened to coincide with a release getting pushed)?

**Comment by mcepl** [comment] 2020-09-07 19:07
@ara4n And BTW, this is me from the email report on this issue.

**Comment by t3chguy** [comment] 2020-10-01 13:09
We had to pull it back out due to other issues it caused: https://github.com/vector-im/element-web/pull/15352

**Comment by Yoric** [comment] 2020-11-28 12:26
Got it twice this week, once on Firefox Stable and once on Firefox Nightly, both times on app.element.io, both times when starting Firefox. In both cases, a reload fixed the issue.

**Comment by lutoma** [comment] 2021-02-04 07:56
This happens to me constantly as well on Firefox.

**Comment by robintown** [comment] 2022-04-25 00:17
Since the only actual reports on this issue are of this occurring in Firefox, closing this as a duplicate of https://github.com/vector-im/element-web/issues/9422

**Closed by robintown** 2022-04-25 00:17 UTC
Labels: T-Defect, P1, I18n, Z-Chronic
