### ISSUE TITLE
Custom emoji reacts

### ISSUE THREAD

**Issue by pharoah-islands** [vector-im/element-web#22322] opened 2022-05-24 10:09 UTC
### Your use case

Implement custom emojis and gifs as reacts to each message.
Please note this is NOT STICKERS.

I am very well aware of the sticker issue, and have searched through all other issues and this is NOT that.
https://github.com/vector-im/element-web/issues/2950

Stickers cannot react to messages. 

When you hover over a message, you will see the emoji button that allows you to react to that message with an emoji pinned to it. This is entirely different from stickers.

What I am suggesting is that custom emojis be allowed through implementing an emoji picker that allows either a png, or a gif.
Discord and Guilded both do this, for an example of what exists already.

 
It might seem a cosmetic unimportant thing, but it is incredibly important for social interaction and context. Reacting to a message or image with a custom emoji adds a deep layer of context that has been well demonstrated on discord and guilded.  

![1627089114_How-to-Create-Custom-Emojis-for-Your-Discord-Server-in](https://user-images.githubusercontent.com/106151850/170007513-d219face-8dba-42db-86a3-e186a32542cc.jpg)

**Comment by t3chguy** [comment] 2022-05-24 10:19
Duplicate of https://github.com/vector-im/element-meta/issues/339

**Closed by t3chguy** 2022-05-24 10:19 UTC
Labels: T-Enhancement
