### ISSUE TITLE
Easier way to filter rooms with pending notifications

### ISSUE THREAD

**Issue by rxl881** [vector-im/element-web#8183] opened 2019-01-21 13:47 UTC
- **Browser**: Chrome
- **OS**: Ubuntu

### Description

I am finding it hard to quickly find rooms with pending notifications (as there are now three small windows that you have to scroll through).

I think that it would be good for an icon or some other control added to the filter rooms input that when clicked on would filter and only display rooms that have unread notification count badges.

![selection_035](https://user-images.githubusercontent.com/6763606/51478334-16af0180-1d83-11e9-827e-9479794c2ed1.png)

**Comment by turt2live** [comment] 2020-08-31 19:34
Duplicate of https://github.com/vector-im/element-web/issues/7185

**Closed by turt2live** 2020-08-31 19:34 UTC
Labels: feature, type:notifications, type:roomlist, ui/ux
