### ISSUE TITLE
Pinned widgets overflow on smaller screen sizes.

### ISSUE THREAD

**Issue by manancodes** [vector-im/element-web#26223] opened 2023-09-22 14:33 UTC
### Steps to reproduce

1. Add 2 or more than 2 widgets in a room.
2. Pin 2 or more than 2 widgets in a room.
3. View it on a screen with smaller width or resize the window to a smaller width.

#### What did you expect?
The widgets should be resized just like a single widget is resized. 
<img width="587" alt="Screenshot 2023-09-22 at 7 58 53 PM" src="https://github.com/vector-im/element-web/assets/54790263/af78186b-1ac7-407f-bce0-dc0b08a26589">

#### What happened instead?
After a certain breakpoint, it overflows out of the container window.
<img width="733" alt="Screenshot 2023-09-22 at 8 00 08 PM" src="https://github.com/vector-im/element-web/assets/54790263/e0e8998c-a956-4705-9af4-ac2379643fb5">

### Operating system

macOS

### Browser information

Edge Browser Version 117.0.2045.31 (Official build) (arm64)

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.11.43, Olm version: 3.2.14

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-09-22 14:47
Duplicate of https://github.com/vector-im/element-web/issues/16200

**Closed by t3chguy** 2023-09-22 14:47 UTC
Labels: T-Defect
