### ISSUE TITLE
Nicknames

### ISSUE THREAD

**Issue by EngineerCorey** [vector-im/element-web#19039] opened 2021-09-14 20:30 UTC
#### What would you like to do?
Be able to locally change nicknames of contacts/users.
#### Why would you like to do it?
Easier to keep track of contacts.
#### How would you like to achieve it?
Ideally some sort of app side feature, potentially adding the ability for manually triggered updates across multiple app instances.

### Have you considered any alternatives?

I am just an end user and thus have not tried anything.

**Comment by robintown** [comment] 2021-09-14 21:24
Duplicate of https://github.com/vector-im/element-web/issues/3130

**Closed by robintown** 2021-09-14 21:24 UTC
Labels: T-Enhancement

**Comment by EngineerCorey** [comment] 2021-09-14 22:13
How is this a duplicate?
Issue [#3130](https://github.com/vector-im/element-web/issues/19039#:~:text=a%20duplicate%20of-,%233130,-44%20minutes%20ago) clearly references custom room naming. In this I'm not talking about **ROOMS**, I'm talking about **INDIVIDUALS**.
In the same way that you can save someone's phone number as any name you like in your phone, so too would I like to locally save their matrix username as whatever I want locally. This would persist across rooms just as your phone contact name persists across apps.

**Comment by robintown** [comment] 2021-09-14 23:08
#3130 is a bit broad in its scope since nicknames are a feature that Matrix doesn't at all have yet, and so it references both room nicknames and user nicknames:

> Have something like an address book where one can give names for people and display these names when the channel is unnamed

See also the spec issue that issue links to, which also references both. If we get closer to the feature becoming a reality and it seems more appropriate to track them separately, we can, but for now I think it's best to just gather the ideas all in one place.
