### ISSUE TITLE
Element desktop tries to render pseudo-URLs and fails.

### ISSUE THREAD

**Issue by antifuchs** [vector-im/element-web#17986] opened 2021-07-13 21:30 UTC
#### Description

I sent a message to a room containing the text `https://host:port/`, which element apparently tries to render as a URL, and fails, displaying "Can't load this message (m.room.message)".

Here's how it started:
![me entering the offending text](https://user-images.githubusercontent.com/11864/125527595-250f33d8-5eeb-49ab-bea8-40fcd02ac1d8.png)

Here's how it's going:
![image](https://user-images.githubusercontent.com/11864/125527632-b42ae2e8-05dc-4e2a-8863-4582900b4481.png)

#### Steps to reproduce

- send `http://host:port` or `https://host:port` to a room
- observe that the message can't be rendered.

I would have expected the message to be rendered, but the URL to not be highlighted as a URL.

#### Version information

- **Platform**: desktop
- 
For the desktop app:

- **OS**: macOS
- **Version**: 1.7.32 (1.7.32)

**Comment by t3chguy** [comment] 2021-07-13 21:31
Pretty sure this is fixed on develop.element.io - cannot reproduce it locally

![image](https://user-images.githubusercontent.com/2403652/125527955-8641fbff-00c7-4762-ae2d-472f54573351.png)

**Closed by t3chguy** 2021-07-13 21:31 UTC
