### ISSUE TITLE
"Add reaction" makes the emoji popup be chopped in half

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#17997] opened 2021-07-14 14:28 UTC
#### Description

The moji popup for the "Add reaction" feature is chopped in half.

![image](https://user-images.githubusercontent.com/152227/125638504-06b2138b-e679-4f9d-b431-adc11d4e0757.png)

At the left edge of this screenshot is also the left edge of the main Element window.

#### Steps to reproduce

1. Add an emoji to a message.
2. An emoji appears underneath. Now press the + next to it.
3. Now that the emoji popup appears farther to the left, it is chopped in half, because that's where the window ends.

Describe how what happens differs from what you expected.

Logs being sent: no (not relevant)

The emoji popup should pop out of the main window. You know, like popups do. The OS-native emoji popup (Win+;) also isn't contained within the application that happens to have called it.

You could also position it a bit more strategically, but ultimately it's a fixed-size popup contained within a variable-size window. There will be a scenario where it doesn't fit no matter how it's designed. This is why popping out of the main window, like all popups and dropdowns an whatnot tend to do, is the best solution.

#### Version information

- **Platform**: desktop
- **OS**: Windows 10 21H1
- **Version**: 1.7.32

**Comment by SimonBrandner** [comment] 2021-07-14 14:41
Duplicate of https://github.com/vector-im/element-web/issues/17527

**Closed by SimonBrandner** 2021-07-14 14:41 UTC
Labels: T-Defect
