### ISSUE TITLE
Element on windows adds desktop shortcut after updating

### ISSUE THREAD

**Issue by aha-tech** [vector-im/element-web#16365] opened 2021-02-04 09:43 UTC
### Description
Using the windows client, whenever Element is updated, it adds a shortcut to the desktop. I delete the shortcut, only for it to reappear after the next update.

### Steps to reproduce

- Install element
- Get no questions about whether or not to add a desktop shortcut
- Delete the shortcut that is created
- Update element
- A new desktop shortcut is created

Describe how what happens differs from what you expected.

Ideally, I'd get asked when installing, whether or not to add a desktop shortcut, but I'm also fine with deleting the desktop shortcut after installation. However, deleting the shortcut every time Element updates (which is fairly frequent) is frustrating.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows 10
- **Version**: 1.7.19

**Comment by t3chguy** [comment] 2021-02-04 15:41
This is internal Squirrel.Windows + electron-builder behaviour

Duplicate of https://github.com/vector-im/element-web/issues/9210

**Closed by t3chguy** 2021-02-04 15:41 UTC
Labels: bug
