### ISSUE TITLE
When I include a URL on Windows Element client it shows HTML spans until I click edit, then Cancel

### ISSUE THREAD

**Issue by jgramp** [vector-im/element-web#23010] opened 2022-08-05 11:57 UTC
### Steps to reproduce

1. Windows Element client.
2. Post a new message.
3. Edit the message including moodle.org (or any URL) in the text.
4. I then see: original text including URLs, these display fine, but any URLs added after editing show the following HTML - [<span><div tabindex="-1" class="mx_TextWithTooltip_target">moodle.org</div></span>](http://moodle.org/)
5. Click edit. Add some text. Click Save. Same problem. The above HTML spans still show.
6. Click edit. Change nothing and click Cancel. The issue resolves. And I now see the moodle.org text as a link and no HTML spans.

When I edit a message and add a URL I see:
![image](https://user-images.githubusercontent.com/8575694/183070417-d90476d7-d453-4122-8a0b-4508d5dcd788.png)

When I edit and save I still see:
![image](https://user-images.githubusercontent.com/8575694/183070444-9489e6e9-a968-48b4-8052-d8e5b2c808e4.png)

When I edit and cancel I then see the correct display:
![image](https://user-images.githubusercontent.com/8575694/183072432-a4dbae05-3454-4ff0-b2a0-bad62bfdcad1.png)

#### What did you expect?
moodle.org to show as a link as soon as I add it to an edited post.

#### What happened instead?
I saw HTML spans and have to edit again and cancel to see the expected output.

### Operating system

Windows.

### Application version

Element version: 1.11.2 Olm version: 3.2.12

### How did you install the app?

I think from element.io/get-started

### Homeserver

moodle.com

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-08-05 15:13
Duplicate of https://github.com/vector-im/element-web/issues/22953

**Closed by t3chguy** 2022-08-05 15:13 UTC
Labels: T-Defect
