### ISSUE TITLE
Can't drag/drop files to upload attachments into a thread

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#19664] opened 2021-11-08 16:32 UTC
### Steps to reproduce

Drag a file into Element and drop it on the thread pane

#### What did you expect?

The file should show up in the thread

#### What happened instead?

The file was uploaded to the main chat

### Operating system

OS X

### Application version

Element Nightly version: 2021110801 Olm version: 3.2.3

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2021-11-08 16:34
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19578

**Closed by SimonBrandner** 2021-11-08 16:34 UTC
Labels: T-Defect, S-Minor, O-Occasional, A-Threads
