### ISSUE TITLE
Dialpad and call hold not working in full screen mode

### ISSUE THREAD

**Issue by AntonDashevsky** [vector-im/element-web#18277] opened 2021-07-28 09:52 UTC
[video with an example](https://i.gyazo.com/8d001d4e2aa2b61c7ece51beda442473.mp4)

#### Steps to reproduce

- Call the apponent in the video call mode
- Expand to full screen
- Try to hold a call - nothing happens - the context menu does not appear

This is probably due to the fact that the context menu does not appear in the same block where `<video />` is located

Logs being sent: no

- **Platform**: web

For the web app:

- **Browser**: Chrome 92.0.4515.107
- **OS**: Windows
- **URL**: private server, v. 1.7.32.1

**Comment by SimonBrandner** [comment] 2021-07-28 11:39
This might actually be quite hard to solve. It is caused by the way we do context menus. The context menu isn't part of the Element that is being full-screened, so the fullscreen view doesn't include the context menu

**Comment by anoadragon453** [comment] 2021-07-28 14:41
Duplicate of https://github.com/vector-im/element-web/issues/17175.

**Closed** 2021-07-28 14:42 UTC
Labels: A-VoIP, P2, T-Defect, X-Needs-Investigation
