### ISSUE TITLE
Copy trailing char

### ISSUE THREAD

**Issue by GFreericks** [vector-im/element-web#20319] opened 2021-12-22 09:38 UTC
### Steps to reproduce

In a chat, when using Shift+Enter to get to the new line, the last character from the previous line was copied behind the carret.

Example:
Type

`Hello world|`

then Shift+Enter

```
Hello world
|d
```

Additional Info:
When there is a character behind the carret, the Problem does not happen:

`Hello|world`

then Shift+Enter

```
Hello
|world
```

Should be easy to reproduce.

Greetings from Leer, Germany
 Gerit Freericks

#### What did you expect?

```
Hello world
|
```

#### What happened instead?

```
Hello world
|d
```

### Operating system

Windows

### Application version

Version Element: 1.9.8 / Version Olm: 3.2.8 / German Version

### How did you install the app?

By update ... originally from https://element.io/get-started#download

### Homeserver

Not sure what info is needed here, maybe the User-Profile "@gfreericks:matrix.prisma-ds.de" helps, but for this issue should this be irrelevant

### Will you send logs?

No

**Comment by gsouquet** [comment] 2021-12-22 14:23
Haven't been able to reproduce this issue so far on either desktop/web on an OSX device

**Comment by GFreericks** [comment] 2021-12-22 14:53
Maybe German Version or Windows Desktop-Version only?

**Comment by SimonBrandner** [comment] 2021-12-22 16:17
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/17215

**Closed by SimonBrandner** 2021-12-22 16:17 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Minor, A-Composer, O-Uncommon
