### ISSUE TITLE
Notification Bell menu is stale and broken on both desktop and web app

### ISSUE THREAD

**Issue by JMoVS** [vector-im/element-web#23579] opened 2022-10-24 11:56 UTC
### Steps to reproduce

1. Normal screen
2. 
<img width="522" alt="grafik" src="https://user-images.githubusercontent.com/7354506/197519775-d593fe2f-3a05-46c3-ae10-77f5b22ad071.png">

3. Click on the bell menu

#### What did you expect?
See latest notifications I received
#### What happened instead?
see stale seemingly random list of notifications

### Operating system

macOS Monteray, but also in Firefox

### Application version

1.11.10

### How did you install the app?

from element.io/getting started

### Homeserver

matrix.phelas.com

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-10-25 09:39
@JMoVS what notifications are missing? Are they in encrypted rooms? This list is entirely built by your homeserver

**Comment by JMoVS** [comment] 2022-10-25 12:30
@t3chguy ah oh, that makes sense - I saw no notice whatsoever that the notifications tab wouldn' show all my notifications and instead the notifications sorted by my homeserver who can't show me encrypted rooms (I think this is not good design as it is right now - either show me a list of received notifications locally or sync them encrypted but the current way just seems broken). Yes, I miss notifications from encrypted rooms.

**Comment by t3chguy** [comment] 2022-10-25 12:31
Duplicate of https://github.com/vector-im/element-web/issues/6874

**Closed by t3chguy** 2022-10-25 12:31 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-Notifications, O-Frequent
