### ISSUE TITLE
Element 1 to 1 video call, also possible if only one of the users has a camera

### ISSUE THREAD

**Issue by horstvogel** [vector-im/element-web#15487] opened 2020-10-18 09:12 UTC
It would be helpful if 1-to-1 video calls also work if only one user had a video camera. For example, a service technician wants to show you the problem via video call, the employee in the office does not have a camera

**Comment by t3chguy** [comment] 2020-10-18 09:31
Duplicate of #466

**Closed** 2020-10-18 09:32 UTC
Labels: suggestion
