### ISSUE TITLE
can't acces app.element.io

### ISSUE THREAD

**Issue by Aadi-mone** [vector-im/element-web#19949] opened 2021-11-30 07:58 UTC
### Steps to reproduce

can't acces app.element.io

### Outcome

can't acces app.element.io

### Operating system

Windows 10

### Application version

um i can't access it then how?

### How did you install the app?

its web

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by novocaine** [comment] 2021-11-30 08:57
Can you provide an error message, screenshot, or provide debug logs?

**Comment by Aadi-mone** [comment] 2021-11-30 09:17
**there is no error message the typical chrome thing, "The site can't be reached"
![784](https://user-images.githubusercontent.com/87631878/144019156-9e40d429-e4e5-450a-9fb3-85fe1192d552.PNG)
and my anti-virus says that your site is sus
![errrr](https://user-images.githubusercontent.com/87631878/144018912-48420c44-d900-4076-9719-c9e8109cf38a.PNG)
I think its blocking your site, but don't know how to stop this freakin avast.**

**Comment by t3chguy** [comment] 2021-11-30 09:25
Closing as duplicate of https://github.com/vector-im/element-web/issues/19872

@Aadi-mone could you fill https://www.avast.com/en-gb/false-positive-file-form.php

**Closed by t3chguy** 2021-11-30 09:25 UTC
Labels: T-Defect

**Comment by Aadi-mone** [comment] 2021-11-30 10:42
sure, thank you.
