### ISSUE TITLE
Debian repo malfunction

### ISSUE THREAD

**Issue by Vitexus** [vector-im/element-web#18369] opened 2021-08-03 16:55 UTC
![image](https://user-images.githubusercontent.com/2621130/128055209-dd4bafbf-aa11-426b-9cc7-cb8fa82d31c9.png)

#### Description

Debian repo described in "Also available on Linux" is not working

#### Steps to reproduce

- copy paste into shell 

```shell
sudo apt install -y wget apt-transport-https

sudo wget -O /usr/share/keyrings/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ default main" | sudo tee /etc/apt/sources.list.d/riot-im.list

sudo apt update

sudo apt install element-desktop
```

**Comment by turt2live** [comment] 2021-08-03 17:00
Duplicate of https://github.com/vector-im/element-web/issues/18345

**Closed by turt2live** 2021-08-03 17:00 UTC
Labels: T-Defect

**Comment by Vitexus** [comment] 2021-08-03 20:25
@turt2live  thank you!
