### ISSUE TITLE
Automatically signed out

### ISSUE THREAD

**Issue by TheEvilSkeleton** [vector-im/element-web#19232] opened 2021-09-30 12:28 UTC
### Steps to reproduce

1. I started the app
2. The app was permanently loading, so I killed the app and relauched it

### What did you expect?

Start as usual

### What happened?

I got signed out saying that it's likely that the storage is full, when that was untrue:

![image](https://user-images.githubusercontent.com/50847364/135455361-b23150a6-bbd2-41b4-82a0-48f55c5683ac.png)

### Operating system

Fedora 35 Silverblue

### Application version

Signed out, can't check version now

### How did you install the app?

From Flathub.

### Homeserver

chat.mozilla.org

### Have you submitted a rageshake?

No

**Comment by TheEvilSkeleton** [comment] 2021-09-30 12:30
Can't even send logs, great.

![image](https://user-images.githubusercontent.com/50847364/135455217-1b368047-2054-4d9f-a06e-90f5ef907e3b.png)

**Comment by novocaine** [comment] 2021-10-01 11:21
If this still reproduces for you, it would be helpful if you could post the content of your logs from developer tools (Ctrl+Shift+I)

**Comment by novocaine** [comment] 2021-10-04 09:14
Those logs don't reveal much, unfortunately - they contain what the app has explicitly logged, but not the unexpected errors which are most likely your issue. If you are able to open developer tools (Ctrl+Shift+I) and tell us what's in there, we might be able to understand the root cause better.

**Comment by novocaine** [comment] 2021-10-04 09:16
Possible duplicate of https://github.com/vector-im/element-web/issues/18423

**Comment by TheEvilSkeleton** [comment] 2021-11-27 02:49
> Those logs don't reveal much, unfortunately - they contain what the app has explicitly logged, but not the unexpected errors which are most likely your issue. If you are able to open developer tools (Ctrl+Shift+I) and tell us what's in the console there, we might be able to understand the root cause better.

Sorry for the late reply! I was able to reproduce it a couple of times but unfortunately I completely forgot about retrieving relevant info. I hope I'll be able to reproduce it and retrieve.

**Comment by TheEvilSkeleton** [comment] 2022-01-06 03:17
> Those logs don't reveal much, unfortunately - they contain what the app has explicitly logged, but not the unexpected errors which are most likely your issue. If you are able to open developer tools (Ctrl+Shift+I) and tell us what's in the console there, we might be able to understand the root cause better.

Is there a standardized way of retrieving log? I can't find anything from Element. I forgot how I retrieved the log last time.

**Comment by MadLittleMods** [comment] 2022-04-23 03:53
@TheEvilSkeleton Here are three different ways to submit debug logs. They all open the same "Submit debug logs" modal. There is also an option to **Download logs** in the modal.

 - `/rageshake`
 - **Settings** -> **Help & About** -> **Submit debug logs**
 - Click on your avatar in the top-left -> **Feedback** -> In the **Report a bug** section -> **debug logs** link

**Comment by TheEvilSkeleton** [comment] 2022-08-03 01:40
My apologies for not explaining well. Occasionally, launching Element gets to this screen:

![image](https://user-images.githubusercontent.com/50847364/182505277-750e059c-4b09-4d63-af16-a61b9e0388e0.png)

It continuously buffers. I can't login, and thus, I can't even provide logs.

**Comment by richvdh** [comment] 2022-11-15 14:19
Seems like a duplicate of https://github.com/vector-im/element-web/issues/21332

**Comment by t3chguy** [comment] 2022-11-15 15:15
@richvdh this issue is older, so wouldn't that be the other way around?

**Comment by richvdh** [comment] 2022-11-15 16:47
yes except that more people seem to be tracking the other, and there seems to have been more investigation over there

**Closed by richvdh** 2022-11-15 16:47 UTC
Labels: T-Defect, X-Needs-Info, S-Critical, A-E2EE, A-E2EE-Key-Backup, A-Logout, O-Uncommon

**Comment by t3chguy** [comment] 2022-11-16 18:24
Soft logout is a specific flow, conflating terms just makes the labels not useful for filtering. Maybe you want to create a label, like `Z-Unexpected-Logout` and apply that for your usage
