### ISSUE TITLE
Blurhash preview ~twice the size of the image

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18240] opened 2021-07-26 16:56 UTC
When the image loads, the timeline jumps

**Comment by Palid** [comment] 2021-07-27 12:29
Duplicate of https://github.com/vector-im/element-web/issues/18254 ?

**Comment by eras** [comment] 2021-08-13 10:58
The issue can be seen by switching to Matrix HQ to this message: https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$_RhglMp7cK4AlNpMi5XLD4QCqm3AdoShRYgzL-a7ac0?via=matrix.org&via=cybre.space&via=libera.chat

It seems to be visible (very, very shortly) when you switch to the room. I guess it shouldn't do the blurhash display at all in that case..

**Comment by t3chguy** [comment] 2021-08-13 11:01
@Palid didn't you fix this issue?

**Comment by SimonBrandner** [comment] 2021-08-13 11:05
> @Palid didn't you fix this issue?

Yeah, I can't see it on nightly

**Comment by Palid** [comment] 2021-08-13 11:06
@t3chguy It escaped my closing, it's fixed. Thanks for catching!

**Closed by Palid** 2021-08-13 11:06 UTC
Labels: T-Defect, A-Media
