### ISSUE TITLE
Trying to accept an invite from a user who's left a room fails badly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#26249] opened 2023-09-27 11:26 UTC
### Steps to reproduce

1. Alice DMs Bob
2. Alice leaves the DM before Bob accepts
3. Bob tries to accept the invite
4. Bob gets a confusing error message about "trying to join a room without any servers specified".

#### What did you expect?

We used to warn sensibly about this: "Conversation no long exists" or similar.

#### What happened instead?

Ideally when Alice leaves the room we'd retract the invite from anyone in it.

### Application version

nightly

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-09-27 11:27
Duplicate of https://github.com/vector-im/element-meta/issues/420

**Closed by t3chguy** 2023-09-27 11:27 UTC
Labels: T-Defect
