### ISSUE TITLE
Translation missing when starting screen sharing session

### ISSUE THREAD

**Issue by HDinger** [vector-im/element-web#19021] opened 2021-09-14 08:45 UTC
### Steps to reproduce

1. Select German as your language
2. Start a video call with another person
3. Within the video call, click on the button to share your screen
4. In the upcoming modal to select the screen, take look at the headlines

### What did you expect?
I expect a complete translation.

### What happened?
It is written, that a translation is missing:
<img width="686" alt="Bildschirmfoto 2021-09-14 um 10 21 42" src="https://user-images.githubusercontent.com/7457313/133225556-00a68373-aca5-477b-a734-14cc76142a16.png">

### Operating system

macOS 11.4

### Application version

v1.8.4

### How did you install the app?

https://element.io/get-started

### Have you submitted a rageshake?

No

**Comment by kittykat** [comment] 2021-09-14 09:03
Thank you for reporting this issue. This is a known defect which we are working to fix. You can work around it for now by going to settings, "Help & About" and using "Clear cache and reload" which is at the bottom of the window.

Duplicate of #9422

**Closed by kittykat** 2021-09-14 09:03 UTC
Labels: T-Defect
