### ISSUE TITLE
Custom shortcuts Desktop (Enhancement request)

### ISSUE THREAD

**Issue by FlanOfHarmony** [vector-im/element-web#20354] opened 2021-12-25 17:52 UTC
#### What would you like to do?
Custom shortcuts
#### Why would you like to do it?
Since we are working on making the `Keyboard Shortcuts` dialog into a settings tab (#19866 and its associated commit #7198), and that a lot of users seem to complain about some shortcuts (sometimes incompatible with the system) why not implement the possibilty of making custom shortcuts ?
#### How would you like to achieve it?
Dunno but I think this should be done using the future settings tab mentionned above

**Comment by SimonBrandner** [comment] 2021-12-27 08:33
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/15076

**Closed by SimonBrandner** 2021-12-27 08:33 UTC
Labels: S-Minor, A-User-Settings, T-Enhancement, A-Shortcuts, O-Occasional
