### ISSUE TITLE
Client side media compression

### ISSUE THREAD

**Issue by hebrides** [vector-im/element-web#16339] opened 2021-02-01 20:56 UTC
**Is your suggestion related to a problem? Please describe.**
When running a Matrix Element on a server, storing media can chew up bandwidth and drive space, especially if you're not integrating AWS or Backblaze into your self-hosted deployment. 

**Describe the solution you'd like**
An optional button to compress media prior to upload on the client. 

**Describe alternatives you've considered**
Considered (also) running a script on the server to compress images through many of the available libraries... that's probably also a good idea for self-hosting too.

**Additional context**
Proposed UX flow:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/7585440/106515033-10d87480-64a3-11eb-8cc2-dee298ea1589.png">

<img width="321" alt="image" src="https://user-images.githubusercontent.com/7585440/106515112-2c437f80-64a3-11eb-97cf-52278945060f.png">

<img width="314" alt="image" src="https://user-images.githubusercontent.com/7585440/106515161-41201300-64a3-11eb-9108-8d9cb1ec78a0.png">

Suggest using the following fast, popular library:

https://www.npmjs.com/package/client-compress

Test here: https://davidmoodie.com/client-compress/

Suggest preselected settings for user to reduce cognitive load of choosing compression amount:
compression: .80 
max width 2550px  (8.5" @ 300 DPI)
max height 3300px (11" @ 300 DPI)

Compressing other media (video, audio) harder, but possible with ffmpeg.wasm: https://github.com/ffmpegwasm/ffmpeg.wasm.

**Comment by t3chguy** [comment] 2021-02-01 21:49
Duplicate of https://github.com/vector-im/element-web/issues/14047

**Closed by t3chguy** 2021-02-01 21:49 UTC
Labels: suggestion
