### ISSUE TITLE
Add multi account support with different homeservers

### ISSUE THREAD

**Issue by ali-shokoohi** [vector-im/element-web#23414] opened 2022-10-04 14:20 UTC
#### What would you like to do?

Multi account support with different home servers

#### Why would you like to do it?

I need to have several accounts for different jobs that I have

#### How would you like to achieve it?

By clicking on the profile picture, select different account in the pop up window

**Comment by weeman1337** [comment] 2022-10-04 14:21
Duplicate of https://github.com/vector-im/element-web/issues/2320

**Closed by weeman1337** 2022-10-04 14:21 UTC
Labels: T-Enhancement
