### ISSUE TITLE
Connections to vector.im and matrix-client.matrix.org while opening element-dekstop

### ISSUE THREAD

**Issue by iambeingtracked** [vector-im/element-web#22081] opened 2022-05-05 09:02 UTC
### Steps to reproduce

1. Open element-dekstop

#### What did you expect?
So it launches, and works without pinging unnecessary things
#### What happened instead?
It pinged vector.im and matrix-client.matrix.org
I would understand if it was necessary. But i tried blocking those in pihole, and element still launched. I'm not using the default integration manager, i'm not using any identity servers. But it still makes those connections

### Operating system

GNU/Linux

### Application version

Element version: 1.10.11 Olm version: 3.2.8

### How did you install the app?

pacman -S element-desktop

### Homeserver

wherelinux.xyz

### Will you send logs?

No

**Comment by aaronraimist** [comment] 2022-05-06 02:33
Duplicate of https://github.com/vector-im/element-web/issues/11655

**Closed by aaronraimist** 2022-05-06 02:33 UTC
Labels: T-Defect
