### ISSUE TITLE
Notifications in thread cause two notifcations

### ISSUE THREAD

**Issue by ctron** [vector-im/element-web#25001] opened 2023-03-31 09:04 UTC
### Steps to reproduce

1. Channel view, someone created a thread
2. Whenever a new message on the thread gets added, I get two notifications: one for the top message which started the thread, and then one more for the actual new message.

#### What did you expect?

I would expect to get only one notification. The new one.

#### What happened instead?

I get two notifications: one for the top message which started the thread, and then one more for the actual new message.

![image](https://user-images.githubusercontent.com/202474/229076613-202c5ebc-3153-4741-b6c3-d63a6095d4de.png)

### Operating system

Fedora Linux

### Browser information

111.0.1 (64-bit)

### URL for webapp

https://element.dentrassi.de

### Application version

Element version: 1.11.24 Olm version: 3.2.12

### Homeserver

Synapse 1.79.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-03-31 09:07
Duplicate of https://github.com/vector-im/element-web/issues/24336

**Closed by t3chguy** 2023-03-31 09:07 UTC
Labels: T-Defect
