### ISSUE TITLE
When scroll to last unread position in room fails, no more messages can be displayed

### ISSUE THREAD

**Issue by JMoVS** [vector-im/element-web#25844] opened 2023-07-25 08:52 UTC
### Steps to reproduce

1. I clicked on the ^ to scroll to the last unread message
2. the view got cleared but an error message popped up

#### What did you expect?
scroll to last unread
#### What happened instead?
<img width="770" alt="grafik" src="https://github.com/vector-im/element-web/assets/7354506/be419420-959c-402b-8272-c806fa9690ee">

if I dismiss this message, I cannot scroll in this room nevertheless and it's not displaying any messages until I switch to another room and then back

<img width="1039" alt="grafik" src="https://github.com/vector-im/element-web/assets/7354506/fecfc56d-958d-4b23-b906-99504e61ccee">

the room where this happened: https://matrix.to/#/#openzfsonmacOS:matrix.org

I'll upload a rageshake - for now it's reproducible.

I see messages => click on the ^ => no longer see messages

### Operating system

macOS

### Application version

Version von Element: 1.11.36 Version von Olm: 3.2.14

### How did you install the app?

element.io

### Will you send logs?

Yes

**Comment by JMoVS** [comment] 2023-07-25 08:54
this happens for me now in multiple rooms (just reproduced it in https://matrix.to/#/#webrtc:matrix.org)

**Comment by t3chguy** [comment] 2023-07-26 11:13
Duplicate of https://github.com/vector-im/element-web/issues/20927

**Closed by t3chguy** 2023-07-26 11:13 UTC
Labels: T-Defect
