### ISSUE TITLE
Hoverover emoji to tell you what they are.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15674] opened 2020-11-08 12:09 UTC
Back when we used emojione we got a free hoverover to tell us the shortcode of a given emoji to help know what they are.  This got removed as per https://github.com/vector-im/element-web/issues/9281#issuecomment-493679366.

Nowadays you can get a similar result by copying the emoji and pasting it in the picker, which will search and thus tell you what it is, but it's worth noting that it's a minor accessibility feature that we lost along the way.

It probably doesn't impact actual screenreaders though, who presumably know how to read out emoji names correctly.

Filing here for completeness.

**Comment by t3chguy** [comment] 2020-11-08 14:47
Duplicate of https://github.com/vector-im/element-web/issues/11176

**Comment by t3chguy** [comment] 2020-11-08 14:47
nvm, wrong issue

**Comment by t3chguy** [comment] 2020-11-08 14:48
Duplicate of https://github.com/vector-im/element-web/issues/9911

**Closed by t3chguy** 2020-11-08 14:48 UTC
Labels: suggestion
