### ISSUE TITLE
Allow setting a custom notification sound globally

### ISSUE THREAD

**Issue by asdil12** [vector-im/element-web#23367] opened 2022-09-28 12:26 UTC
#### What would you like to do?

Currently it is possible to set a custom notification sound per channel. It would be nice to also set the default globally.

#### Why would you like to do it?

I don't like the default sound very much and would like to use a different sound.

#### How would you like to achieve it?

The existing settings dialog could be added to the global settings and be applied if a channel has no custom setting that would then of course overwrite the setting.

**Comment by t3chguy** [comment] 2022-09-28 12:30
Duplicate of https://github.com/vector-im/element-web/issues/5891

**Closed by t3chguy** 2022-09-28 12:30 UTC
Labels: T-Enhancement

**Comment by autoteelar** [comment] 2022-10-26 06:48
duplicate of an ignored issue for 5+ years? lol.


ur supposed to be a tech guy man,, if i was a super cool elit3 hax0r like you i would be patching holes left right and center without barely lifting a finger,

all the time you spent looking for these duplicates you could add genuine features people love and appreciate instead, i just dont understand these devs man
