### ISSUE TITLE
CSP blocks `www.gstatic.cn`

### ISSUE THREAD

**Issue by chengyuhui** [vector-im/element-web#23855] opened 2022-11-29 09:46 UTC
### Steps to reproduce

1. Try to register to servers that require reCAPTCHA.
2. Wait for the captcha to load.

#### What did you expect?
reCAPTCHA loads successfully.
#### What happened instead?
```
Refused to load the script 'https://www.gstatic.cn/recaptcha/releases/Km9gKuG06He-isPsP6saG8cn/recaptcha__zh_cn.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://www.recaptcha.net https://www.gstatic.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
reCAPTCHA uses a different URL to load its scripts if it (somehow) detects that you are in China.

### Operating system

Windows

### Browser information

Chrome 107.0.5304.107

### URL for webapp

app.element.io

### Application version

1.11.15/3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-11-29 09:46
Duplicate of https://github.com/vector-im/element-web/issues/12137

**Closed by t3chguy** 2022-11-29 09:46 UTC
Labels: T-Defect
