### ISSUE TITLE
Fix-up message decoration when mentioned in an edited messages with MSC3952

### ISSUE THREAD

**Issue by clokep** [vector-im/element-web#24923] opened 2023-03-24 12:03 UTC
As part of #24377 initial support for MSC3952 was implemented in #9983. That implementation has a couple of bugs/deficiencies to fix-up around editing messages. (The below all assume you have [MSC3952](https://github.com/matrix-org/matrix-spec-proposals/pull/3952) support enabled.)

----

Currently if you're mentioned in a message it is displayed as red, if that message is then edited (e.g. fix a typo) it is no longer red. The implementation runs push rules over the event and if any event is a highlight than it gets displayed in red. See [`UnwrappedEventTile.shouldHighlight`](https://github.com/matrix-org/matrix-react-sdk/blob/1c9ea423c92d0dff534ed86485d4e73bc3e234de/src/components/views/rooms/EventTile.tsx#L656-L674). This logic needs to be updated somehow for intentional mentions:

* @daniellekirkwood suggested that if the message or any version of it every notified the user (via a highlight) than the event should be red. (See [conversation around here](https://matrix.to/#/!aREzkHGCDRZFBtnnxx:one.ems.host/$-GIzM6kbkv1urG-Zk-S7gDB3tO7_Vu59KQ_M7mN6mbw?via=matrix.org&via=element.io&via=one.ems.host).)
* Another option (which [the MSC](https://github.com/matrix-org/matrix-spec-proposals/blob/clokep/intentional-mentions/proposals/3952-intentional-mentions.md#impact-on-edits) suggests) is that the *latest edit*-only should be checked for mentions. This would be done by checking the mentions property of `m.new_content` instead of the root-level.
	* Implementation-wise, I'm not really sure how to do this, one option could be to "clone" the event, but replace the `content` with `content["m.new_content"]` and then run push rules over that to see if there are any highlights).

While doing this we should be sure to consider both user mentions & room mentions and that the push rules can be disabled by the user.

Similarly to the red text, we sure ensure the state of your own pill (*if one exists*) is consistent with whether the message itself is treated as a highlight or not.

---
[Expected behaviour](https://github.com/vector-im/element-web/issues/24923#issuecomment-1485315439):

1. Someone mentioned me in a message.
2. They then edit the content (not the mentions)
3. My mention is still red

This matches the behavior pre-MSC3952, which is broken by MSC3952's implementation.
This should apply to both pre-MSC3952 and MSC3952 mentions

**Comment by daniellekirkwood** [comment] 2023-03-27 14:00
It's disorienting for users to have a red notification on a room and then to see nothing in the timeline calling their attention... This would happen if the user was mentioned, and then the mention was removed from the timeline message via Edit. In this case, I think the message should stay Red (as it does today) 

This is how the message looks when you are mentioned. 
<img width="252" alt="Screenshot 2023-03-27 at 14 58 20" src="https://user-images.githubusercontent.com/89144281/227961067-e087c8dc-327d-44e0-bec1-e9c26729f6f0.png">

This is the suggestion for what the message looks like when the mention is removed but you were originally tagged in it.
<img width="286" alt="Screenshot 2023-03-27 at 14 59 31" src="https://user-images.githubusercontent.com/89144281/227961415-974cafc8-73b4-4d8b-bf5b-5c3a30475207.png">

We discussed that the all-red messages might be going away soon? 
If this is the case, then the "(edit)" should be red, similar to how a keyword would be highlighted in this case.

**Comment by daniellekirkwood** [comment] 2023-03-27 14:01
@t3chguy did you mention that we were starting to incorp different designs for messages with keywords/replies/mentions?

**Comment by clokep** [comment] 2023-03-27 14:54
> In this case, I think the message should stay Red (as it does today)

It does **not** stay red today. If you remove the mention then it reverts back to normal text.

**Comment by clokep** [comment] 2023-03-27 15:06
> @daniellekirkwood https://github.com/vector-im/element-meta/issues/744

Although we might want to update how this is displayed, I think this is a separate task from updating the logic to ensure it is displayed at the correct time. If it makes sense to do them at the same time, that's great, but I would hate to see the fixes here get stuck behind a design review when they don't really need it.

**Comment by daniellekirkwood** [comment] 2023-03-27 15:11
Ahhh... Ok, then yes, let's move my comment to an Enhancement issue and leave this one as the bug... 

So the definition of done here is: 
- Someone mentioned me in a message
- They then edit the content (not the mentions) 
- My mention is no longer red

**Comment by kerryarchibald** [comment] 2023-03-30 04:59
Updated the ticket description to include the expected behaviour resolved in Patrick's comment.

**Closed** 2023-04-05 02:46 UTC
Labels: T-Defect, A-Notifications, Team: App, Z-GetYourUpdates
