### ISSUE TITLE
Download button in the image fullscreen window does not create the file

### ISSUE THREAD

**Issue by tbabej** [vector-im/element-web#5324] opened 2017-10-17 21:49 UTC
Use case: I want to download the image shared in the channel. Clicking the download link below the image works, but if you:

1. click on the image to see fullscreen version
2. click on the download button in the right panel

a file-system dialog will pop up to save the file (which does not have the correct filename anymore, but is called "download" instead), and if you save it, the file is not created at all.

**Comment by t3chguy** [comment] 2017-10-17 21:59
Needs more information, is this an encrypted room?

**Comment by tbabej** [comment] 2017-10-17 22:18
Correct, e2e encrypted room indeed.

**Comment by linuxmail** [comment] 2018-03-20 13:30
Hello,

we have the same problem with Riot on Windows, Web and Linux version. We have also e2e room.

**Comment by kittykat** [comment] 2021-12-01 12:53
I'm going to close this issue as downloading was fixed and we cannot reproduce it any more. Please file a new issue if you are still experiencing any problems.

**Closed by kittykat** 2021-12-01 12:53 UTC
Labels: T-Defect, P2, S-Minor, A-E2EE, A-Media, X-Needs-Community-Testing
