### ISSUE TITLE
Space settings 

### ISSUE THREAD

**Issue by CodeDoctorDE** [vector-im/element-web#22814] opened 2022-07-12 06:09 UTC
### Steps to reproduce

1. I created a space a few years ago
2. I clicked on the gear icon to open the space settings

#### What did you expect?

A settings dialog.
I created a new space to test and it works perfectly

#### What happened instead?

An error in the console:
```
rageshake.ts:73 TypeError: Cannot read properties of null (reading 'text')
    at _e (SpaceSettingsGeneralTab.tsx:51:35)
    at na (react-dom.production.min.js:157:137)
    at zs (react-dom.production.min.js:267:460)
    at wl (react-dom.production.min.js:250:347)
    at El (react-dom.production.min.js:250:278)
    at yl (react-dom.production.min.js:250:138)
    at hl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at zi (react-dom.production.min.js:122:325)
e.<computed> @ rageshake.ts:73
overrideMethod @ react_devtools_backend.js:4026
os @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
co @ react-dom.production.min.js:131
hs @ react-dom.production.min.js:220
Cl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
zi @ react-dom.production.min.js:122
Fl @ react-dom.production.min.js:252
hl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
zi @ react-dom.production.min.js:122
Gi @ react-dom.production.min.js:123
Vi @ react-dom.production.min.js:122
sl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
f.setState @ react.production.min.js:12
(anonym) @ AsyncWrapper.tsx:63
Promise.then (async)
componentDidMount @ AsyncWrapper.tsx:54
hs @ react-dom.production.min.js:219
Cl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
zi @ react-dom.production.min.js:122
Fl @ react-dom.production.min.js:252
hl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
zi @ react-dom.production.min.js:122
Gi @ react-dom.production.min.js:123
Vi @ react-dom.production.min.js:122
sl @ react-dom.production.min.js:237
Wl @ react-dom.production.min.js:285
Jl @ react-dom.production.min.js:289
t.render @ react-dom.production.min.js:296
reRender @ Modal.tsx:332
await in reRender (async)
createDialogAsync @ Modal.tsx:258
createDialog @ Modal.tsx:109
(anonym) @ DialogOpener.ts:84
e._invokeCallback @ Dispatcher.js:198
e.dispatch @ Dispatcher.js:174
setTimeout (async)
dispatch @ dispatcher.ts:52
N @ space.tsx:61
e @ SpaceContextMenu.tsx:81
qe @ react-dom.production.min.js:52
Ye @ react-dom.production.min.js:52
(anonym) @ react-dom.production.min.js:53
wr @ react-dom.production.min.js:100
xr @ react-dom.production.min.js:101
(anonym) @ react-dom.production.min.js:113
Me @ react-dom.production.min.js:292
(anonym) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Xt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
zi @ react-dom.production.min.js:122
Ie @ react-dom.production.min.js:292
$t @ react-dom.production.min.js:73
rageshake.ts:73 AsyncWrapper promise failed TypeError: Cannot read properties of null (reading 'text')
    at _e (SpaceSettingsGeneralTab.tsx:51:35)
    at na (react-dom.production.min.js:157:137)
    at zs (react-dom.production.min.js:267:460)
    at wl (react-dom.production.min.js:250:347)
    at El (react-dom.production.min.js:250:278)
    at yl (react-dom.production.min.js:250:138)
    at hl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at zi (react-dom.production.min.js:122:325)
```

### Operating system

Windows

### Browser information

Brave 1.40.113, Chromium 103.0.5060.114

### URL for webapp

app.element.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-07-12 06:17
Duplicate of https://github.com/vector-im/element-web/issues/22703

**Closed by t3chguy** 2022-07-12 06:17 UTC
Labels: T-Defect
