### ISSUE TITLE
Something went wrong on joining room

### ISSUE THREAD

**Issue by mpeter50** [vector-im/element-web#24238] opened 2023-01-15 16:14 UTC
### Steps to reproduce

1. I was browsing a space 
2. Clicked Join on a room in the space
3. Element said that something wen wrong

#### What did you expect?
Joining the room

#### What happened instead?
I was requested to report a bug

### Operating system

Windows

### Browser information

Firefox

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-01-16 09:04
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2023-01-16 09:04 UTC
Labels: T-Defect
