### ISSUE TITLE
Flaky cypress test: `crypto.spec > Cryptography > should show the correct shield on edited e2e events ` 

### ISSUE THREAD

**Issue by florianduros** [vector-im/element-web#25619] opened 2023-06-16 12:39 UTC
https://cloud.cypress.io/projects/ppvnzg/runs/15450/test-results/4bd6753c-7fb5-44fc-be4c-f4da5d7aea2c

**Comment by richvdh** [comment] 2023-06-23 10:38
Duplicate of https://github.com/vector-im/element-web/issues/25519

**Closed by richvdh** 2023-06-23 10:38 UTC
Labels: T-Defect, S-Major, A-Testing, A-Developer-Experience, O-Uncommon, Z-Flaky-Test
