### ISSUE TITLE
Spike if we can trivially switch notification defaults

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#17361] opened 2021-05-18 20:01 UTC
We put a bunch of notification work on ice last year. Until we return to it, we should spike if we can trivially (on synapse?) switch the default notifications in rooms to 'Mentions & Keywords':

<img width="451" alt="Screenshot 2021-05-18 at 21 01 17" src="https://user-images.githubusercontent.com/4626865/118715993-39029e00-b81c-11eb-82d3-342fa846a4c3.png">

**Comment by ShadowJonathan** [comment] 2021-07-20 17:10
Would this only apply to public rooms, or also to DMs and private group chats?

**Comment by t3chguy** [comment] 2021-07-20 17:16
Given that push rules differentiate DMs as rooms with exactly 2 members, probably all rooms with >=2 members

**Comment by t3chguy** [comment] 2022-04-28 21:45
Duplicate of https://github.com/vector-im/element-web/issues/3268

**Closed by t3chguy** 2022-04-28 21:45 UTC
Labels: A-Notifications, Z-Synapse, Z-Papercuts, Z-Visibility-1, Z-Impact-1
