### ISSUE TITLE
On Desktop, window dimensions and configuration are not persistent between restarts

### ISSUE THREAD

**Issue by Y0hy0h** [vector-im/element-web#17127] opened 2021-05-01 10:07 UTC
#### Problem
I'm running on Windows 10 and I like to put my chats on the right half of the screen. I can do this by dragging the window to the right border of the screen. With the Signal Desktop app, I can do this once, and when I start Signal the next time, it keeps that window size and position.

With the Element Desktop app, the size and position are lost when I close and restart the app. This is frustrating, because the window always opens up in the middle of the screen with quite a small size, and I keep moving it to the desired place.

Additionally, when the window is resized, the room bar on the left is collapsed to only show the avatars. If I make that bar wider to show the room names, that configuration is also not persistet. So when I close and restart the app and move it into the desired place, the bar collapses and I can't see the room names all over again.

#### Desired solution
The position, size and configuration of the app's window should persist across restarts of the app.

#### Alternatives
No alternatives considered. This is the way that most apps on my machine behave.

#### Context
As far as I understand, both the Signal and Element Desktop apps run on Electron. Therefore I assume that such a behavior is possible with the Element Desktop app as well.

**Comment by t3chguy** [comment] 2021-05-04 09:56
Duplicate of https://github.com/vector-im/element-web/issues/16904

**Closed by t3chguy** 2021-05-04 09:56 UTC
Labels: A-Electron, T-Enhancement, Z-Platform-Specific
