### ISSUE TITLE
Mentions for a user with a slash in the user name don't display correctly through the web app

### ISSUE THREAD

**Issue by bjherbison** [vector-im/element-web#20386] opened 2022-01-02 12:10 UTC
### Steps to reproduce

1. Create a username with a slash.
2. Create a post.
3. Reply to the post.

#### What did you expect?
The reply is displayed correctly.
#### What happened instead?
The reply comes out truncated. In particular, "@m" instead of Nikolaos Chatzikonstantinou.
The posts look correct when viewed from the Android app.

This can be viewed from https://matrix.to/#/!OjiTSQTpPWGpfDenKT:mozilla.org/$u7J_NDywhYk6AnFPT12clfAO82-ndBMAwKYdhxsc9eU?via=mozilla.org&via=matrix.org&via=privacytools.io 
![image](https://user-images.githubusercontent.com/4101902/147875262-91516d05-da6a-4bc7-a0b0-fbedf165f03a.png)
![image](https://user-images.githubusercontent.com/4101902/147875277-1011a979-d245-4b0b-a9a6-4fb6c62b19c9.png)

### Operating system

Ubuntu

### Browser information

Firefox Nightly 97

### URL for webapp

chat.mozilla.org

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### Homeserver

mozilla.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-01-04 10:04
Duplicate of https://github.com/vector-im/element-web/issues/10994

**Closed by t3chguy** 2022-01-04 10:04 UTC
Labels: T-Defect, S-Major, A-Timeline, A-Notifications, Help Wanted, O-Occasional
