### ISSUE TITLE
Mentioning the author of the message when forwarding

### ISSUE THREAD

**Issue by hohlfury** [vector-im/element-web#15535] opened 2020-10-23 09:29 UTC
Hello!
Can I ask you to add a function so that when forwarding messages you can see the nickname of the one from whom this message was forwarded?

**Comment by hohlfury** [comment] 2020-10-23 09:30
I would also like to be able to select several messages for forwarding

**Comment by t3chguy** [comment] 2020-10-23 09:59
Duplicate of https://github.com/vector-im/element-web/issues/4747

**Closed by t3chguy** 2020-10-23 09:59 UTC
Labels: suggestion
