### ISSUE TITLE
UI to show what bridges a room is bridged to

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4320] opened 2017-06-15 10:33 UTC
This could be done via surfacing state events on the room, or perhaps looking at the groups of the users participating in the room?

**Comment by turt2live** [comment] 2017-06-15 15:03
With a little massaging, a solution might also be useful for solving #3087 😇

**Comment by t3chguy** [comment] 2023-03-29 15:18
Duplicate of https://github.com/vector-im/element-web/issues/3963

**Closed by t3chguy** 2023-03-29 15:18 UTC
Labels: P2, T-Enhancement
