### ISSUE TITLE
How and where could we ask the use case question?

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21949] opened 2022-04-27 05:03 UTC
### Your use case

How and where could we ask the user group question [(similar to mobile)](https://www.figma.com/file/xdV4PuI3DlzA1EiBvbrggz/Login-Flow-v2?node-id=2523%3A53958)? 

Could we put it on the [new welcome screen](https://github.com/vector-im/element-web/issues/21947) or is there somewhere else in the [new user flow](https://www.figma.com/file/ZDVvKC8odsa5Jeml9gCuLd/Web%3A-New-User's-Journey?node-id=52%3A19) on web that we could ask?

When we know where and how to ask, we also need to add the same tracking to it as we do on mobile so that we can see all our users on all platforms in posthog

**Comment by gsouquet** [comment] 2022-05-10 07:32
Related, or maybe even duplicate of? https://github.com/vector-im/element-meta/issues/252

**Comment by kittykat** [comment] 2022-05-10 12:39
I think this one would very much depend on what we do with it.

e.g. if we change the default settings based on response? for example, we may want to give community and personal users a dark theme and work users a light theme

**Comment by gsouquet** [comment] 2022-05-18 14:33
Regardless of whether we want to give people a different experience based on why they use Element, we need to be able to identify what use-case they are a part of.

I believe we have to have a way for a homeserver admin to express what kind of users is registering to their instance if they want to. I originally propose to do that in the synapse config, but @t3chguy suggested to do that in the `.well-known` config, which sounds less intrusive
Failing to identify that, we should ask the question as part of the onboarding process. It's not needed as part of the registration flow, but could be asked at a later stage on landing on the welcome screen

**Comment by gsouquet** [comment] 2022-07-22 08:35
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8984

**Closed by gsouquet** 2022-07-22 08:35 UTC
Labels: A-Registration, T-Enhancement, Team: Delight, Z-NewUserJourney
