### ISSUE TITLE
When a Space contains Sub-spaces, the room listing shouldn't show a flat list including all subspace-rooms.

### ISSUE THREAD

**Issue by mattdm** [vector-im/element-web#18905] opened 2021-09-04 16:20 UTC
### Your use case

Our Space has a lot of rooms -- there are probably going to be hundreds. In order to make that not overwhelming, I want to organize these via sub-spaces. However, the UI considers all rooms in sub-spaces to be rooms in the top-level space too. Observe:

![image](https://user-images.githubusercontent.com/123367/132101152-fa7e6353-38b4-4280-a9f0-a68beb1f67b5.png)

(Please ignore visual styling ... this is a new server in progress!)

We don't even have all of our rooms configured yet, and the list is already _basically useless_. It's even worse on mobile.

I would really like one of:

1. Spaces and Rooms displayed as multi-level hierarchy replacing the `> Rooms` list.
2. Room list shows just rooms, but there's a second section `> Spaces` after `> People` and `> Rooms` which lists nested spaces.
3. Long flat list of rooms under `> Rooms`, but broken up into sections with Spaces serving as a section headers

The could also get sub-spaces out of the leftmost bar, allowing that to take up less space.

### Have you considered any alternatives?

We could  create multiple top-level spaces and not use nested spaces. This probably would be fine on our own server, but is less convenient for anyone coming in from a federated server since we'd have to send them a bunch of different space invites.

### Additional context

This is _really_ important to us; one of the chief reasons for moving to Matrix is for ease of use for new users, and this feels like an impediment to that.

**Comment by mattdm** [comment] 2021-09-04 16:26
Note that moving the sub-space list to the second column would have another advantage. Notice how "Contributor Discussions" is truncated to "Contributor Discus..."?

**Comment by mattdm** [comment] 2021-09-05 19:36
Here's a screenshot of the Rust Discord setup:

![image](https://user-images.githubusercontent.com/123367/132139133-262659d3-a614-4fc7-85cb-bc9c5a43f576.png)

This is basically "option 3" of my suggested approaches above. It seems superior in _a lot_ of ways:

* "servers" or "spaces" column on the far left can be very narrow and not take up a lot of the screen.
* There's a clear organization from top to bottom
* Easy to hide the things you're not interested in right now  (click the header to collapse)

This particular approach (as opposed to my "option 2") also has the advantage that you can still see everything at once and move easily between subspaces /sections.

**Comment by mattdm** [comment] 2021-09-05 19:37
@SimonBrandner I notice you've thumbs-downed this suggestion. I'd love to hear the opposing viewpoint, and maybe we can come to something that fits better?

**Comment by t3chguy** [comment] 2021-09-06 08:26
For me the Discord model doesn't work well with very large Guilds, I often find myself having to scroll the list loads to be able to find unreads/notifications as there isn't a way to sort by recency.

A similar issue would be the case if we split up the room list more than just People/Favs/Rooms because then each list would be recents-sorted but not the whole list. Another issue with this proposal is a room may exist in multiple subspaces and thus now then be shown multiple times in a single room list in multiple places, confusingly.

**Comment by Twi1ightSparkle** [comment] 2021-09-07 11:21
> @mattdm  I'd love to hear the opposing viewpoint,

I see the use case for this, but personally I would not like it because I prefer to have my spaces collapsed and just use the space for the current situation (work for example) selected. Then browse the room list including all sub spaces like I did before spaces using keyboard shortcuts.

So an options in settings to choose would be best imo.

**Comment by Erethon** [comment] 2021-09-07 12:49
I would like to +1 what @mattdm is saying/proposing. Current implementation of spaces doesn't help with organizing my rooms in a logical manner, since top level (or higher level) spaces also include all the lower level channels. This become more evident if you have rooms in a higher level space that don't belong in any sub-space and the only view with these rooms gets "polluted" by all the rooms in all the lower level spaces.

As @Twi1ightSparkle said, I would be happy with a setting to choose between the two behaviours and I'm willing to try implementing this if:
1) We think it's something that's useful and might be merged
2) The maintainers think it's "easily" achievable, as my experience with this kind of work is minimal :)

**Comment by mattdm** [comment] 2021-09-08 14:23
@Twi1ightSparkle Ah, I see. I think the primary difference is coming at this from being a heavy matrix user _before_ spaces existed, vs. me coming into this and wanting spaces to provide a curated experience for our users (who might not be familiar with matrix at all).

I think, though, that these things could coexist? Public spaces could work like I'm suggesting, and then you could create your own private spaces with whatever arrangement you want.

**Comment by mattdm** [comment] 2021-09-08 14:30
I want to note another weirdness that happens here: rooms are only considered a member of the top-level space _if you've joined the subspace too_. That leads to some serious cognitive weirdness. In my example at the top, is "Information" a member of the "Fedora" space? _It depends._

**Comment by t3chguy** [comment] 2021-09-08 14:31
That is a separate issue: https://github.com/vector-im/element-web/issues/17293

**Comment by mattdm** [comment] 2021-09-08 15:27
> That is a separate issue: #17293

Well, it _could_ be a separate issue; or, this could be a solution to that issue.

**Comment by t3chguy** [comment] 2021-09-08 15:34
No, it is a technical issue of not having access to the data via /sync - regardless of what the UI/UX looks like.

**Comment by mattdm** [comment] 2021-09-08 15:40
But if you aren't trying to show rooms which are within subspaces as also members of the top-level space, it's irrelevant. That issue is only an issue _because_ they're treated this way -- it's an _example_ of the "weirdness" I mentioned.

**Comment by mattdm** [comment] 2021-09-09 20:54
Oh! I have come across another situation related to this. We have one sub-space, _Project Teams_, which contains a fairly long list of sub-teams. In some cases, a team has more than one channel. I'd like to group those with a further sub-space -- say, for example, Infrastructure.

As it is, that grouping is helpful to the members of that subspace, because it makes it possible to drill down to just those channels. But it's less useful for people who aren't, because now _all_ of those rooms are in their list in the _Project Teams_ space -- not filtered at all.

**Comment by MayeulC** [comment] 2021-09-24 10:01
I think that adding a way to "pin" a subspace to the spaces bar so that it doesn't need to be extended to show the subspace would more or less solve this?

Alternatively, there could be some room state event suggesting a different presentation, but the client should be compatible.

**Comment by emorrp1** [comment] 2021-09-30 12:43
It feels to me that this discussion is simply a repeat of the Home discussion (#18093) just one level down. The solution should include the results of the experiment there and allow the user to select "Show all rooms" for the parent space. Or maybe even just inherit that setting globally since it seems to be a conceptual thing, so if someone has indicated they don't consider Home to be an Other category, then the same should apply to parent spaces.

@MayeulC that would be #17347 I think.

**Comment by thoraj** [comment] 2021-11-19 11:07
Just to pitch in: 
We use Matrix in our solution Verji, and spaces is **very** important to us. "Room hierarchies"  is a highly requested feature from our customers, and we believe that the introduction of Spaces is a game-changer. (So kudos to everyone involved in creating spaces) 

However, for our customers, the current implementation where rooms from sub-spaces float up and show up in higher level spaces renders the solution practically useless. 

Our preferred solution to this would be: 
* Make the behavior configurable per space (a room state event ?). So we could determine if a space only show immediate child-rooms, or the aggregation behavior we have today. 
* Keep the space hierarchy in the leftmost column. Or at least make it an option.

**Comment by Flam3z** [comment] 2021-12-03 02:45
> For me the Discord model doesn't work well with very large Guilds, I often find myself having to scroll the list loads to be able to find unreads/notifications as there isn't a way to sort by recency.
> 
> A similar issue would be the case if we split up the room list more than just People/Favs/Rooms because then each list would be recents-sorted but not the whole list. Another issue with this proposal is a room may exist in multiple subspaces and thus now then be shown multiple times in a single room list in multiple places, confusingly.

High Agree, When I used to use discord and finding huge, active servers It was very fustrating just to find one specific channel under the 5+ or so categories. Just to chime in with my own idea, having some sort of "folders" within the sections that give the freedom to the user of only wanting to be in and see a specific set of rooms within said space.

**Comment by kfiven** [comment] 2021-12-26 15:18
+1 though I am already addicted to this behavior in Cinny client, but when switching to Element, I get lost in scroll when there are hundreds of rooms in subspaces and then the only option is to left is remembering room name and searching it.

**Comment by t3chguy** [comment] 2022-01-27 13:35
Duplicate of https://github.com/vector-im/element-web/issues/17378

**Closed by t3chguy** 2022-01-27 13:35 UTC
Labels: S-Minor, A-Room-List, A-Spaces, X-Needs-Design, T-Enhancement, O-Occasional, A-Subspaces, Z-IA, Z-Labs
