### ISSUE TITLE
Set Custom Install Path

### ISSUE THREAD

**Issue by ArtexJay** [vector-im/element-web#22593] opened 2022-06-15 22:37 UTC
#### What would you like to do?
I want to be able to tell the installer where to install Element. I'd like to install on my other drives and keep my SSD only for the OS environment.
Setup could just ask install normally or custom, if it's custom then i get to pick what path to install it too. If  i select normal, continue installing as it would normally do at this time. 
I don't like the  auto-install to the OS drive directory, hopefully this can be done at some point.

**Comment by turt2live** [comment] 2022-06-15 23:26
Product team: how much of the installer experience is important to you? What other changes can we make while we're in the area (considering this sort of change would require quite a bit of technical/design effort)?

(these questions should probably be answered with tickets rather than comments here)

**Comment by ArtexJay** [comment] 2022-06-16 05:27
Maybe other's might have more ideas on what to change in the installer but for me what i suggested would great.
This would also help differentiate Element from Discord which auto-installs despite their users asking for it for a few years now.

**Comment by t3chguy** [comment] 2022-06-27 08:47
Duplicate of https://github.com/vector-im/element-web/issues/2817

**Closed by t3chguy** 2022-06-27 08:47 UTC
Labels: A-Electron, X-Needs-Product, T-Enhancement, A-Packaging, O-Uncommon
