### ISSUE TITLE
Name and avatar changes should not trigger rooms to become unread

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#11162] opened 2019-10-18 22:57 UTC
When someone changes their name or avatar, we seem to mark every room that we shared with them as unread (because of the `m.room.member` event).

At first glance, we already try to filter these events out of the unread handling, so something a bit more mysterious must be happening...

**Comment by turt2live** [comment] 2019-10-19 06:17
If the room is mentions only then this doesn't happen. If you're seeing it after refresh, it's a duplicate of one of the other "randomly bold" bugs.

All Messages tends to do this iirc.

**Comment by turt2live** [comment] 2020-08-31 19:28
Duplicate of 
https://github.com/vector-im/element-web/issues/110 and/or https://github.com/vector-im/element-web/issues/12063

**Closed by turt2live** 2020-08-31 19:28 UTC
Labels: bug, defect, feature:ftue-notifications, p2, phase:1, type:roomlist
