### ISSUE TITLE
Long usernames in threads in @ dialog overlap

### ISSUE THREAD

**Issue by Winterhuman** [vector-im/element-web#23285] opened 2022-09-15 10:37 UTC
### Steps to reproduce

To make explaining easier, here's an image:

![thread-at-overlap](https://user-images.githubusercontent.com/86165318/190382706-558a85ac-70f8-4ffe-859b-3c5821677935.png)

#### What did you expect?

Long usernames should end with ellipses, or fade out of view (with a tooltip containing the full username on hover maybe?), when displayed in the @ dialog inside threads.

#### What happened instead?

Long usernames overlap other usernames in the @ dialog in threads.

### Operating system

Arch Linux

### Application version

Element version: 1.11.5 Olm version: 3.2.12

### How did you install the app?

FlatHub

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-09-16 08:45
Duplicate of https://github.com/vector-im/element-web/issues/6335

**Closed by t3chguy** 2022-09-16 08:45 UTC
Labels: T-Defect, X-Regression, S-Minor, S-Tolerable, O-Occasional, A-Threads
