### ISSUE TITLE
Link to root message of a thread doesn't open thread panel

### ISSUE THREAD

**Issue by aWeinzierl** [vector-im/element-web#19830] opened 2021-11-21 00:49 UTC
### Steps to reproduce

1. find a root message and get the link through options (three dots when hovering message) ->share->*copy the link*"
2. send that link directly to the main timeline
3. let someone else (not the thread opener) click that link
4. observe only the message being marked, but nothing else happening

#### What did you expect?

Message is marked and thread panel opens with the corresponding thread.

#### What happened instead?

Message is marked.

### Operating system

Windows 10 10.0.19043

### Browser information

Version 95.0.1020.53 (Official build) (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b2e8f212e410-react-256c468c15a3-js-af523522def0 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2021-11-22 06:59
I am a little confused. Are you expecting the thread to be shown and the messages to be selected or only that latter?

**Comment by aWeinzierl** [comment] 2021-11-22 10:16
> I am a little confused. Are you expecting the thread to be shown and the messages to be selected or only that latter?

Seems like I mixed up what happened with what I expected.
I'd expect both.

**Comment by MadLittleMods** [comment] 2021-11-24 22:26
Duplicate of https://github.com/vector-im/element-web/issues/19815

**Closed by MadLittleMods** 2021-11-24 22:26 UTC
Labels: T-Defect, S-Minor, O-Occasional, A-Threads
