### ISSUE TITLE
Twitter bridging and "empty rooms"

### ISSUE THREAD

**Issue by xyzst** [vector-im/element-web#23197] opened 2022-09-02 22:14 UTC
### Steps to reproduce

After providing my Twitter credentials, the bridge attempted to synchronize with Twitter and it resulted in creation of "empty rooms" in Element.

#### What did you expect?

- direct messages from twitter should form their own rooms

#### What happened instead?

- generated multiple "empty rooms"

### Operating system

macOS

### Application version

Element 1.11.4

### How did you install the app?

https://element.io/get-started

### Homeserver

Dendrite 0.9.5

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2022-09-04 06:37
How did you set up the bridge? This sounds like an issue at the bridge's side rather than in Element Web

**Comment by t3chguy** [comment] 2022-09-05 08:53
Duplicate of https://github.com/vector-im/element-web/issues/22710

**Closed by t3chguy** 2022-09-05 08:53 UTC
Labels: T-Defect, X-Needs-Info
