### ISSUE TITLE
Screen sharing stopped working

### ISSUE THREAD

**Issue by adminibt** [vector-im/element-web#23818] opened 2022-11-23 10:42 UTC
### Steps to reproduce

1. Start a call
2. Click on "share screen"
3. Nothing happens

### Operating system

Windows

### Application version

1.11.15

### How did you install the app?

via update

### Homeserver

Synapse 1.72.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-11-23 10:47
Duplicate of https://github.com/vector-im/element-web/issues/23808

**Closed by t3chguy** 2022-11-23 10:47 UTC
Labels: T-Defect
