### ISSUE TITLE
Missing a call counts as 5 notifications

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20691] opened 2022-01-23 13:23 UTC
### Steps to reproduce

1. get called 1:1 e2ee while offline/only online on E android
2. press phone's standby button to silence ringing
3. start E desktop to see notification count of 5

### Outcome

Really this should count as 1 if there is only 1 event in the timeline (the call thingy in missed call state).

I wonder if it should be a "ping" event (red) or something else.

### Operating system

arch

### Application version

Element version: 1.9.9 Olm version: 3.2.8

### How did you install the app?

arch repo

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-01-23 13:44
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/7941

**Closed by SimonBrandner** 2022-01-23 13:44 UTC
Labels: T-Defect
