### ISSUE TITLE
Empty rooms are shown as unread

### ISSUE THREAD

**Issue by smoebody** [vector-im/element-web#22735] opened 2022-07-05 07:09 UTC
### Steps to reproduce

1. The rooms affected had a history.
2. The synapse retention-job purged old events and now there are no more events left, leaving the room empty.
3. Start a new client and observe the status of the rooms.

#### What did you expect?
The room  should not be marked as unread.

#### What happened instead?
The room is marked as unread and this cannot be changed except by typing something in. This effects clients which have no own history in the room. It also effects the browser version.

### Operating system

Fedora Linux 36

### Application version

Element: 1.10.15, Olm: 3.2.8

### How did you install the app?

Flatpak

### Homeserver

Synapse 1.61.1

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-07-05 07:25
Duplicate of https://github.com/vector-im/element-web/issues/19560

**Closed by t3chguy** 2022-07-05 07:25 UTC
Labels: T-Defect
