### ISSUE TITLE
Implement an Account Switcher for users with multiple accounts on Element

### ISSUE THREAD

**Issue by goliv04053** [vector-im/element-web#24206] opened 2023-01-10 22:20 UTC
#### What would you like to do?
Have other accounts on the same app where I can switch without removing an account and entering in other
#### Why would you like to do it?
Make the process of accessing other accounts simplified.
#### How would you like to achieve it?
Like Discord, you login in your account and you can add other accounts to switch. How it's already logged, you can switch to other account.

**Comment by weeman1337** [comment] 2023-01-11 07:32
duplicate of  #2320

**Closed by weeman1337** 2023-01-11 07:32 UTC
Labels: T-Enhancement

**Comment by weeman1337** [comment] 2023-01-11 07:35
Thanks for reporting this issue @goliv04053 . You can follow #2320 for updates on this topic.

> …where I can switch without removing an account and entering in other 

Until then, workarounds can be:
- Browser: Use different browsers or deployments under different URLs
- Desktop: Start the app with `---profile something` arg
