### ISSUE TITLE
Verification came through in a dialog, not the right panel

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#13248] opened 2020-04-17 21:35 UTC
Caught by the end-to-end tests: https://buildkite.com/matrix-dot-org/matrix-react-sdk/builds/5940#1af9b5f8-5c9d-4e98-9521-3e42a64b2abf

Just in case the artifacts go missing, here's some copies: 
[verification.zip](https://github.com/vector-im/riot-web/files/4495323/verification.zip)

Note that Bob starts the verification, and Alice gets it in a dialog:
![screenshot](https://user-images.githubusercontent.com/1190097/79615946-13f3a700-80c1-11ea-9b91-08aec98629f0.png)
![screenshot](https://user-images.githubusercontent.com/1190097/79615952-16560100-80c1-11ea-829c-6d6ca3f44a47.png)

**Comment by maralorn** [comment] 2020-06-30 13:24
We have exactly this issue.

* User A starts verification in side bar.
* User A has error in log, that 
  ```
  got cross-signing keys for @maralorn:maralorn.de: 
  Object { master: undefined, self_signing: undefined, user_signing: undefined }
  ```
* User B sees verification dialog in popup instead of sidebar.

The underlying bug here is probably a synapse issue. But my point is, that the popup of User B might be caused by User A falling back to legacy verification.

Just a guess.

**Comment by mweinelt** [comment] 2020-06-30 13:40
To me this looks like https://github.com/matrix-org/synapse/issues/7504 and https://github.com/matrix-org/synapse/issues/7521 is still happening on 1.15.1.

**Comment by kittykat** [comment] 2021-12-09 18:17
I'm going to close this issue for now as the design has changed since it's been filed and we cannot reproduce it. Please open a new issue if you feel that there are improvements to be made.

**Closed by kittykat** 2021-12-09 18:17 UTC
Labels: T-Defect, A-E2EE-Cross-Signing, X-Needs-Community-Testing
