### ISSUE TITLE
"Something went wrong" when switching to a room

### ISSUE THREAD

**Issue by madduck** [vector-im/element-web#15092] opened 2020-09-04 00:03 UTC
### Description

I was just switching back to the `#redecentralize` room when I was told that "something went wrong"

### Steps to reproduce

1. Switch to another room
2. Switch to `#redecentralize`, see error, where previously I'd be able to interact with the room.

Log: not sent — I cannot send the log without an issue, so that questions seems wrong. I will send the log shortly though.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 80
- **OS**: Debian unstable
- **URL**: develop.riot.im

**Comment by madduck** [comment] 2020-09-04 00:53
This now happens when I switch to any room that I haven't visited in a few hours: https://scratch.madduck.net/2020-09-04-element_something_went_wrong.mkv

**Comment by t3chguy** [comment] 2020-09-04 08:20
Duplicate of https://github.com/vector-im/element-web/issues/15091

**Closed by t3chguy** 2020-09-04 08:20 UTC
