### ISSUE TITLE
Change to a single username / email / phone input for login

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#8311] opened 2019-01-29 17:53 UTC
* Drop the country selector in front
* Detect which one it is based on format

**Comment by jryans** [comment] 2019-01-29 17:56
@nadonomy has more thoughts here, so we should revisit post FOSDEM.

**Comment by lampholder** [comment] 2019-01-30 14:52
My thoughts:
- people often don't know the internationalised version of their phone number
- a phone number is also a valid username

Which isn't to say that we can't achieve less friction in our login, esp. if we're willing to invest in some behind-the-scenes magic to make it all JustWork.

**Comment by turt2live** [comment] 2022-05-07 02:36
Effective duplicate of https://github.com/vector-im/element-web/issues/6826

**Closed by turt2live** 2022-05-07 02:36 UTC
Labels: A-Login, X-Needs-Design, Z-Redesign, T-Enhancement
