### ISSUE TITLE
[Feature request] Turn off mic or video when enter video conference

### ISSUE THREAD

**Issue by kuriot** [vector-im/element-web#14242] opened 2020-06-29 13:19 UTC
Hello.

Sometimes participants reconnect automatically if have bad internet or connection problems and their microphones are turned on automatically. It would be great to have an option in settings to disable mic and video on connection to video conference.

**Comment by edwinsage** [comment] 2021-05-20 19:34
This is also important because you cannot currently join a conference with camera or mic muted, which is unexpected.  A user does not want to be surprised to see that they are suddenly sending a video stream without confirmation.

**Comment by SimonBrandner** [comment] 2022-01-03 17:24
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/11130

**Closed by SimonBrandner** 2022-01-03 17:24 UTC
Labels: Z-Upstream, T-Enhancement, A-Jitsi, O-Occasional
