### ISSUE TITLE
[Regression] Code block line numbers are borked for wrapped lines

### ISSUE THREAD

**Issue by vit9696** [vector-im/element-web#20374] opened 2021-12-30 01:22 UTC
### Steps to reproduce

Send message containing this code block:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
12345
456789 
```

#### What did you expect?

<img width="581" alt="Screenshot 2021-12-30 at 04 21 09" src="https://user-images.githubusercontent.com/4348897/147714311-dc7bfa66-545e-4e37-a273-70dfa3a0a842.png">

#### What happened instead?

<img width="798" alt="Screenshot 2021-12-30 at 04 21 26" src="https://user-images.githubusercontent.com/4348897/147714323-57cfc54e-9c99-4b33-a60c-1fcd43afe2ac.png">

This issue prevents adequate communication with code line references, so for me this defect is of rather importance. I believe the regression happened in 1.9.8, but it is hard to be sure with uncontrolled automatic updates.

### Operating system

macOS

### Application version

1.9.8

### Will you send logs?

No

**Comment by robintown** [comment] 2021-12-30 02:32
Duplicate of https://github.com/vector-im/element-web/issues/20316

**Closed by robintown** 2021-12-30 02:32 UTC
Labels: T-Defect
