### ISSUE TITLE
The custom homeserver field on the login flow doesn't select reliably.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16758] opened 2021-03-23 17:14 UTC
This is reproducable ~70% of the time for me on Catalina + Chrome.  You click on the custom homeserver field to edit it, and it promptly de-focuses immediately afterwards.  Also, the placeholder text is black when it should surely be greyed (or show a suitable example).

https://user-images.githubusercontent.com/1294269/112188710-217fae00-8bfb-11eb-923c-39798ef5b4ef.mov

**Comment by ara4n** [comment] 2021-03-23 17:16
(related https://github.com/vector-im/element-web/issues/16297)

**Comment by SimonBrandner** [comment] 2021-07-18 07:22
I knew it! Duplicate of https://github.com/vector-im/element-web/issues/18031

**Closed by SimonBrandner** 2021-07-18 07:22 UTC
Labels: A-Login, T-Defect, Z-Impact-2, Z-Papercuts, Z-Visibility-2
