### ISSUE TITLE
Quick reaction emoji picker cut off on left side if room list minimized

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17771] opened 2021-06-25 03:35 UTC
There's just not enough room

this guy:
![image](https://user-images.githubusercontent.com/1190097/123365776-2e7ea700-d534-11eb-9128-54c85ab01c71.png)

**Comment by SimonBrandner** [comment] 2021-06-25 06:12
Duplicate of https://github.com/vector-im/element-web/issues/17527

**Closed by SimonBrandner** 2021-06-25 06:12 UTC
