### ISSUE TITLE
Element Desktop on arm64 architecture

### ISSUE THREAD

**Issue by as365n4** [vector-im/element-web#19832] opened 2021-11-21 18:11 UTC
### Your use case

Is there any plan on supporting arm64? When adding your repo to an arm64 based Debian installation, apt complains with: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://packages.element.io/debian default InRelease' doesn't support architecture 'arm64'

### Have you considered any alternatives?

Yes, there is FluffyChat available as FlatPak for arm64, but the native element Desktop app should be available too on this architecture.

### Additional context

Pine64 has sold over 20.000 of their PinePhone which is arm64 and has sold several thousand of their PinebookPRO Laptop which are arm64 and RaspberryPi is making the switch from armhf to arm64, so there is plenty of Users waiting for matrix/element to be available on their Desktop (not in browser!). Especially since Signal/Open Whisper Systems can't be bothered to port their client to the arm64 architecture (issue has been raised with them over 2 years ago). And you guys are developing for that architecture already as it being used on Android, iOS, macOS.... only Linux/Debian is missing. ;-)

**Comment by novocaine** [comment] 2021-11-22 04:30
Duplicate of https://github.com/vector-im/element-web/issues/17942

**Closed by novocaine** 2021-11-22 04:30 UTC
Labels: T-Enhancement, A-Packaging
