### ISSUE TITLE
Crash when joining room with URL in topic from space hierarchy

### ISSUE THREAD

**Issue by AndrewKvalheim** [vector-im/element-web#23677] opened 2022-11-01 19:26 UTC
### Steps to reproduce

1. In a new browser session, sign in to Element.
2. Join and navigate to the space `#issue-23677:kvalhe.im`.
3. Click “Join” on “Room A”.

#### What did you expect?

The room is joined.

#### What happened instead?

Element displays “Something went wrong!” and the the browser console shows:

```plain
12:13:04.290 DOMException: Node.removeChild: The node to be removed is not a child of this node
    r rageshake.ts:64
    unstable_runWithPriority scheduler.production.min.js:18
    R SpaceHierarchy.tsx:122
    unstable_runWithPriority scheduler.production.min.js:18
```

### Operating system

NixOS 22.05

### Browser information

Firefox 106.0.2

### URL for webapp

app.element.io

### Application version

Element version: 1.11.13, Olm version: 3.2.12

### Homeserver

Synapse 1.69.0

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-11-02 02:54
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by robintown** 2022-11-02 02:54 UTC
Labels: T-Defect

**Comment by AndrewKvalheim** [comment] 2022-11-02 03:00
Ah, I’d only searched [matrix-org/matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk/search?q="The+node+to+be+removed+is+not+a+child+of+this+node"&type=issues) since that’s where the trace leads. Then of course submitted here per the UI prompt.
