### ISSUE TITLE
Socks5 and HTTP proxy support

### ISSUE THREAD

**Issue by JanetMw** [vector-im/element-web#22692] opened 2022-06-30 05:18 UTC
### Your use case

Hi I want to run Element in Tails OS but cannot pass the firewall. It has to be proxied over port 9050. Could you please add socks and HTTPS support?

**Comment by t3chguy** [comment] 2022-06-30 09:01
Duplicate of https://github.com/vector-im/element-web/issues?page=2&q=is%3Aissue+is%3Aopen+proxy

**Closed by t3chguy** 2022-06-30 09:01 UTC
Labels: T-Enhancement
