### ISSUE TITLE
Add the ability to search and discover spaces

### ISSUE THREAD

**Issue by ducheng0** [vector-im/element-web#18217] opened 2021-07-25 03:00 UTC
#### Is your suggestion related to a problem? Please describe.
Right now, there is no way to discover or search for spaces, only rooms.

#### Describe the solution you'd like.
An option to search for spaces in the discover tab, similar to Discord's explore page.

**Comment by robintown** [comment] 2021-07-25 12:27
Duplicate of https://github.com/vector-im/element-web/issues/17264

**Closed by robintown** 2021-07-25 12:27 UTC
Labels: T-Enhancement
