### ISSUE TITLE
Line breaks removed when message is one large markdown quote

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18299] opened 2021-07-30 09:13 UTC
Sending:

```
> test
>
> test
```

results in a single line:
<img width="98" alt="Screenshot 2021-07-30 at 10 11 45" src="https://user-images.githubusercontent.com/986903/127630653-a63d6c68-9559-45ab-ad85-4a294bd8e5c4.png">

whereas obviously it should be one markdown quote with linebreaks in it

```
> test
>
> test

hi folks
```

...works as expected.

Probably very closely related to https://github.com/vector-im/element-web/issues/15320

**Comment by AgentOak** [comment] 2021-10-30 19:16
Is this not a straightforward duplicate of #8786?

**Comment by SimonBrandner** [comment] 2021-10-31 09:24
> Is this not a straightforward duplicate of #8786?

Yep, seems to be the case, thanks!

**Closed by SimonBrandner** 2021-10-31 09:24 UTC
Labels: T-Defect, S-Minor, Z-Upstream, A-Composer, O-Occasional
