### ISSUE TITLE
When removing Jitsi Widget from Group it doesn't log you out of Jitsi

### ISSUE THREAD

**Issue by davidscheele** [vector-im/element-web#16889] opened 2021-04-08 13:08 UTC
### Description

When using the Element Desktop Client for Linux (Ubuntu), you can add a jitsi widget to a room. After joining the room through the client, you can delete the widget from the group again. The embedded jitsi view will get closed, the widget will be removed, but the call is still active. The camera is still recording, the mic is still active, anyone who had joined by browser is still in the call and can still see and hear you, but You have absolutely no way of closing the call through Element. Restarting Element fixes the Problem.

### Steps to reproduce

- Create Group
- Add Jitsi Widget to Group
- Open Jitsi-Call through Element
- (Have someone join through his browser)
- Hover over the Widget, select the three dots and delete the jitsi widget from the group
- You won't be able to see that Element is still sending your signal into the jitsi call, nor can you specifically close the call.
- The other User that joined through the browser will still be able to see you.
- Other users in the call that also had joined through Element will get their call closed.

I would expect the call to be closed upon delerting the widget.

### Version information

- Linux (Ubuntu) Desktop
- Ubuntu 20.04.2 LTS
- Element Version: 1.7.24
- olm Version: 3.2.1

**Comment by turt2live** [comment] 2021-04-09 02:16
Duplicate of https://github.com/vector-im/element-web/issues/15703

**Closed by turt2live** 2021-04-09 02:16 UTC
