### ISSUE TITLE
misleading warning on login to riot.im if JS is disabled

### ISSUE THREAD

**Issue by ilu33** [vector-im/element-web#7102] opened 2018-07-29 18:14 UTC
Just a minor improvement:

If you browse to https://riot.im/app/#/login without JS enabled for your homeserver (which you don't have if you want to register just now) you get a warning about your internet connection, SSL certificates and browser addons. The warning should mention that you need to enable JS for either matrix.org or your homeserver (if you already have one) because that is a very common reason for failure.

**Comment by kittykat** [comment] 2021-09-16 07:27
I believe this is fixed now as I cannot reproduce it. Please comment with @kittykat and ask me to reopen the issue if you are still seeing it.

**Closed by kittykat** 2021-09-16 07:27 UTC
Labels: T-Defect, P2, S-Minor
