### ISSUE TITLE
Spaces not showing rooms 

### ISSUE THREAD

**Issue by argentatus-larus** [vector-im/element-web#20045] opened 2021-12-05 01:59 UTC
Hi, I am part of an organization that has used element for a long time. 
When communities were thrown out and Spaces were fully implemented we added every room we had to it (we currently have 73 rooms). 

Everything was nice and good until we noticed 2 things: 
some previously added rooms were not showing up on the space and were impossible to add to the space. 
some rooms that were created outside the space, were version 9, and added to the space were added to the space but were not possible to find them in the spaces menu.

I thought that it was a room version problem so I checked every room version and we have rooms that are Version 1 that are on the space and rooms that are version 9 that are not.

I also thought it could be an admin privilege problem, but some rooms were the Space Admin is admin are not showing up, and some rooms were the Space Admin is not admin are showing up.

I don't know if you can  help me but help is very much welcome

**Comment by SimonBrandner** [comment] 2021-12-05 07:12
@amc-assuncao, it might help to share your version info (version of the client and synapse) and logs. Could you please do that?

**Comment by daniel-bogdoll** [comment] 2021-12-08 14:35
@SimonBrandner same issue here. Previously, newly created rooms could be found within the "Explore rooms" area. Now, they don't show up. Here an example:

Create room:
![image](https://user-images.githubusercontent.com/19552411/145226091-65ed1b06-c601-4c7c-b153-3ea8fcd4fa2c.png)

Room settings:
![image](https://user-images.githubusercontent.com/19552411/145226162-5b7d5733-7863-42d6-9d2d-4e584fd38d08.png)
![image](https://user-images.githubusercontent.com/19552411/145226191-e96ccb9a-b800-4534-9d0a-31a48f4e2f1d.png)

Searching for room:
![image](https://user-images.githubusercontent.com/19552411/145226458-57a0e8fb-a592-406b-9970-6e4b15bb3bf3.png)
--> The room does not show up in the search results. The same holds for rooms created by other people. If they invite me, I get access, but I cannot explore/see/find them otherwise.

**Comment by t3chguy** [comment] 2021-12-08 14:51
If its not showing up in the searchable view on the space home page then its not being returned by the server in the /hierarchy API

**Comment by daniel-bogdoll** [comment] 2021-12-09 11:07
So does this mean our local IT department could fix it or is it a more general issue?

**Comment by squahtx** [comment] 2021-12-13 11:09
The Synapse issue is here: https://github.com/matrix-org/synapse/issues/11134

**Comment by clokep** [comment] 2022-01-21 14:41
The corresponding Synapse bug is fixed in the upcoming version 1.51.0rc1 -- this is already on matrix.org's server.

@argentatus-laurus could you verify that this is no longer happening and the issue is fixed? Thank you!

**Comment by kittykat** [comment] 2022-02-21 18:11
@argentatus-larus I'm going to close this issue for now as the new version of Synapse should have fixed it. Please re-open the issue with more information if you are still experiencing it.

**Closed by kittykat** 2022-02-21 18:11 UTC
Labels: T-Defect, X-Needs-Info, S-Critical, Z-Backend, A-Spaces, Z-Synapse, O-Uncommon
