### ISSUE TITLE
New DM dialogue is cut off

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21644] opened 2022-04-01 15:49 UTC
### Steps to reproduce

click + to start a new DM

### Outcome

![image](https://user-images.githubusercontent.com/2803622/161298105-d5039974-e0c6-4c3f-be48-26442e371e38.png)

the "or send invite link" textbox is cut off

### Operating system

arch

### Application version

Element Nightly version: 2022040101 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-01 18:41
Duplicate of https://github.com/vector-im/element-web/issues/20911

**Closed by robintown** 2022-04-01 18:41 UTC
Labels: T-Defect

**Comment by HarHarLinks** [comment] 2022-04-02 10:09
sorry, I couldn't find that issue since it uses none of the keywords i looked for

**Comment by robintown** [comment] 2022-04-02 12:22
No problem, duplicates never hurt
