### ISSUE TITLE
1:1 call buttons vanish even whilst hovering on them

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#17651] opened 2021-06-15 09:41 UTC
they are shown on hovering over the call view and vanish after a mouse movement timeout, but shouldn't if the cursor is directly on the button, this is poor a11y

**Comment by SimonBrandner** [comment] 2021-06-15 09:52
Duplicate of https://github.com/vector-im/element-web/issues/16751#issue-838661491

**Closed** 2021-06-15 09:58 UTC
