### ISSUE TITLE
Global keyboard shortcut to toggle Riot

### ISSUE THREAD

**Issue by fladd** [vector-im/element-web#13574] opened 2020-05-07 07:55 UTC
**Is your suggestion related to a problem? Please describe.**
Currently, it is not easy to quickly bring the Riot application to the foreground.

**Describe the solution you'd like**
A simple global keyboard shortcut that toggles Riot visibility. 

**Describe alternatives you've considered**
Current alternative involves using Alt-Tab  and arrow keys (or other OS equivalent) to search through _all open application windows_ to find Riot and bring it to the front.

**Additional context**
Instant messengers used to have this feature back in the day to toggle the contact list. ICQ for instance had Alt-Shift-A, if I remember correctly. Other (multi-protocol) clients like Pidgin, Miranda and the like had a feature to customize such a global shortcut.

**Comment by bwindels** [comment] 2020-05-07 10:46
Fwiw, depending on your platform, you might be able to set a shortcut in your desktop settings.

**Comment by fladd** [comment] 2020-05-07 12:57
> 
> 
> Fwiw, depending on your platform, you might be able to set a shortcut in your desktop settings.

At least in Windows this is rather slow (approx. 1 sec), as it actually tries to open the app, then realizes it already is open and then gives focus to the window.

**Comment by t3chguy** [comment] 2023-04-18 15:01
Duplicate of https://github.com/vector-im/element-desktop/issues/724

**Closed by t3chguy** 2023-04-18 15:01 UTC
Labels: T-Enhancement
