### ISSUE TITLE
tab-completing on emoji code tries to complete user isntead

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21547] opened 2022-03-24 13:08 UTC
### Steps to reproduce

1. quickly type `:+1`
2. hit <kbd>Tab</kbd> before the emoji picker pops up

#### What did you expect?
emoji completion

#### What happened instead?
user completion

### Operating system

arch

### Application version

Element Nightly version: 2022032301 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.54

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-03-24 13:35
Duplicate of https://github.com/vector-im/element-web/issues/9757

**Closed by t3chguy** 2022-03-24 13:35 UTC
Labels: T-Defect
