### ISSUE TITLE
Add a Room to Community via Drag&Drop

### ISSUE THREAD

**Issue by a22sc** [vector-im/element-web#14338] opened 2020-07-05 11:06 UTC
An easier mechanism to add rooms to a community would be nice than copying the Room-Id.
"Drag & Drop" or right-click on the room would be my suggestion.

thank you!

**Comment by t3chguy** [comment] 2021-11-02 10:53
Duplicate of https://github.com/vector-im/element-web/issues/6201

**Closed by t3chguy** 2021-11-02 10:53 UTC
Labels: A-Spaces, T-Enhancement
