### ISSUE TITLE
Favourites and People metaspace sections are empty

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20080] opened 2021-12-07 10:08 UTC
### Steps to reproduce

Unknown, but have sent rageshake.

#### What did you expect?

Meta-spaces to function normally.

#### What happened instead?

![image](https://user-images.githubusercontent.com/22740616/145009208-c1ce0531-57cc-40ca-a181-cf0b795a2698.png)
![image](https://user-images.githubusercontent.com/22740616/145009227-f38b8c3b-ee65-4af9-b8a5-72581722848c.png)

These meta-spaces also correctly context-switch to "a" room within that space, but i cant see them in the dropdown.

Clicking the notif bubble also takes me to those rooms.

### Operating system

PopOS Linux, 21.04

### Browser information

Brave (Version 1.26.67 Chromium: 91.0.4472.114)

### URL for webapp

develop.element.io

### Application version

Element version: b0abbfacd48b-react-b4b81a455e14-js-39a8399977af Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2021-12-07 10:11
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/20070

**Closed by SimonBrandner** 2021-12-07 10:11 UTC
Labels: T-Defect
