### ISSUE TITLE
New Recovery Method Warning

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17312] opened 2021-05-15 17:55 UTC
![image](https://user-images.githubusercontent.com/31655082/118373495-77e3ea00-b5b7-11eb-8721-ba962f475537.png)

### Description

I think this warning is on the wrong login.

### Steps to reproduce

Somehow resetting the backup key

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop? web

[rageshake (1).zip](https://github.com/vector-im/element-web/files/6487926/rageshake.1.zip)

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version? Chrome
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web? Develop a few weeks ago

**Comment by kittykat** [comment] 2021-12-21 17:32
@chagai95 I can't reproduce this, could you please update with steps?

**Comment by chagai95** [comment] 2021-12-22 19:10
Sorry, I don't think I'll get around to trying to reproduce this in the near future... And I have no idea what the problem was to begin with maybe @tomtom-78 can help?

**Comment by kittykat** [comment] 2022-01-01 18:57
I'm going to close this issue for now as this area of the app has been updated and we cannot reproduce the issue, if you do come across it again, please comment with @kittykat and I will be happy to re-open it :+1:

**Closed by kittykat** 2022-01-01 18:57 UTC
Labels: T-Defect, X-Needs-Info, S-Minor, A-E2EE-Key-Backup, O-Uncommon
