### ISSUE TITLE
Cannot load Community Rooms if leaving room added

### ISSUE THREAD

**Issue by KazamaSion** [vector-im/element-web#13335] opened 2020-04-23 00:18 UTC
### Description 

If I create a room with no local address, add the room to the community, then leave the room, the community cannot load the room list anymore.  
It's not a network issue. A newly created community with no operations can see the room list (even with no rooms, it at least can load).  
The only way to solve is to destroy and rebuild the community.  

Temporary example of the bugged community: [+ftqu8z5yo:matrix.org](https://matrix.to/#/+ftqu8z5yo:matrix.org)

### Steps to reproduce

- Create a room with no local address
- Add the room to the community
- Leave the room

Logs being sent: yes  
  
Bugged community:  
![](https://i.loli.net/2020/04/23/URVbTiekXYv37oH.png)   
Normal Community:  
![](https://i.loli.net/2020/04/23/VIWzxsm54nAPQ3D.png)  

### Version information

- **Platform**: web and desktop

For the web app:

- **Browser**: Chrome 80
- **OS**: Windows 10
- **URL**: riot.im/app

For the desktop app:

- **OS**: Windows
- **Version**: 1.5.15

**Comment by prasket** [comment] 2020-05-08 23:10
I are also seeing this same behavior in one of the communities on a homeserver I help host. Taking this info I am going to dig into the database to see if there is a way to remove bad room from there to resolve. I will update with info I find.

**Comment by prasket** [comment] 2020-05-09 01:24
OK I can confirm that if you remove the rooms from the group_rooms table in postrgres the rooms will go back to showing again.

**Comment by hlesueur** [comment] 2020-05-09 09:32
Hello, I'm having the same issue, but my community is on matrix.org, so I have no access to the db
Anyone maintining the database would be able to help me removing this broken room from the database?
Thanks!

**Comment by KazamaSion** [comment] 2020-05-09 09:43
Since there's no dev replying to this issue, I think this is no the right place to feedback (maybe?)
So here is the question: where to submit this issue?

**Comment by hlesueur** [comment] 2020-05-09 12:05
I also put it in #riot-web:matrix.org, but no answer until now

I may have a suggestion on how to fix this, but that's nothing I can add on my own.
It's a simple test whether the room is empty when the last user quits it then it should be removed from the community it's attached to (although I don't know how simple it is to test if it's in a community)

**Comment by Twi1ightSparkle** [comment] 2020-05-10 13:10
https://newvector.zammad.com/#ticket/zoom/3139

**Comment by hlesueur** [comment] 2020-05-12 19:02
Hello @Twi1ightSparkle, thanks for the ticket. I've been watching zammad, but it's quite an empty room. 
Is anyone looking at this? Should I do something? 
thank you

**Comment by turt2live** [comment] 2020-05-12 19:27
Apologies for the delayed response here - we don't reply to every issue, nor do we spend a lot of time looking at issues related to the communities feature these days. The whole feature is slated for rewrite at the moment, which is why we're not spending much time triaging these things.

From a high-level glance it looks like this is probably a Synapse issue, and potentially a recentish regression. Considering their implementation has received just as much attention as ours (ie: very little), I am not all that surprised it has regressed, unfortunately. 

Best advice I can give is to be careful about the rooms which get included in a community :(

**Comment by Twi1ightSparkle** [comment] 2020-05-12 19:31
@hlesueur 
We only use Zammad internally, which is why you don't see anything. I will check if we think doing the database fix suggested above is safe, and if yes I will do that for you.

**Comment by hlesueur** [comment] 2020-05-12 22:07
Thanks for both your answers. 
I understand you may have some load here! thanks for the work by the way.

@Twi1ightSparkle are you suggesting doing for me the fix (eg software fix), or doing the manual removal of empty room just for my broken db?
in any case, thanks

**Comment by Twi1ightSparkle** [comment] 2020-05-13 12:30
Synapse issue https://github.com/matrix-org/synapse/issues/4891

**Comment by hlesueur** [comment] 2020-05-13 16:15
Thank you so much @Twi1ightSparkle it's repaired... !

**Comment by t3chguy** [comment] 2021-05-13 08:19
This is fixed by Spaces landing in Beta in next Release

**Closed by t3chguy** 2021-05-13 08:19 UTC
Labels: A-Spaces, T-Defect
