### ISSUE TITLE
Typing links with anchors leads to unexpected autocomplete suggestions

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5820] opened 2017-12-12 17:07 UTC
### Description

![image](https://user-images.githubusercontent.com/1190097/33897978-37797ed4-df24-11e7-8160-6c77187e8734.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment] 2018-07-16 17:03
fixed by matrix-org/matrix-react-sdk#1890

**Comment by ara4n** [comment] 2018-07-16 17:50
i literally tested it with the same text in your screenshot above, and it was fine! can haz screencap?

**Comment by turt2live** [comment] 2018-07-16 18:09
![stats-autocomplete](https://user-images.githubusercontent.com/1190097/42775213-14671754-88f1-11e8-8deb-8fb268728701.gif)

Pardon the bad quality

**Comment by ara4n** [comment] 2018-07-16 18:27
oh, but the bug said pasting! :D yup, agreed; needs to be fixed.

**Comment by turt2live** [comment] 2018-07-16 19:42
Typing the link out is probably rare, although when someone goes to backspace their way into the pasted link, the autocomplete happily tries to help.

**Comment by t3chguy** [comment] 2018-07-26 14:15
This is caused by https://github.com/matrix-org/matrix-react-sdk/blob/efdc5430d714a3df5defc0a1ab540a5ce9632b2b/src/autocomplete/RoomProvider.js#L32 `\B` including `/` 

A better regex is needed

**Comment by yannicka** [comment] 2020-11-28 12:26
I don't have that problem (on Element Web 1.7.14). Is the problem still relevant?

![Peek 28-11-2020 13-24](https://user-images.githubusercontent.com/22885898/100515516-10f38580-317d-11eb-89ba-8d1ce422a1b8.gif)

**Comment by jryans** [comment] 2020-12-01 15:22
I agree this seems fixed indeed!

**Closed by jryans** 2020-12-01 15:22 UTC
Labels: bug, p2, severity:minor, type:composer
