### ISSUE TITLE
Plain text toggle

### ISSUE THREAD

**Issue by dreaddr** [vector-im/element-web#17401] opened 2021-05-19 17:24 UTC
#### Is your suggestion related to a problem? Please describe.
I'm always frustrated when I have to keep slash commanding `/plain` because there is no toggle to auto default to plain text, I send lots of `*Messages` `*Like` `*This with bullets` and they always convert to italics, I do not want that.

#### Describe the solution you'd like.
Just have a toggle in preferences to make all text `/plain` without markdown

#### Describe alternatives you've considered.
Using my phone because that thing doesn't yet kill my lists, hope for the same feature to be there in case markdown gets added.

#### Additional context
Add it to the composer list of preferences, I suppose.

**Comment by t3chguy** [comment] 2021-05-19 17:30
Duplicate of https://github.com/vector-im/element-web/issues/483

**Closed by t3chguy** 2021-05-19 17:30 UTC
Labels: T-Enhancement
