### ISSUE TITLE
Configurable proxy in Element Desktop

### ISSUE THREAD

**Issue by h4x3rotab** [vector-im/element-web#18910] opened 2021-09-05 18:02 UTC
#### What would you like to do?

Change the proxy manually instead of using the system default proxy.

#### Why would you like to do it?

Accessing the global internet in some countries (e.g. China) could be complex. Sometimes we may want to proxy some software, while not touching the system proxy settings. A good example is Telegram, which allows the user to specify a list of the socks5 proxy, and can switch between them on the fly.

#### How would you like to achieve it?

Give user three options in the setting page:

1. No proxy
2. System default
3. Manual (ask user to input protocol, host, port, and optionally username and password. Http and socks5 protocols are preferred)

**Comment by SimonBrandner** [comment] 2021-09-05 18:03
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/3320

**Closed by SimonBrandner** 2021-09-05 18:03 UTC
Labels: T-Enhancement
