### ISSUE TITLE
Click on topic to open it (or make links clickable on room settings)

### ISSUE THREAD

**Issue by alex9099** [vector-im/element-web#15602] opened 2020-10-29 13:07 UTC
If the topic is big (as in, doesn't fit on the top where it shows the clickable links) it cuts and there is no easy way to click on the links that are hidden (one could copy from room settings, but that is a lame solution)

**Describe the solution you'd like**
Click on topic and open the full topic (could be on a popup) with all links clickable like the android app does

**Describe alternatives you've considered**
As said before, I could copy the links from the room settings, but they are not clickable, maybe make the room links clickable there if the user is not admin (since the box is read only it might not make sense to be inside an editable box)

**Comment by t3chguy** [comment] 2020-10-29 13:10
Duplicate of https://github.com/vector-im/element-web/issues/9623

**Closed by t3chguy** 2020-10-29 13:10 UTC
Labels: suggestion

**Comment by alex9099** [comment] 2020-10-29 13:25
Oh well, i searched and found nothing :) thanks
