### ISSUE TITLE
Sending an audio makes it hang and I can't write without clearing the cache

### ISSUE THREAD

**Issue by javierweglin** [vector-im/element-web#21358] opened 2022-03-08 20:12 UTC
### Steps to reproduce

when chatting with a person, clicking on the person, trying to send audio, it hangs

### Outcome

-

### Operating system

Windows 10

### Application version

1.10.6

### How did you install the app?

https://app.element.io/

### Homeserver

matrix.afip.gob.ar

### Will you send logs?

No

**Comment by gsouquet** [comment] 2022-03-09 08:49
What do you mean by "clicking on the person" ? Do you mean their avatar so that the right sidebar opens up and shows their profile? 

Also what would really help debug this issue would be to share a performance recording as I am currently unable to reproduce this issue

**Comment by kerryarchibald** [comment] 2022-03-09 09:41
Probably related to https://github.com/vector-im/element-web/issues/21206, can't recreate on nightly.

**Comment by gsouquet** [comment] 2022-03-09 09:50
@javierweglin would you be able to test against develop.element.io and confirm whether the issue linked by Kerry has fixed your problem or not

**Comment by n3rdybyn47ur3** [comment] 2022-03-10 07:19
Some of my users reported the same problem:

**Steps to reproduce**

Sending a voice message to a person or room. After that, the room stopps working (for the sender):
![element_voice_error](https://user-images.githubusercontent.com/68984615/157608855-1997b0fe-7eef-4a6a-beca-b5c564fa6801.PNG)

This does not happen to everyone or everytime.

**Operating system**

Windows 10

**Application version**
Self hosted webclient
Element version: fe88030bc9ce-react-fe88030bc9ce-js-fe88030bc9ce
Olm version: 3.2.8

Desktop App downloaded from element.io
Version von Element: 1.10.6
Version von Olm: 3.2.8

How did you install the app?
Downloaded Desktop App from https://element.io/get-started
Self hosted Webclient from docker image: docker pull vectorim/element-web 

Homeserver

Self hosted. Not named for privacy reasons. Version 1.52.0

Will you send logs?

No

**Comment by gsouquet** [comment] 2022-03-10 08:36
Could you try this out on develop.element.io as https://github.com/vector-im/element-web/issues/21206 is probably related and has already fixed this issue in an unreleased version of Element

**Comment by n3rdybyn47ur3** [comment] 2022-03-10 09:46
I could not reproduce the error on your developement system, but keep in mind that only some of my users have run into this problem.

**Comment by t3chguy** [comment] 2022-05-01 15:07
This is fixed in 1.10.7

**Closed by t3chguy** 2022-05-01 15:07 UTC
Labels: T-Defect, X-Needs-Info, A-Performance, S-Major, A-Voice Messages, O-Uncommon
