### ISSUE TITLE
Warn users about masked links that look like other links

### ISSUE THREAD

**Issue by SethFalco** [vector-im/element-web#23237] opened 2022-09-07 16:49 UTC
#### What would you like to do?

As Element supports most of the Markdown spec, users and bots can send masked links, i.e. [YouTube](https://www.youtube.com)

I'd like to see Element warn the user and ask them what link they want to visit if the text and link are both a URL, but to different domains.

For example:
[https://falco.fun/](https://yewtu.be/watch?v=dQw4w9WgXcQ)

```md
[https://falco.fun/](https://yewtu.be/watch?v=dQw4w9WgXcQ)
```

#### Why would you like to do it?

I'm all for masked links and think it's a great feature, and in most cases users should be trusted to just hover over and check the link if they're not sure if they can trust it.

However, it's easy to click something thinking it's legitimate and not bother checking the real URL via hover when it already looks like a valid URL in the first place.

The primary problem I can foresee here is phishing, but it could also just be annoying in general.

#### How would you like to achieve it?

I think the UI/UX that Thunderbird has would work really well for this.

On Thunderbird, if you click a link in an email where the text content is a URL but does not match the hyperlink, Thunderbird displays a warning and asks which URL you want to actually visit.

![image](https://user-images.githubusercontent.com/22801583/188934769-aad6c666-bb2e-43bf-a103-335e1bef6a66.png)

Thunderbird does not do this for normal masked URLs, only if the text content of the URL is a properly formatted URL, where the resource it links to is a different URL.

### Additional context

I am not aware of anyone who has been phished/scammed through this. However, I absolutely think this makes it a lot easier than it should be to convince someone to visit links that they shouldn't.

For example, the following to try and convince users to input their account details on another website:
```md
[https://element.io/element-one/free-gift?code=h9834jdnjf](https://element.io.free-gift.one)
```

**Comment by t3chguy** [comment] 2022-09-07 16:56
Duplicate of https://github.com/vector-im/element-web/issues/22875

**Closed by t3chguy** 2022-09-07 16:56 UTC
Labels: T-Enhancement
