### ISSUE TITLE
Element-desktop not working when matrix org is not available

### ISSUE THREAD

**Issue by iz4tow** [vector-im/element-web#23234] opened 2022-09-07 11:47 UTC
### Steps to reproduce

Using a matrix private server
1. Logout
2. Block default homeserver (matrix.org)
3. Try to launch app

#### What did you expect?
The application should be working also without matrix.org asking for a different homeserver 
#### What happened instead?
The application not works without matrix.org availability 

### Operating system

Ubuntu 20.04 desktop 

### Application version

Latest from official repository 

### Homeserver

Latest stable

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-09-07 11:48
Duplicate of https://github.com/vector-im/element-web/issues/11154

**Closed by t3chguy** 2022-09-07 11:48 UTC
Labels: T-Defect
