### ISSUE TITLE
Images never loading after waking up laptop

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18252] opened 2021-07-27 08:05 UTC
The last couple of days I've opened my laptop and there's been an image in the room element was open in that has arrived overnight, but it's just a blurhash and never loads. Switch rooms and back to the same room again makes it load.

**Comment by SimonBrandner** [comment] 2021-07-27 08:09
Perhaps https://github.com/vector-im/element-web/issues/18243 ?

**Comment by novocaine** [comment] 2021-11-19 04:30
@dbkr have you seen this lately?

**Comment by kittykat** [comment] 2022-01-11 18:39
I'm going to close this issue for now as we can't reproduce it. Please reopen if it's still happening!

**Closed by kittykat** 2022-01-11 18:39 UTC
Labels: T-Defect, X-Needs-Info, X-Regression, S-Minor, A-Media

**Comment by Palid** [comment] 2022-01-12 10:41
@kittykat this one's probably related to missing error handling and retires logic for images.
