### ISSUE TITLE
webpack 4: yarn fails when using nodejs 18

### ISSUE THREAD

**Issue by Kunsi** [vector-im/element-web#23696] opened 2022-11-04 06:35 UTC
### Steps to reproduce

- Install nodejs 18
- run `yarn install && yarn build` in repo directory
- get error: `Error: error:0308010C:digital envelope routines::unsupported`

### Outcome

```
│ Error: error:0308010C:digital envelope routines::unsupported
│     at new Hash (node:internal/crypto/hash:71:19)
│     at Object.createHash (node:crypto:133:10)
│     at module.exports (/opt/element-web/node_modules/webpack/lib/util/createHash.js:135:53)
│     at NormalModule._initBuildHash (/opt/element-web/node_modules/webpack/lib/NormalModule.js:417:16)
│     at handleParseError (/opt/element-web/node_modules/webpack/lib/NormalModule.js:471:10)
│     at /opt/element-web/node_modules/webpack/lib/NormalModule.js:503:5
│     at /opt/element-web/node_modules/webpack/lib/NormalModule.js:358:12
│     at /opt/element-web/node_modules/loader-runner/lib/LoaderRunner.js:373:3
│     at iterateNormalLoaders (/opt/element-web/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
│     at iterateNormalLoaders (/opt/element-web/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
│     at /opt/element-web/node_modules/loader-runner/lib/LoaderRunner.js:236:3
│     at context.callback (/opt/element-web/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
│     at /opt/element-web/node_modules/babel-loader/lib/index.js:59:71 {
│   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
│   library: 'digital envelope routines',
│   reason: 'unsupported',
│   code: 'ERR_OSSL_EVP_UNSUPPORTED'
│ }
│
│ Node.js v18.12.0
```

### Operating system

debian stable

### Application version

1.11.13

### Will you send logs?

No

**Comment by weeman1337** [comment] 2022-11-04 08:16
Thanks for reporting the issue @Kunsi . I can reproduce this one.

Found this webpack issue: https://github.com/webpack/webpack/issues/14532
As a workaround see the comments there. For a real solution looks like we need to upgrade to webpack 5.

**Comment by t3chguy** [comment] 2022-11-04 09:11
I've been using Node 18 just fine on macOS installed from homebrew

**Comment by pvagner** [comment] 2022-11-21 12:11
I am now using nodejs 19 on arch linux and I think the issue is not with nodejs as such but it might have to do something with upgrading openssl to version 3.0 I guess

**Comment by globi84** [comment] 2023-01-23 08:37
under windows does it not work or do I something wrong

my batchfile looks like this

```
set NODE_OPTIONS=--openssl-legacy-provider
echo "load enviroment..."
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\VC\Auxiliary\Build\vcvars64.bat"


echo "update rust and cargo"
rustup install stable
rustup default stable

echo "yarn install..."
call yarn install

echo "yarn fetch..."
call yarn run fetch --noverify --cfgdir CONFIGFILE

echo "yarn build native..."
call yarn run build:native

echo "yarn build 64..."
call yarn run build:64
```

**Comment by felipeavilis** [comment] 2023-02-28 21:49
> 

Where should i add this line? Witch file?

**Comment by lamhungypl** [comment] 2023-06-20 03:42
Try `yarn upgrade`. 
In my case, there's only 1 issue with `@babel/plugin-proposal-private-property-in-object` and it can be easily fixed by adding to devDependencies

**Comment by t3chguy** [comment] 2023-10-13 10:52
No longer an issue with latest Node

**Closed by t3chguy** 2023-10-13 10:52 UTC
Labels: T-Defect, S-Major, A-Developer-Experience, O-Occasional

**Comment by TomCool-TomTom** [comment] 2023-10-27 07:44
[t3chguy](https://github.com/t3chguy) What version of Node are your referring to?
