### ISSUE TITLE
can't write $ in code block due to math interpretation

### ISSUE THREAD

**Issue by grinapo** [vector-im/element-web#16290] opened 2021-01-27 08:17 UTC
### Description

This does not work (with _math_ enabled):
> \`\`\`bash
> #!/bin/bash
> problem="$1"
> echo "$problem is $problem"
> \`\`\`

$1 gets interpreted as math, but since it can't work within code block we get a html tag salad. Also cannot be tricked by `$$` or `$$$` either. 

It seems futile to interpret math, and any other advanced commonmark within code blocks.

### Version information
- **Platform**: web, v1.7.18, Chromium

**Comment by SimonBrandner** [comment] 2021-01-27 08:32
I believe this is a duplicate of [#15846](https://github.com/vector-im/element-web/issues/15846)

**Comment by grinapo** [comment] 2021-01-27 10:30
> I believe this is a duplicate of [#15846](https://github.com/vector-im/element-web/issues/15846)

I don't think that LaTeX parsing would (or should) be involved in \`\`\` code blocks.
Yet it seems that that issue is about at least three different problems at once. :frowning_face:

**Comment by turt2live** [comment] 2021-01-27 14:15
Duplicate of #15846

**Closed by turt2live** 2021-01-27 14:15 UTC
Labels: bug
