### ISSUE TITLE
Mentioned room isn't highlighted with red marker

### ISSUE THREAD

**Issue by Gnuxie** [vector-im/element-web#20879] opened 2022-02-02 17:29 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Having a room open that isn't the target room, or have the browser unfocused 

2. What do you click?

I got mentioned in a room several times but didn't get any counters on the left room sidebar (with all rooms selected). 
Though I will still get notified
 
3. More steps…
The room has mentions & keywords as the notification setting, is in my favourites and message previews are enabled

#### What did you expect?
There to be a red notification marker in the room
#### What happened instead?

Nothing, the room doesn't even have the "unread" dot, but i could see my name in the preview and i haven't opened it. There are no other sessions open that could have placed a read marker. 

I appreciate this might be difficult to track down

### Operating system

Manjaro Linux (kernel 5.15.16-1)

### Browser information

Firefox 96.0.3

### URL for webapp

app.element.io/

### Application version

Element version: 1.10.1 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-02-02 21:16
Duplicate of https://github.com/vector-im/element-web/issues/20859

**Closed by robintown** 2022-02-02 21:16 UTC
Labels: T-Defect
