### ISSUE TITLE
Give users the possibility to receive notifications for (emoji) reactions

### ISSUE THREAD

**Issue by lukasIO** [vector-im/element-web#16464] opened 2021-02-16 14:29 UTC
**Is your suggestion related to a problem? Please describe.**
We use element for work related messaging. A lot of times messages in a channel only need a short sign of agreement/approval which is a perfect use case for emoji reactions. Unfortunately there is no option to get notified about such reactions on my own messages.

**Describe the solution you'd like**
I think it would be great if there was an additional option in the notification settings to enable notifications for reactions. Default value should probably be off.

**Describe alternatives you've considered**
We considered replying with an emoji to the message, but that defeats somehow the purpose of the emoji reaction feature (which we really like), plus it get's cluttery if more people reply instead of reacting.

**Comment by t3chguy** [comment] 2022-02-28 07:51
The spec currently only allows setting notifications for all reactions, not just for reactions to your messages.

**Comment by turt2live** [comment] 2022-05-07 01:58
Effective duplicate of https://github.com/vector-im/element-web/issues/9792

**Closed by turt2live** 2022-05-07 01:58 UTC
Labels: A-User-Settings, A-Notifications, T-Enhancement, A-Reactions, X-Spec-Changes, O-Uncommon
