### ISSUE TITLE
Delay when marking/unmarking rooms as favourites

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18868] opened 2021-09-02 11:34 UTC
### Steps to reproduce

Right click on a room in the room list and mark it as a favourite in the context menu

### What happened?

Note there is a delay of up to several seconds before the menu disappears and the room list UI updates

### What did you expect?

For there not to be a delay. It feels like the UI is broken.

### Operating system

OS X

### Browser information

Chrome

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment] 2021-09-02 11:56
This looks like a server issue :( My delay is minimal for example

**Comment by robintown** [comment] 2021-09-02 12:03
Duplicate of https://github.com/vector-im/element-web/issues/14302

**Closed by robintown** 2021-09-02 12:03 UTC
Labels: T-Defect, X-Regression, S-Minor, O-Frequent
