### ISSUE TITLE
The effect for messages mentioning you could be more visually pleasing

### ISSUE THREAD

**Issue by Pointedstick** [vector-im/element-web#15659] opened 2020-11-05 23:09 UTC
### Description
When someone mentions you in a message, the whole message text turns red and the background is changed to a pale tan square:

![Screenshot_20201105_160722](https://user-images.githubusercontent.com/1097249/98306465-2233e280-1f81-11eb-8f5f-a4e4405f69ed.jpeg)

This is not very pretty and I feel like there may be a more visually appealing way to show it.

### Version information
- **Platform**: desktop
- **OS**: Linux: openSUSE Tumbleweed
- **Version**: 1.7.10

**Comment by turt2live** [comment] 2020-11-05 23:15
Posted twice? Duplicate of https://github.com/vector-im/element-web/issues/15660

**Closed by turt2live** 2020-11-05 23:15 UTC
Labels: bug, ui/ux

**Comment by Pointedstick** [comment] 2020-11-05 23:26
Yeah, my bad, sorry.
