### ISSUE TITLE
Default size of quoted or replied to messages is larger than the message itself

### ISSUE THREAD

**Issue by salbeira** [vector-im/element-web#16435] opened 2021-02-11 17:04 UTC
**Is your suggestion related to a problem? Please describe.**
Replying to a message adds the quoted message above your own. The size of this quotation item in the message is LARGER than the quoted message itself and of course larger than the reply to that message. This adds repeated clutter to the message log.

**Describe the solution you'd like**
Quoted or replied to copies of messages should be rendered in a smaller font and a more compact layout than what the message itself uses to make it clear that the quoted message is not more important than the reply. Not only that, but if your reply is itself ony one line large, the quoted line is huge compared to the reply itself, making it very taxing on the eye to follow a thread of messages.

**Describe alternatives you've considered**
Only a "in reply to username" box above the message in a small font.

**Comment by t3chguy** [comment] 2021-02-12 09:58
Duplicate of https://github.com/vector-im/element-web/issues/6579
Will be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3553

**Closed by t3chguy** 2021-02-12 09:58 UTC
Labels: suggestion
