### ISSUE TITLE
mobile UI spacing

### ISSUE THREAD

**Issue by fedon** [vector-im/element-web#14012] opened 2020-06-13 12:40 UTC
![confirmation-r](https://user-images.githubusercontent.com/2691833/84568699-7dbac500-ad81-11ea-8c12-d310e9368bfe.jpg)
![settings-lp](https://user-images.githubusercontent.com/2691833/84568701-7eebf200-ad81-11ea-9cf5-4aae185cca96.jpg)

### Description
On mobile screen there is limited space for chat message which is not used properly.

### Steps to reproduce
One can shrink browser window to get same perspective on desktop. See pics.
Settings are very problematic as well. Left panel should be removable/slide out.
Confirmations take to much horizontal space. It could be only vertical and/or limited to configurable number.
Timestamp and avatar take horizontal space.
Chat should have mobile layout or every feature has to have own configuration option.
Bottom buttons are too small for mobile and take horizontal space in message input bar. The buttons should be much bigger and shown on demand.

- **Platform**: PinePhone Web

For the web app:

- **Browser**: Firefox esr (68)
- **OS**: Linux
- **URL**:  riot.im/app /

**Comment by t3chguy** [comment] 2020-06-13 13:12
It is not a supported environment, even experimentally: https://github.com/vector-im/riot-web#supported-environments

**Comment by fedon** [comment] 2020-06-13 13:24
It is supported "Desktop OSes means macOS, Windows, and Linux versions for desktop devices that are actively supported by the OS vendor and receive security updates".

**Comment by t3chguy** [comment] 2020-06-13 13:28
> for desktop devices 

![image](https://user-images.githubusercontent.com/2403652/84569976-2c5f0580-ad82-11ea-9493-17efb074d09c.png)

**Comment by fedon** [comment] 2020-06-13 13:45
Do you think with Firefox on Android it will look somehow different?
Why Firefox on another supported mobile device won't be valid combination?
May be it is the time to reconsider? Unless you want me to move to Discord ;)

**Comment by darkdragon-001** [comment] 2020-10-11 08:00
Duplicate of #1633

**Closed** 2020-10-11 08:48 UTC
Labels: bug, ui/ux
