### ISSUE TITLE
Desktop client loses keys when disk is full

### ISSUE THREAD

**Issue by drue** [vector-im/element-web#4014] opened 2017-05-24 16:18 UTC
### Description

I ran out of disk space and I believe I rebooted in a disk full condition in order to lose swap files.  After reboot, I get vector-im/element-web#2996.  I'm not sure if vector-im/element-web#3660 is related or if desktop uses a real file API where you can avoid writing to a file when there is no disk space.

### Version information

- OSX Desktop 0.9.9

**Comment by ara4n** [comment] 2017-05-24 20:21
We currently use the localStorage API to store key data; we're about to switch to indexeddb though.  Both will likely fail if your disk fills however (although it shouldn't corrupt entirely, it's up to Chromium rather than us).  However, once #2286 you should at least be able to re-request the missing keys from other devices (including the sender).

**Comment by t3chguy** [comment] 2017-05-25 15:06
So I guess the same would happen in a browser?

**Comment by turt2live** [comment] 2017-05-25 15:10
Browser behaviour is to stop accepting new keys because it can't, leading to future messages being unable to decrypt. I've run into this failure mode many times on riot-web.

**Comment by t3chguy** [comment] 2017-05-25 15:11
@turt2live so #2996?

**Comment by turt2live** [comment] 2017-05-25 15:12
yes, but I'm not sure how desktop behaves, or how the browser behaves when your disk is full tbh.

**Comment by lampholder** [comment] 2017-05-30 09:18
Assigning a high severity and a low priority to reflect that this is highly disruptive but should be solved by #2286 (rather than taking specific steps to handle diskfill)

**Comment by drue** [comment] 2018-05-05 14:06
I'm tired of waking up to "* Unable to decrypt: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. **"  which means I have to quit Riot, delete all of Riot's files, launch and login again, and ask everyone to resend the messages I missed.  Riot taunts me with "Re-request encryption keys from your other devices."  but that doesn't work because I don't have another device.

I use my computer and sometimes it runs out of disk space.  You have to deal with it.  If you are using a broken library you have to patch it or find something else.  Nobody cares if Chrome is broken or whatever.  All they think is "Riot is shit and so is my friend for convincing me to use it."  So I can't recommend Riot to anyone at least until you fix this.

**Comment by axelsimon** [comment] 2018-11-26 10:02
For future reference and in hopes that it will be useful to others, here is how I got rid of this problem:
1. Clear up some space in your home directory (which in all likelihood is on the filesystem that is running out of space)
2. Quit Riot:
1.. If running as a standalone app, close the app
2.. If running as a browser tab, close the browser
3. Restart Riot
1.. Sart the standalone Riot app, or
2.. Start your browser

My encrypted conversations were all back to normal.

**Comment by axelsimon** [comment] 2018-11-26 16:40
Furthermore, would it be possible to show something friendlier to users, to help them? The current message is pretty horrible (you can't read your correspondant's messages, which is bad and stressful and makes you wonder if you've done something wrong, and on top of that the message is super technical/jargon-y).

Can I suggest: 

> Sorry, there is no disk space left on your device, because of this Riot couldn't store the secret keys needed to decrypt the message. Please make some space by deleting some data and restart Riot.

**Comment by t3chguy** [comment] 2020-04-11 23:29
this should now be alleviated on the Desktop app and Firefox where we get Persistent Storage permissions, in Chrome it may/may not get the permissions.

**Comment by axelsimon** [comment] 2020-05-15 10:29
This just happened to me on the desktop app and unfortunately, nothing is improved compared to the situation described several years ago.

The exact same message is still the one shown:
> Unable to decrypt: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing

That message should *really* be changed to something understandable by someone who doesn't have a PhD in databaseology.
How problematic would it be to just replace the current error message with the one i suggested in [November 2018](https://github.com/vector-im/riot-web/issues/4014#issuecomment-441708421)? Can there be another cause but lack of disk space for throwing "Unable to decrypt: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing"?

**Comment by jpeg2600** [comment] 2020-06-21 20:33
I'll just add to the issue that it just occured to me. My disk got full and somebody I couldn't receive or send encrypted messages on Riot afterward, previous messages showed the same failed transaction message. 

I didn't troubleshoot much. I restarted Riot and had access to the previous messages but couldn't send any. I just started a new encrypted room since it was a new server.

**Comment by 3nprob** [comment] 2022-07-09 01:16
@ara4n what prompted the change from P1to P3?

As it may not be clear: Element-desktop will still effectively fatally wipe existing local data/keys/history in the event of storage shortage. It seems prudent to me to prioritize doing what's possible to prevent this for keys, at least, maybe by taking another look at [storage API guarantees](https://github.com/matrix-org/matrix-js-sdk/blob/develop/docs/storage-notes.md).

**Comment by aaronraimist** [comment] 2022-07-09 01:17
@3nprob you are reading that backwards. It went from P3 to P1.

**Comment by 3nprob** [comment] 2022-07-09 01:21
@aaronraimist sorry, my bad, should not comment before coffee.

**Comment by richvdh** [comment] 2023-03-15 15:24
this sounds like a duplicate of #14174 (which is more recent, but has a clearer description of the symptoms), unless anyone can clarify the difference?

**Comment by richvdh** [comment] 2023-03-16 16:00
Duplicate of #14174

**Closed by richvdh** 2023-03-16 16:00 UTC
Labels: T-Defect, S-Critical, A-E2EE, A-Storage, O-Occasional
