### ISSUE TITLE
Error message when replies can't load is indistinguishable from an actual reply

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7989] opened 2019-01-03 12:43 UTC
<img width="770" alt="screenshot 2019-01-03 at 12 16 23" src="https://user-images.githubusercontent.com/1294269/50637320-7028cb00-0f51-11e9-947f-2e20b16916f5.png">

**Comment by yannicka** [comment] 2021-12-11 17:55
I think it's a duplicate of #6690.

**Closed** 2021-12-11 18:15 UTC
Labels: T-Defect, P2, S-Minor, A-Replies, X-Needs-Design
