### ISSUE TITLE
Remote control for screensharing

### ISSUE THREAD

**Issue by MagicMuscleMan** [vector-im/element-web#18993] opened 2021-09-11 03:42 UTC
#### What would you like to do?
Help someone remotely on their computer.

#### Why would you like to do it?
Because noone knows everything.

#### How would you like to achieve it?
During a screensharing, there should be a button to request remote control and to hand over remote control. Of course, the requested remote control needs to be accepted, first, before given.
If we want to be extra fancy, we could also implement auto control if there are multiple people in the screensharing session like a lot of other live collaboration systems do.

### Have you considered any alternatives?

Not using Matrix, but something more capable is an alternative, but I'd prefer if Element would enable it.

### Additional context

I am not sure, whether this is already part of the Matrix specification.

**Comment by SimonBrandner** [comment] 2021-09-11 05:55
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/3259

**Closed by SimonBrandner** 2021-09-11 05:55 UTC
Labels: T-Enhancement
