### ISSUE TITLE
New-style placeholder avatar layout is broken in MemberInfo

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#26058] opened 2023-08-26 16:42 UTC
### Steps to reproduce

1. Look at MemberInfo for a user without an avatar
2. Observe that the initial is not vertically centered, and is presumably too small, too.

<img width="402" alt="Screenshot 2023-08-26 at 17 40 52" src="https://github.com/vector-im/element-web/assets/1294269/eafd99d1-5456-4a49-84d0-6f8872dd7e45">

#### What did you expect?

pretty placeholder avatars.

#### What happened instead?

broken css

### Operating system

macOS

### Application version

nightly

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-08-28 10:46
Looks like the problem has been fixed in the meantime. Cannot reproduce with the current nightly version. Please leave a comment if the problem still exists.

**Comment by ara4n** [comment] 2023-09-01 09:28
it's got even worse now:

<img width="367" alt="Screenshot 2023-09-01 at 10 26 51" src="https://github.com/vector-im/element-web/assets/1294269/8b32ca31-6901-4fd0-9143-2bc73ed7c7cd">

**Comment by ara4n** [comment] 2023-09-01 09:28
(also https://github.com/vector-im/element-web/issues/26081)

**Comment by HarHarLinks** [comment] 2023-09-04 11:04
the v-centering seemed to variate when I'd play with resizing the window etc. it might be a case of not getting updated properly everytime it should

**Comment by Johennes** [comment] 2023-09-04 12:16
I'm going to close this over #26081 because these appear to essentially describe the same problem.

**Comment by Johennes** [comment] 2023-09-04 12:16
Duplicate of #26081

**Closed** 2023-09-04 12:16 UTC
Labels: T-Defect
