### ISSUE TITLE
Links ending in dot are not linkified correctly 

### ISSUE THREAD

**Issue by Rares95** [vector-im/element-web#14908] opened 2020-08-07 13:57 UTC
https://en.wikipedia.org/wiki/A.T.O.M.

Take this link for example. The linkifier doesn't count the last dot as part of the link on Desktop at least

**Comment by odiferousmint** [comment] 2020-08-07 20:56
They are not linkified here either for a reason. I am not sure of a good solution. Example: `Foo: https://bar.baz.`. In this case the URL would be `https://bar.baz.`. :/

**Comment by t3chguy** [comment] 2020-08-08 09:24
> because it gets formatted automatically and turns it into an element of a list which, IMO, is problematic. I would love to have the option to turn that off.

Completely unrelated to this issue.

This issue about linkification which happens on receipt

Markdown parsing (commonmark) happens on send and you can use `/plain` to not have it applied.

**Comment by Rares95** [comment] 2020-08-08 09:28
On Microsoft Edge for Windows 10 it works fine. On Firefox Focus or Edge on Android it does not

**Comment by t3chguy** [comment] 2020-08-11 08:48
> On Microsoft Edge for Windows 10 it works fine. On Firefox Focus or Edge on Android it does not

Can you show an example of what you mean? Screenshots are great.

**Comment by odiferousmint** [comment] 2020-08-12 22:37
> Completely unrelated to this issue.

Not to my half-assed proposal though. :P That was just an example, but my point was that it is definitely doable to do links that way. As far as Markdown parsing is concerned, I definitely would like to have an option to disable it altogether so I will not have to type `/plain` all the time. :P (Yes, this is unrelated, not sure if the issue is still opened or not.)

But yeah, I am not sure if this is going to work. Currently `,` and `.` and perhaps other special characters are not considered as being part of the URL, which is the best way to go, IMO. My half-assed solution was to be able to insert links and send them as-is, with those special characters. So by default (without using the formatter), `https://foobar.` would send `https://foobar`, but with the formatter it would send `https://foobar.`.

I hope it makes sense, I am exhausted.

**Comment by t3chguy** [comment] 2020-08-12 22:39
You can use the commonmark URL syntax `<URL>` which works with trailing dots:

![image](https://user-images.githubusercontent.com/2403652/90075333-03f97600-dcf5-11ea-80e8-5c12642615b5.png)

**Comment by odiferousmint** [comment] 2020-08-15 22:18
Yup, that is what I had in mind. Seems like it is implemented!

**Comment by t3chguy** [comment] 2020-08-17 09:09
Closing as a non-issue.
Often people put a link at the end of a sentence and would hate for every link to be broken by the appended `.`

This is typical behaviour elsewhere such as here on github too. If you want to explicitly mark the dot as part of the link you can either use link `[text](url)` syntax or use the explicit URL `<url>` syntax

**Closed by t3chguy** 2020-08-17 09:09 UTC
Labels: bug
