### ISSUE TITLE
Notification dot/number on pinned desktop app

### ISSUE THREAD

**Issue by ArtexJay** [vector-im/element-web#22475] opened 2022-06-08 00:23 UTC
#### What would you like to do?
Add notification dot/marker/number on Element icon if it's open or pinned on the taskbar.
![image](https://user-images.githubusercontent.com/32932497/172505354-dca2c4d1-f075-4b80-a596-5934d6381e7e.png)

#### Why would you like to do it?
It would be easier to notice/see it compared to when it's in the system tray.

**Comment by t3chguy** [comment] 2022-06-08 07:11
Duplicate of https://github.com/vector-im/element-web/issues/14033

**Closed by t3chguy** 2022-06-08 07:11 UTC
Labels: T-Enhancement

**Comment by ArtexJay** [comment] 2022-06-09 01:06
> Duplicate of #14033

thanks, didn't see/find it when i searched for it myself.
