### ISSUE TITLE
Odd decryption error

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22294] opened 2022-05-20 12:20 UTC
### Steps to reproduce

Not sure, have threads enabled and this is happening in a threaded reaction

#### What did you expect?
Can see my own messages

#### What happened instead?
`** Unable to decrypt: Error: Mismatched room_id for inbound group session (expected !ELvLSzljqBuAwjdBWx:t2l.io, was undefined) **`

Original event source:
```
{
  "content": {
    "algorithm": "m.megolm.v1.aes-sha2",
    "ciphertext": "AwgCEoAC3Iwo6ZZ83IaKpvK1oPtVsREasblaIOhr1yFD5Aa8/0cl69Upzz7L5Y64fSjpymSzYSNC6S4SV8fmVgrae5W2qCc+vCQ3iiIrloZ2nMu5by0eWrSULIPwvbi07uh9imha/k2TKyS5/YZ07DPd88849FlqDATQBJiRm3LCVv4OAplty5a0KFLGo/LTvHeDKCwtzmJQESfRZqnA8ebmV7KmGDY7OSqirT5UyxkFEFiJxbAuqerEZgR/lCYzWiHPHJIvfaMwS36zQV/LjMWASc2UP3BJtGHQT0LjBGX1Ac3wWk3TbFMB54y4isL/AyZtPey7gDZwI/XsgvgYitpmgjqWUIvU8KIQpy+320IrQZkWWokRCuI0fDfa5YoK10eMYtLvBL0gmkBs+j+8HagA62ZFnAXq62Q6UkI63d1XAF1AwEm3jFkQ12NKBA",
    "device_id": "DNGUKBYLBB",
    "m.relates_to": {
      "event_id": "$LxwG5wSz3C0LSBo-an5hJ6trFO0eCBa_NWdcdU50z18",
      "is_falling_back": true,
      "m.in_reply_to": {
        "event_id": "$D5BeVjGRnWFACju2tWQWPlOzYznmiCRjoLVfn_ZKerc"
      },
      "rel_type": "m.thread"
    },
    "sender_key": "pq3xg1h8Df/eLp661Ka4b80xsEPhfbZM0NVcR0W+/B0",
    "session_id": "3NzbKybz16n+eZkOrF+Jl+9O/ZM4p4GFuhysDed1TXA"
  },
  "origin_server_ts": 1653039284977,
  "sender": "@kittykat:matrix.org",
  "type": "m.room.encrypted",
  "unsigned": {
    "age": 9833017,
    "transaction_id": "m1653039284761.91",
    "m.relations": {
      "m.annotation": {
        "chunk": [
          {
            "type": "m.reaction",
            "key": "👍️",
            "count": 1
          }
        ]
      }
    }
  },
  "event_id": "$ovI7xfuAL_7zlB8ff66NDMVTV92AUOCjzDg6o58aVnQ"
}
```

![Screenshot from 2022-05-20 11-26-24](https://user-images.githubusercontent.com/51663/169526397-a0979af9-d788-453b-b365-3809ad871de5.png)

### URL for webapp

develop.element.io

### Application version

Element version: fab52795e355-react-804ddbb332fc-js-e81d84502b66 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-05-20 12:32
Duplicate of https://github.com/vector-im/element-web/issues/22094

**Closed by t3chguy** 2022-05-20 12:32 UTC
Labels: T-Defect, A-E2EE
