### ISSUE TITLE
Logging in with multiple user accounts

### ISSUE THREAD

**Issue by augusto-herrmann** [vector-im/element-web#15974] opened 2020-12-15 11:52 UTC
**Is your suggestion related to a problem? Please describe.**
Suppose I have two different user accounts: one related to my real identity and another one using a pseudonym. If I want to log in to the web app with both user accounts simultaneously, I have to use either two different browsers or a private window.

**Describe the solution you'd like**
I would like to be able to open two different tabs in the same browser and use different Matrix accounts in each one of them.

**Describe alternatives you've considered**
1. Using two different browsers, however keeping two browsers open all the time consumes more memory and more windows to manage.
2. Using a private window in one of the accounts, however, when you open links, they are open in the private window and treated as such (i.e.: does not keep visited links in browser history, cannot access other things you are logged in, etc.).

**Additional context**
For the UI, you could perhaps allow the user to switch between logged in accounts by clicking the user handle on the upper left corner.

**Comment by t3chguy** [comment] 2020-12-15 12:15
Duplicate of https://github.com/vector-im/element-web/issues/2320

**Closed by t3chguy** 2020-12-15 12:15 UTC
Labels: suggestion

**Comment by augusto-herrmann** [comment] 2020-12-15 18:04
Sorry for the duplicate. I really did search the issues before creating this. but did not find that one.
