### ISSUE TITLE
URL detection / highlight doesn't match certain URLs

### ISSUE THREAD

**Issue by agilob** [vector-im/element-web#15163] opened 2020-09-13 19:23 UTC
Link to pic on wikipedia https://en.wikipedia.org/wiki/Faroe_Islands#/media/File:Faroe_Islands,_Bor%C3%B0oy,_Klaksv%C3%ADk_(3).jpg

Link is incorrectly detected so can't be clicked to see the picture
![image](https://user-images.githubusercontent.com/2544251/93026594-9479ed80-f5f6-11ea-9cf9-cb3ecba99e60.png)

**Comment by turt2live** [comment] 2020-09-13 19:57
Duplicate of https://github.com/vector-im/element-web/issues/4674

**Closed by turt2live** 2020-09-13 19:57 UTC
Labels: bug, ui/ux

**Comment by agilob** [comment] 2020-09-13 21:05
>dbkr opened this issue on Jul 25, 2017 · 6 comments 

![image](https://user-images.githubusercontent.com/2544251/93028670-d3af3b00-f604-11ea-90dd-2bc538d0fcf4.png)
