### ISSUE TITLE
Jitsi video conference/call: No video (webcam) nor screen share possible in element-desktop

### ISSUE THREAD

**Issue by Chaz-Photonicity** [vector-im/element-web#23769] opened 2022-11-15 07:00 UTC
### Steps to reproduce

Steps to reproduce (very similar bug as #23028)

- Create a room with more than 2 people in element-desktop.
- Click the video button at the top to start a Jitsi conference.
- Try to use the webcam or try to start a screen share.
- The other people within the call can not see my webcam and I'm unable to choose a window for screen sharing (because the loading wheel spins forever).

#### What did you expect?

- I did expect to share my video from my webcam.
- I did expect to share my screen and/or choose a window to share in the Jitsi widget.

#### What happened instead?

- I can start my webcam (video) stream but the other people can not see it.
- I cannot choose a window or a display to share with the others.

### Operating system

Windows 10.0.19044 build19044

### Application version

Element version: 1.11.14 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started#download

### Homeserver

https://matrix-client.matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-11-15 08:59
How is this different from https://github.com/vector-im/element-web/issues/23028? Can you reliably repro the issue with the webcam? As said before the screen-sharing issue is #4880

**Comment by Chaz-Photonicity** [comment] 2022-11-15 09:01
> How is this different from #23028? Can you reliably repro the issue with the webcam? As said before the screen-sharing issue is #4880

Thanks for response Simon.  Indeed I can repro.  I don't think it's webcam issue .. i can see my video on the same device.  it's just that others can't see.  BTW I'm unable to find any solution to problems of #23028 and #4880.

**Comment by robintown** [comment] 2022-11-16 16:05
@Chaz-Photonicity Are the other users on the call joining from the mobile apps?

**Comment by turt2live** [comment] 2023-01-10 00:45
Closing due to lack of information. If this is still happening, please open a new issue with fresh reproduction steps for our QA team to review.

**Closed by turt2live** 2023-01-10 00:45 UTC
Labels: T-Defect, X-Needs-Info, A-Jitsi
