### ISSUE TITLE
send message textarea should be resized

### ISSUE THREAD

**Issue by FlyingHarman** [vector-im/element-web#21097] opened 2022-02-16 09:18 UTC
#### What would you like to do?
textarea could be resized
#### Why would you like to do it?
multiline-text could be shown all on the screen 
#### How would you like to achieve it?
easy for typing and find

**Comment by t3chguy** [comment] 2022-02-16 10:33
Duplicate of https://github.com/vector-im/element-web/issues/5882

**Closed by t3chguy** 2022-02-16 10:33 UTC
Labels: T-Enhancement
