### ISSUE TITLE
Not displaying reply 

### ISSUE THREAD

**Issue by InezMc** [vector-im/element-web#25673] opened 2023-06-27 15:09 UTC
### Steps to reproduce

<img width="577" alt="image" src="https://github.com/vector-im/element-web/assets/71381074/fd829ed1-c184-484b-aabe-2c3756c5d169">

I have permission for room, and it is a reply to my message that I was replying to but a few days earlier. 

#### What did you expect?
 my reply to be visible
#### What happened instead?

the below text 
<img width="577" alt="image" src="https://github.com/vector-im/element-web/assets/71381074/365700cb-8661-4f7a-ba85-9a059b8880ef">

### Homeserver

m.org

### Will you send logs?

Yes

**Comment by robintown** [comment] 2023-06-28 16:10
Duplicate of https://github.com/vector-im/element-web/issues/10856

**Closed by robintown** 2023-06-28 16:10 UTC
Labels: T-Defect
