### ISSUE TITLE
Custom "nicknames" in DMs

### ISSUE THREAD

**Issue by ArtexJay** [vector-im/element-web#21226] opened 2022-02-26 20:00 UTC
#### What would you like to do?
I'd like to have to have nicknames/custom names set for people in the DM's, etc.

#### Why would you like to do it?
So i don't confuse my family or friends with each other or other people, and know exactly who I am talking to. This could be dependent to each user and will offer personalization as well easier identification of who you are/have been talking to by their name.

#### How would you like to achieve it?
Add option in the DMs settings to add a nickname to the user. This will replace their username within the chat only and will only be visible to you. Not everyone or the other person.

### Have you considered any alternatives?

I wasn't able to find any alternatives.
If there are, I'd like to know them.

**Comment by robintown** [comment] 2022-02-26 21:27
Duplicate of https://github.com/vector-im/element-web/issues/3130

**Closed by robintown** 2022-02-26 21:27 UTC
Labels: T-Enhancement
