### ISSUE TITLE
Chrome's "Suggest Password" feature doesn't work on the registration page

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8841] opened 2019-02-20 20:42 UTC

**Comment by MadLittleMods** [comment] 2020-11-12 18:45
This seems like a good onboarding `delight` issue to make signing up easier. cc @neilisfragile 

I ran into this when trying to create a test user fast.

**Comment by t3chguy** [comment] 2020-11-13 00:41
I don't think there is anything we can do here, the heuristic they use is not documented. Their own user docs say it doesn't always show up and the user should right click which already works in Element:

![image](https://user-images.githubusercontent.com/2403652/99013470-7d993e00-2548-11eb-886a-d5e33cf83389.png)
https://support.google.com/chrome/answer/7570435?co=GENIE.Platform%3DDesktop&hl=en

Tried copying the input from Trello and no luck.

From testing, it looks like it only works on Password fields which exist at the initial point.
I deleted the password field in Trello only to re-add it identically and then it no longer worked.
Given that Element is a Single Page App then it cannot make this work given the current heuristic.

**Comment by MadLittleMods** [comment] 2020-11-13 01:47
Looking at this more, for the "Suggest password" option to show up, it needs to be a synced Chrome profile.

And my test users are using unsynced Chrome profiles which explains why I was missing this. Although those profiles can still save passwords, Chrome seems to have this conditional around the suggestion feature.

Thanks for looking into this @t3chguy! In that case, can this issue be closed? The right-click option is what I was after and was checking for. It's there, just use a synced Chrome profile which applies to everyone.

**Comment by turt2live** [comment] 2020-11-13 07:29
this issue is hoping for the automatic suggestion of a password without manual intervention, though there's a good chance we won't be able to fix it :(

**Comment by t3chguy** [comment] 2020-11-13 09:34
After sleeping on it, given that I'm fairly confident we cannot make it work without manual intervention, I am closing this issue. If it magically starts to work on single page apps in the future then we can investigate whether we can join the club

**Comment by turt2live** [comment] 2020-11-13 14:46
I have visibility on a screenshot where this works in Riot, so reopening.

**Comment by t3chguy** [comment] 2023-06-08 12:29
Duplicate of https://github.com/vector-im/element-web/issues/6353

**Closed by t3chguy** 2023-06-08 12:29 UTC
Labels: T-Defect, P1, S-Minor, A-Registration
