### ISSUE TITLE
Notification settings not saving in macOS app

### ISSUE THREAD

**Issue by fm** [vector-im/element-web#12289] opened 2020-02-07 16:59 UTC
### Description

Some notification settings are not saving in macOS app, it either does nothing; or spins like it's saving, but doesn't save changes

### Steps to reproduce

- Go to Settings -> Notifications
- Switch _**Messages containing keywords**_ from `On` to `Noisy` and nothing happens
- Switch _**When rooms are upgraded**_ from `Noisy` to `On` and it spins like it's saving, but does not save changes. Tried restarting app in case it was a cache issue, and effectively did not save.

_**Call invitation**_ however, does save correctly. So does _**When I'm invited to a room**_

**Video**: [https://ttm.sh/ESU.mov](https://ttm.sh/ESU.mov)

### Version information

- **Platform**: desktop and web
- **OS**: macOS Catalina 10.15.3
- **Versions**: 
_Desktop_:
matrix-react-sdk version: `<local>`
riot-web version: 1.5.8
olm version: 3.1.3
_Web_:
matrix-react-sdk version: `<local>`
riot-web version: 1.4.2
olm version: 3.1.0

- **Browser**: Safari 13.0.5 (15608.5.11)
- **Web URL**: https://riot.privacytools.io

**Comment by t3chguy** [comment] 2023-07-10 11:42
Duplicate of https://github.com/vector-im/element-web/issues/8632

**Closed by t3chguy** 2023-07-10 11:42 UTC
Labels: T-Defect, A-User-Settings, A-Notifications
