### ISSUE TITLE
Sidebar hiding "Rooms" and "Persons" on every start if no Space is available

### ISSUE THREAD

**Issue by kubax** [vector-im/element-web#21730] opened 2022-04-10 09:43 UTC
### Steps to reproduce

Every restart of Element-desktop (affacting Elements-web also) the "Rooms" and "Persons" button on the sidebar is hidden, if no Space is created. When a space is created, the Roms and Persons Button keep persistent over restart of the application.

As i don't see a use (for me) in spaces, i don't use them. But i see a use in the Persons and Rooms button, because i have many DMs and a lot of Rooms. Having to constantly scroll between the two. So i started using the Personst and Rooms buttons, instead of the Home button.

But i have to manually disable and reenable at least one of the sidebar buttons to have both shown, on every restart until i have a space created.

#### What did you expect?
having rooms and personst show, even if there are no spaces created if configured so.

#### What happened instead?
rooms and persons are hidden on restart if no spaces are configured

### Operating system

Arch Linux

### Application version

Version von Element: 1.10.8 Version von Olm: 3.2.8

### How did you install the app?

Arch community repositories (but does also happen on aur repository)

### Homeserver

Docker container running docker.io/matrixdotorg/synapse:latest

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-04-11 08:52
Duplicate of https://github.com/vector-im/element-web/issues/21006

**Closed by t3chguy** 2022-04-11 08:52 UTC
Labels: T-Defect
