### ISSUE TITLE
Space members panel does not change when changing spaces

### ISSUE THREAD

**Issue by jerrykan** [vector-im/element-web#17376] opened 2021-05-19 07:53 UTC
### Description

The right-hand space members panel continues to show members for the previous space when switching to another space.

### Steps to reproduce
- Right-click on a Space and select "Members"
- See that the right hand panel show the members for the current space
- Click on another space to change spaces
- See that the right-hand panel still shows the members (and title) for the previously select space

I would expect that when changing spaces the right-hand panel would update to show information for the newly selected space, or at a minimum collapse/disappear. If the collapse/disappear option is the preferred solution, then I would expect the panel to reappear when I next go back to the space that was showing the members right-hand panel.

### Version information
- **Platform**: web (in-browser)
- **Browser**: Firefox 86.0 (64-bit)
- **OS**: Linux (Debian testing)
- **URL**: app.element.io

**Comment by SimonBrandner** [comment] 2021-05-19 07:55
Duplicate of [#16911](https://github.com/vector-im/element-web/issues/16911)

**Comment by SimonBrandner** [comment] 2021-06-22 13:37
Apparently, I got confused when I closed this. This is a separate issue

**Comment by SimonBrandner** [comment] 2021-12-30 14:24
I does now, afaik

**Closed by SimonBrandner** 2021-12-30 14:24 UTC
Labels: T-Defect, A-Member-List, A-Spaces, X-Needs-Design, A-Right-Panel, O-Occasional
