### ISSUE TITLE
use the same color for display name and fallback avatar

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17413] opened 2021-05-20 10:20 UTC
#### Is your suggestion related to a problem? Please describe.
Both colors are not user configurable (unless using an avatar image). From what I can tell, they're always different colors. This, in my mind, leads to a worse ability to make a mental link between both. Especially when searching the DM in room list, since it uses the avatar color.

#### Describe the solution you'd like.
For now, unify color generation algorithm.
In the long term I'd like to see user definable colors as part of global/space/room profiles.

#### Additional context
#11816

**Comment by t3chguy** [comment] 2021-05-20 10:22
Related https://github.com/vector-im/element-web/issues/2449#issuecomment-506478258

**Comment by robintown** [comment] 2021-07-16 02:58
So I tried this, and of course it looks good in the timeline, but it also starts to really change the look and feel of the room list, introducing a lot more visual noise:

![Screenshot 2021-07-15 at 22-35-23 Element dnd time baybee](https://user-images.githubusercontent.com/48614497/125883683-39d63a5a-edaa-452f-b21b-99528ff6d697.png)

(this example is showing rooms, but of course you get a similar rainbow effect for DMs without avatars)

**Comment by robintown** [comment] 2021-07-16 04:23
Actually, this is a duplicate of #13490

**Closed by robintown** 2021-07-16 04:23 UTC
Labels: A-Avatar, T-Enhancement, X-Needs-Design
