### ISSUE TITLE
May I ask if it is possible to add a web page adaptive mobile browser

### ISSUE THREAD

**Issue by 337077418** [vector-im/element-web#26513] opened 2023-11-07 03:58 UTC
### Your use case

For some reasons, we do not allow the installation of apps and require the use of a mobile browser

**Comment by weeman1337** [comment] 2023-11-07 08:01
Thanks for reporting the issue @337077418  . Unfortunately mobile browsers are currently not supported, see [here](https://github.com/vector-im/element-web#supported-environments). However you could use other clients that scale on mobile, such as https://github.com/vector-im/hydrogen-web/

**Comment by weeman1337** [comment] 2023-11-07 08:01
Duplicate of https://github.com/vector-im/element-web/issues/24082

**Closed by weeman1337** 2023-11-07 08:01 UTC
Labels: T-Enhancement

**Comment by 337077418** [comment] 2023-11-07 08:12
> Hydrogen-web/

[Hydrogen-web/](https://github.com/vector-im/hydrogen-web/)
I have already tried Hydrogen
But it has issues and cannot communicate with the app. Messages sent from the web cannot be decrypted by the Android app

After both sides have undergone facial expression verification, it is normal for Android to send messages to the web. Messages sent by the web cannot be decrypted by Android
