### ISSUE TITLE
Expand topic of the room when clicked on it

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#17916] opened 2021-07-08 13:51 UTC
A-La discord;

![image](https://user-images.githubusercontent.com/22740616/124933387-23337d00-e004-11eb-9cad-2815b9673f68.png)

Or maybe in the sidebar. For that matter, maybe it's interesting to place the topic somewhere under "about" in this section anyways;
![image](https://user-images.githubusercontent.com/22740616/124933581-49f1b380-e004-11eb-8400-f6d5648b3ff7.png)

**Comment by t3chguy** [comment] 2021-07-08 13:53
Duplicate of https://github.com/vector-im/element-web/issues/9623

**Closed by t3chguy** 2021-07-08 13:53 UTC
Labels: A-Room-View, T-Enhancement, X-Needs-Design
