### ISSUE TITLE
Fix react error on share dialog

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21475] opened 2022-03-18 16:16 UTC
### Steps to reproduce

1. Hover over an event
2. Select "share" in the message action bar to open the share dialog

#### What did you expect?

no error

#### What happened instead?

In the console I can see

```
Warning: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
```

### Will you send logs?

No

**Comment by yaya-usman** [comment] 2022-03-25 20:53
hey @gsouquet can i get assigned this issue

**Comment by SimonBrandner** [comment] 2022-03-26 07:22
@yaya-usman, I've assigned you to the issue. If you need any help/have any questions be sure to visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)!

**Comment by yaya-usman** [comment] 2022-03-26 09:26
@SimonBrandner thanks, let me start working on it

**Comment by yaya-usman** [comment] 2022-03-27 17:56
Hi @SimonBrandner , i just set up element-web on my pc and is running on localhost, i can't seem to find where events are located,i could only find share rooms not share events, can you kindly drop screenshots so i can reproduce the issue. Thanks

**Comment by SimonBrandner** [comment] 2022-03-27 18:00
![2022-03-27_20-00](https://user-images.githubusercontent.com/25768714/160294387-cae0045f-0641-49b0-9e9a-6e69ae36dc81.png)

Let me know if it is clearer now?

**Comment by yaya-usman** [comment] 2022-03-27 18:17
> ![2022-03-27_20-00](https://user-images.githubusercontent.com/25768714/160294387-cae0045f-0641-49b0-9e9a-6e69ae36dc81.png)
> 
> Let me know if it is clearer now

Yes,thanks

**Comment by yaya-usman** [comment] 2022-03-27 21:24
@SimonBrandner I have fixed this issue since, but i am having issues pushing my changes to my forked version so i could make a pull request, it's giving me remote push rejected

**Comment by yaya-usman** [comment] 2022-03-27 21:28
> @SimonBrandner I have fixed this issue since, but i am having issues pushing my changes to my forked version so i could make a pull request, it's giving me remote push rejected

The thing is i only cloned the main repo the element-web and followed the guide in setting up the local version by linking matrix-react-sdk and matrix-js-sdk repos, so do i need to fork the supporting repos as well? For instance i only made changes to matrix-react-sdk, so i want to push my changes from there since element-web is linked to it, but somehow it's not working.

**Comment by SimonBrandner** [comment] 2022-03-28 04:39
> so do i need to fork the supporting repos as well?

Yes, you need to fork all the repos, if you make changes to the react-sdk, you only push the changes and make PR from there.

Though, I would suggest asking these questions in https://matrix.to/#/#element-dev:matrix.org

**Closed** 2022-03-28 16:58 UTC
Labels: T-Defect, S-Tolerable, A-Share, O-Uncommon, good first issue
