### ISSUE TITLE
Jitsi widget too sticky

### ISSUE THREAD

**Issue by InezMc** [vector-im/element-web#17524] opened 2021-06-01 12:20 UTC
### Description

First time using the jitsi conference widgit. When exiting I was not able to close the widget. 
What I tried: 
- Switched windows, 
- tried reopening the conference to close it but it was unresponsive
- closed element and opened again
- Restarted computer (this resolved it) 

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent    

![Capture-jitsi conference](https://user-images.githubusercontent.com/71381074/120321869-b548b700-c2db-11eb-8567-b8107b36e41c.JPG)
### Version information

- **Platform**: 
desktop?

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows,  
- **Version**: 20H2

**Comment by InezMc** [comment] 2021-06-01 12:27
Just remembered I also ended up telling the widget to open in my browser after opening it on element.

**Comment by Palid** [comment] 2021-07-23 14:36
Duplicate of https://github.com/vector-im/element-web/issues/17226

**Closed** 2021-07-23 14:42 UTC
Labels: A-Jitsi, A-Widgets, P2, S-Major, T-Defect
