### ISSUE TITLE
Replies to threads sent from clients without threads support appear in the thread sporadically

### ISSUE THREAD

**Issue by waldyrious** [vector-im/element-web#21803] opened 2022-04-14 15:41 UTC
### Steps to reproduce

I tried the threads feature in a test conversation I had created with myself on gitter, and indeed the responses appear in the thread in both places, but on Element the Gitter messages disappeared after reloading the page. Additionally, the third thread message from Gitter appeared as a regular reply in the main timeline on Element, rather than as a thread message (the first two did appear in the thread panel in Element).

Here's what I see on Element:

![image](https://user-images.githubusercontent.com/478237/163423801-cb466816-8d3d-40a2-9ba2-d72a87c495fa.png)

And this is what I see on Gitter:

![image](https://user-images.githubusercontent.com/478237/163423902-6d926337-fbeb-4bcd-ac36-381a134de2f3.png)

On both Element and Gitter, the situation remained the same after refreshing the page.

#### What did you expect?

I expected Element to show the thread responses from Gitter normally, as they appear in the Gitter side.

#### What happened instead?

Threaded messages from gitter had 3 problems:
1) they showed a quote of the previous message (i.e. as if they were replies inside the thread panel);
2) they disappeared after refreshing the page;
3) two of them appeared in the thread panel, but the third appeared as a reply. This is likely because it came after another Gitter reply, which, from Element's POV, does not exist — hence the error message:
   > Unable to load event that was replied to, it either does not exist or you do not have permission to view it.

### Operating system

Ubuntu

### Browser information

Firefox 99.0

### URL for webapp

https://app.element.io

### Application version

Element version: 1.10.10, Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2022-04-15 07:32
This seems to be a duplicate of https://gitlab.com/gitterHQ/webapp/-/issues/2830; Gitter doesn't support stable Matrix threads

**Comment by waldyrious** [comment] 2022-04-15 15:09
Oh, cool, thanks for pointing me there.

I still think that Element doesn't handle the replies sent from Gitter in a reasonable manner. Showing them in the thread panel, giving the appearance of support, but then lose track of them after a reload, doesn't seem like a good way to handle this situation.

I would rather get an error message of some kind (e.g. "unexpected message format" or something along those lines), which would be up-front and honest about what is supported or not. And the messages should definitely not disappear into the ether, either.

**Comment by robintown** [comment] 2022-04-15 15:39
Reopening this to track the reply fallback functionality for threads being unreliable

**Comment by t3chguy** [comment] 2022-04-20 08:16
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/2305

**Closed by t3chguy** 2022-04-20 08:16 UTC
Labels: T-Defect, S-Minor, A-Threads
