### ISSUE TITLE
Image paste doesn't work in rich text editor

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#24041] opened 2022-12-16 15:23 UTC
### Steps to reproduce

1. Enable rich text editor from Labs.
2. Copy an image to clipboard using e.g. Windows Snippets.
3. Click to rich text editor and press Ctrl+V.
4. Nothing happens.

#### What did you expect?
Upload box with image preview shown.

#### What happened instead?
Nothing.

### Operating system

Windows 10

### Browser information

Firefox 108.0

### URL for webapp

https://develop.element.io

### Application version

Element version: a7124c935ece-react-f1e8e7f1406a-js-c973b26fa26e Olm version: 3.2.12

### Homeserver

self hosted Synapse 1.73.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-12-16 15:31
Duplicate of https://github.com/vector-im/element-web/issues/23870

**Closed by t3chguy** 2022-12-16 15:31 UTC
Labels: T-Defect, S-Minor, A-Media, A-File-Upload, A-Composer, A-Shortcuts, O-Occasional, Z-Labs, A-Rich-Text-Editor
