### ISSUE TITLE
UTD

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-web#25745] opened 2023-07-10 08:05 UTC
### Steps to reproduce

1. Receive message

#### What did you expect?
Able to decrypt

#### What happened instead?
Unable to decrypt

### Operating system

Windows

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-07-10 08:17
Duplicate of https://github.com/vector-im/element-meta/issues/245

**Closed by t3chguy** 2023-07-10 08:17 UTC
Labels: T-Defect
