### ISSUE TITLE
https://staging.element.io/#/home is missing big "Log in" and "Register" buttons

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19420] opened 2021-10-18 09:08 UTC
### Steps to reproduce

1. Go to https://staging.element.io/#/home
2. Remember that you have a user account or decide that you really want to register now

#### What did you expect?
As a guest, I really want to use Element so want it to be easy to register an account (or log into an existing account). I would maybe expect them as big action buttons under the three action buttons in the middle of the screen.

#### What happened instead?
Had to click on Guest to see options to log in or register

![Screenshot from 2021-10-18 09-56-31](https://user-images.githubusercontent.com/51663/137702208-29e36009-2b92-492b-aff7-a66a6e75efb6.png)

**Comment by t3chguy** [comment] 2023-04-25 14:42
Not sure where you're getting `/#/home` from - but I think you're looking for https://staging.element.io/ or https://staging.element.io/#/welcome

This also isn't specific to staging, identical on app & develop.

**Comment by t3chguy** [comment] 2023-04-25 14:48
Duplicate of https://github.com/vector-im/element-web/issues/14769

**Closed by t3chguy** 2023-04-25 14:48 UTC
Labels: T-Defect, A-Login, Z-FTUE, Z-Community-Testing
