### ISSUE TITLE
Ringing call popup's avatar cutout is vertically stretched to full height

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#26598] opened 2023-11-16 11:42 UTC
### Steps to reproduce

1. Receive a video call

#### What did you expect?
avatar is displayed in a circle shape
#### What happened instead?
the avatar itself is displayed i a circle shape. for some reason, the background has a white "cutout" which stretches to the full height

### Operating system

Arch

### Browser information

Firefox 119

### URL for webapp

develop.element.io

### Application version

sorry reloaded already :(

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-11-16 11:45
Duplicate of https://github.com/vector-im/element-web/issues/26183

**Closed by t3chguy** 2023-11-16 11:45 UTC
Labels: T-Defect

**Comment by HarHarLinks** [comment] 2023-11-16 12:05
Hm yes it indeed looks a lot like that issue, except I don't share the point of the narrow window: my window is maximized on 2560x1440 at ~27" (~18 ppi)
