### ISSUE TITLE
Clicking a voice message in a reply both play the message and move to its current location

### ISSUE THREAD

**Issue by grimhilt** [vector-im/element-web#22781] opened 2022-07-08 19:37 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Having a voice message and reply to it with anything.
3. What do you click?
Click the pause-play-button of the voice message in the reply field

#### What did you expect?
I would expect the voice message to be played.

#### What happened instead?
The voice message is played but I am moved to its current location which is inconvenient as I do not see the audio i am playing and I wasn't expected to be moved around. 

Moreover it also start a playback queue which isn't expected.

### Operating system

Windows

### Browser information

Firefox

### URL for webapp

app.element.io

### Application version

Element version: 1.11.0 Olm version: 3.2.8

### Homeserver

non public homeserver

### Will you send logs?

No

**Comment by turt2live** [comment] 2022-07-08 20:54
This isn't specific to voice messages: clicking on the media in a reply jumps rather than opens, such as on images and videos.

**Comment by grimhilt** [comment] 2022-07-08 22:09
Indeed, but in this case the media's action is trigger and there is a reply jumps.
I would expect only the action and not the jumps as when clicking a link in a reply.

**Comment by grimhilt** [comment] 2022-07-08 23:58
Related to #18599

**Comment by SimonBrandner** [comment] 2022-07-09 07:30
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/20150

**Closed by SimonBrandner** 2022-07-09 07:30 UTC
Labels: T-Defect
