### ISSUE TITLE
Missing session data on desktop

### ISSUE THREAD

**Issue by Kryptor-Software** [vector-im/element-web#15214] opened 2020-09-16 15:16 UTC
### Description

Sometimes after closing the Element desktop application, there's a 'Missing session data' pop-up the next time the program is run. You are then forced to sign out, all old messages have a shield icon next to them, and Element creates a new session. This has happened to me at least five times. It has happened on both Windows and Linux. Logs have been sent.

### Steps to reproduce

- Close the desktop application
- Relaunch the program

### Describe how what happens differs from what you expected.

The session data shouldn't be getting erased. Furthermore, perhaps old messages shouldn't be given a shield icon that you cannot hide, and Element shouldn't create a new session.

![Screenshot from 2020-09-16 16-03-50](https://user-images.githubusercontent.com/63159663/93355693-3fc4b580-f836-11ea-8c87-050675cc894a.png)

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Windows & PopOS
- **Version**: 1.x.y

**Comment by t3chguy** [comment] 2020-09-16 15:18
Duplicate of https://github.com/vector-im/element-web/issues/12410

Are you by chance low on disk space?

**Comment by Kryptor-Software** [comment] 2020-09-16 15:19
> Duplicate of #12410
> 
> Are you by chance low on disk space?

Nope, nowhere near low on disk space.

**Closed by t3chguy** 2020-09-16 15:18 UTC
Labels: bug

**Comment by hexaheximal** [comment] 2023-04-22 23:57
This issue should be reopened. I have had this issue too many times.

I am using element-desktop 1.11.29 on Debian bullseye. The disk is not full.
