### ISSUE TITLE
"Error decrypting image" in the timeline, but I can download and view the image fine

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#23703] opened 2022-11-04 15:50 UTC
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1342360/200018560-995bbcc6-13f5-476b-b868-7124cdf7f8d3.png)

I saw this in a timeline. Switching back and forth between rooms did not change anything. Clicking "download" on the image allowed me to view it correctly.

My assumption is that the keys for this message did not initially arrive, causing this error, but once they did arrive the error did not disappear?

#### What did you expect?

To not be able to download and decrypt the image, because it wasn't able to be displayed in the timeline.

#### What happened instead?

I couldn't decrypt/display the image in the timeline, but I could see the image when clicking "download". Why are these different?

### Operating system

Arch Linux

### Application version

Element version: 2022102901
Olm version: 3.2.12

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by anoadragon453** [comment] 2022-11-04 16:07
@uhoreg mentioned that this error is displayed for reasons other than the image being unable to decrypt. Such as the image being too large or a weird file format (though this was a 64KiB PNG...).

Also now looking back at the room, the image is displaying fine in the timeline. I've sent another rageshake in case something logged when it changed.

**Comment by t3chguy** [comment] 2022-11-04 16:19
Duplicate of https://github.com/vector-im/element-web/issues/3892

**Closed by t3chguy** 2022-11-04 16:19 UTC
Labels: T-Defect
