### ISSUE TITLE
Video Upload in E2E encrypted rooms fails with files larger than ~70 MB

### ISSUE THREAD

**Issue by chrissi55** [vector-im/element-web#6264] opened 2018-02-27 14:40 UTC
### Description

Problem: I will upload files larger than 60/70 MB (FHD mp4 Videos from Mobile Device)
Upload bar starts with 147 KB / 147 KB then stuck and says Upload not possible (no further info in riot for Android)

The Limit is set to 400 MB in my matrix-synapse -> homeserver.yaml

Giving a try in a non E2E encrypted room - and - no problem Upload is working. 

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: riot for Android
- **Version**: 0.8.1 

I did the same Tests with riot for Linux (under ubuntu 17.10) same thing (E2E Rooms - Limit of nearly 70 MB - Non E2E Rooms Limit of my homeserver.yaml is representative.

The Server is running under ubuntu-server 17.10 with matrix-synapse (from ubuntu Repo) 0.26.
with 6 GB of RAM. I'm using a PostgreSQL Database 9.6.7

**Comment by turt2live** [comment] 2018-02-27 15:46
The main part of this issue sounds like a bug for riot-android: https://github.com/vector-im/riot-android

You do have references to using the web browser though - what was the specific problem encountered with the web browser?

**Comment by chrissi55** [comment] 2018-02-27 16:11
Sorry the internal web browser is disabled in my homeserver.yaml
I'm using the matrix-synapse server-URL and portnumber in all Clients.

My Clients under Android, iOS, Windows 10 and ubuntu linux behave all the same.
So i guess it isn't only a Problem of the Android Version, but i'm not sure.

**Comment by kittykat** [comment] 2021-12-01 12:54
I am going to close this issue for now as we cannot reproduce the problem. Please file a new issue if you are still experiencing any difficulties.

**Closed by kittykat** 2021-12-01 12:54 UTC
Labels: T-Defect, P1, S-Major, A-E2EE, A-Media, X-Needs-Community-Testing
