### ISSUE TITLE
Face pile on space management screen doesn't open member list

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#26207] opened 2023-09-19 15:32 UTC
### Steps to reproduce

1. Manage a space
2. Click on the face pile

#### What did you expect?

The member list to open

#### What happened instead?

Nothing

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023091901 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-09-19 20:47
Duplicate of https://github.com/vector-im/element-web/issues/26164

**Closed by t3chguy** 2023-09-19 20:47 UTC
Labels: T-Defect
