### ISSUE TITLE
feature request: need possibility test audio or video calls before using it

### ISSUE THREAD

**Issue by sl5net** [vector-im/element-web#16508] opened 2021-02-22 11:02 UTC
very often problems
by using  audio or video calls when using linux ubunto or android.

this is very bad for the customer relationship if I have to test it 10 times with them and it still doesn't work. I would like to test it differently. then you can postpone the conversation for a few days without annoying the customer (i hope that the problem will be solved by then for kubuntu ... i don't know what it loves. jitsi and other apss work.

**Comment by sl5net** [comment] 2021-02-25 09:57
Sometimes my counterpart or his device is also the caus: Found out that when you answer a call, you click, your finger often slips a bit or something clicks for an unusually long time ... ☹️. Especially if you are already in the element, it only works every third time to accept a video or audio call. Something made Threema better there, it always works for her. Hmmm

**Comment by SimonBrandner** [comment] 2021-02-28 16:56
Duplicate of [#12647](https://github.com/vector-im/element-web/issues/12647)

**Closed by SimonBrandner** 2021-02-28 16:56 UTC
Labels: suggestion, type:voip
