### ISSUE TITLE
element not installable with the repo on debian 11 bullseye

### ISSUE THREAD

**Issue by damnms** [vector-im/element-web#16699] opened 2021-03-16 21:50 UTC
https://imgur.com/YQ1wTOM.png

### Description

apt-get install element-desktop does not work

### Steps to reproduce

- add the repo
- apt-get install element-desktop

i would expect that it works

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop? desktop

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? debian 11
- **Version**: 1.x.y  Version: 1.7.23

**Comment by SimonBrandner** [comment] 2021-03-17 09:12
Duplicate of [#16174](https://github.com/vector-im/element-web/issues/16174)

**Closed by SimonBrandner** 2021-03-17 09:12 UTC
Labels: T-Defect
