### ISSUE TITLE
Unable to join channels through search

### ISSUE THREAD

**Issue by 5hv5hvnk** [vector-im/element-web#23654] opened 2022-10-29 18:53 UTC
### Steps to reproduce

- After clicking on `join-channel` button after search, the operation of unsuccessful and got a pop up to report the bug.
- System information: MacOS Ventura 13.0, Quad-Core Intel Core i5

#### What did you expect?
Joining the channel, and channel chat opened on the screen.
#### What happened instead?
_Nothing_

### Application version

1.11.12 (1.11.12)

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-10-31 09:43
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-10-31 09:43 UTC
Labels: T-Defect
