### ISSUE TITLE
Message search can never be enabled in some situations

### ISSUE THREAD

**Issue by aneverhopefulhelper** [vector-im/element-web#19358] opened 2021-10-12 10:15 UTC
It seems somehow the passphrase in keytar can get out of sync with the actual database password. Element doesn't appear to be able to recover from this situation, leading to message search just not turning on. We should detect a passphrase mismatch and probably just delete the database and start re-indexing (probably warning the user, lest they end up in a cycle of it re-indexing without their knowledge every time the app is restarted). According to this report, the spinner keeps spinning too, even after it fails.

Original report below:

### Steps to reproduce

1. Trying to enable message search in Element desktop
2. Enable message search under Settings > Security & Privacy

#### What did you expect?
I expected message search to be enabled

#### What happened instead?
The loading/processing wheel spins for *hours* and does not enable message search

### Operating system

Linux Mint

### Application version

Element version: 1.9.2 Olm version: 3.2.3

### How did you install the app?

https://packages.riot.im/debian default/main amd64

### Homeserver

semi.social

### Will you send logs?

Yes

**Comment by aneverhopefulhelper** [comment] 2021-10-12 10:31
In the logs I am seeing EventIndex: Error initializing the event index {"message":"Error opening the database: DatabaseUnlockError(\"Invalid passphrase\")"} I suspect this is related, however, I am unsure how to fix this, if there is a file or something I can delete or modify or some setting I can change then I am willing to do so, but right now I don't know what to do.

**Comment by turt2live** [comment] 2023-01-10 00:06
Duplicate of https://github.com/vector-im/element-web/issues/19001 I believe

**Closed by turt2live** 2023-01-10 00:06 UTC
Labels: T-Defect, S-Major, A-Indexing, O-Uncommon
