### ISSUE TITLE
Search messages in a room by user

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#25871] opened 2023-07-28 22:59 UTC
#### What would you like to do?
Search messages in a room by user
#### Why would you like to do it?
Sometimes it wasn't to see what 1 specific person wrote in a chat, perhaps also for moderation reasons but also just as a user
#### How would you like to achieve it?
Have a filter in the search.

### Have you considered any alternatives?

Make it so that when you search a username all there messages show.

**Comment by t3chguy** [comment] 2023-07-31 08:16
Duplicate of https://github.com/vector-im/element-meta/issues/1477

**Closed by t3chguy** 2023-07-31 08:16 UTC
Labels: T-Enhancement
