### ISSUE TITLE
Key transfer of old messages to someone in a 1 to 1 room

### ISSUE THREAD

**Issue by michaelharmonart** [vector-im/element-web#18304] opened 2021-07-30 19:25 UTC
#### Is your suggestion related to a problem? Please describe.
At this point I've had at least one friend lose access to all their logged in matrix sessions, therefore losing messages they received before that point. Of course they can continue messaging me from a new session, but It would be great if there was a way to restore the messages they no longer have access to. I know it is possible since I can view all those messages, they keys are accessible somewhere by the client.

#### Describe the solution you'd like.
Allow an easy way to send keys to a new session that hasn't been cross signed by a previous one, such as when someone loses access to all their active matrix sessions.

**Comment by robintown** [comment] 2021-07-30 21:36
I *think* a workaround for this might be to have your friend leave the room, and then invite them back in. Once they accept the invite, Element's key-sharing mechanism for historical messages should hopefully kick in.

**Comment by michaelharmonart** [comment] 2021-07-30 22:20
I did have them try that, but I don't believe it worked. i'll need to go check with them to be certain though.

**Comment by aaronraimist** [comment] 2021-07-31 05:28
Check that you see the message "Invited people will be able to read old messages" on the Invite dialog box, if you don't you are probably on an old version of Element. The current version is 1.7.33.

<img width="763" src="https://user-images.githubusercontent.com/5855073/127729770-95661fdc-845e-43dc-9e2c-af23cc56e361.png">

This issue is a duplicate of https://github.com/vector-im/element-web/issues/2286 though so you can thumbs up that one.

**Closed by aaronraimist** 2021-07-31 05:28 UTC
Labels: T-Enhancement
