### ISSUE TITLE
Autocomplete is frustratingly unreliable

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6464] opened 2018-04-06 15:22 UTC
### Description

There's a certain level of expectation that when I type `Please join #riot-and<tab><enter>` that I'll end up with `Please join [#riot-android:matrix.org]` as a message. However, if the browser stalls even for a moment (usually while calculating my autocomplete suggestions), I often end up with `Please join [#riot-ios:matrix.org]and` as a message. Having the wrong message be sent is incredibly frustrating and reduces my confidence that what I type is what is going to be sent.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment] 2018-04-11 15:32
i wonder if this is related to https://github.com/vector-im/riot-web/issues/4708

**Comment by wsmwk** [comment] 2021-09-05 14:41
@turt2live can you still reproduce this issue?

FWIW,  #4708 has since been closed

**Comment by novocaine** [comment] 2021-10-04 15:15
Closing as no answer from OP

**Closed by novocaine** 2021-10-04 15:15 UTC
Labels: T-Defect, X-Needs-Info, A-Performance, S-Major, A-Autocomplete, O-Occasional
