### ISSUE TITLE
VoIP buttons fade out while you're hovering over them.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16928] opened 2021-04-12 17:17 UTC
If you're on a 1:1 VoIP call, the buttons fade out even if the mouse is hovering over them after a small period of inactivity.  Rather than buttons disappearing from under the mouse when you might be trying to click on them, we should keep them visible while mouseovered.

**Comment by SimonBrandner** [comment] 2021-04-12 17:23
Duplicate of your own issue: [#16751](https://github.com/vector-im/element-web/issues/16751)

**Closed by SimonBrandner** 2021-04-12 17:23 UTC
Labels: T-Defect
