### ISSUE TITLE
Do not require a new Windows Firewall rule for every update of Element

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#15973] opened 2020-12-15 11:15 UTC
From a user:

> Hello
> 
> we have just started to use Element for our communication between colleagues.
> 
> We've found that after each update to a new version of Element, there is a new rule in Windows Firewall because each new version of Element has its own new path (%localappdata%\element-desktop\app-*\Element.exe).
> 
> Because normal users do not have administrative privileges, they cannot allow the new firewall rule for the new version of Element.
> 
> We have already tried to change the link to Element to avoid using the version directory. Instead, we use the directory above it (%localappdata%\element-desktop\Element.exe). But that doesn't work either. A new firewall rule with the specific path to the version is still requested.
> 
> By the way: This also leads to many old rules in the firewall for older versions of Element that no longer exist.
> 
> Can you help us to solve this problem?
> 
> Yours sincerely

**Comment by jryans** [comment] 2020-12-17 12:21
Unfortunately, I don't think we can do much about this without changing the Electron updater process, which is itself a minefield. Still, it's good to be aware of the feedback.

**Comment by ThiefMaster** [comment] 2021-08-04 09:23
Maybe that's the way to go then? The current behavior is a huge user-unfriendly mess. As a techie I just find it annoying. But think of less-technical users.

I believe whatever is causing this bad behavior is also the root cause for the notification area / systray icon losing its original position after every update.

**Comment by eetsceeck1** [comment] 2021-09-10 14:16
i have found solution for this, element act as portable without any dependencies on the system which is great, i was hoping from the first place it will be the case, 
now i just did create a folder somewhere desired on the system with it, and i did blocked the updates ip's, no need them so often, 
after a while i will check if there is any new version by myself, 

in that case i think you don't need to use "Squirrel", you can provide it as portable compressed file or something, it will have the same effect as it is with the installer just better, 

anyway i hope it will provide an idea or concept to fix this.
thanks

**Comment by ThiefMaster** [comment] 2021-09-10 14:17
> now i just did create a folder somewhere desired on the system with it, and i did blocked the updates ip's, no need them so often,
after a while i will check if there is any new version by myself,

That is terrible advice. Not updating software is how you end up with insecure versions and potentially getting infected with malware.

**Comment by eetsceeck1** [comment] 2021-09-10 14:29
i am not recommending not to update i was talking about myself that i will check for update by "myself" other people can of course check their updates whenever they like, 
but the concept of instead to use Squirrel installer with a version number which is what is make this issue from the first place, that ourfirewalls, HIPS, and many security modules / softwares are all been set with the file location already will be need to be re-configure again, i did open an another thread for this in not knowing this tread is exist but it been closed with referal to this one so i am answering here to https://github.com/t3chguy, on here: https://github.com/vector-im/element-web/issues/18946#issuecomment-915277020

also, i amnot worried about "malware" and all these crap, my system is heavily protected, 4 firewalls, OSarmor, CIS, Spyshelter, and more 5 security modules i did develop myself, + anti loggers in sort of kinds, 
my problem though, is the certificates of encryption which i have no control of, in most cases the certificates goes to newer version in a new app version, 

also i am running my own synapse server, and element is in encrypted container, 

t3chguy mentioned that the developers cannot change the path name from "version" name to un-version name as every normal software should be, that's what he wrote before he closed my "issue" :
" ===== This is simply how the default Squirrel Windows installer for Electron functions ===== "


the other solution i can think of as a developer myself is wget, curl, or any other remote fetcher to replace the files in a regular folder,

**Comment by rtanglao** [comment] 2022-01-28 05:45
* This is a duplicate of #14788, I believe

**Comment by t3chguy** [comment] 2022-01-28 09:50
Duplicate of https://github.com/vector-im/element-web/issues/14788

**Closed by t3chguy** 2022-01-28 09:50 UTC
Labels: Z-Platform-Specific, A-Electron, T-Enhancement
