### ISSUE TITLE
Horizontal scrollbars on <pre/> blocks are mangled

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4256] opened 2017-06-08 23:23 UTC
at least on compact theme:

<img width="858" alt="screen shot 2017-06-09 at 00 21 40" src="https://user-images.githubusercontent.com/1294269/26954742-bab6f78a-4ca9-11e7-8ad9-6c4e83cc8d19.png">

**Comment by turt2live** [comment] 2017-06-08 23:33
I wouldn't doubt if it's similar to the issue reported on the dark theme ticket: https://github.com/vector-im/riot-web/issues/2988

**Comment by turt2live** [comment] 2017-06-19 14:31
Related: The border on code blocks gets mangled with long strings.
![image](https://user-images.githubusercontent.com/1190097/27290167-a5cd3a00-54c9-11e7-890e-3fc661dd85cb.png)

(related because the fix for the several issues appears to be something to do with the actual text formatting, not the container. or the container is not at a high enough index?)

**Comment by aaronraimist** [comment] 2021-03-12 05:41
I cannot reproduce

**Comment by SimonBrandner** [comment] 2021-03-12 06:33
> I cannot reproduce

Yep, this doesn't seem to be a problem anymore. Let's close this. If there still are some problems let's create a new issue

**Closed by SimonBrandner** 2021-03-12 06:33 UTC
Labels: P2, S-Minor, T-Defect
