### ISSUE TITLE
Build Docker containers for ARM

### ISSUE THREAD

**Issue by mattcen** [vector-im/element-web#15621] opened 2020-10-31 00:26 UTC
**Is your suggestion related to a problem? Please describe.**

I run Element Web via Docker on a Raspberry Pi, so every new release, I must self-compile the Docker image, which take well over an hour.

**Describe the solution you'd like**

Updating the Element Web CI/CD pipeline to build ARM Docker images in addition to amd64 images would solve this problem

**Describe alternatives you've considered**

I've set up my own pipeline to build these images at https://github.com/mattcen/riot-web/commit/37291c8b6688ca1efbce44472e4fe4dcf1125d56, but that currently involves significant hand-holding to merge, re-tag, etc.

**Additional context**

I suggested this as PR #15601, but then found that Element uses Buildkite for its CI/CD, so adding GitHub CI/CD too would be untidy.

The problems I've hit in the past when trying to automate this reliably included failures during the webpack step of the process due to npm running out of memory (or something; I never quite understood it), so that might be an issue, but the process in my PR above seems to work *relatively* reliably.

**Comment by aaronraimist** [comment] 2020-10-31 04:40
Duplicate of #15227

**Closed by aaronraimist** 2020-10-31 04:40 UTC
Labels: suggestion

**Comment by mattcen** [comment] 2020-10-31 04:46
Oops; sorry for the dupe! This is sillier for the fact that I'd *commented* on the original! My bad.
