### ISSUE TITLE
Creating my first space and Home disappeared

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21960] opened 2022-04-27 17:34 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
I clicked to create my first space
2. What do you click?
"+" on the left of the screen

<img width="622" alt="Screenshot 2022-04-27 at 10 33 46" src="https://user-images.githubusercontent.com/89144281/165585895-6a352200-355e-487c-88fe-1d5daa4c7d92.png">

#### What did you expect?
Home to stay where it was
#### What happened instead?
Home icon disappeared

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-04-27 18:10
Duplicate of https://github.com/vector-im/element-web/issues/21006

**Closed by t3chguy** 2022-04-27 18:10 UTC
Labels: T-Defect, S-Tolerable, O-Occasional
