### ISSUE TITLE
Guests are required to register to send message to guest-writable room

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#16037] opened 2020-12-26 20:48 UTC
If guests are allowed to send messages to a room, but they are not members of the room, just peeking, Element requires them to register in order to send messages.

This works without registration:
1. search for the room in the directory
2. click Join
3. the guest user is joined and is able to talk

This doesn't:
1. have a link to the room, e.g. https://app.element.io/#/room/#tarsalgo:grin.hu
2. the user opens it
3. they see the room, but at the bottom of the screen, in place of the composer, there is "Register to send message"
**If the room is guest-writable, then having a Join button would be much better.**

**Comment by t3chguy** [comment] 2020-12-26 20:52
The bug here is the first path working, Element intentionally forces registration and intentionally only allows guests for peeking.

**Comment by notramo** [comment] 2020-12-27 14:22
When redirecting people from the registration-less IRC room to Matrix, using this feature, we replaced IRC with Matrix in some communities.
Please make it configurable on a per-room basis.

**Comment by t3chguy** [comment] 2020-12-27 14:30
Element will be bringing back ILAG probably in 2021 which replaces guest access so that is unlikely to happen.

**Comment by notramo** [comment] 2020-12-27 14:36
Will it be the same UX for IRC users coming to Matrix who don't want to register?

**Comment by t3chguy** [comment] 2020-12-27 14:43
In ILAG they pretty much just pick a username and the account is registered in the background. Guest accounts are too limited and have no transition path to real accounts so Element refuses to use them for write access at this time.

**Comment by notramo** [comment] 2020-12-27 14:47
But for IRC users, transitioning to real account is not a requirement, because **they don't want** a real account.

**Comment by t3chguy** [comment] 2020-12-27 14:52
Then they are welcome to use a different client, Matrix is a different beast and is very different to IRC. ILAG promotes easier onboarding for most users, yes that excludes those that was anonymous throwaways each time they open the thing

**Comment by jryans** [comment] 2021-01-19 16:14
As mentioned above, this is currently the expected behaviour, so I think it's best to close this issue. We can track improving the experience via the various ILAG issues that already exist.

I have created https://github.com/vector-im/element-web/issues/16213 to close the room directory path, since that's just an oversight.

**Closed by jryans** 2021-01-19 16:14 UTC
Labels: bug, defect, p2, severity:major, type:guestaccess
