### ISSUE TITLE
Receiving notification without notification server installed hangs UI thread

### ISSUE THREAD

**Issue by emma-miler** [vector-im/element-web#23362] opened 2022-09-27 20:20 UTC
#### Reproduction
1. Disable/uninstall active notification server
2. Receive a message while application is not focused

#### What did you expect?

Notifications events should not cause UI to hang

#### What happened instead?

Receiving a notification while no notification server is running to respond to the dbus event causes the application to hang until the event times out. 

### Operating system

Arch Linux

### Application version

Element version: 1.11.4 Olm version: 3.2.12

### How did you install the app?

element-desktop package in arch repos

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-09-27 20:50
Duplicate of https://github.com/vector-im/element-web/issues/5315

**Closed by t3chguy** 2022-09-27 20:50 UTC
Labels: T-Defect
