### ISSUE TITLE
Vsync failures, randomly leading to a total whiteout of the viewport

### ISSUE THREAD

**Issue by erkinalp** [vector-im/element-web#23767] opened 2022-11-14 19:06 UTC
### Steps to reproduce

Sadly, no particular steps to reproduce. Happens totally randomly.

#### What did you expect?
Not failing vsync.
#### What happened instead?
`[74493:1114/220306.539127:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!`
This whiteout is not a flashing. It stays white until I close the window

### Operating system

Ubuntu 22.04 + GNOME 42 + amdgpu driver

### Application version

1.11.14

### How did you install the app?

dpkg/apt

### Homeserver

this is a purely client-side bug

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-11-15 10:07
Duplicate of https://github.com/vector-im/element-web/issues/21336

**Closed by t3chguy** 2022-11-15 10:07 UTC
Labels: T-Defect
