### ISSUE TITLE
User status doesn't have “…” at the end of it if it's too long

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#20128] opened 2021-12-10 01:22 UTC
### Steps to reproduce

1. Set a long status
2. Room Info > People > see your long status there

#### What did you expect?
If the user status is long, it should have those three dots at the end of it

#### What happened instead?
![user-status](https://user-images.githubusercontent.com/47475676/145501249-7f408bc0-3e6f-4dc4-983f-a06a327bbd77.png)

### Operating system

Arch Linux

### Application version

Versi Element Nightly: 2021120801 Versi Olm: 3.2.3

### How did you install the app?

AUR

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2021-12-10 05:30
Duplicate of your own issue https://github.com/vector-im/element-web/issues/20092 :P

**Closed by SimonBrandner** 2021-12-10 05:30 UTC
Labels: T-Defect
