### ISSUE TITLE
Navigating between rooms containing E2EE images breaks Firefox spectacularly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#11267] opened 2019-10-30 19:01 UTC
If you create an E2E room in a big account with a few large (~3-4MB) images in it and start navigating back and forth, Firefox particularly grinds to a spectacular halt with ~20s garbage collections (on my top-end MBP).

<img width="1737" alt="Screenshot 2019-10-30 at 19 00 26" src="https://user-images.githubusercontent.com/1294269/67889878-8e4a6200-fb47-11e9-853f-07c764ca7225.png">

It feels like we might be going and undecrypting the original file (even if we don't view it) rather than just the smaller thumbnails?

**Comment by ara4n** [comment] 2019-10-30 19:18
given that clicking on a thumbnail instantly displays the fullres image without downloading anything, it definitely feels like we are incorrectly loading the fullres encrypted images somewhere rather thabn just the thumbnails.

**Comment by ara4n** [comment] 2019-11-01 18:56
This is currently making my riot/web literally unusable due to the 20s GCs on firefox (after I stupidly sent a 11MB encrypted image into a room).

The problem is that MImageBody decrypts both the thumbnail and the actual target on mount, and apparently always has done.  Instead, need to delegate decrypting the target until something actually tries to get at the content URL.

**Comment by ara4n** [comment] 2019-11-01 19:25
...which is relatively tricky, as we currently need the content URL to render the download link of the image, unless we lazyload that in, which would feel quite flakey. probably better to avoid providing a download link from the thumbnail entirely, and instead only from the lightbox.

**Comment by kittykat** [comment] 2021-12-01 12:58
I'm going to close this issue for now as we cannot reproduce it. Please reopen if you are still experiencing it.

**Closed by kittykat** 2021-12-01 12:58 UTC
Labels: T-Defect, A-E2EE, X-Needs-Community-Testing
