### ISSUE TITLE
Room initial is not updated when a room is created

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#24986] opened 2023-03-30 05:21 UTC
### Steps to reproduce

1. Create a new room with a random name
2. Check the room avatar

Otherwise:
- Run `create-room.spec.ts` tests on Cypress

#### What did you expect?

The avatar's initial should be that of the room name you specified.

#### What happened instead?

The room avatar stayed `E` of "Empty room" until you reopen the room after you visit another room.

https://user-images.githubusercontent.com/3362943/228736971-79be7349-54d1-4d58-abde-4f9e84df8082.mp4

### Operating system

Debian

### Browser information

Firefox

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by luixxiul** [comment] 2023-03-30 05:24
Please note that this might be intermittent, and causes [this change](https://percy.io/dfde73bd/matrix-react-sdk/builds/26262885/changed/1462494763?browser=edge&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1024&widths=1024%2C1920) on a Percy snapshot for https://github.com/matrix-org/matrix-react-sdk/pull/10467.

**Comment by t3chguy** [comment] 2023-04-03 08:52
Duplicate of https://github.com/vector-im/element-web/issues/22590

**Closed by t3chguy** 2023-04-03 08:52 UTC
Labels: T-Defect, S-Tolerable, A-Create-Room, O-Occasional
