### ISSUE TITLE
Collapsed timeline items are misaligned

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#18098] opened 2021-07-20 13:42 UTC
![image](https://user-images.githubusercontent.com/1342360/126321704-39281a77-0961-44ed-bafc-41a7a825261d.png)

Collapsed timeline items don't horizontally align with their one-off state event counterparts.

Occurs in both compact and normal view modes.

Platform: Web and Desktop
OS: Arch Linux
Version: 77edbc27f82c-react-340d09d45762-js-b936b4a2ce9c

**Comment by robintown** [comment] 2021-07-20 13:54
Duplicate of https://github.com/vector-im/element-web/issues/18079

**Closed by robintown** 2021-07-20 13:54 UTC
Labels: T-Defect
