### ISSUE TITLE
Timeline is showing ancient displaynames for some users in some rooms for newly arrived messages

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20988] opened 2022-02-08 19:07 UTC
### Steps to reproduce

In one instance, I was in a DM with agk from FOSDEM around midday today - I sent a message and it appeared from `Matthew (away)`, despite me not using that nick forever.

In another instance, Ben BZ suddenly started sending messages in a private room from `Ben BZ (back Jan 4)` (I had upgraded to a newer nightly since the previous incident, fwiw. On re-looking at the agk room, the displayname was now correct).

It's not a state reset though, as there are no events between the messages showing the displayname changing - it looks like a sentinel or historical displayname bug.

#### What did you expect?

Displaynames to be right.

#### What happened instead?

Zombie displaynames from months gone by started appearing on newly sent msgs, both from myself & others.

### Operating system

macOS

### Application version

Nightly

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by lampholder** [comment] 2022-02-08 22:29
Looks like the same thing I've been seeing https://github.com/vector-im/element-web/issues/20981

Mine has been inconsistent between devices - I think I've only actually noticed problems on Element Desktop.

**Comment by robintown** [comment] 2022-02-08 22:42
Duplicate of https://github.com/vector-im/element-web/issues/20981

**Closed by robintown** 2022-02-08 22:42 UTC
Labels: T-Defect
