### ISSUE TITLE
Double call ends call view after timeout while call is still active in the background

### ISSUE THREAD

**Issue by LGro** [vector-im/element-web#15107] opened 2020-09-06 08:44 UTC
### Description

When accidentally double clicking the video call button, the call view with video and audio disappears after a timeout even though the call is still active and the other side can still see & hear me.

### Steps to reproduce

- From element-desktop click the video call icon (in a 1:1 encrypted chat where the other person has element-ios, not sure if this is specific to that setup) twice within 1-2 seconds
- Accept the call on the other side
- Wait until the timeout for not accepting the second call that was triggered in the background passes
- Observe notification that the call timeout (the other side not picking up the second call in the background) was exceeded and see the previously active call view disappear on the element-desktop side
- The other side, element-ios in this case, can still see and hear the element-desktop contact in the active call, even though the latter doesn't have any clue that the call is still ongoing

I'd expect that only one call is triggered, even though I clicked the video call icon twice.

Log: not sent but exported, can be provided on demand

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu 20.04.1 LTS
- **Version**: 1.7.5

**Comment by turt2live** [comment] 2020-09-06 08:53
Duplicate of https://github.com/vector-im/element-web/issues/12569

**Closed by turt2live** 2020-09-06 08:53 UTC
