### ISSUE TITLE
Error when starting a chat with delayed room creation

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#24179] opened 2023-01-06 11:49 UTC
### Steps to reproduce

1. Start a chat with someone new
2. type message
3. press enter

#### What did you expect?
Message sent

#### What happened instead?
'Some of your messages could not be sent'

Looks like element is trying to fetch a particular event in a room and synapse is retuning a 404 because it can't find it - perhaps a race with something reqiesting an event before it's been persisted?

### Will you send logs?

Yes

**Comment by turt2live** [comment] 2023-01-09 18:12
Looks like the errors are coming from a `/members` call - this may be a change in synapse?

**Comment by andybalaam** [comment] 2023-01-11 10:00
The URL which is returning a 404 is:

```https://matrix-client.matrix.org/_matrix/client/r0/rooms/!lFfrlZXUrMAOXpzuxp%3Amatrix.org/members?not_membership=leave&at=m3595246325%7E2.3595246467%7E3.3595246468%7E36.3595246466_757284974_52668403_1826042582_1854740460_3893944_721765062_6284542923_0```

**Comment by andybalaam** [comment] 2023-01-11 10:02
The error from Synapse is generated here: https://github.com/matrix-org/synapse/blob/develop/synapse/handlers/message.py#L206

**Comment by andybalaam** [comment] 2023-01-11 10:09
I don't see anything so far in matrix-js-sdk that guarantees that the sync token we supply comes from after the room was created. Still digging.

**Comment by andybalaam** [comment] 2023-01-11 10:20
The stack trace for where we call this API in Element Web looks like:

```
members (webpack:///matrix-js-sdk/src/client.ts?e845#7811)
loadMembersFromServer (webpack:///matrix-js-sdk/src/models/room.ts?1ede#872)
loadMembers (webpack:///matrix-js-sdk/src/models/room.ts?1ede#887)
loadMembersIfNeeded (webpack:///matrix-js-sdk/src/models/room.ts?1ede#926)
loadMembersIfJoined (webpack:///matrix-react-sdk/src/components/structures/RoomView.tsx?908e#1269)
onRoomLoaded (webpack:///matrix-react-sdk/src/components/structures/RoomView.tsx?908e#1226)
onRoomViewStoreUpdate (webpack:///matrix-react-sdk/src/components/structures/RoomView.tsx?908e#668)
componentDidMount (webpack:///matrix-react-sdk/src/components/structures/RoomView.tsx?908e#842)
commitLifeCycles (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#20663)
commitLayoutEffects (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#23426)
callCallback (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#3945)
invokeGuardedCallbackDev (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#3994)
invokeGuardedCallback (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#4056)
commitRootImpl (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#23151)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.development.js?3069#468)
runWithPriority$1 (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#11276)
commitRoot (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#22990)
performSyncWorkOnRoot (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#22329)
flushSyncCallbackQueueImpl (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#11327)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.development.js?3069#468)
runWithPriority$1 (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#11276)
flushSyncCallbackQueueImpl (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#11322)
flushSyncCallbackQueue (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#11309)
scheduleUpdateOnFiber (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#21893)
enqueueSetState (webpack:///node_modules/react-dom/cjs/react-dom.development.js?61bb#12467)
setState (webpack:///node_modules/react/cjs/react.development.js?72d0#365)
setState (webpack:///matrix-react-sdk/src/components/structures/MatrixChat.tsx?ab0b#413)
viewRoom (webpack:///matrix-react-sdk/src/components/structures/MatrixChat.tsx?ab0b#978)
onAction (webpack:///matrix-react-sdk/src/components/structures/MatrixChat.tsx?ab0b#695)
_invokeCallback (webpack:///matrix-react-sdk/node_modules/flux/lib/Dispatcher.js?1f1c#214)
dispatch (webpack:///matrix-react-sdk/node_modules/flux/lib/Dispatcher.js?1f1c#189)
```

**Comment by andybalaam** [comment] 2023-01-11 10:23
Examining that stack trace, in `viewRoom` we have:

```
if (!this.firstSyncComplete) {
...
    await this.firstSyncPromise.promise;
}
```

So this convinces me that we did wait for a sync before asking for the members.

We get the sync token inside `loadMemberFromServer` with:

```
        const lastSyncToken = this.client.store.getSyncToken();
```

So I am convinced that we are using a correct sync token, so this is a Synapse problem. I will log a bug there.

**Comment by andybalaam** [comment] 2023-01-11 10:32
Reported as https://github.com/matrix-org/synapse/issues/14814 . I am fairly sure this is not an Element Web problem, so closing but please re-open if we get evidence to the contrary.

**Comment by t3chguy** [comment] 2023-01-11 10:35
@andybalaam `firstSyncPromise` is whether the first ever sync (after loading sync accumulator) is complete, not whether a sync containing all rooms you have requested to join has completed.

> Element Web creates the room, waits for a sync, then calls the members API with the latest sync token:


This does not appear to be true based on the above.

**Comment by andybalaam** [comment] 2023-01-11 10:50
Thank you @t3chguy . I will continue investigating, but @richvdh also concluded from the Synapse side that the token looks correct, so the balance of probability is still pointing in that direction.

**Comment by richvdh** [comment] 2023-01-11 10:54
It may that there are problems on both sides, either of which can cause this problem!

I would say:
 * Element should not call `/members` on a given room until that room has appeared down `/sync` (which may be some time after the `/createRoom` call completes, of course
 * Provided it does so, Synapse should not 404.

In the example I am looking at, it certainly seems that the problem is on Synapse's side.

**Comment by andybalaam** [comment] 2023-01-11 11:36
In [createRoom.ts](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/createRoom.ts#L347) we read:

```
                // NB we haven't necessarily blocked on the room promise, so we race
                // here with the client knowing that the room exists, causing things
                // like https://github.com/vector-im/vector-web/issues/1813
                // Even if we were to block on the echo, servers tend to split the room
                // state over multiple syncs so we can't atomically know when we have the
                // entire thing.
```

Which implies such races may exist BUT the assumption in the code above is that if `client.getRoom(roomId)` returns something, then the room has come down the sync.

We do call `getRoom` in [RoomView.tsx](https://github.com/matrix-org/matrix-react-sdk/blob/df03112a3ba76e58ca2cf710aee233fef69c9492/src/components/structures/RoomView.tsx#L665) before calling `onRoomLoaded`, which leads to the `members` call, so I am convince (again) that Element Web is doing the right thing here.

**Closed by andybalaam** 2023-01-11 11:36 UTC
Labels: T-Defect, X-Regression, X-Release-Blocker, X-Needs-Investigation, A-DM-Start
