### ISSUE TITLE
Messages appear out of order

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#21636] opened 2022-04-01 10:34 UTC
### Steps to reproduce

1. Saw a notification in a room
2. Clicked it, and found no notification
3. Scrolled way up to find it, and noticed that the notification was sent today, but it was placed in the timeline between messages that were a month old

![image](https://user-images.githubusercontent.com/1342360/161247070-3e735267-61c8-4587-8739-7362522cd81d.png)
![image](https://user-images.githubusercontent.com/1342360/161246856-949e6785-a83e-411b-8cf2-3a5069cd0a8d.png)

Clicking back and forth between rooms does not fix the timeline. I am also able to backfill the room properly by scrolling up.

#### What did you expect?

The most recent messages to be at the bottom of the timeline.

#### What happened instead?

They were lodged between a string of messages sent a month ago.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022033101, Olm version: 3.2.8

### Homeserver

amorgan.xyz

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-04-01 10:42
Duplicate of https://github.com/vector-im/element-web/issues/1456

**Closed by t3chguy** 2022-04-01 10:42 UTC
Labels: T-Defect
