### ISSUE TITLE
Screenshare settings

### ISSUE THREAD

**Issue by Doomsdayrs** [vector-im/element-web#21558] opened 2022-03-25 03:50 UTC
##### Change the quality of the screenshare.
IE:
140p
240p
360p
480p
720p
1080p
...
4k
Automatic

##### Change the FPS of the screenshare
15fps
24fps
30fps
60fps
...
Source
Automatic

#### Why would you like to do it?

By doing so, I can ensure my stream maintains lag free. 

#### How would you like to achieve it?

When screen sharing, provide a button to change the screen share quality.

### Additional context

Sometimes my friends say "the video is lagging" and we have to swap to Discord because I can change the stream quality there

**Comment by SimonBrandner** [comment] 2022-03-25 05:26
Related: https://github.com/vector-im/element-web/issues/19008, https://github.com/vector-im/element-web/issues/16657

**Comment by gsouquet** [comment] 2022-03-25 09:34
Closing as duplicate of https://github.com/vector-im/element-web/issues/19008

**Closed by gsouquet** 2022-03-25 09:34 UTC
Labels: A-VoIP, T-Enhancement, O-Occasional
