### ISSUE TITLE
deactivate small screen overlay of caller ?

### ISSUE THREAD

**Issue by ihubgit** [vector-im/element-web#16083] opened 2021-01-06 10:32 UTC
Hi, when doing a one2one video call in element, the majority of the screen is filled with the recipient obviously, but there's this floating small overlay screen showing the caller. Now in other apps one can either hide or minimize this, as it does hide the recipient from time to time. Is there a way to do this? Haven't found it in the settings.

**Comment by SimonBrandner** [comment] 2021-01-06 10:56
@ihubgit There's currently no way to do this. VoIP is currently being worked on so we can hope the UI will get some polishing. 

I also think that there should be some way to customize the position of the caller's video (drag and drop or something along those lines).

**Comment by SimonBrandner** [comment] 2021-01-06 13:24
Related to #16084

**Comment by jdohm** [comment] 2021-03-02 22:04
I use the Call feature a lot, one problem with the fixed position is also: it hides a part of the last message in other rooms. 
It also hides the React/Reply/Options buttons. 

(I'm using the Element desktop client on Ubuntu)

![image](https://user-images.githubusercontent.com/9203094/109721167-49a36080-7bab-11eb-8070-d22561fcc805.png)

**Comment by SimonBrandner** [comment] 2021-05-02 14:02
Duplicate of [#15839](https://github.com/vector-im/element-web/issues/15839)

**Closed by SimonBrandner** 2021-05-02 14:02 UTC
Labels: A-VoIP, T-Enhancement
