### ISSUE TITLE
Date separator multiplying at random

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20955] opened 2022-02-07 09:17 UTC
### Steps to reproduce

 * I sent some messages (which sent), and closed my laptop, perhaps before local echo was received.
 * I then opened it the next day, and the room claims the msgs hadn't sent, and there were data separators appearing in realtime, slowing expanding up the timeline.
 * I restarted and upgraded to the latest nightly
 * It still did it
 * I hit "send" on the unsent messages
 * They sent, and it stopped sprouting new date separators... but the multiple ones were still there.

<img width="1118" alt="Screenshot 2022-02-07 at 09 02 17" src="https://user-images.githubusercontent.com/1294269/152759536-232c14d3-dcfe-4148-9526-2dfa8910e48d.png">

and after restart:

<img width="1322" alt="Screenshot 2022-02-07 at 09 14 10" src="https://user-images.githubusercontent.com/1294269/152759552-60ecf693-f352-4c7d-b5d2-89bc4613f938.png">

#### What did you expect?

No crazy exploding date separators

#### What happened instead?

Exploding date separators

### Operating system

macOS

### Application version

Nightly

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ara4n** [comment] 2022-02-07 09:19
i assume i'll need to flush cache or something to fix it :(

**Comment by gsouquet** [comment] 2022-02-07 09:27
Duplicate of https://github.com/vector-im/element-web/issues/13232

**Closed by gsouquet** 2022-02-07 09:27 UTC
Labels: T-Defect
