### ISSUE TITLE
File panel has unhelpful and badly aligned error message

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20253] opened 2021-12-17 17:34 UTC
### Steps to reproduce

1. In an encrypted room, open file panel

#### What did you expect?
To see files

#### What happened instead?
Error message. I'm not sure what I'm supposed to be checking in settings.

![Screenshot from 2021-12-17 17-32-05](https://user-images.githubusercontent.com/51663/146584836-0f31eab7-6612-43d4-bd37-6decb92864f6.png)

### Operating system

Arch Linux

### Application version

Element version: 1.9.7 Olm version: 3.2.8

### How did you install the app?

Flatpak

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2021-12-18 08:39
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19245 and https://github.com/vector-im/element-web/issues/18164

**Closed by SimonBrandner** 2021-12-18 08:39 UTC
Labels: T-Defect, A-File-Panel
