### ISSUE TITLE
clicking on section titles in the room list doesn't jump to it anymore and it makes it super painful to navigate

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#22144] opened 2022-05-11 10:11 UTC
I now have to scroll endlessly or try to grab the scroller and move it around which is not very efficient.

**Comment by t3chguy** [comment] 2022-05-11 10:11
Duplicate of your own https://github.com/vector-im/element-web/issues/21420

**Closed by t3chguy** 2022-05-11 10:11 UTC
