### ISSUE TITLE
`Something went wrong!` on joining another another room on a space

### ISSUE THREAD

**Issue by Benjamin-Loison** [vector-im/element-web#23392] opened 2022-10-02 21:49 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

I joined the OpenStreetMap space by clicking on https://matrix.to/#/#osm-space:matrix.org, that way I joined the `osm-fr` room then I explored the list of rooms of this space to join `OSM General`.

2. What do you click?

However when clicking on the `Join` button next to the `OSM General` room I got a `Something went wrong!` while actually joining `OSM General` room...

3. More steps…

Here is a video I recorded showing this issue:

https://user-images.githubusercontent.com/12752145/193477794-22fed614-4b93-48f3-8944-0db3546acb9e.mp4

#### What did you expect?
Graphically join the wanted room on a space (or at least have a confirmation).
#### What happened instead?
Got a `Something went wrong` (but the room in the space is correctly joined).

### Operating system

Ubuntu 22.04.1 LTS

### Application version

Element version: 1.11.8 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started#linux-details (instructions followed after Mon Apr 25 13:58:07 2022)

### Homeserver

matrix.org

### Will you send logs?

Yes
(When clicking `Submit debug logs` and providing this GitHub issue URL I got `Logs sent` `Thank you!`)

**Comment by SimonBrandner** [comment] 2022-10-03 07:38
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by SimonBrandner** 2022-10-03 07:38 UTC
Labels: T-Defect
