### ISSUE TITLE
Room image was fetched, but isn't displayed

### ISSUE THREAD

**Issue by Winterhuman** [vector-im/element-web#23383] opened 2022-09-30 13:28 UTC
### Steps to reproduce

1. Go to https://matrix.to/#/#UVR:cyberia.club
2. See the default room image, a blue "U" icon.
3. Click **Room Info** in the top-right, and click the blue "U" icon inside of the opened panel.
4. See that the room's image is actually present in Element's cache, but it's not being used everywhere for some reason. (going to **Room settings** also doesn't work and shows a generic image file icon with the text "Room avatar" next to it)

#### What did you expect?

The room image to be displayed since the image is present in Element's cache.

#### What happened instead?

Element isn't using the room image despite it being present in it's cache.

### Operating system

Arch Linux

### Application version

Element version: 1.11.8, Olm version: 3.2.12

### How did you install the app?

FlatHub

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-09-30 13:30
This is because the avatar is `image/webp` which Synapse (matrix.org) server does not support thumbnailing - https://matrix.org/_matrix/media/r0/thumbnail/cyberia.club/MGJxUrLBYsTZiwaRfczIhqen?height=64&method=crop&width=64 fails

**Comment by t3chguy** [comment] 2022-09-30 13:30
Duplicate of https://github.com/vector-im/element-web/issues/3563

**Closed by t3chguy** 2022-09-30 13:30 UTC
Labels: T-Defect
