### ISSUE TITLE
SVG room icons not viewable

### ISSUE THREAD

**Issue by erkinalp** [vector-im/element-web#25182] opened 2023-04-23 09:33 UTC
#### What would you like to do?
SVG room icons appear as letters in the room selector.
#### Why would you like to do it?
Vector images scale losslessly

### Have you considered any alternatives?

none

### Additional context

for an example, see #darkreader-community:matrix.org

**Comment by t3chguy** [comment] 2023-04-24 07:35
Duplicate of https://github.com/vector-im/element-web/issues/2581

**Closed by t3chguy** 2023-04-24 07:35 UTC
Labels: T-Enhancement
