### ISSUE TITLE
Performance issue after loading large number of join events

### ISSUE THREAD

**Issue by Winterhuman** [vector-im/element-web#21638] opened 2022-04-01 11:37 UTC
### Steps to reproduce

1. Go to https://matrix.to/#/#lobby:ipfs.io
2. Scroll up until you reach the part of the message history where 2000+ members joined at once.
3. Notice Element's UI visibly lag and stutter even after it's finished counting all the join events.

#### What did you expect?

The lag to disappear when the join events were all counted up.

#### What happened instead?

The lag continues indefinitely when the 2000+ join events are in view.

### Operating system

Arch Linux

### Application version

Element version: 1.10.8, Olm version: 3.2.8

### How did you install the app?

FlatHub

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-04-01 11:40
I think this is a duplicate of https://github.com/vector-im/element-web/issues/9200

**Closed by t3chguy** 2022-04-01 11:40 UTC
Labels: T-Defect
