### ISSUE TITLE
Rendering line numbers for code blocks gets very slow past a few hundred lines

### ISSUE THREAD

**Issue by squahtx** [vector-im/element-web#19202] opened 2021-09-28 12:05 UTC
### Steps to reproduce

1. Look at https://matrix.to/#/!ehXvUhWNASUkSLvAGP:matrix.org/$_GbJeMbzwT7yp7w2-euN-HUHcrnSeGlQzITxcbkW3Wg?via=matrix.org&via=libera.chat&via=underzsea.com in `#synapse:matrix.org`, or send a 500-700 line code block. The code block doesn't have to have anything apart from line breaks in it.
2. Element Web freezes for multiple seconds

![image](https://user-images.githubusercontent.com/8349537/135081914-d26f6b84-d67e-42d2-923e-2f386431b325.png)
`addLineNumbers` appears to take quadratic time; the spacing of the blue bits gets larger and larger as time progresses.

### What did you expect?
Element Web to be responsive

### What happened?
Element Web froze for ~10 seconds

### Operating system

Windows

### Browser information

Chrome 93.0.4577.82

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by kittykat** [comment] 2021-09-30 13:04
I had no issues with that message on Web (develop.e.i, Chromium), so marking as platform specific.

**Comment by ndren** [comment] 2023-10-19 17:44
@squahtx if it still comes up, the repository for addLineNumbers seems to be matrix-react-sdk: https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/messages/TextualBody.tsx

**Comment by Johennes** [comment] 2023-10-26 11:37
I tried desktop and web in Firefox but couldn't reproduce this, neither with the message linked above or a custom code block of a few hundred lines. Closing as we don't appear to have had a reproducible error case here since 2021.

**Closed by Johennes** 2023-10-26 11:37 UTC
Labels: T-Defect, A-Performance, Z-Platform-Specific, S-Minor, O-Uncommon
