### ISSUE TITLE
Add "Jump to room" functionality for sticky widgets.

### ISSUE THREAD

**Issue by toger5** [vector-im/element-web#19567] opened 2021-11-01 11:59 UTC
#### What would you like to do?
Jump to the room the jistsi sticky (PIP) frame belongs to.
#### Why would you like to do it?
It can be hard to find the room the jisti meeting belongs to. And I often need to search the room list to open the room so that I can see the jitsi conference in a bigger view.
#### How would you like to achieve it?
A button added to the jitsi sticky widget (or to widgets in the sticky state in general), to immediately jump to the room it belongs to.

### Additional context

This is already fixed for native element calls, where the PIP can be dragged around/ shows what room it belongs to and gives a button to jump to the room.
![](https://user-images.githubusercontent.com/1922197/110317654-5a693180-8004-11eb-9c11-e9bd36fd43cb.png)
(from: https://github.com/vector-im/element-web/issues/15682)
This functionality would be nice to have ported to sticky widgets in general. It might not only be helpful for the jisti meet widget.

**Comment by t3chguy** [comment] 2021-11-01 12:02
Duplicate of https://github.com/vector-im/element-web/issues/15920

**Closed by t3chguy** 2021-11-01 12:02 UTC
Labels: T-Enhancement

**Comment by toger5** [comment] 2021-11-01 12:21
Thanks for referencing #15920, but I think this is not the same issue. Of course there are not that many sticky widgets (atm). But they all suffer from the same issue of having no reference to the room they belong to. So adding this to all sticky widgets as part of element and not the jistsi widget in particular might be a good addition.
I will add a comment in #15920.
