### ISSUE TITLE
option for get direct link for download file in element-desktop

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#18504] opened 2021-08-12 00:02 UTC
### Your use case

In element web I can get direct link to file:
![1](https://user-images.githubusercontent.com/1297163/129117958-0faaa856-0d43-4786-8312-26b5b9d3fb97.png)
But in element-desktop I can not get it.

In some cases we get this links and use our matrix server as web-storage. But in element-desktop users can not get direct link to files or images. I think will be nice if add "copy direct link" item to menu for each file in file list of room and in menu of file in room (between "share" and "view source").

**Comment by robintown** [comment] 2021-08-12 00:17
Duplicate of https://github.com/vector-im/element-web/issues/18498

**Closed by robintown** 2021-08-12 00:17 UTC
Labels: T-Enhancement
