### ISSUE TITLE
Embed images more directly

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19648] opened 2021-11-06 10:24 UTC
#### What would you like to do?

When images are embedded, URL preview shows a smallish preview.

![image](https://user-images.githubusercontent.com/22740616/140606148-68e97802-0d7b-4ed6-8884-51847ffcc0d2.png)

However, on platforms like discord, this image is expanded to a full-sized embed directly under the image.

![image](https://user-images.githubusercontent.com/22740616/140606187-b258cdb4-e31f-43e9-98db-248e34f1ee99.png)

*Note: discord hides this behaviour now, showing only the embedded image if the message is only a link like that* 

I would like if Element could expand direct image links to show like full-sized images under the posts they get linked under.

Optionally;
- Also render `mxc://` URIs this way.
- Detect `_matrix/media/r0/download` content links and handle them the same way as a `mxc://` URI this way.

#### Why would you like to do it?

This is standard behaviour in most messengers.

#### How would you like to achieve it?

Detect if an URL is a direct image link (through URL preview responses), and display the image full-size as an embed.

**Comment by t3chguy** [comment] 2021-11-09 16:22
Duplicate of https://github.com/vector-im/element-web/issues/19095

**Closed by t3chguy** 2021-11-09 16:22 UTC
Labels: A-Timeline, A-URL-Previews, A-Media, T-Enhancement, O-Occasional
