### ISSUE TITLE
On answering an invite to a DM, scrollback is entirely missing

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8572] opened 2019-02-13 14:12 UTC
It looks like Riot is either not calling /messages on joining the room to backpaginate the timeline, or the server is lying about there not being any scrollback immediately after you having joined.  Hitting refresh however fixes it.

**Comment by ara4n** [comment] 2019-02-13 14:18
reproduced this 1 in 3 times.

**Comment by ara4n** [comment] 2019-02-13 14:19
rageshooked

**Comment by t3chguy** [comment] 2022-05-13 12:05
Duplicate of https://github.com/vector-im/element-web/issues/8372

**Closed by t3chguy** 2022-05-13 12:05 UTC
Labels: T-Defect, P1, S-Major
