### ISSUE TITLE
User-adjustable message pane size

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16671] opened 2021-03-12 02:52 UTC
Please add an Appearance configuration feature that allows the user to specify the maximum height of the message window during typing of the message.  I type long notes, and I need to see the whole note.  I can't do that well without scrolling.  If I scroll with the arrow keys, I might jump out of the message into the previous or next.  This becomes a problem for editing long messages.  The maximum height should be allowed to go to the full height of the Element window client area if desired.

**Comment by t3chguy** [comment] 2021-03-12 08:52
Duplicate of https://github.com/vector-im/element-web/issues/5882

**Closed by t3chguy** 2021-03-12 08:52 UTC
Labels: A-Composer, T-Enhancement
