### ISSUE TITLE
Pressing Ctrl+F (Cmd+F on macOS) should open the in-chat search UI.

### ISSUE THREAD

**Issue by sirocyl** [vector-im/element-web#15816] opened 2020-11-24 19:32 UTC
### Repro
- Be in any room view, where the search button for that room, in the header, is visible.
- Use the universal keyboard shortcut for "Find". (In my case: press `Ctrl` and `F`.)

### Expectation
... is that pressing `Ctrl+F` should perform the same function as clicking or focusing on the Search button in the header, whenever it's visible.
(dev note: The specific CSS UI class is `mx_RoomHeader_searchButton`.)
- The Search bar UI should extend and become visible,
- Text input focus should jump to the search bar.

### Observed behavior
... is that nothing visibly happens.
- The text focus remains where it was, be it the chat message entry, or the rooms sidebar search box.

### Platform/Version
- **OS:** Windows 10 v1809
- **Platform:** Element Desktop,
- **Version:** latest release as of this writing (1.7.12).

Willing to help debug and test if need be; I know my way around Electron devtools/inspector. Logs will be sent on request.

A recording of the expected behavior, here on Discord, is provided as a GIF below.
Note the search UI element, highlighted in yellow.

![The capture, a GIF showing an on-screen keyboard, and CTRL-F opening the search box.](https://user-images.githubusercontent.com/944067/100142251-974c5680-2e61-11eb-84f6-f542a9efe8fc.gif)

**Comment by t3chguy** [comment] 2020-11-24 20:40
Closing as duplicate of https://github.com/vector-im/element-web/issues/14027 which also has more upvotes

**Closed by t3chguy** 2020-11-24 20:40 UTC
Labels: bug, ui/ux
