### ISSUE TITLE
Riot UI window not showing on MacOS 10.15.5

### ISSUE THREAD

**Issue by fwh-dc** [vector-im/element-web#13989] opened 2020-06-11 10:09 UTC
### Description

After updating MacOs with the supplemental update to Catalina 10.15.5 the Riot UI window does not show.

The app doesn't crash. I just can't access the window.

I've tried with Riot 1.6.4 and after downgrading to 1.6.2 without any luck.

### Steps to reproduce

- Update to MacOs 10.15.5
- Start Riot

No window appears.

Logs being sent: yes/no

### Version information

- **Platform**: desktop

For the web app:

- **OS**: macOS?

For the desktop app:

- **OS**: macOS
- **Version**: 10.15.5

**Comment by oschmi** [comment] 2020-07-29 21:13
I can confirm this issue and here comes a workaround:
Click on View -> Toggle full screen

At least you can use the client in full screen :)

**Comment by iokuznetsov** [comment] 2020-08-03 09:18
Happens to me as well, started after upgrade to Element; fullscreen shows the GUI but the conversation/user names in the left pane only appear as icons, i.e. no names visible.

**Comment by t3chguy** [comment] 2020-08-03 11:37
Duplicate of https://github.com/vector-im/element-web/issues/12433

**Closed by t3chguy** 2020-08-03 11:37 UTC
Labels: bug, platform specific, type:electron
