### ISSUE TITLE
Display Image, duplicated in Background

### ISSUE THREAD

**Issue by irelativism** [vector-im/element-web#16449] opened 2021-02-14 22:48 UTC
profile display image is duplicated in background after recent changes to adress profile states.
this is a persistent issue, so no need for reproducible instructions

It would be expected for the background to be the default blank tone.

![Screenshot from 2021-02-14 22-28-59](https://user-images.githubusercontent.com/75645715/107891451-ab5e9c00-6f16-11eb-9d5f-c689d343692a.png)

- **Platform**:both native electron or debian app or browser?

- **Browser**: TorBrowser(firefox), GnomeWeb(epiphany), BraveBrowser(chromium).
- **OS**: HyperbolaGNULinux, OpenBSD, Debian.
- **URL**: app.element.io, chat.tchncs.de.

**Comment by t3chguy** [comment] 2021-02-14 23:04
Duplicate of #14665

**Closed** 2021-02-14 23:05 UTC
Labels: bug, ui/ux
