### ISSUE TITLE
Need to find a way to expose non-federatable space configuration knob

### ISSUE THREAD

**Issue by TheRadialActive** [vector-im/element-web#26167] opened 2023-09-14 12:44 UTC
#### What would you like to do?
I would like to have a ui element with the ability to mark a space as "non-federatable" when creating it in element.

#### Why would you like to do it?
In our case, we really want to be sure, only users of our homeserver can join specific public spaces by themselves.

#### How would you like to achieve it?
The functionality is already available for rooms (see #1296 ), and the interface for it could almost be copied from there.

### Have you considered any alternatives?

We already tested it successfully by sending a customized POST query to the homeserver via the devtools in Firefox. But that's really time consuming.

**Comment by t3chguy** [comment] 2023-09-14 14:08
Duplicate of https://github.com/vector-im/element-meta/discussions/741

**Closed by t3chguy** 2023-09-14 14:08 UTC
Labels: T-Enhancement
