### ISSUE TITLE
Ignore avatar/nickname changes when sorting rooms

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-web#16816] opened 2021-03-29 23:18 UTC
#### Is your suggestion related to a problem? Please describe.
When changing my avatar or nickname, events are sent to each room I'm in to indicate that. This then messes up the order of rooms in my room list, so rooms which I use very infrequently sometimes rise to the top, which is annoying.

#### Describe the solution you'd like.
Events like avatar or nickname changes should be ignored when sorting rooms.

#### Describe alternatives you've considered.
None

#### Additional context
It seems this is already the case for Element Android.

**Comment by aaronraimist** [comment] 2021-03-30 00:52
Duplicate of #110

**Closed by aaronraimist** 2021-03-30 00:52 UTC
Labels: T-Enhancement
