### ISSUE TITLE
option to unmute rooms for N minutes after having typed there

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3180] opened 2017-02-09 02:16 UTC

**Comment by Matrixcoffee** [comment] 2017-02-17 20:00
Maybe even group rooms where you have recently sent something into a separate category, e.g. "Active Conversations".

**Comment by t3chguy** [comment] 2023-03-29 15:06
Duplicate of https://github.com/vector-im/element-web/issues/2588

**Closed by t3chguy** 2023-03-29 15:06 UTC
Labels: P2, A-Notifications, T-Enhancement
