### ISSUE TITLE
Crash of version 1.7.33 on hirsute on amd64

### ISSUE THREAD

**Issue by monochromec** [vector-im/element-web#18189] opened 2021-07-22 18:40 UTC
Same symptoms as https://github.com/vector-im/element-web/issues/18173 but apparently different root cause
(stack trace at: https://gist.github.com/monochromec/14ce9a604a368d0ee017730923ab9265)

#### Description

Random crashes on Ubuntu 21.04

#### Steps to reproduce

- Start Element
- Observe crash while app becomes unresponsive

Logs being sent: yes

(Cf. above)

#### Version information

- **Platform**: web (in-browser) or desktop?
Desktop 1.7.33
- Ubuntu 21.04

1.7.33 apparently really missed the boat on several platforms. More than happy to provide additional information - please let me know what else is required...

**Comment by dbkr** [comment] 2021-07-22 21:36
The stack traces in your stack trace are just it complaining very loudly about not being able to find an en_us translation (which doesn't exist for desktop, probably because none of the few strings in desktop have any British / American-isms in them), so it's possible it is the same root cause.

**Comment by monochromec** [comment] 2021-07-22 21:49
So this is a packaging issue?

**Comment by monochromec** [comment] 2021-07-23 06:20
The Flatpak version has the same issue. :-(

Let me know if / what additional info is required so this can be fixed ASAP.

**Comment by monochromec** [comment] 2021-08-07 12:51
So the missing json file is indeed a packaging issue as the corresponding asar file only contains en_EN.json. It would be great if the US locale could be included in the asar configuration as well.

**Comment by t3chguy** [comment] 2021-08-07 12:58
As per https://github.com/vector-im/element-desktop#translations - there isn't yet a US translation in Weblate

**Comment by monochromec** [comment] 2021-08-08 06:45
According to weblate there is :-). It's just not complete yet, hence I presume the missing file.

**Comment by t3chguy** [comment] 2021-08-10 07:56
https://translate.element.io/projects/element-desktop/#languages

![image](https://user-images.githubusercontent.com/2403652/128830089-029a7e3b-1e06-462f-b507-3e294a371ef5.png)

Where are you seeing the US translation..?

**Comment by monochromec** [comment] 2021-08-11 13:36
https://translate.element.io/projects/element-web/element-web/

<img width="1407" alt="Trans2" src="https://user-images.githubusercontent.com/606567/129038772-36ca1ced-529a-4753-892e-1dd91f2caa3f.png">

**Comment by t3chguy** [comment] 2021-08-11 13:39
That's a different repo. And in fact the element-web portion of the app does have the US lang.

![image](https://user-images.githubusercontent.com/2403652/129039213-76ad7ed1-e47a-41a3-9403-cd9416abd734.png)

**Comment by novocaine** [comment] 2021-09-27 16:07
@monochromec are you still experiencing issues with current versions? (e.g. 1.9.0)

**Comment by monochromec** [comment] 2021-09-29 08:11
The app is still missing the json file but it's not crashing anymore.

**Comment by novocaine** [comment] 2021-09-29 08:14
I believe the missing JSON file will cause it to remain in English (UK), which is not ideal but not fatal. Closing this one.

**Closed by novocaine** 2021-09-29 08:14 UTC
Labels: T-Defect, Z-Platform-Specific, S-Critical, A-Electron, O-Uncommon
