### ISSUE TITLE
"Compare a unique set of emoji if you don't have a camera on either device" shows on aarch64 app when the linux phone has a camera.

### ISSUE THREAD

**Issue by AnotherNeko** [vector-im/element-web#26003] opened 2023-08-18 21:47 UTC
### Steps to reproduce

1. Test the camera to make sure it works using the the app Megapixels, works as expected.
2. logged in to a homeserver on the deb app "element-desktop", on aarch64 build on Mobian
3. Start verification process. 
4. "Verify with another device".
5. Accept from another Matrix client (in this case, it's Element in my web browser on my PC)
6. I see "Compare a unique set of emoji if you don't have a camera on either device". There is no option to use the linux phone's camera, even though a different app, Megapixels, has access to the camera.

#### What did you expect?
Similar to the Element app for Android, I expected the phone to ask to use the camera (if permission is necessary), then activate a QR code scanner in Element and show a QR code to scan on the other client.
#### What happened instead?
I see "Compare a unique set of emoji if you don't have a camera on either device".

### Operating system

Mobian on Pinephone (not pro)

### Application version

Element version: 1.11.39 Olm version: 3.2.14

### How did you install the app?

https://element.io/download#linux    , aarch64

### Homeserver

Synapse

### Will you send logs?

Yes

**Comment by AnotherNeko** [comment] 2023-08-19 00:50
another detail is that I was using Phosh desktop. I haven't tested with other DEs like Plasma Mobile, but I could...

**Comment by AnotherNeko** [comment] 2023-08-19 13:08
tested on Plasma Mobile, same problem.

**Comment by t3chguy** [comment] 2023-08-21 07:48
Duplicate of https://github.com/vector-im/element-web/issues/12178

**Closed by t3chguy** 2023-08-21 07:48 UTC
Labels: T-Defect
