### ISSUE TITLE
room previews leak escaped HTML

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17585] opened 2021-06-07 16:43 UTC
<img width="400" alt="Screenshot 2021-06-07 at 17 42 32" src="https://user-images.githubusercontent.com/1294269/121058103-e6cbf180-c7b7-11eb-97c6-783f4ad6a80f.png">

the `&amp;` should be a &

**Comment by t3chguy** [comment] 2021-06-07 16:44
Duplicate of https://github.com/vector-im/element-web/issues/17101

**Closed by t3chguy** 2021-06-07 16:44 UTC
Labels: T-Defect
