### ISSUE TITLE
Dark to Light mode seems to work in a weird way.

### ISSUE THREAD

**Issue by 28JayG** [vector-im/element-web#23748] opened 2022-11-10 11:36 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
- update **config.json**, with custom theme, set default theme to  custom-[theme] in **config.json**
- now login to the application, custom theme is applied.

2. What do you click?
- click user icon, switch to dark mode.
- again switch back to light mode. default light mode is applied and not custom theme

#### What did you expect?
After converting back to light mode from dark mode, custom theme must be applied.

#### What happened instead?
After converting to light mode from dark mode, **default** light mode is applied & **not** custom theme

### Operating system

Windows, Ubuntu

### Browser information

Chrome

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-11-10 13:47
Duplicate of https://github.com/vector-im/element-web/issues/14873

**Closed by t3chguy** 2022-11-10 13:47 UTC
Labels: T-Defect
