### ISSUE TITLE
"Something went wrong" when joining room

### ISSUE THREAD

**Issue by mpeter50** [vector-im/element-web#23072] opened 2022-08-14 14:59 UTC
### Steps to reproduce

1. I had the Pine64 Space opened
2. I've clicked "Join" for the PineNote room.
3. I was presented with the "Something went wrong" dialog.

#### What did you expect?
I expected to join said room. 

#### What happened instead?
The "Something went wrong" dialog was shown.

### Operating system

Windows

### Browser information

Firefox

### URL for webapp

app.element.io

### Application version

1.11.2

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by mpeter50** [comment] 2022-08-14 15:01
It might be helpful to know that joining the room was successful, but the browser's urlbar was still showing the URL of the space, so the problem might have happened while switching to the joined room.

**Comment by mpeter50** [comment] 2022-08-14 15:03
Hmm, it happened again while joining another room from the same space: the PineBook room.
I've submitted these logs too.

**Comment by SimonBrandner** [comment] 2022-08-14 15:04
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by SimonBrandner** 2022-08-14 15:04 UTC
Labels: T-Defect
