### ISSUE TITLE
Room sorting fails after initial log in.

### ISSUE THREAD

**Issue by bbissm** [vector-im/element-web#25767] opened 2023-07-11 15:31 UTC
### Steps to reproduce

The functionality for sorting rooms either alphabetically or by most recent only works after a room has been selected. This process sets two keys in the localstorage, namely 'mx_space_context_<space-name>' and 'mx_last_room_id', which are essential for sorting the sublist of rooms.

However, an issue arises when these localstorage keys are not defined. (When no room has been selected after a user has freshly logged in). In these instances, the sorting functionality fails to work as intended. 

#### What did you expect?
The roomsublist should be sorted
#### What happened instead?
Nothing.

### Operating system

Windows

### Browser information

Google Chrome

### Application version

1.11.35

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-07-11 15:50
Duplicate of https://github.com/vector-im/element-web/issues/25553

**Closed by t3chguy** 2023-07-11 15:50 UTC
Labels: T-Defect

**Comment by bbissm** [comment] 2023-07-12 13:50
So you don't plan to fix the issue on your web client? @t3chguy

**Comment by t3chguy** [comment] 2023-07-12 13:55
@bbissm sorry what? Your issue is identical to https://github.com/vector-im/element-web/issues/25553 - which is open. What I don't plan to do is leave two identical issues open to create more confusion.
