### ISSUE TITLE
New messages not showing in the left panel on develop

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#25777] opened 2023-07-12 12:47 UTC
### Steps to reproduce

1. Receive message
2. See notifications appear on EX/legacy iOS and Android
3. See no notifications in the left panel on web
4. Search for DM where new message arrived and see the unread marker in the search results, but still not in the left panel

#### What did you expect?
All 5 apps show new messages at the same time

#### What happened instead?
Mobile apps show notifications in system notifications, but web doesn't show new messages in the left panel

### Browser information

Version 114.0.5735.198 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 311c5fec664d-react-186497a67d09-js-e68a1471c12c Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-07-13 15:06
Duplicate of https://github.com/vector-im/element-web/issues/25331

**Closed by t3chguy** 2023-07-13 15:06 UTC
Labels: T-Defect, X-Regression, S-Major, A-Notif-Panel, A-Notifications, O-Occasional
