### ISSUE TITLE
Custom tag icon breaks UI as of 1.7.11

### ISSUE THREAD

**Issue by daduke** [vector-im/element-web#15600] opened 2020-10-29 08:06 UTC
### Description

Starting with 1.7.11 (and including 1.7.12), the custom tag icon, which used to be in the lower left corner, moved up and to the right and breaks the UI.

### Steps to reproduce

- have custom tags enabled
- upgrade to 1.7.11
- *gasp*

![element](https://user-images.githubusercontent.com/818170/97541122-e9b26880-19c4-11eb-8445-74be441f5297.png)

The screenshot shows Element Desktop (self-built Fedora rpm) on the left and Element Web on the right. An incomplete workaround is to add

```
.mx_CustomRoomTagPanel {
	position: absolute;
	bottom: 0px;
}
```
to the CSS which moves it back, albeit with some clipping.

Logs being sent: no

### Version information

1.7.11 and 1.7.12

- **Platform**: both

For the web app:

- **Browser**: at least FF + Chrome
- **OS**: at least Fedora + Win10 

For the desktop app:

- **OS**: at least Fedora + WIn10

**Comment by t3chguy** [comment] 2020-10-29 08:37
Duplicate of #15579

**Closed** 2020-10-29 08:37 UTC
Labels: bug, ui/ux
