### ISSUE TITLE
emoji verification descriptions are ellipses

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19977] opened 2021-11-30 23:17 UTC
### Your use case

descriptions can be ellipses which isn't great. there is plenty space.

![image](https://user-images.githubusercontent.com/2803622/144143224-0b15c342-8fe6-4e31-82b2-802ac40c01b4.png)

happens at least in the popup, not sure about right panel.
A-E2EE-SAS-Verification
A-E2EE-Cross-Signing

**Comment by dbkr** [comment] 2021-12-02 14:30
I'd probably say minor for this one, effectively the workaround is to guess it from the text you can see + the image.

**Comment by HarHarLinks** [comment] 2021-12-02 14:47
in case it's not clear: this should be made to work flexible enough for any emoji description i18n

**Comment by bmarty** [comment] 2022-04-04 12:59
I have encountered the issue today, I agree this is not great, and this should be fixed.

**Comment by t3chguy** [comment] 2022-04-08 09:08
This was done specifically by design

**Comment by bmarty** [comment] 2022-04-22 10:34
We suck

**Comment by turt2live** [comment] 2022-05-07 03:51
Duplicate of https://github.com/vector-im/element-web/issues/12974

**Closed by turt2live** 2022-05-07 03:51 UTC
Labels: S-Minor, X-Needs-Design, T-Enhancement, A-E2EE-SAS-Verification, A-E2EE-Cross-Signing, A-Appearance, O-Occasional, Z-WTF
