### ISSUE TITLE
More advanced search

### ISSUE THREAD

**Issue by deepadmax** [vector-im/element-web#25540] opened 2023-06-08 16:54 UTC
#### What would you like to do?

I'd like to be able to search for messages not just by content but by author and possibly other properties.

#### Why would you like to do it?

- Sometimes the results in a public room can be overwhelming to browse when you're looking for something by someone who you know said it.
- You may want to go back through your own messages for something you've said and delete it.
- _There really are a lot of reasons to support a more complex search._

#### How would you like to achieve it?
By adding options to filter messages by author, mentions, attachments, etc. Take inspiration from Discord if you will.

### Have you considered any alternatives?

I wouldn't know what alternatives there *could* be to a more detailed search functionality.

**Comment by t3chguy** [comment] 2023-06-09 07:16
Duplicate of https://github.com/vector-im/element-meta/issues/1156

**Closed by t3chguy** 2023-06-09 07:16 UTC
Labels: T-Enhancement
