### ISSUE TITLE
It's too easy to accidentally ignore a user

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8014] opened 2019-01-04 00:16 UTC
This is a concern raised by someone else, and probably applies to the mobile apps more than the web side. May be fixed by https://github.com/vector-im/riot-web/issues/6819 as a clear indicator that you're ignoring someone?

Concern is that the ignore button is easy to press if you're trying to start a chat with someone.

**Comment by lampholder** [comment] 2019-01-04 09:56
Agreed; we should probably just make the action of ignoring somebody much more heavyweight (multistage, 'are you sure', etc.), since the whole point of ignoring somebody is that you push them out of your Riot experience pretty much entirely.

**Comment by aaronraimist** [comment] 2021-12-28 20:27
Closing as duplicate of #14633

**Closed by aaronraimist** 2021-12-28 20:27 UTC
Labels: T-Defect, P3, S-Minor, A-Right-Panel
