### ISSUE TITLE
Emojis completion erases text

### ISSUE THREAD

**Issue by Epy** [vector-im/element-web#17925] opened 2021-07-09 19:23 UTC
#### Steps to reproduce
Hello

- `In a Matrix chat room, with Element web (Firefox 78) I write some words, then a text smiley like this :) without replacing it by the  image emoji then some other words and a text shortcut for an emoji, like <3` at the end of sentence

- If I use the keyboard (tab key) to validate remplacement of <3 by :heart: it erases the sentence between the :) smiley and the heart to only let the heart.

- My sentence ends like this in the edit zone.
`In a Matrix chat room, with Element web (Firefox 78) I write some words, then a text smiley like this` :heart: 

Thanks

#### Version information

I use the Element app

- **Browser**: Firefox 78.11.0esr
- **OS**: Debian Buster up-to-date
- **URL**: https://app.element.io/

**Comment by SimonBrandner** [comment] 2021-07-09 19:29
Yeah, I can repro the above with _Automatically replace plain text Emoji_

**Comment by yannicka** [comment] 2021-08-29 15:55
Strange, I can't reproduce the problem (with "Automatically replace plain text Emoji"). :thinking:

*Note: issue from #16312.*

**Comment by SimonBrandner** [comment] 2021-08-29 15:59
We changed the way emoji behave since, so this no longer seems relevant, so I am going to close this, send a message with `@SimonBrandner` in case I am wrong

**Closed by SimonBrandner** 2021-08-29 15:59 UTC
Labels: T-Defect, A-Autocomplete, A-Composer

**Comment by Epy** [comment] 2024-07-01 21:26
Hello
I'm sorry but this bug is back

`Version de https://element.underworld.fr : 1.11.67
Version crypto : Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1`

**Comment by SimonBrandner** [comment] 2024-07-02 08:14
@t3chguy, could you please have a look?

**Comment by t3chguy** [comment] 2024-07-02 08:27
Sorry it'd be down to the maintainer. I suggest opening a new issue with all the necessary details and logs.
