### ISSUE TITLE
UTD from Inez on desktop

### ISSUE THREAD

**Issue by deniseal** [vector-im/element-web#16404] opened 2021-02-08 14:55 UTC
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

<img width="737" alt="image" src="https://user-images.githubusercontent.com/51328716/107236555-56ea8680-6a15-11eb-9058-a50b6608f462.png">

### Version information

- **Platform**:desktop

For the desktop app:

- **OS**: macOS
- **Version**: 1.7.20

**Comment by t3chguy** [comment] 2023-07-11 09:22
Duplicate of https://github.com/vector-im/element-meta/issues/245

**Closed by t3chguy** 2023-07-11 09:22 UTC
Labels: T-Defect, S-Major, A-E2EE, Z-UISI, O-Uncommon
