### ISSUE TITLE
Default language selection does not work for Chinese users

### ISSUE THREAD

**Issue by alvinhochun** [vector-im/element-web#18007] opened 2021-07-15 11:04 UTC
#### Description

The default language selection does not work for most if not all Chinese users, regardless of region.

It seems that Element web uses the codes zh_Hant and zh_Hans for Traditional Chinese and Simplified Chinese. Without looking at the code, I will take a guess that Element web is using `window.navigator.languages` to check for the browser language and does a simple comparison to attempt to select a language. This wouldn't work for Chinese.

The browsers use [BCP 47](https://tools.ietf.org/search/rfc5646#appendix-A) language tags. For Chinese, it is often in the `language-region` or `language-script-region` format, e.g. `zh-HK`, `zh-Hant-TW`, `zh-Hans-CN`. Given the Chinese languages used in Element web, what should happen instead, is to take the `language-script` combo and compare with that. When the `script` part is not provided, the *better* way is to make use of the [Likely Subtags data from Unicode CLDR](https://unicode-org.github.io/cldr-staging/charts/38/supplemental/likely_subtags.html) to choose the best match, but a simple mapping is mostly sufficient:

- `zh-TW` / `zh-HK` / `zh-MO` map to `zh-Hant`
- For the rest of `zh-*` map to `zh-Hans`

#### Steps to reproduce

- Set browser to prefer any flavour of Chinese language.
- Open https://app.element.io/

Describe how what happens differs from what you expected.

Site uses English as default instead of Traditional Chinese or Simplified Chinese.

#### Version information

- **Platform**: web
- **Browser**: Firefox (Windows), Firefox (Linux), Firefox (Android), Chrome (Android)
- **OS**: Windows, Arch Linux, Android
- **URL**: app.element.io

**Comment by t3chguy** [comment] 2021-07-15 16:18
Duplicate of https://github.com/vector-im/element-web/issues/15868

**Closed by t3chguy** 2021-07-15 16:18 UTC
Labels: I18n, T-Defect

**Comment by alvinhochun** [comment] 2021-07-15 18:37
https://github.com/vector-im/element-web/issues/5913 seems more relevant.

Please note that I also proposed the fix in the first post.

**Comment by qzicxjmozbxameuhnk** [comment] 2021-07-21 01:14
This looks like the correct solution, but according to my observations, the implementation code for language selection is in the [matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk) project, and element-web will use this project during the build process, so it seems that this needs to be fixed by the upstream project.

If element-web users cannot touch the upstream project, or simply want to fix the problem in this project, here is a one-line code solution: https://github.com/vector-im/element-web/issues/5913#issuecomment-883257145
