### ISSUE TITLE
multi-login support missing UI/UX

### ISSUE THREAD

**Issue by jimmont** [vector-im/element-web#15847] opened 2020-11-28 05:48 UTC
Description: 
When logged into both chat.mozilla.org and app.element.io I have no way (that is obvious to me) to switch credentials to another alias using one or more auth providers in each.

Expected:
When using Google products I can switch between accounts using the small circle with my image/icon in the upper right (ltr/en-us language). Click the icon-control, select another account (work, personal, etc).

Versions:
applies to all platforms of current active release as-of 2020-11-28 when filing this bug, in use on iOS and the web at app.element.io and chat.mozilla.org

**Comment by t3chguy** [comment] 2020-11-28 10:45
Duplicate of https://github.com/vector-im/element-web/issues/2320

**Closed by t3chguy** 2020-11-28 10:45 UTC
Labels: bug, ui/ux
