### ISSUE TITLE
Forward Message sends message to wrong room when switching between spaces

### ISSUE THREAD

**Issue by rooly4** [vector-im/element-web#17458] opened 2021-05-24 18:13 UTC
### Description

Selecting a different space while attempting to forward a room forwards the message to the first visible room in the newly selected space, or not at all if no room was previously set visible

### Steps to reproduce

- Have Spaces beta enabled and several spaces configured
- Select "Forward Message" from the context menu on the current room
- Click on different space
- Message shows up in selected room from new space
  - Message may not show up at all if no room was selected

Forwards should only be sent to rooms the user is chatting in.

Honestly the whole forwarding thing may just need to be revisited design wise wrt spaces. I just wanted to make sure the bug was reported

### Version information

- **Platform**: desktop
- **OS**: Ubuntu
- **Version**: Element version: 1.7.28, olm version: 3.2.1

**Comment by t3chguy** [comment] 2021-05-24 18:17
Duplicate of https://github.com/vector-im/element-web/issues/17109

**Closed by t3chguy** 2021-05-24 18:17 UTC
