### ISSUE TITLE
Room unusable after "Failed to find load timeline position"

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#22725] opened 2022-07-04 11:27 UTC
### Steps to reproduce

1. Enter a specific room that is showing this problem
2. Click the "Go to last unread message" button
3. Problem 1: Receive a message "Failed to load timeline position"
4. Problem 2: I can see no messages, and I am unable to scroll in the room.

#### What did you expect?
I expected to go back to the last unread message.
And I expected to be able to use the room after the error.

#### What happened instead?
I see a blank room that is unusable until I go to a different one.

![unable mp4](https://user-images.githubusercontent.com/76812/177147219-358532fb-f7b1-435b-81ff-8cda7c663171.gif)

### Operating system

Ubuntu 21.10

### Browser information

Firefox 101.0.1

### URL for webapp

https://develop.element.io

### Application version

Element version: 53ce8388f1b3-react-0026e0462b3f-js-ee0264f77d02 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by bwindels** [comment] 2022-07-04 11:38
Making this minor given that you can switch back and forth as a (cumbersome) workaround

**Comment by andybalaam** [comment] 2022-07-04 11:39
My rageshake is attached above.

**Comment by t3chguy** [comment] 2022-07-04 11:48
Duplicate of https://github.com/vector-im/element-web/issues/20927

**Closed by t3chguy** 2022-07-04 11:48 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Timeline, O-Occasional
