### ISSUE TITLE
Use room alias/address instead of room id in generated permalinks if alias available.

### ISSUE THREAD

**Issue by iokiwi** [vector-im/element-web#15833] opened 2020-11-26 05:13 UTC
**Is your suggestion related to a problem? Please describe.**

The permalinks generated to share a room always use an opaque, non human readable room id rather than the nice, human readable room alias.

 * looks spammy / scary for new users
 * Opaque and spammy looking even for savvy users

![Screenshot from 2020-11-26 17-45-44](https://user-images.githubusercontent.com/1480457/100310763-ce159e80-3012-11eb-8571-6c3f69f5a29b.png)

This renders on matrix.to as

![Screenshot from 2020-11-26 17-46-31](https://user-images.githubusercontent.com/1480457/100310124-5f841100-3011-11eb-9342-e4f8a5269256.png)

**Describe the solution you'd like**

Generate link using room's alias/address if such an alias exists. If I construct the url myself using the room alias rather than the room id the url rendered on matrix.to is much more user friendly.

![Screenshot from 2020-11-26 17-46-55](https://user-images.githubusercontent.com/1480457/100310114-5d21b700-3011-11eb-8d87-7c2d6cde5fc3.png)

**Describe alternatives you've considered**
None. The only work around I have is to construct/modify the Url myself.

**Additional context**
None

**Comment by t3chguy** [comment] 2020-11-26 09:15
Duplicate of https://github.com/vector-im/element-web/issues/12447

**Closed by t3chguy** 2020-11-26 09:15 UTC
Labels: suggestion
