### ISSUE TITLE
Search results always show mxid, not Display Name

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#17956] opened 2021-07-12 13:19 UTC
A message showing a displayname:

![image](https://user-images.githubusercontent.com/1922197/125294392-225c5d00-e31c-11eb-9b22-37e2eb8665a1.png)

Search results, including the above message, this time showing the mxid:

![image](https://user-images.githubusercontent.com/1922197/125294080-e5906600-e31b-11eb-878d-824ece0cb13e.png)

**Comment by t3chguy** [comment] 2021-07-12 13:22
@lampholder what version is this as this should be fixed?

**Comment by lampholder** [comment] 2021-07-12 13:29
My screenshot is from Element version: 1.7.32 (/app) but it's also visible on Nightly Desktop Latest

**Comment by t3chguy** [comment] 2021-07-12 13:33
I can repro

**Comment by t3chguy** [comment] 2021-07-12 13:34
Duplicate of https://github.com/vector-im/element-web/issues/560

**Closed by t3chguy** 2021-07-12 13:34 UTC
Labels: T-Defect, X-Needs-Info
