### ISSUE TITLE
.APNG file is playing in the sidepanel (Web and Client)

### ISSUE THREAD

**Issue by Z0pyrus** [vector-im/element-web#22608] opened 2022-06-17 21:29 UTC
### Steps to reproduce

1. Set an gif/video as .apng file as the profile picture 
2. Side panel will play the .apng in client and as well on web

### Outcome

What did you expect?
The .apng file shouldn't play in the side panel.

What happened instead?
It played the .apng file

### Operating system

Windows 10, Manjaro, Web

### Application version

Version von Element: 1.10.13/15 Version von Olm: 3.2.8

### How did you install the app?

From https://element.io/get-started, pacman

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-06-18 13:47
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/18878

**Closed by SimonBrandner** 2022-06-18 13:47 UTC
Labels: T-Defect
