### ISSUE TITLE
Display glitches in Threads

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#19624] opened 2021-11-04 12:52 UTC
### Steps to reproduce

Not sure what the repro steps are

### Outcome

Kat's avatar appears as a giant K in a weird place obscuring text in the chat

<img width="1229" alt="Screenshot 2021-11-04 at 12 49 22" src="https://user-images.githubusercontent.com/57377/140316445-e5f87d18-58b6-46db-a0bd-27db4d2740c6.png">

Also in the thread view

<img width="437" alt="Screenshot 2021-11-04 at 12 49 47" src="https://user-images.githubusercontent.com/57377/140316516-a5af7c1c-ce0f-4d60-8614-dafa78595365.png">

### Operating system

OS X

### Application version

Element Nightly version: 2021110401 Olm version: 3.2.3

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by robintown** [comment] 2021-11-04 14:15
Duplicate of https://github.com/vector-im/element-web/issues/19623

**Closed by robintown** 2021-11-04 14:15 UTC
Labels: T-Defect, S-Minor, A-Threads
