### ISSUE TITLE
Some files missing from files panel

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18550] opened 2021-08-15 11:46 UTC
### Steps to reproduce

1. Receive file in e2ee dm
2. wait a day
3. search the file in files panel

I can't really reproduce, but this is how it happened.
The problem persists when restarting element.

### What happened?

it's missing for me on nightly. it does however appear in the panel for the other user (stable).

### What did you expect?

all files in file panel (except voice messages)

### Operating system

arch

### Application version

Element Nightly version: 2021081501 Olm version: 3.2.3

### How did you install the app?

aur nightly-bin

**Comment by HarHarLinks** [comment] 2021-08-15 11:47
logs submitted

**Comment by HarHarLinks** [comment] 2021-08-16 12:34
The file I noticed this with has now appeared in Element Nightly version: 2021081601 Olm version: 3.2.3

**Comment by HarHarLinks** [comment] 2021-09-02 14:25
Another file, this time an image, is again not in the files panel.
Element Nightly version: 2021090101
Olm version: 3.2.3

Again, the problem persists when restarting element, but I assume that that is just cache. I think what happened last time for the file to appear after a while is it was so old so when I looked again it was loaded fresh.

**Comment by t3chguy** [comment] 2022-11-14 13:42
Duplicate of https://github.com/vector-im/element-web/issues/12490

**Closed by t3chguy** 2022-11-14 13:42 UTC
Labels: T-Defect, S-Major, A-E2EE, A-File-Panel, O-Uncommon
