### ISSUE TITLE
Add ability to remove rooms from spaces from context menu in room list

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#17544] opened 2021-06-03 13:55 UTC
A suggestion from @JordanHancock-NV after reaching for it as a natural place to want to remove a room from a Space. Relatedly, 'Explore rooms' didn't feel like a good place to reach to manage which rooms are in Spaces. 

cc @niquewoodhouse @t3chguy

**Comment by t3chguy** [comment] 2021-06-03 13:56
Duplicate of https://github.com/vector-im/element-web/issues/17279

**Closed by t3chguy** 2021-06-03 13:56 UTC
Labels: A-Spaces
