### ISSUE TITLE
Searching - multiple results for the same user

### ISSUE THREAD

**Issue by markiceman** [vector-im/element-web#11028] opened 2019-10-02 06:23 UTC
I'm using Synapse + mxisd with searching in LDAP (AD). Riot Desktop application version 1.4.0 and 1.4.1 (older version are OK), have issue with searching.

Example:

If I search user with substring "kbre", then i have doubled (sometimes tripled and more) results with the same user.

I see in syslog: There are two results for user from mxisd:

one LDAP search in display name and second by 3PID. But it is still the same user.

Riot 1.3.x and older display it correctly, but Riot 1.4.x display double results. It is wrong.

![Výstřižek](https://user-images.githubusercontent.com/54726936/66022102-2aebf680-e4ed-11e9-8c90-5983df52d3d5.PNG)

It is similar situation as this:

https://github.com/vector-im/riot-android/issues/1984

- **Platform**: desktop

- **OS**: Windows
- **Version**: 1.4.1

**Comment by markiceman** [comment] 2019-10-04 10:42
1.4.2  have the same problem.

**Comment by t3chguy** [comment] 2019-10-04 13:05
That looks like there are legatimely two different users, given the Matrix IDs are of different length, there are no 3PIDs involved here at all.

**Comment by t3chguy** [comment] 2019-10-04 13:05
That looks like there are legatimely two different users, given the Matrix IDs are of different length, there are no 3PIDs involved here at all.

**Comment by markiceman** [comment] 2019-10-04 14:53
No, it is the same user with the same MXID. Only my blue line have different length ...

**Comment by t3chguy** [comment] 2019-10-04 14:59
Can you share the API request responses from the network tab of your browser so we can figure out where this issue lies?

**Comment by markiceman** [comment] 2019-10-05 23:41
I don't know, how can i do it from desktop application.

**Comment by t3chguy** [comment] 2019-10-06 08:18
Desktop app is based on electron (chromium) so control shift i will bring up dev tools

**Comment by markiceman** [comment] 2019-10-07 07:06
{"limited":false,"results":[{"display_name":"Bréxxxá Kateřxxx","user_id":"@kbrexxxa:matrix.airbank.cz"},{"display_name":"Bréxxxá Kateřxxx 🦙","avatar_url":"mxc://matrix.airbank.cz/kpBRzDmEJXzmhLugaQjvuxxx","user_id":"@kbrexxxa:matrix.airbank.cz"}]}

**Comment by t3chguy** [comment] 2019-10-07 07:20
So this appears to be a mxisd issue as it returns the same user twice

**Comment by markiceman** [comment] 2019-10-07 07:33
But older Riot versions are OK. Why?

**Comment by markiceman** [comment] 2019-10-07 07:39
I checked the situation in older version (1.3.2) now. Riot gets the same response, but display only one result. It is correct.

**Comment by jryans** [comment] 2019-10-07 10:55
It sounds like there may be a regression in the address picker component then...?

**Comment by t3chguy** [comment] 2019-10-07 11:00
I mean is it doing the wrong thing? Its being given two results by the server for its query and its rendering them

**Comment by t3chguy** [comment] 2019-10-07 11:00
If it was to ignore one of them, which would it ignore, given they are different results?

**Comment by turt2live** [comment] 2019-10-07 11:04
They both have the same MXID, so should be concatenated. We should probably use the most detailed record.

**Comment by jryans** [comment] 2019-10-07 11:05
I guess I am curious what changed about the behaviour and why it only showed one before. I am worried we may have been applying some clean up logic that has gone missing, or something similar.

**Comment by markiceman** [comment] 2019-10-18 21:00
Version 1.5.0 have the same problem.

**Comment by lampholder** [comment] 2019-10-24 16:21
We're about to take a holistic look at user listing, so hopefully we'll sweep this issue up with that.

**Comment by kittykat** [comment] 2022-01-07 09:20
@markiceman is there any chance you could re-test and confirm if you are still experiencing this issue or whether it was resolved in the review of the search?

**Comment by markiceman** [comment] 2022-01-07 13:18
![obrazek](https://user-images.githubusercontent.com/54726936/148549285-ffa3f5cc-eb56-4a45-8ad0-8c29a604114b.png)

Still the same. 

Verze Riot: 1.9.8
Verze Olm: 3.2.8

**Comment by t3chguy** [comment] 2022-01-07 13:41
This still looks to be an issue with the backend, nothing in the spec says that the client must de-duplicate these results nor how.

**Comment by markiceman** [comment] 2022-01-07 14:09
I have users in LDAP. Software ma1sd found one record in Display Name and another record in 3PID (maybe email address). I don't know where must be deduplicate ...

**Comment by t3chguy** [comment] 2022-01-07 14:35
I would argue the backend should de-duplicate so that all clients don't have to

**Closed** 2023-07-19 09:49 UTC
Labels: T-Defect, X-Cannot-Reproduce, X-Regression, S-Minor, Z-Backend, A-Invite, A-Identity-Server, O-Uncommon, X-Needs-Community-Testing
