### ISSUE TITLE
Spaces feedback button is not clickable

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18657] opened 2021-08-20 11:02 UTC
### Steps to reproduce

1. Explore rooms for a space
2. Click on Give feedback

<img width="380" alt="Screenshot 2021-08-20 at 11 59 37" src="https://user-images.githubusercontent.com/57377/130224017-a7ad7c77-2588-4630-8cfb-7348061046de.png">

### What happened?

Nothing happened

### What did you expect?

To go to a feedback form.

### Operating system

OS X

### Browser information

Chrome

### URL for webapp

app.element.io

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment] 2021-08-20 11:05
Duplicate of https://github.com/vector-im/element-web/issues/18524

**Closed by SimonBrandner** 2021-08-20 11:05 UTC
Labels: T-Defect, S-Major, A-Spaces, O-Intermediate
