### ISSUE TITLE
Option for icon always visible in system tray resets on update on windows?

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18596] opened 2021-08-17 16:00 UTC
### Steps to reproduce

Report from #element-web:matrix.org that this option resets on every update of the app.

### What happened?

it reset

### What did you expect?

it not to reset

**Comment by t3chguy** [comment] 2021-08-31 12:09
Duplicate of https://github.com/vector-im/element-web/issues/4601

**Closed by t3chguy** 2021-08-31 12:09 UTC
Labels: T-Defect, Z-Platform-Specific, S-Minor, A-Electron, O-Low
