### ISSUE TITLE
Homeserver URL validity check fails on desktop but not on web

### ISSUE THREAD

**Issue by besendorf** [vector-im/element-web#18836] opened 2021-08-30 12:49 UTC
### Steps to reproduce

During log in after starting element-dektop on Windows 10 when entering an alternatiove homeserver the validity check fails. However on element web. The check doesnt fail for the same url.
![grafik](https://user-images.githubusercontent.com/26350155/131341288-67e42f9f-c326-4b2f-b8ce-38cf2a33e0f7.png)

### What happened?

see above

### What did you expect?

homeserver check works as expected

### Operating system

Windows 10

### Application version

1.8.1.0

### How did you install the app?

from https://element.io/get-started via the installer

### Homeserver

chat.astafu.de

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment] 2021-08-30 13:04
I cannot repro on Debian bookworm, are you able to reliably repro after a restart?

**Comment by besendorf** [comment] 2021-08-30 13:06
> 
> 
> I cannot repro on Debian bookworm, are you able to reliably repro after a restart?

Yes. In fact this is the case since a few weeks now. There wasn't anything on stdout either or else I would've posted it.
Are there any logfiles I can check?

**Comment by SimonBrandner** [comment] 2021-08-30 13:15
I can't repro on a Windows 10 laptop either. Could you please try re-installing Element desktop and testing this then?

**Comment by besendorf** [comment] 2021-08-30 13:16
> 
> 
> I can't repro on a Windows 10 laptop either. Could you please try re-installing Element desktop and testing this then?

I already tried this last week but will do again and report back.

**Comment by SimonBrandner** [comment] 2021-08-30 13:17
> I already tried this last week but will do again and report back.

It might also be worth checking all Element directories were deleted, though this feels like something very weird is going on and I don't think it is necessarily caused by Element

**Comment by besendorf** [comment] 2021-08-30 13:22
> 
> 
> > I already tried this last week but will do again and report back.
> 
> It might also be worth checking all Element directories were deleted, though this feels like something very weird is going on and I don't think it is necessarily caused by Element

Still same issue. I also deleted all files in %appdata%.

![grafik](https://user-images.githubusercontent.com/26350155/131345795-739484da-67e8-40bb-91d2-4d404d504007.png)

**Comment by SimonBrandner** [comment] 2021-08-30 13:28
Ok, could you please try hitting `Ctrl+Shift+I` to see if there are any errors in the console

**Comment by besendorf** [comment] 2021-08-30 13:31
> 
> 
> Ok, could you please try hitting `Ctrl+Shift+I` to see if there are any errors in the console

![grafik](https://user-images.githubusercontent.com/26350155/131347096-b5e8eabf-3258-4ada-8b41-c23d0be55d3e.png)

**Comment by SimonBrandner** [comment] 2021-08-30 13:59
Ok, this seems to be a duplicate of https://github.com/vector-im/element-web/issues/18248, so let's close this in favour of that and concentrate on that issue

**Closed by SimonBrandner** 2021-08-30 13:59 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, S-Critical, A-Electron
