### ISSUE TITLE
Ability to temporarily mute notifications for a room.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17710] opened 2021-06-20 13:29 UTC
I can't believe we haven't got an issue for this, but I can't find one.

We should have a "suppress notifications from this room for the next hour/day/month/year" feature, like WhatsApp's.

**Comment by t3chguy** [comment] 2021-06-20 13:33
This sounds more like a spec issue given its unlikely web will be alive at the conclusion of that period and disabling push rules temporarily thus should be done by the server.

**Comment by ShadowJonathan** [comment] 2021-06-20 16:18
For reference, Telegram and Discord allow this as well (mute for X time).

I'd argue that an MSC that can "suppress/have a push rule until time stamp" would be the best way to handle this.

**Comment by aaronraimist** [comment] 2021-06-21 17:13
Duplicate of https://github.com/vector-im/element-web/issues/3569

**Closed by aaronraimist** 2021-06-21 17:13 UTC
Labels: T-Enhancement, X-Spec-Changes
