### ISSUE TITLE
Search error leads to unbreakable loop

### ISSUE THREAD

**Issue by zzottel** [vector-im/element-web#3936] opened 2017-05-17 10:52 UTC
When I'm searching for "boot" in the room #archlinux:matrix.org on my HS with Riot Web, I first get a result. If I then scroll up, I get the following dialog box:
![2017-05-17 12_49_38-riot](https://cloud.githubusercontent.com/assets/1236369/26150611/69167786-3aff-11e7-8ac8-dc7b3499ad46.png)

Riot refreshes itself several times a second. Clicking on OK or the X doesn't help, nor does a reload of Riot. Only taking away the path (room) from the URL stops the loop.

Synapse logs the following every time Riot refreshes:
`2017-05-17 12:27:15,409 - synapse.http.server - 123 - INFO - POST-1824240- <XForwardedForRequest at 0x7f0bccdf1fc8 method=POST uri=/_matrix/client/r0/search?next_batch=YWxsCgoxNDgzNDcwODY4NzA0LDI0MDkwMg&access_token=<redacted> clientproto=HTTP/1.1 site=8008> SynapseError: 404 - No row found`

Riot Web version: 0.9.9, self-hosted
Synapse version: 0.20.0

**Comment by lampholder** [comment] 2017-05-22 15:27
Testing this on 0.9.10 on /app I couldn't reproduce the problem - @zzottel are you still seeing this?

**Comment by zzottel** [comment] 2017-05-23 08:06
Yes, still the same with Riot v0.9.10 (and Synapse 0.21.0, both self-hosted).

**Comment by lampholder** [comment] 2017-07-21 12:06
Still can't reproduce this :\ I wonder if it is some corruption that has occurred in your homeserver? Or a problem with an event that occurred before I joined #archlinux:matrix.org?

**Comment by krombel** [comment] 2018-02-05 16:19
I got hit by that bug today as well.
request: `_matrix/client/r0/search?next_batch=YWxsCgoxNDk4NjU0NTIzMjYxLDI4MDQwOA`
response: 404
```
{"errcode":"M_UNKNOWN","error":"No row found"}
```
This is a snippet of the logs shortly before I had to restart riot.
```
2018-02-05T15:08:46.597Z E Search failed: M_UNKNOWN: No row found
2018-02-05T15:08:46.609Z I Starting load of AsyncWrapper for modal
2018-02-05T15:08:46.623Z I AsyncWrapper load completed with ErrorDialog
2018-02-05T15:08:46.662Z W Join message has no target! -- undefined
2018-02-05T15:08:46.688Z W Join message has no target! -- undefined
2018-02-05T15:08:46.747Z W Join message has no target! -- undefined
2018-02-05T15:08:46.779Z W Join message has no target! -- undefined
2018-02-05T15:08:46.898Z E Search failed: M_UNKNOWN: No row found
2018-02-05T15:08:46.910Z I Starting load of AsyncWrapper for modal
2018-02-05T15:08:46.923Z I AsyncWrapper load completed with ErrorDialog
2018-02-05T15:08:47.309Z W Join message has no target! -- undefined
2018-02-05T15:08:47.364Z W Join message has no target! -- undefined
2018-02-05T15:08:47.568Z W Join message has no target! -- undefined
2018-02-05T15:08:47.594Z W Join message has no target! -- undefined
```
although I do not think that "Join message has no target" is related as they appeared before the loop as well.
After disconnected the client (and stopped the requests this way) I could close 100s of ErrorDialogs.

It might be related to the fact that I was scrolling up which triggers a loop of
- a pagination request
- request failes
- no results get added but the "is searching"-state gets reset
- Client has no events on top so pagination should be triggered

My version: Current develop of synapse and riot

**Comment by yannicka** [comment] 2020-05-21 09:55
Do you still have the problem? I can't reproduce it either (Riot Web 1.6.1 or Riot Desktop 1.6.0).

**Comment by kittykat** [comment] 2021-09-03 10:07
Closing as this issue cannot be reproduced any more. Please reopen or comment with @kittykat asking to reopen if this exact issue still persists for anyone.

**Closed by kittykat** 2021-09-03 10:07 UTC
Labels: T-Defect, X-Cannot-Reproduce
