### ISSUE TITLE
Plus sign on the People tab on the side of the app is wonky when the window is squashed 

### ISSUE THREAD

**Issue by nemkicsiaron** [vector-im/element-web#19154] opened 2021-09-24 07:00 UTC
### Steps to reproduce

1. On app Startup, push the window until the stack of people you DM'd loses the names and becomes just their pictures.
2. Nothing else

### What did you expect?
A plus sign to show up similar to the icon of my contacts. Like on Android.

### What happened?
The plus sign appeared but its background is distorted.
![image](https://user-images.githubusercontent.com/64364380/134631818-6960747d-59e8-43e7-b09a-6ac3ee8a2cae.png)

### Operating system

Windows 10 Pro 21H1

### Application version

Element version: 1.8.5, Olm version: 3.2.3

### How did you install the app?

From https://element.io/get-started

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment] 2021-09-24 15:32
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/17068

**Closed by SimonBrandner** 2021-09-24 15:32 UTC
Labels: T-Defect, S-Tolerable, A-Room-List, O-Frequent, good first issue
