### ISSUE TITLE
Add Room to Space quickly

### ISSUE THREAD

**Issue by dzg** [vector-im/element-web#20657] opened 2022-01-20 19:18 UTC
#### What would you like to do?
Quickly add a room to another space 
#### Why would you like to do it?
Only way I know to do this is go the target space, find 'add existing room' 
#### How would you like to achieve it?
Via context menu ... something like "Add to Space > [submenu list of Spaces]"
![image](https://user-images.githubusercontent.com/466557/150406671-24b92a0c-3791-47b7-85f0-ca150d660ad1.png)

**Comment by SimonBrandner** [comment] 2022-01-20 19:26
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/17028

**Closed by SimonBrandner** 2022-01-20 19:26 UTC
Labels: T-Enhancement
