### ISSUE TITLE
Message which was retried from element-android shows authenticity can't be guaranteed on this device in element-web

### ISSUE THREAD

**Issue by barathrm** [vector-im/element-web#16023] opened 2020-12-22 17:54 UTC
### Description

One of my own messages in an e2ee DM room has a gray shield, even though it's from a cross-verified device.

The message(s) showing with a gray shield on an element-web session were sent from element-android 1.0.11, however only after retrying a few times manually after they'd failed to send automatically.

Related to https://github.com/vector-im/element-web/issues/14323 ?

### Version information

element-web is the desktop version.
element-android is version 1.0.11 from f-droid.

For the desktop app:

- **OS**: linux
- **Version**: 1.7.16

**Comment by jryans** [comment] 2021-01-14 15:19
Hmm, this doesn't really seem expected to me... @uhoreg, would you expect gray shields when retrying messages...?

**Comment by uhoreg** [comment] 2021-01-14 16:26
Retrying shouldn't affect anything.  My wild guess would be that if you had to retry several times, it's an indication that the server was having issues, so it could be that there were delays in sending the key over to your web device, at which point the web device tried to re-fetch the key from your Android device, which can trigger the grey shield.  The next release should have https://github.com/matrix-org/matrix-js-sdk/pull/1571, which may help this issue, in that when the original key finally does come in, it will mark it as trusted.

**Comment by kittykat** [comment] 2021-12-21 17:08
I'm going to close this issue for now as we can't reproduce it and don't have enough information to debug it any further. Please attach a rageshake and comment with @kittykat if you experience it again and I will re-open the issue.

**Closed by kittykat** 2021-12-21 17:08 UTC
Labels: T-Defect, P2, S-Minor, A-E2EE, X-Needs-Community-Testing
