### ISSUE TITLE
.well-known is not used at registration

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#15568] opened 2020-10-26 21:40 UTC
Element doesn't do .well-known discovery when entering a custom server name at registration.
This can seriously affect FTUE. It would be good if Element did the discovery everytime, so the users could extract the server name from the Matrix ID (the part after the `:`), and not have to think about the two different addresses (the one in the ID, and the real address). 
E.g. the grin.hu server is located at matrix.grin.hu
It is configured at login from .well-known, but not at registration.
![kép](https://user-images.githubusercontent.com/26059643/97231337-42baaa80-17d3-11eb-8c59-85bb0eb866c6.png)

**Comment by t3chguy** [comment] 2020-10-26 21:47
The Matrix spec only defines the well-known resolution from an MXID, during registration the user doesn't enter an MXID.
The same applies to login, if you enter a url manually then it will be used verbatim.

**Comment by notramo** [comment] 2020-10-26 21:53
Do you think it is good for FTUE?
So I have to explain to my non-techie friends, that:
"Matrix is based on HTTPS. Nevermind if you don't know what it is, simply remember you have to enter it as a prefix before the second half of the Matrix ID. Like in an URL. But this is not a webpage that you can visit, you enter this address into https://app.element.io Also, the actual address of the Matrix server is not the same as it is in your Matrix ID, it is different, so when you enter the address, you have to use https://matrix.grin.hu, but when you give your Matrix ID to someone, it ends simply with :grin.hu"

**Comment by t3chguy** [comment] 2020-10-26 21:54
I don't. But it's also an issue for the Matrix spec rather than Element.

**Comment by turt2live** [comment] 2020-10-26 22:12
Duplicate of https://github.com/vector-im/element-web/issues/8310

**Closed by turt2live** 2020-10-26 22:12 UTC
