### ISSUE TITLE
direct chat missing in spaces on Element desktop but not Element Android

### ISSUE THREAD

**Issue by Thatoo** [vector-im/element-web#17599] opened 2021-06-09 07:18 UTC
I have created a Space where I invited friends and family. All rooms appears both in Element Desktop and Android and all direct chat are listed in Element Android but some are missing in Element Desktop (Debian buster).
They are invited but they don't appear in the list of direct chat in Element Desktop. They do appear in Element Android in the same "space".

**Comment by t3chguy** [comment] 2021-06-09 07:19
Please fill the issue template. Things like version are important.

**Comment by Thatoo** [comment] 2021-06-09 07:24
### Version information

- **Platform**:  desktop
- **OS**: Debian Buster
- **Version**: 1.7.30

For Android
- **Version**: 1.1.8

**Comment by SimonBrandner** [comment] 2021-06-09 14:15
Duplicate of [#17291](https://github.com/vector-im/element-web/issues/17291)

**Closed by SimonBrandner** 2021-06-09 14:15 UTC
Labels: T-Defect
