### ISSUE TITLE
Make controls for direct call screen sharing, rather than have the feature hidden

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#16610] opened 2021-03-05 11:51 UTC
### Description

> Screen Share is still an Easter Egg are you planning on changing that soon? If yes, it currently does not allow for switching back and forth, so you need to call again and your own stream blocks a corner of the screen sharing.

**Comment by SimonBrandner** [comment] 2021-03-05 11:54
Duplicate of [#12652](https://github.com/vector-im/element-web/issues/12652)

**Closed by SimonBrandner** 2021-03-05 11:54 UTC
Labels: A-VoIP, ui/ux
