### ISSUE TITLE
Message is stuck at bottom of message list 

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#20462] opened 2022-01-10 14:57 UTC
### Steps to reproduce

(This is just a repeat of a comment I made on a closed issue concerning the same problem.)

I too have this problem still. I have one message stuck from several months ago. I have second stuck from a few weeks ago. My business partner has one stuck message in the room we share. The message that is stuck for him is not the same one that is stuck for me.

My Android Element client shows one stuck message. My Windows desktop Element client shows two stuck messages. The one stuck message on Android is neither of the stuck messages on the desktop.

This is one of our main complaints. I'm trying to hold on. He wants to return to Telegram. We like the encryption of Element, but the ergonomics are mediocre to poor. He's not a fan. (The other showstopper for us is the lack of correct/timely notifications. This is fairly simple to do. If the devs here have any doubt about how to do this correctly, do what Tg does; it works. We've seen enough falsely positive notifications from Element to screw up three time-sensitive financial transactions. This is the point at which a user will typically trade back the improved security for less security, in favor of reliable, timely messages that have been acked and do not need to be second guessed about whether they were really acked. In such cases the improved encryption is not as valuable.)

### Outcome

No stuck messages

### Operating system

Windows 10

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-01-10 14:59
As per that closed issue, this is a Synapse bug in not sending the message down /sync as is required by the spec causing the client to get confused.

**Comment by SimonBrandner** [comment] 2022-01-10 15:13
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/17966

**Closed by SimonBrandner** 2022-01-10 15:13 UTC
Labels: T-Defect, Z-Backend, Z-Synapse
