### ISSUE TITLE
Allow Guest Users to join PM rooms

### ISSUE THREAD

**Issue by LookitheFirst** [vector-im/element-web#14932] opened 2020-08-11 14:28 UTC
**Is your suggestion related to a problem? Please describe.**
Right now, it is impossible to initiate a PM chat room with a guest user, when the guest wants to accept the invitation to join, they get asked to create an account.

**Describe the solution you'd like**
A guest user should be able to initiate a PM chat room with other people and accept an invitation to such a room

**Describe alternatives you've considered**

**Additional context**
[I've asked for this feature in the Synapse Repo](https://github.com/matrix-org/synapse/issues/7918), the answer was that Synapse supports it, but it's not enabled in Element

**Comment by t3chguy** [comment] 2020-08-12 09:33
Duplicate of https://github.com/vector-im/element-web/issues/9264

**Closed by t3chguy** 2020-08-12 09:33 UTC
Labels: suggestion
