### ISSUE TITLE
Completely frozen with 100% CPU

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21184] opened 2022-02-23 17:33 UTC
### Steps to reproduce

1. switch space by clicking the unread indicator in the space bar
2. #20425 happens
3. click again to switch to the space I actually wanted
4. stuck

I'll try to submit logs when I can figure out how...

#### What did you expect?
no crash :(

#### What happened instead?
GUI is frozen, 100% CPU.
Upon closing and restart, the GUI is stuck here, no buttons work, not even Ctrl+Shift+I:
![image](https://user-images.githubusercontent.com/2803622/155374506-e3f1acce-311b-4640-b12b-0b863978c295.png)

### Operating system

arch

### Application version

nightly 2022022301

### How did you install the app?

aur/element-desktop-nightly-bin

### Homeserver

1.52

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2022-02-23 17:35
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/21127

**Closed by SimonBrandner** 2022-02-23 17:35 UTC
Labels: T-Defect

**Comment by HarHarLinks** [comment] 2022-02-23 17:37
@SimonBrandner I'm not sure it is, because mine does not unfreeze at all. I think I have also experienced #21127 last week, but as that issue title says it unfroze after a couple seconds. My current issue is not unfreezing at all.
