### ISSUE TITLE
Stuck unread status on a room

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#21614] opened 2022-03-31 08:17 UTC
### Steps to reproduce

I opened a room with an unread message, scrolled around for a bit, but the unread dot was not dismissed.

#### What did you expect?

I opened a room with a new message. I expect the unread dot to be dismissed and the room to be marked as read.

#### What happened instead?

The room was not marked as read.

![image](https://user-images.githubusercontent.com/463342/161010061-d948bfd0-8a41-4682-9241-fdcec35fc9e8.png)

### Operating system

Arch Linux

### Application version

Element version: 1.10.8 Olm version: 3.2.8

### How did you install the app?

Arch Linux repository

### Homeserver

termina.org.uk, Synapse 1.55.0

### Will you send logs?

Yes

**Comment by dkasak** [comment] 2022-03-31 08:42
And now the notification changed to a red one after I opened a thread in the room where I was highlighted (well, replied to). So I'm sending another log.

**Comment by dkasak** [comment] 2022-03-31 09:02
This seems like a thread bug. The dot/badge now disappeared after someone sent a new message and I viewed it, but opening the mentioned thread and scrolling in it first makes the white dot reappear and, if I scroll further, the red badge. I will then be unable to dismiss the dot/badge until someone sends a new message into the room and I view it.

**Comment by gsouquet** [comment] 2022-03-31 14:42
Looks like it's been already reported

Duplicate of https://github.com/vector-im/element-web/issues/21114
Duplicate of https://github.com/vector-im/element-web/issues/21413

**Closed by gsouquet** 2022-03-31 14:42 UTC
Labels: T-Defect
