### ISSUE TITLE
Badge on Windows task bar entry

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#22909] opened 2022-07-21 13:41 UTC
#### What would you like to do?
Element should probably have badge on the task bar entry (as opposed to the system tray icon) which appears to be a thing that is possible in Windows now (thunderbird does it).

#### Why would you like to do it?
General platform consistency

#### How would you like to achieve it?
🤷

**Comment by t3chguy** [comment] 2022-07-21 13:46
Duplicate of #14033

**Closed** 2022-07-21 13:46 UTC
Labels: Z-Platform-Specific, A-Electron, T-Enhancement
