### ISSUE TITLE
Better search - filter for files, date range, etc.

### ISSUE THREAD

**Issue by lukaszpolowczyk** [vector-im/element-web#18320] opened 2021-08-01 17:00 UTC
It is useful to filter the files, people, dates, room type, etc. that are in Slack.

The advantages of improving the search engine are rather obvious? 

![Zrzut ekranu z 01-08-2021 18_56_18](https://user-images.githubusercontent.com/16800535/127779213-5ab5b14b-a28b-4278-8548-9a1d44e22783.png)
![Zrzut ekranu z 01-08-2021 18_56_31](https://user-images.githubusercontent.com/16800535/127779214-cc1971ca-a16c-48be-83cb-05613a7968d3.png)

**Comment by SimonBrandner** [comment] 2021-08-01 17:09
Duplicate of https://github.com/vector-im/element-web/issues/16172 and https://github.com/vector-im/element-web/issues/16253 and possibly others. I am not completely sure those issues request exactly what you are after though it would be better to mention those things there rather than having too many issues

**Closed by SimonBrandner** 2021-08-01 17:09 UTC
Labels: T-Enhancement
