### ISSUE TITLE
Transparent user avatars non-opaquely overlap in read receipts

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#26163] opened 2023-09-13 17:29 UTC
### Steps to reproduce

1. Send a message with an opaque avatar
2. Have a non-opaque avatar user read it
3. Observe read receipts from a third account

#### What did you expect?

The transparent avatar should cut into the opaque avatar, not bleed through. I believe this was the case at some point in the past.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/1837ff10-8603-43d8-913c-7042d3b76c0b)

There is a subtle outline on the transparent user's avatar, and the opaque avatar is bleeding through.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023091301 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by germain-gg** [comment] 2023-09-20 13:40
Closing and marking as a duplicate of https://github.com/vector-im/element-web/issues/26159 to have one thread on conversation

**Closed** 2023-09-20 13:42 UTC
Labels: T-Defect, X-Regression, S-Tolerable, A-Read-Receipts, A-Avatar, O-Occasional

**Comment by germain-gg** [comment] 2023-09-20 14:33
Yes that is true, but whatever we settle on will apply to both issues. I've also commented on the counterpart to explain that we have to take in consideration the issue here.
I'm not overly inclined to keep the two open as this will split the discussion needlessly.
