### ISSUE TITLE
Allow having People and Rooms in the same group in sidebar

### ISSUE THREAD

**Issue by abryzak** [vector-im/element-web#18936] opened 2021-09-07 03:14 UTC
#### What would you like to do?

In general when using a messenger, I don't make much distinction between group conversations and one-on-one conversations. It would be useful to be able to have both the People and Rooms sections in the sidebar in one section that contains both.

#### Why would you like to do it?

Currently the People section is before the Rooms sections; if the People section is showing all entries, the Rooms section is out of view and requires a lot of scrolling or collapsing of the People section to reach. Having both in the same section would allow me to have the most recent activity, regardless of if it's a direct message or a group message to always be at the top of the list below the favorites section, which would be more convenient.

#### How would you like to achieve it?

An option in the Appearance settings or in the triple dot menu for the People and Rooms sections in the sidebar would be fine.

**Comment by t3chguy** [comment] 2021-09-07 09:35
Duplicate of https://github.com/vector-im/element-web/issues/15657

**Closed by t3chguy** 2021-09-07 09:35 UTC
Labels: T-Enhancement
