### ISSUE TITLE
QR code for adding a new owned device

### ISSUE THREAD

**Issue by grinapo** [vector-im/element-web#16240] opened 2021-01-22 11:19 UTC
**Is your suggestion related to a problem? Please describe.**
Adding a new (mobile) device now require some fiddling: user have to re-enter homeserver, account name, and password at least, gets a question about cross-signing and possibly even more questions which are proper in the general case but completely unnecessary when we _do_ know that this is an additional device for an already established account.

**Describe the solution you'd like**
A QR code could contain all the required information (hs, account_name, a flag for adding_new_device_login), so the user only have to provide a password [or other verification scheme]. 
Preferably it would work at in-app login (element-mobile versions) instead of giving hs/credentials. 

(It may try to open the app as well from the generic QR reader.)

**Comment by t3chguy** [comment] 2021-01-22 12:11
Duplicate of https://github.com/vector-im/element-web/issues/11416

**Closed by t3chguy** 2021-01-22 12:11 UTC
Labels: suggestion
