### ISSUE TITLE
Postpone creation of new DM room with user to first message send event by author

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#16031] opened 2020-12-25 09:24 UTC
**Is your suggestion related to a problem? Please describe.**
1. Very often people do a missclicks on "Direct message" link in user profile panel, that immediately creates the new DM room with that user, user got the invite, accept it, and wait for the real message, or ask "What do you want to ask?" in this room. But the initiator simply do the missclick (or try to understand what this link is doing) and can't cancel the process already.

2. Other problematic situation is when user really plan to send the new private message to other user, but not yet compose the full text. For start composing (which can took a long time) the direct message text to targeted user, author needs to create a DM room preliminarily (for got access to private message composer interface), and the recipient will immediately receive invite to this room with no messages, and will be confused "what he want to tell me?", starts asking questions "what do you want to ask?", "hey, did you hear me?", etc.

**Describe the solution you'd like**
Good solution for both described problems can be postponing creation of DM room to first message send event. This is how most of other messengers works now (Telegram, WhatsApp, Viber, etc): before first DM message was send, the recipient didn't receive any invites or notifications that "someone maybe want to ask you something in DM, start preparing for this!".

Will be good to have same behavior on Element's too, for not spam of users with invites to empty DM rooms without messages, that confusing people.

If users will want to simply "find each other" using DM, they simply can post "hi, here am I" in first message.

And implementing https://github.com/vector-im/element-web/issues/4686 together with this feature will make the whole room invites more understandable!

**Comment by t3chguy** [comment] 2020-12-29 13:10
Duplicate of https://github.com/vector-im/element-web/issues/14736

**Closed by t3chguy** 2020-12-29 13:10 UTC
Labels: suggestion
