### ISSUE TITLE
`libnotify` warnings on Debian Buster make app unusable (need to restart)

### ISSUE THREAD

**Issue by shirishag75** [vector-im/element-web#8279] opened 2019-01-27 22:59 UTC
Dear all, 

Thank you for maintaining riot-web. I was trying it out on debian-buster and got the following - 

```
$ riot-web
Starting auto update with base URL: https://riot.im/download/desktop/update/
Auto update not supported on this platform

(riot-web:30233): libnotify-WARNING **: 04:14:00.416: Failed to connect to proxy

(riot-web:30233): libnotify-WARNING **: 04:14:25.442: Failed to connect to proxy

(riot-web:30233): libnotify-WARNING **: 04:14:35.268: Failed to connect to proxy

(riot-web:30233): libnotify-WARNING **: 04:15:35.269: Failed to connect to proxy

(riot-web:30233): libnotify-WARNING **: 04:16:00.295: Failed to connect to proxy
^C^C
```

Could somebody fix this, thank you. 

```
Package: riot-web
Version: 0.17.9
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.19.0-1-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages riot-web depends on:
ii  gconf-service     3.2.6-5
ii  gconf2            3.2.6-5
ii  libappindicator1  0.4.92-7
ii  libnotify4        0.7.7-4
ii  libnss3           2:3.41-1
ii  libxss1           1:1.2.3-1
ii  libxtst6          2:1.2.3-1

riot-web recommends no packages.

riot-web suggests no packages.

-- no debconf information
```

**Comment by shirishag75** [comment] 2019-02-26 21:32
It's one month and still no resolution. In fact, it has become much more painful to have a conversation since 1.0.1 

```
Subject: libnotify makes it impossible to have a conversation
Package: riot-web
Version: 1.0.1
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.19.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages riot-web depends on:
ii  gconf-service     3.2.6-5
ii  gconf2            3.2.6-5
ii  libappindicator1  0.4.92-7
ii  libnotify4        0.7.7-4
ii  libnss3           2:3.42.1-1
ii  libxss1           1:1.2.3-1
ii  libxtst6          2:1.2.3-1

riot-web recommends no packages.

riot-web suggests no packages.

-- no debconf information

```

**Comment by jryans** [comment] 2019-02-27 10:12
Can you explain how it is "painful"? In the first comment, it appeared that you receive some warning in the terminal. Is anything else happening?

**Comment by shirishag75** [comment] 2019-02-27 12:38
It's painful because I can't use riot-web after that. I have to shut down the app. Re-start it , talk for couple of minutes , again get the error and can no longer talk. The cycle just goes on repeating :(

**Comment by jryans** [comment] 2019-02-27 12:46
Do you know of a live install image for that Debian release? I found https://www.debian.org/CD/live/, but it seems to only have the stable release.

**Comment by shirishag75** [comment] 2019-02-27 13:49
We do have weekly testing live iso's but I couldn't tell if they are any good or not. See https://get.debian.org/cdimage/unofficial/non-free/images-including-firmware/weekly-live-builds/amd64/iso-hybrid/ 

there is also https://get.debian.org/cdimage/unofficial/non-free/images-including-firmware/buster_di_alpha5+nonfree/amd64/iso-cd/firmware-buster-DI-alpha5-amd64-netinst.iso

There is an errata published, please look into that https://www.debian.org/devel/debian-installer/errata

Some notes - 

1. The weekly-build is more recent than alpha 5 but no guarantees . I have given for 64-bit machines, if you are looking for 32-bit then just replace amd64 with i386 and you should be able to use the same. 

2. The second one I have shared is just the netinstall . If you want or have the bandwidth you could also look at https://get.debian.org/cdimage/unofficial/non-free/images-including-firmware/buster_di_alpha5+nonfree/amd64/iso-dvd/firmware-buster-DI-alpha5-amd64-DVD-1.iso 

Let me know if you get into any issues with either.  There are bit-torrent releases as well as you could use wget or some sort of download manager if you on some non-linux platform.

**Comment by shirishag75** [comment] 2019-03-07 04:55
This has got fixed with the newest release i.e. riot-web 1.0.3 -

**Comment by shirishag75** [comment] 2019-03-07 05:48
I thought it got fixed but no, it's still there :(

```
$ riot-web
Starting auto update with base URL: https://riot.im/download/desktop/update/
Auto update not supported on this platform

(riot-web:22338): libnotify-WARNING **: 10:55:50.547: Failed to connect to proxy

(riot-web:22338): libnotify-WARNING **: 10:56:15.553: Failed to connect to proxy

(riot-web:22338): libnotify-WARNING **: 10:56:25.547: Failed to connect to proxy

(riot-web:22338): libnotify-WARNING **: 10:58:47.974: Failed to connect to proxy

(riot-web:22338): libnotify-WARNING **: 10:59:12.981: Failed to connect to proxy

(riot-web:22338): libnotify-WARNING **: 10:59:22.554: Failed to connect to proxy

```

**Comment by jryans** [comment] 2019-03-07 13:02
Looks like the list in https://get.debian.org/cdimage/unofficial/non-free/images-including-firmware/weekly-live-builds/amd64/iso-hybrid/ has different variants for Gnome, KDE, etc. Which one would be closest to what you are using?

**Comment by shirishag75** [comment] 2019-03-07 13:08
You could either use mate or use lxqt . I interchangeably use both the desktops. The behaviour I shared is the same on both the same desktops.

**Comment by jryans** [comment] 2019-03-07 16:27
I tried testing with `debian-live-testing-amd64-mate+nonfree.iso`. Riot starts successfully, and I don't receive any error like you are encountering.

Can you think of any other steps to reproduce the issue?

**Comment by shirishag75** [comment] 2019-03-07 16:36
I am not saying it doesn't start. I am saying it starts giving those libnotify warnings.  I tried to see why I need libnotify4 and it says - 
```

$ aptitude why libnotify4
i   riot-web Depends libnotify4
```

**Comment by jryans** [comment] 2019-03-07 17:16
I did not receive any warnings from libnotify when trying to duplicate your setup, so for the moment it seems unclear if this is an issue for all debian buster users, or something specific to your systems.

The libnotify dependency comes from Electron's notification APIs.

It seems like similar issues have been opened for at least other Electron-based apps:

https://github.com/meetfranz/franz/issues/592

This suggests to me that it's an issue either in Electron or in the libnotify supplied by the distribution. I don't believe there's much that Riot can do about this, but please let us know if there is.

**Comment by shirishag75** [comment] 2019-03-21 15:46
at least for the moment, with the new release the issue has stopped . 

@jryans the only fix they seemed to have done in this release is at https://github.com/vector-im/riot-web/issues/9205 from what I could gather. Maybe that has something to with it. 

/me clueless.

**Comment by se17p** [comment] 2021-01-15 14:13
I just tested and disabling "desktop notifications for this sessions" stops freezing (also with audible notifications enabled).

**Comment by se17p** [comment] 2021-01-15 14:26
As a side note my system also has problems with notifications from some other apps (e.g. network manager) which may have been caused by trying KDE/wayland.

IMO moving notifications to another thread would be a good idea, because now it looks like it causes also some internal problems: 
```
[53135:0115/150826.622895:ERROR:libnotify_notification.cc(51)] notify_notification_show: domain=322 code=24 message="Error calling StartServiceByName for org.freedesktop.Notifications: Timeout was reached"
[53135:0115/150851.662512:INFO:CONSOLE(2)] "/sync error %s ConnectionError: request failed: ETIMEDOUT", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/150851.662571:INFO:CONSOLE(2)] "ConnectionError: request failed: ETIMEDOUT", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/150851.662620:INFO:CONSOLE(2)] "Number of consecutive failed sync requests: 1", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/150851.662665:INFO:CONSOLE(2)] "Starting keep-alive", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/150851.662714:INFO:CONSOLE(2)] "MatrixClient sync state => %s RECONNECTING", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/150856.457561:INFO:CONSOLE(2)] "Presence: %s unavailable", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/151009.899042:INFO:CONSOLE(2)] "Presence: %s online", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/151011.279134:INFO:CONSOLE(2)] "Starting load of AsyncWrapper for modal", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/151011.305435:INFO:CONSOLE(2)] "Returning cached capabilities", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/151017.439477:INFO:CONSOLE(2)] "/sync error %s ConnectionError: request failed: ETIMEDOUT", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/151017.439563:INFO:CONSOLE(2)] "ConnectionError: request failed: ETIMEDOUT", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/151017.439627:INFO:CONSOLE(2)] "Number of consecutive failed sync requests: 2", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/151017.439667:INFO:CONSOLE(2)] "Starting keep-alive", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/151017.443061:INFO:CONSOLE(2)] "MatrixClient sync state => %s RECONNECTING", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
[53135:0115/151025.497093:INFO:CONSOLE(2)] "MatrixClient sync state => %s SYNCING", source: vector://vector/webapp/bundles/*****/vendors~init.js (2)
```

**Comment by jryans** [comment] 2021-01-15 17:15
Unfortunately, Element itself can't really do anything about how `libnotify` is used. It's managed by Electron / Chromium.

**Comment by shirishag75** [comment] 2021-02-02 01:24
@jryans do you know if the specific issue has been relayed to the libnotify maintainers. If yes, is there some bug/ticket we could look into and associate with. Some way to track it.  After a bit of search, did find a bunch of tickets and where the release can be tracked but no sure way to figure things out. 

https://gitlab.gnome.org/GNOME/libnotify

**Comment by jryans** [comment] 2021-02-04 12:11
I do not know anything more about this topic than what's contained in this issue already.

**Comment by MadLittleMods** [comment] 2023-02-17 23:09
@shirishag75 @se17p Is this still reproducible?

**Comment by MadLittleMods** [comment] 2023-02-17 23:15
Closing in favor of https://github.com/vector-im/element-web/issues/23252 which looks like to be a new report of this

**Closed by MadLittleMods** 2023-02-17 23:15 UTC
Labels: T-Defect, Z-Platform-Specific, S-Major, A-Notifications, Z-Upstream, O-Uncommon
