### ISSUE TITLE
Backslash in markdown mode removes new line

### ISSUE THREAD

**Issue by Destroyer** [vector-im/element-web#18828] opened 2021-08-28 16:13 UTC
### Steps to reproduce

1. Create a message like
```
hello
- world
```
2. It is converted into markdown
3. Avoid converting the dash into markdown list by using backslash
```
hello
\- world
```
4. The dash is now treated as a symbol, however line break is removed 

### What happened?

Backslash that should be escaping dash as an active markdown character removes line break as well
![obrazek](https://user-images.githubusercontent.com/289988/131224106-5ed2a406-aa76-485d-842d-79789ab6c7e9.png)

### What did you expect?

New line should still be applied. 

The only workaround is to use /plain or /html mode which is annoying because you always have to end up editing the message 
if you don't realize this quirk

### Operating system

Windows

### Application version

verze Element: 1.8.1 Verze Olm: 3.2.3

### Have you submitted a rageshake?

No

**Comment by ShadowJonathan** [comment] 2021-08-28 16:33
Duplicate of #18827

**Closed** 2021-08-28 16:34 UTC
Labels: T-Defect
