### ISSUE TITLE
User-selectable custom background

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16662] opened 2021-03-11 08:34 UTC
Can we allow the user to upload a .jpg or .png or some other image-format file to be used as a background?   Telegram has this feature.

**Comment by SimonBrandner** [comment] 2021-03-11 08:39
Duplicate of [#6356](https://github.com/vector-im/element-web/issues/6356)

**Comment by t3chguy** [comment] 2021-03-11 08:39
Duplicate of ... - @SimonBrandner beat me to it :D

**Closed by SimonBrandner** 2021-03-11 08:39 UTC
Labels: T-Enhancement
