### ISSUE TITLE
Keep the "signing in" loading in the same place 

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21945] opened 2022-04-27 04:46 UTC
### Your use case

When the user signs in for the first time the button disappears and the "Signing in..." copy moves to below the SSO. It can be jarring because it moves the page around.

| Before clicking sign in | After clicking sign in | 
|---|---|
| <img width="403" alt="Screenshot 2022-04-26 at 21 45 18" src="https://user-images.githubusercontent.com/89144281/165442481-8173e5cb-4776-4ea7-834c-7df365fc14c3.png"> |<img width="409" alt="Screenshot 2022-04-26 at 21 45 24" src="https://user-images.githubusercontent.com/89144281/165442479-a3ce547e-2f23-4d5e-a13b-d5992f310e0f.png"> |

**Comment by turt2live** [comment] 2022-05-07 04:05
Duplicate of https://github.com/vector-im/element-web/issues/21545

**Closed by turt2live** 2022-05-07 04:05 UTC
Labels: A-Login, T-Enhancement, A-Appearance, Z-WTF, Team: Delight, Z-NewUserJourney
