### ISSUE TITLE
if the user we are calling is already busy in another call, we didn't get any feedback or error message.

### ISSUE THREAD

**Issue by nashi24** [vector-im/element-web#15907] opened 2020-12-07 13:22 UTC
if a user is trying to call some user who is already busy in some another call, user should get some response or busy status in some form.

**Comment by t3chguy** [comment] 2020-12-07 13:26
Duplicate of your own issue?

https://github.com/vector-im/element-web/issues/15904

**Comment by nashi24** [comment] 2020-12-07 13:31
I have closed that one, i need to know is there any way to check if a user is already busy in some another call?

**Comment by nashi24** [comment] 2020-12-07 13:32
or we don't have any feature to check if a user is already in call or not?

**Comment by t3chguy** [comment] 2020-12-07 13:36
I don't know whether we do, given it'd be a privacy leak to know whether a user is in a call at any given time without their explicit consent to tell you that

**Comment by nashi24** [comment] 2020-12-07 13:54
@t3chguy Thanks

**Comment by hex-m** [comment] 2021-09-24 08:29
> it'd be a privacy leak to know whether a user is in a call

While this is true and we should strive to solve this as good as possible, this has been the default for decades in the phone system.

As long as the receiver gets notified that she got "pinged" I think it's fine. If her client informs her about a high number of incoming calls she could block the caller.

Also, there should be a way to generally set the status to "busy" which should be indistinguishable from an ongoing call from the caller pov. This make it related to [presence](https://github.com/vector-im/element-web/issues/8029).

**Comment by t3chguy** [comment] 2022-05-23 19:12
Duplicate of https://github.com/vector-im/element-meta/issues/333

**Closed by t3chguy** 2022-05-23 19:12 UTC
Labels: A-VoIP, T-Enhancement, O-Occasional
