### ISSUE TITLE
Why does vector love russia?

### ISSUE THREAD

**Issue by G2G2G2G** [vector-im/element-web#21326] opened 2022-03-05 20:41 UTC
### Steps to reproduce

![image](https://user-images.githubusercontent.com/50514477/156899367-2f658e37-2b85-465a-8764-1aa6b21c8a1d.png)

#### What did you expect?
US flag
#### What happened instead?
My element desktop telling me I should love Russia and not the US

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-03-05 20:54
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19178

**Closed by SimonBrandner** 2022-03-05 20:54 UTC
Labels: T-Defect
