### ISSUE TITLE
Feature Request: Change Microphone Sensibility

### ISSUE THREAD

**Issue by fabianjost** [vector-im/element-web#15534] opened 2020-10-23 07:49 UTC
Hey guys,

we love the element desktop app for Linux and Windows and we use it everyday. Great work! I remember Teamspeak having a setting in their options that allowed me to set up the microphone sensibility. So my friends don't hear the background noises while I was not talking (keyboard typing for example). This would be awesome. Keep up the awesome work.

Best wishes
Fabian

**Comment by SimonBrandner** [comment] 2021-12-05 07:25
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/1673

**Closed by SimonBrandner** 2021-12-05 07:25 UTC
Labels: P2, A-VoIP, T-Enhancement
