### ISSUE TITLE
Replying to a bing should not notify again

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#20510] opened 2022-01-12 14:26 UTC
### Steps to reproduce

1. I am am member of a room where someone previously used `@room` to bing everyone
2. Someone else replies to that message
3. I get notified again, as if a new `@room` bing happened

#### What did you expect?
I expected a reply to a bing not to re-bing me.

#### What happened instead?
I received a notification

### Operating system

Ubuntu 21.10

### Browser information

Firefox 95.0.1 (64-bit)

### URL for webapp

https://develop.element.io

### Application version

Element version: ef9335697e05-react-f81120f35f09-js-4acb98c4963d Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-01-12 14:31
Related https://github.com/vector-im/element-web/issues/5420

**Comment by HarHarLinks** [comment] 2022-01-12 17:18
dupe of https://github.com/vector-im/element-web/issues/20334, https://github.com/vector-im/element-web/issues/7874

solution: https://github.com/matrix-org/matrix-react-sdk/pull/6964

**Comment by gsouquet** [comment] 2022-01-13 08:46
Duplicate of #20334 
Duplicate of #7874

**Closed by gsouquet** 2022-01-13 08:46 UTC
Labels: T-Defect, X-Spec-Changes
