### ISSUE TITLE
Error on old invitation

### ISSUE THREAD

**Issue by fsiegenthaler** [vector-im/element-web#8689] opened 2019-02-15 08:53 UTC
### Description

I have an invitation to my account siegi@matrix.org from group chat SwissNeutral.net #swissneutral:matrix.org and it's an old test when i create my account on matrix.org server with several address mail on the same account. From my memory i've tried to invite myself with a secondary mail address.

I'm already the owner of SwissNeutral.net group and i cannot delete this useless invitation. I think i created an error from server side.

Possibly it's the same error with issue #7384 but i'm not sure.

### Steps to reproduce

When i want to accept or refuse i have this message: 

"You have been invited to join this room by @siegi:matrix.org
Would you like to accept or decline this invitation?"

When i click "Accept" i have this message: "Failed to join room
No known servers" and when i click "Decline" i have this error: Failed to reject invite
No create event in auth events.

And when i want to reject invitation by the side bar of web app Riot i have this message: "Failed to reject invitation
M_FORBIDDEN: No create event in auth events"

Log: not sent

### Version information

- **Platform**: web Riot
riot-web version: 1.0.0 (and older)  
olm version: 3.0.0  

For the web app:

- **Browser**: Firefox 65.0 
- **OS**: Ubuntu
- **URL**: riot.im/app

For the desktop app:

- **OS**: Android 6.0.1
- **Version**: Riot Android (from F-Droid) 0.8.21 (F-610fc121d) and older

You can contact me for more information by mail or Matrix: florian@siegenthaler.mx or @siegi:matrix.org

Thank you for your perfect work!
![riot_screenshot](https://user-images.githubusercontent.com/24881365/52845258-ef8beb80-3106-11e9-8f9c-fb9c133817fd.png)

**Comment by nextistum** [comment] 2020-03-06 08:31
I can confirm this bug in full, though in my case with the desktop client and an months-old invitation from a user unknown to me, therefore I have no information on the server.
It would be good to have this fixed since now the client always shows one unread message. Thank you for the great work!

**Comment by rubinlinux** [comment] 2020-03-10 22:28
I am experiencing this bug on riot.im right now as well. No apparent way to clear the invite.

**Comment by richvdh** [comment] 2020-07-13 20:57
This issue is a bit of an edge-case. It seems to have been caused by sending a 3pid invite to an unregistered 3rd-party ID, and then registering for that 3pid yourself. Not exactly a common case, but still, Riot and Synapse shouldn't wedge like this.

I've opened #7838 to track this on the Synapse side. @fsiegenthaler: now that #7804 has landed, you may find that you can reject the invite and it will go away. Can you confirm?

**Comment by t3chguy** [comment] 2023-04-25 15:07
Closing in favour of matrix-org/synapse#7838

**Closed by t3chguy** 2023-04-25 15:07 UTC
Labels: T-Defect, P1, S-Major, Z-Stuck-Invite
