### ISSUE TITLE
Arm64 Native Build For Windows

### ISSUE THREAD

**Issue by huangyinhaow** [vector-im/element-web#24799] opened 2023-03-11 14:09 UTC
Windows computers with Arm SOC have a long battery life and now more and more people, especially teachers and students, are using these kind of computers and wnr is exactly what they need.
Thanks!

**Comment by t3chguy** [comment] 2023-03-11 15:42
Duplicate of #17942

**Closed** 2023-03-11 15:42 UTC
Labels: T-Enhancement

**Comment by huangyinhaow** [comment] 2023-03-11 23:37
#17942 is about Linux, not windows.

**Comment by t3chguy** [comment] 2023-03-12 08:08
How do you figure? The issue title literally says windows & linux

**Comment by huangyinhaow** [comment] 2023-03-12 08:28
> How do you figure? The issue title literally says windows & linux

Yes, it has "windows & linux" in its title, but we don't get any useful replies on "Windows" below.

**Comment by huangyinhaow** [comment] 2023-03-12 09:46
Sorry, I thought #17942 was closed because it hasn't been updated in a long time.

**Comment by jglathe** [comment] 2024-06-21 20:21
What is this. No ARM64 for Windows? Quite unbelievable.
