### ISSUE TITLE
Find a way to allow bulk redaction to help folks manage spam

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2158] opened 2016-09-11 09:15 UTC
Redactions get rate limited

**Comment by lampholder** [comment] 2018-01-11 14:24
Related:
- https://github.com/vector-im/riot-web/issues/2158 
- https://github.com/vector-im/riot-web/issues/3689
- https://github.com/vector-im/riot-web/issues/5885
- https://github.com/vector-im/riot-web/issues/5898

**Comment by PC-Admin** [comment] 2018-04-23 00:37
You should have bulk redaction just because it would be an enhancement and the current redaction system in riot is annoying.

I should be able to select multiple messages, (or all) and redact them in 3 clicks. You're currently forced to click way too many times, try redacting 20 messages, that will be 60 clicks, then tell me how you feel.

Can we please make this happen? The Riot UI/UX is currently bad and i would like to see Riot become something worth telling people about.

**Comment by aaronraimist** [comment] 2021-07-30 07:48
Duplicate of https://github.com/vector-im/element-web/issues/3689

**Closed by aaronraimist** 2021-07-30 07:48 UTC
Labels: A-Redaction, P3, T-Enhancement

**Comment by alittlebitofit** [comment] 2022-05-05 07:46
It's 2022 and most chat apps have this feature so why not Element too?

Please make it.
