### ISSUE TITLE
A11y: Automatic breaks and content wrapping

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#24934] opened 2023-03-24 13:20 UTC
<img width="218" alt="Screenshot 2023-03-24 at 13 19 59" src="https://user-images.githubusercontent.com/89144281/227532024-10347f2f-8b19-40a0-ac41-378d7b628618.png">

If the browser width is reduced to 320 pixels according to the default, the controls
in the header area of the page are no longer displayed (example marked in red).
Furthermore, content from the middle area of the page wraps around in such a way
that some of it can no longer be read. (Example marked in blue).

**Comment by MadLittleMods** [comment] 2023-03-24 21:30
This seems more like a "mobile" thing than an accessibility related (of course the definition can be stretched that far though). Mobile is considered experimental in Element and is unusable at the moment. Here is a larger set of issues: https://github.com/vector-im/element-web/labels/A-Mobile

A bunch of these issues could be addressed with some spikes and some process change to think about it in reviews for new things so things don't continue regressing.

**Comment by t3chguy** [comment] 2023-03-27 07:20
Duplicate of https://github.com/vector-im/element-web/issues/1633

**Comment by daniellekirkwood** [comment] 2023-03-27 08:29
Re-opening temporarily as this issue appears on a board that is being shown to a customer today. 

Once meeting is concluded, I'll close this again and replace it with the tagged duplicate. 

Thanks for the input!

**Closed** 2023-03-27 15:35 UTC
Labels: T-Defect, S-Major, O-Occasional, A-Mobile, Z-Compound, Z-Retainer
