### ISSUE TITLE
Unable to invite my EMS MXID to a public room on Matrix.org

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#22023] opened 2022-05-02 17:59 UTC
### Steps to reproduce

_Where are you starting? What can you see?_
I'm in my test account on Matrix.org, created a public room, clicked Invite and entered my EMS MXID, `@daniellekirkwood:one.ems.host`

> Failed to find the following users
>
> The following users might not exist or are invalid, and cannot be invited: @daniellekirkwood:one.ems.host

<img width="785" alt="" src="https://user-images.githubusercontent.com/89144281/166299745-f87ec7c5-a738-4246-a462-ecd47f7af515.png">

#### What did you expect?
To invite my EMS account 
#### What happened instead?
Could not find user...

### Operating system

Mac

### URL for webapp

app.element.io

### Application version

Element version: 1.10.11 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by MadLittleMods** [comment] 2022-05-02 19:06
When I try to `/invite @daniellekirkwood:one.ems.host`

`GET https://matrix-client.matrix.org/_matrix/client/r0/profile/%40daniellekirkwood%3Aone.ems.host` -> 403 forbidden

> Server error
> 
> You do not have permission to invite people to this room.

![](https://user-images.githubusercontent.com/558581/166308817-95b1b073-7ff7-4cfb-b572-872b681afc6a.png)



And when I use the invite dialog like you're doing, I get the same 403 forbidden (`GET https://matrix-client.matrix.org/_matrix/client/r0/profile/%40daniellekirkwood%3Aone.ems.host` -> 403 forbidden) error on your mxid even though I am an admin in the room. The error dialog saying I don't have permission seems like a different bug where it responds to any 403 because I do have permission to invite.

> Failed to invite users to test-public1
> 
> You do not have permission to invite people to this room.

![](https://user-images.githubusercontent.com/558581/166308800-214afd2a-4e06-4ecc-b8cb-cd2e64d2c235.png)

One thing I noticed was that your invite input is empty/blank. It should have the MXID of the person you're trying to invite like my screenshot.

**Comment by t3chguy** [comment] 2022-05-03 07:31
Duplicate of https://github.com/vector-im/element-web/issues/17269

**Closed by t3chguy** 2022-05-03 07:31 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, A-Invite, O-Uncommon, A-EMS
