### ISSUE TITLE
Element Desktop screensharing keeps loading without displaying either whole screen or specific window

### ISSUE THREAD

**Issue by AntoineC4Ci** [vector-im/element-web#22890] opened 2022-07-19 10:15 UTC
### Steps to reproduce

1. Startup Element app.
2. Join Video Call.
3. Click on screenshare.
4. Both "Your entire screen" & "Application window" stuck in a infinite loading screen

### Outcome

I expected to see share previews in the popup so I would be able to share my screen with my team.

However, it will not load the preview (infinite loading) and therefore I can't show my team my screen.

### Operating system

Windows 11

### Application version

Version de Element : 1.11.0 Version de Olm : 3.2.8

### How did you install the app?

from element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-07-19 12:35
Duplicate of #4880

**Closed by t3chguy** 2022-07-19 12:35 UTC
Labels: T-Defect
