### ISSUE TITLE
Space avatar thumbnail in the space index room is low res

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16975] opened 2021-04-16 12:13 UTC
Looks like we're requesting 32x32px or something rather than a larger size which will get us a sensible quality avatar for the size of the element.

<img width="280" alt="Screenshot 2021-04-16 at 13 11 07" src="https://user-images.githubusercontent.com/1294269/115022561-72f72200-9eb5-11eb-9b93-c39fad549d4e.png">

**Comment by t3chguy** [comment] 2021-04-19 07:57
Mine is requesting a 160x160 for a render size of 80x80 with a 96x96 being sent back

![image](https://user-images.githubusercontent.com/2403652/115201333-226a0980-a0ed-11eb-9997-9e45e30477d1.png)

Cannot reproduce.

**Comment by niquewoodhouse** [comment] 2021-05-12 09:27
Is it maybe something to do with that specific image?  For the element web team, its just a 32x32 image?

**Comment by t3chguy** [comment] 2021-05-12 09:29
Probably, though I have no access to whatever space that was to check

**Comment by t3chguy** [comment] 2021-06-22 08:41
Closing as unable to reproduce

**Closed by t3chguy** 2021-06-22 08:41 UTC
Labels: A-Spaces, T-Defect, X-Cannot-Reproduce
