### ISSUE TITLE
[Bug] Stuck Message Notification

### ISSUE THREAD

**Issue by 8227846265** [vector-im/element-web#24492] opened 2023-02-10 22:30 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Encrypted Room's Thread Messages

2. What do you click?
If you re-open Element Desktop App (Windows), it will show you an unread message notification that was edited by a room member, and it cannot be marked as read no matter what. It keeps popping up!

#### What did you expect?
If the message is read on the Thread. It should be read

#### What happened instead?
It's stuck being unread and keep sending the message notification every single time I open Element!

### Operating system

Windows 11

### Application version

Element version: 1.11.22 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started

### Will you send logs?

Yes

**Comment by 8227846265** [comment] 2023-02-10 22:31
Screenshot: All the notification is already read. But unread message notification won't go away when you re-open Element Desktop App.
![image](https://user-images.githubusercontent.com/66582769/218212612-424ff3b6-80b8-480e-ad9f-b799f173d50b.png)

**Comment by weeman1337** [comment] 2023-02-13 07:31
Thank you for your report @8227846265 .

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-02-13 07:31
Duplicate of #24394

**Closed by weeman1337** 2023-02-13 07:31 UTC
Labels: T-Defect
