### ISSUE TITLE
Light/dark theme transition is broken for the first transition

### ISSUE THREAD

**Issue by ofalvai** [vector-im/element-web#21593] opened 2022-03-30 06:44 UTC
### Steps to reproduce

My Element client is set to follow the OS theme setting and macOS is set to "Auto" light/dark theme based on sunset/sunrise.

I noticed that Element sometimes is stuck in dark mode even though the rest of the OS is in light mode. So I made some manual theme toggling in macOS and observed how Element behaved. The video below demonstrates that the first theme transition of `dark -> light` is ignored, but any subsequent transition is correctly handled in Element.

https://user-images.githubusercontent.com/1694986/160767742-c8126089-edf1-40eb-b713-813b46e44d71.mov

#### What did you expect?

Element should follow the system theme in all cases

#### What happened instead?

The first `dark -> light` transition is ignored while subsequent transitions are handled correctly.

### Operating system

macOS

### Application version

Element Nightly Version 2022032901

### How did you install the app?

From the Nightly download page

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-03-30 07:53
Duplicate of https://github.com/vector-im/element-web/issues/15459

**Closed by t3chguy** 2022-03-30 07:53 UTC
Labels: T-Defect, S-Minor, A-Appearance, O-Occasional, good first issue
