### ISSUE TITLE
Riot fails to respond properly to a Matrix homeserver that has a self-signed certificate

### ISSUE THREAD

**Issue by xuhdev** [vector-im/element-web#3361] opened 2017-03-03 22:28 UTC
### Description

If the homeserver has a self-signed certificate, and the user has logged in, Riot fails to inform users that it cannot connect. Instead, it only shows a cursor that rotating forever.

### Steps to reproduce

- Set up a homeserver using a self-signed certificate.
- Start Riot in browser, trust the homesever certificate and log in.
- Close the Riot tab. Untruest the homeserver certificate.
- Start Riot in browser again.

Describe how what happens differs from what you expected.

I cannot log in and no error message is shown. Below is the screenshot:

![screenshot_2017-03-03_14-26-08](https://cloud.githubusercontent.com/assets/325476/23571331/7d3d9ffe-001d-11e7-9834-1623cbbbb244.png)

### Version information

- **Browser**: Chrome 56
- **OS**: Windows and Debian.
- **URL**: self hosted, 0.9.7.

**Comment by ara4n** [comment] 2017-03-08 15:45
This shouldn't happen - it should say "Can't connect; check your SSL settings and trust the server".  @dbkr @lukebarnard1  is there a chance this has regressed in recent login/auth/reg/rts stuff?

**Comment by xuhdev** [comment] 2017-03-08 18:37
@ara4n Your description happens if the SSL certificate is not trusted in the first place. In my case, (1) the certificate is trusted first, then (2) the user logs in, then (3) the user untrusts the SSL certificate.

**Comment by ara4n** [comment] 2017-03-27 11:44
related from @vurpo:

```
hmmm
My homeserver's cert (on port 8448) had expired apparently, and this meant Riot on my laptop was not able to connect, because it was stiill configured to use port 8448 and not 443
but interestingly, there was no meaningful error, only "connection to the server lost", and when I tried to restart Riot, it hung on the spinning loading screen with no feedback
The developer console revealed the error to me
```

**Comment by MacLemon** [comment] 2017-07-28 19:05
Same problem for Riot-iOS: https://github.com/vector-im/riot-ios/issues/1419
Expired certificates cause the client to just spin forever, without any information to the user.

**Comment by fadeAce** [comment] 2018-03-09 06:45
@xuhdev How youSet up homeserver using a self-signed certificate actually .
Can't find any intro in doc.

**Comment by xuhdev** [comment] 2018-03-09 07:59
@fadeAce I explained this in [one of my blog posts](https://www.topbug.net/blog/2016/12/05/set-up-synapse-matrix-homeserver-on-ubuntu-16-04/). Search for "certificate".

**Comment by t3chguy** [comment] 2022-05-07 02:36
Duplicate of https://github.com/vector-im/element-web/issues/251

**Closed by t3chguy** 2022-05-07 02:36 UTC
Labels: T-Defect, P2, X-Regression, S-Minor
