### ISSUE TITLE
Can't get rid of unread status of a room

### ISSUE THREAD

**Issue by jplatte** [vector-im/element-web#24595] opened 2023-02-21 07:58 UTC
### Steps to reproduce

I opened Element today, caught up with some messages in a room I already read fully on mobile, but it still has the small white dot on it indicating unread messages. There is no unread dot on the thread button. Right click > Mark read does nothing.

edit: It just fixed itself after a new message came in. That message was marked read while I had the rageshake popup open. I hope the logs are helpful in some way.

I see that there was https://github.com/matrix-org/matrix-react-sdk/pull/9941 which was released in 1.11.23, I will close this issue if I don't see unreads get stuck after that upgrade. It happens quite frequently right now.

#### What did you expect?

The room being marked as read.

#### What happened instead?

The room being marked as unread.

### Operating system

arch linux

### Application version

1.11.20

### How did you install the app?

element-desktop package

### Will you send logs?

Yes

**Comment by jplatte** [comment] 2023-02-21 08:14
Thanks, will do!

**Comment by hannesj** [comment] 2023-02-21 10:25
Same happening for me

```
Room status
- Room unread status: Grey, count: 1
- Notification state is all_messages
- Room is not encrypted 🚨
Main timeline
- Total: 0
- Highlight: 0
- Dot: false
Threads timeline
- Thread Id: $jtjo-SmBBn-XHtNdAtoRdp_4NVarqimhlitazkkCAJ8
  - Total: 0
  - Highlight: 0
  - Dot: true
  - User read up to: $dMfTNUYSLULO4oMp7J4ls5KKBc0FVT9tc_5cEsdSNow
  - Last event:
    - ID: $lN1o4lvKnAbps-_9Iy96r0ftnrT2a-qswveKK2yDRVc
    - Type: m.room.message
    - Sender: @:matrix.org
- Thread Id: $RQma5fDLdgQbsPfeFNnHnv5GB9ushpuR9iCe_9ZbYTo
  - Total: 1
  - Highlight: 0
  - Dot: false
  - User read up to: $Bm4Zka0Uz3CiHV8eH-t1YB7t5KduUahotNlzgMcRj-I
  - Last event:
    - ID: $Bm4Zka0Uz3CiHV8eH-t1YB7t5KduUahotNlzgMcRj-I
    - Type: m.room.message
    - Sender: @:matrix.org
```

**Comment by jjenzz** [comment] 2023-02-21 10:28
i am also experiencing this in 1.11.23 for two separate channels atm.

```sh
Room status
- Room unread status: Bold
- Notification state is mentions_only
- Room is encrypted ✅
Main timeline
- Total: 0
- Highlight: 0
- Dot: true
- User read up to: $mWPaOJh3aGQfe0gnOuZdRYShYrFGPbsOJJx_L8gSiUI
- Last event:
    - ID: $Ep4VPli6avtqd9tkagMDnGaDXirivoJ9Y81W8-5mgTw
    - Type: m.room.message
    - Sender: @:matrix.org
Threads timeline
```

```sh
Room status
- Room unread status: Bold
- Notification state is mentions_only
- Room is encrypted ✅
Main timeline
- Total: 0
- Highlight: 0
- Dot: true
- User read up to: $zrhU_0DGz34rHOFCupwkVKOiZ2lHrFRjmVH3fKDX9ew
- Last event:
    - ID: $KXV3ws_VEpU9-CE0L2hL9r96SNebLZ3083TuGZUonHw
    - Type: m.room.message
    - Sender: @:matrix.org
```

**Comment by leonardehrenfried** [comment] 2023-02-22 08:56
I'm seeing the same thing:

```
Notifications debug
Room ID: !oXNNoHKzbaSOlFzLEt:gitter.im
Room status

    Room unread status: Bold
    Notification state is all_messages_loud
    Room is not encrypted 🚨

Main timeline

    Total: 0
    Highlight: 0
    Dot: true
    User read up to: $aNsXIp8g11CepCRja3GMWVRX64zqthaEbMv-7eY1O7g
    Last event:
        ID: $ecsA3i6u5yFAsgFrBDUosPs_wNoz34GtC_RR5fd63cQ
        Type: m.room.message
        Sender: @optionsome-6357be356da03739849e595d:gitter.im
```

**Comment by hannesj** [comment] 2023-02-28 12:07
Now the devtools shows an item where I'm the sender of the last message in the thread.

![image](https://user-images.githubusercontent.com/698100/221850090-874bca6c-a994-4370-afe6-efd97fd62755.png)

**Comment by jplatte** [comment] 2023-03-07 13:34
Still a problem on latest git version (`1.11.24.r26.g3c4d25d6c2-1` as determined by the AUR pkgbuild's `pkgver`):

```
Notifications debug
Raum-ID: !QQpfJfZvqxbCfeDgCj:matrix.org
Raumstatus
  Room unread status: Fett
  Notification state is mentions_only
  Room is not encrypted 🚨
Hauptverlauf
  Insgesamt: 0
  Höhepunkt: 0
  Punkt: true
  Der Benutzer hat gelesen bis: $zlFg0n1gHgrFBVZU02lI98tRMnk1aquFrfvZdObFffo
  Neuestes Ereignis:
    ID: $wQhdJXJA3EYaXkcEs8HAL6ensLajCod63STdxvSmU04
    Typ: m.reaction
    Absender: @andrewm:element.io
Thread-Verlauf
```

**Comment by MadLittleMods** [comment] 2023-03-21 19:08
Reproduction:

Rageshake logs: https://github.com/matrix-org/element-web-rageshakes/issues/20739

Notifications debug output:
```
Room status
 - Room unread status: Bold
 - Notification state is mentions_only
 - Room is not encrypted 🚨
Main timeline
 - Total: 0
 - Highlight: 0
 - Dot: true
 - User read up to: $v1xNjqIMcB93heBFWqXdwzt6N2PvRpyl2eSSynsfad0
 - Last event:
    - ID: $XwfpdmDh6-HCg5ot9lOxgdceNnJvmsn3aW3c0ooQEQE
    - Type: m.room.member
    - Sender: @shayshay:matrix.org
Threads timeline
```

Stuck unread dot in room list | No unread dots on threads | Last event in main timeline
--- | --- | ---
![](https://user-images.githubusercontent.com/558581/226715040-8328c363-d9fa-4b6f-9c10-f57c5ccc9f4b.png) | ![](https://user-images.githubusercontent.com/558581/226715065-35deb76d-96e1-475f-80cf-d22cc1f88e67.png) | ![](https://user-images.githubusercontent.com/558581/226715406-da638dc6-6d58-4efb-a4e7-a73b1a4e1753.png)

**Comment by alexander-potemkin** [comment] 2023-04-21 14:45
@t3chguy , is there any news on that one?
It keeps happening every day for me, quite annoying...

**Comment by t3chguy** [comment] 2023-04-21 15:13
@alexander-potemkin any news would be in this ticket. I'm not assigned to this issue so I have no idea what's going on with it.

**Comment by alexander-potemkin** [comment] 2023-04-24 09:05
@t3chguy there are none so far, that's exactly the reason I'm asking. I understand now you are not the person in charge, which was not clear initially, as you were the person to triage the issue.

For everyone looking for the fix and updates - that seems to be a ticket to track: https://github.com/vector-im/element-web/issues/24392

**Comment by jplatte** [comment] 2023-07-07 08:33
Got a new really weird stuck unread status with Element Desktop 1.11.35: It says I have a mention in the room (likely one from yesterday, that I already read yesterday, outside a thread. When switching between that room and others, it disappeared and re-appeared, though the room was always marked as unread (just sometimes with, sometimes without a mention, i.e. large red circle with `1` in it vs. small white circle).

After clicking around for a while, I was no longer able to reproduce the unread-with-mentions state, but after restarting and waiting a bit it came back. I also got the jump-to-last-unread-msg button in the top-right, and clicked it. This changed the room into a view where *only* the latest message (which also is a thread root) and the thread button were visible, and the unread status changed to a *grey* circle.

Here's the debug output with the grey circle, I think red circle as exactly the same except for the unread status bit. Unfortunately I wasn't able to get the unread status other than small-white-circle after locale change.

```
Raumstatus
Room unread status: Grau, count: 1
Benachrichtigungsstand ist mentions_only
Raum ist verschlüsselt ✅
Hauptverlauf
Insgesamt: 1
Höhepunkt: 0
Punkt: true
Der Benutzer hat gelesen bis: $mHNMm_1CJYxDgZYBxC2uCs0PFiAV0VJPZ-1U9T9ULzc
Neuestes Ereignis:
ID: $hV68nj_BXk7BSSu5IxUygqE_LExBIAzqzeaQodUT-eI
Typ: m.room.message
Absender: @jorgem:element.io
```

Here it is for small-white-circle:

```
Room status
Room unread status: Bold
Notification state is mentions_only
Room is encrypted ✅
Main timeline
Total: 0
Highlight: 0
Dot: true
User read up to: $Z6i_qIRweVT0knSg-rECw4Ek-N_1pFMLY2q5e0gTt1Q
Last event:
ID: $hV68nj_BXk7BSSu5IxUygqE_LExBIAzqzeaQodUT-eI
Type: m.room.message
Sender: @jorgem:element.io
Threads timeline
```

I was able to clear the unread status by adding a reaction to an arbitrary message (and removing it again).

**Comment by t3chguy** [comment] 2023-07-20 14:21
This is believed to have been fixed, if you are still experiencing issues with Stuck Notifications please comment on the issue **with reproduction steps and submit new logs**

**Closed by t3chguy** 2023-07-20 14:21 UTC
Labels: T-Defect, S-Major, A-Notifications, O-Frequent

**Comment by imincik** [comment] 2023-08-25 09:53
I am hitting this issue all the time. 

```
Developer Tools
Notifications debug
Room ID: !LIBpELfAqNehbGpenv:matrix.org
Room status
Room unread status: Bold
Notification state is all_messages
Room is encrypted ✅
Main timeline
Total: 0
Highlight: 0
Dot: true
User read up to: $QUWKt-bTlne6Klf0srRXtv6QT5t8hUA0EU_Q_oP7i24
User read up to (ignoreSynthetic): $QUWKt-bTlne6Klf0srRXtv6QT5t8hUA0EU_Q_oP7i24
Last event:
ID: $giyMcyg82KOpmYGQRfUc1XfZEP9ILq8LquZEOyGMJ-A
Type: m.room.message
Sender: @alejandrosame:matrix.org
Threads timeline
```

Element version: 1.11.38
Olm version: 3.2.14

**Comment by viceice** [comment] 2024-01-05 07:12
I see this happenening on windows desktop app after hibernate. All threads are unrad again. 

A restart of element app resolves the issue.

**Comment by hurradiegams** [comment] 2024-01-06 09:39
> I see this happenening on windows desktop app after hibernate. All threads are unrad again.
> 
> A restart of element app resolves the issue.

Same here on Element Desktop on Linux.
After hibernation most of the threads are unread again, some channels too. If necessary I will provide logs.

Should this Issue be reopened or should one make a new one?
