### ISSUE TITLE
Sometimes scrolling (up) does not work

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17593] opened 2021-06-08 10:00 UTC
### Description

Rolling my mouse wheel to go back in the timeline, but it doesn't work reliably?

### Steps to reproduce

- I'm visiting a couple public, federated rooms that were active over what is night for me
- there's the jump to last unread button
- try scrolling a bit
- nothing
- move mouse around for a bit, did element freeze?
- try scrolling here and there
- for some reason is scrolls when pointer is here, but not there
- eventually it works normally
- ???

could actually be a performance or backfilling issue?

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021060802-1

**Comment by gsouquet** [comment] 2021-06-09 16:14
I have spent a bit of time trying to reproduce this issue without much luck so far.

If it does happen to you again, would you mind rageshaking as it might unveil some precious detail to debug

In the mean time a few questions to understand a bit more where that could come from
- Did that happen right after you launched Element or did you left it on overnight?
- Have you experienced it again after that time?

**Comment by HarHarLinks** [comment] 2021-06-09 16:53
- it was shortly after launching
- i'm keeping an eye on it, so far i don't think it happened again

my intuition is that it is a performance problem of element and/or my (own, somewhat slow) homeserver. it might have been backfilling history at the point, but unlucky content somehow that the spinner wasn't visible?

**Comment by rkfg** [comment] 2021-06-10 11:16
Happens to me as well on current develop. An easy way to reproduce when you have unread messages:
- click "Jump to first unread"
![2021-06-10_14-14-20](https://user-images.githubusercontent.com/184066/121515707-2a13a380-c9f6-11eb-9d24-d490532df728.png)
- scroll works there
- click "Scroll to most recent messages": 
![2021-06-10_14-15-18](https://user-images.githubusercontent.com/184066/121515846-4b748f80-c9f6-11eb-9871-9c0e0ad64632.png)
- scroll locks up; move the mouse around while scrolling, after some time it randomly unlocks. Often locks up again when you scrolled to the last message.

**Comment by gsouquet** [comment] 2021-06-10 11:19
Would you be able to share a bit more information regarding your spec (OS, Browser, version, ...)
And if possible a rageshake could potentially help to unveil some important bits to resolve this

Thank you

**Comment by rkfg** [comment] 2021-06-10 11:22
Using Brave 1.24.86 Chromium: 90.0.4430.212 (Official Build) (64-bit) on Debian testing. Reproducible on develop (https://develop.element.io/#/room/#matrix:matrix.org). Rageshake logs sent.

**Comment by HarHarLinks** [comment] 2021-06-10 15:11
thanks for helping track this down, rkfg

it happened again to me just now, rageshake submitted. notice I did *not* use the go to unread nor go to most recent buttons, just load the room. element has been running for several hours before it.

**Comment by rkfg** [comment] 2021-06-10 15:35
Yes, it happens sometimes even after switching between rooms. Then when I scroll it eventually start scrolling as if I'm trying to scroll through some invisible space (?) below the page. I just literally scroll for a long time, not even moving the mouse and the timeline starts moving after a while. Looks very weird.

**Comment by HarHarLinks** [comment] 2021-06-11 14:59
Currently happening to me, again in TWIM room. Clicked "scroll up to last unread" and it's stuck (without going there). Clicked submit feedback then debug log, but that isn't popping up either now i can't even click submit feedback.

It "unlocked", I scrolled up slightly and back down, stuck again.

**Comment by jryans** [comment] 2021-06-14 17:08
What about keyboard scrolling actions like page up / page down, do they still work in the locked case?

**Comment by rkfg** [comment] 2021-06-14 17:33
PageUp/PageDown do work while mouse wheel doesn't.

**Comment by jryans** [comment] 2021-06-15 09:05
Hmm, I wonder if this was triggered by the recent scrolling change in https://github.com/matrix-org/matrix-react-sdk/pull/5823...

**Comment by jryans** [comment] 2021-06-15 09:26
I _think_ I can replicate this when testing in Chrome Canary on macOS with a mouse wheel, though it's a bit of a subtle issue.

**Comment by HarHarLinks** [comment] 2021-06-15 12:17
Have you tested using a federated room? It happens in particular almost every time I open https://matrix.to/#/#thisweekinmatrix:matrix.org from my somewhat underpowered private homeserver (there is a backlog of unread messages that start out of screen for me 99% of cases).

I can confirm PageUp/PageDown do work while mouse wheel doesn't. Additionally, after using PageUp once, then using the wheel works. It is only when going back to the very bottom while there are still unread messages that it sticks there again. Scrolling back down too quickly will skip marking some unread messages as read by/for me (green line is supposedly where other participants would see my avatar icon?), and it stays sticky.

**Comment by jryans** [comment] 2021-06-15 14:21
Hmm, still having trouble reproducing this consistently... 😕 I don't think it would be related to federated rooms, server performance, or anything like that...

**Comment by HarHarLinks** [comment] 2021-06-16 19:09
It has now for the first time happened on a room internal to my hs. As before, I need only open the room which has had enough activity while I was away to offer the jump to first unread button and scrolling is stuck.

My platform as mentioned above is (Arch) Linux, but I will add that I use the desktop app nightly through xwayland on wayland (swaywm) and pipewire, perhaps this is some weird edge case with this setup.

**Comment by rkfg** [comment] 2021-06-16 20:44
I don't think it's platform-dependent. I'm on Debian with just plain Xorg and AwesomeWM and it still happens.

**Comment by mserajnik** [comment] 2021-06-21 20:02
This happens to me with my self-built Element Desktop (Electron) as well after updating to v1.7.31. It did not happen with v1.7.29, which I used previously.

**Comment by novocaine** [comment] 2021-11-09 17:18
@HarHarLinks is this still happening?

**Comment by rkfg** [comment] 2021-11-09 19:16
Can't reproduce here, at least with the steps I described above. And I don't remember it happening for a while already. Thanks!

**Comment by novocaine** [comment] 2021-11-09 20:02
Hrm okay, if anyone still sees it we will reopen. Closing for now.

**Closed by novocaine** 2021-11-09 20:02 UTC
Labels: T-Defect, X-Cannot-Reproduce, X-Regression, S-Minor, A-Timeline, O-Uncommon
