### ISSUE TITLE
Copy image to clipboard broken

### ISSUE THREAD

**Issue by v411e** [vector-im/element-web#26572] opened 2023-11-14 07:55 UTC
### Steps to reproduce

1. Go to Element Web or Desktop and open a chat with some images
2. Right click on an image, select "Copy Image"
3. Open another Program (e.g. MS Word or Thunderbird)
4. Image can not be pasted
![image](https://github.com/vector-im/element-web/assets/8049779/20884959-946f-4a57-9ed0-b83730226757)

#### What did you expect?
I expected the image to be properly copied and pasted.

#### What happened instead?
Image can not be pasted.

### Operating system

Windows 10

### Browser information

Google Chrome and Element Desktop

### Application version

Element 1.11.49

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-11-14 09:51
This is a feature of your browser, not the app. I suggest using something like https://evercoder.github.io/clipboard-inspector/ to see what your browser copied.

**Comment by v411e** [comment] 2023-11-15 07:56
Okay interesting. Looks like it is copied as "Blob URL" and not all other apps support reading that.

````
<img src="blob:vector://vector/17061205-bc4c-4ae9-baf9-e77c98b54368" alt="image.png">
````

**Comment by t3chguy** [comment] 2023-11-15 22:08
Blob URLs are not accessible to sites other than the one they originated from so this feels like a Chrome issue. 

When I copy image from Chrome on macOS in an encrypted room and paste it into the site above I get the actual `image/png` and not just the blob URL `text/html` entity

![image](https://github.com/vector-im/element-web/assets/2403652/56840bb3-5bd6-4f5a-a5f0-5a74d8388b93)

The actual `image/png` is what other sites should be using rather than the `text/html` - can you confirm if you're seeing both entries in the clipboard @v411e

**Comment by lalitkumawat1m** [comment] 2023-11-16 08:38
I want to work on this issue please assign it to me

**Comment by t3chguy** [comment] 2023-11-16 08:39
@lalitkumawat1m this is an upstream issue, so not an issue with Element Web/Desktop but either with https://github.com/chromium/chromium or MS Word and/or Thunderbird

**Comment by v411e** [comment] 2023-11-17 07:48
Yes, can confirm. This is Copied from Element Desktop and pasted in Chrome

![image](https://github.com/vector-im/element-web/assets/8049779/9feb92a1-dcf8-4740-9c8e-079dc888972c)

**Comment by v411e** [comment] 2023-11-17 07:54
But I just tried it using Element Web in Firefox and it was the exact same problem. So I guess it is not just a Chrome Issue then?

Copied from Element Web in Firefox, pasted in Thunderbird/Microsoft Word:
![image](https://github.com/vector-im/element-web/assets/8049779/99c10604-b36e-4bf3-ae79-294c10a6c6df)


Copied from Element Web in Firefox, pasted in Chrome:
![image](https://github.com/vector-im/element-web/assets/8049779/405e0be3-781d-4944-a35c-f8e587842bb5)

**Comment by t3chguy** [comment] 2023-11-17 08:35
No, as you have shown that the `image/png` data is visible there, the problem is with the app pasting using `text/html` instead of `image/png` - the former they cannot parse due to blob. There is nothing we can do here, we cannot not use blob URIs due to end-to-end encryption, there's no actual URL which represents the media given its encrypted. It is probably MS Word & Thunderbird trying to be clever around "rich" pasting, but getting it wrong when they can't load the blob.

**Closed by t3chguy** 2023-11-17 08:35 UTC
Labels: T-Defect, X-Needs-Info, Z-Upstream

**Comment by v411e** [comment] 2023-11-17 10:39
Ah makes sense, thank you for explaining
