### ISSUE TITLE
Animated SVG pfp replaced with generic pfp.

### ISSUE THREAD

**Issue by nathanielcwm** [vector-im/element-web#19557] opened 2021-10-31 05:49 UTC
### Steps to reproduce

1. [Download a test image](https://upload.wikimedia.org/wikipedia/commons/b/ba/Toy_train_SMIL.svg)
2. Open settings and change your pfp to that image
3. Observe that it displays properly *and is animated* in settings
![image](https://user-images.githubusercontent.com/22572406/139570073-4f6cc1d1-0f0a-41f5-9af6-c46b177155f5.png)
4. Exit out of settings
5. Observe that your pfp is now replaced by the generic pfp 
![image](https://user-images.githubusercontent.com/22572406/139569843-b0c88ff7-d373-4815-a431-9e1c27a7c325.png)
6. Observe that CPU usage while having element open is quite high as if it were trying to render the animated svg.
7. Open settings and observe that the animated svg is no longer displayed as the pfp and only the alt text is visible.
![image](https://user-images.githubusercontent.com/22572406/139569860-eb11676e-3cf3-4ce6-8a2d-15ac7201156e.png)

#### What did you expect?
It actually works as a profile picture or it is blocked from being set as the profile picture on save.
#### What happened instead?
It allows it to be set as the profile picture however in other parts of element it either doesn't display or it switches to the generic blank pfp.

### Operating system

Windows 10

### Browser information

Firefox 93

### URL for webapp

app.element.io

### Application version

Element version: 1.9.3 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2021-11-01 08:45
Duplicate of https://github.com/vector-im/element-web/issues/2581

Unrelated to them being animated

**Closed by t3chguy** 2021-11-01 08:45 UTC
Labels: T-Defect, S-Minor, A-User-Settings, A-Avatar, O-Uncommon
