### ISSUE TITLE
Add a reason to an invite

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#20576] opened 2022-01-15 14:49 UTC
#### What would you like to do?
Have a reason message/text added to an invite
#### Why would you like to do it?
So people know why I'm inviting them to a room
#### How would you like to achieve it?
Not sure if this is supported by the protocol?

### Have you considered any alternatives?

Nope.

### Additional context

On LinkedIn you can do this.

**Comment by robintown** [comment] 2022-01-15 14:52
You can do this with the /invite command, like so:

```
/invite @user:example.org reason
```

But otherwise this is a duplicate of https://github.com/vector-im/element-web/issues/17035.

**Closed by robintown** 2022-01-15 14:52 UTC
Labels: T-Enhancement
