### ISSUE TITLE
Status message

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#18123] opened 2021-07-21 00:01 UTC
#### Is your suggestion related to a problem? Please describe.
I would like to leave the client running and keep getting updates (not the same as notifications though) on a room without appearing as online/available.

#### Describe the solution you'd like.
A status message like on most other IM platforms. There would be a choice of:
* Online/available
* Online/away (or similar)
* Online, but appear as offline
* Offline

And could be accompanied by a custom status message, again like on many other IM platforms. Something like "I'm away until 10:00" or "I popped to the shops for a bit". There could also be a similar message when just online/available, like "I'm here, and still healthy" or "I'm working on project 42 today"

#### Describe alternatives you've considered.
Can't really think of any. I'm just looking at how Slack has implemented this, and then noticed Element/Matrix hasn't (or doesn't appear to), but for me Slack is not exactly a great alternative.

#### Additional context
I suppose I could post a screenshot of what Slack offers in the way of status messages, but frankly ICQ and MSN had this feature in some way or another, way back when. So, I'm assuming many people have encountered a feature similar to this request on some other IM software they've used, making much more information a bit superfluous.

**Comment by robintown** [comment] 2021-07-21 01:48
Duplicate of https://github.com/vector-im/element-web/issues/8029 and a number of the related issues linked there

**Closed by robintown** 2021-07-21 01:48 UTC
Labels: T-Enhancement
