### ISSUE TITLE
no back button on a bad login server

### ISSUE THREAD

**Issue by foldleft** [vector-im/element-web#13413] opened 2020-04-28 10:20 UTC
I input my login server incorrectly. I got an error message but was unable to hit 'back' and try again

**Comment by turt2live** [comment] 2020-04-28 15:46
Presumably this is entering a bad server? Screenshots help a lot...

This is what happens when you enter it the first time:
![image](https://user-images.githubusercontent.com/1190097/80508274-15c93000-8935-11ea-8ea6-1dbf6bc2543a.png)

If you fail to correct it and enter it again (press 'next' despite error):
![image](https://user-images.githubusercontent.com/1190097/80508331-27aad300-8935-11ea-87c8-02a432674dd3.png)

Seems like we have a state machine issue here.

**Comment by t3chguy** [comment] 2020-10-02 11:40
Duplicate of https://github.com/vector-im/element-web/issues/12323

**Closed by t3chguy** 2020-10-02 11:40 UTC
Labels: bug, defect
