### ISSUE TITLE
Rageshakes fail when indexeddb is unavailable

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#19298] opened 2021-10-05 17:40 UTC
### Steps to reproduce

1. Get into a state where the indexed db is broken
2. Try to rageshake

#### What did you expect?

It should at a bare minimum allow me to download them.

#### What happened instead?

It crashes with "Failed to send Logs: No connected database"

Relevant screenshots of the logs on why it failed to do indexeddb operations. (There is no rageshake specific error)

![image](https://user-images.githubusercontent.com/1374914/136074819-3f473685-77e6-41b5-b3a1-671272841d86.png)

### Operating system

Windows 11

### Browser information

Firefox 92.0.1 (64-bit) (Private window)

### URL for webapp

staging.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2021-10-06 08:26
The logs are stored in IndexedDB though, so without it there is no where to store them, hence lack of ability to rageshake/download them.

**Comment by SimonBrandner** [comment] 2021-10-06 14:03
Is there any point in having this issue, since there doesn't seem to be a solution?

**Comment by gsouquet** [comment] 2021-10-07 08:20
I think it's good to have a comprehensive set of issues related to storage so that we can have a good understanding of what needs to be fixed when we're going to look at upgrading the storage layer

**Comment by turt2live** [comment] 2022-05-07 03:06
Duplicate of https://github.com/vector-im/element-web/issues/13290

**Closed by turt2live** 2022-05-07 03:06 UTC
Labels: T-Defect, S-Minor, A-Storage, A-Feedback-Reporting, O-Uncommon
