### ISSUE TITLE
Joining a room inside a space immediately led to bug / debug logs screen

### ISSUE THREAD

**Issue by jblachly** [vector-im/element-web#23758] opened 2022-11-12 16:35 UTC
### Steps to reproduce

From anywhere, `/join #vls:matrix.org`

The spaces correctly appears.

Click "Join" button for the "General" channel.

Something went wrong / bug / submit debug logs screen appeared

#### What did you expect?

Join the channel in the #vls space

#### What happened instead?

Bug / submit debug logs screen

### Operating system

Mac OS

### Browser information

Firefox Latest

### URL for webapp

https://chat.mozilla.org/

### Homeserver

chat.mozilla.org

### Will you send logs?

Yes

**Comment by jblachly** [comment] 2022-11-12 16:38
Additional info: After submitting logs, then clicking "clear cache and reload", I returned to the Spaces main screen; it showed that I was joined in the VLS General room; the "Join" button was instead "View". Clicking "View" I was able to join the channel.

**Comment by robintown** [comment] 2022-11-13 01:59
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by robintown** 2022-11-13 01:59 UTC
Labels: T-Defect
