### ISSUE TITLE
Group DM encryption is set unreliably

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#23415] opened 2022-10-04 14:34 UTC
### Steps to reproduce

Starting 3 different Group DMs today by:

1. Clicking [+] in the people list
2. Inviting people by Matrix ID
3. With users on matrix.org, element.io & one.ems.host
4. Where I can see device lists on their profiles

...is producing different results.

In one group chat, the initial message sent on invite was sent in the clear:

<img width="734" alt="Screenshot 2022-10-04 at 15 21 59" src="https://user-images.githubusercontent.com/4626865/193847359-00ba0604-6cf0-4703-9ceb-b9211b7f680f.png">

In another group chat, everything worked (encryption enabled, sent encrypted):

<img width="855" alt="Screenshot 2022-10-04 at 15 27 23" src="https://user-images.githubusercontent.com/4626865/193847644-cb74a2a1-203f-49dc-8e08-68d34dcbafb3.png">

In another group chat, encryption wasn't enabled at all:

<img width="856" alt="Screenshot 2022-10-04 at 15 26 00" src="https://user-images.githubusercontent.com/4626865/193847581-001158eb-c125-4ed9-8309-4f2d75924734.png">

### Outcome

Confusion.

### Operating system

macOS latest.

### Browser information

Chrome latest.

### URL for webapp

develop.element.io

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2022-10-04 14:36
We should force key download when creating a DM.

**Comment by turt2live** [comment] 2022-10-05 05:20
This is not `S-Critical` - there are workaround (enable encryption), and data is not lost. Messages can also be sent, which means work is not prevented.

**Comment by weeman1337** [comment] 2023-05-12 09:09
I've tried to reproduce this with existing users, users on other servers, a brand new account that doesn't know about the invited users yet: Unfortunately I cannot reproduce this.

**Comment by t3chguy** [comment] 2023-10-16 10:12
Closing due to no reproduction

**Closed by t3chguy** 2023-10-16 10:12 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, A-E2EE, A-DMs, O-Occasional, A-DM-Start
