### ISSUE TITLE
Disambiguation is messed up in IRC layout

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#17690] opened 2021-06-18 14:10 UTC
When using IRC layout, user disambiguation pushes the username over the timestamp
![image](https://user-images.githubusercontent.com/1012976/122573916-19c67e80-d01d-11eb-8591-6f2dbaf8530a.png)

(Nightly build 20210617)

**Comment by robintown** [comment] 2021-06-18 14:24
Duplicate of #17648

**Closed** 2021-06-18 14:25 UTC
Labels: A-IRC-Layout, T-Defect
