### ISSUE TITLE
Clicking on links in search results not working if the URL contains a search term

### ISSUE THREAD

**Issue by xjru** [vector-im/element-web#24900] opened 2023-03-22 21:11 UTC
Clicking on a link in the search results won't work if a search term occurs directly within the URL. The search term gets highlighted in the results, which breaks apart the URL into the sections before and after the search term.

**Comment by t3chguy** [comment] 2023-03-22 21:45
Duplicate of https://github.com/vector-im/element-web/issues/17011

Next time please ensure you fill the issue template.

**Closed by t3chguy** 2023-03-22 21:45 UTC
