### ISSUE TITLE
clicking message being replied to doesnt take you to message

### ISSUE THREAD

**Issue by ninja85a** [vector-im/element-web#23804] opened 2022-11-20 22:20 UTC
### Steps to reproduce

1. click a message that is being replied to
2. have the page slightly refresh and have extra text added to the URL but nothing else happen

#### What did you expect?
to be take to the message being replied to
#### What happened instead?
nothing happens

### Operating system

fedora 36 KDE

### Browser information

firefox 107

### URL for webapp

develop.element.io

### Application version

Element version: 923120625cee-react-caac0594792b-js-cb410f463a24 Olm version: 3.2.12

### Homeserver

Synapse 1.71.0

### Will you send logs?

No

**Comment by robintown** [comment] 2022-11-20 22:35
Duplicate of https://github.com/vector-im/element-web/issues/23794

**Closed by robintown** 2022-11-20 22:35 UTC
Labels: T-Defect
