### ISSUE TITLE
Screen sharing in video rooms beta.

### ISSUE THREAD

**Issue by Coo-ops** [vector-im/element-web#25932] opened 2023-08-08 05:13 UTC
#### What would you like to do?

I'd like to see screen sharing be an option in the integrated voice/video rooms feature that is currently in beta.

#### Why would you like to do it?

My goal is to replace Discord and have drop-in/out rooms where people can chill and game stream.

Of course, screen sharing is as always a very important tool for any sort of team meetings and conferencing regardless.

#### How would you like to achieve it?

Unfortunately due to a lack of a public roadmap, it is unclear whether this is even being planned so I opened this feature request to ensure that it's being considered.

### Have you considered any alternatives?

Not without sacrificing privacy, data sovereignty and security by returning to Discord.

**Comment by t3chguy** [comment] 2023-08-08 07:48
Duplicate of https://github.com/vector-im/element-desktop/issues/683

**Closed by t3chguy** 2023-08-08 07:48 UTC
Labels: S-Major, T-Enhancement, Z-Labs, A-Video-Rooms
