### ISSUE TITLE
nootnoot UTD for some time...

### ISSUE THREAD

**Issue by JigmeDatse** [vector-im/element-web#7360] opened 2018-09-19 05:03 UTC
### Description

For a while We've not been able to decrypt nootnoot on the matrix.org account.  

### Steps to reproduce

- nootnoot sends a message
- comes in UTD to matrix.org account.  

I believe it should be able to be decrypted, but I *think* the issue is on the other side...  

Log: sent/not sent?    

Log should be sent soon.  

### Version information

riot.im/develop

Google Chrome 69.0.3497.92 on Gentoo Linux

**Comment by ara4n** [comment] 2018-09-30 21:47
I just went through the logs; and as far as I can see you're not seeing any Olm traffic from him. my guess is that unreliable weho.st<->matrix.org federation means that his device list is out of date (or that the toDevice messages are going missing), so he's not encrypting for you. We need a rageshake from his side to understand better.

Alternatively, his client might be crashing out every time it tries to send keys over Olm.

**Comment by t3chguy** [comment] 2023-07-10 11:50
Duplicate of https://github.com/vector-im/element-meta/issues/245

**Closed by t3chguy** 2023-07-10 11:50 UTC
Labels: T-Defect, P2, S-Major, A-E2EE, Z-Rageshake
