### ISSUE TITLE
Spaces room error and duplication

### ISSUE THREAD

**Issue by InezMc** [vector-im/element-web#17611] opened 2021-06-10 08:22 UTC
### Description

My spaces rooms were acting strangely and also duplicating. The one room replaced other rooms throughout my space in child spaces it should not be in. 

### Steps to reproduce

- Dont know how to reproduce and it stopped doing it after about 10 minutes

Describe how what happens differs from what you expected.

The spaces notifications were being strange, not going away after looking into rooms. And the one room TIL -internal was duplicating across my child rooms. In my space each room is represented once. It even was displaying twice in the one space. I did not get a screen shot of this before it corrected itself. 

Logs being sent: yes 

 
![image](https://user-images.githubusercontent.com/71381074/121489146-b197ed00-c9cb-11eb-8f47-fb4205f1793e.png)

And 5 minutes later its back to how it should be after clicking around a bit. I went to another space and then back to this space. I thought I had already done that though so I am not sure. 
![image](https://user-images.githubusercontent.com/71381074/121490789-46e7b100-c9cd-11eb-93d0-2a2b0e55ca8d.png)

### Version information

- **Platform**:  desktop?

 

For the desktop app:

- **OS**: Windows,  
- **Version**: 20H2

**Comment by t3chguy** [comment] 2021-06-10 08:27
Duplicate of https://github.com/vector-im/element-web/issues/14508 - predates Spaces
As for notifications, that depends on an echo from the server so service slowdowns can make it feel broken

**Closed by t3chguy** 2021-06-10 08:27 UTC
Labels: T-Defect
