### ISSUE TITLE
Joining multiple subspaces in quick succession without automatically switching to each of them

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#19065] opened 2021-09-16 07:30 UTC
#### What would you like to do?

I'd like to join multiple subspaces of a space in relatively quick succession, without being switched to the newly joined subspace on each join. For clarity, this is about the "Explore rooms" dialogue of a space.

#### Why would you like to do it?

I think this should be a relatively common use case when browsing a large "meta" space which acts purely as a collection of other related subspaces. In this case, the user will usually browse the meta space, pick out some subspaces he is interested in and will want to join them.

An example setting where this might commonly occur is a company space listing the subspaces of all the company's teams and projects.

The current behaviour of immediately switching to the new subspace is additionally cumbersome due to the space listing operation being a bit slow at the moment (at least for me), though the context switch would be annoying even if it was fast.

#### How would you like to achieve it?

I propose that the "Join" button for subspaces in a space shouldn't immediately switch to the joined subspace. It should instead replace the "Join" button with a spinner while it's performing the action and then with the "View" button (or other completion signal) when it's done. The subspace would then appear in the space side bar and the user would switch to it manually if they want to explore it further.

**Comment by kittykat** [comment] 2021-09-16 07:33
Needs product input to decide if this is an interaction that we want to have (I would say yes for when a new space member is exploring the space, especially as the subspace can be expanded to show rooms)

**Comment by t3chguy** [comment] 2021-09-16 07:44
Duplicate of https://github.com/vector-im/element-web/issues/17388 (which has a different proposed solution to the same problem)

**Closed by t3chguy** 2021-09-16 07:44 UTC
Labels: A-Spaces, X-Needs-Product, T-Enhancement, O-Occasional, A-Subspaces
