### ISSUE TITLE
Repair redacting unsent messages

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#10565] opened 2019-08-15 11:13 UTC
Currently, it is possible to redact messages that have not been sent (e.g. due to a broken connection).  Such redactions are not permanent, however - they undo themselves.
Either allow redacting, but then make the changes permanent, or disallow redacting unsent messages.

**Comment by t3chguy** [comment] 2019-08-15 11:14
Probably related https://github.com/vector-im/riot-web/issues/5898

**Comment by t3chguy** [comment] 2023-03-31 10:51
Duplicate of https://github.com/vector-im/element-meta/issues/1345

**Closed by t3chguy** 2023-03-31 10:51 UTC
Labels: T-Enhancement, A-Redaction
