### ISSUE TITLE
 Extra space available in other member's chat section when someone stops typing.

### ISSUE THREAD

**Issue by 2580ayush2580** [vector-im/element-web#16080] opened 2021-01-05 18:49 UTC
### Description

If someone starts typing a message in the room and stop typing the message without sending a message or erase the message then there will be extra space(div) available in other member's chat section.

### Steps to reproduce

- Create 2 accounts on the element-web app
- Create Room and add both accounts in the room and open both accounts on different windows
- Start typing with one account and stop typing without sending any message or erase your message.
- You will see bug as shown in screenshots.

Describe how what happens differs from what you expected.

When I stop typing then there should be no extra div available which is showing typing status.

Logs being sent: no

![i1](https://user-images.githubusercontent.com/56980422/103683036-b0dbd480-4faf-11eb-8d94-31d79f3f6b8b.png)
![i2](https://user-images.githubusercontent.com/56980422/103683045-b2a59800-4faf-11eb-8acc-68ef413a4927.png)
### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
- **OS**: Ubuntu 20.04.1 LTS

**Comment by t3chguy** [comment] 2021-01-05 19:15
This is intentional to prevent the chat bouncing up and down as people start and stop typing 

Duplicate of https://github.com/vector-im/element-web/issues/8552

**Closed by t3chguy** 2021-01-05 19:15 UTC
Labels: bug, ui/ux
