### ISSUE TITLE
Vertically resizing the window obscures the bottom of the thread panel

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#20700] opened 2022-01-24 11:22 UTC
### Steps to reproduce

Have a thread open and resize the window vertically

Before

<img width="662" alt="Screenshot 2022-01-24 at 11 20 00" src="https://user-images.githubusercontent.com/57377/150773931-fb0d1a5c-b5e8-4b82-a1f9-db1d6c44e730.png">

After (no vscroll is available, so I have no way to access the bottom of the thread)

<img width="423" alt="Screenshot 2022-01-24 at 11 20 12" src="https://user-images.githubusercontent.com/57377/150773956-2b9c9e4a-5166-4575-b63f-4208986e6806.png">

#### What did you expect?

The panel's layout should update in response to the resize

#### What happened instead?

I lost access to the bottom of the thread

### Operating system

OS X

### Browser information

Nightly

### URL for webapp

develop.element.io

### Application version

Nightly

### Homeserver

threads-dev.lab.element.dev

### Will you send logs?

No

**Comment by gsouquet** [comment] 2022-01-26 14:39
Duplicate of https://github.com/vector-im/element-web/issues/20594

**Closed by gsouquet** 2022-01-26 14:39 UTC
Labels: T-Defect, S-Minor, O-Occasional, A-Threads, Z-Labs
