### ISSUE TITLE
Emojis suddenly small ;-(

### ISSUE THREAD

**Issue by rgpublic** [vector-im/element-web#25307] opened 2023-05-08 13:50 UTC
### Steps to reproduce

If you used *only* emojis in a line then those emojis appeared enlarged (Linux). Suddenly this doesn't seem to work anymore. On my smartphone (Android) I see the enlarged emojis. But my chat partner (Windows) also doesn't see the large emojis if I write them. He can send me large emojis, though. I hate to say it but this bug is really, really depressing. No large emojis anymore for me. Not funny at all.

#### What did you expect?
Seeing large emojis

#### What happened instead?
I see small emojis

### Operating system

Manjaro Linux 22.1.1 (Talos)

### Application version

Version Element: 1.11.26, Version Olm: 3.2.12

### How did you install the app?

Official Manjaro community repository

### Homeserver

Snapse 1.82.0+kinetic1

### Will you send logs?

No

**Comment by kerryarchibald** [comment] 2023-05-09 03:02
I can reproduce this by disabling markdown in composer preferences, or enabling the rich text editor in labs.
With either of the settings above, a plain emoji message is sent with a `formatted_body`, which the big emoji logic does not correctly interpret as an emoji body.
```
{
    "msgtype": "m.text",
    "body": "😀",
    "format": "org.matrix.custom.html",
    "formatted_body": "😀"
 }
```
Without the settings above, the same message is sent without the custom html format and is interpreted as an emoji body correctly
```
{
    "msgtype": "m.text",
    "body": "😀"
 }
```

**Comment by kerryarchibald** [comment] 2023-05-09 03:34
Probably duplicate https://github.com/vector-im/element-web/issues/22009

**Comment by t3chguy** [comment] 2023-05-09 08:19
Duplicate of https://github.com/vector-im/element-web/issues/22009

**Closed by t3chguy** 2023-05-09 08:19 UTC
Labels: T-Defect
