### ISSUE TITLE
(Encrypted, PM?) with many attachments causes element to hang

### ISSUE THREAD

**Issue by fmlatghor** [vector-im/element-web#18306] opened 2021-07-30 19:58 UTC
![image](https://user-images.githubusercontent.com/52841429/127705133-d44b51e2-e3b6-43f6-ac20-b23a3249446d.png)

#### Description
I am not entirely sure if this is because the room is encrypted, but in a encrypted PM if I open it and let it load the good amount of attachments in it, element goes to a white screen and just hangs at that.
```
<--- Last few GCs --->

[4:0x7a000000000]    95628 ms: Scavenge 516.6 (537.9) -> 508.8 (537.9) MB, 0.1 / 0.0 ms  (average mu = 0.960, current mu = 0.938) allocation failure
[4:0x7a000000000]    95634 ms: Scavenge 516.6 (537.9) -> 508.8 (537.9) MB, 0.1 / 0.0 ms  (average mu = 0.960, current mu = 0.938) allocation failure
[4:0x7a000000000]    95641 ms: Scavenge 516.6 (537.9) -> 508.8 (537.9) MB, 0.1 / 0.0 ms  (average mu = 0.960, current mu = 0.938) allocation failure


<--- JS stacktrace --->
```
This is what shows up at the time of the crash.

#### Steps to reproduce
1. flatpak install flathub im.riot.Riot
2. flatpak run im.riot.Riot
3. Open an encrypted PM with large and many attachments.

#### Version information
OS: Fedora 33, flathub (system)
Version: 1.7.33 - element-desktop

**Comment by robintown** [comment] 2021-07-30 21:40
This sounds like a duplicate of https://github.com/vector-im/element-web/issues/18149. @fmlatghor are any of the attachments in that room large audio files?

**Comment by fmlatghor** [comment] 2021-07-30 21:48
Okay, it is a duplicate. Though I'm using an up-to-date release.

**Comment by robintown** [comment] 2021-07-30 21:52
Closing since this is fixed on develop and will be in the next release

**Comment by fmlatghor** [comment] 2021-07-30 21:53
Okay, thanks for letting know.

**Closed by robintown** 2021-07-30 21:52 UTC
