### ISSUE TITLE
Audio volume inconsistent in call when sharing desktop audio

### ISSUE THREAD

**Issue by Skyliegirl33** [vector-im/element-web#22531] opened 2022-06-10 21:18 UTC
### Steps to reproduce

1. Start a call
2. Use a monitor device for the input source
3. The audio volume for others will be inconsistent and change from very quiet to very loud

It should be noted that I know this isn't officially supported -- but as Discord and other applications have no such odd issue, it most certainly is Element specific.

#### What did you expect?
I expect audio volume to be consistent and not fly all over the place.
#### What happened instead?
The audio volume changes for no reason, independent of any volume settings.

### Operating system

Arch Linux

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### How did you install the app?

From the Arch repository

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-06-10 21:21
Duplicate of https://github.com/vector-im/element-web/issues/6278

**Closed by t3chguy** 2022-06-10 21:21 UTC
Labels: T-Defect
