### ISSUE TITLE
The desktop app for GNU/Linux constantly using ~12% of CPU

### ISSUE THREAD

**Issue by lboklin** [vector-im/element-web#3558] opened 2017-04-03 09:04 UTC
### Description

Official GNU/Linux desktop app runs at a constant ~12% CPU usage under KDE Neon 5.9. 

At first I believed it had something to do specifically with my account, because the same CPU usage was seen while riot.im/app was opened in a Firefox tab, but went down significantly if I opened a private browsing session and stayed logged out. Additionally, my gf's app runs as it should on her laptop running the exact same system environment and package versions. On that same laptop and that same riot-web app binary but in my own user session and riot user account, the same performance issues are displayed as on my own PC.

However, further investigation gave inconsistent data, and riot.im/app in a non-private browsing session now later seems to alternate between 0% and ~8%. The desktop app remains at a constant 12% whether I'm logged in or not.

I have tried reinstalling and purging the configs and using nativefier to wrap the dev version as an electron app. Neither made a difference and it stayed at ~12% CPU usage.  

(Just as I'm about to submit this, it suddenly starts behaving. In other words, I have no idea of how to reproduce this.)

Log: Not sent (nu such feature found in the Settings page).

![System monitor's process overview](https://cloud.githubusercontent.com/assets/6375669/24602237/40d4bb5e-185c-11e7-9eee-696ae19dbd06.png)
![`strace` of process](https://cloud.githubusercontent.com/assets/6375669/24602244/466f4782-185c-11e7-8d2a-819ddd7aad13.png)
![CPU profile report](https://cloud.githubusercontent.com/assets/6375669/24602438/0dac7b4e-185d-11e7-9c60-6ff50ca84c5c.png)

### Version information

- **Platform**: Desktop
- **OS**: KDE Neon 5.9, all up to date.
- **Version**: 0.9.7

**Comment by ara4n** [comment] 2017-04-04 16:41
This was reliably chewing 12% cpu idling with all the time going into chromium itself (as `(program)`), but obviously there's some weirdness happening.

Totally spurious idea: i wonder if Chromium was doing some weird background task like downloading certificate transparency data?

**Comment by kittykat** [comment] 2021-09-03 10:05
Closing as cannot reproduce this now and performance has been improved since this issue was filed. Please reopen or comment with @kittykat asking to reopen if anyone is still seeing this exact issue.

**Closed by kittykat** 2021-09-03 10:05 UTC
Labels: T-Defect, A-Performance, X-Cannot-Reproduce
