### ISSUE TITLE
Forwarded copies should not be deleted when a message is.

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#10924] opened 2019-09-20 17:19 UTC
I saw a nice picture, and forwarded it to another room.  Later the picture was deleted in the original room - and it also disappeared in the other room.  This is unexpected behaviour and should not happen.  At the best, when deleting a message, it should ask: 'Delete forwarded copies too?'.

Edit: the message is gone for me, in Riot Desktop - but another member sees it on her iPhone.
For me there is a single empty line , and the button ribbon that appears on hovering only has the three vertical dots.

**Comment by jamazi** [comment] 2020-01-14 15:37
Confirmed

**Comment by tulir** [comment] 2021-01-20 15:18
This is a bug. Forwarded copies aren't linked to the original in any way in the protocol, but Element Web seems to reuse some internal structures that cause forwards to become empty when the original is redacted. It seems to only happen when forwarding to a different encrypted room, the source room doesn't matter.

**Comment by Biep** [comment] 2021-01-20 15:25
Linking would in itself be a good idea, but only with decent garbage collection/reference counting.  The code for replying could be re-used.
Actually there should be two mechanisms, like citing and replying.  The one "freezes" the message, and the other creates a dynamic link.  When uploading huge files, having only a link helps keep the memory load down.

**Comment by tulir** [comment] 2021-01-20 15:58
Forwarding already doesn't copy media content (that's the main reason forwarding exists), but media isn't linked to messages yet, so removing a message won't remove the media.

**Comment by maxkratz** [comment] 2021-05-17 16:00
> Element Web seems to reuse some internal structures that cause forwards to become empty when the original is redacted. It seems to only happen when forwarding to a different encrypted room, the source room doesn't matter.

After deleting a forwarded message (aka "the copy"), the bug occurred, too. I was able to remove/hide the original message by deleting the forwarded one.

**Comment by Destroyer** [comment] 2021-09-11 21:42
This is really annoying because if somebody else deletes your forwarded message, you don't even notice that it happened in other chats - there's no event information about that

**Comment by HarHarLinks** [comment] 2022-02-22 23:09
I'm hitting this in Element Nightly version: 2022022001
Olm version: 3.2.8

**Comment by 532910** [comment] 2022-02-23 12:03
Why this marked as minor?

**Comment by t3chguy** [comment] 2022-02-24 12:45
> Why this marked as minor?

Because

> To be perfectly clear: the message is not deleted in any other rooms. Reloading/restarting Element will bring it back.

**Closed** 2022-03-24 12:26 UTC
Labels: T-Defect, S-Minor, A-Timeline, O-Uncommon, A-Message-Forwarding
