### ISSUE TITLE
"Seen by" overflows with text when in a thread

### ISSUE THREAD

**Issue by moritzdietz** [vector-im/element-web#24541] opened 2023-02-15 16:15 UTC
### Steps to reproduce

When looking at this thread in TWIM: https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$ZzpgC2K0bqxhEsiDpYRzb1uNFvjdg5KbKP3MBV1QiTw?via=matrix.org&via=element.io&via=envs.net
I noticed that the "seen by" information is overflowing with the text of the message.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/7935536/219085711-fcb095fb-3a9b-41f8-9c93-aa7c688c0092.png">
<img width="519" alt="image" src="https://user-images.githubusercontent.com/7935536/219085733-ecb45580-9ae9-4f0b-b943-540dbe0aa244.png">

#### What did you expect?
That the "seen by" would be below the actual message
#### What happened instead?
It overflows with the message making it look weird

### Operating system

macOS

### Application version

Nightly Version 2023021501 (2023021501)

### Homeserver

Synapse 1.76.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-02-15 16:18
Duplicate of https://github.com/vector-im/element-web/issues/23569

**Closed by t3chguy** 2023-02-15 16:18 UTC
Labels: T-Defect
