### ISSUE TITLE
Thread sidebar got very confused - no scrolling, messages out of order, weird indentation

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#21952] opened 2022-04-27 10:53 UTC
### Steps to reproduce

In the company-internal channel i was looking at a thread. It was confusing because:
 - Axel's message at 11:23 was above Agustina's, which was the original message in the thread
 - A image in reply to a message was oddly formatted
 - Having hit "view in room" i was unable to scroll down the sidebar any more"

#### What did you expect?
 - messages in order
 - to be able to scroll down
#### What happened instead?
 - out of order and unable to scroll to bottom

### Operating system

Ubuntu

### Application version

Element version: 1.10.10 Olm version: 3.2.8

### How did you install the app?

deb repo

### Homeserver

EMS server

### Will you send logs?

Yes

**Comment by gsouquet** [comment] 2022-07-29 13:05
The indentation and the no scrolling issues have been fixed as far as I understand

The message ordering problem is a duplicate of https://github.com/vector-im/element-web/issues/21952

**Closed by gsouquet** 2022-07-29 13:05 UTC
Labels: T-Defect, S-Major, O-Occasional, A-Threads
