### ISSUE TITLE
Please fix that element won't ask another element user for resending/redoing encryption if we're both connected

### ISSUE THREAD

**Issue by ell1e** [vector-im/element-web#23512] opened 2022-10-17 22:55 UTC
### Steps to reproduce

1. We're both chatting in an encrypted chat. Suddenly I'm seeing this:

![Screenshot from 2022-10-18 00-46-17](https://user-images.githubusercontent.com/64124388/196297945-c1cfa335-3ac3-46c5-b160-7f2caa335db2.png)

2. We continue talking, the next messages work again, but here comes the catch:
3. As we talk, evidently have a working connection with working encryption again, the above error messages do *not* recover with the proper message contents

#### What did you expect?
If a secure encryption is established again with a sender client that has just minutes ago sent me messages from that same device and something about the keys failed, the protocol absolutely should fetch those again.

#### What happened instead?
Doesn't work, I just stare at errors and have to clumsily ask what was even said, and/or feel embarrassed again for making other people even use Matrix. And I even use Labs and hydrated backup device enabled, I don't know what failed with that with us both not even switching devices - and I think that's less relevant than the question why it doesn't *recover.* These failures would be so much less disruptive and sad if the clients just talked this out.

### Operating system

Fedora 36

### Application version

Element version: 1.11.8 Olm version: 3.2.12

### How did you install the app?

via flathub flatpak

### Homeserver

matrix.org, room is also on matrix.org, other user also uses matrix.org. room has more than us two as users though, some of those from somewhere else

### Will you send logs?

Yes

**Comment by uhoreg** [comment] 2022-10-19 21:22
Just to confirm, was the other user using the same device when sending both the undecryptable messages and the succesfully-decrypted messages?

**Comment by ell1e** [comment] 2022-10-19 21:36
If I understood their description right then yes. On my end no device switch either, it also was just minutes apart. Two messages mid conversation basically just failed out of the blue, it worked before and it worked after, but the two messages just never recovered.

**Comment by richvdh** [comment] 2022-11-18 18:22
Hi, thanks for the report.

I've studied the logs and it looks like the original problem was due to https://github.com/vector-im/element-web/issues/23792. In this case it looks to have been triggered by the sender using element in two tabs at once (not that that is an unreasonable thing to do!)

duplicate of #23792.

**Closed by richvdh** 2022-11-18 18:22 UTC
Labels: T-Defect, S-Major, A-E2EE, Z-UISI, O-Occasional
