### ISSUE TITLE
New notifications settings radio buttons are not always round

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18047] opened 2021-07-18 23:26 UTC
The radio buttons can end up being tall rounded rectangles, which then positions the center of the radio buttons too low by a few pixels.  Look carefully at the below.

![Screenshot 2021-07-19 at 00 25 13](https://user-images.githubusercontent.com/1294269/126085313-b6e87d2a-8861-490d-8abe-05b2b6effe03.png)

This on Eledesktop on macOS.

**Comment by ara4n** [comment] 2021-07-18 23:27
This section gets it right though:

![Screenshot 2021-07-19 at 00 27 00](https://user-images.githubusercontent.com/1294269/126085337-0285f53c-01d7-4386-a561-9c502448ba69.png)

**Comment by turt2live** [comment] 2021-07-18 23:41
"wtf"

**Comment by turt2live** [comment] 2021-07-19 04:08
I'm not able to reproduce this, but I'm also unable to get my hands on a Mac to test desktop/nightly properly. Safari, Chrome, Edge, Firefox, and Windows 10 all seem fine though.

If other people encounter this, please comment with system information. If possible, please also take a peek at what might be causing the extra 2px of vertical height.

**Comment by t3chguy** [comment] 2023-07-10 14:00
Closing due to unable to reproduce

**Closed by t3chguy** 2023-07-10 14:00 UTC
Labels: T-Defect, X-Cannot-Reproduce, Sponsored
