### ISSUE TITLE
In-thread read receipt appears on top of full-screen toggle in embedded videos

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#25350] opened 2023-05-12 08:51 UTC
### Steps to reproduce

1. Create a room with at least 2 users
2. Send a video in a thread
3. Get the other user to read the message (to get their read receipt to go down)

#### What did you expect?

The full-screen toggle of the video player is easily accessible.

#### What happened instead?

The read receipt appears on top, making it awkward and difficult to full-screen the video.

Not sure a defect is the most fitting label, I wasn't sure what to use, feel free to recategorise if needed.

 

https://github.com/vector-im/element-web/assets/5547783/8f4b8232-aa38-4ec0-adac-2072a28d1666

### Operating system

macOS Ventura (13.3.1)

### Browser information

Firefox 112.0.2

### URL for webapp

app.element.io

### Application version

Element version: 1.11.31, Olm version: 3.2.14

### Homeserver

abolivier.bzh

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-05-12 09:01
Duplicate of https://github.com/vector-im/element-web/issues/23576

**Closed by t3chguy** 2023-05-12 09:01 UTC
Labels: T-Defect

**Comment by babolivier** [comment] 2023-05-12 09:12
Ah thanks - I was looking specifically for video-related issues and couldn't find one.
