### ISSUE TITLE
warn if rooms have unsent messages

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18346] opened 2021-08-02 21:42 UTC
i just discovered a room with an unsent message from weeks ago which really should have sent. there was no badge or notif on the room to warn me it had unsent msgs stuck in it.

**Comment by aaronraimist** [comment] 2021-08-03 00:25
Duplicate of https://github.com/vector-im/element-web/issues/14181

**Closed by aaronraimist** 2021-08-03 00:25 UTC
