### ISSUE TITLE
Show message count badge instead of a dot for room with messages

### ISSUE THREAD

**Issue by rda0** [vector-im/element-web#15146] opened 2020-09-10 19:01 UTC
Message count badges are beautiful and useful, but they are not shown for rooms set to `Mentions & Keywords` or if notifications for rooms are turned off in the defaults. Instead these rooms show a small dot:

![image](https://user-images.githubusercontent.com/6731714/92780203-140f7e80-f3a3-11ea-979f-9363f63b5c63.png)

- I think this would improve FTUE: When the new room list arrived, I did not know what the dot means. I did not even see the dot until someone told me that there is one ;)
- The larger message count badge would make it clearer to see which rooms have messages when scanning the roomlist.
- The message count would help checking what is going on. Is the count increasing? How many new messages do I have to expect when selecting the room?
- The overall look of the roomlist would be cleaner

**Describe the solution you'd like**
I do not see a downside in replacing the dot with a message count badge but a configuration option would be great too.

**Comment by turt2live** [comment] 2020-09-10 19:04
Duplicate of https://github.com/vector-im/element-web/issues/14261

**Closed by turt2live** 2020-09-10 19:04 UTC
Labels: suggestion
