### ISSUE TITLE
Encrypted history is "hidden" even after the keys have been shared from another room member

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#18029] opened 2021-07-16 17:50 UTC
#### Description

I joined `!CiocXwxWnCxeGovDNs:gruenhage.xyz` which is an encrypted room with shared history (Members only (since the point in time of selecting this option), which was selected soon after the creation of the room). Upon joining, I saw this:

![image](https://user-images.githubusercontent.com/1342360/125988523-41b4eb95-b3ce-4c6b-9dfc-de00f8e14d81.png)

with the timeline above that being blank. I read @tulir's message and saw that he was replying a message I could decrypt, but couldn't see. Upon clicking the image in the reply, I was brought up to the image event and suddenly all the messages around it appeared, and I could read the whole room history.

I know that Element Web tries to hide messages that are undecryptable after you join a room - but does it actually then proceed to show them once you've decrypted them?

#### Steps to reproduce

- Be invited to an existing, encrypted room with history sharing enabled.
- Join the room - you can only see messages up to the point you were invited.
- Trigger some way to view past messages - probably just clicking on another room and back would work.
- See the old messages and wonder why you couldn't see them before.

Logs being sent: yes

#### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: Nightly 2021071601

**Comment by t3chguy** [comment] 2021-07-16 18:03
> but does it actually then proceed to show them once you've decrypted them?

No, does switching room away and back fix this issue?
I was sure there was another issue tracking this but cannot find it right now

**Comment by robintown** [comment] 2021-07-19 20:47
Duplicate of https://github.com/vector-im/element-web/issues/16983

**Closed by robintown** 2021-07-19 20:47 UTC
Labels: T-Defect
