### ISSUE TITLE
Timeline jump after following a reply link

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#20154] opened 2021-12-13 09:47 UTC
### Steps to reproduce

1. In a room, looking at a reply
2. Click the original message within the reply
3. We scroll to the original message, as expected
4. Wait about half a second
5. The scroll position jumps elsewhere

This video shows me clicking a reply, which scrolls to the right place (a video) and when I am about to click the video, it jumps away, without me clicking anything.
![timeline-jump](https://user-images.githubusercontent.com/76812/145789063-5c53197f-3a34-4b43-a521-185ad9e39f33.gif)

#### What did you expect?

I expect to keep looking at the same thing if I didn't click anything

#### What happened instead?

The timeline spontaneously jumped to a different scroll position.

### Operating system

Ubuntu MATE 21.10

### Browser information

Firefox 95.0 (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.9.6 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by robintown** [comment] 2022-04-09 01:57
Since this is caused by the previous behavior of un-highlighting events on scroll, this is fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8263

**Closed by robintown** 2022-04-09 01:57 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Timeline, O-Frequent, A-Timeline-Jumpy-Scroll
