### ISSUE TITLE
Composer forgets selection if formatting when all selected by mouse

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23613] opened 2022-10-26 15:27 UTC
### Steps to reproduce

1. Enable the new composer
2. Type some text
3. Select all using the mouse/touchpad
4. Click bold

#### What did you expect?

All test still selected

#### What happened instead?

Composer forgets selection

![composer1](https://user-images.githubusercontent.com/6216686/198068346-461cf776-7f91-4602-b5fe-906f91f2e878.gif)

### Operating system

Ubuntu 22.04.1 LTS

### Browser information

Firefox 106.0.1 (64-bit)

### URL for webapp

https://develop.element.io/

### Application version

Element version: 12bde9a51421-react-0f1738b09875-js-dddc0aeccb32 Olm version: 3.2.12

### Will you send logs?

No

**Comment by andybalaam** [comment] 2022-11-08 16:18
This is caused by a bug with backwards selections (dragging from right to left).

This is fixed in matrix-rich-text-editor so should be fixed next time Element Web upgrades to the latest release.

I'm not sure, but this might be the fix https://github.com/matrix-org/matrix-rich-text-editor/pull/230

**Comment by florianduros** [comment] 2022-11-16 15:30
Fixed with https://github.com/matrix-org/matrix-react-sdk/pull/9573

**Closed by florianduros** 2022-11-16 15:30 UTC
Labels: T-Defect, S-Minor, O-Occasional, Z-Labs, A-Rich-Text-Editor
