### ISSUE TITLE
Quick way to delete messages with a single click keybinding

### ISSUE THREAD

**Issue by jjj333-p** [vector-im/element-web#21786] opened 2022-04-14 04:36 UTC
#### What would you like to do?
When you hold down the alt key or some kind of keybinding, the little menu options when hovering the mouse includes a delete button that has no confirmation prompt. 

#### Why would you like to do it?
When you want to delete several messages it is a hassle to 3 dots > delete > confirm, and it would be nice to have some keybinding to be able to delete without a confirmation prompt, similar to how on discord if you hold down the shift key it does what I described in "What would you like to do?" Another solution to this could also be perhaps to have a way to select multiple messages? 

when holding shift while hovering mouse on a message on discord:
![image](https://user-images.githubusercontent.com/94018608/163314407-d370f658-5a22-4de3-ae4b-d055f77c9c59.png)

### Have you considered any alternatives?

perhaps there could be a way to select multiple messages and perform actions on them in bulk?

**Comment by SimonBrandner** [comment] 2022-04-14 07:34
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/18711

**Closed by SimonBrandner** 2022-04-14 07:34 UTC
Labels: T-Enhancement
