### ISSUE TITLE
Crash when Joining from Explore Rooms

### ISSUE THREAD

**Issue by bronson** [vector-im/element-web#23064] opened 2022-08-12 02:22 UTC
### Steps to reproduce

1. I'm in the Veloren space: https://matrix.to/#/#veloren-space:fachschaften.org
2. I click the `+` to the right of "Veloren" and choose Explore Rooms.
3. I Join a room. This issue seems to happen for most rooms but not all -- some rooms were added successfully.
4. It crashes with "Something went wrong!"
5. When I "Clear cache and reload", I see that the room has been successfully added.

#### What did you expect?

The room to get added without crashing.

#### What happened instead?

This crash.

### Operating system

MacOS

### Application version

Element 1.11.2

### How did you install the app?

Downloaded from https://element.io/get-started

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2022-08-12 05:52
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by SimonBrandner** 2022-08-12 05:52 UTC
Labels: T-Defect
