### ISSUE TITLE
"update" doesn't restart element

### ISSUE THREAD

**Issue by wsmwk** [vector-im/element-web#17623] opened 2021-06-10 23:20 UTC
### Description

"update" doesn't restart element after updating

### Steps to reproduce

- element displays "update available" prompt - dismiss or update
- click update

Results: element appears to have updated, but is not running

Expectation: I expected element to start up on it's own after the update

This happened when updating to 1.7.29, and also when updating from 1.7.29 to 1.7.30

Logs being sent: no (I'd be happy to send logs, but I don't find any menu item to do it.

All versions.  Currently 1.7.30

- **Platform**: desktop

For the desktop app:
- **OS**: macOS
- **Version**: 11.4.0

**Comment by t3chguy** [comment] 2021-06-10 23:20
Duplicate of https://github.com/vector-im/element-web/issues/12433

**Closed by t3chguy** 2021-06-10 23:20 UTC
Labels: T-Defect
