### ISSUE TITLE
Personalize homeserver in invitation mail

### ISSUE THREAD

**Issue by stemy2** [vector-im/element-web#16062] opened 2021-01-03 11:59 UTC
**Is your suggestion related to a problem? Please describe.**
I sent an invitation mail to somebody, who was strangely unable to create an account. It appeared that when clicking on the invitation link, he is asked to create an account on the default matrix server, event if they were sent from my own homeserver so all the usernames he tried were already taken. I had to explain that he had to change the server setting to my own homeserver, wich is pretty complicated for a newbie like him.

**Describe the solution you'd like**
An ability to send an invite mail that allows to use custom server by default so the user doesn't have to change the server on the page where he is redirected with the invite link.

**Describe alternatives you've considered**

**Additional context**
Picture #1
![Screenshot_20210103_125251](https://user-images.githubusercontent.com/22192600/103477866-b4f2d100-4dba-11eb-8b53-de53fcc937d9.png)

Picture #2
![screenshot](https://user-images.githubusercontent.com/22192600/103477868-c045fc80-4dba-11eb-9796-8bcb84cecbf3.png)

When a user click on invitation link, he is redirected to Picture #1. To have the situation on the Picture #2, he has to do a manual modification. I'd like to make an invitation link that redirects directly to Picture #2 without manual modification from the user.

**Comment by t3chguy** [comment] 2021-01-03 12:02
Related https://github.com/vector-im/element-web/issues/5923

**Comment by t3chguy** [comment] 2021-01-03 12:02
Duplicate of https://github.com/vector-im/element-web/issues/12472

**Closed by t3chguy** 2021-01-03 12:02 UTC
Labels: suggestion
