### ISSUE TITLE
Unable to complete sign-up with Chrome - error displaying captcha.

### ISSUE THREAD

**Issue by tim-seoss** [vector-im/element-web#15410] opened 2020-10-07 15:18 UTC
### Unable to complete sign-up with Chrome - error displaying captcha.

Whilst trying to complete a user sign-up in element web, on macOS Chrome, the following is displayed:
```
This homeserver would like to make sure you are not a robot

[Empty boxes]
Error: reCAPTCHA has already been rendered in this element
```

### Steps to reproduce

- Attempt to sign up to more than one Matrix account (on the Matrix.org home server) in succession with Chrome on macOS
- At captcha challenge, the error described is displayed

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome - macOS Chrome Version 85.0.4183.121 (Official Build) (64-bit)
- **OS**: macOS
- **URL**: app.element.io

**Comment by t3chguy** [comment] 2020-10-07 15:23
Do you have any chrome extensions? Does the error occur if you run in incognito?

**Comment by tim-seoss** [comment] 2020-10-07 15:30
No chrome extensions.  After going back to the site later, the error did not occur (but this I think was because the captcha flow wasn't triggered - it presumably is a rate-limit thing?) I am reporting this error on behalf of another user, sorry, omitted the screenshot from the original message.  Please see attached:
<img width="1995" alt="Screenshot 2020-10-06 at 12 45 53" src="https://user-images.githubusercontent.com/5011760/95352689-6072af00-08ba-11eb-8791-53fa9daa6a00.png">

**Comment by tim-seoss** [comment] 2020-10-07 15:31
Hmm, looks like there are extensions installed from that screenshot, I'll check with the user what they are.

**Comment by tim-seoss** [comment] 2020-10-07 16:07
See attached screen-shot for the user's Chrome Extensions
<img width="1957" alt="Screenshot 2020-10-07 at 16 54 12" src="https://user-images.githubusercontent.com/5011760/95357218-7fc00b00-08bf-11eb-9213-1552c367e42c.png">

**Comment by tim-seoss** [comment] 2020-10-07 16:08
See attached screen-shot for the user's Chrome Extensions
<img width="1230" alt="Screenshot 2020-10-07 at 16 54 12" src="https://user-images.githubusercontent.com/5011760/95357391-b8f87b00-08bf-11eb-9fcc-fe5785e143f9.png">

**Comment by t3chguy** [comment] 2020-10-07 16:10
Best if they can try with them disabled, like in incognito.#

> Does the error occur if you run in incognito?

**Comment by tim-seoss** [comment] 2020-10-07 16:15
Sorry, I won't be able to get this user to retry because they're already unimpressed with Matrix / Element due to numerous UI/UX sharp edges and bugs.  Also I believe that this captcha isn't on the normal sign-up path, but is only triggered as part of a rate-limiting / anti-abuse path (is that correct?), and so would be hard to reproduce anyway?

I appreciate your point about extensions, but the above list looks reasonably innocuous / non-invasive.

**Comment by t3chguy** [comment] 2020-10-07 16:18
Nope, captcha is always on the registration path if the homeserver has it configured. `matrix.org` is one such server.
I guess nothing stops a server doing it based on rate-limiting but existing software doesn't

**Comment by tim-seoss** [comment] 2020-10-07 16:24
Thanks. This was pointing at matrix.org.  I can try and reproduce this myself, but I don't have a Mac, so this seems like it might not be a good idea.

The user later succeeded at the sign-up (without using Incognito mode I believe), so it looks like this is something intermittent.

Without knowing the underlying implementation, perhaps this is some sort of race internal on code running on the browser, or possibly something triggered by network errors, server latency etc.

**Comment by tim-seoss** [comment] 2020-10-07 16:26
Perhaps it would be possible to trigger this error in a reproducible way via a code modification, and then implement a retry, or at the very least a more friendly, helpful error message suggesting that the user retry and/or try to use an incognito window?

**Comment by jryans** [comment] 2021-02-08 15:48
At the moment, I am not quite sure what to do with this report, as so far we only have one report of this, and it would be ideal if we could find a way to reproduce or understand the cause.

Perhaps the related issue https://github.com/vector-im/element-web/issues/16379 will be enlightening once resolved.

**Comment by yichangshengwu** [comment] 2022-06-19 23:53
Tried both browsers vivaldi and firefox,
Tried changing servers.
It's always been "This homeserver would like to make sure you are not a robot."
I didn't even see the word "google recaptcha"!
There is no other error message other than that sentence...

**Comment by t3chguy** [comment] 2023-06-08 12:25
Closing due to no repro in 2 years

**Closed by t3chguy** 2023-06-08 12:25 UTC
Labels: T-Defect, P2, S-Major, A-Registration, X-Needs-Investigation
