### ISSUE TITLE
Bad pill rendering for messages notifying userid containing a slash

### ISSUE THREAD

**Issue by c-cal** [vector-im/element-web#17105] opened 2021-04-29 09:20 UTC
### Description

- userid are truncated at slash position, preventing displaynames from being rendered.
- clicking on the pill opens a non-existent user profile.

### Steps to reproduce

- join a room with a user whose userid contains a slash
- write a message to notify them => no obvious problem with suggested pills

![image](https://user-images.githubusercontent.com/57274151/116525621-00386e80-a8d9-11eb-91bd-a143c423b5db.png)

- message composition also seems correct

![image](https://user-images.githubusercontent.com/57274151/116526331-c74cc980-a8d9-11eb-9a47-2aac4be51b25.png)

- **bad rendering once the message is sent**

![image](https://user-images.githubusercontent.com/57274151/116526445-e6e3f200-a8d9-11eb-9d48-15d8fde0abc1.png)
![image](https://user-images.githubusercontent.com/57274151/116528296-f401e080-a8db-11eb-9cb4-e4d55f2d6690.png)

- **wrong user profile**

![image](https://user-images.githubusercontent.com/57274151/116528417-1ac01700-a8dc-11eb-8b92-47fe40d2af36.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox
- **URL**: app.element.io

**Comment by t3chguy** [comment] 2021-04-29 09:25
Related https://github.com/vector-im/element-web/issues/10994

**Comment by aaronraimist** [comment] 2021-12-19 16:38
Duplicate of https://github.com/vector-im/element-web/issues/6381

**Closed by aaronraimist** 2021-12-19 16:38 UTC
Labels: T-Defect, A-Pills
