### ISSUE TITLE
"Sort by activity" order in "People" section of room is lost after updating profile picture

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#18068] opened 2021-07-20 04:39 UTC
#### Description

I have the left panel's "People" section, sorted by "Activity" - it shows recently chatted people at top right. But after I updated my profile picture (avatar), they are becomes mixed randomly. And seems same will happen if I change other profile fields like display name...

Seems this happens because they becomes sorted by timestamp of recent event with my own avatar update.

And same problem is with "Rooms" section too, but that is not too conspicuous, because rooms have higher volume of activity to quickly becomes re-ordered right by other events.

Is it possible to exclude that type of events from "sort by activity" order?

#### Steps to reproduce

- Set "People" section sorted by activity
- Talk with some people and see those room at top of the list.
- Change your avatar
- See that in "People" section rooms becomes sorted by random order, and all your recent chats are scattered all over the list.

#### Version information
- **Platform**: web
- **URL**: develop.element.io

**Comment by SimonBrandner** [comment] 2021-07-20 06:14
Duplicate of https://github.com/vector-im/element-web/issues/110

**Closed by SimonBrandner** 2021-07-20 06:14 UTC
Labels: T-Defect
