### ISSUE TITLE
Threads list empty

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21822] opened 2022-04-16 11:49 UTC
### Steps to reproduce

1. Enabled threads beta
2. start thread on 2 messages
3. go "back" from thread panel to threads panel

#### What did you expect?
list of threads

#### What happened instead?
- at first the panel was not just empty, but the element that is supposed to hold the list of threads `class="mx_AutoHideScrollbar mx_ScrollPanel mx_RoomView_messagePanel mx_GroupLayout mx_MessagePanel_narrow"` was not there at all(!)
- then I tried switching back and forth to another room once. after a sec of being back in the original room, above element loaded, but was empty with the usual "this is where your threads would be if there were any" message
- then eventually after dozens more seconds the threads loaded

### Operating system

arch

### Application version

Element Nightly version: 2022041601 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.56

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-16 23:01
Duplicate ofhttps://github.com/vector-im/element-web/issues/21737

**Closed by robintown** 2022-04-16 23:01 UTC
Labels: T-Defect, S-Major, A-Threads

**Comment by HarHarLinks** [comment] 2022-04-17 10:49
> Duplicate ofhttps://github.com/[/issues/21737](https://github.com/vector-im/element-web/issues/21737)

I don't completely understand the very technical description in that issue, are you certain it includes my first point of the missing element resulting in proper broken (not just empty) UI?

**Comment by robintown** [comment] 2022-04-17 13:47
Oh, right, that point about the panel being completely empty is tracked as https://github.com/vector-im/element-web/issues/21335
