### ISSUE TITLE
Rooms set to "mention only" stop sending notifications after a while

### ISSUE THREAD

**Issue by trosel** [vector-im/element-web#6609] opened 2018-04-25 21:31 UTC
### Description

Notifications work fine for DM conversations and for rooms set to "all messages"

But when you set a room to "mentions only", it only works correctly for a couple hours and then you stop getting notifications. 

### Steps to reproduce

- Set a room to "mentions only" notification level
- ask a friend to mention you and send normal messages

You will get notification bubbles in the room accurately for an hour or two, but eventually they will stop showing up. You will no longer see notification bubbles next to the rooms with the number of notifications.

Again, this doesn't seem to be an issue with "all messages" rooms. Only with "mentions only" rooms.

Log: not sent

### Version information
- **Platform**: desktop
- **OS**: Windows
- **Version**: 0.14.1

**Comment by aaronraimist** [comment] 2020-07-15 23:58
@trosel Is this still an issue for you? I've never experienced this.

**Comment by kittykat** [comment] 2021-09-14 09:05
I am going to close this issue for now as we cannot reproduce it. Please reply with @kittykat if it is still occurring for you so that I can reopen the issue.

**Closed by kittykat** 2021-09-14 09:05 UTC
Labels: T-Defect, S-Major, A-Notifications, O-Low
