### ISSUE TITLE
Augmenting invitations with personal information

### ISSUE THREAD

**Issue by madduck** [vector-im/element-web#7477] opened 2018-10-11 03:28 UTC
As I invite someone to a room, I might want to provide some additional information and/or background as to why they should join. Right now, I need to do so in a separate chat (which may be a chicken-egg thing where no such chat exists), or use another medium.

I understand this could be an avenue for spam, but I am sure we could find ways to mitigate this. Point being: please let me augment an invitation with a personal message, similar to how networks like Xing or LinkedIn allow me to add a comment to a contact request.

Thanks,
-m

Possibly related:  #6999 #3484

**Comment by aaronraimist** [comment] 2018-10-11 03:32
See [this convo](https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$15392280075320ewvhC:madduck.net) for an explanation for why room previews may not always be enough

**Comment by turt2live** [comment] 2018-10-11 04:00
I can't find the ticket anymore, but somewhere out there is a thing for "include the topic in the invite_room_state" - this could probably be used to communicate some sort of motive.

Equally, there's https://github.com/vector-im/riot-web/issues/4958 and https://github.com/vector-im/riot-web/issues/807 which might also be good alternatives.

**Comment by aaronraimist** [comment] 2018-10-11 04:09
The use case @madduck brought up for why peaking doesn't solve the problem is what about when you are inviting the user to a large existing room like #matrix:matrix.org for example. Room peaking ~~works great~~ would work great (or not: https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$15392277915315sPZtA:madduck.net) for new rooms but not for existing rooms.

**Comment by robintown** [comment] 2021-07-16 04:13
Invite reasons are this feature - closing in favor of #17035 since that issue has more concrete/up to date details

**Closed by robintown** 2021-07-16 04:13 UTC
Labels: A-Invite, P2, T-Enhancement
