### ISSUE TITLE
Attempting to join a room from a space asks me to open an issue

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element-web#22924] opened 2022-07-23 18:49 UTC
### Steps to reproduce

1. I joined `#debian-space:matrix.debian.social`
2. I clicked join next to "Debian Women"
3. I was asked to open an issue and send debug log.

#### What did you expect?

I expected to be joined to the room.

#### What happened instead?

I was asked to open an issue and send debug log.

### Operating system

Fedora 36

### Browser information

Microsoft Edge Versio 103.0.1264.62 (Virallinen koontiversio) (64-bittinen)

### URL for webapp

develop.element.io

### Application version

Element-versio: b3b8e2e0a20f-react-787ace9dc5ed-js-5367ee18fbd2
Olm-versio: 3.2.12

### Homeserver

[pikaviestin.fi](http://pikaviestin.fi/) is on Synapse 1.62.0

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2022-07-25 13:06
Did you manage to join the room in any other way?

**Comment by Mikaela** [comment] 2022-07-25 15:00
I didn't try as I was distracted by the prompt to open an issue and then I forgot it. Did the logs shed any light on this?

**Comment by t3chguy** [comment] 2022-07-26 07:24
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-07-26 07:24 UTC
Labels: T-Defect, X-Needs-Info, S-Major
