### ISSUE TITLE
incoming phantom call on startup

### ISSUE THREAD

**Issue by eladyn** [vector-im/element-web#21294] opened 2022-03-03 15:04 UTC
This bug might be similar to the ones mentioned in #18454 or #20954, but is different enough that I decided to open a new issue. Feel free to integrate this into one of the others, if you think that this would fit it better.

### Steps to reproduce

1. don't know how to reproduce that reliably: Have a call in the (recent?) timeline that causes this behavior.
2. Start/Reload Element with a different room than the one actually causing the problem opened by default (at least that seems to increase the probability.)
3. Switch to the room with the problematic call.
4. Watch the room history load.

&rarr; receive a phantom call

#### What did you expect?

Not receiving call notifications, when I'm not actually being called.

#### What happened instead?

I'm receiving a phantom call.

#### Additional Information

Reproducing this a few times causes the following to appear in the timeline (Element Android):

![grafik](https://user-images.githubusercontent.com/59307989/156589916-f12f2672-d550-42be-adb7-70d9db2be8ef.png)

Viewing the decrypted event source shows that they all reference the same call:
```json
{
    "room_id": "!something:some.thing",
    "type": "m.call.reject",
    "content": {
        "version": 1,
        "call_id": "e81b868d-8638-4ec5-ac23-d610888a82e0",
        "party_id": "SOMETHING"
    }
}
```

After deleting the call that caused all this, the issue isn't reproducible anymore.

Note that all this has only yet been reproducible on Element Desktop.

### Operating system

Arch Linux

### Application version

Element version: 1.10.6 Olm version: 3.2.8

### How did you install the app?

https://flathub.org/apps/details/im.riot.Riot

### Homeserver

1.53.0

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-03-03 16:35
@eladyn, do you agree with this being a duplicate of https://github.com/vector-im/element-web/issues/4607?

**Comment by eladyn** [comment] 2022-03-03 21:09
The majority of the comments in #4607 seem to suggest that the other issue is actually about Element only ringing for a short time at startup. In my case though, the ringing doesn't stop until I either accept or decline the call. I'm not sure if the original poster was describing my issue or the short ringing (https://github.com/vector-im/element-web/issues/4607#issue-243450235). If the former is true, feel free to close this.

**Comment by turt2live** [comment] 2022-06-15 19:08
Duplicate of https://github.com/vector-im/element-web/issues/4607

**Closed by turt2live** 2022-06-15 19:08 UTC
Labels: T-Defect, S-Major, A-VoIP, O-Uncommon
