### ISSUE TITLE
Display name changes (& other state events?) intermittently cause the room to appear unread

### ISSUE THREAD

**Issue by benbz** [vector-im/element-web#20662] opened 2022-01-21 08:38 UTC
### Steps to reproduce

1.EleWeb/EleDesktop is open and there are no rooms appearing unread
2. Restart the client
3. Some rooms appear unread
4. Visit the room and all the messages since my read marker are users changing name

Whether the room is unread or not seems to depend on the client instance - it will appear unread in a particular Element instance but in others it won't.

#### What did you expect?

* Restarting Element should not show rooms as unread unless new messages have been posted in the mean time
* Rooms should be consistently marked as read across all instances.

#### What happened instead?

* Restarting Element sometimes shows rooms as unread and when visiting those rooms it appears just to be display name changes
* Starting up another Element Web/Desktop client whilst this room is unread doesn't necessarily show the same room as unread

### Operating system

Ubuntu Linux & Mac

### Application version

Element 1.9.9

### How did you install the app?

Deb for Linux, Manually downloaded for MAc

### Homeserver

banzan.uk

### Will you send logs?

Yes

**Comment by benbz** [comment] 2022-01-21 08:42
Updating my read marker in one of the involved rooms (even on a client that doesn't show the room as unread) marks the room as unread on all clients.

**Comment by jakewb-b** [comment] 2022-03-21 09:12
I think I experienced the same issue when changing my name recently pre and post annual leave. On both occasions, on Element Nightly, I had several unread rooms at the point when I changed my name. After changing my name, all rooms showed as read (i.e. no black dots on room thumbnails, or bolded room names in room list).

**Comment by t3chguy** [comment] 2022-03-21 09:17
Duplicate of https://github.com/vector-im/element-web/issues/15860

**Closed by t3chguy** 2022-03-21 09:17 UTC
Labels: T-Defect, S-Minor, A-Room-List, A-Read-Marker, X-Needs-Investigation, O-Occasional
