### ISSUE TITLE
Missing session data

### ISSUE THREAD

**Issue by iptq** [vector-im/element-web#23623] opened 2022-10-26 22:37 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

    Open the element desktop app.

2. What do you click?

    Nothing.

#### What did you expect?

The main application view with my channels on the left and the space for messages on the right.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1700346/198150717-d3871149-113f-4b88-a5fc-aaf86fc771bb.png)

I am not low on disk space, nor am I in a browser. Fortunately, this is not the only instance of Element so I can still retrieve encryption keys but it asked to file an issue so here I am.

### Operating system

NixOS

### Application version

Element version: 1.10.13 Olm version: 3.2.8 (I had to sign in again to view this information, this was not available at the sign in screen or using `--version` at the command line)

### How did you install the app?

Package `element-desktop` from Nixpkgs

### Homeserver

Synapse 1.58.1 on Debian 4.19.235-1

### Will you send logs?

No

**Comment by iptq** [comment] 2022-10-26 22:40
Issue template was very limiting so I'll just add here that I think it might be due to me downgrading Element Desktop since I changed my Nixpkgs. Does Element not have a stable on-disk format? This is very concerning for me going forward.

Also, here are the logs, but they don't seem very useful:

[rageshake.tar.gz](https://github.com/vector-im/element-web/files/9874123/rageshake.tar.gz)

**Comment by ilieandriuta** [comment] 2022-10-27 05:47
Hi! I just upgraded to the last Element app 1.11.12 on Windows last night and in the morning when I opened Element I got:

![image](https://user-images.githubusercontent.com/32512703/198201611-d44b0f6f-6433-4562-b8e3-082e54f26e27.png)

I've never encountered such an error until now (using Element since long time). Is there a way I can recover my session?

Thank you!

**Comment by ilieandriuta** [comment] 2022-10-27 06:49
It seems the matrix server I've been using was down. Now it seems to be working again. Thanks!

**Comment by t3chguy** [comment] 2022-10-31 15:59
Duplicate of https://github.com/vector-im/element-web/issues/23123

**Comment by t3chguy** [comment] 2022-10-31 16:00
@ilieandriuta that is a different issue - https://github.com/vector-im/element-web/issues/23634

**Closed by t3chguy** 2022-10-31 15:59 UTC
Labels: T-Defect, S-Critical, A-E2EE, O-Uncommon
