### ISSUE TITLE
Something wrong happens when I join a sub-space

### ISSUE THREAD

**Issue by nimau** [vector-im/element-web#24142] opened 2023-01-03 17:30 UTC
### Steps to reproduce

1. I've searched for a space to join (using "France" as keyword)
2. I've joined a sub-space from the search result
3. The application prompt me to report a log for an unexpected error

### Operating system

MacOS 13.1

### Browser information

Chrome Version 108.0.5359.124 (Official Build) (arm64)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.17
Olm version: 3.2.12

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2023-01-03 19:23
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by SimonBrandner** 2023-01-03 19:23 UTC
Labels: T-Defect
