### ISSUE TITLE
ability to hop back and forth between images in the lightbox

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17451] opened 2021-05-24 08:34 UTC
element mobile lets you swipe left & right to navigate images in a room. arrow keys should do the same in eleweb when you're viewing an image.

**Comment by t3chguy** [comment] 2021-05-24 08:35
Duplicate of yourself in 2015 :D 

Duplicate of https://github.com/vector-im/element-web/issues/337

**Closed by t3chguy** 2021-05-24 08:35 UTC
