### ISSUE TITLE
If two people make a call at the same time, the state of the call will be broken

### ISSUE THREAD

**Issue by smorimoto** [vector-im/element-web#17418] opened 2021-05-20 18:43 UTC
### Description

As the title says.

### Steps to reproduce

1. User A makes a call
1. User B makes a call
1. User A ends own call
1. User B ends own call
1. The Element client continues to ring the call bell

### Logs being sent

No.

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Windows
- **Version**:
  - Element version: 1.7.28
  - olm version: 3.2.1

**Comment by robintown** [comment] 2021-05-21 00:59
This sounds like #17393, which should be fixed in 1.7.29rc1

**Comment by smorimoto** [comment] 2021-05-21 01:02
You may be right. Let me try that tomorrow evening.

**Comment by robintown** [comment] 2021-05-21 01:03
Wait I must be wrong, #17393 never got past staging

**Comment by SimonBrandner** [comment] 2021-05-21 08:14
I think I might have seen this in the wild before :thinking: Probably even before my `CallFeed` rewrite

**Comment by SimonBrandner** [comment] 2021-05-21 08:15
@smorimoto, logs might actually help in this case. Could you please send them?

**Comment by t3chguy** [comment] 2021-05-21 08:19
> This sounds like #17393, which should be fixed in 1.7.29rc1

It doesn't look to have made it into any RC yet.

![image](https://user-images.githubusercontent.com/2403652/119105818-a0d00900-ba15-11eb-9d17-09ba982d52fc.png)

only available on /develop

**Comment by SimonBrandner** [comment] 2021-05-21 08:20
> > This sounds like #17393, which should be fixed in 1.7.29rc1
> 
> It doesn't look to have made it into any RC yet.
> 
> ![image](https://user-images.githubusercontent.com/2403652/119105818-a0d00900-ba15-11eb-9d17-09ba982d52fc.png)
> 
> only available on /develop
> 
> [matrix-org/matrix-js-sdk#1690](https://github.com/matrix-org/matrix-js-sdk/pull/1690) looks related and this _is_ in staging

This was discovered in 1.7.28

**Comment by SimonBrandner** [comment] 2021-05-21 08:22
> matrix-org/matrix-js-sdk#1690 looks related and this is in staging - would be good if reporter could retry on develop.element.io

Related but the problem was something a bit different there but yeah would be great to try on develop

**Comment by smorimoto** [comment] 2021-05-25 18:54
I don't have enough time to confirm it, so it would be great if someone could confirm that! If necessary.

**Comment by SimonBrandner** [comment] 2021-08-18 08:16
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.

**Closed by SimonBrandner** 2021-08-18 08:16 UTC
Labels: T-Defect, X-Needs-Info, P1, A-VoIP
