### ISSUE TITLE
Make themes possible

### ISSUE THREAD

**Issue by insaneriotpoodle** [vector-im/element-web#16915] opened 2021-04-11 19:53 UTC
#### Is your suggestion related to a problem? Please describe.
Make themes more accessible for non IT people.
Not a problem with how the thing is but with how it looks.

#### Describe the solution you'd like.
A screen to change how element looks. Where I can change colours, places and stuff and save it. A way for people to send their self created themes to each other. So I can click on it and get asked if I want to make that thing my theme for element. I dont know code.

#### Describe alternatives you've considered.
???

#### Additional context
Am I even in the right place here? Github is weird. I dont know what half the things mean.

**Comment by SimonBrandner** [comment] 2021-04-12 05:48
There is already some work on this done in Labs. [Here](https://github.com/vector-im/element-web/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AA-Themes-Custom) are some related issues.

Duplicate of [#13223](https://github.com/vector-im/element-web/issues/13223)

**Closed by SimonBrandner** 2021-04-12 05:48 UTC
Labels: T-Enhancement
