### ISSUE TITLE
Loader looks bad in dark mode

### ISSUE THREAD

**Issue by niwla23** [vector-im/element-web#16498] opened 2021-02-20 17:15 UTC
### Description

The loader looks bad in dark mode. I can't really describe it, but I guess it is the darker colors with a light border.

As a comparsion, here is the spinner in light mode, which looks much better:
![grafik](https://user-images.githubusercontent.com/46248939/108603312-987d1900-73a7-11eb-97e9-083102031b1e.png)

### Steps to reproduce
Open any long loading page

Describe how what happens differs from what you expected.

Logs being sent: yes/no

![grafik](https://user-images.githubusercontent.com/46248939/108603263-4d630600-73a7-11eb-8c5a-cb6c764149f4.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Kubuntu 20.04?
- **Version**: 1.7.20

**Comment by niwla23** [comment] 2021-02-20 17:16
Maybe removing the white border arond the segments would fix this

**Comment by SimonBrandner** [comment] 2021-02-20 17:36
Duplicate of [#15450](https://github.com/vector-im/element-web/issues/15450)

**Closed by SimonBrandner** 2021-02-20 17:36 UTC
Labels: bug, ui/ux
