### ISSUE TITLE
Rageshake and possibly e2e message sending broken in firefox private mode

### ISSUE THREAD

**Issue by jordigh** [vector-im/element-web#15276] opened 2020-09-24 16:19 UTC
### Description

I can't send encrypted messages in a PM. It works on Chrome but not in Firefox. I get failure and all attempts to retry immediately fail again.

![screenshot7](https://user-images.githubusercontent.com/260143/94172109-158b7d00-fe60-11ea-89dd-b940c3d34ca1.png)

### Steps to reproduce

After opening a PM with another user (which apparently has to be encrypted, don't see an option to not encrypt), sending them any message fails.

Log: unable to automatically send from the web app. The spinner just spins forever and never finishes "collecting logs". Any other instructions to send logs would be appreciated.

### Version information

- **Platform**: browser
- **Browser**: Firefox 68.12.0esr
- **OS**: DebianGNU/Linux
- **URL**: app.element.io

**Comment by dbkr** [comment] 2020-09-24 16:32
If you can open developer tools in firefox and look for any errors there (sounds like there probably are some) and copy as much as you can, or come & find one of us in #element-web:matrix.org if you don't want to post them publicly.

**Comment by jordigh** [comment] 2020-09-24 16:55
I just verified that it only fails in private browsing.

**Comment by dbkr** [comment] 2020-09-24 17:07
Confirmed rageshaking doesn't work, which unsurprising since there's no indexeddb for it to get the logs from, but it would be nice if it it did something better than spin indefinitely or say, "No available database" (which is what is did for me on mac, in either 68 ESR or 81).

I couldn't repro the the e2e sending failures but from the logs it was an indexeddb failure, which means element was incorrectly using the indexeddb crypto store for some reason when it should have fallen back to a different one.

**Comment by jryans** [comment] 2020-09-24 17:10
The rageshake portion is a known failure at the moment, tracked by https://github.com/vector-im/element-web/issues/13290.

**Comment by jryans** [comment] 2023-05-17 09:53
Firefox [plans to enable](https://groups.google.com/a/mozilla.org/g/dev-platform/c/yy7uUP47KGQ/m/OxoUI2GHAgAJ) IndexedDB in private browsing mode for Firefox 115 (release planned for 2023-07-04). I assume this should "magically" resolve issues such as this.

**Comment by t3chguy** [comment] 2023-07-27 14:42
Closing as 115 is now out

**Closed by t3chguy** 2023-07-27 14:42 UTC
Labels: T-Defect, Z-Platform-Specific, P2, S-Major
