### ISSUE TITLE
Camera preview is frozen, but video is correctly playing for recipient

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20568] opened 2022-01-15 09:13 UTC
### Steps to reproduce

1. Join a video call
2. Turn on video
3. See a still image of your face
4. Recipient can see your video perfectly fine

#### What did you expect?
I expected the video preview to preview a video instead of an image
#### What happened instead?
The video preview previewed an image

### Operating system

Windows 10

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-01-15 15:52
Does this always happen? Can you please send logs? Is there any more other info you can provide?

I cannot repro

**Comment by AverytheFurry** [comment] 2022-01-16 01:02
> Does this always happen? Can you please send logs? Is there any more other info you can provide?
> 
> I cannot repro

Don't like sending data including the people I talk to :p

**Comment by SimonBrandner** [comment] 2022-01-16 07:01
Well since we don't have a reproduction case nor the logs, I am afraid we can't do much here... If this happens frequently could you perhaps set up a test account, reproduce there and send logs from there?

**Comment by AverytheFurry** [comment] 2022-01-16 07:34
> 

sure, if I find out how to reproduce it (why is the people you talk to included in logs??)

**Comment by SimonBrandner** [comment] 2022-03-04 15:35
Have you been able to repro this?

**Comment by AverytheFurry** [comment] 2022-03-05 20:31
> Have you been able to repro this?

Nope, sorry :p

**Comment by SimonBrandner** [comment] 2022-03-05 20:53
I am going to close this then, let me know if you ever see this again

**Closed by SimonBrandner** 2022-03-05 20:53 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, S-Major, A-VoIP
