### ISSUE TITLE
Thread: add a notification in the main timeline when a new message is posted

### ISSUE THREAD

**Issue by tobiasBora** [vector-im/element-web#22571] opened 2022-06-14 15:10 UTC
#### What would you like to do?

When a new message is posted in a thread, it could be cool to write a notification in the main timeline to specify that a new message was posted…

#### Why would you like to do it?

… otherwise it is easy to miss a reply to a thread.

#### How would you like to achieve it?

Just a small notification that points to the thread, like "A reply has been posted to thread XXX." that should appear in the timeline, like any other message (except that it is smaller). For people not interested by these notifications, one could disable them.

### Have you considered any alternatives?

Not using threads, but only traditional replies, but the messages quickly get messed-up.

**Comment by t3chguy** [comment] 2022-06-14 15:18
Duplicate of https://github.com/vector-im/element-meta/issues/322

**Closed by t3chguy** 2022-06-14 15:18 UTC
Labels: T-Enhancement
