### ISSUE TITLE
Favourites and People meta-spaces are empty

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#20093] opened 2021-12-08 01:13 UTC
### Steps to reproduce

I've have the favourites and peoples spaces enabled for a little while.

At some point in the last couple of days, they started showing as empty:

![Screenshot 2021-12-08 at 12 10 33](https://user-images.githubusercontent.com/57377/145130597-8d4b6c76-f6b4-48e0-bb90-18a312fd86b4.png)

![Screenshot 2021-12-08 at 12 10 52](https://user-images.githubusercontent.com/57377/145130606-bccf1da7-4816-466e-8673-0b04d62dd4ca.png)

 

### Outcome

I have 10 favourites which I'd expect to see, and who knows how many DMs

### Operating system

OS X

### Application version

Element Nightly version: 2021120701 Olm version: 3.2.3

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by turt2live** [comment] 2021-12-08 01:40
Duplicate of https://github.com/vector-im/element-web/issues/20070

**Closed by turt2live** 2021-12-08 01:40 UTC
Labels: T-Defect, S-Major, A-Spaces, O-Uncommon, Z-Labs
