### ISSUE TITLE
message shows red shield because 'encrypted by a deleted session' which is not true

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#14152] opened 2020-06-23 14:13 UTC
see https://matrix.to/#/!HhZHxURiCDviGNNPnc:matrix.org/$6Ta1gDRWAVj0HlObtxEYv-IAmHRTn7Otw_StFuRKqJE?via=matrix.org&via=vector.modular.im&via=twilightsparkle.dev

**Comment by jryans** [comment] 2020-06-24 11:48
@bwindels Is there any way to know if the message keys were gossiped from a different session...? If yes, it sounds like a duplicate of https://github.com/vector-im/riot-web/issues/13689.

**Comment by rda0** [comment] 2020-07-20 10:25
I see this for deleted messages in Element Desktop (Windows) 1.7.1

![image](https://user-images.githubusercontent.com/6731714/87927568-b38b5180-ca83-11ea-9489-722381858f00.png)

**Comment by turt2live** [comment] 2022-06-13 20:29
Without rageshakes and due to the time delay between reporting and triage I don't think this is an actionable issue. If folks are still seeing this, please open a new issue.

**Closed by turt2live** 2022-06-13 20:29 UTC
