### ISSUE TITLE
Unable to decrypt: The sender has disabled encrypting to unverified devices

### ISSUE THREAD

**Issue by n13** [vector-im/element-web#22648] opened 2022-06-26 00:55 UTC
### Steps to reproduce

1. Where are you starting? What can you see?2. 

1 - Install the app
2 - Start a chat with someone
3 - Leave it open for a few days

3. What do you click?4. 

Nowhere

5. More steps…

None

#### What did you expect?

I expected to be able to continue to see the chat messages, if new messages were sent

I expected that once a secure connection is established, it will remain secure. 

#### What happened instead?

I got error messages and was unable to see the messages from the other party

'''
xxxxxxxx
I would need to login from my laptop to test it. 
xxxxxxxx
** Unable to decrypt: The sender has disabled encrypting to unverified devices. **
xxxxxxxx
** Unable to decrypt: The sender has disabled encrypting to unverified devices. **
'''

#### Remedy

I tried to remedy this situation and found a setting to "verify" my device. I was then told it is impossible to verify my device. 

So you put all that effort into making an amazing app, but then, you torpedo it by making the app unusable for normal people - in the name of security? 

What do you mean verify? This is my laptop. I download apps. I use the apps. It's perfectly fine, has no viruses, and should be auto-verified on install. Sort of like when we initially exchange keys. Later on, when I have more devices, I could add them in the verify list, of course. 

#### Screenshot
<img width="748" alt="image" src="https://user-images.githubusercontent.com/65412/175794991-1365499e-72bb-4df8-b985-86a2767fcc9a.png">

### Operating system

Mac OS

### Application version

Version 1.10.15 (1.10.15)

### How did you install the app?

From the website

### Homeserver

I don't know what this question means or how to answer it. Where can I find the setting for "home server"?? I just installed the app. 

### Will you send logs?

Yes

**Comment by n13** [comment] 2022-06-26 01:02
I think this is a major user interface blunder, which could be very easily fixed.

For instance, if account verification is so important, this should happen on install, BEFORE I start a chat with anyone

If it's not that important, then remove that setting altogether.

**Comment by HarHarLinks** [comment] 2022-06-26 11:15
> Why does it say "Verify this session"? I thought I was supposed to verify the device?

:+1: to that, Element should decide on a single term for things.

**Comment by turt2live** [comment] 2022-06-26 23:11
Duplicate of https://github.com/vector-im/element-web/issues/18255 or https://github.com/vector-im/element-web/issues/2996

**Closed by turt2live** 2022-06-26 23:11 UTC
Labels: T-Defect
