### ISSUE TITLE
Riot leaves all versions of a room if you leave a previous version of the room

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#10380] opened 2019-07-21 17:51 UTC
I left the original #synapse:matrix.org but it made me leave the upgraded room too. This doesn't seem like the correct behavior to me. I only want that to happen if I leave the current version of the room. I would like to be able to leave old room versions because of bugs like https://github.com/matrix-org/synapse/issues/5245 which keep notifying me in the old room. Probably related to https://github.com/vector-im/riot-web/issues/8539 and https://github.com/matrix-org/matrix-react-sdk/pull/2818

**Comment by turt2live** [comment] 2019-07-22 07:07
This is technically a feature, but it is indeed a bit awkward if you intentionally leave a non-current version of the room. I'm not really sure what leaving it would gain you though, you're more likely to have even more problems. For instance, there's a good chance you'll end up state reset back in but won't see the tombstone event on the old room and therefore end up with two rooms.

**Comment by aaronraimist** [comment] 2019-07-22 10:39
😐

This is a bit off topic but is there eventually going to be a setting either in the server config or for an individual user to say, do not allow me to join a v1 room?

**Comment by turt2live** [comment] 2019-07-22 15:35
Probably at the server level the room version just won't be supported anymore, but this is a long way out for adoption.

**Comment by Mikaela** [comment] 2020-02-11 18:17
My issue is that I am in IRC bridged rooms and whenever an IRC user pings me, I pinged twice and for the second one I have to click "you have a notification in older version of this room" to see it.

The fix again seems to be leaving that room which results into this issue, as I generally don't have a permission in the old versions to require PL100 for sending messages.

I don't know if matrix-appservice-irc has an issue about this, but I think it could happen with any bridge or maybe even without bridges if someone is bugged and starts talking in the old room.

**Comment by schildbach** [comment] 2020-07-17 13:00
I also think this is unexpected behaviour – I expected only to leave the old, renamed version of the room.

I think ideally a dialog would appear, listing all aliases/versions of the room and you can individually leave (or maybe also join/migrate to) aliases.

**Closed** 2020-08-20 13:17 UTC
Labels: type:roomupgrades
