### ISSUE TITLE
Ability to send photos directly from within the app.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#24974] opened 2023-03-28 17:59 UTC
#### What would you like to do?

A few times recently i've seen non-technical users ask why they can't take/send photos directly from within EW like they can on EI & EA. Having a "send photo" button which uses getUserMedia to grab a photo from a camera and send it directly from within the app would have made them happy.

#### Why would you like to do it?

Parity with EI/EA, and to help non-technical users who don't know how to use Quicktime or Photo Booth or something to take photos on their laptop and then manually upload to EW.

#### How would you like to achieve it?

Yet another send button, similar to sending location or files etc - but for photos.

### Have you considered any alternatives?

Alternatively, we could add a video messaging feature similar, and give it a "send a photo" mode as well as a "send a video" mode.

### Additional context

I haven't missed this myself, but that's 'cos i'm a poweruser.

**Comment by t3chguy** [comment] 2023-03-29 07:24
Duplicate of https://github.com/vector-im/element-web/issues/16101

**Closed by t3chguy** 2023-03-29 07:24 UTC
Labels: T-Enhancement
