### ISSUE TITLE
No feedback when decrypting attachments

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2749] opened 2016-12-16 09:41 UTC
coffee says he got a file decrypt link from yannick with an apk in e2e room; clicked it; no feedback whilst stuff downloaded, and then the download link disappered entirely

**Comment by richvdh** [comment] 2016-12-16 09:43
It seems unlikely apks would be singled out for special treatment?

**Comment by richvdh** [comment] 2016-12-16 13:34
Indeed, apks seem to work fine for me.

I can believe that there is no feedback while download and decryption happens, or if there is an error. 

(Also, this is a two-step process: First, click "Decrypt", which downloads and decrypts the attachment. Then the link turns into "Download", which is a misleading name, as by then the attachment is downloaded and in memory. Then, clicking "Download" just gives you a save dialog.)

**Comment by ara4n** [comment] 2016-12-16 13:46
i can believe this isn't apk specific, was just filing the bug verbatim as it came in from @matrixcoffee. It sounds like the link never turned into "Download".  @matrixcoffee: what browser was this; can you repro it; and if so, can you please share the JS console?

**Comment by ara4n** [comment] 2017-02-22 01:05
i just got bitten badly by this - it took about 3 minutes to download a 24MB encrypted attachment, and there was *no* reaction whatsoever to me having clicked the link.  I had to guess that it was working based on the network inspector.  Finally it changed to 'Download...' rather than 'Decrypt...' which is unintuitive, given it'd already downloaded it by that point......

**Comment by richvdh** [comment] 2017-02-23 00:29
argh. yes. This isn't a p2 cosmetic imho...

**Comment by lampholder** [comment] 2018-01-18 10:52
Meddling with the labels on this, because it is _highly_ annoying.

Also, it seems that once it has decrypted the link loses it's `cursor: pointer` styling.

**Comment by kittykat** [comment] 2021-12-21 16:45
I'm going to close this for now as we couldn't reproduce it:

> Attachment decryption button isn't there anymore.

Please re-open with more details if there is still an issue here.

**Closed by kittykat** 2021-12-21 16:45 UTC
Labels: T-Defect, P1, S-Minor, A-E2EE, X-Needs-Community-Testing
