### ISSUE TITLE
Same-time mutual calls inform user of the incoming call before resolving

### ISSUE THREAD

**Issue by tusooa** [vector-im/element-web#14423] opened 2020-07-12 03:10 UTC
### Description

If two users call each other at the same time, they both receive a notification about the incoming call before the call is connected. In the notification, the users are given the options to accept or decline the incoming call. If the user accepts the incoming call, the call may not be connected properly. This behaviour is really counter-intuitive. When confronted with the "they are calling you" notification, the intuition is to click "Accept" but the way to successfully make a call is to just wait for it to resolve. We should not display the call notification if the call is from the party we are calling.

### Steps to reproduce

- Use two accounts to voice call each other in a direct room at the same time
- Do nothing more

Describe how what happens differs from what you expected.

Expected: The call is connected without showing any information about the incoming call.

Actual: There is a notification about the incoming call from the other party. It shows up for several seconds, and asks whether to accept or decline. If the user does not click any of them, the call is connected.

Logs being sent: no

### Version information

- **Platform**: web (in-browser) or desktop? web

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? Firefox ESR 68.10.0
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows 10
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web? riot.im/app

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? N/A
- **Version**: 1.x.y  N/A

**Comment by MadLittleMods** [comment] 2022-02-19 01:06
Related to https://github.com/vector-im/element-web/issues/20259

Duplicate?

**Comment by SimonBrandner** [comment] 2022-02-19 08:25
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/20259

**Closed by SimonBrandner** 2022-02-19 08:25 UTC
Labels: T-Defect, A-VoIP
