### ISSUE TITLE
Guest user message is sent twice

### ISSUE THREAD

**Issue by vonkoff** [vector-im/element-web#16045] opened 2020-12-28 22:51 UTC
### Description

When a guest joins chat and starts typing then what they wrote out appears twice when sent. Other users in the chat don't see, but the guest user does on his screen. 

### Steps to reproduce

-Join room as guest.
-Join any room.
-Start typing and sending in chats to see the error.

Logs being sent:  yes

![image](https://user-images.githubusercontent.com/16548992/103247425-dbd18300-4934-11eb-8ec1-c0d0bba9cf54.png)

### Version information

- **Platform**:  **Web app**

For the web app:

- **Browser**:  **Chrome**
- **OS**:  **Windows 10**
- **URL**:  Element version: 1.7.16

**Comment by jryans** [comment] 2021-01-15 17:04
Thanks for the issue, I can reproduce this. I wonder how long it's been this way... 😅

**Comment by t3chguy** [comment] 2021-01-15 17:06
This looks like https://github.com/matrix-org/synapse/issues/8521

**Comment by t3chguy** [comment] 2022-04-27 22:29
Yes, closing in favour of https://github.com/matrix-org/synapse/issues/8521

**Closed by t3chguy** 2022-04-27 22:29 UTC
Labels: T-Defect, S-Major, A-Guest-Access, A-Timeline, Z-Backend, Z-Synapse, O-Occasional
