### ISSUE TITLE
Updates to threads not updating the room counter

### ISSUE THREAD

**Issue by karlabbott** [vector-im/element-web#21178] opened 2022-02-23 13:39 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

Any room with a thread in it. When the thread is updated (people reply to it), the room counter is not getting updated. This is causing me to miss messages in rooms that prior to threads would not have been a problem.

#### What did you expect?

The room counter will be updated on replies to a thread.

#### What happened instead?

The room counter and the state of the room go unchanged.

### Operating system

Linux

### Application version

Element version: 3810b7e3297d-react-5e76d988ca53-js-2128f67dc344 Olm version: 3.2.8

### How did you install the app?

https://develop.element.io

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by gsouquet** [comment] 2022-03-07 15:18
@karlabbott is this something you can still experience? I am unable to reproduce

**Comment by karlabbott** [comment] 2022-03-07 15:19
Let me turn threads back on and test.

**Comment by gsouquet** [comment] 2022-03-08 09:18
I haven't been able to reproduce following the given steps, is there anything else I should be doing? Unfortunately the rageshake did not un-earth anything useful for this issue

https://user-images.githubusercontent.com/769871/157205637-8c2c4449-c6af-4687-86ca-b4c39bb15787.mov

**Comment by karlabbott** [comment] 2022-03-08 13:10
As of today, I can no longer reproduce the issue either.

**Comment by gsouquet** [comment] 2022-03-08 15:42
Closing for now, feel free to re-open if the issue reappears!

**Closed by gsouquet** 2022-03-08 15:42 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, O-Uncommon, A-Threads, Z-Labs
