### ISSUE TITLE
DM on first message is broken for group DMs.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23162] opened 2022-08-28 18:00 UTC
### Steps to reproduce

1. Start a DM with two people
2. Note that the resulting screen confusingly says that sending a message will only invite one person to the chat:

![image](https://user-images.githubusercontent.com/1294269/187088163-7a4f98d6-c0c1-40c3-b908-f202e9ce8aeb.png)

3. Also observe that the prompt is weirdly vertically positioned - is all the empty space at the bottom deliberate? Why isn't it bottom-aligned?

#### What did you expect?

DMs not to lie about who they're inviting.

### Operating system

macOS

### Application version

Nightly

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ara4n** [comment] 2022-08-28 18:01
I don't even have a RightPanel to confirm who's actually in the room and who isn't!

**Comment by ara4n** [comment] 2022-08-28 18:08
(in the end, it correctly invited the two people; it's just the prompt that feels very strange)

**Comment by robintown** [comment] 2022-08-29 04:20
Duplicate of https://github.com/vector-im/element-web/issues/23094

**Closed by robintown** 2022-08-29 04:20 UTC
Labels: T-Defect, X-Regression, S-Major, A-DMs, O-Frequent
