### ISSUE TITLE
Add a "delete device" button to "Not Trusted" pop up .

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17687] opened 2021-06-18 10:42 UTC
#### Is your suggestion related to a problem? Please describe.
When I log n to a session but don't have access to another device or key, then I will have an unverified device, would be nice to be able to get rid of that more easily. Also, when a login goes wrong (It takes ages to sync the rooms and I refreshed or just closed the tab)

#### Describe the solution you'd like.
Add another button to the following screen - "delete device"
![image](https://user-images.githubusercontent.com/31655082/122548874-2f926e80-d032-11eb-9270-3e40162fcabd.png)

This would be the same as going to security and privacy section and searching for the device manually and deleting it:
![image](https://user-images.githubusercontent.com/31655082/122549258-96178c80-d032-11eb-8f3a-c9980171c9ae.png)

**Comment by SimonBrandner** [comment] 2021-06-18 14:40
Duplicate of [#13187](https://github.com/vector-im/element-web/issues/13187)

**Closed by SimonBrandner** 2021-06-18 14:40 UTC
Labels: T-Enhancement
