### ISSUE TITLE
Add ability to mix all tags together under a single sorting mechanism

### ISSUE THREAD

**Issue by Pointedstick** [vector-im/element-web#15657] opened 2020-11-05 23:01 UTC
### Description
You can sort your direct messages by recency. And you can sort your group chats by recency. But there's no way to intersperse them such that *everything* is sorted by recency. As a result, if you have a ton of chats, you'll constantly be scrolling between your list of DMs and your list of group chats, which gets old.

### Version information
- **Platform**: desktop
- **OS**: Linux: openSUSE Tumbleweed
- **Version**: 1.7.10

**Comment by t3chguy** [comment] 2020-11-05 23:55
Sure you can, you can put them all in favourites or use a tag manager like tags.t2bot.io to move them all to Rooms/DMs

**Comment by Pointedstick** [comment] 2020-11-06 04:10
> you can put them all in favourites

That's a workaround that doesn't seem adequate. If I put literally every room and DM in my favorites list, I've turned favorites into something else, and I can't use it as a favorites list.

> or use a tag manager like tags.t2bot.io to move them all to Rooms/DMs

I don't know what that is and it also seems like a fiddly workaround. I feel like the app should handle this itself, without workarounds needed.

**Comment by ArneNostitz** [comment] 2021-04-23 08:25
I would also love a way to have a "all chats" section. I don't need the separation and having to scroll down to the room list to get a new msg is very tiresomely ... desktop and mobile. 

it would be great to at least have the option to ignore the room / dm separation. 

thanks!

**Comment by SimonBrandner** [comment] 2021-04-23 08:41
Reading through this, it seems that [#16306](https://github.com/vector-im/element-web/issues/16306) is what you want. @Pointedstick, @ArneNostitz, would you agree to close this in favour of that issue?

**Comment by rhyst** [comment] 2022-10-25 10:51
Sorry to just bump this issue with a question but given a similar change is now default in Element Android for usability reasons, is there any progress or update on having this as an option in web/desktop?

**Comment by CyberSardinha** [comment] 2022-12-03 23:42
This would be great I have exactly the same problem. I have too many people and can't really see the rooms on the list view

**Comment by t3chguy** [comment] 2023-03-29 15:29
Duplicate of https://github.com/vector-im/element-web/issues/2042

**Closed by t3chguy** 2023-03-29 15:29 UTC
Labels: A-Room-List, T-Enhancement
