### ISSUE TITLE
Change mention type from plaintext to special symbol like @

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#4973] opened 2017-09-05 03:57 UTC
Very often I see messages like this, that prevent user mentions:

> freijon: not soo big uhm I am not sure (please yell at me if I am wrong) Matthev (v = w for no mention), luké (é = e_) , Davé (é=e) and hm is Michael (t3chguy) also in the team?

I see here the problem with mentioning - it's too easy to do unneeded mention! For example, if I have name 'good', I will have many miss-mentions. Same here if I have popular name like "Bob" - I will receive mentions for all Bobs. 

Will be good to change mention type from plaintext name to special symbol, for example via @ like in github, to minimize miss-mentions. Maybe do this optionally for not change old behaviour.

Using @ is very popular in other popular projects like Twitter, also now we have easy way to mention via click on user in Riot.

**Comment by MurzNN** [comment] 2017-09-05 04:02
I think that plaintext mentions go to Matrix from IRC (like many other features, ex slash-commands), and this change will be badly accepted by IRC fans, but IRC is too old and the world is changing ;)

**Comment by lampholder** [comment] 2017-09-05 10:58
I realise I have uncritically carried my IRC behaviour over to Riot/Matrix (and indeed spell people's names M4tthew, etc, to avoid binging).

We'd need to think about how we did this - right now Riot mentions are triggered on users' entering a display name or a mxid, and to my mind it feels peculiar to mention `@mxid:matrix.org` by typing `@Display Name` when @Display Name looks a little bit like a mxid but isn't one :\

**Comment by MTRNord** [comment] 2017-09-05 12:03
What about only doing a mentor when sending pills? (of course it needs full client Support first)

**Comment by t3chguy** [comment] 2017-09-05 12:04
@MTRNord its Synapse that calculates the "ping", so it'd need Synapse support first
disabling mention on Displayname in Riot leads to Pills not pinging you, whereas those should probably get their own rule

**Comment by weeman1337** [comment] 2021-06-01 11:00
I made the mistake choosing my given name as local part. Now I receive notifications for every "michael". This is so annoying :/ If not switching it completely it would already help if I can choose not to be notified on "substring match mentions".

**Comment by MadLittleMods** [comment] 2022-04-14 20:25
Related to https://github.com/vector-im/element-web/issues/19833

**Comment by t3chguy** [comment] 2022-05-10 20:36
Duplicate of https://github.com/vector-im/element-web/issues/8431

**Closed by t3chguy** 2022-05-10 20:36 UTC
Labels: P3, X-Needs-Design, T-Enhancement, A-Pills, X-Spec-Changes, Z-MadLittleMods
