### ISSUE TITLE
Filter not working on Element Desktop.

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16640] opened 2021-03-08 18:58 UTC
### Description

Filter not working on Element Desktop. Something is happening with the first letter typed but that's it

### Steps to reproduce

not sure

Here is a screen cap:
https://nextcloud.chagai.website/s/X5Z7d3EAJ58Ak3q

Logs being sent: yes

### Version information

Logs being sent: yes

Version information
Platform: web (in-browser) or desktop? desktop
For the desktop app:

OS: Windows, macOS, Ubuntu, Arch Linux, etc? Windows
Version: 1.7.13

**Comment by t3chguy** [comment] 2021-03-08 19:01
Duplicate of https://github.com/vector-im/element-web/issues/15322

**Closed by t3chguy** 2021-03-08 19:01 UTC
