### ISSUE TITLE
Enable email notifications get reset after logout and login again

### ISSUE THREAD

**Issue by JohnRock0422** [vector-im/element-web#16811] opened 2021-03-29 03:58 UTC
### Description

After enabling email notifications option and logout
![bug2](https://user-images.githubusercontent.com/26728661/112784730-f971ce00-9084-11eb-9fdd-1d1478cccd4f.png)

When I login again with the same account, the option get reset
![bug](https://user-images.githubusercontent.com/26728661/112784782-127a7f00-9085-11eb-9224-a0bedfe39770.png)

**Comment by t3chguy** [comment] 2021-04-12 11:20
Duplicate of https://github.com/vector-im/element-web/issues/6072

**Closed by t3chguy** 2021-04-12 11:20 UTC
Labels: T-Defect
