### ISSUE TITLE
Connectivity to the Server Has Been Lost

### ISSUE THREAD

**Issue by joecarvill** [vector-im/element-web#18584] opened 2021-08-17 09:19 UTC
### Steps to reproduce

1. I was prompted to udpate my Element desktop app on Windows this morning
2. After the update I'm just getting the 'Connectivity to the Server Has Been Lost'
3. I have uninstalled and reinstalled the app but arrive at the same issue. 
4. My iOS app is still working, so not an issue with my account. 

### What happened?

I was prompted to udpate my Element desktop app on Windows this morning. After the update I'm just getting the 'Connectivity to the Server Has Been Lost'.

### What did you expect?

As all other Element updates, I was expecting the app to simply re-open as it normally does without any requests for encryption keys etc.

### Operating system

Windows

### Application version

Element 1.8.0

### How did you install the app?

Google Chrome

**Comment by SimonBrandner** [comment] 2021-08-17 10:18
What homeserver are you using? Also, please send logs, if you haven't done so yet

**Comment by joecarvill** [comment] 2021-08-17 10:27
Hey Simon - we're being hosted on EMS. Logs already sent...I hope!

**Comment by kittykat** [comment] 2021-08-17 10:55
I had the same problem on app.element.io this morning but it resolved itself before I could file a useful issue.

**Comment by joecarvill** [comment] 2021-08-17 12:09
I've now updated to version 1.8.1 but still having the shame issue

**Comment by jaywink** [comment] 2021-08-18 08:22
From EMS side I can confirm the homeserver is fine.

There are a lot of `Invalid Authorization header.` in the rageshake logs.

Another user reported to me yesterday about Element Desktop not starting after update - hope not related? In this case the app didn't start at all however, though it's still unclear if it's running in the background without the user realizing.

@joecarvill with the app open, can you try clearing the cache? "Settings" -> "Help & About" -> "Clear cache and reload"

**Comment by joecarvill** [comment] 2021-08-18 08:28
Morning @jaywink and @SimonBrandner I actually just tried logging out and then logging back in on the app and it's reconnected. 

Would you still like me to clear the cache as above?

**Comment by joecarvill** [comment] 2021-08-18 08:28
Thanks for your help and advice on this - really appreciated

**Comment by SimonBrandner** [comment] 2021-08-18 08:32
Morning, if everything works, it doesn't seem to be necessary. If you ever experience this again, you can try doing that, and maybe it helps. 

Since the issue seems to have fixed itself for you, I am going to close this. Let me know by typing `@SimonBrandner` if you ever experience this again and aren't able to fix this, I will re-open in that case

**Comment by jconnolly837** [comment] 2021-11-09 21:49
I seem to be having this same issue. I opened Element today and it had signed me out. I signed back in and everything seemed normal, until Element is restarted. I can manually sign out and sign back in to temp fix the issue again, but it comes back after Element has been closed and opened. 

I tried to clear the cache as suggested above. I clicked "Help & About" and the settings box just closes. Every time I click it, it closes and nothing happens. 

I'm on Arch Linux, Element version 1.9.4-1 from the community repo. Element was working perfectly before running package updates last night. 

@SimonBrandner

**Comment by novocaine** [comment] 2021-11-10 09:16
@jconnolly837 we need to know what homeserver you're connecting to, and we need you to send debug logs (Feedback -> Debug Logs)

**Comment by jconnolly837** [comment] 2021-11-10 21:40
I'm using the default matrix.org homeserver. 
[elementlogs.zip](https://github.com/vector-im/element-web/files/7516106/elementlogs.zip)
@SimonBrandner

**Comment by SimonBrandner** [comment] 2021-11-11 06:46
@jconnolly837, thanks for the logs though no need to ping me...

**Comment by jconnolly837** [comment] 2021-11-13 17:51
The issue appears to be solved after deleting "~/.config/Element" and relogging in. I can end and launch Element all I want and it will launch normally. Hopefully my logs can help prevent this from happening in future updates.

**Comment by novocaine** [comment] 2021-11-16 01:17
```
2021-11-09T21:23:46.083Z I Failed to check for protocol support: will retry Invalid Authorization header.
M_MISSING_TOKEN: Invalid Authorization header.
    at vector://vector/webapp/bundles/ce9e2fc2ce480117ab65/vendors~init.js:2:922585
    at vector://vector/webapp/bundles/ce9e2fc2ce480117ab65/vendors~init.js:2:922742
    at Object.callback (vector://vector/webapp/bundles/ce9e2fc2ce480117ab65/vendors~init.js:2:921874)
    at vector://vector/webapp/bundles/ce9e2fc2ce480117ab65/vendors~init.js:2:28999
    at XMLHttpRequest.i.onreadystatechange (vector://vector/webapp/bundles/ce9e2fc2ce480117ab65/vendors~init.js:2:29023)
2021-11-09T21:23:47.019Z I EventIndex: Error initializing the event index {"message":"Error opening the database: DatabaseUnlockError(\"Invalid passphrase\")"}
```

**Comment by novocaine** [comment] 2021-11-24 03:05
Closing as this isn't recurring for the OP.

**Closed by novocaine** 2021-11-24 03:05 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Critical, Z-Rageshake, O-Uncommon

**Comment by gerroon** [comment] 2022-02-20 19:19
I have this issue suddenly with my self hosted Synapse. The android app works, the desktop has full internet, but Element refuses to connect to the server.

```
Getting push rules failed M_MISSING_TOKEN: Invalid Authorization header.

```

**Comment by devurandom** [comment] 2022-07-07 16:23
I run into the same problem with my account on matrix.org.

> I tried to clear the cache as suggested above. I clicked "Help & About" and the settings box just closes. Every time I click it, it closes and nothing happens.

I experience the same problem.

> GET https://matrix-client.matrix.org/_matrix/client/r0/rooms/[REDACTED] 401
> M_MISSING_TOKEN: Invalid Authorization header.

I see these, too. The console (ctrl+shift+i) is full of them.

**Comment by Kevin8675** [comment] 2023-01-31 03:02
> I run into the same problem with my account on matrix.org on the desktop app (might be related to [flathub/im.riot.Riot#247](https://github.com/flathub/im.riot.Riot/issues/247)).
> 
> > I tried to clear the cache as suggested above. I clicked "Help & About" and the settings box just closes. Every time I click it, it closes and nothing happens.
> 
> I experience the same problem.
> 
> > GET [https://matrix-client.matrix.org/_matrix/client/r0/rooms/[REDACTED]](https://matrix-client.matrix.org/_matrix/client/r0/rooms/%5BREDACTED%5D) 401
> > M_MISSING_TOKEN: Invalid Authorization header.
> 
> I see these, too. The console (ctrl+shift+i) is full of them.

I am experiencing the exact same issue. I am using Arch Linux. When I am running the KDE desktop environment, element connects and works fine, but when I switch to BSPWM then it fails to connect to the server (would probably happen on other DE/WMs though). I think this is an issue relating to the keyshare in KDE not being accessible in other desktop environments. Any help appreciated.
