### ISSUE TITLE
Switch to immutable DMs

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#11245] opened 2019-10-28 10:23 UTC
JS SDK issue: https://github.com/matrix-org/matrix-js-sdk/issues/1058
Synapse issue: https://github.com/matrix-org/synapse/issues/6261

There was also vector-im/riot-web#10415 but this got closed

**Comment by turt2live** [comment] 2022-05-07 02:51
Effective duplicate of https://github.com/vector-im/element-web/issues/3457

**Closed by turt2live** 2022-05-07 02:51 UTC
Labels: A-DMs, A-E2EE-Cross-Signing, A-Immutable-DMs
