### ISSUE TITLE
translate emoji search

### ISSUE THREAD

**Issue by Yajo** [vector-im/element-web#20939] opened 2022-02-06 12:45 UTC
#### What would you like to do?
Send an emoji

#### Why would you like to do it?
They're cool 😎 

#### How would you like to achieve it?
Searching in my mother language 

### Have you considered any alternatives?

Learn English. I can, but not all my contacts. 

### Additional context

One contact told me this is a nice feature she likes in Google chat, and she's missing it in element. Makes total sense IMHO.

**Comment by SimonBrandner** [comment] 2022-02-06 13:07
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/11013

**Closed by SimonBrandner** 2022-02-06 13:07 UTC
Labels: T-Enhancement

**Comment by Yajo** [comment] 2022-02-06 15:09
Ah sorry, I searched but couldn't find that issue. Thanks!

**Comment by SimonBrandner** [comment] 2022-02-06 15:10
> Ah sorry, I searched but couldn't find that issue. Thanks!

No worries :)
