### ISSUE TITLE
Zoom in on specific pictures does not work at all or not well

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16587] opened 2021-03-03 08:37 UTC
### Description

When the length is much longer than the width for example or maybe even big pictures and in general you can only zoom in to a specific size and then it will zoom out again making the GUI bigger but not the picture

Pictures 
### Steps to reproduce

try these pictures:
![image](https://user-images.githubusercontent.com/31655082/109777042-9155d680-7c03-11eb-8bb7-d35a93448dae.png)
![image](https://user-images.githubusercontent.com/31655082/109777228-c5c99280-7c03-11eb-9d72-a3995451364c.png)

Logs being sent: no

### Version information

- **Platform**: web (in-browser) or desktop? web

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? Chrome
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web? app.element.io

**Comment by jryans** [comment] 2021-04-20 10:21
That does not seem like a picture of Element Web...

**Comment by t3chguy** [comment] 2021-04-20 10:23
@jryans those are example images to reproduce the issue

**Comment by SimonBrandner** [comment] 2021-05-01 10:46
@chagai95, I am not sure I understand what exactly is the issue about... Are the problems solved by the new image view? If not, could you perhaps try to explain this in more detail/add screenshots/add a recording?

**Comment by SimonBrandner** [comment] 2021-05-13 07:57
I will close this as there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.

**Closed by SimonBrandner** 2021-05-13 07:57 UTC
Labels: A-Media, P3, S-Tolerable, T-Defect, X-Needs-Info

**Comment by chagai95** [comment] 2021-05-13 09:26
Sorry I missed this, I guess this could turn into a feature request to add more zoom capability because it still seems limited, also the intuitive CRTL mouse scroll is not regarded and only the mouse scroll is mapped to zooming, any specific reason for that?  @SimonBrandner  Thanks so much for pinging and the zoom is amazing otherwise!

**Comment by SimonBrandner** [comment] 2021-05-13 09:36
> Also the intuitive CRTL mouse scroll is not regarded and only the mouse scroll is mapped to zooming, any specific reason for that?

It works for me both with and without pressing <kbd>Ctrl</kbd> :thinking: If this isn't the case for you, please open an issue and please include browser info.

The zoom behavior originates from [#17049](https://github.com/vector-im/element-web/issues/17049). There has been a suggestion to change this ([#17114](https://github.com/vector-im/element-web/issues/17114)) but that quite conflicts with the expected behavior in the original issue. That is why I suggested [this](https://github.com/matrix-org/matrix-react-sdk/pull/5949#issuecomment-831847745).

Feel free to comment in the relevant places
