### ISSUE TITLE
Allow disabling Markdown on messages you send

### ISSUE THREAD

**Issue by abb128** [vector-im/element-web#17869] opened 2021-07-03 17:44 UTC
My good friend often writes emotions such as `>w<` or `- _ -` and it's frustrating when Markdown messes it up. Currently, the only way to get around this is to remember to prepend `/plain` to the message every time. This is annoying and it's easy to forget.

On the Android app, there's already an option and chat command (`/markdown on/off`) to disable Markdown styling on the messages you send. I suggest that this feature be added to element-web as well.

**Comment by SimonBrandner** [comment] 2021-07-03 18:31
Duplicate of https://github.com/vector-im/element-web/issues/483

**Closed by SimonBrandner** 2021-07-03 18:31 UTC
Labels: T-Enhancement
