### ISSUE TITLE
Insane amounts of critical bugs for more than 6 months! Remaining unpatched since it started!

### ISSUE THREAD

**Issue by NovaZek** [vector-im/element-web#22528] opened 2022-06-10 17:18 UTC
### Steps to reproduce

Where to start ...

PC:
- The client will glitch and bug out, when sending video formats (be it webm, mp4 or whatever). The entire chat will be blank (background glitches in front of the actual text-html instance).

- Scrolling up (when there were some videos being uploaded few hours ago), it will cause the same issue, when the client tries to render the video panel.

- Playing videos in fullscreen (when you even can get to this step ever...) will kinda loop weirdly around. Forwarding 1s, glitching back 0.3s and retaining the actual speed again and looping this nonsense once again. It is like the player starts the video clip twice and tries to catch up with the first started one. Very annoying.

Android (in combination with PC):

- Images being uploaded via PC or Android will have a critical bug on Android. You will not see the image, if it passes around 2.0mb size. The area, where the image should be actually located at, will be simply empty. I, on my OnePlus 7 Pro, can somewhat tap to the most outter right area to open the image in my own phone's image viewer (while tapping the other 90% of the area will result into a black screen with nothing to see, but the system buttons down below). This same approach is for example NOT working on the Samsung Galaxxy S21. There is no way to bypass this issue otherwise.
... While sending pictures above 2.0mb with an Android, which you cannot see on your Android device (... what a mess), you can see them on the PC, though.

There are app crashings occuring when recording voice messages near the 2 minute mark via the Samsung S21, while no issues with the OnePlus 7 Pro, happens very rarely on PC.

Android only:
There are sometimes issues with the Android version running in the background and immensly draining battery since version 1.4.8 - it keeps running in the background, despite killing it with the taskmanager. It simply starts on its own without the app being actually running for the user (not visible in the taskmanager). Probably an issue with the push-service? Had to remove the background data settings from this app (the first time), to make it actually shut up and stop running non stop.

https://www.reddit.com/r/elementchat/comments/supvhl/immense_issues_with_image_fetching/
There are others reporting the same annoying bugs.

### Outcome

See above. Explained detailed. No sense in splitting that entirely into two segments.

### Operating system

Windows 10 x64 Pro, Android 11 (latest patches) on both Devices

### Application version

Element version: 1.10.1 Olm version: 3.2.8; Android version, both, 1.4.16

### How did you install the app?

PC: Installer; Android: Store (no external APK approach on first, via APK the second time)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-06-10 19:18
> The client will glitch and bug out, when sending video formats (be it webm, mp4 or whatever). The entire chat will be blank (background glitches in front of the actual text-html instance).

> Scrolling up (when there were some videos being uploaded few hours ago), it will cause the same issue, when the client tries to render the video panel.



Duplicate of https://github.com/vector-im/element-web/issues/8313

> Playing videos in fullscreen (when you even can get to this step ever...) will kinda loop weirdly around. Forwarding 1s, glitching back 0.3s and retaining the actual speed again and looping this nonsense once again. It is like the player starts the video clip twice and tries to catch up with the first started one. Very annoying.

Please open an issue with a screen recording ideally

> Images being uploaded via PC or Android will have a critical bug on Android. You will not see the image, if it passes around 2.0mb size. The area, where the image should be actually located at, will be simply empty. I, on my OnePlus 7 Pro, can somewhat tap to the most outter right area to open the image in my own phone's image viewer (while tapping the other 90% of the area will result into a black screen with nothing to see, but the system buttons down below). This same approach is for example NOT working on the Samsung Galaxxy S21. There is no way to bypass this issue otherwise.
... While sending pictures above 2.0mb with an Android, which you cannot see on your Android device (... what a mess), you can see them on the PC, though.

needs reporting to https://github.com/vector-im/element-android otherwise it'll never get fixed

**Comment by robintown** [comment] 2022-06-10 19:57
@t3chguy I see no reason why the first couple of issues would be related to https://github.com/vector-im/element-web/issues/8313, the latter is very sparse on details but doesn't seem to have any relation to videos.

**Comment by robintown** [comment] 2022-06-10 20:02
@NovaZek You seem to be running a rather outdated version of Element as well. If you can still reproduce the video-related bugs in a more recent version, please open individual issues for them.

**Closed by robintown** 2022-06-10 20:02 UTC
Labels: T-Defect

**Comment by t3chguy** [comment] 2022-06-10 20:06
![image](https://user-images.githubusercontent.com/2403652/173142700-64508618-f95d-4b96-a0be-82d870581b6c.png)
