### ISSUE TITLE
Sender profiles are often missing when scrolling back (or on RRs)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17808] opened 2021-06-28 02:33 UTC
I assume this is a LL bug.  When you're scrolling back, it's quite common to see raw mxids as senders without an avatar, even though the sender had a profile at the time.  It looks like we have a LL bug where only the LL'd members' profiles are visible.  Similarly, if an RR appears for a non-LL'd user, it may also lack an avatar.

Looks like something might be going wrong in the logic which calls /members to pull in all the membership events after having initially LL'd a room.

**Comment by SimonBrandner** [comment] 2021-06-28 04:27
I've never seen this and can't repro

**Comment by MadLittleMods** [comment] 2021-09-02 05:21
Duplicate of https://github.com/vector-im/element-web/issues/7417

**Closed by MadLittleMods** 2021-09-02 05:21 UTC
Labels: T-Defect, X-Cannot-Reproduce, A-Timeline
