### ISSUE TITLE
All E2E history taking ~15 minutes to decrypt on launch

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13266] opened 2020-04-18 20:14 UTC
...actually, as i filed this, they finally decrypted. But it took about 5 minutes.

**Comment by ara4n** [comment] 2020-04-23 16:12
i'm seeing this every time i launch Nightly.

**Comment by ara4n** [comment] 2020-04-26 18:24
Just had another instance of this - i launched Nightly at 19:16:56, and my E2EE messages only became visible at 19:22:07.  The server is relatively unloaded, and i'm on good internet.

**Comment by turt2live** [comment] 2020-04-27 17:23
@ara4n is this messages being invisible or saying the words "unable to decrypt"?

**Comment by ara4n** [comment] 2020-05-04 00:29
this is the messages being invisible (unless you have invisible events being displayed, and then you see m.room.encrypted placeholders until they finally decrypt).

I just had it again, except this time it literally took 10 minutes before history was visible.

**Comment by turt2live** [comment] 2020-05-04 00:46
This is a long-standing bug then: https://github.com/vector-im/riot-web/issues/7116

**Comment by ara4n** [comment] 2020-05-04 14:31
yes, except it used to be a rare occurrence, whereas now it is 100% reproducable and really impacts usability.

**Comment by turt2live** [comment] 2020-05-04 14:38
I've seen it every single day since reporting 2 years ago :(

**Comment by ara4n** [comment] 2020-05-04 15:08
well, this has got to be fixable - during the 10 minutes, incremental /syncs are happily bouncing away - it's very unclear what it's actually blocking on...

**Comment by dbkr** [comment] 2020-05-04 17:48
So this is because at startup we load 50 events worth of history for each room from disk and decrypt any that are encrypted. This takes some time but is also slowed down quite a lot by it firing `Event.decrypted` for every one which causes things like breadcrumbs to recalculate badges and the timeline to update.

Things we could do to make this smarter:
 * Decrypt events in a priority queue of some kind, prioritising events for the room that's visible (would obviously need a way for the app to tell js-sdk which to prioritise, and a reasonably invasive change since right now we just start decrypting them all async and leave them to it).
 * Decrypt events lazily: tricker as we'd only be able to do this for events where we knew, without decrypting them, that they wouldn't affect badges & such (ie. work out if they'd already been read).
 * Not show the UI until we've decrypted the history. This would mean we wouldn't need to worry about doing UI update work in `Event.decrypted` until the initial load had finished, plus we'd only show the UI once it was actually correct. It could make loading feel slower though if you're staring at a spinner or whatever loading UI we use.
 * Actually make the decryption faster: right now each decryption is separate and starts a separate indexeddb txn to get the keys. Batching them up together may save us some time.

**Comment by turt2live** [comment] 2020-05-04 17:51
some of the async store work from the room list rewrite might help the event loop speed a bit - theory is that it would be able to listen for `Event.decrypted` and not block the js-sdk with breadcrumbs calculations (as the breadcrumbs would be handling updates async and render the changes when ready).

**Comment by ara4n** [comment] 2020-05-18 16:20
This is now literally taking my top-end MBP 15 minutes before i can send E2E messages after launch in Riot Nightly.

I am really surprised the decryption is going this slowly  - i can see the messages flickering into the timeline; it feels at a rate of about 10Hz or so.  Some kind of batching (whether that's to avoid dispatches, or to avoid hammering indexddb) seems preferable.  Or caching badge/unread state somehow so we don't have to decrypt msgs for rooms we're not in?

**Comment by dbkr** [comment] 2020-05-26 08:06
I did some experiments on a branch to speed up the initial decryption of events: https://github.com/matrix-org/matrix-js-sdk/compare/dbkr/bulk_decryption_experiment_hack (see commit message for more details).

Testing on my account this roughly halves the time taken between launch and the last message in a given room being decrypted. It is fairly invasive though and makes a lot of assumptions, ie. it reads megolm sessions, unpickles them and uses them without pickling them and saving them back. In practice we always keep the earliest point in the megolm ratchet anyway but this is certainly a departure from the intended use.

**Comment by Half-Shot** [comment] 2020-07-19 10:08
It's not clear from the issue if this blocks the client completely? I'm finding that after starting desktop, it renders a broken looking Element (userId rather than displayname in the profile spot, no rooms in room list, blank timeline etc) for about 5 minutes and then everything comes to life. I'm unsure if it's the same cause, but feels similar.

**Comment by ara4n** [comment] 2020-07-20 15:18
My problem tends not to be entirely blank timeline, but instead stale timeline which takes ~15 minutes to refresh; meanwhile messages slowly decrypt and trickle into the RoomList previews - I see them coming in at roughly 5 per second.  Given I'm probably in ~200 encrypted rooms, each with ~20 messages of scrollback, this means 4,000 messages to decrypt, which at 5 per second means waiting up to 13 minutes 20s until the rooms are usable.

Quick fixes could be to:
 * only load the most recent message of each room by default, pulling in the remainder on demand
 * only decrypt the most recent message of rooms
 * don't fire events for every decrypted message during startup

**Comment by turt2live** [comment] 2020-07-22 19:25
On a flip side to this: The full page spinner that takes ~5-10 minutes to go away (then falling into the encryption history taking forever) appears to be too many things listening to startup spam, leading to it slowing down.

**Comment by dbkr** [comment] 2020-07-24 10:03
Hmm - I may have been reproducing an entirely different bug then, since I was watching all of the e2e messages decrypt and so if it started up looking at an e2e room, that room was blank (apart from any state/unencrypted events). I don't understand how the room is stale - when are the stale messages from? Are they in the set of 200*50 messages that are decrypting?

On the solutions:
 * only load the most recent message of each room by default, pulling in the remainder on demand
   * What do you mean by 'load' here? They come from the sync accumulator which gives us one big blob, so we can't pick & choose what's loaded from disk.
 * only decrypt the most recent message of rooms
   * this sounds like the second of my ideas above I think
 * don't fire events for every decrypted message during startup
   * I think this is my 3rd one and is one of the optimisations I applied on my experimental branch. It didn't help a great deal for me.

**Comment by jryans** [comment] 2020-07-24 10:32
@ara4n confirms both desktop and browser versions are affected, so clarifying the title.

**Comment by ara4n** [comment] 2020-09-24 09:58
Something seems to have improved significantly on this at some point - circumstantially it's gone back to taking tens of seconds to load e2ee history (at least in the rooms i expect to see) after upgrading Element Nightly.  Is anyone else (@turt2live, @dbkr) seeing it still?  Or am I just getting lucky that the rooms I try to view on launch are the first to decrypt?

One thought: is there a way to to prioritise decrypting rooms as you view them (whilst keeping the big background decrypt chugging away)?

**Comment by turt2live** [comment] 2020-09-24 13:02
I'm still seeing it, and it's still because we decrypt all rooms on startup

**Comment by ara4n** [comment] 2020-09-26 09:04
So i just measured on launch, picking the arbitrary encrypted room I wanted to read, and it took 3 minutes 13 seconds from launch.  As it happens my target room was one of the last ones to decrypt.  So, the good news is that it's definitely not 15 minutes any more.  But it's still getting on for 5 minutes on a large account.

**Comment by AmandineLP** [comment] 2020-10-01 08:46
+1

**Comment by ara4n** [comment] 2021-01-18 14:06
it's back up to 9 minutes on my account now.

**Comment by jryans** [comment] 2021-05-12 11:56
@ara4n @gsouquet Great to see that https://github.com/matrix-org/matrix-js-sdk/pull/1684 is merged! Do we think this is sufficient to close this issue? We can of course still keep exploring more performance improvements anyway. I'm just wondering if we've made "enough" improvement to assuage the main user impact here.

**Comment by jryans** [comment] 2021-05-17 09:50
Sounds like this is working well and addresses the main performance impact here, so let's close this. We can track further performance tweaks separately.

**Closed by jryans** 2021-05-17 09:50 UTC
Labels: A-E2EE, A-Electron, A-Performance, T-Defect, Z-Chronic
