### ISSUE TITLE
Emoji in Emoji selector cannot be selected by keyboard

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#24439] opened 2023-02-05 11:14 UTC
### Steps to reproduce

1. Open the emoji picker
2. Press tab

#### What did you expect?

It should tab through the emoji list

#### What happened instead?

It skips over it

### Operating system

macOS

### Browser information

Firefox

### URL for webapp

develop.element.io

### Application version

Version von Element: e047e5d803c4-react-a756b33fe912-js-2a363598dd98 Version von Olm: 3.2.12

### Homeserver

midnightthoughts.space

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-02-06 09:04
Duplicate of https://github.com/vector-im/element-web/issues/17189

**Closed by t3chguy** 2023-02-06 09:04 UTC
Labels: T-Defect
