### ISSUE TITLE
Random UISI while in chat

### ISSUE THREAD

**Issue by JulipahNewter** [vector-im/element-web#22504] opened 2022-06-09 21:36 UTC
### Steps to reproduce

While I had the element desktop client open a member of the encrypted room sent a message, which randomly came in with a UISI. This person did not add or any remove any sessions, and all subsequent messages were decrypted, so I cannot see why this would happen.
![uisi](https://user-images.githubusercontent.com/107220630/172948707-102b2604-1b3c-470d-9192-cdee24c0e1a7.png)

#### What did you expect?
The message to be decrypted
#### What happened instead?
The message was not decrypted

### Operating system

Linux Mint 20.3 Cinnamon

### Application version

Element version: 1.10.14 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by aaronraimist** [comment] 2022-06-10 02:10
> Will you send logs?

> No

It is essentially impossible to diagnose UISIs without logs.

**Comment by t3chguy** [comment] 2022-06-10 07:29
Duplicate of https://github.com/vector-im/element-web/issues/2996

**Closed by t3chguy** 2022-06-10 07:30 UTC
Labels: T-Defect, X-Needs-Info, Z-UISI
