### ISSUE TITLE
Fix flaky widget-pip-close.spec.ts end to end test

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23372] opened 2022-09-29 09:35 UTC
I have noticed multiple PRs where `widget-pip-close.spec.ts` has been flaky

https://github.com/matrix-org/matrix-react-sdk/pull/9328 for instance

**Comment by t3chguy** [comment] 2022-09-30 07:30
![image](https://user-images.githubusercontent.com/2403652/193215611-27e869ce-1068-4f07-9592-9158ce3e9632.png)

https://dashboard.cypress.io/projects/ppvnzg/runs/4345/overview/7958767d-7cd3-4714-a53b-86bc9f1a9a6a

**Comment by t3chguy** [comment] 2022-10-13 12:18
Duplicate of https://github.com/vector-im/element-web/issues/23286

**Closed by t3chguy** 2022-10-13 12:18 UTC
Labels: T-Task, A-Developer-Experience, Z-Flaky-Test
