### ISSUE TITLE
Can't set SVG as Space icon

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#17443] opened 2021-05-22 19:10 UTC
### Description

Trying to set an SVG image as space icon fails even though the dialog claims it succeeds. The spaces sidebar does not reflect the new icon and revisiting the space settings does not show the icon either.

### Steps to reproduce

- Create a new space
- Try to set an SVG icon

Rageshake also coming (with icon).

### Version information

- **Browser**: Firefox 89.0b15 (64-bit)
- **OS**: Ubuntu
- **URL**: private server, v1.7.28 Element without modifications

**Comment by t3chguy** [comment] 2021-05-22 19:24
Duplicate of #2581

**Closed by t3chguy** 2021-05-22 19:25 UTC
Labels: A-Media, A-Spaces, T-Defect

**Comment by jaywink** [comment] 2021-05-22 19:28
Oh right. I logged a new issue as I couldn't see anything spaces specific and this particular SVG at least does work as a room icon, but not as a space icon :thinking:

**Comment by t3chguy** [comment] 2021-05-22 19:34
Spaces use the RoomAvatar component so that's very strange.

**Comment by jaywink** [comment] 2021-05-22 19:41
Well, I just tried it again and it works :P The SVG is in the rageshake.

**Comment by jaywink** [comment] 2021-05-22 19:43
Ah wait, ignore me. I tried it on my other account, which uses matrix-media-repo. On Synapse media repo, no it doesn't work, you're correct.
