### ISSUE TITLE
option to create a reminder easily

### ISSUE THREAD

**Issue by anbrme** [vector-im/element-web#18751] opened 2021-08-25 14:17 UTC
#### What would you like to do?

I would like to be able to easily create a reminder for an arbitrary value of time on a chat/message basis

#### Why would you like to do it?

I think that when using Element as a primary platform, both relevant business and personal-related matters imply that a reminder option might be necessary or desirable. Going to an external app is not ideal. So, including a reminder tool is useful.

#### How would you like to achieve it?

Based on my experience, the most practical implementation is that provided by Telegram, where you write a message and long-pressing it opens a reminder tool that allows you to choose an arbitrary value of time. So, say you are chatting and someone says that "yes, you should buy bread", you can write a new message with "buy bread", long-press it and set a reminder. In Telegram this works only in the Saved Messages chat, which is a note-to-self chat, so I have no idea how it can be done in Element. Yet, I think it could be a very useful feature, particularly for businesses and if the reminder can be set in a group chat tagging specific users.

### Have you considered any alternatives?

I will try a bot, but it is rather cumbersome, particularly because it forces to use specific commands. This goes against a "natural" use, which is the case when Element is used by non technical people (as in my case, where I use an Element Home subscription with my family).

### Additional context

Thanks for your great work, Element is shaping up wonderfully.

**Comment by t3chguy** [comment] 2021-08-31 13:58
Duplicate of https://github.com/vector-im/element-web/issues/15726

**Closed by t3chguy** 2021-08-31 13:58 UTC
Labels: S-Minor, X-Needs-Design, X-Needs-Product, T-Enhancement, O-Low
