### ISSUE TITLE
App doesn't send messages and when within 10 minutes tells my session can't be restored

### ISSUE THREAD

**Issue by SanderBuruma** [vector-im/element-web#24771] opened 2023-03-08 13:03 UTC
### Steps to reproduce

1. I start up element
2. It tells me that my session is no longer good and gives me the option to sign out
3. Sign out
4. I log in from scratch with username, password and backup key.
5. I see everyone else's messages after they are decrypted
6. I try to send a message but it doesn't get sent
7. Within 10 minutes session can't be restored again
8. return to step 2

#### What did you expect?
being able to send messages and retain a session for 10+ minutes
#### What happened instead?
Get a message that my messages can't get sent. 10 minutes or so in I can't recover session even though I can read some messages and I can send a bug report and sign in again

### Operating system

Windows

### Application version

I can't access the Help & About without being logged in

### How did you install the app?

https://element.io/download

### Homeserver

matrix.tradcatholic.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-03-08 13:05
Duplicate of https://github.com/vector-im/element-web/issues/24560

**Closed by t3chguy** 2023-03-08 13:05 UTC
Labels: T-Defect
