### ISSUE TITLE
Starting message with colon-emoji-code doesn't pop chooser on first try

### ISSUE THREAD

**Issue by afranke** [vector-im/element-web#25306] opened 2023-05-08 12:50 UTC
### Steps to reproduce

1. Go to any room, send a first message and keep the entry focused so it’s in a “reset” state.
2. Start typing `:think` and wait. Notice how nothing happens.
3. Delete what you just typed, then type `:think` again. The chooser now shows as expected.

#### What did you expect?

Chooser shows every time.

#### What happened instead?

Chooser only shows on second try.

### Operating system

Fedora

### Browser information

Firefox 112

### URL for webapp

app.element.io

### Application version

Element version: 1.11.30 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-05-09 07:40
Duplicate of https://github.com/vector-im/element-web/issues/25170

**Closed by t3chguy** 2023-05-09 07:40 UTC
Labels: T-Defect

**Comment by afranke** [comment] 2023-05-09 09:40
Fair enough. I did a search before filing this, but was focused on emoji behaviour.
