### ISSUE TITLE
Mardown syntax detected in URLs

### ISSUE THREAD

**Issue by basxto** [vector-im/element-web#16057] opened 2021-01-01 15:56 UTC
### Description

Markdown syntax gets erroneously detected in links

### Steps to reproduce
Write `https://play.workadventu.re/_/frama_day5/raw.githubusercontent.com/frama19/rc3-world-FraMa/day5/outside.json vs https://test.visit.at.wa-test.rc3.cccv.de/_/global/raw.githubusercontent.com/frama19/rc3-world-FraMa/day5/outside.json`

Logs being sent: no

![2021-01-01_16:53_893x40](https://user-images.githubusercontent.com/1314450/103441930-d5534c00-4c51-11eb-94af-9decc6299602.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.7.16

**Comment by t3chguy** [comment] 2021-01-01 15:57
Duplicate of https://github.com/vector-im/element-web/issues/4674

**Closed by t3chguy** 2021-01-01 15:57 UTC
Labels: bug
