### ISSUE TITLE
Improve Conference call discoverability when one starts

### ISSUE THREAD

**Issue by Caspy7** [vector-im/element-web#16024] opened 2020-12-22 23:29 UTC
Firefox Nightly 86.0a1 
Element version: v1.7.16
****
I saw a notification that a channel I was in was starting a conference call.
The notification looked like this:
![image](https://user-images.githubusercontent.com/3854676/102941520-87cc2780-4478-11eb-805d-1ecd1aac2f69.png)
I looked at the top of the room and saw this:
![image](https://user-images.githubusercontent.com/3854676/102941589-b77b2f80-4478-11eb-88de-56352584f7f8.png)
giving me no hint about how to join this conference call.

If we direct users to "look up" we need to give them an easier way to discover what they're looking for. At first I just assumed that something was broken. I clicked the info button and found nothing relevant.

**Comment by turt2live** [comment] 2020-12-23 01:16
Pretty sure this is actually a bug - there should be a conference call there. Considering it's not on the info card, I'm counting this as a duplicate of https://github.com/vector-im/element-web/issues/15991

**Closed by turt2live** 2020-12-23 01:16 UTC
Labels: bug, ui/ux
