### ISSUE TITLE
Can't register on app.element.io on 1366x768 laptop

### ISSUE THREAD

**Issue by chrwei** [vector-im/element-web#20165] opened 2021-12-13 17:46 UTC
### Steps to reproduce

1. use a small screen laptop or size your browser window to be smaller than 800px tall, or document viewport to be less than 600px tall.
2. go to https://app.element.io/#/register
3. there's no scroll bar, and the register button is below the bottom of the screen.

 

#### What did you expect?
a scroll bar to access the register button

#### What happened instead?
no scroll bar, can't register.

### Operating system

windows

### Browser information

up to date chrome

### URL for webapp

https://app.element.io/#/register

### Will you send logs?

No

**Comment by aaronraimist** [comment] 2022-01-17 23:12
Thanks for the bug report. This issue has already been reported as https://github.com/vector-im/element-web/issues/19548. You can thumbs up that issue if you would like to.

Duplicate of https://github.com/vector-im/element-web/issues/19548

**Closed by aaronraimist** 2022-01-17 23:12 UTC
Labels: T-Defect, S-Major, A-Registration, O-Uncommon
