### ISSUE TITLE
Shared locations do not show up in bubbles

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-web#20918] opened 2022-02-04 17:11 UTC
### Steps to reproduce

1. In any Element app, share your location
2. View the location Element Nightly Version 2022020401 with bubbles view enabled

#### What did you expect?
The location pin overlaid on a map should be visible in the timeline, within a bubble

#### What happened instead?
A large empty space shows in the timeline in place of the location
![Screenshot 2022-02-04 at 15 51 15](https://user-images.githubusercontent.com/87766619/152572380-45a366b8-bcd2-43aa-973f-accb0c793449.png)

### Operating system

MacOS

### Application version

Element Nightly Version 2021120601

### Will you send logs?

No

**Comment by robintown** [comment] 2022-02-04 17:18
Duplicate of https://github.com/vector-im/element-web/issues/20916

**Closed by robintown** 2022-02-04 17:18 UTC
Labels: T-Defect

**Comment by jakewb-b** [comment] 2022-02-04 17:20
@robintown - the issue recorded in 20916 is 'timestamp and text overlapping' which appears to me to be different, which is why I created the additional issue. Are you confident this is a duplicate?

**Comment by robintown** [comment] 2022-02-04 17:22
Yes, because even if a visually glitchy alt text appears, it seems the real problem is just that the map is not rendering at all.
