### ISSUE TITLE
"Some of your messages have not been sent" but no unsent messages to be found

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#19675] opened 2021-11-10 09:00 UTC
When I opened Element this morning I saw this when displaying `#synapse-dev`:

![image](https://user-images.githubusercontent.com/5547783/141081792-48f67680-8fe6-41be-b922-16c737dd8e2f.png)

But a) the dialog doesn't show me which messages have failed to send (my latest message in the room was yesterday morning), and b) scrolling up on the timeline doesn't show any message with a red circle in front of them (which iirc is what should show when a message fails to send?).

**Comment by babolivier** [comment] 2021-11-10 09:00
Have sent logs

**Comment by babolivier** [comment] 2021-11-10 10:35
Sorry I realise I forgot to mention the version I was running :man_facepalming: it's whatever was running on develop.element.io, currently it's

Element version: 28f00498a2b2-react-71d894664113-js-b07d44a6c057
Olm version: 3.2.3

But I'm not sure if it's the same now as it was then

**Comment by dbkr** [comment] 2021-11-10 14:54
This will probably be a reaction or some similar event that isn't rendered as its own tile that's failed to send.

**Comment by novocaine** [comment] 2021-11-12 13:46
I think this is most likely a duplicate of https://github.com/vector-im/element-web/issues/18403

**Comment by babolivier** [comment] 2021-12-02 10:18
> I think this is most likely a duplicate of #18403

I'm not sure it is, actually. It's happened just now in HQ, in which I interact little enough to be able to easily remember what I've sent. With a new account, I sent exactly 3 messages (4 if counting edits) and no other event (so no reaction, etc) and all are showing up as sent in the timeline. But when I opened Element Web a few minutes ago, it showed me the "Some of your messages have not been sent". I've also checked with another account and all of these messages show as sent.

I've sent a rageshake about this.

**Comment by novocaine** [comment] 2021-12-02 10:52
Thanks.

To track this, we can log what the unsent event actually is so it'll show up in rageshakes.

**Comment by turt2live** [comment] 2022-05-07 02:00
Closing in favour of https://github.com/vector-im/element-web/issues/21615 pending more information.

**Closed by turt2live** 2022-05-07 02:00 UTC
Labels: T-Defect, S-Major, A-Timeline, Z-Rageshake, O-Occasional
