### ISSUE TITLE
OpenBSD -  Unknown platform

### ISSUE THREAD

**Issue by pau-amaro-seoane** [vector-im/element-web#16321] opened 2021-01-30 19:35 UTC
When trying to build element, after `yarn run build`, I get `Error: Unknown platform: openbsd`

Is there a way for you to address this and allow openbsd users to have a port of element desktop?

thanks

**Comment by jryans** [comment] 2021-02-01 11:09
@pau-amaro-seoane, are there builds of Electron for OpenBSD...? I don't see it on their [supported platforms](https://www.electronjs.org/docs/tutorial/support#supported-platforms). Assuming Electron is not supported, I would recommend using Element Web in a browser.

**Comment by pau-amaro-seoane** [comment] 2021-02-01 14:08
electron is there: 

https://openports.se/devel/electron

https://cloudflare.cdn.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/electron-8.2.0p0.tgz

**Comment by t3chguy** [comment] 2021-02-01 16:41
I think the issue is lack of support from https://www.electron.build/ which is what `yarn run build` runs directly. Though it claims to have `freebsd` support.

**Comment by jryans** [comment] 2021-02-08 15:52
Right, as @t3chguy says, it's not a supported platform via `electron-builder`, so you would likely need to maintain a custom build pipeline for this.

**Comment by jryans** [comment] 2021-02-08 15:53
Also, while it may exist in OpenBSD, that's quite old version. Given this, I don't think this is something core team can support at this time, so I'll close the issue.

**Closed by jryans** 2021-02-08 15:53 UTC
Labels: suggestion, type:packaging
