### ISSUE TITLE
Error when joining room from space summary

### ISSUE THREAD

**Issue by AndrewFerr** [vector-im/element-web#23079] opened 2022-08-15 14:54 UTC
### Steps to reproduce

1. Viewed a space's summary to search for a room in it
2. Clicked "Join" for a room that the search turned up
3. Got a crash screen & was prompted to submit a case for it

#### What did you expect?
I should have just joined the room.

#### What happened instead?
The room join ~failed~ succeeded but an error page showed up.

### Operating system

Fedora Linux 36 (Workstation Edition)

### Browser information

Firefox 103.0.2

### URL for webapp

chat.element.io

### Application version

1.11.2

### Homeserver

https://element.ems.host

### Will you send logs?

Yes

**Comment by AndrewFerr** [comment] 2022-08-15 14:55
Turns out the room join succeeded after all!  Not sure what the error was, then.

**Comment by t3chguy** [comment] 2022-08-15 14:57
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-08-15 14:57 UTC
Labels: T-Defect
