### ISSUE TITLE
Using gitter, and it is always showing (1) in browser tab etc. Mark all as read not working

### ISSUE THREAD

**Issue by scaddenp** [vector-im/element-web#25638] opened 2023-06-20 21:06 UTC
### Steps to reproduce

https://app.gitter.im/?#/room/#serenity-bdd_serenity-core:gitter.im/$w9qDn7T2oBpJ7ZKNe5_KLOZY623k-fmv6f5L9ImuRmg
is where I am having problem.

![image](https://github.com/vector-im/element-web/assets/225041/a94dd241-6a64-4fc1-92ce-16cc6aa68dae)

and
![image](https://github.com/vector-im/element-web/assets/225041/f7b79b42-9d07-4418-b565-f9e37b8786b3)

If I scroll up, I get to see "Jump to new Messages" and "Mark all as read" widgets on right. Jump to new messages doesnt take me to anything I havent read, and Mark all as read doesnt do anything

### Outcome

I expect the Element icon on the browser to be clear and room indicator not to show any numbers

Nothing I do changes that. Updated to latest version, Cleared Cache and Reload.

### Operating system

Windows 10

### Browser information

Chrome 114.0.5735.134

### URL for webapp

https://app.gitter.im/?#/room/#serenity-bdd_serenity-core:gitter.im

### Application version

Gitter version: 1.11.34 Olm version: 3.2.14

### Homeserver

homeserver

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-06-21 08:51
Thank you for reporting the issue @scaddenp . There are currently a bunch of issues under investigation around stuck notifications: https://github.com/vector-im/element-web/issues/24392

The one you are mentioning specifically should be https://github.com/vector-im/element-web/issues/24595

I am going to close this issue. You should track the other issues for updates on this topic.

**Comment by weeman1337** [comment] 2023-06-21 08:51
Duplicate of https://github.com/vector-im/element-web/issues/24595

**Closed by weeman1337** 2023-06-21 08:51 UTC
Labels: T-Defect, S-Minor, A-Notifications, O-Uncommon
