### ISSUE TITLE
Ability to deliberately delete megolm keys for a room

### ISSUE THREAD

**Issue by Zborniev** [vector-im/element-web#4687] opened 2017-07-27 14:54 UTC
Megolm room keys seem to hang around forever, and the new key share logic seems to make them spread even further.  What do I do if I want to deliberately delete my keys for a specific room or set of messages, so that it is properly off the record and forgotten?

**Comment by kittykat** [comment] 2021-12-21 13:37
Duplicate of #4104

**Closed by kittykat** 2021-12-21 13:37 UTC
Labels: P2, A-E2EE, T-Enhancement
