### ISSUE TITLE
No X in the new search

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#22779] opened 2022-07-08 10:41 UTC
### Steps to reproduce

1. Open the new search (ctrl +k)
2. No X...

https://aarenet-my.sharepoint.com/:v:/p/chagai_friedlander/EcMwARPinZFJnaxLkij4MD0B87Px4zxuafsMCHxzwS4G8A

#### What did you expect?
An X
#### What happened instead?
I did not see one.

### Operating system

Windows

### Browser information

102.0.5005.115 (Official Build) (64-bit)

### URL for webapp

https://app.element.io

### Application version

Element version: 1.11.0 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by turt2live** [comment] 2022-08-11 21:28
Duplicate of https://github.com/vector-im/element-web/issues/22566

**Closed by turt2live** 2022-08-11 21:28 UTC
Labels: S-Minor, T-Enhancement, O-Occasional, A-New-Search-Experience, Team: Delight
