### ISSUE TITLE
"Connectivity to the server has been lost" after connection works again

### ISSUE THREAD

**Issue by codemmmmm** [vector-im/element-web#25604] opened 2023-06-15 07:25 UTC
### Steps to reproduce

1. Use element normally
2. Lost network connection (switching from WIFI to ethernet)
3. Network connection restored

Similar to https://github.com/vector-im/element-web/issues/14529 and my previous issue https://github.com/vector-im/element-web/issues/24988 . I opened another issue because this time I have logs of the connection being restored automatically (after too long) without restarting and I didn't know if I can just send logs for the old issue again.

#### What did you expect?

Element should reconnect to the server automatically and quickly.

Sending and receiving messages should work again.

#### What happened instead?

Element took a few minutes to reconnect.

### Operating system

Arch Linux

### Application version

Element version: 1.11.31 Olm version: 3.2.14

### Homeserver

tu-dresden.de

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-06-15 07:34
> I can just send logs for the old issue again.

You can, but in this instance I'll re-attach them.

Duplicate of https://github.com/vector-im/element-web/issues/24988

**Closed by t3chguy** 2023-06-15 07:34 UTC
Labels: T-Defect
