### ISSUE TITLE
No option to remap (or at least disable) keyboard shortcuts

### ISSUE THREAD

**Issue by ksze** [vector-im/element-web#14909] opened 2020-08-07 14:48 UTC
![image](https://user-images.githubusercontent.com/381556/89656495-3e7e9f80-d8fe-11ea-9926-ae1fd01a9695.png)

# Description

I use element-web at chat.mozilla.org and it's super annoying that it overrides my keyboard shortcuts with no option for me to opt out. For example, `Ctrl+.` is usually bound to open the Firefox Multi-Account Containers extension menu, but it's hijacked by element-web to open the channel member list.

I looked for a setting to disable keyboard shortcuts but can't find anything like that.

### Steps to reproduce

- go to any website running element-web and log into the matrix service
- click on your own avatar on the top left
- in the menu that pops up, select "All settings"
- realise that there is no option to change or opt out of the keyboard shortcuts there, and despair

I expect there to be an option in element-web itself to at least disable the keyboard shortcuts.

Some people may argue that in Firefox, I could right-click the page, open "View Page Info", go to the "Permissions" tab, and block "Override Keyboard Shortcuts" there:
![image](https://user-images.githubusercontent.com/381556/89657671-024c3e80-d900-11ea-89e9-868006011d58.png)

However, that "solution" is completely besides the point. There is simply no guarantee that any particular browser supports that kind of control. element-web should itself be a good citizen and present the option to opt out of keyboard shortcuts to the user.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 79 (but really, this is browser independent)
- **OS**: Ubuntu (but really, this is OS independent)
- **URL**: chat.mozilla.org

**Comment by t3chguy** [comment] 2020-08-08 09:44
Duplicate of https://github.com/vector-im/element-web/issues/12645 / https://github.com/vector-im/element-web/issues/12492

**Closed by t3chguy** 2020-08-08 09:44 UTC
Labels: bug, ui/ux
