### ISSUE TITLE
The hopeful emoji is very sad

### ISSUE THREAD

**Issue by daenney** [vector-im/element-web#17924] opened 2021-07-09 15:38 UTC
#### Description

The hopeful emoji is very sad.

#### Steps to reproduce
- Type `:hopeful` in the input field
- Be sad

![Screenshot from 2021-07-09 17-36-52](https://user-images.githubusercontent.com/569574/125103077-492c5080-e0dc-11eb-8dfb-fa4bdd59359d.png)

The description of the `:hopeful:` emoji reads: "Sad but relieved face"

#### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Btw, I run Arch Linux
- **Version**: 1.7.29

**Comment by t3chguy** [comment] 2021-07-09 15:39
Duplicate of https://github.com/vector-im/element-web/issues/13857

**Closed by t3chguy** 2021-07-09 15:39 UTC
Labels: T-Defect
