### ISSUE TITLE
Add Settings Option to Disable Smooth Scrolling

### ISSUE THREAD

**Issue by sktsee** [vector-im/element-web#24081] opened 2022-12-21 17:46 UTC
#### What would you like to do?
I would like to be able to disable smooth scrolling in the Linux version of Element-desktop.
#### Why would you like to do it?
Smooth scrolling is anything but a smooth UI experience. For one, not enough lines are scrolled with a mouse wheel. 3 or 4 at best. Secondly, the scrolling is slow and pauses after 3 or 4 lines. I've turned off smooth scrolling in multiple applications that support it because of the above listed issues. It's not very well implemented and uses the cpu excessively.
#### How would you like to achieve it?
I'd like an option in the Appearance, or Preferences sections under Settings to be able to toggle smooth scrolling on or off.

### Have you considered any alternatives?

none.

### Additional context

nope.

**Comment by SimonBrandner** [comment] 2022-12-22 10:34
Duplicate of https://github.com/vector-im/element-web/issues/15850

**Closed by SimonBrandner** 2022-12-22 10:34 UTC
Labels: T-Enhancement
