### ISSUE TITLE
only show spaces sidebar if more than one space is used by user

### ISSUE THREAD

**Issue by dukepeet** [vector-im/element-web#24714] opened 2023-03-01 17:03 UTC
#### What would you like to do?
i'd like to not see the spaces sidebar and the Home "space" if i'm only using a single space. (if i start a private chat with someone from a different space, without joining the space itself, which i heard is possible, that would count as using multiple spaces already, in this context.)

#### Why would you like to do it?
it makes no difference to have a Home "space" in addition to the space itself, if multiple spaces are not in use.
it gives rise to possible confusion when people click a notification and it takes them through the levels of element/home > space > room [> thread], and when they want to quit, they feel like they have to quit the same space twice. i guess similar issues are possible which are only relevant in this context.
altogether, the Home "space" is practically useless in this case, which in turn should render the spaces sidebar useless as well. (the "add space" and "browse spaces" options could be available through the profile menu or something similar.)

#### How would you like to achieve it?
i'd like to automatically disable the spaces sidebar and the Home space until i start using multiple spaces.

### Have you considered any alternatives?

i've considered Slack as an alternative :D as they do it roughly the way i described, and my use case seems to be no different across the two apps. now my mind is too narrowed to be able to think of other ways or use cases, sorry :)

**Comment by t3chguy** [comment] 2023-03-01 17:04
Duplicate of https://github.com/vector-im/element-web/issues/18898

**Closed by t3chguy** 2023-03-01 17:04 UTC
Labels: T-Enhancement

**Comment by dukepeet** [comment] 2023-03-01 17:15
@t3chguy i think this is not a duplicate as #18898 aims to allow users to close the spaces bar if they so choose, but i'm suggesting to completely disable it (and also the Home view) as long as a user has no access to more than one space.
i did first search for this issue being reported, saw #18898 and understood it as a different request, hence i opened this issue.

please reopen it or give a different (or more detailed :) ) justification. im a newbie, thanks for the patience 0:)

**Comment by t3chguy** [comment] 2023-03-01 17:20
@dukepeet #18898 tracks all variations of "Not everyone needs a space panel" - even if you have 1 space, + Home, you need a way to change between them. 

> it makes no difference to have a Home "space" in addition to the space itself, if multiple spaces are not in use.

This isn't the case, Home (with all rooms not enabled) will sow rooms which are not in that 1 space you are in.

I suggest adding your opinion to the meta issue which will be used by product & design to derive a solution from.

**Comment by dukepeet** [comment] 2023-03-01 17:48
@t3chguy thanks, it's not clear from the description that
> #18898 tracks all variations
so i'd suggest then changing that or phrasing it differently (especially the title! i like yours much better, you could create a meta-issue with that title and reference the current open one, if you don't want to override that) or only tracking comments that are relevant to that bug and not changing the scope midway through the discussion, as this only occurred to me by reading through dozens of comments.
[the last of which](https://github.com/vector-im/element-web/issues/18898#issuecomment-1179328959) on this specific proposal is actually that "this thread is still about making the spaces bar always toggleable, regardless whether the user has already joined a space".

fwiw 
> even if you have 1 space, + Home, you need a way to change between them.
is fair but that does not warrant the need for a sidebar. however,
> [show] rooms which are not in that 1 space you are in
would be a different use case to what i suggested; mine is about cases when only a single space is used without any rooms that'd belong to a different space.

all in all i think i still consider my argument on this not being a duplicate valid :) thanks for the quick and useful feedback though, i appreciate that a lot! :)

**Comment by t3chguy** [comment] 2023-03-02 13:35
> would be a different use case to what i suggested; mine is about cases when only a single space is used without any rooms that'd belong to a different space. hence my argument that in this case, even the home view is unnecessary.

I suggest opening an issue in https://github.com/vector-im/element-meta/ if you feel like this is a case that should get special support by Element

**Comment by dukepeet** [comment] 2023-03-07 09:16
@t3chguy why is that a more suitable place? :)

**Comment by t3chguy** [comment] 2023-03-07 09:47
Because whether the Element clients give special treatment to users in exactly 1 space with 0 orphaned rooms should be considered cross-platform
