### ISSUE TITLE
Sticky headings jockey for position causing scroll jitter in room list

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#18440] opened 2021-08-06 20:40 UTC
### Steps to reproduce

This bug depends on your viewport height compared to one of your room list sub-sections.

 1. Start with a big viewport, and have a room subsection expanded where all of it fits on screen
 1. Resize to shrink your viewport so that it's just big enough to show the whole room subsection. Then shrink a bit more so that the headings overlap when you scroll down
 1. Scroll to the bottom of the room list
 1. Notice the jitter

I have reproduced this with Chrome on Windows and the Element desktop app on macOS but seems like it would happen in any environment.

I have also reproduced this with several different room sub-sections and also when switched to a space.

Related issues:

 - https://github.com/vector-im/element-web/issues/17864
 - https://github.com/vector-im/element-web/issues/17460
 - https://github.com/vector-im/element-web/issues/18366
 - https://github.com/vector-im/element-web/issues/14085

### What happened?

The whole scrollable room list area jitters up and down as the different sticky headings jockey for position (jumpy).

https://user-images.githubusercontent.com/558581/128567603-cc95887d-05e2-45e5-b8c6-8e9c17b205cd.mp4

### What did you expect?

The headings would have a steady state no matter how big the viewport is.

### Operating system

Windows, macOS

### Browser information

Chrome, Element desktop app

### URL for webapp

develop.element.io

**Comment by robintown** [comment] 2021-08-06 20:52
Duplicate of https://github.com/vector-im/element-web/issues/18440

**Comment by MadLittleMods** [comment] 2021-08-09 23:22
> https://user-images.githubusercontent.com/769871/124301357-9c8c2500-db57-11eb-86cc-a9d7463254de.mov
> 
> Issues with:
> 
> - `End` keyboard shortcut
> - `Type.Unregister`
> 
> View conversation https://matrix.to/#/!aDqOGCgMtPXQREzAWj:pvagner.tk/$iQrjry688G69WQ2fB_XyoYXaIXo2YbHLNWU01wAfpPI?via=pvagner.tk&via=matrix.org&via=t2l.io
> 
> *-- @gsouquet, https://github.com/vector-im/element-web/issues/17864*

**Closed** 2021-09-14 19:40 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Room-List, O-Intermediate
