### ISSUE TITLE
When a few versions behind, Nightly doesn't update to the latest version on macOS

### ISSUE THREAD

**Issue by thibaultamartin** [vector-im/element-web#24230] opened 2023-01-13 14:07 UTC
### Steps to reproduce

1. Use a nightly from Jan 8
2. Be on Jan 13
3. Go to option, check for updates
4. Click the update button
5. Element updates to the 2023011201 nightly and tells you a new update is available
6. Be a little sad, but hey it's a nightly after all

#### What did you expect?

I expected Element to update to the latest version directly.

#### What happened instead?

I updated to a nightly between my outdated one and today's nightly.

### Operating system

macOS

### Application version

Element Nightly version: 2023011201

### How did you install the app?

https://element.io/get-started#nightly

### Homeserver

Synapse 1.73

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-01-13 14:24
Duplicate of https://github.com/vector-im/element-web/issues/19372

**Closed by t3chguy** 2023-01-13 14:24 UTC
Labels: T-Defect, S-Minor, A-Electron-Nightly, O-Occasional
