### ISSUE TITLE
Element web app hangs on "Verify this login", with an "Incoming verification request - waiting for a partner to confirm" dialog open

### ISSUE THREAD

**Issue by callegar** [vector-im/element-web#14997] opened 2020-08-18 16:01 UTC
### Description

After having tried RiotX on a mobile phone, I have been told to upgrade to Element. I did it on the phone, on a tablet and also tried the web app on Firefox for linux, using an Ubuntu 20.04 machine. Install on the phone apparently went fine, without asking anything. On the tablet I got a request to "validate" and I succeded in doing it with the phone. On the web app I cannot proceed, because the app gets stuck in the situation in subject after validating it from the phone.

I wonder if this may happen because the web app was open when I validated the tablet, and some stale information is there.

I have tried clearing the web app data, but this seems to make no difference.

### Steps to reproduce

- Open the app on firefox, get sign in dialog
- Sign in
- See the "Verify this login dialog"
- Note that in mobile phone app one has a new access dialog "Was it you?" click on it
- Press scan code on mobile phone app
- Scan the code, get the "almost there" dialog on both the mobile phone app and the web app on the computer
- Note that on the web app you are invited to check if you see the same shield on the other device. Press yes.

Web app now hangs on "Verify this login".

If after the second point you proactively try to verify the session from the mobile phone using the session manager and you do it with the emoji sequence, then when the web app hangs you also get the "incoming verification request - waiting for a partner to confirm" dialog.

Describe how what happens differs from what you expected.

Logs being sent: yes/no Probably not

Can this be done, given that the web app hangs?

You should be able to verify your session in the web app, without anything hanging.

### Version information

- **Platform**: web (in-browser) or desktop? WEB

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?   Firefox 79
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Ubuntu
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web? app.element.io

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by callegar** [comment] 2020-08-18 16:05
Just tested, exactly the same issue using chrome.

**Comment by callegar** [comment] 2020-08-18 16:08
When the web app hangs, the mobile phone app shows a validated session for it in the session manager.
If at this point you go to the web app and you reload the page, the web app asks to log in again and then to verify again, until you accumulate a new session in the mobile app...

**Comment by sebthom** [comment] 2020-08-18 18:55
Having the same/similar issue. Trying to connect element-web 1.7.4 with a private server running 1.19.0.
I can verify the browser session via the QR code on the mobile app but then the screen hangs at "Verify this login" for ever.

![image](https://user-images.githubusercontent.com/426959/90553743-2c6dee00-e195-11ea-9bd6-a8d5d9d6d6e8.png)

**Comment by kayb94** [comment] 2020-08-19 08:39
I have the very same issue

**Comment by t3chguy** [comment] 2020-08-19 16:16
@sebthom was your mobile phone app iOS or Android?
@kayb94 same for you.

**Comment by sebthom** [comment] 2020-08-19 16:57
> @sebthom was your mobile phone app iOS or Android?
> @kayb94 same for you.

Android

**Comment by callegar** [comment] 2020-08-19 17:51
Android for me as well...

**Comment by t3chguy** [comment] 2020-08-20 09:09
We believe this to be an Element Android bug, duplicate of https://github.com/vector-im/element-web/issues/14970

**Comment by callegar** [comment] 2020-08-20 09:52
Can you please clarify the consequences?
Does one need to wait for an updated android version to be able to also use the element web app, or is there an alternate way to force the web app access to be considered validated?

**Comment by t3chguy** [comment] 2020-08-20 09:57
You can always use your security key/passphrase to validate the device non-interactively during log in

**Comment by callegar** [comment] 2020-08-20 11:23
Exactly the same things happens using a IOS client for the validation, though.

**Comment by jryans** [comment] 2020-08-20 16:12
I'll reopen this for now then.

**Comment by t3chguy** [comment] 2020-08-20 16:17
@jryans how is it different from https://github.com/vector-im/element-web/issues/14970

**Comment by shanel** [comment] 2020-08-21 01:37
I am running into this issue as well. I have the Android app. I have tried getting both the web app and the OS X app to login using the android app and they both hang as above. I will note that if I look on the phone in the Security & Privacy settings it *does* say there are three active sessions - my phone, my os x app, and the web app. But if I restart say my OS X app it will restart logged in but say I need to verify the session.

**Comment by kayb94** [comment] 2020-08-25 13:01
I just sent two logs, too (before things went wrong and after, the first one was a mistake)

**Comment by nrbray** [comment] 2020-08-25 20:03
Same problem for me: Element on Android 9, Chrome on Ubuntu 18.04.

mxSendRageshake("https://github.com/vector-im/element-web/issues/14997 Logs", true);
rageshake.js:65 Collecting app version information
rageshake.js:65 Sending bug report.
undefined
rageshake.js:65 Collecting logs
rageshake.js:65 Uploading report
rageshake.js:65 Waiting for response from server
rageshake.js:65 Bug report sent!

Also sent logs via App from nrbray with a same as #14997 in the title or comment

**Comment by jryans** [comment] 2020-09-02 13:47
Thanks to everyone who reported logs here. After looking in more detail and reproducing the issue locally, I believe this is indeed the same as https://github.com/vector-im/element-web/issues/14970, and I have fixes in progress for web to resolve this tracked on that issue. With that in mind, I'll close this as a duplicate of https://github.com/vector-im/element-web/issues/14970.

**Closed by jryans** 2020-09-02 13:47 UTC
Labels: bug, feature:e2e-cross-signing, feature:e2e-sas-verification, major, needs-investigation, p1
