### ISSUE TITLE
Flaky test: lazy loading

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23271] opened 2022-09-13 15:01 UTC
```
  Lazy Loading
Copy /home/runner/work/matrix-react-sdk/matrix-react-sdk/cypress/plugins/synapsedocker/templates/default -> /home/runner/work/_temp/react-sdk-synapsedocker-Y0z1wa
Gen /home/runner/work/matrix-react-sdk/matrix-react-sdk/cypress/plugins/synapsedocker/templates/default/homeserver.yaml
Gen /home/runner/work/matrix-react-sdk/matrix-react-sdk/cypress/plugins/synapsedocker/templates/default/localhost.signing.key
Starting synapse with config dir /home/runner/work/_temp/react-sdk-synapsedocker-Y0z1wa...
Started synapse with id aa18a9c55867b43b6a56df29be50cd377aa026beac8a432e80128a0cca3c6f35 on port 46219.
    1) should handle lazy loading properly even when offline
Stopped synapse id aa18a9c55867b43b6a56df29be50cd377aa026beac8a432e80128a0cca3c6f35.


  0 passing (45s)
  1 failing

  1) Lazy Loading
       should handle lazy loading properly even when offline:
     AssertionError: Timed out retrying after 10000ms: Expected not to find content: 'Charly #6' within the selector: '.mx_MemberList .mx_EntityTile_name' but continuously found it.
      at eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/lazy-loading/lazy-loading.spec.ts:210:55)
  at Array.forEach (<anonymous>)
      at checkMemberListLacksCharlies (http://localhost:8080/__cypress/tests?p=cypress/e2e/lazy-loading/lazy-loading.spec.ts:209:18)
      at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/lazy-loading/lazy-loading.spec.ts:242:9)
```

**Comment by robintown** [comment] 2022-09-15 13:04
Duplicate of https://github.com/vector-im/element-web/issues/23154

**Closed by robintown** 2022-09-15 13:04 UTC
Labels: T-Defect, S-Minor, A-Testing, O-Occasional, Z-Flaky-Test
