### ISSUE TITLE
unbanning doesn't work over federation?

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#3666] opened 2017-04-20 12:30 UTC
Seems that if you ban then unban someone over federation, they're still not allowed to join the room. Probably because if they were the only user on that server, that server is no longer in the room, therefore the unban doesn't propagate, so their server still thinks they're banned. (It's even worse because you can re-invite the user, but their server still thinks they're banned and so doesn't even let them reject the invite).

**Comment by richvdh** [comment] 2017-04-20 13:07
https://github.com/matrix-org/synapse/issues/1563

**Comment by grinapo** [comment] 2021-01-06 00:24
Am I observe correctly that this bug is actually screwing up unbans since 2016? User cannot join a room anymore any way.

**Comment by t3chguy** [comment] 2021-01-06 00:26
Its an edge case bug for if only that one user from that server is in the room, in which case the server won't see the unban. Either way it really doesn't belong on the element-web bug tracker :(

**Comment by kittykat** [comment] 2021-08-03 10:03
I'm closing this issue because the problem is with the server, see matrix-org/synapse#1563

**Closed by kittykat** 2021-08-03 10:03 UTC
Labels: P2, S-Critical, T-Defect, Z-Synapse
