### ISSUE TITLE
Set username/nick for the space

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18609] opened 2021-08-18 08:44 UTC
#### What would you like to do?
In the same way that I can set `/myroomnick`, I want to be able to set `/myspacenick`

#### Why would you like to it?
e.g. I want to add "(away)" or "(back on <date>)" to my username in my work space, but not my other spaces or
Set my real name in my workspace and nick in my other spaces or

#### How would you like to achieve it?
I found /myroomnick to be undiscoverable (I found it by accident because I'm familiar with /nick from IRC), but convenient once I knew about it.

I would like to be able to set this in the space settings overlay for spaces, and room settings for rooms.

### Have you considered any alternatives?

n/a

### Additional context

Triaging as S-Major because there are no suitable workarounds. Not sure on prevalence.

**Comment by SimonBrandner** [comment] 2021-08-18 08:47
Duplicate of https://github.com/vector-im/element-web/issues/17177

**Closed by SimonBrandner** 2021-08-18 08:47 UTC
Labels: S-Major, A-Spaces, T-Enhancement
