### ISSUE TITLE
Read markers occlude notice messages

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#17161] opened 2021-05-04 15:49 UTC
In IRC.  As shown in https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$2XoYbgXZILForsQ9CNdVzpocWAgBmWkuyXf7vxzMeCo?via=matrix.org&via=privacytools.io&via=mozilla.org

**Comment by jryans** [comment] 2021-05-04 15:51
Seems perhaps specific to IRC layout.

**Comment by Biep** [comment] 2021-05-04 15:52
I have to wait till the markers move before I can read the hidden part - or play with the window size.

**Comment by psrpinto** [comment] 2021-08-16 15:17
Adding screenshot:

![image](https://user-images.githubusercontent.com/550401/129586626-6414ade7-b490-44d2-8061-41268654f396.png)

The title of this issue is "Read markers occlude notifications" but, if I understand correctly, the issue is that, when using the IRC layout, read markers occlude part of the message. Is this correct @Biep?

**Comment by dbkr** [comment] 2022-01-17 12:02
I'm going to jump in and say, yes, this seems like it's probably the correct summary. Presumably the correct fix is that all messages, including notices, should have a right margin big enough to avoid the read marker gutter? Or is this explicitly not desired for IRC mode and iwe should fix it some other way? @janogarcia - can you confirm?

**Comment by t3chguy** [comment] 2022-05-07 11:18
Those are Read Receipts (not markers) and this is now fixed

**Closed by t3chguy** 2022-05-07 11:18 UTC
Labels: T-Defect, P2, S-Tolerable, A-Timeline, X-Needs-Design, A-Read-Marker, A-IRC-Layout, O-Occasional
