### ISSUE TITLE
Option to auto translate all messages in a room to a language of your choice 

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#15199] opened 2020-09-15 14:11 UTC
Customer request.

**Is your suggestion related to a problem? Please describe.**
To make it easier for someone that does not speak the language of a room to follow along.

**Describe the solution you'd like**
A setting somewhere where you can enable auto translation of all messages into a language of your choice.

**Describe alternatives you've considered**
No good options currently other than copy-pasting individual messages into Google Translate or similar service. Which is labor intensive and not very fun.

**Comment by t3chguy** [comment] 2020-09-15 14:14
Duplicate of https://github.com/vector-im/element-web/issues/103

**Closed by t3chguy** 2020-09-15 14:14 UTC
Labels: suggestion
