### ISSUE TITLE
Numerous crashes in various situations

### ISSUE THREAD

**Issue by Anglodel** [vector-im/element-web#24319] opened 2023-01-25 18:30 UTC
### Steps to reproduce

1. **Where are you starting? What can you see?** I launch Element Desktop, and it either crashes a few seconds after the launch, or when there seems to be a key exchange (between clients or the matrix instance, maybe ?)
2. **What do you click?** I clicked nothing. Sometimes it’ll crash at launch during the loading animation, sometimes when the pointer hover over the button to ask the keys to other devices, sometimes when viewing the list of other connected clients/sessions, sometimes when starting to type something…

#### What did you expect?
I expected the app not to crash.
#### What happened instead?
Instead, it crashes in various, not really understandable situations.

I don’t know if the logs I’ll try to send with `/rageshake` will be the same as the ones following, so as there’s no other boxes to place them, here are typical lines that appear in the terminal when the client crashes :
```
➜  ~ element-desktop
/home/symstheir/.config/Element exists: yes
/home/symstheir/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to fr
Fetching translation json for locale: fr
Resetting the UI components after locale change
Resetting the UI components after locale change
libva error: /usr/lib/dri/i965_drv_video.so init failed
Changing application language to fr
Fetching translation json for locale: fr
Resetting the UI components after locale change
[72873:0125/185559.451303:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[1]    72842 trace trap (core dumped)  element-desktop
```

### Operating system

Arch Linux x86_64 / Kernel: 6.1.6-zen1-2-zen

### Application version

Version de Element : 1.11.20 Version de Olm : 3.2.12

### How did you install the app?

Arch repos https://archlinux.org/packages/community/x86_64/element-desktop/

### Homeserver

https:/matrix.underworld.fr

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-01-26 07:35
Hey @Anglodel :wave: Thanks for reporting the issue. Do you run Wayland?

**Comment by Anglodel** [comment] 2023-01-26 12:34
I indeed am using Wayland, with KDE Plasma.
I didn’t think to mention it, nor search if it had already been discussed in another issue, which I usually do. Now I see that there seems to be some precedents, yet I cannot know if the problems have the same causes and if they’re similar.

**Comment by edwargix** [comment] 2023-01-28 19:56
seems to be the same issue: https://github.com/vector-im/element-web/issues/24319

some friends are also experiencing crashing on X with i3 and Xfce

**Comment by t3chguy** [comment] 2023-01-30 13:03
Duplicate of https://github.com/vector-im/element-web/issues/24360

**Closed by t3chguy** 2023-01-30 13:03 UTC
Labels: T-Defect, X-Community-Supported-Platform
