### ISSUE TITLE
MELS should collapse invited+joined+left repeat patterns (e.g. IRC bridged users in private rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8261] opened 2019-01-25 10:55 UTC
Membership `EventListSummary` (MELS) should collapse invited+joined+left repeat patterns (e.g. IRC bridged users in private rooms

**Comment by MadLittleMods** [comment] 2022-10-14 22:08
Duplicate or highly related to https://github.com/vector-im/element-web/issues/5720

**Comment by t3chguy** [comment] 2022-10-17 08:02
Duplicate of https://github.com/vector-im/element-web/issues/5720

**Closed by t3chguy** 2022-10-17 08:02 UTC
Labels: S-Minor, A-Timeline, T-Enhancement, O-Occasional, A-ELS
