### ISSUE TITLE
riot should say 'connecting' when waiting for a webrtc call to connect

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#5619] opened 2017-11-16 13:46 UTC
Right now we have 2 separate state machines for calls, one in js-sdk and one in react-sdk, where the react-sdk one manages the UI state. The react-sdk one is frequently a lie though, eg. it goes to state 'connected' as soon as it make an attempt to send an answer, meaning the UI doesn't at all reflect the actual connection state of the call.

We really should be using the js-sdk state machine rather than having 2 separate ones (although I think it would need to be slightly extended, like with at least a, 'sending_answer' state)

**Comment by lampholder** [comment] 2017-11-22 16:30
I'm calling this a 'bug' due to 'The react-sdk one is frequently a lie'.

**Comment by SimonBrandner** [comment] 2021-07-30 07:15
This is either fixed or a dupe of https://github.com/vector-im/element-web/issues/18220

**Closed by SimonBrandner** 2021-07-30 07:15 UTC
Labels: A-VoIP, P1, S-Minor, T-Defect
