### ISSUE TITLE
Highlights in encrypted non-DM rooms does not result in a red pill

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#23887] opened 2022-12-02 12:13 UTC
Initially filed as #23861, moving to a new issue since this isn't related to threads after all.

### Steps to reproduce

1. Create a new encrypted room
2. Invite at least two other accounts
3. Have one of those accounts highlight/mention another one

#### What did you expect?

Element considers the new message as an outstanding highlight (i.e. notification number in the favicon and red pill in the room list)

#### What happened instead?

The favicon isn't changed, the room doesn't get a red pill in the room list - it just gets a dot to tell me I have missed a message.

https://user-images.githubusercontent.com/5547783/205290335-21739685-e80b-4ec3-8371-75869ac20151.mp4

### Operating system

Arch Linux

### Browser information

Firefox 107.0

### URL for webapp

develop.element.io

### Application version

Element version: 6d724cb4cb38-react-c8877727a582-js-79ccd7c330c2, olm version: 3.2.12

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-12-02 15:34
Duplicate of https://github.com/vector-im/element-web/issues/23885

**Closed by t3chguy** 2022-12-02 15:34 UTC
Labels: T-Defect
