### ISSUE TITLE
Create a distinctive icon for Element Nightly

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#18988] opened 2021-09-10 16:17 UTC
#### What would you like to do?

Have a different favicon for Element Nightly

#### Why would you like to do it?

To easily differentiate between production and nightly environment

#### How would you like to achieve it?

Similarly to what browsers do

### Additional context

![https://i.imgur.com/yMnWI4z.jpg](https://i.imgur.com/yMnWI4z.jpg)

![https://icons.iconarchive.com/icons/google/chrome/icons-390.jpg](https://icons.iconarchive.com/icons/google/chrome/icons-390.jpg)

**Comment by SimonBrandner** [comment] 2021-09-10 16:23
Duplicate of https://github.com/vector-im/element-web/issues/14592

**Closed by SimonBrandner** 2021-09-10 16:23 UTC
Labels: S-Tolerable, X-Needs-Design, T-Enhancement, A-Developer-Experience, O-Low
