### ISSUE TITLE
Element Keeps Crashing, without any action

### ISSUE THREAD

**Issue by ovflowd** [vector-im/element-web#26238] opened 2023-09-26 11:13 UTC
### Steps to reproduce

1. I'm just visualising a random chat
2. It crashes (without any interaction, at random times, with random chats)
3. Crash seems to be an OOM Crash

---

Notes:

- Unable to attach Logs from the moment of the crash, as well, it crashes
- Using certain Labs Features (Video Rooms)
- Location is disabled for Chrome
- Using specific Extensions (Grammarly, U Block Origin, NordVPN, Fontanello, JSONVue, Refined GitHub)

```
Could not load content for webpack:///node_modules/matrix-react-sdk/src/audio/Playback.ts (Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)
```

### Screenshots

![Screenshot at Sep 26 13-11-09](https://github.com/vector-im/element-web/assets/12037269/eb15743d-2f79-4a5c-a296-f71d75ee9410)

![Screenshot at Sep 26 13-10-01](https://github.com/vector-im/element-web/assets/12037269/b88e99fb-69cc-427a-9c2e-6088be45a8e7)

![Screenshot at Sep 26 13-06-37](https://github.com/vector-im/element-web/assets/12037269/58cb65a7-f21d-4f56-9956-b61fc66924cc)

![Screenshot at Sep 26 13-11-57](https://github.com/vector-im/element-web/assets/12037269/6a57f7cb-350c-4624-8123-a00b0e4fd2e5)

### Outcome

The Application should not crash.

### Operating system

macOS (Ventura 13.6)

### Browser information

116.0.5845.187

### URL for webapp

https://app.element.io/

### Homeserver

gnome.element.io

### Will you send logs?

Yes

**Comment by ovflowd** [comment] 2023-09-26 11:14
There's definitely an obvious gigantic Memory Leak on Element Web

![image](https://github.com/vector-im/element-web/assets/12037269/f2a4c511-5e06-452d-aec7-106e43e67b90)

**Comment by ovflowd** [comment] 2023-09-26 11:16
I can attest the issue happens more often if I switch quickly from one chat to another.

**Comment by t3chguy** [comment] 2023-09-26 11:27
Duplicate of https://github.com/vector-im/element-web/issues/26239

**Closed by t3chguy** 2023-09-26 11:27 UTC
Labels: T-Defect
