### ISSUE TITLE
Video rooms broken

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#26490] opened 2023-11-01 16:02 UTC
### Steps to reproduce

1. Enter a video room (without any other clients joined to the video call at the time)

#### What did you expect?
Video room UI & to be able to enter the call

#### What happened instead?
Blank white (or black) chat area.

Probably regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11792 - looks like it's waiting for the video call to arrive, but it never does unless a non-element web/desktop clients starts one. We probably just need to not wait.

https://github.com/vector-im/element-web/issues/26487 may be related (the second bug in there looks like this one, not necessarily the first bug).

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-11-01 16:04
Duplicate of https://github.com/vector-im/element-web/issues/26487

**Closed by t3chguy** 2023-11-01 16:04 UTC
Labels: T-Defect, A-VoIP, Z-Labs, A-Video-Rooms
