### ISSUE TITLE
Don't prevent people with no microphone from using the voice call feature

### ISSUE THREAD

**Issue by KamilBaczkowski** [vector-im/element-web#21391] opened 2022-03-11 10:48 UTC
#### What would you like to do?
I would like to be able to use the voice call feature even if I don't have an audio input device.

#### Why would you like to do it?
My girlfriend and I have two PCs, one next to each other, so we only use one microphone. Because of that, only one of us actually has an audio input, and can't join into voice calls.
Another use case might be users that join into a voice call and listen, but write their responses on a text channel.

#### How would you like to achieve it?
Currently, Element Desktop just blocks this use case. I think that instead of blocking voice calling outright, there might be a warning message.

### Have you considered any alternatives?

I could go and add a dummy audio input device on my computer so that Element is happy, but doing this requires you to be tech-savvy.

**Comment by SimonBrandner** [comment] 2022-03-11 14:24
Related: https://github.com/vector-im/element-web/issues/18525

**Comment by KamilBaczkowski** [comment] 2022-03-11 14:40
@SimonBrandner I am willing to take some time and try to resolve it myself, I would just need some guidance regarding where to look for the appropriate code

**Comment by gsouquet** [comment] 2022-03-11 17:16
Duplicate of https://github.com/vector-im/element-web/issues/18525

**Closed by gsouquet** 2022-03-11 17:16 UTC
Labels: A-VoIP, T-Enhancement, O-Uncommon
