### ISSUE TITLE
Add flag to disable blurred avatar backdrop in the left panel

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19019] opened 2021-09-14 08:11 UTC
#### What would you like to do?
Disable the blurred avatar backdrop

#### Why would you like to do it?
See #19013 - it causes performance issues in Firefox on Fedora

#### How would you like to achieve it?
Add a setting

**Comment by t3chguy** [comment] 2021-09-14 10:45
We never had such a flag so it isn't a regression

**Comment by SimonBrandner** [comment] 2021-09-14 12:13
> We never had such a flag so it isn't a regression, it causes contrast issues so is an a11y issue though

If we were to actually do this, we might as well allow setting a custom image

**Comment by robintown** [comment] 2021-09-14 14:39
Duplicate of https://github.com/vector-im/element-web/issues/14665

**Closed by robintown** 2021-09-14 14:39 UTC
Labels: A-Performance, Z-Platform-Specific, S-Major, A-Room-List, T-Enhancement, A11y, O-Low
