### ISSUE TITLE
Trying to invite a user into a room who's already in the room now fails with "Failed to invite" error

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15711] opened 2020-11-12 14:24 UTC
From the current InviteDialog, trying to re-invite someone fails horribly if they're already in the room.

**Comment by turt2live** [comment] 2020-11-12 15:16
Duplicate of https://github.com/vector-im/element-web/issues/15051

**Closed by turt2live** 2020-11-12 15:16 UTC
Labels: bug
