### ISSUE TITLE
Password for the application

### ISSUE THREAD

**Issue by ImStandy** [vector-im/element-web#20544] opened 2022-01-13 18:53 UTC
#### What would you like to do?
Make it possible to enable a password somewhere in the settings

#### Why would you like to do it?
I wouldn't really want my friends/relatives to go into the element and read my text messages...

#### How would you like to achieve it?
Just give the possibility to set a master password on the application that will decrypt the messages.

**Comment by SimonBrandner** [comment] 2022-01-14 06:51
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/3777

**Closed by SimonBrandner** 2022-01-14 06:51 UTC
Labels: T-Enhancement
