### ISSUE TITLE
Clicking on the jump to unread message arrow results in "Tried to load a specific point in this room's timeline, but was unable to find it."

### ISSUE THREAD

**Issue by QEDeD** [vector-im/element-web#26373] opened 2023-10-16 09:53 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
In a room with several users (20-100) from several servers

2. What do you click?
The "jump to unread message"-arrow

3. More steps…
That's it, I get the error "Tried to load a specific point in this room's timeline, but was unable to find it."

#### What did you expect?
Either there should be an unread message or the arrow shouldn't show that there was an unread message.

#### What happened instead?
I got the error.

This could be related to the general issue of unread message I supposehttps://github.com/vector-im/element-web/issues/24392 

### Operating system

MacOS

### Application version

Element version: 1.11.46 Olm version: 3.2.14

### How did you install the app?

https://element.io/download

### Homeserver

non-pubic: Synapse 1.93.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-10-16 09:54
Duplicate of https://github.com/vector-im/element-web/issues/20397

**Closed by t3chguy** 2023-10-16 09:54 UTC
Labels: T-Defect
