### ISSUE TITLE
Last word of character Korean isn't sent

### ISSUE THREAD

**Issue by stvkim** [vector-im/element-web#12181] opened 2020-02-01 03:18 UTC
### Description

The last word of character Korean isn't sent
#### Riot Browser
![riot_browser](https://user-images.githubusercontent.com/16550609/73586065-c9b05000-44eb-11ea-87d2-f77f65426188.gif)
#### Riot Desktop
![riot_desktop_windows](https://user-images.githubusercontent.com/16550609/73586068-ce750400-44eb-11ea-932c-18b4aa87cd0a.gif)
Similar previous issue : #5495

### Steps to reproduce

- Change to any Korean input method
- Type a sentence and press enter without typing 'space', ' . ' kind of character which is shared with English keyboard

### Version information

- **Platform**: web and Desktop
- **Browser**: Chrome
- **OS**: Windows 10
- **Desktop Version**: 1.5.8

**Comment by Fnux** [comment] 2020-03-22 15:03
Issue confirmed on MacOS / Chrome / Riot 1.5.10.

CC @verysanghee

**Comment by Fnux** [comment] 2020-03-23 08:46
Reading on previous issues:
  * Similar issue some time ago when Riot was using SlateJS (#7665)
     - SlateJS has been replaced by in-house CIDER: 

> let the record show that we're solving this by moving away from Slate to a lightweight editor we wrote ourselves called [CIDER](https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/ciderEditor.md). Please help us test it by going to riot.im/develop and turning on the new editor in Labs in Settings, and hopefully almost all of these issues are resolved.

  * This merge request seems to apply changes on relevant parts of the matrix-react-sdk codebase: https://github.com/matrix-org/matrix-react-sdk/pull/3477/files

**Comment by Fnux** [comment] 2020-03-23 09:13
I was able to reproduce on Fedora 31 / Qutebrowser with qtwebengine backend (= chromium) but not on Firefox, using the ibus-hangul input method.

Firefox might be the workaround for the time being.

**Comment by Fnux** [comment] 2020-03-23 11:25
From https://github.com/matrix-org/matrix-react-sdk/blob/470cb2c05e0d0be3573e171fadc3e81db8344a05/src/components/views/rooms/BasicMessageComposer.js#L187 :

        // some browsers (Chrome) don't fire an input event after ending a composition,
        // so trigger a model update after the composition is done by calling the input handler.

        // however, modifying the DOM (caused by the editor model update) from the compositionend handler seems
        // to confuse the IME in Chrome, likely causing https://github.com/vector-im/riot-web/issues/10913 ,
        // so we do it async

        // however, doing this async seems to break things in Safari for some reason, so browser sniff.

**Comment by bwindels** [comment] 2020-03-23 18:58
Oooops, just saw I missed this ticket. @HeeJoong Could you please type the same sequence (under `Simple DOM contenteditable`) in https://danburzo.github.io/input-methods/index.html and post here either a screenshot of the complete list or an export of the website?

**Comment by bwindels** [comment] 2020-03-23 19:06
@Fnux thank you for your research. Feel free to post the above as well for your reproduction scenario with Qutebrowser.

**Comment by Fnux** [comment] 2020-03-24 08:07
Qutebrowser uses chromium as a backend ;-)

```
qutebrowser v1.10.1
Backend: QtWebEngine (Chromium 73.0.3683.105)
Qt: 5.13.2
```

![Screenshot from 2020-03-24 08-58-49](https://user-images.githubusercontent.com/1146924/77402016-3ccc9900-6dae-11ea-894a-70aafcb5f084.png)

As you can see above, there is no `compositionend` event when ibus is not sure of your input (a hangul character can be generated from multiple latin characters, the mapping is not prefix-free).

@bwindels thanks for your help! Tell me if there is anything I can do (you can ping me on #riot-dev).

**Comment by bwindels** [comment] 2020-03-24 09:17
Right, it was my assumption that every IME would fire a `compositionend` event after entering what is considered a meaningful unit in a given language (character or word). If that's not always clear cut (e.g. current composition makes sense on it's own but it also makes sense to append more) I guess that will need some extra work to work well. I guess pressing enter would also finish the composition, but we need to `preventDefault()` on that event so you don't add a newline when sending a message. Hmm, not sure, will have a think.

In the meantime, could you record the above log again while pressing enter after typing your sequence? Just to see if there is a `compositionend` event then.

**Comment by Fnux** [comment] 2020-03-24 15:27
Yes, there's a compositionend event in that case (at least on Linux / IBUS).

**Comment by Fnux** [comment] 2020-04-11 06:28
Might be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4339 ? I'll have to test.

**Comment by MadLittleMods** [comment] 2021-08-24 01:36
Thanks for linking the PR that might have fixed this! I'm unable to reproduce the bug now on Windows 10 and macOS 😀

이제 타이핑이 됩니다!

**Closed** 2021-08-24 01:36 UTC
Labels: T-Defect, Z-Platform-Specific, A-Composer
