### ISSUE TITLE
Mouse hover/click gets stuck flipping between states, and no click is possible

### ISSUE THREAD

**Issue by NukeManDan** [vector-im/element-web#22038] opened 2022-05-03 17:14 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

Trying to interact with a message's menue typically (reply, forward, etc.)

1. What do you click?

Somewhere on the page, sometimes hover alone triggers this.

#### What did you expect?
Mouse to work at anytime

#### What happened instead?

mouse is in "stuck" state where it's unusable. Animation from frame to frame as click/fill icon and not able to interact.

### Operating system

Ubuntu

### Application version

Element version: 1.10.11 Olm version: 3.2.8

### How did you install the app?

apt

### Will you send logs?

No

**Comment by NukeManDan** [comment] 2022-05-03 17:15
I can send logs if needed. This has occurred on two separate Ubuntu machines, and started about a month ago if I recall. 
I am also an active user of the new labs search and threads features FYI.

**Comment by t3chguy** [comment] 2022-05-03 17:16
Duplicate of https://github.com/vector-im/element-web/issues/21147

**Closed by t3chguy** 2022-05-03 17:16 UTC
Labels: T-Defect

**Comment by NukeManDan** [comment] 2022-05-03 17:20
Also: in the tray, I am and to reset the mouse to working if I do a "show/hide" cycle to bring the window back up.
