### ISSUE TITLE
Improve search experience for some languages.

### ISSUE THREAD

**Issue by YamatoRyou** [vector-im/element-web#21857] opened 2022-04-20 11:36 UTC
### Your use case

The current version cannot properly search message content based on some written languages without word segmentation, such as Chinese, Japanese. Unless:
a) there is a space to the right of the word to be searched for;
b) The word to be searched is at the beginning of the entire message (even if there is a newline, if the keyword to be searched is at the beginning of the line, it still cannot be searched).

After a simple test, it was found that this problem occurs in the Web (including the Web-based desktop client), Android, and iOS versions.

Example:
Keywords to be searched for:
![{1B4DD9BD-AE73-0B81-9468-73B3FB74CA7A}](https://user-images.githubusercontent.com/48104960/164219783-a36e7200-c9c6-4ef3-af37-c2bce9daef4a.png)

Put keywords into the search box to search only this chat room:
![{5A2C44C3-9FF3-70FC-03DC-B571158C2F9F}](https://user-images.githubusercontent.com/48104960/164219904-74b5de97-511e-43d1-b4c2-306a3bdaabe3.png)

Failed to list any content matching this keyword.
![{20294CDA-3932-77CB-5749-2240D96044E4}](https://user-images.githubusercontent.com/48104960/164220081-5bcd140d-4cf9-4b85-ba99-86fe536e3a3c.png)

### Have you considered any alternatives?

a) Export chat as HTML file, open this file in browser, press F3 and type keyword to search.
b) Use the "Inspect Elements" function to directly search for HTML elements, but this function has no effect on messages that have not yet been loaded.

### **I'm not sure if the cause of this issue is Element or Synapse, I'll ask the question here first.**

**Comment by t3chguy** [comment] 2022-04-20 11:39
Duplicate of https://github.com/vector-im/element-web/issues/16289

**Closed by t3chguy** 2022-04-20 11:39 UTC
Labels: T-Enhancement
