### ISSUE TITLE
"Copy link to thread" should give feedback that the link was copied

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21459] opened 2022-03-17 20:49 UTC
### Steps to reproduce

1. Have threads
2. Click "Copy link to thread"

#### What did you expect?

A "Copied!" or similar tooltip update. Could also be a checkmark, animation, etc. 

See "share room" dialog or various copy-able fields in settings for expected behaviour.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/158892773-cfb66f87-abf1-433a-9edd-85eb8870d4fc.png)

### Operating system

Windows 10

### Application version

Nightly (2021-03-17)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by gsouquet** [comment] 2022-03-18 10:17
Duplicate of https://github.com/vector-im/element-web/issues/19933

**Closed by gsouquet** 2022-03-18 10:17 UTC
Labels: T-Defect, A-Threads, Z-Labs
