### ISSUE TITLE
When composing multi-line messages, timeline between composer only jumps after a delay

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18022] opened 2021-07-16 14:58 UTC
(https://github.com/vector-im/element-web/issues/18018 is also related)

#### Description

When i'm composing a multi-line message, it feels very buggy, as the timeline only jumps with the top of the composer after a slight (and unpredictable) delay.

(Sometimes the timeline doesn't jump up at all if the multi-line has been removed and replaced a bunch of times, it'll "de-couple" the top of the composer to the timeline, and have subsequent messages appear without the timeline scrolling into view for them)

#### Steps to reproduce

- enter room
- quickly make a newline message with ctrl+shift's
- observe effect

#### Video

https://user-images.githubusercontent.com/22740616/125967428-4d67a888-a0ab-4f2f-9279-f4f7f2b1589e.mp4

#### Describe the fix you have in mind

Something like how discord does it, with near-instant timeline "bumping";

https://user-images.githubusercontent.com/22740616/125967736-914b6705-8fd6-4316-b00b-d36f0bbafedf.mp4

#### Version information

- **Platform**: desktop

- **OS**: Linux
- **Version**: 1.7.32

**Comment by robintown** [comment] 2021-07-16 15:25
Duplicate of https://github.com/vector-im/element-web/issues/18022

**Closed by robintown** 2021-07-16 15:25 UTC
Labels: T-Defect
