### ISSUE TITLE
It's hard to see where the multi-line composer begins and the timeline ends

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18023] opened 2021-07-16 15:04 UTC
#### Description

It's hard to see where a multi-line composer ends and the timeline begins;

<details>
<summary>Screenshots</summary>

Normal situation;

![image](https://user-images.githubusercontent.com/22740616/125968145-d8a214c8-d6f7-471d-bfd3-ed3e22173463.png)

Some letters on every new line;

![image](https://user-images.githubusercontent.com/22740616/125968179-31b134c1-053c-4a7f-bdde-f4710b91dc23.png)

Last situation, but timeline is behind composer (often the case with #18022);

![image](https://user-images.githubusercontent.com/22740616/125968258-13a0a206-c029-44bd-86b5-ca1b7aac3167.png)

Only empty newlines to exacerbate the effect;

![image](https://user-images.githubusercontent.com/22740616/125968333-08bbc950-7b62-4ab9-9580-ad52d67c0310.png)

</details>

*Note: I know a new design has been deployed on Android and iOS that "boxes" the composer, but I'm filing this issue in case this design decision isn't taken on web as well.*

#### Version information

- **Platform**: desktop

- **OS**: Linux
- **Version**: 1.7.32

**Comment by t3chguy** [comment] 2021-07-16 15:05
Duplicate of https://github.com/vector-im/element-web/issues/14735

**Closed by t3chguy** 2021-07-16 15:05 UTC
Labels: T-Defect

**Comment by robintown** [comment] 2021-07-16 15:26
Related: https://github.com/vector-im/element-web/issues/17362
