### ISSUE TITLE
Voice call picture-in-picture should remember its position after being full-screened

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#24446] opened 2023-02-06 13:29 UTC
When the voice call picture in picture window is moved to the top right or to other locations than the bottom right, it shouldn't reset when the voice call is placed in full screen again. When you look at another room, the window should not return to the bottom left.

(Reported in a [rageshake](https://github.com/matrix-org/element-web-rageshakes/issues/19948))

**Comment by SimonBrandner** [comment] 2023-02-08 07:59
Duplicate of https://github.com/vector-im/element-web/issues/18589

**Closed by SimonBrandner** 2023-02-08 07:59 UTC
Labels: T-Enhancement, Z-Labs, A-Video-Rooms
