### ISSUE TITLE
A single pre-join UISI hides the whole of history

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#24190] opened 2023-01-09 13:11 UTC
A single undecryptable event in the room history predating your join causes the whole of the history to be hidden, even if most of it would be decryptable.

(This behaviour was introduced in https://github.com/matrix-org/matrix-react-sdk/pull/3881).

**Comment by turt2live** [comment] 2023-01-09 17:57
Duplicate of https://github.com/vector-im/element-web/issues/22671

**Closed by turt2live** 2023-01-09 17:57 UTC
