### ISSUE TITLE
Jump to bottom button shows when timeline doesn't have a scrollbar

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22006] opened 2022-05-01 17:32 UTC
### Steps to reproduce

Multiple approaches:

1. Reload the app in a busy room (causes timeline to need backfilling, thus no scrollbar)

or

2. Create a new room and send a couple messages to it

#### What did you expect?

The jump to bottom button to only show up if needed

#### What happened instead?

It was present.
![image](https://user-images.githubusercontent.com/1190097/166157373-d4193b8b-9a66-47a2-8268-c1c9f7fe1aa1.png)

### Operating system

Windows 10

### Application version

Nightly (2022-05-01)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-05-01 17:34
Duplicate of https://github.com/vector-im/element-web/issues/22003

**Closed by t3chguy** 2022-05-01 17:34 UTC
Labels: T-Defect
