### ISSUE TITLE
Add option to mention roles / user groups

### ISSUE THREAD

**Issue by 33Fraise33** [vector-im/element-web#11228] opened 2019-10-25 09:20 UTC
**Is your suggestion related to a problem? Please describe.**
When running matrix to use at your company it's really hard to get the right departments to get notified about a message. You're unsure what notification triggers they might have.

**Describe the solution you'd like**
It would be very nice to have the option to mention self created roles, a little bit like the game chat client: Discord but then for the professional world. 
1. create role R&D, Sales, Accounting, IT, ....
2. Add R&D people to that role
3. mention @R&D in the general room or socials room, ....
4. they get notified

**Describe alternatives you've considered**
Other options are creating extra rooms where people of the correct department have notifications turned on for. 

**Additional context**
/

**Comment by SimonBrandner** [comment] 2021-06-22 09:59
Duplicate of https://github.com/vector-im/element-web/issues/12548

**Closed by SimonBrandner** 2021-06-22 09:59 UTC
Labels: T-Enhancement
