### ISSUE TITLE
Lightbox-like viewer for more file types

### ISSUE THREAD

**Issue by minecraftchest1** [vector-im/element-web#22591] opened 2022-06-15 14:43 UTC
#### What would you like to do?
Have Element open or preview files, rather then saving them.

#### Why would you like to do it?
Show the contents of common files such as
 * txt
 * png
 * mp3
 * mp4
 * jpg
 * etc

#### How would you like to achieve it?
Either by handling the files directly, or having the browser deal with them. Showing them in an embedded iframe or by opening in a new tab would work, although having the ability to choose one of the other of these issues would be nice.

### Have you considered any alternatives?

Saving the files to a temp dir, them manually opening them, copying the link from element somehow and manually opening in a new tab.

### Additional context

No.

**Comment by t3chguy** [comment] 2022-06-15 15:45
Duplicate of https://github.com/vector-im/element-web/issues/1856

**Closed by t3chguy** 2022-06-15 15:45 UTC
Labels: A-Timeline, A-Media, X-Needs-Product, T-Enhancement, A-Inline-Widgets, O-Occasional
