### ISSUE TITLE
"Some of your messages have not been sent" doesn't highlight the message when the unsent event doesn't have its own tile

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18403] opened 2021-08-05 08:08 UTC
#### Description
<img width="1005" alt="Screenshot 2021-08-05 at 08 58 36" src="https://user-images.githubusercontent.com/57377/128315186-1b92cc71-776d-44b3-854d-3144a0662aa0.png">

If an edit, reaction, or other event without its own tile is unsent, Element flags the problem but doesn't show which message has a related event pending.

#### Steps to reproduce

- An edit (in my case) fails to send
- Reload Element and view the channel

Acceptance criteria: highlight the pending related message somehow.

**Comment by t3chguy** [comment] 2021-08-05 08:26
Don't they get a red exclamation mark in the read receipt region?

![image](https://user-images.githubusercontent.com/2403652/128317926-158e0870-2bcc-4cc4-91e5-b2163bd554eb.png)

**Comment by novocaine** [comment] 2021-08-05 08:58
If so, there was no visible messaged marked in this way, so possible bug - I will try to repro.

**Comment by t3chguy** [comment] 2021-08-05 09:01
Seems like related to https://github.com/vector-im/element-web/issues/17078 in that case

**Comment by novocaine** [comment] 2021-08-05 11:20
I think the issue is that I have an unsent edit, which maybe we don't currently have a way of visualising.

`unsentMessages` contains an event like

```
"type": "m.room.encrypted",
    "content": {        
        "m.relates_to": {
            "rel_type": "m.replace",
            "event_id": "..."
        }
    },
```

I can't see reference to `m.replace` in the spec so can't confirm for sure.

**Comment by novocaine** [comment] 2021-08-05 11:25
ah, also, retry all doesn't actually clear it - the popup clears, but when I restart Element it comes back.

**Comment by t3chguy** [comment] 2021-08-05 11:25
Ah yes, unsent edits are only visible in the timeline if you have `Show hidden events` enabled

> I can't see reference to m.replace in the spec so can't confirm for sure.

https://github.com/matrix-org/matrix-doc/pull/2676

The edit itself is not meant to be visible in the timeline, but only affect the target event

**Comment by t3chguy** [comment] 2021-08-05 11:26
> ah, also, retry all doesn't actually clear it - the popup clears, but when I restart Element it comes back.


This sounds like a duplicate of https://github.com/vector-im/element-web/issues/17589 then

**Comment by turt2live** [comment] 2022-05-07 02:01
Duplicate of https://github.com/matrix-org/matrix-react-sdk/pull/5954

**Closed by turt2live** 2022-05-07 02:01 UTC
Labels: T-Defect, S-Minor, O-Uncommon
