### ISSUE TITLE
Files in encrypted rooms cannot be downloaded in Chromium/Chrome/Edge based browsers

### ISSUE THREAD

**Issue by MacLemon** [vector-im/element-web#16642] opened 2021-03-08 23:37 UTC
### Description

Files, including images, that get posted to E2EE rooms cannot be downloaded with the displayed Download link. This only affects Element-web and not Element-Electron/Desktop.

### Steps to reproduce

- Use any encrypted room
- post a file to the room, can be a picture as well.
- Click on the decrypt link
![image](https://user-images.githubusercontent.com/90635/110395213-0dba4080-806e-11eb-8469-14ffe8ffe76e.png)
- wait for the file to decrypt
- click the download link to actually download the file or picture.
![image](https://user-images.githubusercontent.com/90635/110395276-288cb500-806e-11eb-849a-f1b8d13204e3.png)

Nothing happens.

Expected: The file should download to the default downloads folder, or prompt the user to pick a local filesystem location to download the file to.

Logs being sent: *yes*

When clicking the download link, the browser console logs this line.
```
Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.
```
This links to the Google Chrome article [Feature: Download in Sandboxed Iframes (removed)](https://www.chromestatus.com/feature/5706745674465280).

It looks like the embedder is not setting `allow-downloads` on the iframe.
 
### Version information

- **Platform**: only web browser affected

For the web app:

- **Browser**: Chromium 88.0.4324.96, Google Chrome 89.0.4389.82, Firefox 86.0
- **OS**: macOS 10.15.7 (Catalina), Linux
- **URL**:  https://chat.fairydust.space/ running Element version: 1.7.22, olm version: 3.2.1

For the desktop app:
Does *not* affect the Desktop app! The same file can be downloaded there just fine.

Related issues:
- Open: [Files in encrypted rooms do not download in Firefox #15210](https://github.com/vector-im/element-web/issues/15210), seems to be the same or closely related issue regarding Firefox.
- Closed: [Remove "Decrypt image.png (123 KB)" text. #16087](https://github.com/vector-im/element-web/issues/16087). Seems to explain the need for the decrypt/download link.

**Comment by jryans** [comment] 2021-03-09 13:09
@MacLemon Hmm, very curious... I am not able to reproduce it here though. I tried testing in Chrome Canary 91 on macOS 10.15.7, and the encrypted file downloads automatically after clicking "decrypt".

The sandbox iframe already has `allow-download` as well, so the logged message you see doesn't really make sense to me.

Could you perhaps try logging in via https://develop.element.io and see if can reproduce it there?

**Comment by jryans** [comment] 2021-03-24 02:12
More info is needed here and we cannot reproduce at the moment. so let's close this for now.

**Closed by jryans** 2021-03-24 02:12 UTC
Labels: A-File-Download, P1, S-Major, T-Defect, X-Cannot-Reproduce, X-Needs-Info, Z-Platform-Specific
