### ISSUE TITLE
Unread marker won't disappear

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#20081] opened 2021-12-07 10:21 UTC
### Steps to reproduce

1. This normally works fine, but today I entered a room
2. Note that there are no unread messages
3. Press Esc to ensure nothing is unread

#### What did you expect?

The unread marker should disappear from this room in the roomlist - i.e. it should not be bold and there should be no dot next to it.

![image](https://user-images.githubusercontent.com/76812/145011178-fdbba838-d460-4a32-9c21-37b8cbcf9fd8.png)

#### What happened instead?

The room still appears unread.

When I press Esc, the "jump to unread" buttons (the up-arrow-with-dot and the x-in-a-circle below it) appears for 3 seconds and then disappears, but the unread marker in the room list does not change.

### Operating system

Ubuntu 21.10

### Browser information

Firefox 94.0 (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b0abbfacd48b-react-b4b81a455e14-js-39a8399977af Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by kittykat** [comment] 2021-12-14 14:57
@andybalaam Could there be a new message in a thread somewhere in the backlog?

**Comment by gsouquet** [comment] 2021-12-14 16:55
Duplicate of https://github.com/vector-im/element-web/issues/20052

**Closed by gsouquet** 2021-12-14 16:55 UTC
Labels: T-Defect, X-Regression, S-Minor, A-Room-List, A-Notifications, O-Frequent, Z-ThreadsP0
