### ISSUE TITLE
New reactions picker sometimes goes off the top of the screen

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#11175] opened 2019-10-21 10:40 UTC
I'll do a screenshot when I see it again - from memory I was reacting to a messages just about halfway up the visible timeline.

Firefox osx

**Comment by lampholder** [comment] 2019-10-21 12:57
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/1922197/67207030-aa912500-f40a-11e9-9f04-5c3a78bd9118.png">

**Comment by turt2live** [comment] 2019-10-21 15:04
largely a duplicate of https://github.com/vector-im/riot-web/issues/3429

**Comment by turt2live** [comment] 2022-05-07 01:53
I can no longer reproduce this specific case. If it's still happening, please open a new issue with fresh information.

**Closed by turt2live** 2022-05-07 01:53 UTC
Labels: T-Defect, A-Reactions
