### ISSUE TITLE
cannot unpin message/don't know how it got pinned in the first place

### ISSUE THREAD

**Issue by nrdxp** [vector-im/element-web#18683] opened 2021-08-21 22:42 UTC
### Steps to reproduce

Sorry, not sure how to reproduce as I don't know how it happened in the first place, and apologies if this is already asked/answered somewhere, but I couldn't find anything in docs or in issues.

### What happened?

I sent a message in a room yesterday, and ever since it was sent, it's been pinned for me to the bottom of the room chat. I have no idea how this happened or how to undo it. There are no clear indications of an "unpin" buttom anywhere so I would consider this a bug

### What did you expect?

To just send a normal message as usual

### Operating system

NixOS

### Application version

1.7.3.4

### How did you install the app?

from NixOS declarative configuration

### Have you submitted a rageshake?

No

**Comment by robintown** [comment] 2021-08-21 23:46
Duplicate of https://github.com/vector-im/element-web/issues/17966

**Closed by robintown** 2021-08-21 23:46 UTC
Labels: T-Defect
