### ISSUE TITLE
Surprise sunglasses (inappropriate plain-text emoji replacement)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#23411] opened 2022-10-04 09:48 UTC
### Steps to reproduce

1. Enable _Automatically replace plain text emoji_
2. Copy+paste this into the composer:
```
- [link](https://example.com/12345678)
- 
```
3. Then type some more characters after the second bullet
4. 😎

#### What did you expect?
Not 😎

#### What happened instead?
😎

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2022093001 Olm version: 3.2.12

### How did you install the app?

web then auto udpated

### Homeserver

lant.uk

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-10-04 09:50
Duplicate of https://github.com/vector-im/element-web/issues/19472

**Closed by t3chguy** 2022-10-04 09:50 UTC
Labels: T-Defect
