### ISSUE TITLE
Element Web crashes when I block Chrome from having location permissions and then try to share location

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-web#21575] opened 2022-03-28 11:15 UTC
### Steps to reproduce

1. In Element Web (version: 1.10.7) on Chrome (version 99.0.4844.83)
2. Go to a room and attempt to share location
3. Assuming location permissions have not previously been given, Chrome asks for location - select 'block'
4. Alternatively, before sharing location, click the padlock symbol on the URL bar and explicitely disable location permissions - then attempt to share location
5. Given either 3 or 4 has been done, the location share preview map will remain on the zoomed out global view and spin for a few seconds
6. Then the app crashes, and goes to an 'Aw Snap' page, showing Error Code 5.

#### What did you expect?
If location sharing is blocked by the browser, after a set period of time Element should provide an alert saying that location sharing has failed, and the function should close.

#### What happened instead?
The whole app crashed.

### Operating system

MacOS

### Browser information

Chrome Version 99.0.4844.83 

### URL for webapp

app.element.io

### Application version

Element version 1.10.7

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment] 2022-03-28 11:36
https://user-images.githubusercontent.com/769871/160389767-1c8a917f-2394-48e9-8b88-2940e7fe5725.mov

Have not been able to reproduce so far
Does this happen in private browsing too (just so that we can clear out that your extensions do not interfere with Element)

**Comment by jakewb-b** [comment] 2022-03-28 11:50
Yup, seems to happen in incognito as well.
https://user-images.githubusercontent.com/87766619/160391896-f7a0c4d2-6772-483a-bd1a-3a1281abe2f2.mov

**Comment by kerryarchibald** [comment] 2022-03-28 16:50
@jakewb-b can you please try to recreate on develop or nightly?

**Comment by jakewb-b** [comment] 2022-03-29 08:22
@kerryarchibald - I get the exact same behaviour on develop. Not able to test on nightly as we don't have location sharing there.

**Comment by t3chguy** [comment] 2023-07-25 11:23
![image](https://github.com/vector-im/element-web/assets/2403652/e3e46629-80d0-415f-9f81-7828fe360dc4)

Closing as cannot reproduce.

**Closed by t3chguy** 2023-07-25 11:23 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, O-Uncommon, Z-Labs, A-Location-Sharing
