### ISSUE TITLE
Avatars can be wrong when kicking users from a room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2011] opened 2016-08-26 10:35 UTC

**Comment by ara4n** [comment] 2016-08-26 10:35
<img width="307" alt="screen shot 2016-08-26 at 11 34 48" src="https://cloud.githubusercontent.com/assets/1294269/18002695/2e5290b0-6b81-11e6-9bcc-225b075e90a7.png">

Amandine's avatar; Katy's userid (from #marketing)

**Comment by MadLittleMods** [comment] 2021-09-02 07:05
Duplicate of https://github.com/vector-im/element-web/issues/9534

**Closed by MadLittleMods** 2021-09-02 07:05 UTC
Labels: T-Defect, P2, S-Minor, A-Timeline, A-Avatar
