### ISSUE TITLE
Disabled presence shows all users as offline

### ISSUE THREAD

**Issue by heftig** [vector-im/element-web#15485] opened 2020-10-17 23:03 UTC
Connecting with app.element.io to a Synapse homeserver that has presence disabled shows all users as offline.

It seems that Element can be configured to ignore presence for specific homeservers, but this requires a custom deployment of Element.

It would be nice if Element could ask Synapse whether presence is enabled, so Element can configure itself properly.

Or maybe the blacklist of homeservers without presence could be replaced with a whitelist of homeservers with presence.

**Comment by t3chguy** [comment] 2020-10-17 23:05
Duplicate of https://github.com/vector-im/element-web/issues/4398

Synapse does not expose that anywhere so Synapse can't ask them anything.

> whitelist of homeservers with presence.

Isn't presence enabled by default so that seems really backwards.

**Closed by t3chguy** 2020-10-17 23:05 UTC
Labels: bug
