### ISSUE TITLE
UISI in Element Internal

### ISSUE THREAD

**Issue by callahad** [vector-im/element-web#16349] opened 2021-02-02 16:49 UTC
### Description

Saw a UISI on EleWeb and Android. See attached rageshake.

Log: sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: macOS
- **URL**: develop.element.io

**Comment by turt2live** [comment] 2022-06-14 05:18
Duplicate of https://github.com/vector-im/element-web/issues/2996

**Closed by turt2live** 2022-06-14 05:18 UTC
Labels: T-Defect, S-Major, A-E2EE, Z-UISI, O-Uncommon
