### ISSUE TITLE
Unused Pulse Audio sound sources dont get removed after audio call

### ISSUE THREAD

**Issue by biberino** [vector-im/element-web#21246] opened 2022-03-01 10:50 UTC
### Steps to reproduce

1. Element Desktop, Ubuntu 18.04, Pulse Audio
2. Element plays sound from an audio call
3. A new sound source appears in Pulse Audio that plays that sound just fine
4. After the audio call ends, the sound source still stays there creating a huge list over time
![pulse-audio](https://user-images.githubusercontent.com/19487147/156154605-c424da4a-95d2-433b-9865-e29550523d56.png)
5. Sound from voice messages and notifications seem to not have that issue
6. That issue came to my attention in the last month or so, previous versions of Element didnt seem to have this problem

#### What did you expect?
The unused sound source gets deleted as soon as its no longer used.
#### What happened instead?
The sound source stays in the list forever.

### Operating system

Ubuntu 18.04

### Application version

1.10.5

### Will you send logs?

No

**Comment by YourSandwich** [comment] 2022-03-01 16:14
This is a duplicate of Issue #19294

**Comment by SimonBrandner** [comment] 2022-03-01 16:16
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19294

**Closed by SimonBrandner** 2022-03-01 16:16 UTC
Labels: T-Defect, Z-Platform-Specific, A-Electron, Z-Upstream
