### ISSUE TITLE
Inconsistency between colors for unset avatars. "Seen" avatar is not centered

### ISSUE THREAD

**Issue by Rares95** [vector-im/element-web#14862] opened 2020-08-03 08:57 UTC
![image](https://user-images.githubusercontent.com/2606875/89164922-0979f200-d578-11ea-9332-bb05075f24ce.png)

There seems to be an issue with the consistency of colors of the avatar when you have no custom avatar. 

Also the "Seen" mini avatar circled in green is not centered correctly

**Comment by t3chguy** [comment] 2020-08-03 09:18
Duplicate of https://github.com/vector-im/element-web/issues/13489

**Closed by t3chguy** 2020-08-03 09:18 UTC
Labels: bug, ui/ux
