### ISSUE TITLE
When invited to a room with encrypted messages it's necessary to switch back and forth between rooms to successfully load history

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#23429] opened 2022-10-05 15:57 UTC
### Steps to reproduce

1. Get an invite to an e2ee room (A)
2. Join the room (A)
3. (Possibly) see some messages in A
4. Click on another room (B)
5. Click back to room A
6. See more history in A
7. Click on another room (B)
8. Click back to room A
9. See more history in A

#### What did you expect?

When I join a room, I should see history, even if it takes time to load.

#### What happened instead?

I have to click around the UI to load messages.

### Will you send logs?

Yes

**Comment by uhoreg** [comment] 2022-10-05 16:12
This seems to be the same as https://github.com/vector-im/element-web/issues/16983, which was supposedly fixed.  Possibly also the same as https://github.com/vector-im/element-web/issues/22999

**Comment by benparsons** [comment] 2022-10-05 16:14
Indeed looks like the same as #22999

**Comment by t3chguy** [comment] 2022-10-06 07:48
Duplicate of #22999

**Closed by t3chguy** 2022-10-06 07:48 UTC
Labels: T-Defect
