### ISSUE TITLE
Mac Desktop - hitting the "Restart" button in the application update dialog quits instead of restarting

### ISSUE THREAD

**Issue by justdave** [vector-im/element-web#15207] opened 2020-09-16 05:25 UTC
### Description

hitting the "Restart" button in the application update dialog quits instead of restarting.

### Steps to reproduce

- automatically download an update
- get prompted to apply the update
- Click "restart"

Describe how what happens differs from what you expected.

I would expect the application to launch again after quitting.

Logs being sent: yes

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS
- **Version**: whatever was immediately prior to 1.7.7 (too late to check its version after it updated)

**Comment by t3chguy** [comment] 2020-09-16 07:59
Duplicate of https://github.com/vector-im/element-web/issues/12433

**Closed by t3chguy** 2020-09-16 07:59 UTC
Labels: bug
