### ISSUE TITLE
Current Element converts things with . in code to links; shouldn't

### ISSUE THREAD

**Issue by marcusmueller** [vector-im/element-web#21649] opened 2022-04-02 11:27 UTC
### Steps to reproduce

1. Type a message like

<pre>it's basically the same, depending on whether you run GNU Radio in an separate thread, or blockingly (`top_block.run()` vs `top_block.start()`)</pre>

2. Hit return
3. Get the code with things that really aren't URLs converted to links

#### What did you expect?

Code formatting being left alone by the URLification

#### What happened instead?

Things that really aren't URLs being converted to links, which is not helpful and makes things confusing, especially when communicating to people not familiar with a programming language or framework

![Screenshot 2022-04-02 at 13-25-13 Element Ham Radio](https://user-images.githubusercontent.com/958972/161380977-a07614ff-2b35-4a2b-8ba9-5c3efc157fe1.png)

### Operating system

Linux x86_64

### Browser information

FF 98 64bit

### URL for webapp

EMS-hosted Element 1.10.8

### Application version

Element version: 1.10.8 Olm version: 3.2.8

### Homeserver

gnuradio.ems.host

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-02 12:24
Duplicate of https://github.com/vector-im/element-web/issues/9613

**Closed by robintown** 2022-04-02 12:24 UTC
Labels: T-Defect
