### ISSUE TITLE
Element crashes randomly with "Trace/breakpoint trap (core dumped)"

### ISSUE THREAD

**Issue by monstro1** [vector-im/element-web#21379] opened 2022-03-10 15:35 UTC
### Steps to reproduce

Seems to occur at random.

### Outcome

Crashes seemingly at random. Sometimes upon startup, other times only after it's been open for a few hours.

### Operating system

Manjaro

### Application version

Element version: 1.10.4 Olm version: 3.2.8

### How did you install the app?

Using pacman

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-03-10 15:44
This is a bug with the community-maintained arch package

**Comment by t3chguy** [comment] 2022-03-10 15:45
Duplicate of https://github.com/vector-im/element-web/issues/20926

**Closed by t3chguy** 2022-03-10 15:45 UTC
Labels: T-Defect
