### ISSUE TITLE
Logging out does not close "verified device"

### ISSUE THREAD

**Issue by bkmgit** [vector-im/element-web#24290] opened 2023-01-23 05:42 UTC
### Steps to reproduce

Log in to element on a browser that does not use cookies.
Log out.
Clear browser history.
Log in to element again.
Try to view an encrypted chat.

#### What did you expect?
When using the web version and not saving cookies, when you log out, and then log back in, the device still appears as a verified device from which one can request keys. When one tries to view an encrypted chat, application requests keys from other sessions, which no longer exists.
#### What happened instead?
Expect device to be removed, since a web session is temporary.  Expect decryption should be able to happen using second password.

### Operating system

Fedora linux

### Browser information

Firefox

### URL for webapp

webchat.kde.org

### Application version

Element version: 1.11.19 Olm version: 3.2.12

### Will you send logs?

No

**Comment by weeman1337** [comment] 2023-01-23 07:57
Thanks for reporting the issue @bkmgit . Unfortunately, I cannot reproduce it. Can you update your description to contain more detailed steps? Do you enter your security key when logging in again?

**Comment by t3chguy** [comment] 2023-03-13 09:20
Closing due to lack of requested info

**Closed by t3chguy** 2023-03-13 09:20 UTC
Labels: T-Defect, X-Needs-Info

**Comment by bkmgit** [comment] 2023-03-14 06:06
Switched to using desktop app.
