### ISSUE TITLE
Thread summary only shows thread root

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20900] opened 2022-02-03 19:26 UTC
### Steps to reproduce

1. write a thread
2. add another message

#### What did you expect?
thread
#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/152414210-98bca6a4-23df-4e4e-8b5f-022c550f37b8.png)

event source: https://matrix.to/#/!CMjQWAjoxImKwLBMzX:matrix.org/$dCrUaYzX3HrrbTT3CILCbShbGtV3xKXEjG6Ydta9gsE?via=matrix.org&via=element.io&via=envs.net

regarding the message content: is it? it feels like stuff is getting moved around and breaking where it used to work due to last minute changes in thread spec that are getting implemented. i'm hitting 3 bugs every time i tried to use threads this week.

### Operating system

arch

### Application version

Element Nightly version: 2022020301 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.51

### Will you send logs?

No

**Comment by robintown** [comment] 2022-02-03 22:02
Duplicate of https://github.com/vector-im/element-web/issues/20873

**Closed by robintown** 2022-02-03 22:02 UTC
Labels: T-Defect
