### ISSUE TITLE
Develop Crashes when changing from Home to Space

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#19947] opened 2021-11-29 23:00 UTC
### Steps to reproduce

1. Switch to the home page
2. Switch to a space

#### What did you expect?
Normal change

#### What happened instead?
"Something went wrong" handler pops up for the whole page

### Operating system

Windows 11

### Browser information

Firefox 94.0.1 (64-bit)

### URL for webapp

develop.element.io

### Homeserver

nordgedanken.dev

### Will you send logs?

Yes

**Comment by robintown** [comment] 2021-11-29 23:42
Duplicate of https://github.com/vector-im/element-web/issues/19942

**Closed by robintown** 2021-11-29 23:42 UTC
Labels: T-Defect
