### ISSUE TITLE
Notification system for group calls / new group calls

### ISSUE THREAD

**Issue by PxBCPG** [vector-im/element-web#19831] opened 2021-11-21 17:45 UTC
#### What would you like to do?

- a new notification system for group calls
- a new system for group calls

#### Why would you like to do it?

- calling in a group give you less change to get the person than calling it in 1:1, because of the notification system

#### How would you like to achieve it?

- new notification system
- change completely the system of group call to a more modern one

### Additional context

The jitsi integration to element is very good, especially compared to other solutions (like mattermost or rocket.chat). But they are still not as good as the integrated ones (such as on wire, discord or other platforms).

**Comment by SimonBrandner** [comment] 2021-11-21 17:47
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/18709, https://github.com/vector-im/roadmap/issues/1, https://github.com/vector-im/roadmap/issues/28

**Closed by SimonBrandner** 2021-11-21 17:47 UTC
Labels: T-Enhancement
