### ISSUE TITLE
Reaction panel is sometimes clipped

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-web#15944] opened 2020-12-10 11:41 UTC
### Description

When using Element Desktop in a smallish window, it is possible to click a reaction button that presents a clipped Emoji picker.

### Steps to reproduce

- In my case my window is ~680px high
- Click a reaction button thats ½ to ⅔ of the way down the window
- The Emoji panel is presented missing the search field and categories

<img width="1117" alt="Screenshot 2020-12-10 at 11 31 24" src="https://user-images.githubusercontent.com/6060466/101767388-0d94be00-3adc-11eb-8461-d14ca7e8d3a5.png">

I would expect the panel to either spawn in a floating window so it didn't get clipped, or to reposition itself so that it overlapped the button, but was fully visible.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS 11.0.1
- **Version**: 1.17.15

**Comment by t3chguy** [comment] 2020-12-10 11:42
Duplicate of https://github.com/vector-im/element-web/issues/3429

**Closed by t3chguy** 2020-12-10 11:42 UTC
Labels: bug
