### ISSUE TITLE
Background highlighting when hovering over a subspace in the space home looks odd

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20710] opened 2022-01-24 13:09 UTC
### Steps to reproduce

1. Go to explore Space page for a Space with subspaces
2. Hover over a collapsed subspace

### Outcome

I feel like there should be some padding to the left and right of the `>` or something like that:

![Screenshot from 2022-01-24 12-55-22](https://user-images.githubusercontent.com/51663/150787902-5c1d6b6a-d04e-4b7f-8504-d576c8be7871.png)

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

chat.fosdem.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-01-24 13:13
Duplicate of https://github.com/vector-im/element-web/issues/17253

**Closed by t3chguy** 2022-01-24 13:13 UTC
Labels: T-Defect, A-Spaces, X-Needs-Design, A-Subspaces
