### ISSUE TITLE
Clicking "Add emoji" in thread view highlights message instead of opening the emoji selector 

### ISSUE THREAD

**Issue by aWeinzierl** [vector-im/element-web#19829] opened 2021-11-21 00:42 UTC
### Steps to reproduce

1. open a thread

In a narrow window (half screen size, for example, such that you need to click the three dots to see "Add emoji"), repeat something like the following: 
1. send an emoji
2. click on the previously sent emoji
3. click the three dots next to the message box
4. Select "add emoji"
5. notice that the emoji selection window doesn't open and the previous message is marked

It probably will not happen every time, but it is not seldom.

#### What did you expect?

After clicking "Add emoji" the emoji selector opens.

#### What happened instead?

After clicking "Add emoji" a message in the thread in highlighted.

### Operating system

Windows 10 10.0.19043

### Browser information

Edge Version 95.0.1020.53 (Official build) (64-bit)

### URL for webapp

develop.element.io

### Application version

"Element version: b2e8f212e410-react-256c468c15a3-js-af523522def0 Olm version: 3.2.3"

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment] 2021-12-15 09:16
Closing as I was not able to reproduce this problem.

Tried on Edge/Firefox/Chrome on macOs and the issue does not appear to be present anymore

**Closed by gsouquet** 2021-12-15 09:16 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, A-Composer, A-Emoji, O-Frequent, A-Threads, Z-ThreadsP0, Z-Labs
