### ISSUE TITLE
`Bug` Editing Text with ` will add \ automatically

### ISSUE THREAD

**Issue by 8227846265** [vector-im/element-web#25827] opened 2023-07-20 06:53 UTC
### Steps to reproduce

1. Send a message like this `Test
![image](https://github.com/vector-im/element-web/assets/66582769/fa5fa02a-3a10-491c-807c-618d7f3d04fd)

2. Once the message is sent. Try to edit it.

3. Upon seeing the edit option. The text will now be like this.
![image](https://github.com/vector-im/element-web/assets/66582769/fb8bcf7c-c141-4dc6-ab80-06f1816ff1dd)

4. If you try to complete it
![image](https://github.com/vector-im/element-web/assets/66582769/2e3354ab-4aa6-4df9-97c6-67576094d6af)

5. It will look like this once edited.
![image](https://github.com/vector-im/element-web/assets/66582769/fc46e5b0-bdf8-4577-853a-cd66d3a5e414)
![image](https://github.com/vector-im/element-web/assets/66582769/65d30b6f-f691-40e3-a876-eeffac961526)

#### What did you expect?
I can edit the message with a missing ` and there's no \ added

#### What happened instead?
I can edit the message with a missing ` and there's an added \

### Operating system

Windows

### Application version

Element version: 1.11.36 Olm version: 3.2.14

### How did you install the app?

https://element.io/get-started

### Will you send logs?

No

**Comment by germain-gg** [comment] 2023-07-20 07:49
Duplicate of https://github.com/vector-im/element-web/issues/22456

**Closed by germain-gg** 2023-07-20 07:49 UTC
Labels: T-Defect
