### ISSUE TITLE
Clicking Re-join on kick no longer provokes a visible spinner

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15679] opened 2020-11-09 09:43 UTC
Clicking rejoin after being kicked seems to perform no visible UI action, although I can see the join requests going through in the logs.

https://chaotic.half-shot.uk/_matrix/media/r0/download/half-shot.uk/24abf08e4249618a7b29a6674ad1a4056c7dd878

Element version: 1.7.12

**Comment by t3chguy** [comment] 2020-11-09 10:34
Duplicate of https://github.com/vector-im/element-web/issues/9850

**Closed by t3chguy** 2020-11-09 10:34 UTC
