### ISSUE TITLE
Out of Memory Error when opening specific chat

### ISSUE THREAD

**Issue by neferin12** [vector-im/element-web#18274] opened 2021-07-27 21:46 UTC
#### Description

If i try to open a specific chat (it happens only with this one chat), element gets really unresponsive and crashes after a couple of seconds with an "Out of memory" Error in the browser and in the desktop app the whole app just becomes white.

#### Steps to reproduce
I don't really know what causes this, so i can't really say how to reproduce it, but the following points describe, how this chats differs from the other chats and some facts that might be interesting:
- it is a chat that is bridged from whatsApp
- there are a lot voice messages in the recent messages (The last 100 messages contain well above an hour of audio material)
- The chat is encrypted

Describe how what happens differs from what you expected.
It crashes which it probably should not do

Logs being sent: yes

![screenshot](https://user-images.githubusercontent.com/33598039/127230355-001cedeb-df0c-4292-94df-3c794d7338b8.png)
#### Version information

- **Platform**: web (in-browser) or desktop? **Both**

For the web app:

- **Browser**: Chrome v91.0.4472.164
- **OS**: Windows
- **URL**: app.element.io as well as on a private server with element 1.7.33

For the desktop app:

- **OS**: Windows
- **Version**: 1.7.33

**Comment by t3chguy** [comment] 2021-07-27 21:49
Duplicate of https://github.com/vector-im/element-web/issues/18149 - fixed on develop and will be fixed in 1.7.34

**Closed by t3chguy** 2021-07-27 21:49 UTC
Labels: T-Defect
