### ISSUE TITLE
A number followed by a dot is unindented

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#22583] opened 2022-06-14 22:02 UTC
### Steps to reproduce

1. Send this message: `2000000. This is 2 million`

#### What did you expect?
Nothing special. Message displays like any other.

#### What happened instead?
It unindents like that:
![image](https://user-images.githubusercontent.com/152227/173696623-395c35b4-0ac1-4657-94d2-d460c63652f2.png)

### Operating system

Windows 10, Ubuntu 22.04

### Application version

Element version: 1.10.15 Olm version: 3.2.8

### Will you send logs?

No

**Comment by turt2live** [comment] 2022-06-14 22:20
Duplicate of https://github.com/vector-im/element-meta/issues/189

**Closed by turt2live** 2022-06-14 22:20 UTC
Labels: T-Defect

**Comment by thany** [comment] 2022-06-14 22:36
Well, duplicate is a bit overstating it. It describes a similar issue.

You probably forgot to notice that I'm sending a message with only ONE number. There is no numbered list that is incorrectly formatted. The problem is that it formats as a numbered list in the first place.

**Comment by turt2live** [comment] 2022-06-14 23:13
Duplicate of https://github.com/vector-im/element-web/issues/7631 then 😇
