### ISSUE TITLE
Calling doesn't in conduit homeservers

### ISSUE THREAD

**Issue by jakubcze12** [vector-im/element-web#22455] opened 2022-06-06 12:00 UTC
### Steps to reproduce

When attempting to call in a DM, by clicking the "call" or "video" button, the GUI doesn't react at all. I've set up a coturn server and directed conduit to it according to [this guide](https://gitlab.com/famedly/conduit/-/blob/next/TURN.md).

This is the output of `journalctl -u conduit` on the homeserver:

`WARN conduit::error: 404 Not Found: M_NOT_FOUND: Unknown or unimplemented route`

This is an issue only in element-web/dekstop. It doesn't happen on other clients, such as fluffychat, where the call initiates as expected. Calling **to** element web/desktop from another client does work.

#### What did you expect?

The call to initiate.

#### What happened instead?

The GUI doesn't react at all, and conduit gives an error message.

### Operating system

All supported by element web/desktop.

### Application version

1.10.13

### How did you install the app?

Through the gentoo linux repository.

### Homeserver

matrix.based-jacob.xyz

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-06-06 12:13
Duplicate of https://github.com/vector-im/element-web/issues/21680

**Closed by t3chguy** 2022-06-06 12:13 UTC
Labels: T-Defect
