### ISSUE TITLE
Invite dialog to a group chat can sometimes include duplicate user records

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22232] opened 2022-05-16 22:33 UTC
### Steps to reproduce

Unclear. See screenshot.

#### What did you expect?

1 of each user

#### What happened instead?

2 of one user (the searched one).

![image](https://user-images.githubusercontent.com/1190097/168693280-3995f4a9-8e64-460c-bc48-09350de2c82a.png)

### Will you send logs?

No

**Comment by robintown** [comment] 2022-05-17 13:50
Next time you see this, it would be good to know whether the results are duplicated by Synapse or the client

**Comment by turt2live** [comment] 2022-05-17 18:37
I believe one was from Synapse and the other from the client, from memory.

**Comment by t3chguy** [comment] 2022-05-23 19:13
Duplicate of https://github.com/vector-im/element-web/issues/11028

**Closed by t3chguy** 2022-05-23 19:13 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Minor, A-Invite, O-Uncommon
