### ISSUE TITLE
Showing Display Name Of both the users In Power Level Change Event

### ISSUE THREAD

**Issue by Sr-Preet** [vector-im/element-web#17602] opened 2021-06-09 12:40 UTC
Whenever an admin user of room changes the power level of another member the textual event shows the name of only admin user and display the matrix id of other user.
We can split the user id but even doing doesn't provide us with the display name.
This needs to be corrected.

**Comment by aaronraimist** [comment] 2021-06-15 21:38
Duplicate of https://github.com/vector-im/element-web/issues/3969

**Closed by aaronraimist** 2021-06-15 21:38 UTC
Labels: T-Enhancement
