### ISSUE TITLE
If you change the system theme from "Match system theme" to dark mode, the display will be broken

### ISSUE THREAD

**Issue by zamrumrvo** [vector-im/element-web#23504] opened 2022-10-17 04:35 UTC
### Steps to reproduce

![image](https://user-images.githubusercontent.com/105505901/196090001-7a01cd4e-61c8-4f80-b6e0-5a76a1ed9539.png)

#### What did you expect?
changed theme
#### What happened instead?
broken theme

### Operating system

windows

### Application version

maybe latest version (app has broken and I can't confirm it)

### Will you send logs?

No

**Comment by dbkr** [comment] 2022-10-17 13:31
I can't reproduce this bug, although the repro steps are quite vague. Also I'm trying on the web (I don't have the windows version to hand to try). I'm not sure I'm looking at in the screenshot - is that really how it breaks?

**Comment by turt2live** [comment] 2023-01-10 00:36
I cannot reproduce this on Windows Desktop (Nightly) - closing as fixed.

If this is untrue, please open a new issue with fresh reproduction steps and more detail.

**Closed by turt2live** 2023-01-10 00:36 UTC
Labels: T-Defect, X-Needs-Info, A-Themes-Official
