### ISSUE TITLE
Element Desktop for Linux keeps logging the session out once a few days

### ISSUE THREAD

**Issue by masscream** [vector-im/element-web#18082] opened 2021-07-20 11:11 UTC
![Screenshot_2021-07-20_12-53-01](https://user-images.githubusercontent.com/11753248/126313111-ad9f4679-e70a-4ada-8346-d71ca8974a6a.png)

#### Description

Once upon a time, the Element session gets logged out. It makes things complicated with ppl who are very basic users (don't know how to set Element up, forget often their passwords, and let their younger relatives fix it / log in again and again.) Therefore there comes a question, why it throws a session out ? I thought that updates could have been the cause but today, my Element logged me out with the message above for no reason.

#### Steps to reproduce

Install Element for Linux, use it every day, one day it will throw you out.

I would expect not to throw me out at all, until I delete the session folder manually or logout myself.

[issue.txt](https://github.com/vector-im/element-web/files/6847734/issue.txt)
[log-0.log](https://github.com/vector-im/element-web/files/6847735/log-0.log)

#### Version information

element-desktop/unknown,now 1.7.32 amd64

For the desktop app:

- **OS**: Debian Linux Testing (happens also on Buster version)
- **Version**: 11, 10

**Comment by kojid0** [comment] 2021-07-23 07:37
Facing the same issue but I'm on version 1.7.33, Ubuntu 20.04 (ZorinOS)

**Comment by novocaine** [comment] 2021-11-19 03:48
Is this still happening?

Can you provide more details when it usually happens? Is it after some idle period, or when you're chatting? Does it happen after updates to Element or to your system?

**Comment by kojid0** [comment] 2021-11-19 09:04
Not to me anymore. Will leave a comment here if I encounter it again.

**Comment by masscream** [comment] 2022-03-26 19:08
Still occurs for me on one of the PCs I'm in charge of. Debian 11 Bullseye, Xfce. I'm sending logs from that Element instance with the reference to this issue.

**Comment by petitminion** [comment] 2022-04-24 18:52
it happens to me on 
kubuntu 21.10 
Element version: 1.10.10
Olm version: 3.2.8

It happens regulary, but can say what triggers it :s

**Comment by turt2live** [comment] 2022-06-14 05:34
Duplicate of https://github.com/vector-im/element-web/issues/22563

**Closed by turt2live** 2022-06-14 05:34 UTC
Labels: T-Defect, X-Needs-Info, Z-Platform-Specific, X-Regression, S-Major, A-Electron, A-Logout, O-Uncommon

**Comment by olfMombach** [comment] 2026-08-19 12:11
> Duplicate of https://github.com/vector-im/element-desktop/issues/819

How is that issue related in any way?

**Comment by olfMombach** [comment] 2026-08-19 12:13
And I also have this issue on Linux Mint 22.1, where it just logs itself out. I have confirmed that this is **not** related to updates.
