### ISSUE TITLE
Read receipts fly from the sky now

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17561] opened 2021-06-04 21:03 UTC
even if the message they are falling from is immediately prior

**Comment by robintown** [comment] 2021-06-04 21:55
Duplicate of #17557

**Comment by t3chguy** [comment] 2021-06-04 21:55
#17557 says read marker, that's the green horizontal line

**Comment by DantrazTrev** [comment] 2021-06-06 19:25
The issue traces back to here matrix-org/matrix-react-sdk/pull/6079. It kinda works when the div wrapper added over is removed in `EventTile`'s  `getReadAvatar`

```
 return (
            <div className="mx_EventTile_msgOption">
                <span className="mx_EventTile_readAvatars">
                    { remText }
                    { avatars }
                </span>
            </div>
        )
```
Although changing the `leftOffset` 

Not sure about the entire chain that causes it but probably has something to do with `ReadReciptMarker`'s `animateMaker` getting the correct position of `oldInfo` or `newElement`. This is much more evident from the `startOffset` in `animateMaker` which is a bit different from the normal case of the avatar dropping

**Closed** 2021-06-09 15:16 UTC
Labels: A-Read-Receipts, P1, S-Major, T-Defect, X-Regression, X-Release-Blocker
