### ISSUE TITLE
[Spaces] Add Mark as read to spaces context menu in the spaces panel

### ISSUE THREAD

**Issue by licentiapoetica** [vector-im/element-web#20502] opened 2022-01-12 09:38 UTC
#### What would you like to do?
Marking all channels with unread messages as read via shortcut so I don't have to click manually on all of them

#### Why would you like to do it?
Lazy

#### How would you like to achieve it?
by gods grace

### Have you considered any alternatives?

Clicking every room by hand

**Comment by t3chguy** [comment] 2022-01-12 09:45
Duplicate of https://github.com/vector-im/element-web/issues/8541

**Closed by t3chguy** 2022-01-12 09:45 UTC
Labels: T-Enhancement
