### ISSUE TITLE
Regex style replacement (`s/foo/bar/`)

### ISSUE THREAD

**Issue by haasn** [vector-im/element-web#17427] opened 2021-05-21 04:39 UTC
#### Describe the feature you'd like.
A lot of other popular IM clients for XMPP, Discord etc. support the ability to regex-replace text, in the manner of `s/pattern/replacement/` (sometimes with the last `/` being optional).

I think it would be good, and probably relatively easy, so support it in Element as well. Open questions include how far back you want to apply the regex match, i.e. should it only be allowed to replace the previous message, or should it also extend back to the past few lines in case the first line doesn't match?

**Comment by t3chguy** [comment] 2021-05-21 07:05
Duplicate of #10647

**Closed** 2021-05-21 07:05 UTC
Labels: T-Enhancement
