### ISSUE TITLE
SEGV on macos

### ISSUE THREAD

**Issue by dominikwerder** [vector-im/element-web#9871] opened 2019-05-28 14:10 UTC
```txt
Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   com.github.Electron.framework 	0x000000010c6ebad0 0x10aa03000 + 30313168
1   com.github.Electron.framework 	0x000000010c6ebc8e 0x10aa03000 + 30313614
2   com.github.Electron.framework 	0x000000010c7b500b 0x10aa03000 + 31137803
3   com.github.Electron.framework 	0x000000010c7cf45f 0x10aa03000 + 31245407
4   com.github.Electron.framework 	0x000000010c7cf918 0x10aa03000 + 31246616
5   com.github.Electron.framework 	0x000000010c873eba 0x10aa03000 + 31919802
6   com.github.Electron.framework 	0x000000010c87717a 0x10aa03000 + 31932794
7   com.github.Electron.framework 	0x000000010c8737df 0x10aa03000 + 31918047
8   com.apple.CoreFoundation      	0x00007fff2f5188f1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
9   com.apple.CoreFoundation      	0x00007fff2f5d230c __CFRunLoopDoSource0 + 108
10  com.apple.CoreFoundation      	0x00007fff2f4fb350 __CFRunLoopDoSources0 + 208
11  com.apple.CoreFoundation      	0x00007fff2f4fa7cd __CFRunLoopRun + 1293
12  com.apple.CoreFoundation      	0x00007fff2f4fa033 CFRunLoopRunSpecific + 483
13  com.apple.HIToolbox           	0x00007fff2e7e4d96 RunCurrentEventLoopInMode + 286
14  com.apple.HIToolbox           	0x00007fff2e7e4b06 ReceiveNextEventCommon + 613
15  com.apple.HIToolbox           	0x00007fff2e7e4884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
16  com.apple.AppKit              	0x00007fff2ca94a73 _DPSNextEvent + 2085
17  com.apple.AppKit              	0x00007fff2d22ae34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
18  com.apple.AppKit              	0x00007fff2ca89885 -[NSApplication run] + 764
19  com.github.Electron.framework 	0x000000010c87461c 0x10aa03000 + 31921692
20  com.github.Electron.framework 	0x000000010c8732fe 0x10aa03000 + 31916798
21  com.github.Electron.framework 	0x000000010c7f12c5 0x10aa03000 + 31384261
22  com.github.Electron.framework 	0x000000010b412e83 0x10aa03000 + 10550915
23  com.github.Electron.framework 	0x000000010b412c70 0x10aa03000 + 10550384
24  com.github.Electron.framework 	0x000000010b4151a2 0x10aa03000 + 10559906
25  com.github.Electron.framework 	0x000000010b40f0c8 0x10aa03000 + 10535112
26  com.github.Electron.framework 	0x000000010c6677d8 0x10aa03000 + 29771736
27  com.github.Electron.framework 	0x000000010da5c27d 0x10aa03000 + 50696829
28  com.github.Electron.framework 	0x000000010c666884 0x10aa03000 + 29767812
29  com.github.Electron.framework 	0x000000010aa052d4 AtomMain + 84
30  im.riot.app                   	0x000000010652af10 0x10652a000 + 3856
31  libdyld.dylib                 	0x00007fff5742c015 start + 1
```

### Description

On closing Riot, got already the 3rd time a "app closed unexpectedly". This time I looked into the details and saw that it's a segmentation violation.

### Steps to reproduce

Happens only from time to time on Cmd-Q.

Have the feeling that it happens more often if app was in fullscreen.

### Version information

Desktop macos Riot 1.1.2
macos 10.13.6

**Comment by jryans** [comment] 2019-05-29 09:59
I'm not sure there's much we can do here, unfortunately... Hopefully, whatever the issue is, it's fixed in a newer Electron version.

**Comment by aaronraimist** [comment] 2021-05-05 02:58
@dominikwerder have you experienced this on  any recent version of Element?

**Comment by dominikwerder** [comment] 2021-05-06 07:58
I no longer have the apple hardware since quite some time, sorry.

**Comment by SimonBrandner** [comment] 2021-05-06 12:19
In that case, I think we can close this. If you or anyone else happen to stumble upon this again _feel free_ to reopen or ping me!

**Closed by SimonBrandner** 2021-05-06 12:19 UTC
Labels: A-Electron, T-Defect, X-Needs-Info, Z-Upstream
