### ISSUE TITLE
changing account disables search on desktop client

### ISSUE THREAD

**Issue by fabianunterstell** [vector-im/element-web#17045] opened 2021-04-22 15:33 UTC
![account_switch_bug](https://user-images.githubusercontent.com/2976347/115741542-25385900-a390-11eb-93c8-f8b618dc3174.PNG)

### Description

Switching to another user on desktop client disables the search with error `Use the Desktop app to search encrypted messages`.

### Steps to reproduce

1. Sign out
2. Sign in with different account
3. Use the search in encrypted room
4. Receive incorrect error message: `Use the Desktop app to search encrypted messages`

This can be fixed by removing the `EventStore` folder. This reenables the search for the newly logged in account.

### Version information

- **Platform**: web (in-browser) or desktop?
Windows 10 desktop

- For the desktop app:
Element version: 1.7.25
olm version: 3.2.1

**Comment by t3chguy** [comment] 2021-04-22 15:37
Duplicate of https://github.com/vector-im/element-web/issues/16568

**Closed by t3chguy** 2021-04-22 15:37 UTC
Labels: T-Defect
