### ISSUE TITLE
Homeserver URL does not appear to be a valid Matrix homeserver

### ISSUE THREAD

**Issue by mgkmgk81** [vector-im/element-web#23735] opened 2022-11-09 05:48 UTC
### Steps to reproduce

Hello, I set up a server on Debian\nginx in the local network, if I go through the web interface (https://matrix.test.rus/), then I get to the server without problems, if the desktop client Element or some other is used, I get an error: 
"URL does not appear to be a valid Matrix homeserver"
What could be the problem ?
My Nginx config:

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

      
    listen 8448 ssl http2 default_server;
    listen [::]:8448 ssl http2 default_server;

    server_name matrix.test.rus;

    ssl_certificate /etc/ssl/private/matrix.crt;
    ssl_certificate_key /etc/ssl/private/matrix.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /var/www/element;
    index index.html;


    location ~* ^(\/_matrix|\/_synapse\/client) {
        proxy_pass http://127.0.0.1:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
    }

    location /.well-known/matrix/client {
        default_type application/json;
        add_header Access-Control-Allow-Origin *;

        return 200 '{ "m.homeserver": { "base_url": "https://matrix.test.rus:443" } }';
    }


   location /.well-known/matrix/server {
		default_type application/json;
                add_header Access-Control-Allow-Origin *;
		return 200 '{"m.server": "matrix.test.rus:443"}';
   
    }
}
```

![Screenshot_72](https://user-images.githubusercontent.com/103593723/200580911-19fc65a5-e85a-49a2-a994-b87317e1d5f7.jpg)

### Operating system

Debian 11

### Homeserver

local matrix.test.rus

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-11-09 08:58
![image](https://user-images.githubusercontent.com/2403652/200785271-093d9aab-62cf-4ded-8f6c-47980e7c91d1.png)

Your `.well-known/matrix/client` file specifies https://matrix.test.rus:443 but then a request to https://matrix.test.rus:443/_matrix/client/versions fails with `curl: (6) Could not resolve host: matrix.test.rus`

This looks like a networking issue

**Comment by mgkmgk81** [comment] 2022-11-09 09:43
My server don't look outside in web, only inside the local network \ domain, it cannot resolve by matrix.org, or is it a prerequisite for connecting the Desktop client?

**Comment by t3chguy** [comment] 2022-11-09 09:43
No it isn't. Check console to see the logs of the failure. The network tab especially.

**Comment by mgkmgk81** [comment] 2022-11-09 09:49
What do you mean by console?  matrix.synapse and nginx logs - no errors

**Comment by mgkmgk81** [comment] 2022-11-09 09:59
Found this:
2022-11-09T05:24:03.516Z E Invalid /versions response
2022-11-09T05:24:03.516Z E Error processing homeserver config: {"state":"FAIL_ERROR","error":"Homeserver URL does not appear to be a valid Matrix homeserver","base_url":"https://matrix.test.rus:8448"}
2022-11-09T05:24:03.517Z E Homeserver URL does not appear to be a valid Matrix homeserver
Error: Homeserver URL does not appear to be a valid Matrix homeserver
    at v (vector://vector/webapp/bundles/d390d45e962452a8336b/vendors~init.js:2:112631)
    at B.buildValidatedConfigFromDiscovery (vector://vector/webapp/bundles/d390d45e962452a8336b/vendors~element-web-app.js:2:1877103)
    at B.validateServerConfigWithStaticUrls (vector://vector/webapp/bundles/d390d45e962452a8336b/vendors~element-web-app.js:2:1875910)
    at async m.deriveData (vector://vector/webapp/bundles/d390d45e962452a8336b/vendors~element-web-app.js:2:2109459)
    at async m.validate (vector://vector/webapp/bundles/d390d45e962452a8336b/vendors~init.js:2:669011)
    at async _.validate (vector://vector/webapp/bundles/d390d45e962452a8336b/vendors~init.js:2:172072)
    at async vector://vector/webapp/bundles/d390d45e962452a8336b/vendors~element-web-app.js:2:2110217

**Comment by t3chguy** [comment] 2022-11-09 10:03
> The network tab especially.

**Comment by mgkmgk81** [comment] 2022-11-09 10:22
> > Особенно вкладка "Сеть".

Tab in Element desktop, or where?

**Comment by t3chguy** [comment] 2022-11-09 10:48
![image](https://user-images.githubusercontent.com/2403652/200810642-319ea772-16f1-4607-9622-61efbe97fba1.png)

Top left of the Electron console

**Comment by mgkmgk81** [comment] 2022-11-09 12:14
> ![image](https://user-images.githubusercontent.com/2403652/200810642-319ea772-16f1-4607-9622-61efbe97fba1.png)
> 
> Top left of the Electron console

Perhaps I didn't ask the right question. I use Element for Windows, there are no settings before connecting, after connecting to matrix.org, I can go into the settings, but there is nothing about the network, only download the logs that I have given above.
![Screenshot_73](https://user-images.githubusercontent.com/103593723/200827580-5ff8b2b5-6d1b-4671-ab3e-aaffec23bd7b.jpg)
![Uploading Screenshot_74.jpg…]()

**Comment by t3chguy** [comment] 2022-11-09 14:38
https://www.tutorialspoint.com/electron/electron_debugging.htm#:~:text=To%20open%20DevTools%2C%20use%20the,how%20to%20use%20devtools%20here.

**Comment by mgkmgk81** [comment] 2022-11-10 07:27
> https://www.tutorialspoint.com/electron/electron_debugging.htm#:~:text=To%20open%20DevTools%2C%20use%20the,how%20to%20use%20devtools%20here.

Why i need use "Electron", what does this have to do with the case?
My server is working fine, problem only in desctop Element clint via SSL https, 8008 is working
![Screenshot_75](https://user-images.githubusercontent.com/103593723/201026776-7b753b87-7682-48f2-a8b8-ea000e6b282a.jpg)

**Comment by t3chguy** [comment] 2022-11-10 09:23
Element Desktop is built on Electron.
You say it works on 8008, is your SSL certificate self signed or?

**Comment by mgkmgk81** [comment] 2022-11-10 09:59
> 
Yes, self signed, via openssl, not certbot.

**Comment by t3chguy** [comment] 2022-11-10 10:02
Duplicate of https://github.com/vector-im/element-web/issues/3003

**Closed by t3chguy** 2022-11-10 10:02 UTC
Labels: T-Defect, X-Needs-Info
