### ISSUE TITLE
Query web app search functionality status

### ISSUE THREAD

**Issue by ldexterldesign** [vector-im/element-web#26620] opened 2023-11-21 18:28 UTC
### Your use case

👋

Thanks for software

#### What would you like to do?

Search in web app, like desktop app

#### Why would you like to do it?

So I can find content

#### How would you like to achieve it?

Using the search button/feature

It's my understanding that a contributing factor that search in web app isn't possible is because encryption is set by default?: if yes then my vote goes to disabling encryption by default and adding a prompt to enable encryption instead. I would bet most users are going to care more about search (i.e. an expected simple feature) than encryption (i.e. arguably a complex advanced feature) so currently the way things are UX is hurt; and it's hurting adoption from people I recommend Element to.

Aside - because search *still* doesn't exist in the web app - I would like to know why these related issues aren't *still* open?:
https://github.com/vector-im/element-web/issues/2548
https://github.com/vector-im/element-web/issues/13298
https://github.com/vector-im/element-web/issues/13539

Hope this is useful and to hear back

Cheers

### Have you considered any alternatives?

Ya, I - and others - now have to resort to using the desktop app

**Comment by t3chguy** [comment] 2023-11-21 20:47
Duplicate of https://github.com/vector-im/element-web/issues/16483

**Closed by t3chguy** 2023-11-21 20:47 UTC
Labels: T-Enhancement
