### ISSUE TITLE
Thread content is not persistent in the right panel when navigating to other rooms

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20100] opened 2021-12-08 10:32 UTC
### Steps to reproduce

1. Reply to a message in a thread
2. Navigate to another room while the thread is still open in the right panel

#### What did you expect?
Thread panel persists and content does not change (can see root message and own message)

#### What happened instead?
I can see the correct thread content only in the room where the thread is located. When viewing another room, I can only see the root message.

https://user-images.githubusercontent.com/51663/145192961-12857cf3-228a-476d-900c-e360a3fa02b2.mp4

### URL for webapp

develop.element.io

### Application version

Element version: b0abbfacd48b-react-697b5d28b3bf-js-72bc13eb395e Olm version: 3.2.3

### Will you send logs?

No

**Comment by daniellekirkwood** [comment] 2021-12-13 17:36
Right now Threads don't transcend Rooms. 
When a users moves Room the Thread panel should clear. Threads are Room specific (currently).

I'm marking this as enhancement (for after first launch) as this is something that would be great to add to the Threads experience

**Comment by gsouquet** [comment] 2021-12-14 07:49
Duplicate of https://github.com/vector-im/element-web/issues/19686

**Closed by gsouquet** 2021-12-14 07:49 UTC
Labels: S-Major, T-Enhancement, O-Occasional, A-Threads, Z-Labs
