### ISSUE TITLE
Message not going through from staging to develop

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#25801] opened 2023-07-14 09:24 UTC
### Steps to reproduce

1. Two accounts on matrix.org - create the room from develop, accept invite from staging
2. Have some weirdness around room encryption and naming
3. Send message from staging to develop

#### What did you expect?
Message arrives on develop

#### What happened instead?
Nothing on develop
Edit: still nothing a few hours later

Messages from develop do go through to staging

![Screenshot from 2023-07-14 10-17-42](https://github.com/vector-im/element-web/assets/51663/f433f044-ec36-4a59-82a0-15f7daa9f749)

### Browser information

Chromium 114.0.5735.198 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io, staging.element.io

### Application version
Element version: b89b000f05a1-react-77c3a89cbc14-js-0b193f466562
Olm version: 3.2.14

Element version: 1.11.36-rc.1
Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-07-24 16:20
@kittykat are you still seeing this because it sounds like a release blocker

**Comment by t3chguy** [comment] 2023-07-25 08:06
Going ahead with the RC due to unable to reproduce, will continue to monitor

**Comment by weeman1337** [comment] 2023-07-25 09:08
Can't reproduce either :shrug:

**Comment by kittykat** [comment] 2023-07-26 08:44
@t3chguy Yes, I can still not see messages in one direction as of today in that DM

**Comment by kittykat** [comment] 2023-07-26 12:04
Also cannot see messages from that user in a group chat. Between Android, iOS and web, I'm seeing three different things in the timeline when that user is concerned. None of them correspond to reality!

**Comment by t3chguy** [comment] 2023-07-26 12:11
This turned out to be that agelessant was marked as ignored so the server was omitting their events

**Closed by t3chguy** 2023-07-26 12:11 UTC
Labels: T-Defect, X-Cannot-Reproduce, X-Release-Blocker
