### ISSUE TITLE
Missing session data on startup

### ISSUE THREAD

**Issue by Xiretza** [vector-im/element-web#25168] opened 2023-04-20 18:05 UTC
### Steps to reproduce

1. electron renderer died somehow (element window turned white, but tray context menu to show/hide/quit still worked)
2. restarted element, got "Missing session data"

I'm not super low on disk space, and either way I don't think electron should discard data like that.

#### What did you expect?

Session data not to go missing

#### What happened instead?

Session data went missing

### Operating system

Arch Linux

### Application version

element-desktop 1.11.26-1

### How did you install the app?

pacman

### Homeserver

xiretza.xyz

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-04-21 08:23
Duplicate of https://github.com/vector-im/element-desktop/issues/692

**Closed by t3chguy** 2023-04-21 08:23 UTC
Labels: T-Defect
