### ISSUE TITLE
Soft-crash on joining room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#19114] opened 2021-09-21 14:06 UTC
### Steps to reproduce

typed /join #libocon:libera.chat in nightly

### What happened?

got a soft crash

### Operating system

macos

### Application version

nightly

### Homeserver

matrix.org

### Have you submitted a rageshake?

Yes

**Comment by SimonBrandner** [comment] 2021-09-21 14:09
Duplicate of https://github.com/vector-im/element-web/issues/19101

**Closed by SimonBrandner** 2021-09-21 14:09 UTC
Labels: T-Defect
