### ISSUE TITLE
Getting notifications on a room when i'm not tagged or quoted

### ISSUE THREAD

**Issue by r3pek** [vector-im/element-web#19545] opened 2021-10-28 13:44 UTC
### Steps to reproduce

I have a couple of rooms from the mautrix whatsapp bridge, which means all users are on my domain. whenever someone quotes a message from the chat (and i'm not quoted nor tagged), a notification is triggered and the text appears in red as if i'm tagged. What I **think** the problem is, is that the domain part of my server (r3pek.org) matches my username (r3pek), and since all users have the id `whatsapp_123123123132123:r3pek.org` it ends up matching the on domain part and triggers the notification. (i might be wrong, this is just a guess)

### Outcome

No notification when i'm not tagged or quoted.

### Operating system

Fedora Linux

### Application version

Element version: 1.9.3 Olm version: 3.2.3

### How did you install the app?

Installed from Fedora COPR

### Homeserver

r3pek.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-05-10 20:36
Duplicate of https://github.com/vector-im/element-web/issues/[8431](https://github.com/vector-im/element-web/issues/8431)

**Closed by t3chguy** 2022-05-10 20:36 UTC
Labels: T-Defect, S-Minor, A-Notifications, O-Uncommon
