### ISSUE TITLE
When beginning to type (and the window is focused, but not the input bar), the input bar should be focused

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19696] opened 2021-11-11 10:50 UTC
#### What would you like to do?

When i have the input bar not focused, and i begin to type, it begins to highlight random parts of the screen with orange bars.

Coming from discord and telegram, this is disorienting, in those clients, the input bar gets focused on the first key-press, with everything you "just type" being put into there.

So, i'd like for that same behaviour to be in element.

#### Why would you like to do it?

Muscle-memory, but also because it makes typing into a room much more comfortable.

#### How would you like to achieve it?

By making element focus on the input bar (if none others are focused) and put all of my input in there.

**Comment by SimonBrandner** [comment] 2021-11-11 11:52
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19479

**Closed by SimonBrandner** 2021-11-11 11:52 UTC
Labels: T-Enhancement, A-Composer, O-Frequent
