### ISSUE TITLE
Can't share screen in desktop app

### ISSUE THREAD

**Issue by cybertschunk** [vector-im/element-web#17023] opened 2021-04-20 18:30 UTC
### Description

I can not share my screen in a video call. The application can't find any application windows or screens.

### Steps to reproduce

- Open a video call with someone else
- Click on the screen share button

Describe how what happens differs from what you expected.

I can't select an application window to share. The loading screen never finishes.

Logs being sent: yes

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Windows 10
- **Version**: 1.7.25

**Comment by SimonBrandner** [comment] 2021-04-20 18:31
Duplicate of [#4880](https://github.com/vector-im/element-web/issues/4880)

**Closed by SimonBrandner** 2021-04-20 18:31 UTC
Labels: T-Defect
