### ISSUE TITLE
encrypted messages from someone in a group chat don't want to decrypt

### ISSUE THREAD

**Issue by acoolstraw** [vector-im/element-web#25233] opened 2023-04-28 14:13 UTC
### Steps to reproduce

1. use it

#### What did you expect?
the messages to decrypt
#### What happened instead?
they didn't

![image](https://user-images.githubusercontent.com/45886986/235171257-71475bbe-0f63-4f46-9a1c-693a5824235b.png)
![image](https://user-images.githubusercontent.com/45886986/235171287-55349915-d827-4895-967c-f5a682533c08.png)

i really don't get how something like this can happen you guys have millions of dollars in funding get good or something. every time i try to use matrix it ends up fucking with my messages for no reason with no trigger

### Operating system

a web browser

### Browser information

chromium latest

### URL for webapp

chat.tchncs.de

### Application version

dunno

### Homeserver

tchncs.de

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-04-28 14:21
Duplicate of https://github.com/vector-im/element-meta/issues/245

**Closed by t3chguy** 2023-04-28 14:21 UTC
Labels: T-Defect

**Comment by acoolstraw** [comment] 2023-04-28 14:33
faggot, kill yourself
