### ISSUE TITLE
Mark all as read (Spaces)

### ISSUE THREAD

**Issue by Monstanner** [vector-im/element-web#17796] opened 2021-06-27 07:24 UTC
#### Is your suggestion related to a problem? Please describe.

If you have several rooms in a space, an unread indicator is displayed for the Space. Then you click on the Space and then you have to go to all the rooms that contain new messages. 

#### Describe the solution you'd like.

Instead of going through each room individually, there should be a Mark all as read button when you right click on a Space. Like in the Picture.

#### Additional context

![request](https://user-images.githubusercontent.com/45621250/123536205-2e93c800-d729-11eb-832f-476f8d62770c.jpg)

**Comment by t3chguy** [comment] 2021-06-28 07:23
Duplicate of https://github.com/vector-im/element-web/issues/8541

**Closed by t3chguy** 2021-06-28 07:23 UTC
Labels: A-Notifications, A-Spaces, T-Enhancement
