### ISSUE TITLE
Visual glitch on the "Invite to this community" button

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#15908] opened 2020-12-07 13:52 UTC
![image](https://user-images.githubusercontent.com/5547783/101358899-6d4c5880-3893-11eb-8ce9-f0c08e2d085f.png)

Seen on develop.element.io

**Comment by t3chguy** [comment] 2020-12-07 13:57
Duplicate of https://github.com/vector-im/element-web/issues/15809

**Closed by t3chguy** 2020-12-07 13:57 UTC
