### ISSUE TITLE
Room avatar change alignment is weird

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#26404] opened 2023-10-19 20:13 UTC
### Steps to reproduce

1. Observe someone else change (or set) the room avatar

#### What did you expect?

Aligned elements.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/29262abb-d923-49e7-a88a-7c5ad900d052)

The user's avatar is too high, and the room's avatar is too low.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023101901 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-10-20 07:49
Duplicate of https://github.com/vector-im/element-web/issues/22744

**Closed by t3chguy** 2023-10-20 07:49 UTC
Labels: T-Defect
