### ISSUE TITLE
Stop creating a desktop icon for Element after updates

### ISSUE THREAD

**Issue by AlexAltea** [vector-im/element-web#21959] opened 2022-04-27 17:10 UTC
### Your use case

Every one or two weeks a desktop icon/shortcut for Element appears, presumably after an auto-update, that I have to remove.

It is getting seriously annoying.

**Comment by t3chguy** [comment] 2022-04-27 17:14
Duplicate of https://github.com/vector-im/element-web/issues/9210

**Closed by t3chguy** 2022-04-27 17:14 UTC
Labels: T-Enhancement
