### ISSUE TITLE
Stuck unread indicators

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20971] opened 2022-02-07 19:42 UTC
### Steps to reproduce

This behavior started at a seemingly random time, but is now happening to me consistently:

1. Receive a message
2. View the message to mark it as read

#### What did you expect?

The room should not have any notification indicators on it since I have read all the messages.

#### What happened instead?

The room still has an unread dot that won't go away:

![Screenshot 2022-02-07 at 14-39-14 Element sandbox](https://user-images.githubusercontent.com/48614497/152859598-5e4565b1-ca62-435f-9ec3-6b7b0c370bbd.png)

Reloading Element causes it to disappear.

### Operating system

NixOS unstable

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 64242a004eb7-react-8e72118b5d4a-js-07171a95c4f0 Olm version: 3.2.8

### Homeserver

Synapse 1.51.0

### Will you send logs?

No

**Comment by tcitworld** [comment] 2022-02-08 08:15
I have the same issue with 64242a004eb7-react-8e72118b5d4a-js-07171a95c4f0

**Comment by andybalaam** [comment] 2022-02-08 09:48
I just hit this problem and rageshaked.

**Comment by babolivier** [comment] 2022-02-08 10:03
Same, I've been observing this since yesterday evening. Only sending an event or refreshing the tab marks the room as unread.

**Comment by t3chguy** [comment] 2022-02-08 11:19
Possible regression caused by https://github.com/matrix-org/matrix-js-sdk/commit/07171a95c4f0

**Comment by dbkr** [comment] 2022-02-08 12:20
Other reports of this coming in (including me) so marking as blocker

**Closed** 2022-02-08 12:32 UTC
Labels: T-Defect, X-Regression, S-Major, X-Release-Blocker, A-Notifications, O-Frequent

**Comment by dkasak** [comment] 2022-02-16 13:08
I recently started having the opposite issue, where the unread messages indicator is never shown despite there being new room messages. Any chance that's related to this bug or should I submit a new issue?

**Comment by robintown** [comment] 2022-02-16 13:43
@dkasak That sounds like https://github.com/vector-im/element-web/issues/20859 which was fixed recently. What version are you using?

**Comment by dkasak** [comment] 2022-02-16 14:10
Could be, I'm still on v1.10.1. Though the fix for that issue talks about mentions explicitly, and my issue is not related to mentions specifically.

**Comment by Weuxel** [comment] 2024-03-01 08:41
Still in 1.11.58.
