### ISSUE TITLE
Stuck notification in relation with threads

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21823] opened 2022-04-16 11:53 UTC
### Steps to reproduce

1. Enabled threads beta
2. start thread on 2 messages
3. go "back" from thread panel to threads panel
4. go back and forth between rooms
5. the other person is not even writing messages during this, it feels like it is stuck on my own messages notification somehow

#### What did you expect?
no notification counter

#### What happened instead?
On top of #21822, there was a stuck notification (grey circle with a 1) on that room in the room list, but no notification indication on the threads panel or button, or I could not see it

Now after opening 21822 it has gone away inexplicably, probably because the other person kept writing in the room.

### Operating system

arch

### Application version

Element Nightly version: 2022041601 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.56

### Will you send logs?

No

**Comment by novocaine** [comment] 2022-04-21 07:45
Is this a duplicate of https://github.com/vector-im/element-web/issues/21798 ?

**Comment by HarHarLinks** [comment] 2022-04-21 10:15
> Is this a duplicate of #21798 ?

I don't think so, @novocaine @t3chguy 
21798 seems to be about the dot on the threads button, this 21823 is about the room list as stated in the OP.

**Comment by novocaine** [comment] 2022-04-26 08:19
Related: https://github.com/vector-im/element-web/issues/21114

**Comment by HarHarLinks** [comment] 2022-05-27 11:47
I can confirm this is still in Element Nightly version: 2022052601 Olm version: 3.2.8
Again it was caused by a thread that wasn't appropriately marked as read by my client as I read it. Yet I only had a notification indicator in the room list, not in the threads list.

**Closed** 2022-10-24 06:50 UTC
Labels: T-Defect, S-Major, A-Notifications, O-Uncommon, A-Threads, Z-ThreadsNotifications
