### ISSUE TITLE
Newly Joined Users to Room Can't Read Previous Messages

### ISSUE THREAD

**Issue by InklingGirl** [vector-im/element-web#21258] opened 2022-03-01 19:25 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

My own multi-user group chat room, new users see:![2022-03-02_06-13](https://user-images.githubusercontent.com/9910447/156233829-1387a33a-7de1-421b-9574-e73a6ef5df18.png)

Despite the default setting being:![2022-03-02_06-20](https://user-images.githubusercontent.com/9910447/156234456-4eb1b263-3057-4b76-86b3-b82e5cf1ed47.png)

2. What do you click? 

N/A

3. More steps…

N/A

#### What did you expect?

For new users to see all past messages.

#### What happened instead?

![2022-03-02_06-20](https://user-images.githubusercontent.com/9910447/156234456-4eb1b263-3057-4b76-86b3-b82e5cf1ed47.png)

### Operating system

Canonical Ubuntu 20.04 LTS Focal Fossa

### Application version

Element version: 1.10.4 Olm version: 3.2.8

### How did you install the app?

From the first-party Element PPA.

### Homeserver

kom.intkos.link

### Will you send logs?

No

**Comment by robintown** [comment] 2022-03-04 02:30
From the rageshake title at least this sounds like it could be https://github.com/vector-im/element-web/issues/16983. @InklingGirl did this issue resolve itself after the new members switched to a different room and back?

**Comment by uhoreg** [comment] 2022-04-20 14:13
Closing as a duplicate of #16983.

**Closed by uhoreg** 2022-04-20 14:13 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-E2EE, O-Occasional
