### ISSUE TITLE
Allow the changing of volume for audio file playback

### ISSUE THREAD

**Issue by hiddeninthesand** [vector-im/element-web#20647] opened 2022-01-19 19:04 UTC
#### What would you like to do?

Be able to change the volume of audio file playback, like you can on Discord.

#### Why would you like to do it?

I value my hearing, and some files are too loud.

#### How would you like to achieve it?

A small button that expands into a volume slider in the playback UI, much like the video playback UI, or the audio playback UI on Discord.

### Have you considered any alternatives?

There isn't any alternative to this I could think of, besides changing the volume of the entire application, but that's a bit silly.

**Comment by robintown** [comment] 2022-01-19 19:11
Duplicate of https://github.com/vector-im/element-web/issues/18466

**Closed by robintown** 2022-01-19 19:11 UTC
Labels: T-Enhancement
