### ISSUE TITLE
Provide option to disable auto gain adjustment in private calls

### ISSUE THREAD

**Issue by Brando753** [vector-im/element-web#20919] opened 2022-02-04 17:17 UTC
#### What would you like to do?
Be able to disable auto-gain adjustments in private voice calls.

#### Why would you like to do it?
Element is dramatically decreasing my microphone gain and I would like it to be forced to use my desktop settings. Most voice call software that does auto-gain adjustment (google meets, zoom, discord, etc) provides a way to disable this feature. 

#### How would you like to achieve it?
A simple checkbox in the settings panel under audio/video settings should be sufficient.

### Have you considered any alternatives?

Not really sure what else I could do to prevent this from occurring. 

### Additional context

My audio setup is a bit unusual hence why the autogain has such a problem with it, this is not unique to element, however most systems let me disable auto gain to force the correct settings.

**Comment by t3chguy** [comment] 2022-02-04 17:55
Duplicate of https://github.com/vector-im/element-web/issues/6278

**Closed by t3chguy** 2022-02-04 17:55 UTC
Labels: T-Enhancement
