### ISSUE TITLE
All recent messages are UISI after launching app.element.io for the first time since Aug

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#19376] opened 2021-10-13 10:03 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

Launched app.element.io for the first time in a few months

#### What did you expect?

After a while i'd expect to see E2EE history visible, as fallback keys should mean that i should have still been sent megolm keys despite being offline for a few months.

#### What happened instead?

Pretty much all E2EE messages appear to be UISI, even after waiting 20+ minutes.  Meanwhile my logs are exploding with keyshare requests.

Alternatively, my client could be using 4S to grab the missing keys from serverside backup rather than either keysharing them or waiting for old to-device megolm keys to come through.

It almost feels like we're not draining our backlog of to-device msgs correctly though...

### Operating system

macOS

### Browser information

Chrome

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by turt2live** [comment] 2022-06-14 05:15
Duplicate of https://github.com/vector-im/element-web/issues/21195

**Closed by turt2live** 2022-06-14 05:15 UTC
Labels: T-Defect, S-Critical, A-E2EE, Z-UISI, O-Occasional
