### ISSUE TITLE
LibreJS compatibility

### ISSUE THREAD

**Issue by jakubcze12** [vector-im/element-web#23272] opened 2022-09-13 19:37 UTC
### Your use case

[LibreJS](https://en.wikipedia.org/wiki/GNU_LibreJS) is a tool used by Free Software supporters and activists to defend themselves from proprietary JavaScript and online surveillance. Element already is Free Software, but in order for the Javascript to load with LibreJS it must be first manually whitelisted. Adding LibreJS support to element web would greatly improve the usability of the extension.

### What would you like to do?

Element to support LibreJS according to [this](https://www.gnu.org/software/librejs/free-your-javascript.html).

#### Why would you like to do it?

For the sake of more usability of the extension, especially when switching between different instances or element web.

**Comment by t3chguy** [comment] 2022-09-14 08:00
Duplicate of https://github.com/vector-im/element-web/issues/5188

**Closed by t3chguy** 2022-09-14 08:00 UTC
Labels: T-Enhancement
