### ISSUE TITLE
Message bubble breaks VoIP call tiles

### ISSUE THREAD

**Issue by gaelledel** [vector-im/element-web#18152] opened 2021-07-21 15:26 UTC
![Uploading Screenshot 2021-07-21 at 16.15.58.png…]()
The call tiles are broken with the message bubble layout.

**Comment by SimonBrandner** [comment] 2021-07-21 15:27
Duplicate of https://github.com/vector-im/element-web/issues/18144 :)

**Closed by SimonBrandner** 2021-07-21 15:27 UTC
Labels: A-Message-Bubbles, T-Defect
