### ISSUE TITLE
Add hint that bookmarking login page is not what you want

### ISSUE THREAD

**Issue by sphh** [vector-im/element-web#14995] opened 2020-08-18 13:48 UTC
### Description

I made a bookmark https://app.element.io/#/login and everytime I use it, I have to login with username and password and then verify this session - which is a bit annoying. If I use https://app.element.io/#/home, I don't have to login and do not have to go through the verification process. I just found this out by reading #14636 (between the lines).

I would have preferred to have this mentioned somewhere. I can think of the following options:
- Make a note on the login page (https://app.element.io/#/login or https://app.element.io/#/welcome), that it is better to bookmark https://app.element.io/#/home (or whatever is the endorsed link) instead of https://app.element.io/#/login.
- Put a "Why do I see this (all the time)?" link onto the "Verify this session" page, which explains, that if you have bookmarked https://app.element.io/#/login, a new session is initiated whenever this bookmark is clicked upon and it is better to use https://app.element.io/#/home. Here would also be the place to put other possible causes (deleted cookies, persistent storage, fingerprinting, ...), why a new session is created.
- Add a button somewhere, which adds the right bookmark to the main page or to conversations/rooms. (Can this also be done for the `New Tab` page? That's where I have saved the - wrong - link https://app.element.io/#/login).

IMHO such information would help newcomers to not turn away from element, because of the annoying process to verify the device every time they start the webapp!

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 79.0
- **OS**: Linux Mint 20
- **URL**: app.element.io

**Comment by TR-SLimey** [comment] 2020-08-18 14:18
Better yet, make `#login` automatically check for a saved active session and move to `#home` if it exists in storage. That way, not even the slightest bit of user input is required, nor are there any resources to read for the user.

**Comment by sphh** [comment] 2020-08-18 14:31
If that's possible, it would be even better!!

**Comment by jryans** [comment] 2020-08-18 15:13
Yes, I think the core concern here is that we may want to change `login` to redirect back into the app if there is an active session. I am guessing there's an open issue somewhere for this...

**Comment by sphh** [comment] 2020-08-18 15:35
It would certainly help to not turn people away from element. Every user lost is probably lost forever! Personally I nearly stopped using it, because the annoyance factor was very high!

@jryans Do you mean #12476 (and thanks for that excellent title!)

And this is another one, describing the same problem #14767

**Comment by notramo** [comment] 2020-08-24 15:09
@sphh Matrix is not for average people. It is for experienced geeks. I tried to get my friends use it. They was annoyed. Every time I got a question from them (or they didn't know what to do) I tried to tell the devs what is not user friendly, and make suggestions. They tried to convince me that it is user friendly already and there is nothing to do. *The only way they would understand it is that they would get __all__ their frends (not only the geeks) to use Matrix. Then they would get the same questions and annoyance as me.*

**Comment by jryans** [comment] 2020-08-24 15:16
> @jryans Do you mean #12476 (and thanks for that excellent title!)

Yes, I guess let's consider this a duplicate of #12476.

> And this is another one, describing the same problem #14767

It's not clear to me that #14767 is reloading the login page, so unsure so far if that's the same.

**Closed by jryans** 2020-08-24 15:16 UTC
Labels: bug, ui/ux
