### ISSUE TITLE
riot-web does not close

### ISSUE THREAD

**Issue by DoctorSubtilis** [vector-im/element-web#9934] opened 2019-06-02 19:22 UTC
### Description

When I click on "quit" on tray icon, the tray icon disappears, but the program remain active (though invisible).  
If I close via "System activity" the four rows of riot-web and try to re-open the program, it doesn't start (not "visibly" at least: no tray icon). I must close session and then the program (as autostart) works.
![riot-bug](https://user-images.githubusercontent.com/20089138/58766279-e3744e80-857c-11e9-8479-4793bd5a3e04.png)

### Steps to reproduce

- close riot-web
- try to re-open
- the program doesn't start

Describe how what happens differs from what you expected.

Log: sent    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu
- **Version**: 1.0.7

**Comment by DoctorSubtilis** [comment] 2019-06-25 14:28
With the last version, 1.2.2, the problem was not fixed:  
![riot bug (no tray icon)](https://user-images.githubusercontent.com/20089138/60106928-49ac5580-9766-11e9-9f70-45a03c1b20a8.png)

**Comment by t3chguy** [comment] 2022-05-07 01:32
Are you still experiencing this?

**Comment by DoctorSubtilis** [comment] 2022-05-07 06:20
To be honest I don't use riot-web any more. Sorry...

**Comment by SimonBrandner** [comment] 2022-05-07 06:59
> To be honest I don't use riot-web any more. Sorry...

We're sorry to hear that

<hr>

I am going to close this issue as we can't reproduce it; if you ever see this again, please let us know!

**Closed by SimonBrandner** 2022-05-07 06:59 UTC
Labels: T-Defect, Z-Platform-Specific, P2, A-Electron
