### ISSUE TITLE
Rooms disappear from a Space if the Space has a redacted / empty object `m.space.child` state for it

### ISSUE THREAD

**Issue by syldrathecat** [vector-im/element-web#22494] opened 2022-06-09 02:07 UTC
1. Create a space
2. Create a (private) room
3. Use /devtools in the room's timeline to create a custom room state event:
    - Event Type: `m.space.parent`
    - State Key: `!<space-room-id>:homeserver.tld`
    - Content: `{"via":["homeserver.tld"]}`
4. Verify that the private room now appears under the space, in the side bar
5. Use /devtools to enable Developer Mode
6. Use "See room timeline" to access the space's timeline
7. Use /devtools in the space's timeline to create a custom room state event:
    - Event Type: `m.space.child`
    - State Key: `!<private-room-id>:homeserver.tld`
    - Content: `{}`
8. Observe that the private room no longer appears under the space

**Expected:** The room should remain visible

Although the spec isn't explicit about what should happen in this situation, the wording does seem to imply that `m.space.parent` always takes effect regardless of `m.space.child`:

> Rooms can additionally claim to be part of a space by populating their own state with a parent event.

Without allowing `m.space.parent` to override `m.space.child`, there is no way to turn a room from a listed member of a space in to an un-listed one.

**Comment by syldrathecat** [comment] 2022-06-09 02:11
(I edited to remove the first half of this issue, relating to behavior for an empty `via` array, because I don't think it was valid)

**Comment by robertlong** [comment] 2022-06-09 16:54
Similar to https://github.com/vector-im/element-web/issues/22496, I think this may be the intended behavior. `m.space.child` is used to generate the space hierarchy.

> To avoid situations where a room falsely claims it is part of a given space, m.space.parent events should be ignored unless one of the following is true:
>
>    - A corresponding m.space.child event can be found in the supposed parent space.
>    - The sender of the m.space.parent event has sufficient power level in the supposed parent space to send m.space.child state events (there doesn’t need to be a matching child event).

https://spec.matrix.org/v1.2/client-server-api/#mspaceparent-relationships

**Comment by robertlong** [comment] 2022-06-09 16:59
Ah, as @robintown commented here, you do in fact have the proper power level in the parent space so this should work. These two issues are likely caused by the same bug.

https://github.com/vector-im/element-web/issues/22496#issuecomment-1151370792

I'll remove the needs-investigation tag.

**Comment by turt2live** [comment] 2022-06-14 04:54
Duplicate of https://github.com/vector-im/element-web/issues/22496

**Closed by turt2live** 2022-06-14 04:54 UTC
Labels: T-Defect, S-Minor, A-Spaces, Z-Spec-Compliance, O-Uncommon, A-Subspaces
