### ISSUE TITLE
verify from another login should not show when no other devices

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17840] opened 2021-06-29 18:05 UTC
### Description
You can verify from another login even though you have only this one

### Steps to reproduce

- delete all sessions
- login
- see you can verify from another login

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Chrome - the newest version: Version 91.0.4472.77 (Official Build) (64-bit)
- **OS**: Windows
- **URL**: develop branch

Short video explaining the problem:

https://user-images.githubusercontent.com/31655082/123846088-3c0da580-d915-11eb-9a34-4ab9366cbc02.mp4

**Comment by t3chguy** [comment] 2021-06-29 19:47
Duplicate of https://github.com/vector-im/element-web/issues/17765

**Closed by t3chguy** 2021-06-29 19:47 UTC
Labels: A-E2EE-Cross-Signing, S-Minor, T-Defect, X-Regression, Z-Papercuts
