### ISSUE TITLE
Subscribing to many rooms in a space leads to crashes

### ISSUE THREAD

**Issue by BastianZim** [vector-im/element-web#24330] opened 2023-01-25 20:30 UTC
### Steps to reproduce

1. Visit space
2. Subscribe to many rooms
3. Process fails

#### What did you expect?
Succeeds and subcribes
#### What happened instead?
Crashes but subscribes to some

### Operating system

macOS

### Browser information

Safari Version 16.2 (18614.3.7.1.5)

### URL for webapp

https://app.element.io

### Will you send logs?

Yes

**Comment by justjanne** [comment] 2023-01-26 10:10
Likely duplicate of https://github.com/vector-im/element-web/issues/22752

**Comment by SimonBrandner** [comment] 2023-01-27 07:29
Closing as duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by SimonBrandner** 2023-01-27 07:29 UTC
Labels: T-Defect
