### ISSUE TITLE
Ability to export a chat from a timestamp/date range

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25397] opened 2023-05-17 20:13 UTC
#### What would you like to do?

In the chat export options, a new option for "Today", "Yesterday", "Since <date/time>", etc should be added so I can export a range of the chat.

#### Why would you like to do it?

I'm willing to accept that this might be just how I use chat exports, but I often find that I want to export everything that was said today, in the last hour, or sent on a particular day - I don't know how many messages ago that is, or if that includes the "current timeline" (which are the two existing options). I'd make heavy use of "Today" and "Yesterday" options, assuming they understood timezones ;)

#### How would you like to achieve it?

see above

### Have you considered any alternatives?

Usually the workaround is to just export a bunch of the timeline and then cut out the parts that aren't needed (I typically export as plain text anyways, making this easier). Ideally though, I can save a few minutes of manual editing by just exporting what I want.

**Comment by eTomte** [comment] 2023-05-17 20:19
I too would like to see date range options.  Maybe integrate some of the date picker code that is already being used for archive.matrix.org??

**Comment by t3chguy** [comment] 2023-05-18 08:31
Duplicate of https://github.com/vector-im/element-web/issues/19310

**Closed by t3chguy** 2023-05-18 08:31 UTC
Labels: T-Enhancement
