### ISSUE TITLE
Emojis with long "short"-codes look broken in the UI

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#22161] opened 2022-05-12 10:29 UTC
### Steps to reproduce

1. Search for "hand with index..." in the emoji picker.
2. See the following:

![image](https://user-images.githubusercontent.com/1342360/168050598-252f0fad-2ceb-4d70-a036-791862d10a92.png)

#### What did you expect?

Good question! I'd at least expect the shortcode not to extend off the side of the picker UI.

Whether it should be truncated (potentially controversial as you lose information) or simply hard-wrapped at the character level, I'm not sure.

#### What happened instead?

UI look brokey.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022051001, Olm version: 3.2.8

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-05-12 10:30
Duplicate of https://github.com/vector-im/element-web/issues/22126

**Closed by t3chguy** 2022-05-12 10:30 UTC
Labels: T-Defect

**Comment by anoadragon453** [comment] 2022-05-12 10:31
D'oh! I did try to find an existing issue I swear :heart:
