### ISSUE TITLE
Flickering cursor and unresponsive UI

### ISSUE THREAD

**Issue by JulianGro** [vector-im/element-web#21327] opened 2022-03-06 04:54 UTC
### Steps to reproduce

Use Element normally.
Profit.

### Additional information
A semi reproduceable issue I have only encountered since the last update from 1.10.5 to 1.10.6. Considering how often this happens now, I am sure it is a regression either from that update or since 1.10.4 or 1.10.3.
Sometimes the UI regains responsibility after a while, sometimes it doesn't.
It seems like this happens when you click on something while it is changing or about to change. As in clicking reply while someone sends a message, or clicking something while the tooltip is starting to appear. It also seems to happen when just hovering over stuff sometimes.

I would like to send logs, but they contain some private information and nothing that seems useful even on log level -1. (Tested command `element-desktop --enable-logging --log-file=element.log --log-level=-1`)
I would think that some sort of UI log would be required.

I just confirmed that this issue also happens using element-web inside the Vivaldi webbrowser which is also Chromium based.

#### What did you expect?
Stuff should work fine.
#### What happened instead?
UI stops responding, the button that the cursor was over starts flickering, the cursor starts flickering.

### Operating system

Linux Mint 19.3 Cinnamon x86_64

### Application version

Element: 1.10.6, Olm: 3.2.8

### How did you install the app?

Official installation instructions some time ago. https://packages.element.io/debian/

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by luixxiul** [comment] 2022-03-06 07:22
Is this same problem as https://github.com/vector-im/element-web/issues/21313 ?

**Comment by SimonBrandner** [comment] 2022-03-06 07:25
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/21147

**Closed by SimonBrandner** 2022-03-06 07:25 UTC
Labels: T-Defect
