### ISSUE TITLE
"Download this file" for an image on element-desktop opens it in firefox instead

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-web#16266] opened 2021-01-24 18:27 UTC
### Description

I remember this working before but when I now want to save an image to disk it will get opened in my default browser instead.

### Steps to reproduce

- Have a non-e2ee room with an image sent
- Click "Download XYZ.JPG" (or enlarge the image and click "Downlaod this file")
- image will be opened in firefox

Describe how what happens differs from what you expected.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**:Arch Linux
- **Version**: 1.7.17

**Comment by SimonBrandner** [comment] 2021-01-25 06:43
@Bubu For me, it opens it in Gwenview, which is also not really what I'd like... Maybe the code could be improved to be more deterministic

**Comment by t3chguy** [comment] 2021-01-25 10:28
Duplicate of https://github.com/vector-im/element-web/issues/12405

**Closed by t3chguy** 2021-01-25 10:28 UTC
Labels: bug
