### ISSUE TITLE
How to download chat in plain text?

### ISSUE THREAD

**Issue by sailikk** [vector-im/element-web#15835] opened 2020-11-26 09:02 UTC
### Description

I didn't select the "feature request" tag since I'm not sure if this exists or not yet, but if it doesn't, please add a "feature request" tag. I am concerned about longevity. I use this to chat with some friends, and I would like that not to disappear in the future, so I was thinking of taking periodic backups. Usually, projects in the Open Source community have some way to back up things in plain text, so they can be opened and modified freely.

So, I suppose if it does exist, could someone explain how to do it? If it does not, please tag this with "feature request"

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome, version: 86.0.4240.198 (Official Build) (64-bit) (cohort: Stable)
- **OS**: Windows 10
- **URL**: app.element.io

**Comment by t3chguy** [comment] 2020-11-26 09:03
Duplicate of https://github.com/vector-im/element-web/issues/2630 which lists some tools for this.

**Closed by t3chguy** 2020-11-26 09:03 UTC
