### ISSUE TITLE
Adjustable space panel width and/or splitter

### ISSUE THREAD

**Issue by shoqvalue** [vector-im/element-web#23935] opened 2022-12-07 18:15 UTC
#### What would you like to do?
Set the default width of the sidebar and/or have a splitter for manually adjusting the width of the spaces pane. The current 250px fixed width is inadequate for deep hierarchies (3 or more nested spaces, or just nodes with longer than typical names). 

Related:  On hovering over a room or space name, a tooltip should reveal the full name of the room.

#### Why would you like to do it?
Because names in deep hierarchies are currently clipped and often unreadable. It looks terrible when the user can't read the entire name, and the admin is forced to shorten the name just so it's visible. 
#### How would you like to achieve it?
Quick fix:  In settings, user would have a preference or "Sidebar Minimum Width"
Ideal fix:  Setting preference above plus adjustable "splitter" between spaces pane and rooms pane within the sidebar.

**Comment by SimonBrandner** [comment] 2022-12-08 09:39
Related https://github.com/vector-im/element-web/issues/22311

**Comment by t3chguy** [comment] 2022-12-12 10:01
Duplicate of https://github.com/vector-im/element-web/issues/22311

**Closed by t3chguy** 2022-12-12 10:01 UTC
Labels: S-Tolerable, A-Spaces, X-Needs-Design, T-Enhancement, O-Uncommon
