### ISSUE TITLE
Improvement: Add function to prune/mass delete historical rooms

### ISSUE THREAD

**Issue by dragonchaser** [vector-im/element-web#16946] opened 2021-04-14 09:31 UTC
#### Is your suggestion related to a problem? Please describe.
I had a bridge on my homeserver that was running havoc and created way to many portal rooms, after leaving all of them I am stuck with 100+ historical rooms I do not want to "forget" manually.

#### Describe the solution you'd like.
Add a an item to the context menu of the historical rooms list to prune (e.g. mass delete) all items. Also a function to leave rooms in bulk (e.g. filter them by regexp) would be nice, but I guess this is too special to be useful for generic usage. 

#### Describe alternatives you've considered.
Deleting them manually.... way to time consuming.

**Comment by Biep** [comment] 2021-04-14 09:36
Filtering by search criterion, or otherwise selecting with check boxes, and the option to revert the selection, so that the few rooms **not** to be deleted can be checked, and the result then reversed.  It seems unlikely that *both* hundreds of rooms are to be forgotten, *and* hundreds to be retained.

**Comment by SimonBrandner** [comment] 2021-04-14 10:10
Duplicate of [#5280](https://github.com/vector-im/element-web/issues/5280)

**Closed by SimonBrandner** 2021-04-14 10:10 UTC
Labels: T-Enhancement
