### ISSUE TITLE
Loading the page shows an infinite spinner 

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#22217] opened 2022-05-16 08:33 UTC
### Steps to reproduce

1. Open Firefox, disable all add-ons and navigate to https://develop.element.io/

#### What did you expect?
To see the Element Web UI

#### What happened instead?
I see just a spinner and a Logout link

![image](https://user-images.githubusercontent.com/76812/168551983-83ad733e-b7a4-4856-b2e9-621a5bd833b5.png)

### Operating system

Ubuntu 21.10

### Browser information

Firefox 100.90

### URL for webapp

https://develop.element.io

### Application version

Element version: f080b1fb273e-react-fc2d7b67d135-js-ba1f6ffc84b0 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by andybalaam** [comment] 2022-05-16 08:34
I can't rageshake, but here are some console logs:

```
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). moz-extension:33:9
Initialised rageshake. rageshake.ts:72:27
To fix line numbers in Chrome: Meatball menu → Settings → Ignore list → Add /rageshake\.js$ rageshake.ts:72:27
Using Web platform rageshake.ts:72:27
XHRGEThttps://develop.element.io/config.develop.element.io.json?cachebuster=1652689836412
[HTTP/2 404 Not Found 29ms]

Configuring rageshake persistence... rageshake.ts:72:27
returning explicit theme: light-high-contrast 2 rageshake.ts:72:27
Using WebAssembly Olm rageshake.ts:72:27
set language to en rageshake.ts:72:27
Application is running in production mode rageshake.ts:72:27
Vector starting at https://develop.element.io/ rageshake.ts:72:27
startUpdater, current version is f080b1fb273e-react-e1d11db25601-js-ba1f6ffc84b0 rageshake.ts:72:27
Verifying homeserver configuration rageshake.ts:72:27
Config uses a default_server_name - doing .well-known lookup rageshake.ts:72:27
DEPRECATED CONFIG OPTION: In the future, default_server_name will not be accepted. Please use default_server_config instead. rageshake.ts:72:27
No update available, already on f080b1fb273e-react-e1d11db25601-js-ba1f6ffc84b0 rageshake.ts:72:27
Using homeserver config: 
Object { hsUrl: "https://matrix-client.matrix.org", hsName: "matrix.org", hsNameIsDifferent: true, isUrl: "https://vector.im", isDefault: true, isNameResolvable: true, warning: null }
rageshake.ts:72:27
Updating SdkConfig with validated discovery information rageshake.ts:72:27
returning explicit theme: light-high-contrast rageshake.ts:72:27
Got pickle key rageshake.ts:72:27
Restoring session for @andybalaam:matrix.org rageshake.ts:72:27
setLoggedIn: mxid: @andybalaam:matrix.org deviceId: MKBDKTQJQJ guest: false hs: https://matrix-client.matrix.org/ softLogout: false  freshLogin: false rageshake.ts:72:27
StorageManager: Checking storage consistency rageshake.ts:72:27
StorageManager: Local storage supported? true rageshake.ts:72:27
StorageManager: IndexedDB supported? true rageshake.ts:72:27
StorageManager: Local storage contains data? true rageshake.ts:72:27
StorageManager: Crypto initialised? true rageshake.ts:72:27
StorageManager: Sync store using IndexedDB contains data? true rageshake.ts:72:27
StorageManager: Crypto store using IndexedDB contains data? true rageshake.ts:72:27
StorageManager: Storage consistency checks passed rageshake.ts:72:27
Some cookies are misusing the recommended “SameSite“ attribute 3
Session persisted for @andybalaam:matrix.org rageshake.ts:72:27
Lifecycle: Starting MatrixClient rageshake.ts:72:27
EventIndex: Platform doesn't support event indexing, not initializing. rageshake.ts:72:27
IndexedDBStore.startup: connecting to backend rageshake.ts:72:27
MatrixClientPeg: waiting for MatrixClient store to initialise rageshake.ts:72:27
returning explicit theme: light-high-contrast rageshake.ts:72:27
Switching to room id !uDeZzTCTgIIqoUZmIp:matrix.org at event undefined rageshake.ts:72:27
StorageManager: Persistent? true rageshake.ts:72:27
IndexedDB worker is ready rageshake.ts:72:27
LocalIndexedDBStoreBackend.connect: connecting... 872e090734592b905ed9.worker.js:885:22
LocalIndexedDBStoreBackend.connect: awaiting connection... 872e090734592b905ed9.worker.js:885:22
LocalIndexedDBStoreBackend.connect: connected 872e090734592b905ed9.worker.js:885:22
LocalIndexedDBStoreBackend: loading account data... 872e090734592b905ed9.worker.js:885:22
LocalIndexedDBStoreBackend: loading sync data... 872e090734592b905ed9.worker.js:885:22
The resource at “https://develop.element.io/fonts/Inter/Inter-BoldItalic.2129bd0.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. develop.element.io
The resource at “https://develop.element.io/fonts/Inter/Inter-Bold.fc28dff.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. develop.element.io
The resource at “https://develop.element.io/fonts/Inter/Inter-SemiBoldItalic.10a60d8.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. develop.element.io
The resource at “https://develop.element.io/fonts/Inter/Inter-SemiBold.0802d48.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. develop.element.io
The resource at “https://develop.element.io/fonts/Inter/Inter-MediumItalic.8154ac2.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. develop.element.io
The resource at “https://develop.element.io/fonts/Inter/Inter-Medium.027d14e.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. develop.element.io
The resource at “https://develop.element.io/fonts/Inter/Inter-Italic.b791861.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. develop.element.io
Wait!
If someone told you to copy/paste something here, there is a high likelihood you're being scammed!
If you know what you're doing, Element is open-source, be sure to check out our GitHub (https://github.com/vector-im/element-web/) and contribute! rageshake.ts:81:39
Wait!
If someone told you to copy/paste something here, there is a high likelihood you're being scammed!
If you know what you're doing, Element is open-source, be sure to check out our GitHub (https://github.com/vector-im/element-web/) and contribute! 5 rageshake.ts:81:39
```

**Comment by t3chguy** [comment] 2022-05-16 08:41
Looks similar to https://github.com/vector-im/element-web/issues/16503

**Comment by andybalaam** [comment] 2022-05-16 08:52
I hope/assume this will go away if I delete the cache, but I will refrain from doing that for a while in case people ask me to gather more information.

**Comment by andybalaam** [comment] 2022-05-16 08:55
Element Web is working OK for me in Chromium.

**Comment by andybalaam** [comment] 2022-05-16 09:10
I did have Element Web open in two different browser tabs.

**Comment by andybalaam** [comment] 2022-05-16 09:15
Inspired by #16503 I restarted Firefox and the problem went away :tada:

**Comment by novocaine** [comment] 2022-05-16 09:20
is this a duplicate of https://github.com/vector-im/element-web/issues/16503 ?

**Comment by novocaine** [comment] 2022-05-16 09:21
Did it happen once, or even after refreshing the page?

**Comment by novocaine** [comment] 2022-05-16 12:45
I believe this is a duplicate of https://github.com/vector-im/element-web/issues/17891

**Closed by novocaine** 2022-05-16 12:45 UTC
Labels: T-Defect, X-Regression, S-Critical, O-Uncommon
