### ISSUE TITLE
Scroll through images with buttons and key strokes (light box)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#20238] opened 2021-12-17 10:58 UTC
### Your use case

When viewing an image, it would be nice to be able to scroll to the next image in the timeline (or message). 

- [ ] Add left and right arrows to the image viewer screen
- [ ] Allow keyboard left and right to scroll

This enhancement was raised during community testing on December 16, 2021
"When viewing an image, add buttons to view the next and previous image in the room. Allow navigation via keyboard"

**Comment by t3chguy** [comment] 2021-12-17 11:00
Duplicate of https://github.com/vector-im/element-web/issues/337

**Closed by t3chguy** 2021-12-17 11:00 UTC
Labels: T-Enhancement, Z-Papercuts, A-Light-Box, Z-Community-Testing
