### ISSUE TITLE
1.11.4 after update - "Couldn't find webapp files in any of.."

### ISSUE THREAD

**Issue by cremesk** [vector-im/element-web#23174] opened 2022-08-31 18:32 UTC
### Steps to reproduce

`element-desktop`

### Outcome

```
/home/sven/.config/Element exists: no
/home/sven/.config/Riot exists: yes
Using legacy user data path: /home/sven/.config/Riot
Couldn't find webapp files in any of: 
	/opt/Element/resources/app.asar/webapp.asar
	/opt/Element/resources/webapp.asar
	/opt/Element/resources/app.asar/webapp
	/opt/Element/resources/webapp
App setup failed: exiting Error: Failed to find webapp files
    at /opt/Element/resources/app.asar/lib/electron-main.js:145:15
    at Generator.throw (<anonymous>)
    at rejected (/opt/Element/resources/app.asar/lib/electron-main.js:43:65)
```

### Operating system

Ubuntu

### Application version

1.11.4

### How did you install the app?

from https://element.io/get-started

### Homeserver

envs.net / Synapse 1.66.0

### Will you send logs?

No

**Comment by turt2live** [comment] 2022-08-31 18:36
Note that this only affects the Linux (Debian) builds specifically

**Comment by Polve** [comment] 2022-08-31 18:38
Same for me: after apt updating I've now a non-functional client.

Since this is very annoying, can someone give me the direct link to the download of the previous deb?

**Comment by turt2live** [comment] 2022-08-31 18:42
v1.11.4 is a **security release**, so please watch [the announcements room](https://matrix.to/#/#element-web-announcements:matrix.org) for updates on when the Linux builds are available.

**Comment by cremesk** [comment] 2022-08-31 18:48
> Same for me: after apt updating I've now a non-functional client.
> 
> Since this is very annoying, can someone give me the direct link to the download of the previous deb?
> 
> UPDATE found: https://packages.element.io/debian/pool/main/e/element-desktop/element-desktop_1.11.3_amd64.deb

@Polve in the meantime, it is better to use an updated public element web client. e.g. https://app.element.io/version.

**Comment by paboum** [comment] 2022-08-31 19:30
Seems like a regression of #13710

**Comment by turt2live** [comment] 2022-08-31 21:35
This should be fixed in 1.11.4-1, published now to the debian repo. We've confirmed it at least loads, so the remaining bugs are just regular bugs ;) 

We haven't identified a cause, but it appears the build script just didn't do its job. We're taking a look at hardening the release process separate to this stuff anyways, so will likely resolve it there.

Apologies for the inconvenience.

**Closed by turt2live** 2022-08-31 21:35 UTC
Labels: T-Defect, Z-Platform-Specific

**Comment by paboum** [comment] 2022-08-31 22:21
> We haven't identified a cause, but it appears the build script just didn't do its job. We're taking a look at hardening the release process separate to this stuff anyways, so will likely resolve it there.

You could also test the package before releasing it, the procedure doesn't seem complicated, just unpack .deb and run the binary.

**Comment by turt2live** [comment] 2022-08-31 22:38
That is part of the improvements to the release system that we're looking at, though not for several stages down the road. We're more focused on testing that the application itself (which would normally be packaged correctly) is stable - the steps to build a package haven't changed in a long while.
