### ISSUE TITLE
Use a different icon for Element Nightly

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#21718] opened 2022-04-08 10:33 UTC
#### What would you like to do?

Easily differentiate Desktop and Desktop Nightly

#### Why would you like to do it?

Because I'm runing them both and it would help to separate them

#### How would you like to achieve it?

Use a different icon - Firefox Nightly do this, it's a darker version of the existing logo, works well.

**Comment by t3chguy** [comment] 2022-04-08 10:34
Duplicate of https://github.com/vector-im/element-web/issues/14592

**Closed by t3chguy** 2022-04-08 10:34 UTC
Labels: A-Electron, T-Enhancement, A-Electron-Nightly
