### ISSUE TITLE
Unread room with non-zero notification count not sorted correctly in room list

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#25622] opened 2023-06-19 07:28 UTC
### Steps to reproduce

My room list is set up to sort alphabetically with unread rooms first.

![Screenshot 2023-06-19 at 09 25 43](https://github.com/vector-im/element-web/assets/1137962/bcbbb39b-b86d-4fe2-98d6-603df3f40773)

Somebody replied in a thread to me in the #element-dev:matrix.org room.

#### What did you expect?

The room to receive a non-zero unread count and move towards the top of my room list.

#### What happened instead?

The room received a non-zero unread count but stayed in the middle of the room list, even after rooms with only the unread dot but no notification count. Screenshot in the rageshake.

### Operating system

macOS

### Application version

Element Desktop nightly

### How did you install the app?

https://packages.element.io/nightly/

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-06-19 08:18
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by weeman1337** [comment] 2023-06-19 08:18
Duplicate of https://github.com/vector-im/element-web/issues/24547

**Closed by weeman1337** 2023-06-19 08:18 UTC
Labels: T-Defect
