### ISSUE TITLE
clicking on a RR should take you to their MemberInfo

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15258] opened 2020-09-22 15:29 UTC
i think this used to work?

**Comment by t3chguy** [comment] 2020-09-22 15:31
Duplicate of #5784

**Comment by turt2live** [comment] 2020-09-22 15:31
Duplicate of https://github.com/vector-im/element-web/issues/5784

This has never been a feature.

**Closed** 2020-09-22 15:31 UTC
