### ISSUE TITLE
Infinite spinner trying to join #home:fosdem.org

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20604] opened 2022-01-18 11:11 UTC
### Steps to reproduce

1. Clicked on a link to #home:fosdem.org within the app
2. Hit join on the space dialog that was shown

### Outcome

Infinite spinner shown; never joined the space:

<img width="621" alt="Screenshot 2022-01-18 at 11 11 24" src="https://user-images.githubusercontent.com/1294269/149926692-6239b40e-e38d-4249-925e-92860591bece.png">

### Operating system

macOS 12.1 on M1

### Application version

Nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by kittykat** [comment] 2022-01-18 18:54
Possibly duplicate of #20457

**Comment by t3chguy** [comment] 2022-01-18 21:23
Yup!

**Closed by t3chguy** 2022-01-18 21:23 UTC
Labels: T-Defect, S-Major, Z-Rageshake, A-Spaces, X-Needs-Investigation
