### ISSUE TITLE
element-desktop Linux system tray left and right click both open the menu, I suggest right click open the menu and left click show or hide element-desktop.

### ISSUE THREAD

**Issue by xekon** [vector-im/element-web#17850] opened 2021-06-30 20:40 UTC
#### Is your suggestion related to a problem?
Yes, showing/displaying the element-desktop requires additional mouse movement and an extra click.

#### Describe the solution you'd like.
I would absolutely love it if the left click facilitated show/hide functionality of element, currently both left and right click open a menu.

#### Describe alternatives you've considered.
The only other alternative I have considered is using pidgin, that one the left click shows or hides the window, its also open source, but that one is XMPP, and as far as I can tell Element is the most polished matrix client for linux.

#### Additional context
This is a screenshot of the menu that is displayed when you left or right click on the element-desktop system tray icon.

My operating system is Kubuntu 20.04.2

![2021-06-30_13-38](https://user-images.githubusercontent.com/106644/124028181-8ee46d00-d9a8-11eb-96e6-7150d8ecc0ae.png)

**Comment by xekon** [comment] 2021-06-30 21:18
I just found this: https://github.com/vector-im/element-web/issues/11772

This worked for me:

```
sudo touch /opt/Element/libappindicator3.so
sudo touch /opt/Element/libappindicator3.so.1
```

After doing that left click now shows and hides Element.

**Comment by hwittenborn** [comment] 2021-07-01 02:29
I would honestly prefer it doesn't do that.

All of my other apps that are pinnable to the system tray bring up a context menu when clicked on, regardless if on a right click or left click.

It would make Element the odd ball out, and just wouldn't feel right to me. It would require me redo my muscle memory (albeit a tiny part, but one I use frequently), and again, just wouldn't fit in well with the rest of my apps.

Just my take on it.

**Comment by hwittenborn** [comment] 2021-07-01 02:30
Something I *have* seen though is opening up the app if you double click the system tray icon. I'd be fine with something like that.

**Comment by xekon** [comment] 2021-07-01 03:09
yeah, i think its common in windows for it to be double click, so maybe there should be options for what the left click does.

It is now show/hide properly for me with a single left click after doing this:

sudo touch /opt/Element/libappindicator3.so
sudo touch /opt/Element/libappindicator3.so.1

**Comment by t3chguy** [comment] 2021-07-01 07:20
Duplicate of https://github.com/vector-im/element-web/issues/11772

**Closed by t3chguy** 2021-07-01 07:20 UTC
Labels: T-Enhancement
