### ISSUE TITLE
Alternate UI Design for Send Custom Event in Dev Tools

### ISSUE THREAD

**Issue by DantrazTrev** [vector-im/element-web#17086] opened 2021-04-28 05:06 UTC
#### Is your suggestion related to a problem? Please describe.
From the UI I could figure out that send custom events in Dev Tools has two options State Event and Event. However selecting between these two is a  bit confusing considering the button is highlighted and placed right next to the send button and might be confused for the main action button rather than a toggle 
![Element  2  _ dantes test dum](https://user-images.githubusercontent.com/43457420/116349100-e3366980-a80c-11eb-9185-ccc3f896a9c0.gif)

#### Describe the solution you'd like.
Possibly a toggle switch above the Event Content that allows switching between the two.

**Comment by aaronraimist** [comment] 2021-04-29 01:27
Duplicate of #9583

**Closed by aaronraimist** 2021-04-29 01:27 UTC
Labels: A-DevTools, T-Enhancement
