### ISSUE TITLE
Lists change style when edited

### ISSUE THREAD

**Issue by Arnei** [vector-im/element-web#23507] opened 2022-10-17 14:36 UTC
### Steps to reproduce

1. In a room, create a chat message with the following properties:
  i. At least one line of text.
  ii. A list of items with at least one item in a sublist
3. Edit the message slightly. For example, add or delete a character.
4. Watch all list elements gain additional padding
5. Edit the message sligtly again.
6. Watch all list elements lose the additional padding.
7. Repeat

A screencap of what it looks like:
[Screencast.webm](https://user-images.githubusercontent.com/14070005/196203542-4ce737b4-5838-43b4-b055-44f199607419.webm)

It seems that editing a message like the one described above results in all the list items text being wrapped in `<p></p>` tags. These then receive a margin from the markdown-body style, adding space between the list elements. Curiously, this does not happen if the list does not contain any sublist or if the list is the only part of the message.

Potentially related part of the code: https://github.com/matrix-org/matrix-react-sdk/blob/631720b21b9260bd05478e92034f8b9c46be342b/src/Markdown.ts#L282

#### What did you expect?

For list style to be consist across edits.

#### What happened instead?

List gained/lost padding after edits.

### Operating system

Fedora 35

### Browser information

Firefox 102.0.2

### URL for webapp

develop from a couple days ago

### Application version

Version von Element: !!UNSET!! Version von Olm: 3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-10-17 14:39
Related https://github.com/vector-im/element-web/issues/22863

**Comment by t3chguy** [comment] 2022-11-02 11:47
Duplicate of https://github.com/vector-im/element-web/issues/10725

**Closed by t3chguy** 2022-11-02 11:47 UTC
Labels: T-Defect, S-Minor, A-Composer, O-Occasional
