### ISSUE TITLE
Angle brackets in messages are escaped when editing

### ISSUE THREAD

**Issue by progval** [vector-im/element-web#24163] opened 2023-01-04 20:56 UTC
### Steps to reproduce

1. type `<foo> bar` and send
3. press the ArrowUp key

#### What did you expect?

The edited message should appear as `<foo> bar`

#### What happened instead?

The edited message appears as `\<foo> bar`

### Operating system

Debian 11

### Browser information

Firefox 102.6esr

### URL for webapp

https://riot.im/app/

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment] 2023-01-05 09:09
Duplicate of https://github.com/vector-im/element-web/issues/22456

**Closed by gsouquet** 2023-01-05 09:09 UTC
Labels: T-Defect
