### ISSUE TITLE
Setting default language is invalid

### ISSUE THREAD

**Issue by lostmaniac** [vector-im/element-web#15868] opened 2020-12-01 09:28 UTC
I configure in the default config.json

   "settingDefaults": {
"language": "zh_Hans"
}

Cannot take effect

**Comment by t3chguy** [comment] 2020-12-01 10:35
I believe the language will only be considered if the user's browser doesn't have a specified language.

**Comment by MSG-maniac** [comment] 2020-12-01 12:13
But my browser is in Chinese, and the English version is still open.

**Comment by t3chguy** [comment] 2020-12-01 12:16
Sounds like your account already has English pre-set, try to reproduce using a new account.

**Comment by MSG-maniac** [comment] 2020-12-01 14:15
![捕获](https://user-images.githubusercontent.com/6057477/100751731-a9f6fa80-3422-11eb-9e2b-5e1c6fc1b7a4.PNG)

**Comment by MSG-maniac** [comment] 2020-12-01 14:17
The Chinese language of the code is: zh_Hans
The Chinese language identifier of the browser is: zh-CN

----
navigator.languages

(4) ["zh-CN", "en", "en-GB", "en-US"]
0: "zh-CN"
1: "en"
2: "en-GB"
3: "en-US"

**Comment by MSG-maniac** [comment] 2020-12-01 14:25
https://github.com/vector-im/element-web/issues/5913

**Comment by jryans** [comment] 2020-12-02 10:50
Hmm, perhaps we need to some specialised mapping to account for different language codes like this case...

**Comment by MSG-maniac** [comment] 2020-12-02 12:02
Is there any temporary solution?

**Comment by MSG-maniac** [comment] 2020-12-02 12:03
Or how long can the repair be completed? thank you very much

**Comment by MSG-maniac** [comment] 2020-12-02 12:04
Now that there is an option to prohibit switching languages, it is reasonable to have an option to configure the default language, right?

**Comment by jryans** [comment] 2020-12-14 14:37
> Is there any temporary solution?

You can adjust the language in every session, but I don't think that's what you want...

**Comment by t3chguy** [comment] 2021-07-15 18:41
Duplicate of https://github.com/vector-im/element-web/issues/5913

**Closed by t3chguy** 2021-07-15 18:41 UTC
Labels: I18n, P2, S-Major, T-Defect

**Comment by qzicxjmozbxameuhnk** [comment] 2021-07-20 09:53
@lostmaniac in https://github.com/vector-im/element-web/issues/15868#issuecomment-737187050
> 有什么临时解决办法吗？

Here is a temporary solution with one line of code: 
https://github.com/vector-im/element-web/issues/5913#issuecomment-883257145
