### ISSUE TITLE
Blank window on SIGTERM

### ISSUE THREAD

**Issue by bagage** [vector-im/element-web#15440] opened 2020-10-12 09:25 UTC
### Description

When running low memory using the Electron app, `element-desktop` renderer process is getting killed (because it's the highest consumer), resulting in a blank window:
 
![image](https://user-images.githubusercontent.com/1451988/95729401-22400b80-0c7d-11eb-858e-0de35e351336.png)

The problem is: you cannot do anything but stop Element and start it again.

Other Electron apps (for instance Slack), keeps the menu bar with the "Force refresh" button available, resulting in the renderer being restarted, which fixes the problem.

### Steps to reproduce

1. Find the element-desktop render PID `ps aux | grep 'element-desktop --type=renderer'`
2. Kill it with SIGTERM: `kill -15 $pid`

--> element-desktop shows blank window.

### Version information

- **Platform**: web (in-browser) or desktop? desktop

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Ubuntu
- **Version**: 1.x.y  1.7.8 olm 3.1.3

**Comment by turt2live** [comment] 2020-10-12 20:39
This is largely the same root cause as https://github.com/vector-im/element-web/issues/4264 - closing in favour of that

**Closed by turt2live** 2020-10-12 20:39 UTC

**Comment by bagage** [comment] 2020-10-12 21:26
Strictly speaking, I do not think they share the same root cause: #4264 is about handling big file uploads (the fix would probably mean using less memory when opening big files).

This one is about fixing the problem that arises when no memory is left and the renderer is killed. It can be because of a big file upload, or because another application (say `make -j4`) is consuming many memory, resulting in element renderer to be killed. The fix here would be to at least have a button to restart the renderer, nothing related to memory at all.

**Comment by turt2live** [comment] 2020-10-12 22:02
#4264's root cause is memory exhaustion, which causes the rendering process to crash. The fix is to make the rendering process not crash, or if it does then take the rest of the app with it.
