### ISSUE TITLE
UISIs in threads are super ugly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#22077] opened 2022-05-04 23:29 UTC
### Steps to reproduce

<img width="412" alt="Screenshot 2022-05-05 at 00 27 53" src="https://user-images.githubusercontent.com/1294269/166841342-aa4ee3e7-bef1-46b0-a11f-3b984c817145.png">

in the timeline, shown as:

<img width="623" alt="Screenshot 2022-05-05 at 00 28 25" src="https://user-images.githubusercontent.com/1294269/166841366-6ee457aa-720d-4f9d-af3c-ab632a963b50.png">

(Separately, i have no idea why the room ID would be mismatched here :-/)

#### What did you expect?

Pretty UISIs

#### What happened instead?

Ugly UISIs

### Operating system

macOS

### Homeserver

nightly

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-05-04 23:37
Duplicate of https://github.com/vector-im/element-web/issues/22047

**Closed by t3chguy** 2022-05-04 23:37 UTC
Labels: T-Defect
