### ISSUE TITLE
Forgotten rooms reappear from riot.im interface

### ISSUE THREAD

**Issue by bennabiy** [vector-im/element-web#4886] opened 2017-08-25 14:54 UTC
When I choose to forget a room listed under historical, it disappears for about a second, then reappears. Then a second forget issued causes it to disappear totally.

**Comment by turt2live** [comment] 2020-08-31 19:44
I can't reproduce this on a pre-Element version, so presuming it was fixed in 2018/2019.

**Closed by turt2live** 2020-08-31 19:44 UTC
Labels: bug, minor, p1, type:roomlist, ui/ux
