### ISSUE TITLE
"Help & About" screen isn't working

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#22961] opened 2022-07-29 08:57 UTC
### Steps to reproduce

Possibly related to #22960, but: clicking on "Help & About" in the settings screen just makes the Settings modal disappear

#### What did you expect?

A help & about screen

#### What happened instead?

Settings modal disappears

### Operating system

Ubuntu 22.04

### Application version

element-nightly 2022071901

### How did you install the app?

nightly debian

### Homeserver

synapse 1.61.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-07-29 09:02
Duplicate of https://github.com/vector-im/element-web/issues/22892

**Comment by richvdh** [comment] 2022-07-29 09:03
I should really search the issue tracker before filing issues, sorry :/

**Closed by t3chguy** 2022-07-29 09:02 UTC
Labels: T-Defect
