### ISSUE TITLE
Cannot decrypt messages from one particular user

### ISSUE THREAD

**Issue by ibeckermayer** [vector-im/element-web#25265] opened 2023-05-02 18:55 UTC
### Steps to reproduce

1. One user sends a message to the room
2. Other users can see his messages, I can't

#### What did you expect?
I expected to be able to see his messages

#### What happened instead?
I just get an "Unable to decrypt" for all of his messages. I also see:

"Open another device to load encrypted messages
This device is requesting decryption keys from your other devices. Opening one of your other devices may speed this up."

stuck to the top of the screen in this chat, but opening my other device doesn't solve anything. I only have two sessions open, both verified.

### Operating system

MacOS

### Application version

Element version: 1.11.30 Olm version: 3.2.14

### Will you send logs?

Yes

**Comment by richvdh** [comment] 2023-11-07 11:36
Duplicate of https://github.com/vector-im/element-meta/issues/245

**Closed by richvdh** 2023-11-07 11:36 UTC
Labels: T-Defect, S-Major, Z-UISI, O-Uncommon, Team: Crypto
