### ISSUE TITLE
Voice Message - Malformed waveform data in event content

### ISSUE THREAD

**Issue by onurays** [vector-im/element-web#18939] opened 2021-09-07 09:13 UTC
### Steps to reproduce

Send a voice message and check waveform data in event content.

### What happened?

Waveform array data is filled with `null`s and Android cannot render it:

![image](https://user-images.githubusercontent.com/1254401/132318115-1f7b5dbf-1da4-40f5-90a3-0cc300924dbc.png)

### Operating system

macOS

### Browser information

Firefox 91.0.2

### Have you submitted a rageshake?

Yes

**Comment by Half-Shot** [comment] 2021-09-07 09:52
Duplicate of https://github.com/vector-im/element-web/issues/18587, also allegedly fixed.

**Comment by bmarty** [comment] 2021-09-07 10:04
Can reproduce with:

Element version: ed3ba39ffe6b-react-527ea6eb774b-js-324f9e58ea34
Olm version: 3.2.3

Am I supposed to have the fix?

**Comment by dbkr** [comment] 2021-09-07 11:26
Will re-open the other issue - the version you have contains the commit that should have fixed it.

**Closed** 2021-09-07 11:27 UTC
Labels: T-Defect, A-Voice Messages
