### ISSUE TITLE
Clicking a room alias in a topic opens in a new tab

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24739] opened 2023-03-05 01:26 UTC
### Steps to reproduce

1. Have a room with a room alias in it (not a markdown link)
2. Click it

#### What did you expect?

To be navigated to the room.

#### What happened instead?

It opened matrix.to in a web browser

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2023030301 Olm version: 3.2.12

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by luixxiul** [comment] 2023-03-07 06:37
Duplicate of https://github.com/vector-im/element-web/issues/23395 ?

**Comment by t3chguy** [comment] 2023-03-07 08:56
Duplicate of #23395

**Closed by t3chguy** 2023-03-07 08:56 UTC
Labels: T-Defect
