### ISSUE TITLE
Allow notifications to be muted for a set time period, after this time period notifications will automagically unmute.

### ISSUE THREAD

**Issue by BjornW** [vector-im/element-web#20765] opened 2022-01-26 11:15 UTC
#### What would you like to do?
I'd like to be able to mute notifications for a set time.

#### Why would you like to do it?
It would allow my to set certain time periods in which I wish not to be disturbed by notifications while still leaving Element open in a tab for the occasional glance at rooms I need to watch.  

#### How would you like to achieve it?
Instead of notifications on/off we could a global 'do not disturb for [1 hour | 4 hrs | a day | a week | a month ]' setting for notifications. Similar to for instance Signal uses in their Android app with groups. 

### Have you considered any alternatives?

The alternative is switching notifications off, but then I forget to switch them on again....

### Additional context

If there's anything I can do to help with this feature, please let me know and point me in the right direction.

**Comment by t3chguy** [comment] 2022-01-26 11:50
Duplicate of https://github.com/vector-im/element-web/issues/3569

**Closed by t3chguy** 2022-01-26 11:50 UTC
Labels: T-Enhancement
