### ISSUE TITLE
(Feature Request) "Smart" Push Notifications

### ISSUE THREAD

**Issue by Mobmaker55** [vector-im/element-web#18011] opened 2021-07-15 20:19 UTC
#### Is your suggestion related to a problem? Please describe.
I have Element on both my phone, and on my desktop through web. Discord has a feature where when you are at your desktop, your mobile apps don't receive push notifications. Element does not have this feature, and sends a notification to ALL connected logins & devices (as far as I am aware).

#### Describe the solution you'd like.
I would like for "smart" notifications to exist where notifications are not pushed out to all other devices when one is active.

#### Describe alternatives you've considered.
You can simply disable notifications on your phone while you're using your desktop, and then re-enable them once you're on the road, but that is a clunky and inconvenient solution.

#### Additional context
I don't really have anything else to say lol, it's a pretty simple feature concept.

**Comment by ShadowJonathan** [comment] 2021-07-15 22:56
This is a Spec question, but let me fill in some extra information on how to approach this;

You can do this by looking at the "presence" data that these devices might send to the server. Directly comparing it with discord means you'd require synapse/matrix to be able to differentiate different "classes" of devices, doing this via simple "desktop"/"mobile" methods would actually leak some privacy information regarding some metadata of where a user might be, which is something I think is worth avoiding.

Instead, this could be implemented by either implementing nameless "priority classes" of devices a device might register to (which is the complex solution), or you'd implement a generic "timeout" functionality where you take into account presence data from each device, and only send notifications when all of them are on "idle" (when you're away for a minute from your PC, for instance).

**Comment by t3chguy** [comment] 2021-07-15 23:33
Duplicate of https://github.com/vector-im/element-web/issues/469

**Closed by t3chguy** 2021-07-15 23:33 UTC
Labels: T-Enhancement
