### ISSUE TITLE
No way to delete session from session verification dialog

### ISSUE THREAD

**Issue by strct** [vector-im/element-web#15058] opened 2020-08-27 19:54 UTC
### Description

No way to delete session from session verification dialog.

### Steps to reproduce

- click on Review in the "Review where you are logged in" - dialog
![Screenshot_2020-08-27 Element](https://user-images.githubusercontent.com/48618304/91487819-a5182d00-e8ae-11ea-850f-03b92d9f067c.png)

- Click on an old session, which you know isn't valid anymore and want to remove
![Screenshot_2020-08-27 Element2](https://user-images.githubusercontent.com/48618304/91488056-05a76a00-e8af-11ea-9dc3-8115b0be90f3.png)

It is confusing that the only option is to verify the device. An option to delete the session would be helpful, since that is the action I would like to take for an old session.

![screenshot](https://user-images.githubusercontent.com/48618304/91487171-a563f880-e8ad-11ea-9ffd-4ceb9da006fe.png)

### Version information

- **Platform**: web

For the web app:

- **URL**: app.element.io

**Comment by turt2live** [comment] 2020-08-27 19:57
This is essentially a duplicate of the following:
* https://github.com/vector-im/element-web/issues/14343
* https://github.com/vector-im/element-web/issues/13596
* https://github.com/vector-im/element-web/issues/13187
* https://github.com/vector-im/element-web/issues/13086

**Closed by turt2live** 2020-08-27 19:57 UTC
Labels: bug, ui/ux
