### ISSUE TITLE
Add full date support on message

### ISSUE THREAD

**Issue by Serizao** [vector-im/element-web#26065] opened 2023-08-28 11:03 UTC
#### What would you like to do?
I would like to add day/month/years to message with different date format ex fr date format dd/mm/yy vs en date format mm/dd/yy

#### Why would you like to do it?
I'd like to see faster traceability. For example, after a search in a room, if there are a lot of messages, it's difficult to pinpoint the date and time.

#### How would you like to achieve it?

I think this needs to be integrated into the preference

### Have you considered any alternatives?

N.A.

### Additional context

exemple this is actual:
![image](https://github.com/vector-im/element-web/assets/11671895/2dd28316-0361-41c1-90e7-889e4d21460e)

and i would like 
![image](https://github.com/vector-im/element-web/assets/11671895/ce718093-5b79-48b4-9cee-98ccb781f802)

**Comment by HarHarLinks** [comment] 2023-08-28 11:57
(you can see it currently by hovering the cursor over the timestamp, but i agree it should be easier to do and more discoverable. however alternative solution concepts also exists, like floating date borders)

**Comment by germain-gg** [comment] 2023-08-30 06:36
Marking as a duplicate of https://github.com/vector-im/element-web/issues/7575

This is an alternative solution to what is suggested there. I would suggest your idea there.

**Closed by germain-gg** 2023-08-30 06:36 UTC
Labels: S-Minor, A-Timeline, T-Enhancement
