### ISSUE TITLE
Seshat Broken (Invalid Passphrase)

### ISSUE THREAD

**Issue by dylangerdaly** [vector-im/element-web#22828] opened 2022-07-13 03:00 UTC
### Steps to reproduce

1. Totally wipe EventStore
2. Ensure Native Libs are compiled + libsqlcipher is supported
3. Enable E2EE Search
4. Cry

#### What did you expect?
Seshat to work
#### What happened instead?
```
EventIndex: Error initializing the event index {message: 'Error opening the database: DatabaseUnlockError("Invalid passphrase")'}
```

Note: I'm not using Keytar, so I'm using a `DEFAULT_PASSPHRASE` for my Seshat Cache

### Operating system

Fedora 35

### Application version

Element version: 1.11.0 Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-07-13 08:52
Duplicate of https://github.com/vector-im/element-web/issues/19001

**Closed by t3chguy** 2022-07-13 08:52 UTC
Labels: T-Defect
