### ISSUE TITLE
heic images not shown in browser and/or desktop app, but ok in mobile apps

### ISSUE THREAD

**Issue by theogfx** [vector-im/element-web#18519] opened 2021-08-13 00:21 UTC
### Steps to reproduce

Send a picture from phone in HEIC format to a person or a room.

### What happened?

Picture does not show either in Dekstop app or in Element Web (thumbnail or fullsize), but shows properly on Android and iPhone devices. This behavior affects all people in the room, not only my user.

When the picture is downloaded, it does open correctly in Windows (but not in apps).

View source content :

![image](https://user-images.githubusercontent.com/29391/129285930-70959423-933f-46d6-bc1c-3fe048e518a1.png)

### What did you expect?

Picture to be shown in Desktop and/or Web app.

### Operating system

Windows 10 21H1 with HEIF Image Extension installed (from Windows Store)

### Browser information

All latest browsers (Google Chrome Version 93.0.4577.42 ; Firefox 90+)

### URL for webapp

https://app.element.io/

**Comment by aaronraimist** [comment] 2021-08-13 03:06
Duplicate of #9143

Your browser would need to support this, and none do https://caniuse.com/heif.

**Closed by aaronraimist** 2021-08-13 03:06 UTC
Labels: T-Defect
