### ISSUE TITLE
Honour keyshare requests from people you sent messages to.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7427] opened 2018-09-30 16:32 UTC
We apparently request keyshares from sending devices (as well as ourselves), but the sender ignores them like this:

```
2018-08-31T14:52:31.714Z I m.room_key_request from @Amandine:matrix.org:ZNPRXEQNQD for !teBWTcboSifjyWqxfY:matrix.org / f7mPJ4rZe3p8fuBpaOZL/SP1e6YQfXYtLlgP46mh2mU (id m1535727143583.162)
2018-08-31T14:52:31.714Z I Ignoring room key request from other user for now
```

If we actually upheld them, it'd work around a bunch of UISIs.  If the sender can work out whether it's safely allowed to honour the req, it should.

**Comment by turt2live** [comment] 2022-06-14 05:23
I believe the behaviour here has dramatically changed, and is pre-cross-signing.

Considering a duplicate of https://github.com/vector-im/element-web/issues/15160

**Closed by turt2live** 2022-06-14 05:23 UTC
Labels: P1, A-E2EE, T-Enhancement
