### ISSUE TITLE
Error inviting a user into a room

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-web#21748] opened 2022-04-12 10:17 UTC
### Steps to reproduce

1. Created a new room
2. Added some users (works)
3. Adding the next user stoped working (Error message: You do not have permission to invite people to this room.)

#### What did you expect?
User to be added/invited to the room

#### What happened instead?
Error msg:  You do not have permission to invite people to this room.

from the debug logs the relevant lines seems to be:
```
2022-04-12T10:07:05.503Z I Inviting @a_specific_user:one.ems.host
2022-04-12T10:07:05.655Z E Profile lookup over federation is disabled on this homeserver
M_FORBIDDEN: Profile lookup over federation is disabled on this homeserver
    at S (vector://vector/webapp/bundles/1324aa54203c1fcdfc73/vendors~init.js:2:806154)
    at vector://vector/webapp/bundles/1324aa54203c1fcdfc73/vendors~init.js:2:805557
    at Object.callback (vector://vector/webapp/bundles/1324aa54203c1fcdfc73/vendors~init.js:2:805120)
    at vector://vector/webapp/bundles/1324aa54203c1fcdfc73/vendors~init.js:2:11207
    at XMLHttpRequest.i.onreadystatechange (vector://vector/webapp/bundles/1324aa54203c1fcdfc73/vendors~init.js:2:11231)
2022-04-12T10:07:05.656Z I Sharing history with []
2022-04-12T10:07:05.656Z I downloadKeys: already have all necessary keys
2022-04-12T10:07:05.656Z I sendSharedHistoryInboundSessions to users []
2022-04-12T10:07:05.659Z I Could not find /%\(roomName\)s/g in Konnte Benutzer nicht in den Raum einladen:
2022-04-12T10:07:05.661Z I Starting load of AsyncWrapper for modal
2022-04-12T10:07:05.666Z I shared-history sessions []
2022-04-12T10:07:09.354Z I Starting load of AsyncWrapper for modal
2022-04-12T10:07:09.369Z I Returning cached capabilities
2022-04-12T10:07:13.144Z I Starting load of AsyncWrapper for modal
2022-04-12T10:07:16.599Z I Sending bug report.
```

### Operating system

macOS

### Application version

Version von Element: 1.10.8 Version von Olm: 3.2.8

### How did you install the app?

homebrew

### Homeserver

https://element.ems.host

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-04-12 10:20
Duplicate of https://github.com/vector-im/element-web/issues/17269

**Closed by t3chguy** 2022-04-12 10:20 UTC
Labels: T-Defect
