### ISSUE TITLE
Order of reactions is not consistent

### ISSUE THREAD

**Issue by sephii** [vector-im/element-web#21468] opened 2022-03-18 10:57 UTC
### Steps to reproduce

1. Add some reactions on a message, eg. using letter emojis to form a word
2. Check the message on another account
3. Notice the order of reactions is not the same (the order is also different when checking the message on the element Android app and the web app)

#### What did you expect?

The order of reactions should be the same for all users who see the message.

#### What happened instead?

The order seems to be random for reactions having the same count.

### Operating system

Linux

### Browser information

Firefox 98.0

### URL for webapp

1.10.7

### Application version

Element : 1.10.7 Olm : 3.2.8

### Homeserver

Synapse 1.51.0

### Will you send logs?

No

**Comment by gsouquet** [comment] 2022-03-18 14:55
Duplicate of https://github.com/vector-im/element-web/issues/9698

**Closed by gsouquet** 2022-03-18 14:55 UTC
Labels: T-Defect
