### ISSUE TITLE
Command list doesn't fit on smaller screens

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#15561] opened 2020-10-26 16:57 UTC
![image](https://user-images.githubusercontent.com/26059643/97202987-38d18100-17ac-11eb-82fc-392a7b20bdb5.png)

**Comment by t3chguy** [comment] 2020-10-26 16:58
Duplicate of https://github.com/vector-im/element-web/issues/5138

**Closed by t3chguy** 2020-10-26 16:58 UTC
Labels: bug, ui/ux
