### ISSUE TITLE
Person / direct-chat missing / disappears from "People" group in "home" space

### ISSUE THREAD

**Issue by barathrm** [vector-im/element-web#20440] opened 2022-01-08 10:53 UTC
### Steps to reproduce

Not sure how to reproduce it, I've noticed it happen sometimes. Maybe when I've gotten a notification from them on a mobile client and then want to read it in element before having read it on the mobile client?

#### What did you expect?

I expected this person to show up in the "People" category in my home space.

#### What happened instead?

The person / direct-chat was missing. I opened and collapsed the category without them showing up. *Searching* for them made them pop up in the people category correctly.

### Operating system

opensuse tumbleweed

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://packages.riot.im/debian

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-01-09 07:03
I think sending logs could be helpful in this case, you can do so by typing `/rageshake` into the composer, hitting enter and filling in the dialog

**Comment by turt2live** [comment] 2022-06-14 04:54
Duplicate of https://github.com/vector-im/element-web/issues/22030

**Closed by turt2live** 2022-06-14 04:54 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-Room-List, A-Spaces, A-DMs, O-Uncommon
