### ISSUE TITLE
Layout issue in secondary column at minimum width 

### ISSUE THREAD

**Issue by puenka** [vector-im/element-web#19241] opened 2021-09-30 21:14 UTC
### Steps to reproduce

The secondary column has a layout issue when the width is minimized. It seems like the background bubble of the compass shifts downwards a bit, as you can see in the screenshot. Also, just having "..." instead of people and rooms is quite useless, I suggest replacing those with pictograms in the smallest width setting.
![min_width](https://user-images.githubusercontent.com/2266341/135530743-99a21875-7071-4a28-b482-d6d19960d266.png)

Here is the same view with the width set to the next largest setting at the lower end of the smoothly scalable interval.
![small_width](https://user-images.githubusercontent.com/2266341/135530750-954d0b0c-3219-4671-bb91-b9751babffa9.png)

### What did you expect?
That the layout looks neat.

### What happened?
It looks broken.

### Operating system

Ubuntu 20.04

### Application version

Element version: 1.9.0 Olm version: 3.2.3

### How did you install the app?

Flatpak

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment] 2021-10-01 04:19
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/17068

**Closed by SimonBrandner** 2021-10-01 04:19 UTC
Labels: T-Defect
