### ISSUE TITLE
Microphone auto adjust settings wont disable

### ISSUE THREAD

**Issue by tonytonyistony** [vector-im/element-web#24353] opened 2023-01-28 00:07 UTC
### Steps to reproduce

1. Go to 'All Settings > Voice & Video'
2. Toggle off 'Automatically adjust the microphone volume'
3. Click X to close menu.
4. Start a Jitsi voice call
5. Open your systems sound settings
6. Makes noises and watch the gain controls move

#### What did you expect?
Turning off auto adjust mic makes it so gain settings dont adjust automatically.

#### What happened instead?
The mic still auto adjusts while talking

### Operating system

Pop!_OS 22.04 LTS

### Application version

1.11.17

### How did you install the app?

Pop Shop

### Homeserver

1.75.0

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2023-01-28 08:10
Duplicate of

**Closed by SimonBrandner** 2023-01-28 08:10 UTC
Labels: T-Defect

**Comment by t3chguy** [comment] 2023-01-30 10:55
@SimonBrandner duplicate of what?

**Comment by t3chguy** [comment] 2023-01-30 10:56
Duplicate of https://github.com/vector-im/element-web/issues/24355
