### ISSUE TITLE
"Something went wrong" when trying to join room

### ISSUE THREAD

**Issue by schildbach** [vector-im/element-web#23498] opened 2022-10-15 14:24 UTC
### Steps to reproduce

From the home of a space, I tried to join a room. Soon, the "Something went wrong" dialog appeared. I will attach a log.

Space: https://matrix.to/#/#solokeys-space:matrix.org
Room I tried to join: "SoloKeys Development"

#### What did you expect?
Successful room join

#### What happened instead?
"Something went wrong"

### Operating system

Ubuntu 22.04.1

### Application version

im.riot.Riot 1.11.10

### How did you install the app?

flatpak install flathub im.riot.Riot

### Homeserver

Synapse 1.68.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-10-17 07:51
Duplicate of https://github.com/vector-im/element-web/issues/22752

**Closed by t3chguy** 2022-10-17 07:51 UTC
Labels: T-Defect
