### ISSUE TITLE
Element freezes/stops rendering when doing anything that requires the file picker / file chooser

### ISSUE THREAD

**Issue by barathrm** [vector-im/element-web#20671] opened 2022-01-21 15:11 UTC
### Steps to reproduce

Download any file. Trying to download the debug logs also triggers it.

#### What did you expect?

I'd expect the file picker to open to allow me to select a file or directory.

#### What happened instead?

Element freezes, or at least stops rendering.

I can't upload logs because the file picker doesn't work.

### Operating system

openSUSE Tumbleweed

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://github.com/taw00/element-rpm

### Will you send logs?

No

**Comment by HarHarLinks** [comment] 2022-01-21 16:17
maybe related #18268, though file picker works for me

**Comment by dbkr** [comment] 2022-01-21 17:26
I suspect the logs may not be useful (although possibly), but can you clarify how this prevents you sending logs? You should just be able to paste the URL of this issue into the box and hit the send button?

Anyone else getting (or not getting) this issue - are you using the same RPM package?

**Comment by barathrm** [comment] 2022-01-21 21:12
I updated/switched to the openSUSE element packages that are (apparently!) now provided by the official openSUSE repositories and I can't reproduce the issue anymore, so I guess it's fixed and potential distro-dependent.

**Comment by aaronraimist** [comment] 2022-01-21 21:26
Closing since you can't reproduce anymore. If you experience the issue again then we can reopen.

**Closed by aaronraimist** 2022-01-21 21:26 UTC
Labels: T-Defect, Z-Platform-Specific, S-Major, O-Occasional
