### ISSUE TITLE
Typing :+ does not suggest the thumbsup emoji any more

### ISSUE THREAD

**Issue by hpdeifel** [vector-im/element-web#14569] opened 2020-07-17 07:31 UTC
### Description

Typing `:+` does not suggest the thumbsup emoji any more, it did before updating from Riot to Element.

This feature is absolutely necessary to spread some positivity into this world, and be efficient about it!

### Version information

- **Platform**: Desktop, flatpak

For the desktop app:

- **OS**: Fedora
- **Version**: Element version: 1.7.1

**Comment by hpdeifel** [comment] 2020-07-17 07:40
Weird, it works after restarting Element. I'll keep testing if it breaks again. Otherwise this might have been a glitch in the matrix

**Comment by t3chguy** [comment] 2020-07-17 08:14
I've experienced this too, it is very strange. 99% of the time works though

**Comment by MadLittleMods** [comment] 2021-10-05 21:34
The only time I can reproduce this now is when you fully type out `:+1:` and the autocomplete sorting changes, see https://github.com/vector-im/element-web/issues/19302

![](https://user-images.githubusercontent.com/558581/136105818-5017bfe3-26b5-4f35-a840-2864d668976a.png)

**Comment by SimonBrandner** [comment] 2021-10-06 04:16
I think we can close this since the way this works has changed and the exact issue doesn't seem to be reproducible

**Closed by SimonBrandner** 2021-10-06 04:16 UTC
Labels: T-Defect, A-Composer, A-Emoji
