### ISSUE TITLE
Search UI doesn't support usecase of examining multiple results very well

### ISSUE THREAD

**Issue by makoConstruct** [vector-im/element-web#25658] opened 2023-06-23 19:03 UTC
### Your use case

I'd like to be able to run a search, then click the first result that seems interesting, read the conversation around it, then go back, examine the second result that seems interesting, and so on, until I've looked at all interesting results. This is a pretty common workflow.

This currently doesn't really work, or, the UX is terminally awkward, due to two issues:
- search queries take multiple seconds to resolve, and often fail (timeout), so repeatedly searching the same thing is very painful. I'd expect that this is hard to to fix, focus on the other issue.
- because **the search result page doesn't get a history pushState url**, you do end up having to repeatedly run the same search query each time you return to the search results. You can't just press back, as pressing back takes you to the page you were on before running the search. This may be a bug. Search result pages should probably have urls instead of just retaining the URL of the page you were on before doing the search.

You'll also need to make sure you retain the search query results so that when the user goes back, it's fast, and make sure it returns them to the same scroll offset. Then it would be perfect :+1: 

### Have you considered any alternatives?

You display the immediate prior and next message in search results. This is not enough info, of course, there is generally a lot more to a conversation than the immediate prev and next.

**Comment by t3chguy** [comment] 2023-06-26 09:12
Duplicate of https://github.com/vector-im/element-web/issues/17918

**Closed by t3chguy** 2023-06-26 09:12 UTC
Labels: T-Enhancement
