### ISSUE TITLE
left/right aligned chats (me: right-aligned, rest: left-aligned)

### ISSUE THREAD

**Issue by romeokienzler** [vector-im/element-web#17183] opened 2021-05-06 13:40 UTC
#### Is your suggestion related to a problem? Please describe.
no

#### Describe the solution you'd like.
Show text from other persons left-aligned and my text right-aligned in chats. 

#### Describe alternatives you've considered.
no

#### Additional context
It is a common practice in many messengers like WhatsApp, Signal, ... to show received text left-aligned and sent text right-aligned to easily distinguish between what you have written and what others have written.

**Comment by SimonBrandner** [comment] 2021-05-06 13:43
Duplicate of [#4635](https://github.com/vector-im/element-web/issues/4635)

**Comment by t3chguy** [comment] 2021-05-06 13:44
You beat me to it :D

**Closed by SimonBrandner** 2021-05-06 13:43 UTC
Labels: T-Enhancement
