### ISSUE TITLE
Confusing error ("you do not have permissions to invite") when inviting to unfederated room

### ISSUE THREAD

**Issue by clokep** [vector-im/element-web#22189] opened 2022-05-13 18:36 UTC
### Steps to reproduce

1. Create a room with federation turned off.
2. Attempt to invite someone from a different domain.
3. See a "you do not have permissions to invite" message.

#### What did you expect?
A better error message: "You cannot invite users from other domains" (or something worded better than that).

#### What happened instead?
The message implies that there's a permissions problem that can be fixed, but this is not possible.

### Operating system

macOS

### Browser information

Firefox 101.0b6

### URL for webapp

https://chat.mozilla.org

### Application version

Unsure

### Homeserver

mozilla.org

### Will you send logs?

No

**Comment by clokep** [comment] 2022-05-13 18:37
CC @sancus

**Comment by turt2live** [comment] 2022-05-13 18:53
![image](https://user-images.githubusercontent.com/1190097/168351845-86b2a852-f48f-4015-941d-0db99291f2c8.png)

The error comes from element in translating the `M_FORBIDDEN` error code.

**Comment by turt2live** [comment] 2022-05-13 18:53
related: https://github.com/vector-im/element-web/issues/22102

**Comment by t3chguy** [comment] 2022-05-13 19:24
Duplicate of https://github.com/vector-im/element-web/issues/20395

**Closed by t3chguy** 2022-05-13 19:24 UTC
Labels: T-Defect
