### ISSUE TITLE
Brendan getting UTD from me

### ISSUE THREAD

**Issue by deniseal** [vector-im/element-web#20466] opened 2022-01-11 09:57 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### Operating system

macOS

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-07-11 09:22
Duplicate of https://github.com/vector-im/element-meta/issues/245

**Closed by t3chguy** 2023-07-11 09:22 UTC
Labels: T-Defect, S-Major, A-E2EE, Z-UISI, O-Uncommon
