### ISSUE TITLE
Don't know when invited to a room when filtering

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#15211] opened 2020-09-16 13:25 UTC
I'm assuming we hide invites as they're a distraction while filtering, but the knock on effect is sometimes I'll be filtering for some minutes, and then will have no idea I've been invited to another room. We might solve this 'for free' when we implement a notification centre, but in lieu of that we should also consider exposing invites somehow while filters are active.

**Comment by turt2live** [comment] 2020-09-16 16:32
duplicate of https://github.com/vector-im/element-web/issues/15088

**Closed by turt2live** 2020-09-16 16:32 UTC
Labels: bug, minor, p2, type:invite, type:new-room-list, type:roomlist
