### ISSUE TITLE
"Unverified login" toaster doesn't disappear immediately after reviewing new login

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13181] opened 2020-04-15 18:59 UTC
After self-signing new login toaster for "unverified login, was this you?" hung around for 5-10s before spontaneously disappearing

**Comment by jryans** [comment] 2020-04-16 09:49
I think the issue is that the toaster waits around for remote echo effectively. We'd need to add some form of local echo / optimistically clear it after completing verification.

**Comment by kittykat** [comment] 2021-12-09 17:53
We cannot reproduce this and there have been many changes to the area so I will close this issue for now. Please reopen if you continue to experience the problem.

**Closed by kittykat** 2021-12-09 17:53 UTC
Labels: T-Defect, A-E2EE-Cross-Signing, X-Needs-Community-Testing
