### ISSUE TITLE
Add a setting for the voice message button to be hidden

### ISSUE THREAD

**Issue by sinistergamer3333** [vector-im/element-web#18579] opened 2021-08-16 22:45 UTC
#### What would you like to do?
Title.
#### Why would you like to it?
It's in the same place the stickers button used to be.
#### How would you like to achieve it?
Either allow it to be hidden or allow it to be moved.

**Comment by turt2live** [comment] 2021-08-16 22:51
Duplicate of https://github.com/vector-im/element-web/issues/18464

**Closed by turt2live** 2021-08-16 22:51 UTC
Labels: T-Enhancement
