### ISSUE TITLE
spoiler is shown at notifcation

### ISSUE THREAD

**Issue by Lukas1818** [vector-im/element-web#20531] opened 2022-01-13 14:25 UTC
### Steps to reproduce

* let someone send a spoiler in a room, where you get notifications
* look at the notification

the notification:
![image](https://user-images.githubusercontent.com/44570204/149347670-b62f22e0-3c85-425b-a467-77408b93f4e9.png)

in element:
![image](https://user-images.githubusercontent.com/44570204/149347840-80f3339f-7343-4e93-87ae-67cb759ea1da.png)

#### What did you expect?
Show a notification that a spoiler was send, without the message content.
#### What happened instead?
A message with the content of the spoiler is shown.

### Operating system

Manjaro

### Application version

Element version: 1.9.8

### How did you install the app?

https://archlinux.org/packages/community/x86_64/element-desktop/

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-01-13 14:55
Duplicate of https://github.com/vector-im/element-web/issues/12034

**Closed by t3chguy** 2022-01-13 14:55 UTC
Labels: T-Defect
