### ISSUE TITLE
Substring search doesn't work in encrypted rooms.

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#14018] opened 2020-06-13 21:37 UTC
While searching `Marvell` in encrypted room works fine, `Marvel` gives zero results.

**Comment by t3chguy** [comment] 2020-06-13 21:41
Is this an encrypted or unencrypted room? If unencrypted then its server-side search and depends on the implementation your server is using.

**Comment by 532910** [comment] 2020-06-13 21:43
encrypted

**Comment by 532910** [comment] 2020-06-13 21:43
For unencrypted it works fine.

**Comment by t3chguy** [comment] 2023-04-25 14:52
Duplicate of https://github.com/vector-im/element-meta/issues/1479

**Closed by t3chguy** 2023-04-25 14:52 UTC
Labels: T-Defect, S-Minor, A-Indexing, O-Uncommon
