### ISSUE TITLE
Your UI wastes a lot of space.

### ISSUE THREAD

**Issue by ewtoombs** [vector-im/element-web#17989] opened 2021-07-14 08:14 UTC
Your UI wastes a lot of space, making it hard to read when the browser window's width is small.

Here's what I did to fix this:
https://greasyfork.org/en/scripts/429321-element-io-width/code

**Comment by t3chguy** [comment] 2021-07-14 08:18
Duplicate of https://github.com/vector-im/element-web/issues/6488****

**Closed by t3chguy** 2021-07-14 08:18 UTC
Labels: T-Defect

**Comment by t3chguy** [comment] 2021-07-14 08:19
```
.mx_LeftPanel .mx_LeftPanel_GroupFilterPanelContainer {
    display: none;
  }
```

this is completely redundant, there's a setting to hide that panel.

![image](https://user-images.githubusercontent.com/2403652/125588547-0da186a3-674d-43bf-80dc-d2093d8340d5.png)

**Comment by ewtoombs** [comment] 2021-07-14 08:20
If there is, it is very well hidden. Where is it?
