### ISSUE TITLE
Lightbox/image-viewer can't always be dismissed by clicking outside the shown image image

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-web#16254] opened 2021-01-23 20:21 UTC
### Description

I had a particular image where dismissing it by clicking outside the image border doesn't work as expected.
The red areas *should* dismiss the image but this doesn't work. Left-and right of the image dismissing it works, at the very top and bottom it works as well.

![image](https://user-images.githubusercontent.com/105185/105613035-3ccb6a00-5dc0-11eb-8ce8-bf92d4528212.png)

original image: 
![IMG_20210123_203406](https://user-images.githubusercontent.com/105185/105613119-d266f980-5dc0-11eb-95e8-2af04898bce1.jpg)

### Steps to reproduce

- Send the above image to an encrypted (necessary?) room
- open it in the lightbox image viewer
- try to exit the image viewer by clicking above or below the image
For the web app:

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.7.17

**Comment by SimonBrandner** [comment] 2021-01-24 06:53
@Bubu  This is an issue with the image view. I've fixed it in [this](https://github.com/matrix-org/matrix-react-sdk/pull/5521) PR, it's waiting for review

**Comment by Bubu** [comment] 2021-01-24 15:32
This also happens the other way around with portrait sized images.

**Comment by SimonBrandner** [comment] 2021-01-24 15:36
@Bubu My PR should fix that as well

**Comment by t3chguy** [comment] 2021-01-25 10:30
Duplicate of https://github.com/vector-im/element-web/issues/12933

**Closed by t3chguy** 2021-01-25 10:30 UTC
Labels: bug
