### ISSUE TITLE
MOD audio file playback broken

### ISSUE THREAD

**Issue by jae1911** [vector-im/element-web#24395] opened 2023-02-01 13:27 UTC
### Steps to reproduce

1. Grab a MOD file from AMP or ModArchive
2. Send it in a room
3. Observe the "Error downloading audio"

![image](https://user-images.githubusercontent.com/76598503/216055580-fb40f9df-8839-43e4-9a7d-70d418f93eb1.png)

#### What did you expect?

The MOD file being able to be played by users.

#### What happened instead?

An error "Error downloading audio" shows up.

### Operating system

ArchLinux

### Application version

Element 1.11.20; Olm 3.2.12

### How did you install the app?

https://archlinux.org/packages/community/x86_64/element-desktop/

### Homeserver

Synapse 1.76.0

### Will you send logs?

Yes

**Comment by jae1911** [comment] 2023-02-01 13:30
Additional notes:  
Years ago, MODs started working but got broken again later.  
Also, it seems they are correctly detected as audio files but cannot be decoded by whatever player is used (even though any player/tool like VLC, MPV or ffmpeg can use them).

**Comment by t3chguy** [comment] 2023-02-01 13:47
> Also, it seems they are correctly detected as audio files

Just means it has an `audio/*` mime type

> cannot be decoded by whatever player is used

The one built into chrome - https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs MOD is not supported

**Comment by t3chguy** [comment] 2023-02-01 13:47
Duplicate of https://github.com/vector-im/element-web/issues/11794

**Closed by t3chguy** 2023-02-01 13:47 UTC
Labels: T-Defect
