### ISSUE TITLE
Desktop App update breaks taskbar settings in Windows

### ISSUE THREAD

**Issue by adam248** [vector-im/element-web#24347] opened 2023-01-27 02:01 UTC
**Describe the bug**
Every time the app updates on Windows it creates a new program and breaks the taskbar icon settings

**To Reproduce**
1. Update the app from within the app when asked to update.

**Expected behavior**
The settings of which icons appear on the taskbar in Windows should be remembered.

**Screenshots**
![image](https://user-images.githubusercontent.com/85082674/214994277-ec9788e9-7423-42a7-a0ea-487e30022b8b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by t3chguy** [comment] 2023-02-01 11:15
Duplicate of https://github.com/vector-im/element-web/issues/10131

**Closed by t3chguy** 2023-02-01 11:15 UTC
Labels: T-Defect, Z-Platform-Specific, S-Minor, O-Frequent
