### ISSUE TITLE
Auto-completing room alias remove half-typed alias from the message bar

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#11786] opened 2020-01-06 20:02 UTC
### Description

So I typed a message "Yeah, I've noticed that as well. I'd ask in #riot-an" then two suggestions came up. I wanted the first, so I hit tab. Upon the first selection being highlighted, `#riot-an` disappeared from the message bar:

![image](https://user-images.githubusercontent.com/1342360/71844990-5f93bf00-3095-11ea-8a5e-2d47de86c5fa.png)

Hitting tab again highlighted the second choice, which did complete to a pill:

![image](https://user-images.githubusercontent.com/1342360/71845011-6ae6ea80-3095-11ea-90ca-ff361cd781ec.png)

Hitting tab over and over switched between `#riot-an`, <nothing> and the pill in the second screenshot.

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox v73.0a1
- **OS**: Debian
- **URL**: riot.im/develop

**Comment by jaywink** [comment] 2020-03-13 10:32
I've also hit this, I think. When I tab complete an alias, the half typed text just disappears.

Additionally it doesn't seem to be possible to autocomplete in any way currently and also continue writing since pressing enter sends the message.

![Peek 2020-03-13 12-31](https://user-images.githubusercontent.com/1174866/76613359-a6cf7d80-6526-11ea-80e5-ee01bac5a197.gif)

**Comment by jaywink** [comment] 2020-03-13 10:34
Hmm was just going to report a version and it seems matrix-react-sdk is marked as `<local>` which could be the cause for me. Riot desktop 1.5.3, Ubuntu 19.10.

Not entirely sure why my Riot would use a local SDK.

**Comment by SimonBrandner** [comment] 2021-06-26 16:54
@anoadragon453 and @jaywink, are you still experiencing this? I don't think I am able to repro

**Comment by jaywink** [comment] 2021-06-28 12:35
@SimonBrandner I've not seen this for a while :+1:

**Comment by SimonBrandner** [comment] 2021-06-28 12:36
Ok, let's close this then. Shout if you see this again

**Closed by SimonBrandner** 2021-06-28 12:36 UTC
Labels: A-Autocomplete, A-Composer, P1, T-Defect, X-Needs-Info
