### ISSUE TITLE
Timestamp misplaced on a reply to an action

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16741] opened 2021-03-22 15:35 UTC
<img width="677" alt="Screenshot 2021-03-22 at 15 34 46" src="https://user-images.githubusercontent.com/1294269/112016008-3a696000-8b24-11eb-80e3-ad7bf388a59a.png">

**Comment by aaronraimist** [comment] 2021-03-27 05:13
Duplicate of #14166

**Closed by aaronraimist** 2021-03-27 05:13 UTC
Labels: A-Timeline, T-Defect
