### ISSUE TITLE
/shrug does not support markdown

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#26365] opened 2023-10-13 13:43 UTC
### Steps to reproduce

1. Type a message containing markdown syntax and prepended with `/shrug`, such as `/shrug *hello*`
2. Observe that the message is not interpreted as markdown, but plain text

#### What did you expect?

For me to shrug and then have formatted messages.

#### What happened instead?

Sadness.

### Operating system

NixOS Linux

### Application version

Element version: 1.11.45 Olm version: 3.2.14

### How did you install the app?

From https://github.com/NixOS/nixpkgs/

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-10-13 13:44
Duplicate of https://github.com/vector-im/element-web/issues/9794

**Closed by t3chguy** 2023-10-13 13:44 UTC
Labels: T-Defect
