### ISSUE TITLE
Cannot answer video call without a webcam

### ISSUE THREAD

**Issue by cheryllium** [vector-im/element-web#15285] opened 2020-09-25 20:16 UTC
### Description

It's not possible to answer a video call unless you also have a webcam set up, making it impossible to start a one-sided video call. You will receive an error "Couldn't start capturing media! Is your microphone set up and does this app have permission?"

This happens for both video calls and screenshare calls.

### Steps to reproduce

- Do not have a webcam set up 
- Have another user start a video call with you in Direct Message
- Try to answer the call

Describe how what happens differs from what you expected.

Logs being sent: yes

I expect to be able to answer the call and see the other person's video, and if I don't have my webcam set up then my own video should just be disabled. 

The following error message is displayed instead of being able to answer the call: 

![image](https://user-images.githubusercontent.com/5027241/94311661-9ffbdb80-ff49-11ea-913a-b1b8b8d34986.png)

### Version information

- **Platform**: Desktop
- **OS**: Windows 10
- **Version**: 1.7.7 

(The above are for the person who is trying to answer the call. It does not matter where the call is being placed from.)

**Comment by t3chguy** [comment] 2020-09-28 09:21
Duplicate of https://github.com/vector-im/element-web/issues/188

**Closed by t3chguy** 2020-09-28 09:21 UTC
Labels: bug

**Comment by NotZoeyDev** [comment] 2020-10-05 12:57
I have a webcam and Element is unable to recognize it, it works fine on my macbook but no dice on Chrome or the desktop app on Windows 10. 

This is extremely annoying that there's no fix yet available for this issue.
