### ISSUE TITLE
Link previews can occupy the entire timeline if window width is small

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#3903] opened 2017-05-12 09:47 UTC
![image](https://cloud.githubusercontent.com/assets/1922197/26002579/00b5c9f6-3728-11e7-8c0c-c00910e2cbc0.png)

**Comment by uhoreg** [comment] 2017-05-16 01:36
This could be addressed by the same CSS that I proposed at https://github.com/vector-im/riot-web/issues/2894#issuecomment-293391782

**Comment by MadLittleMods** [comment] 2021-09-02 05:56
Duplicate of https://github.com/vector-im/element-web/issues/7897

**Closed by MadLittleMods** 2021-09-02 05:56 UTC
Labels: T-Defect, P2, A-URL-Previews
