### ISSUE TITLE
call hangups are treated as unread messages

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#15393] opened 2020-10-06 17:57 UTC

**Comment by SimonBrandner** [comment] 2021-06-23 09:03
This is a problem for _all_ `m.call` events

**Comment by t3chguy** [comment] 2021-06-23 09:06
Hmm, https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/Unread.ts#L40-L41 answer/hangup shouldn't

**Comment by SimonBrandner** [comment] 2021-06-23 09:08
The count displayed in the room-tile actually depends on the js-sdk's `Room::getUnreadNotificationCount()`

**Comment by SimonBrandner** [comment] 2021-06-23 09:09
https://github.com/SimonBrandner/matrix-react-sdk//blob/develop/src/stores/notifications/RoomNotificationState.ts#L79

**Comment by SimonBrandner** [comment] 2021-06-25 07:33
Note: what Dave probably meant here is: "call hangups are treated as _notifications_", hence the confusion above ^

**Comment by novocaine** [comment] 2021-08-25 14:34
Downgrading to S-minor as this does not significantly degrade major functionality; it's just a bit annoying

**Comment by turt2live** [comment] 2021-09-07 20:15
PR reverted; reopening

**Comment by SimonBrandner** [comment] 2021-12-05 07:38
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/7941

**Closed by SimonBrandner** 2021-12-05 07:38 UTC
Labels: T-Defect, S-Minor, A-VoIP, O-Frequent
