### ISSUE TITLE
System font isn't honored in the Explore rooms filter textbox

### ISSUE THREAD

**Issue by intelfx** [vector-im/element-web#17791] opened 2021-06-26 18:18 UTC
### Description

The filter textbox in the Explore rooms dialog does not honor system font, if one is configured in Element.

### Steps to reproduce

- configure Element to use a specific system font
- go to Explore rooms
- observe textbox being hardcoded to use Inter font

![Снимок экрана от 2021-06-26 21-14-42](https://user-images.githubusercontent.com/1158172/123522093-d4ace700-d6c3-11eb-9c27-cb12591474d4.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 91 Nightly
- **OS**: Linux, Windows
- **URL**: develop.element.io

**Comment by intelfx** [comment] 2021-06-26 18:19
Tangential: this is not the first place that is hardcoded to use Inter font, disregarding the system font configuration, and not the last. Would it be possible to somehow mass-fix these or is it required to report them one by one?

**Comment by SimonBrandner** [comment] 2021-06-26 18:51
Duplicate of https://github.com/vector-im/element-web/issues/14163

Also, I am attempting a mass-fix at https://github.com/matrix-org/matrix-react-sdk/pull/6272. Feel free to try out the live-preview and let me know if I've missed some places

**Closed by SimonBrandner** 2021-06-26 18:51 UTC
Labels: T-Defect

**Comment by intelfx** [comment] 2021-06-26 18:54
@SimonBrandner sorry, I somehow missed that report.
What is a live preview?

**Comment by SimonBrandner** [comment] 2021-06-26 18:59
> @SimonBrandner sorry, I somehow missed that report.
> What is a live preview?

No worries :)

If you open that PR and scroll to the bottom you can open a live preview of that PR - the code deployed to Netlify, so that you can try it out:

![Screenshot_20210626_205903](https://user-images.githubusercontent.com/25768714/123523010-59e2cc80-d6c1-11eb-9a2d-4cef8d1287b4.png)

**Comment by SimonBrandner** [comment] 2021-06-26 19:00
PS: They take a while to load the first time
