### ISSUE TITLE
Collapse long messages

### ISSUE THREAD

**Issue by penn5** [vector-im/element-web#17582] opened 2021-06-07 13:12 UTC
#### Is your suggestion related to a problem? Please describe.
https://app.element.io/#/room/!AUyclzjhyJPgZJeNkW:matrix.org/$ZV9ykyJ2kNrrtsh2ln4c5SLyiXFrcwM_fSTYHCcycd8?via=matrix.org&via=fairydust.space&via=t2bot.io - this message takes a very long time to scroll past

#### Describe the solution you'd like.
When a message takes more than half the screen height, collapse with a button to view more.

#### Describe alternatives you've considered.
Leave it be?

#### Additional context
![image](https://user-images.githubusercontent.com/5600962/121022535-529f6180-c79a-11eb-816a-7079efd3ef0d.png)

**Comment by SimonBrandner** [comment] 2021-06-07 14:43
Duplicate of [#4388](https://github.com/vector-im/element-web/issues/4388)

**Closed by SimonBrandner** 2021-06-07 14:43 UTC
Labels: T-Enhancement
