### ISSUE TITLE
When opening a thread, summary gets replaced with wrong message and count gets incremented

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21923] opened 2022-04-25 22:59 UTC
### Steps to reproduce

Unclear if this is a consistent repro, but I'm hitting this with nearly all threads now:

1. Have some people start a thread, but don't participate in it or open it
2. Observe the summary's latest message and message count
3. Open the thread

#### What did you expect?

For the latest message and message count to remain accurate after opening the thread.

#### What happened instead?

The count gets incremented by 1, and the latest message gets substituted with a random message from the thread.

### Operating system

NixOS unstable

### Browser information

Firefox 99.0

### URL for webapp

develop.element.io

### Application version

Element version: 2ffb3a11808c-react-f85e178fc18b-js-ac08e5241079 Olm version: 3.2.8

### Homeserver

Synapse 1.57.0

### Will you send logs?

No

**Comment by novocaine** [comment] 2022-04-26 08:22
Is this a duplicate of https://github.com/vector-im/element-web/issues/21770 ?

**Comment by t3chguy** [comment] 2022-04-26 08:26
Possibly the same root cause but I don't think a duplicate issue manifestation

**Comment by HarHarLinks** [comment] 2022-07-18 20:27
I'm seeing this too e.g. i noticed on this thread https://matrix.to/#/!CMjQWAjoxImKwLBMzX:matrix.org/$WtlhZv0k35IFA56OR6Au1c5fg4_RHzuGtSO6gIzN9qw?via=matrix.org&via=element.io&via=one.ems.host

I first thought it might be caused by the edit being technically after the last message, but that is not the case.

Element Nightly version: 2022071801
Olm version: 3.2.8

**Comment by gsouquet** [comment] 2022-11-15 10:47
I believe this would have been addressed by https://github.com/matrix-org/matrix-react-sdk/pull/9356, I have not been able to reproduce

**Closed by gsouquet** 2022-11-15 10:47 UTC
Labels: T-Defect, S-Minor, O-Occasional, A-Threads

**Comment by robintown** [comment] 2022-11-15 12:53
Yep, it was!
