### ISSUE TITLE
half typed message in composer bugs with threads

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20306] opened 2021-12-21 16:51 UTC
### Steps to reproduce

1. start composing in a thread
2. switch to another room
3. the thread panel from the old room is still visible! but the composer is now empty
4. switch back to the room
5. the message is in both the thread and the main composer

### Outcome

see above

### Operating system

arch

### Application version

Element Nightly version: 2021122001 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by HarHarLinks** [comment] 2021-12-21 16:52
related: pretty much the opposite of #19875 😅

**Comment by HarHarLinks** [comment] 2021-12-21 16:54
apparently on top of this, going back to the room of step 2 shows an outdated view of the thread which is missing your message assuming you sent it after 5.

**Comment by kittykat** [comment] 2021-12-21 17:51
May be a duplicate of #20111

**Closed** 2022-01-12 17:13 UTC
Labels: T-Defect, S-Minor, A-Composer, O-Occasional, A-Threads, Z-Labs
