### ISSUE TITLE
In the bubbles layout, clicking on a cited reply outside the text, opens a matrix.to link

### ISSUE THREAD

**Issue by pioneer** [vector-im/element-web#18363] opened 2021-08-03 14:09 UTC
When clicking on the text itself in a cited reply (see the cursor position on the screenshot), the timeline correctly jumps to the referred message and highlights it.
![cursor_in](https://user-images.githubusercontent.com/200538/128029520-1e586618-ada1-42eb-9f31-79769e72dbd8.png)

Whereas clicking outside the text (see the second screenshot and the cursor position there), opens the corresponding matrix.to link in the default system browser.
![cursor_out](https://user-images.githubusercontent.com/200538/128029689-c56ff923-2484-4b2f-84cf-92b512067f23.png)

**Expected behaviour:** regardless of the place clicked, I think the timeline should scroll back to the referred message.

**Comment by SimonBrandner** [comment] 2021-08-03 14:11
Duplicate of https://github.com/vector-im/element-web/issues/18327

**Closed by SimonBrandner** 2021-08-03 14:11 UTC
Labels: T-Defect
