### ISSUE TITLE
Right click opens up the options menu

### ISSUE THREAD

**Issue by Adithr123** [vector-im/element-web#20689] opened 2022-01-23 03:18 UTC
#### What would you like to do?
On messages, instead of having to click, being able to right click like discord to open up the menu.

### Have you considered any alternatives?

NA

**Comment by SimonBrandner** [comment] 2022-01-23 07:25
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/16480

**Closed by SimonBrandner** 2022-01-23 07:25 UTC
Labels: T-Enhancement

**Comment by Adithr123** [comment] 2022-01-23 18:57
This isnt a issure

**Comment by Adithr123** [comment] 2022-01-23 18:58
@SimonBrandner This is a feature request.

**Comment by SimonBrandner** [comment] 2022-01-23 20:09
> @SimonBrandner This is a feature request.

Sorry, I know it's not an issue but a feature request, nonetheless it is a duplicate of https://github.com/vector-im/element-web/issues/16480
