### ISSUE TITLE
In video rooms I cannot share screen or windows

### ISSUE THREAD

**Issue by thanasistrisp** [vector-im/element-web#22516] opened 2022-06-10 10:22 UTC
### Steps to reproduce

Only in video rooms (not in simple rooms) I cannot share the screen. It shows a black screen that loads forever:
![image](https://user-images.githubusercontent.com/79643637/173045405-56a58602-51aa-464d-92c8-2ec63d3a599b.png)

#### What did you expect?
To be able to share screen
#### What happened instead?
A black screen

### Operating system

Windows 11

### Application version

Element Nightly: 0.0.1-nightly.2022061001

### How did you install the app?

From element website

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-06-10 11:05
Unrelated to Video rooms

Duplicate of https://github.com/vector-im/element-web/issues/4880

**Closed by t3chguy** 2022-06-10 11:05 UTC
Labels: T-Defect
