### ISSUE TITLE
no audible ring from incoming call since update (windows desktop)

### ISSUE THREAD

**Issue by matrixhalpia** [vector-im/element-web#8872] opened 2019-02-22 05:43 UTC
### Description

Since updating the Windows app, I no longer hear incoming or outgoing calls ringing. The same applies when I use Riot in browser (Chrome on windows) If I am looking at the app, I will see the visible notification for an incoming call. If I am calling someone I will see "active call" Bar, but there is no ringing sound.
### Steps to reproduce

- Select person
- click Phone Icon to call
- Hear nothing until they answer

or

- Receive incoming call
- Hear nothing to audibly alert you the call is incoming
- Miss call and hear about it later "why didn't you answer?"

The previous version made a ringing sound in either case

Log: sent   

![image](https://user-images.githubusercontent.com/45929938/53221482-643aba80-361e-11e9-9045-bcb4db077af9.png)
The Incoming call notification is accompanied by silence

![image](https://user-images.githubusercontent.com/45929938/53221522-9815e000-361e-11e9-9cd3-98043965a478.png)
The outgoing call is accompanied by silence until you hear the far end answer and speak.
### Version information

- **Platform**: Windows

For the web app:

- **Browser**: Chrome Version 72.0.3626.109 (Official Build) (64-bit
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows 10 Pro
- **Version**: 10.0.0.17134

**Comment by jryans** [comment] 2019-02-22 10:51
Thanks for the report! I am not able to reproduce this at the moment.

The next time you receive a silent call like this, could you please submit debug logs via User menu (top left) -> Settings -> Help & About -> Submit debug logs?

**Comment by julienmeyer** [comment] 2019-03-08 09:52
Same problem here. Works with the browser version but not with the desktop. I sent the debug log.

**Comment by gerroon** [comment] 2019-03-24 21:19
I have the same problem on Debian :(

**Comment by turt2live** [comment] 2019-10-23 02:39
@matrixhalpia @julienmeyer @gerroon are you still having this problem? If you are, please submit debug logs (Settings -> Help -> Submit Debug Logs) so we can take a look.

**Comment by SimonBrandner** [comment] 2021-05-22 17:26
@matrixhalpia, is this still a problem?

**Comment by matrixhalpia** [comment] 2021-05-24 16:14
Hi. I don't know. We switched to slack as this issue was disruptive. 
Should it now be resolved? If so, I will try out the latest version.

Matt Halpin     ***@***.*** ***@***.***>taav.com 
***@***.***>  o: ***@***.***>(510)403-9808 
<tel:+15104039808>  m: <tel:+15104039808>(415)602-0153  
<tel:+14156020153>

------ Original Message ------
From: "Šimon Brandner" ***@***.***>
To: "vector-im/element-web" ***@***.***>
Cc: "matrixhalpia" ***@***.***>; "Mention" 
***@***.***>
Sent: 5/22/2021 10:27:09 AM
Subject: Re: [vector-im/element-web] no audible ring from incoming call 
since update (windows desktop) (#8872)

>
***@***.*** <https://github.com/matrixhalpia>, is this still a

**Comment by SimonBrandner** [comment] 2021-05-24 16:16
The issue is two years old and without a reproduction case, so I was wondering if this wasn't something specific to your situation that might have gotten resolved. Could you please try out a new version, to see what is the current situation?

**Comment by SimonBrandner** [comment] 2021-05-24 16:17
Also, if the issue is still present, please send debug logs

**Comment by SimonBrandner** [comment] 2021-07-22 08:12
I will close this as I can not reproduce this and there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.

**Closed by SimonBrandner** 2021-07-22 08:12 UTC
Labels: A-VoIP, P1, S-Major, T-Defect, X-Cannot-Reproduce, X-Needs-Info
