### ISSUE TITLE
Room invites appear in as spaces in the left left panel

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/element-web#17089] opened 2021-04-28 13:27 UTC
### Description

With Spaces enabled on Element Desktop Nightly 270421 talking to the matrix.org server. 

If I am invited to a room the invite appears in the llp as if it were an invite to a space. 

![Screenshot 2021-04-28 at 14 20 07](https://user-images.githubusercontent.com/451032/116411269-77b0c400-a82d-11eb-9760-c5a914a65644.png)

In this case, the orange background Neil is a test user use inviting me to a room, but it looks as if I am being invited to a space, rather than a regular room invite. 

This happens consistently.

**Comment by SimonBrandner** [comment] 2021-04-28 13:33
I would swear that this is a duplicate of something but I can't find that issue :thinking:

**Comment by t3chguy** [comment] 2021-04-28 14:14
This is fixed on Develop, reporter was using an old Nightly build (and the nightly build this morning with the fix failed)

**Closed by t3chguy** 2021-04-28 14:14 UTC
Labels: A-Spaces, T-Defect
