### ISSUE TITLE
Failed verification prompts the user with "Got it!" making it sound like it succeeded

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13219] opened 2020-04-16 15:31 UTC
When verification fails, or is cancelled, we get a cheery "Got it!" button on the error state.  This is a bit confusing, as "Got it!" sounds pretty positive given the bad news...

**Comment by kittykat** [comment] 2021-12-09 18:25
I'm going to close this issue for now as the UI has changed since it's been filed and we cannot reproduce it. Please open a new issue if you feel that there are improvements to be made.

**Closed by kittykat** 2021-12-09 18:25 UTC
Labels: T-Defect, A-E2EE-Cross-Signing, X-Needs-Community-Testing
