### ISSUE TITLE
Scrolling beyond the bottom of the Room List is very jerky

### ISSUE THREAD

**Issue by emorrp1** [vector-im/element-web#17565] opened 2021-06-04 22:23 UTC
https://user-images.githubusercontent.com/71895/120867461-e1895f80-c589-11eb-9d67-eceba15d60e5.mp4

### Description

When scrolling down to the bottom of the Room List it doesn't stop scrolling as normal, but jerks up and down. This only happens with the Historical section collapsed and the Low priority in "Show less" mode, not after clicking either "Show more" or "Historical".

### Steps to reproduce

- Run fullscreen on a 1680x1050 resolution
- Click "Show less" in all sections
- Collapse Historical and People
- Scroll down beyond the bottom of the Room List

In any other configuration of the Room List, scrolling past the bottom just stops scrolling. **Edit:** It seems it may actually not be to do with scrolling past the bottom, but the fact that it's exactly that point that People is about to replace Favourites at the top:

![image](https://user-images.githubusercontent.com/71895/120868732-958bea00-c58c-11eb-831a-72bd5c7b67da.png)

Log: not sent

### Version information

- **Platform**: desktop ([flatpak](https://flathub.org/apps/details/im.riot.Riot))

For the desktop app:

- **OS**: Debian 10
- **Version**: 1.7.29

**Comment by SimonBrandner** [comment] 2021-06-05 05:28
Duplicate of [#17460](https://github.com/vector-im/element-web/issues/17460)

**Closed by SimonBrandner** 2021-06-05 05:28 UTC
