### ISSUE TITLE
switching HS back to matrix.org in login screen doesn't work

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#16226] opened 2021-01-20 19:10 UTC
![Peek 2021-01-20 19-09](https://user-images.githubusercontent.com/1389908/105223045-2ff60e80-5b53-11eb-93ed-cbb176cfb332.gif)

**Comment by t3chguy** [comment] 2021-01-20 19:12
Duplicate of https://github.com/vector-im/element-web/issues/16139 - should be fixed on develop

**Comment by t3chguy** [comment] 2021-01-20 19:20
vdh says problem isn't fixed on develop

**Comment by SimonBrandner** [comment] 2021-01-20 20:19
@t3chguy I can reproduce this on `develop`. I think #16139 was about something bit different. Maybe [the fix](https://github.com/matrix-org/matrix-react-sdk/pull/5552) caused this?

**Comment by t3chguy** [comment] 2021-01-20 20:21
I've seen this exact bug prior to the fix for #16139 landing so I doubt that

**Comment by SimonBrandner** [comment] 2021-01-20 20:24
@t3chguy Yeah, you're right, reverting the fix didn't help, this is something different

**Comment by 2580ayush2580** [comment] 2021-01-21 14:03
![21](https://user-images.githubusercontent.com/56980422/105359347-5bddc680-5c1d-11eb-8000-e7384953dc55.png)
@t3chguy this Radio button is not taking any Input(URL) for selecting home-server and when empty string passes into validation function it simply returns an error.

In this [PR](https://github.com/matrix-org/matrix-react-sdk/pull/5552), I only added, a condition which is Validation only checks if a home-server is not a matrix.org.

I think we should add a field which passes a default URL which is matrix.org.
I have exactly no idea but if you guide me I would be happy on working this.

**Comment by dangwynne** [comment] 2021-01-21 22:07
Hi, I've submitted a PR for this so that the default config is passed if the default radio button is selected. Problem was that once the custom HS was set that config was always getting passed irregardless of which radio button was selected.

**Closed** 2021-01-22 01:18 UTC
Labels: bug
