### ISSUE TITLE
"Element is open in another tab" mistakenly showing after browser restart

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#26192] opened 2023-09-18 15:22 UTC
### Steps to reproduce

1. Pin the Element tab in Firefox (with no other Element tab open)
2. Close Firefox
3. Open Firefox
4. Show the Element tab

#### What did you expect?

Element starts loading

#### What happened instead?

A message appears telling me that Element is open in another tab, and that I need to close said tab (which doesn't exist) and click "Continue". Doing nothing except clicking "Continue" makes the message disappear and Element starts loading.

### Operating system

Arch Linux

### Browser information

Firefox 117.0

### URL for webapp

app.element.io

### Application version

Element version: 1.11.43 Olm version: 3.2.14

### Homeserver

abolivier.bzh

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-09-18 15:32
Duplicate of https://github.com/vector-im/element-web/issues/26165

**Closed by t3chguy** 2023-09-18 15:32 UTC
Labels: T-Defect

**Comment by richvdh** [comment] 2023-09-21 15:55
Looks like the `pagehide` handler didn't get run for the session which was closed at 2023-09-18T15:18:50.402Z, so when a new session was started at 2023-09-18T15:19:17.083Z D it thought the old one was still running.

Not really sure what we can do about this, if firefox doesn't run the handlers it is supposed to.
