### ISSUE TITLE
Slow room joins show an unclear error

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19717] opened 2021-11-11 19:37 UTC
### Steps to reproduce

1. try to join a big room that isn't yet synced to your homeserver at all
2. click join
3. wait for sync

#### What did you expect?
1. we can join multiple rooms at once with matrix-org/matrix-react-sdk#7041 - this message should be more precise
2. join the room or stop spinning

#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/141357789-0bb8d76c-0375-4500-bc34-b1da4c4706d2.png)
1. unclear error
2. keeps spinning even after accepting the error
3. eventually joined the room

### Operating system

arch

### Application version

Element Nightly version: 2021111101 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by aaronraimist** [comment] 2021-11-12 03:17
Duplicate of these existing issues: https://github.com/vector-im/element-web/issues/15627 https://github.com/vector-im/element-web/issues/5776 https://github.com/vector-im/element-web/issues/6554 https://github.com/vector-im/element-web/issues/9610

**Closed by aaronraimist** 2021-11-12 03:17 UTC
Labels: T-Defect
