### ISSUE TITLE
Add an option for account switching

### ISSUE THREAD

**Issue by artiblaster** [vector-im/element-web#16185] opened 2021-01-17 21:48 UTC
I have 2 accounts. 1 for porn and 1 for other uses. It is difficult to log in and out to check them. Facebook has a 1-click account switching feature. 

Furthermore, when I log out, the logged out account can't decrypt encrypted messages.

So I recommend an account switching feature that allows users to still receive encrypted messages.

**Describe alternatives you've considered**
Using discord

**Comment by turt2live** [comment] 2021-01-17 21:50
Duplicate of https://github.com/vector-im/element-web/issues/2320

**Comment by t3chguy** [comment] 2021-01-17 21:50
> Furthermore, when I log out, the logged out account can't decrypt encrypted messages.

That is a property of Perfect Forward Secrecy: https://en.wikipedia.org/wiki/Forward_secrecy

Multiple account support is a duplicate of https://github.com/vector-im/element-web/issues/2320

**Closed** 2021-01-17 21:50 UTC
Labels: suggestion

**Comment by artiblaster** [comment] 2021-01-18 23:18
> > Furthermore, when I log out, the logged out account can't decrypt encrypted messages.
> 
> That is a property of Perfect Forward Secrecy: https://en.wikipedia.org/wiki/Forward_secrecy
> 

Is there a way that logging in/out can be set up to not break Perfect Forward Secrecy?
