### ISSUE TITLE
Element Web missed encryption keys after HDD overflowing  

### ISSUE THREAD

**Issue by msva** [vector-im/element-web#25819] opened 2023-07-17 15:10 UTC
### Steps to reproduce

1. Fill the HDD partition up to the end
2. reload Element page
3. It shows message "it seems, your browser deleted the keys when there was not enough space in the disk. To help us prevent this in the future, please send us the logs"
4. logs-sending form requires to create the issue.
5. here it is

#### What did you expect?
Normal page reload

#### What happened instead?
Error message about missed keys appeared, and requires to re-login

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-07-17 15:11
Duplicate of https://github.com/vector-im/element-web/issues/18423

**Comment by msva** [comment] 2023-07-17 15:11
I tried to send the logs, but instead I got the error "No connected database" :shrug:

![image](https://github.com/vector-im/element-web/assets/268102/60f4a530-f51b-4b6a-8a45-967092d02dae)

**Closed by t3chguy** 2023-07-17 15:11 UTC
Labels: T-Defect
