### ISSUE TITLE
Message search in an E2EE chat without keyring has broken

### ISSUE THREAD

**Issue by bodqhrohro** [vector-im/element-web#25025] opened 2023-04-03 17:27 UTC
### Steps to reproduce

1. Start `element-desktop` without a keyring daemon running.
2. Focus the search box.

### Outcome

When I first installed `element-desktop`, there was no keyring daemon running in my system. It managed to store a local search database of decrypted messages anyway.

Later I launched `gnome-settings-daemon` manually [according to ArchWiki](https://wiki.archlinux.org/title/GNOME/Keyring#Launching_gnome-keyring-daemon_outside_desktop_environments_(KDE,_GNOME,_XFCE,_...)), as `nheko` and `skypeforlinux` demanded some sort of keyring. I discovered that if `element-desktop` is launched after the keyring was unlocked, message search fails there with `Error opening the database: DatabaseUnlockError("Invalid passphrase")` But if I killed `gnome-settings-daemon`, launched `element-desktop` and pressed Escape two times to dismiss keyring password prompts, the search still worked. Since that, I didn't upgrade `element-desktop` for more than 2 months.

Recently, I upgraded `element-desktop` and discovered I cannot search without unlocking the keyring too. Dismissing the prompts results in `Error getting the event index passphrase out of the secret store [Error: Cannot create an item in a locked collection]` in stderr (AFAIR, I had it before the upgrade too, but it didn't affect anything), and the same `Error opening the database: DatabaseUnlockError("Invalid passphrase")` as if the keyring would be unlocked.

Can I restore the old behaviour or finally make it work with an unlocked keyring? Ideally without re-fetching the message cache.

### Operating system

Debian GNU/Linux 12

### Application version

Element version 1.11.28, olm version 3.2.12

### How did you install the app?

https://packages.element.io/debian

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-04-04 07:47
Duplicate of https://github.com/vector-im/element-web/issues/17845

**Closed by t3chguy** 2023-04-04 07:47 UTC
Labels: T-Defect
