### ISSUE TITLE
Thread index panel is very stale

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#22133] opened 2022-05-10 16:54 UTC
### Steps to reproduce

1. I'm actively talking in a bunch of threads in backend internal
2. However, the thread index in the RightPanel is showing no thread activity newer than 5 hours ago, and doesn't show the new threads at all.

Will post a screenshot that demonstrates on the rageshake

#### What did you expect?

Up-to-date thread index panel

#### What happened instead?

Weirdly stale thread index panel

### Operating system

macOS

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by gsouquet** [comment] 2022-07-29 12:42
Duplicate of https://github.com/vector-im/element-web/issues/21799

**Closed by gsouquet** 2022-07-29 12:42 UTC
Labels: T-Defect, X-Blocked, S-Major, O-Uncommon, A-Threads
