### ISSUE TITLE
Start automatically after system login not working. 

### ISSUE THREAD

**Issue by AnisTaluqdar** [vector-im/element-web#24843] opened 2023-03-16 11:59 UTC
### Steps to reproduce

Its no longer working as automatically system login. I just installed the latest version in windows 11 and this option is not working. 

#### What did you expect?

I expect it will work automatically after system login

#### What happened instead?

It does not start automatically after system login 

### Operating system

Windows 11

### Application version

Element version: 1.11.25 Olm version: 3.2.12

### How did you install the app?

https://element.io/download

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-03-16 12:12
Duplicate of https://github.com/vector-im/element-web/issues/16437

**Closed by t3chguy** 2023-03-16 12:12 UTC
Labels: T-Defect
