### ISSUE TITLE
Glitch after following a search result and then switching rooms

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#21781] opened 2022-04-13 15:57 UTC
### Steps to reproduce

1. While in a room (Room A) search in "All rooms" for a thread reply from a different room (Room B).
2. In the search results, locate the desired thread reply from Room B and click on it. You should now be taken to Room B.
3. Now, click on Room A on the left sidebar.

#### What did you expect?

Go back to Room A without any unexpected warnings.

#### What happened instead?

An empty thread panel is shown in Room A and the following error message in a modal window:

> Failed to load timeline position
> Tried to load a specific point in this room's timeline, but was unable to find it.

### URL for webapp

develop.element.io

### Application version

Element version: 03ab1237ed77-react-fe4683df1043-js-9aab9178360b Olm version: 3.2.8

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-13 16:16
Duplicate of https://github.com/vector-im/element-web/issues/21742

**Closed by robintown** 2022-04-13 16:16 UTC
Labels: T-Defect, A-Threads
