### ISSUE TITLE
Hovering over link does not highlight it

### ISSUE THREAD

**Issue by domoritz** [vector-im/element-web#17004] opened 2021-04-19 15:56 UTC
### Description

This is a problem when there are multiple links in a message. 

### Version information

- **Platform**: desktop

- **OS**: macOS
- **Version**: 1.7.25

**Comment by t3chguy** [comment] 2021-04-19 16:07
Where is this commonplace? 

This is not a standard behaviour
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_test

> This is a problem when there are multiple links in a message.

What is special about multiple links here?

**Comment by domoritz** [comment] 2021-04-19 16:14
Slack and Discord add the underline on hover for example. 

I would say that messages are different from general websites since one might send messages with multiple long links. Websites typically use separate link text and URLs.

**Comment by t3chguy** [comment] 2021-04-19 18:33
Duplicate of https://github.com/vector-im/element-web/issues/15252
Related https://github.com/vector-im/element-web/issues/14737

**Closed by t3chguy** 2021-04-19 18:33 UTC
Labels: A-Timeline, S-Minor, T-Defect
