### ISSUE TITLE
Element-Desktop Hung in Windows terminalserver

### ISSUE THREAD

**Issue by gerhard-recher** [vector-im/element-web#16410] opened 2021-02-08 17:52 UTC
### Description
Download Windows Setup File, execute this in Windows terminalserver.

No logs will be produced , program simply hungs, and has 4 instances in Task manager.

Execution as Administrator or simple User does no difference in behaviour

element-desktop Version 1.7.20
Windows Version: server 2012 Terminalserver

**Comment by jryans** [comment] 2021-03-05 17:42
Hmm, my guess is there's some kind 2012 Terminal Server specific issue, as we haven't had reports of this. We only [support](https://github.com/vector-im/element-web#supported-environments) Windows 10 currently. If you can reproduce the same failure on Windows 10, then let's investigate that, but for now I'll close this.

**Closed by jryans** 2021-03-05 17:42 UTC
Labels: T-Defect

**Comment by gerhard-recher** [comment] 2021-03-07 12:10
It is reproduceable and No debug Logs are avail

Am 5. März 2021 18:43:11 MEZ schrieb "J. Ryan Stinnett" <notifications@github.com>:
>Hmm, my guess is there's some kind 2012 Terminal Server specific issue,
>as we haven't had reports of this. We only
>[support](https://github.com/vector-im/element-web#supported-environments)
>Windows 10 currently. If you can reproduce the same failure on Windows
>10, then let's investigate that, but for now I'll close this.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/element-web/issues/16410#issuecomment-791576031

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jryans** [comment] 2021-03-08 17:21
@gerhard-recher Hmm, on Windows 10? What version of Windows 10 specifically...?

Since other Windows users seem to be okay, there must something system specific happening here...
