### ISSUE TITLE
Call sound settings and window adjustment 

### ISSUE THREAD

**Issue by pyr-kaboosh** [vector-im/element-web#17073] opened 2021-04-26 19:35 UTC
Can you add an option to change the call sound volume only?

I swear the next time someone calls me and I don't expect I will either have a heart attack or I'll punch my monitor. 

and since we are on the topic, maybe make the call window when in other chats movable or able to hide it, since it covers up parts of the text chat.  (pic related)

![Chat](https://user-images.githubusercontent.com/80962489/116140346-82594500-a6d7-11eb-8440-c7e87bf772ee.PNG)

**Comment by PeterBadzhakov** [comment] 2021-04-26 19:36
#wontfix

Works on my machine (Manjaro)

**Comment by SimonBrandner** [comment] 2021-04-27 10:46
Duplicate of [#16116](https://github.com/vector-im/element-web/issues/16116) and [#4192](https://github.com/vector-im/element-web/issues/4192) (and I am pretty sure there are some more dupes for this one)

**Closed by SimonBrandner** 2021-04-27 10:46 UTC
