### ISSUE TITLE
Users are ending up with multiple devices after registration

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#9480] opened 2019-04-15 14:55 UTC
We've seen this on a modular instance (though it's almost certainly not a modular problem). Every registration seems to have created two unnamed devices, which also seems to have created some issues with encryption.

**Comment by lampholder** [comment] 2019-04-24 14:02
Okay I can reproduce this _very_ easily:
- open a 'guest' browser in chrome
- register for a new account with an email address
- fish the link out of your email
- open the link in a new tab in the 'guest' browser
- go through the registration flow in the second browser
- boom - check how many devices you've got! Is it 2? Is it 4? Is it 10? Worst I've seen so far is 10 devices created for one registration. All of them have devices ids as device names, only two of them have last-accessed times.

**Comment by jryans** [comment] 2019-06-12 14:20
@lampholder Is this believed to be fixed now?

**Comment by aaronraimist** [comment] 2021-05-07 01:13
I cannot reproduce

**Comment by turt2live** [comment] 2021-05-07 01:14
Let's consider this one fixed at some point in the last couple years.

**Closed by turt2live** 2021-05-07 01:14 UTC
Labels: A-Registration, T-Defect, X-Cannot-Reproduce
