### ISSUE TITLE
Your browser can't run Element (Firefox)

### ISSUE THREAD

**Issue by davidak** [vector-im/element-web#16048] opened 2020-12-29 16:15 UTC
### Description

i was using Element 10 minutes ago, now it says my browser is not supported

i didn't change anything about my system, did you brake Element?

### Steps to reproduce

- open https://app.element.io/ in Firefox

Describe how what happens differs from what you expected.

app should work

Logs being sent: yes/no

![Screenshot from 2020-12-29 17-07-06](https://user-images.githubusercontent.com/91113/103297660-16045880-49f9-11eb-9006-f5680efd2e65.png)

### Version information

- **Platform**: web (in-browser) or desktop? web

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? Firefox 84
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? NixOS 21.03.git.173696f216f (yes, i'm from the future)
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web? https://app.element.io/

**Comment by t3chguy** [comment] 2020-12-29 16:21
Check your browser console. Given that there is no `I understand the risks and wish to continue` button means that React failed to run.

**Comment by davidak** [comment] 2020-12-29 16:30
```
Browser missing feature: 'localstorage' index.ts:74:20

Exception
​
columnNumber: 0
​
data: null
​
filename: "https://app.element.io/bundles/504aa24e021ebeda5b73/vendors~init.js"
​
lineNumber: 2
​
message: ""
​
name: "NS_ERROR_FILE_NO_DEVICE_SPACE"
​
result: 2152857616
​
stack: "v@https://app.element.io/bundles/504aa24e021ebeda5b73/vendors~init.js:2:322656\n@https://app.element.io/bundles/504aa24e021ebeda5b73/vendors~init.js:2:326469\na@https://app.element.io/bundles/504aa24e021ebeda5b73/bundle.js:2:561\n@https://app.element.io/bundles/504aa24e021ebeda5b73/vendors~init.js:2:193248\na@https://app.element.io/bundles/504aa24e021ebeda5b73/bundle.js:2:561\n@https://app.element.io/bundles/504aa24e021ebeda5b73/vendors~init.js:2:157722\na@https://app.element.io/bundles/504aa24e021ebeda5b73/bundle.js:2:561\n@https://app.element.io/bundles/504aa24e021ebeda5b73/vendors~init.js:2:161599\na@https://app.element.io/bundles/504aa24e021ebeda5b73/bundle.js:2:561\n@https://app.element.io/bundles/504aa24e021ebeda5b73/vendors~init.js:2:152153\na@https://app.element.io/bundles/504aa24e021ebeda5b73/bundle.js:2:561\n80@https://app.element.io/bundles/504aa24e021ebeda5b73/init.js:1:7057\na@https://app.element.io/bundles/504aa24e021ebeda5b73/bundle.js:2:561\npromise callback*64/<@https://app.element.io/bundles/504aa24e021ebeda5b73/bundle.js:2:6428\n64@https://app.element.io/bundles/504aa24e021ebeda5b73/bundle.js:2:7806\na@https://app.element.io/bundles/504aa24e021ebeda5b73/bundle.js:2:561\n@https://app.element.io/bundles/504aa24e021ebeda5b73/bundle.js:2:3415\n@https://app.element.io/bundles/504aa24e021ebeda5b73/bundle.js:2:3424\n"
​
<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
index.ts:213:12
```

Yeah, my disk was full, but now i have 500 MB free again. Turns out i have to restart the browser.

There could have been a more useful error message.

**Comment by t3chguy** [comment] 2020-12-29 16:33
Duplicate of https://github.com/vector-im/element-web/issues/3897

**Closed by t3chguy** 2020-12-29 16:33 UTC
Labels: bug
