### ISSUE TITLE
Can't explore public spaces 

### ISSUE THREAD

**Issue by PxBCPG** [vector-im/element-web#19643] opened 2021-11-05 16:33 UTC
#### What would you like to do?

Bee able to join public spaces as we can join public rooms, namely by discovering them in the "explore rooms" section. 

#### Why would you like to do it?

Because otherwise public spaces are like private spaces 

#### How would you like to achieve it?

2 solutions for me:
- Add them into the "explore room" section 
- Add a special section "explore spaces"

**Comment by SimonBrandner** [comment] 2021-11-05 16:45
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/17264

**Closed by SimonBrandner** 2021-11-05 16:45 UTC
Labels: T-Enhancement
