### ISSUE TITLE
Disable 1-to-1 calls in favor of Jitsi

### ISSUE THREAD

**Issue by maxkratz** [vector-im/element-web#19249] opened 2021-10-01 15:11 UTC
#### What would you like to do?

Disable 1-to-1 calls in all Element clients that are connected to the homeserver, e.g., via a configuration option and use Jitsi instead.

#### Why would you like to do it?

We are running a Synapse/Element combination at our department at the technical university of Darmstadt with a large number of public rooms for different courses for students. Currently, the UX for calls is very different in personal rooms and in group rooms. It would be nice to be able to completely disable the 1-to-1 call feature *for all element clients* on our instance to also use Jitsi in personal rooms.

#### How would you like to achieve it?

Two configuration options:
- For the web-based version, via a configuration option, e.g.:
```
"disable_direct_calls": true,
```
- For all other clients (desktop app, mobile apps, etc.), via a homeserver well-known directive, e.g. with nginx:
```
location /.well-known/matrix/client {
	default_type "text/plain";
	add_header Access-Control-Allow-Origin *;
	return 200 '
	{
	        "m.homeserver": {
	                "base_url": "https://my-server.tld"
		},
		"im.vector.riot.jitsi": {
			"preferredDomain": "my-jitsi.tld"
		},
                "im.vector.riot": {
                         "disable_direct_calls": "true"
                }
        }';
}
```

**Comment by SimonBrandner** [comment] 2021-10-01 15:21
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/16700

**Closed by SimonBrandner** 2021-10-01 15:21 UTC
Labels: T-Enhancement

**Comment by maxkratz** [comment] 2021-10-01 15:24
@SimonBrandner Thank you, I didn't manage to find the other issue :dizzy_face:.

**Comment by SimonBrandner** [comment] 2021-10-01 15:27
> @SimonBrandner Thank you, I didn't manage to find the other issue dizzy_face.

No worries :)
