### ISSUE TITLE
Group E2E rooms trigger unread count even if "the global don't notify for group rooms" is turned on

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2351] opened 2016-09-24 21:56 UTC
This is due to a thinko somewhere in https://github.com/matrix-org/synapse/pull/1131 that means that the overrides for the group settings don't apply.

**Comment by kittykat** [comment] 2021-12-01 12:56
I'm going to close this issue for now as we cannot reproduce it. Please reopen if you are still experiencing the issue.

**Closed by kittykat** 2021-12-01 12:56 UTC
Labels: T-Defect, P2, A-E2EE, X-Needs-Community-Testing
