### ISSUE TITLE
People's tab slow to open with a lot (600+) DMs

### ISSUE THREAD

**Issue by daedric7** [vector-im/element-web#26171] opened 2023-09-15 08:15 UTC
### Steps to reproduce

After the recent update, i noticed that there's a certain lag opening the people's tab.

I have a lot of DMs due to bridges, and it always take about 1 second to register the click.

#### What did you expect?

Opening as fast as the other tabs

#### What happened instead?

Several times slower than any other tab, including the Start tab that also shows the same rooms.

### Operating system

Windows

### Application version

versão do Element: 1.11.42 Olm version: 3.2.14

### How did you install the app?

selfhosted via docker compose -  image: vectorim/element-web:latest

### Homeserver

https://aguiarvieira.pt, latest Synapse.

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-09-15 09:09
This is a subset of https://github.com/vector-im/element-web/issues/18512 because the `People` metaspace force-expands the People sublist.

**Comment by t3chguy** [comment] 2023-09-16 22:17
Duplicate of https://github.com/vector-im/element-web/issues/20143

**Closed by t3chguy** 2023-09-16 22:17 UTC
Labels: T-Defect
