### ISSUE TITLE
AVIF Support - White image on preview

### ISSUE THREAD

**Issue by peepopoggers** [vector-im/element-web#19075] opened 2021-09-16 21:48 UTC
### Steps to reproduce

1. Upload a .avif image
2. Look at the chat and there will be a while preview (unless it is different on my version for some reason)
3. When you click on the image it displays alright

### What did you expect?
The preview to show the image
### What happened?
It was white

### Operating system

Popos 20.04
(using i3 with xorg)

### Application version

Element version: 1.8.5 Olm version: 3.2.3

### How did you install the app?

element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment] 2021-09-17 08:15
This sounds like a Synapse thumbnailing issue

**Comment by t3chguy** [comment] 2021-09-17 08:18
Though I cannot reproduce, can you include the AVIF file you tried? I tried using https://raw.githubusercontent.com/link-u/avif-sample-images/master/fox.profile0.10bpc.yuv420.avif
and it worked fine

![image](https://user-images.githubusercontent.com/2403652/133749319-5384b2d2-1197-4978-b287-7ef04595bfe2.png)

**Comment by peepopoggers** [comment] 2021-09-17 10:01
https://anonfiles.com/96M5V6Hfu7/staringcat_avif

GH does not support it rn.
Try this. May be a bug to do with my specs.

**Comment by t3chguy** [comment] 2021-09-17 10:07
![image](https://user-images.githubusercontent.com/2403652/133765817-0d754eb9-991e-4582-93f2-90b6d9b0095e.png)

im loving the photo, seems to work fine here on Element Desktop macOS

**Comment by peepopoggers** [comment] 2021-09-17 10:39
ok. i am using popos 20.04 and previews dont work

**Comment by MadLittleMods** [comment] 2021-09-28 18:21
Also works on Element web on Windows 10.

This seems like an OS specific support thing.

**Comment by peepopoggers** [comment] 2021-09-28 20:30
That is weird.
I added the specific window manager and display manager to my original comment.

**Comment by peepopoggers** [comment] 2021-09-28 20:31
![image](https://user-images.githubusercontent.com/72892531/135161019-44041239-ce69-42d5-bbf5-3f4abfef52ff.png)
It is working on arch linux with xmonad and xorg however

**Comment by turt2live** [comment] 2022-06-14 05:39
This will be one or more different environmental issues out of our control. Closing in favour of platform-level bugs, once diagnosed.

**Closed by turt2live** 2022-06-14 05:39 UTC
Labels: T-Defect, X-Needs-Info, Z-Platform-Specific, S-Major, A-Media, Z-Upstream, O-Uncommon

**Comment by shmerl** [comment] 2022-10-09 02:53
What is the resolution of this? What does "envoromental issue" means here? I just tried it in Firefox (on Linux) and the issue is happening. Firefox supports AVIF fine for a while arleady.

Example of the image it occurs with:

[avatar.avif.zip](https://github.com/vector-im/element-web/files/9740666/avatar.avif.zip)

**Comment by shmerl** [comment] 2022-10-09 03:02
Hm, I just tried it in 1:1 room and it worked fine. Weird. Where it didn't work was a bigger chat room.
