### ISSUE TITLE
Unsupported Browser error in Element Desktop

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#25862] opened 2023-07-28 00:06 UTC
### Steps to reproduce

1. Launch Element Desktop
2. See this:
<img width="1136" alt="Screenshot 2023-07-28 at 00 59 59" src="https://github.com/vector-im/element-web/assets/1922197/c9d582e6-a171-438a-9811-963435f66ecc">

I tried reinstalling from the web and the same thing happened.

### Operating system

macOS 13.4.1 (22F82)

### Application version

Version 1.11.36 (1.11.36)

### How did you install the app?

https://element.io/download

### Homeserver

lant.uk

### Will you send logs?

No

**Comment by lampholder** [comment] 2023-07-28 00:07
Clicking _I understand the risks and wish to continue_ does nothing.

**Comment by t3chguy** [comment] 2023-07-28 06:04
Logs from the console please. Are you getting close to running out of disk space?

**Comment by t3chguy** [comment] 2023-08-14 12:03
Hi, I'm going to close this issue for now as there is not enough info here for us to be able to action it. Please feel welcome to reopen or ask me to reopen the issue if you update the description with steps/screenshots/video/more details so our developers can have a look at it.

**Comment by lampholder** [comment] 2023-08-23 20:24
From the console:

> Browser missing feature: 'localstorage' (anonymous) @ logger.ts:48

Which is not an encouraging sign. I was briefly low on disk space - now I have ~46GB free. I'm going to try a fresh install.

**Comment by lampholder** [comment] 2023-08-23 21:01
Reinstalling a fresh build of Element doesn't help, though on reflection I don't think that it would. I probably need to trash the local state completely then try again.

**Comment by Johennes** [comment] 2023-08-24 06:01
@t3chguy are you able to advise what could need purging after having survived uninstall?

**Comment by t3chguy** [comment] 2023-08-24 09:21
@Johennes all of the app data. "Uninstalling" in macOS is deleting a directory (Element.app) - it's even worse than Windows. `rm -rf ~/Library/Application\ Support/Element*`

This issue sounds like https://github.com/vector-im/element-web/issues/10891

**Comment by t3chguy** [comment] 2023-08-24 09:50
Duplicate of https://github.com/vector-im/element-web/issues/10891

**Closed by t3chguy** 2023-08-24 09:50 UTC
Labels: T-Defect, X-Needs-Info
