### ISSUE TITLE
User avatars overlap the message line and timestamp

### ISSUE THREAD

**Issue by Winterhuman** [vector-im/element-web#22952] opened 2022-07-28 14:41 UTC
### Steps to reproduce

1. Start Element.
2. Got to any room and hover over a user's message.
3. Notice the timestamp is partially covered up.

Image to show the issue:
![time-misalignment](https://user-images.githubusercontent.com/86165318/181561671-1775ba33-81e0-44ab-b2fa-bd490e82d69c.png)

#### What did you expect?

The timestamp shouldn't appear underneath the user avatar.

#### What happened instead?

The message line, and thus the timestamp, is underneath the user avatar.

### Operating system

Arch Linux

### Application version

Element version: 1.11.1, Olm version: 3.2.8

### How did you install the app?

FlatHub

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Winterhuman** [comment] 2022-07-28 14:48
Some additional information:

I tried to see if this was caused by https://github.com/vector-im/element-web/issues/22852 or https://github.com/vector-im/element-web/issues/22850, but, changing the DPI didn't do anything.

However, this issue was present in the Element version of https://github.com/vector-im/element-web/issues/22852, I covered up the user's text with a white block which I made sure to match to the pixel, and the issue is present in the image as well; the message line is too high.

**Comment by MadLittleMods** [comment] 2022-07-28 18:17
For reference, font size can be adjusted via **Settings** -> **Appearance** -> **Font size**. 

Interestingly, the default in the settings is `15` but the actual size on the page is `14px` (the problem is not present).

But at `13`, the actual size on the page is `11.2px` and this is reproducible. Since the range in the slider is `13` - `18` and any value from the slider is probably is considered "safe"/"recommended", we should probably fix the overlap. Although the HTML and CSS could probably be adjusted to accommodate any font size.

![](https://user-images.githubusercontent.com/558581/181607573-ad7f7113-11dc-4577-907d-1d8d8ffefe5c.png)

**Comment by MadLittleMods** [comment] 2022-07-28 18:19
This is a duplicate of https://github.com/vector-im/element-web/issues/11051 although that specifically tracks Compact layout and the problem is also reproducible in the default Modern layout.

**Comment by t3chguy** [comment] 2022-07-29 08:29
Duplicate of #11051 
Made the issue broader given the fix should take both issues into account

**Closed by t3chguy** 2022-07-29 08:29 UTC
Labels: T-Defect, S-Tolerable, A-Timeline, O-Uncommon
