### ISSUE TITLE
Call rings without someone calling

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-web#23762] opened 2022-11-13 14:26 UTC
### Steps to reproduce

1. I login to my machine
2. Element desktop is already running
3. I switch to a 1:1 room where the last interaction was a 1:1 video call
4. Element begins ringing
5. I try to answer and the video call opens
6. Nobody is there

#### What did you expect?
At first, I expected someone to be at the other end

In hindsight, as nobody was calling me, I expected the desktop app not to ring

#### What happened instead?
The desktop app was ringing

### Operating system

Windows 11

### Application version

Element version: 1.11.14
Olm version: 3.2.12

### How did you install the app?

element.io

### Homeserver

Synapse

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2022-11-15 08:56
Duplicate of https://github.com/vector-im/element-web/issues/4607

**Closed by SimonBrandner** 2022-11-15 08:56 UTC
Labels: T-Defect

**Comment by jakecoppinger** [comment] 2022-12-08 08:06
I don't think this is a duplicate of #4607.

#4607 details phantom phone calls as Element syncs history, which disappear as further events are synced.

This issue (which I also have, only with one chat) is a phantom phone call which _doesn't disappear_.

- There is no real ongoing phone call on any other device
- There is no phone call invite in the chat on my phone
- The other person in the DM chat doesn't get notified _unless_ I "pick up" or "decline".

Very strange behaviour - the only way I can stop the phantom call is quit element and not open that DM.

I only have this issue on web and not iOS.
