### ISSUE TITLE
Improve error message if a guest is not allowed to peek

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#7333] opened 2018-09-13 17:35 UTC
For example if the HHS doesn't allow guest, trying to access a room bring ups "xxxxx is not accessible at this time."
The error message should be more explicit and mention that "only registered users can view this room, please register **here**"

**Comment by turt2live** [comment] 2018-09-26 20:36
@AmandineLP I can't reproduce this. When trying to visit a room that has guest access disabled, I get this:
![image](https://user-images.githubusercontent.com/1190097/46107788-89272080-c199-11e8-9ccc-96a8400340ef.png)

Clicking on "Click here" I get the "Please pick a username" dialog. Is there some steps I may have missed?

**Comment by t3chguy** [comment] 2022-05-10 20:53
Closing due to lack of being told what specification combination is required to make this happen.

**Closed by t3chguy** 2022-05-10 20:53 UTC
Labels: T-Defect, P1, X-Cannot-Reproduce, S-Major
