### ISSUE TITLE
Ctrl+A shortcut closes the desktop app

### ISSUE THREAD

**Issue by Govi59** [vector-im/element-web#17711] opened 2021-06-20 21:13 UTC
### Description
When I use the shortcut `Ctrl+A` in order to select all the text in the writing area, the text is not selected and the app closes instead.

### Steps to reproduce
- write text in the writing area
- press `Ctrl` and `A`
- the alert shows up and the text is not selected

I would like the text to be selected and not the app to ask me if I want to close it.

![image](https://user-images.githubusercontent.com/22171202/122688354-14835280-d21c-11eb-9c78-c4e09986f0f7.png)

### Version information

- **Platform**: desktop
- **OS**: Linux Mint 20.1 Cinnamon
- **Version** de Element : 1.7.25
- **Version** de olm : 3.2.1

Note: the shortcut works fine on Element web.

**Comment by robintown** [comment] 2021-06-20 22:16
Duplicate of #16938, which has been fixed. You'll need to upgrade to Element Desktop 1.7.26 or later.

**Closed** 2021-06-21 01:13 UTC
Labels: T-Defect
