### ISSUE TITLE
Element Nightly App Crashing on Startup (Linux)

### ISSUE THREAD

**Issue by jph168** [vector-im/element-web#21727] opened 2022-04-08 21:18 UTC
### Steps to reproduce

Last Known Good Element Nightly Version: 2022011101 Feb-11 08:23
First Bad Element Nightly Version: 2022021102 Feb-11 14:35
Latest Element Stable Release: 1.10.8 Unaffected

Immediate Difference between:
Non Broken
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:

/opt/Element-Nightly/resources/app.asar/lib/language-helper.js
/opt/Element-Nightly/resources/app.asar/lib/tray.js
/opt/Element-Nightly/resources/app.asar/lib/electron-main.js

===================================================
Every Broken
Resetting the UI components after locale change
Resetting the UI components after locale change
[5589:0408/025620.382477:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:

/opt/Element-Nightly/resources/app.asar/lib/language-helper.js
/opt/Element-Nightly/resources/app.asar/lib/tray.js
/opt/Element-Nightly/resources/app.asar/lib/electron-main.js

culprit line:
5589:0408/025620.382477:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process

Sending Logs through Element is not possible with this issue.

#### What did you expect?
Not an Immediate crash.

#### What happened instead?
An immediate crash.

### Operating system

Linux

### Application version

2022021102+

### How did you install the app?

Manually Compiled.

### Will you send logs?

No

**Comment by robintown** [comment] 2022-04-08 22:18
It would help to know more about your operating system. What distro are you using?

**Comment by jph168** [comment] 2022-04-08 22:20
> It would help to know more about your operating system. What distro are you using?

Manjaro Linux

**Comment by robintown** [comment] 2022-04-08 22:22
Duplicate of https://github.com/vector-im/element-web/issues/20926

**Closed by robintown** 2022-04-08 22:22 UTC
Labels: T-Defect, X-Needs-Info

**Comment by jph168** [comment] 2022-04-08 22:27
oof this Duplicate isn't very Specific about it being Element Nightly.

**Comment by jph168** [comment] 2022-04-08 22:34
> Duplicate of #20926

This Duplicate isn't very Specific about it being Element Nightly or very Specific about any Actual Specifics.
