### ISSUE TITLE
User status is always offline [presence is disabled] on matrix.org server

### ISSUE THREAD

**Issue by jeangb** [vector-im/element-web#2667] opened 2016-11-30 16:43 UTC
No matter what client I use (android, iOs, web) my status is offline in the room details and member section.
Sometimes it's "Offline 4s ago" and the "4s ago" may represent the last time I posted a message. 

Here are some logs from browser (chrome) : https://gist.github.com/jeangb/0cccd6b1a2093228e3064ddb05beeb91
![presence offline](https://cloud.githubusercontent.com/assets/22364949/20761447/4e44d9da-b723-11e6-96fe-48816f3bdba2.png)

**Comment by bakfietz** [comment] 2017-04-12 11:06
In some rooms, people's status is allways offline, in some rooms it seems to work fine

**Comment by lampholder** [comment] 2017-05-31 11:05
I believe this is the result of presence's being turned off on matrix.org homeserver for performance reasons. It would be nice to do better - Offline != Presence Unknown, but I believe this is tricky.

**Comment by darkuranium** [comment] 2017-06-02 15:04
This is most definitely a bug, @lampholder. I know the other person has presence on, and yet they can be shown as online in one client, offline in another, and "idle for 6 hours" in a third (even if I've just talked to them).

In fact, it even shows ***me*** as being offline sometimes.

**Comment by t3chguy** [comment] 2017-06-02 16:29
@darkuranium are you using the matrix.org homeserver? If so then it is not a bug, it is due to the fact that the matrix.org HS has had its Presence frozen/disabled due to it using too many resources. **AS @lampholder TOLD YOU.**

**Comment by darkuranium** [comment] 2017-06-03 00:56
@t3chguy: Relax, I fucking misunderstood, okay? Jesus christ, what's wrong with you people.

And ultimately, it doesn't matter. What matters is whether it works or not; it doesn't work as it was supposed to, so it's a fault. Whether it's a software bug or not is not my problem.

**Comment by ara4n** [comment] 2017-06-03 11:06
@t3chguy, please don't yell at folks... @darkuranium: yup, it sucks and it is definitely a bug. We'll see about turning it back on this week.

**Comment by laurathiessen** [comment] 2017-06-24 04:19
how do you fix this?

**Comment by laurathiessen** [comment] 2017-06-24 04:28
how do you resolve this? my account is doing the same thing

**Comment by luksch** [comment] 2017-06-27 07:08
Any news on that? I experience the same behavior (again?) on the matrix hoe server

**Comment by metrowave** [comment] 2017-07-10 21:15
mine also is turned off all the time!

**Comment by t3chguy** [comment] 2017-07-10 23:18
@metrowave https://www.hello-matrix.net/public_servers.php

**Comment by metrowave** [comment] 2017-07-11 18:57
@t3chguy, many thanks... It is magically fixed. Now my status is correctly updated :)

**Comment by Nostradamos** [comment] 2017-07-11 21:56
Still not working for me, neither in riot.im/develop nor in latest riot-web app from ubuntu ppa.

**Comment by lampholder** [comment] 2017-07-21 12:28
We still haven't turned it on, at least not permanently.

We do need to do better with this - at the very least we shouldn't be making false claims about users' presence. Could we tactically switch OFFLINE for UNKNOWN, or perhaps OFFLINE/UNKNOWN?

**Comment by lampholder** [comment] 2017-07-21 12:29
Switching to P1 because I feel this feature's (at least apparent) malfunctioning creates a very bad impression with users.

**Comment by anastiel** [comment] 2017-07-25 02:54
So in case this bug would have no solution?

**Comment by lampholder** [comment] 2017-07-25 09:44
Well, there are two solutions:
- in the short term, somehow stop the UX being so confusing
- in the longer term, get the presence feature reenabled on matrix.org so that we reliably advertise user status

**Comment by darkuranium** [comment] 2017-07-25 10:28
@lampholder For the short term, I think your idea of adding an "unknown" option is the best.

**Comment by magykjames** [comment] 2017-08-13 18:41
I just set it up and talked two others into joining as well, and we all three show up as offline. This issue still remains as of August 13, 2017 unless I'm missing a setting somewhere. I assumed maybe it was some sort of privacy setting.

**Comment by t3chguy** [comment] 2017-08-13 20:45
@magykjames since this issue is still open, yes it still exists.

**Comment by shmerl** [comment] 2018-01-23 16:59
is there any ETA on fixing this on matrix.org, or at least improving the client to report unknown status?

**Comment by t3chguy** [comment] 2018-01-23 17:10
@shmerl probably best thing to track is Dendrite: https://docs.google.com/spreadsheets/d/1tkMNpIpPjvuDJWjPFbw_xzNzOHBA-Hp50Rkpcr43xTw

**Comment by lampholder** [comment] 2018-03-02 10:43
Fixing presence/rolling out Dendrite is going to take a while, and in the meantime this continues to confuse people.

There's probably another solution whereby individual servers could expose whether or not they're supporting presence, which could then be aggregated into a status value that a homeserver could share with its client, so that the client could make a decision whether to show 'Presence data unavailable' for users on a given homeserver (regardless of the last value it got down the sync).

In the absence of any supporting infrastructure for the above or the desire to spend undue time on overengineering wallpaper, I know it's a little distasteful, but could we just hard code riot web, android and iOS to display 'Presence data unavailable' for all users on matrix.org for now?

**Comment by turt2live** [comment] 2018-03-02 14:24
> There's probably another solution whereby individual servers could expose whether or not they're supporting presence, which could then be aggregated into a status value

Related: https://github.com/vector-im/riot-web/issues/4398

**Comment by rodneyrod** [comment] 2018-04-23 02:52
@Lampholder What about temporarily adopting the Telegram model? It doesn't track absolute online status.

**Comment by phoerious** [comment] 2019-04-19 20:38
This issue is two years old now and the last activity here was 12 months ago. Has there been any progress on this matter? Seeing everyone offline with "last seen 700+ days ago" is very irritating.

**Comment by Midek** [comment] 2019-05-01 10:54
@phoerious Just host your own HS with presence enabled instead. Matrix is supposed to be decentralised anyway.

**Comment by MightyCreak** [comment] 2019-05-01 11:15
@Midek Not everyone has the skills, the time, or the money to host their own matrix server. Especially since matrix needs around 4GB of RAM, and Synapse still hasn't reached 1.0, and Dendrite is supposed to replace it which, I project, won't be a piece of cake to migrate to (especially if you're not a professional sysadmin).

And also the root of the issue is potentially quite serious because, if I understand correctly, it means that there is a scalability issue within the Matrix code.

I don't have my own server, but I'm paying Matrix on Patreon, so I feel, in a way, that I'm paying for a service, and I think it's legit to ask why this 2 years old major p1 bug (as the labels say) is still not addressed, don't you think?

**Comment by phoerious** [comment] 2019-05-01 11:55
I am using Matrix, because I do not want to host my own messaging server. I ran a ZNC for years and keeping it updated and securely configured is just something I don't have the time for. As said before, this should be fixed by Matrix not by me running my own instance. If that's a problem, then there really is a scalability issue that needs to be addressed and if that does not happen, then people will just keeping using WhatsApp or whatever.

**Comment by lampholder** [comment] 2019-05-01 12:16
Hi all - thanks for your comments; we know this is an annoying feature not to support on matrix.org but I'm afraid it hasn't yet risen to the top of the pile :( 

If you're interested in what we're working on ahead of specific presence scalability, please take a look at the [homeserver roadmap](https://github.com/orgs/matrix-org/projects/9) and the [riot web roadmap](https://github.com/vector-im/riot-web/projects/16) - some of the homeserver work actually does address scalability issues generally, so should get us closer to being able to reenable presence on matrix.org.

> Seeing everyone offline with "last seen 700+ days ago" is very irritating.

I don't think you should be seeing this (if you're using riot.im/app or /develop or desktop anyway) - the (outdated) presence data should be being hidden if the app is configured correctly.

**Comment by phoerious** [comment] 2019-05-01 14:03
> I don't think you should be seeing this (if you're using riot.im/app or /develop or desktop anyway) - the (outdated) presence data should be being hidden if the app is configured correctly.

Nope, matrix.org, most recent versions of Riot Android/Desktop, seeing exactly that.

**Comment by liberodark** [comment] 2020-04-14 12:44
No new about this ?
Any fix for that ?

Best Regards

**Comment by t3chguy** [comment] 2020-04-14 12:48
I don't think matrix.org is planning on re-enabling presence any time soon, you may wish to register on a different server. Communications will still work between servers due to federation.

**Comment by TheJJ** [comment] 2020-05-20 11:54
Would it be possible to let homeservers report their presence-enabled-status and then disable graying out users on a client? Just like it's done with the `config.json`, but in a way the server reports this itself.

This is important as many other homeservers also have presence disabled on purpose.

I've been asked many times why users are grayed out, and for them it's a small (but effective) annoyance.

**Comment by MightyCreak** [comment] 2020-05-20 14:20
This issue is 4.5 years old. I'd be interested to know if there's a technical solution for this issue (not a workaround)?

For instance, I've seen that the switch to Redis allowed to add more workers, could it have been used to re-enable presence on matrix.org? Is the issue about the way presence is coded? Does the current implementation use too much resources? Can it be optimized? If not, what's the plan?

In the end, presence is a useful feature, and although a company should not use matrix.org as their homeserver, the fact it is disabled does not provide a very good demo. I'm afraid this could have a negative impact on a decision maker.

**Comment by vgmoose** [comment] 2020-11-13 22:18
Seems like https://github.com/matrix-org/synapse/issues/3971 may be a good issue to track for the technical limitations

**Comment by JPustkuchen** [comment] 2021-02-23 08:13
This is still an open issue for us, we're using EMS Hosting so I guess it should at least work there? ;)

**Comment by t3chguy** [comment] 2021-02-23 09:11
@JPustkuchen chat to your EMS support, only they know your config.

**Comment by JPustkuchen** [comment] 2021-02-23 09:24
Thank you @t3chguy, I just wrote them to see what's the problem.

**Comment by JPustkuchen** [comment] 2021-02-27 16:59
Ok EMS Support says they also have this disabled for paying customers due to too the technical reasons given above. They're waiting for a fix of these issues. A bit funny that a status indicator is such a big problem for a project of this size... ;)

**Comment by t3chguy** [comment] 2021-02-27 17:10
The performance issue on the server-side - Synapse - not Element.
If you think about it, presence has to be propagated to every other device of every user in every room that a user is in, that very quickly ramps up to a lot of users*devices.

Closing the Element side,

https://github.com/matrix-org/synapse/issues/9478 is probably worth following

**Closed by t3chguy** 2021-02-27 17:10 UTC
Labels: bug, matrix.org infrastructure, p1, severity:major, type:memberlist, type:presence

**Comment by autoteelar** [comment] 2021-06-01 08:46
randy do more

**Comment by XdekHckr** [comment] 2024-10-26 18:11
Still not fixed lmao. You can't even setup your status. You can't even disable seen message. Matrix and element is crap.
