### ISSUE TITLE
Invite by mxId - Don't add unrecognised mxId in the ‘suggestions’ section

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#25446] opened 2023-05-25 17:03 UTC
### Steps to reproduce

Scenario 1:
- Start a new DM by filling a non-existent MatrixId

Scenario 2:
- Open an existing group chat
- Invite a new member by filling a non-existent MatrixId

#### What did you expect?
if we do not recognise the MXID (= the getProfile failed (for example: M_NOT_FOUND error, or 502 code)) we should not show it in the ‘suggestions’ section

#### What happened instead?
The unrecognised mxId is added in suggestions:
<img width="748" alt="Screenshot 2023-05-24 at 08 56 11" src="https://github.com/vector-im/element-web/assets/8969772/efe910bc-905e-4f0c-b0d2-bfcf9d4335cc">

### Application version

Element version: 1.11.31
Olm version: 3.2.14

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-05-30 09:12
> if we do not recognise the MXID (= the getProfile failed (for example: M_NOT_FOUND error, or 502 code)) we should not show it in the ‘suggestions’ section

Synapse has settings which make it hide profiles unless you share a room, e.g. https://github.com/vector-im/element-web/issues/23403 so doing that would prevent users starting DMs even if they had shared MXIDs out-of-band. Doubt this is what we want and is inherently only privacy by obscurity.

**Comment by giomfo** [comment] 2023-05-30 09:31
@t3chguy in that case, the "Invite" button is still available to start DM or invite the unrecognised Id
(cc @daniellekirkwood )

**Comment by daniellekirkwood** [comment] 2023-05-30 09:48
I don't follow the technical constraint here -- 

If the MXID is invalid/unknown, we should hide the "suggestions" section.

**Comment by daniellekirkwood** [comment] 2023-05-30 09:51
Sorry, somehow managed to click too many buttons at once on the keyboard... Found some new shortcuts though 🤦 

If you share a room with the user, it makes sense that that profile shows up in "suggestions". If you don't share a room or can't recognise the user it doesn't make sense that there's a "suggestion"... 

Happy to loop in design here as they may have other ideas, or a way to rename the section from "Suggestion" to something more meaningful (as suggestion is not accurate). 

Removing "Suggestions" doesn't stop the user from clicking invite?

**Comment by t3chguy** [comment] 2023-05-30 09:52
> I don't follow the technical constraint here -- 
> 
> If the MXID is invalid/unknown, we should hide the "suggestions" section. 
> 
> 
> 

The MXID isn't invalid, it's unknown because servers won't tell us definitively whether an MXID exists for privacy reasons.

**Comment by daniellekirkwood** [comment] 2023-05-30 10:22
but when you do know the MXID, it renders with a display name instead?

**Comment by t3chguy** [comment] 2023-05-30 10:23
@daniellekirkwood Yes, if the server wishes to give you a profile then we will render it

**Comment by daniellekirkwood** [comment] 2023-05-30 10:35
can we have: if there's a profile show 'SUGGESTIONS' else show _something else_ ✨  ?

**Comment by t3chguy** [comment] 2023-05-30 10:39
Sure

**Comment by daniellekirkwood** [comment] 2023-05-30 11:12
Have reached out to @nadonomy for a design consult. I think we either hide suggestions if there's no profile or we rename it to something more appropriate. 

Alfie also had a bit of feedback on this topic so I will pass along there also :)

**Comment by daniellekirkwood** [comment] 2023-06-05 08:54
OK, that feels like the plan ahead then ☝️ 

@giomfo is this confirmed part of the retainer time?

**Comment by giomfo** [comment] 2023-06-05 09:52
> is this confirmed part of the retainer time?

Yes I will ask @weeman1337 to work on it

**Comment by richvdh** [comment] 2023-06-13 09:23
Transferring some context from the [pull request](https://github.com/matrix-org/matrix-react-sdk/pull/11055):

This reverts a change originally made to fix https://github.com/vector-im/element-web/issues/12440. @turt2live gave some more context around the reasons for that change in [this comment](https://github.com/matrix-org/matrix-react-sdk/pull/11055#issuecomment-1588285498). In summary:

 * There are many good reasons why a `/profile` request may fail for a genuine user. A successful `/profile` request is a good indication that a user exists, but an *unsuccessful* one doesn't tell us a whole lot.
 * The fact that you can still click "Invite" when the user doesn't appear in the list is hard to discover.

I realise this thread has been around this loop before, but I just wanted to double-check that we still think this is a correct change to make in light of the fact that we've deliberately made the opposite decision in the past.

I don't have strong feelings either way, but I just want to be sure that the decisions are being made with all the information.

@nadonomy, @daniellekirkwood could you confirm, please?

**Comment by daniellekirkwood** [comment] 2023-06-13 09:41
I think our options are still the 2 highlighted above... Rename the section, or remove it. I'm happy with either one of these but I understand how some folks can see how the "invite" button might not be discoverable.

Suggestion:
I created this posthog graph that we can use to monitor any drop in create room and revert this change if needed
https://posthog.hss.element.io/insights/GS7jX5qe

**Comment by daniellekirkwood** [comment] 2023-06-13 12:48
Having read @turt2live 's feedback on the PR I'd like to re-iterate that the issue is mainly that Element "suggests" MXIDs that are invalid. Changing the title of the section when there's no profile found would help to clear up the confusion. 

I do not agree that that "Invite" button is hard to find but as we're not looking at updating this screen for a little while, renaming the section would be a suitable solution for me atm. 

👀  @nadonomy

**Comment by weeman1337** [comment] 2023-06-14 07:13
Some users have a closed network. They have profiles enabled and do not federate with the world. For them it would be good not to display invalid MXIDs. I can also understand that this may not work great in the context of (unknown) federation.

→ What about considering this as a config option? The option should not be visible to the user. It can just be in the JSON shipped with the client. This would meet the demands of users in a known, closed network.

**Comment by t3chguy** [comment] 2023-06-14 08:14
> It can just be in the JSON shipped with the client.

That'd require building & signing & notarising your own desktop apps. IMO this should be done at the spec level with a proper way to query whether an MXID exists which has a tri-state response. Yes|No|Unknown - where open federation servers return Yes|Unknown only depending on public presence, closed federations can switch to Yes|No if they deem it to be what they desire.

**Closed** 2023-06-15 09:32 UTC
Labels: T-Defect, S-Minor, A-Invite, O-Occasional
