### ISSUE TITLE
Composer keyboard focus is easily lost

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-web#19794] opened 2021-11-18 02:14 UTC
### Steps to reproduce

I've noticed that recently I start and try typing in element-desktop (not sure if that's any different in web :shrug: ) the cursor is never inside the composer when I expect it to. This probably happened about 100 times today.

This is happening when clicking the "down to bottom"-arrow button, even when the composer was focused before. It's also happening when clicking on random non-clickable areas in the timeline.

Some more notes here:

* It seems like previously hitting any non-shortcut key would focus the composer: https://github.com/vector-im/element-web/issues/5775#issuecomment-613354924 This definitely isn't happening anymore
* Trying to use tab to get the cursor back into the input field is not working. It keeps cycling through items in the timeline, potentially way offscreen where you last were, resetting your scroll-position.

#### What did you expect?

I would like to be able to type messages at pretty much all times.

#### What happened instead?

The cursor is almost never in the input field.

### Operating system

Arch Linux

### Application version

1.9.4

### How did you install the app?

archlinux-package

### Homeserver

bubu1.eu

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2021-11-18 06:43
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19479

**Closed by SimonBrandner** 2021-11-18 06:43 UTC
Labels: T-Defect

**Comment by Bubu** [comment] 2021-11-18 10:15
Thanks, I somehow didn't find the other issues. I'm glad it's being looked into already :-).
