### ISSUE TITLE
"User ID already taken" still occurring

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#10038] opened 2019-06-13 11:28 UTC
I registered with an email address on matrix.org. Upon opening the email verification link in a new tab, the initiating tab completed it's registration and logged in. The verification tab smacked into a 'User ID already taken' error (at the top of the registration page).

So I tried a second time. This time, the verification tab got stuck for a very long time showing this:
![image](https://user-images.githubusercontent.com/1922197/59428913-752e5800-8dd6-11e9-982c-49067195eb1b.png)

The console log in the initiating tab had this to say:
![image](https://user-images.githubusercontent.com/1922197/59428984-a149d900-8dd6-11e9-803f-4c61083b5fef.png)

Eventually, after maybe a couple of minutes, both the initiating tab and the verification hit this:
![image](https://user-images.githubusercontent.com/1922197/59428960-9131f980-8dd6-11e9-8e81-df4477313a5a.png)

N.B. in this last screenshot we see the "User ID already taken" notice at the bottom of the registration pane - this is different to how it rendered in the first test (where it appeared at the top of the registration pane).

**Comment by lampholder** [comment] 2019-06-13 11:29
Eventually, both the tabs completed sign in.

**Comment by lampholder** [comment] 2019-06-13 11:30
BUT BOTH TABS WANTED ME TO COMPLETE TERMS AND CONDITIONS:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/1922197/59429147-0a315100-8dd7-11e9-947a-542f1c42a246.png">

**Comment by wuhlheide** [comment] 2019-12-28 17:44
Same here with Riot 1.5.4:
`2019-12-28 18:40:45,356 - synapse.http.server - 80 - INFO - POST-1930- <XForwardedForRequest at 0x7fbba646bbe0 method='POST' uri='/_matrix/client/r0/register' clientproto='HTTP/1.1' site=8008> SynapseError: 400 - User ID already taken.`

**Comment by Plecra** [comment] 2020-02-11 20:20
Until this is properly fixed, I think it'd would be helpful to add a note that mentions this bug, so that new users can try to login anyway. It not obvious there's even a problem when it crops up at the moment

**Comment by the-moog** [comment] 2020-04-02 15:54
Still here in latest 1.5.15.  The good news is the email field is filled properly at last!!

**Comment by kittykat** [comment] 2021-09-03 09:54
Cannot reproduce on develop.element.io - registration tab and verification tab both refresh correctly so closing this issue. Please reopen issue or comment with @kittykat so that I can reopen it if you can still trigger the defect.

**Closed by kittykat** 2021-09-03 09:54 UTC
Labels: T-Defect, X-Needs-Investigation
