### ISSUE TITLE
WIN10 media keys broken - DUPLICATE

### ISSUE THREAD

**Issue by FGHTech** [vector-im/element-web#16430] opened 2021-02-10 17:48 UTC
### Description

Play pause focus is on Element instead of what is actually playing (WIN10), even thoguh there is not an active call.

### Steps to reproduce

1. Install Element
2. Initiate a call
3.  -> end call.
4. Play music through Spotify desktop application.
5. Use play pause media keys in attempt of changing songs or play/pause.

Instead of focusing on Spotify, Element for some reason has focus stating the last caller's name in the "track name" variable of the WIN10 popup. Fairly irritating when wanting to use media keys to change tracks or play/pause.

Would be very nice to have a toggle in settings just to disable Element from using the "WIN10 now playing window".

### Image:

![image](https://user-images.githubusercontent.com/56099414/107549608-4df1e480-6bd0-11eb-9f89-24c67217538a.png)

### Version information

For the desktop app:
- **Platform**: Desktop WIN10
- Element version: 1.7.20
- olm version: 3.2.1
![image](https://user-images.githubusercontent.com/56099414/107549776-81cd0a00-6bd0-11eb-814c-f1b97ed4b409.png)

**Comment by t3chguy** [comment] 2021-02-10 17:51
Duplicate of https://github.com/vector-im/element-web/issues/15704

**Closed by t3chguy** 2021-02-10 17:51 UTC
