### ISSUE TITLE
More inline preview filetypes

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17072] opened 2021-04-26 17:36 UTC
Element has support for displaying images and playing audio and video inline when they're uploaded as a file. This could be extended for more file types, several text and document types come to mind: txt, md, tex (render with upcoming latex support?), any programming language extension, pdf, archive files (list contents), ....

#### Describe the solution you'd like.
For code, use syntax highlighting.

example: text files on discord
![image](https://user-images.githubusercontent.com/2803622/116125645-0b678080-a6c6-11eb-88e1-015b7dabf0f3.png)

Long ones can be expanded inline or viewed fullscreen. Also the programming language can be changed manually if needed. This could integrate nicely with triple backtick code blocks, latex and gitter support.

#### Describe alternatives you've considered.
Other competitors are probably also worth taking a look at.

#### Additional context
I heard there are lots of (German) universities offering matrix/element to employees, researchers and students in their software suites...
If this is a dupe, please add some keywords like preview, file, inline to it so it may be found.

**Comment by t3chguy** [comment] 2021-04-27 07:25
Related https://github.com/vector-im/element-web/issues/1677
Without server support, things like archive files will be likely infeasible due to severe memory limitations in javascript

**Comment by ara4n** [comment] 2022-05-01 16:20
See also https://github.com/vector-im/element-web/issues/3466

**Comment by t3chguy** [comment] 2022-06-15 15:45
Duplicate of https://github.com/vector-im/element-web/issues/1856

**Closed by t3chguy** 2022-06-15 15:45 UTC
Labels: A-Timeline, T-Enhancement, O-Uncommon
