### ISSUE TITLE
Notifications are received even while you have the chat open (no option)

### ISSUE THREAD

**Issue by yunginnanet** [vector-im/element-web#15458] opened 2020-10-14 08:22 UTC
### Description

Chats give you notifications when you have the chat open...

### Steps to reproduce

chat with your friends online using Element
have the window open
when they message you, despite your window being open to said chat, you are given an audible notification
find out that there is no setting to fix it
cry yourself to sleep
ponder if its all even worth it

### What should have happened

when the chat window is open you shouldn't be notified that you are receiving messages in that chat

### Version information

- **Platform**: desktop
- **OS**: Linux
- **Version**: Element version: 1.7.9

**Comment by t3chguy** [comment] 2020-10-14 08:25
Duplicate of https://github.com/vector-im/element-web/issues/3434

**Closed by t3chguy** 2020-10-14 08:25 UTC
Labels: bug, ui/ux
